### ISSUE TITLE
Add support for ssz_generic tests

### ISSUE THREAD

**Issue by asanso** [prysmaticlabs/prysm#10001]
Currently Prysm lacks support for [`ssz_generic`](https://github.com/ethereum/consensus-spec-tests/tree/master/tests/general/phase0/ssz_generic) spec tests.
It would be nice to have them

**Comment by prestonvanloon** [comment]
I don't think we support generic types here. That is partially supported in https://github.com/ferranbt/fastssz.

**Comment by rauljordan** [comment]
Agreed we cannot support these in Prysm as we simply use fastssz for codegen. Fastssz should be passing these spec tests instead
