### ISSUE TITLE
Beacon chain OOM after db/backup

### ISSUE THREAD

**Issue by lukaszsamson** [prysmaticlabs/prysm#10008]
# 🐞 Bug Report

### Description

 After requesting db backup on beacon chain the program slowed down, used up all of the memory and later crashed

### Has this worked before in a previous version?

 Yes, worked 2 months ago

## 🔥 Error
After hitting db/backup HTTP endpoint (on mainnet) the system slowed down due to high memory usage
logs were full of errors (only some show here)
<pre><code>
Dec 10 12:04:21 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 12:04:21" level=error msg="Could not handle p2p pubsub" error="could not process block: could not execute state transition: could not process block: could not retrieve attestation signature set: could not interface with committee cache: context deadline exceeded" prefix=sync topic="/eth2/afcaaba0/beacon_block/ssz_snappy"
Dec 10 12:32:45 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 12:32:45" level=warning msg="Batch is not processed" error="no good blocks in batch" prefix=initial-sync
Dec 10 12:40:40 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 12:40:40" level=warning msg="Range is not processed" error="Range had no valid blocks to process" prefix=initial-sync
Dec 10 13:34:37 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 13:34:37" level=warning msg="Could not update head" error="signed beacon block can't be nil" prefix=blockchain
Dec 10 13:34:50 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 13:34:50" level=warning msg="Could not update head" error="head at slot 2693184 with weight 425858 is not eligible, finalizedEpoch 84160 != 84160, justifiedEpoch 84161 != 84162" prefix=blockchain
Dec 10 14:25:07 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 14:25:04" level=warning msg="Coul
d not process attestation for fork choice" aggregationCount=1 beaconBlockRoot=0xc746b3f06bdf committeeIndex=4 error="could not process attestation: target epoch 84169 does not match current epoch 84172 or prev epoch 84171" prefix=blockchain slot=2693422 targetRoot=0xc746b3f06bdf
Dec 10 14:09:56 eth2-prod-1b prysm.sh[5780]: time="2021-12-10 14:09:56" level=warning msg="Attestation is too old to broadcast, discarding it. Current Slot: 2693447 , Attestation Slot: 2693202" prefix=p2p
</code></pre>
and eventually beacon chain was killed by linux OOM killer
<pre><code>
Dec 10 14:28:56 eth2-prod-1b kernel: Out of memory: Kill process 5780 (beacon-chain-v2) score 934 or sacrifice child
Dec 10 14:28:56 eth2-prod-1b kernel: Killed process 5780 (beacon-chain-v2) total-vm:104747652kB, anon-rss:7140072kB, file-rss:0kB, shmem-rss:0kB
Dec 10 14:28:56 eth2-prod-1b kernel: oom_reaper: reaped process 5780 (beacon-chain-v2), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
</code></pre>
The machine has 8GB RAM and 2GB swap and usually beacon chain uses ~3GB. Here it allocated ~100GB

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
AWS linux 2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
2.0.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
Hey @lukaszsamson , 

With the beacon database being about 40gb now, doing in-memory backups isn't feasible anymore. To back up the database you need to copy all the data in-memory which is the reason for the large amount of memory allocated. Also due to the time it takes to backup the db, backups are non-atomic so there is the possibility of getting the db in an inconsistent state. I would recommend manually backing up the db (shutdown the node and the manually copy the file via the filesystem).

**Comment by lukaszsamson** [comment]
The docs still recomend doing it via db/backup API call though. If that’s no longer supported then deprecate it and update docs.

**Comment by nisdas** [comment]
@lukaszsamson 

I added a warning on the risks of performing a backup for the beacon node at its current size:
https://github.com/prysmaticlabs/documentation/pull/392

**Comment by terencechain** [comment]
Closing after updating the doc
