### ISSUE TITLE
Sync Loop When Using Nethermind on Kintsugi

### ISSUE THREAD

**Issue by SeaMonkey82** [prysmaticlabs/prysm#10037]
# 🐞 Bug Report

### Description

Prysm beacon-chain goes into a loop at block batch starting from 0x1b0d81e1... 704/52782 when syncing from nethermind.

## 🔥 Error

<pre><code>
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 58 starting from  0x1b0d81e1... 704/52798 - estimated time remaining 33m15s blocksPerSecond=26.1 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0xb2609ef77a56281c77b2c034e71b08b0f6f3d3772aa0416fc2071f7607f5e9de
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 59 starting from  0x78aabd19... 768/52798 - estimated time remaining 29m51s blocksPerSecond=29.1 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0x429320fa1db14720e032b782d597e07806a83d82e80100b2c793c813d16f8829
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 58 starting from  0xe827fbf4... 832/52798 - estimated time remaining 27m6s blocksPerSecond=31.9 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0x33b88a54f22d649dd55ecdf7b873b40405abb6652300a5124a14c095632de78a
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 56 starting from  0xbc31f878... 896/52798 - estimated time remaining 24m53s blocksPerSecond=34.8 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0x52ca1a668d701f22987d3077f6c7e5e6fc18cf2c282b6334980150730e962ead
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 64 starting from  0xe1650627... 960/52798 - estimated time remaining 22m45s blocksPerSecond=38.0 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0xbb36fd645e75b2d1d045767c20b0963dc0794d33a93b9b4bc8b3f106dc2b914a
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 57 starting from  0xbcca82bf... 1024/52798 - estimated time remaining 21m8s blocksPerSecond=40.8 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0x947f441c045ae8d188ab5b83a1bc3b908b933422207b0d455669f9cabb512ff5
[2021-12-23 16:04:42]  INFO initial-sync: Processing block batch of size 59 starting from  0x3ce444a0... 1088/52798 - estimated time remaining 19m41s blocksPerSecond=43.8 peers=38
[2021-12-23 16:04:42]  WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0x5f318ff4885ba8af9db9520a664e09eaca830e69d69907c61fc88064635b4a06
[2021-12-23 16:04:49]  INFO initial-sync: Processing block batch of size 53 starting from  0xb4d312ea... 640/52799 - estimated time remaining 18m44s blocksPerSecond=46.4 peers=39
[2021-12-23 16:04:49]  WARN initial-sync: Batch is not processed error=incorrect random
github.com/prysmaticlabs/prysm/beacon-chain/core/execution.validatePayload
        beacon-chain/core/execution/process.go:99
github.com/prysmaticlabs/prysm/beacon-chain/core/execution.ProcessPayload
        beacon-chain/core/execution/process.go:52
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ProcessBlockForStateRoot
        beacon-chain/core/transition/transition_no_verify_sig.go:330
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ProcessBlockNoVerifyAnySig
        beacon-chain/core/transition/transition_no_verify_sig.go:198
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransitionNoVerifyAnySig
        beacon-chain/core/transition/transition_no_verify_sig.go:77
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransition
        beacon-chain/core/transition/transition.go:63
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock
        beacon-chain/blockchain/process_block.go:111
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock
        beacon-chain/blockchain/receive_block.go:39
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks.func1
        beacon-chain/sync/initial-sync/round_robin.go:289
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
        beacon-chain/sync/initial-sync/round_robin.go:296
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
        beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch
        beacon-chain/sync/initial-sync/round_robin.go:86
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
        beacon-chain/sync/initial-sync/round_robin.go:49
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
        beacon-chain/sync/initial-sync/service.go:105
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1371
could not process execution payload
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ProcessBlockForStateRoot
        beacon-chain/core/transition/transition_no_verify_sig.go:332
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ProcessBlockNoVerifyAnySig
        beacon-chain/core/transition/transition_no_verify_sig.go:198
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransitionNoVerifyAnySig
        beacon-chain/core/transition/transition_no_verify_sig.go:77
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransition
        beacon-chain/core/transition/transition.go:63
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock
        beacon-chain/blockchain/process_block.go:111
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock
        beacon-chain/blockchain/receive_block.go:39
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks.func1
        beacon-chain/sync/initial-sync/round_robin.go:289
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
        beacon-chain/sync/initial-sync/round_robin.go:296
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
        beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch
        beacon-chain/sync/initial-sync/round_robin.go:86
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
        beacon-chain/sync/initial-sync/round_robin.go:49
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
        beacon-chain/sync/initial-sync/service.go:105
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1371
could not process block
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransitionNoVerifyAnySig
        beacon-chain/core/transition/transition_no_verify_sig.go:79
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransition
        beacon-chain/core/transition/transition.go:63
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock
        beacon-chain/blockchain/process_block.go:111
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock
        beacon-chain/blockchain/receive_block.go:39
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks.func1
        beacon-chain/sync/initial-sync/round_robin.go:289
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
        beacon-chain/sync/initial-sync/round_robin.go:296
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
        beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch
        beacon-chain/sync/initial-sync/round_robin.go:86
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
        beacon-chain/sync/initial-sync/round_robin.go:49
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
        beacon-chain/sync/initial-sync/service.go:105
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1371
could not execute state transition
github.com/prysmaticlabs/prysm/beacon-chain/core/transition.ExecuteStateTransition
        beacon-chain/core/transition/transition.go:65
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onBlock
        beacon-chain/blockchain/process_block.go:111
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock
        beacon-chain/blockchain/receive_block.go:39
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks.func1
        beacon-chain/sync/initial-sync/round_robin.go:289
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
        beacon-chain/sync/initial-sync/round_robin.go:296
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
        beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch
        beacon-chain/sync/initial-sync/round_robin.go:86
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
        beacon-chain/sync/initial-sync/round_robin.go:49
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
        beacon-chain/sync/initial-sync/service.go:105
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1371
could not process block
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlock
        beacon-chain/blockchain/receive_block.go:40
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks.func1
        beacon-chain/sync/initial-sync/round_robin.go:289
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
        beacon-chain/sync/initial-sync/round_robin.go:296
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
        beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch
        beacon-chain/sync/initial-sync/round_robin.go:86
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync
        beacon-chain/sync/initial-sync/round_robin.go:49
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start
        beacon-chain/sync/initial-sync/service.go:105
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1371
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux Mint 20.2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
51ef502b04b286fe920aeaf06aa49c53ffabd754
  </code>
</pre>

**Comment by handelaar2** [comment]
Seeing exactly the same sync loop (block 704->640) with Prysm (docker `kintsugi-9475bc`) and Nethermind (docker `kintsugi_0.5` ).

<img width="1211" alt="2021-12-24_12-07-57" src="https://user-images.githubusercontent.com/28559038/147347968-f642af6a-171f-44e2-95c1-a413a42584f0.png">

cc: @MarekM25

**Comment by mcdee** [comment]
Seeing the same thing with a sepolia nethermind/prysm combo:

```
{"blocksPerSecond":"158.6","level":"info","msg":"Processing block batch of size 58 starting from  0x27351b29... 228800/230259 - estimated time remaining 9s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"could not process block in batch: could not set node to invalid: invalid nil or unknown node","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"161.4","level":"info","msg":"Processing block batch of size 57 starting from  0x903c5ab9... 228864/230259 - estimated time remaining 8s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0x50242b62ae84b3c3d81c358018e921b6bed9162df93aa54e7c0fd83e5846d7ae (in processBatchedBlocks, slot=228864)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"164.2","level":"info","msg":"Processing block batch of size 55 starting from  0x4bc8ac24... 228928/230259 - estimated time remaining 8s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0xcaba60a99b5db81f0817f948bd46495534f552d328371a3a28c6866ab9011143 (in processBatchedBlocks, slot=228928)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"167.3","level":"info","msg":"Processing block batch of size 62 starting from  0x5bfbcfdd... 228992/230259 - estimated time remaining 7s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0x16ddf9693b346b8af5b0df15567951017b77ca48aaf481549b4dd3fd437096bb (in processBatchedBlocks, slot=228992)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"170.1","level":"info","msg":"Processing block batch of size 56 starting from  0xbd413723... 229056/230259 - estimated time remaining 7s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0xc9bec9d52ee5041f583aae88f6d50ade33db228d7a22c0a9b5fc108947503440 (in processBatchedBlocks, slot=229056)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"173.1","level":"info","msg":"Processing block batch of size 59 starting from  0x00828e09... 229184/230259 - estimated time remaining 6s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0xf1d91d2919131ad4f1b2a41642e2b7c5064f5abf0bda3d048006ee61c0269938 (in processBatchedBlocks, slot=229184)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"176.0","level":"info","msg":"Processing block batch of size 59 starting from  0x4bddfc5a... 229248/230259 - estimated time remaining 5s","peers":9,"prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"error":"beacon node doesn't have a parent in db with root: 0x76de5677a16a763d1e4b075dac90153253a80a2664900b9e4ebd848db52d35f9 (in processBatchedBlocks, slot=229248)","level":"warning","msg":"Batch is not processed","prefix":"initial-sync","time":"2022-07-22T13:31:50Z"}
{"blocksPerSecond":"153.1","level":"info","msg":"Processing block batch of size 58 starting from  0x27351b29... 228800/230259 - estimated time remaining 9s","peers":8,"prefix":"initial-sync","time":"2022-07-22T13:31:52Z"}
```

Can supply additional debugging information if required.

**Comment by james-prysm** [comment]
followed up with @SeaMonkey82 , we can close for now and reopen as needed.
