### ISSUE TITLE
Replace codename `Merge` with `Bellatrix`

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10036]
Throughout the Prysm code base, we used `Merge` as the code name for the next hard fork. Finally, as of earlier this week, the community has decided `Bellatrix` to be the next consensus layer hard fork code name. We can now replace all the instances of `Merge` to `Bellatrix` ⭐

**Comment by leolara** [comment]
I could do it 🖐️ please

**Comment by alikonuk1** [comment]
i can do it too

**Comment by leolara** [comment]
@alikonuk1  I am already working on it, I tell you if I need help, or perhaps you could help during the review to check it

**Comment by leolara** [comment]
re: https://github.com/ethereum/consensus-specs/pull/2774

**Comment by rkapka** [comment]
Reopening because the merged PR is just the first step

**Comment by leolara** [comment]
@rkapka Thanks

**Comment by leolara** [comment]
I am working on this, preparing a PR that is going to focus on the proto package, then I will do other package. It is almost done but I get a build error that I have not been able to fix yet.

**Comment by leolara** [comment]
If you want we can have a call about is also

**Comment by terencechain** [comment]
> I am working on this, preparing a PR that is going to focus on the proto package, then I will do other package. It is almost done but I get a build error that I have not been able to fix yet.

No worries, can you open a PR with what you have? I can help

**Comment by leolara** [comment]
Ok, here is almost midnight, tomorrow morning I create PR

**Comment by leolara** [comment]
I think this is done and can be closed
