### ISSUE TITLE
REST API - Can't Look Ahead at Upcoming Block Proposals

### ISSUE THREAD

**Issue by jclapis** [prysmaticlabs/prysm#10035]
Hello!

We're adding a new feature to the Rocket Pool node operator dashboard which notifies users when they have an upcoming block proposal or sync committee, so they know not to take their systems down for maintenance. We're using the standard Beacon REST API for this. For example, assuming the current Epoch is `61766`:

```
curl -X GET "http://localhost:5052/eth/v1/validator/duties/proposer/61767" -H "accept: application/json"
```

This returns the following:

```
{"message":"Request epoch 61767 can not be greater than current epoch 61766","code":400}
```

This route works up to 2 epochs beyond `head` for Nimbus and up to 1 epoch ahead for Teku. Lighthouse shows the same behavior as the above. The [official spec](https://ethereum.github.io/beacon-APIs/#/Validator/getProposerDuties) for this route isn't clear on whether or not it's legal to call it on future epochs. Assuming it is, we would like this route to be able to look ahead so users know if they are safe to restart their systems without potentially missing an upcoming proposal.

Thank you!

**Comment by jclapis** [comment]
After a lengthy conversation with Lighthouse (https://discord.com/channels/605577013327167508/618981555985186827/923422432415608872), we decided that lookahead is too volatile for this route to be of practical use. I will close this issue and bring it up with Nimbus and Teku to see if they'd be willing to adopt your behavior here.

**Comment by jclapis** [comment]
We had a follow-on discussion in that thread after @nisdas brought to light some information from @potuz. It seems like there is general agreement that volatility is actually quite low, and for our use case (informing users of pending proposals so they can delay maintenance activities) this is a useful thing to have. I'd like to reopen it for consideration.

**Comment by james-prysm** [comment]
linked the correct pr and closing this issue
