### ISSUE TITLE
Add better coverage to state pkg's getter and settter

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10047]
State pkg's test coverage is weak. Some of the getters and setters don't have tests. Opening this issue to track state pkg's test coverage improvement. This is an excellent first issue to add tests to the getters and the setters

<img width="996" alt="Screen Shot 2021-12-31 at 7 27 23 AM" src="https://user-images.githubusercontent.com/21316537/147830491-b71d9bee-cc4e-4878-bc8d-992066601a1d.png">

**Comment by leolara** [comment]
If nobody took this when i am doing with the renaming I would like to take this. But better get the other one done before jumping into this :-)

**Comment by nisdas** [comment]
Hey @leolara , 

Thanks for your interest in this ! Some background for this issue, currently we have 3 state packages:
https://github.com/prysmaticlabs/prysm/tree/develop/beacon-chain/state/v1
https://github.com/prysmaticlabs/prysm/tree/develop/beacon-chain/state/v2
https://github.com/prysmaticlabs/prysm/tree/develop/beacon-chain/state/v3

All the state structs in these packages adhere to the same interface and have the same getters and setters. Depending on the specific state, some getters may return an error(deprecated field/method). For any tests that are targetted at getters and setters ideally we will only need to implement the test cases once and be able to apply this across the different state types without having to duplicate this for each specific state.

**Comment by leolara** [comment]
Thanks @nisdas

**Comment by leolara** [comment]
I will work on this while my other PR is being reviewed. Please assign to me @terencechain @nisdas

**Comment by leolara** [comment]
One thing I am seeing, this test for example makes coverage very misleading:

https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/state/v1/getters_test.go#L32-L78

Most of the coverage might be this, that only checks that it does not panic.

**Comment by leolara** [comment]
@nisdas I guess the way to do not repeat the tests, would be to have some test functions that receive a state factory interface as parameter. Then all the tests for getters and setters available in phase0 state could be written once and run on all three states versions for example.

Where would we put such functions?

**Comment by nisdas** [comment]
@leolara You can put it a new package specifically for testing them. Ex: `statetesting`

**Comment by leolara** [comment]
Blocked by #10069 as said in https://github.com/prysmaticlabs/prysm/pull/10074#issuecomment-1011063294

**Comment by rkapka** [comment]
Even though #10069 was merged, let's wait for #9820

**Comment by leolara** [comment]
Next, I am going to send a PR with a DRY implementation of a test, and then when that is approved, I will add more coverage and with DRY.

**Comment by leolara** [comment]
Coverage of v2 currently with TestNilState_NoPanic:

<img width="510" alt="Screenshot 2022-03-10 at 11 29 24" src="https://user-images.githubusercontent.com/1210482/157643851-b9217f6e-e6ac-46ee-83df-ca1baf980a42.png">

Coverage without TestNilState_NoPanic:

<img width="503" alt="Screenshot 2022-03-10 at 11 31 03" src="https://user-images.githubusercontent.com/1210482/157643994-557d926f-7b0e-4b85-9768-156d01124e1c.png">

There is no so much difference, which is good :-)

**Comment by james-prysm** [comment]
Will start to assist with this
