### ISSUE TITLE
Invalid validator balances for finalized epoch

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#10043]
Hi,

StakeWise runs oracles that periodically sync balances from the beacon chain. Previously we were running them only with Prysm beacon nodes, but now we are planning to use also Lighthouse and Teku.
For some reason, Teku and Lighthouse return the same value, but Prysm returns a different one for the same finalized epoch.

The latest measurement:

finalized epoch: `87819`
activated validators: `911`
total rewards (Lighthouse, Teku): `1285.825380501 ETH`
total rewards (Prysm): `1285.825369063 ETH`

All the clients are running the latest versions and beacon nodes are queried using the ETH2 Standard API:

For checking whether the epoch is finalized, we use `/eth/v1/beacon/states/{state_id}/finality_checkpoints`.
For fetching validator balances we use: `/eth/v1/beacon/states/{state_id}/validators?id={'&id='.join(public_keys)`

**Comment by rkapka** [comment]
Hi @tsudmi , thanks for the report. Can you paste the exact request that you make when fetching balances? `state_id` is supposed to be a slot number.

**Comment by rkapka** [comment]
Fixed by https://github.com/prysmaticlabs/prysm/pull/10255
