### ISSUE TITLE
Soft remove pyrmont testnet

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10051]
Pyrmont test-net has had no official support since the summer of 2021. With infra providers like beaconcha.in and infura dropping Pyrmont support and client like [Teku dropping Pyrmont support](https://github.com/ConsenSys/teku/pull/4405/files), I think it makes sense to think to  Prysm can / should drop Pyrmont support. I think aligning a point release is sensible and without removing the flag itself, rather than exiting gracefully when the testnet flag is applied

**Comment by leolara** [comment]
@terencechain please assign to me, it seems easy. Just exiting when the flag is set with a warning?

**Comment by terencechain** [comment]
> @terencechain please assign to me, it seems easy. Just exiting when the flag is set with a warning?

That sounds reasonable to me
