### ISSUE TITLE
Missed block proposal despite 100% effectiveness: Failed to request block from beacon node

### ISSUE THREAD

**Issue by wavey0x** [prysmaticlabs/prysm#10059]
# 🐞 Bug Report

### Description

 
Despite my validators hitting at or near 100% effectiveness for some time, I missed a proposal on 1/4/2022. The same validator had a successful proposal earlier the same day, and has been submitting attestations with no issue. I've been unable to determine the root cause and would like some help investigating further.

https://beaconcha.in/validator/82a25ffb16ca060cd7ecd8f2c68c93349e10656283f997fc9d4baa4a0c119d7b3e6916336daf03e193055daa4c32b8c0#blocks

### Has this worked before in a previous version?

 This behavior has not been noticed in previous versions.

## 🔬 Minimal Reproduction

 Unclear. This has only happened once, during a block proposal.

## 🔥 Error

<pre><code>

Jan 04 12:26:35 staker validator[756]: time="2022-01-04 12:26:35" level=info msg="Previous epoch aggregated voting summary" attestationInclusionPct="100%" averageInactivityScore=0 correctlyVotedHeadPct="75%" correctlyVotedSourcePct="100%" correctlyVotedTargetPct="10>
Jan 04 12:26:35 staker validator[756]: time="2022-01-04 12:26:35" level=info msg="Vote summary since launch" attestationsInclusionPct="100%" correctlyVotedHeadPct="97%" correctlyVotedSourcePct="100%" correctlyVotedTargetPct="100%" numberOfEpochs=3124 pctChangeCombin>
Jan 04 12:26:47 staker validator[756]: time="2022-01-04 12:26:47" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x943fcbb4a086] slot=2874446 slotInEpoch=14 totalAttestersInEpoch=4
Jan 04 12:26:47 staker validator[756]: time="2022-01-04 12:26:47" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x82a25ffb16ca] slot=2874454 slotInEpoch=22 totalAttestersInEpoch=4
Jan 04 12:26:47 staker validator[756]: time="2022-01-04 12:26:47" level=info msg="Proposal schedule" prefix=validator pubKey=0x82a25ffb16ca slot=2874454
Jan 04 12:26:47 staker validator[756]: time="2022-01-04 12:26:47" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x8be02ac52634] slot=2874460 slotInEpoch=28 totalAttestersInEpoch=4
Jan 04 12:26:47 staker validator[756]: time="2022-01-04 12:26:47" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x987417a0993c] slot=2874463 slotInEpoch=31 totalAttestersInEpoch=4
Jan 04 12:29:39 staker validator[756]: time="2022-01-04 12:29:39" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[34389] BeaconBlockRoot=0x660a9230d827 CommitteeIndex=13 Slot=2874446 SourceEpoch=89825 SourceRoot=0xc85fc36eb5ad Targe>
Jan 04 12:31:11 staker validator[756]: time="2022-01-04 12:31:11" level=error msg="Failed to request block from beacon node" blockSlot=2874454 error="rpc error: code = Internal desc = Could not fetch Altair beacon block: could not compute state root: could not calcu>
Jan 04 12:31:19 staker validator[756]: time="2022-01-04 12:31:19" level=info msg="Submitted new attestations" AggregatorIndices=[34375] AttesterIndices=[34375] BeaconBlockRoot=0x5fad1def191c CommitteeIndex=1 Slot=2874454 SourceEpoch=89825 SourceRoot=0xc85fc36eb5ad T>
Jan 04 12:32:27 staker validator[756]: time="2022-01-04 12:32:27" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[3000] BeaconBlockRoot=0xa9668c543e32 CommitteeIndex=49 Slot=2874460 SourceEpoch=89825 SourceRoot=0xc85fc36eb5ad Target>
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[2999] BeaconBlockRoot=0x13c2eb9bc5f3 CommitteeIndex=15 Slot=2874463 SourceEpoch=89825 SourceRoot=0xc85fc36eb5ad Target>
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=89825 inactivityScore=0 newBalance=34.785534592 oldBalance=34.78551669 >
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=89825 inactivityScore=0 newBalance=34.750128118 oldBalance=34.750110216>
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=89825 inactivityScore=0 newBalance=34.575003253 oldBalance=34.574985351>
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=89825 inactivityScore=0 newBalance=34.659596586 oldBalance=34.659578684>
Jan 04 12:33:03 staker validator[756]: time="2022-01-04 12:33:03" level=info msg="Previous epoch aggregated voting summary" attestationInclusionPct="100%" averageInactivityScore=0 correctlyVotedHeadPct="100%" correctlyVotedSourcePct="100%" correctlyVotedTargetPct="1>

</code></pre>

## 🌍  Your Environment

**Operating System:**
<pre>
  <code>
Ubuntu
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
Geth version: 1.10.2-stable-97d11b01

**Comment by prestonvanloon** [comment]
@wavey0x do you have the full error message? In your snippet, this is cut off:
```
Jan 04 12:31:11 staker validator[756]: time="2022-01-04 12:31:11" level=error msg="Failed to request block from beacon node" blockSlot=2874454 error="rpc error: code = Internal desc = Could not fetch Altair beacon block: could not compute state root: could not calcu>
```

**Comment by wavey0x** [comment]
Sorry about that. Here it is:

`Jan 04 12:31:11 staker validator[756]: time="2022-01-04 12:31:11" level=error msg="Failed to request block from beacon node" blockSlot=2874454 error="rpc error: code = Internal desc = Could not fetch Altair beacon block: could not compute state root: could not calculate state root at slot 2874453: could not process block: could not process block operation: could not verify operation lengths: incorrect outstanding deposits in block body, wanted: 16, got: 0" prefix=validator pubKey=0x82a25ffb16ca`

**Comment by rkapka** [comment]
This is the same error as in https://github.com/prysmaticlabs/prysm/issues/9787

**Comment by nisdas** [comment]
Not the same error @rkapka , this was diagnosed offline. It turns out @wavey0x 's geth node was doing nothing at all(no new blocks were being processed), so no new deposits could be inluded into the block by the validator.

**Comment by prestonvanloon** [comment]
@nisdas is there any corrective action to take here or can we close this issue?

@wavey0x were there any signs that your geth node was not operating correctly? 
Was there anything we could add to Prysm to help notify of this issue?

**Comment by nisdas** [comment]
> Was there anything we could add to Prysm to help notify of this issue?

They had 0 peers, so their geth node wasn't getting anything. For prysm to be able to do something it would need to get the peer count of the geth node. To access this particular rpc method, geth will need to enable admin access to prysm which is undesirable. And I think this particular method is only specific to geth in any case.
