### ISSUE TITLE
Support multiple bootnodes from CLI

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10067]
It will be great to support multiple boot nodes from the CLI command line with comma separation. (e.g `----bootstrap-node $BOOTNODE1,$BOOTNODE2,$BOOTNODE3... `). There's no other way to support >1 boot node other than hard coding in the config and invoking it using a flag

**Comment by prestonvanloon** [comment]
> There's no other way to support >1 boot node other than hard coding in the config and invoking it using a flag

You can specify the flag multiple times `--bootstrap-node=$BOOTNODE1 --bootstrap-node=$BOOTNODE2 --bootstrap-node=$BOOTNODE3`

**Comment by terencechain** [comment]
> > There's no other way to support >1 boot node other than hard coding in the config and invoking it using a flag
> 
> 
> 
> You can specify the flag multiple times `--bootstrap-node=$BOOTNODE1 --bootstrap-node=$BOOTNODE2 --bootstrap-node=$BOOTNODE3`

Gotcha. We just need to update the instructions then

**Comment by prestonvanloon** [comment]
Any of the `SliceFlag` type flags are the same. I.e. `--peer`, `--bootstrap-node`, `--p2p-denylist`, etc.

**Comment by terencechain** [comment]
This issue can be closed here and revisit in the docs repo
