### ISSUE TITLE
Optimize Validator Registration Contract in Solidity

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1008]
Here are a few ideas to optimize our [validator registration contract](https://github.com/prysmaticlabs/prysm/blob/master/contracts/validator-registration-contract/validator_registration.sol). I'd love for someone with great solidity experience to pick this up.

- Optimize to be gas efficient especially `receiptTree` gets updated
- Is in-line assembly the best way to handle byte operations such as addition and conversion to int? Can we do better?
- Write some solidity unit tests for byte operations to ensure it works

**Comment by cyberbono3** [comment]
Hey guys,
The 3 basic tests for toBytes(), mergeBytes() and getReceiptRoot() pass using Truffle and Ganache-cli
https://github.com/cyberbono3/validator-registration-contract/blob/master/test/test.js 
Moreover, I added SafeMath library to prevent uint underflow or overflow.

@terenc3t What is the next step?

I have to resolve this issue in order to make comprehensive testing of getReceiptRoot() .

In order to make comprehensive test of getReceiptTree I intended to compute 
          receiptTree[1] relying on line 56 in validator_registation.sol
          receiptTree[index] = abi.encodePacked(keccak256(mergeBytes(receiptTree[index * 2], receiptTree[index * 2 + 1])));
          It follows, calculatation of receiptTree[1] requires computation of receiptTree[2] and receiptTree[3]
          receiptTree[1] = abi.encodePacked(keccak256(mergeBytes(receiptTree[2], receiptTree[3])));
          Conclusevely, line 55 in validator_registation.sol index = index / 2 results in computation of even receiptTree only
          Thus, i am unable to compute receiptsTree3 , receiptsTree5 or any other odd receiptTrees

**Comment by cyberbono3** [comment]
@KimiWu123   I would appreciate your help or guidance in resolving the issue above

**Comment by KimiWu123** [comment]
Hi @cyberbono

I'd like to do some minor 
1. Using 0.5.1compiler
2. Fix a bug
3. Align the Vyper sample code in spec2.0

And then we base on my PR(I'll commit it later) to continue. Is that okay?

One more question, is 'mergeBytes' really save a lot of gas? I use abi.encodePacked on Remix, and it seems not big difference. I'll double check the result before committing my PR.

**Comment by KimiWu123** [comment]
Hi @cyberbono3 , 

I think we don't need to calculate the odd parts, let's say`MERKLE_TREE_DEPTH=4`, the tree would be like this after 
first deposit
　　　　1
　　　2
　　4
　8
16
second deposit,
　　　　1
　　　2
　　4
　8
16  17
third deposit,
　　　　      1
　　　    2
　　   4
　8　　    **9**
16  17  18

the odd parts would grow after people deposit. Correct me if I'm wrong.

**Comment by cyberbono3** [comment]
Hey,

Siorry for delayed response!
Indeed! Output of abi.encodePacked and mergeBytes match

Regarding calculationg of odd parts, Keeping in mind that Merkle_Tree_Depth = 4 first invocation of deposit function will produce the following indexes : 16, 8 , 4 , 2 ,1  Then, totalDepositCount will be incremented and it will produce 17 and fixed point numbers  8.5  4.25 2.125 1.0625    

Currently, float numbers are not supported in Solidity  https://solidity.readthedocs.io/en/develop/types.html#fixed-point-numbers

Index represents uint type, which might be a problem.  I suggest to change index type from uint to fixed point number  @terenc3t  what do u think?

**Comment by cyberbono3** [comment]
@KimiWu123 Let me commit my tests in separate PR.

**Comment by terenc3t** [comment]
Not as strong in solidity as you guys - what's the benefit of using fixed point number over uint here?

**Comment by KimiWu123** [comment]
@cyberbono3 , oh, that's true. I didn't think about it. how about we just `mod` the indexes to decide add one or not? I know fixed point number, but I haven't used it. Is it could be indexes of an array? Besides, the document says `Fixed point numbers are not fully supported by Solidity yet`.

**Comment by terenc3t** [comment]
closed via #1110

**Comment by KimiWu123** [comment]
Hi @terenc3t , 
sorry, I'm not sure it's a right place to discuss.

@cyberbono3 ,
I misunderstood, in your case, there is no problem, 

> Merkle_Tree_Depth = 4 first invocation of deposit function will produce the following indexes : 16, 8 , 4 , 2 ,1 Then, totalDepositCount will be incremented and it will produce 17 


here, we use uint as indexes so 17/2 would be 8 which is parent of 16 and 17. I think that's why they just use uint instead of other types.
