### ISSUE TITLE
GetValidatorPerformance reports all MissingValidators in Kintsugi

### ISSUE THREAD

**Issue by alrevuelta** [prysmaticlabs/prysm#10087]
# 🐞 Bug Report

### Description

When calling `GetValidatorPerformance` on a node running `kintsugi` testnet on commit b45826e7317ffd0d5bf5a875d63d0e7d4e35b7f9 with active validators (as reported by [beaconchain-kintsugi](https://beaconchain.kintsugi.themerge.dev/)), no information is reported, and all validators are labeled as `MissingValidators`.

### Has this worked before in a previous version?

It worked in multiple other version such as `v1x` and `v2x`

## 🔬 Minimal Reproduction

* Run a node with geth and prysm b45826e7317ffd0d5bf5a875d63d0e7d4e35b7f9 on kintsugi network at `localhost:4000`
* Run the following code

```go
package main

import (
	"context"
	"encoding/hex"

	"github.com/ethereum/go-ethereum/common/hexutil"
	ethpb "github.com/prysmaticlabs/prysm/v2/proto/prysm/v1alpha1"
	log "github.com/sirupsen/logrus"
	"google.golang.org/grpc"
)

func main() {
	dialContext, err := grpc.DialContext(context.Background(), "localhost:4000", grpc.WithInsecure())
	if err != nil {
		log.Fatal("error: ", err)
	}

	beaconClient := ethpb.NewBeaconChainClient(dialContext)

	var keysStr = []string{
		"0x874b3a82cf639d0e3a2102f11e905f46a5527a98b245415a43bff4019b7ac04040523b93b3f296ff5fdd1ae09e3ecd7c",
		"0x98a1de5787286b6cf43a7a1692a67b06cc101576b59fec58497be2cf6e64efa22bf31f8e2a0867b247fc836e5bbf40a8",
		"0x8384044d52da1075dcc4f51bb843120b2ac9c80286b8a336f552ff34ea513db358ff3571642b508eade29cd3783e7dbf",
	}

	keys := make([][]byte, 0)

	for _, keyStr := range keysStr {
		key, _ := hexutil.Decode(keyStr)
		keys = append(keys, key)
	}

	req := &ethpb.ValidatorPerformanceRequest{
		PublicKeys: keys,
	}

	valsPerformance, err := beaconClient.GetValidatorPerformance(context.Background(), req)
	if err != nil {
		log.Fatal(err)
	}

	for _, missingVal := range valsPerformance.MissingValidators {
		log.Info(hex.EncodeToString(missingVal))
	}
}

```

## 🔥 Error

No error is displayed, but no information is reported for the validators. All of them are reported as `MissingValidators` but [beaconchain-kintsugi](https://beaconchain.kintsugi.themerge.dev/) reports that they indeed exist in the network.

## 🌍  Your Environment

**Operating System:**

macOS

**What version of Prysm are you running? (Which release)**
b45826e7317ffd0d5bf5a875d63d0e7d4e35b7f9

**Anything else relevant (validator index / public key)?**

Used validators, see [beaconchain-kintsugi](https://beaconchain.kintsugi.themerge.dev/):
* "0x874b3a82cf639d0e3a2102f11e905f46a5527a98b245415a43bff4019b7ac04040523b93b3f296ff5fdd1ae09e3ecd7c",
* "0x98a1de5787286b6cf43a7a1692a67b06cc101576b59fec58497be2cf6e64efa22bf31f8e2a0867b247fc836e5bbf40a8",
* "0x8384044d52da1075dcc4f51bb843120b2ac9c80286b8a336f552ff34ea513db358ff3571642b508eade29cd3783e7dbf",

**Comment by terencechain** [comment]
Should be fixed. Can you try latest release?
