### ISSUE TITLE
Prysm Proto APIs v3 Wishlist

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#10094]
# 🚀 Feature Request

### Description

This is a tracking issue for items we would like to see when we create a v3 for Prysm's gRPC APIs, given some recent discussions about this topic between our team.

- [ ] Use more idiomatic oneof and optionals for a cleaner schema
- [ ] Change the SignedBeaconBlockContainerV2 to return a oneof type for SignedBeaconBlocks instead of having the signature as a separate field in the protobuf
- [ ] Standard API: remove `v2` from all messages that are not request/responses (e.g. `BeaconStateV2`)

TODO: Add more items as needed

**Comment by rkapka** [comment]
Merging to linked issue
