### ISSUE TITLE
Track GenesisTime in the ForkChoice Store Type

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#10099]
# 💎 Issue

### Background

The fork choice store type does not store the genesis time of the beacon chain. In some recent changes to the fork choice algorithm, there is a function called `BoostProposerRoot` in #10083 

```go
func (f *ForkChoice) BoostProposerRoot(_ context.Context, blockSlot types.Slot, blockRoot [32]byte, genesisTime time.Time) error
```
which requires the genesis time on every call. Instead, the actual `type ForkChoice struct` should track this value.

### Description

This issue will require some refactoring, as we initialize the fork choice store in `node/node.go` before the rest of the services in Prysm. However, we only receive the genesis time after the `blockchain` service initializes. We might want to move the call to `forkchoice.New()` to within the blockchain service, and we must take to avoid any unintended consequences.

**Comment by potuz** [comment]
Fixed with #10427
