### ISSUE TITLE
Validator accounts backup missing `path` as defined in EIP-2335

### ISSUE THREAD

**Issue by philknows** [prysmaticlabs/prysm#10107]
# 🐞 Bug Report

### Description
To help with client diversity, the exported keystores from Prysm should follow the BLS12-381 private keys JSON schema for use with other Ethereum Consensus clients.

The `validator accounts backup` function is currently not exporting the `path` parameter as required in the [EIP-2335 spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md#json-schema).

Even if no path is known or the path is not relevant, the empty string, "" should be included.

### Has this worked before in a previous version?

N/A

## 🔬 Minimal Reproduction

1. Use the `validator accounts backup --wallet-dir=<YourWalletDir>` function to export your backup.zip
2. Unzip your backup.zip
3. View the missing parameter in the keystore.json

## 🌍  Your Environment

**Operating System:**

Ubuntu Server 20.04.3

**What version of Prysm are you running? (Which release)**

v2.0.5

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
The path is missing from this struct https://github.com/prysmaticlabs/prysm/blob/8d610319bcd8b2252357543f0d5001d34f0b1a15/validator/keymanager/types.go#L55-L61

Assuming it should be an empty string. I think that adding a path field would resolve the issue. 
A regression test is a requirement to consider this issue resolved.
