### ISSUE TITLE
Support "fat-manifest" multi-arch container images

### ISSUE THREAD

**Issue by anthr76** [prysmaticlabs/prysm#10119]
# 🚀 Feature Request

Images like `gcr.io/prysmaticlabs/prysm/validator:stable` should support arm64

### Description

These images should be able to be ran on amd64 *or* arm64

### Describe the solution you'd like

The build system should implment a fat-manifest

### Describe alternatives you've considered

Building, and maintaing my own image. This is required for multi-arch clusters without tolerating to amd64 which increases power usage.

**Comment by prestonvanloon** [comment]
Probably depends on https://github.com/bazelbuild/rules_docker/issues/1599 or doing something else entirely.

**Comment by prestonvanloon** [comment]
Seems like we can do a workaround like this: https://github.com/buchgr/bazel-remote/pull/453

**Comment by anthr76** [comment]
That looks like a suitable workaround. Are maintainers okay with something like that?

**Comment by prestonvanloon** [comment]
Fixed in #12428. We are planning to switch to these multi-arch images, starting in the next release.
