### ISSUE TITLE
Inconsistent Balance against Other ETH2 Nodes

### ISSUE THREAD

**Issue by nyunyunyunyu** [prysmaticlabs/prysm#10132]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...
Prysm/Teku/Lighthouse nodes return different values when querying the balance of the same validator at the same epoch. 

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....
I don't know. 

## 🔬 Minimal Reproduction

When querying validator status using the eth2 offical API(eth/v1/beacon/states/<state>/validators),  Prysm v2.0.4 nodes return results are different from the return results of Teku v22.1.0/Lighthouse v2.0.1. 

Query url: eth/v1/beacon/states/1267872/validators?id=127768

Return value:
Prysm: 
`{"data":[{"index":"127768","balance":"32158220821","status":"active_ongoing","validator":{"pubkey":"0x80ca933844c93aef171e5d20eb7ce8673913cddfcacf76dbe2da2c98c286e7111e1ab5505a16bb27e8c1f7c50dc394fd","withdrawal_credentials":"0x009d5dd4bc8d5ee9cddebf3295b6ded10b90f827bb925fb72ba47945b9dd79d3","effective_balance":"32000000000","slashed":false,"activation_eligibility_epoch":"34210","activation_epoch":"34253","exit_epoch":"18446744073709551615","withdrawable_epoch":"18446744073709551615"}}]}`

Lighthouse/teku: 
`{"data":[{"index":"127768","balance":"32158271384","status":"active_ongoing","validator":{"pubkey":"0x80ca933844c93aef171e5d20eb7ce8673913cddfcacf76dbe2da2c98c286e7111e1ab5505a16bb27e8c1f7c50dc394fd","withdrawal_credentials":"0x009d5dd4bc8d5ee9cddebf3295b6ded10b90f827bb925fb72ba47945b9dd79d3","effective_balance":"32000000000","slashed":false,"activation_eligibility_epoch":"34210","activation_epoch":"34253","exit_epoch":"18446744073709551615","withdrawable_epoch":"18446744073709551615"}}]}
`

You can see the balances are different: 32158220821 v.s. 32158271384
At epoch 39621(slot 1267872), most validators have the discrepancy.

Epochs have the issue: 39621, 56660, 61796, 68109, 69522, 75012, 76488.

And I noticed a pattern: For all the epochs before these error epochs,  their last slots are missing/orphaned.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rkapka** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/10043

**Comment by rkapka** [comment]
Fixed by https://github.com/prysmaticlabs/prysm/pull/10255
