### ISSUE TITLE
cannot unmarshal string into Go struct field SyncProgress.StartingBlock of type uint64 [kintsugi-prysm-besu]

### ISSUE THREAD

**Issue by SeaMonkey82** [prysmaticlabs/prysm#10134]
# 🐞 Bug Report

### Description

prysm-besu beacon on kintsugi periodically throws 

`ERROR powchain: Could not connect to powchain endpoint: could not dial eth1 nodes: json: cannot unmarshal string into Go struct field SyncProgress.StartingBlock of type uint64`

This doesn't appear to impact attestations or proposals.

### Has this worked before in a previous version?

I believe this is an existing bug.

## 🔬 Minimal Reproduction

Besu:
`~/Downloads/merge-testnets/kintsugi/besu/build/install/besu/bin/besu --data-path "/home/seamonkey/eth/kintsugi-prysm-besu" --genesis-file $HOME/Downloads/merge-testnets/kintsugi/besu_genesis.json --rpc-http-apis=ADMIN,ETH,NET,DEBUG,TXPOOL,EXECUTION --rpc-http-cors-origins="moz-extension://a0ffd254-28a5-4292-bf02-4195ced390d3,moz-extension://f6780ea6-1162-4fe5-b170-c37b605ae299" --network-id=1337702 --sync-mode=full --p2p-port 13455 --rpc-http-port 8549 --p2p-host "1.2.3.4" --rpc-http-enabled --Xmerge-support=true --p2p-enabled=true --bootnodes=enode://6f377dd1ef5a3272d7e02fac9064c4f95d74f7edfd866e59ded774ee5b4649ff61c3f24c95f5c3d07d692b447f0569716b8921b6861810b96a705c92e1d27ff9@161.35.67.219:30303 --miner-coinbase="0x0000000000000000000000000000000000000000" --miner-enabled`

Prysm beacon:
`bazelisk run //beacon-chain -- --genesis-state ~/Downloads/merge-testnets/kintsugi/genesis.ssz --datadir ~/eth/kintsugi-prysm-besu --http-web3provider=http://127.0.0.1:8549 --kintsugi-testnet --p2p-tcp-port 13456 --p2p-udp-port 13456 --p2p-host-ip "1.2.3.4"`

Prysm validator:
`bazelisk run //validator -- --wallet-password-file ~/eth/kintsugi-prysm-besu/smashword --wallet-dir ~/eth/kintsugi-prysm-besu/nonhdwallet --graffiti "prysm-besu seamonkey.tech" --kintsugi-testnet`

## 🔥 Error

<pre><code>
[2022-01-25 21:11:33] ERROR powchain: Could not connect to powchain endpoint: could not dial eth1 nodes: json: cannot unmarshal string into Go struct field SyncProgress.StartingBlock of type uint64
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux Mint 20.3
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v2.0.5/77f815a39f8328b4e25faf0e66ec1df4bfed50c2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

kintsugi-prysm-besu validators on beacon chain explorer
https://beaconchain.kintsugi.themerge.dev/dashboard?validators=72489,72490,72491,72492,72493,72494,72495,72496

**Comment by nisdas** [comment]
I have seen this pretty often too when running on kintsugi, @jmozah any ideas why we get this error ?

**Comment by rauljordan** [comment]
Their API is probably different and returns a string instead of a number in JSON. This is hard for us to fix without breaking other APIs such as geth, unfortunately

**Comment by terencechain** [comment]
I think this is no longer relevant. Please reopen if still persists
