### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Limpisey168** [prysmaticlabs/prysm#10135]
{"signType":"ethSignTx","blockchain":"BNB","action":"coldWalletSign","sign":{"from":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","gas":"0x5208","chainId":56,"to":"0x8c1659fdba7b9507594a4FD78be301Dd04CD11C1","value":"0x8ac7230489e80000","gasPrice":"0x12a05f200","nonce":"0x0"}}

**Comment by Limpisey168** [comment]
> {"signType":"ethSignTx","blockchain":"BNB","action":"coldWalletSign","sign":{"from":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","gas":"0x5208","chainId":56,"to":"0x8c1659fdba7b9507594a4FD78be301Dd04CD11C1","value":"0x8ac7230489e80000","gasPrice":"0x12a05f200","nonce":"0x0"}}

**Comment by nisdas** [comment]
This looks unrelated to prysm , I am closing the issue unless you have something that indicates otherwise.

**Comment by Limpisey168** [comment]
ok

**Comment by Limpisey168** [comment]
thank you for all supporter

**Comment by Soundpisey** [comment]
> {"signType":"ethSignTx","blockchain":"BNB","action":"coldWalletSign","sign":{"from":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","gas":"0x5208","chainId":56,"to":"0x8c1659fdba7b9507594a4FD78be301Dd04CD11C1","value":"0x8ac7230489e80000","gasPrice":"0x12a05f200","nonce":"0x0"}}
