### ISSUE TITLE
Validator Losing $$ first two days Prysm says something not communication - Please Help

### ISSUE THREAD

**Issue by Earnie-Beisbol** [prysmaticlabs/prysm#10148]
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
  },
  "status": 0,
  "statusText": "Unknown Error",
  "url": "/api/v2/validator/beacon/participation",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for /api/v2/validator/beacon/participation: 0 Unknown Error",
  "error": {
    "isTrusted": true
  }
}

# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Thanks for filing this issue. We need a bit more information here. Can you please provide the information requested in the issue template? What errors do you see? How can we reproduce the error? What version of Prysm? Which validator index?
