### ISSUE TITLE
Panic in new API for ETH1 connections

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#10165]
# 🐞 Bug Report

### Description

Trying to fetch the eth1 connections results in panic
curl http://localhost:3500/eth/v1alpha1/node/eth1/connections

new functionality in release v2.0.6:
Add endpoint to query eth1 connections #10073 #10103

### Has this worked before in a previous version?

N/a

## 🔬 Minimal Reproduction

curl http://localhost:3500/eth/v1alpha1/node/eth1/connections

## 🔥 Error
![2022-02-01_09-16-26](https://user-images.githubusercontent.com/28559038/151934043-d49baac5-c37d-4fd0-a4a2-aa4d8a0d46b6.png)

## 🌍  Your Environment

**Operating System:**

Linux with latest Prysm 2.0.6

**Anything else relevant (validator index / public key)?**

cc:  @michaelneuder

**Comment by prestonvanloon** [comment]
Looks like an err is nil.

https://github.com/prysmaticlabs/prysm/blob/9166f40a042ad4244d1fb6b0cb084a5b6245aff1/beacon-chain/rpc/prysm/v1alpha1/node/server.go#L230

**Comment by michaelneuder** [comment]
yup, I will look at this tonight EST, thanks!

**Comment by prestonvanloon** [comment]
Thanks @michaelneuder

**Comment by michaelneuder** [comment]
Opened https://github.com/prysmaticlabs/prysm/pull/10186

**Comment by rauljordan** [comment]
No longer an issue now that we only support a single eth1 connection
