### ISSUE TITLE
Space Efficient Representation of Deposit Trie

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#10179]
# 🚀 Feature Request

### Description

With the large growth of the validator registry and the constant deposits into the beacon-chain, the size of our in-memory
deposit trie has been growing to a non-trivial size. Maintaining this in memory will lead to a larger amount of our heap being 
allocated to represent our trie. 

### Describe the solution you'd like

Our deposit trie, has a few properties that allow us to perform a certain set of optimizations on. 
-> New deposits into the trie are always inserted into a new index ( last deposit index +1)
-> Old deposits are permanently written into the trie and cannot be overwritten by later deposits.

Given that new deposits inserted in will always have a higher deposit number, we can maintain a lot fewer interior nodes than
we do now. 

Currently if we have a set of deposits:
```
D_0 , D_1 , D_2 , D_3 ....... D_N-1 
```

We would store the parent nodes of roots of those deposit in the level above:
```
R_(0 1) , R_(2 3), R_(4 5) ..... R_(N-2 N-1)
```
The same reduction applies for the level above in the trie and so on. We would continue
doing this until we reached `R_Trie` . Currently we persist all these deposit roots and their relevant interior nodes. While this 
wasn't an issue when we had a small amount of deposits, with mainnet being as large as it has been, the space taken up by those interior nodes has grown. 

Given that we only expect to insert new deposits into the trie at a higher index, we can make some simplifications. Instead of storing 

```
R_(0 1) , R_(2 3), R_(4 5) ..... R_(N-2 N-1)
```
and all its interior nodes, we just need to store the last branch. In the above case it would simply be 
```
R_Trie
.
.
.
R_(N-2 N-1)
      \
    R _ N-1
```

By simply keeping this branch, you can use it to derive the next branch for a new deposit. Instead of storing `2n` roots , you would only need to store `log n + a` roots, where a is a fixed constant. This would be a very large improvement over the current status-quo and is especially effective for a large number of deposits. 
  
### Describe alternatives you've considered

None others so far

**Comment by potuz** [comment]
Putting this here for lack of a better place as it's vaguely related if we can prune old deposits

https://eips.ethereum.org/EIPS/eip-4881

**Comment by rauljordan** [comment]
Closing in favor of #11256
