### ISSUE TITLE
Error Not Logged When A Port is Taken Up

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1017]
Currently if a port for p2p is already taken up, an error is not logged. A PR for this would
be to have an error logged if a specified port cannot be used

**Comment by prestonvanloon** [comment]
In my opinion, this should force a graceful shutdown of the application. If the port to bind is already in use, then their will be no way to communicate with peers.

To reproduce the problem, run two beacon-chain nodes with the `--p2p-port` flag set to the same value. You would expect one to fail entirely, but it is silently failing to bind to the port.

**Comment by jgimeno** [comment]
I can take a look on this issue if you don't mind?

**Comment by nisdas** [comment]
Sure thing ! Assigned to @jgimeno

**Comment by jgimeno** [comment]
Another problem I have seen while executing the code is using the same folder for database, it does not even throw any error, it gets stucked in line 66 in node/node.go.

```
	if err := beacon.startDB(ctx); err != nil {
```

Maybe this is another issue we need to create?

**Comment by prestonvanloon** [comment]
@jgimeno Yes, that looks like it would be another issue. We should have a lock on the database directory such that only one process can use it.

**Comment by prestonvanloon** [comment]
@jgimeno created here: #1112
