### ISSUE TITLE
`validator wallet create` does not recognize `imported`

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#10181]
# 🐞 Bug Report

### Description

When running `validator --datadir /var/lib/prysm wallet create --wallet-dir /var/lib/prysm --keymanager-kind imported --accept-terms-of-use --wallet-password-file /var/lib/prysm/password.txt`, the following errors are logged:

```
[2022-02-03 12:20:49]  WARN flags: Running on Ethereum Consensus Mainnet
[2022-02-03 12:20:49] FATAL wallet: Could not create a wallet: imported is not an allowed keymanager
```

The usage for the command shows:

```
NAME:
   validator wallet create - creates a new wallet with a desired type of keymanager: either on-disk (imported), derived, or using remote credentials

USAGE:
   validator wallet create [command options] [arguments...]

OPTIONS:
   --wallet-dir value                     Path to a wallet directory on-disk for Prysm validator accounts (default: "/nonexistent/.eth2validators/prysm-wallet-v2")
   --keymanager-kind value                Kind of keymanager, either imported, derived, or remote, specified during wallet creation
```

I'd expect `keymanager-kind` to either accept `imported` or the usage text to be changed.

### Has this worked before in a previous version?

Unknown

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
validator version Prysm/v2.0.6/e26cde5e091befe0c777992734c37e7a1e6c53c2. Built at: 2022-01-25 21:30:35+00:00
  </code>
</pre>

**Comment by michaelneuder** [comment]
This is related to https://github.com/prysmaticlabs/prysm/pull/10155. We thought it was going to be backwards compatible, sorry. I will take a look at this tonight EST. @rauljordan FYI

**Comment by yorickdowne** [comment]
I tried with `local` and get: `Could not create a wallet: local is not an allowed keymanager`

**Comment by prestonvanloon** [comment]
@yorickdowne @michaelneuder the PR #10155 was not included in v2.0.6 so that is unlikely to be the root cause of the issue.

> I tried with local and get: Could not create a wallet: local is not an allowed keymanager

yes, this is because v2.0.6 does not have #10155. Perhaps try from the head of the develop branch.

**Comment by yorickdowne** [comment]
Got it thanks. Any take on wallet-dir being ignored?

**Comment by prestonvanloon** [comment]
This feels familiar but I can't recall if we have fixed this before... @james-prysm @rauljordan -- any thoughts?

**Comment by james-prysm** [comment]
@prestonvanloon @rauljordan @michaelneuder I'm not sure if there's some backstory on this but apparently it's been this way for quite some time... the term used apparently is  'direct' from this code here https://github.com/michaelneuder/prysm/blob/v2.0.0/validator/keymanager/types.go
you would do --keymanager-kind direct for imported... it looks like it has been this way since v2.0.0? or am I seeing this wrong... anyone have some backstory on why it was this way i guess the document might need to be updated?

**Comment by yorickdowne** [comment]
Thank you, I shall try direct.

If you have wallet-dir parameter working can you share the full command line? I tried it right after validator and after wallet create and it’s ignored in both locations.

**Comment by james-prysm** [comment]
i think you are missing a dot in front for example i used ./prysm.sh validator wallet create --wallet-dir ./test --keymanager-kind direct

**Comment by yorickdowne** [comment]
I am good for the directory, it was just not giving it a —datadir. Sorry for the runaround on that.

**Comment by james-prysm** [comment]
oh i don't think --datadir is required for wallet create, it's required when you're running the validator

**Comment by yorickdowne** [comment]
It’s required so the acceptance file for terms of use can be written. All good, works the way it is now :)

**Comment by michaelneuder** [comment]
oh cool. glad it wasn't #10155 haha. would've been 2/2 on my first 2 PRs causing bugs.

**Comment by rauljordan** [comment]
The solution to this would be to ensure the --keymanager-kind flag supports `imported`, `local`, and `direct` with the same behavior for all three

**Comment by yorickdowne** [comment]
Personally I’d be alright if the help text matched the behavior, no other changes :).

**Comment by james-prysm** [comment]
I'll try to get a longerterm fix in this week for  supporting these while ensuring backward compatibility.
