### ISSUE TITLE
Validator send attestation the slot before sync this slot.

### ISSUE THREAD

**Issue by Dimasin** [prysmaticlabs/prysm#10202]
# 🐞 Bug Report

### Description

Validator send attestation the slot before sync this slot. Fields BeaconBlockRoot and TargetRoot write from the parent slot.

### Has this worked before in a previous version?

 Yes, the previous versions are also affected.

## 🔥 Error

<pre><code>
beacon-chain[6134]: time="2022-02-08 19:14:38" level=info msg="Synced new block" block=0xc3a47c81... epoch=97670 finalizedEpoch=97668 finalizedRoot=0xba580f17... parentRoot=0x71ed36a3... prefix=blockchain slot=3125471 slotInEpoch=31 version=altair
beacon-chain[6134]: time="2022-02-08 19:14:38" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain slot=3125471 syncBitsCount=506
validator[6172]: time="2022-02-08 19:14:48" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x000000000000] slot=3125472 slotInEpoch=0 totalAttestersInEpoch=1
validator[6172]: time="2022-02-08 19:14:51" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[XXXXXX] BeaconBlockRoot=0xc3a47c81a490 CommitteeIndex=60 Slot=3125472 SourceEpoch=97670 SourceRoot=0x2808b7ffa375 TargetEpoch=97671 TargetRoot=0xc3a47c81a490 prefix=validator
beacon-chain[6134]: time="2022-02-08 19:14:53" level=info msg="Synced new block" block=0x458d2cf1... epoch=97671 finalizedEpoch=97669 finalizedRoot=0x987e56de... parentRoot=0xc3a47c81... prefix=blockchain slot=3125472 slotInEpoch=0 version=altair
...
validator[6172]: time="2022-02-08 19:27:23" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=97671 inactivityScore=0 newBalance=XX.XXXXXXXXX oldBalance=XX.XXXXXXXXX percentChange="-0.00001%" ...
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-99-generic x86_64)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
 v2.0.6 e26cde5
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
[See pict](https://github.com/Dimasin/prysm/blob/main/prysm_bug.png) or [link slot](https://beaconcha.in/block/3125472) and [Attestation 63 - 64](https://beaconcha.in/block/3125473#attestations)

**Comment by Dimasin** [comment]
It doesn't just happen to zero slots:
```sh
validator[6172]: time="2022-02-09 05:16:51" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[XXXXXX] BeaconBlockRoot=0x34b6cf9eebff CommitteeIndex=5 Slot=3128482 SourceEpoch=97764 SourceRoot=0x7c8d96e12788 TargetEpoch=97765 TargetRoot=0x1a7407f91ad7 prefix=validator
beacon-chain[6134]: time="2022-02-09 05:16:52" level=info msg="Synced new block" block=0x8c0ed93b... epoch=97765 finalizedEpoch=97763 finalizedRoot=0x2222cd14... parentRoot=0x34b6cf9e... prefix=blockchain slot=3128482 slotInEpoch=2 version=altair
```

**Comment by potuz** [comment]
This is the expected behavior, the block was synced 5 seconds into the slot, we submit our attestation at second 4 for the previous block in this case. Unfortunately there are plenty of late blocks still on mainnet.

**Comment by Dimasin** [comment]
How can this be changed ?
