### ISSUE TITLE
Release non-portable builds of blst

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#10220]
Our current release comes with portable versions of blst to accommodate people running with CPUs that do not support ADX (supported first by Intel in Broadwell, launched over 7 years ago). Given that the vast majority of users do have newer CPUs we should release a separate compiled binary without the compile flags `__BLST_PORTABLE`  so that the included assembly has the performance-enhancing instructions. This targets the most intense CPU bound paths of our code. 

This can be easily used by users of the prysm.sh or prysm.bat scripts by adding a flag to those. Others may choose to download the right binary from the release page.

**Comment by prestonvanloon** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/8410 

Users complained about their CPU throwing illegal instructions for ADX.

**Comment by potuz** [comment]
Fixed in v2.1.1
