### ISSUE TITLE
Cross compilation on Apple M1 development environment

### ISSUE THREAD

**Issue by leolara** [prysmaticlabs/prysm#10257]
# 🚀 Feature Request

### Description

We could enable cross compilation on Apple M1 development environment

### Describe the solution you'd like

Adapting the current cross compilation infrastructure to Apple M1

### Describe alternatives you've considered

None

**Comment by leolara** [comment]
@prestonvanloon could you assign to me?

**Comment by prestonvanloon** [comment]
> @prestonvanloon could you assign to me?

Yes, thanks!

**Comment by rauljordan** [comment]
Done! Thanks @leolara
