### ISSUE TITLE
Feature/Bug Silently fail when using custom presets.

### ISSUE THREAD

**Issue by z3n-chada** [prysmaticlabs/prysm#10254]
# 🚀 Feature Request

### Description
Currently when using prysm you can update some of the preset values (for example EPOCHS_PER_ETH1_VOTING_PERIOD). This change is not propagated or warned about. When we modify the EPOCHS_PER_ETH1_VOTING_PERIOD we effect the structure of the BeaconState and therefore all state and roots. In this case the size of the eth1_data_votes list. Currently the user is not warned about this being ignored and can lead to issues in local testnets. 

### Describe the solution you'd like

Either allow this behavior more transparently and modify the BeaconState object based on the presets that effect the structures, or warn the user and stop the process when using a config with these set. 

A reasonable workaround would be to just exit when we parse the config and recommend a compile flag for the next build.

### Describe alternatives you've considered
..

**Comment by prestonvanloon** [comment]
I think it would be reasonable to check the beacon config on start up against the build time configured beacon state. 
If there is a mismatch, then fail to run the application.

**Comment by nisdas** [comment]
@z3n-chada This should be fixed on our end, ideally you should be able to provide any config value for `EPOCHS_PER_ETH1_VOTING_PERIOD` and the hash tree root calcuation shouldn't change. We have compile time presets which we should use instead of the config.
