### ISSUE TITLE
Simpler web UI CI for release

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#10272]
# 🚀 Feature Request

### Description

Currently, the web UI release requires a prod build locally, packaged tar file with a corresponding sha256, and updated site.go file in prysm. much of this is manual and prone to human error. we would like a more standard way of doing this with less human interaction.

### Describe the solution you'd like

once we flag the web release the prysm CICD should take the flaged release version and build the website into a static folder in prysm which can be released. we would have to incorporate a new dependency for this to be possible in go but would greatly simplify and streamline our webui release process.

**Comment by GAURAV1-ui** [comment]
I want to work on this issue.

**Comment by rauljordan** [comment]
The current steps are:

## Building the Prod Web UI Bundle

Make sure you have node < v17 installed (we use v15). Then:

```
git clone git@github.com:prysmaticlabs/prysm-web-ui && cd prysm-web-ui
npm install
npm run build:prod
```

This will build the web UI to the `dist/` folder.

## Creating the Gzipped Release Asset with Sha

Then, we gzip the built bundle with
```
cd dist && tar -czvf ~/Desktop/prysm-web-ui.tar.gz .
```
We then create a shasum256 for the file gzipped file
```
cd ~/Desktop && shasum -a 256 prysm-web-ui.tar.gz > ~/Desktop/prysm-web-ui.tar.gz.shasum256
```

## Tag a Web UI Release

We then tag a release on Github in the web UI repository and upload both assets (gzipped and shasum file)

## Bake the New Web UI Release into the Prysm Repo

Then, we go into the Prysm repository, and perform the following steps:

In the WORKSPACE file, find the line with:
```
http_archive(
    name = "prysm_web_ui",
    build_file_content = """
filegroup(
    name = "site",
    srcs = glob(["**/*"]),
    visibility = ["//visibility:public"],
)
""",
    sha256 = "f196fe4367c2d2d01d36565c0dc6eecfa4f03adba1fc03a61d62953fce606e1f",
    urls = [
        "https://github.com/prysmaticlabs/prysm-web-ui/releases/download/v1.0.2/prysm-web-ui.tar.gz",
    ],
)
```
and update the version in the URL as well as the sha256 with the new values.

Then, try to build the site data
```
bazel build //validator/web:site_data
```

Copy the built site data from the bazel folders into the Prysm repo
```
cp bazel-bin/validator/web/site_data.go ./validator/web/site_data.go
```

Format the file:
```
gofmt -w -s ./validator/web/site_data.go
```
Create a pull request in the Prysm repo with your changes

**Comment by rauljordan** [comment]
> I want to work on this issue.

hi @GAURAV1-ui unfortunately this is something we need to handle internally, as only our team has permissions to automate CI pipelines. @Taranpreet26311 from our team is our devops person and can help look into this

**Comment by GAURAV1-ui** [comment]
Thanks rauljordan, for contacting.

**Comment by prestonvanloon** [comment]
This is probably something that can be done with a github action or some form of automation. Reminds me of @renovate-bot.
