### ISSUE TITLE
Prysm-web3signer validator process exits if no public keys are provided

### ISSUE THREAD

**Issue by pablomendezroyo** [prysmaticlabs/prysm#10294]
# 💎 Issue

The Prysm-web3signer validator process exits if no public keys are provided `--validators-external-signer-public-keys`. 

### Background

 Context and background information on the discussion...
Not sure if this is an expected behaviour, but ideally it should keep running, specially for the future once the [remote api keymanager on the client](https://ethereum.github.io/keymanager-APIs/#/Remote%20Key%20Manager) is implemented so it keeps listening for requests to upload new validators

### Description

The error 
```
time="2022-03-01 14:44:49" level=error msg="could not decode public key for web3signer: : empty hex string" prefix=main
```

**Comment by james-prysm** [comment]
currently expected behavior, feature request linked here https://github.com/prysmaticlabs/prysm/issues/10293

**Comment by james-prysm** [comment]
I believe this is fixed in the current version in develop. closing.
