### ISSUE TITLE
Update validator cmd to use functional options

### ISSUE THREAD

**Issue by kasey** [prysmaticlabs/prysm#10339]
# 💎 Issue
We have done some work to clean up the beacon node initialization process using [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis). The validator cli hasn't had this makeover yet, which would be an improvement for the addition of more cli flags, like the fee recipient config.

### Background

examples of functional options being generated from flags (which are also pushed into the component-specific flag handling package):
  - https://github.com/prysmaticlabs/prysm/blob/develop/cmd/beacon-chain/blockchain/options.go
  - https://github.com/prysmaticlabs/prysm/blob/develop/cmd/beacon-chain/powchain/options.go

how the FlagOptions are set up and passed in to the beacon-chain node: https://github.com/prysmaticlabs/prysm/blob/develop/cmd/beacon-chain/main.go#L234-L246
variadic argument on node.New: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/node/node.go#L108
applying the opts: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/node/node.go#L149
opt definitions: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/node/options.go

### Description

Update the validator cli to use the same functional options pattern as beacon-chain.

**Comment by mauriceLC92** [comment]
Hey @kasey 👋 

First time seeing the repo! Keen to start contributing...Could you assign this issue to me?

**Comment by nisdas** [comment]
Assigned to you @mauriceLC92

**Comment by james-prysm** [comment]
i think we can close this now with mike's help
