### ISSUE TITLE
Issue adding multiple beacons as rpc-providers in .yaml config

### ISSUE THREAD

**Issue by curveballdaniel** [prysmaticlabs/prysm#10342]
# 🐞 Bug Report

### Description

I've been testing a setup (`IP:port,IP2:port2`) and my validator seems to get stuck here:
```
time="2022-03-10 20:20:12" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator
```
Individually (without a comma separation), it works with both of the beacons. v2.0.6 for both beacon + validator

Both beacons are fully synced, and swapping to either them after a restart of the validator with different flags (a single beacon) automatically starts validating/attesting with no problems.

### Has this worked before in a previous version?

Haven't tested.

## 🔬 Minimal Reproduction

I'm running this from a docker-compose, pulling from a config file:

Image: `gcr.io/prysmaticlabs/prysm/validator:v2.0.6`, command: `--config-file=/config/validator.yaml` (assorted other stuff, such as ports and the lot all as should be)

The config file:
```
---
accept-terms-of-use: yes

##############
# Connectivity
beacon-rpc-provider: XYZ:4000,XYZA:4000
monitoring-host: 0.0.0.0

grpc-gateway-host: 0.0.0.0

prater: yes
```

After discussion in the discord that:

"
With yaml files it's slightly different format this should work
```
beacon-rpc-provider:
- XYZ:4000
- XYZA:4000
```
"

I then received this error back from the validator, which dies immediately:

```
time="2022-03-10T22:06:47Z" level=error msg="Mismatched type for flag 'beacon-rpc-provider'. Expected 'string' but actual is ''" prefix=main
```

## 🔥 Error

Error when using expected `.yaml` format:

```
time="2022-03-10T22:06:47Z" level=error msg="Mismatched type for flag 'beacon-rpc-provider'. Expected 'string' but actual is ''" prefix=main
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**What version of Prysm are you running? (Which release)**

v2.0.6
Validator: `gcr.io/prysmaticlabs/prysm/validator:v2.0.6`
Beacon: `gcr.io/prysmaticlabs/prysm/beacon-chain:v2.0.6`

**Anything else relevant (validator index / public key)?**
N/A

**Comment by rkapka** [comment]
Hi @curveballdaniel. The syntax
```
beacon-rpc-provider:
- XYZ:4000
- XYZA:4000
```
will not be supported because it requires changes that would interfere with a lot of stakers' setups. However, the syntax `beacon-rpc-provider: XYZ:4000,XYZA:4000` should work correctly. Can you please verify that this problem persists in a newer version of Prysm?

**Comment by curveballdaniel** [comment]
Understood. I have just tested the `beacon-rpc-provider: XYZ:4000,XYZA:4000` input on v2.1.3 and it works! I can live with this solution 🙂. Thank you!
