### ISSUE TITLE
Incorrect root in beacon headers API

### ISSUE THREAD

**Issue by z3n-chada** [prysmaticlabs/prysm#10393]
# 🐞 Bug Report

### Description

The /eth/v1/beacon/headers/<id> endpoint returns the htr of the SignedBeaconBlockHeader instead of the BeaconBlockHeader

### Has this worked before in a previous version?
Not sure.

## 🔬 Minimal Reproduction

<pre>
  <code>
curl http://PRYSMNODE_IP:BEACON_API_PORT/eth/v1/beacon/headers/1 | jq
  </code>
</pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   OS agnostic
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    Most likely version agnostic
  </code>
</pre>

**Comment by terencechain** [comment]
Thanks for the issue!
