### ISSUE TITLE
Add option to save periodic state checkpoints

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#10410]
With the new checkpoint sync feature, we can let a node save periodically beacon states ssz and let the node backup from those. Instead of backing up the entire dbase, the node can resync quickly from these automatic backups without relying on any provider. 
cc @kasey

**Comment by muang0** [comment]
Love this, exactly the use-case I was looking looking to fill with checkpoint-sync.
If you happen to know already, could you could share a rough estimate on how much time it might take to checkpoint-sync from a recently finalized state?

**Comment by prestonvanloon** [comment]
This is easily achievable with the beacon API.

```bash
# Fetch the latest finalized state from the debug endpoint and do something with it...
curl -X 'GET' \
  'http://beacon_node:3500/eth/v2/debug/beacon/states/finalized' \
  -H 'accept: application/octet-stream'
  ```
