### ISSUE TITLE
build: llvm error when build prysm from source on macos 

### ISSUE THREAD

**Issue by VieYang** [prysmaticlabs/prysm#10442]
# 🐞 Bug Report

### Description

build error on macos

### Has this worked before in a previous version?

it's ok on linux but not for mac

## 🔥 Error

<pre>
  <code>
% uname -a 
Darwin User 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
% bazel version
Bazelisk version: v1.11.0
Build label: 4.2.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 2 18:28:52 2021 (1638469732)
Build timestamp: 1638469732
Build timestamp as int: 1638469732
% bazel build //beacon-chain:beacon-chain                 
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False' 
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False' 
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_ubuntu_clang not using checked in configs; Bazel version 4.2.2 was picked/selected but no checked in config was found in map {"4.2.1": ["clang"]}
WARNING: /Users/user/project/prysm/beacon-chain/BUILD.bazel:3:14: target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
INFO: Build options --compilation_mode, --copt, --crosstool_top, and 3 more have changed, discarding analysis cache.
INFO: Analyzed target //beacon-chain:beacon-chain (0 packages loaded, 14241 targets configured).
INFO: Found 1 target...
INFO: From BazelWorkspaceStatusAction stable-status.txt:
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Target //cmd/beacon-chain:beacon-chain up-to-date:
  bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain
INFO: Elapsed time: 7.080s, Critical Path: 6.01s
INFO: 8 processes: 1 internal, 7 darwin-sandbox.
INFO: Build completed successfully, 8 total actions
% bazel build //beacon-chain:beacon-chain --config=release
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False' 
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False' 
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_ubuntu_clang not using checked in configs; Bazel version 4.2.2 was picked/selected but no checked in config was found in map {"4.2.1": ["clang"]}
WARNING: /Users/user/project/prysm/beacon-chain/BUILD.bazel:3:14: target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
INFO: Build options --compilation_mode, --copt, --crosstool_top, and 3 more have changed, discarding analysis cache.
INFO: Analyzed target //beacon-chain:beacon-chain (0 packages loaded, 14314 targets configured).
INFO: Found 1 target...
INFO: From BazelWorkspaceStatusAction stable-status.txt:
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
date: illegal option -- -
usage: date [-jnRu] [-r seconds|file] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
ERROR: /private/var/tmp/_bazel_user/393fe119889f7a13bb777ea02f597f70/external/com_google_protobuf/BUILD:210:11: Compiling src/google/protobuf/io/tokenizer.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/llvm_toolchain/bin/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 43 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
In file included from external/llvm_toolchain/bin/../include/c++/v1/cstring:60:
external/llvm_toolchain/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
                                                               ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:80:75: error: use of undeclared identifier 'strpbrk'
char* __libcpp_strpbrk(const char* __s1, const char* __s2) {return (char*)strpbrk(__s1, __s2);}
                                                                          ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:87:65: error: use of undeclared identifier 'strrchr'; did you mean 'strchr'?
char* __libcpp_strrchr(const char* __s, int __c) {return (char*)strrchr(__s, __c);}
                                                                ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:94:76: error: use of undeclared identifier 'memchr'
void* __libcpp_memchr(const void* __s, int __c, size_t __n) {return (void*)memchr(__s, __c, __n);}
                                                                           ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:101:74: error: use of undeclared identifier 'strstr'; did you mean 'strchr'?
char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                         ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:77:13: note: 'strchr' declared here
      char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:101:74: error: no matching function for call to 'strchr'
char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                         ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:77:13: note: candidate disabled: <no message provided>
      char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
external/llvm_toolchain/bin/../include/c++/v1/string.h:101:81: error: cannot initialize a parameter of type 'char *' with an lvalue of type 'const char *'
char* __libcpp_strstr(const char* __s1, const char* __s2) {return (char*)strstr(__s1, __s2);}
                                                                                ^~~~
external/llvm_toolchain/bin/../include/c++/v1/string.h:77:32: note: passing argument to parameter '__s' here
      char* strchr(      char* __s, int __c) {return __libcpp_strchr(__s, __c);}
                               ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:69:9: error: no member named 'memcpy' in the global namespace; did you mean 'memchr'?
using ::memcpy;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/string.h:96:13: note: 'memchr' declared here
const void* memchr(const void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
            ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:70:9: error: no member named 'memmove' in the global namespace
using ::memmove;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:71:9: error: no member named 'strcpy' in the global namespace; did you mean 'strchr'?
using ::strcpy;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:72:9: error: no member named 'strncpy' in the global namespace
using ::strncpy;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:73:9: error: no member named 'strcat' in the global namespace; did you mean 'strchr'?
using ::strcat;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:74:9: error: no member named 'strncat' in the global namespace
using ::strncat;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:75:9: error: no member named 'memcmp' in the global namespace; did you mean 'memchr'?
using ::memcmp;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/string.h:96:13: note: 'memchr' declared here
const void* memchr(const void* __s, int __c, size_t __n) {return __libcpp_memchr(__s, __c, __n);}
            ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:76:9: error: no member named 'strcmp' in the global namespace; did you mean 'strchr'?
using ::strcmp;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/string.h:75:13: note: 'strchr' declared here
const char* strchr(const char* __s, int __c) {return __libcpp_strchr(__s, __c);}
            ^
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.cc:91:
In file included from external/com_google_protobuf/src/google/protobuf/io/tokenizer.h:41:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string:504:
In file included from external/llvm_toolchain/bin/../include/c++/v1/string_view:175:
In file included from external/llvm_toolchain/bin/../include/c++/v1/__string:57:
In file included from external/llvm_toolchain/bin/../include/c++/v1/algorithm:641:
external/llvm_toolchain/bin/../include/c++/v1/cstring:77:9: error: no member named 'strncmp' in the global namespace
using ::strncmp;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:78:9: error: no member named 'strcoll' in the global namespace
using ::strcoll;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:79:9: error: no member named 'strxfrm' in the global namespace
using ::strxfrm;
      ~~^
external/llvm_toolchain/bin/../include/c++/v1/cstring:82:9: error: no member named 'strcspn' in the global namespace
using ::strcspn;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Target //cmd/beacon-chain:beacon-chain failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/user/project/prysm/proto/prysm/v1alpha1/BUILD.bazel:151:11 GoCompilePkg proto/prysm/v1alpha1/go_default_library.a failed: (Exit 1): cc_wrapper.sh failed: error executing command external/llvm_toolchain/bin/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 43 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 2.160s, Critical Path: 0.68s
INFO: 28 processes: 15 internal, 13 darwin-sandbox.
FAILED: Build did NOT complete successfully
  </code>
</pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Darwin User 21.4.0 Darwin Kernel Version 21.4.0
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.6
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
I think that release builds only work on linux at this time. Someone with darwin/arm64 will have to take a look. 

Do you have xcode build tools installed (`xcodebuild --version`)?

I wonder if it would work with g++ instead of llvm...

**Comment by VieYang** [comment]
Not yet, only `CommandLineTools`, I can install it now.

And, I tried to build prysm with llvm13 and llvm14, but I failed.

**Comment by VieYang** [comment]
```
% xcodebuild -version  
Xcode 13.3
Build version 13E113
```

**Comment by VieYang** [comment]
nope, it's the same error.

**Comment by VieYang** [comment]
When I build with `bazel-5.1.0-darwin-arm64`:

```
% ./bazel-5.1.0-darwin-arm64 version
Build label: 5.1.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 24 14:22:07 2022 (1648131727)
Build timestamp: 1648131727
Build timestamp as int: 1648131727
vie@Vie prysm % ./bazel-5.1.0-darwin-arm64 build //beacon-chain:beacon-chain --config=release
WARNING: /Users/vie/project/prysm/beacon-chain/BUILD.bazel:3:14: target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
ERROR: /private/var/tmp/_bazel_vie/393fe119889f7a13bb777ea02f597f70/external/prysm_toolchains/BUILD.bazel:148:10: configurable attribute "toolchain" in @prysm_toolchains//:cc-toolchain-multiarch doesn't match this configuration. Would a default condition help?

Conditions checked:
 @prysm_toolchains//:linux_arm64
 @prysm_toolchains//:linux_amd64
 @prysm_toolchains//:osx_amd64
 @prysm_toolchains//:windows_amd64

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @prysm_toolchains//:cc-toolchain-multiarch has configuration identifier 7e64eec. To inspect its configuration, run: bazel config 7e64eec.

For more help, see https://docs.bazel.build/configurable-attributes.html#why-doesnt-my-select-choose-what-i-expect.

ERROR: /Users/vie/project/prysm/cmd/beacon-chain/BUILD.bazel:132:10: While resolving toolchains for target //cmd/beacon-chain:beacon-chain: invalid registered toolchain '@prysm_toolchains//:cc-toolchain-multiarch': 
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: 
INFO: Elapsed time: 56.447s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 177 targets configured)
```

Is it because the compiler did not find the corresponding version of the llvm package for the system?

**Comment by rauljordan** [comment]
Bazel build now works on M1 and M2 macs. Please let us know if this issue is still present

**Comment by VieYang** [comment]
`bazel build //beacon-chain:beacon-chain` is ok but `bazel build //beacon-chain:beacon-chain --config=release` still had this error.

**Comment by potuz** [comment]
https://discord.com/channels/476244492043812875/701094045879107744/1009429658112102421

Is this relevant?

**Comment by prestonvanloon** [comment]
We could update llvm to a more recent one. 10.0.0 is 2 years old

**Comment by VieYang** [comment]
> https://discord.com/channels/476244492043812875/701094045879107744/1009429658112102421
> 
> Is this relevant?

No, I don't think the two are the same error.  
Although both errors occur after adding `--config=release`, but  I don't think the cause of the error is quite the same.
This error caused by llvm.

**Comment by VieYang** [comment]
> We could update llvm to a more recent one. 10.0.0 is 2 years old

Yes, we should upgrade it to the latest version. 
 I tried to upgrade llvm before, but obviously, I failed.

**Comment by james-prysm** [comment]
closing due to raul testing on mac m1 in #11310
