### ISSUE TITLE
Support retrieving genesis from a remote beacon node at startup

### ISSUE THREAD

**Issue by kasey** [prysmaticlabs/prysm#10448]
# 🚀 Feature Request

### Description

Checkpoint sync allows the checkpoint state and block to be downloaded from a remote beacon node URL. It would be convenient if genesis could also be downloaded the same way. 

### Describe the solution you'd like

Add a `--genesis-beacon-api-url` flag that can be used to specify the URL of a trusted beacon node API.

**Comment by prestonvanloon** [comment]
Could `--genesis-state=` accept a URL?

**Comment by kasey** [comment]
> Could `--genesis-state=` accept a URL?

On the fence about this. URLs and file names validate differently. "Could not open file <malformed URL>" or "Could not connect to server non-existent-file.TLD". It seems simpler to give validation feedback when they are separate flags. Thoughts?

**Comment by kasey** [comment]
When I have made flags like this in the past I would require that files be specified as `file://` but I don't think we want to do that here.
