### ISSUE TITLE
Prysm beacon node needs much CPU

### ISSUE THREAD

**Issue by luarx** [prysmaticlabs/prysm#10458]
# 💎 Issue

### Background

I run Prysm v2.0.5 and see that the **Beacon node** needs a lot of CPU.

### Description
Is there any option that can be configured to try to reduce that? 

Thanks in advance!

**Comment by rkapka** [comment]
Hi @luarx , are you observing the same issue in the latest release - v2.1.2? If yes, can you be more precise and present a screenshot of CPU metrics?

**Comment by james-prysm** [comment]
the issue is stale waiting for more info.
