### ISSUE TITLE
ExecutionPayload fields not complying with the consensus spec

### ISSUE THREAD

**Issue by alrevuelta** [prysmaticlabs/prysm#10460]
# 🐞 Bug Report

### Description

Taken from the official spec, the [`ExecutionPayload`](https://github.com/ethereum/consensus-specs/blob/master/specs/bellatrix/beacon-chain.md#executionpayload) contains different fields that the ones [prysm has](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/apimiddleware/structs.go#L389-L403). One of the reasons of this difference is that `coinbase` was renamed to `fee_recipient` in this [PR](https://github.com/ethereum/consensus-specs/pull/2728).

Moreover, there are other differences, prysm/spec.
* `coinbase`/`fee_recipient`
* `receipt_root`/`receipts_root`
* `random`/`prev_randao`

### Has this worked before in a previous version?
NA

## 🔬 Minimal Reproduction
NA

## 🔥 Error
NA

## 🌍  Your Environment

**Operating System:**
NA

**What version of Prysm are you running? (Which release)**
NA

**Anything else relevant (validator index / public key)?**
NA

**Comment by nisdas** [comment]
Hey @rkapka , according to this [comment](https://github.com/prysmaticlabs/prysm/pull/10479#issuecomment-1087450033), it seems that it is still non-compliant. If it is accurate, we should re-open the issue till its resolved.
