### ISSUE TITLE
Sir, I am working on a ZKT project and need a lot of Goerli. I am willing to buy Goerli with USDT. Can you help me

### ISSUE THREAD

**Issue by Jiangzy520** [prysmaticlabs/prysm#10478]
# 💎 Issue

### Background

 Context and background information on the discussion...

**Comment by Jiangzy520** [comment]
@Nongmingong88

**Comment by Jiangzy520** [comment]
@potuz Sir I am also a mountain biker. Road bike enthusiast. Can you help me find Goerli. Finish my homework

**Comment by prestonvanloon** [comment]
We cannot help you, sorry.
