### ISSUE TITLE
panic: page 3421999 already freed

### ISSUE THREAD

**Issue by ihsanmaulanahamdani** [prysmaticlabs/prysm#10484]
Latest Prysm Version: v2.0.6

I got panic error and don't know what to do.

The error details:

2022-04-06 04:08:19]  INFO initial-sync: Processing block batch of size 64 starting from  0xb7011772... 3525984/3530739 - estimated time remaining 24m45s blocksPerSecond=3.2 peers=35
[2022-04-06 04:08:24]  INFO rpc: gRPC client connected to beacon node addr=127.0.0.1:52582
panic: page 3421999 already freed

goroutine 6994 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc000123100, 0x624a0c, 0x7f30ff72f000)
external/io_etcd_go_bbolt/freelist.go:175 +0x3e7
go.etcd.io/bbolt.(*node).spill(0xc037cb5110, 0xc050a51008, 0x1)
external/io_etcd_go_bbolt/node.go:359 +0x405
go.etcd.io/bbolt.(*node).spill(0xc037cb50a0, 0xc050a50ff0, 0x1)
external/io_etcd_go_bbolt/node.go:346 +0xba
go.etcd.io/bbolt.(*node).spill(0xc037cb5030, 0xc050a50fd8, 0x4)
external/io_etcd_go_bbolt/node.go:346 +0xba
go.etcd.io/bbolt.(*node).spill(0xc037cb4fc0, 0xc050a50fc0, 0x4)
external/io_etcd_go_bbolt/node.go:346 +0xba
go.etcd.io/bbolt.(*node).spill(0xc037cb4bd0, 0xc01cdfb350, 0xc003b36bb0)
external/io_etcd_go_bbolt/node.go:346 +0xba
go.etcd.io/bbolt.(*Bucket).spill(0xc01c7ff840, 0xc003b36c00, 0x19)
external/io_etcd_go_bbolt/bucket.go:570 +0x49a
go.etcd.io/bbolt.(*Bucket).spill(0xc013274718, 0x1b9789f70c, 0x30f7ee0)
external/io_etcd_go_bbolt/bucket.go:537 +0x3f6
go.etcd.io/bbolt.(*Tx).Commit(0xc013274700, 0x0, 0x0)
external/io_etcd_go_bbolt/tx.go:160 +0xe8
go.etcd.io/bbolt.(*DB).Update(0xc000f02800, 0xc003b37048, 0x0, 0x0)
external/io_etcd_go_bbolt/db.go:701 +0x105
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlocks(0xc001eb6180, 0x213ac98, 0xc0326995f0, 0xc0171143c0, 0x1d, 0x1d, 0x0, 0x0)
beacon-chain/db/kv/blocks.go:298 +0x4ab
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockBatch(0xc000e94400, 0x213abf0, 0xc05068b380, 0xc0097a6c00, 0x40, 0x40, 0xc016b09800, 0x40, 0x40, 0x0, ...)
beacon-chain/blockchain/receive_block.go:104 +0x592
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks(0xc01c7fe240, 0x213abf0, 0xc05068b380, 0x0, 0xed7582757, 0x30f7ee0, 0xc0097a6c00, 0x40, 0x40, 0xc07974d500, ...)
beacon-chain/sync/initial-sync/round_robin.go:283 +0x8fa
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData(0xc01c7fe240, 0x213abf0, 0xc05068b380, 0x0, 0xed7582757, 0x30f7ee0, 0x35cd5f, 0xc0514a2240)
beacon-chain/sync/initial-sync/round_robin.go:133 +0x14f
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch(0xc01c7fe240, 0x213abf0, 0xc05068b380, 0x0, 0xed7582757, 0x30f7ee0, 0x0, 0x0)
beacon-chain/sync/initial-sync/round_robin.go:86 +0x253
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync(0xc01c7fe240, 0x0, 0xed7582757, 0x30f7ee0, 0x0, 0x0)
beacon-chain/sync/initial-sync/round_robin.go:49 +0x19e
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc01c7fe240)
beacon-chain/sync/initial-sync/service.go:105 +0x8dd
created by github.com/prysmaticlabs/prysm/runtime.(*ServiceRegistry).StartAll
runtime/service_registry.go:46 +0x236

**Comment by prestonvanloon** [comment]
Looks a lot like this issue: https://github.com/etcd-io/bbolt/issues/266

You may need to delete your beaconchain.db and resync from genesis. Try running with `--clear-db`. That will attempt to delete your existing database and resync from genesis.

**Comment by rkapka** [comment]
Closing this because it's an issue with bolt itself.
