### ISSUE TITLE
Orphaned blocks served in BlocksByRange responses

### ISSUE THREAD

**Issue by michaelsproul** [prysmaticlabs/prysm#10491]
# 🐞 Bug Report

### Description

I think Prysm is serving orphaned blocks in response to `BlocksByRange` requests, contrary to this condition from the spec:

> Clients MUST respond with blocks from their view of the current fork choice -- that is, blocks from the single chain defined by the current head. Of note, blocks from slots before the finalization MUST lead to the finalized block reported in the Status handshake.

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#beaconblocksbyrange

I noticed this because Lighthouse logs a warning whenever it re-orgs, and we frequently see re-orgs during sync where Lighthouse has received orphaned blocks from before finalization:

> Apr 04 02:36:39.505 WARN Beacon chain re-org, reorg_distance: 1, new_slot: 3505952, new_head: 0xc222af38aad7bf5688dacab3bee3e641f7643cd8b6609cde511b5ca4aa5f4d59, new_head_parent: 0x959073f80a2037b63e183c96fc2e5b94ecb88128000d85ed9ae20b758390c604, previous_slot: 3505909, previous_head: 0x5fc2e763069065502974ef077ad26caf5756c0f993be940bd2f12a0914be6d77, service: beacon, module: beacon_chain::beacon_chain:3423

These blocks seem to come from Prysm peers. In the example above block 3505909 is an orphaned block that was received in a batch from `16Uiu2HAmT7bYXYzjcWQZXxrYLSUsjKg3RCfCocxn1gm8KuYFnAd4` running Prysm (logs are in reverse chronological order here):

> Apr 04 02:36:04.890 DEBG Batch processed, service: sync, processed_blocks: 52, last_block_slot: **3505909**, chain: 17417785903489362713, first_block_slot: 3505857, batch_epoch: **109558**, module: network::beacon_processor::worker::sync_methods:109

> Apr 04 02:35:42.856 DEBG Requesting batch, start_slot: 3505857, end_slot: 3505920, downloaded: 0, processed: 0, state: Downloading(**16Uiu2HAmT7bYXYzjcWQZXxrYLSUsjKg3RCfCocxn1gm8KuYFnAd4**, 0 blocks, 167), epoch: **109558**, chain: 17417785903489362713, service: sync, module: network::sync::range_sync::chain:886

> Apr 04 02:31:47.927 DEBG Identified Peer, protocols: ["/ipfs/id/1.0.0", "/ipfs/id/push/1.0.0", "/meshsub/1.1.0", "/meshsub/1.0.0", "/floodsub/1.0.0", "/eth2/beacon_chain/req/status/1/ssz_snappy", "/eth2/beacon_chain/req/goodbye/1/ssz_snappy", "/eth2/beacon_chain/req/ping/1/ssz_snappy", "/eth2/beacon_chain/req/beacon_blocks_by_range/2/ssz_snappy", "/eth2/beacon_chain/req/beacon_blocks_by_root/2/ssz_snappy", "/eth2/beacon_chain/req/metadata/2/ssz_snappy"], observed_address: "/ip4/122.148.186.92/tcp/39746", listening_ addresses: ["/ip4/144.91.111.23/tcp/13000"], agent_version: **Prysm/v2.0.6/e26cde5e091befe0c777992734c37e7a1e6c53c2**, protocol_version: ipfs/0.1.0, peer: **16Uiu2HAmT7bYXYzjcWQZXxrYLSUsjKg3RCfCocxn1gm8KuYFnAd4**, service: libp2p, module: lighthouse_network::peer_manager:399

The `Status` message for this peer shows that it had already finalized past slot 3505909 (epoch 109559):

> Apr 04 02:31:48.283 DEBG Received Status Response, fork_digest: [175, 202, 171, 160], finalized_epoch: **109934**, finalized_root: 0xcd62…31f1, head_slot: 3517956, head_root: 0x0458…f093, peer_id: 16Uiu2HAmT7bYXYzjcWQZXxrYLSUsjKg3RCfCocxn1gm8KuYFnAd4, service: router, module: network::router::processor:147

I've observed these re-orgs multiple times while syncing Lighthouse, but have only just got around to digging into it in detail. Notably, they occur on Gnosis chain quite often, where all peers are either Lighthouse or Prysm.

## 🔬 Minimal Reproduction

Run Lighthouse on the same network as Prysm and observe re-orgs from before finalization from Prysm peers.

## Impact

The impact of this bug is quite minor:

- It slows down sync for all clients by forcing them to work around unnecessary re-orgs.
- It creates peering issues, as some clients may penalise Prysm peers for this behaviour (e.g. Lighthouse penalises and bans Prysm when this happens).

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

Observed with Prysm v2.0.6 on mainnet and Gnosis chain.

**Comment by nisdas** [comment]
Appreciate the report @michaelsproul , we are aware of the issue and are working on a solution for it. This will most likely not be fixed in the next release but the release after that. Will keep you updated on the status of the fixes in this issue.

**Comment by michaelsproul** [comment]
Awesome, thanks!

**Comment by rauljordan** [comment]
hi @nisdas is this one fixed?

**Comment by nisdas** [comment]
It is fixed, we can close it.
