### ISSUE TITLE
Deprecate Hash Utils for ETH1.0 Keccak256

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1051]
Should we deprecate our hash utils package and just use go-ethereum/common? common package is thoroughly tested works and has good helper methods. @rauljordan mentioned crypto/sha3 package is different than the one ETH1.0 client uses.

For background and history, there was an EIP back to standardize hashes and the decision was made to not use a standard sha3 implementation that hare out there and instead use a modified keccak256 which lives in common package. Currently, all ETH1.0 client use the modified keccak256.

@nisdas has raised a question on whether `common.BytesToHash` hashes or simply converts byte slice into 32 byte array. He is doing more investigation so tentatively assigning this to him.

Reference: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by nisdas** [comment]
Hey so I figured it out, the sha3 package in geth is actually a previous version of the sha3 package in golang crypto : https://github.com/golang/crypto/tree/master/sha3 . They checked in a version before the standards were changed, so to hash it we simply do `crypto.Keccak256Hash()` . Will push up a PR for this in a while
