### ISSUE TITLE
`/eth/v1/events` emits `context deadline exceeded` after 2 mins (v2.1.0)

### ISSUE THREAD

**Issue by moshe-blox** [prysmaticlabs/prysm#10575]
# 🐞 Bug Report

### Description

The Beacon API endpoint at `/eth/v1/events` always emits an error event after about 2 minutes, and then stops emitting anything while keeping the connection alive.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: v2.0.6

## 🔬 Minimal Reproduction

Prysm: v2.1.0
Network: prater

Request:
```
GET /eth/v1/events?topics=head
```

Response:
```
event: head
data: ...

event: head
data: ...

<a few more valid head events>

event: error
data: {"status_code":504,"message":"context deadline exceeded"}

<connection still alive, no more head events>
```

## 🔥 Error

Nothing that I could find in the logs, unfortunately.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.1.0
  </code>
</pre>

**Comment by moshe-blox** [comment]
[This commit](https://github.com/prysmaticlabs/prysm/commit/1c2e463a30aaab10d312edf708d9f4713af89908) introduced a 120s default API timeout, which applies for`/eth/v1/events` as well.

Could setting the `Grpc-Timeout` header to 0 in [this HTTP request](https://github.com/prysmaticlabs/prysm/blob/1c2e463a30aaab10d312edf708d9f4713af89908/beacon-chain/rpc/apimiddleware/custom_handlers.go#L189) help?

**Comment by rauljordan** [comment]
Thanks for the report @moshe-blox, tagging @rkapka to help find a good path forward on this one. I don't think setting the timeout in that specific line would help, but rather we could add change the function where we add the 2 min timeout:
```go
func (m *ApiProxyMiddleware) ProxyRequest(req *http.Request) (*http.Response, ErrorJson)
```
to instead have some ugly conditional check for the `events` endpoint, and add a timeout of 0 if that's the case. Alternatively, we could check if the request headers include the event-stream header and do that instead, as that might be more reliable

**Comment by rauljordan** [comment]
I still got the deadline when modifying the code like this:
```go
// ProxyRequest proxies the request to grpc-gateway.
func (m *ApiProxyMiddleware) ProxyRequest(req *http.Request) (*http.Response, ErrorJson) {
	// In case we are proxying event stream requests, we do not set an HTTP timeout.
	timeout := m.Timeout
	if req.Header.Get("Content-Type") == "text/event-stream" {
		timeout = time.Duration(0)
	}
```
Maybe i need to do the same in multiple places of the api middleware?

**Comment by rkapka** [comment]
The reason why this change does not work is because the grpc-gateway server still times out.
https://github.com/prysmaticlabs/prysm/blob/16bbf5602fc1b0756c4e2e61cfcb220a85de117b/api/gateway/options.go#L87-L93
From the perspective of Beacon APIs, we can remove this part because grpc-gateway endpoints are marked as `/internal`. But from the perspective of Prysm APIs, this will make the `--api-timeout` flag not do anything, because Prysm APIs rely solely on grpc-gateway. To resolve this we can potentially register two grpc-gateway servers, one for each API.
