### ISSUE TITLE
v2.1.0 endpoint connection error

### ISSUE THREAD

**Issue by Lex1559** [prysmaticlabs/prysm#10596]
#10596 🐞 Bug Report

### Description

Series of powchain errors since relaunching Prysm version v2.1.0. When the local geth client is stopped attempts to connect to infura results in a runtime error.

 

###  

Yes, the previous version in which this bug was not present was: v2.0.6 

## 🔬 Minimal Reproduction

Ran ./prysm.sh beacon-chain --http-web3provider=/Users/lex/Mainnet/geth.ipc  --fallback-web3provider=https://mainnet.infura.io/v3/***

## 🔥 Error

ERROR powchain: Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: Post "https://mainnet.infura.io/v3/***: dial tcp: lookup mainnet.infura.io: no such host

ERROR powchain: Could not connect to execution client endpoint: could not dial execution node: dial unix /Users/lex/Mainnet/geth.ipc: socket: too many open files

**When local geth client is stopped**

ERROR powchain: Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: Post "https://mainnet.infura.io/v3/**": x509: certificate signed by unknown authority

ERROR powchain: Could not connect to execution endpoint error=dial unix /Users/lex/Mainnet/geth.ipc: connect: no such file or directory
could not dial execution node
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).setupExecutionClientConnections
	beacon-chain/powchain/rpc_connection.go:22
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
	beacon-chain/powchain/service.go:229
runtime.goexit
	src/runtime/asm_amd64.s:1581
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4add812]

goroutine 262 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initPOWService(0xc000223110)
	beacon-chain/powchain/service.go:565 +0xb2
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc000223110, 0xc0000a8480)
	beacon-chain/powchain/service.go:617 +0x89
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
	beacon-chain/powchain/service.go:254 +0x4b1

## 🌍  Your Environment

macOS Monterey 12.1 on an M1 Mac mini

**What version of Prysm are you running? (Which release)**

Prysm/v2.1.0/72562dcf3ad8205e8576346665b3a5c8d9fd9c08

**Anything else relevant (validator index / public key)?**

Running local geth client but no validator 
![Screenshot 2022-05-01 at 20 14 00](https://user-images.githubusercontent.com/94316627/166161670-867668fc-fa26-4dee-9f2f-766b115cb87f.png)

**Comment by nisdas** [comment]
@Lex1559 #10574 should fix this, we will most likely be having our new release today/tomorrow with the patch.

**Comment by rkapka** [comment]
Hi @Lex1559 , does this issue still appear in newer releases?

**Comment by Lex1559** [comment]
Hey @rkapka all good now thanks. This issue was fixed with the subsequent release. Currently running Geth 1.10.19 and Prysm/v2.1.2/e33850bf51e3a6e9bbf93e8ef799bff1d5e33f32 and haven't had this issue since.
