### ISSUE TITLE
Support builder spec

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10593]
## Background
We want to support builder spec v0.2.1. The builder API will be implemented by both EL and CL clients that wish to participate in a builder network. Large number of validators will rely on this interface to extract MEV so it's important CLs integrate this spec. Without it, it could affect network share negatively as validators will seek to CL clients with better economics 

##  Requirements

- [x] New builder service
    - [x] http client to call builder api
- [ ] Add builder healthz monitoring
    - [ ] Other services should aware when a builder is down
    - [ ] Poll `builder_status`
- [x] Implement builder APIs
    - [x] `builder_status`
    - [x] `builder_registerValidatorV1`
        - [x] beacon node support
        - [x] validator client support
    - [x] `builder_getHeaderV1`
    - [x] `builder_getPayloadV1`
- [ ] Utililize parallsell calls to `engine_getPayload` and `builder_getHeaderV1` for fallback
- [x] Disallow builder usage until first finalized epoch post TTD
- [ ] Add new cli endpoint to specify builder endpoint
- [ ] Enhanced loggings
- [ ] Enhance metrics
- [ ] Validate `SignedBuilderBid`
- [ ] Log and check MEV rewards 
- [ ] How should we prune registration objects in DB?

### Beacon Node
- [x] support new Beacon API  https://github.com/ethereum/beacon-APIs/pull/209

### Validator Client
- [x] support new Beacon API https://github.com/ethereum/beacon-APIs/pull/209
- [x] Must provide signed data (should cache them to avoid resigning every epoch). Related ref: https://github.com/ethereum/consensus-specs/pull/2884Reference: https://github.com/ethereum/execution-apis/pull/209
- [ ] Update proposer settings file to mirror [teku PR](https://hackmd.io/@StefanBratanov/BkMlo1RO9), [teku PR2](https://github.com/ConsenSys/teku/pull/5860)

**Comment by james-prysm** [comment]
## Open questions
-  how do we want to support web3signer/remote signer on this new API
- what new CLI flags are we adding to support this feature?
- how do we want to pass this new information to our service? 
- should we extend our existing fee recipient flags/json interface or introduce new flags to handle additional information needed.
