### ISSUE TITLE
Checkpoint Sync node version parsing fails on other beacon node API implementations

### ISSUE THREAD

**Issue by kasey** [prysmaticlabs/prysm#10617]
# 🐞 Bug Report

### Description

Checkpoint Sync needs to fetch a state by slot from the remote beacon node. The previous version of prysm had a bug where it was not running process_slots when retrieving a state by slot, so those older versions are incompatible. We use the beacon node api `/eth/v1/node/version` api to figure out if the remote node is compatible. The problem is, the regex to detect prysm versions is too restrictive and fails to parse version strings for nimbus, teku and lighthouse. We need to loosen it up to ignore everything after the initial client name and semver.

### Has this worked before in a previous version?
no

## 🔬 Minimal Reproduction
attempt to run `go run github.com/prysmaticlabs/prysm/cmd/prysmctl cpt latest --beacon-node-host=<lighthouse|nimbus|teku url>`. Observe an error like ```
unable to proceed with fallback method without confirming node version: could not be parsed: ... ```

## 🔥 Error

:point_up: 

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

`v2.1.1`

**Comment by jclapis** [comment]
For reference, here is a string from Nimbus which causes the `invalid node version response` error when checkpoint syncing (taken from curling `/eth/v1/node/version`):
`{"data":{"version":"Nimbus/v22.4.0-039bec-stateofus"}}`
