### ISSUE TITLE
Checksum to fee recipient address

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10631]
It might be useful to validate the fee recipient address for checksum as defined in eip55. The client should warn or error out if the checksum fails 

Reference: https://eips.ethereum.org/EIPS/eip-55

**Comment by prestonvanloon** [comment]
If we implement it, this should warn or error at startup and should not hinder any block proposals.

**Comment by james-prysm** [comment]
I tested with common.HextoAddress() function that we use and it makes even invalid checksummed values i.e. 0xae967917c465db8578ca9024c205720b1a3651A9 into 
valid ones i.e. 0xAe967917c465db8578ca9024c205720b1a3651A9
my question is are those 2 addresses different? 🤔  I thought it would be the same...

**Comment by james-prysm** [comment]
> > my question is are those 2 addresses different? 🤔 I thought it would be the same...
> 
> They are different. https://coincodex.com/article/2078/ethereum-address-checksum-explained/

ah ok let me refactor to do the check before the to address function then and add tests.
