### ISSUE TITLE
Instructions for Setting Up Local Test Network

### ISSUE THREAD

**Issue by mrihn** [prysmaticlabs/prysm#10695]
Are there instructions for bringing up a local test network?

I only see instructions for running a validator on the Mainnet or Prater testnet in the official documentation, but some older issues discuss building a local testnet. Is this still possible/supported with the latest version?

**Comment by xihucuyu888** [comment]
any updates?

**Comment by rauljordan** [comment]
hi @xihucuyu888 and @mrihn apologies for the huge delay on this, but we now have fully functional instructions to do this [here](https://www.notion.so/prysmaticlabs/PUBLIC-DOC-Configuring-a-Local-Prysm-Development-Network-a2e7ba2e28694778aac86c5a420b2fab). Please let us know if you run into any problems. You can talk to our team on Discord [here](https://discord.gg/prysmaticlabs) or reply in this closed Github issue

**Comment by xihucuyu888** [comment]
https://github.com/rauljordan/eth-pos-devnet
