### ISSUE TITLE
BeaconAPI endpoint conformance issues.

### ISSUE THREAD

**Issue by z3n-chada** [prysmaticlabs/prysm#10725]
# 🐞 Bug Report

### Description
There are several beaconAPI endpoints where prysm deviates from the [spec](https://ethereum.github.io/beacon-APIs/). 

### Has this worked before in a previous version?

Unsure

## 🔬 Minimal Reproduction

To reproduce get a synced node and query the BeaconAPI with expected input unless otherwise specified. (note for all tests CL fork version was bellatrix)

### Issues with responses:
| API Path                         | Inputs | Issue                                |
|:-------------------------------- |:------ |:------------------------------------ |
| /eth/v1/node/syncing             | None   | no is_optimistic field in response   |
| /eth/v1/node/identity            | None   | metadate field lacks a syncnet field |
| /eth/v2/beacon/blocks/{block_id} | "head" | No execution_optimistic field        |

### Issues with status codes:
In the {block_id} and {state_id} requests, if we give a slot in the future we would expect to see a 404 instead of a 500 status code.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
prysm-devel (unknown commit hash, at the time or writing the version will be less than a week old)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by Faraj1** [comment]
Hi

**Comment by james-prysm** [comment]
I believe these have been resolved
