### ISSUE TITLE
Implement Block Operations in Spec

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1073]
Hi all,

This is a tracking issue to implement the block operations as defined in the current spec [here](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#block-operations). This can be split into separate PRs implementing each section including `casper slashing`, `proposer slashing`, and more.

I will begin with the proposer slashing conditions.

**Comment by nisdas** [comment]
@rauljordan Can we close this ?

**Comment by rauljordan** [comment]
#1104 will resolve it
