### ISSUE TITLE
REST interface does not return SSZ when requested with `Accept` header

### ISSUE THREAD

**Issue by arnetheduck** [prysmaticlabs/prysm#10743]
### Description

The following request should return SSZ (because of the [higher priority](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) of `application/octet-stream`), but returns JSON instead:

```
curl -H "Accept: application/octet-stream,application/json;q=0.9" http://localhost:3500/eth/v2/debug/beacon/states/head
```

Prysm version 2.1.2 (following user report - Nimbus uses accept headers to sync more efficiently when possible / supported)

**Comment by rkapka** [comment]
https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Debug/getDebugChainHeadsV2 does not have a `application/octet-stream` media type.

**Comment by arnetheduck** [comment]
This issue is in relation to https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#%2FDebug%2FgetStateV2=

**Comment by rkapka** [comment]
Oh, it's `/state/head`, not `/heads`. My bad.
