### ISSUE TITLE
API Middleware/ gRPC gateway handling custom http response codes

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#10745]
# 🚀 Feature Request

### Description
With more Rest based API integrations added to Prysm we need more flexibility with our API middleware/gRPC gateway setup. Currently, our API Middleware/ gRPC gateway setup doesn't allow us to return custom codes for successes (so only 200 ok) 

these are the [current mappings](https://github.com/grpc-ecosystem/grpc-gateway/blob/22a95e12d5f30a61979d8b1c12d4d319232b2ac9/runtime/errors.go#L36)
Ideally, we would like a way to override this for more custom codes such as 202 on our API returns. 

some examples where this is used.

1. [keymanager api set fee recipient](https://github.com/ethereum/keymanager-APIs/blob/master/apis/fee_recipient.yaml)
2. [blinded_block](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlindedBlock)

### Describe the solution you'd like
we should provide a way to customize a new gRPC option for custom returns
https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#controlling-http-response-status-codes

**Comment by rkapka** [comment]
Closed with https://github.com/prysmaticlabs/prysm/pull/10850
