### ISSUE TITLE
how to start ropsten beacon chain

### ISSUE THREAD

**Issue by masayil** [prysmaticlabs/prysm#10759]
**Prater** testnet needs to download genesis.ssz.Does **Ropsten** need to do this？Or just add `--ropsten`?
My command( just add --ropsten):`/root/ropsten-beacon/beacon-chain-v2.1.3-rc.0-linux-amd64 --http-web3provider=http://192.168.7.35:8551 --jwt-secret=/root/ropsten-beacon/jwtsecret --monitoring-port 17070 --ropsten --rpc-host '0.0.0.0' --grpc-gateway-host '0.0.0.0' --datadir=/root/ropsten-beacon/node --accept-terms-of-use=true`
log output：I think it's normal!
![image](https://user-images.githubusercontent.com/65291464/170481558-6738e985-d864-44cd-8768-b24a1d6b6299.png)

**Comment by prestonvanloon** [comment]
Please see the documentation https://docs.prylabs.network/docs/next/install/install-with-script/#step-4-run-a-beacon-node-using-prysm

You do need a genesis ssz file

**Comment by masayil** [comment]
> Please see the documentation https://docs.prylabs.network/docs/next/install/install-with-script/#step-4-run-a-beacon-node-using-prysm
> 
> You do need a genesis ssz file

thanks.I think it's normal!
![image](https://user-images.githubusercontent.com/65291464/170486955-246f5146-1f94-4045-9544-b1f3215c4269.png)
