### ISSUE TITLE
Could not log ttd due to empty hex string

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10790]
```
[2022-05-30 08:00:58] ERROR powchain: Could not log ttd status error=got an unexpected error in JSON-RPC response: empty hex string
```

To reproduce:
- EL client is syncing so it may not know what is the latest TD
- CL client has not passed Bellatrix epoch or the latest TTD has not reached
- CL will then request the latest TD from EL in an attempt to log TTD progress

![Screen Shot 2022-05-30 at 4 36 22 PM](https://user-images.githubusercontent.com/21316537/171068394-ccb51b60-8cdc-47c3-834e-72389706cc43.png)
![Screen Shot 2022-05-30 at 4 36 10 PM](https://user-images.githubusercontent.com/21316537/171068408-7caec5a7-7aee-413c-8d47-0c968476da1b.png)

**Comment by prestonvanloon** [comment]
How can this be reproduced?

**Comment by terencechain** [comment]
> How can this be reproduced?

Hi, I updated the steps to reproduce. Sorry I should have done this earlier but I forgot
