### ISSUE TITLE
E2E flaking with aggregate bitvector

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#10796]
# 🐞 Bug Report

### Description
Validator Participation tests in E2E are failing due to not enough validators participating caused by a flaky error

### Has this worked before in a previous version?

Was also flaking I believe.

## 🔬 Minimal Reproduction

Running web3signer E2E sometimes produces this error same with minimal E2E test.

## 🔥 Error

<pre><code>
 assertions.go:86: endtoend_test.go:167 Evaluation failed for epoch 7: In block of slot 42 ,the aggregate bitvector with length of 31 only got a count of 30: In block of slot 42 ,the aggregate bitvector with length of 31 only got a count of 30
</code></pre>

## 🌍  Your Environment

CI/CD on buildkite

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
2.1.2
  </code>
</pre>

**Comment by rauljordan** [comment]
I don't think we've seen this one for a very long time and perhaps was resolved? Will close for now
