### ISSUE TITLE
Clients Can Join the Network, Sync, and Propagate Messages

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#108]
This is a mega issue and might need to be broken up into smaller tasks.

- [x] Clients can join the network
- [x] Clients can sync collations
- [x] Clients propagate messages
- [ ] Clients are selective about their peers (torus network?)
- [x] p2p messages are defined

TODO: Add more tasks to the list above and/or break into smaller issues. 

We had some discussion in #72, but bumped it to Sapphire. I still agree with this since the purpose of this issue is to have some minimal and mostly local example of syncing with actors communicating over some network. A full implementation for Sapphire includes peer discovery and many other tasks.

**Comment by rauljordan** [comment]
Best places to start are in defining the barebones p2p messages + the initial join/handshake as PR's @prestonvanloon

**Comment by prestonvanloon** [comment]
Yes. I'll flush this out in a design, but those are probably the best places to start based on the exploration I have done so far.

**Comment by prestonvanloon** [comment]
The immediate goal is to add this to the service registry to start P2P and outline a basic interface for interaction with other services.

**Comment by prestonvanloon** [comment]
I will update after #222 is merged.

**Comment by rauljordan** [comment]
Update on this @prestonvanloon ?

**Comment by rauljordan** [comment]
Bump @prestonvanloon

**Comment by prestonvanloon** [comment]
Thanks I've updated based on the p2p PR merged.

I haven't been able to get syncing to work successfully yet so I won't mark that box as complete. 
The p2p messages are currently defined as protobufs but we are still exploring whether this is the best solution. See #150

**Comment by terenc3t** [comment]
@prestonvanloon Can we close this yet?

**Comment by prestonvanloon** [comment]
Closing stale issue
