### ISSUE TITLE
could not prune fork choice nodes: unknown finalized root

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10826]
I saw the following error from latest develop: `2536195be0b5c84b544b165630c28229e12ee45a`:  `{"error":"could not process block in batch: could not prune fork choice nodes: unknown finalized root","message":"Batch is not processed","prefix":"initial-sync","severity":"WARNING"}`

Maybe we missed a case where `fCheckpoint == s.store.finalizedCheckpoint`, we may want to revisit the case where `fCheckpoint` is older than `s.store.finalizedCheckpoint` in blockcahin service

This error is mainly cosmetic, the node doesn't get stuck because even though it failed to process the batch, it indeed managed to insert them all and continues syncing

**Comment by rauljordan** [comment]
Hi @terencechain still an issue?

**Comment by potuz** [comment]
This was fixed in 2.1.4rc0
