### ISSUE TITLE
"Could not connect to execution endpoint" when run prysm with geth on ropsten

### ISSUE THREAD

**Issue by shiziwen** [prysmaticlabs/prysm#10844]
When I run the prysm node on ropsten, I got:
```
level=error msg="Could not connect to execution endpoint" error="could not make initial request to verify execution chain ID: chain not synced beyond EIP-155 replay-protection fork block" prefix=powchain
```

For the EL, I use geth with the config `--authrpc.port 9551 --authrpc.vhosts localhost --authrpc.jwtsecret /data1/ropsten/jwtsecret`, and `--accept-terms-of-use=true --http-web3provider=http://localhost:9551 --ropsten --jwt-secret=/data1/ropsten/jwtsecret` for prysm.

**Comment by shiziwen** [comment]
The prysm version is v2.1.3-rc.2.

**Comment by shiziwen** [comment]
May be it is related to https://github.com/ethereum/go-ethereum/issues/22729, so I may need to wait util the geth node sync to the latest data.

**Comment by rauljordan** [comment]
Hi @shiziwen do you still have this problem?
