### ISSUE TITLE
Kubernetes liveness/readiness probe

### ISSUE THREAD

**Issue by srinathanand** [prysmaticlabs/prysm#10870]
# General Question/Issue

### Background
Kubernetes liveness/readiness probe

### Description
Is there a liveness/readiness probe that can be defined when running the `prysmaticlabs/prysm/beacon-chain` docker image in a Kubernetes cluster?

**Comment by nisdas** [comment]
cc @prestonvanloon @Taranpreet26311

**Comment by srinathanand** [comment]
Thanks @prestonvanloon
