### ISSUE TITLE
Prysm can't connect to go-ethereum's engine API

### ISSUE THREAD

**Issue by sokiaoba** [prysmaticlabs/prysm#10911]
### Description

After I upgraded go-ethereum nodes to the newest version [Camaron (v1.10.19)](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.19), prysm-beacon-node stopped connecting to go-ethereum.

My speculation is, this is specifically related to Cameron's breaking change below.

```
The engine API is now only available with JWT authentication.
```

But something I don't really understand is that since I set jwt-secret for both go-ethereum & prysm-beacon-node, 
I thought all api calls from prysm-beacon-node to go-ethereum are supposed to be authenticated with jwt.

(please tell me if this issue is supposed to be in go-ethereum's repository)

### Has this worked before in a previous version?

It worked fine with [go-ethereum@v1.10.18](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.18)

## 🔬 Minimal Reproduction

Basically the same settings as https://notes.ethereum.org/@launchpad/ropsten#Prysm.

## 🔥 Error

```
geth-ropsten-fast-1-cd94d4cf-qdlsv geth WARN [06-21|07:16:05.612] Served engine_exchangeTransitionConfigurationV1 conn=[::1]:45362 reqid=5    duration="26.301µs" err="the method engine_exchangeTransitionConfigurationV1 does not exist/is not available"
geth-ropsten-fast-1-cd94d4cf-qdlsv beacon-node time="2022-06-21 07:16:05" level=error msg="Could not check configuration values between execution and consensus client" error="method not found" prefix=powchain
```

## 🌍  Your Environment

* environment: azure kubernetes service
* geth: [Camaron (v1.10.19)](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.19)
* prysm-beacon-node: [latest](https://hub.docker.com/layers/prysm-beacon-chain/prysmaticlabs/prysm-beacon-chain/latest/images/sha256-5f3c44d44ffc5d668713d55d88d73b93d23868c81594784f35f953992c141daf?context=explore)

**Comment by nisdas** [comment]
Hey @sokiaoba , which flags are you running prysm with ?

**Comment by nisdas** [comment]
`   - '--http-web3provider=http://localhost:8545'`
This wont work, change this to 
`   - '--http-web3provider=http://localhost:8551'`
instead

**Comment by sokiaoba** [comment]
Got it. I'll try.

**Comment by sokiaoba** [comment]
@nisdas It seems the error was solved. Thank you.
