### ISSUE TITLE
Cannot build Prysm from source on Amazon Linux2

### ISSUE THREAD

**Issue by KenKoide** [prysmaticlabs/prysm#10922]
# 🐞 Bug Report

### Description

Cannot build Prysm from source on Amazon Linux2.

### Has this worked before in a previous version?

 
This is my first time building Prysm.
'gmp' is installed.
'gmpxx.h' is not found in find.

```
[ prysm (v2.1.2) ] sudo yum install gmp
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package 1:gmp-6.0.0-15.amzn2.0.2.x86_64 already installed and latest version
Nothing to do

[ prysm (v2.1.2) ] sudo find / -name gmpxx.h
[ prysm (v2.1.2) ] 
```

## 🔥 Error

<pre><code>

[ prysm (v2.1.2) ] ~/node_modules/.bin/bazel build //beacon-chain:beacon-chain --config=release
DEBUG: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False' 
DEBUG: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False' 
DEBUG: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
WARNING: /home/ec2-user/pkg-eth-docker/moneta-prysm/prysm/beacon-chain/BUILD.bazel:3:14: target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class javax.net.ssl.SSLHandshakeException Remote host terminated the handshake
DEBUG: Rule 'vaticle_bazel_distribution' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1646647146 +0000"
DEBUG: Repository vaticle_bazel_distribution instantiated at:
  /home/ec2-user/pkg-eth-docker/moneta-prysm/prysm/WORKSPACE:354:11: in <toplevel>
  /home/ec2-user/pkg-eth-docker/moneta-prysm/prysm/deps.bzl:4643:10: in prysm_deps
  /home/ec2-user/pkg-eth-docker/moneta-prysm/prysm/tools/go/def.bzl:61:18: in maybe
Repository rule git_repository defined at:
  /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //beacon-chain:beacon-chain (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Generating into bazel-out/k8-opt/bin/proto/eth/v1/go_proto_/github.com/prysmaticlabs/prysm/proto/eth/v1:
2022/06/23 07:33:50 grpc
2022/06/23 07:33:50 Casting for 4 extensions: cast_type, ssz_size, ssz_max, spec_name
INFO: From Generating into bazel-out/k8-opt/bin/proto/eth/service/go_proto_/github.com/prysmaticlabs/prysm/proto/eth/service:
2022/06/23 07:33:50 grpc
2022/06/23 07:33:50 Casting for 5 extensions: http, cast_type, ssz_size, ssz_max, spec_name
INFO: From Generating into bazel-out/k8-opt/bin/proto/eth/v2/go_proto_/github.com/prysmaticlabs/prysm/proto/eth/v2:
2022/06/23 07:33:50 grpc
2022/06/23 07:33:50 Casting for 4 extensions: cast_type, ssz_size, ssz_max, spec_name
ERROR: /home/ec2-user/.cache/bazel/_bazel_ec2-user/3ef682185c64f618e776054f0cc21c1b/external/herumi_mcl/BUILD.bazel:78:10: Compiling src/gen.cpp [for host] failed: (Exit 1): clang failed: error executing command external/llvm_toolchain/bin/clang -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/herumi_mcl/src/gen.cpp:3:
In file included from external/herumi_mcl/include/mcl/op.hpp:9:
external/herumi_mcl/include/mcl/gmp_util.hpp:37:10: fatal error: 'gmpxx.h' file not found
#include <gmpxx.h>
         ^~~~~~~~~
1 error generated.
Target //cmd/beacon-chain:beacon-chain failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.216s, Critical Path: 1.48s
INFO: 32 processes: 21 internal, 11 linux-sandbox.
FAILED: Build did NOT complete successfully
[ prysm (v2.1.2) ] 
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Amazon Linux2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.1.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
Hey have you looked at our building from source guide ?
https://docs.prylabs.network/docs/install/install-with-bazel . Let us know if this still doesn't work.

**Comment by KenKoide** [comment]
Of course!
Nice document.

Most of the problems were solved with the documentation.
Only this error is troubling me.

**Comment by nisdas** [comment]
And just to confirm you installed this ? `libgmp-dev` . If that is the case this is an odd error.

**Comment by KenKoide** [comment]
I'm having trouble with "No package."
```
[ prysm (v2.1.2) ] sudo yum install libgmp-dev
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
No package libgmp-dev available.
Error: Nothing to do
[ prysm (v2.1.2) ] 
```

**Comment by nisdas** [comment]
I see that you are using Amazon's version of Linux, this only works on debian/ubuntu. It seems that their version of linux is based on rhel. In that case try this: https://pkgs.org/download/gmp-devel . `sudo yum install  gmp-devel`

**Comment by KenKoide** [comment]
Thank you, nisdas SAN!

I have moved on. I'm still getting errors on the next one, though (lol)

**Comment by KenKoide** [comment]
All the builds came through!
Thanks for the support!

```
INFO: Analyzed target //beacon-chain:beacon-chain (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Compiling src/asm/x86-64.s:
clang: warning: argument unused during compilation: '-U _FORTIFY_SOURCE' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fstack-protector' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fno-omit-frame-pointer' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fcolor-diagnostics' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-D _FORTIFY_SOURCE=1' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-D NDEBUG' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-ffunction-sections' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fdata-sections' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-D __DATE__="redacted"' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-D __TIMESTAMP__="redacted"' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-D __TIME__="redacted"' [-Wunused-command-line-argument]
INFO: From GoCompilePkg external/com_github_ethereum_go_ethereum/crypto/secp256k1/secp256k1.a:
prysm/external/com_github_ethereum_go_ethereum/crypto/secp256k1/secp256.go:28:9: warning: 'NDEBUG' macro redefined [-Wmacro-redefined]
#define NDEBUG
        ^
<command line>:3:9: note: previous definition is here
#define NDEBUG 1
        ^
1 warning generated.
Target //cmd/beacon-chain:beacon-chain up-to-date:
  bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain
INFO: Elapsed time: 197.062s, Critical Path: 46.62s
INFO: 796 processes: 3 internal, 793 linux-sandbox.
INFO: Build completed successfully, 796 total actions
[ prysm (v2.1.2) ] 
```

**Comment by nisdas** [comment]
Great ! In that case I am closing this issue unless you have some other issues with building prysm.
