### ISSUE TITLE
chain not synced beyond EIP-155 replay-protection fork block

### ISSUE THREAD

**Issue by Duanraudon** [prysmaticlabs/prysm#10948]
# 💎 Issue

### Background

When I use geth as the execution layer and prysm as the consensus layer to synchronize ropsten, the prysm log always shows the following information, how can I solve this?

### Description

prysm log:

y execution chain ID: chain not synced beyond EIP-155 replay-protection fork block" prefix=powchain
time="2022-06-29 09:03:40" level=info msg="Peer summary" activePeers=43 inbound=0 outbound=43 prefix=p2p
time="2022-06-29 09:04:40" level=info msg="Peer summary" activePeers=44 inbound=0 outbound=44 prefix=p2p
time="2022-06-29 09:05:10" level=error msg="Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: chain not synced beyond EIP-155 replay-protection fork block" prefix=powchain
time="2022-06-29 09:05:40" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
time="2022-06-29 09:06:40" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
time="2022-06-29 09:07:25" level=error msg="Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: chain not synced beyond EIP-155 replay-protection fork block" prefix=powchain
time="2022-06-29 09:07:40" level=info msg="Peer summary" activePeers=46 inbound=0 outbound=46 prefix=p2p
time="2022-06-29 09:08:40" level=info msg="Peer summary" activePeers=45 inbound=0 outbound=45 prefix=p2p
time="2022-06-29 09:09:40" level=error msg="Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: chain not synced beyond EIP-155 replay-protection fork block" prefix=powchain

geth log:

INFO [06-29|09:21:31.705] State sync in progress                   synced=70.95% state=41.74GiB accounts=230,697,717@6.41GiB slots=137,811,744@28.65GiB codes=1,267,483@6.67GiB  eta=6h0m43.915s
WARN [06-29|09:21:31.724] Unexpected storage ranges packet         peer=fa48a39c reqid=884,142,286,406,892,604
WARN [06-29|09:21:31.747] Unexpected bytecode packet               peer=0324bf10 reqid=6,616,886,557,082,279,966
WARN [06-29|09:21:31.775] Unexpected storage ranges packet         peer=139fa632 reqid=6,946,866,827,372,460,977
WARN [06-29|09:21:31.777] Unexpected storage ranges packet         peer=b0445182 reqid=6,785,834,559,659,889,227
WARN [06-29|09:21:31.785] Unexpected bytecode packet               peer=b878346f reqid=2,028,403,797,080,305,194
WARN [06-29|09:21:31.810] Unexpected storage ranges packet         peer=b878346f reqid=3,442,446,758,154,841,945
WARN [06-29|09:21:31.819] Unexpected storage ranges packet         peer=0324bf10 reqid=8,263,225,426,604,513,194
INFO [06-29|09:21:33.176] Disabling direct-ancient mode            origin=12,350,646 ancient=11,370,495
INFO [06-29|09:21:34.021] Imported new block headers               count=0    elapsed=8.602ms     number=12,350,712 hash=d3a581..1b1f0c age=2w6d9h     ignored=66
INFO [06-29|09:21:34.022] Legacy sync reached merge threshold      number=12,350,713 hash=4e8451..5809f6 td=50,001,647,293,494,169 ttd=50,000,000,000,000,000
INFO [06-29|09:21:34.259] State sync in progress                   synced=70.95% state=41.74GiB accounts=230,714,828@6.41GiB slots=137,811,744@28.65GiB codes=1,267,483@6.67GiB  eta=6h0m41.362s

start command：

version: "3"
services:
  prysm:
    image: gcr.dockerproxy.com/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.4
    container_name: ropsten-prysm-test
    restart: unless-stopped
    command: --datadir=/prysm-data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --http-web3provider=http://ropsten:8545 --jwt-secret=/ropsten-data/geth/jwtsecret --genesis-state=/prysm-data/genesis.ssz --ropsten --accept-terms-of-use
    ports:
      - 3500:3500
      - 4000:4000
      - 13000:13000
      - 12000:12000/udp
    volumes:
      - ./ropsten-data:/ropsten-data
      - ./prysm-data:/prysm-data
      - /etc/localtime:/etc/localtime
    depends_on:
      - "ropsten"
  ropsten:
    image: ethereum/client-go:v1.10.19
    container_name: ropsten-test
    restart: unless-stopped
    command: --syncmode snap --datadir=/ropsten-data --ropsten --ws --ws.port 8545 --ws.api eth,net,web3,erigon,debug,ots,engine --ws.origins "*" --ws.addr 0.0.0.0 --http --http.api eth,net,web3,erigon,debug,ots,engine --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.vhosts "*"
    volumes:
      - ./ropsten-data:/ropsten-data
      - /etc/localtime:/etc/localtime
    ports:
      - 8545:8545
      - 30303:30303

**Comment by Duanraudon** [comment]
I feel that this problem should be caused by the too low version of Ethereum in go.mod

**Comment by imnotanoob** [comment]
Were you ever able to figure this out?

**Comment by prestonvanloon** [comment]
Some RPC requests will fail with this error when go-ethereum has not synced beyond block 2,675,000
