### ISSUE TITLE
Register large number of validators: context deadline exceeded

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10949]
Observed in the Kiln cluster- when registering a large number of validator keys, the following error occurred, and not all the validators / only partial validators got registered. I'm not sure how many keys we hold per pod
```
{"message":"Failed to update proposer settings: could not submit signed registrations to beacon node: rpc error: code = DeadlineExceeded desc = context deadline exceeded","prefix":"validator","severity":"WARNING","slot":787712}
```

**Comment by terencechain** [comment]
We run 1k keys per validator client

**Comment by james-prysm** [comment]
This is a great point will try to work on API threshholds we can break it up into chunks if it's too big

**Comment by prestonvanloon** [comment]
What is the deadline and what are the expensive parts of the process? Could it be optimized or parallelized in some way to reduce the total time?

**Comment by james-prysm** [comment]
> What is the deadline and what are the expensive parts of the process? Could it be optimized or parallelized in some way to reduce the total time?

right now it's set at the slot deadline
client/validator.go line 960
```
deadline := v.SlotDeadline(slots.RoundUpToNearestEpoch(slots.CurrentSlot(v.genesisTime)))
	ctx, cancel := context.WithDeadline(ctx, deadline)
``` 
perhaps this isn't correct?

we can bundle this and call the api multiple times in blocks instead of all in the same API, what do you think Preston.
```

	if _, err := validatorClient.SubmitValidatorRegistration(ctx, &ethpb.SignedValidatorRegistrationsV1{
		Messages: signedRegs,
	});
```
it's just a list of messages at the end of the day.
