### ISSUE TITLE
Can we have a metric for effectiveness? 

### ISSUE THREAD

**Issue by dharmendrakariya** [prysmaticlabs/prysm#10983]
# 🚀 Feature Request

Can we have a metric for Validator Effectiveness?

### Description

I want to track all my validator's effectiveness! for that we need a metric! we can build histogram or something in Grafana!

Right now we are keeping track of our effectiveness by looking at the below site! but we have more than 3500+ validators and thats not easy for us to keep track of our validators' performance!
https://beacon.gnosischain.com/validator/8e9a7220e7ccbd936b2956a0547cb2378028110eb2b6dc99c47890bce8ba1e11703185440856b6753bb5d2591517e875

### Describe the solution you'd like

I want something in grafana (obviously with the help of prometheus metrics) to see the validator's performance!

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

yes! something like this but I am not sure if this is the actual effectiveness or not! also I wan to have all my validator's effectiveness! perhaps we can build histogram or something out of them!
![image](https://user-images.githubusercontent.com/22043860/177206739-a8ae41bc-cead-4520-81dd-6adac37608ed.png)

**Comment by potuz** [comment]
You would be better off not following effectiveness. This measure has little to no connection to the actual validator performance. As an example: a validator that has missed **all of the attestations** from the last 100 epochs, except one of them, that was incldued in the very next slot, will report itself as effectiveness 100% in beaconcha.in.

**Comment by dharmendrakariya** [comment]
Are you talking about the query I wrote or in general effectiveness metric? if so, what would be the better approach to get the performance track?

**Comment by nisdas** [comment]
@potuz I am guessing the validator monitor would be much more effective here, correct ?

**Comment by potuz** [comment]
The validator monitor gives you a ton of information. What the user does with it is a different story. Users want a single measurement that represents performance, but unfortunately that's not an easy thing to define. There have been a few attempts at this and not one has been successful.

**Comment by nisdas** [comment]
In that case, @dharmendrakariya can use the monitor metrics instead ? They just need to track the `timely_head` metric, and observe how many times it is missed. The `effectiveness` metrics from beaconcha.in is a poor gauge anyway. this would be more accurate.

**Comment by potuz** [comment]
If they want to reproduce the effectiveness measure from beaconcha.in they can too via the validator monitor since it includes the inclusion distance

**Comment by dharmendrakariya** [comment]
sorry but how can we enable validator monitor? perhaps this https://docs.prylabs.network/docs/prysm-usage/individual-validator-monitoring ? also if we give extra flags and restart the container, would it cause any problem? I guess no , right?

**Comment by dharmendrakariya** [comment]
I am again afraid that this won't solve our problem in the first place! cause we have large number of validators and we want to track effectiveness(lets say inclusion distance) for all of them! neither scraping that data nor getting all of them on grafana dashboard will be easy I am guessing! what you think? any way would you suggest? perhaps, could you include ```inclusion distance``` as a metrics! I heard from use that lighthouse has one of a kind!

**Comment by dharmendrakariya** [comment]
alright! will give it a shot and let you know! thanks for all the support and instant response! :)

**Comment by potuz** [comment]
If you do test it and you find anything that you would want to change/add, please do comment it in https://github.com/prysmaticlabs/prysm/issues/10147, I'll be happy to add it.

**Comment by rauljordan** [comment]
hi @dharmendrakariya can we close this issue in favor of #10147?

**Comment by dharmendrakariya** [comment]
yes! yes @rauljordan
