### ISSUE TITLE
How to import the validator keys in kiln?

### ISSUE THREAD

**Issue by come-maiz** [prysmaticlabs/prysm#11001]
# 💎 Issue

### Background

I'm trying to set up a validator in kiln, but it is not an option in the `validator accounts import` command.

### Description

```
$ go run ./cmd/validator/... accounts import --help
```

Only shows flags for mainnet, prater, ropsten and sepolia.

How do I import the account to run a validator in kiln?

**Comment by terencechain** [comment]
@james-prysm can you help here?

**Comment by james-prysm** [comment]
I don't believe you need to add anything on the validator side, just import without the testnet flag as long as you have everything else set to kiln https://hackmd.io/@prysmaticlabs/B1Q2SluWq. kiln was not configured like the other test nets and doesn't have its own flag.

**Comment by terencechain** [comment]
@come-maiz like james said, you have to use config. Will close this for now, feel free to dm us if you have any more questions!
