### ISSUE TITLE
Could not get ancestor state: unknown block"

### ISSUE THREAD

**Issue by mtxmomoaudio** [prysmaticlabs/prysm#11016]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...
Recently had issues with a completely full hard drive. Managed to clone everything over to a 2TB drive but upon starting everthing i'm getting this from my beacon-chain service.
I've wiped my geth chaindata and resynced using defaults. I rebooted after syncing to the latest block but error still appears.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

My system was setup using the instructions here at github.com/metalnull-operator/eth-ubuntu.

## 🔥 Error

<pre><code>
level=error msg="could not get ancestor state: unknown block" prefix=main

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu 20
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
2.1.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by mtxmomoaudio** [comment]
solved. I had deleted the geth database only and not the prysm data base. After deleting the laters and resyncing, everything went back to normal.

**Comment by nisdas** [comment]
Closing the issue in that case @mtxmomoaudio
