### ISSUE TITLE
Fee recipient address in the form of an ENS .ETH address

### ISSUE THREAD

**Issue by marungao** [prysmaticlabs/prysm#11063]
# 🚀 Feature Request

### Description

In the configuration file or cli flag, allow the use of an ENS .ETH address to configure the fee recipient address

Also, consider the use of the ENS address to replace other 0x1231321....12323 addresses

### Describe the solution you'd like

Actual configuration flag:
--suggested-fee-recipient=0x0123456722E6b0000012BFEBf6177F1D2e9758D9

Proposed change:
--suggested-fee-recipient=gimmegimmegimme.eth

**Comment by james-prysm** [comment]
Something like this will require middleware or a ux wrapper to the services, we don't want to intermix these things and add dependencies into our system. closing the ticket for now.
