### ISSUE TITLE
Transition payload production might fail if the TTD block timestamp coincides with the slot time

### ISSUE THREAD

**Issue by marioevz** [prysmaticlabs/prysm#11069]
# 🐞 Bug Report

### Description

Transition payload production might fail with the following error if the TTD block matches the slot time, because Prysm attempts to produce a payload with `timestamp==parent.timestamp`, where `parent` is the terminal PoW block.

Block is skipped in the beacon chain because of this.

### Has this worked before in a previous version?

Not sure.

## 🔬 Minimal Reproduction

Using branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients and the following command reproduces the issue every time:
```
go build -v .
./hive --client go-ethereum,prysm-bn,prysm-vc --sim eth2/engine --sim.limit "/equal-timestamp-terminal-transition-block" --sim.logle
vel 5
```

## 🔥 Error

[Geth/v1.10.21-unstable-a7d47ee7-20220718]
<pre><code>
TRACE[07-19|02:07:23.238] Engine API request received              method=ForkchoiceUpdated head=b26e6a..d45b18 finalized=000000..000000 safe=b26e6a..d45b18
ERROR[07-19|02:07:23.238] Failed to create empty sealing payload   err="invalid timestamp, parent 1658196443 given 1658196443"
WARN [07-19|02:07:23.238] Served engine_forkchoiceUpdatedV1        conn=172.17.0.3:38672 reqid=274 duration="323.194µs"        err="Invalid payload attributes"           errdata="{Error:invalid timestamp, parent 1658196443 given 1658196443}"
</code></pre>

[validator version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:58:45+00:00]
<pre><code>
time="2022-07-19 02:07:23" level=error msg="Failed to request block from beacon node" blockSlot=78 error="rpc error: code = Unknown desc = could not prepare payload: payload attributes are invalid / inconsistent" prefix=validator pubKey=0x8c405832ec39
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.6 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:44:24+00:00
validator version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:58:45+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
Docker version 20.10.17, build 100c701

**Comment by nisdas** [comment]
Is there anything prysm can do here ? We provide the current unix time to the execution engine, the fact that it coincides with the terminal block exactly means geth will always return an error. @terencechain @potuz What do you guys think ?

**Comment by terencechain** [comment]
I have a branch that fixes this. I'll push it in the next hour

**Comment by rauljordan** [comment]
hi @terencechain what's the status of this one?
