### ISSUE TITLE
Exported keystore file is missing path property

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#11064]
# 🐞 Bug Report

### Description

A keystore file exported from Prysm is missing the `path` property. This causes it to be un-importable in Lodestar.

In a file created from deposit-cli, path looks like this: `"path": "m/12381/3600/N/0/0"` with `N` starting at `0` depending on path taken.

**Comment by potuz** [comment]
A keystore can be constructed from any single private key, it does not need to be derived from an HD one. While many have used the deposit-cli, we cannot assume this is the case. Why does lodestar need the path to import it?

**Comment by yorickdowne** [comment]
I do not know why Lodestar needs this. Could you ping the devs there directly? I'm just trying to get some dialogue going.

**Comment by yorickdowne** [comment]
Playing in-between @potuz , answer from Lodestar:

"
We're just following the EIP 🤷
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md#json-schema
According to the schema the path is required.
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md#path
And the path should be set to "" if its not known or relevant.

Ofc we're happy to relax our validation. We should probably update the EIP if it seems like that isn't what we want tho.
"

**Comment by james-prysm** [comment]
https://github.com/prysmaticlabs/prysm/issues/10107 this looks related. I thought we fixed this and just have path return with ""

**Comment by yorickdowne** [comment]
Ohhhh I feel foolish, this might be my mistake. I may not have run with current Prysm to test import. Hang loose shall redo the test.

**Comment by yorickdowne** [comment]
Confirmed that this was my mistake. Sorry for wasting time!
