### ISSUE TITLE
Circuit breaker for relayer/builder

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11109]
We should implement some circuit breakers to break from mev-boost / builder network when the chain has experienced severe liveness issues. More is outlined in this proposal: https://hackmd.io/@ralexstokes/BJn9N6Thc

Lighthouse has implemented similar proposals here: https://github.com/sigp/lighthouse/issues/3355

**Comment by rauljordan** [comment]
Done at #11215
