### ISSUE TITLE
validator_failed_proposals apears only after first failed proposal

### ISSUE THREAD

**Issue by p2p-sergey-y** [prysmaticlabs/prysm#11102]
# 💎 Issue

### Background

I found out that `validator_failed_proposals` only appears after first fail, and it's hard to write an alert rule for that

### Description

This `validator_failed_proposals` metric appears only after the first failed proposal, so `validator_failed_proposals` immediately starts showing `1` value
![image](https://user-images.githubusercontent.com/87700053/180966468-f1254ea2-4dac-48c7-9682-51e666996330.png)

This is a problem because it's hard to write an alert exactly for the first fail. For others, it's elementary: we can use simple rate like `rate(validator_failed_proposals{...}[X])>0` but it skips the first one.

We need to set `0` for this metric from the start.

**Comment by prestonvanloon** [comment]
Would it work if you used `absent()`? Or maybe `absent_over_time()`

https://prometheus.io/docs/prometheus/latest/querying/functions/#absent

I think it would be like `rate(absent(validator_failed_proposals{...}[X]))>0`

**Comment by p2p-sergey-y** [comment]
I tried to use `absent` and `vector(0)` to trick that but unsuccessful.
The problem this absent is totally opposite to our problem: it exists only before first appear of metrics,  so it also can't be used in `rate` in that way.
![image](https://user-images.githubusercontent.com/87700053/181010572-c949ebfe-a7ec-42ca-8eee-a6ec800e3a1f.png)

**Comment by prestonvanloon** [comment]
I see, maybe something like this?
```
rate(validator_failed_proposals{pubkey="..."}[5m]) OR on() vector(0)
```

That should show zero until the rate is available. Is this what you tried already?

**Comment by p2p-sergey-y** [comment]
Unfortunately, no (it was my first attempt to resolve this issue).
Problem here what at first appearance rate will be 0 because start metric value is '1':
![image](https://user-images.githubusercontent.com/87700053/181029125-68e40999-e870-4643-9d4e-3640dae2b99e.png)
So, all expression value will be 0 in this situation:
![image](https://user-images.githubusercontent.com/87700053/181030440-59668aca-9e65-4102-b852-e9b30a0c05da.png)

In general, we need to detect two events:
* changes of `validator_failed_proposals` 
* first appearance of  `validator_failed_proposals` valid for some **finite time** 

First one we can do straightforward: `rate(validator_failed_proposals{...}[X])>0` which will be valid for X window, so we will receive alert only once.
But the second one is hard to do for finite time. We could just use something like `validator_failed_proposals{}==1` for detecting first appearance, but it will be valid until second failed block proposal, and it could take a long, long time. So, we will have a long time valid alert, and it's not a good thing.

And the problem is exactly in detecting first appearance, I have no idea how to detect it for some X window.

Anyway, setting this metric to 0 from start reduce detection problem to only one: catch changes on metric, it's simple and convenient

**Comment by prestonvanloon** [comment]
Thanks for the detailed response. I am hesitant to preemptively set these metrics to zero as that creates unnecessary additional influxDB ingestion/storage. As I understand it, you are trying to achieve alerts that fire on failed block proposals. There are some limitations to PromQL and alerting for this type of use case. 

Either your alert will fire for a long time or for only a moment. 

- `rate(validator_failed_proposals{pubkey="..."}[5m]) > 0`  will fire for about 5 minutes then resolve itself. 
- `rate(validator_failed_proposals{pubkey="..."}[24h]) > 0` will fire for longer, 24h, but you wouldn't receive further alerts in that time period if multiple proposals failed.

In any case, I believe that the missing metrics can be solved with the appropriate promQL statements. However, I question the usefulness of setting up alerts based on rate or delta of this metric with just PromQL and grafana.

**Comment by p2p-sergey-y** [comment]
Hello!
After two days of trying, I found how we can detect this first appearance of failed block proposal:
```
(validator_failed_proposals{...} unless validator_failed_proposals{...} offset X) == 1
```
![image](https://user-images.githubusercontent.com/87700053/181719147-e46d7679-9d02-4a27-9c58-41f03ae630ad.png)

In general, we just shift the same metric to X in timeline and remove it after that time using `unless` operator. It's a little tricky, but it works.

So, the result statement will be looking like that:
```
(validator_failed_proposals{...} unless validator_failed_proposals{...} offset X) == 1
or rate(validator_failed_proposals{...}[X]) > 0
```

**Comment by nisdas** [comment]
Closing this issue as it appears resolved.

**Comment by thevops** [comment]
Why a validator doesn't show this metric unless occurs? Is there any advantage of that approach?

In my opinion, such an approach makes it more difficult to create e.g. a Grafana dashboard or alerts. Working on non-existing metrics leads to overcomplicated queries for monitoring systems.
