### ISSUE TITLE
Merge readiness endpoint

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11114]
I think a merge readiness endpoint will be useful to have. The current beacon API doesn't specify anything like this. 

Example:

```bash
curl -X GET "http://localhost:3500/eth/v1alpha1//merge_readiness"
```

```
{
       "merged":"false",
       "terminal_total_difficulty":"4234324"
       "current_difficulty":"34324"
    }
 }
```

**Comment by nisdas** [comment]
Do we need a separate api endpoint for this ? It seems like this will be redundant by the time the merge is done. Anyway we can use `healthz` ? Maybe @prestonvanloon has some ideas on this

**Comment by terencechain** [comment]
> Do we need a separate api endpoint for this ? It seems like this will be redundant by the time the merge is done. Anyway we can use `healthz` ? Maybe @prestonvanloon has some ideas on this

Open for feedback. I saw Lighthouse has this and thought it may be nice to copy pasta

**Comment by rauljordan** [comment]
A bit too late for this one, unfortunately. Will close for now
