### ISSUE TITLE
Support e2e test for mev-boost

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11113]
Add support for e2e test for mev-boost side car for block proposal and more

**Comment by james-prysm** [comment]
this can only happen after the relay becomes open source right?

**Comment by terencechain** [comment]
We can mock the responses

**Comment by maxwolff** [comment]
@terencechain could you say more about what you think the deliverable is here? should we actually start up a mev-boost server in the e2e test? run the docker image?

**Comment by james-prysm** [comment]
https://github.com/prysmaticlabs/prysm/issues/12278 closed , doesn't support mev-boost but it does support a mocked builder.
