### ISSUE TITLE
Error not thrown when multiple processes connect to same datadir

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1112]
Identified in this comment: https://github.com/prysmaticlabs/prysm/issues/1017#issuecomment-447559851

We should visibly fail when two processes attempt to access the datadir concurrently. 
The database package should maintain a lock of some kind and throw a fatal error if attempting to access a datadir which is already locked by another process.

**Comment by kushagrasharma** [comment]
Hi, I'd be happy to take this one on!

**Comment by prestonvanloon** [comment]
Thanks @kushagrasharma!
