### ISSUE TITLE
Setting Goerli flag in YAML does not set network to Prater

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#11122]
https://github.com/prysmaticlabs/prysm/blob/63a8690140c00ba6e3e4054cac3f38a5107b7fb2/config/features/config.go#L114

Running v2.1.4-rc.0 with Goerli flag set in YAML config file does not set chain for Prater network. Using Goerli flag on command line does work. An alias for Prater was created with issue #11605, but as best as I can tell the cli library doesn't check aliases when using ctx.Bool on the line referenced in the link above.

**Comment by metanull-operator** [comment]
Now that I think about it, my previous comment doesn't make sense. Alias appears to still be checked when goerli used on command line. So, not clear to me why this doesn't work from YAML.

**Comment by terencechain** [comment]
> Now that I think about it, my previous comment doesn't make sense. Alias appears to still be checked when goerli used on command line. So, not clear to me why this doesn't work from YAML.

Can you share the yaml file?

**Comment by metanull-operator** [comment]
Unfortunately, I can no longer match up what my configuration was when I submitted this with the log entry I have that says I was on the wrong network.

Current logs seem to be about something different than my original report, but something doesn't seem right. I won't speculate further.

Systemd Service File:
```
`ExecStart=/home/prysm-beacon/bin/beacon-chain --config-file /home/prysm-beacon/prysm-beacon.yaml`
```

prysm-beacon.yaml
```
datadir: "/home/prysm-beacon/prysm"
p2p-host-ip: "XXX.XXX.XXX.XXX"
http-web3provider: "http://127.0.0.1:8545"
monitoring-host: "0.0.0.0"
p2p-tcp-port: XXXX
p2p-udp-port: XXXX
accept-terms-of-use: true
goerli: true
jwt-secret: "/srv/ethereum/secrets/jwtsecret"
genesis-state: "/home/prysm-beacon/prater/genesis.ssz"
#checkpoint-sync-url: "https://XXXXXXXXXX@eth2-beacon-prater.infura.io"
grpc-gateway-host: "0.0.0.0"
suggested-fee-recipient: "0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

Logs
```
Jul 27 12:32:04 nuc systemd[1]: Started Prysm Beacon Chain Client.
Jul 27 12:32:04 nuc beacon-chain[143357]: time="2022-07-27 12:32:04" level=warning msg="Running on Ethereum Mainnet" prefix=flags
Jul 27 12:32:04 nuc beacon-chain[143357]: time="2022-07-27 12:32:04" level=info msg="Checking DB" database-path="/home/prysm-beacon/prysm/beaconchaindata" prefix=node
Jul 27 12:32:04 nuc beacon-chain[143357]: time="2022-07-27 12:32:04" level=info msg="Opening Bolt DB at /home/prysm-beacon/prysm/beaconchaindata/beaconchain.db" prefix=db
Jul 27 12:32:04 nuc beacon-chain[143357]: time="2022-07-27 12:32:04" level=error msg="you have disabled the flag enable-only-blinded-beacon-blocks, and your node must resync to ensure your database is compatible. If you do not want to resync, please re-enable the enable-only-blinded-beacon-blocks flag" prefix=main
Jul 27 12:32:04 nuc systemd[1]: prysm-beacon.service: Succeeded.
Jul 27 12:32:09 nuc systemd[1]: prysm-beacon.service: Scheduled restart job, restart counter is at 1.
Jul 27 12:32:09 nuc systemd[1]: Stopped Prysm Beacon Chain Client.
Jul 27 12:32:09 nuc systemd[1]: Started Prysm Beacon Chain Client.
```
After I remove `goerli: true` from config and add ``--goerli`` to systemd service file, I end up with this...

`ExecSAtart/home/prysm-beacon/bin/beacon-chain --config-file /home/prysm-beacon/prysm-beacon.yaml --goerli`

Config
```
datadir: "/home/prysm-beacon/prysm"
p2p-host-ip: "XXX.XXX.XXX.XXX"
http-web3provider: "http://127.0.0.1:8545"
monitoring-host: "0.0.0.0"
p2p-tcp-port: XXXX
p2p-udp-port: XXXX
accept-terms-of-use: true
#goerli: true
jwt-secret: "/srv/ethereum/secrets/jwtsecret"
genesis-state: "/home/prysm-beacon/prater/genesis.ssz"
#checkpoint-sync-url: "https://XXXXXXXXXX@eth2-beacon-prater.infura.io"
grpc-gateway-host: "0.0.0.0"
suggested-fee-recipient: "0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

Logs:
```
Jul 27 12:37:31 nuc systemd[1]: Started Prysm Beacon Chain Client.
Jul 27 12:37:31 nuc beacon-chain[144774]: time="2022-07-27 12:37:31" level=warning msg="Running on the Prater Testnet" prefix=flags
```
...and functioning resumes as normal. No problems syncing up.

**Comment by metanull-operator** [comment]
You can see in the first log where is says it is connecting to mainnet. This is what made me initially think it wasn't respecting the Goerli flag in YAML. But from command line it says Prater.

**Comment by nisdas** [comment]
we do versioning by the fork-version afaik, @kasey can confirm on this.

**Comment by metanull-operator** [comment]
Sorry @nisdas, is your comment something actionable for me, or is this a note to devs?

**Comment by nisdas** [comment]
Hey @metanull-operator , this is mostly a note to kasey

**Comment by james-prysm** [comment]
https://github.com/urfave/cli/issues/1394 looks like this is the underlying issue to this.

**Comment by james-prysm** [comment]
I believe this will be fixed with v3 cli, waiting for release, I fixed the bug in the library.
