### ISSUE TITLE
Validator not failing over to other beacon chains

### ISSUE THREAD

**Issue by jacquesvcritien** [prysmaticlabs/prysm#11139]
Hi!

In our validator config, we have multiple beacon-chain endpoints configured through the **--beacon-rpc-gateway-provider**  and **--beacon-rpc-provider** flags. However, whenever there is some sort of disconnection between the validator and the connected beacon-chain, the node does not failover to the next beacon-chain in the configured list. Instead, it just hangs and does not try to reconnect to the original beacon-chain endpoint or a new one. When this happens, the beacon node being used would still be healthy however the connection to it may have had a hiccup, and the validator client stops sending requests to it.

In addition, we also see a spike in `grpc_method="DomainData" DeadlineExceeded` errors around this time.

**Comment by rkapka** [comment]
Hi @jacquesvcritien , I tried to reproduce the problem but the failover worked for me.

First I started two beacon nodes:
```
--datadir=xxx --http-web3provider=zzz --prater

--datadir yyy --http-web3provider=zzz --monitoring-port=8081 p2p-tcp-port=13001 --p2p-udp-port=12001 --grpc-gateway-port=3501 --rpc-port=4001 --prater
```

Then I started the validator client:
```
--wallet-dir=vvv --beacon-rpc-provider="127.0.0.1:4000,127.0.0.1:4001" --beacon-rpc-gateway-provider="127.0.0.1:3500,127.0.0.1:3501"
```

Initially the second beacon node was not fully synced and the validator started attesting, which ensured me that it's connected to the first node. After some time I stopped the first node and got the following logs from the validator client:
```
ERROR validator: Could not receive blocks from beacon node, could not connect error=rpc error: code = Canceled desc = Context canceled
WARN validator: block stream interrupted error=rpc error: code = Canceled desc = Context canceled: could not connect
```

After a few minutes the validator client started attesting again:
```
INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=113599 inactivityScore=0 newBalance=31.999053034 oldBalance=31.999064814 percentChange=-0.00004% percentChangeSinceStart=-0.00007% pubKey=0xb6bdb41f87ee startBalance=31.999076594
INFO validator: Attestation schedule attesterDutiesAtSlot=1 pubKeys=[0xb6bdb41f87ee] slot=3635237 slotInEpoch=5 totalAttestersInEpoch=1
INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[372936] BeaconBlockRoot=0xce1e1e68cf22 CommitteeIndex=52 Slot=3635237 SourceEpoch=113600 SourceRoot=0xa18b0704344c TargetEpoch=113601 TargetRoot=0xc28561307823
```

**Comment by franono** [comment]
Hi @rkapka, (replying on behalf of @jacquesvcritien), we're hitting a different rpc error than Context canceled. Ours stall is being hit when the following error happens:
```DeadlineExceeded desc = context deadline exceeded,```

I want to figure out how to replicate this, as we've only hit this in production whilst validator clients are using a beacon chain at another provider and there's a hiccup in the internet connection for a short time (possibly seconds rather than minutes).

**Comment by terencechain** [comment]
Please reopen this still persists
