### ISSUE TITLE
Unable to broadcast sync committee contribution

### ISSUE THREAD

**Issue by Inphi** [prysmaticlabs/prysm#11147]
# 🐞 Bug Report

### Description

Running a validator on a local testnet creates a lot of errors because it fails to broadcast sync committee messages. This happens as soon as altair begins and once the beacon node peers with another beacon node. The peer does not subscribe to all sync committee subnets and thus misses certain message broadcasts.

While both beacon nodes are synchronized, with matching block and state roots, I see alot of errors that look like the following:
```
time="2022-08-02 04:46:21" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/de1c6e6d/sync_committee_3/ssz_snappy - only 0 out of 1 peers were able to be found" prefix=p2p
```

### Has this worked before in a previous version?

Unclear. I haven't checked that far back.

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

I'm running a 2 beacon node paired with 2 validator client setup.
(here I show how to reproduce using interop testing, but this problem occurs even without any mocking)

#### Beacon Node

```
beacon-node \
    --accept-terms-of-use \
    --min-sync-peers 0\
    --disable-sync\
    --bootstrap-node=\
    --datadir /chaindata \
    --force-clear-db \
    --interop-eth1data-votes \
    --http-web3provider="$EXECUTION_NODE_URL" \
    --deposit-contract $DEPOSIT_CONTRACT \
    --chain-config-file=$CUSTOM_CHAIN_CONFIG \ # not noteworthy. Contains mostly defaults.
    --contract-deployment-block $CONTRACT_DEPLOYMENT_BLOCK \
    --interop-num-validators 4 \
    --rpc-host 0.0.0.0 \
    --rpc-port 4000 \
    --grpc-gateway-host 0.0.0.0 \
    --grpc-gateway-port 3500 \
    --enable-debug-rpc-endpoints \
    --p2p-local-ip 0.0.0.0 \
    --p2p-host-ip "$EXTERNAL_IP"

validator
      --accept-terms-of-use
      --beacon-rpc-provider $BEACON_NODE_RPC
      --interop-num-validators=4
      --interop-start-index=0
      --force-clear-db
      --chain-config-file=/config/prysm-chain-config.yml
      --suggested-fee-recipient $FEE_RECIPIENT

# on another machine
beacon-node \
    --accept-terms-of-use \
    --verbosity="$VERBOSITY" \
    --datadir /chaindata \
    --bootstrap-node $BOOTNODE \
    --min-sync-peers 1 \
    --force-clear-db \
    --interop-eth1data-votes \
    --interop-genesis-time $INTEROP_GENESIS_TIME \
    --http-web3provider="$EXECUTION_NODE_URL" \
    --deposit-contract $DEPOSIT_CONTRACT \
    --chain-config-file=$CUSTOM_CHAIN_CONFIG \
    --contract-deployment-block $CONTRACT_DEPLOYMENT_BLOCK \
    --interop-num-validators 4 \
    --rpc-host 0.0.0.0 \
    --rpc-port 4000 \
    --grpc-gateway-host 0.0.0.0 \
    --grpc-gateway-port 3500 \
    --enable-debug-rpc-endpoints \
    --p2p-local-ip 0.0.0.0 \
    --p2p-host-ip "$EXTERNAL_IP"
```

## 🔥 Error
Error logs are all similar:

<pre><code>
20839: time="2022-08-02 05:14:39" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/5c5af27d/sync_committee_1/ssz_snappy - only 0 out of 1 peers were able to be found" prefix=p2p
20841: time="2022-08-02 05:14:39" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/5c5af27d/sync_committee_1/ssz_snappy - only 0 out of 1 peers were able to be found" prefix=p2p
20843: time="2022-08-02 05:14:39" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/5c5af27d/beacon_attestation_0/ssz_snappy - only 0 out of 1 peers were able to be found" prefix=p2p
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux (Ubuntu 20)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
c1f89cc4c8c09494fe0aaa6e095c257a4bae1e16
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

cc: @terencechain

**Comment by prestonvanloon** [comment]
It is possible that your one and only peer was not listening for that subnet at the time. Consider running both nodes with `--subscribe-all-subnets`.

**Comment by Inphi** [comment]
That did the trick! Thanks!
