### ISSUE TITLE
Wallet create/recovery with non-english mnemonics

### ISSUE THREAD

**Issue by shenhanc** [prysmaticlabs/prysm#11148]
# 🚀 Feature Request

### Description

Many wallet management tools support non-English mnemonics (e.g., the official staking deposit tool), would be better if prysm could also support this. 

### Describe the solution you'd like

[bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) has good support for non-enghlish mnemonics, should be relatively straightforward to add support in prysm.

(I personally use east Asia mnemonics for all my wallets and am willing to be assigned to this feature.)

**Comment by prycey77** [comment]
Can I pick this up?

**Comment by rkapka** [comment]
> Can I pick this up?

Assigned to you @prycey77

**Comment by james-prysm** [comment]
I believe this partially addresses this at least for recovery https://github.com/prysmaticlabs/prysm/pull/11278

**Comment by james-prysm** [comment]
it seems like we are supporting the following for recovery at least
```
"chinese_simplified":  wordlists.ChineseSimplified,
		"chinese_traditional": wordlists.ChineseTraditional,
		"czech":               wordlists.Czech,
		"english":             wordlists.English,
		"french":              wordlists.French,
		"japanese":            wordlists.Japanese,
		"korean":              wordlists.Korean,
		"italian":             wordlists.Italian,
		"spanish":             wordlists.Spanish,
```
did not see a list for creation that's where the opportunity is
