### ISSUE TITLE
goerli alias seems not to work when used configuration file

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/prysm#11150]
**Version:** v2.1.4-rc.0

# 🐞 Bug Report

### Description

When using`--goerli` option (instead of `--prater`) directly in command line, everything is OK.
However, using the following configuration file:
```
goerli: true
```
won't work and **Prysm** will act as if it is running on mainnet:

```
Running on Ethereum Mainnet
```

Note that if I use the `--prater` option or the following configuration file:
```
prater: true
```

everything is OK.

**Comment by metanull-operator** [comment]
Also reported in #11122.

**Comment by james-prysm** [comment]
related issue updated

**Comment by james-prysm** [comment]
closing this in favor of #11122 ( duplicate )
