### ISSUE TITLE
Validator CLI flag for --wallet-dir requires an = when using "accounts list"

### ISSUE THREAD

**Issue by jyap808** [prysmaticlabs/prysm#11177]
# 🐞 Bug Report

### Description

This errors:
```
$ ./validator-v2.1.4-rc.1-linux-amd64 accounts list --goerli --wallet-dir /somedir
[2022-08-05 21:01:05] ERROR main: unrecognized argument: /somedir
```

Needs to be specified like this to work:
```
$ ./validator-v2.1.4-rc.1-linux-amd64 accounts list --goerli --wallet-dir=/somedir
```

"accounts import" works fine without the "=". For example, this works
```
$ ./validator-v2.1.4-rc.1-linux-amd64 accounts import --goerli --wallet-dir /somedir --keys-dir /tmp
```

### Has this worked before in a previous version?

Unknown

## 🔬 Minimal Reproduction

See description

## 🔥 Error

See description

## 🌍  Your Environment

**Operating System:**

Linux

**What version of Prysm are you running? (Which release)**

v2.1.4-rc.1

**Comment by james-prysm** [comment]
I think it's a property of how our flag system works, try doing `accounts list  --wallet-dir /somedir --goerli`

**Comment by jyap808** [comment]
Yeah I’m saying the flag parsing should be consistent behavior, not trial and error.

**Comment by james-prysm** [comment]
still investigating if it's something that'd need to change on ourside or on the cli package

**Comment by james-prysm** [comment]
Sorry for the late response, I believe this needs to be addressed at the CLI package side and will take some time before it's addressed along with a few other things. Will keep this open for tracking.

**Comment by james-prysm** [comment]
I believe we should have addressed this , can reopen if needed
