### ISSUE TITLE
Attestations failing - level=warning msg="Range is not processed" error="Range had no valid blocks to process" prefix=initial-sync

### ISSUE THREAD

**Issue by tamaszl** [prysmaticlabs/prysm#11178]
# 💎 Issue

validator started failing attestations. I restarted the beacon-chain and now i get this warning: 
Aug 06 08:48:03 eth2 prysm.sh[1617195]: time="2022-08-06 08:48:03" level=warning msg="Range is not processed" error="Range had no valid blocks to process" prefix=initial-sync

### Background

# $HOME/prysm/prysm.sh beacon-chain --version
Latest Prysm version is v2.1.3.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v2.1.3-linux-amd64: OK

https://prater.beaconcha.in/validator/844e5fa0e7ab1e46b67cc7d8eb86f90f0e01b0a475a8bac1e827355fd18dc8905c2005d3fc7db6b44a785fe1140b99b6#attestations

### Description

Need help troubleshooting above warning and failed attestations.

**Comment by terencechain** [comment]
Looks like this is resoled, the validator is attesting good
