### ISSUE TITLE
Validator registration on non-builder beacon node

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11181]
Assume the following setups
```
Default: bn1 (w mevboost)     \____ validators w/ builder enabled
Fallback: bn2 (w/o mevboost)  /
```

In the event bn1 goes down, validators switch to bn2. The builder-enabled validators will all default to local EE for block construction.  Validators will see messages such as `could not submit validator registration.` Is that enough? Could we do more on the validator's or the beacon node's end to amplify the intent so validators could notify bn2 to turn on mev-boost asap?

**Comment by james-prysm** [comment]
perhaps we should add an additional log on the beacon node side if they are using the EE fallback/have the builder flag on
