### ISSUE TITLE
Checkpoint not work prater

### ISSUE THREAD

**Issue by Piradoxlanieve** [prysmaticlabs/prysm#11183]
# 🐞 Bug Report

### Description

I'm trying to run from checkpoint, it worked for me once, but now I wanted to sync again since I deleted the database but I got this error.

## 🔥 Error

<pre>ago 08 15:15:33 AcePc prysm.sh[155371]: Verified /home/eth/prysm/dist/beacon-chain-v2.1.3-linux-amd64 has been signed by Prysmatic Labs.
ago 08 15:15:33 AcePc prysm.sh[155371]: Starting Prysm beacon-chain --prater --http-web3provider=http://127.0.0.1:5555 --http-web3provider=http://127.0.0.1:8555 --jwt-secret=/home/eth/.eth2validators_test/secrets/jwtsecret --suggested-fee-recipient=0x1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --p2p-tcp-port 13005 --p2p-udp-port 12005 --checkpoint-sync-url=https://prater.checkpoint-sync.ethdevops.io/ --genesis-beacon-api-url=https://prater.checkpoint-sync.ethdevops.io/ --enable-debug-rpc-endpoints --grpc-max-msg-size=6568081 --datadir /mnt/ssd/.eth2_test --p2p-max-peers=45 --accept-terms-of-use
ago 08 15:15:33 AcePc prysm.sh[155371]: time="2022-08-08 15:15:33" level=info msg="Raised fd limit to 524288 from 1024"
ago 08 15:15:33 AcePc prysm.sh[155371]: time="2022-08-08 15:15:33" level=warning msg="Running on the Prater Testnet" prefix=flags
ago 08 15:15:33 AcePc prysm.sh[155371]: time="2022-08-08 15:15:33" level=info msg="Checking DB" database-path="/mnt/ssd/.eth2_test/beaconchaindata" prefix=node
ago 08 15:15:33 AcePc prysm.sh[155371]: time="2022-08-08 15:15:33" level=info msg="Opening Bolt DB at /mnt/ssd/.eth2_test/beaconchaindata/beaconchain.db" prefix=db
ago 08 15:15:33 AcePc prysm.sh[155371]: time="2022-08-08 15:15:33" level=info msg="requesting https://prater.checkpoint-sync.ethdevops.io/eth/v2/debug/beacon/states/genesis"
ago 08 15:15:40 AcePc prysm.sh[155371]: time="2022-08-08 15:15:40" level=info msg="requesting https://prater.checkpoint-sync.ethdevops.io/eth/v2/debug/beacon/states/finalized"
ago 08 15:15:44 AcePc prysm.sh[155371]: time="2022-08-08 15:15:44" level=info msg="detected supported config in remote finalized state, name=prater, fork=bellatrix"
ago 08 15:15:46 AcePc prysm.sh[155371]: time="2022-08-08 15:15:46" level=info msg="requesting https://prater.checkpoint-sync.ethdevops.io/eth/v2/beacon/blocks/0x5a5dee0748a2047d4c1222ad82e1b220d5fd511450f092aec73ddc9babf211b7"
ago 08 15:15:47 AcePc prysm.sh[155371]: time="2022-08-08 15:15:47" level=error msg="Error retrieving checkpoint origin state and block: unable to unmarshal block to a supported type using the detected fork schedule: slot=3621312, epoch=113166, version=0x01001020: fork or config detected in unmarshaler is different than block" prefix=main
ago 08 15:15:47 AcePc systemd[1]: beacon-chain_test.service: Succeeded.

<code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm version is v2.1.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by james-prysm** [comment]
@kasey do you have an opinion on this?

**Comment by Allen-yan** [comment]
I meet the same issue
version v2.1.4
ubuntu 20.04

The upper node running with 
`./prysm.sh  beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex --genesis-state=/data/prysm/genesis.ssz --enable-debug-rpc-endpoints  --grpc-max-msg-size=65568081 `

The new prater node running with options
`/data/prysm/prysm.sh beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex  --checkpoint-sync-url=http://upper-host --accept-terms-of-use`

Here's the error logs 
`time="2022-08-16 16:05:43" level=error msg="Error retrieving checkpoint origin state and block: error requesting block by root = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: error requesting state by id = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: code=500, url=http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3, body=response body:
{"message":"Unknown block type *blocks.SignedBeaconBlock","code":500}: did not receive 2xx response from API" prefix=main`

if I curl the http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3 url directly , it returned 200

**Comment by Piradoxlanieve** [comment]
> I meet the same issue version v2.1.4 ubuntu 20.04
> 
> The upper node running with `./prysm.sh beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex --genesis-state=/data/prysm/genesis.ssz --enable-debug-rpc-endpoints --grpc-max-msg-size=65568081 `
> 
> The new prater node running with options `/data/prysm/prysm.sh beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex --checkpoint-sync-url=http://upper-host --accept-terms-of-use`
> 
> Here's the error logs `time="2022-08-16 16:05:43" level=error msg="Error retrieving checkpoint origin state and block: error requesting block by root = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: error requesting state by id = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: code=500, url=http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3, body=response body: {"message":"Unknown block type *blocks.SignedBeaconBlock","code":500}: did not receive 2xx response from API" prefix=main`
> 
> if I curl the http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3 url directly , it returned 200
In the end I managed to get it to work with my infura api, I think you are missing a flag to put.
--enable-debug-rpc-endpoints \
--grpc-max-msg-size=65568081 \
--checkpoint-sync-url=https:///yourapi-infura@eth2-beacon-prater.infura.io \
--genesis-beacon-api-url=https://yourapi-infura@eth2-beacon-prater.infura.io \

**Comment by kasey** [comment]
> I meet the same issue version v2.1.4 ubuntu 20.04
> 
> The upper node running with `./prysm.sh beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex --genesis-state=/data/prysm/genesis.ssz --enable-debug-rpc-endpoints --grpc-max-msg-size=65568081 `
> 
> The new prater node running with options `/data/prysm/prysm.sh beacon-chain --http-web3provider=http://localhost:8551 --prater --jwt-secret=/data/prysm/jwt.hex --checkpoint-sync-url=http://upper-host --accept-terms-of-use`
> 
> Here's the error logs `time="2022-08-16 16:05:43" level=error msg="Error retrieving checkpoint origin state and block: error requesting block by root = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: error requesting state by id = 0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3: code=500, url=http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3, body=response body: {"message":"Unknown block type *blocks.SignedBeaconBlock","code":500}: did not receive 2xx response from API" prefix=main`
> 
> if I curl the http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3 url directly , it returned 200

@Piradoxlanieve and @Allen-yan I believe this issue has been fixed in our development branch. The merged PR is visible here:
https://github.com/prysmaticlabs/prysm/pull/11210/files

This fix will be available in the next release, `3.0.0-rc0`, which should be available this Friday. The issue was an error on the serving side ("upper node") when requesting the ssz-encoding of a post-bellatrix block. If you add an `Accept` header to your curl request, I believe you'll get an error response -- try this:

`curl -H "Accept: application/octet-stream" http://upperhost:3501/eth/v2/beacon/blocks/0xcf5639a5df69ba9264f60476d9ea6183637afe49ab4db86cff323e946875c0b3`

The `Accept: application/octet-stream` header tells the beacon node API to respond with an ssz-encoded block (rather than the default json-encoded response). This code path specifically had the bug and is what prysm uses under the hood when requesting a block for checkpoint sync. If this request fails, then I'm fairly confident this is the issue you are experiencing, in which case please hold tight a few days and give the next release a try.

**Comment by Allen-yan** [comment]
Great! Thanks! Looking forward to the new version

**Comment by rauljordan** [comment]
Let us know if unresolved after the new version is released and we can revisit this

**Comment by Allen-yan** [comment]
I have upgraded my nodes with the latest release version v3.0.0. The checkpoint sync mode works ! My new node has synced to the latest blocks.
Thanks a lot !

By the way can I initialize another new node from this new node  ?  Or is a node synced from checkpoint mode  the same as " a fully synced beacon node"?
https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync#option-1-configure-checkpoint-sync-via-network-request
