### ISSUE TITLE
Add `/eth/v1/validator/register_validator` to Beacon API

### ISSUE THREAD

**Issue by moshe-blox** [prysmaticlabs/prysm#11220]
# 🚀 Feature Request

### Description

Prysm can `register_validator` via gRPC, but not yet via the Beacon API.

This would be great for 3rd party validator clients such as [Vouch](github.com/attestantio/vouch).

[Link to spec](https://ethereum.github.io/beacon-APIs/#/Validator/registerValidator) <--

🙏

**Comment by terencechain** [comment]
cc @james-prysm is this implemented?

**Comment by james-prysm** [comment]
working on this now.

**Comment by james-prysm** [comment]
@moshe-blox wondering if you'd be able to run a small test on my PR above just making sure things are good on that end.
