### ISSUE TITLE
There is something wrong with the documentation, can't access curl http://localhost:3500/eth/v1alpha1/node/syncing

### ISSUE THREAD

**Issue by hanzhenlong1314** [prysmaticlabs/prysm#11238]
# 💎 Issue

### Background

 Context and background information on the discussion...

### Description

I build a beacon chain test node according to this documentation (https://docs.prylabs.network/docs/install/install-with-docker), but execute curl http://localhost:3500/eth/v1alpha1/node/syncing Nothing came back, so I just used curl http://localhost:13000/eth/v1/node/syncing but the value returned was /multistream/1.0.0, I used (docker run -dit -v /data/ node_eth2/prysm:/data -v /data/node_eth2/genesis.ssz:/genesis/genesis.ssz -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node \
gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
--datadir=/data \
--rpc-host=0.0.0.0 \
--monitoring-host=0.0.0.0 \
--http-web3provider=https://goerli.infura.io/v3/XXX\
--genesis-state=/genesis/genesis.ssz \
--prater) to run the node, I did not find the mapping of port 3500 in the document, is there a problem with the document?

![image](https://user-images.githubusercontent.com/25896081/185074004-5380aee8-0fe0-454b-b3db-ca18b54f404a.png)
![image](https://user-images.githubusercontent.com/25896081/185074386-7fd4e4dd-af8b-4a54-b6de-651c484072bf.png)
![image](https://user-images.githubusercontent.com/25896081/185074461-2dd10203-d7ef-42f0-b691-8c63a752e5d2.png)

**Comment by nisdas** [comment]
@hanzhenlong1314 You need to use port 3500 , not 13000. That is our p2p port.

**Comment by hanzhenlong1314** [comment]
> @hanzhenlong1314 You need to use port 3500 , not 13000. That is our p2p port. 3500 is the default api endpoint

So how should I modify this command, docker run -dit -v /data/ node_eth2/prysm:/data -v /data/node_eth2/genesis.ssz:/genesis/genesis.ssz -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node
gcr.io/prysmaticlabs/prysm/beacon-chain:stable
--datadir=/data
--rpc-host=0.0.0.0
--monitoring-host=0.0.0.0
--http-web3provider=https://goerli.infura.io/v3/XXX\
--genesis-state=/genesis/genesis.ssz
--prater ,


ocker run -dit -v /data/ node_eth2/prysm:/data -v /data/node_eth2/genesis.ssz:/genesis/genesis.ssz -p 4000:4000 -p 3500:3500 -p 12000:12000/udp - -name beacon-node
gcr.io/prysmaticlabs/prysm/beacon-chain:stable
--datadir=/data
--rpc-host=0.0.0.0
--monitoring-host=0.0.0.0
--http-web3provider=https://goerli.infura.io/v3/XXX\
--genesis-state=/genesis/genesis.ssz
--prater Is this right?

**Comment by nisdas** [comment]
Add `-p 3500:3500` to your docker command

**Comment by hanzhenlong1314** [comment]
> Add `-p 3500:3500` to your docker command . That is correct

ok,thanks,iwill try it

**Comment by hanzhenlong1314** [comment]
> Add `-p 3500:3500` to your docker command . That is correct
![image](https://user-images.githubusercontent.com/25896081/185080371-1aff41d5-bfa6-4858-a486-41cddf9a26de.png)
![image](https://user-images.githubusercontent.com/25896081/185080435-68db506f-7a62-49b2-bd44-884b1aed907f.png)
docker run -dit -v /data/node_eth2/prysm:/data -v /data/node_eth2/genesis.ssz:/genesis/genesis.ssz -p 4000:4000 -p 13000:13000 -p 3500:3500 -p 12000:12000/udp --name beacon-node \
gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
--datadir=/data \
--rpc-host=0.0.0.0 \
--monitoring-host=0.0.0.0 \
--http-web3provider=https://goerli.infura.io/v3/xxx \
--genesis-state=/genesis/genesis.ssz \
--prater
Still not working
![image](https://user-images.githubusercontent.com/25896081/185080734-b6022f39-02b6-4e4f-8871-cb680464d71c.png)

**Comment by rauljordan** [comment]
hi @hanzhenlong1314 I think you issue is you need to provide --grpc-gateway-host=0.0.0.0 as well. Let me know if that fixes it

**Comment by terencechain** [comment]
@hanzhenlong1314 please reopen if it still exists after adding gateway host

**Comment by hanzhenlong1314** [comment]
> @hanzhenlong1314 please reopen if it still exists after adding gateway host

it work
