### ISSUE TITLE
Document p2p.Broadcast

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1126]
The current documentation for broadcast is only `Broadcast a message to the world.` This is incredibly useless given that the broadcast functionality is non trivial.

https://godoc.org/github.com/prysmaticlabs/prysm/shared/p2p#Server.Broadcast

Documentation here should outline the full usage and requirements for broadcast. Furthermore, we should expand on the p2p examples to provide better insight on how things work. This lack of documentation slow progress on features like #543 by outside contributors.

Thanks @jgimeno for the feedback!

**Comment by kushagrasharma** [comment]
I'd be happy to work on this one!

**Comment by terenc3t** [comment]
Great. Thanks @kushagrasharma !

**Comment by kushagrasharma** [comment]
I added documentation for Broadcast, I wasn't sure if you meant add examples for Broadcast which I did, or examples for the rest of the p2p library as well, which I'd be happy to add on.

**Comment by ratikesh9** [comment]
@kushagrasharma  are you adding the example to understand the implementation of broadcast along with your pull request ? I can help with this if you want ?
