### ISSUE TITLE
Blinded block generation should not require validator registration

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#11293]
# 🐞 Bug Report

### Description

When attempting to generate a blinded beacon block prysm currently refuses to do so unless the validator has been registered.  However, in configurations with multiple beacon nodes or alternative registration systems the beacon node may not have been informed of the registration.  As such, it should not check for local knowledge of the registration as a gate to fetching blocks from the MEV relay.

Relevant code: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go#L45-L46

It may be desirable to carry out a check that the returned block header has a non-zero fee recipient for situations where the relay really does not know the fee recipient address. 

### Has this worked before in a previous version?

No.

## 🌍  Your Environment

Prysm v3.0.0

**Comment by terencechain** [comment]
I'm concerned about setups like:

1.) 
bn (`--http-mev-relay=xyz`)  <-> vc (`--enable-builder=false`)

or hybrid version

2.)
bn (`--http-mev-relay=xyz`)  <-> vc where settings are mixture of `--enable-builder=true/false`

In such setups, the validators who prefer local ee would always call mev-boost/relayer firsthand then fallback to failure. Even worse, a bad relayer could return a legit block even if the validators did not register.


Would it be better to add a beacon node flag like skip registration check? `--skip-builder-registration-check`

**Comment by mcdee** [comment]
Wouldn't a VC that had `--enable-builder=false` request beacon blocks rather than blinded beacon blocks, so that wouldn't be an issue?

I'd be fine with a flag, just not sure that it's necessary.

**Comment by terencechain** [comment]
> Wouldn't a VC that had `--enable-builder=false` request beacon blocks rather than blinded beacon blocks, so that wouldn't be an issue?

I think this is true for beacon API. For prysm API, it's a single endpoint, so we don't have a great way for separation.

Couple options
1. Caller always has to register through the beacon node before the proposal (this is not ideal)
2. Add a flag to the beacon node to skip the registration check
3. Fix prysm validators / prysm API to have better isolations for full block and blind block (this will take a while)

**Comment by terencechain** [comment]
The more I look at the code, I realized `ProduceBlindedBlock` really shouldn't care whether the validator is registered. I'll study how we can refactor it better. I think this is the best option
