### ISSUE TITLE
prysm.bat beacon-chain --http-web3provider=//./pipe/geth.ipc --suggested-fee-recipient=0x01234567722E6b0000012BFEBf6177F1D2e9758D9

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#11336]
excuse me ，i want to know ,//./pipe/geth.ipc   do not need to change?the only thing i need to change is the ETH address

**Comment by james-prysm** [comment]
we have this awesome doc from @mick-prysm https://docs.prylabs.network/docs/install/install-with-script that shows the flags you'll need... that being said yet you will need to update that suggested-fee-recipient flag value with a wallet address you own.

**Comment by james-prysm** [comment]
closing for being stale...
