### ISSUE TITLE
error main：error preparing to initialize genesis db state from local ssz files:error checking existence of ssz-encoded file genesis.ssz for genesis state init : createfile genesis.ssz:the system cannot find the file specified.

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#11335]
### Description

error main：error preparing to initialize genesis db state from local ssz files:error checking existence of ssz-encoded file genesis.ssz for genesis state init : createfile genesis.ssz:the system cannot find the file specified.

## 🔥 Error

error main：error preparing to initialize genesis db state from local ssz files:error checking existence of ssz-encoded file genesis.ssz for genesis state init : createfile genesis.ssz:the system cannot find the file specified.

</code></pre>

## 🌍  Your Environment

**Operating System:**
window10

**What version of Prysm are you running? (Which release)**

3.0.0

**Anything else relevant (validator index / public key)?**

prysm.bat beacon-chain --http-web3provider=//./pipe/geth.ipc --suggested-fee-recipient=0x01234567722E6b0000012BFEBf6177F1D2e9758D9
is the only thing i need to change is the address??? to me ,is :prysm.bat beacon-chain --http-web3provider=//./pipe/geth.ipc --suggested-fee-recipient=0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,   "//./pipe/geth.ipc "do not need to change?

**Comment by james-prysm** [comment]
responded in another issue you opened

**Comment by james-prysm** [comment]
There are other flags you need and the --http-web3provider flag has changed https://docs.prylabs.network/docs/prepare-for-merge you'll find the correct flags and changes in the merge doc we prepared.

**Comment by james-prysm** [comment]
closing for being stale...
