### ISSUE TITLE
error could not connect to execution client endpoint error=could not dia1 execution node:no known transport for URL scheme"C"

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#11337]
error could not connect to execution client endpoint error=could not dia1 execution node:no known transport for URL scheme"C"

windows 10 .

**Comment by prestonvanloon** [comment]
@navy665180 could you share what flag value you used for `--execution-endpoint` or `--http-web3provider`?

**Comment by james-prysm** [comment]
stale... no response from user.
