### ISSUE TITLE
Missing timeouts for some builder requests

### ISSUE THREAD

**Issue by jtraglia** [prysmaticlabs/prysm#11358]
# 💎 Issue

### Background

I was looking at the builder endpoint in Prysm. Making sure that everything looks right.

### Description

[There is a timeout for getting the block header](https://github.com/jtraglia/prysm/blob/436792fe385134611376a54b03bb7e5f6264eaf7/beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go#L390) but I don't see timeouts for the other builder requests:

* [Getting the builder status](https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/api/client/builder/client.go#L265)
* [Submitting validator registration](https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/api/client/builder/client.go#L218)
* [Getting a payload from the builder](https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/api/client/builder/client.go#L245)

What would happen if the builder/relay keeps the connection open and doesn't return anything?

There is a `WithTimeout` wrapper in the builder client, but it is unused:

https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/api/client/builder/client.go#L37-L42

A while ago, I made [an issue in the builder-specs](https://github.com/ethereum/builder-specs/issues/35) regarding timeouts; wondering if they should be clearly stated in the specs or not. We came to the conclusion that it shouldn't be mandated, but if there is a problem it would be a bug.

**Comment by terencechain** [comment]
`Getting the builder status`: we only call this once at start. If the builder status fails, then we mark the builder as unhealthy. We use the default HTTP timeout for this. I don't feel too strongly about aligning with the spec unless someone feels strongly about it 
`Submitting validator registration`: the timeout is on the validator client side. It used to timeout quite a lot but ever since then it's been fixed
`Getting a payload from the builder`: we use the default timeout here because eitherway the proposer is missing the block

**Comment by jtraglia** [comment]
Thank you, @terencechain. You're right. I needed to go up a few more calls. Sorry, I'm still getting used to Prysm.

This is the timeout (deadline) for validator registrations and proposals, right? It has until the end of the slot.

https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/validator/client/runner.go#L107-L110

> we use the default timeout here because either way the proposer is missing the block

Yes, after submitting the signed header there's no going back.

So yeah nevermind, this looks fine. Thanks again!

**Comment by terencechain** [comment]
Thanks for the review. Really appreciate it! <3
