### ISSUE TITLE
Set checkpoint-sync flag on synced node

### ISSUE THREAD

**Issue by muang0** [prysmaticlabs/prysm#11376]
# 💎 Issue
When started with checkpoint-sync arguments, can prysm choose between checkpoint-sync provided state and existing db finalized head (if db already exists for node)?  Or maybe even just skip loading checkpoint-sync configured state if db is populated with any state?

### Background

(Nice-to-have) in prod environments if there was some issue that required db wipe/new volume, teams could recover by falling back on checkpoint-sync without having to update prysm arguments.  This could also pair nicely with #10410 for teams that don't want to rely on an external api

**Comment by prestonvanloon** [comment]
I don't think we will implement this. If a prod environment is already wiping a volume then they can add a flag too.
