### ISSUE TITLE
Unable to connect to peer nodes on prysm (Goerli)

### ISSUE THREAD

**Issue by FahdW** [prysmaticlabs/prysm#11382]
```
[2022-09-01 02:02:15]  WARN powchain: Unable to cache headers for execution client votes error=(1661916256 > 1660182359): provided time is later than the current eth1 head
[2022-09-01 02:02:17]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2022-09-01 02:02:22]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2022-09-01 02:02:27]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0

```

This is pretty much what i am getting from Prysm as i try and run geth

I am on Geth 1.0.23 
Prysm 3.0.0

I have opened the ports approriately, my Geth was previously syncing and it can't get past the block that is the latest goerli block.

I performed a `geth removedb` but that seems to have yielded nothing because i previously ran this chain on snap mode, i am unsure if that is contributing to it. However Prysm just refuses to sync to a peer

**Comment by nisdas** [comment]
https://docs.prylabs.network/docs/install/install-with-script

You need to provide a genesis state for goerli, please look at our docs for the correct steps to run prysm.

**Comment by nisdas** [comment]
@FahdW Can you remove prysm's db from the data directory and try again ? It should be in `~/.eth2`

**Comment by nisdas** [comment]
Can you add to `--verbosity=debug` in prysm and paste the logs that you see

**Comment by nisdas** [comment]
@FahdW It doesn't appear you removed the old db. The debug logs are consistent with an older db. Can you confirm that you removed it ?

**Comment by nisdas** [comment]
What about your firewall ? Any restrictions on the machine prysm and geth are running on

**Comment by nisdas** [comment]
Is prysm able to make outbound connections from any port in your machine ?

**Comment by nisdas** [comment]
When you say 
> I have opened 12000 UDP and 13000 TCP

Do you mean you have opened these ports up for inbound connections ? Or are these only for outbound connections via your security group

**Comment by nisdas** [comment]
Ok so, you need to allow outbound udp connections from any port in your machine through your security group.
