### ISSUE TITLE
Flag to filter out builder profit

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11393]
We can add a CLI flag to filter out builder blocks based on builder profit (ex: `--builder-profit-threshold <wei value> `). If the builder's bid is below the threshold value then we default to using the local execution engine. Unfortunately, the local block's value can't be retrieved nor compared at this moment until engine-API support. Credit to @realbigsean for this idea

**Comment by realbigsean** [comment]
Thanks for the shoutout @terencechain  but I have to deflect the credit to @allboxes who raised an [issue](https://github.com/sigp/lighthouse/issues/3517) in our repo!
