### ISSUE TITLE
Increaes builder-api getPayload timeout to 3s

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11399]
We should increase getPayload timeout to 3s. Given once a signed header has been submitted, there's no other alternative, the node might as well wait longer to publish the block. Given attestations are broadcasted at 4s mark. 3s mark is a good value for timeout bound

**Comment by potuz** [comment]
Is this supposed to be for all cases or only when using an external builder and we have already sent a blinded block? I would agree with the latter, but not the former

**Comment by terencechain** [comment]
> Is this supposed to be for all cases or only when using an external builder and we have already sent a blinded block? I would agree with the latter, but not the former

My apology, I forgot engine-api also uses `getPayload`. My intent for this is only for external builder in the event that  blinded block has been signed and sent

**Comment by potuz** [comment]
> My apology, I forgot engine-api also uses `getPayload`. My intent for this is only for external builder in the event that blinded block has been signed and sent

Thinking a little more about this, it may be that the same timeout works for the local engine as well: if the local engine does not return a block anyway we're not proposing and there aren't options.

**Comment by terencechain** [comment]
> > My apology, I forgot engine-api also uses `getPayload`. My intent for this is only for external builder in the event that blinded block has been signed and sent
> 
> Thinking a little more about this, it may be that the same timeout works for the local engine as well: if the local engine does not return a block anyway we're not proposing and there aren't options.

that's a fine point. I also created #11404 that's inspired from your comment
