### ISSUE TITLE
ERROR main: could not process block: could not process block header: parent root  does not match the latest block header signing root in state

### ISSUE THREAD

**Issue by miguelmota** [prysmaticlabs/prysm#11405]
# 🐞 Bug Report

### Description

Can't finish syncing because of error `ERROR main: could not process block: could not process block header: parent root 0x7e535f17c96b293b70cf215adaa950dc5dfae51a10480186b2c2e52648386ddf does not match the latest block header signing root in state 0x8f531f5266ce77444d6c9af9eb9ae65740527b8408df1c6b90f823f5522559f9`

### Has this worked before in a previous version?

Yes version from a few months ago

## 🔬 Minimal Reproduction

```sh
docker run \
	--name beacon \
	-it \
	-d \
	--restart=unless-stopped \
	--network="host" \
	--log-driver local \
	--log-opt max-size=2gb \
	-p 4000:4000 \
	-p 13000:13000 \
	-p 12000:12000/udp \
	-p 3500:3500 \
	-v $HOME/.eth2_beacon_chain_data:/data \
	gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
	--datadir=/data \
	--rpc-host=0.0.0.0 \
	--grpc-gateway-host=0.0.0.0 \
	--monitoring-host=0.0.0.0 \
	--enable-debug-rpc-endpoints \
	--grpc-max-msg-size=65568081 \
	--accept-terms-of-use \
	--http-web3provider="$ETH1_PROVIDER"
```

## 🔥 Error

```sh
[2022-09-05 16:27:42]  WARN flags: Running on Ethereum Mainnet
[2022-09-05 16:27:42]  INFO node: Checking DB database-path=/data/beaconchaindata
[2022-09-05 16:27:42]  INFO db: Opening Bolt DB at /data/beaconchaindata/beaconchain.db
[2022-09-05 16:27:42]  INFO node: Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa
[2022-09-05 16:27:42] ERROR main: could not process block: could not process block header: parent root 0x7e535f17c96b293b70cf215adaa950dc5dfae51a10480186b2c2e52648386ddf does not match the latest block header signing root in state 0x8f531f5266ce77444d6c9af9eb9ae65740527b8408df1c6b90f823f5522559f9
```

## 🌍  Your Environment

**Operating System:**

```sh
Linux intelnuc 5.19.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 31 Aug 2022 22:09:40 +0000 x86_64 GNU/Linux
```

**What version of Prysm are you running? (Which release)**

```sh
REPOSITORY                                TAG        IMAGE ID       CREATED        SIZE
gcr.io/prysmaticlabs/prysm/beacon-chain   stable     6ea5cb3b5d8a   13 days ago    125MB
```

**Comment by potuz** [comment]
At this stage @miguelmota it is starting to look like you have some hardware problems, most likely memory. Specially given #11400, could we ask you to upload your database giving rise to any of these issues (if you can reproduce them consistently) so that we try them locally?

**Comment by potuz** [comment]
I believe this is a corrupt memory
 ```[2022-09-05 16:27:42] ERROR main: could not process block: could not process block header: parent root 0x7e535f17c96b293b70cf215adaa950dc5dfae51a10480186b2c2e52648386ddf does not match the latest block header signing root in state 0x8f531f5266ce77444d6c9af9eb9ae65740527b8408df1c6b90f823f5522559f9
```
The beacon block with that parent root is [this one](https://beaconcha.in/block/0x7e535f17c96b293b70cf215adaa950dc5dfae51a10480186b2c2e52648386ddf). The state root for the child block is `0x9f58880714984090e81ecb5e9f44dd875b585d800e4544b3226fb811d2d71817` instead of the reported one, so either we are processing a wrong block (the next missed/orphaned block is two epochs afterwards), or we are computing the wrong state root, or there's some memory corruption here. We could test this by getting a copy of the database and processing manually the state transition.

**Comment by miguelmota** [comment]
@potuz thanks for the response and suggestions. I replaced the memory modules and initiated a resync. I'll report back if there's any corrupt data errors but the bad memory seems like the root cause.
