### ISSUE TITLE
Critical 🔥: The validator keeps submitting outdated message to beacon node. "Sync Committee Message is too old to broadcast, discarding it"

### ISSUE THREAD

**Issue by nining** [prysmaticlabs/prysm#11415]
# 🐞 Bug Report

### Description

The validator keep submitting outdated message to beacon node.  

### Has this worked before in a previous version?

Never has this issue before

## 🔬 Minimal Reproduction

N/A

## 🔥 Error

<pre><code>

Here is the log from validator:
time="2022-09-08 08:02:03" level=info msg="Submitted new sync message" blockRoot=0x5fa482fc3bb6 prefix=validator slot=4647608 slotStartTime=2022-09-08 08:01:59 +0800 CST timeSinceSlotStart=4.005916114s validatorIndex=29352
time="2022-09-08 08:02:07" level=info msg="Submitted new sync contribution and proof" aggregatorIndex=29352 bitsCount=1 blockRoot=0x5fa482fc3bb6 prefix=validator slot=4647608 slotStartTime=2022-09-08 08:01:59 +0800 CST subcommitteeIndex=0 timeSinceSlotStart=8.003357728s

Here is the log from beacon node:
time="2022-09-08 16:47:27" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/4a26c58b/sync_committee_0/ssz_snappy - only 2 out of 1 peers were able to be found" prefix=p2p
time="2022-09-08 16:47:27" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message time 2022-09-08 16:47:11 +0800 CST (slot 4650234) not within allowable range of 2022-09-08 16:47:23 +0800 CST (slot 4650235) to 2022-09-08 16:47:28.172803507 +0800 CST m=+16522.728301869 (slot 4650235)" prefix=p2p

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.5 LTS
  </code>
</pre>

<pre>
  <code>
version:
beacon-chain-v3.1.0-linux-amd64
validator-v3.1.0-linux-amd64
  </code>
</pre>

validator index is 29352

**Comment by Tumble23** [comment]
This can be solved by (re)installing the chrony package on Ubuntu.  I think we may have lost it in an upgrade...

https://www.osradar.com/ntp-server-chrony-ubuntu/
