### ISSUE TITLE
Network or system error

### ISSUE THREAD

**Issue by VTsuprov** [prysmaticlabs/prysm#11423]
# 🐞 Bug Report

### Description

Evrthg worked well but the prysm has suddenly stopped connecting to the chain.
I use dappnode. The system reports that it works ok. But I cann't update any packages with Dappnode UI

## 🔬 Minimal Reproduction

So when i open the prysm UI I do not get any data from the validator. The interface is empty. And then i get the error

## 🔥 Error

{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 504,
  "statusText": "Gateway Timeout",
  "url": "http://prysm.dappnode/api/v2/validator/beacon/validators?page_size=1&page_token=0&public_keys=oC6Cn2rMS68oWtk2OOuVhKfN9e8HWAIhPHnGIHM8eva%2F43%2Fwu%2F1GgFchWKNDYddW&public_keys=",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://prysm.dappnode/api/v2/validator/beacon/validators?page_size=1&page_token=0&public_keys=oC6Cn2rMS68oWtk2OOuVhKfN9e8HWAIhPHnGIHM8eva%2F43%2Fwu%2F1GgFchWKNDYddW&public_keys=: 504 Gateway Timeout",
  "error": {
    "code": 4,
    "message": "context deadline exceeded",
    "details": []
  }
}

## 🌍  Your Environment

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.49
dappmanager.dnp.dappnode.eth: 0.2.44, commit: 7c9a6772
ipfs.dnp.dappnode.eth: 0.2.15
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8

**What version of Prysm are you running? (Which release)**

Version: 1.0.24 (v2.1.2 upstream)

**Anything else relevant (validator index / public key)?**
The validator prysm log in the dappnode contains errors:
time="2022-09-08 22:17:19" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator

The beacon-chain log also has errors:
time="2022-09-08 22:37:28" level=error msg="Could not connect to execution client endpoint: could not make initial request to verify execution chain ID: Post "http://geth.dappnode:8545": dial tcp 172.33.0.4:8545: connect: no route to host" prefix=powchain
time="2022-09-08 22:38:07" level=info msg="Peer summary" activePeers=37 inbound=0 outbound=37 prefix=p2p

**Comment by james-prysm** [comment]
stale, closing now
