### ISSUE TITLE
Runtime error after building prysm from source

### ISSUE THREAD

**Issue by willruggiano** [prysmaticlabs/prysm#11422]
I am trying to package prysm for nixpkgs, which means building the binaries from source.

I have been able to "successfully" build the project, however when I run it I get the following error;
```
panic: ERR Init curve=5

goroutine 1 [running]:
github.com/prysmaticlabs/prysm/v3/crypto/bls/herumi.HerumiInit()
        github.com/prysmaticlabs/prysm/v3/crypto/bls/herumi/init.go:8 +0x90
github.com/prysmaticlabs/prysm/v3/crypto/bls.init.0()
        github.com/prysmaticlabs/prysm/v3/crypto/bls/bls.go:14 +0x17
```

As a disclaimer, I am not familiar with the source code of prysm (or its dependencies); I just run some validator nodes and am looking to use Nix/OS as my underlying operating system.

Any suggestions on how to further debug this error?

**Comment by willruggiano** [comment]
I am running the following, which yields that error;
```
beacon-chain --help
```
where `beacon-chain` is the binary that has been built locally

**Comment by nisdas** [comment]
Hey @willruggiano , 

This appears to be an issue with running with herumi. It isn't able to initialize the bls curve correctly. 
https://github.com/herumi/bls-eth-go-binary/blob/master/bls/bls.go#L49

This is indicative of some possible incompatibility with mcl.

**Comment by rauljordan** [comment]
hi @willruggiano are you still experiencing this issue?

**Comment by willruggiano** [comment]
I ended up downloading the binaries and just patching them with patchelf.

See: https://github.com/willruggiano/eth-nix/blob/main/packages/prysm/default.nix

It works for my purposes so I haven’t tried to build the project from source again
