### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [prysmaticlabs/prysm#11430]
# 💎 Issue

Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string `js-libp2p/0.36.2` to `lodestar/version`. We are requesting an update to your client on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug purposes. We will not implement until it has been completed between all the various clients on the network.

**Comment by nisdas** [comment]
Hey @philknows , thanks for the ping. @rauljordan we can probably fix this in our client identification metrics to check for both `js-libp2p` and `lodestar`

**Comment by philknows** [comment]
Hi @nisdas and @rauljordan! Any updates on when this may get implemented in Prysm? Thanks!

**Comment by nisdas** [comment]
Hey @philknows , 

Will take a look at this today/this week. Its a simple change on our end.
