### ISSUE TITLE
Add option to log full ssz data on rejected gossip messages

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#11431]
Learned from @ajsutton that this is what Teku does and it's very handy, for example we remove invalid blocks from DB, we may keep the data in the logs.

**Comment by ajsutton** [comment]
This is useful, but worth noting that it is a potential DoS vector as you can wind up logging quite a lot if someone keeps sending you large invalid messages.  You'll likely want to only enable it on nodes not doing anything else important.
