### ISSUE TITLE
`accounts backup` creates a `name` field, should be `description`

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#11437]
# 🐞 Bug Report

### Description

When using `accounts backup`, the resulting keystore-0.json is incorrectly formatted: It contains a `name` field, which should be `description` as per [EIP-2335](https://eips.ethereum.org/EIPS/eip-2335#description).

This causes import into Nimbus to fail.

## Sample

```
{
        "crypto": {
                "checksum": {
                        "function": "sha256",
                        "message": "2bdf079e6dc7982f76a6a30e01629efb5a2de3353e107e4e81409e5110c9abbb",
                        "params": {}
                },
                "cipher": {
                        "function": "aes-128-ctr",
                        "message": "1fa5fe7ac721cece0475d4fa23af164f22ee870b22910512f06457d272044e6e",
                        "params": {
                                "iv": "4ba02f9dc303837f9b3cca50c923259e"
                        }
                },
                "kdf": {
                        "function": "pbkdf2",
                        "message": "",
                        "params": {
                                "c": 262144,
                                "dklen": 32,
                                "prf": "hmac-sha256",
                                "salt": "5344de5e69637b11d1c42ae667806e52ed7eeb047cc68b31fca771a4d530b2f9"
                        }
                }
        },
        "uuid": "de9e4aec-87cb-41ad-ad96-039fcf3175db",
        "pubkey": "8ed78a5495b54d5b6cc8bf170534ecb633b9694fba121ca680744fa9633f1b67cc77c045f88a6f97be781fe6c2867646",
        "version": 4,
        "name": "keystore",
        "path": ""
}
```

## 🌍  Your Environment

Ubuntu 22.04, docker

Prysm v3.1.1

**Comment by sleepyqadir** [comment]
@prestonvanloon can you assign this task to me?

**Comment by yorickdowne** [comment]
Jim comments that he needs this to remain `name`. And to resolve this by "You could tweak the JSON in passing to change 'name' to 'description'.". 

Reason as to why this is a wontfix in his library: "description isn't unique, whereas name is.  This was a long-ago argument, but we require the name field to be present and unique as it is commonly used as the reference for the account."

**Comment by prestonvanloon** [comment]
@sleepyqadir Thank you!

@yorickdowne That seems reasonable. We could map description to name and the inverse as well.

**Comment by mratsim** [comment]
> Jim comments that he needs this to remain `name`. And to resolve this by "You could tweak the JSON in passing to change 'name' to 'description'.".
> 
> Reason as to why this is a wontfix in his library: "description isn't unique, whereas name is. This was a long-ago argument, but we require the name field to be present and unique as it is commonly used as the reference for the account."

I think the spec (EIP-2335) needs to be rediscussed and eventually modified to support the current limitations then. Otherwise we'll get many varying implementations for a prime attack target.
