### ISSUE TITLE
Prysm REST API does not work for sync committee

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#11436]
# 🐞 Bug Report

### Description

Lighthouse VC v3.1.0 towards Prysm REST API v3.1.1

Lighthouse VC shows this error:

```
validator_1             | Sep 12 12:33:18.001 INFO All validators active                   slot: 3873166, epoch: 121036, total_validators: 2, active_validators: 2, current_epoch_proposers: 0, service: notifier
validator_1             | Sep 12 12:33:24.002 WARN Failed to download sync committee duties, error: All endpoints failed http://consensus:5052/ => RequestFailed(Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("consensus")), port: Some(5052), path: "/eth/v1/validator/duties/sync/120832", query: None, fragment: None }, source: TimedOut })), sync_committee_period: 472, service: duties
validator_1             | Sep 12 12:33:24.037 INFO Connected to beacon node                endpoint: http://consensus:5052/, version: Prysm/v3.1.1 (linux amd64)
```

It appears `eth/v1/validator/duties/sync/` is not implemented in Prysm's REST API

### Has this worked before in a previous version?

Unknown

## 🌍  Your Environment

Ubuntu 22.04, docker

## Prysm startup parameters

For reference, this is how the Prysm CL is started:

```
      - docker-entrypoint.sh
      - beacon-chain
      - --datadir
      - /var/lib/prysm/
      - --rpc-host
      - 0.0.0.0
      - --grpc-gateway-host
      - 0.0.0.0
      - --grpc-gateway-port
      - ${CL_REST_PORT:-5052}
      - --execution-endpoint
      - ${EL_NODE}
      - --jwt-secret
      - /var/lib/prysm/ee-secret/jwtsecret
      - --p2p-tcp-port
      - ${PRYSM_PORT}
      - --p2p-udp-port
      - ${PRYSM_UDP_PORT}
      - --p2p-max-peers
      - ${CL_MAX_PEER_COUNT:-45}
      - --verbosity
      - ${LOG_LEVEL}
      - --${NETWORK}
      - --accept-terms-of-use
      - --monitoring-host
      - 0.0.0.0
      - --monitoring-port
      - "8008"
      - --suggested-fee-recipient
      - ${FEE_RECIPIENT}
```

`docker-entrypoint.sh` adds additional parameters as desired, such as checkpoint sync, mev-boost.

**Comment by rkapka** [comment]
I think this is a timeout issue as per `source: TimedOut`. Will look into this.

**Comment by rkapka** [comment]
I am querying `/eth/v1/validator/duties/sync/120832` on Prater and it gives me the response in a few seconds. You can try increasing the timeout with the `--api-timeout` flag.

**Comment by yorickdowne** [comment]
Hey sorry for sending you down a rabbit hole! I think I overloaded this machine. I was trying to track down a connection issue, but I think in the process of trying to reproduce it I didn't give the clients enough resources.

Thank you for taking the time to have a look. If I find what caused the Vouch<->Prysm issue, I'll open a new github issue for it.
