### ISSUE TITLE
Next state slot cache audit and improvements

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11432]
Opening this issue to track audit and improvement for the next slot state cache
We suspect the next state slot cache has some issues given the `next_slot_cache_miss` count.
We also know specific issues exist, such that
- It doesn't cache well in the event of a skip slot. 31-> one won't work because it's only cached up to 0. So we will still need to process 0->1. This can improve together with skip slot fcu call 
- There's only one entry, and it expects the subsequent retrieval to be based on the last processed block. This won't work with reorgs. We can improve upon from 1 entry to 2-3 entries

**Comment by terencechain** [comment]
#11433 also prompts a good question on why we can't leverage skip slot state cache for next slot state cache

**Comment by nisdas** [comment]
I think we have spent a large chunk of our time over the last few months on this. I will consider this resolved, unless @terencechain @potuz feel strongly otherwise.
