### ISSUE TITLE
Handle Race When Initializing The P2P Service

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#11444]
# 🐞 Bug Report

### Description

Currently if we initialize a libp2p host without initializing the peer manager in time, this could 
cause a panic.

Bug Found By Antithesis.

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

It would be possible to trigger this for nodes running via a preknown/static identity at startup. If they are constantly dialed in from
inbound peers.

## 🔥 Error

```
panic: runtime error: invalid memory address or nil pointer dereference
segmentation violation code=0x1 addr=0x50 pc=0x14ed43e]

goroutine 222 [running]:
github.com/prysmaticlabs/prysm/v3/beacon-chain/p2p.(*Service).isPeerAtLimit(0xc000312900, 0x1)
/git/src/github.com/prysmaticlabs/prysm/beacon-chain/p2p/discovery.go:460 +0x3e
github.com/prysmaticlabs/prysm/v3/beacon-chain/p2p.(*Service).InterceptAccept(0xc000312900, {0x7f6d3a0b6d60, 0xc0037abb00})
/git/src/github.com/prysmaticlabs/prysm/beacon-chain/p2p/connection_gater.go:56 +0xa5
[github.com/libp2p/go-libp2p/p2p/net/upgrader.(*listener).handleIncoming(0xc0002101c0)
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.20.3/p2p/net/upgrader/listener.go:87 +0x172
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).UpgradeListener
/root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.20.3/p2p/net/upgrader/upgrader.go:111 +0x225
```

**What version of Prysm are you running? (Which release)**

`57b7e0b57252eacd79ea64b5a25c6ab32ee42da9`

**Comment by dyng** [comment]
Hi @nisdas , I want to help on this issue, can you provide more informations? The line number in stack trace does not match the source in `57b7e0b57252eacd79ea64b5a25c6ab32ee42da9` well and I can't say which object is nil with confidence. Thanks!

**Comment by dyng** [comment]
@nisdas Thanks for your explanation, I'm working on this now. Will update here if any progress.

**Comment by dyng** [comment]
Hi @nisdas, I think a simple solution that 'deny all incoming connection when `peers` is not ready' should work fine in this case, but not sure if it's ok to do like that. Do you have any suggestion?

**Comment by nisdas** [comment]
@dyng That seems like it would make sense, I don't have any opposition to the solution.
