### ISSUE TITLE
What happens with full node if Prysm not synced yet

### ISSUE THREAD

**Issue by izidorit** [prysmaticlabs/prysm#11447]
Hi Guys,

Sorry for opening this but I don't find the answer anywhere, and I'm afraid the worst will happen. We have 4 full nodes for ethereum mainnet, which will change to POS tomorrow.
I prepared GETH and PRYSM, but I'm very much concerned what will happen with our node, if PRYSM hasn't synced yet, and merge will happen?
It says in the logs it's ready "Ready for The Merge", but I can see it needs 40h more...Can someone answer what will happen tomorrow?

```
Sep 14 17:11:09 srv09 prysm.sh[145119]: time="2022-09-14 17:11:09" level=info msg="Processing block batch of size 62 starting from  0xe2d74eb4... 2399551/4695953 - estimated time remaining 40h30m3s" blocksPerSecond=15.8 peers=51 prefix=initial-sync
Sep 14 17:11:11 srv09 prysm.sh[145119]: time="2022-09-14 17:11:11" level=info msg="Ready for The Merge" latestDifficulty=58712522006955327774482 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
Sep 14 17:11:13 srv09 prysm.sh[145119]: time="2022-09-14 17:11:13" level=info msg="Processing block batch of size 63 starting from  0x46bce7d5... 2399615/4695954 - estimated time remaining 40h22m17s" blocksPerSecond=15.8 peers=56 prefix=initial-sync
```

Thank you in advance for your help!

**Comment by rauljordan** [comment]
Hi Izidorit are you part of our discord? Come in and we can help https://discord.gg/prysmaticlabs

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: izidorit ***@***.***>
Sent: Wednesday, September 14, 2022 1:25:56 PM
To: prysmaticlabs/prysm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [prysmaticlabs/prysm] What happens with full node if Prysm not synced yet (Issue #11447)


Hi Guys,

Sorry for opening this but I don't find the answer anywhere, and I'm afraid the worst will happen. We have 4 full nodes for ethereum mainnet, which will change to POS tomorrow.
I prepared GETH and PRYSM, but I'm very much concerned what will happen with our node, if PRYSM hasn't synced yet, and merge will happen?
It says in the logs it's ready "Ready for The Merge", but I can see it needs 40h more...Can someone answer what will happen tomorrow?

Sep 14 17:11:09 srv09 prysm.sh[145119]: time="2022-09-14 17:11:09" level=info msg="Processing block batch of size 62 starting from  0xe2d74eb4... 2399551/4695953 - estimated time remaining 40h30m3s" blocksPerSecond=15.8 peers=51 prefix=initial-sync
Sep 14 17:11:11 srv09 prysm.sh[145119]: time="2022-09-14 17:11:11" level=info msg="Ready for The Merge" latestDifficulty=58712522006955327774482 network=mainnet prefix=powchain terminalDifficulty=58750000000000000000000
Sep 14 17:11:13 srv09 prysm.sh[145119]: time="2022-09-14 17:11:13" level=info msg="Processing block batch of size 63 starting from  0x46bce7d5... 2399615/4695954 - estimated time remaining 40h22m17s" blocksPerSecond=15.8 peers=56 prefix=initial-sync


Thank you in advance for your help!

**Comment by stellaro15** [comment]
Any specific reason why people should go to some gaming platform to receive support for project-related questions? There are a lot of emerging issues after the merge and we hope you guys aren't spending your time on gaming instead of working on Prysm.

**Comment by stellaro15** [comment]
Any specific reason why people should go to some gaming platform to seek support for project-related questions? There are a lot of emerging issues after the merge and we hope you guys aren't spending your time on video games instead of working on Prysm.

**Comment by prestonvanloon** [comment]
The execution node would stop until a consensus client synced. You need both to stay with the chain after the merge.

**Comment by stellaro15** [comment]
> The execution node would stop until a consensus client synced. You need both to stay with the chain after the merge.

That didn't happen at all, now a lot of people get out-of-synced Geth. Your post-merge integration for Geth is completely broken and there are lots of other issues emerging right now that you ignore.

I get now why you guys are using Discord. Not being able to take constructive critics isn't a good start for this project, as deleting comments you dislike like a toddler won't get you anywhere.  Sadly, Golang community is a complete nightmare and people in Ethereum community must cope with amateur developers like you due to lack of mature projects written in C/C++.

**Comment by emrahsariboz** [comment]
> The execution node would stop until a consensus client synced. You need both to stay with the chain after the merge.

So that means the execution client will not start syncing until Prysm finishes sync?

**Comment by prestonvanloon** [comment]
> > The execution node would stop until a consensus client synced. You need both to stay with the chain after the merge.
> 
> So that means the execution client will not start syncing until Prysm finishes sync?

It means that the execution client will sync up until the last proof of work block, then it needs a consensus client to continue. I could be wrong, I haven't tried it myself, but that is how I understand it.
