### ISSUE TITLE
what happened with this 

### ISSUE THREAD

**Issue by Ericalvin** [prysmaticlabs/prysm#11448]
Hi every one, 
I run a Geth and Prysm,  and prysm log say "Ready for The Merge", but still "initial-sync: Processing block batch of size", now already merge, what should i do ? wait the "initial-sync" finish ? 

`[2022-09-15 07:00:50]  WARN powchain: Execution client is not syncing`
`[2022-09-15 07:00:41]  INFO initial-sync: Processing block batch of size 62 starting from  0x3b65eb41... 1674130/4700126 - estimated time remaining 38h7m13s blocksPerSecond=22.1 peers=41`

thank you!

**Comment by Sreeram1993** [comment]
Its because your beacon chain is not synced till merge slot. Wait for the beacon chain to sync. Then it will connect with geth node and run together.

**Comment by prestonvanloon** [comment]
Thanks @Sreeram1993, that is correct. The execution client has halted until prysm is synced enough to drive it.

**Comment by rotsen11** [comment]
Enviado desde mi iPhoneEl 15 sep 2022, a la(s) 8:41, Sreeram J ***@***.***> escribió:﻿
Its because your beacon chain is not synced till merge slot. Wait for the beacon chain to sync. Then it will connect with geth node and run together.

**Comment by Ericalvin** [comment]
@Sreeram1993 @prestonvanloon  thank you.

**Comment by rotsen11** [comment]
- [ ] @rotsen11
