### ISSUE TITLE
prysm time issue

### ISSUE THREAD

**Issue by Ericalvin** [prysmaticlabs/prysm#11466]
Hi, every one,
I run prysm+geth on the same host, and my prysm log say:
`Unable to cache headers for execution client votes error=(1663488087 > 1663322891): provided time is later than the current eth1 head`

how to fix this ? thank you.

**Comment by zhaomengru2015** [comment]
same issue here 
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/9380107/190956293-0cf78fff-c7f5-4d40-82a5-210801d5f93d.png">

**Comment by anchorite01** [comment]
Me too
![image](https://user-images.githubusercontent.com/40764351/190959378-d051be63-052f-447a-beb3-24a658f82a2d.png)

**Comment by Ericalvin** [comment]
@zhaomengru2015 @anchorite01  I think i know the cause of error , it look like geth was not fully synced, my geth is sync finish now, then prysm log  no longer show those log.

**Comment by zhaomengru2015** [comment]
@Ericalvin thanks for your reply
but my geth node stuck with error
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/9380107/190992411-5c83dfe6-ef9f-4e5d-b41a-c35282671c0c.png">

**Comment by zhaomengru2015** [comment]
@Ericalvin thanks for your reply, but my geth stuck with error
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/9380107/190996003-66a28096-4a8f-48a6-a5a4-d9c01e8d9700.png">
anything I can do to fix that?

**Comment by terencechain** [comment]
Which prysm version? Afaik, the warning is removed in the latest release

**Comment by prestonvanloon** [comment]
@terencechain that warning was not removed.

https://github.com/prysmaticlabs/prysm/blob/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930/beacon-chain/execution/service.go#L541-L549

**Comment by prestonvanloon** [comment]
I suspect this is an issue only during initial syncing, when the execution client (eth1) head is still behind the requested block header cache range. 

The warning can be safely ignored during initial sync. However if you are seeing these issues once both clients are fully synced, then it is a bigger issue. 

In any case, I think the UX needs to be improved in Prysm

**Comment by terencechain** [comment]
My bad, looks like this PR didn't make it to 3.1.1: https://github.com/prysmaticlabs/prysm/pull/11398

I think the UX can still be improved. Maybe we can change logging to `Unable to cache headers for execution client votes, perhaps your execution layer client is still syncing`

**Comment by anchorite01** [comment]
> Which prysm version? Afaik, the warning is removed in the latest release
Thanks for your recovery，I deleted geth's data and resynced and it's ok now

**Comment by james-prysm** [comment]
Closing this issue as user mentioned it's working ok now.
