### ISSUE TITLE
No proposal for 20 days with 10 validators, is this normal?

### ISSUE THREAD

**Issue by tunlong** [prysmaticlabs/prysm#11465]
# 💎 Issue
I'm running 10 validators solo. It is a very long time I don't get a proposal since Aug 31. No error log found with below program. It seems erverything is fine, just no proposal. So I wanna know is this normal? 
prysm 3.1.1
geth 1.10.25
mev 1.3.1
![image](https://user-images.githubusercontent.com/32350461/190940799-adb07dae-0e34-4405-ac7c-c79da92b235c.png)

**Comment by skillful-alex** [comment]
It can be normal.
But to understand exactly, you need to see what the status of the validator is, and whether attestations are sent to them. For example on https://beaconcha.in/

**Comment by prestonvanloon** [comment]
Proposers are selected at random. Given that this is random, you might not get a block for 100 days and you might get 100 blocks in one day.  You should expect each of your validators to propose 4 to 6 blocks per year, on average. 

With that said, I don't believe there is any technical issue here.

**Comment by tunlong** [comment]
> It can be normal. But to understand exactly, you need to see what the status of the validator is, and whether attestations are sent to them. For example on https://beaconcha.in/

I have checked the status on beaconcha.in. The attestations is good enough, even no misss attestation.
