### ISSUE TITLE
Fetching beacon block through API triggers relay request

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#11481]
# 🐞 Bug Report

### Description

When an attempt to obtain a beacon block via the `/eth/v2/validator/blocks/{slot}` is made to a beacon node configured with an MEV relay, the beacon node erroneously contacts that MEV relay.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

- configure prysm with the `--http-mev-relay` option
- attempt to fetch a block via the REST API with the `/eth/v2/validator/blocks/{slot}` endpoint

## 🔥 Error

A call to ` /eth/v2/validator/blocks/{slot}` should not attempt to contact MEV relays.  This call must return a complete beacon block proposal, which requires a complete execution payload.  It cannot obtain this from the MEV relay at this point in the process, so instead should obtain a complete execution payload from its connected execution node.

**Comment by prestonvanloon** [comment]
@mcdee Could you help point to the part in the specification that says a block retrieved from `/eth/v2/validator/blocks/{slot}` must be a block produced by a local execution node? In review of #11488, I was struggling to find this information.

**Comment by mcdee** [comment]
https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/produceBlockV2 states that the returned object is a `BeaconBlock`, not a `BlindedBeaconBlock`.  As such, the block must return a full `ExecutionPayload`.  MEV-boost relays do not provide an `ExecutionPayload`, only an `ExecutionPayloadHeader`, prior to being presented with a signed `BeaconBlockHeader`.  Hence it is not possible for `/eth/v2/validator/blocks/{slot}` to use the information provided by the MEV relay in its response, and calling it is superfluous and slows down the response.

**Comment by prestonvanloon** [comment]
Thanks @mcdee. That makes sense!
