### ISSUE TITLE
mev-boost context deadline exceeded

### ISSUE THREAD

**Issue by Chaz27** [prysmaticlabs/prysm#11490]
# 💎 Issue

I've setup mev-boost locally and connected to the endpoint via the beacon node config --http-mev-relay="http://localhost:18550".
However both times trying to retrieve a block I've received the error message "context deadline exceeded". I'm guessing this is a timeout error?

> ERROR rpc/validator: Failed to build a block from external builder, falling back to local execution client error=could not get payload header: Get "http://localhost:18550/eth/v1/builder/header/xxxxxxx/xxxxxxx/xxxxxxx": context deadline exceeded

In the mev-boost logs, there are no errors, all requests have success 200. However what I did notice is the last request took 0.941017 seconds to process. I'm guessing there is some lag time between my server (not US based) and wherever the relays are.

What timeout limit does prysm run for these relay requests? Are there any options to increase this and if so, do you then run the risk of being late on a block proposal? Or perhaps is there a way to request the block slightly earlier to account for the delay?

**Comment by prestonvanloon** [comment]
The builder API specification says honest proposers must abort the SignedBuilderBid request after 1s. 

https://github.com/ethereum/builder-specs/blob/main/specs/validator.md#relation-to-local-block-building

This timeout is not configurable in Prysm. Consider using a different relay or local block production only.

**Comment by terencechain** [comment]
I believe this is related and somewhat addressed by: https://github.com/prysmaticlabs/prysm/pull/11413
