### ISSUE TITLE
could not read JWT secret file for authenticating execution API

### ISSUE THREAD

**Issue by kapisolec** [prysmaticlabs/prysm#11509]
# 💎 Cannot open JWT secret file

### Description

 Hello, I'm trying to sync my own Ethereum fullnode after the merge. I decided to use prysm beacon node and I constantly get the error:
```
[2022-09-28 18:01:47] ERROR main: could not read JWT secret file for authenticating execution API: open /root/jwtsecret: no such file or directory
```

I've got no clue why it's happening. If I run my geth execution client it works just fine (it says loaded jwtsecret succesfully). Only when I try to use the consensus client I get the error. Obviously there is a *jwtsecret* file at `/root/` directory

My run command is:

```
docker run -it -v $HOME/.eth2:/data -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node \
  gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
  --datadir=/data \
  --jwt-secret=/root/jwtsecret \
  --rpc-host=0.0.0.0 \
  --grpc-gateway-host=0.0.0.0 \
  --monitoring-host=0.0.0.0 \
  --execution-endpoint=/root/.ethereum/geth.ipc
  ```

**Comment by james-prysm** [comment]
From the error it's definitely saying that the path is not accessible, since it's running from docker maybe the relative path/absolute path is not what it's expected to be.

**Comment by prestonvanloon** [comment]
@kapisolec You must make that file available to you docker container. You did a volume mount for `$HOME/.eth2` but did not do a volume mount for `/root`

**Comment by kapisolec** [comment]
Thank you very much, I mounted /root volume and it worked, thanks!

**Comment by achakhalyan** [comment]
Hi, I also have that problem can You help me too?
`could not read JWT secret file for authenticating execution API: open /root/ethereum/consensus/jwt.hex: no such file or directory`
