### ISSUE TITLE
Prysm Validator Node's multiple beacon endpoints with TLS are not working.

### ISSUE THREAD

**Issue by sungjun-kdac** [prysmaticlabs/prysm#11505]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...
I runned one prysm validator node as follows.
--beacon-rpc-provider=xxx.xxx.xxx.xxx:4000,yyy.yyy.yyy.yyy:4000
 --tls-cert=/config/tls/ca.cert
But validator node is not working.
In case of --beacon-rpc-provider=xxx.xxx.xxx.xxx:4000 only one parameter, It is working well.
Is it bug?

### Has this worked before in a previous version?
Not working.

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>
time="2022-09-27 12:56:13" level=warning msg="Could not determine if beacon chain started" error="could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for eth2.node, not xxx.xxx.xxx.xxx:4000,yyy.yyy.yyy.yyy:4000": could not connect" prefix=validator

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**
<pre>
  <code>
Prysm Beacon Node Version : v3.1.1
Prysm Validator Node Version : v3.1.1
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rohrerman** [comment]
:+1:
I would welcome this feature! At the moment I am running a backup-cl-el-machine...
