### ISSUE TITLE
beaconchain.db Archive Data Will Quickly Exceed the 16TB File Size Limit on EXT4 Filesystems

### ISSUE THREAD

**Issue by ymonye** [prysmaticlabs/prysm#11518]
Hi,

As I'm currently synching an archive mainnet instance of Prysm, I'd noticed everything is kept in a single file (beacondchain.db) which is already at 4TB. I can always accommodate by migrating to XFS RAID arrays, but this would be an issue once it approaches the 16TB file size limit for users on EXT4 formatted RAID arrays.

Does the team plan to split the beaconchain.db data into multiple files?

**Comment by prestonvanloon** [comment]
@ymonye What is the value for `--slots-per-archive-point=`? 

Using multiple files would require a different database backend. We currently use [bbolt](https://pkg.go.dev/go.etcd.io/bbolt). It would be a considerable effort to add a different database backend, but it is possible

**Comment by ymonye** [comment]
> @ymonye What is the value for `--slots-per-archive-point=`?
> 
> Using multiple files would require a different database backend. We currently use [bbolt](https://pkg.go.dev/go.etcd.io/bbolt). It would be a considerable effort to add a different database backend, but it is possible

Hey Preston, I have this value at 1. I just double-checked your docs and saw the recommended value is a multiple of 32... my mistake there. Could that be why my db built up so quickly to 4TB?

**Comment by potuz** [comment]
> Could that be why my db built up so quickly to 4TB?

Certainly, 32 or even 128 would work fine for an archive node

**Comment by ymonye** [comment]
> > Could that be why my db built up so quickly to 4TB?
> 
> Certainly, 32 or even 128 would work fine for an archive node

Thank you!
