### ISSUE TITLE
Empty Block. Txs on EC but not seen anything on Prysm 

### ISSUE THREAD

**Issue by PacoBits** [prysmaticlabs/prysm#11516]
We produced a empty block: https://etherscan.io/block/15637620 

This issue is reproducible on mainnet and prater using this setup:

We have a 3-layer configuration with the validator client, the Beacon node  and the execution client running separately.

These are our current versions and configs:

```
Validator set up - version: Lighthouse/v3.1.2-01e84b7
         lighthouse vc
         --beacon-nodes http://prsym,http://lh_fallback
         --network mainnet
         --metrics
         --metrics-allow-origin *
         --graffiti "Block by Stakely Lido04"
         --suggested-fee-recipient 0x388C818CA8B9251b393131C08a736A67ccB19297
         --init-slashing-protection
         --metrics-port 4067

```

```
PRYSM Beacon  set up - Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930. Built at: 2022-09-09 21:18:25+00:00
...
    network_mode: host
    volumes:
      - /xx/xxx/prysm-data/:/data
      - /xx/xxx/merge_besu_prysm.hex:/merge_jwt
    command: >-
      --datadir=/data
      --rpc-host=0.0.0.0
      --monitoring-host=127.0.0.1
      --execution-endpoint=http://x.x.x.x:8551
      --jwt-secret /merge_jwt
      --subscribe-all-subnets=true
      --mainnet
      --accept-terms-of-use
      --grpc-gateway-host 0.0.0.0
      --checkpoint-sync-url=http://x.x.x.x:xx
      --genesis-beacon-api-url=http://x.x.x.x:xx
      --suggested-fee-recipient  xxxx
```

```
Execution Client - besu/v22.7.4/linux-x86_64/openjdk-java-11
...
    network_mode: host
    volumes:
      - /xx/xxx/besu-data/:/var/lib/besu
      - /xx/xxx/merge_besu_prysm.hex:/var/lib/merge_jwt
    command: >-
      --rpc-http-enabled
      --data-path=/var/lib/besu
      --network=mainnet
      --engine-rpc-http-port=8551
      --engine-jwt-secret=/var/lib/merge_jwt
      --engine-jwt-enabled=true
      --engine-host-allowlist="*"
      --engine-rpc-enabled
      --rpc-http-api=ADMIN,TXPOOL,DEBUG,ETH,NET
      --host-allowlist="*"
```

The attached logs shows block was generated by besu with 276 transactions, but prysm doesnt shows any info and finally block is published with 0 tx:
Validator client log (no more info related to block on Validator Client):
`Successfully published block\cf0             slot: 4801150, graffiti: Some("Block by Stakely Lido04"), attestations: 128, deposits: 0, block_type: Full, service: block`

We are stuck on this problem since merge on prater. Its reproducible at anytime on prater and mainnet. 
[besu29092022.log](https://github.com/prysmaticlabs/prysm/files/9681660/besu29092022.log)
[prysm29092022.log](https://github.com/prysmaticlabs/prysm/files/9681661/prysm29092022.log)

**Comment by potuz** [comment]
Besu's log shows 
```
besu_latest | 2022-09-29 07:50:23.120+00:00 | vert.x-worker-thread-0 | INFO  | EngineGetPayload | Fetch block proposal by identifier: 0x00000000678e1db4, hash: 0x38dd24b7c70d00e5e5731ac6fa43bd50e7ad1e595dd07aca64d14c524f4d0f5b, number: 15637620, coinbase: 0x388c818ca8b9251b393               131c08a736a67ccb19297, transaction count: 0
```
Which is the block that was published with zero transactions, and then later shows
```
besu_latest | 2022-09-29 07:50:26.629+00:00 | EthScheduler-Computation-0 | INFO  | MergeCoordinator | Successfully built block 15637620 (0x2ebb788240d29463fda65eea54568dc0d9df44d41e27608cf1bdea16b3770dc7) for proposal identified by 0x00000000678e1db4, with 276 transactions, in                3523ms
```
that it built the block with the same identifier in 3.5 seconds. I am guessing that there is a timeout going on here, hinting to a Besu bug. 

On the other hand, Besu's logs also show something strange: there are many different `newPayloads` in sequence, and only few  FCU. It would be nice to know if they do not log every FCU received.  The last FCU received by Besu before the block fetch is 
```
besu_latest | 2022-09-29 07:49:38.632+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xfd652371a6e32022aa881fe1acf6231b90bac2335deeab1d6282c3abfeb2d32d, finalized: 0x1628b1e4a5e31942f77f30bbc57bcd8d8e3df63cd8a2b2f2ef52509               1e2a25797, safeBlockHash: 0xdd6cc218bacffc30bea8c1b12d5e4b59f0a8019a6b16db30cdae463834b9a046
```
Which corresponds to the block in slot `4801146`, that's 4 blocks before the proposal. If those logs are accurate, then probably what happened is that prysm didn't give any time to Besu to produce the block. This is backed up by the logs:

The logs show that Besu started producing the block 3.5 seconds before `07:50:26.629`, that is `07:50:23.106`. This is only 14ms before the fetch message. So it seems that Besu started producing the block at the same time that it was requested one. 

So the question here is whether there is a bug in Besu not caring/logging for the FCUs that prysm sent, or there is a bug in Prysm not sending FCUs. From prysms logs there is nothing wrong, it acted as it was supposed to, but it's hard to tell without debug logs.

**Comment by potuz** [comment]
Confirmed with Besu that they don't log all FCUs so fixing #11520 should close this issue. Can we probably mark it as duplicate?

**Comment by fab-10** [comment]
Looking at the Besu logs, the GetPayload was called shortly after the FcU call with the payload parameters, and so only the empty block was ready at that time, and it was returned, concurrently the better one was still building but if was ready too late. We are evaluating strategies to mitigate this kind of scenario and avoid returning an empty block.
