### ISSUE TITLE
Expose current sync committee and next sync committee per pubkey in the validator prometheus metrics

### ISSUE THREAD

**Issue by ybstaked** [prysmaticlabs/prysm#11522]
# 🚀 Feature Request

### Description

Mainly need to know two things (from sync committee perspective):
- which pubkey is in a sync committee currently
- which pubkey will be in a sync committee next

If we're really concerned about data, then as a baseline, even just knowing that the validator has one of the keys in sync committee currently and/or next would be useful to expose via prometheus, so we can plan maintenance at the validator level (which is managing for us ~200-300 pubkeys) accordingly.  

### Describe the solution you'd like

Expose prometheus metric per pubkey in the validator metrics

### Describe alternatives you've considered

I've looked at https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet/part-ii-maintenance/checking-my-eth-validators-sync-committee-duties already, but would like to have this via prometheus

### Links:
- [Prysmatic Labs code-review channel discord conversation with potuz and prestonvanloon](https://discord.com/channels/476244492043812875/483017808658169866/1025450792112631848)

**Comment by ybstaked** [comment]
@prestonvanloon or @potuz any updates on this?

**Comment by ybstaked** [comment]
This does not even have to be per pubkey, just need to know per VC process whether or not (binary) it has any validator keys that are currently in sync committee, so we can know whether or not to do any maintenance on the VC process (upgrades, etc.)

**Comment by ybstaked** [comment]
linking this new discord convo with potuz: https://discord.com/channels/476244492043812875/781210739762397234/1062012591892877424

**Comment by terencechain** [comment]
Closing this in favor of https://github.com/prysmaticlabs/prysm/issues/12521
