### ISSUE TITLE
Beacon api `GetProposerDuties` does not cache proposers for next slot

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11520]
Related [11516](https://github.com/prysmaticlabs/prysm/issues/11516)

For an EE to prepare a payload in advance, the beacon node must know the to-be-served proposers at the current epoch. If at slot `N`, the beacon node knows it is serving a proposer at `N+1`. The beacon node will call FCU with a payload attribute. Or else the beacon node will not do that.

We currently do this for prysm-api, but we do not do this for beacon-API: https://github.com/prysmaticlabs/prysm/blob/211c5c2c5c5760a7f8966db26262d78853d0b388/beacon-chain/rpc/eth/validator/validator.go#L126

This, unfortunately, make beacon-API unsafe to use. When we fix this, we should do an audit for beacon-API to ensure all the prysm-API functionalities are carried over

**Comment by potuz** [comment]
Related to #11516 (note that this does not explain the lack of FCU logs in that issue)
