### ISSUE TITLE
`--monitor-indices` doesn't produce expected `INFO: monitor` output

### ISSUE THREAD

**Issue by mick-prysm** [prysmaticlabs/prysm#11532]
# 🐞 Bug Report

### Description

`--monitor-indices` doesn't produce expected output. [Docs set the expectation](https://docs.prylabs.network/docs/prysm-usage/individual-validator-monitoring) that `beacon-chain --monitor-indices 1` will generate output `INFO monitor: "Starting service" ValidatorIndices="[1 2 12 15]"`. I don't see this using 3.1.1:

![Untitled](https://user-images.githubusercontent.com/103775631/193621048-cf6e8393-204c-4968-b6bf-37e0d941e6fa.png)

### Has this worked before in a previous version?

Not sure.

## 🔬 Minimal Reproduction

For Windows:

 1. `curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.bat --output prysm.bat`
 2. `prysm.bat beacon-chain --monitor-indices 1`
 3. Expect `INFO monitor:` output, don't see it.

## 🔥 Error

No `INFO` output indicating that Prysm is monitoring the specified validator index.

## 🌍  Your Environment

Win11 / Prysm 3.1.1

Related docs issue: https://github.com/prysmaticlabs/documentation/issues/640

**Comment by nisdas** [comment]
@potuz any ideas ?

**Comment by potuz** [comment]
> @potuz any ideas ?

Something broke in the cli parsing of integer slices. It's returning nil here: https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/node/node.go#L933
without any bandwitdh to look at it now

**Comment by nisdas** [comment]
Np, will look at this now. I suspect updating our cli library broke some things.
