### ISSUE TITLE
Potential block packing weakness in algorithm

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#11548]
# 🐞 Bug Report

Mainnet block 4864065 was possibly generated by prysm (as per blockprint).  If so, it shows a weakness in prysm's block packing algorithm where it prefers low-value attestations with a lower inclusion distance than high-value attestations with a higher inclusion distance.

### Description

Block 4864064 included no attestations (due to an issue with a different client).  this means that come the time that 4864065's proposal the attestation pool should contain a large number of attestations for both blocks 4864063 and 4864064.  however, looking at the attestations in block 4864065 they are exclusively for block 4864064.  The block packing starts off well, with attestations containing large numbers of highly populated aggregate attestations with the correct votes and inclusion distance of 1, however jumping down to the last attestation in the block it only had 8 votes, 5 of which were duplicates from prior attestations in the same block.  This, and a number of slots above it, would have served better by including one of the highly populated aggregate attestations with distance 2.

(Note that I am making an assumption here that there were attestations for block 4864063 in the attestation pool at this time, however if not we likely have a bigger problem!  The block was received by nodes around the 2 second mark, so it wasn't delivered late and should have been attested to.  It was also built upon for the block 4864064.  Finally, even if it were received late then the attestation pool should still have had lots of highly populated aggregate attestations with correct source/target that should have been worth more than some of the attestations included in the block.)

### Has this worked before in a previous version?

Unknown.  Note that the prysm version here is also unknown, because this was seen on the network but not generated by a specific known node.

**Comment by potuz** [comment]
There's a trade-off here in that it's preferable to have attestations with the right target for the current epoch as justification is more important than validator earnings. But it's a great find, we need to discuss the design around this

**Comment by mcdee** [comment]
This may be a larger discussion, then, but in my opinion the rewards for any attestation should be totally aligned with their value to the chain.  If that is not the case then we should revisit the rewards so that they are, otherwise we will end up with a conflict between what is best for the chain Vs .what is best for the proposer (at least in this specific situation).

**Comment by terencechain** [comment]
I'm going to close this but feel free to open if we need to push it forward
