### ISSUE TITLE
Builder validator registration not working with parameter: --proposer-settings-file

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#11554]
# 🐞 Bug Report

### Description

To activate MEV, I added the following '2 parameters' to the validator config:
--enable-builder
--suggested-fee-recipient=xxx

This works and I see a validator log entry: `"Submitted builder validator registration settings for custom builders"`

However the moment I add parameter `--proposer-settings-file` (with a valid json file), it no longer registers my validator for custom builders.

### Has this worked before in a previous version?
n/a

## 🔬 Minimal Reproduction
Take a validator where MEV is working.

Then add parameter `--proposer-settings-file` with a proposer-setting-json-file.
(the existing '2 parameter' that worked are still there btw. I only added this one)
My json looks like below and the validator is not complaining about its structure or values.
Note that it says enable= true under validator_registration. It also has a fee_recipient.
{
  "proposer_config": {
    "0x...................................": {
      "fee_recipient": "0x..........",
      "validator_registration": {
        "enabled": true,
        "gas_limit": 30000000
      }
    }
  },
  "default_config": {
    "fee_recipient": "0x...........",
      "validator_registration": {
        "enabled": true,
        "gas_limit": 30000000
      }
  }
}

Now restart the validator. It will no longer submit the validator registration settings.

## 🔥 Error

n/a

## 🌍  Your Environment

**Operating System:**

Ubuntu
validator version Prysm/v3.1.1/653ea3b030c3bb99aa3f3d95a8de9f4d6e147930. Built at: 2022-09-09 17:24:18+00:00

**Comment by james-prysm** [comment]
the log may not print because the value may already be cached. did you check on your custom builder that the value is not included?

**Comment by handelaar2** [comment]
That was indeed the issue.  `builder`(json) and `--enable-builder`  both work, but with  `validator_registration`(json) and `--enable-validator-registration`, only the latter works. PrysmaticLabs should really update the below link. Its current state (old) will put a lot of people on the wrong foot.
https://boost.flashbots.net/mev-boost-status-updates/mev-boost-status-update-sep-9-sept-22-2022
 
![2022-10-18_07-54-25](https://user-images.githubusercontent.com/28559038/196347092-3ba566de-175f-44f0-8091-9d143205bc65.png)

https://hackmd.io/@prysmaticlabs/BJeinxFsq. <==============

![2022-10-18_07-57-01](https://user-images.githubusercontent.com/28559038/196347561-aad97e05-8f74-405f-a07f-d3fa006770ae.png)
