### ISSUE TITLE
Feature Request: Validator flag to bypass confirmation prompt when exiting

### ISSUE THREAD

**Issue by cprivitera** [prysmaticlabs/prysm#11573]
Source: https://docs.prylabs.network/docs/wallet/exiting-a-validator

Request: (how can we help?)

Is there a way to bypass the prompt when exiting a validator? Is there a flag to accept-voluntary-exit?

**Comment by prestonvanloon** [comment]
@cprivitera I have transferred this request to a feature request for Prysm.

**Comment by rkapka** [comment]
I would like to see it as a wallet setting.

**Comment by potuz** [comment]
> I would like to see it as a wallet setting, given that exiting is a wallet command.

Aren't we moving this to prysmctl?

**Comment by rkapka** [comment]
We will support both prysmctl and the validator client until Prysm v4

**Comment by rkapka** [comment]
After some thought I decided to go with a flag instead of a wallet setting. It will be much easier to implement,
