### ISSUE TITLE
Implement per valdiator reward API

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11581]
Some of these APIs that @michaelsproul proposed provide excellent visibility to validator performances, I think Prysm should consider them and even better promote them to be part of the beacon API standard 

https://github.com/sigp/lighthouse/issues/3661

**Comment by terencechain** [comment]
> If these metrics can be exposed by the beacon monitor and the standard is agnostic to who is exporting these metrics then I think we should implement these in the monitor. I don't like the fact that we're computing validator metrics repeatedly now and would want to deprecate validator client metrics in favor of the beacon ones

I agree that we should remove validator client metrics and promote beacon node side monitoring metrics

**Comment by potuz** [comment]
@sproul explained that I had a misconception of what this API is about. The beacon monitor will not be a place for these. The monitor could be the natural consumer of this endpoints in order to export tracking metrics. But the API and the endpoints themselves need to be in the beacon
