### ISSUE TITLE
Make payload an interface in beacon state

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11604]
In `beacon-chain/state/state-native/beacon_state_mainnet.go`, instead of having:

```go
type BeaconState struct {
	latestExecutionPayloadHeader        *enginev1.ExecutionPayloadHeader        `ssz-gen:"true"`
	latestExecutionPayloadHeaderCapella *enginev1.ExecutionPayloadHeaderCapella `ssz-gen:"true"`
}
```

we should just have:
```go
type BeaconState struct {
	executionData interfaces.ExecutionData
}
```

Where `ExecutionData` is the superset. This avoids boating the beacon state with more fields of payload whenever it's updated in the future. This is much cleaner

Note that `ssz-gen` currently is unused and can be removed

credit to @Inphi for pointing this out

**Comment by prestonvanloon** [comment]
Does this change how ssz-gen will work? I think it needs to know the underlying type

**Comment by terencechain** [comment]
> Does this change how ssz-gen will work? I think it needs to know the underlying type

I don't think beacon state uses ``ssz-gen:"true"``, the SSZ marshal/unmarshal is done through native protobuf iirc
the SSZ hashtreeroot is hand crafted

**Comment by prestonvanloon** [comment]
> I don't think beacon state uses ssz-gen:"true", the SSZ marshal/unmarshal is done through native protobuf iirc
the SSZ hashtreeroot is hand crafted

OK -- it was in your description which is why i mentioned it. Why is it in the description?

**Comment by prestonvanloon** [comment]
Discussed the ssz-gen issue offline. @rkapka is there a plan to use ssz-gen for native state or can we remove those unused struct tags?

**Comment by terencechain** [comment]
> > I don't think beacon state uses ssz-gen:"true", the SSZ marshal/unmarshal is done through native protobuf iirc
> > the SSZ hashtreeroot is hand crafted
> 
> OK -- it was in your description which is why i mentioned it. Why is it in the description?

Sorry. I copied and pasted from the codebase. I'll remove them now

**Comment by Inphi** [comment]
I can look into doing this if no one else is. Would rather have this resolved sooner rather than later to simplify the upstream EIP-4844 implementation.

**Comment by terencechain** [comment]
Thanks @Inphi ! I dont think anyone else is working on this
