### ISSUE TITLE
successive reduction in validator balance on ropsten ?

### ISSUE THREAD

**Issue by garyng2000** [prysmaticlabs/prysm#11625]
given that ropsten will be gone soon(it is still working as I can still submit tx to EL and the CL is still syncing), I am using it to test the final leg of the process(voluntary exit) and observe something I can't explain.

I am seeing a constant reduction in validator balances on each epoch(may not be related to exit as one of them is active, the other is still in exiting state and it is still participating in the attestation, based on the validator log). what would cause something like this ?

a side question is when will the state changed from 'exiting' to 'exited' ? it has been about 48 hours passed and it is still not removed from the CL(still attesting). I would assume not that many are queuing for exit.

**Comment by rkapka** [comment]
> a side question is when will the state changed from 'exiting' to 'exited' ? it has been about 48 hours passed and it is still not removed from the CL(still attesting). I would assume not that many are queuing for exit.

You will need to wait at least for at least `MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 256` epochs, which is around 27 hours, plus the time needed for your validator to be processed through the ext queue. It seems like it should have exited by now.

**Comment by james-prysm** [comment]
Circling back on this is this still an issue?

**Comment by garyng2000** [comment]
it finally changed from 4 to 6, after I think 3 weeks. so still function as expected. ropsten really is on its final days as the balances of those active are constantly decreasing each epoch. But that is not a concern to me anymore assuming it is a network thing and my test of the full cycle has been completed. this ticket can be closed.
