### ISSUE TITLE
Memory consumption rising to 100% with 128GB RAM

### ISSUE THREAD

**Issue by PandamineHub** [prysmaticlabs/prysm#11627]
Hello all, could you please help me? I am facing issue with memory consumption. When I run prysm it consistently increase memory consumption higher and higher up to almost 100% and I have 128GB RAM. Before sometimes it happened when I was runnning slasher, now its happening with and without --slasher as well.

running prysm v3.1.2

**Comment by PandamineHub** [comment]
Hello nisdas,

ExecStart=/home/panda/ethereum/consensus/prysm/./prysm.sh beacon-chain --mainnet --execution-endpoint=/home/panda/ethereum/execution/geth.ipc --p2p-max-peers 50 --slasher --datadir /home/panda/ethereum/consensus --suggested-fee-recipient="My address"

**Comment by nisdas** [comment]
@PandamineHub You can try a fresh sync. If you constantly move between slasher( and no slasher) flag it causes a lot of disk fragmentation with your db. This could lead to what you saw above, you can try checkpoint sync:
https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by PandamineHub** [comment]
I did not move between slasher and no-slasher, it happenned today that my memory consumption rised to 110GB, so I have restarted prysm, but didnt help, then I only tried to run without slasher, but didnt help as well

**Comment by nisdas** [comment]
How long have you been running with a slasher ?

**Comment by PandamineHub** [comment]
from beginning as I know, for months..

**Comment by nisdas** [comment]
So 2 years ?

**Comment by nisdas** [comment]
Do you know how big is your database right now ?

**Comment by nisdas** [comment]
I would recommend using checkpoint sync to get back online, and removing your current db if you want to have your validators online soon.

**Comment by PandamineHub** [comment]
When I remove db and use checkpoint sync, the whole database will download again or not? Do I need to reconfigure it later or can I use checkpoint sync from now forever?

**Comment by prestonvanloon** [comment]
When we update to go1.19 (https://github.com/prysmaticlabs/prysm/pull/11630), we can introduce a memory limit flag or users can set GOMEMORYLIMIT environment variable. 

See the changes in "Runtime" of the release notes https://tip.golang.org/doc/go1.19

**Comment by PandamineHub** [comment]
Hello, how can I delete SLASHER DB?

**Comment by james-prysm** [comment]
Please reach out on discord to continue the discussion, this issue seems user-specific.
