### ISSUE TITLE
When trying to run beacon chain recieving error slice out of bounds

### ISSUE THREAD

**Issue by A-Link-To-The-Future** [prysmaticlabs/prysm#11626]
After running

./prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=jwt.hex --suggested-fee-recipient=0x*

ERROR main: Runtime panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647

I am running the latest stable release of ubuntu.

**Comment by nisdas** [comment]
@A-Link-To-The-Future Do you mind pasting the whole panic ? Otherwise its hard for us to investigate this

**Comment by A-Link-To-The-Future** [comment]
2022-11-06 18:23:08] ERROR main: Runtime panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647
goroutine 1 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
main.main.func2()
	cmd/beacon-chain/main.go:211 +0x45
panic({0x552ea0, 0xc000056198})
	GOROOT/src/runtime/panic.go:838 +0x207
go.etcd.io/bbolt.unsafeByteSlice(...)
	external/io_etcd_go_bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
	external/io_etcd_go_bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x0?)
	external/io_etcd_go_bbolt/cursor.go:328 +0x96
sort.Search(0x7f42497775b8?, 0xc004fc8fa8)
	GOROOT/src/sort/search.go:66 +0x48
go.etcd.io/bbolt.(*Cursor).nsearch(0x4be3a0?, {0x2e3fc78?, 0x0?, 0x0?})
	external/io_etcd_go_bbolt/cursor.go:327 +0x105
go.etcd.io/bbolt.(*Cursor).search(0xc001671178, {0x2e3fc78, 0xc, 0xc}, 0xc0016710d0?)
	external/io_etcd_go_bbolt/cursor.go:257 +0x1f5
go.etcd.io/bbolt.(*Cursor).seek(0xc004fc9178, {0x2e3fc78?, 0x183a8a5?, 0xc001671108?})
	external/io_etcd_go_bbolt/cursor.go:159 +0x48
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc0004da0f8, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:167 +0xe6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0x183a1a5?, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:201 +0x31
go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)
	external/io_etcd_go_bbolt/tx.go:115
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.createBuckets(0xc0004da0e0, {0xc004fc9330?, 0x19, 0x311a340?})
	beacon-chain/db/kv/kv.go:250 +0x75
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore.func1(0x7f42497775b8?)
	beacon-chain/db/kv/kv.go:158 +0x4a6
go.etcd.io/bbolt.(*DB).Update(0xc0001001e0?, 0x91e640)
	external/io_etcd_go_bbolt/db.go:694 +0x82
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore({0xba4468?, 0xc001656000}, {0xc00014f770, 0x2a})
	beacon-chain/db/kv/kv.go:157 +0x430
github.com/prysmaticlabs/prysm/v3/beacon-chain/db.NewDB(...)
	beacon-chain/db/db.go:13
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.(*BeaconNode).startDB(0xc0004a2140, 0x0?, {0x802a7a, 0x2a})
	beacon-chain/node/node.go:359 +0x25d
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.New(0xc000a21dc0, {0xc00169fd18, 0x3, 0x183704d?})
	beacon-chain/node/node.go:189 +0xb05
main.startNode(0xc000a06000?)
	cmd/beacon-chain/main.go:288 +0x5ab
github.com/urfave/cli/v2.(*App).RunContext(0xc000514000, {0xba44a0?, 0xc00012e000}, {0xc00012c000, 0x4, 0x4})
	external/com_github_urfave_cli_v2/app.go:350 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:247
main.main()
	cmd/beacon-chain/main.go:216 +0x1d5

panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647 [recovered]
	panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647

goroutine 1 [running]:
main.main.func2()
	cmd/beacon-chain/main.go:212 +0xd4
panic({0x552ea0, 0xc000056198})
	GOROOT/src/runtime/panic.go:838 +0x207
go.etcd.io/bbolt.unsafeByteSlice(...)
	external/io_etcd_go_bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
	external/io_etcd_go_bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x0?)
	external/io_etcd_go_bbolt/cursor.go:328 +0x96
sort.Search(0x7f42497775b8?, 0xc004fc8fa8)
	GOROOT/src/sort/search.go:66 +0x48
go.etcd.io/bbolt.(*Cursor).nsearch(0x4be3a0?, {0x2e3fc78?, 0x0?, 0x0?})
	external/io_etcd_go_bbolt/cursor.go:327 +0x105
go.etcd.io/bbolt.(*Cursor).search(0xc001671178, {0x2e3fc78, 0xc, 0xc}, 0xc0016710d0?)
	external/io_etcd_go_bbolt/cursor.go:257 +0x1f5
go.etcd.io/bbolt.(*Cursor).seek(0xc004fc9178, {0x2e3fc78?, 0x183a8a5?, 0xc001671108?})
	external/io_etcd_go_bbolt/cursor.go:159 +0x48
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc0004da0f8, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:167 +0xe6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0x183a1a5?, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:201 +0x31
go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)
	external/io_etcd_go_bbolt/tx.go:115
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.createBuckets(0xc0004da0e0, {0xc004fc9330?, 0x19, 0x311a340?})
	beacon-chain/db/kv/kv.go:250 +0x75
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore.func1(0x7f42497775b8?)
	beacon-chain/db/kv/kv.go:158 +0x4a6
go.etcd.io/bbolt.(*DB).Update(0xc0001001e0?, 0x91e640)
	external/io_etcd_go_bbolt/db.go:694 +0x82
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore({0xba4468?, 0xc001656000}, {0xc00014f770, 0x2a})
	beacon-chain/db/kv/kv.go:157 +0x430
github.com/prysmaticlabs/prysm/v3/beacon-chain/db.NewDB(...)
	beacon-chain/db/db.go:13
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.(*BeaconNode).startDB(0xc0004a2140, 0x0?, {0x802a7a, 0x2a})
	beacon-chain/node/node.go:359 +0x25d
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.New(0xc000a21dc0, {0xc00169fd18, 0x3, 0x183704d?})
	beacon-chain/node/node.go:189 +0xb05
main.startNode(0xc000a06000?)
	cmd/beacon-chain/main.go:288 +0x5ab
github.com/urfave/cli/v2.(*App).RunContext(0xc000514000, {0xba44a0?, 0xc00012e000}, {0xc00012c000, 0x4, 0x4})
	external/com_github_urfave_cli_v2/app.go:350 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:247
main.main()
	cmd/beacon-chain/main.go:216 +0x1d5

**Comment by nisdas** [comment]
This might indicate that your db has been corrupted

**Comment by A-Link-To-The-Future** [comment]
what steps should i take to renew my db then?

**Comment by nisdas** [comment]
You can take a look here:
https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by A-Link-To-The-Future** [comment]
./prysm.sh beacon-chain --checkpoint-sync-url=http://localhost:3500 --genesis-beacon-api-url=http://localhost:3500
ran this command and recieved the same error

**Comment by A-Link-To-The-Future** [comment]
[2022-11-06 18:33:50] ERROR main: Runtime panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647
goroutine 1 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
main.main.func2()
	cmd/beacon-chain/main.go:211 +0x45
panic({0x552ea0, 0xc00013a3f0})
	GOROOT/src/runtime/panic.go:838 +0x207
go.etcd.io/bbolt.unsafeByteSlice(...)
	external/io_etcd_go_bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
	external/io_etcd_go_bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x0?)
	external/io_etcd_go_bbolt/cursor.go:328 +0x96
sort.Search(0x7f80c6fed108?, 0xc004f56fa8)
	GOROOT/src/sort/search.go:66 +0x48
go.etcd.io/bbolt.(*Cursor).nsearch(0x4be3a0?, {0x2e3fc78?, 0x0?, 0x0?})
	external/io_etcd_go_bbolt/cursor.go:327 +0x105
go.etcd.io/bbolt.(*Cursor).search(0xc00230f178, {0x2e3fc78, 0xc, 0xc}, 0xc00230f0d0?)
	external/io_etcd_go_bbolt/cursor.go:257 +0x1f5
go.etcd.io/bbolt.(*Cursor).seek(0xc004f57178, {0x2e3fc78?, 0x183a8a5?, 0xc00230f108?})
	external/io_etcd_go_bbolt/cursor.go:159 +0x48
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc00057c0f8, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:167 +0xe6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0x183a1a5?, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:201 +0x31
go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)
	external/io_etcd_go_bbolt/tx.go:115
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.createBuckets(0xc00057c0e0, {0xc004f57330?, 0x19, 0x311a340?})
	beacon-chain/db/kv/kv.go:250 +0x75
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore.func1(0x7f80c6fed108?)
	beacon-chain/db/kv/kv.go:158 +0x4a6
go.etcd.io/bbolt.(*DB).Update(0xc000b02230?, 0x91e640)
	external/io_etcd_go_bbolt/db.go:694 +0x82
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore({0xba4468?, 0xc001448000}, {0xc0000582a0, 0x2a})
	beacon-chain/db/kv/kv.go:157 +0x430
github.com/prysmaticlabs/prysm/v3/beacon-chain/db.NewDB(...)
	beacon-chain/db/db.go:13
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.(*BeaconNode).startDB(0xc00041c140, 0x0?, {0x802a7a, 0x2a})
	beacon-chain/node/node.go:359 +0x25d
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.New(0xc000b22300, {0xc0003fa8a0, 0x5, 0x183704d?})
	beacon-chain/node/node.go:189 +0xb05
main.startNode(0xc000b08000?)
	cmd/beacon-chain/main.go:288 +0x5ab
github.com/urfave/cli/v2.(*App).RunContext(0xc00037ba00, {0xba44a0?, 0xc00012c000}, {0xc000114150, 0x3, 0x3})
	external/com_github_urfave_cli_v2/app.go:350 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:247
main.main()
	cmd/beacon-chain/main.go:216 +0x1d5

panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647 [recovered]
	panic: runtime error: slice bounds out of range [::2474945000] with length 2147483647

goroutine 1 [running]:
main.main.func2()
	cmd/beacon-chain/main.go:212 +0xd4
panic({0x552ea0, 0xc00013a3f0})
	GOROOT/src/runtime/panic.go:838 +0x207
go.etcd.io/bbolt.unsafeByteSlice(...)
	external/io_etcd_go_bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
	external/io_etcd_go_bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x0?)
	external/io_etcd_go_bbolt/cursor.go:328 +0x96
sort.Search(0x7f80c6fed108?, 0xc004f56fa8)
	GOROOT/src/sort/search.go:66 +0x48
go.etcd.io/bbolt.(*Cursor).nsearch(0x4be3a0?, {0x2e3fc78?, 0x0?, 0x0?})
	external/io_etcd_go_bbolt/cursor.go:327 +0x105
go.etcd.io/bbolt.(*Cursor).search(0xc00230f178, {0x2e3fc78, 0xc, 0xc}, 0xc00230f0d0?)
	external/io_etcd_go_bbolt/cursor.go:257 +0x1f5
go.etcd.io/bbolt.(*Cursor).seek(0xc004f57178, {0x2e3fc78?, 0x183a8a5?, 0xc00230f108?})
	external/io_etcd_go_bbolt/cursor.go:159 +0x48
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc00057c0f8, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:167 +0xe6
go.etcd.io/bbolt.(*Bucket).CreateBucketIfNotExists(0x183a1a5?, {0x2e3fc78, 0xc, 0xc})
	external/io_etcd_go_bbolt/bucket.go:201 +0x31
go.etcd.io/bbolt.(*Tx).CreateBucketIfNotExists(...)
	external/io_etcd_go_bbolt/tx.go:115
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.createBuckets(0xc00057c0e0, {0xc004f57330?, 0x19, 0x311a340?})
	beacon-chain/db/kv/kv.go:250 +0x75
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore.func1(0x7f80c6fed108?)
	beacon-chain/db/kv/kv.go:158 +0x4a6
go.etcd.io/bbolt.(*DB).Update(0xc000b02230?, 0x91e640)
	external/io_etcd_go_bbolt/db.go:694 +0x82
github.com/prysmaticlabs/prysm/v3/beacon-chain/db/kv.NewKVStore({0xba4468?, 0xc001448000}, {0xc0000582a0, 0x2a})
	beacon-chain/db/kv/kv.go:157 +0x430
github.com/prysmaticlabs/prysm/v3/beacon-chain/db.NewDB(...)
	beacon-chain/db/db.go:13
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.(*BeaconNode).startDB(0xc00041c140, 0x0?, {0x802a7a, 0x2a})
	beacon-chain/node/node.go:359 +0x25d
github.com/prysmaticlabs/prysm/v3/beacon-chain/node.New(0xc000b22300, {0xc0003fa8a0, 0x5, 0x183704d?})
	beacon-chain/node/node.go:189 +0xb05
main.startNode(0xc000b08000?)
	cmd/beacon-chain/main.go:288 +0x5ab
github.com/urfave/cli/v2.(*App).RunContext(0xc00037ba00, {0xba44a0?, 0xc00012c000}, {0xc000114150, 0x3, 0x3})
	external/com_github_urfave_cli_v2/app.go:350 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:247
main.main()
	cmd/beacon-chain/main.go:216 +0x1d5

**Comment by nisdas** [comment]
You need to remove your old db first. You can run it with `--clear-db` first

**Comment by A-Link-To-The-Future** [comment]
i'm still recieving the same error. should i manually remove beaconchain.db from the .eth2 folder?

**Comment by nisdas** [comment]
Yes, you can do that too

**Comment by A-Link-To-The-Future** [comment]
That appears to have worked, thank you!
