### ISSUE TITLE
The `dependent_root` value of API `eth/v1/validator/duties/proposer/{epoch}` is wrong.

### ISSUE THREAD

**Issue by yierx** [prysmaticlabs/prysm#11628]
# 🐞 Bug Report

### Description
API: https://ethereum.github.io/beacon-APIs/#/Validator/getProposerDuties

**get /eth/v1/validator/duties/proposer/157122**
returns
```
{
	"dependent_root": "0xd2079019489e13199234195d832452aba8cb8bc9086f90aeb9b355c49a99401c",
	"data": [...]
}
```

but the expected should be
```
{
	"dependent_root": "0xf5c9192534cffa0ea8e0b8b1e53021b99d855d66d8010d01fff8f083d9063163",
	"data": [...]
}
```

**Comment by james-prysm** [comment]
just wondering how did you get the expected dependent root, is it comparing it with another client?

**Comment by yierx** [comment]
@james-prysm the expected slot is 157122 * 32 - 1 = 5027903, so we can fetch the header info by calling get `/eth/v1/beacon/headers/5027903`, the result is 
```
{
	"data": {
		"root": "0xf5c9192534cffa0ea8e0b8b1e53021b99d855d66d8010d01fff8f083d9063163",
          ...
}
```

**Comment by yierx** [comment]
> The dependent_root value is get_block_root_at_slot(state, compute_start_slot_at_epoch(epoch) - 1)

https://ethereum.github.io/beacon-APIs/#/Validator/getProposerDuties
