### ISSUE TITLE
Hide Password File

### ISSUE THREAD

**Issue by bmmojo** [prysmaticlabs/prysm#11632]
# 💎 Issue

### Description

Hello, I wanted to know is it possible to hide the wallet password file in the command line? I'm concerned that if a threat actor was sitting on my network, they could take advantage of this and easily find this file. If you could point me to a guide that would be great!

`./prysm.sh accounts import --keys-dir=/Users/insertname/Documents/dev/staking_deposit-cli-#######-darwin-amd64/validator_keys --goerli --wallet-dir=./wallet --wallet-password-file=/Users/insertname/Documents/dev/staking_deposit-cli-#######-darwin-amd64/passwords/password.txt`
`./prysm.sh --wallet-dir=./wallet --goerli --wallet-password-file=/Users/insertname/Documents/dev/staking_deposit-cli-#######-darwin-amd64/passwords/password.txt`

**Comment by garyng2000** [comment]
the design is intended for server side usage so all precautions about how to protect these 'secret files' have to be taken. beside, a thread vector should not be able randomly access you file and even if they do, the max damage would be they can see your pubkey(or may be export it) and import it to another node which cause slashing/exit but would not be able to touch your balance as it is not stored at prysm level.

**Comment by bmmojo** [comment]
Great thank you @garyng2000
