### ISSUE TITLE
"Could not process deposit log" error message

### ISSUE THREAD

**Issue by Andrei-sys** [prysmaticlabs/prysm#11649]
Hello, updated CL with v3.1.2 and the node is fully synced but there are some weird error messages that don't know if I should take into consideration or not. Anyone encountered the same issue after the update?

level=info msg="Falling back to historical headers and logs sync. Current difference is 42059" prefix=powchain
level=error msg="Could not process deposit log: received incorrect merkle index: wanted 409932 but got 470819" prefix=powchain
level=info msg="Synced new block" block=0xa3074d5d... epoch=159515 finalizedEpoch=159513 finalizedRoot=0xb709e6be... prefix=blockchain

**Comment by nisdas** [comment]
Hey @Andrei-sys , 

which execution client is this with ?

**Comment by Andrei-sys** [comment]
Hi, Erigon v2022.10.01

**Comment by nisdas** [comment]
Ok this is a known erigon issue, you will have to ask the erigon team on it. Alternatively, restarting erigon has been said to work for it.

**Comment by Andrei-sys** [comment]
Ok...I see, will ask them then, thank you very much for your quick answer!
