### ISSUE TITLE
Add support for generating a new ND account

### ISSUE THREAD

**Issue by Karmastic** [prysmaticlabs/prysm#11641]
# 🚀 Feature Request

### Description

The `validator` CLI allows generating an ND wallet but only allows importing accounts into it.  It would be useful to be able to generate an account (BLS key for Validator) non-interactively from the CLI.

### Describe the solution you'd like

Currently we use `ethdo` for this but would like to eliminate that dependency for our key generation. Ethdo uses the `herumi/bls` package to accomplish this; prysm already includes this package as well for its BLS support, but does not expose a mechanism for creating a new key.

### Describe alternatives you've considered

There are other tools we could use to do this but we want to use one of the clients we currently support to reduce external dependencies.  Lighthouse only supports generating HD wallets and accounts non-interactively and we would like to keep using ND wallets. We have not approached the lighthouse team but will do so if we cannot get support added to prysm.

**Comment by potuz** [comment]
I think key generation belongs naturally on tooling and not on prysm itself, by adding key generation to prysm it increases the surface area for operator errors and very bad bugs that are not part of the core functionality of Prysm. Specialized and audited tooling exist for this motive and I don't see why should Prysm risk adding this functionality and getting it wrong.

**Comment by james-prysm** [comment]
> On key generation in prysm itself, it will be unlikely that we will be adding it in at the current stage. Pre- beacon-chain launch, we made the decision not to have prysm generate keys/wallets but instead only be able to import/recover. Users would use the staking cli to generate new keys and prysm would then import those. On keeping the dependency chain minimal, underneath Prysm depends on quite a few wealdtech/attestant libraries to handle the respective wallets. So underneath Prysm would still use wealdtech/attestant libraries to generate new keys if we were ever to have the feature 
-nishant

we can keep this one open to continue the discussion here.

**Comment by prestonvanloon** [comment]
This issue is 1 year old and there hasn't been much discussion. Closing this since ethdo is a viable solution. If herumi's library is the issue, consider proposing a change to ethdo to use [blst](https://github.com/supranational/blst).
