### ISSUE TITLE
cannot get peers with v3.1.2, but can with v3.1.1

### ISSUE THREAD

**Issue by chappjc** [prysmaticlabs/prysm#11643]
Between these minor patch releases, it goes from being able to get "suitable" peers to never getting any.  It's as simple as downgrading to v3.1.1 and prysm gets peers right away.  Switch to v3.1.2 and it just says `INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0` forever.

It is perfectly reproducible by switching between these two releases.  Immediate peers with v3.1.1, but never gets peers with v3.1.2.

If it is relevant, when 3.1.2 is searching for peers, I can only shutdown by forcing a panic with 10 interrupts.

**Comment by nisdas** [comment]
Hey @chappjc ,

This is related to https://github.com/libp2p/go-libp2p/issues/1849, we will have this patched by the next release. For now you can run with v3.1.1 .

**Comment by prestonvanloon** [comment]
@nisdas has this been fixed in develop branch? We are planning v3.1.3 now and need to know if this has been included.

**Comment by chappjc** [comment]
Resolved by https://github.com/prysmaticlabs/prysm/pull/11599
