### ISSUE TITLE
error in obtaining the beacon state

### ISSUE THREAD

**Issue by xichan-ms** [prysmaticlabs/prysm#11663]
when I query the beacon state by following api path, **always return 404**, however, other apis works.
/eth/v2/debug/beacon/states/{state_id}

is there any config wrong for my node or nit in api path? great thanks

![image](https://user-images.githubusercontent.com/26354131/201946160-7cf8fe95-cfb9-4020-924c-6d68a0f76cda.png)

**Comment by nisdas** [comment]
@xichan-ms You have to use the `--enable-debug-rpc-endpoints` flag , this will allow you access to the debug namespace

**Comment by james-prysm** [comment]
closing after informing the user, can reopen if it's a bug.
