### ISSUE TITLE
ERROR blockchain: Could not compute head from new attestations error=unknown justified root

### ISSUE THREAD

**Issue by A-Link-To-The-Future** [prysmaticlabs/prysm#11672]
Getting this error, when running beacon-chain. 
ERROR blockchain: Could not compute head from new attestations error=unknown justified root
also comes with warnings: Skip processing batched blocks error=beacon node doesn't have a parent in db with root:

**Comment by james-prysm** [comment]
Have you found a way to resolve this? gut is telling me that there was an unsafe shutdown that corrupted the db. you can try resyncing with checkpoint sync https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by adamkoch** [comment]
My beacon node randomly started showing this error today, after running fine for many months and is now missing attestations. I am using v3.1.2, logs show:
```
time="2022-12-12 22:33:14" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync
time="2022-12-12 22:33:47" level=error msg="Could not compute head from new attestations" error="unknown justified root" prefix=blockchain
time="2022-12-12 22:34:12" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-12-12 22:33:49" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x56638b8c13dd7b6ec19b497a04dc80d92880533c7251cc26c175a9aabfe557ab (in processBatchedBlocks, slot=5333696)" prefix=initial-sync
time="2022-12-12 22:34:23" level=error msg="Could not compute head from new attestations" error="unknown justified root" prefix=blockchain
time="2022-12-12 22:33:49" level=info msg="Processing block batch of size 64 starting from  0xc18f42e9... 5333632/5335067 - estimated time remaining 1m52s" blocksPerSecond=12.8 peers=51 prefix=initial-sync
time="2022-12-12 22:34:26" level=warning msg="Execution client is not syncing" prefix=powchain
time="2022-12-12 22:34:32" level=info msg="Processing block batch of size 64 starting from  0xc07f90cd... 5333440/5335070 - estimated time remaining 56s" blocksPerSecond=28.7 peers=51 prefix=initial-sync
time="2022-12-12 22:32:47" level=error msg="Could not compute head from new attestations" error="unknown justified root" prefix=blockchain
```

A restart did not help. I have cleared the beacon chain data and am trying to re-sync to get my node back online.

**Comment by nisdas** [comment]
This seems like an issue with your execution client, what are its logs ?

**Comment by adamkoch** [comment]
I think checkpoint sync is working, but I'm not sure how long it should take or what should show while it syncs.

Beacon node shows:
```
time="2022-12-12 23:07:44" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xa27e00af6e75 headPayloadBlockHash=0xee40473cd0ce headSlot=5335236 prefix=blockchain
time="2022-12-12 23:09:37" level=info msg="Peer summary" activePeers=50 inbound=26 outbound=24 prefix=p2p
```

Validator shows:
```
time="2022-12-12 23:06:48" level=info msg="Submitted builder validator registration settings for custom builders" prefix=validator
time="2022-12-12 23:07:39" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2022-12-12 23:07:55" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = Unavailable desc = the node is currently optimistic and cannot serve validators" prefix=validator pubKey=0x8f7a2cb65410 slot=5335237
```

Geth is showing:
```
Error: invalid merkle root (remote: b4a58fced6505b135e70b1ace3e308cef8f7f05bdda8edd0e04028b263fe5173 local: 2e4701dd484489a354954d388e5f2e7d6d5bfa4d55145f9162de23431e89c7f7)
##############################
 
ERROR[12-12|12:08:08.919] Beacon backfilling failed                err="retrieved hash chain is invalid: invalid merkle root (remote: b4a58fced6505b135e70b1ace3e308cef8f7f05bdda8edd0e04028b263fe5173 local: 2e4701dd484489a354954d388e5f2e7d6d5bfa4d55145f9162de23431e89c7f7)"
WARN [12-12|12:08:17.242] Marked new chain head as invalid         hash=5d016a..ad553f badnumber=16,166,786 badhash=a29274..38ec74
INFO [12-12|12:08:38.566] Looking for peers                        peercount=12 tried=25 static=0
WARN [12-12|12:08:48.080] Snapshot extension registration failed   peer=94a3e001 err="peer connected on snap without compatible eth support"
INFO [12-12|12:08:48.637] Looking for peers                        peercount=13 tried=37 static=0
WARN [12-12|12:08:48.972] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
INFO [12-12|12:08:58.644] Looking for peers                        peercount=14 tried=37 static=0
WARN [12-12|12:10:35.099] Snapshot extension registration failed   peer=94a3e001 err="peer connected on snap without compatible eth support"
WARN [12-12|12:13:29.773] Checkpoint challenge timed out, dropping id=1a8f6dc2279f063e conn=dyndial addr=3.225.199.99:30303 type=Geth/v1.10.26-stable...
INFO [12-12|12:13:31.066] Looking for peers                        peercount=16 tried=31 static=0
```

**Comment by adamkoch** [comment]
Ok I guess it was the execution client (geth) that broke. I'm still not sure what it suddenly stopped working. I have now rolled back geth a few days using [`debug.setHead()`](https://geth.ethereum.org/docs/rpc/ns-debug#debug_sethead) and while it is not yet sync'd and back online the logs for both geth and beacon don't have errors now and are just awaiting sync to catch up.

**Comment by cosmicnet** [comment]
I've hit this issue or similar. I noticed yesterday that prysm had crashed. When I restarted I was getting lots of the above errors along with lots of "error=beacon node doesn't have a parent in db with root". From geth I could see prysm must have crashed on the 28th. I didn't have much luck resetting it to a checkpoint, so I'm now resyncing prysm from scratch :(

I hope geth is ok, I guess I'll find out in a few days.

Idk what caused prysm to crash, but certainly it's crash recovery needs to be improved so that the DB does not end up in such a state that you need to resync from scratch.

**Comment by adamkoch** [comment]
FWIW, my issue ended up being hardware related - either SSD/disk or memory, even after running memtest and disk checks I didn't actually work out the exact issue. But my symptoms were that prysm would sometimes sync up and start working again but eventually throw errors again. I switched to another machine and that resolved the issue.

**Comment by nisdas** [comment]
@cosmicnet This might be a geth issue, if checkpoint sync didn't fix it. If geth's db is bad, prysm can't sync to the current network head. Can you look at your geth logs ?

**Comment by cosmicnet** [comment]
@nisdas Geth didn't show any errors at first, other than that prysm had gone. After I tried restarting prysm and using the checkpoint geth did show an error do I stopped it. Unfortunately I don't have a copy of that error now. As it was prysm that crashed and not geth, I don't think the issue started with geth. However, I am concerned that geth may have been affected by trying the checkpoint in prysm. I really, really don't want to resync geth from scratch as well. Hopefully once prysm is synced up again I'll restart geth and all will be good.

**Comment by nisdas** [comment]
Do you have the prysm error, that started this off ?

**Comment by cosmicnet** [comment]
@nisdas unfortunately not. I didn't have the config set log to a file. I've now changed that but of course it's too late. So I have no logs surrounding the crash. However this issue #11471 basically describes what I saw when I restarted, but at a head_slot from the 28th.
