### ISSUE TITLE
--monitoring-port -1

### ISSUE THREAD

**Issue by fcorneli** [prysmaticlabs/prysm#11699]
To prevent `prysm` from highjacking port 8080, which is already used by our application server, I temporarily want to disable the prysm metrics via:
```
... --monitoring-port -1
```
However, prysm gives a rather ugly error on this:
```
level=error msg="Could not listen to host:port :127.0.0.1:-1" error="listen tcp: address -1: invalid port" prefix=prometheus
```
Would be nicer if prysm would say on `--monitoring-port -1` something like: disabling monitoring service, really dude?

**Comment by prestonvanloon** [comment]
Try `--disable-monitoring` .

**Comment by fcorneli** [comment]
heh... didn't notice this options. Thanks.
