### ISSUE TITLE
Wrong exit codes when validator doesn't run

### ISSUE THREAD

**Issue by Wolmin** [prysmaticlabs/prysm#11715]
# 🐞 Bug Report

### Description

 I am writing a piece of code that relies on exit codes from various binaries, including beaconchain and validator. It is important that when those exit, they return an appropriate non-zero exit code, but validator doesn't, after it fails to run it returns a 0 exit code.

### Has this worked before in a previous version?

 
 It returned 0 exit code while failing too

## 🔬 Minimal Reproduction

1. Download validator binary and put it into a folder from PATH variable
2. Run validator without any dependencies - in case you saved your validator as a file `validator`, just type `validator` command
3. Check the `?` environmental variable - `echo $?`

## 🔥 Error

<pre><code>

anonymous@anonymous:~$ validator
[2022-12-02 10:16:15]  WARN flags: Running on Ethereum Mainnet
[2022-12-02 10:16:15] ERROR main: could not open wallet: no wallet found. You can create a new wallet with `validator wallet create`. If you already did, perhaps you created a wallet in a custom directory, which you can specify using `--wallet-dir=/path/to/my/wallet`
anonymous@anonymous:~$ echo $?
0

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Liunx Ubuntu 22.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v3.1.2 (tested on v3.1.1 too)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by james-prysm** [comment]
Most commands already have a log.Fatal triggering the Exit code 1 but will add for node runs.
