### ISSUE TITLE
Add `finalized` flag to API responses

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#11747]
# 🚀 Feature Request

We need to implement https://github.com/ethereum/beacon-APIs/pull/254

### Description

Several API endpoints must return a `finalized` metadata field. This issue tracks progress of the feature:
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockAttestations
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlindedBlock
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockV2
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockHeaders
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockHeader
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockRoot
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getEpochCommittees
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateFinalityCheckpoints
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateFork
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateRandao
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateRoot
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getEpochSyncCommittees
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateValidators
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateValidator
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getStateValidatorBalances
- [x] https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Debug/getStateV2

**Comment by liemle82** [comment]
I'm taking a stab at this... i'm very new... please assign to me if you're willing to take the risk :P

**Comment by rkapka** [comment]
Hi @thearyanag , sure. I already implemented all block endpoints. You can take care of the state ones.

**Comment by rkapka** [comment]
There is a way to avoid calling `HashTreeRoot` on the block to check finalization. The algorithm works as follows:
> you check the parent root, if it equals the finalized checkpoint you return false. If not then you check if the parent is final. If it is then you return true, otherwise false. This assumes that the block is canonical. If it's not then return false

**Comment by thearyanag** [comment]
Hey thanks for the heads up , on it now , was actually figuring out that
only/

Regards ,
aryan
