### ISSUE TITLE
Update Validator Client Block Proposal Mechanism With the Spec

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1182]
Currently with the changes in the spec, when proposing the block the validator client will also be required 
to pre-compute the state root when proposing a block. This is how block proposal currently will work according to the spec:
- Proposer runs state transition function without proposer signature validation
- Proposer sets block.state_root to the new state root after state transition
- Proposer signs hash_tree_root(ProposalSignedData(state.slot, BEACON_CHAIN_SHARD_NUMBER, block_without_signature_root)). <- includes new state root
- Broadcast block.

A PR to resolve this would allow the validator client to perform the above functionality.

**Comment by terenc3t** [comment]
Here is the validator client design spec: 
https://docs.google.com/document/d/1LygmeNSivUo4OMl7s0SuXJl8gQKMMezJrtl0YEzpoVo/edit?ts=5bfca994#heading=h.4d4hnezaletr

**Comment by rauljordan** [comment]
This is closed by #1224
