### ISSUE TITLE
EIP-4844 follow ups

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11823]
We are expanding from #11579. Here we open up another set of todos for tracking the next phase for features around EIP4844 that Prysm should support

Beacon-API
- [x] Add `getBlobsSideCar` endpoint https://github.com/ethereum/beacon-APIs/pull/286

Validator / Proposer RPC
- [x] Builder API support. The validator should be able to outsource block construction similar to today, where block construction also encompasses blob construction.

Crypto library / KZG verifications 
- [x] We should understand the geth internals. Are we happy with using whatever geth is using? Exploring tradeoffs may be worthwhile
- [x] Should we define trusted setup parameters within prysm, that way we can load the parameters and pass to the kzg library instead of trusting kzg library for *everything*

Sync
- [x] Fix `beacon_block_and_blobs_sidecar_by_root`. Prysm node can't request `beacon_block_and_blobs_sidecar_by_root` from another Prsym node due to error `Stream reset`.  Fixed in https://github.com/prysmaticlabs/prysm/pull/11621/commits/ec72575fc9d27eafe70b01d88476bd7930659b0e
- [x] Can sync blobs up to data availability period when using weak subjectivity sync. Backwards block sync may be required
- [ ] Review peer scoring and rate limiting for serving blobs

Database
- [x] If the blob is empty (ie zeros), don't write it to DB or cache
- [x] Is the current scheme good enough for empty blobs and pruning blobs?
- [x] CLI parameter to let Prysm use a different data directory for blobs. Blobs should have a low disk read-write access requirement so that HDD may be used. Migration tools too?

Prysm internal
- [x] Rename everything eip4844 to deneb 🦢 
- [x] Better handling for zero blob sidecar. We shouldn't have to store it, and we shouldn't have to respond it upon request. That said, we should have a quick lookup to know if a slot has block with zero kzg commitment without having to unmarshal the block
- [x] Blind block handling for eip4844 block. Make sure nothing breaks for blob

Tooling
- [x] Extend prysmctl to download and upload blobs

E2E test
- [x] Extend e2e test to EIP4844 behavior. Can submit and download blobs

**Comment by emailtovamos** [comment]
Hello @terencechain,
Just curious about what's the current state of these tasks. 
Are they up to date? What's the biggest challenge right now which is still being figured out? 
Thanks!

**Comment by alexlucaci** [comment]
Hi @terencechain 
Just a follow up of @emailtovamos question. We are working at BNBChain and we are interested to integrate the changes in bsc so let us know if we can help with anything.

Thanks,
Alex Lucaci

**Comment by terencechain** [comment]
Only backfilling and peer scoring left. Tracking via different thread
