### ISSUE TITLE
Getting Error "Not connected to ETH1. Cannot determine validator ETH1 deposit block number"

### ISSUE THREAD

**Issue by sean-connery-adigium** [prysmaticlabs/prysm#11832]
# 🐞 Bug Report

### Description

We are trying to create a new blockchain to use PoS.
The network starts in PoW mode until reaching epoch 4 and switches for PoS as per Raul’s tutorial https://github.com/rauljordan/eth-pos-devnet
This was working well in interop mode, and the validator was validating new blocks that are synched with the Beacon chain and the geth execution node.
When we removed the interop parameters, the beacon chain is not able to communicate with the geth node.

The validator says: Waiting for deposit to be observed by beacon node
The geth node is not complaining and not moving to PoS.

### Has this worked before in a previous version?
Unknown

## 🔬 Minimal Reproduction

We created [this script](https://github.com/oone-world/eth-pos-devnet/blob/master/restart-server.sh
) which streamlines the process detailed below.

Here are geth’s [genesis.json](https://github.com/oone-world/eth-pos-devnet/blob/master/execution/genesis.json) and the beacon-chain’s [config.yaml ](https://github.com/oone-world/eth-pos-devnet/blob/master/consensus/config.yml) files

We connected Geth node with BeaconChain and a Validator with BeaconChain
### Starting Geth
We started with a geth node that we initialized using the command
```
geth --datadir=execution init execution/genesis.json
```
We created a geth public and private key pair using meta mask
```
account_geth_address=0xF359C69a1738F74C044b4d3c2dEd36c576A34d9f
account_geth_privateKey=0x28fb2da825b6ad656a8301783032ef05052a2899a81371c46ae98965a6ecbbaf
```
We imported the account using the command
```
geth --datadir=execution account import --password execution/geth_password.txt execution/account_geth_privateKey
```
We started the geth node in PoW using the following command
```
geth --networkid=123456 \
	--http \
	--http.api=eth,net,web3,personal,miner \
	--http.addr=0.0.0.0 \
	--http.vhosts=* \
	--http.corsdomain=* \
	--authrpc.vhosts=* \
	--authrpc.addr=0.0.0.0 \
	--authrpc.jwtsecret=execution/jwtsecret \
	--datadir=execution \
	--allow-insecure-unlock \
	--unlock=$account_geth_address \
	--password=execution/geth_password.txt \
	--syncmode=full \
	--bootnodes= \
	--mine
```
### Beacon Chain
We initialized `genesis.ssz` using the docker image
```
create-beacon-chain-genesis:
	image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest"
	command:
		- testnet
		- generate-genesis
		- --num-validators=64
		- --output-ssz=/consensus/genesis.ssz
		- --chain-config-file=/consensus/config.yml
	volumes:
		- ./consensus:/consensus
```
We run the beacon chain using the following command
```
./prysm.sh beacon-chain \
	--datadir=consensus/beacondata \
	--min-sync-peers=0 \
	--genesis-state=consensus/genesis.ssz \
	--bootstrap-node= \
	--chain-config-file=consensus/config.yml \
	--config-file=consensus/config.yml \
	--rpc-host=0.0.0.0 \
	--grpc-gateway-host=0.0.0.0 \
	--monitoring-host=0.0.0.0 \
	--execution-endpoint=http://localhost:8551 \
	--chain-id=32382 \
	--accept-terms-of-use \
	--jwt-secret=execution/jwtsecret \
	--suggested-fee-recipient=$account_geth_address \
	--p2p-host-ip=$my_ip
```
### Validator
We created a validator key using the deposit-cli tool
```
./deposit --language English new-mnemonic --mnemonic_language English --num_validators 1 --chain mainnet
```
The geth `genesis.json` already have the compiled deposit contract from the mainnet

We made the deposit from our geth account to the deposit contract to start staking with the validator key deposit data

We imported the validator key
```
./prysm.sh validator \
	accounts \
	import \
	--accept-terms-of-use \
	--keys-dir=validator_keys/ \
	--wallet-dir=wallet_dir \
	--wallet-password-file=wallet_dir/password.txt \
	--account-password-file=wallet_dir/password.txt
```
We run the validator
```
./prysm.sh validator \
	--beacon-rpc-provider=localhost:4000 \
	--datadir=consensus/validatordata \
	--accept-terms-of-use \
	--chain-config-file=consensus/config.yml \
	--wallet-dir=wallet_dir \
	--wallet-password-file=wallet_dir/password.txt
```

## 🔥 Error
The below errors appear repeatedly in the beacon chain log:
<pre><code>
time="2022-12-28 17:53:16" level=error msg="Could not process new slot" error="0x0000000000000000000000000000000000000000000000000000000000000000: unknown finalized root" prefix=blockchain

time="2022-12-28 17:53:40" level=warning msg="Not connected to ETH1. Cannot determine validator ETH1 deposit block number" prefix="rpc/validator"
</code></pre>

When the network should move to PoS we get the error message
<pre><code>
time="2022-12-28 17:58:16" level=error msg="Unable to retrieve proof-of-stake genesis block data" error="not found" prefix=powchain

</code></pre>

And here are the complete logs for each node
[geth](https://drive.google.com/file/d/1dkfiJsMqxTYw1LjtWIC2hRNQHN7bz81k/view?usp=sharing)
[beacon](https://drive.google.com/file/d/1EtSfGSi9hAKrxbAVtDcvdyHvz31KaEfC/view?usp=sharing)
[validator](https://drive.google.com/file/d/1nLm7UdU0SB7W1v9XN8lFjjYt1i9PIyCQ/view?usp=sharing)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04.1 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain-v3.2.0-linux-amd64
validator-v3.2.0-linux-amd64
  </code>
</pre>

Please let me know if you want any further information.

**Comment by lthibault** [comment]
Did you ever figure this out? We're seeing something similar.

**Comment by nisdas** [comment]
@lthibault @sean-connery-adigium We will have an updated version of the above devnet instructions soon. We hope to have it released pretty soon. There were a few flag changes along with other feature changes for capella, so the instructions will not work as expected.

**Comment by rauljordan** [comment]
Hi @lthibault this should now be fixed. Let us know if we should reopen

**Comment by Fueav** [comment]
I have also encountered this problem, and I want to know what caused it and how to solve it.

**Comment by lthibault** [comment]
@nisdas Would you be able to point me to the PR/commit that fixes the issue? Thanks!

**Comment by nisdas** [comment]
@lthibault @Fueav 

This should be fixed in our latest set of instructions, you can take a look at 
https://github.com/OffchainLabs/eth-pos-devnet/tree/a293e5c52ec63a4e18fc691ee3013a9fb18e8694

Let us know if you guys still have issues with it

**Comment by lthibault** [comment]
@nisdas Thank you, sir!
