### ISSUE TITLE
Attestation is too old to broadcast, discarding it. Current Slot: xxx , Attestation Slot: xxx

### ISSUE THREAD

**Issue by arshad-deriv** [prysmaticlabs/prysm#11852]
Hi
For past few weeks we are getting these intermittent warning logs from consensus node

```
Attestation is too old to broadcast, discarding it. Current Slot: xxxx , Attestation Slot: xxx
```
May i know what could be the reason behind this issue & is it something that is fixed in newer version(3.2.0) ? 

Sometimes this logs is flooding & there is not much info about this log over there to fix this.

Versions currently running for 
Consensus client:  beacon-chain-v3.1.1-linux-amd64
Execution client : geth-linux-amd64-1.10.26-e5eb32ac

**Comment by kingwilliams1966** [comment]
I am having the same issue, same setup; any thoughts, anyone?

**Comment by kingwilliams1966** [comment]
Same issue, didn’t start until my validator, after 30 days, caught up and started working again.

**Comment by sokiaoba** [comment]
Same here. And I'm not sure they are related but when this happens block generation of our prysm / execution node tend to slow down.

**Comment by SeaMonkey82** [comment]
I'm seeing this a lot with prysm-besu and prysm-erigon on Goerli using the development branches of all clients.

**Comment by yashLN** [comment]
We had the same issue and validators started missing attestation. The log disappeared after restarting beacon node. I'm using the beacon latest release 4.0.0 with geth 1.11.5

**Comment by terencechain** [comment]
This typically happens when your node is syncing or there's a temporary downtime. Please reopen if it still persists
