### ISSUE TITLE
rewrite TestClient_IPC Capella's test. 

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#11881]
To merge https://github.com/prysmaticlabs/prysm/pull/11879, a engine unit test is skipped. We need to find a way to rewrite it such that it's not too invasive for no gain.

**Comment by rauljordan** [comment]
Is this still relevant @potuz after the work done this past week?

**Comment by james-prysm** [comment]
Closing as I think this is stale, test seems to be fine and not skipped
