### ISSUE TITLE
Update Slashing Conditions per Spec

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1190]
Update [IsDoubleVote](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/attestations/attestation.go#L81) and [IsSurroundVote](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/attestations/attestation.go#L102) to the latest spec as referenced below. Instead of checking for slot number, we should be checking for epoch number. To complete this issue, we should fix the code and the exisiting unit tests.

Reference: https://github.com/ethereum/eth2.0-specs/pull/373

**Comment by arku** [comment]
@terenc3t I would like to work on this issue.

**Comment by terenc3t** [comment]
Assigned to @arku. Thank you for your help!

**Comment by arku** [comment]
@terenc3t A minor thing. The first function mentioned in the issue description should be `IsDoubleVote` and not `IsUpdateVote`.

**Comment by terenc3t** [comment]
> @terenc3t A minor thing. The first function mentioned in the issue description should be `IsDoubleVote` and not `IsUpdateVote`.

That's correct.

**Comment by arku** [comment]
@terenc3t Thanks for the description update!
