### ISSUE TITLE
Shell Script to Generate and Replace pb.go

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1191]
The current steps to generate new proto pb.go can be tedious and unintuitive. Let's develop a shell script like `./scripts/update-go-pbs.sh` to copy the new proto pb.go from `bazel-bin` dir to `proto` directory 

The manual steps are outlined here: https://github.com/prysmaticlabs/prysm/tree/master/proto

**Comment by terenc3t** [comment]
Thanks @kushagrasharma! Assigned to you

**Comment by kushagrasharma** [comment]
Is using `protoc` instead of copying over the bazel files acceptable? If so, the one-liner `find . -type f -name '*.proto' -exec protoc --go_out=. {} \;` should be able to generate all the pb.go files for us inside their own directories.
