### ISSUE TITLE
Improving correctlyVotedHeadPct

### ISSUE THREAD

**Issue by okorolov** [prysmaticlabs/prysm#11913]
# 💎 Issue

### Background

Currently, my correctlyVotedHeadPct is at ~96%. I'm looking for ways to improve this value.
And around 2-3 days I get 1 missed attestation. 

### Description

Some information on the setup:
Execution client: `Geth 1.10.26`
Consensus client: `Prysm 3.2.0`
Environment: `AWS + Kubernetes`
Time synchronization: `chrony`
Number of active peers: `~75+`

Main suspect so far - is block arrival latency.
According to `block_arrival_latency_milliseconds_bucket` I have ~8.5% of blocks arriving with 4s+ delay.
Referring to this topic https://github.com/prysmaticlabs/prysm/issues/5665 I understand that this value should be lower, but I don't understand how I can improve the situation. 
If I enable `attest-timely` feature I start seeing a lot of missed attestations ~ 5-10 missed attestations per day.  

I would appreciate any guidance or suggestions.
Thanks.

**Comment by sdalmeida** [comment]
@okorolov can you give more information on your hardware specs? What type of SSD/HDD are you using, size, brand, RAID?

**Comment by okorolov** [comment]
@sdalmeida I'm running in AWS, so using GP3 volumes for the chain data, no raids or anything tricky. 
It seems that at some point I have figured it out. 
In my case, 2 changes played the final role in stats improvement:
- peer count increase on consensus and execution nodes from 50/30 to 100/55-60. 
- the instance type change for both consensus and execution nodes to have better CPUs. 
Now I have correctly voted head at ~98%, and my validators usually stay within 15-30% rank on beaconcha.in, so I think this is acceptable. 

So I think the issue can be closed.
