### ISSUE TITLE
Extend Intersection, Union Functionalities to More Types

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1193]
It's unfortunate the functions under [slice](https://github.com/prysmaticlabs/prysm/blob/master/shared/slices/slice.go) package are purely for uint32. In the future people might want to use this package thinking it is more powerful and can work for different types but find it a type mismatch. The goal of this issue is to extend these functions (Intersection, Union, Not..etc) to work with multiple types

**Comment by ratikesh9** [comment]
@terenc3t  will be happy to take this up

**Comment by terenc3t** [comment]
Assigned to @ratikesh9. Thank you for your help!

**Comment by ratikesh9** [comment]
Updated the repository with generic slices.

https://github.com/prysmaticlabs/prysm/pull/1219
