### ISSUE TITLE
change signature of `pruneCanonicalAttsFromPool`

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#11934]
Currently the function `pruneCanonicalAttsFromPool` is called only from `onBlock` at a point where the head root and the incoming block root are known. the only way for the block to be canonical is if these two roots are equal. There  is no need for the canonical check being performed withing the function `pruneCanonicalAttsFromPool`.

**Comment by terencechain** [comment]
We should address this in: https://github.com/prysmaticlabs/prysm/pull/11771
