### ISSUE TITLE
Implement Beacon API reward endpoints

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#11952]
# 🚀 Feature Request

### Description

Implement reward-related Beacon API endpoints:
- https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getSyncCommitteeRewards
- https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockRewards
- https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getAttestationsRewards

**Comment by duktig666** [comment]
Whether it contains punishment information？
Based on this, alarm and monitoring can be performed.
