### ISSUE TITLE
Remove Explicit Declaration of Repeated Demo Config Values

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1197]
The demo config and default config have the same values declared for a few fields ex: 
`LatestRandaoMixesLength:       8192`
`LatestBlockRootsLength:        8192`
 
A PR to resolve this would instead simply declare in the demo config for these values as : 
`LatestRandaoMixesLength:       defaultBeaconConfig.LatestRandaoMixesLength`
`LatestBlockRootsLength:       defaultBeaconConfig.LatestBlockRootsLength`

and so on for the other common fields.

**Comment by cyberbono3** [comment]
https://github.com/prysmaticlabs/prysm/pull/1209
