### ISSUE TITLE
Increase default grpc max message size

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#11983]
# 💎 Issue

### Background

Default parameters for GRPC mean that standard REST API calls fail.

### Description

Attempting to obtain the `/validators` endpoint from a prysm beacon node with minimal configuration returns:

```
{"message":"grpc: received message larger than max (70716973 vs. 4194304)","code":429}
```

It would be great if the max message size was set to something reasonable such that validators (and, ideally, state) could be retrieved from the node without requiring the more obscure parameters such as `grpc-max-msg-size`

**Comment by prestonvanloon** [comment]
Perhaps grpc-max-msg-size can be some very large value. 

@mcdee Do you have any suggested new default? 

I am considering using max int64 (no limit) and logging an ominous warning when the operator has their gRPC host set to anything other than localhost. The point of this guard is to prevent someone from sending an impossibly large message that would overwhelm the server and/or client, but that shouldn't be a factor for individuals running with a local validator or advanced professionals with other safeguards in place.

If you're happy with the suggestion above, we can add this in quickly ahead of Capella.
