### ISSUE TITLE
Indefinite hang on startup

### ISSUE THREAD

**Issue by kaladinlight** [prysmaticlabs/prysm#11996]
# 💎 Issue

### Background

I have been syncing an archive node for weeks now and upon starting back up my beacon node, I end up in some sort of deadlock/hang state somewhere in [startStateGen](https://github.com/prysmaticlabs/prysm/blob/77d3ccb9ad8b28656452456d2d25437f5fc53d88/beacon-chain/node/node.go#L494) which I would assume is related to finalizing checkpoints reading through the code. I have turned on trace level logging, but am not getting much detail to go off. Hoping someone might have some ideas, would hate to resync from scratch since it takes forever...

Here are the flags I am using:
`--datadir=/data --execution-endpoint=http://localhost:8551 --jwt-secret=/jwt.hex --accept-terms-of-use --slots-per-archive-point=32 --verbosity=trace   
`

### Description

Startup Logs:
```
time="2023-02-15 17:53:08" level=info msg="Finished reading JWT secret from /jwt.hex"
time="2023-02-15 17:53:08" level=warning msg="Running on Ethereum Mainnet" prefix=flags
time="2023-02-15 17:53:08" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node                                                                                             │
time="2023-02-15 17:53:08" level=debug msg="Starting DB" prefix=node
time="2023-02-15 17:53:08" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
time="2023-02-15 17:53:08" level=info msg="Opening Bolt DB at /data/beaconchaindata/beaconchain.db" prefix=db
time="2023-02-15 17:53:26" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
time="2023-02-15 17:53:26" level=debug msg="Starting Slashing DB" prefix=node
time="2023-02-15 17:53:26" level=debug msg="Starting State Gen" prefix=node
```

**Comment by rauljordan** [comment]
Hi @kaladinlight did you ever manage to get past this issue? Or did it hang forever?

**Comment by kaladinlight** [comment]
> Hi @kaladinlight did you ever manage to get past this issue? Or did it hang forever?

No I gave up. It seemed really memory hungry if you wanted to try to bump RAM. Feels like it is trying to load tons of data into memory before continuing sync, but I'm not positive

**Comment by terencechain** [comment]
I'm going to close this but feel free to reopen if we should continue investigation
