### ISSUE TITLE
Modify EVM for Sharding

### ISSUE THREAD

**Issue by Magicking** [prysmaticlabs/prysm#12]
The EVM needs to be modified in order for sharding to works, unfortunately documentation is still in progress, I'm creating this issue to centralize the documentations and discussions for the work in progress implementation in Geth.

List of useful links:
 - https://ethresear.ch/t/tradeoffs-in-account-abstraction-proposals/263 (New opcodes proposal)
 - https://github.com/ethereum/vyper/issues/632 (New opcodes discussion)
 - https://ethresear.ch/t/log-shards-and-emv-abstraction/747 (Log shards [opcode] and EMV abstraction)
 - https://github.com/ethereum/py-evm/issues/226 (SIGHASH opcode issue)
 - https://ethresear.ch/c/sharding (General overview)

TODO:
Opcodes (ordered by complexity):
 - [ ] SIGHASH (Calculate transaction hash w/o signature)
 - [ ] CREATE2 (CREATE w/ salt argument)
 - [ ] PAYGAS (Refunds unused gas via a temporary account)
 - [ ] BREAKPOINT (Revert transaction up to a certain point)

**Comment by Magicking** [comment]
# EVM Modification Strategy

The geth EVM support configuration via the [go-ethereum/core/vm.Config](https://godoc.org/github.com/ethereum/go-ethereum/core/vm#Config) type and more specifically the JumpTable.

Since I haven't seen any thorough discussion on how/when includes them I propose for now to use a specific EVM configuration for the sharding client that would includes the new opcodes (more information in ethereum/vyper#632).

**Comment by jamesray1** [comment]
For clarity on why this was closed, according to [the draft phase 1 spec](https://ethresear.ch/t/sharding-phase-1-spec/1407) the EVM won't be specified until phase 2.

**Comment by rauljordan** [comment]
This is quite out of scope as we will no longer use the EVM for Ethereum2.0. A lot of floating context around state execution at the moment, but will close this for now as it will no longer be relevant anyways.
