### ISSUE TITLE
Create health check for AttestationService 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1201]
As part of #1183, all services should maintain a `Status` method that will return an error if there is any unhealthy status to report. This task requires some creative thinking to evaluate a definition of a healthy service. It is possible that a service can always be healthy and in that case we would simply remove the TODO and update the godoc to explain why the service is always healthy. 

Service definition: beacon-chain/attestation/service.go

What makes this service healthy or unhealthy? 

Perhaps we return an error if an attestation has not been received in some time?

**Comment by mattisstenejohansen** [comment]
(new and motivated contributor) Hey, @prestonvanloon I'd love to work on this.

**Comment by prestonvanloon** [comment]
Hey @mattisstenejohansen, I'm glad to hear it! 

Let's assign this this to you. I'm working on wrapping up the PR #1183 today, but if you want to go head and get started then you can fork that branch.

Thanks!

**Comment by mattisstenejohansen** [comment]
Hi, thanks!
I see that there is already done something for the Attestation Status here: https://github.com/prysmaticlabs/prysm/blob/6abd1781c38a4c2549bd27a39098d4384ff1920f/beacon-chain/attestation/service.go#L64

Should I just leave it and consider it done?

**Comment by prestonvanloon** [comment]
@mattisstenejohansen Probably not. This issue is to determine if that is the case. If there are valid health checks to implement (I think there are), then it should be implemented as part of this issue.

**Comment by terenc3t** [comment]
Implemented in attestation service

**Comment by prestonvanloon** [comment]
It is not implemented

https://github.com/prysmaticlabs/prysm/blob/7f3d8a7e7b8052a5b52f0a41f1d08f59f2446784/beacon-chain/attestation/service.go#L75

**Comment by rauljordan** [comment]
Attestation service no longer exists using the --next flag
