### ISSUE TITLE
Create health check for ChainService

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1202]
As part of #1183, all services should maintain a Status method that will return an error if there is any unhealthy status to report. This task requires some creative thinking to evaluate a definition of a healthy service. It is possible that a service can always be healthy and in that case we would simply remove the TODO and update the godoc to explain why the service is always healthy.

Service definition: beacon-chain/blockchain/service.go

What makes this service healthy or unhealthy?

Some ideas:
- The web3service has gone away and we are trying to reconnect to it.
- Chain head block not received in some time
- Block processing hasn't received a block in some time

**Comment by ratikesh9** [comment]
Chain head block not received in some time 

@prestonvanloon  specifically what is the time limits in order to create unhealthy check?

**Comment by prestonvanloon** [comment]
@ratikesh9 Let's try something like 2 minutes. Thanks!

**Comment by ratikesh9** [comment]
In block processing if the subscription to incoming channel returns error should it be considered as fail status of service ?

Does Chain head block not received in some time means that we are not able to get chain head from beacon db ?

**Comment by nisdas** [comment]
@ratikesh9 We dont receive the chain head at regular intervals, we only get the chain head when we read it from the db. An error during the read of the db, can be considered as a failure. 

Not sure what you mean by the incoming channel returning an error, it is of the type `*pb.BeaconBlock` , 
so we will either get normal blocks,nil blocks . You can check, though if the channel is closed with `ok`, if it is closed it can be considered a failure

**Comment by nisdas** [comment]
ah , yes that would also be considered as a service failure

**Comment by prestonvanloon** [comment]
#1290 was never merged.
