### ISSUE TITLE
 too many colons in address" "Zhejiang"

### ISSUE THREAD

**Issue by Piradoxlanieve** [prysmaticlabs/prysm#12033]
# 🐞 Bug Report

### Description
I am following this guide, geth sync and consensus sync but the validator has this error
Sorry my english.

https://www.coincashew.com/coins/overview-eth/guide-or-ethereum-staking-on-zhejiang-testnet#step-5.-setup-execution-layer-client

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

El cliente GEth
```
feb 22 18:24:24 gigabyte geth[483876]: INFO [02-22|18:24:24.135] Imported new potential chain segment     number=144,487 hash=7dff31..dc4655 blocks=1  txs=4   mgas=0.084 elapsed=2.698ms      mgasps=31.134  dirty=2.03MiB
feb 22 18:24:24 gigabyte geth[483876]: INFO [02-22|18:24:24.150] Chain head was updated                   number=144,487 hash=7dff31..dc4655 root=cf9082..225eab elapsed=2.940577ms
feb 22 18:24:36 gigabyte geth[483876]: INFO [02-22|18:24:36.208] Imported new potential chain segment     number=144,488 hash=de22f7..9852b1 blocks=1  txs=3   mgas=0.063 elapsed=3.692ms      mgasps=17.062  dirty=2.04MiB
feb 22 18:24:36 gigabyte geth[483876]: INFO [02-22|18:24:36.221] Chain head was updated                   number=144,488 hash=de22f7..9852b1 root=32f2cf..6e78a2 elapsed=1.581649ms
```
Cliente consenso prysm
```
feb 22 18:24:48 gigabyte bazel[583196]: time="2023-02-22 18:24:48" level=info msg="Finished applying state transition" attestations=15 payloadHash=0xb2a6da389435 prefix=blockchain slot=151924 syncBitsCount=484 txCount=1
feb 22 18:25:00 gigabyte bazel[583196]: time="2023-02-22 18:25:00" level=info msg="Synced new block" block=0x16789803... epoch=4747 finalizedEpoch=4745 finalizedRoot=0xe66735a8... prefix=blockchain slot=151925
feb 22 18:25:00 gigabyte bazel[583196]: time="2023-02-22 18:25:00" level=info msg="Finished applying state transition" attestations=15 payloadHash=0x48e5a1e48059 prefix=blockchain slot=151925 syncBitsCount=484 txCount=19
feb 22 18:25:12 gigabyte bazel[583196]: time="2023-02-22 18:25:12" level=info msg="Synced new block" block=0x3e605f9f... epoch=4747 finalizedEpoch=4745 finalizedRoot=0xe66735a8... prefix=blockchain slot=151926
feb 22 18:25:12 gigabyte bazel[583196]: time="2023-02-22 18:25:12" level=info msg="Finished applying state transition" attestations=15 payloadHash=0x3af807b36a9c prefix=blockchain slot=151926 syncBitsCount=484 txCount=6
feb 22 18:25:24 gigabyte bazel[583196]: time="2023-02-22 18:25:24" level=info msg="Synced new block" block=0x791953e0... epoch=4747 finalizedEpoch=4745 finalizedRoot=0xe66735a8... prefix=blockchain slot=151927
feb 22 18:25:24 gigabyte bazel[583196]: time="2023-02-22 18:25:24" level=info msg="Finished applying state transition" attestations=15 payloadHash=0x10157447e615 prefix=blockchain slot=151927 syncBitsCount=484 txCount=3
feb 22 18:25:30 gigabyte bazel[583196]: time="2023-02-22 18:25:30" level=info msg="Peer summary" activePeers=30 inbound=0 outbound=30 prefix=p2p
feb 22 18:25:36 gigabyte bazel[583196]: time="2023-02-22 18:25:36" level=info msg="Synced new block" block=0x4a5db0b7... epoch=4747 finalizedEpoch=4745 finalizedRoot=0xe66735a8... prefix=blockchain slot=151928
feb 22 18:25:36 gigabyte bazel[583196]: time="2023-02-22 18:25:36" level=info msg="Finished applying state transition" attestations=30 payloadHash=0x43336f482124 prefix=blockchain slot=151928 syncBitsCount=484 txCount=2
```

-->

## 🔥 Error
Prysm valiadator
<pre><code>

feb 22 18:11:25 gigabyte bazel[583203]: time="2023-02-22 18:11:25" level=info msg="Syncing with beacon node to align on chain genesis info" prefix=validator
feb 22 18:11:29 gigabyte bazel[583203]: time="2023-02-22 18:11:29" level=warning msg="Could not determine if beacon chain started" error="could not receive ChainStart from stream: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address http://localhost:4000: too many colons in address": could not connect: could not connect" prefix=validator
feb 22 18:11:35 gigabyte bazel[583203]: time="2023-02-22 18:11:35" level=info msg="Syncing with beacon node to align on chain genesis info" prefix=validator
feb 22 18:11:39 gigabyte bazel[583203]: time="2023-02-22 18:11:39" level=warning msg="Could not determine if beacon chain started" error="could not receive ChainStart from stream: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address http://localhost:4000: too many colons in address": could not connect: could not connect" prefix=validator

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Description:    Ubuntu 22.04.2 LTS

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v3.2.1-rc.1/a4579398cb879282012d3afbf799279cd1b19af6. Built at: 2023-02-22 17:01:32+00:00"

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by potuz** [comment]
You have an extra colon after 4000 in localhost:4000, remove that from the configuration

**Comment by Piradoxlanieve** [comment]
> You have an extra colon after 4000 in localhost:4000, remove that from the configuration
@potuz 
It seems that there are no double dots in the file, I have to comment that when compiling with bazel beacon it works, but validator with the validator user fails and I had to compile and run it with root, maybe that has something to do with it? sorry my bad english
```

Wants=network-online.target
After=network-online.target
Documentation=https://www.coincashew.com

[Service]
Type=simple
User=validator
Group=validator
Restart=on-failure
RestartSec=3
KillSignal=SIGINT
TimeoutStopSec=900
WorkingDirectory=/usr/local/bin/prysm
ExecStart=bazel run //cmd/validator  --sandbox_debug --config=release -- \
  --accept-terms-of-use=true \
  --datadir=/var/lib/prysm/zhejiang \
  --chain-config-file=/var/lib/ethereum/zhejiang/custom_config_data/config.yaml \
  --beacon-rpc-provider=http://localhost:4000 \
  --wallet-dir=/var/lib/prysm/zhejiang/validator-data \
  --wallet-password-file=/var/lib/prysm/zhejiang/validator-data/validators-password.txt \
  --suggested-fee-recipient=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Install]
WantedBy=multi-user.target
```

**Comment by potuz** [comment]
can you try removing entirely the line `beacon-rpc-provider...`?
