### ISSUE TITLE
Clarity on Epoch while broadcasting Voluntary Exit

### ISSUE THREAD

**Issue by imnotanoob** [prysmaticlabs/prysm#12035]
Hello,

We are trying to implement the voluntary exit command before the ETH2.0 merge, and I had a general question on epoch, and how it works.

- I understand the formula to calculate the epoch is given here: https://github.com/prysmaticlabs/prysm/blob/d4f3257f609b7a6690b8fcf0845457602fe0eb84/validator/client/propose.go#L216
- I want to understand how epoch works while broadcasting a voluntary exit message. For example if we broadcast a message at an earlier epoch (so the epoch is already proposed), does that just invalidate the broadcast? 
- Is there a better technique of calculating the epoch? Potentially looking at the `target` `attestations` of the last proposed slot and appending by +1?

**Comment by potuz** [comment]
You can sign the voluntary exit with any epoch you want. The only caveat is that you also need to sign it with a fork version (corresponding to the epoch you signed it for) and the exit will be valid for the current fork and the next fork version. 

This allows you to sign an exit in the future, that will only be valid when the epoch that you signed it for is already reached. Notice though that you cannot sign for a fork that you don't already know will happen. 

Please close this issue if this reply did solve your question, and if it didn't please close it anyway and reach us in Discord that will be more appropriate than on this setup.
