### ISSUE TITLE
Create health check for web3service

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1204]
As part of #1183, all services should maintain a Status method that will return an error if there is any unhealthy status to report. This task requires some creative thinking to evaluate a definition of a healthy service. It is possible that a service can always be healthy and in that case we would simply remove the TODO and update the godoc to explain why the service is always healthy.

Service definition: beacon-chain/powchain/service.go

What makes this service healthy or unhealthy?

Ideas:
- web3 client disconnected, but we are attempting to reconnect
- web3 client is not syncing or hasn't reported a new block in some time

**Comment by skillful-alex** [comment]
working on it

**Comment by rauljordan** [comment]
Closed by #1502

**Comment by skillful-alex** [comment]
#1502 solves another error
This is a request to implement the `Status()` function in the `beacon-chain/powchain/service.go`
