### ISSUE TITLE
runtime error: integer divide by zero

### ISSUE THREAD

**Issue by quentinlesceller** [prysmaticlabs/prysm#12048]
# 🐞 Bug Report

### Description

As titled. Beacon-chain crashes with a divide by zero error.

### Has this worked before in a previous version?

Never seen this error before.

## 🔬 Minimal Reproduction

Beacon-chain is currently syncing connected to a modified geth.

## 🔥 Error

<pre><code>
Feb 24 18:09:41 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:41" level=info msg="Processing block batch of size 1 starting from  0x6090b2e3... 5868540/5869846 - estimated time remaining 1h2m11s" blocksPerSecond=0.3 peers=55 prefix=initial-sync
Feb 24 18:09:41 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:41" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x3c1d8e6bedb2c287942dbfe7362c5454c001216e7d86fb12b04caa97d1201e0f (in processBatchedBlocks, slot=5868540)" prefix=initial-sync
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:42" level=debug msg="Searching for non-skipped slot" headEpoch=183389 prefix=initial-sync start=5868539 targetEpoch=183430
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:42" level=debug msg="Requesting blocks" capacity=1 count=32 peer=16Uiu2HAmJxiZu1zRoydXvChr5g1oh6Dkx8egY8zWUh9gRxTKFLUR prefix=initial-sync score="[100.0%, raw: 64.00,  blocks: 0/640]" start=5868540 step=1
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:42" level=debug msg="Slowing down for rate limit" peer=16Uiu2HAmJxiZu1zRoydXvChr5g1oh6Dkx8egY8zWUh9gRxTKFLUR prefix=initial-sync
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: time="2023-02-24 18:09:42" level=debug msg="Context closed, exiting goroutine (blocks fetcher)" prefix=initial-sync
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: panic: runtime error: integer divide by zero
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: goroutine 10761 [running]:
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.timeToWait(...)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher.go:401
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksFetcher).waitForBandwidth(0xc009fd5900, {0xc05cc2f890, 0x27}, 0x20)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher.go:378 +0x46a
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksFetcher).requestBlocks(0xc009fd5900, {0xc03cf8, 0xc04cf781e0}, 0xc037d94640, {0xc05cc2f890, 0x27})
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher.go:327 +0x50a
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksFetcher).nonSkippedSlotAfterWithPeersTarget.func1({0xc05cc2f890, 0x27}, 0x598bfc, 0x20, 0x1)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher_utils.go:74 +0xbb
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksFetcher).nonSkippedSlotAfterWithPeersTarget(0xc009fd5900?, {0xc03cf8?, 0xc04cf781e0?}, 0x598bfb, {0xc000022e00, 0xb, 0x0?}, 0x2cc86)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher_utils.go:92 +0x196
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksFetcher).nonSkippedSlotAfter(0xc00a2a8690?, {0xc03c50?, 0xc00a286f40?}, 0xc005db7328?)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_fetcher_utils.go:52 +0x3b7
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksQueue).resetFromSlot(0xc006aefd50, {0xc03c50, 0xc00a286f40}, 0x598bf5)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_queue_utils.go:57 +0xe5
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksQueue).onProcessSkippedEvent.func1(0xc01aff9f20, {0xc00a2a8750?, 0xc0002cc380?})
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_queue.go:443 +0x51d
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*stateMachine).trigger(0xc01aff9f20, 0x0, {0x0, 0x0})
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/fsm.go:171 +0x8c
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksQueue).loop(0xc006aefd50)
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_queue.go:205 +0xb05
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]: created by github.com/prysmaticlabs/prysm/v3/beacon-chain/sync/initial-sync.(*blocksQueue).start
Feb 24 18:09:42 bc-prod-eth-prysm beacon-chain[1312]:         beacon-chain/sync/initial-sync/blocks_queue.go:148 +0x78

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
 beacon-chain --version
beacon-chain version Prysm/v3.2.1/0cf1ca8b3cf0c4124fa3183412975721bd31d183. Built at: 2023-02-13 17:23:43+00:00
  </code>
</pre>

**Comment by quentinlesceller** [comment]
Okay after some investigations it looks like this was fixed in https://github.com/prysmaticlabs/prysm/pull/11988. Can we have another bug fix release please?

**Comment by prestonvanloon** [comment]
@quentinlesceller we are planning a release early next week. Sorry, for the inconvenience! It should be OK to use the prior version of Prysm until this is resolved. 

Closing this as fixed per #11988
