### ISSUE TITLE
GRPC health following the standard

### ISSUE THREAD

**Issue by killerwhile** [prysmaticlabs/prysm#12050]
# 🚀 Feature Request

### Description

GRPC defines a standard for health checking endpoint in [https://github.com/grpc/grpc/blob/master/doc/health-checking.md](https://github.com/grpc/grpc/blob/master/doc/health-checking.md). Implementing the same would allow easy integration with monitoring tools such as [prometheus/blackbox_exporter](https://github.com/prometheus/blackbox_exporter).

**Comment by rkapka** [comment]
Hi @killerwhile. We have a long-term plan to move away from gRPC in our APIs, therefore we probably won't implement this.
