### ISSUE TITLE
Create health check for RPCService

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1205]
As part of #1183, all services should maintain a Status method that will return an error if there is any unhealthy status to report. This task requires some creative thinking to evaluate a definition of a healthy service. It is possible that a service can always be healthy and in that case we would simply remove the TODO and update the godoc to explain why the service is always healthy.

Service definition: beacon-chain/rpc/service.go

What makes this service healthy or unhealthy?

Ideas:
- If any of its dependent services are unhealthy, report unhealthy
- If the grpcService is not listening for traffic (this failure just logs an error, and the process continues)

**Comment by cyberbono3** [comment]
working on it
