### ISSUE TITLE
Fail to do a checkpoint syncing

### ISSUE THREAD

**Issue by JAVAN000B** [prysmaticlabs/prysm#12064]
### Discussed in https://github.com/prysmaticlabs/prysm/discussions/12060

<div type='discussions-op-text'>

<sup>Originally posted by **JAVAN000B** March  1, 2023</sup>
when i trying to use the --checkpoint-sync-url for syncing my node ,I notice that all urls provided form  https://eth-clients.github.io/checkpoint-sync-endpoints/ gave me 500 response. Here below is the logs

Error retrieving checkpoint origin state and block: erroe requesting state by id = finalized: code=500,url= https://sepolia.checkpoint-sync.ethdevops.io/.
(I tried all 3 urls provided ,none of them gave me 200 responses) 

So, I used --enable-debug-rpc-endpoints on my other node, which has already synced. And by replacing --checkpoint-sync-url to my own nodes ip:3500, I got following errors

level=info msg="detected supported config in remote finalized state, name=sepolia, fork=capella" Error retrieving checkpoint origin state and block : unable to unmarshal block to a supported type using the detected fork schedule: unable to initialize BeaconBlock for fork version=capella at slot=1821856

Any ideas about this problem? I am wondering if the checkpoint can still be used after the capella fork.
</div>

**Comment by nisdas** [comment]
Hey @JAVAN000B , for sepolia please use this release candidate:
https://github.com/prysmaticlabs/prysm/releases/tag/v3.2.2-rc.0

**Comment by JAVAN000B** [comment]
Thanks it wrorks,using the 3.2.2 version fix my problem !
