### ISSUE TITLE
Create health check for SyncService 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1206]
As part of #1183, all services should maintain a Status method that will return an error if there is any unhealthy status to report. This task requires some creative thinking to evaluate a definition of a healthy service. It is possible that a service can always be healthy and in that case we would simply remove the TODO and update the godoc to explain why the service is always healthy.

Service definition: beacon-chain/sync/service.go

What makes this service healthy or unhealthy?

Ideas:
- Service is not syncing
- Service is not synced

**Comment by cyberbono3** [comment]
working on it

**Comment by nisdas** [comment]
Closed by #1316
