### ISSUE TITLE
Sepolia: Could not process block

### ISSUE THREAD

**Issue by skliarovartem** [prysmaticlabs/prysm#12065]
Trying to run sync with geth and see in logs these messages:
`could not process block: could not validate new payload: method not found: received an undefined execution engine error`

prysm: v3.2.2
network: sepolia
geth: v1.11.2
then sometimes it is passed, but in case if prysm or node was rebooted there is no way to make it works, it is stuck on some block and sync is not going on

**Comment by skliarovartem** [comment]
Yes, Im sure about versions.
here is how I start services:
`/usr/bin/geth --sepolia --syncmode "light" --http --http.api net,eth,personal,web3,engine,admin,debug --authrpc.vhosts=localhost --authrpc.jwtsecret=/data_eth/ethereum/consensus/prysm/jwt.hex --datadir /data_eth/database`

`/data_eth/ethereum/consensus/prysm/prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --sepolia --jwt-secret=/data_eth/ethereum/consensus/prysm/jwt.hex --datadir=/data_eth/database --verbosity debug --checkpoint-sync-url=https://sepolia.checkpoint-sync.ethdevops.io --genesis-beacon-api-url=https://sepolia.checkpoint-sync.ethdevops.io`

**Comment by skliarovartem** [comment]
`Mar 01 07:23:47 ip-10-1-48-123 prysm.sh[12567]: time="2023-03-01 07:23:47" level=info msg="Processing block 0x3ab307d8... 1826528/1826818 - estimated time remaining 1m1s" blocksPerSecond=4.7 peers=20 prefix=initial-sync
Mar 01 07:23:47 ip-10-1-48-123 prysm.sh[12567]: time="2023-03-01 07:23:47" level=info msg="Processing block 0x9de4218f... 1826560/1826818 - estimated time remaining 41s" blocksPerSecond=6.2 peers=20 prefix=initial-sync
Mar 01 07:23:47 ip-10-1-48-123 prysm.sh[12567]: time="2023-03-01 07:23:47" level=debug msg="Could not process batch blocks due to missing parent" firstSlot=1826497 lastSlot=1826560 missingParent=0x983f06d19f2e69ea2cd9c292401b01a5bae1989e17c856f9885206f95a8d21a5 prefix=initial-sync`

**Comment by nisdas** [comment]
```
time="2023-03-01 07:07:32" level=warning msg="Block is not processed" error="could not process block: could not validate new payload: method not found: received an undefined execution engine error" prefix=initial-sync Mar 01 07:07:32
```
Means you are using a older version of geth, I expect this is no longer an issue anymore. Closing this issue now unless you are still running into issues.
