### ISSUE TITLE
Geth websocket keeps reconnecting the client

### ISSUE THREAD

**Issue by nivshitrit** [prysmaticlabs/prysm#12089]
# 💎 Issue

http request work perfectly, but my websocket keeps reconnecting the client.
client can connect to the ws, but after 20-30 seconds gets disconencted and reconnected, error message is:
`{"error": "websocket: close 1006 (abnormal closure): unexpected EOF"}
`
this are my ws related flags for geth:
```
--ws
--ws.origins=*
--ws.addr=0.0.0.0
```

im using the websocket on the default port 8546, not sure what else to do 

logs on the geth node look perfectly fine, couldnt find anything wrong in there.

### Background

 Context and background information on the discussion...

**Comment by nisdas** [comment]
This looks like an issue with geth, please open the issue there:
https://github.com/ethereum/go-ethereum
