### ISSUE TITLE
[docs?] Prysm stops with invalid argument when using datadir

### ISSUE THREAD

**Issue by jgresham** [prysmaticlabs/prysm#12105]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....
[docs?] Prysm stops with invalid argument when using datadir

## 🔬 Minimal Reproduction

Run the docker command in the docs at https://docs.prylabs.network/docs/install/install-with-docker#appendix-a-manage-prysm-with-docker
```
docker run -it -v $HOME/.eth2:/data -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node \
  gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
  --datadir=/data \
  --clear-db \
  --rpc-host=0.0.0.0 \
  --monitoring-host=0.0.0.0 \
  --execution-endpoint=<YOUR_ETH_EXECUTION_NODE_ENDPOINT> 
```
Remove datadir arugment and it works
## 🔥 Error

<pre><code>[2023-03-09 01:40:00]  WARN flags: Running on Ethereum Mainnet
[2023-03-09 01:40:00]  WARN node: In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient).
[2023-03-09 01:40:00]  INFO node: Checking DB database-path=/data/beaconchaindata
[2023-03-09 01:40:00]  INFO db: Opening Bolt DB at /data/beaconchaindata/beaconchain.db
invalid argument</code></pre>

Only the log "invalid argument" without specifying if datadir is incorrect

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Mac Ventura/Docker
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    or
gcr.io/prysmaticlabs/prysm/beacon-chain@sha256:7c80d751daca74a9c50ec2e4524ca95b093563700a050e6863096efd263adae1
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
This is an odd error, this is a standard command that many users to run prysm and it hasn't changed in a while. If you replace `$HOME` with the path to your actual home directory, does it work ?

**Comment by jgresham** [comment]
I can see that `beaconchaindata` & `beaconchaindata/beaconchain.db` get created at `$HOME/.eth2`. Also prysm runs when changing the value passed to `--datadir` to something other than `/data` (but the data won't persist between runs). hmm

**Comment by james-prysm** [comment]
wanted to check in on the status of this. are you still having issues? @jgresham

**Comment by jgresham** [comment]
yes, I am, however, I was had an alias setup for docker, so I was actually using `podman` (docker alternative). I don't have this issue on Windows. I'm also using an M1, apple chip mac.

**Comment by jgresham** [comment]
I'll try to test with Docker on my mac tonight or tomorrow. Would still be nice to have a more description error log than "invalid argument" from the container if possible

**Comment by james-prysm** [comment]
the invalid argument refers to the message above, opening at /data/beaconchaindata/beaconchain.db seems to fail perhaps it can't find the path from your current setup.

**Comment by jgresham** [comment]
<img width="719" alt="Captura de pantalla 2023-03-23 a la(s) 12 12 02 p m" src="https://user-images.githubusercontent.com/3721291/227323614-0f519ea1-23b7-4c96-8bea-15ce51865874.png">
 
I see that prysm creates the file. I've tried deleting it and re-starting prysm. I also ran `chmod 777 ` on it to make sure it wasn't a permissions issue. Additionally, it seems that prysm reads the jwtsecret fine.

**Comment by james-prysm** [comment]
Did not see any more updates since this last comment, issue is stale, will reopen if not resolved.
