### ISSUE TITLE
Restarted beacon-chain cannot generate blocks.

### ISSUE THREAD

**Issue by egonspace** [prysmaticlabs/prysm#12104]
# 💎 Issue
I set up a private pos chain with prysm interop configuration referring https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet.

The private chain was successfully launched, but the block is not generated when the process of geth, beacon-chain, and validator was terminated and restarted.

```
[2023-03-09 13:52:58]  INFO rpc: gRPC client connected to beacon node addr=127.0.0.1:49217
[2023-03-09 13:53:10]  INFO powchain: Connected to new endpoint: http://localhost:8551
[2023-03-09 13:53:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:54:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:55:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:56:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:57:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:58:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
[2023-03-09 13:59:55]  INFO p2p: Peer summary activePeers=0 inbound=0 outbound=0
...
```

beacon-chain command:
```
beacon-chain \
--datadir=/.beacon/data \
--min-sync-peers=0 \
--interop-genesis-state=/.prysm/genesis.ssz \
--interop-eth1data-votes \
--bootstrap-node=  \
--chain-config-file=/.prysm/config.yml \
--config-file=/.prysm/config.yml \
--chain-id=7688  \
--execution-endpoint=http://localhost:8551 \
--accept-terms-of-use \
--jwt-secret=/.geth/data/geth/jwtsecret \
--suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
```

What's the problem?

### Background

 Context and background information on the discussion...

**Comment by egonspace** [comment]
I lacked the understanding of the beacon chain. When a node starts, there seems to be a process of waiting for syncing based current time, which seems to be waiting indefinitely.

What I'm curious about is whether there is an implementation that assumes a local private network in the beacon chain. Because local networks should be able to stop for a certain period of time.

**Comment by nisdas** [comment]
It appears your validator is offline ? I don't see any blocks /attestations from it.

**Comment by egonspace** [comment]
validator waits for node's syncing forever.

**Comment by nisdas** [comment]
You need to regenerate the genesis state so that your genesis time is not in the past

**Comment by egonspace** [comment]
Are you saying that if I regenerate the genesis state, I have to start creating blocks from block 0? I want to continue creating blocks on top of the existing ones. When I regenerated the `genesis.ssz` file and ran it with the existing blocks still in place, I encountered the following error.

```
Could not process attestations and update head error=could not process block: could not process block header: parent root 0x1ddeea5937355e7a0f2c257ab01744c114c6f1c7e2eaad74a06c233285f742d9 does not match the latest block header signing root in state 0xcfd02715f250a89136e40ea3b156ef11ea86988581c72ef4dc69689eb6b93fc9
```

**Comment by nisdas** [comment]
> Are you saying that if I regenerate the genesis state, I have to start creating blocks from block 0?

Yes

**Comment by egonspace** [comment]
Okay, I see. I close this.
