### ISSUE TITLE
Unable to run validators on local devnet

### ISSUE THREAD

**Issue by ayazabbas** [prysmaticlabs/prysm#12122]
# 🐞 Bug Report

### Description

How do I run validators on a local devnet?

I used the staking-cli-tool to generate keys, I imported these using `validator accounts import` and then spun up a validator client with --wallet-dir set. This is all using prysm v3.2.1

I also called the deposit function on the beacon deposit contract for each validator in the generated deposit_data.json file.

Error in the validator client:
```
msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0xa899f495274d status="UNKNOWN_STATUS"
```

Error in the beacon client:
```
msg="Not connected to ETH1. Cannot determine validator ETH1 deposit block number" prefix="rpc/validator"
```

The network is running fine with the deterministic interop validator settings, but I can't add additional validators. Am I missing an intermediate step or something? The beacon -> geth connection seems fine because the network progresses normally with the interop validators performing duties.

### Has this worked before in a previous version?
Never tried before.

## 🔬 Minimal Reproduction
Run a local devnet as in https://github.com/rauljordan/eth-pos-devnet and attempt to create additional validators as in https://docs.prylabs.network/docs/install/install-with-script#step-5-run-a-validator-using-prysm

## 🌍  Your Environment

**Operating System:**
Ubuntu

**What version of Prysm are you running? (Which release)**
v3.2.1

## Additional Information
beacon command:
```
/usr/local/bin/beacon-chain --datadir=/data/prysm --min-sync-peers=0 --minimum-peers-per-subnet=0 --genesis-state=/data/prysm/genesis.ssz --interop-eth1data-votes --chain-config-file=/data/prysm/config.yml --config-file=/data/prysm/config.yml --chain-id=3737 --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --grpc-gateway-port 5052 --grpc-max-msg-size=65568081 --enable-debug-rpc-endpoints --execution-endpoint=http://localhost:8551 --accept-terms-of-use --jwt-secret=/data/ethereum/geth/jwtsecret --suggested-fee-recipient=0x48bdc4Ed4b6c6a0E32bD2D7075c99eD5F917DDA0 --p2p-priv-key=/data/prysm/privkey --http-mev-relay=http://127.0.0.1:18550 --max-builder-consecutive-missed-slots 30000 --max-builder-epoch-missed-slots 33 --bootstrap-node=
```

validator command:
```
/usr/local/bin/validator --beacon-rpc-provider=127.0.0.1:4000 --datadir=/data/prysm/validator --accept-terms-of-use --wallet-dir=/home/ubuntu/wallet --wallet-password-file=/home/ubuntu/passwd --chain-config-file=/data/prysm/config.yml --config-file=/data/prysm/config.yml --suggested-fee-recipient=0x48bdc4Ed4b6c6a0E32bD2D7075c99eD5F917DDA0 --enable-builder
```

geth command:
```
/usr/local/bin/geth --http --http.api "eth,engine" --datadir=/data/ethereum --allow-insecure-unlock --unlock="0x48bdc4Ed4b6c6a0E32bD2D7075c99eD5F917DDA0" --password=/data/ethereum/.gethpasswd --syncmode=full --networkid=3737 --mine --miner.etherbase="0x48bdc4Ed4b6c6a0E32bD2D7075c99eD5F917DDA0" --log.json --metrics --metrics.addr 127.0.0.1
```

**Comment by ayazabbas** [comment]
From discussion on Discord it looks like this may be resolved by PR https://github.com/prysmaticlabs/prysm/pull/12125 - I will update here if that's the case.

**Comment by james-prysm** [comment]
@ayazabbas https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet our document got updated, try it again when you have time and let us know if we can close this.

**Comment by james-prysm** [comment]
issue became stale, please reach out if it's not working for you.
