### ISSUE TITLE
mDNS data race from upstream dependencies

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1212]
This is a general tracking bug to update the upstream dependencies after the following PRs have been merged:

- https://github.com/libp2p/go-libp2p/pull/513
- https://github.com/whyrusleeping/mdns/pull/4

I only experience these data races locally and buildkite seems happy about them. 
Anyway, I think it should be fixed so I fixed it.

**Comment by rauljordan** [comment]
Can we close this @prestonvanloon?

**Comment by prestonvanloon** [comment]
We don't use mDNS discovery anymore. Closing
