### ISSUE TITLE
`beacon-chain`  fails to parse `genesis.ssz` generated with `minimal` preset

### ISSUE THREAD

**Issue by 0x416e746f6e** [prysmaticlabs/prysm#12142]
# 🐞 Bug Report

### `beacon-chain`  fails to parse genesis.ssz generated with `minimal` preset

When I try to plug prysm beacon into a local privatenet (for testing) that runs on top of `minimal` preset, it fails with error:

> could not load genesis from file: failed to unmarshal state, detected fork=phase0: incorrect size

### Has this worked before in a previous version?

I don't think so.  Looking at the code in `proto/prysm/v1alpha1/generated.ssz.go` I see that it hardcodes the value of `8192` for `SLOTS_PER_HISTORICAL_ROOT` while in case of `minimal` it's `64`.

## 🔬 Minimal Reproduction

```bash
echo 0 > deploy_block.txt

curl https://raw.githubusercontent.com/ethereum/consensus-specs/v1.2.0/configs/minimal.yaml > config.yaml

docker run --rm -v "$(pwd):/data" sigp/lcli:v3.4.0 \
  lcli interop-genesis \
    --genesis-time 1678954188 \
    --spec minimal \
    --testnet-dir /data

curl https://raw.githubusercontent.com/ethereum/consensus-specs/v1.2.0/configs/minimal.yaml > config.yaml

docker run --rm -v "$(pwd):/data" gcr.io/prysmaticlabs/prysm/beacon-chain:v3.2.2 \
  --accept-terms-of-use \
  --chain-config-file /data/config.yaml  \
  --genesis-state /data/genesis.ssz
```

## 🔥 Error

<pre><code>
time="2023-03-16 12:55:39" level=warning msg="Running on Ethereum Mainnet" prefix=flags
time="2023-03-16 12:55:39" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node
time="2023-03-16 12:55:39" level=info msg="Checking DB" database-path="/home/.eth2/beaconchaindata" prefix=node
time="2023-03-16 12:55:39" level=info msg="Opening Bolt DB at /home/.eth2/beaconchaindata/beaconchain.db" prefix=db
could not load genesis from file: failed to unmarshal state, detected fork=phase0: incorrect size
</code></pre>

## 🌍  Your Environment

**Operating System:**

I use MacOS, but this also happens (obviously) on Linux.

**What version of Prysm are you running? (Which release)**

`v3.2.2`

**Comment by prestonvanloon** [comment]
@0x416e746f6e yes -- the provided docker images are built with compile time configuration for mainnet state size config. If you wish to run a minimal state, you must build with minimal config. Using `--config=minimal` and building with bazel is the recommended approach. Alternatively, you can do the following to use go tooling:

```sh
# regenerate the generated files with hardcoded values
# bazel is required for this step
./hack/update-go-ssz.sh --config=minimal

# build with go 
go build ./cmd/beacon-chain -tags minimal -o prysm-beacon-chain

# run it
./prysm-beacon-chain --accept-terms-of-use --chain-config-file /data/config.yaml --genesis-state /data/genesis.ssz
```
