### ISSUE TITLE
Validator to Relayer `GetHeader` takes 400ms to arrive. Why?

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12187]
On the [Mevconomics.wtf Summit](https://www.youtube.com/watch?v=t3sL0sCJFzk&t=4233s), Elaine Hu pointed out on average relayer receives `GetHeader` request on average **400ms** into the slot. This seems much longer than I had thought. Ideally, the relayer should receive the request close to the slot start. Here are a few reasons on top of my mind:
1. Network latency between beacon node -> relayer 
2. Beacon node does some things before calling `GetHeader` (i.e pack attestations, slashings...etc). Prysm's block-building process is sequential and doesn't need to be sequential. We should be able to parallelize block construction   
3. Mev-boost itself adds delay 

I think the reason is a mixture between 1 and 2. I don't have good data, so I think the first step is adding some good metrics and logs to monitor this. It's good to look into this problem now because it'll only get worse with EIP4844

**Comment by elenahoo** [comment]
The average is based on 1800 blocks, some more details from the original post I quoted the number from https://bloxroutelabs.medium.com/mastering-defi-trading-block-building-and-mev-f662650736c0

**Comment by rauljordan** [comment]
hi @terencechain we can likely close this right? we'll have a chance at gathering more data with parallel block construction later on
