### ISSUE TITLE
prysm stuck in processing slot 6076224 after geth crash and restart

### ISSUE THREAD

**Issue by niekaixuan** [prysmaticlabs/prysm#12186]
# 💎 Issue

### Background

before error occurs, I kill geth with -9 args，I suspect it's a crash. what shoud I do so that I can resync immediately rather than from the scratch

=== system info ===
Geth version: 1.11.4-stable
CL client & version: prysm@v3.2.2
OS & Version: Linux

### Description
my prysm process stuck in the process slot 6076224, and the logs prompts me that  "could not validate new payload: received an INVALID payload from execution engine", however, geth logs out that "Post-merge network, but no beacon client seen. Please launch one to follow the chain! "

==== logs from prysm
time="2023-03-25 18:36:14" level=info msg="Processing block 0xa19d173d... 6076224/6076379 - estimated time remaining 1m43s" blocksPerSecond=1.5 peers=51 prefix=initial-sync
time="2023-03-25 18:36:14" level=info msg="Processing block 0x248e65b7... 6076256/6076379 - estimated time remaining 39s" blocksPerSecond=3.1 peers=51 prefix=initial-sync
time="2023-03-25 18:36:38" level=info msg="Peer summary" activePeers=48 inbound=45 outbound=3 prefix=p2p
time="2023-03-25 18:36:44" level=warning msg="Pruned invalid blocks" blockRoot=0xb0f25987804255e678e57bb8cf5b85fdd5f6eb3fd6cf9b24cefff5a87d929f36 invalidChildrenCount=0 prefix=blockchain slot=6076195
time="2023-03-25 18:36:44" level=warning msg="Block is not processed" error="could not process block: could not validate new payload: received an INVALID payload from execution engine" prefix=initial-sync
time="2023-03-25 18:36:44" level=info msg="Processing block 0xa19d173d... 6076224/6076381 - estimated time remaining 1m44s" blocksPerSecond=1.5 peers=48 prefix=initial-sync
time="2023-03-25 18:36:44" level=info msg="Processing block 0x248e65b7... 6076256/6076381 - estimated time remaining 40s" blocksPerSecond=3.1 peers=48 prefix=initial-sync
time="2023-03-25 18:37:02" level=warning msg="Pruned invalid blocks" blockRoot=0xb0f25987804255e678e57bb8cf5b85fdd5f6eb3fd6cf9b24cefff5a87d929f36 invalidChildrenCount=0 prefix=blockchain slot=6076195
time="2023-03-25 18:37:02" level=warning msg="Block is not processed" error="could not process block: could not validate new payload: received an INVALID payload from execution engine" prefix=initial-sync
time="2023-03-25 18:37:02" level=info msg="Processing block 0xa19d173d... 6076224/6076383 - estimated time remaining 33s" blocksPerSecond=4.7 peers=53 prefix=initial-sync
time="2023-03-25 18:37:02" level=info msg="Processing block 0x248e65b7... 6076256/6076383 - estimated time remaining 20s" blocksPerSecond=6.3 peers=54 prefix=initial-sync
time="2023-03-25 18:37:38" level=info msg="Peer summary" activePeers=42 inbound=41 outbound=1 prefix=p2p
time="2023-03-25 18:37:58" level=warning msg="Pruned invalid blocks" blockRoot=0xb0f25987804255e678e57bb8cf5b85fdd5f6eb3fd6cf9b24cefff5a87d929f36 invalidChildrenCount=0 prefix=blockchain slot=6076195
time="2023-03-25 18:37:58" level=warning msg="Block is not processed" error="could not process block: could not validate new payload: received an INVALID payload from execution engine" prefix=initial-sync
time="2023-03-25 18:37:58" level=info msg="Processing block 0xa19d173d... 6076224/6076387 - estimated time remaining 1m48s" blocksPerSecond=1.5 peers=47 prefix=initial-sync
time="2023-03-25 18:37:58" level=info msg="Processing block 0x248e65b7... 6076256/6076387 - estimated time remaining 42s" blocksPerSecond=3.1 peers=47 prefix=initial-sync
time="2023-03-25 18:38:38" level=info msg="Peer summary" activePeers=47 inbound=47 outbound=0 prefix=p2p
time="2023-03-25 18:39:38" level=info msg="Peer summary" activePeers=46 inbound=46 outbound=0 prefix=p2p
time="2023-03-25 18:40:38" level=info msg="Peer summary" activePeers=45 inbound=45 outbound=0 prefix=p2p
time="2023-03-25 18:41:33" level=warning msg="Pruned invalid blocks" blockRoot=0xb0f25987804255e678e57bb8cf5b85fdd5f6eb3fd6cf9b24cefff5a87d929f36 invalidChildrenCount=0 prefix=blockchain slot=6076195
time="2023-03-25 18:41:33" level=warning msg="Block is not processed" error="could not process block: could not validate new payload: received an INVALID payload from execution engine" prefix=initial-sync
time="2023-03-25 18:41:33" level=info msg="Processing block 0xa19d173d... 6076224/6076405 - estimated time remaining 2m0s" blocksPerSecond=1.5 peers=51 prefix=initial-sync
time="2023-03-25 18:41:33" level=info msg="Processing block 0x248e65b7... 6076256/6076405 - estimated time remaining 48s" blocksPerSecond=3.1 peers=51 prefix=initial-sync
time="2023-03-25 18:41:38" level=info msg="Peer summary" activePeers=51 inbound=48 outbound=3 prefix=p2p

==== logs from geth ====
WARN [03-25|18:24:33.205] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:25:09.201] Checkpoint challenge timed out, dropping id=b7c49b425d5e0340 conn=inbound addr=18.197.3.70:58412     type=erigon/v2.37.0-stabl...
WARN [03-25|18:25:48.213] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:26:22.784] Checkpoint challenge timed out, dropping id=3d928d9a6f744124 conn=inbound addr=18.194.164.44:41866   type=erigon/v2.40.1-stabl...
WARN [03-25|18:27:19.030] Snapshot extension registration failed   peer=cd0e3f58 err="peer connected on snap without compatible eth support"
WARN [03-25|18:27:38.020] Rewinding blockchain to block            target=377,753,600
INFO [03-25|18:27:38.021] Loaded most recent local block           number=16,841,876 hash=88004b..8ae0f0 td=58,750,003,716,598,352,816,469 age=1w1d17h
INFO [03-25|18:27:38.021] Loaded most recent local finalized block number=16,841,788 hash=08b319..cd4a62 td=58,750,003,716,598,352,816,469 age=1w1d17h
INFO [03-25|18:27:38.021] Loaded last fast-sync pivot marker       number=16,837,867
WARN [03-25|18:28:08.227] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:28:58.233] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:31:53.256] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:32:19.409] Snapshot extension registration failed   peer=8ea667b8 err="peer connected on snap without compatible eth support"
WARN [03-25|18:33:48.269] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:37:33.296] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:38:19.783] Snapshot extension registration failed   peer=78b25cdc err="peer connected on snap without compatible eth support"
WARN [03-25|18:38:28.304] Post-merge network, but no beacon client seen. Please launch one to follow the chain! 
WARN [03-25|18:42:08.325] Post-merge network, but no beacon client seen. Please launch one to follow the chain!

**Comment by nisdas** [comment]
This looks like an issue with geth database corruption so it doesnt have anything to do with prysm. This message indicates
```
my prysm process stuck in the process slot 6076224, and the logs prompts me that "could not validate new payload: received an INVALID payload from execution engine", however, geth logs out that "Post-merge network, but no beacon client seen. Please launch one to follow the chain! "

```
geth is marking valid blocks as invalid. Closing this issue unless you feel otherwise.
