### ISSUE TITLE
Incorrect safeBlockHash in fcU with payload attributes

### ISSUE THREAD

**Issue by michaelsproul** [prysmaticlabs/prysm#12195]
# 🐞 Bug Report

### Description

While testing Prysm with my execution multiplexer ([eleel](https://github.com/michaelsproul/eleel)) I noticed that some of Prysm's forkchoiceUpdated messages were not matching Lighthouse.

I tracked it down to Prysm sometimes setting the `safeBlockHash` to the `finalizedBlockHash` rather than the `justifiedBlockHash`. I noticed that this seems to happen only for fork choice updates that include payload attributes, which at a glance makes sense given the code here:

https://github.com/prysmaticlabs/prysm/blob/f5bfb8e9eb8c00adb7e72396183e4e14d41abb25/beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go#L139-L143

This isn't a critical bug, and I think the impact is minimal. For now I'll work around it in `eleel`.

### Has this worked before in a previous version?

Not sure. I noticed it on v3.2.2 and upgrading to v4.0.0 didn't fix it.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04 x86_64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v4.0.0
  </code>
</pre>

**Comment by potuz** [comment]
Oh nice catch thanks for the report @michaelsproul will move to unrealized justified checkpoint all of those
