### ISSUE TITLE
Unable to use `prysmctl validator withdraw` with Prater/Goerli

### ISSUE THREAD

**Issue by pablote** [prysmaticlabs/prysm#12209]
I'm trying to follow this guide for setting up the execution address on my testnet validator in Prater/Goerli: https://docs.prylabs.network/docs/wallet/withdraw-validator

When I run prysmctl with the following command: `./prysmctl validator withdraw --beacon-node-host=http://localhost:3500 --path=./staking_deposit-cli/bls_to_execution_changes/bls_to_execution_change-1680129667.json` (plus the confirm flags)

I get the following response:
```
FATA[0002] Could not set withdrawal addresses            error="setting withdrawals using the BLStoExecutionChange endpoint is only available after the Capella/Shanghai hard fork."
```

I understand this is not available on mainnet yet, but shouldn't this work on goerli? I'm connecting to a beacon node which is running on prater, also the bls change json file has a `"network_name": "goerli",` at some point. I've also tried adding flags to this command line like `--prater` `--goerli` `--network=goerli` but no luck.

**Comment by nisdas** [comment]
@pablote Which version is this ? this should be fixed on `v4.0.1`

**Comment by pablote** [comment]
```
# ./beacon-chain --version
beacon-chain version Prysm/v4.0.0/191e603e2816e63ca8b1d2615634108e009caceb. Built at: 2023-03-28 14:58:35+00:00
```

I can't seem to get a version from prysmctl but I'm pretty sure I downloaded the latest one from the releases page. I'm gonna try  redownloading just to be sure.

**Comment by james-prysm** [comment]
there was a bug but has since been fixed and merged in, it should be in the latest version. it tries to get the current version of the fork on the beacon node so please double check if that network is in fact a prater node. please let us know if you're still running into issues.

**Comment by pablote** [comment]
I've just redownloaded and it worked fine now. Thanks.
