### ISSUE TITLE
The beacon state in checkpoint is invalid.

### ISSUE THREAD

**Issue by zghh** [prysmaticlabs/prysm#12206]
# 🐞 Bug Report

### Description

I started the first prysm node with `--enable-debug-rpc-endpoints` flag and it worked fine. Then I started the second node with `--checkpoint-sync-url` flag to pull the checkpoint from the first node, but the following error occurred when the second node started.

### Has this worked before in a previous version?

This bug was not present in the previous version.

## 🔥 Error

<pre><code>'time='2023-03-15 14:04:35' level=info msg='Finished reading JWT secret from /workdir/execution/jwtsecret''
'time='2023-03-15 14:04:35' level=warning msg='Running on the Prater Testnet' prefix=flags'
'time=''2023-03-15 14:04:35'' level=warning msg=''In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient).'' prefix=node'
'time='2023-03-15 14:04:35' level=info msg='Checking DB' database-path='/workdir/consensus/beaconchaindata' prefix=node'
'time='2023-03-15 14:04:35' level=info msg='Opening Bolt DB at /workdir/consensus/beaconchaindata/beaconchain.db' prefix=db'
'time=''2023-03-15 14:04:35'' level=warning msg=''database contains genesis with htr=0x895390e92edc03df7096e9f51e51896e8dbe6e7e838180dadbfd869fdd77a659, ignoring remote genesis state parameter'''
'time=''2023-03-15 14:04:37'' level=info msg=''detected supported config in remote finalized state, name=prater, fork=capella'''
'Error retrieving checkpoint origin state and block: finalized state slot does not match latest block header slot 5195936 != 5195935'
</code></pre>

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

<pre><code>v3.2.2</code></pre>

**Comment by potuz** [comment]
Thanks for the report, this seems to be a bug, the first block of that epoch,  5195936 was missed. You could try again on a different epoch and it should succeed I guess.

**Comment by zghh** [comment]
Is there a plan to fix this bug? Because it is a long time for an epoch.

**Comment by potuz** [comment]
The problem has been identified and is being fixed, but I didn't understand the comment on it being a long time for an epoch?

**Comment by zghh** [comment]
> The problem has been identified and is being fixed, but I didn't understand the comment on it being a long time for an epoch?

If a slot is 12s, an epoch contains 32 slots, the node only starts successfully on a different epoch after waiting for 384s.

**Comment by LilkkJerry** [comment]
@potuz Hi, i met the same problem with v4.0.1, has it already fixed in v4.0.2 or v4.0.3? Thanks :)
