### ISSUE TITLE
Impact on Ethereum node performance if moving beacon data from SSD to HDD

### ISSUE THREAD

**Issue by NakedKoala** [prysmaticlabs/prysm#12215]
Definition of Ethereum node performance metrics:

* response latency for its rpc method
* delay in hearing about new block event & pendingTx (via subscription to these event streams)

(I am using GETH) 

Question:

Does Prysm deliver what Ethereum execution client need ( in order NOT to have these 2 metrics deteriorate) before it flushes the data onto disk ?  If this is true, then moving the beacon data directory to slower disk would be ok ? 

Can developer confirm that this is true ?

**Comment by rauljordan** [comment]
hi @NakedKoala unfortunately it is not possible to use an execution client without an SSD, and I believe you will also have a lot of these problems with Prysm if you do not use an SSD. The node simply cannot sync and an execution client will never catch up to the chain head without an SSD. It's a minimum requirement
