### ISSUE TITLE
confusion about fee recipient

### ISSUE THREAD

**Issue by garyng2000** [prysmaticlabs/prysm#12213]
in order to dynamically update a fee recipient of a given validator, I believe the key manager api should be used. but how this is persisted is a bit confused to me as there were a few issue tickets about this.

Below are the questions I have
1. Assuming I supplied a proposed-setting-file with 3 validators setting, and use the key manager api to update one of them, would the old value used on validator restart or that the new one would be 'persisted' to the file ?
2.  assuming I don't provide a setting-file and do an initial setup via key manager, would the setting persist on validator restart ?
3.  assuming I use proposed-setting-url instead, I would think that I have to keep the url content in sync with whatever changed via key manager api such that on restart the 'revised' value would be used ?

**Comment by garyng2000** [comment]
what if the beacon node is restarted ? or that info actually is 'broadcasted' to the beacon chain ?

**Comment by james-prysm** [comment]
the beacon node persists it in the db so it'll keep the values

**Comment by james-prysm** [comment]
closing this issue as there have not been additional questions.
