### ISSUE TITLE
 Slow performance on `eth/v1/beacon/states/head/validators`

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12252]
Reported by @metachris, he conducted a performance test to get all validators from the CL clients using the command time curl http://localhost:3500/eth/v1/beacon/states/head/validators. However, running this command on the machine where Prysm is running took 19 seconds to complete. This is significantly slower than Lighthouse, which took only 2 seconds to complete

**Comment by rkapka** [comment]
I just checked this after migrating to pure HTTP endpoints. On Prater with over 600k validators the request takes around 1.2s - 1.4s
