### ISSUE TITLE
GOMAXPROCS env

### ISSUE THREAD

**Issue by keithchew** [prysmaticlabs/prysm#12253]
Hi

I am on prysm v4.0.0, and I would like to define GOMAXPROCS from the environment variable. However, I can see in cmd/beacon-chain/main.go (line 200), we have:
```
		runtime.GOMAXPROCS(runtime.NumCPU())
```
which is not respecting the env variable? If so, is there another way to set GOMAXPROCS?

**Comment by prestonvanloon** [comment]
I think we should remove that line about setting GOMAXPROCS. Otherwise, there is no way to override it and I believe the default is NumCPU anyway

**Comment by prestonvanloon** [comment]
@keithchew

Thanks for confirming that. If you would like to send a PR removing any
instances of this issue, I will review it early this week with the team and
merge it if we don't find any valid reason for the code to be there.
