### ISSUE TITLE
Mev-boost got a good best bid with larger reward, but Prysm still built locally with a small reward.

### ISSUE THREAD

**Issue by biteric2000** [prysmaticlabs/prysm#12289]
# 🐞 Bug Report

### Description
Something really weird happened with my validator. 
MEV boost got a good best bid of 0.196 ETH, but Prysm still built locally without asking relay for the block body. 
Instead, we only got a ~0.018 ETH of local block produce reward. (Shown in the "produced block" tab of the fee recipient and no related "internal transaction" found.)

The network seems fine. Both prysm and mev log around it was normal info.

## 🔥 Log
<pre><code>[MEV-Boost log]
time="2023-Txxxx" level=info msg="best bid" blockHash=0xnnnnn blockNumber=xxxx method=getHeader parentHash=0xmmmmm pubkey=0xnnnnn relays="https://0xa7ab7a996c8584251c8f925da3170bdfd6ebc75d50f5ddc4050a6fdc77f2a3b5fce2cc750d0865e05d7228af97d69561@agnostic-relay.net" slot=xxxxx txRoot=xxxxx value=0.195513127666416350

[Prysm log]
[2023-xxxx]  INFO rpc/validator: Received header with bid blockHash=0xnnnnn builderPubKey=0xnnnnn value=195513127666416350

[2023-xxxx]  WARN rpc/validator: Proposer: using local execution payload because higher value builderGweiValue=195513127666416350 localBoostPercentage=100 localGweiValue=18395081606530051
</code></pre>

Wondering what does the  "because higher value builderGweiValue" and "localBoostPercentage=100" mean. 

And apparently 0.018 ETH is of much lower value than 0.196 ETH, how could the client instead choose to build locally?

PS. We double checked and never configed the minimal value to build locally option, all blocks are built default with mev relay.

Software Versions: Prysm 4.0.2 MEV-boost 1.50

### Has this worked before in a previous version?
This has never happened before.
Been staking for a long time, with a number of successfully proposed blocks.

**Comment by potuz** [comment]
Thanks, bug identified, fix coming in a couple of hours
