### ISSUE TITLE
Use Simulated Backend to Write YAML Tests for Epoch Transition

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#1230]
Similar to #718, #1185. In this case, we want PR that can successfully transition through different epochs. This would allow us to have high confidence in our runtime if epoch transitions can execute flawlessly from a YAML test.

A follow-up PR can implement better debugging tools and perhaps a dump of the state at the beginning of each epoch to visualize: 
1.) validator status, balances and who has been rewarded/penalized 
2.) current justification and finalization status of previous epoch slots

**Comment by rauljordan** [comment]
Deprecated as we now use spec tests from https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests and their YAML format to test all core transition items
