### ISSUE TITLE
Validators Without MEV failing on Prysm v4.0.2

### ISSUE THREAD

**Issue by danspina1** [prysmaticlabs/prysm#12311]
### Description

We are running multiple validators without MEV enabled and every single one of those validators has failed to produce a block. (5 in the last 24 hours)

### Has this worked before in a previous version?

Yes, prior to the v4.0.2 it worked

## 🔬 Minimal Reproduction

Since the rest of our validators  are running with MEV and are working fine, I'd suggest turning MEV off 

## 🔥 Error

The below are two of the examples we are seeing

From validators: 

`Failed to request block from beacon node" blockSlot=6260812 error="rpc error: code = Unknown desc = runtime error: invalid memory address or nil pointer dereference" prefix=validator pubKey=0x8c3c1e4c2ee3`

`time="2023-04-20 04:17:35" level=error msg="Failed to request block from beacon node" blockSlot=6261686 error="rpc error: code = Unknown desc = runtime error: invalid memory address or nil pointer dereference" prefix=validator pubKey=0x8c6893e3f7c5` 

From beacon: 

`time="2023-04-20 04:17:35" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 661819656 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/prysmaticlabs/prysm/v4/monitoring/tracing.RecoveryHandlerFunc({0xc1c078?, 0xc120dd6150?}, {0x3f5d00?, 0x2daac00})
	monitoring/tracing/recovery_interceptor_option.go:29 +0x1f7
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0xc1c078?, 0xc120dd6150?}, {0x3f5d00?, 0x2daac00?}, 0xc087092180?)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:29 +0x7b
panic({0x3f5d00, 0x2daac00})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/prysmaticlabs/prysm/v4/beacon-chain/builder.(*Service).GetHeader(0xc000225bf0, {0xc1c040?, 0xc0bc643980?}, 0x3f3fc0?, {0xc, 0x9a, 0xa1, 0x8, 0xe1, 0xe9, ...}, ...)
	beacon-chain/builder/service.go:105 +0x140
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/prysm/v1alpha1/validator.(*Server).getPayloadHeaderFromBuilder(0xc000e08000, {0xc1c078, 0xc120dd68d0}, 0x5?, 0xc10c84d180?)
	beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:147 +0x350
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/prysm/v1alpha1/validator.(*Server).setExecutionData(0xc000e08000?, {0xc1c078, 0xc120dd68d0}, {0xc3b740, 0xc086e85c00}, {0xc41e48, 0xc0cdccd440})
	beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go:52 +0x297
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/prysm/v1alpha1/validator.(*Server).GetBeaconBlock(0xc000e08000, {0xc1c078?, 0xc120dd6840?}, 0xc086e85b20)
	beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go:123 +0xf28
github.com/prysmaticlabs/prysm/v4/proto/prysm/v1alpha1._BeaconNodeValidator_GetBeaconBlock_Handler.func1({0xc1c078, 0xc120dd6840}, {0x568fc0?, 0xc086e85b20})
	bazel-out/k8-opt-ST-4a519fd6d3e4/bin/proto/prysm/v1alpha1/go_proto_/github.com/prysmaticlabs/prysm/v4/proto/prysm/v1alpha1/validator.pb.go:4894 +0x78
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc1c078?, {0xc1c078, 0xc120dd6840}, {0x568fc0, 0xc086e85b20}, 0x33282a0?, 0xc10058ed50)
	beacon-chain/rpc/service.go:438 +0x50
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xc1c078?, 0xc120dd6840?}, {0x568fc0?, 0xc086e85b20?})
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1({0xc1c078, 0xc120dd6150}, {0x568fc0, 0xc086e85b20}, 0x10?, 0xc0860f99c0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:34 +0x11e
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xc1c078?, 0xc120dd6150?}, {0x568fc0?, 0xc086e85b20?})
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0xc1c078, 0xc120dd6150}, {0x568fc0, 0xc086e85b20}, 0xc01c751970?, 0xc0860f9bc0)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xc1c078?, 0xc120dd6150?}, {0x568fc0?, 0xc086e85b20?})
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0xc1c078?, 0xc120dd6150?}, {0x568fc0?, 0xc086e85b20?}, 0x7ed3a446c6d0?, 0xc0860f99a0?)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:33 +0xc4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xc1c078?, 0xc120dd6150?}, {0x568fc0?, 0xc086e85b20?})
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0xc1c078, 0xc120dd6150}, {0x568fc0, 0xc086e85b20}, 0xc01c751ae8?, 0x3f4a40?)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xbe
github.com/prysmaticlabs/prysm/v4/proto/prysm/v1alpha1._BeaconNodeValidator_GetBeaconBlock_Handler({0x67db80?, 0xc000e08000}, {0xc1c078, 0xc120dd6150}, 0xc0e181af60, 0xc000527860)
	bazel-out/k8-opt-ST-4a519fd6d3e4/bin/proto/prysm/v1alpha1/go_proto_/github.com/prysmaticlabs/prysm/v4/proto/prysm/v1alpha1/validator.pb.go:4896 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f4380, {0xc293a0, 0xc0001d9800}, 0xc1170ead80, 0xc00029d710, 0x2dcb8d8, 0x0)
	external/org_golang_google_grpc/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0004f4380, {0xc293a0, 0xc0001d9800}, 0xc1170ead80, 0x0)
	external/org_golang_google_grpc/server.go:1626 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	external/org_golang_google_grpc/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:939 +0x28a`

## 🌍  Your Environment
Linux Ubuntu 20.04

**What version of Prysm are you running? (Which release)**

Prysm 4.0.2
Geth 1.11.5

**Comment by terencechain** [comment]
This will be fixed in v4.0.3. ETA is today or tomorrow (depends on your timezone)

**Comment by james-prysm** [comment]
closing for now, there are a few other mev related items that are addressed in already open issues.
