### ISSUE TITLE
Can I connect other validators(e.g. Lighthouse, Teku..) to Prysm beacon node?

### ISSUE THREAD

**Issue by LilkkJerry** [prysmaticlabs/prysm#12320]
# 💎 Issue

Hi,

I wonder that is it possible to connect other validator to Prysm beacon node? 

### Description

I would like to enrich my validator types, however, some of them will connect to a prysm beacon node. I wonder is it possible to do this, and is it recommended?

**Comment by rkapka** [comment]
Hi @LilkkJerry. Yes, it is possible as the beacon node supports https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/ValidatorRequiredApi

**Comment by LilkkJerry** [comment]
Hi @rkapka , thanks for your reply！
I noticed that currently Prysm validator still use gRPC to interact with beacon, although it has a  'enable-beacon-rest-api', but i still need to configure 'beacon-rpc-provider' at the same time. Does it mean Prysm beacon doesn't have a full support for official beacon-API yet or Prysm validator doesn't fully support work with beacon-API?
Looking forward to your reply!

**Comment by rkapka** [comment]
> Does it mean Prysm beacon doesn't have a full support for official beacon-API yet or Prysm validator doesn't fully support work with beacon-API?

The latter. It is an unfinished, highly experimental project so please do not by any means use this flag on Mainnet.

**Comment by LilkkJerry** [comment]
> > Does it mean Prysm beacon doesn't have a full support for official beacon-API yet or Prysm validator doesn't fully support work with beacon-API?
> 
> The latter. It is an unfinished, highly experimental project so please do not by any means use this flag on Mainnet.

Thanks :)
