### ISSUE TITLE
How to customize the minimum number of mortgage tokens in devnet

### ISSUE THREAD

**Issue by cppfuns** [prysmaticlabs/prysm#12330]
I want to customize the minimum number of ETH participating in the deposit to 1000 in devnet. 
I modified the system deposit contract, updated the genesis alloc, and reset the chain network. 
And the deposit_data.json corresponding to the amount is generated. 
After the transaction is successful, the corresponding validator participates in the block generation. 
But when the current validator is activated, 96800ETH is returned. 
In addition to modifying the system contract, what else needs to be modified?

**Comment by cppfuns** [comment]
@nisdas Do you have any suggestions? Thank you

**Comment by LilkkJerry** [comment]
@cppfuns Could you plz share how you build the pos devnet? I'm trying to find a way to maintain a stable ethereum pos private devnet. Thanks :)

**Comment by LilkkJerry** [comment]
@cppfuns I met a problem when using devnet, everytime when I restart the network(geth, beacon and validator), the network can not produce new block. Do you know how to solve this?

**Comment by cppfuns** [comment]
> @cppfuns I met a problem when using devnet, everytime when I restart the network(geth, beacon and validator), the network can not produce new block. Do you know how to solve this?

Do you currently have only one genesis node producing blocks? Because a new consensus cannot be reached, the slot consensus cannot be continuously reached into the final state. You need to add a new node and stake it as a validator node.

**Comment by rauljordan** [comment]
Hi @cppfuns you can edit the `num-validators` value in docker-compose.yml for create-beacon-chain-genesis and the `interop-num-validators` value under the validator definition in that same file. Currently it is set to 64 validators in the chain. Each validator has 32 ETH
