### ISSUE TITLE
Can I directly use multiAddr to connect to other nodes without using enr?

### ISSUE THREAD

**Issue by cppfuns** [prysmaticlabs/prysm#12331]
I think some nodes are connected directly through multiAddr. I saw similar [test codes](https://github.com/prysmaticlabs/prysm/blob/ebccdfadb5406b4c153d2b182328374a971683f8/beacon-chain/p2p/service_test.go#L200), but I didn’t find the corresponding startup parameters.

**Comment by nisdas** [comment]
You can do this via `--peer` and provide that peer's multiaddress as an argument
