### ISSUE TITLE
REST API beacon state missing historical summaries

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#12346]
# 🐞 Bug Report

### Description

Querying the beacon state against a prysm node fails to return the `historical_summaries` information.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

```
curl -s http://localhost:5052/eth/v2/debug/beacon/states/head | jq .data.historical_summaries
null
```

## 🌍  Your Environment

prysm 4.0.3

**Comment by rauljordan** [comment]
hi @mcdee unable to reproduce with the version after 3 different checkpoint syncs of a prysm node on 4.0.3. I am able to get the historical summaries. Are you seeing other issues from simply issuing the http request to curl -s http://localhost:5052/eth/v2/debug/beacon/states/head ?

**Comment by mcdee** [comment]
Seeing this on `prysm-nethermind-1.srv.4844-devnet-5.ethpandaops.io` at current:

```
devops@prysm-nethermind-1 ➜  ~ curl -s http://localhost:5052/eth/v2/debug/beacon/states/head | jq .data.historical_summaries
null
```

**Comment by mcdee** [comment]
(also seeing it on mainnet nodes, but I figure you can gain access to the 4844 devnet node to check for yourself).

**Comment by rkapka** [comment]
This was fixed here: https://github.com/prysmaticlabs/prysm/pull/12410

Note that the PR is against branch `eip4844`. This code will be a part of `deneb-integration` branch very soon.
