### ISSUE TITLE
Export metric for validator_identity and include index

### ISSUE THREAD

**Issue by 0xste** [prysmaticlabs/prysm#12348]
# 🚀 Feature Request

### Description
We don't currently have a way to retrieve validator index from prometheus, it's useful when joining to other metrics

### Describe the solution you'd like
Introduce a metric like:
`validator_identity_info{pubkey="0xa8e6154ac3be1246a5a229c8b3d9328dfc2d5da3e73bc1891da0ee9596f345b42e79f3878f879d0fa3df9ea72eb28725", index="469113"}`

- Info suffix as per -> https://prometheus.io/docs/practices/naming/
- Other default metrics can be added by the agent i.e. hostname/instance/job

**Comment by 0xSte** [comment]
Code may look something like:

`prysm/validator/client.go Global Var`
```
	// ValidatorIdentityGaugeVec used to track validator identity
	ValidatorIdentityGaugeVec = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "validator",
			Name:      "identity_info",
			Help:      "Identifying information for the validator",
		},
		[]string{
			"pubkey", "index",
		},
	)
```

`prysm/validator/client.go logForEachValidator(...)`
```
ValidatorIdentityGaugeVec.WithLabelValues(pubKey, index).Set(1) 
```

I'm not sure we'd need to care too much de-registering exited validators too much given this is an info metric

**Comment by rauljordan** [comment]
Hi @0xSte we've talked about this before but adding the pubkey would increase the [cardinality](https://grafana.com/blog/2022/10/20/how-to-manage-high-cardinality-metrics-in-prometheus-and-kubernetes/) of our metrics significantly. We have tried this and it affects operators that are running a lot of keys

**Comment by 0xSte** [comment]
Alternatively @rauljordan, we could add validator index to an existing high-cardinality metric behind the "emitAccountMetrics" flag to reduce the need for additional active series, would this approach satisfy the cardinality non-functional requirement?


https://github.com/prysmaticlabs/prysm/blob/535b38395ec8a47447192cefb283394f839f7e61/validator/client/metrics.go#L20-L29


becomes -> 
```
...
		[]string{
			"pubkey", "index"
		},
...
```
---

https://github.com/prysmaticlabs/prysm/blob/535b38395ec8a47447192cefb283394f839f7e61/validator/client/validator.go#L384-L387

becomes -> 

```
		if v.emitAccountMetrics {
			fmtKey := fmt.Sprintf("%#x", status.publicKey)
			ValidatorStatusesGaugeVec.WithLabelValues(fmtKey, status.index).Set(float64(status.status.Status))
		}

```

---

https://github.com/prysmaticlabs/prysm/blob/535b38395ec8a47447192cefb283394f839f7e61/validator/client/validator.go#L914-L916

☝️getting index is a bit more involved in this instance

**Comment by 0xSte** [comment]
My understanding is that there's a 1:1 relationship between pubkey + index and that it's assigned on validator activation? I may be missing some context

https://docs.prylabs.network/docs/how-prysm-works/validator-lifecycle#pending-state
