### ISSUE TITLE
Error could not update forkchoice's justified checkpoint: could not update justified balances: could not get justified balances: could not get ancestor state: signed beacon block can't be nil

### ISSUE THREAD

**Issue by 0xMantrax** [prysmaticlabs/prysm#12367]
# 🐞 Bug Report

### Description
I want to restart the sync of my ethererum node on ubuntu server but I encounter this problem: 

FATAL blockchain: could not update forkchoice's justified checkpoint: could not update justified balances: could not get justified balances: could not get ancestor state: signed beacon block can't be nil

### Has this worked before in a previous version?

I launched the sync of my etherum node on ubuntu server a few days ago, everything was going well. I was at about 60% of the sync blocks but I had to reboot my server. And now I want to restart the sync but I faced this error while it was working fine before the reboot.

## 🔬 Minimal Reproduction

I just use this command to start the sync:
./prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=/home/user/.ethereum/prysm/jwt.hex 

## 🔥 Error

<pre><code>
FATAL blockchain: could not update forkchoice's justified checkpoint: could not update justified balances: could not get justified balances: could not get ancestor state: signed beacon block can't be nil

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.10.Desktop
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v4.0.3.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by james-prysm** [comment]
no more updates since then, issue is stale, closing for now.
