### ISSUE TITLE
prysm stuck in error: Could not compute head from new attestations

### ISSUE THREAD

**Issue by niekaixuan** [prysmaticlabs/prysm#12366]
# 🐞 Bug Report

### Description

 
my prysm process  stuck in error prompts, could not sync any more

### Has this worked before in a previous version?

 Yes

## 🔬 Minimal Reproduction

geth start script:
```shell
geth  --txlookuplimit 0  --ws --ws.addr 0.0.0.0 --ws.port 8536 --ws.api eth,net,web3,debug  --http --http.api eth,net,engine,admin,web3,debug --http.addr 0.0.0.0 --http.port 6745 --http.corsdomain '*' --http.vhosts '*'  --datadir /data/eth/geth --authrpc.addr localhost --authrpc.port 8551 --authrpc.vhosts localhost --authrpc.jwtsecret jwt.hex
```

prysm start script:
```shell
./prysm.sh beacon-chain \
--accept-terms-of-use \
--execution-endpoint=http://localhost:8551 \
--jwt-secret=jwt.hex \
--checkpoint-sync-url https://sync-mainnet.beaconcha.in \
--genesis-beacon-api-url https://sync-mainnet.beaconcha.in \
--datadir /data/eth/prysm/chaindata
```

## 🔥 Error

<pre><code>

time="2023-05-06 14:41:51" level=info msg="Processing block batch of size 54 starting from  0x1ddd3ede... 6209568/6377607 - estimated time remaining 8h29m12s" blocksPerSecond=5.5 peers=11 prefix=initial-sync
time="2023-05-06 14:41:51" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x17e982907f2e6fa0bf97835043c95aa3c5b0e2ca4b6a0d62001675e2554af812 (in processBatchedBlocks, slot=6209568)" prefix=initial-sync
time="2023-05-06 14:41:51" level=info msg="Processing block batch of size 54 starting from  0xdd370f3c... 6209632/6377607 - estimated time remaining 5h41m24s" blocksPerSecond=8.2 peers=11 prefix=initial-sync
time="2023-05-06 14:41:51" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x36e75ca0dd4961167c472b110cb9ec3dbe849f219340b6aed115969a9628e6e3 (in processBatchedBlocks, slot=6209632)" prefix=initial-sync
time="2023-05-06 14:41:51" level=info msg="Processing block batch of size 53 starting from  0x4555def2... 6209696/6377607 - estimated time remaining 4h17m55s" blocksPerSecond=10.8 peers=11 prefix=initial-sync
time="2023-05-06 14:41:51" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xe4248a355a48890a4186d4d65aa174799865484bbafab2a7ecd24ad58b71e31c (in processBatchedBlocks, slot=6209696)" prefix=initial-sync
time="2023-05-06 14:41:51" level=info msg="Processing block batch of size 54 starting from  0x8f173bf0... 6209760/6377607 - estimated time remaining 3h26m27s" blocksPerSecond=13.6 peers=11 prefix=initial-sync
time="2023-05-06 14:41:51" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x6ca15ae736a097bc63fbb6f3aaf2fa3e393593777c0881c8b4e28acaced5520c (in processBatchedBlocks, slot=6209760)" prefix=initial-sync
time="2023-05-06 14:41:51" level=info msg="Processing block batch of size 52 starting from  0xf158d3e5... 6209824/6377607 - estimated time remaining 2h53m9s" blocksPerSecond=16.1 peers=11 prefix=initial-sync
time="2023-05-06 14:41:51" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xdbfd88bab713f792fa62426df8688c959a052e54539313738b66ded35fd62ee0 (in processBatchedBlocks, slot=6209824)" prefix=initial-sync
time="2023-05-06 14:41:57" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:41:59" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:09" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:11" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:18" level=info msg="Peer summary" activePeers=10 inbound=0 outbound=10 prefix=p2p
time="2023-05-06 14:42:21" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:23" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:33" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:35" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain
time="2023-05-06 14:42:45" level=error msg="Could not compute head from new attestations" error="0x179948652d0a55ea65029294190359bfa2c2b13fb8603f697b3d5521144cf4be: unknown justified root" prefix=blockchain

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  OS & Version: CentOS Linux release 7.9.2009 (Core)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Geth version: 1.11.4-stable
CL client & version: prysm@v4.0.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by lyciumlee** [comment]
same bug. "Could not compute head from new attestation"

**Comment by ogglin** [comment]
+ same bug. "Could not compute head from new attestation"

**Comment by YuXiaoCoder** [comment]
same bug. "Could not compute head from new attestation"

**Comment by aerielabio** [comment]
same bug. "Could not compute head from new attestation"

**Comment by nisdas** [comment]
@niekaixuan It appears the issue might be with your execution client, if you think this is still an issue can you paste more logs ? 
`Could not compute head from new attestation` is a cosmetic log which doesn't mean anything, it is getting removed in the next release.

**Comment by niekaixuan** [comment]
> @niekaixuan It appears the issue might be with your execution client, if you think this is still an issue can you paste more logs ? `Could not compute head from new attestation` is a cosmetic log which doesn't mean anything, it is getting removed in the next release.

Old logs are overwritten. It looked like something was wrong with the execution layer, so I resynced the execution layer, and the chain goes well now
