### ISSUE TITLE
v4.0.4 panic: runtime error: invalid memory address or nil pointer dereference (Slasher)

### ISSUE THREAD

**Issue by victorelec14** [prysmaticlabs/prysm#12404]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

After upgrading to version 4.0.4 (from 4.0.3) I have this error when I have the "--slasher" flag enabled, when I disable the flag, it starts normally

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: v4.0.3

## 🔥 Error

<pre><code>

prysm-node_1                    | time="2023-05-15 20:32:09" level=info msg="Starting beacon node" prefix=node version="Prysm/v4.0.4/ad749a40b696a94cc240d4ddef9b1061d3a39bb3. Built at: 2023-05-15 17:16:52+00:00"
prysm-node_1                    | panic: runtime error: invalid memory address or nil pointer dereference
prysm-node_1                    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x303d423]
prysm-node_1                    | 
prysm-node_1                    | goroutine 7435 [running]:
prysm-node_1                    | github.com/prysmaticlabs/prysm/v4/beacon-chain/slasher.(*Service).waitForChainInitialization(0xc05eebda00)
prysm-node_1                    |       beacon-chain/slasher/service.go:176 +0x43
prysm-node_1                    | github.com/prysmaticlabs/prysm/v4/beacon-chain/slasher.(*Service).run(0xc05eebda00)
prysm-node_1                    |       beacon-chain/slasher/service.go:95 +0x36
prysm-node_1                    | created by github.com/prysmaticlabs/prysm/v4/beacon-chain/slasher.(*Service).Start
prysm-node_1                    |       beacon-chain/slasher/service.go:91 +0x56
prysm-node_1                    | time="2023-05-15 20:32:10" level=warning msg="Enabled feature flag" prefix=flags slasher="Enables a slasher in the beacon node for detecting slashable offenses"

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.1
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
prysmaticlabs/prysm-beacon-chain:stable  

Prysm/v4.0.4/ad749a40b696a94cc240d4ddef9b1061d3a39bb3. Built at: 2023-05-15 17:16:52+00:00"
  </code>
</pre>

Thanks 👍

**Comment by jonjander** [comment]
I have the same issue, running Nethermind 1.18.0 and Prysm 4.0.4 on windows.

**Comment by kasey** [comment]
This has been resolved in our main branch by #12405, but we are not planning another full release until next 5/22 (which will be `v4.0.5`). In the meantime, you can run `v4.0.3-hotfix` (released 5/12) to pick up the performance hot fix relating to state replays, while avoid this nil pointer exception. I'm sorry for the inconvenience!

cc @jonjander @victorelec14

**Comment by prestonvanloon** [comment]
Pinned for visibility until v4.0.5 is released early next week.
