### ISSUE TITLE
Running Prysm without connecting to github (China bans Github)

### ISSUE THREAD

**Issue by biteric2000** [prysmaticlabs/prysm#12406]
The connection to Github is very unstable in China, sometimes the site is completely banned.
When  Github connection is lost, even with Prysm client and blockchain data up to date, we still cannot run prysm with the default prysm.bat / prysm.sh script successfully. 
Is there a way to run Prysm beacon and validator client directly using local downloaded file? Just like geth and other clients, possibly with modified bat/sh file or a command specifying the executables.
Any suggestion is appreciated. Thanks!

**Comment by nisdas** [comment]
@biteric2000 You possibly need to fix the tag if you want to run with the script:
```
USE_PRYSM_VERSION=v4.0.4 ./prysm.sh beacon-chain
```
This will not download the latest binary and just use your currently downloaded one.

**Comment by biteric2000** [comment]
Thank you @nisdas !
Added set USE_PRYSM_VERSION=v4.0.4 
and deleted the first "for-curl-echo" request lines in the script. Seems working fine now. No more internet connection checks. (Will manually update versions from now on.) Cheers!
