### ISSUE TITLE
Use of monitor-indices at v4.0.4 cannot sync beacon chain in goerli network

### ISSUE THREAD

**Issue by gitmewai** [prysmaticlabs/prysm#12411]
# 🐞 Bug Report

### Description

When using the command line option `monitor-indices`, prysm-beacon-chain `v4.0.4` cannot sync

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was: `v4.0.3`

## 🔬 Minimal Reproduction

1. Include the following option in config file:
```
monitor-indices: [123456]
```

## 🔥 Error

<pre><code>
May 16 15:41:16 eth-1 systemd[1]: Started Prysm Eth2 Beacon Chain.
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=info msg="Finished reading JWT secret from /etc/eth2/jwtsecret"
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=warning msg="Running on the Prater Testnet" prefix=flags
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=warning msg="Enabled feature flag" build-block-parallel="Builds a beacon block in parallel for consensus and execution. It results in faster block construction time" prefix=flags
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=info msg="Checking DB" database-path="/var/lib/prysm/beacon-chain/beaconchaindata" prefix=node
May 16 15:41:16 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:16" level=info msg="Opening Bolt DB at /var/lib/prysm/beacon-chain/beaconchaindata/beaconchain.db" prefix=db
May 16 15:41:17 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:17" level=info msg="Deposit contract: xxxx" prefix=node
May 16 15:41:17 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:17" level=info msg="Running node with peer id of xxxx " prefix=p2p
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="gRPC server listening on port" address="127.0.0.1:4000" prefix=rpc
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Starting beacon node" prefix=node version="Prysm/v4.0.4/ad749a40b696a94cc240d4ddef9b1061d3a39bb3. Built at: 2023-05-15 16:25:06+00:00"
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Waiting for state to be initialized" prefix=initial-sync
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Starting service" ValidatorIndices=[123456] prefix=monitor
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Starting API middleware" prefix=gateway
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Cleaning up dirty states" count=1 prefix=db
May 16 15:41:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:25" level=info msg="Starting gRPC gateway" address="127.0.0.1:3500" prefix=gateway
May 16 15:41:40 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:40" level=info msg="Connected to new endpoint: http://127.0.0.1:8551" prefix=powchain
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Received state initialized event" prefix=initial-sync
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Starting initial chain sync..." prefix=initial-sync
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Started discovery v5" ENR="enr:-MK4QIo8VYepNrJYyP8vZsmRNXV9eZN3VViqLaVfIYL2veJRJd57xJNtsawLEtGN7nVz4imLPNIhqt_VU5p1e59lELGGAYglOW9kh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBiiUHvAwAQIP__________gmlkgnY0gmlwhAMBVJSJc2VjcDI1NmsxoQONwF4RGoI3tP-cvEq2bMancvcDRVdlEHRH80Clq1gPuYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A" prefix=p2p
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Node started p2p server" multiAddr="/ip4/x.x.x.x/tcp/13000/p2p/xxxx" prefix=p2p
May 16 15:41:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:41" level=info msg="Node started external p2p server" multiAddr="/ip4/x.x.x.x/tcp/13000/p2p/xxxx" prefix=p2p
May 16 15:41:46 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:46" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 15:41:46 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:46" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
May 16 15:41:48 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:48" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 15:41:51 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:51" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=1
May 16 15:41:56 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:56" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=2
May 16 15:41:58 eth-1 beacon-chain[32268]: time="2023-05-16 15:41:58" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 15:42:00 eth-1 beacon-chain[32268]: time="2023-05-16 15:42:00" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 15:42:00 eth-1 beacon-chain[32268]: time="2023-05-16 15:42:00" level=info msg="gRPC client connected to beacon node" addr="127.0.0.1:33058" prefix=rpc
May 16 15:42:01 eth-1 beacon-chain[32268]: time="2023-05-16 15:42:01" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=2
May 16 15:42:08 eth-1 beacon-chain[32268]: time="2023-05-16 15:42:08" level=info msg="Processing block batch of size 24 starting from  0x552181d3... 5645185/5645310 - estimated time remaining 1m44s" blocksPerSecond=1.2 peers=5 prefix=initial-sync
May 16 15:42:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:42:41" level=info msg="Peer summary" activePeers=6 inbound=0 outbound=2 prefix=p2p
May 16 15:43:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:43:41" level=info msg="Peer summary" activePeers=3 inbound=0 outbound=1 prefix=p2p
May 16 15:44:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:44:41" level=info msg="Peer summary" activePeers=8 inbound=0 outbound=1 prefix=p2p
May 16 15:45:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:45:41" level=info msg="Peer summary" activePeers=7 inbound=0 outbound=0 prefix=p2p
May 16 15:45:57 eth-1 beacon-chain[32268]: time="2023-05-16 15:45:57" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:46:11 eth-1 beacon-chain[32268]: time="2023-05-16 15:46:11" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:46:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:46:25" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:46:39 eth-1 beacon-chain[32268]: time="2023-05-16 15:46:39" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:46:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:46:41" level=info msg="Peer summary" activePeers=13 inbound=0 outbound=0 prefix=p2p
May 16 15:46:53 eth-1 beacon-chain[32268]: time="2023-05-16 15:46:53" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:47:07 eth-1 beacon-chain[32268]: time="2023-05-16 15:47:07" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:47:21 eth-1 beacon-chain[32268]: time="2023-05-16 15:47:21" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:47:35 eth-1 beacon-chain[32268]: time="2023-05-16 15:47:35" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:47:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:47:41" level=info msg="Peer summary" activePeers=10 inbound=0 outbound=0 prefix=p2p
May 16 15:47:49 eth-1 beacon-chain[32268]: time="2023-05-16 15:47:49" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:48:03 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:03" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:48:17 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:17" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:48:31 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:31" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:48:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:41" level=info msg="Peer summary" activePeers=15 inbound=1 outbound=0 prefix=p2p
May 16 15:48:45 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:45" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:48:59 eth-1 beacon-chain[32268]: time="2023-05-16 15:48:59" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:49:13 eth-1 beacon-chain[32268]: time="2023-05-16 15:49:13" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:49:27 eth-1 beacon-chain[32268]: time="2023-05-16 15:49:27" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:49:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:49:41" level=info msg="Peer summary" activePeers=10 inbound=1 outbound=0 prefix=p2p
May 16 15:49:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:49:41" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:49:55 eth-1 beacon-chain[32268]: time="2023-05-16 15:49:55" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:50:09 eth-1 beacon-chain[32268]: time="2023-05-16 15:50:09" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:50:23 eth-1 beacon-chain[32268]: time="2023-05-16 15:50:23" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:50:37 eth-1 beacon-chain[32268]: time="2023-05-16 15:50:37" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:50:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:50:41" level=info msg="Peer summary" activePeers=11 inbound=1 outbound=0 prefix=p2p
May 16 15:50:51 eth-1 beacon-chain[32268]: time="2023-05-16 15:50:51" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:51:05 eth-1 beacon-chain[32268]: time="2023-05-16 15:51:05" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:51:19 eth-1 beacon-chain[32268]: time="2023-05-16 15:51:19" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:51:33 eth-1 beacon-chain[32268]: time="2023-05-16 15:51:33" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:51:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:51:41" level=info msg="Peer summary" activePeers=12 inbound=1 outbound=0 prefix=p2p
May 16 15:51:47 eth-1 beacon-chain[32268]: time="2023-05-16 15:51:47" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:52:01 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:01" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:52:15 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:15" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:52:29 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:29" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:52:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:41" level=info msg="Peer summary" activePeers=15 inbound=1 outbound=0 prefix=p2p
May 16 15:52:43 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:43" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:52:57 eth-1 beacon-chain[32268]: time="2023-05-16 15:52:57" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:53:11 eth-1 beacon-chain[32268]: time="2023-05-16 15:53:11" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:53:25 eth-1 beacon-chain[32268]: time="2023-05-16 15:53:25" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:53:39 eth-1 beacon-chain[32268]: time="2023-05-16 15:53:39" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:53:41 eth-1 beacon-chain[32268]: time="2023-05-16 15:53:41" level=info msg="Peer summary" activePeers=16 inbound=1 outbound=0 prefix=p2p
May 16 15:53:53 eth-1 beacon-chain[32268]: time="2023-05-16 15:53:53" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:54:07 eth-1 beacon-chain[32268]: time="2023-05-16 15:54:07" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 15:54:21 eth-1 beacon-chain[32268]: time="2023-05-16 15:54:21" level=warning msg="Execution client is not syncing" prefix=powchain
</code></pre>

If the `monitor-indices` option is removed for prysm-beacon-chain v4.0.4, the node can sync as usual.

<pre><code>
May 16 16:03:43 eth-1 systemd[1]: Started Prysm Eth2 Beacon Chain.
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=info msg="Finished reading JWT secret from /etc/eth2/jwtsecret"
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=warning msg="Running on the Prater Testnet" prefix=flags
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=warning msg="Enabled feature flag" build-block-parallel="Builds a beacon block in parallel for consensus and execution. It results in faster block construction time" prefix=flags
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=info msg="Checking DB" database-path="/var/lib/prysm/beacon-chain/beaconchaindata" prefix=node
May 16 16:03:43 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:43" level=info msg="Opening Bolt DB at /var/lib/prysm/beacon-chain/beaconchaindata/beaconchain.db" prefix=db
May 16 16:03:44 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:44" level=info msg="Deposit contract: xxxx" prefix=node
May 16 16:03:45 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:45" level=info msg="Running node with peer id of xxxx " prefix=p2p
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="gRPC server listening on port" address="127.0.0.1:4000" prefix=rpc
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="Starting beacon node" prefix=node version="Prysm/v4.0.4/ad749a40b696a94cc240d4ddef9b1061d3a39bb3. Built at: 2023-05-15 16:25:06+00:00"
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="Starting API middleware" prefix=gateway
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="Waiting for state to be initialized" prefix=initial-sync
May 16 16:03:52 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:52" level=info msg="Starting gRPC gateway" address="127.0.0.1:3500" prefix=gateway
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Received state initialized event" prefix=initial-sync
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Starting initial chain sync..." prefix=initial-sync
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Started discovery v5" ENR="enr:xxxx" prefix=p2p
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Node started p2p server" multiAddr="/ip4/x.x.x.x/tcp/13000/p2p/xxxx" prefix=p2p
May 16 16:03:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:03:59" level=info msg="Node started external p2p server" multiAddr="/ip4/x.x.x.x/tcp/13000/p2p/xxxx" prefix=p2p
May 16 16:04:00 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:00" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 16:04:04 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:04" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
May 16 16:04:07 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:07" level=info msg="Connected to new endpoint: http://127.0.0.1:8551" prefix=powchain
May 16 16:04:10 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:10" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 16:04:11 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:11" level=info msg="Processing block batch of size 24 starting from  0x552181d3... 5645185/5645420 - estimated time remaining 3m15s" blocksPerSecond=1.2 peers=3 prefix=initial-sync
May 16 16:04:27 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:27" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 16:04:27 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:27" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 16:04:27 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:27" level=error msg="Could not compute head from new attestations" error="xxxx: unknown justified root" prefix=blockchain
May 16 16:04:27 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:27" level=info msg="Processing block batch of size 49 starting from  0xe1837478... 5645216/5645422 - estimated time remaining 56s" blocksPerSecond=3.6 peers=2 prefix=initial-sync
May 16 16:04:38 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:38" level=info msg="Processing block batch of size 50 starting from  0xf1ea2f13... 5645281/5645423 - estimated time remaining 28s" blocksPerSecond=5.0 peers=1 prefix=initial-sync
May 16 16:04:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:04:59" level=info msg="Peer summary" activePeers=7 inbound=1 outbound=0 prefix=p2p
May 16 16:05:06 eth-1 beacon-chain[32353]: time="2023-05-16 16:05:06" level=info msg="Processing block batch of size 49 starting from  0x5072f706... 5645345/5645425 - estimated time remaining 32s" blocksPerSecond=2.5 peers=1 prefix=initial-sync
May 16 16:05:58 eth-1 beacon-chain[32353]: time="2023-05-16 16:05:58" level=warning msg="Skip processing batched blocks" error="could not process block in batch: timeout from http.Client: received an undefined execution engine error" prefix=initial-sync
May 16 16:05:58 eth-1 beacon-chain[32353]: time="2023-05-16 16:05:58" level=info msg="Synced to finalized epoch - now syncing blocks up to current head" currentSlot=5645429 prefix=initial-sync syncedSlot=5645343
May 16 16:05:58 eth-1 beacon-chain[32353]: time="2023-05-16 16:05:58" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=1
May 16 16:05:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:05:59" level=info msg="Peer summary" activePeers=3 inbound=1 outbound=1 prefix=p2p
May 16 16:06:15 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:15" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:06:19 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:19" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:06:33 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:33" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:06:47 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:47" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:06:50 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:50" level=info msg="gRPC client connected to beacon node" addr="127.0.0.1:40052" prefix=rpc
May 16 16:06:59 eth-1 beacon-chain[32353]: time="2023-05-16 16:06:59" level=info msg="Peer summary" activePeers=19 inbound=6 outbound=13 prefix=p2p
May 16 16:07:01 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:01" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:07:15 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:15" level=warning msg="Execution client is not syncing" prefix=powchain
May 16 16:07:21 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:21" level=info msg="Synced new block" block=0x5072f706... epoch=176417 finalizedEpoch=176415 finalizedRoot=0x146866e5... prefix=blockchain slot=5645345
May 16 16:07:21 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:21" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x1e389babed9b prefix=blockchain slot=5645345 syncBitsCount=391 txCount=83
May 16 16:07:21 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:21" level=info msg="Synced new block" block=0xc5c10f2a... epoch=176417 finalizedEpoch=176415 finalizedRoot=0x146866e5... prefix=blockchain slot=5645346
May 16 16:07:21 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:21" level=info msg="Finished applying state transition" attestations=128 payloadHash=0xfef3dc7c118d prefix=blockchain slot=5645346 syncBitsCount=404 txCount=42
May 16 16:07:22 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:22" level=info msg="Synced new block" block=0xc0e9e009... epoch=176417 finalizedEpoch=176415 finalizedRoot=0x146866e5... prefix=blockchain slot=5645347
May 16 16:07:22 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:22" level=info msg="Finished applying state transition" attestations=128 payloadHash=0xb3d74b5a3efd prefix=blockchain slot=5645347 syncBitsCount=423 txCount=39
May 16 16:07:22 eth-1 beacon-chain[32353]: time="2023-05-16 16:07:22" level=info msg="Synced new block" block=0x501d788d... epoch=176417 finalizedEpoch=176415 finalizedRoot=0x146866e5... prefix=blockchain slot=5645348
</code></pre>

## 🌍  Your Environment

**Operating System:**

`Debian 10`

**What version of Prysm are you running? (Which release)**

Geth `Geth/v1.11.6-stable-ea9e62ca/linux-amd64/go1.20.3`
Prysm `Prysm/v4.0.4/ad749a40b696a94cc240d4ddef9b1061d3a39bb3`

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Looks like a valid bug to me. I added this to e2e test locally and it failed 100% of the time (10 of 10 runs).
