### ISSUE TITLE
Use ToBytes32 Across Prysm

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1241]
We now have a convenience [method](https://github.com/prysmaticlabs/prysm/blob/73ff78f4491aacb570bc5c0ff1a344d3e119a387/shared/bytes/bytes.go#L64) for converting a byte slice to a fix sized 32 byte array. Let's use that across Prysm and replace the current in line conversations with the method`ToBytes32`.

Look for the following patterns to replace:
```
var array1 []byte
var array2 [32]byte
copy(array2[:], array1)
```

**Comment by cyberbono3** [comment]
I will take care of it!

**Comment by JeremiGendron** [comment]
```regex
(var\s+(.*)\s+\[\](byte))
(var\s+(.*)\s+\[32\](byte))
(copy\((.*)\[:\],\s+(.*)\))
```
@cyberbono3 if helps

**Comment by cyberbono3** [comment]
@JeremiGendron   thank you
