### ISSUE TITLE
(Gitcoin Bounty) Guide Request: Setting up slasher protection as middleware box

### ISSUE THREAD

**Issue by riordant** [prysmaticlabs/prysm#12437]
After reading the great discussion here:
https://github.com/prysmaticlabs/prysm/issues/7740

I would like a guide to setting up the 2.c in the following comment:
https://github.com/prysmaticlabs/prysm/issues/7740#issuecomment-724454531

Focus should be on Linux based environment.

Offering $200 Gitcoin Bounty for this: https://bounties.gitcoin.co/issue/29863

**Comment by web3files** [comment]
Hi. I am ready to work on this bounty. Is it cancelled ?
