### ISSUE TITLE
Slow performance on grpc `/ethereum.eth.v1alpha1.BeaconNodeValidator/MultipleValidatorStatus`

### ISSUE THREAD

**Issue by ihooni** [prysmaticlabs/prysm#12457]
# 💎 Issue

### Background

When calling grpc `MultipleValidatorStatus`, the for loop below is executed for getting the last activated validator index if there are PENDING/DEPOSITIED/PARTIALLY_DEPOISTED validators.

https://github.com/prysmaticlabs/prysm/blob/666188dfea8c5d6ba0d9650b1f4d24c3122906d1/beacon-chain/rpc/prysm/v1alpha1/validator/status.go#L345-L354

The problem is that this for loop is executed for each pending validators in `MultipleValidatorStatus` request.

Currently, there are more than 70,000 pending validators on the eth network.
<img width="251" alt="Screenshot 2023-05-24 at 2 11 06 PM" src="https://github.com/prysmaticlabs/prysm/assets/37792049/a77f7c2a-8bd5-40d3-8d1e-3f209cf71104">

So, if `MultipleValidatorStatus` is requested for 100 pending validators, the code inside the for loop will be executed 70,000 * 100 = 7,000,000 times.

### Description

Below is a flame graph when `MultipleValidatorStatus` is requested for 100 pending validators. Most of the time is spent in the for loop.
<img width="1565" alt="Screenshot 2023-05-24 at 2 14 25 PM" src="https://github.com/prysmaticlabs/prysm/assets/37792049/159211df-5cd2-4a42-9737-e5f5f5a7dd70">

It seems that a significant performance improvement can be achieved by replacing the simple for loop with binary search or calculating `lastActivatedvalidatorIndex` only once and reusing it.

I think this improvement is necessary because the grpc `MultipleValidatorStatus` is called in `AllValidatorsAreExited`, which is executed before performing the roles in the validator-client.

https://github.com/prysmaticlabs/prysm/blob/666188dfea8c5d6ba0d9650b1f4d24c3122906d1/validator/client/runner.go#L94-L103

**Comment by james-prysm** [comment]
Thanks for the feedback I'll try to get something in soon.
