### ISSUE TITLE
Client Diversity: Prysm VC <> Teku BN + Prysm VC <> Lighthouse BN does not work

### ISSUE THREAD

**Issue by ybstaked** [prysmaticlabs/prysm#12467]
# 🐞 Bug Report

### Description

Prysm Validator is not able to validate connecting with Teku Beacon.  We used flag `--enable-beacon-rest-api --beacon-rest-api-provider http://cl-teku-beacon:5051`

### Has this worked before in a previous version?

I saw this note here: https://github.com/prysmaticlabs/prysm/issues/12320#issuecomment-1521823347.  **I'd like to know when this will be made stable interface in releases, as this is important for client diversity.**

## 🔬 Minimal Reproduction

```validator --accept-terms-of-use --attest-timely --wallet-dir=/home/prysm/ --enable-beacon-rest-api --beacon-rest-api-provider http://cl-teku-beacon.eth2-prater:5051  --log-file=/tmp/ethereum2.log --wallet-password-file file.txt --prater --monitoring-host 0.0.0.0 --proposer-settings-file=/home/prysm/remote/new-fee-recipient.json --enable-builder  --validators-external-signer-public-keys=\"http://$POD_IP:5050/api/v1/eth2/publicKeys\" --validators-external-signer-url=\"http://$POD_IP:5050\"```

## 🔥 Error

Process fails without any errors.

## 🌍  Your Environment

**Operating System:**

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v4.0.5
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by ybstaked** [comment]
From discord: https://discord.com/channels/476244492043812875/781210739762397234/1111479814667370496

<img width="867" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/85460995/33bc0987-b1fe-45e8-aa0e-162f61225541">

**Comment by nisdas** [comment]
cc @rkapka

**Comment by ybstaked** [comment]
Hi team, any update on this?  I also discovered that Prysm VC does not work with Lighthouse BN.

```
time="2023-07-27 17:54:15" level=warning msg="Could not determine if beacon chain started" error="could not receive ChainStart from stream: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json": could not connect" prefix=validator
time="2023-07-27 17:54:25" level=info msg="Syncing with beacon node to align on chain genesis info" prefix=validator
time="2023-07-27 17:54:25" level=warning msg="Could not determine if beacon chain started" error="could not receive ChainStart from stream: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json": could not connect" prefix=validator
```

Context here: https://discord.com/channels/605577013327167508/605577013331361793/1134182157636612106

**Comment by nisdas** [comment]
Tagging @rkapka as he has been working on this for the last few months.

**Comment by prestonvanloon** [comment]
The latest compatibility matrix may be found in the ethpandaops/ethereum-package repo https://github.com/ethpandaops/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility

**Comment by saolyn** [comment]
Closing this in favor of #13852
