### ISSUE TITLE
Extremely poor block production performance after updated to v4.0.5

### ISSUE THREAD

**Issue by nining** [prysmaticlabs/prysm#12472]
# 💎 Issue

### Background

 Heard it might produce more blocks after the upgrade.

### Description

Before the upgrade, we could produce 6 ~ 10 blocks per day.  After the upgrade, the 3 days produced blocks were 3, 2, 1.  I don't know what's wrong here or if it's only the jitter.

**Comment by nisdas** [comment]
@nining The block proposal process is pseudo-random, so there is no guarantee that you will produce `X` number of blocks per day.

**Comment by nining** [comment]
> @nining The block proposal process is pseudo-random, so there is no guarantee that you will produce `X` number of blocks per day.

I understand that.  Statistically, the produced blocks number is always too low after days, and I think it means something.

**Comment by potuz** [comment]
@nining were you assigned blocks to produce that were missing or you simply were assigned less blocks?

**Comment by nining** [comment]
> @nining were you assigned blocks to produce that were missing or you simply were assigned less blocks?

How can I get this information?  I didn't have any specific config.

**Comment by nisdas** [comment]
@nining This is resolved with v4.0.7, if this is still not the case I will reopen this issue.
