### ISSUE TITLE
Update Config To Include Networking Config

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#12478]
# 💎 Issue

### Background

Since https://github.com/ethereum/consensus-specs/pull/3375 has been merged in the consensus-specs repo. We can now bundle both the consensus and networking config data into a single config. 

### Description

This issue is to track the update of our internal config structure to accommodate this particular change. Some things to be mindful of:
-  Does not break users running custom devnets. Previous flags/configurations used by them still work fine here. 
-  This works fine with e2e and our other multiclient testing configurations.

**Comment by anukul** [comment]
Duplicate #12547
