### ISSUE TITLE
External Builder Error on Local devnet

### ISSUE THREAD

**Issue by aaroua5** [prysmaticlabs/prysm#12498]
As I am attempting to run a local devnet (which starts at bellatrix by default), where the genesis block is proposed at slot 0, the proposer is requesting the block header from an external block-builder for slots starting from slot 1, using the old head (the parent of the current head.

Any Idea how can I resolve this ?

This is the output of the builder

`ERROR[06-06|16:26:49.830] error with builder processing on payload attribute latestSlot=2 processedSlot=2 headHash=0xde4dad6f2b9682bdc9f146efe8354a3d5df223267e42f1a4c076956ceea62d13 error="parent block hash not found in block tree given head block hash 0xde4dad6f2b9682bdc9f146efe8354a3d5df223267e42f1a4c076956ceea62d13"`

This keeps happening for each slot as it keeps asking for block with parent that is not the latest block but the one before that.

**Comment by nisdas** [comment]
Are you sure this is prysm ? These logs do not look like they are from prysm.

**Comment by terencechain** [comment]
Closing this. Feel free to reopen if needed
