### ISSUE TITLE
Frequently encounter error : "Could not request attestation to sign at slot"

### ISSUE THREAD

**Issue by eyougo** [prysmaticlabs/prysm#12491]
# 🐞 Bug Report

### Description

Our validator is connected to our beacon chain node, both of these are version v4.0.5 . In recent days, we have sometimes encountered the following errors and missed attestation, but at other times it is as normal as before. When problems occur, the debug logs are as follows error.

### Has this worked before in a previous version?

The errors is from version v4.0.5 in recent days.

## 🔥 Error

<pre><code>
content:time="2023-06-05 17:36:08" level=debug msg="Set deadline for proposals and attestations" deadline=2023-06-05 17:35:35 +0800 CST prefix=validator slot=6594475
content:time="2023-06-05 17:36:08" level=debug msg="gRPC request finished." backend=[] duration=21.523µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
content:time="2023-06-05 17:36:08" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x8d1a13a18157 slot=6594475
content:time="2023-06-05 17:36:08" level=debug msg="gRPC request finished." backend=[] duration=14.92µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
content:time="2023-06-05 17:36:08" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x90180806f911 slot=6594475
content:time="2023-06-05 17:36:08" level=debug msg="gRPC request finished." backend=[] duration=11.391µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
content:time="2023-06-05 17:36:08" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x90c6c5fd2726 slot=6594475
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
centos7
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v4.0.5
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
This should be resolved in v4.0.7. If you still are running into it, I will reopen the issue
