### ISSUE TITLE
create a new file when file specified by --log-file option doesn't exist

### ISSUE THREAD

**Issue by niekaixuan** [prysmaticlabs/prysm#12496]
# 🚀 Feature Request

#### prysm start command
```shell
./prysm.sh beacon-chain --config-file=/data/ethereum/node/cl/config.yaml
```
Inside the config.yaml, I specified --log-file to /data/ethereum/node/cl/log/prysm.log and it is not exist before, as a result , there is no log file in my directory, track the journal of the process, I got these prompts
```shell
Jun 06 11:26:19  prysm.sh[28341]: time="2023-06-06 11:26:19" level=info msg="Logs will be made persistent" logFileName="/data/ethereum/node/cl/log/prysm.log"
Jun 06 11:26:19  prysm.sh[28341]: time="2023-06-06 11:26:19" level=error msg="Failed to configuring logging to disk." error="open /data/ethereum/node/cl/log/prysm.log: no such file or directory" prefix=main
```
### Describe the solution you'd like

 

just create a new file when it doesn't exist

**Comment by bharath-123** [comment]
hey @nisdas i ll pick this up

**Comment by nisdas** [comment]
Assigned to you !

**Comment by bharath-123** [comment]
Hey @nisdas in the latest develop branch, the log-file is being created if it doesn't exist. I have tested this out in the latest `develop` branch code, plus:
```
// ConfigurePersistentLogging adds a log-to-file writer. File content is identical to stdout.
func ConfigurePersistentLogging(logFileName string) error {
	logrus.WithField("logFileName", logFileName).Info("Logs will be made persistent")
	f, err := os.OpenFile(logFileName, os.O_CREATE|os.O_WRONLY|os.O_APPEND, params.BeaconIoConfig().ReadWritePermissions) // #nosec G304
	if err != nil {
		return err
	}

	addLogWriter(f)

	logrus.Info("File logging initialized")
	return nil
}
```
The file modes are set such that the log file is created if not present.

**Comment by bharath-123** [comment]
apologies, this happens when the directory is not present. will fix for that case
