### ISSUE TITLE
Deneb devnet6 blockers

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12493]
Devnet v6 spec: https://notes.ethereum.org/@bbusa/dencun-devnet-6
Specs: https://github.com/ethereum/consensus-specs/releases/tag/v1.4.0-alpha.1

We'll branch off `deneb-devnet6` from `deneb-integration`. Here are the remaining items to support Devnet6 fully:

**Spec**
- [x] https://github.com/ethereum/consensus-specs/pull/3354
- [x] https://github.com/ethereum/execution-apis/pull/404

**Blockchain pkg**
- [ ] New `process_execution_payload`
- [ ] Use `NewPayloadV3`
- [ ] `verify_blob_kzg_proof_batch` before insert block to forkchoice

**Sync pkg**
- [x] Blobs by range
- [x] Blobs by root
- [ ] When to import block

**Initial sync pkg**
- [ ] Tighten everything together 

**Crypto library**
- [x] Import go-kzg

**Prysm RPC**
- [x] Broadcast blobs

**Comment by james-prysm** [comment]
closing as we have moved on to later devnets
