### ISSUE TITLE
Get currently Beacon IP from gRPC Load Balancing context

### ISSUE THREAD

**Issue by ArturDolzan** [prysmaticlabs/prysm#12508]
My validator is using the gRPC Load Balancing, which means I setup `--beacon-rpc-provider` as `--beacon-rpc-provider="beaconA:port,beaconB:port"`. My question is basically, how can I get which beacon the validator is pointed currently? Is there any api or cli I could call?

**Comment by prestonvanloon** [comment]
There isn't a way to do this at this time. 

Related: https://github.com/prysmaticlabs/prysm/issues/13264 https://github.com/prysmaticlabs/prysm/issues/10147
