### ISSUE TITLE
Question regarding sync

### ISSUE THREAD

**Issue by kaber2** [prysmaticlabs/prysm#12520]
Hello. I'm trying to sync prysm to a state where I can issue validator queries (getProposerDuties) for each epoch. The block range I'm interested in is all blocks starting at the merge, basically I want to be able to query the validator for every block since the merge.

So my idea was to do one full sync, export the block corresponding to the merge and then do a second sync using --checkpoint-block from that block.

I'm now running prysm sync with "--slots-per-archive-point=32" for the first sync. The sync is insanely slow and the database grows a lot. After two days I am currently at endSlot=2309023, with the database having a size of 963G already.

Is there a better way to achieve what I need? Thanks!

**Comment by prestonvanloon** [comment]
Sorry that this question wasn't answered earlier. You could collect the data with a short slots per archive point, but it would require a lot of space as you have found out. I imagine that the data would still be retrievable within a reasonable amount of time with the default flags. 

Another way would be to hack the client to write the duties to a file on every epoch transition. If you still need assistance on this, try reaching out on discord and we can help.

**Comment by kaber2** [comment]
Thank you for your response!
