### ISSUE TITLE
Option to have current + upcoming duties as metrics

### ISSUE THREAD

**Issue by ybstaked** [prysmaticlabs/prysm#12521]
* Proposal duties if in the next epoch
* Sync committee duties - relates to #11522

**Comment by bharath-123** [comment]
Hey @ybstaked I believe that prysm has a metric to get the upcoming proposal slots of a validator by the `validator_next_proposal_slot` metric. This should be in the latest v4.0.7

The sync committee duties metrics are not yet there

**Comment by james-prysm** [comment]
I believe this issue has been addressed by terence.
