### ISSUE TITLE
Validator client fails to update proposer settings because of bn latency with high amount of keys

### ISSUE THREAD

**Issue by 0xalex88** [prysmaticlabs/prysm#12527]
# 💎 Issue

### Background

Starting the validator client fails when there are enough keys and enough latency to the beacon node to reach the 12 seconds timeout while updating proposer settings

### Description

We have a vc with failover beacon nodes, one of them is in another datacenter and there are 1k (mostly pending) keys configured. When the validator client tries to start with the failover node that has 10ms latency (vs 0.5ms of the primary) it fails after 12 seconds with:

```json
{"time":"2023-06-13T22:50:58Z","level":"info","msg":"Validator client started with provided proposer settings that sets options such as fee recipient and will periodically update the beacon node and custom builder (if --enable-builder)","prefix":"validator"}
// more validatorIndex requests
{"time":"2023-06-13T22:51:10Z","backend":null,"duration":10916936,"level":"debug","method":"/ethereum.eth.v1alpha1.BeaconNodeValidator/ValidatorIndex","msg":"gRPC request finished."}
{"time":"2023-06-13T22:51:10Z","error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"fatal","msg":"Failed to update proposer settings","prefix":"validator"}
```

while with the primary one it starts fine after 3-4 seconds:

```json
{"time":"2023-06-13T22:51:35Z","level":"debug","msg":"Prepare proposer request did not success with all pubkeys","prefix":"validator","pubkeysCount":1000,"reqCount":31}
```

It seems that the [loop](https://github.com/prysmaticlabs/prysm/blob/develop/validator/client/validator.go#L1018-L1034) that gets the validator indexes calls the beacon node sequentially. so if there's a 10ms delay and 1k keys that's already 10 seconds (without counting for the actual time taken to process the request).

What could be a possible solution? Doing the index requests in parallel? Making the 12 seconds deadline adjustable? Or is 10ms/1k keys too much?

**Comment by james-prysm** [comment]
> flag to skip the first call (downside would be that the validator won't be registered to the builder if it's the first start or fee recipient won't be updated until next epoch, probably not a big deal since it's opt-in)
not set a deadline on start (can result in slower startup like you said but with many keys also pruning the slashing database takes longer so I suppose that who has a high number of keys is already used to that)
configurable deadline (like --api-timeout for api requests, could also be a hidden flag)

> remove it + skip if db matches is probably the best, provides slow starts when required and fast restarts (opt-in)

adding discord discussion items

**Comment by 0xalex88** [comment]
I've removed the deadline on startup https://github.com/0xalex88/prysm/commit/8a2d8eee2fed692d4f2379b04b684adf7c14a7ea 

I might be wrong but I think the test `TestUpdateProposerSettingsAt_EpochEndExceeded` was testing something different than the EpochEnd deadline, I think it was passing because of the 12 seconds deadline of the startup push, but it wasn't reaching the periodical push because the slot passed to the channel wasn't the start of the epoch (which is later checked in `if slots.IsEpochStart(slot) && v.ProposerSettings() != nil {`
I'll look into adding the "skip if db matches" flag tomorrow

**Comment by nisdas** [comment]
@0xalex88 I think we can extend the deadline to a larger number (2 minutes, etc) for the first call to update proposer settings. It doesn't need to be 1 slot. This should fix your issue

**Comment by 0xalex88** [comment]
@nisdas I've opened pr #12533 for this
