### ISSUE TITLE
Begin Integrating SSZ in Prysm's P2P Layer

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1253]
This is a follow up to #631 as now we have a common serialization format for Ethereum Serenity. We can therefore begin using SSZ to serialize and send objects via p2p for cross-client compatibility. Possible PRs that work on this front could modify the sync service to use SSZ instead of proto objects.

From now on, any future p2p code should default to SSZ for sending messages. This is also an issue thread to discuss ways in which we could play nicely with proto and what the roles of proto and SSZ can be to coexist well.

**Comment by terenc3t** [comment]
Sounds good. thanks @houjieth

**Comment by rauljordan** [comment]
This has already been done throughout our repo by using SSZ by default for everything so far as of latest master on spec v0.8.1
