### ISSUE TITLE
Can't load network config correctly

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12547]
## Issue Description
Prysm currently splits the chain configuration and network configuration. When a user loads a configuration file, it only applies to the chain configuration and not the network configuration. This means that if a field specified in the configuration file is part of the network configuration, it will never get applied.

## Proposed Solutions
There are two possible solutions to address this issue:

1. Combine the chain configuration and network configuration into a single configuration file. This way, when a user loads a configuration, it will apply to both the chain and network configurations.

2. Modify the code to ensure that config changes from the file also apply to the network configuration. This would involve updating the relevant code in the `network_config.go` file [here](https://github.com/prysmaticlabs/prysm/blob/develop/config/params/network_config.go) to incorporate the changes from the configuration file.

**Comment by anukul** [comment]
hi! i would like to attempt this

**Comment by 0xCMars** [comment]
Hi! If this issue still open?

**Comment by prestonvanloon** [comment]
Fixed by #13364
