### ISSUE TITLE
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.

### ISSUE THREAD

**Issue by plansten** [prysmaticlabs/prysm#12567]
**System information**
**prysm version:**
v4.0.6
**OS & Version:**
CentOS Linux release 7.9.2009 (Core)
**uname -r:**
5.4.185-200.el7.x86_64
**processor model name:**
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

**Actual behaviour**
`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.`

**Additional information**
prysm worked on server which processor have flag 3dnowprefetch, but my processor don`t have this flag.

**Comment by prestonvanloon** [comment]
@plansten you will need to use the slower "portable" version of blst. How are you running prysm?

**Comment by plansten** [comment]
@prestonvanloon I use this docker image: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.6

**Comment by prestonvanloon** [comment]
@plansten use gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.6-portable

**Comment by dot3x3q** [comment]
I had the same SIGILL as OP. Is there a tag that people can use like "beacon-chain:latest-portable" which will allow us to follow the latest portable version? 

Forgive me if I am misunderstanding this. My fear is that users like us who use an older server architecture might be left behind.

**Comment by nisdas** [comment]
@dot3x3q Our releases will always have a portable tag to them, would that be enough for you ? Or do you want to run straight from our latest develop commit

**Comment by prestonvanloon** [comment]
@dot3x3q I second what @nisdas. We will always provide the portable images until we are able to release Prysm with a version of blst that is aware of the CPU features at runtime. See: https://github.com/supranational/blst/issues/10

**Comment by longfin** [comment]
I guess `gcr.io/prysmaticlabs/prysm/validator:v4.0.7-portable` image has SIGILL issue. 😢 

```bash
$ docker run gcr.io/prysmaticlabs/prysm/validator:v4.0.6-portable --version
validator version Prysm/v4.0.5/Local build. Built at: 2023-06-15 17:58:09+00:00

$ docker run gcr.io/prysmaticlabs/prysm/validator:v4.0.7-portable --version
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
```

**Comment by MQLYES** [comment]
> @plansten use `gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.6-portable`

it's  useful . thanks
