### ISSUE TITLE
Delay between Beacon API block's event and availability to request this block

### ISSUE THREAD

**Issue by maslianko-bloXroute** [prysmaticlabs/prysm#12563]
# 🐞 Bug Report

### Description
I'm currently working with Beacon API stuff and use prysm nodes for accessing corresponding endpoints. I'm encountering an error. 

The flow of handling the blocks from Beacon API looks like this:
- We subscribe to block event
- We receive an event
- We request the block of hash that we received inside the event

I'm subscribing to block events by using the endpoint: `http://%s/eth/v1/events?topics=block`.
And when I receive the block event I'm trying to fetch it using the `http://%s/eth/v2/beacon/blocks/%s` route.
But in the case of the Prysm client, the response of this route is undefined, sometimes it's okay, and sometimes it returns
`code:404 message:Could not find requested block: signed beacon block can't be nil`.
And if I made this request in a few seconds, the block will be accessible.

## Expected result
The flow should be deterministic. And if the node sends the event about the block, it should be accessible by another endpoint without any delays.

## 🔬 Minimal Reproduction
1. Subscribe to `http://%s/eth/v1/events?topics=block`
2. Request block from `http://%s/eth/v2/beacon/blocks/%s`
3. The result is not always the block

Note: I use the `Accept: application/octet-stream` header to request the block.

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**
{
  "data": {
    "version": "prysm/v4.0.0-boost0.2.0 (linux amd64)"
  }
}

**Comment by james-prysm** [comment]
Brought it up with the team for more review. currently this is probably happening because of
```
	// Broadcast the block on a feed to notify other services in the beacon node
	// of a received block (even if it does not process correctly through a state transition).
```
so the block is broadcasted before it's reviewed, which has a few steps of its own.
you can see the code in `validateBeaconBlockPubSub` function
