### ISSUE TITLE
Prysm stops syncing and reports error：msg=Could not compute head from new attestations

### ISSUE THREAD

**Issue by zlxadata** [prysmaticlabs/prysm#12583]
Prysm version： 4.0.5
Erigon version：erigon version 2.43.0-stable

OS & Version：Linux - Ubuntu 22.10

Commit hash:

Erigon Command (with flags/config)：
--datadir=/node2/data-erigon
--torrent.download.rate=20mb
--http --http.addr 0.0.0.0
--authrpc.jwtsecret /node2/data-erigon/jwt.hex

Concensus Layer：Prysm v4.0.5

Concensus Layer Command (with flags/config):
--datadir=/node2/data-prysm
--jwt-secret=/node2/data-erigon/jwt.hex
--rpc-host=0.0.0.0
--grpc-gateway-host=0.0.0.0
--monitoring-host=0.0.0.0 -
-execution-endpoint=http://127.0.0.1:8551/
--accept-terms-of-use=true

Now prysm stop syncing and keeps showing Error

Prysm logs：

6月 30 11:31:21 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:21" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:23 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:23" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:26 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:26" level=info msg="Peer summary" activePeers=13 inbound=0 outbound=13 prefix=p2p
6月 30 11:31:33 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:33" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:35 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:35" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:42 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:42" level=info msg="Processing block batch of size 63 starting from  0x0a4e4c4d... 5668320/6772656 - estimated time remaining 97h23m2s" blocksPerSecond=3.1 peers=15 prefix=initial-sync
6月 30 11:31:48 zlaxdata erigon[642734]: [WARN] [06-30|11:31:48.188] [NewPayload] Previously known bad block  hash=0xa5504b6bdd6fc6ed892f3117aec28c7f57b53b82eed9dd00bbf70f63476670a5
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=error msg="Could not compute head from new attestations" error="0x0a4e4c4da96876474f87246b4bdb1b9e451b5fb301367578edaa74dd18c97168: unknown justified root" prefix=blockchain
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 63 starting from  0xcdc19ee9... 5668384/6772657 - estimated time remaining 48h41m21s" blocksPerSecond=6.3 peers=14 prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xb2551d4cd3b4de77b002ccc36a482c79159b5aefd5c24a7ff397435ba4f571ee (in processBatchedBlocks, slot=5668384)" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 64 starting from  0xac441ed1... 5668448/6772657 - estimated time remaining 32h17m12s" blocksPerSecond=9.5 peers=14 prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xb3f3b1e679ed4f0441c0c3eb4e09c215ab72cbb9fcd4d88a7f624dbe31ff7ad9 (in processBatchedBlocks, slot=5668448)" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 63 starting from  0x9e454aee... 5668512/6772657 - estimated time remaining 24h14m44s" blocksPerSecond=12.7 peers=14 prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x785dde27cb26d36eac79119d9c4d4cbd8127f569aa74842d3e3a27204be22d45 (in processBatchedBlocks, slot=5668512)" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 64 starting from  0x19503709... 5668576/6772657 - estimated time remaining 19h20m58s" blocksPerSecond=15.8 peers=14 prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xcdcdfa11e038c75280b4c4acf420f909b8b14a9387d51fc691032f3213553a92 (in processBatchedBlocks, slot=5668576)" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 63 starting from  0xf6d55b70... 5668640/6772657 - estimated time remaining 16h8m26s" blocksPerSecond=19.0 peers=14 prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xfaffe650e8309d9bcc5c6cfe7e412e2c25f270eade2c3e55feb65c1af24b81c1 (in processBatchedBlocks, slot=5668640)" prefix=initial-sync
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=info msg="Processing block batch of size 64 starting from  0x33a5931f... 5668704/6772657 - estimated time remaining 13h48m47s" blocksPerSecond=22.2 peers=14 prefix=initial-sync

Does anyone have the same problem and how to solve it now？

**Comment by mikhail-khalizev** [comment]
The same situation, but in v4.0.6.
I copied my prysm db to [Dropbox](https://www.dropbox.com/sh/3j1lm2bqbr1kggy/AABHsMyHR9Ngk6vmXSbhwmqka?dl=0).
Log: [prysm.log](https://github.com/prysmaticlabs/prysm/files/11912789/prysm.log).

**Comment by Neq900** [comment]
I'm getting the same errors

**Comment by nisdas** [comment]
This is an issue with erigon:
```
6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync

```
Prysm is stuck because erigon isn't giving us the appropriate responses for engine calls.

**Comment by pramonoutomo** [comment]
> This is an issue with erigon:
> 
> ```
> 6月 30 11:31:48 zlaxdata beacon-chain[642875]: time="2023-06-30 11:31:48" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync
> ```
> 
> Prysm is stuck because erigon isn't giving us the appropriate responses for engine calls.

so do you got any fix for this?
