### ISSUE TITLE
Missing on sync committee - Failed to find peers

### ISSUE THREAD

**Issue by fabrice-quadrata** [prysmaticlabs/prysm#12596]
# 🐞 Bug Report

### Description
I'm experiencing sporadic sync committee misses with my Prysm node. (29% proposed, 71% missed on my recent committee).
It appears to be due to not being able to find sync committee peers. 

I have already excluding the following:
- no problems with normal attestations
- my peer count is steady at 100 (for normal p2p attestations)
- CPU & my RAM shown good metrics
- internet latency was low
- I tried adding `--minimum-peers-per-subnet=10` and `--p2p-max-peers=100` (up from 60) 

I first experienced it with `4.0.5`, tried restarting with `4.0.6`, which improved shortly after restarting for a few epochs and then missed once again due to no sync peers found.

### Has this worked before in a previous version?

Yes, I had once been in a sync committee (it was likely prior to 4.0.3), did not have the issue.

 Yes, the previous version in which this bug was not present was: I think before 4.0.3

## 🔬 Minimal Reproduction
Not able to reproduce

## 🔥 Error

```
Jun 30 02:59:00 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:00" level=info msg="Finished applying state transition" attestations=128 payloadHash=0xad0d2da84205 prefix=blockchain slot=6774593 syn>
Jun 30 02:59:03 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:03" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/bba4da96/sync_committee_3/s>
Jun 30 02:59:03 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:03" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message is too late
Jun 30 02:59:03 pznuc prysm-beaconchain-4.0.6[885614]: sync message time 2023-06-30 02:58:47 -0700 PDT (slot 6774592) not within allowable range of 2023-06-30 02:58:59 -0700 PDT (slot 6774593) to 2023-06-30 02:59>
Jun 30 02:59:09 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:09" level=info msg="Peer summary" activePeers=109 inbound=92 outbound=17 prefix=p2p
Jun 30 02:59:13 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:13" level=info msg="Synced new block" block=0x5c4bc5ec... epoch=211706 finalizedEpoch=211704 finalizedRoot=0xa2c9eec2... prefix=blockc>
Jun 30 02:59:13 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:13" level=info msg="Finished applying state transition" attestations=128 payloadHash=0xc3116cea419c prefix=blockchain slot=6774594 syn>
Jun 30 02:59:16 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:16" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/bba4da96/sync_committee_3/s>
Jun 30 02:59:16 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:16" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message is too late
Jun 30 02:59:16 pznuc prysm-beaconchain-4.0.6[885614]: sync message time 2023-06-30 02:58:59 -0700 PDT (slot 6774593) not within allowable range of 2023-06-30 02:59:11 -0700 PDT (slot 6774594) to 2023-06-30 02:59>
Jun 30 02:59:25 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:25" level=info msg="Synced new block" block=0x70653e8e... epoch=211706 finalizedEpoch=211704 finalizedRoot=0xa2c9eec2... prefix=blockc>
Jun 30 02:59:25 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:25" level=info msg="Finished applying state transition" attestations=66 payloadHash=0xff790655a4c4 prefix=blockchain slot=6774595 sync>
Jun 30 02:59:27 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:27" level=error msg="Failed to find peers" error="unable to find requisite number of peers for topic /eth2/bba4da96/sync_committee_3/s>
Jun 30 02:59:27 pznuc prysm-beaconchain-4.0.6[885614]: time="2023-06-30 02:59:27" level=warning msg="Sync Committee Message is too old to broadcast, discarding it" error="sync message is too late
Jun 30 02:59:27 pznuc prysm-beaconchain-4.0.6[885614]: sync message time 2023-06-30 02:59:11 -0700 PDT (slot 6774594) not within allowable range of 2023-06-30 02:59:23 -0700 PDT (slot 6774595) to 2023-06-30 02:59>
lines 121-174
```

![image](https://github.com/prysmaticlabs/prysm/assets/106488900/31a381fa-b523-45a2-a0dc-a0c99dd081ba)
<img width="723" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/106488900/22f75e16-0929-45d6-bfea-bf6b422dff75">

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Arch Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
4.0.6 (but tried with 4.0.5)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by alexfisher** [comment]
I also ran into this issue today with a validator assigned to sync committee (on version 4.0.8). :-(  Sync messages were good for a number of hours, and then they started missing a bit, and then more, until all were being missed.  Restarting prysm seems to have fixed it and sync messages are being received now.  Validator effectiveness showing 100% entire time on beaconcha.in as attestations were all fine.

**Comment by nisdas** [comment]
@alexfisher Do you have metrics from that period ?

**Comment by alexfisher** [comment]
I had a normal 100-110 peers during that time.

**Comment by fabrice-quadrata** [comment]
Still running into this issue actually... only 40% of sync attestations are successful, the rest "missed"

Tried disabling the firewall as well. Peering for attestations is constant at 70. Sync committee peering is between 4-10.

No error/warning logs.

**Comment by prestonvanloon** [comment]
Closing old issues. If this is still an issue, please reply here or file another issue with updated information. With the information here, it is hard to say if you simply had bad peers or if there is an issue with Prysm. We haven't seen this type of issue recently so it may be fixed.
