### ISSUE TITLE
QuickStart guide points to corrupted genesis state file for sepolia testnet

### ISSUE THREAD

**Issue by sirgarfieldc** [prysmaticlabs/prysm#12609]
Same as title.

Followed the quickstart guide on goerli and everything was fine. Switched over to sepolia then see this error 

```
could not load genesis from file: version=0x22736570 not found in any known fork choice schedule: unable to find requested BeaconChainConfig
```

QuickStart documentation points to this genesis file https://github.com/eth-clients/merge-testnets/blob/main/sepolia/genesis.ssz

Edit:  Not sure if prysm is the problem here
See https://github.com/eth-clients/merge-testnets/issues/32

**Comment by nisdas** [comment]
@sirgarfieldc I am assuming this is because you downloaded the webpage rather than the genesis file. With the genesis file, this shouldnt be an issue. If this is still an issue, I will reopen this.
