### ISSUE TITLE
Could not get ancestor state: unknown block

### ISSUE THREAD

**Issue by slider90** [prysmaticlabs/prysm#12645]
# 🐞 Bug Report

### Description

After updating the version of beacon chain client from version `gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.5` to `gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.7` the contaner started restarting continiously with the following issue:

>time="2023-07-21 12:50:55" level=debug msg="Starting Slashing DB" prefix=node
time="2023-07-21 12:50:55" level=debug msg="Starting State Gen" prefix=node
could not get ancestor state: unknown block

### Has this worked before in a previous version?

Previous version worked ok before yesterday. 
Yesterday we started getting notifications that the client is not syncing.  And we decided to update the version to v4.0.7
>time="2023-07-20 19:09:49" level=warning msg="Execution client is not syncing" prefix=powchain

## 🔬 Minimal Reproduction

Install beacon chain client:
gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.5

Install geth client:
ethereum/client-go:v1.12.0 

Update beacon chain client to v4.0.7
gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.7

## 🔥 Error

<pre><code>
time="2023-07-21 12:50:55" level=debug msg="Starting Slashing DB" prefix=node
time="2023-07-21 12:50:55" level=debug msg="Starting State Gen" prefix=node
could not get ancestor state: unknown block

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Amazon Linux - amzn2-ami-kernel-5.10-hvm-2.0.20221210.1-x86_64-gp2
Docker client version - 20.10.23
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.7
  </code>
</pre>

**Comment by agnxsh** [comment]
hi can i be assigned this issue?

**Comment by prestonvanloon** [comment]
Closing old issues, we don't have enough information to investigate this issue. If this is still a problem, please reply here with more information to reproduce the issue or file a new issue.
