### ISSUE TITLE
Implement EIP-7044

### ISSUE THREAD

**Issue by bharath-123** [prysmaticlabs/prysm#12648]
# 🚀 Feature Request

### Description

We should implement EIP-7044 for perpetually valid signed voluntary exits:
https://eips.ethereum.org/EIPS/eip-7044

**Comment by bharath-123** [comment]
Would love to pick this up @nisdas

**Comment by terencechain** [comment]
implemented here: https://github.com/prysmaticlabs/prysm/pull/12577

**Comment by bharath-123** [comment]
cool! thats great! closing this issue then
