### ISSUE TITLE
Beacon node gets stuck on restart (devnet)

### ISSUE THREAD

**Issue by bilaljawed** [prysmaticlabs/prysm#12684]
Hi guys, I am following the devnet guide in prysm docs and its working great, however when i rerun the beacon node it stops running, when i run it the first time with new data it works...

## Log

`ethpos-validate-node-1  | time="2023-08-01 08:55:08" level=error msg="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
ethpos-validate-node-1  | time="2023-08-01 08:55:08" level=error msg="Failed to update assignments" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
ethpos-validate-node-1  | time="2023-08-01 08:55:08" level=warning msg="Validator client started without proposer settings such as fee recipient and will continue to use settings provided in the beacon node." prefix=validator
ethpos-ethereum-node-1  | INFO [08-01|08:55:08.256] Unlocked account                         address=0x123463a4B065722E99115D6c222f267d9cABb524
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=10 prefix=validator pubKeys=[0x8f467e5723de 0x954eb88ed120 0xb245d63d3f9d 0xa98ed496c2f4 0xae00fc3de831 0x9243ef5ed3bd 0x9648b83a4f09 0x92a93728c252 0x92f43d79d9f4 0xac9f4df3f20a] slot=36 slotInEpoch=0 totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0x80a2be2c7dbc slot=36
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=11 prefix=validator pubKeys=[0x9314c6de0386 0x903e2989e744 0x872c61b4a7f8 0xab8d3a9bcc16 0xaf344fce60db 0xb9d1d914df3d 0x81054bd51ce5 0xb7ee0ef26144 0xa852816b8e46 0xb397692ccbf4 0x8a0d24195510] slot=37 slotInEpoch=1 totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0xab8d3a9bcc16 slot=37
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=11 prefix=validator pubKeys=[0xa99a76ed7796 0x81283b7a20e1 0xa6d310dbbfab 0x9893413c0028 0x8d5d3672a233 0xaef9162ee6f2 0xa5869ba554d1 0x8a298ee1ac04 0xae4d49364e4a 0x94f0c8535601 0x8826e820179f] slot=38 slotInEpoch=2 totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0x963528adb532 slot=38
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=10 prefix=validator pubKeys=[0xb89bebc69976 0x9977f1c8b731 0xa8d4c7c27795 0x876dd4705157 0x8dde83069208 0xae241af60691 0xaecc56f2b1c4 0xb8cd1cef89aa 0x87c9f7605d07 0xa48cc260df1d] slot=39 slotInEpoch=3 totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0xa99a76ed7796 slot=39
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=11 prefix=validator pubKeys=[0xa3a32b0f8b4d 0x88c141df77cd 0xab0bdda0f85f 0xaec922bd7a9b 0x84398f539a64 0xa1c76af1545d 0x963528adb532 0xa4855c83d868 0xb08f7feb8678 0xb5bb0162a4f2 0x92977e713966] slot=40 slotInEpoch=4 totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0xae241af60691 slot=40
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Attestation schedule" attesterDutiesAtSlot=11 prefix=validator pubKeys=[0x8dd74e1bb522 0x96746aaba64d 0xa9cf360aa15f 0xb7e6e187ed81 0x925b1fb57c06 0xa34febc12af0 0xafc0fa2ed6a2 0x9698d9519a02 0x91ae4686b0d2 0x80a2be2c7dbc 0x86a73886aa01] slot=41 slotInEpoch=5 timeTillDuty=12s totalAttestersInEpoch=64
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=info msg="Proposal schedule" prefix=validator pubKey=0x88c141df77cd slot=41 timeTillDuty=12s
ethpos-chain-beacon-1   | time="2023-08-01 08:55:16" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=224.576102ms slot=40
ethpos-chain-beacon-1   | time="2023-08-01 08:55:16" level=warning msg="voting period before genesis + follow distance, using eth1data from head" genesisTime=1690879636 latestValidTime=1690850964 prefix="rpc/validator"
ethpos-ethereum-node-1  | INFO [08-01|08:55:16.271] Ignoring beacon update to old head       number=0 hash=d39965..875f4d age=8m    have=7
ethpos-chain-beacon-1   | time="2023-08-01 08:55:16" level=error msg="Could not pack deposits and attestations" error="rpc error: code = Internal desc = Could not get ETH1 deposits: could not fetch eth1data height: could not query block with given hash: Post "http://ethereum-node:8551": context canceled" prefix="rpc/validator"
ethpos-validate-node-1  | time="2023-08-01 08:55:16" level=error msg="Failed to request block from beacon node" blockSlot=40 error="rpc error: code = Unknown desc = could not build block in parallel: rpc error: code = Internal desc = Could not get local payload: nil payload with block hash: 0xd39965f2210e26e4f5e48639d8e62686867537e2f639c0f8bc7b60096e875f4d" prefix=validator pubKey=0xae241af60691
ethpos-validate-node-1  | time="2023-08-01 08:55:20" level=info msg="Submitted new sync message" blockRoot=0xe4fb73ac040f prefix=validator slot=40 slotStartTime=2023-08-01 08:55:16 +0000 UTC timeSinceSlotStart=4.005962861s validatorIndex=35
ethpos-validate-node-1  | time="2023-08-01 08:55:20" level=info msg="Submitted new sync message" blockRoot=0xe4fb73ac040f prefix=validator slot=40 slotStartTime=2023-08-01 08:55:16 +0000 UTC timeSinceSlotStart=4.006499531s validatorIndex=55
ethpos-validate-node-1  | time="2023-08-01 08:55:20" level=info msg="Submitted new sync message" blockRoot=0xe4fb73ac040f prefix=validator slot=40 slotStartTime=2023-08-01 08:55:16 +0000 UTC timeSinceSlotStart=4.007050604s validatorIndex=49
ethpos-validate-node-1  | time="2023-08-01 08:55:24" level=info msg="Submitted new attestations" AggregatorIndices=[2] AttesterIndices=[53 14 3 59 31 11 57 2 20 5 27] BeaconBlockRoot=0xe4fb73ac040f CommitteeIndex=0 Slot=40 SourceEpoch=0 SourceRoot=0x000000000000 TargetEpoch=6 TargetRoot=0xe4fb73ac040f prefix=validator
ethpos-chain-beacon-1   | time="2023-08-01 08:55:28" level=warning msg="numPerSlot is 0, skipping initializing topic scoring" prefix=p2p
ethpos-chain-beacon-1   | time="2023-08-01 08:55:28" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/5af31293/beacon_attestation_48/ssz_snappy"
ethpos-chain-beacon-1   | time="2023-08-01 08:55:28" level=info msg="Subscribed to topic" prefix=sync topic="/eth2/5af31293/sync_committee_0/ssz_snappy"
ethpos-chain-beacon-1   | time="2023-08-01 08:55:28" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=196.880193ms slot=41
ethpos-chain-beacon-1   | time="2023-08-01 08:55:28" level=warning msg="voting period before genesis + follow distance, using eth1data from head" genesisTime=1690879636 latestValidTime=1690850964 prefix="rpc/validator"

ethpos-chain-beacon-1   | time="2023-08-01 08:57:13" level=error msg="Beacon node is not respecting the follow distance" prefix=powchain`

For the re run i am not creating any new genesis file or anything using old data already present in the directories using the docker:

## Docker code for re run

`version: "3.9"
services:
  ethereum-node:
    image: "ethereum/client-go:latest"
    command:
      - --http
      - --http.api=eth,engine,net,web3,txpool,debug
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/execution_data/jwtsecret
      - --datadir=/execution_data
      - --allow-insecure-unlock
      - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
      - --password=/execution_data/geth_password.txt
      - --nodiscover
      - --syncmode=full
      - --gcmode=archive
    ports:
      - 8551:8551
      - 8545:8545
    volumes:
      - ./execution_data:/execution_data
      - ./execution_data/geth_password.txt:/execution_data/geth_password.txt
      - ./jwtsecret:/execution_data/jwtsecret
      
  chain-beacon:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command:
      - --datadir=/consensus_data/beacondata
      - --min-sync-peers=0
      - --genesis-state=/consensus_data/genesis.ssz
      - --bootstrap-node=
      - --chain-config-file=/consensus_data/config.yml
      - --chain-id=32382
      - --rpc-host=0.0.0.0
      - --contract-deployment-block=0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://ethereum-node:8551
      - --accept-terms-of-use
      - --jwt-secret=/execution_data/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --rpc-port=4001
    depends_on:
      ethereum-node:
        condition: service_started
    volumes:
      - ./consensus_data:/consensus_data
      - ./jwtsecret:/execution_data/jwtsecret

  validate-node:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command:
      - --beacon-rpc-provider=chain-beacon:4001
      - --datadir=/consensus_data/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --interop-start-index=0
      - --chain-config-file=/consensus_data/config.yml
    depends_on:
      chain-beacon:
        condition: service_started
    volumes:
      - ./consensus_data:/consensus_data
`

Any insights would be appreciated

Thank you

**Comment by nisdas** [comment]
@bilaljawed Can you post this issue here ?
https://github.com/OffchainLabs/eth-pos-devnet

This is where we track our devnet bugs/issues.

**Comment by bilaljawed** [comment]
> 

The issue is there already since 3 months, nobody has responded

https://github.com/OffchainLabs/eth-pos-devnet/issues/19

**Comment by nisdas** [comment]
Ok lets continue this conversation there then, closing this issue.
