### ISSUE TITLE
Prysm goerli sync stuck...

### ISSUE THREAD

**Issue by amiDMast** [prysmaticlabs/prysm#12683]
**Guys I need your help please**
My prysm sync stuck...

OS: `Ubuntu 20.04`
CPU: `AMD Ryzen 5 3600 6-Core Processor`
RAM: `64 Gb`
Prysm version: `v4.0.7` 
https://github.com/prysmaticlabs/prysm/releases/download/v4.0.7/beacon-chain-v4.0.7-linux-amd64

Run cmd: 
<pre><code>
/opt/prysm/prysm-latest --goerli --accept-terms-of-use --datadir='/var/lib/eth/prysm-goerli' \
                                          --genesis-state=/opt/prysm/goerli-genesis.ssz \
                                          --execution-endpoint='http://localhost:8551' \
                                          --jwt-secret='/var/lib/eth/.ethereum/goerli/geth/jwtsecret' \
                                          --p2p-allowlist=public
</code></pre>

Prysm logs:
<pre><code>
Aug  1 08:06:28 test-node prysm[1252449]: time="2023-08-01 08:06:28" level=info msg="Processing block batch of size 53 starting from  0x838f5d88... 3639487/6197432 - estimated time remaining 49h20m35s" blocksPerSecond=14.4 peers=55 prefix=initial-sync
Aug  1 08:06:32 test-node prysm[1252449]: time="2023-08-01 08:06:32" level=warning msg="Skip processing batched blocks" error="could not process block in batch: method not found: received an undefined execution engine error" prefix=initial-sync
Aug  1 08:06:32 test-node prysm[1252449]: time="2023-08-01 08:06:32" level=info msg="Processing block batch of size 44 starting from  0x0907056d... 3639551/6197432 - estimated time remaining 42h48m9s" blocksPerSecond=16.6 peers=55 prefix=initial-sync
Aug  1 08:06:32 test-node prysm[1252449]: time="2023-08-01 08:06:32" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xde42a768d50b918c813a7c4336a0863abaee4efafc19307a152aece8b5c47b02 (in processBatchedBlocks, slot=3639551)" prefix=initial-sync
Aug  1 08:06:34 test-node prysm[1252449]: time="2023-08-01 08:06:34" level=error msg="Could not compute head from new attestations" error="0x838f5d884ba9acb97b5e7092259a8f4fc7f73c0b1133448513b4f749e75f24a1: unknown justified root" prefix=blockchain
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=info msg="Processing block batch of size 42 starting from  0xa6b9e351... 3639616/6197432 - estimated time remaining 44h16m5s" blocksPerSecond=16.1 peers=55 prefix=initial-sync
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x871cc23406ea513c9691e25b37c46746141bc6ebeb9077cb83f509d504961fbd (in processBatchedBlocks, slot=3639616)" prefix=initial-sync
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=info msg="Processing block batch of size 45 starting from  0x18670808... 3639680/6197432 - estimated time remaining 38h49m27s" blocksPerSecond=18.3 peers=55 prefix=initial-sync
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xccbad80f90868af630b39b224c2d5017c7b3c832d8cdd539b54842bbe1edd676 (in processBatchedBlocks, slot=3639680)" prefix=initial-sync
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=info msg="Processing block batch of size 51 starting from  0x8b3e505d... 3639743/6197432 - estimated time remaining 34h4m30s" blocksPerSecond=20.9 peers=55 prefix=initial-sync
Aug  1 08:06:35 test-node prysm[1252449]: time="2023-08-01 08:06:35" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xe1569b04030074fc0e3c851c054cc8976770554c2e8169fa812c0f7b1f941cc6 (in processBatchedBlocks, slot=3639743)" prefix=initial-sync
Aug  1 08:06:36 test-node prysm[1252449]: time="2023-08-01 08:06:36" level=error msg="Could not compute head from new attestations" error="0x838f5d884ba9acb97b5e7092259a8f4fc7f73c0b1133448513b4f749e75f24a1: unknown justified root" prefix=blockchain
Aug  1 08:06:41 test-node prysm[1252449]: time="2023-08-01 08:06:41" level=info msg="Processing block batch of size 53 starting from  0x838f5d88... 3639487/6197433 - estimated time remaining 49h20m35s" blocksPerSecond=14.4 peers=55 prefix=initial-sync
Aug  1 08:06:45 test-node prysm[1252449]: time="2023-08-01 08:06:45" level=warning msg="Skip processing batched blocks" error="could not process block in batch: method not found: received an undefined execution engine error" prefix=initial-sync
Aug  1 08:06:45 test-node prysm[1252449]: time="2023-08-01 08:06:45" level=info msg="Processing block batch of size 44 starting from  0x0907056d... 3639551/6197433 - estimated time remaining 42h48m9s" blocksPerSecond=16.6 peers=55 prefix=initial-sync
Aug  1 08:06:45 test-node prysm[1252449]: time="2023-08-01 08:06:45" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xde42a768d50b918c813a7c4336a0863abaee4efafc19307a152aece8b5c47b02 (in processBatchedBlocks, slot=3639551)" prefix=initial-sync
Aug  1 08:06:46 test-node prysm[1252449]: time="2023-08-01 08:06:46" level=error msg="Could not compute head from new attestations" error="0x838f5d884ba9acb97b5e7092259a8f4fc7f73c0b1133448513b4f749e75f24a1: unknown justified root" prefix=blockchain
Aug  1 08:06:47 test-node prysm[1252449]: time="2023-08-01 08:06:47" level=info msg="Processing block batch of size 42 starting from  0xa6b9e351... 3639616/6197433 - estimated time remaining 44h16m5s" blocksPerSecond=16.1 peers=55 prefix=initial-sync
Aug  1 08:06:47 test-node prysm[1252449]: time="2023-08-01 08:06:47" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x871cc23406ea513c9691e25b37c46746141bc6ebeb9077cb83f509d504961fbd (in processBatchedBlocks, slot=3639616)" prefix=initial-sync
Aug  1 08:06:48 test-node prysm[1252449]: time="2023-08-01 08:06:48" level=error msg="Could not compute head from new attestations" error="0x838f5d884ba9acb97b5e7092259a8f4fc7f73c0b1133448513b4f749e75f24a1: unknown justified root" prefix=blockchain
Aug  1 08:06:53 test-node prysm[1252449]: time="2023-08-01 08:06:53" level=info msg="Processing block batch of size 53 starting from  0x838f5d88... 3639487/6197434 - estimated time remaining 43h3m47s" blocksPerSecond=16.5 peers=55 prefix=initial-sync
</code></pre>

Any ideas?

**Comment by nisdas** [comment]
@amiDMast Seems like your geth node isnt running
```
Aug  1 08:06:32 test-node prysm[1252449]: time="2023-08-01 08:06:32" level=warning msg="Skip processing batched blocks" error="could not process block in batch: method not found: received an undefined execution engine error" prefix=initial-sync
```

**Comment by nisdas** [comment]
@amiDMast What are your geth logs ? and flags

**Comment by amiDMast** [comment]
@nisdas Seems that you are right, problem with light syncmode geth. 
But it's my task, to test light mode synchronization..

Run cmd geth:
<pre><code>
/usr/bin/geth --goerli --syncmode='light' --cache='2000' --maxpeers='200' --allow-insecure-unlock --port='30303' \
                        --http --http.api='admin,eth,debug,net,txpool,personal,web3' --http.addr='0.0.0.0' --http.vhosts='*' --http.port='8545' \
                        --ws --ws.api='admin,eth,debug,miner,net,txpool,personal,web3' --ws.addr='0.0.0.0' --ws.port='8546' \
                        --metrics --metrics.influxdb --metrics.influxdb.tags='test-node' \
                        --authrpc.addr='0.0.0.0' --authrpc.port='8551' --authrpc.vhosts='localhost' --authrpc.jwtsecret='/var/lib/eth/.ethereum/goerli/geth/jwtsecret'
</code></pre>

Geth logs: 
<pre><code>
Aug  1 08:48:01 test-node ethereum[1259333]: WARN [08-01|08:53:41.496] Light client mode is an experimental feature
...
Aug  1 08:48:13 test-node ethereum[1259250]: WARN [08-01|08:48:13.461] Served eth_call                          conn=127.0.0.1:51006 reqid=3 duration=12.002883502s err="getDeleteStateObject (0000000000000000000000000000000000000000) error: no suitable peers available"
Aug  1 08:48:21 test-node ethereum[1259250]: WARN [08-01|08:48:21.645] Served engine_newPayloadV1               conn=127.0.0.1:51006 reqid=7 duration="7.214µs"     err="the method engine_newPayloadV1 does not exist/is not available"
Aug  1 08:48:35 test-node ethereum[1259250]: WARN [08-01|08:48:35.026] Served engine_newPayloadV1               conn=127.0.0.1:51138 reqid=5 duration="5.681µs"     err="the method engine_newPayloadV1 does not exist/is not available"
Aug  1 08:48:40 test-node ethereum[1259250]: WARN [08-01|08:48:40.467] Served eth_call                          conn=127.0.0.1:51006 reqid=3 duration=12.002308161s err="getDeleteStateObject (0000000000000000000000000000000000000000) error: no suitable peers available"
Aug  1 08:48:47 test-node ethereum[1259250]: WARN [08-01|08:48:47.458] Served engine_newPayloadV1               conn=127.0.0.1:51006 reqid=7 duration="4.859µs"     err="the method engine_newPayloadV1 does not exist/is not available"
Aug  1 08:49:00 test-node ethereum[1259250]: WARN [08-01|08:49:00.457] Served engine_newPayloadV1               conn=127.0.0.1:51138 reqid=4 duration="9.227µs"     err="the method engine_newPayloadV1 does not exist/is not available"
Aug  1 08:49:07 test-node ethereum[1259250]: WARN [08-01|08:49:07.479] Served eth_call                          conn=127.0.0.1:51006 reqid=3 duration=12.001851785s err="getDeleteStateObject (0000000000000000000000000000000000000000) error: no suitable peers available"
Aug  1 08:49:08 test-node ethereum[1259250]: WARN [08-01|08:49:08.857] Served engine_newPayloadV1               conn=127.0.0.1:51006 reqid=6 duration="5.912µs"     err="the method engine_newPayloadV1 does not exist/is not available"
Aug  1 08:49:25 test-node ethereum[1259250]: WARN [08-01|08:49:25.730] Served engine_newPayloadV1               conn=127.0.0.1:51138 reqid=4 duration="6.482µs"     err="the method engine_newPayloadV1 does not exist/is not available"
</code></pre>

**Comment by amiDMast** [comment]
@nisdas Thank you for help!

**Comment by nisdas** [comment]
Closing this issue, as we can't fix it on Prysm's end
