### ISSUE TITLE
VNext Planning (released v4.0.8)

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#12692]
## Background

This PR is a tracking issue for the next version release of Prysm

### Required

~~- [ ] #11942~~ Moved to the next release
- [x] #12476 
- [x] #12586 
- [x] #12631 
- [x] #12687 
- [x] #12590 
- [x] #12639 
- [x] #12691 
- [x] #12693

### Nice-to-Have
- [x] Multi-value slice container types

**Comment by terencechain** [comment]
Let's wait for `https://github.com/prysmaticlabs/prysm/pull/12697` and cut a commit

**Comment by prestonvanloon** [comment]
Please include a deprecation notice for grpc-gateway https://github.com/prysmaticlabs/prysm/issues/12682. 

> Deprecation notice: grpc-gateway endpoints will be deprecated in an upcoming release. This deprecation will remove the JSON endpoints for gRPC services, including the event source stream. If you are using grpc-gateway endpoints for JSON, consider updating your tooling to use the standard beacon API endpoints supported in Prysm. gRPC endpoints are not affected by this deprecation. See https://github.com/prysmaticlabs/prysm/issues/12682 for more information.

**Comment by terencechain** [comment]
Done: https://github.com/prysmaticlabs/prysm/releases/tag/v4.0.8
