### ISSUE TITLE
Disable logging to STDOUT when logging into a file has been enabled

### ISSUE THREAD

**Issue by c0deright** [prysmaticlabs/prysm#12705]
# 🚀 Feature Request

### Description

prysm does logging to STDOUT and can log to a file via `--log-file`. When a logfile is configured prysm should not log to STDOUT.
Right now we have `--log-file` enabled to persist the logging in the filesystem but because prysm is logging to STDOUT too, all logs are logged via systemd/syslog, too.

This redundancy is not necessary.

### Describe the solution you'd like

Disable logging to STDOUT when logging into a file has been enabled via `--log-file`.

### Describe alternatives you've considered

Alternative via systemd service file:

Before

```
[Service]
ExecStart=prysm --log-file=/data/prysm.log .....
```

After:

```
[Service]
ExecStart=prysm .....
StandardOutput=append:/data/prysm.log
```

**Comment by c0deright** [comment]
The systemd alternative does work ... so maybe that is the easiest way to have only one log.

**Comment by james-prysm** [comment]
Lets go with the alternative and reopen if need be.
