### ISSUE TITLE
Support for eth_getBlockReceipts

### ISSUE THREAD

**Issue by MRabenda** [prysmaticlabs/prysm#12743]
Hey,

`eth_getBlockReceipts` is super useful for chain processing. We are using it for several chains but seems that Prysm/Arbitrum is not supporting it (Am I correct?) Is there an option that would be supported in the future?

**Comment by nisdas** [comment]
Hey @MRabenda , 

I think this is the wrong repo for that request :) For anything related to arbitrum the nitro repo would be the correct place for it:
https://github.com/OffchainLabs/nitro

Prysm being a consensus layer client doesn't handle transaction receipts

**Comment by MRabenda** [comment]
thanks @nisdas!
