### ISSUE TITLE
FATAL: Beacon-Chain Failing to start (Unable to get justified balances/could not get ancestor state)

### ISSUE THREAD

**Issue by Maxx3r** [prysmaticlabs/prysm#12745]
I started having this issue recently and I am not sure the cause. My server was offline for about a month during a move of location. And now it will not start at all and gets a fatal error (See log output below) 

[2023-08-15 09:44:39]  INFO blockchain: Blockchain data already exists in DB, initializing...
[2023-08-15 09:44:39]  INFO gateway: Starting API middleware
[2023-08-15 09:44:39]  INFO gateway: Starting gRPC gateway address=127.0.0.1:3500
[2023-08-15 09:44:39] FATAL blockchain: could not update forkchoice's justified checkpoint: could not update justified balances: could not get justified balances: could not get ancestor state: unknown block

My GETH node is synced fully and I am just unsure of how to proceed. I have found little to no documentation including this error that I am seeing. Any and all help would be greatly appreciated. 

Version: beacon-chain-v4.0.7-linux-amd64: OK
OS: Ubuntu Server

I am happy to provide any information required! 

Thanks in advance!

**Comment by Maxx3r** [comment]
Similar to https://github.com/prysmaticlabs/prysm/issues/12722 by the looks of it

**Comment by Maxx3r** [comment]
Closing


fix: --force-remove-db to the options when runningprsym and then it started syncing and works again

**Comment by pascaldekloe** [comment]
Doing a hard reset and starting all over again ain't a "fix". 😅 Good to know that this happens to others as well though. Thanks for reporting.

**Comment by cshintov** [comment]
Happened with me today. 5 of our nodes met with this fate.

**Comment by prestonvanloon** [comment]
Could anyone share a beaconchain.db with this fail to start condition? That would help us troubleshoot and issue a proper fix.

**Comment by pascaldekloe** [comment]
Too late. I don't keep 200+ GB laying around for over a month. 😅

**Comment by prestonvanloon** [comment]
@pascaldekloe I understand entirely! I'll try to start from an old checkpoint/backup to see if I can reproduce.
