### ISSUE TITLE
keymanager API voluntary_exit creates incorrect structure

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#12744]
# 🐞 Bug Report

### Description

When calling keymanager API `/eth/v1/validator/<pubkey>/voluntary_exit`, Prysm creates a JSON structure that places everything under `data`. It should not.

Generated data:

```
{"data":{"message":{"epoch":"196868","validator_index":"505597"},"signature":"0xhexsig"}}
```

Should be:

```
{"message":{"epoch":"196868","validator_index":"505597"},"signature":"0xhexsig"}
```

**What version of Prysm are you running? (Which release)**

`v4.0.7`

**Comment by saolyn** [comment]
Thanks @yorickdowne for pointing this out. We cross-checked that the generated data does have the correct format according to the [Keymanager API specification](https://ethereum.github.io/keymanager-APIs/?urls.primaryName=dev#/Voluntary%20Exit/signVoluntaryExit) , but we understand how it can be annoying to have that `data` field when using it. We would prefer sticking to the specification in general

**Comment by yorickdowne** [comment]
Ok that’s interesting. This is not the format that the CL REST interface accepts.

Guide me a little here if you would. Is this a spec snafu, or deliberate? Keymanager generates one format, rest on the CL expects another.

**Comment by yorickdowne** [comment]
Right. Seems that’s a thing across the board — GET returns something with data but POST expects it without. Fair enough, thanks for humoring me and explaining this spec wrinkle. I shall adjust my code accordingly.
