### ISSUE TITLE
Dynamically add peers addresses

### ISSUE THREAD

**Issue by icemagno** [prysmaticlabs/prysm#12760]
We already have ```--peer value [ --peer value ] ``` command line option.

But it will be great if we have something like geth ```admin.addPeer()``` or even better:

```{ "jsonrpc": "2.0", "method": "admin_addPeer", "id": 1, "params": [ ... ] }```

I'm using this to estabilish a peer sync between 2 private servers.

**Comment by nisdas** [comment]
@icemagno We already have this:
https://github.com/prysmaticlabs/prysm/issues/12473 , this was added in this PR:
https://github.com/prysmaticlabs/prysm/pull/12531

You can add a peer dynamically via this path:
```
/prysm/node/trusted_peers
```

Closing this issue now, if you have issues with this particular method will reopen the issue.

**Comment by icemagno** [comment]
Oh.. thanks.
Is there some place I can access all documentation for the API ?
