### ISSUE TITLE
Stuck syncing

### ISSUE THREAD

**Issue by Ololosha100501** [prysmaticlabs/prysm#12762]
Hello guys. I'm not sure if this problem in prysm or with geth, hope you will say. 
So. Running Geth 1.12.0 and Prysm 4.0.7
And this bundle worked perfect before the last week. Tonight was the third time it stucked. 

Logs are in attachments. 
[geth log.txt](https://github.com/prysmaticlabs/prysm/files/12393118/geth.log.txt)
[prysm log.txt](https://github.com/prysmaticlabs/prysm/files/12393119/prysm.log.txt)

All started in prysm at 03:52:36 - **WARN p2p: Attestation is too old to broadcast, discarding it. Current Slot: 7145661 , Attestation Slot: 7145628**

But node still worked. Worked for almost an hour, though there was a lot of old attestation warnings. 

Then at 04:45:52 geth started to say **Ignoring already known beacon payload    number=17,959,321 hash=a1fae9..88f259 age=17s**
And this is all it sayed for next 3.5 hours. 

At this time prysm sayed either **WARN initial-sync: Block is not processed error=could not notify the engine of the new payload: timeout from http.Client: received an undefined execution engine error** or **WARN initial-sync: Range is not processed error=Range had no valid blocks to process**

Within this time there was a lot of peers connected. 

My setup: 
AMD Ryzen 5 5600G
32 GB RAM
Windows 10 x64

**Comment by nisdas** [comment]
It looks like an issue with geth:
```
[2023-08-21 04:45:43] ERROR sync: Could not handle p2p pubsub error=could not notify the engine of the new payload: timeout from http.Client: received an undefined execution engine error topic=/eth2/bba4da96/beacon_block/ssz_snappy
```
Prysm can't do anything because geth keeps on timing out

**Comment by MariusVanDerWijden** [comment]
Theres nothing in our logs indicating that geth is timing out, our logs only shows prysm calling `newPayload` with the same block over and over again.
```
WARN [08-21|07:58:15.517] Ignoring already known beacon payload    number=17,959,321 hash=a1fae9..88f259 age=3h12m40s
WARN [08-21|07:58:28.320] Ignoring already known beacon payload    number=17,959,321 hash=a1fae9..88f259 age=3h12m53s
WARN [08-21|07:58:43.721] Ignoring already known beacon payload    number=17,959,321 hash=a1fae9..88f259 age=3h13m8s
WARN [08-21|07:58:59.137] Ignoring already known beacon payload    number=17,959,321 hash=a1fae9..88f259 age=3h13m24s
```

The logs indicate that the node is kinda slow though, its executing ~10-30 MGas/s, usually nodes execute ~100MGas/s. CPU and RAM look okay, so it might be a disk issue

**Comment by holiman** [comment]
> received an undefined execution engine error 

That does sound like we are returning an error which prysm doesn't recognize, and it labels it "timeout" for some reason.

**Comment by Ololosha100501** [comment]
And again

[Geth logs.txt](https://github.com/prysmaticlabs/prysm/files/12447806/Geth.logs.txt)
[Prysm logs.txt](https://github.com/prysmaticlabs/prysm/files/12447807/Prysm.logs.txt)

**Comment by Ololosha100501** [comment]
> The logs indicate that the node is kinda slow though, its executing ~10-30 MGas/s, usually nodes execute ~100MGas/s. CPU and RAM look okay, so it might be a disk issue

Using Kingston SKC2500M82000G, it seems fast enough for everything

**Comment by prestonvanloon** [comment]
Closing old issues. Please reply or file a new issue if you are still experiencing this
