### ISSUE TITLE
An easy to find place to API documentation

### ISSUE THREAD

**Issue by icemagno** [prysmaticlabs/prysm#12761]
Forgive me but I'm trying hard to find the documentations for the REST API ...

I open a request for a feature that already implemented #12760 because I couldn't found it.

And even that response was not clear enough to me ( something like "the endpoint is like this bro.." but knowing the address is not enough. I need all paramenter, formats addresses etc...

Like this https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-admin. A very good example.

Or even this ( that I don't know what exactly is : that say "Beacon-API" but from Ethereum? ) https://ethereum.github.io/beacon-APIs/#/ 

So... ok... the address is ```/prysm/node/trusted_peers``` and now ? What I must pass? Is it POST? GET? Is the query parameter JSON? XML:? 

This page is even more confusing:

https://docs.prylabs.network/docs/how-prysm-works/prysm-public-api

The ```/p2p``` endpoint? where is it documented?
Is there more endpoints from ```/prysm/``` ? 
Why ```/p2p```is not under ```/prysm/``` like ```/node``` is ?

**Comment by nisdas** [comment]
cc @rkapka

**Comment by nisdas** [comment]
This endpoint was recently implemented which is why there aren't the appropriate docs on it, thanks for bringing this up, we will see that this is added into our docs

**Comment by icemagno** [comment]
A swagger like docs will be good

**Comment by icemagno** [comment]
Still needing to know how to use ```/prysm/node/trusted_peers``` endpoint bro ... what must I pass as parameter? wich format?
Send the complete call example please.

Please help.

**Comment by icemagno** [comment]
Trying to send a RAWtext body in a POST request with just

```
/ip4/127.0.0.1/tcp/13000/p2p/16Uiu2HAmA4QLSyNYTjNpcjzSESAJmvN1WneZC6UHs3RsFE43xGsL
```
to 

```http://192.21.81.44:8080/prysm/node/trusted_peers```

but receiving "Page not found"

**Comment by nisdas** [comment]
For adding a peer @icemagno 
```
 curl 'http:/localhost:3500/prysm/node/trusted_peers' -X POST -H "Content-Type: application/json" -d '{"addr":"/ip4/192.168.9.10/tcp/13000/p2p/16Uiu2HAmA4QLSyNYTjNpcjzSESAJmvN1WneZC6UHs3RsFE43xGsL"}'
```

This should work

**Comment by icemagno** [comment]
WOW man !! You just saved my day

**Comment by icemagno** [comment]
Just one more question:

Is the trusted peers mutual?
I mean...

When I add a node "A" to a node "B" ... is the node "B" added to node "A" too?

**Comment by nisdas** [comment]
It is not, you will need to specify it for the other node too. It is only set as trusted on the node you initialized in (node B)

**Comment by rkapka** [comment]
I will close this issue because problems got resolved. A Swagger page for custom endpoints will be implemented in the future.
