### ISSUE TITLE
Could not get validator roles

### ISSUE THREAD

**Issue by bilaljawed** [prysmaticlabs/prysm#12791]
Hi guys,

I am running a private network using GETH and Prysm. I added a new validator which showed up after the usual waiting time but when i run the validator it shows errors even if it detects the validator is activated, am i overlooking something? 

## Logs

eth-pos-validator-1  | time="2023-08-24 08:33:54" level=info msg="Validating for public key" prefix=validator publicKey=0xac2026628af2
eth-pos-validator-1  | time="2023-08-24 08:33:54" level=info msg="Validator activated" index=5 prefix=validator publicKey=0xac2026628af2
eth-pos-validator-1  | time="2023-08-24 08:33:55" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0xac2026628af2] slot=32931 slotInEpoch=3 totalAttestersInEpoch=1
eth-pos-validator-1  | time="2023-08-24 08:33:55" level=info msg="Proposal schedule" prefix=validator pubKey=0xac2026628af2 slot=32931
eth-pos-validator-1  | time="2023-08-24 08:33:55" level=info msg="Proposal schedule" prefix=validator pubKey=0xac2026628af2 slot=32933 timeTillDuty=3s
eth-pos-validator-1  | time="2023-08-24 08:33:55" level=info msg="Validator client started with provided proposer settings that sets options such as fee recipient and will periodically update the beacon node and custom builder (if --enable-builder)" prefix=validator
eth-pos-validator-1  | time="2023-08-24 08:33:57" level=info msg="Submitted new sync message" blockRoot=0x8e00e2495b69 prefix=validator slot=32932 slotStartTime=2023-08-24 08:33:56 +0000 UTC timeSinceSlotStart=1.163258271s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:33:59" level=info msg="Submitted new sync message" blockRoot=0x8e00e2495b69 prefix=validator slot=32933 slotStartTime=2023-08-24 08:33:58 +0000 UTC timeSinceSlotStart=1.387003311s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:00" level=error msg="Failed to propose block" blockSlot=32933 error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xac2026628af2
eth-pos-validator-1  | time="2023-08-24 08:34:00" level=error msg="Could not report validator's rewards/penalties" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
eth-pos-validator-1  | time="2023-08-24 08:34:00" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0xac2026628af2] slot=32939 slotInEpoch=5 timeTillDuty=10s totalAttestersInEpoch=1
eth-pos-validator-1  | time="2023-08-24 08:34:00" level=info msg="Proposal schedule" prefix=validator pubKey=0xac2026628af2 slot=32939 timeTillDuty=10s
eth-pos-validator-1  | time="2023-08-24 08:34:01" level=info msg="Submitted new sync message" blockRoot=0x304a085debbb prefix=validator slot=32934 slotStartTime=2023-08-24 08:34:00 +0000 UTC timeSinceSlotStart=1.362839539s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:02" level=error msg="Could not submit signed contribution and proof" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
eth-pos-validator-1  | time="2023-08-24 08:34:02" level=info msg="Submitted new sync message" blockRoot=0xd04a343aec8a prefix=validator slot=32935 slotStartTime=2023-08-24 08:34:02 +0000 UTC timeSinceSlotStart=948.004643ms validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:05" level=info msg="Submitted new sync message" blockRoot=0x30f5237545be prefix=validator slot=32936 slotStartTime=2023-08-24 08:34:04 +0000 UTC timeSinceSlotStart=1.111858637s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:07" level=info msg="Submitted new sync message" blockRoot=0xbe2b4ce5cf72 prefix=validator slot=32937 slotStartTime=2023-08-24 08:34:06 +0000 UTC timeSinceSlotStart=1.10638489s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:08" level=info msg="Submitted new sync message" blockRoot=0x2383c74f1822 prefix=validator slot=32938 slotStartTime=2023-08-24 08:34:08 +0000 UTC timeSinceSlotStart=727.201127ms validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:11" level=warning msg="No attestations to aggregate" error="rpc error: code = NotFound desc = Could not find attestation for slot and committee in pool" prefix=validator slot=32939
eth-pos-validator-1  | time="2023-08-24 08:34:11" level=info msg="Submitted new sync message" blockRoot=0x2383c74f1822 prefix=validator slot=32939 slotStartTime=2023-08-24 08:34:10 +0000 UTC timeSinceSlotStart=1.616147331s validatorIndex=5
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=error msg="Failed to sign block" error="could not get domain data: rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xac2026628af2
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xac2026628af2 slot=32939
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=error msg="Could not report validator's rewards/penalties" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0xac2026628af2] slot=32941 slotInEpoch=1 timeTillDuty=2s totalAttestersInEpoch=1
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=info msg="Proposal schedule" prefix=validator pubKey=0xac2026628af2 slot=32941 timeTillDuty=2s
eth-pos-validator-1  | time="2023-08-24 08:34:12" level=info msg="Proposal schedule" prefix=validator pubKey=0xac2026628af2 slot=32944 timeTillDuty=8s
eth-pos-validator-1  | time="2023-08-24 08:34:39" level=error msg="Could not request sync message block root to sign" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
eth-pos-validator-1  | time="2023-08-24 08:34:39" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: rpc error: code = Internal desc = Could not get sync subcommittee index: could not process slots: expected state.slot 32950 < slot 32941" prefix=validator slot=32941
eth-pos-validator-1  | time="2023-08-24 08:34:39" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: rpc error: code = Internal desc = Could not get sync subcommittee index: could not process slots: expected state.slot 32950 < slot 32942" prefix=validator slot=32942
eth-pos-validator-1  | time="2023-08-24 08:34:40" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: rpc error: code = Internal desc = Could not get sync subcommittee index: could not process slots: expected state.slot 32950 < slot 32943" prefix=validator slot=32943
eth-pos-validator-1  | time="2023-08-24 08:34:40" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: rpc error: code = Internal desc = Could not get sync subcommittee index: could not process slots: expected state.slot 32950 < slot 32944" prefix=validator slot=32944
eth-pos-validator-1  | time="2023-08-24 08:34:40" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: rpc error: code = Internal desc = Could not get sync subcommittee index: could not process slots: expected state.slot 32950 < slot 32945" prefix=validator slot=32945

**Comment by DenkevichOleg** [comment]
Are you found solutions? @bilaljawed

**Comment by prestonvanloon** [comment]
Closing old issues. Please reply here to open it again or file a new issue. Thanks
