### ISSUE TITLE
Prysm exit 1 on private network.

### ISSUE THREAD

**Issue by neodiz** [prysmaticlabs/prysm#12819]
### Description

I created a private network by example. 
 - 1 node(prysm +geth + validator ) work with --min-sync-peers=0 
 - 2 nodes(prysm + geth + validator) work with --min-sync-peers=1 
 - 1 node(prysm + geth ) work with --min-sync-peers=1  
 - 1 bootstrap node. 
For a while everything worked correctly. 3 prysm that had the --min-sync-peers=1 option crashed.

### Has this worked before in a previous version?

Not tested 

## 🔬 Minimal Reproduction
Node 1
<pre>
  <code>
      - --min-sync-peers=0
      - --minimum-peers-per-subnet=0
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --contract-deployment-block=0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://geth1:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=
      - --verbosity=debug
      - --p2p-host-ip=
      - --p2p-tcp-port=13000
      - --p2p-udp-port=13000
      - --p2p-static-id
  </code>
</pre>

Node 2,Node 3
<pre>
  <code>
     - --min-sync-peers=1
      - --minimum-peers-per-subnet=0
      - --genesis-state=/files/genesis.ssz
      - --bootstrap-node=
      - --chain-config-file=/files/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://geth3:8551
      - --accept-terms-of-use
      - --jwt-secret=/jwtsecret
      - --suggested-fee-recipient=
      - --verbosity=debug
      - --p2p-tcp-port=13001 
      - --p2p-udp-port=13001 
      - --p2p-host-ip=
  </code>
</pre>

## Environment
Operation system ubuntu 22.04
docker image gcr.io/prysmaticlabs/prysm/beacon-chain:stable

<pre>
  <code>
time="2023-08-26 07:53:53" level=warning msg="Execution client is not syncing" prefix=powchain
panic: runtime error: integer divide by zero
goroutine 216 [running]:
github.com/prysmaticlabs/prysm/v4/consensus-types/primitives.ValidatorIndex.Mod(...)
        consensus-types/primitives/validator.go:39
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/altair.NextSyncCommitteeIndices({0xcc80f8, 0xc033638cc0}, {0xcf2de8?, 0xc026c1f680})
        beacon-chain/core/altair/sync_committee.go:129 +0x4d8
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/altair.NextSyncCommittee({0xcc80f8?, 0xc033638cc0?}, {0xcf2de8?, 0xc026c1f680})
        beacon-chain/core/altair/sync_committee.go:64 +0x50
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/altair.ProcessSyncCommitteeUpdates({0xcc80f8, 0xc033638cc0}, {0xcf2de8?, 0xc026c1f680})
        beacon-chain/core/altair/epoch_spec.go:33 +0xcd
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/altair.ProcessEpoch({0xcc80f8?, 0xc033638a80?}, {0xcf2de8, 0xc026c1f680})
        beacon-chain/core/altair/transition.go:108 +0x3a9
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/transition.ProcessSlots({0xcc8050?, 0xc000544a00?}, {0xcf2de8, 0xc026c1f680}, 0x15000)
        beacon-chain/core/transition/transition.go:258 +0xa93
github.com/prysmaticlabs/prysm/v4/beacon-chain/core/transition.UpdateNextSlotCache({0xcc8050, 0xc000544a00}, {0xc01f496c60, 0x20, 0x0?}, {0xcf2de8?, 0xc026c1e480?})
        beacon-chain/core/transition/trailing_slot_state_cache.go:61 +0xa5
github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain.(*Service).lateBlockTasks(0xc0002ae2d0, {0xcc8050, 0xc000544a00})
        beacon-chain/blockchain/process_block.go:521 +0x205
github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain.(*Service).runLateBlockTasks(0xc0002ae2d0)
        beacon-chain/blockchain/process_block.go:492 +0x1d9
created by github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain.(*Service).Start
        beacon-chain/blockchain/service.go:135 +0x125
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
"Prysm/v4.0.7/58df1f1ba5996d299c1c1d5874464884ee551be8. Built at: 2023-07-13 16:55:01+00:00"
  </code>
</pre>

**Comment by neodiz** [comment]
Latest node(prysm + geth ) work with --min-sync-peers=1

**Comment by prestonvanloon** [comment]
Closing old issues. Looks like a bad chain config. Please reply or file another issue if you are still experiencing this.
