### ISSUE TITLE
`Proposer: withdrawal roots don't match, using local block` and finally no local block is proposed

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/prysm#12820]
# 🐞 Bug Report

### Description

During the last month, we missed 3 blocks with `Prysm x BloXroute relay` combo.
The root cause is `Proposer: withdrawal roots don't match`, but at this point we are yet unsure if the issue comes from BloXroute relay(s) or from Prysm.

==> This ticket **only** talks about the second part of the error message in the title, namely: `using local block`.

-------

Here are the 3 blocks we missed:

**Slot:** 6977825
**⚠️ Slot in epoch:** 1
**Date:** Jul-28-2023 15:25:23 UTC
**Relay:** BloXroute regulated
**BN/VC:** Prysm

**Logs:**
- [MEV-boost (with uninteresting lines removed)](https://gist.github.com/nalepae/cd3d749d87947bbae0840c119efd5375)
- [VC](https://gist.github.com/nalepae/880484d718f0e2d2796c9678c9bf7808)
- [BN](https://gist.github.com/nalepae/44db908b328b6da4f533973d4a2167f6)

**Slot:** 7110305
**⚠️ Slot in epoch:** 1
**Date:** Aug-16-2023 01:01:23 UTC
**Relay:** BloXroute regulated
**BN/VC:** Prysm

**Logs:**
- [MEV-boost](https://gist.github.com/nalepae/b23a7e7c0694d0add4501b3e1f593d08)
- [VC](https://gist.github.com/nalepae/33e4fc0ea1654d88d6975d97604a1d0a)
- [BN](https://gist.github.com/nalepae/ace4e5201c7d2f7a59e8c1558bb19d31)

**Slot:** 7167681
**⚠️ Slot in epoch:** 1
**Date:** Aug-24-2023 00:16:35 UTC
**Relay:** BloXroute Max Profit
**BN/VC:** Prysm

**Logs:**
- [MEV-boost](https://gist.github.com/nalepae/0f5b5178b9b2cabd753488635d4391c8)
- [VC](https://gist.github.com/nalepae/8797a9a2fbe0d8d81f145340dc1afccb)
- [BN](https://gist.github.com/nalepae/e7b033bc5e79a3520545c6f313de67e9)

For these 3 blocks, we have the following log in the BN:

```
Proposer: withdrawal roots don't match, using local block
```

However, no local block never was proposed.

(Please note `getPayload` with the block signature in the body of the request in never called.)

**Information worth notifying**: `<slot_number>%32 == 1` (second slot in the epoch) for all missed blocks

## 🌍  Your Environment

**Operating System:**

**What version of Prysm are you running? (Which release)**
- Prysm BN/VC: `4.0.7`
- Geth: `v1.12.0`
- W3S: `23.6.0`
- MEV-boost: `1.6`

**Comment by nisdas** [comment]
Hey @nalepae , if the relay is indeed giving a bad payload then prysm will reject it with that error. Do you see any other local errors over the last few days ? If we correctly fallback to the local payload then I will close the issue.
