### ISSUE TITLE
Checkpoint sync fails to start - "requesting" log lines not appearing

### ISSUE THREAD

**Issue by please-fill-out-this-field** [prysmaticlabs/prysm#12825]
# 💎 Issue

### Background

Prysm v4.0.6

geth 1.12.0

That's how I start Prysm:

```
beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=/path/to/jwt.hex --datadir=/path/to/consensus --accept-terms-of-use --checkpoint-sync-url=https://beaconstate-mainnet.chainsafe.io --genesis-beacon-api-url=https://beaconstate-mainnet.chainsafe.io
```

And here's the guide I'm trying to follow:

https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

### Description

> To confirm that checkpoint sync has succeeded, look for the following output:
> ```level=info msg="requesting <your configured checkpoint sync endpoint>"```

I don't see these lines - `$my_command_line | grep requesting` prints nothing no matter how long I wait.

I got this message, among others

```
msg="Synced to finalized epoch - now syncing blocks up to current head" currentSlot=7202416 prefix=initial-sync syncedSlot=7202409
```

and since then it only prints "synced new block" stuff.

Data generated by Prysm currently occupies about 7 GB - I believe I'm very far from being fully synced.

Oh by the way, I thought maybe the guide is obsolete and these log lines are no longer printed in newer prysm versions even if the connection is actually happening. So I tried `netstat -tupa` just in case. Still nothing related to my configured checkpoint provider.

Am I missing something?

**Comment by please-fill-out-this-field** [comment]
> Checkpoint sync is a feature to sync from a checkpoint so the small disk footprint is expected since you are only syncing the last part of the chain since the checkpoint.

Okay, how do I know when my node becomes operational?

What about the "requesting" logs anyway?

**Comment by james-prysm** [comment]
Please reach out on discord if there's further issues with getting started, an issue on the docs for any outdated material can also be added. closing this issue as it's pretty stale.
