### ISSUE TITLE
Can't sync blocks by range under interop mode

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12831]
```
time="2023-08-29 22:41:12" level=debug msg="Could not request blocks by range from peer" error="stream reset" peer=16Uiu2HAm22c9ybDmv5NC5XUXcpxPZdaMaTEFaq8Q8tDiDnmY2pjF prefix=initial-sync
```

**Comment by kasey** [comment]
@terencechain does this need a resolution? I think stream resets between peers are expected and a request like this should typically be retried automatically.

**Comment by terencechain** [comment]
I think the resolution here will be to try interop script and make sure the second node can sync block by range. It's not working for me and that that will be valuable to test
