### ISSUE TITLE
How do I fix this problem  "could not find block in DB" prefix=blockchain"

### ISSUE THREAD

**Issue by tz321** [prysmaticlabs/prysm#12846]
# 🐞 Bug Report

### Description

 I use the command ./prysm.sh beacon-chain --mainnet --execution-endpoint=http://localhost:8551 --jwt-secret=/root/eth/consensus/prysm/jwt.hex
It has been running for more than two weeks and many blocks have been synchronized before. I encountered this problem recently.
## 🔥 Error

<pre><code>

Troubleshooting report
---------
Operating system: Linux, MacOS, Arm64
Network: Mainnet
Execution client: Geth
EN-BN connection: HTTP-JWT
---------
Beacon node command:  nohup ./prysm.sh beacon-chain  --mainnet --execution-endpoint=http://localhost:8551 --jwt-secret=/root/eth/consensus/prysm/jwt.hex  >nohup.txt 2>&1 &
---------
Unexpected output: Latest Prysm version is v4.0.8.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v4.0.8-linux-amd64: OK
gpg: Signature made Wed 23 Aug 2023 03:51:23 AM CST using RSA key ID F1A5036E
gpg: Good signature from "Preston Van Loon "
gpg:                 aka "Preston Van Loon "
gpg:                 aka "Preston Van Loon "
gpg:                 aka "Preston Van Loon (0xf71E9C766Cdf169eDFbE2749490943C1DC6b8A55) "
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /root/eth/consensus/prysm/dist/beacon-chain-v4.0.8-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --mainnet --execution-endpoint=http://localhost:8551 --jwt-secret=/root/eth/consensus/prysm/jwt.hex
time="2023-09-04 10:00:03" level=info msg="Finished reading JWT secret from /root/eth/consensus/prysm/jwt.hex"
time="2023-09-04 10:00:03" level=warning msg="Running on Ethereum Mainnet" prefix=flags
time="2023-09-04 10:00:03" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node
time="2023-09-04 10:00:03" level=info msg="Checking DB" database-path="/root/.eth2/beaconchaindata" prefix=node
time="2023-09-04 10:00:03" level=info msg="Opening Bolt DB at /root/.eth2/beaconchaindata/beaconchain.db" prefix=db
time="2023-09-04 10:00:03" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
time="2023-09-04 10:00:35" level=info msg="Running node with peer id of 16Uiu2HAm4R8S8v4qNFgXW6pEUT1wKNPAfjnPyuTyF2yRcbvyWSsW " prefix=p2p
time="2023-09-04 10:00:36" level=info msg="gRPC server listening on port" address="127.0.0.1:4000" prefix=rpc
time="2023-09-04 10:00:36" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
time="2023-09-04 10:00:36" level=info msg="Starting beacon node" prefix=node version="Prysm/v4.0.8/0ca3644057e27966a446051fe3bc3389a1add54e. Built at: 2023-08-22 18:13:00+00:00"
time="2023-09-04 10:00:36" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2023-09-04 10:00:36" level=info msg="Starting API middleware" prefix=gateway
time="2023-09-04 10:00:36" level=fatal msg="could not update forkchoice's justified checkpoint: could not update justified balances: could not get justified balances: could not get state summary: could not find block in DB" prefix=blockchain

</code></pre>

## 🌍  Your Environment
**Operating System:**
<pre>
  <code>
CentOS Linux release 7.9.2009  

Linux ecs-eth 3.10.0-1160.92.1.el7.x86_64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
https://docs.prylabs.network/docs/install/install-with-script
curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh --output prysm.sh && chmod +x prysm.sh
./prysm.sh beacon-chain  --mainnet --execution-endpoint=http://localhost:8551 --jwt-secret=/root/eth/consensus/prysm/jwt.hex

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Looks like an improper shutdown. Closing old issues here. If this is still an issue, please reply or create another issue. Thanks
