### ISSUE TITLE
Unable to luanch: Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md

### ISSUE THREAD

**Issue by mbwmbw1337** [prysmaticlabs/prysm#12845]
Any ideas? 
```
docker run -it -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon-node \
  --workdir=$(eval echo ~$USER)/beacon-node  \
  --mount type=bind,source=$(eval echo ~$USER)/beacon-node,target=/data \
  --mount type=bind,source=$(eval echo ~$USER)/eth-node,target=/eth-node \
  -e CGO_CFLAGS='-O -D__BLST_PORTABLE__' \
  -e CGO_CFLAGS_ALLOW='-O -D__BLST_PORTABLE__' \
  gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
  --datadir=/data \
  --rpc-host=0.0.0.0 \
  --grpc-gateway-host=0.0.0.0 \
  --monitoring-host=0.0.0.0 \
  --execution-endpoint=/eth-node/.ethereum/geth.ipcmkdir: cannot create directory ‘/home/docker/beacon-node’: File exists
$ $ $ > > > > > > > > > > > 
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
```

**Comment by potuz** [comment]
You need to use the portable version in that CPU. Latest versions of prysm would do a runtime check. Closing this issue as completed. Feel free to reopen it if you need more help

**Comment by mbwmbw1337** [comment]
Thank you for the very quick response. I am using the latest docker image. I did not see any commentary in the documentation about the different versions: portable and non-portable. However, I did see them in release notes.

I would urge you to update https://docs.prylabs.network/docs/install/install-with-docker as soon as possible.

What is the docker image URL for the portable version?
