### ISSUE TITLE
Avoid caching pre-genesis SignedValidatorRegistration objects

### ISSUE THREAD

**Issue by bharath-123** [prysmaticlabs/prysm#12840]
Prysm caches SignedValidatorRegistration objects as shown here before sending it to the MEV relay https://github.com/prysmaticlabs/prysm/blob/0a5c322f2211bee538c9f8279711ef94d6f13c28/validator/client/registration.go#L79 , I believe we register SignedValidatorRegistration with the relayers every epoch. Epoch 0 runs before the genesis timestamp. Sending SignedValidatorRegistration object to relayers before genesis fails because of https://github.com/flashbots/mev-boost-relay/blob/main/services/api/service.go#L1019 . The request to send fails, but the object is still cached. Whenever we resend it post-genesis, we pick the cached object with a stale timestamp, making it such that the validators can never be registered on the relay.

The solution I feel should be we shouldn't cache pre-genesis ValidatorRegistration objects in prysm. We should add a check if the timestamp is before genesis and avoid caching such an object.

This is not an issue in the current status quo, as relayers were introduced post genesis. This mainly fails in custom devnet setups where we setup relays from genesis. 

This issue can be reproduced using kurtosis(https://github.com/kurtosis-tech/eth2-package), by setting up with prysm as the consensus client.

**Comment by bharath-123** [comment]
With the below network.json file, we can setup the kurtosis devnet
```
{
  "participants": [
    {
      "el_client_type": "geth",
      "el_client_image": "",
      "el_client_log_level": "",
      "el_extra_params": [],
      "cl_client_type": "prysm",
      "cl_client_log_level": "",
      "cl_client_image": "",	
      "beacon_extra_params": [],
      "validator_extra_params": [],
      "builder_network_params": null,
      "count": 1
    }
  ],

  "network_params": {
    "network_id": "3151908",

    "deposit_contract_address": "0x4242424242424242424242424242424242424242",

    "seconds_per_slot": 12,

    "slots_per_epoch": 32,

    "num_validator_keys_per_node": 64,

    "preregistered_validator_keys_mnemonic": "giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete",

    "capella_fork_epoch": 1,
    "deneb_fork_epoch": 5000
  },

  "launch_additional_services": true,

  "wait_for_finalization": false,

  "wait_for_verifications": false,

  "verifications_epoch_limit": 5,

  "global_client_log_level": "info",

  "snooper_enabled": false,

  "parallel_keystore_generation": false,

  "mev_type": "full",

  "mev_params": {
    "mev_relay_api_extra_args": [],
    "mev_relay_housekeeper_extra_args": [],
    "mev_relay_website_extra_args": [],
    "mev_builder_extra_args": [],
    "mev_flood_extra_args": []
  }
}


```
with the following command:

`sudo kurtosis run --enclave my-testnet github.com/kurtosis-tech/eth2-package "$(cat ./network.json)"`

you can see through the mev-relayer api logs the error that `timestamp is too early`

**Comment by nisdas** [comment]
cc @james-prysm

**Comment by bharath-123** [comment]
Discussed with james offline, raised a PR to fix this  https://github.com/prysmaticlabs/prysm/pull/12847
