### ISSUE TITLE
`eth_call` is sent to Nethermind with field not included in API specification.

### ISSUE THREAD

**Issue by kamilchodola** [prysmaticlabs/prysm#12850]
# 🐞 Bug Report

### Description

In Nethermind we reverted one of the changes and ensured that our eth_call is according to the spec:
https://[ethereum.github.io/execution-apis/api-documentation/](https://ethereum.github.io/execution-apis/api-documentation/)
One of important things is to have "input" field on transaction details.

When this adjustment was made, noticed that on any node with Prysm (sepolia/mainnet/goerli) we started getting errors:
```
Error when handling ID 3, eth_call({
  "data": "0x621fd130",
  "from": "0x0000000000000000000000000000000000000000",
  "to": "0x7f02c3e3c98b133055b8b348b2ac625669ed295d"
},latest) | {"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"revert"},"id":3}
```
After some investigation we noticed, that instead of receiving "input" from prysm we got "data". When we reverted that change everything is fine for now, but the usage of eth_call in that scenario is not matching the API specifications mentioned above.

### Has this worked before in a previous version?

Yes, until we adjusted according to spec.

## 🔬 Minimal Reproduction

I guess it is quite self explanatory from Description - as for now Nethermind handles both fields but we would like to support only one as described in spec.

## 🔥 Error
<pre><code>
Error when handling ID 3, eth_call({
  "data": "0x621fd130",
  "from": "0x0000000000000000000000000000000000000000",
  "to": "0x7f02c3e3c98b133055b8b348b2ac625669ed295d"
},latest) | {"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"revert"},"id":3}
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04, Docker installation of Prysm and nethermind
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
4.0.8
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
-

**Comment by nisdas** [comment]
Hey @kamilchodola , 

Thanks for opening the issue, we do not currently directly implement the handlers for execution APIs, instead we use geth's bindings here. It appears to be the reason why have the `data` field instead of the `input` field. 
https://github.com/ethereum/go-ethereum/blob/master/ethclient/ethclient.go#L622

We can try and get this resolved upstream and then have the changes reflected in prysm.

**Comment by nisdas** [comment]
A corresponding issue has been opened here:
https://github.com/ethereum/go-ethereum/issues/28077
