### ISSUE TITLE
checkpoint-sync download 404

### ISSUE THREAD

**Issue by Linzdigr** [prysmaticlabs/prysm#12862]
Hello there,

From the [doc](https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync) I tried to get a file export of the current checkpoint of a Prysm synced node with different version of prysmctl but I can't get anything different from a **404 Not found** in the process.

Prysm node is a docker image instance on latest (sha256:e19c420dea9f1b5820b00e6d0ccf07983703d3051b8c60dee7a38f31a601489a / https://github.com/prysmaticlabs/prysm/commit/34f507f4b2a589ee70d16a9818458edd8015da34)

See the last try below:

```sh
~/ETH/prysm/cmd/prysmctl# curl http://localhost:3500/eth/v1/node/syncing | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   111  100   111    0     0    99k      0 --:--:-- --:--:-- --:--:--  108k
{
  "data": {
    "head_slot": "7272245",
    "sync_distance": "0",
    "is_syncing": false,
    "is_optimistic": true,
    "el_offline": true
  }
}

~/ETH/prysm/cmd/prysmctl# git rev-parse origin/master
2674e204cab117b1e902c78d72d8b6faaec7e6a0

~/ETH/prysm/cmd/prysmctl# go run main.go checkpoint-sync download
FATA[0000] Could not download checkpoint-sync data       error="error requesting state by id = finalized: code=404, url=http://localhost:3500/eth/v2/debug/beacon/states/finalized, body=response body:\n{\"message\":\"Not Found\",\"code\":404}: recv 404 NotFound response from API: did not receive 2xx response from API"
exit status 1
```

Is there something wrong in my process ?

Thanks.

**Comment by prestonvanloon** [comment]
Closing old issues. If this is still an issue, please reply or create a new github issue.
