### ISSUE TITLE
DB: Prune Irrelevant Blob Sidecars

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12869]
**Description:**

There's a current behavior in our node where it saves a valid blob sidecar regardless of the status of the associated block. This can lead to situations where the block either never arrives or is invalid upon arrival, yet the blob sidecar remains saved in the DB.

**Proposed Solutions:**
1. Prune blob sidecar if it's older than the finalized epoch and has no associated block.
2. Prune blob sidecar is not part of the canonical chain if it's older than the finalized epoch and its associated block.
3. Prune blob sidecar if its associated block transitions from an optimistic status to an invalid status. (Note: This behavior might already be implemented)

**Comment by kasey** [comment]
I don't think this is worth the trouble because the round-robin db behavior will eventually reuse the key and overwrite the value.

**Comment by terencechain** [comment]
I'm not too worried about storage. I'm more worried about returning the wrong data to requests that are RPC or P2P

**Comment by kasey** [comment]
Per the p2p2 spec, `BlobSidecarsByRange` will only return blobs that are referenced by canonical blocks leading up to our current view of head, so that shouldn't be an issue. The implementation queries for blocks over the given range and then looks up the blobs for each block by root.

**Comment by terencechain** [comment]
> Per the p2p2 spec, `BlobSidecarsByRange` will only return blobs that are referenced by canonical blocks leading up to our current view of head, so that shouldn't be an issue. The implementation queries for blocks over the given range and then looks up the blobs for each block by root.

What about beacon api?

**Comment by kasey** [comment]
Can we change this issue to something like "Beacon API should check to ensure blob sidecars retrieved by slot are for a canonical block"? I'm betting it will be much simpler for Beacon API code to check in with `IsCanonical` than it will be to correctly implement blob pruning.

**Comment by terencechain** [comment]
Yeah. It'd make sense to close this and open another one for beacon api
I'll let it marinate for a while before closing it if anyone else has inputs

**Comment by terencechain** [comment]
But keep in mind there is a paradigm shift under this new thinking. We/the node have always assumed everything stored in the DB is valid. This changes this assumption moving forward

**Comment by terencechain** [comment]
Note this will be handled in #12875. I will close it for now. Feel free to reopen if anyone feels otherwise
