### ISSUE TITLE
Implement Updating of State Latest Deposit Root

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1287]
Hi all,

This is part of #1284. According to the spec and the [document](https://docs.google.com/document/d/1-4ct3v7O9dRiYZXqMO3lO6V3MqZd3Aa881CsagwAGVI/edit#) put together by the Pegasys team regarding deposit processing: 

Every DEPOSIT_ROOT_VOTING_PERIOD / EPOCH_LENGTH epochs (1024/64 = 16 epochs) 
a check is done. If a deposit root has received over half of the available votes during the 
last epoch we put it into the state’s latest_deposit_root and clear the candidate deposit root list.

A PR would implement the logic above in the `blockchain` service to update the state accordingly. It is recommended to use a Mutex here to prevent any other updates to state during the setting of the latest_deposit_root.

**Comment by terenc3t** [comment]
This exists. It's part of epoch processing

https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/epoch/epoch_processing.go#L30
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/epoch/epoch_processing.go#L60
