### ISSUE TITLE
Send POW Chain Deposit Logs to Validator Clients via gRPC

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1288]
Hi all,

Beacon block proposers need to be aware of any incoming deposits from the POW Chain deposit contract to include in the deposits field of their proposed beacon blocks. The easiest way to do this would be to implement an RPC method called `LatestDeposit` in the beacon node which would receive deposit objects from an event feed (which would originate from the `powchain` service) and stream them via gRPC to connected validator clients.

A PR for this issue would implement the above with relevant tests.

**Comment by cyberbono3** [comment]
@rauljordan could you please give more context regarding this issue? so I can start digging into it.

**Comment by prestonvanloon** [comment]
Is this in any design doc? 
What about the alternative: reading the contract itself from PoW?

**Comment by terenc3t** [comment]
@cyberbono3 not at this moment, do you mind wrap up #1316 and #1320 first before taking this? let's limit ourselves to 2 outstanding PRs : )
