### ISSUE TITLE
rpc/validator: Not connected to ETH1. Cannot determine validator ETH1 deposit block number

### ISSUE THREAD

**Issue by ppppppppppppppppppppl** [prysmaticlabs/prysm#12881]
## Description
Please help!
I'm running PoS Geth and Prysm on Windows following setup instructions from prylabs: https://docs.prylabs.network/docs/install/install-with-scriptand 

My validator just **activated** today, and beaconcha.in shows that I missed all the slots and my balance has been going down! Also I keep getting this message from validation: 
`[2023-09-09 13:48:39]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0x88dc8960e9a0 status=UNKNOWN_STATUS `

Here is the beacon node connectivity status: 
```
*builder.Service: OK
*prometheus.Service: OK
*execution.Service: OK
*blockchain.Service: OK
*initialsync.Service: OK
*rpc.Service: OK
*gateway.Gateway: OK
*p2p.Service: OK
*attestations.Service: OK
*sync.Service: OK
```

Here is beacon node - execution node connectivity status: 
```
curl http://localhost:8080/healthz
*p2p.Service: OK
*rpc.Service: OK
*initialsync.Service: OK
*sync.Service: OK
*builder.Service: OK
*gateway.Gateway: OK
*prometheus.Service: OK
*execution.Service: OK
*attestations.Service: OK
*blockchain.Service: OK
```

EL syncing status:
```
eth.syncing
false
```

CL syncing status:
```
curl http://localhost:3500/eth/v1/node/syncing
{"data":{"head_slot":"7289037","sync_distance":"1","is_syncing":false,"is_optimistic":false,"el_offline":false}}
```

Can anyone help? I've attached a full troubleshooting report and logs from EL, CL and validation. 

[Validation Log.txt](https://github.com/prysmaticlabs/prysm/files/12566672/Validation.Log.txt)
[Execution Log.txt](https://github.com/prysmaticlabs/prysm/files/12566673/Execution.Log.txt)
[Beacon Log.txt](https://github.com/prysmaticlabs/prysm/files/12566674/Beacon.Log.txt)
[debugging report.txt](https://github.com/prysmaticlabs/prysm/files/12566408/debugging.report.txt)

### Operating System:
`Windows 11`

### Prysm Version
```
Latest prysm release is v4.0.8.
Using prysm version v4.0.8.
Beacon chain is up to date.
WARN GPG verification is not natively available on Windows.
WARN Skipping integrity verification of downloaded binary
Verifying binary authenticity with SHA256 Hash.
SHA256 Hash Match
Starting Prysm beacon-chain --version
beacon-chain version Prysm/v4.0.8/0ca3644057e27966a446051fe3bc3389a1add54e. Built at: 2023-08-22 18:30:36+00:00
```

### Geth Version
```
Version: 1.12.2-stable
Git Commit: bed84606583893fdb698cc1b5058cc47b4dbd837
Git Commit Date: 20230812
Architecture: amd64
Go Version: go1.20.7
Operating System: windows
GOPATH=
GOROOT=
```

**Comment by nisdas** [comment]
@ppppppppppppppppppppl It does appear to be an issue with your execution node, it is constantly generating snapshots. Maybe try waiting for it to resolve or restarting your node.

**Comment by ppppppppppppppppppppl** [comment]
> @ppppppppppppppppppppl It does appear to be an issue with your execution node, it is constantly generating snapshots. Maybe try waiting for it to resolve or restarting your node.

It's still generating the snapshots after two hours. EL and CL are fully synced. I have restarted the node and rebooted the computer. But I still have the issue. Do you think I have configuration issues? I'm wondering how long it will take to fix on its own. 

```
INFO [09-09|18:48:40.557] Aborting state snapshot generation       root=22ae06..e704f2 at=0ab7ea..1deeea accounts=9,180,836       slots=41,347,197      storage=3.46GiB    dangling=0 elapsed=1h10m42.423s eta=26h58m4.094s
INFO [09-09|18:48:40.565] Resuming state snapshot generation       root=bc6e0e..b2a095 at=0ab7ea..1deeea accounts=9,180,836       slots=41,347,197      storage=3.46GiB    dangling=0 elapsed=1h10m42.432s eta=26h58m4.3s
```

**Comment by ppppppppppppppppppppl** [comment]
> > @ppppppppppppppppppppl It does appear to be an issue with your execution node, it is constantly generating snapshots. Maybe try waiting for it to resolve or restarting your node.
> 
> It's still generating the snapshots after two hours. EL and CL are fully synced. I have restarted the node and rebooted the computer. But I still have the issue. Do you think I have configuration issues? I'm wondering how long it will take to fix on its own.
> 
> ```
> INFO [09-09|18:48:40.557] Aborting state snapshot generation       root=22ae06..e704f2 at=0ab7ea..1deeea accounts=9,180,836       slots=41,347,197      storage=3.46GiB    dangling=0 elapsed=1h10m42.423s eta=26h58m4.094s
> INFO [09-09|18:48:40.565] Resuming state snapshot generation       root=bc6e0e..b2a095 at=0ab7ea..1deeea accounts=9,180,836       slots=41,347,197      storage=3.46GiB    dangling=0 elapsed=1h10m42.432s eta=26h58m4.3s
> ```

Maybe I should refer to the ETA 27h?

**Comment by ppppppppppppppppppppl** [comment]
> @ppppppppppppppppppppl It does appear to be an issue with your execution node, it is constantly generating snapshots. Maybe try waiting for it to resolve or restarting your node.

After running a night, it has completed creating the snapshot. But the validation still gives me the same message. The balance is still decreasing. Can anyone help with this issue?
`[2023-09-10 09:21:27]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0x88dc8960e9a0 status=UNKNOWN_STATUS`

Attachin
[Beacon Log.txt](https://github.com/prysmaticlabs/prysm/files/12568276/Beacon.Log.txt)
[Execution Log.txt](https://github.com/prysmaticlabs/prysm/files/12568277/Execution.Log.txt)
g EL and CL logs
