### ISSUE TITLE
bugs for sync from a checkpoint

### ISSUE THREAD

**Issue by leafan** [prysmaticlabs/prysm#12907]
### Describe the bug

when clear the db path(even in a clean directory), thenstart the program with flags: --checkpoint-sync-url=https://sync.invis.tools/ --genesis-beacon-api-url=https://sync.invis.tools/ which copied from here: "https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync#option-1-configure-checkpoint-sync-via-network-request", it shows me error:

[2023-09-15 18:16:24] WARN flags: Running on Ethereum Mainnet
[2023-09-15 18:16:24] WARN node: In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient).
[2023-09-15 18:16:24] INFO node: Checking DB database-path=/root/.eth2/beaconchaindata
[2023-09-15 18:16:24] INFO db: Opening Bolt DB at /root/.eth2/beaconchaindata/beaconchain.db
[2023-09-15 18:16:24] **WARN database contains genesis with htr=0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b, ignoring remote genesis state parameter**

and then, it will no longer output any things.

I think it's a bug: it will produce the db when there's no db file, whatever your params are.

There's some same issues, but i don't think it's fixed:
1. https://github.com/prysmaticlabs/prysm/issues/11525
2. https://github.com/prysmaticlabs/prysm/issues/12206

### Has this worked before in a previous version?

```text
tried for v4.0.6, also failed.
```

### 🔬 Minimal Reproduction

1. new directory
2. start the program with sync flags

### 🌍 Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v4.0.8, v4.0.6

**Comment by leafan** [comment]
solved.

comment one line for file: fullnode/eth/prysm/beacon-chain/sync/genesis/api.go:

`
func (dl *APIInitializer) Initialize(ctx context.Context, d db.Database) error {
	existing, err := d.GenesisState(ctx)
	if err != nil {
		return err
	}
	if existing != nil && !existing.IsNil() {
		htr, err := existing.HashTreeRoot(ctx)
		if err != nil {
			return errors.Wrap(err, "error while computing hash_tree_root of existing genesis state")
		}
		log.Warnf("database contains genesis with htr=%#x, ignoring remote genesis state parameter", htr)
		// return nil   # comment for --checkpoint-sync-url option first.
	}
	sb, err := dl.c.GetState(ctx, beacon.IdGenesis)
	if err != nil {
		return errors.Wrapf(err, "Error retrieving genesis state from %s", dl.c.NodeURL())
	}
	return d.LoadGenesis(ctx, sb)
}

`

I don't know whether it's a good choice, but it fit for me. And I think it was right, for it showed me a warning, and then should be go again.

**Comment by nisdas** [comment]
This looks like it stalls here `https://sync.invis.tools/ ` , maybe try another checkpoint sync provider

**Comment by leafan** [comment]
> This looks like it stalls here `https://sync.invis.tools/ ` , maybe try another checkpoint sync provider

 ok, got it, let me check.
Thanks.
