### ISSUE TITLE
Wrong type in `/eth/v1/config/deposit_contract` endpoint

### ISSUE THREAD

**Issue by pk910** [prysmaticlabs/prysm#12949]
### Describe the bug

Prysm nodes currently return the `chain_id` field in [/eth/v1/config/deposit_contract](https://ethereum.github.io/beacon-APIs/#/Config/getDepositContract) as numeric value:
```
{
    "data": {
        "chain_id": 7011893058,
        "address": "0x6f22fFbC56eFF051aECF839396DD1eD9aD6BBA9D"
    }
}
```
According to the specs this should be a string (`"7011893058"`).

Some downstream libraries (eg. [attestantio/go-eth2-client](https://github.com/attestantio/go-eth2-client)) don't like that and fail on initialization because of that.

### Has this worked before in a previous version?

probably there since ~2 weeks, the relevant code has been touched in https://github.com/prysmaticlabs/prysm/pull/12872

### 🔬 Minimal Reproduction

call `/eth/v1/config/deposit_contract` api and check result

**Comment by saolyn** [comment]
Thank you for bringing this to our attention
