### ISSUE TITLE
`Prepared Capella beacon block is blinded` when requesting a full block

### ISSUE THREAD

**Issue by michaelsproul** [prysmaticlabs/prysm#12950]
### Describe the bug

We (Lighthouse) received a report on Discord of a failed proposal due this error being returned from the `/eth/v2/beacon/blocks` endpoint:

> CRIT Error whilst producing block            info: proposal did not use a builder, block_slot: Slot(X), message: Recoverable("Some endpoints failed, num_failed: 1 http://192.168.1.2:5052/ => RequestFailed(Recoverable(\"Error from beacon node when producing block: ServerMessage(ErrorMessage { code: 500, message: \\\"Prepared Capella beacon block is blinded\\\", stacktraces: [] })\"))"), service: block

This is a Lighthouse VC connected to a Prysm BN, and the inner error `Prepared Capella beacon block is blinded` comes from the Prysm BN. I don't understand what this means, because on this code path the Lighthouse VC is definitely hitting the `/eth/v2/beacon/blocks` endpoint. Is this the result of a misconfiguration where the Prysm BN wants to use a builder, and therefore can't build local blocks? Or is this likely related to the recent Geth block-building bug?

**Comment by james-prysm** [comment]
aware of the issue, will address as we clean up the api. closing for now

**Comment by terencechain** [comment]
Reopening the issue. The `/eth/v2/beacon/blocks` API should always return a full block, regardless of MEV-Boost settings. A straightforward fix is in the works, utilizing the existing `skipMevBoost` flag in the gRPC endpoint. A PR will be opened today to address this.

**Comment by terencechain** [comment]
@michaelsproul, the latest prysm develop branch should have this issue fixed. `/eth/v2/beacon/blocks` will never return a blind block. Please let me know if you see more issues 🙏🏼

**Comment by michaelsproul** [comment]
Fantastic, thanks!

This wasn't something I ran into personally, but I'll let you know if I see any more reports!

**Comment by marioevz** [comment]
Hey @james-prysm, this is currently reproducing in hive when I changed the prysm validator client to switch to use the rest API of prysm beacon node:
```
time="2023-10-26 19:54:25" level=error msg="Failed to request block from beacon node" blockSlot=2 error="failed to query GET REST endpoint: error 500: Prepared Capella beacon block is blinded" prefix=validator pubKey=0xa80e6e09cadb
```
Then the builder is unable to build anything throughout the entire epoch.

These are the parameters I'm currently using:

prysm beacon node:
```bash
--verbosity=trace
--accept-terms-of-use=true
--datadir=/data/beacon
--chain-config-file=/hive/input/config.yaml
--genesis-state=/hive/input/genesis.ssz
--p2p-tcp-port=900
--p2p-udp-port=9000
--p2p-host-ip=172.19.0.5
--p2p-local-ip=172.19.0.5
--execution-endpoint=http://172.19.0.3:8551
--jwt-secret=/jwtsecret
--min-sync-peers=1
--subscribe-all-subnets=true
--enable-debug-rpc-endpoints=true
--disable-monitoring=false
--monitoring-host=0.0.0.0
--monitoring-port=8080
--http-mev-relay=http://0x95fde78acd5f6886ddaf5d0056610167c513d09c1c0efabbc7cdcc69beea113779c4a81e2d24daafc5387dbf6ac5fe48@172.19.0.3:18550
--deposit-contract=0x4242424242424242424242424242424242424242
--contract-deployment-block=0
--rpc-host=0.0.0.0
--rpc-port=4001
--grpc-gateway-host=0.0.0.0
--grpc-gateway-port=4000
--grpc-gateway-corsdomain=*
--suggested-fee-recipient=0xa94f5374Fce5edBC8E2a8697C15331677e6EbF0B
```

validator client:
```
--verbosity=trace
--accept-terms-of-use=true
--prater
--enable-beacon-rest-api=true
--beacon-rest-api-provider=http://172.19.0.5:4000
--datadir=/data/vc
--wallet-dir=/data/validators
--wallet-password-file=/wallet.pass
--chain-config-file=/hive/input/config.yaml
--enable-builder
--suggested-fee-recipient=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
```

This is on `devnet-10` and `develop` branches.

**Comment by james-prysm** [comment]
will investigate perhaps it's related to this bug radek was researching https://github.com/prysmaticlabs/prysm/pull/13116

**Comment by rkapka** [comment]
Hi @marioevz , the initial issue was related to the `/beacon/blocks` endpoint, but I expect you are running into issues when producing the block? In that case it's another endpoint that's being triggered. Nonetheless, https://github.com/prysmaticlabs/prysm/pull/13116 takes a stab at fixing the problem with producing blinded blocks with the REST validator client.

**Comment by marioevz** [comment]
Hey @rkapka, the problematic behavior is no longer happening after running with #13116, I think this can be closed again, thanks!

**Comment by rkapka** [comment]
@marioevz I'm glad to hear this. Closing.
