### ISSUE TITLE
`/eth/v1/beacon/headers/{block_id}` does not accept hex encoded block root

### ISSUE THREAD

**Issue by pk910** [prysmaticlabs/prysm#12977]
### Describe the bug

The `/eth/v1/beacon/headers/{block_id}` endpoint does not support hex encoded block roots with 0x prefix:

```
{
  "message": "Invalid block ID: could not parse block ID: strconv.ParseUint: parsing \"0x9dd67540a9c17a4ba2d8346b545ffb1f6d4c0412ffb6a5ab36634440314901dd\": invalid syntax",
  "code": 400
}
```

According to the specs, this should be allowed: [Beacon/getBlockHeader](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader).

The error is triggered here:
https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/rpc/lookup/blocker.go#L78

I guess the logic in line 72-76 should handle blockroot arguments,  but it assumes a binary `id` instead of hex encoding  

### 🔬 Minimal Reproduction

call `/eth/v1/beacon/headers/{block_id}` with any hex encoded block root as `block_id`

**Comment by rkapka** [comment]
Thanks for finding this @pk910 ! It is indeed a bug in the code you mentioned.

**Comment by marioevz** [comment]
This bug is currently affecting prysm runs in the `eth2-deneb-builder` tests here: https://hiveinterop.ethdevops.io/
