### ISSUE TITLE
Invalid TTD configured when i set up devnet

### ISSUE THREAD

**Issue by 757566833** [prysmaticlabs/prysm#12975]
# 💎 Issue

### Background

i want to set up devnet to test,the reference documentation is 

https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet#manual-setup-built-from-source

I did not build from source code but directly downloaded the release

```
geth version 1.13.2-stable-dc34fe82

beacon-chain version Prysm/v4.0.8/0ca3644057e27966a446051fe3bc3389a1add54e. Built at: 2023-08-22 18:13:00+00:00

validator version Prysm/v4.0.8/0ca3644057e27966a446051fe3bc3389a1add54e. Built at: 2023-08-22 18:13:00+00:00

```
download all from release 4.0.8

https://github.com/prysmaticlabs/prysm/releases/tag/v4.0.8

when i run beacon-chain

<img width="730" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/25276557/715daf40-2d99-4eb2-95c2-a173f848af24">

geth log 
```
WARN [10-01|12:04:08.223] Invalid TTD configured                   geth=0 beacon=0x32
WARN [10-01|12:04:08.223] Served engine_exchangeTransitionConfigurationV1 conn=127.0.0.1:45162 reqid=101 duration="77.034µs"  err="invalid ttd: execution 0 consensus 0x32"
```

beacon-chain log

```
[2023-10-01 11:55:18] ERROR powchain: Could not check configuration values between execution and consensus client error=invalid ttd: execution 0 consensus 0x32: client error while processing request
[2023-10-01 11:55:18]  WARN powchain: Execution client is not syncing
[2023-10-01 11:55:18] ERROR powchain: Beacon node is not respecting the follow distance
```
https://github.com/OffchainLabs/eth-pos-devnet/blob/master/execution/genesis.json
```
...
"terminalTotalDifficulty": 0,
...
```
config.yml
```
...
TERMINAL_TOTAL_DIFFICULTY: 50
...
```
It seems to be talking about this

how to solve this

**Comment by prestonvanloon** [comment]
Try setting TERMINAL_TOTAL_DIFFICULTY to 0 to match geth

**Comment by terencechain** [comment]
@757566833 closing this, feel free to reopen if still persists
