### ISSUE TITLE
Checking DB - Massive Memory Usage & Runtime - Full Archive Node

### ISSUE THREAD

**Issue by mbwmbw1337** [prysmaticlabs/prysm#13006]
I am seeing 5+ hour runtime for the Checking DB stage and upwards of 40-60 GB of memory used. I am running a full archive node for Prysm. Any tips?

**Comment by mbwmbw1337** [comment]
Now up to 10 hours still checking database.

**Comment by prestonvanloon** [comment]
@mbwmbw1337 I'm looking into this now to see if there is any additional information we can surface to understand this very long start up and high memory usage. Based on the symptoms, it sounds like the db is doing a full scan.

**Comment by mbwmbw1337** [comment]
See #13051.

I think they're related. Highly likely because I am saving each block?

**Comment by nisdas** [comment]
@mbwmbw1337 Every node always saves each block, what that flag does is it saves each state for a slot. Imo, there isn't much benefit to saving it every slot:
```
--slots-per-archive-point=1 
```
Using 
```
--slots-per-archive-point=32 
```
should give a similar performance without increasing the database to such large sizes.

**Comment by prestonvanloon** [comment]
I haven't had much time to investigate this. It sounds like an improper shutdown is causing bbolt to do some extra work.

**Comment by prestonvanloon** [comment]
Closing old issues. I never got to find the root cause of this. The trigger was an improper shutdown (panicked code) and then bolt db was in a really bad state. Not sure what we can do to fix it in Prysm besides never panic. 

If this is still an issue, please reply here or create another ticket. Thanks
