### ISSUE TITLE
blob backfilling

### ISSUE THREAD

**Issue by kasey** [prysmaticlabs/prysm#13029]
# 🚀 Feature Request

### Description

Implement blob backfilling on top of the block backfilling feature (assumes https://github.com/prysmaticlabs/prysm/pull/12968 is merged)

### Describe the solution you'd like

The simplest solution is for the backfill workers to download blobs for the given blocks after the blocks have been downloaded.

### Describe alternatives you've considered

We could consider backfilling blocks in parallel with blocks, but this would make the backfilling process more complicated. Parallelization becomes much more manageable after we implement https://github.com/prysmaticlabs/prysm/issues/13028.

**Comment by terencechain** [comment]
duplicated #12993
