### ISSUE TITLE
Vulnerability to DOS Attacks During Initial Sync

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13054]
During the initial sync, performing KZG checks after saving blobs to the database exposes our system to a potential Denial of Service (DOS) attack. Peers could intentionally overload the database with malformed or malicious blobs. This vulnerability is also present in regular sync, although the risk is somewhat mitigated compared to the initial sync.

**Comment by kasey** [comment]
This was resolved as part of https://github.com/prysmaticlabs/prysm/pull/13351
