### ISSUE TITLE
Stops syncing randomly

### ISSUE THREAD

**Issue by DarshJainKarpuragaurai** [prysmaticlabs/prysm#13052]
### Describe the bug

I am running a full node for ethereum usign prysm + nethermind on windows pc

when i run prysm using the following command
./prysm.bat beacon-chain --execution-endpoint=http://localhost:8551 --jwt-secret=G:\ethereum\consensus\prysm\jwt-secret 

it starts running and syncing properly with active peers of more than 20

Output -
processing batch of 64 and so on

but after 30 mins each time, the active peers drop to 0 and syncing stops endlessly

I have to manually restart prysm to start syncing again

please help

**Comment by james-prysm** [comment]
There's no error  reported in this. what are you seeing?

**Comment by prestonvanloon** [comment]
We are missing some information here. Please attach the full logs and explain which versions of the software you are running. 

Closing this issue for now.
