### ISSUE TITLE
Check blobs by root return

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13101]
If the returned blobs is different than requested blobs, the node will stuck at DA check

**Comment by nisdas** [comment]
> Now, you can imagine a block with one blob that you are asking for. You cycle through your peers. The first peer you request returns a block with a bad blob. But you will never try to make a second request. Your node is officially stuck until a restart

If a peer provides a bad blob, we would reprocess the block again, no ? I don't see how this would be an issue, as we would be re-requesting blobs in the background. I think our current code is fine, as it remains that we **have** seen the block and it is in our pending queue.
