### ISSUE TITLE
Excessive Blob Causes Data Availability Check to Fail

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13107]
When excessive blobs are present in the database, the data availability check fails. Currently, the database retrieves all blobs based on their root. This behavior is problematic, especially when the block references fewer KZG commitments than the number of blobs retrieved from the database. For instance, if a block references only 4 KZG commitments but the database retrieves 6 blobs (2 being excessive), the DA check will attempt to verify all 6 blob sidecars against the 4 KZG commitments, resulting in a failure.

**Comment by kasey** [comment]
The new filesystem blob api only allows one index to be retrieved at a time, and the DA check works in a totally different way, so this is no longer valid.
