### ISSUE TITLE
Validator is stucked after depositing eth 

### ISSUE THREAD

**Issue by Niet-Pham** [prysmaticlabs/prysm#13105]
### Describe the bug

I'm building my custom network PoS. I created successfully genesis execution node & beacon node. After that I created another execution node and beacon node and ran validator,  it synced with genesis node. Then I deposited for this new beacon node, after a few seconds the validator logs of this is running

### 🔬 Minimal Reproduction

My building network step:
1. Using `prysmctl `to create genesis state: `prysmctl testnet  generate-genesis --fork=capella --num-validators=3 --output-ssz=path/to/genesis.ssz  --chain-config-file=path/to/config.yaml --geth-genesis-json-in=path/to/genesis.json  --geth-genesis-json-out=path/to/genesis.json `
2. run execution node genesis: `geth init --datadir ...` && `geth --networkid=... .....`
3. run beacon node genesis:
4. run validator client: `./prysm.sh validator  --interop-num-validators=3 --interop-start-index=0 --wallet-dir= .... `
After created genesis node, execution node is running
Then I run new node: geth init > run execution > run beacon > validator client. This node is synced with genesis node. Validator logs is: 
![image](https://github.com/prysmaticlabs/prysm/assets/55547523/dc755ca9-e622-46fc-a18e-d9e535fe28f6) (each epoch will 
 repeat log info UNKNOWN_STATUS)
But when I call the deposit function of deposit contract. The validator client log is same like stuck (not repeat log UNKNOWN_STATUS again)

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v4.1.0

**Comment by mattfixme** [comment]
anything update?

**Comment by prestonvanloon** [comment]
Closing this issue. The eth1data voting period is several hours long so you wouldn't see the validator deposit for some time...
