### ISSUE TITLE
Should verify sidecar's blob/proof in BlobAlignsWithBlock

### ISSUE THREAD

**Issue by jtraglia** [prysmaticlabs/prysm#13112]
In [`verify.BlobAlignsWithBlock`](https://github.com/prysmaticlabs/prysm/blob/58cdb29ef3fce7fcf723c81b7970d13cf27104a5/beacon-chain/sync/verify/blob.go#L21) I think it would be a good idea to also verify the sidecar's blob and proof. This function appears to be used during syncing (initial sync & blob sidecars by root). I'm sure this will be checked later (in `IsDataAvailable`), but it could be beneficial to catch issues sooner and downscore bad peers. Without this, I believe it's possible to send a mostly correct sidecar but with an invalid blob/proof. Making this change could also save some unnecessary database writes, like [here](https://github.com/prysmaticlabs/prysm/blob/4809da62cc4fb1770faa9eb25fbd4cf913d27d8c/beacon-chain/sync/rpc_beacon_blocks_by_root.go#L169), when sent invalid sidecars.

**Comment by terencechain** [comment]
Makes sense to me. We are adding a temporary cache before storing blob sidecars to the DB. Let's add a note for this on top
