### ISSUE TITLE
Beacon API endpoint `/eth/v1/beacon/blob_sidecars/` returns error 500 on empty blobs block

### ISSUE THREAD

**Issue by marioevz** [prysmaticlabs/prysm#13134]
### Describe the bug

Beacon API endpoint `/eth/v1/beacon/blob_sidecars/` returns error 500 on an empty-blobs block after Deneb, where it should be returning an empty list instead.

Prysm:
```bash
$ curl https://$DEVNET_USER:$DEVNET_PASS@bn.prysm-geth-1.dencun-devnet-10.ethpandaops.io/eth/v2/beacon/blocks/32141 | jq '.data.message.body.blob_kzg_commitments'
[]
$ curl https://$DEVNET_USER:$DEVNET_PASS@bn.prysm-geth-1.dencun-devnet-10.ethpandaops.io/eth/v1/beacon/blob_sidecars/32141
{"message":"could not retrieve blobs for slot 32141: not found in db","code":500}
```

Lighthouse:
```bash
$ curl https://$DEVNET_USER:$DEVNET_PASS@bn.lighthouse-geth-1.dencun-devnet-10.ethpandaops.io/eth/v1/beacon/blob_sidecars/32141
{"data":[]}
```

This is also intermittently affecting Prysm on hive runs, where most of the blocks do contain blobs, but in the rare case where it does not, the test fails because of this unexpected error.

### Has this worked before in a previous version?

```text
I'm not sure.
```

### 🔬 Minimal Reproduction

Query a Prysm node for `/eth/v1/beacon/blob_sidecars/` on devnet-10 on any slot where there were no blobs included. E.g. slot 32141.

### Error

```text
< HTTP/2 500
< server: nginx/1.25.2
< date: Fri, 27 Oct 2023 20:13:53 GMT
< content-type: application/json
< content-length: 81
< vary: Origin
< strict-transport-security: max-age=31536000
<
* Connection #0 to host bn.prysm-geth-1.dencun-devnet-10.ethpandaops.io left intact
{"message":"could not retrieve blobs for slot 32141: not found in db","code":500}
```
```


### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

Branch `devnet-10`

### Anything else relevant (validator index / public key)?

_No response_

**Comment by terencechain** [comment]
thanks for opening this! we should fix it soon

**Comment by wangwzhou** [comment]
Wondering how about the blob_sidecars response for blocks before Deneb upgrade. Right now, I'm getting `Not Found` 404 error for holesky/mainnet chain blocks, should we also get an empty list instead? @terencechain

**Comment by marioevz** [comment]
> Wondering how about the blob_sidecars response for blocks before Deneb upgrade. Right now, I'm getting `Not Found` 404 error for holesky/mainnet chain blocks, should we also get an empty list instead? @terencechain

I think an empty list pre-deneb would be confusing, because the value is non-existent pre-deneb.

IMO empty list should only appear after deneb fork has happened.
