### ISSUE TITLE
validator metics value have error

### ISSUE THREAD

**Issue by lzdohh** [prysmaticlabs/prysm#13136]
prysm version: v4.0.8
os version: ubuntu18.04
The blocks shown here are 1 success and 1 failure.
[https://beaconcha.in/validator/0x9219e33c919a1bf162a90cc69ce691c49a0b80c9e6cfbc3d7fabf55f4f6fa4fbd38974961efa83db516c96dcb5fa0d13](https://beaconcha.in/validator/0x9219e33c919a1bf162a90cc69ce691c49a0b80c9e6cfbc3d7fabf55f4f6fa4fbd38974961efa83db516c96dcb5fa0d13)
But the values obtained by metrics all failed. How do I fix this problem?

![image](https://uploads.linear.app/f4701061-fce7-4442-919a-4d09f3211ada/bd373610-feef-4dd2-8a71-a4d78fad3f20/9aa7793d-bb07-4014-a9f9-69c58ce6e544?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NzAxMDYxLWZjZTctNDQ0Mi05MTlhLTRkMDlmMzIxMWFkYS9iZDM3MzYxMC1mZWVmLTRkZDItOGE3MS1hNGQ3OGZhZDNmMjAvOWFhNzc5M2QtYmIwNy00MDE0LWE5ZjktNjljNThjZTZlNTQ0IiwiaWF0IjoxNzExMDQ0NTg5LCJleHAiOjMzMjgxNjA0NTg5fQ.mu7BA2ahJDTGECu4HLlNPpOlR7NQ_aiOwI58dtuPGEk "=1330x")

**Comment by prestonvanloon** [comment]
The validator is only aware of the RPC response value of the block submission. If a proposal fails, according to the beacon chain, then this can appear as a failed block proposal. There is a chance that the block proposal was successful and the result was not returned in time. It's not possible to tell what happened from metrics alone without any logs. If you are using mev-boost then that can cause issues here as the MEV actors are playing timing games
