### ISSUE TITLE
what does 'Invalid Eth1 deposit' mean

### ISSUE THREAD

**Issue by garyng2000** [prysmaticlabs/prysm#13133]
### Describe the bug

I am seeing below in the validator log(goerli)

level=warning msg="Invalid Eth1 deposit" prefix=validator pubKey=0xa805ed32dde0 status=INVALID

but not sure what it means or it should be a concern ?

The format looks ok to me

https://goerli.beaconcha.in/validator/a805ed32dde0dee522c9a62c267bf68554c2458bd278e40ec2accf1bec9a85db27c1ac044e588c0c2e35525e649418c8#deposits

**Comment by garyng2000** [comment]
is it possible that the deposit MUST BE sent from the same eth1 address if the withdrawal_address if it is an ETH1 address ?

**Comment by prestonvanloon** [comment]
@garyng2000 it is not required to send a deposit from the same eth1 address as the withdrawal_address. Perhaps this deposit was created with the wrong network information? How did you produce an invalid deposit?

**Comment by potuz** [comment]
The most common error for invalid deposits is to have a wrong fork id, the signature then is invalid.

**Comment by garyng2000** [comment]
thanks, and yes it is the fork id, a wrong deposit json(for another network) is used.

**Comment by james-prysm** [comment]
closing this as it seems resolved
