### ISSUE TITLE
Update Builder Flow to Accommodate New Blob Sidecar Format

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13157]
The new blob sidecar format brings about several changes to the builder flow. Validators no longer need to submit blind blob bundles. Instead, they will receive KZG commitments from the builder to put in the block body. Additionally, validators must include an inclusion proof and block header when broadcasting a blob sidecar. This issue aims to track the changes required in the builder flow and the Builder API implementation.

**Comment by james-prysm** [comment]
related to https://github.com/ethereum/builder-specs/pull/90

**Comment by james-prysm** [comment]
PR merged in
