### ISSUE TITLE
Update Proposer RPC, Validator Client, and Remove Obsolete Signing Code Due to New Blob Sidecar Format

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13155]
With the new blob sidecar format and the removal of signed blob sidecars, multiple components of the system require updating. This includes proposer RPC endpoints (which are responsible for inclusion proof generation and usage), the validator client, and the removal of outdated signing code, such as web3signing. This issue aims to track all the related work.

**Comment by yawayl** [comment]
is this marking .\
