### ISSUE TITLE
Optimize Gossip Validations with Blob Inclusion Header Signature

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13154]
With the introduction of blob inclusion proof and new format of blob sidecar, the process of gossip validations across blob sidecar(s) and beacon block has become more efficient. Specifically, we now only have to verify a single signature. This issue aims to track the work related to these optimizations.

**Comment by kasey** [comment]
groundwork for this was laid here https://github.com/prysmaticlabs/prysm/pull/13245
and I believe it will be wired into gossip here https://github.com/prysmaticlabs/prysm/pull/13294

Note that this will cache signature verification amongst the blobs, but to also share the cache with blocks, we need to add a `verification.BlockVerifier` and use that in place of block gossip validation code.
