### ISSUE TITLE
`/eth/v1/node/version` no longer present

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#13176]
### Describe the bug

This endpoint now returns a 404.

### Has this worked before in a previous version?

```text
Yes.
```

### 🔬 Minimal Reproduction

Previous version:

```
curl -s http://localhost:3500/eth/v1/node/version && echo ''
{"data":{"version":"prysm/v4.0.7 (linux amd64)"}}
```

Current version (4.1.1):

```
curl -s http://localhost:3500/eth/v1/node/version
404 page not found
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

4.1.1

**Comment by mcdee** [comment]
This one is a bit odd; different nodes on 4.1.1 give different responses.  Here is a different error:

```
curl -s http://localhost:3500/eth/v1/node/version
{"message":"could not unmarshal error: invalid character 'p' after top-level value","code":500}
```

And yet another gives a good response:

```
curl -s http://localhost:3500/eth/v1/node/version
{"data":{"version":"prysm/v4.1.1 (linux amd64)"}}
```

All of the nodes give the same response to `/eth/v1/node/syncing` and appear to be happily synced.

**Comment by rkapka** [comment]
Hi @mcdee , this is something I was not able to reproduce. Could it be that the endpoint is queried just after restarting a node? Maybe the HTTP server is not available yet when the endpoint is executed.

**Comment by mcdee** [comment]
No, pyrsm had been up and running for a while and, as mentioned, `/eth/v1/node/syncing` worked and returned information.

We reverted to an earlier version so don't have it available for further testing.

**Comment by james-prysm** [comment]
Also tried reproducing haven't seen it yet
