### ISSUE TITLE
Dependency conflict with go-libp2p library

### ISSUE THREAD

**Issue by wangwzhou** [prysmaticlabs/prysm#13206]
### Describe the bug

I have `prysmaticlabs/prysm/v4@v4.1.0` imported in my service. However when I try to upgrade its dependency `libp2p/go-libp2p` to a recent version `v0.30.0` in my service as well, it starts to complain about

```
github.com/prysmaticlabs/prysm/v4/beacon-chain/rpc/eth/shared imports
github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain imports
github.com/prysmaticlabs/prysm/v4/beacon-chain/p2p imports
github.com/libp2p/go-libp2p/p2p/muxer/mplex: module github.com/libp2p/go-libp2p@latest found (v0.32.1), but does not contain package github.com/libp2p/go-libp2p/p2p/muxer/mplex
```

Check the `Removal of mplex` in [go-libp2p](https://github.com/libp2p/go-libp2p) V0.30.0 Release https://github.com/libp2p/go-libp2p/releases/tag/v0.30.0

### Has this worked before in a previous version?

```text
It works when I use `libp2p/go-libp2p=v0.27.8` whose version is the same as in `prysmaticlabs/prysm/v4@v4.1.0`
```

### What version of Prysm are you running? (Which release)

v4.1.0

**Comment by prestonvanloon** [comment]
Updating libp2p is often a non-trivial amount of work due to consistently breaking change in their library. A pull request to upgrade libp2p is welcome. Otherwise, I'm not sure when we will have time to upgrade.
