### ISSUE TITLE
Design and Implement Beacon Operations Pool

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1323]
After speaking with @prestonvanloon, we both realized there's a need for a beacon transaction pool (in beacon node or in validator client) which stores the following beacon block body objects. A generic implementation (i.e. any struct that implements a specific interface can be pooled with the generic implementation) makes sense and may be helpful for reusability 

```
{
    'proposer_slashings': [ProposerSlashing],
    'casper_slashings': [CasperSlashing],
    'attestations': [Attestation],
    'custody_reseeds': [CustodyReseed],
    'custody_challenges': [CustodyChallenge],
    'custody_responses': [CustodyResponse],
    'deposits': [Deposit],
    'exits': [Exit],
}
```

**Comment by terenc3t** [comment]
tentatively assigning this to Preston since he is working on validator client.

**Comment by prestonvanloon** [comment]
Is this related to #1438?

**Comment by terenc3t** [comment]
Yeah it is. My bad for creating the duplicated. I'm going to delete #1438 and let's use this to track further progress
