### ISSUE TITLE
Testnet Setup: Connectivity Issues Between Prysm and Geth Nodes on Different Droplets

### ISSUE THREAD

**Issue by Gopal-Gurram** [prysmaticlabs/prysm#13248]
Hellooo! 😄

I have created the testnet blockchain using the prysm and geth.

Machine 1: Running execution client bootnode. 
Machine 2: Running Node 1 (execution client configured to use bootnode from Machine 1 / consensus client with no bootnode)
Machine 3: Running Node 2 (execution client configured to use bootnode from Machine 1 / consensus client configured to use Machine 2's consensus client as bootnode).

All nodes have the same genesis.

but here two nodes from different machines are not connecting to each other, they will connect to the same droplet.

Below are two files that are creating the nodes :

prepare.sh: It is for the node-0
createNode.sh: it is for the node-1

[createNode.txt](https://github.com/prysmaticlabs/prysm/files/13524878/createNode.txt)
[prepare.txt](https://github.com/prysmaticlabs/prysm/files/13524879/prepare.txt)

**Comment by rupamharod1** [comment]
hello ,
i am also facing same issue. I am running different nodes on different machine my machine are also not connecting to each other

**Comment by prestonvanloon** [comment]
You have `--execution-endpoint` set to localhost so that won't work if the nodes are not on the same host. Set the flag value to the appropriate address and it should work.
