### ISSUE TITLE
Metric of the beacon node in use by the validator client

### ISSUE THREAD

**Issue by jacquesvcritien** [prysmaticlabs/prysm#13264]
# 🚀 Feature Request

### Description

When running validator clients, we often pass in multiple consensus layer endpoints for robustness. However, it is not easy debugging when there are issues with proposals or attestations. Would it be possible to add a Prometheus metric indicating the consensus layer being used? This would help us identify the consensus layer likely to be causing issues at a particular time.

### Describe the solution you'd like

Have a Prometheus metric indicating he consensus layer node endpoint being used by the validator client

**Comment by prestonvanloon** [comment]
@jacquesvcritien Thanks for the feature request. Could you explain how you are adding multiple consensus layer endpoints to the validator client? I would like to understand the flags you are using so we can replicate that setup to test this feature.

**Comment by james-prysm** [comment]
I think this is a related issue that hasn't been addressed yet https://github.com/prysmaticlabs/prysm/issues/10147

**Comment by prestonvanloon** [comment]
Closing old issues. Please reply or file a new issue if this is still relevant.
