### ISSUE TITLE
A "BUILD.bazel" file missing in master branch

### ISSUE THREAD

**Issue by zhaochonghe** [prysmaticlabs/prysm#13260]
### Describe the bug

Is the folder "beacon-chain" missing a "BUILD.bazel" file in the master branch? After downloading the master branch, it is failed to compile by using the command "bazel build //beacon-chain --config=release", and the result is as shown in the attached figure. But I can compile the branch "v4.1.1" successfully when there is a "BUILD.bazel" included in the folder "beacon-chain". 
![build](https://github.com/prysmaticlabs/prysm/assets/41711151/61a1a0fd-bb2c-4fa7-a586-7a9811dfb884)

**Comment by prestonvanloon** [comment]
That target has been removed in #13035. 

There was a deprecation warning in place for 2 years. #8540

Update your commands to use `//cmd/beacon-chain` and `//cmd/validator`
