### ISSUE TITLE
Could not download checkpoint-sync data (Holesky testnet)

### ISSUE THREAD

**Issue by Downager** [prysmaticlabs/prysm#13288]
### Describe the bug

I am experiencing an error with prysmctl version 4.1.1 when attempting to download checkpoint data from a beacon node at https://holesky.beaconstate.info. The command results in a fatal error, citing an issue with detecting the chain config for the finalized state.
```
prysmctl checkpoint-sync download --beacon-node-host=https://holesky.beaconstate.info
FATA[0016] Could not download checkpoint-sync data       error="error detecting chain config for finalized state: version=0x04017000 not found in any known fork choice schedule: unable to find requested BeaconChainConfig"
```

**Comment by prestonvanloon** [comment]
@Downager we were missing holesky and sepolia from the default supported configs. #13323 will fix your problem.
