### ISSUE TITLE
Beacon node high CPU usage

### ISSUE THREAD

**Issue by montekki** [prysmaticlabs/prysm#13291]
### Describe the bug

While running a local testnet with a beacon and validator nodes I've noticed really high CPU usages (this is beacon):

<img width="728" alt="Screenshot 2023-12-07 at 14 07 13" src="https://github.com/prysmaticlabs/prysm/assets/56672/d051a1e1-93de-496f-8a76-da9022be3284">

Validator node at the same time:

![image](https://github.com/prysmaticlabs/prysm/assets/56672/b29ab74a-71c6-4a19-8f03-4d3c4e8dab9c)

and this puts the network into the 120% cpu mode which is sort of excessive isn't it? 

Which is kind of frustrating to see when at the same time geth (which is an execution node and AFAIU is supposed to be heavier than the consensus ones) is working under 1% CPU. Is there any reason for such high resource consumption?

### Platform(s)

Mac (Apple Silicon)

### What version of Prysm are you running? (Which release)

Prysm/v4.1.1/bc9151d647e70cf5e0b6dbcee01998c430a96cb5

**Comment by prestonvanloon** [comment]
@montekki thanks so much for the report. Could you explain a bit more about the setup and how to reproduce it?

How many validators are running? What flags are you using?

Regarding your comment about geth using low resources: if there are few execution transactions, then geth would be mostly producing empty blocks which requires little resources. However, the beacon node produces blocks with attestations and these are never empty (unless something is horribly wrong).

In any case, if you could share some reproduction steps, we could profile the beacon-chain to help understand where the CPU resources are spent. 

You could try yourself by running the beacon node with `--pprof` flag and then taking a sample from that running beacon-node like `go tool pprof -http localhost:7070 http://localhost:6060/debug/pprof/profile\?seconds\=30`. You may safely share the resulting pprof.pb.gz here if you like too.

**Comment by montekki** [comment]
Yep sure that is from https://github.com/matter-labs/zksync-era/blob/main/docker-compose.yml which is for the most part https://github.com/OffchainLabs/eth-pos-devnet tuned for our usecase. To run it I would suggest a modified version of `./bin/ci_localnet_up` from the root of the repo:

```bash
#!/usr/bin/env bash

set -e

mkdir -p ./volumes/postgres ./volumes/geth/keystore ./volumes/prysm/beacon ./volumes/prysm/validator
cp ./docker/prysm/config.yml ./volumes/prysm/config.yml
cp ./docker/geth/jwtsecret ./volumes/geth/jwtsecret
cp ./docker/geth/password.sec ./volumes/geth/password.sec
cp ./docker/geth/keystore/UTC--2019-04-06T21-13-27.692266000Z--8a91dc2d28b689474298d91899f0c1baf62cb85b ./volumes/geth/keystore/
docker-compose up -d --wait
```
Which basically just doesn't run ci-specific `runner` profile.

**Comment by nisdas** [comment]
@montekki Maybe you can try removing this flag ?
https://github.com/matter-labs/zksync-era/blob/main/docker-compose.yml#L69
This will cause issues if you are running with a merged network

**Comment by montekki** [comment]
@nisdas same

**Comment by prestonvanloon** [comment]
Is this still an issue in v5?

**Comment by montekki** [comment]
@prestonvanloon unfortunately I can't tell, we've completely replaced `geth`+`prysm` stack with `reth`. If you can't repro you should close this issue probably
