### ISSUE TITLE
Provider detected DDOS on port 13000 

### ISSUE THREAD

**Issue by michaelr524** [prysmaticlabs/prysm#13310]
# 💎 Issue

We have private ips blocked in the firewall rules.
However, this time it triggered the alert on a public IP.

We've upgraded to the latest version of prysm just in case.
And now looking for a way to make sure this doesn't happen again.
Please help resolve this issue. 

> ##############################################################################
> #      DDoS-Attack detected from host XXX.XX.196.58                          #
> ##############################################################################
>
>
> TIME                                 SRC              ->  DST              SIZE  PROT  SRC-PORT  DST-PORT
> ----------------------------------------------------------------------------------------------------------
> 2023-12-10 02:23:07.025467139 +0000  XXX.XX.196.58    ->  XX.XX.184.18      599   TCP     13000     13000
> 2023-12-10 02:23:07.178939428 +0000  XXX.XX.196.58    ->  XX.XX.184.18      626   TCP     13000     13000
> 2023-12-10 02:23:07.202211167 +0000  XXX.XX.196.58    ->  XX.XX.184.18      637   TCP     13000     13000
> 2023-12-10 02:23:07.325235745 +0000  XXX.XX.196.58    ->  XX.XX.184.18      625   TCP     13000     13000
> 2023-12-10 02:23:07.330941067 +0000  XXX.XX.196.58    ->  XX.XX.184.18      606   TCP     13000     13000
> 2023-12-10 02:23:07.337085624 +0000  XXX.XX.196.58    ->  XX.XX.184.18      596   TCP     13000     13000
> 2023-12-10 02:23:07.343531473 +0000  XXX.XX.196.58    ->  XX.XX.184.18      597   TCP     13000     13000
> 2023-12-10 02:23:07.350754645 +0000  XXX.XX.196.58    ->  XX.XX.184.18      605   TCP     13000     13000
> 2023-12-10 02:23:07.42906235  +0000  XXX.XX.196.58    ->  XX.XX.184.18       52   TCP     13000     13000
> 2023-12-10 02:23:07.778864103 +0000  XXX.XX.196.58    ->  XX.XX.184.18      595   TCP     13000     13000
> 2023-12-10 02:23:07.792440587 +0000  XXX.XX.196.58    ->  XX.XX.184.18      598   TCP     13000     13000
> 2023-12-10 02:23:08.330234693 +0000  XXX.XX.196.58    ->  XX.XX.184.18       52   TCP     13000     13000
> 2023-12-10 02:23:08.337529362 +0000  XXX.XX.196.58    ->  XX.XX.184.18       52   TCP     13000     13000
> 2023-12-10 02:23:08.345178091 +0000  XXX.XX.196.58    ->  XX.XX.184.18       52   TCP     13000     13000
> 2023-12-10 02:23:08.352734321 +0000  XXX.XX.196.58    ->  XX.XX.184.18       52   TCP     13000     13000
>

**Comment by hzysvilla** [comment]
try flag -p2p-denylist=private?

**Comment by michaelr524** [comment]
Thanks @hzysvilla 
Apparently it’s a provider mistake.
They apologized.
I will close the issue.
