### ISSUE TITLE
Clean Up Error Chains

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#1333]
Logging error chains can get incredibly messy, we should spend some time and go through each package to check how errors getting returned. For example, an error printed for unable to process block:

`could not execute state transition unable to process block: could not verify and process block randao: could not verify block randao: expected hashed block randao layers to equal proposer randao: received 0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563 = 0x0000000000000000000000000000000000000000000000000000000000000000`

**Comment by nisdas** [comment]
@terenc3t imo , this is pretty useful as it gives a very descriptive way to pin down the error. Using this I can know exactly calling which method fails and where that method fails at. Maybe we can actually separate errors into Error messages from Debug messages. 

We ouput an error message which basically is one line and a high level overview of what function/method failed.
The debug message after that can contain the detailed error chain.

**Comment by terenc3t** [comment]
@nisdas  But they are all the same errors, I don't mind the chaining, I'm just saying repeating `could not verify block randao` is not very helpful and cosmetic in terms of debugging

**Comment by nisdas** [comment]
@terenc3t ah , k . I get your point. yeah definitely a few places where we have redundant error strings

**Comment by prestonvanloon** [comment]
In some cases, we don't need to format the error before returning it.

**Comment by nisdas** [comment]
@terencechain should we close this ?

**Comment by terencechain** [comment]
Naa, I'd still like to keep this open. We can do a clean sweep after test net to fix all the errors where in some cases we don't need to format the error before returning it.

**Comment by rauljordan** [comment]
Resolved by using `errors.Wrap` throughout our repo in our current master branch
