### ISSUE TITLE
Incorrect entry limit for BlobsBundle is used

### ISSUE THREAD

**Issue by jtraglia** [prysmaticlabs/prysm#13333]
# 💎 Issue

### Background

Regarding the max number of entries in a `BlobsBundle`...

### Description

https://github.com/prysmaticlabs/prysm/blob/c47c52152b1ee953723d571a3b3ab951230c73dd/api/client/builder/types.go#L1022-L1026

I believe the limit here should be `MaxBlobCommitmentsPerBlock`, not `MaxBlobsPerBlock`.

These are the limits in [`BlobsBundle`](https://github.com/ethereum/builder-specs/blob/main/specs/deneb/builder.md#blobsbundle) in the builder specs.

```python
class BlobsBundle(Container):
  commitments: List[KZGCommitment, MAX_BLOB_COMMITMENTS_PER_BLOCK]
  proofs: List[KZGProof, MAX_BLOB_COMMITMENTS_PER_BLOCK]
  blobs: List[Blob, MAX_BLOB_COMMITMENTS_PER_BLOCK]
```

Also, should `MaxBlobsPerBlock` be in `fieldparams`? This is a spec value and will change in the future. I think it should be in `params.config` instead. I'm guessing it's more practical as a constant?

cc @james-prysm

**Comment by james-prysm** [comment]
for the first question, I believe I missed that in reviewing, so I believe we need to update that value.  ( it should not be maxBlobsPerBlock as it represents max blob sidecars and not the byte value length...

> Also, should MaxBlobsPerBlock be in fieldparams? This is a spec value and will change in the future. I think it should be in params.config instead. I'm guessing it's more practical as a constant?

I don't believe I was the one who added it there and would need to give it a bit more thought.

**Comment by kasey** [comment]
`MAX_BLOBS_PER_BLOCK` is a preset, not a param.
https://github.com/ethereum/consensus-specs/blob/dev/presets/mainnet/deneb.yaml#L10
