### ISSUE TITLE
Remove .Get Calls in DB Methods

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1337]
Hi all,

Go best practices dictate not using .Get as the prefix for getter functions, which we use as defaults in our DB package for the beacon chain. A simple PR would deprecate uses of .Get and simply stick to naming such as `db.BlockBySlot`, etc.

**Comment by wildmolasses** [comment]
Hi, I'd be happy to work on this. It'll help me become more familiar with your code base. The only thing I'm confused on is whether to remove the "Get" from test function names as well (`TestGetNilAttestation`, `TestGetBlockBySlotEmptyChain`, etc). I'll submit a PR preserving the test names as they are and will look for feedback there.
