### ISSUE TITLE
Failed to Propose Block

### ISSUE THREAD

**Issue by koloz193** [prysmaticlabs/prysm#13371]
### Describe the bug

i have a full local eth2 setup running as docker containers (geth, prysm beacon, prysm validator). im having trouble sending blob transactions. the error i keep getting is:
``` 
time="2023-12-20 14:19:54" level=error msg="Failed to propose block" blockSlot=42187 error="rpc error: code = Unknown desc = could not process beacon block: could not validate blob data availability: can't verify opening proof" prefix=validator pubKey=0x8dde83069208
```
as output from the validator container. ive verified that i can send blob transactions on devnet12 and that both the cli tool and the container are using the same trusted setup json

### Platform(s)

Mac (Apple Silicon)

### What version of Prysm are you running? (Which release)

4.1.1

**Comment by terencechain** [comment]
you probably want latest prysm release and geth release all together

**Comment by koloz193** [comment]
yup updating from 4.1.1 to latest worked. thanks!
