### ISSUE TITLE
Switch from Big Endian to Small Endian

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1338]
Looks the community has favored using small endian over big endian. Let's update that in our code base: https://github.com/ethereum/eth2.0-specs/pull/139

This applies to SSZ and another potential location is: https://github.com/prysmaticlabs/prysm/blob/master/shared/bytes/bytes.go

**Comment by nisdas** [comment]
This is only for SSZ though, unless you want to apply this across the whole repo ?

**Comment by nisdas** [comment]
I dont know if its the best to apply this across the whole repo.
Ex: Log data from the POW chain stores its integers in big-endian. It can be confusing keeping in mind all these places where it is big-endian. I am leaning towards defaulting to big-endian across our repo excluding SSZ. Afaik there is no where in our repo where we use little endian

**Comment by houjieth** [comment]
Let me fix the ssz part.
