### ISSUE TITLE
some p2p tests fail when port is in use

### ISSUE THREAD

**Issue by wildmolasses** [prysmaticlabs/prysm#1344]
When running my `ipfs daemon`, or when running beacon chain (@prestonvanloon), the following tests fail:

```
//shared/p2p:go_default_test                                             FAILED in 8.7s
  /private/var/tmp/_bazel_ed/eaff1278acd2faea992dee5290fd6552/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/shared/p2p/go_default_test/test.log
//shared/p2p:go_norace_test                                              FAILED in 0.6s
  /private/var/tmp/_bazel_ed/eaff1278acd2faea992dee5290fd6552/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/shared/p2p/go_norace_test/test.log
```

When I exit my ipfs daemon the tests pass. 

@prestonvanloon 's thought from discord:

> Yeah it seems to die if this common port is in use
> Same error if you try to run the tests with a beacon node running
> Some peer count expectations fail
> If you could file a bug, I will look into it but I don’t know if there is anything that can be done because p2p nodes wanna connect to each other
> I wonder if I can sandbox the test from the network :thinking::thinking::thinking:
> That’s probably the answer

**Comment by prestonvanloon** [comment]
More to this: the p2p tests expect there to be no other libp2p peer within discovery. So the tests are creating a libp2p node and inadvertently connecting to the ipfs node. This changes some test expectations with discovery, among other things.

The ideal solution is to execute this test within a network sandbox or some virtual environment.

**Comment by wildmolasses** [comment]
It seems [bazel doesn't support network sandboxing on mac osx](https://github.com/bazelbuild/bazel/issues/2669).

**Comment by prestonvanloon** [comment]
The solution is to add the following tag

```python
tags = ["block-network"],
```

As @wildmolasses, this isn't support on Mac (yet) but would still be an improvement. 
This is blocked by #1524 as tests will fail without a network connection.

**Comment by rauljordan** [comment]
Can this be closed @prestonvanloon ?

**Comment by prestonvanloon** [comment]
Yeah, should be OK
