### ISSUE TITLE
How to request data of a missed slot.

### ISSUE THREAD

**Issue by hyue0768** [prysmaticlabs/prysm#13443]
How to request data of a missed slot? If the slot is missed, the api return `{"message":"Could not find requested block: signed beacon block can't be nil","code":404}`, but I need the detailed data of the missed slot, not 404. 
Thanks!

**Comment by prestonvanloon** [comment]
@hyue0768 What data are you looking for here? If there is no block in that slot, a BlockBySlot request would be a 404.

**Comment by prestonvanloon** [comment]
Closing old issues. If you have more context for the question then we may be able to help. Please reply to this issue or file another one with your specific request or question.
