### ISSUE TITLE
`/eth/v3/validator/blocks/{slot}` not returning execution payload value

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#13466]
### Describe the bug

The endpont `/eth/v3/validator/blocks/{slot}` returns `0` for the execution payload value in both the headers and the returned JSON.

Headers in the response from a request on goerli:

```
Content-Type: application/json
Date: Sun, 14 Jan 2024 17:27:37 GMT
Eth-Consensus-Block-Value: 27063895
Vary: Origin;Origin
Eth-Consensus-Version: capella
Eth-Execution-Payload-Blinded: true
Eth-Execution-Payload-Value: 0
```

And the start of the returned JSON:

```
{"version":"capella","execution_payload_blinded"
:true,"execution_payload_value":"0","consensus_block_value":"27063895","data":{"slot":"7395438",
```

This happens for both blinded and unblinded payloads.

### Has this worked before in a previous version?

```text
No.
```

### 🔬 Minimal Reproduction

Call `/eth/v3/validator/blocks/{slot}` with appropriate parameters.

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

beacon-chain version Prysm/v4.2.0/3a2b486bde28f9b2a02c716782a738c64d62a8e8. Built at: 2024-01-11 01:35:41+00:00

**Comment by james-prysm** [comment]
we're investigating this and we'll have a fix for it soon.
