### ISSUE TITLE
Under some circumstances fee-recipient is not taken into account

### ISSUE THREAD

**Issue by aimxhaisse** [prysmaticlabs/prysm#13469]
### Describe the bug

We observed a case where the `suggested-fee-recipient` on BN /default `fee-recipient` on VC is not always taken into account at the time a beacon is restarted.

### Has this worked before in a previous version?

Unsure as this happens at a high scale/low occurence, it may have been present in previous versions.

### 🔬 Minimal Reproduction

The timeline is as follows:

- VC is configured with an external builder and has a default `fee-recipient` set (non-null address)
- corresponding BN is restarted with a non-null `suggested-fee-recipient`
- VC registers to the beacon, for some reason the external builder errors so that VC/BN have to fallback to local block building
- one of the validator key of the VC has to propose a block during the epoch the BN restart happens
- it proposes a block with `0x000.000` as a fee-recipient

#### Logs

Validator (v4.0):

```
2024-01-11 22:46:14.923	
time="2024-01-11 22:46:14" level=info msg="Submitted new block" blockRoot=0x6efd618dddbb fork=capella gasUtilized=0.9979254666666667 graffiti="..." numAttestations=128 numDeposits=0 parentHash=0x2a26d72119c0 payloadHash=0x64bb1d5637a6 prefix=validator pubKey=0xae675c466327 slot=759231 txCount=33 withdrawalCount=16
```

Beacon (v4.2):

```
time="2024-01-11 22:46:14" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=2.308701105s slot=759231
time="2024-01-11 22:46:14" level=warning msg="could not find tracked proposer index" headRoot=0xacbe38c88a5f2b3607326b372317ce98ed6b431dfcfc635c3855a67f325b71f7 slot=759231 validatorIndex=560809
time="2024-01-11 22:46:14" level=info msg="Finished building block" prefix="rpc/validator" sinceSlotStartTime=2.494683942s slot=759231 validator=560809
```

Looking at the code around the `could not find tracked proposer index` warning, I guess some internal cache with the validator configuration is not filled at this stage (maybe it depends on the validator having attested before?), so it defaults to a default struct with a zeroed fee-recipient.

```
val, tracked := vs.TrackedValidatorsCache.Validator(vIdx)
        if !tracked {
                logrus.WithFields(logFields).Warn("could not find tracked proposer index")
        }

[...]

                attr, err = payloadattribute.New(&enginev1.PayloadAttributesV2{
                        Timestamp:             uint64(t.Unix()),
                        PrevRandao:            random,
                        SuggestedFeeRecipient: val.FeeRecipient[:],
                        Withdrawals:           withdrawals,
                })

```

### Error

This leads to proposing a block with a null fee-recipient, example of such a block: https://holesky.beaconcha.in/slot/759231

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v4.2.0

### Anything else relevant (validator index / public key)?

This happened twice during a restart of about 100K validators on holesky, so fairly confident I can narrow it a bit more if needed.

**Comment by nisdas** [comment]
@aimxhaisse There has been an API change in v4.2.0, so we highly recommend running a v4.2.0 beacon with a v4.2.0 validator client. Otherwise you might run into the edge cases described above: 

From our release notes
```
Upgrading / Downgrading Validators
There are some API changes bundled in this release that require you to upgrade or downgrade in particular order. If the validator is updated before the beacon node, it will see repeated 404 errors at start up until the beacon node is updated as it uses a new API endpoint introduced in v4.2.0.

🔼 Upgrading: Upgrade the beacon node, then the validator.
🔽 Downgrading: Downgrade the validator to v4.1.1 then downgrade the beacon node.

```

**Comment by aimxhaisse** [comment]
Thanks for the quick response, this actually happened during an upgrade following the recommendations (i.e: just after upgrading the beacon to v4.2.0 and before upgrading the validators). I'll try to trigger it with both BN and VC in v4.2.0.

**Comment by aimxhaisse** [comment]
We weren't able to reproduce it so far, marking as closed but may re-open if we see it again.
