### ISSUE TITLE
no enough suitable peers to sync after dencun upgrade in goerli testnet

### ISSUE THREAD

**Issue by wangjiangw** [prysmaticlabs/prysm#13489]
We have been running an Ethereum sync node, and ever since the Goerli testnet Dencun upgrade, we have been experiencing synchronization issues. Below is the error log. Can anyone help provide stable node connections or has anyone encountered a similar problem? Thank you for your assistance in resolving this.

![image](https://github.com/prysmaticlabs/prysm/assets/7013043/9b20375e-14ce-4f2e-865c-a490fb1c1311)

the prysm version is latest : v4.2.0

**Comment by nisdas** [comment]
@wangjiangw Please update to this version for goerli:
https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.0

It should fix your issues

**Comment by wangjiangw** [comment]
> @wangjiangw Please update to this version for goerli: https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.0
> 
> It should fix your issues

i have tried, but still in this situation, i think if most of nodes not to upgrade after dencun cause this problem,

**Comment by Brindrajsinh-Chauhan** [comment]
Is there going to be a different release for Sepolia and Holesky Hardforks?

**Comment by ChrisRut** [comment]
> Is there going to be a different release for Sepolia and Holesky Hardforks?

https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.1

**Comment by prestonvanloon** [comment]
Recent releases have solved the issue.
