### ISSUE TITLE
The beacon cannot synchronize blocks normally and keeps returning errors.

### ISSUE THREAD

**Issue by 0xZonh** [prysmaticlabs/prysm#13483]
### Describe the bug

Today I found that the goerli network was unable to synchronize the latest block. Checking the last synchronization time, it seems to have occurred near 1705473120. The geth version is 1.13.9, and the beacon version is 4.1.1. Considering the possible reasons for the fork, I upgraded geth to 1.13.10 and beacon to 4.2.0, but it seems that the problem has not been solved yet.

The following error message

geth:
`WARN [01-18|08:06:59.106] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!`

prysm:
`14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x023ed0fca3a7cbd109d48676faeeb47e3be6b0200fe01fc88e8b35cc40157e12 (in processBatchedBlocks, slot=7413825)" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xb402dd656bd8e93367c889e882f513c7f63c1e62c346342b4b67e72e075bb32b (in processBatchedBlocks, slot=7413888)" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0xaac2bbd7556c81dcc33083d1f81df7732218cbf0840d92549c2c112a8578dccf (in processBatchedBlocks, slot=7413953)" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x36c289cf06fd828fc1af624f6c424e52ac733b7e81b985936a3cfdd02cdba296 (in processBatchedBlocks, slot=7414016)" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x42187289599e99d86f33c6df8e5f6740fddd7f2886d0d7e3a2cee4cd068e6818 (in processBatchedBlocks, slot=7414080)" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:46" level=warning msg="Skip processing batched blocks" error="beacon node doesn't have a parent in db with root: 0x69096b33b3aece9cdf58c3a4127e5e1b76e2f195d5be24a17d1941da3e80769e (in processBatchedBlocks, slot=7414145)" prefix=initial-sync

14|beacon  | time="2024-01-18 08:07:51" level=info msg="Processing block batch of size 28 starting from  0x92d898cb... 7413760/7421439 - estimated time remaining 45m42s" blocksPerSecond=2.8 peers=27 prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:54" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not validate state root, wanted: 0x0498b3bee228592e79df7c54fa568adbfc463919bf02c35d7990dfe01f71e392, received: 0xcaedd8c6d9dc0162b57b0ddf63f75c43a38c4bdb137516df2288799ff604bade" prefix=initial-sync
14|beacon  | time="2024-01-18 08:07:56" level=info msg="Peer summary" activePeers=27 inbound=0 outbound=27 prefix=p2p`

### What version of Prysm are you running? (Which release)

4.2.0

**Comment by nisdas** [comment]
@0xZonh Please use this version of prysm:
https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.0

You should be able to synchronize goerli again

**Comment by 0xZonh** [comment]
> @0xZonh请使用此版本的 prysm： https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.0
> 
> 你应该可以再次同步goerli

Thank you for your answer. What is the reason why prysm 4.2.0 version cannot synchronize blocks normally?

**Comment by nisdas** [comment]
It has a bug, that is fixed in this PR:
https://github.com/prysmaticlabs/prysm/pull/13477

**Comment by junghyun0783** [comment]
I have the same problem.
If this happens, will I continue to receive the existing data when I receive the new version? Or should I get a new one?
Please help me!!

**Comment by nisdas** [comment]
@junghyun0783 You can just run your node with the new version and you should be fine. The old data will work here

**Comment by junghyun0783** [comment]
@nisdas 
Thank you for your kind reply.

All you have to do is change the 3 files in the dist folder to "4.2.1-rc", right?

However, this is my first time using the patch so I have a question.
Now "beacon-chain-v4.2.0-windows-amd64.exe.sig", "beacon-chain-v4.2.0-windows-amd64.exe.sha256", "beacon-chain-v4.2.0-windows-amd64. I was writing it as "exe"

After renaming 4.2.1-rc to 4.2.0, blocks are now synchronized. So should I always rename it to 4.2.0?
I think there is a config file. Where can I proceed?

**Comment by nisdas** [comment]
@junghyun0783 Are you using `prysm.bat` ? if you are then you can just set this environment variable and run the script again:
```
set USE_PRYSM_VERSION=v4.2.1-rc.0
``
This should allow your node to pick up that version and run it automatically. You don't need to modify filenames anywhere

**Comment by junghyun0783** [comment]
@nisdas 
Thank you for your really kind reply.
Problem solved ^^
This version is a temporary version, right?

**Comment by nisdas** [comment]
@junghyun0783 That is correct, this is only a release candidate. We will have a full release soon

**Comment by prestonvanloon** [comment]
v4.2.1 is released
