### ISSUE TITLE
Should We Store Both Txs and Chunks Inside Collation?

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#135]
I'd like to start an a discussion for the following. In Collation structure, we have`body` and `transactions` fields. 
```go
// Collation base struct.
type Collation struct {
	header *CollationHeader
	// body represents the serialized blob of a collation's transactions.
	// this is a read-only property.
	body []byte
	// transactions serves as a useful slice to store deserialized chunks from the
	// collation's body. Every time this transactions slice is updated, the serialized
	// body would need to be recalculated. This will be a useful property for proposers
	// in our system.
	transactions []*types.Transaction
}
```
`body` stores chunks from serialized `transactions`. Once we serialize `transactions` into chunks and store chunks into `body`, should we store the `transactions` into the collation along side with `body`?  
```go
collation := sharding.NewCollation(header, serializedTxs, txs)
//or 
collation := sharding.NewCollation(header, serializedTxs, nil)
```
The downside is the duplication of transactions in memory footprint, but might be worth it if we are going to be serializing/deserializing very frequently

**Comment by rauljordan** [comment]
My first instinct is that serializing/deserializing frequently will depend on the requirements of proposers and notaries as we build them out. I'd rather assume we will be doing this frequently than not, as it seems easier to refactor and scale down that way.

**Comment by nisdas** [comment]
I would rather we store chunks and transactions in the collation for now. If it does cause any significant performance issues we can always refactor and remove it in the future

**Comment by prestonvanloon** [comment]
The main question to answer here is whether this trade-off makes sense for a production client. 

There are 3 possible combinations of storing collation data in memory:
- Store serialized body and a list of transactions. No serialization/deserialization needed for all usages of a collation
- Store serialized body only. Deserialization necessary to inspect the contents of the collation.
- Store list of transactions only. Serialization necessary when transmitting, saving, or verifying proofs of a collation.

**Comment by nisdas** [comment]
With the changed spec, this issue is outdated, I am closing it
