### ISSUE TITLE
Incorrect eth version on debug fork choice beacon api path

### ISSUE THREAD

**Issue by Savid** [prysmaticlabs/prysm#13500]
### Describe the bug

Looks like [`/eth/v1/debug/fork_choice`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Debug/getDebugForkChoice) was changed to `/eth/v2/debug/fork_choice` in this PR https://github.com/prysmaticlabs/prysm/pull/13164 which differs from the beacon api spec

### Has this worked before in a previous version?

```text
Requesting fork choice on `/eth/v1/debug/fork_choice` with `--enable-debug-rpc-endpoints` gave the correct fork_choice payload

eg.

curl http://localhost:5052/eth/v1/debug/fork_choice
```
```


### 🔬 Minimal Reproduction

Start beacon node with `--enable-debug-rpc-endpoints` and run `curl http://localhost:5052/eth/v2/debug/fork_choice`

### Error

_No response_

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

develop-4e24102 

### Anything else relevant (validator index / public key)?

_No response_

**Comment by james-prysm** [comment]
oops we'll get that fixed, sorry missed from migrations
