### ISSUE TITLE
Is it possible to add validator to devnet that you provide?

### ISSUE THREAD

**Issue by KP-Universe** [prysmaticlabs/prysm#13520]
# 💎 Issue

Actually I made custom devnet following you example from [https://docs.prylabs.network/docs/install/install-with-script](https://docs.prylabs.network/docs/install/install-with-script).
I add new node from another machine but I also want to run validator at this new node.
But I can't find any reference of "adding validator on custom net", "staking to custom net".

If you don't mind can I get any hint of that?

### Background

Context and background information on the discussion...

### Description

**Comment by prestonvanloon** [comment]
Yes, it is possible. We don't have capacity to write out the details for a local devnet. There may be some answers for you here: https://github.com/OffchainLabs/eth-pos-devnet
