### ISSUE TITLE
Debug verbosity generates massive amount of "Deposit registered" (--enable-eip-4881)

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#13548]
When running the beacon with `--verbosity=debug` and `--enable-eip-4881` (in combination with `--force-clear-db`), the logs in the beginning get flooded with: 
`beacon-chain[3185]: time="2024-01-28 09:36:41" level=debug msg="Deposit registered from deposit contract" eth1Block=8475376 merkleTreeIndex=216000 prefix=execution publicKey=0x94e53dd57e8c45bcb7eeaf91a6d19bf3908be7c7f0ddedce14a519e48ceba64bd42c923dcf96fde79c48deea51dd003a`

merkleTreeIndex >230000 and counting.

This is probably too much, even for a debug log.
(Journalctl starts suppressing them also)

### Background
applied parameter `--enable-eip-4881` and `--verbosity=debug`
version: v4.2.1-rc.2

 Context and background information on the discussion...

**Comment by potuz** [comment]
This is only at startup. Having said so, probably that log can be redesigned, deposits registering will change a bit in the next fork
