### ISSUE TITLE
Cannot start prysm

### ISSUE THREAD

**Issue by tjayrush** [prysmaticlabs/prysm#13560]
### Describe the bug

Been running sepolia for many years using Prysm. Today, I did `git pull` and then `git checkout master`. 

Ran the script as always to start prysm. Got this message.

jrush@wildmolasses:~/D/prysm|develop⚡?➤ ./sepolia.sh
Starting local Bazel server and connecting to it...
WARNING: Target pattern parsing failed.
ERROR: Skipping '//beacon-chain': no such package 'beacon-chain': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/jrush/Development/prysm/beacon-chain
WARNING: No targets found to run. Will continue anyway
INFO: Found 0 targets...
ERROR: command succeeded, but there were errors parsing the target pattern
INFO: Elapsed time: 2.669s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

I found a bug with a similar issue, but it was closed without resolution. I'm not sure how to proceed.

### Has this worked before in a previous version?

```text
Yes. For many years. Here's the script I use to start up:


#!/usr/bin/env bash

bazelisk run \
    //beacon-chain -- --sepolia \
    --datadir "/mnt/md0/erigon-sepolia/" \
    --genesis-state "/mnt/md0/erigon-sepolia/genesis.ssz" \
    --jwt-secret "/mnt/md0/erigon-sepolia/jwt.hex"
```
```


### 🔬 Minimal Reproduction

Run above script

### Error

```text
jrush@wildmolasses:~/D/prysm|develop⚡?➤ ./sepolia.sh
Starting local Bazel server and connecting to it...
WARNING: Target pattern parsing failed.
ERROR: Skipping '//beacon-chain': no such package 'beacon-chain': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /home/jrush/Development/prysm/beacon-chain
WARNING: No targets found to run. Will continue anyway
INFO: Found 0 targets...
ERROR: command succeeded, but there were errors parsing the target pattern
INFO: Elapsed time: 2.669s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

latest

### Anything else relevant (validator index / public key)?

Been running for many years.

**Comment by prestonvanloon** [comment]
Sorry about that @tjayrush! We moved the entrypoint to `//cmd/beacon-chain` a few years ago and kept an alias there until recently. You'll need to update your script to use `//cmd/beacon-chain` and, if you run a validator, `//cmd/validator`.
