### ISSUE TITLE
How do I get the inclusion proof a validator balance against specific beacon block root?

### ISSUE THREAD

**Issue by adu-web3** [prysmaticlabs/prysm#13632]
Hellooo! 😄

To help us tend to your issue faster, please search our currently open issues before submitting a new one.
Existing issues often contain information about workarounds, resolution, or progress updates.

💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎💎-->

# 💎 Issue

### Background

I need to verify validator's balance at specific beacon block in EVM, but I don't know how to get merkle proof from beacon chain node because there seems no relative apis supporting fetching inclusion proof of validator fields.

### Description

**Comment by prestonvanloon** [comment]
@adu-web3 you'll want to refer to the ssz merkle proof document: https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md and then generate the proof from the beacon state.

You are correct. There is no API for this and no plan to add it at this time. 

- Get the state ([/eth/v2/debug/beacon/states/{state_id}](https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2)) in ssz format
- Find a tool that can generate merkle proofs for the given ssz object or write your own with the merkle proof doc above.
