### ISSUE TITLE
Does Prysm not support remote execution node connection?

### ISSUE THREAD

**Issue by SipengXie** [prysmaticlabs/prysm#13631]
# 💎 Issue

### Background
I tried to run Prysm and Geth on hosts in different regions and connect them through the network. Geth listens to port 8551 by default. On the two hosts, I used `nc` to listen and access port 8551. It was successful, but when I run Geth and Prysm on each of the two hosts Prysm reports the error: connection refused. I'm pretty sure they both use the same jwtsecret, and the geth is started with `--authrpc.vhosts="*"`

### Description
The error of Prysm:
```
 ERROR execution: Could not connect to execution client endpoint error=Post "http://...:8551": dial tcp ...:8551: connect: connection refused: Post "http://...:8551": dial tcp ...:8551: connect: connection refused
```

**Comment by prestonvanloon** [comment]
@SipengXie Could you please add the flags you are using the version of the software you are running?

To answer your question: Yes, Prysm does support connecting to an execution client on a remote machine.

**Comment by SipengXie** [comment]
geth version 1.13.11-stable-8f7eb9cc
Prysm version is v4.2.1.

Does the server which runs the Prysm needs to open its 8551 port?

**Comment by SipengXie** [comment]
`./prysm.sh beacon-chain --mainnet --datadir $DATADIRPRYSM  --execution-endpoint=http://[geth_ip_addr]:8551 --jwt-secret=$JWT`

`'geth --mainnet  --datadir $DATADIRGETH  --syncmode full --gcmode archive --authrpc.vhosts="*"   --authrpc.jwtsecret=$JWT`

**Comment by prestonvanloon** [comment]
@SipengXie geth binds to the loopback address by default. https://geth.ethereum.org/docs/interacting-with-geth/rpc#http-server

I think you need to add --rpc.host=0.0.0.0 and/or --authrpc.host=0.0.0.0

**Comment by prestonvanloon** [comment]
I just checked my personal deployment, these are my flags:

```
/home/geth/go-ethereum/geth --http --http.addr=0.0.0.0 --http.vhosts=* --authrpc.addr=0.0.0.0 --authrpc.vhosts=* --authrpc.jwtsecret=/home/geth/jwt.hex --http.corsdomain=* --txlookuplimit=10000000 --pprof
```

Notice that you do need to bind to 0.0.0.0 instead of the default. Add `--authrpc.addr=0.0.0.0` to geth to resolve your issue.

**Comment by SipengXie** [comment]
@prestonvanloon well, it's quite embarrassing that the Prysm reports: 
`Could not connect to execution client endpoint error=could not verify execution chain ID as your connection is not authenticated. If connecting to your execution client via HTTP, you will need to set up JWT authentication. See our documentation here https://docs.prylabs.network/docs/execution-node/authentication: 401 Unauthorized: stale token`

I'm pretty sure they use the same jwt.hex. Are there any other flags I should add to the geth or Prysm?

**Comment by prestonvanloon** [comment]
@SipengXie The JWT is only valid for 60 seconds. Here is where geth returns the error:

https://github.com/ethereum/go-ethereum/blob/93c541ad563124e81d125c7ebe78938175229b2e/node/jwt_handler.go#L74

Are your clocks in sync?

**Comment by SipengXie** [comment]
Thank you, I'll try it out.
