### ISSUE TITLE
Trusted Peers Don't Bypass the Connection Gater

### ISSUE THREAD

**Issue by dennis-tra** [prysmaticlabs/prysm#13659]
# 💎 Issue

### Description

I'm running a Geth/Prysm setup and want to dynamically peer new libp2p hosts with Prysm. The idea is to dynamically spin up new hosts that peer with Prysm and participate in the GossipSub mesh to perform some measurements about message propagation.

When starting my custom libp2p nodes they use Prysm's (Beacon) API to register themselves as trusted peers and afterwards establish a P2P connection to it. However, more often than not, Prysm refuses to connect because _I assume_ (haven't fully verified it yet) libp2p's connection gater rejects the connection because Prysm is, e.g., at its max connection capacity.

If this analysis is correct, my expectation of the trusted peer feature would be that the connection would be granted regardless of the peer limit. I can see arguments in favour of the opposite standpoint so I wanted to start a discussion and perhaps get a suggestion what alternative ways exist.

Some complications: in `InterceptAccept` Prysm's/libp2p's ConnectionGater hasn't authenticated the connection yet, which means the peer ID can't be checked against the set of trusted peers at this point. Moving the logic to `InterceptSecured` has security implications in case of a flood of junk connections, I suppose.

**Comment by nisdas** [comment]
So `InterceptAccept` would be unrelated to your problem as that is only relevant for inbound connections/dials. If a peer is marked as a trusted peer, we will consistently be performing outbound dials with them until we have established a connection. If your remote peers are unable to be dialed by the main geth/prysm node pair then there would be some other issue here. However it is hard to diagnose the issue without logs from the remote libp2p hosts.

**Comment by dennis-tra** [comment]
Ah, I see, I didn't know Prysm tries to explicitly dial back! With my current setup Prysm definitely won't reach my peers, so dial-back won't work. However, this is easy to change in my specific case 👍 thanks!
