### ISSUE TITLE
the height of the goerli node we deployed is stuck at height 10641185

### ISSUE THREAD

**Issue by hanzhenlong1314** [prysmaticlabs/prysm#13693]
Hello, the height of the goerli node we deployed is stuck at height 10641185. We have upgraded the version to v1.13.14 and the consensus layer to [https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.0](https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.0), but currently The altitude has not been restored,
the prysm client log:

![image](https://uploads.linear.app/f4701061-fce7-4442-919a-4d09f3211ada/3debbd68-2a74-4960-a502-d4a98185eb46/902fa41b-0a4d-4a00-813b-da96840b8572?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NzAxMDYxLWZjZTctNDQ0Mi05MTlhLTRkMDlmMzIxMWFkYS8zZGViYmQ2OC0yYTc0LTQ5NjAtYTUwMi1kNGE5ODE4NWViNDYvOTAyZmE0MWItMGE0ZC00YTAwLTgxM2ItZGE5Njg0MGI4NTcyIiwiaWF0IjoxNzEwOTY0NDQ3LCJleHAiOjMzMjgxNTI0NDQ3fQ.Z_zCQn-LVWU4AKpDAefHmB8zF3E8SysVseV6EdLR5hE)

the geth client log:

![image](https://uploads.linear.app/f4701061-fce7-4442-919a-4d09f3211ada/5397a36d-2a19-4990-a76c-584abe2be663/ec2ef4f6-5fce-48a3-8134-6a4e0b765d29?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y0NzAxMDYxLWZjZTctNDQ0Mi05MTlhLTRkMDlmMzIxMWFkYS81Mzk3YTM2ZC0yYTE5LTQ5OTAtYTc2Yy01ODRhYmUyYmU2NjMvZWMyZWY0ZjYtNWZjZS00OGEzLTgxMzQtNmE0ZTBiNzY1ZDI5IiwiaWF0IjoxNzEwOTY0NDQ3LCJleHAiOjMzMjgxNTI0NDQ3fQ.EQcdv6wib5S1TKVqE5bYQyrRou-sryHBYRdjO3rHyK4)

**Comment by chichi13** [comment]
Same problem here, impossible to sync the node with prysm v5.0.0 on Goerli:

```bash
2024-03-06 12:53:08.120    
time="2024-03-06 12:53:08" level=info msg="Processing block 0xd8c811d1... 7766016/7768165 - estimated time remaining 5m2s" blocksPerSecond=7.1 peers=70 prefix=initial-sync

2024-03-06 12:53:08.120    
time="2024-03-06 12:53:08" level=info msg="Processing block 0x0909ff3c... 7765984/7768165 - estimated time remaining 5m46s" blocksPerSecond=6.3 peers=70 prefix=initial-sync
2024-03-06 12:53:08.120    
time="2024-03-06 12:53:08" level=info msg="Processing block 0x8861b3e7... 7765888/7768165 - estimated time remaining 11m0s" blocksPerSecond=3.5 peers=70 prefix=initial-sync
2024-03-06 12:53:08.119    
time="2024-03-06 12:53:08" level=info msg="Processing block 0xfb59ab57... 7765760/7768165 - estimated time remaining 13h21m40s" blocksPerSecond=0.1 peers=70 prefix=initial-sync
```

**Comment by nmiceli-simtlix** [comment]
Hi, we are experiencing the same problem as well

```
time="2024-03-06 14:13:39" level=info msg="Processing block 0xfb59ab57... 7765760/7768868 - estimated time remaining 17h16m0s" blocksPerSecond=0.1 peers=28 prefix=initial-sync
time="2024-03-06 14:13:39" level=info msg="Processing block 0x8861b3e7... 7765888/7768868 - estimated time remaining 14m23s" blocksPerSecond=3.5 peers=28 prefix=initial-sync
time="2024-03-06 14:13:49" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:14:03" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:14:13" level=info msg="Peer summary" activePeers=32 inbound=0 outbound=32 prefix=p2p
time="2024-03-06 14:14:17" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:14:31" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:14:45" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:14:59" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:15:08" level=info msg="Processing block 0xfb59ab57... 7765760/7768875 - estimated time remaining 17h18m20s" blocksPerSecond=0.1 peers=39 prefix=initial-sync
time="2024-03-06 14:15:13" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-03-06 14:15:13" level=info msg="Peer summary" activePeers=36 inbound=0 outbound=36 prefix=p2p
time="2024-03-06 14:15:14" level=info msg="Processing block 0x8861b3e7... 7765888/7768876 - estimated time remaining 14m26s" blocksPerSecond=3.5 peers=36 prefix=initial-sync
time="2024-03-06 14:15:27" level=warning msg="Execution client is not syncing" prefix=execution
```

Prysm v5.0.0 | Go-Ethereum v1.13.14

**Comment by drcliche** [comment]
+1

**Comment by junghyun0783** [comment]
me too!

**Comment by junghyun0783** [comment]
@drcliche @nmiceli-simtlix  @chichi13 @hanzhenlong1314 
A new version has been released from prysm.
Please proceed after upgrading to https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.1-rc.3.
Once synchronization is in progress.

**Comment by hanzhenlong1314** [comment]
> @drcliche @nmiceli-simtlix @chichi13 @hanzhenlong1314 A new version has been released from prysm. Please proceed after upgrading to https://github.com/prysmaticlabs/prysm/releases/tag/v5.0.1-rc.3. Once synchronization is in progress.

got it,thanks

**Comment by c0deright** [comment]
+1

Will this bug affect mainnet as soon as the upcoming fork kicks in? Do we need to upgrade our prysm daemons to `v5.0.1-rc.3` or later before the cancun fork?

**Comment by potuz** [comment]
This bug is present in all versions of prysm prior to v5.0.1-rc.3. While this bug is highly unlikely to happen in mainnet (it requires a combination of massive slashings together with ~33% of the network being offline) it is a possibility, that is why the version is a recommended upgrade.

**Comment by prestonvanloon** [comment]
Goerli is being sunset. We believe these issues were resolved, but there are so no good peers left on the network.
