### ISSUE TITLE
Fully supporting Event stream standards

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#13730]
# 💎 Issue

This issue is to track a TODO item from PR: https://github.com/prysmaticlabs/prysm/pull/13563

in the PR we use a simple scanner to process event stream data which can handle `/n/r` or `/n` but not `/r` alone therefore not adhering to the standards defined in https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface on the beacon api https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events
This simple implementation can be used for now as our events endpoint is not fully mainnet ready at the time of this issue. Further improvements and full use of the events endpoint may be needed and can be re-evaluated then.

**Comment by samuel-videau** [comment]
@james-prysm I got this! I'll push a PR.
Basically it just needs a custom split function to be added to the scanner as follow `scanner.Split(scanLinesCarriage)`
Should I add `scanLinesCarriage` function in the same `event_stream.go` file or is there another file I can use for utility functions?
