### ISSUE TITLE
holesky p2p blob error: could not validate blob data availability: context deadline waiting for blob sidecars: context deadline exceeded

### ISSUE THREAD

**Issue by SimonSMH1015** [prysmaticlabs/prysm#13741]
### Describe the bug

holesky prysm logs contains

```time="2024-03-14 00:32:08" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars: context deadline exceeded" prefix=sync topic="/eth2/69ae0e99/beacon_block/ssz_snappy" ```

And then  my node stop getitng  latest beacon blocks in time.
After restarting the node, this error shows again.

### Has this worked before in a previous version?

```text
Never met this berofe. I updated 5.0.1 from 5.0.0 three days ago.
```

### 🔬 Minimal Reproduction

 the beacon node command is

beacon-chain --datadir /workdir/consensus --min-sync-peers 1 --rpc-*.*.*.* --execution-endpoint http://127.0.0.1:8551 --grpc-gateway-host *.*.*.*--p2p-local-ip *.*.*.* --p2p-host-ip *.*.*.* --p2p-tcp-port 30310 --p2p-udp-port 30311 --grpc-gateway-port 3500 --jwt-secret /workdir/execution/jwtsecret --genesis-beacon-api-url http:etc --checkpoint-sync-url http://etc  --peer /ip4/*.*.*.*/tcp/30310/p2p/16Uiu2HAm5DJETH8phZWd6aRmyyFc2b7jW4PqojaWnaD3WmeHtGhe,/ip4/*.*.*.*tcp/30310/p2p/16Uiu2HAmABx4mxt1B7ykpfSZjpCww1bHeY9hAGB1GgWqt2q5YyrJ --p2p-priv-key /workdir/consensus/p2p-priv-key --holesky --disable-eip-4881 --accept-terms-of-use --enable-debug-rpc-endpoints --subscribe-all-subnets --p2p-allowlist private

### Error

```text
="2024-03-14 00:32:08" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars: context deadline exceeded" prefix=sync topic="/eth2/69ae0e99/beacon_block/ssz_snappy"
```

![blobError](https://github.com/prysmaticlabs/prysm/assets/39431803/fd459f2c-d0ca-47d4-b5ce-31d7e197869d)

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.0.1

### Anything else relevant (validator index / public key)?

I also have 5000 validators running remotely connecting to this node.

**Comment by prestonvanloon** [comment]
@terencechain did you receive any additional information on this report?

**Comment by YuXiaoCoder** [comment]
I'm having the same problem.
```log
time="2024-03-24 23:40:36" level=info msg="Synced new block" block=0x17dbf830... epoch=272059 finalizedEpoch=272057 finalizedRoot=0x64c2b443... prefix=blockchain slot=8705901
time="2024-03-24 23:40:36" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x7e3dbbf72650 prefix=blockchain slot=8705901 syncBitsCount=212 txCount=294
time="2024-03-24 23:40:43" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars: context deadline exceeded" prefix=sync topic="/eth2/6a95a1a9/beacon_block/ssz_snappy"
time="2024-03-24 23:40:48" level=info msg="Synced new block" block=0x4e6bc23a... epoch=272059 finalizedEpoch=272057 finalizedRoot=0x64c2b443... prefix=blockchain slot=8705902
time="2024-03-24 23:40:48" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x1c9829e8db19 prefix=blockchain slot=8705902 syncBitsCount=512 txCount=145
```

**Comment by terencechain** [comment]
From the look, this seems okay as we've seen block gossip without blobs. As long as your node stays syncing / not stuck, then it should be fine. Feel free to reopen this if it's not the case, and we'll take a further look.

**Comment by YuXiaoCoder** [comment]
I also encountered another error where I wasn't sure if there was a connection, causing the number of proofs lost to go up
```log
time="2024-03-27 10:50:09" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xad249e3a6fdb committeeIndex=16 error="could not process attestation: epoch 272613 root 0xad249e3a6fdb42e16f84970249f531e27a3a2a18e2fcdc59edb69fba38ad588c: not a checkpoint in forkchoice" prefix=blockchain slot=8723647 targetRoot=0xad249e3a6fdb
time="2024-03-27 10:50:09" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xad249e3a6fdb committeeIndex=26 error="could not process attestation: epoch 272613 root 0xad249e3a6fdb42e16f84970249f531e27a3a2a18e2fcdc59edb69fba38ad588c: not a checkpoint in forkchoice" prefix=blockchain slot=8723644 targetRoot=0xad249e3a6fdb
time="2024-03-27 10:50:09" level=warning msg="Could not process attestation for fork choice" aggregationCount=3 beaconBlockRoot=0xad249e3a6fdb committeeIndex=3 error="could not process attestation: epoch 272613 root 0xad249e3a6fdb42e16f84970249f531e27a3a2a18e2fcdc59edb69fba38ad588c: not a checkpoint in forkchoice" prefix=blockchain slot=8723647 targetRoot=0xad249e3a6fdb
time="2024-03-27 10:50:09" level=warning msg="Could not process attestation for fork choice" aggregationCount=3 beaconBlockRoot=0xad249e3a6fdb committeeIndex=56 error="could not process attestation: epoch 272613 root 0xad249e3a6fdb42e16f84970249f531e27a3a2a18e2fcdc59edb69fba38ad588c: not a checkpoint in forkchoice" prefix=blockchain slot=8723647 targetRoot=0xad249e3a6fdb
time="2024-03-27 10:50:09" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xad249e3a6fdb committeeIndex=11 error="could not process attestation: epoch 272613 root 0xad249e3a6fdb42e16f84970249f531e27a3a2a18e2fcdc59edb69fba38ad588c: not a checkpoint in forkchoice" prefix=blockchain slot=8723647 targetRoot=0xad249e3a6fdb
time="2024-03-27 11:02:57" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xd869de7ffb2d committeeIndex=43 error="could not process attestation: epoch 272615 root 0xd869de7ffb2d39491da321d3add818837a2a40b5ba8e012b5611dbdc2ba13f68: not a checkpoint in forkchoice" prefix=blockchain slot=8723711 targetRoot=0xd869de7ffb2d
time="2024-03-27 11:02:57" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xd869de7ffb2d committeeIndex=34 error="could not process attestation: epoch 272615 root 0xd869de7ffb2d39491da321d3add818837a2a40b5ba8e012b5611dbdc2ba13f68: not a checkpoint in forkchoice" prefix=blockchain slot=8723710 targetRoot=0xd869de7ffb2d
time="2024-03-27 11:02:57" level=warning msg="Could not process attestation for fork choice" aggregationCount=2 beaconBlockRoot=0xd869de7ffb2d committeeIndex=27 error="could not process attestation: epoch 272615 root 0xd869de7ffb2d39491da321d3add818837a2a40b5ba8e012b5611dbdc2ba13f68: not a checkpoint in forkchoice" prefix=blockchain slot=8723711 targetRoot=0xd869de7ffb2d
time="2024-03-27 11:03:07" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars: context deadline exceeded" prefix=sync topic="/eth2/6a95a1a9/beacon_block/ssz_snappy"
```

**Comment by hwhe** [comment]
i meet the same problem. it occur "could not validate blob data availability" error. Can you help identify the probable cause?


`time="2024-04-28 02:59:59" level=info msg="Peer summary" activePeers=2 inbound=2 outbound=0 prefix=p2p
time="2024-04-28 02:58:59" level=info msg="Peer summary" activePeers=2 inbound=2 outbound=0 prefix=p2p
time="2024-04-28 02:57:59" level=info msg="Peer summary" activePeers=2 inbound=2 outbound=0 prefix=p2p
time="2024-04-28 02:57:38" level=error msg="Could not handle p2p pubsub" error="could not validate blob data availability: context deadline waiting for blob sidecars slot: 1528485, BlockRoot: 0x58e28a75f6e597bda0ea5c843975f13c2394ae714357c7b105d852c37774248a: context deadline exceeded" prefix=sync topic="/eth2/69ae0e99/beacon_block/ssz_snappy"
time="2024-04-28 02:57:12" level=error msg="Still waiting for DA check at slot end." blobsExpected=6 blobsWaiting=3 prefix=blockchain root=0x58e28a75f6e597bda0ea5c843975f13c2394ae714357c7b105d852c37774248a slot=1528485
time="2024-04-28 02:56:59" level=info msg="Peer summary" activePeers=2 inbound=2 outbound=0 prefix=p2p
time="2024-04-28 02:56:49" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=6 payloadHash=0x777edc5613ab prefix=blockchain slot=1528484 syncBitsCount=357 txCount=83
time="2024-04-28 02:56:49" level=info msg="Synced new block" block=0xbf97c55c... epoch=47765 finalizedEpoch=47763 finalizedRoot=0xda215c47... prefix=blockchain slot=1528484
time="2024-04-28 02:56:39" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x5658935227e3 prefix=blockchain slot=1528483 syncBitsCount=475 txCount=0
time="2024-04-28 02:56:39" level=info msg="Synced new block" block=0xc3970907... epoch=47765 finalizedEpoch=47763 finalizedRoot=0xda215c47... prefix=blockchain slot=1528483
time="2024-04-28 02:56:26" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x6127fe994f64 prefix=blockchain slot=1528482 syncBitsCount=12 txCount=20
time="2024-04-28 02:56:26" level=info msg="Synced new block" block=0x68cb6676... epoch=47765 finalizedEpoch=47763 finalizedRoot=0xda215c47... prefix=blockchain slot=1528482
time="2024-04-28 02:56:17" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=4 payloadHash=0x90d1ba2b95b2 prefix=blockchain slot=1528481 syncBitsCount=484 txCount=93
time="2024-04-28 02:56:17" level=info msg="Synced new block" block=0x82e7caf1... epoch=47765 finalizedEpoch=47763 finalizedRoot=0xda215c47... prefix=blockchain slot=1528481
time="2024-04-28 02:56:02" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:02" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:02" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500
time="2024-04-28 02:56:01" level=info msg="Updated fee recipient addresses for validator indices" prefix="rpc/validator" validatorCount=500`
