### ISSUE TITLE
Update VerifyCasperVotes to VerifySlashableVoteData

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1375]
VerifyCasperVotes is outdated, we should align them with the spec. See the following references for all the changes that have gone through since:

https://github.com/ethereum/eth2.0-specs/commit/4aa6ec4468e6410bff4a21fddaadba4330212f29
https://github.com/ethereum/eth2.0-specs/commit/ddbd8b70ac5a86b1e92903a77b37443da41e88f0

These mostly name changes, nothing drastic

**Comment by IvanTheGreatDev** [comment]
I'd like to take this!

**Comment by nisdas** [comment]
Sounds good, assigned to @IvanTheGreatDev  :)
