### ISSUE TITLE
can't get /eth/v1/beacon/blob_sidecars 

### ISSUE THREAD

**Issue by CroutonDigital** [prysmaticlabs/prysm#13783]
### Describe the bug

I run prysm node with next arguments: 

```
  ethereum-prysm-node-arbitrum:
    container_name: ethereum-prysm-node-arbitrum
    restart: always
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.0.0
    command: >
      --rpc-host=0.0.0.0
      --rpc-port=4000
      --grpc-gateway-host=0.0.0.0
      --grpc-gateway-port=7500
      --datadir=/root/prysm
      --p2p-host-ip=65.108.201.189
      --p2p-tcp-port=13010
      --p2p-udp-port=12010
      --accept-terms-of-use
      --jwt-secret=/jwtsecret 
      --execution-endpoint=http://ethereum-node:8551
      --checkpoint-sync-url=http://testing.mainnet.beacon-api.nimbus.team
```

But can't get /eth/v1/beacon/blob_sidecars 

### Has this worked before in a previous version?

```text
Never used before
```

### 🔬 Minimal Reproduction

curl http://ethereum-prysm-node-arbitrum:7500/eth/v1/beacon/blob_sidecars/8633650 -H "accept: application/json" 

got 
{"message":"Block not found: block not found: no block roots at slot 8633650","code":404}/ 

### Error

```text
{"message":"Block not found: block not found: no block roots at slot 8633650","code":404}/
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v5.0.0

**Comment by james-prysm** [comment]
the error seems like you don't have teh block for the associated slot, are you using checkpoint sync ? you can try some time later.

**Comment by CroutonDigital** [comment]
Yes, but I have prysm node, without checkpoint sync. Same issue. What you mean try some time later?

**Comment by CroutonDigital** [comment]
Some users have issue with prysm and arbitrum. https://github.com/OffchainLabs/nitro/issues/2191

**Comment by james-prysm** [comment]
will look deeper into it. are there any other logs that would be useful for us? you have tried other slots?

**Comment by CroutonDigital** [comment]
Yes, but no success

**Comment by nisdas** [comment]
Do you know which slot you have checkpoint synced from ? Also is your node fully synced

**Comment by james-prysm** [comment]
checking back in here, any additional info you can provide?

**Comment by 0xARK** [comment]
Hello, I have the same problem. My node is fully synced:
```bash
ubuntu:~$ curl http://localhost:3500/eth/v1/node/syncing
{"data":{"head_slot":"8726804","sync_distance":"0","is_syncing":false,"is_optimistic":false,"el_offline":false}}
```

**Comment by nisdas** [comment]
@0xARK Did you checkpoint sync your node ?

**Comment by 0xARK** [comment]
Hello, yes I used checkpoint sync, here is my startup command:

```
docker run -it -d -v /nvme2/nitro-pruned.tar:/nitro-pruned.tar -v /arbitrum/data:/home/user/.arbitrum -p 9642:9642 -p 43585:8547 -p 43586:8548 \
  --net node-network \
  --ip 172.18.0.7 \
  --name arbitrum-node offchainlabs/nitro-node:v2.3.0-3e14543 \
  --http.addr 0.0.0.0 \
  --ws.addr 0.0.0.0 \
  --ws.origins "*" \
  --graphql.enable \
  --graphql.vhosts "*" \
  --init.url file:///nitro-pruned.tar \
  --parent-chain.connection.url http://172.18.0.5:8545 \
  --parent-chain.blob-client.beacon-url http://172.18.0.6:3500 \
  --chain.id 42161
```

If you want to ask me from which block I synced can you tell me how to check that ?

**Comment by nisdas** [comment]
This is your arbitrum command @0xARK , can you paste your prysm command ?

**Comment by 0xARK** [comment]
Oh sorry, I answered an issue on arbitrum too and assumed I was on arbitrum repo. Here is it, and yes I'm using checkpoint sync:

```
docker run -it -d -v /prysm:/prysm -p 4000:4000 -p 13000:13000 -p 12000:12000/udp \
    --net node-network \
    --ip 172.18.0.6 \
    --name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
    --datadir /prysm/data \
    --jwt-secret /prysm/jwt.hex \
    --rpc-host 0.0.0.0 \
    --grpc-gateway-host 0.0.0.0 \
    --monitoring-host 0.0.0.0 \
    --p2p-host-ip $(sudo curl -s ident.me) \
    --execution-endpoint http://172.18.0.5:8551 \
    --checkpoint-sync-url https://sync.invis.tools \
    --genesis-beacon-api-url https://sync.invis.tools \
    --accept-terms-of-use
```

**Comment by nisdas** [comment]
In that case that is an issue, as you are asking for blobs from  a block before your checkpoint. You can add these 2 flags:
```
--enable-experimental-backfill
```
```
--backfill-oldest-slot=slotToBackfillTill
```

**Comment by 0xARK** [comment]
Ok, I'll try these right now, thanks

**Comment by 0xARK** [comment]
I confirm that it works, only by adding the following line to my startup command:
```
--enable-experimental-backfill=true
```

**Comment by james-prysm** [comment]
I believe this was solved and can close this issue now.
