### ISSUE TITLE
no peers to connected for sepolia testnet after upgrade

### ISSUE THREAD

**Issue by wangjiangw** [prysmaticlabs/prysm#13781]
after cancun upgrade, the nodes we are running are easy to stop syncing, in the logs we found some issues，no enough nodes to connected
![image](https://github.com/prysmaticlabs/prysm/assets/7013043/2c05d8b3-d213-412c-af0a-420f87edae0b)
we have waiting a few days, but never recover.

has anyone known how to fix it ? or any suggestion ?

**Comment by wangjiangw** [comment]
i have fixed it by remove --block-batch-limit flag

**Comment by prestonvanloon** [comment]
Your block-batch-limit may have been too high. The recommended maximum is 64 for Dencun.

**Comment by wangjiangw** [comment]
> Your block-batch-limit may have been too high. The recommended maximum is 64 for Dencun.

@prestonvanloon   but prysm always has no enough peers, for me, the node can not sync after re-start, the log like this ：

![image](https://github.com/prysmaticlabs/prysm/assets/7013043/a652cd47-2ee0-43fb-8157-af5e8cc9e63e)

**Comment by wangjiangw** [comment]
do you have any static peers info ?
