### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wzl521** [prysmaticlabs/prysm#13795]
### Describe the bug

I keep getting the following error while building the Docker image：

consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
#14 ERROR: process "/bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain" did not complete successfully: exit code: 1

Then I located the line of code where the error occurred, as follows：
![image](https://github.com/prysmaticlabs/prysm/assets/63525530/6b9aede9-0294-453e-93bb-a6cad8035dfa)

Conclusion: The package is using a local package, but it keeps trying to download, causing compilation errors. Seeking a solution from experts！

### Error

```text
#14 7.065 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
#14 7.065 	go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
#14 ERROR: process "/bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain" did not complete successfully: exit code: 1
------
 > [builder 4/4] RUN cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain:
6.301 go: downloading github.com/docker/go-units v0.4.0
6.311 go: downloading github.com/godbus/dbus/v5 v5.1.0
6.316 go: downloading github.com/opencontainers/runtime-spec v1.0.2
6.334 go: downloading github.com/go-logr/logr v0.2.1
6.337 go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
6.338 go: downloading github.com/modern-go/reflect2 v1.0.1
6.340 go: downloading github.com/marten-seemann/qtls-go1-18 v0.1.2
6.349 go: downloading sigs.k8s.io/yaml v1.2.0
7.065 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
7.065 	go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
```

### What version of Prysm are you running? (Which release)

5.0.1

**Comment by nisdas** [comment]
Which version of go is this ?

**Comment by wzl521** [comment]
> 这是哪个版本的 go？

go 1.21

**Comment by nisdas** [comment]
```
#14 7.065 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
#14 7.065 	go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
```
Why are you fetch v3 here ?

**Comment by wzl521** [comment]
> ```
> #14 7.065 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
> #14 7.065 	go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
> ```
> 
> Why are you fetch v3 here ?

Previously, I was testing with version 3, but even after switching to version 5, I still encounter the same error.

**Comment by wzl521** [comment]
> ```
> #14 7.065 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata; to add it:
> #14 7.065 	go get github.com/prysmaticlabs/prysm/v3/proto/prysm/v1alpha1/metadata
> ```
> 
> Why are you fetch v3 here ?

this is v5 error: 
#14 11.97 consensus-types/wrapper/metadata.go:6:2: no required module provides package github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1/metadata; to add it:
#14 11.97 	go get github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1/metadata
#14 ERROR: process "/bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain" did not complete successfully: exit code: 1

**Comment by nisdas** [comment]
> https://github.com/prysmaticlabs/prysm/issues/14 11.97 go get github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1/metadata

why are you fetching this in the first place ? can you run from the commit you want, with no local changes and simply run this:
```
/bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain
```

**Comment by wzl521** [comment]
> > #14 11.97 去获取 github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1/metadata
> 
> 你为什么首先要获取这个？您可以从您想要的提交运行，无需进行本地更改，只需运行以下命令：
> 
> ```
> /bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain
> ```

Are you suggesting running this command directly in the editor?

**Comment by wzl521** [comment]
> > #14 11.97 go get github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1/metadata
> 
> why are you fetching this in the first place ? can you run from the commit you want, with no local changes and simply run this:
> 
> ```
> /bin/sh -c cd /prysm && go build -o ./cmd/beacon-chain/beacon-chain ./cmd/beacon-chain
> ```

![image](https://github.com/prysmaticlabs/prysm/assets/63525530/0bdf07a0-3355-477e-86ba-251a1600f431)
Why  is the toolchain highlighted in red？

**Comment by nisdas** [comment]
> Are you suggesting running this command directly in the editor?

I am not sure what you are trying to run, I am just going by your logs. You can ignore the toolchain underlining for now and see if it builds.

**Comment by nisdas** [comment]
It looks like you are running a custom branch of prysm, if that is the case we can't help you much. As far as we know prysm compiles fine for every commit in `develop`

**Comment by nisdas** [comment]
I will be closing this @wzl521 , unless there is a build step that does not work from a commit in `develop` .
