### ISSUE TITLE
Multiple network flags should prevent the BN to start.

### ISSUE THREAD

**Issue by nalepae** [prysmaticlabs/prysm#13801]
### Describe the bug

Let's run the BN with both `--sepolia` and `--holesky` flags, like:

```
bazel run //cmd/beacon-chain --config=release -- --execution-endpoint=http://localhost:8551 --sepolia --jwt-secret /Users/manu/OffchainLabs/ethereum/jwt.hex --checkpoint-sync-url https://sepolia.beaconstate.info --genesis-beacon-api-url https://sepolia.beaconstate.info --accept-terms-of-use --holesky --force-clear-db
```

The BN starts. It should exit on error immediately.

### Has this worked before in a previous version?

Probably not.

Related to: https://github.com/prysmaticlabs/prysm/issues/13799

**Comment by shyam-patel-kira** [comment]
Hey @nalepae, I'd like to contribute to this issue, unsure how can I test a particular change, let's say in `cmd/beacon-chain/main.go`

**Comment by nalepae** [comment]
To run tests with bazel, you can look at [here](https://docs.prylabs.network/docs/contribute/contribution-guidelines#running-bazel-tests).

Also, it is also possible to run test without bazel, and especially to run tests directly in your code editor (ex: VSCode) as usual.

**Comment by shyam-patel-kira** [comment]
I already looked, and I get that I can run it this way, but there are no test case for multiple network/chainId flags, should I create new tests, if yes where should I do that?

**Comment by nalepae** [comment]
For the scope of this ticket, you can, for example, create a test that enable multiple flags, and check that in this case the BN refuses to start.
