### ISSUE TITLE
SSZ spec missing explicit checks container decoding

### ISSUE THREAD

**Issue by ChihChengLiang** [prysmaticlabs/prysm#1383]
Hello 👋 ,

A behavior of deserialization in the SSZ spec has been updated.
To prevent containers to consume ill format bytes. It is required to fail if, after the deserialization, some extra bytes still exists.

See issue https://github.com/ethereum/eth2.0-specs/issues/479

**Comment by terenc3t** [comment]
Thank you @ChihChengLiang for letting us know 🙏 
cc @houjieth
