### ISSUE TITLE
Prysm is sending exited validators to MEV-Boost but should only send active or pending ones

### ISSUE THREAD

**Issue by CertHum-Jim** [prysmaticlabs/prysm#13840]
### Describe the bug

While running Flashbots mev-boost, receiving an error indicating that the builder is sending exited validators, and it is only expecting Active and Pending.

from relays.

### 🔬 Minimal Reproduction

Setup prysm on v5.0.2, mev-boost on v1.7, view logs of mev-boost.

### Error

```text
`mev-boost[3167722]: time="2024-03-30T15:40:35.281Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"not a known validator: 0x80c7db2bc1ea6eca8452930bc95d1f2a23e5593b3caa1c6a0424edb6964e5919b20c7d6847046c7d9a524168a7f212e8\"}\n" method=registerValidator numRegistrations=5 ua=Prysm/v5.0.1/a1a81d1720a0a3b850992d4825d0a023baa8e65a url="https://mainnet-relay.securerpc.com/eth/v1/builder/validators" version=1.7

mev-boost[3167722]: time="2024-03-30T16:03:59.337Z" level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.305586 method=POST path=/eth/v1/builder/validators status=502 version=1.7
`

Note: same error on all relays
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.0.2

### Anything else relevant (validator index / public key)?

This previously happened on nimbus and lighthouse in the below issues and is part of the beacon-API standard which leads me to suggest a prysm issue:

[beacon-APIs#230](https://github.com/ethereum/beacon-APIs/pull/230)
[nimbus-eth2#3961](https://github.com/status-im/nimbus-eth2/issues/3961)
[lighthouse#3465](https://github.com/sigp/lighthouse/issues/3465)

**Comment by james-prysm** [comment]
did you see any logs that mention: `Skipping non-active status key.`

**Comment by CertHum-Jim** [comment]
`  --mainnet \
  --checkpoint-sync-url=https://beaconstate-mainnet.chainsafe.io \
  --genesis-beacon-api-url=https://beaconstate-mainnet.chainsafe.io \
  --execution-endpoint=http://localhost:1234 \
  --jwt-secret=/var/lib/ethereum-data/jwt.hex \
  --grpc-gateway-host=0.0.0.0 \
  --datadir=/var/lib/ethereum-data/consensus/prysm/ \
  --suggested-fee-recipient=some-valid-address \
  --http-mev-relay=http://127.0.0.1:18550 \
  --accept-terms-of-use`
  
  That message is not found in the prysm or mev-boost logs.

**Comment by james-prysm** [comment]
those look good, though wondering if anything with sync may have affected this since it's checkpoint sync.

typically the validator would be filtered and only active, pending activation in the same epoch, and exiting validators would be sent https://github.com/prysmaticlabs/prysm/blob/53fdd2d0623d8d7a89b70b82076630ab20454199/validator/client/validator.go#L1135

perhaps there is an edge case where the validator became exited while the validator believed it was still in exiting status. Will investigate this edge case. If there is any more information that you could provide for the above scenario it will help me in my investigations

**Comment by james-prysm** [comment]
checking back in here if there's any more information that can be provided

**Comment by CertHum-Jim** [comment]
Hi @james-prysm the node is synched and not showing any other unusual behavior. If there's something specific you want me to look for or any different flags to configure, let me know.

I can resynch, too if you think that may resolve the issue. The only other thing of not is that the node is supporting DVT for SSV but I'm not sure if that could impact. Otherwise it's a pretty standard deployment.

**Comment by james-prysm** [comment]
if you restart the validator it "should" possibly get the right state at the beginning. I've seen in the past that for dvt some users have experienced context time outs on registering validators periodically. if that's the case then the beacon node may have cached a registered validator that was exiting and is now exited. I guess if you can tell me if getting this error was around the same time the validator exited.  + if restarting your validator results in a printout of `Skipping non-active status key.` At first look I think this will be a harder issue to debug. you could resync but that's only needed if your system thinks the validator is active when it's not, (don't think that's possible)

**Comment by CertHum-Jim** [comment]
This is the first time I've looked at the logs, and it seems the error cleared (in mev-boost) last night:

`Apr 02 19:49:35 -- mev-boost[3167722]: time="2024-04-02T19:49:35.036Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.004225 method=POST pa>
Apr 02 19:49:23 -- mev-boost[3167722]: time="2024-04-02T19:49:23.036Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.004694 method=POST pa>
Apr 02 19:49:11 -- mev-boost[3167722]: time="2024-04-02T19:49:11.034Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.003367 method=POST pa>
Apr 02 19:49:02 -- mev-boost[3167722]: time="2024-04-02T19:49:02.319Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.156887 method=GET path=/et>
Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.491Z" level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.459604 method=POST pa>
Apr 02 19:48:59  mev-boost[3167722]: time="2024-04-02T19:48:59.491Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 40>
Apr 02 19:48:59  mev-boost[3167722]: time="2024-04-02T19:48:59.195Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 40>
Apr 02 19:48:59  mev-boost[3167722]: time="2024-04-02T19:48:59.19Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400>
Apr 02 19:48:59  mev-boost[3167722]: time="2024-04-02T19:48:59.172Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 40>
Apr 02 19:48:59  mev-boost[3167722]: time="2024-04-02T19:48:59.159Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 40`

**Comment by CertHum-Jim** [comment]
This is the first time I've looked at the box in the past day and it seems the error cleared last night (no other intervention. below  are the mev logs: (Apr 02 19:48:59 is when the last 400 appeared)

```Apr 02 19:49:47 -- mev-boost[3167722]: time="2024-04-02T19:49:47.036Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.003927 method=POST path=/eth/v1/builder/validators status=200 version=1.7

Apr 02 19:49:35 -- mev-boost[3167722]: time="2024-04-02T19:49:35.036Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.004225 method=POST path=/eth/v1/builder/validators status=200 version=1.7

Apr 02 19:49:23 -- mev-boost[3167722]: time="2024-04-02T19:49:23.036Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.004694 method=POST path=/eth/v1/builder/validators status=200 version=1.7

Apr 02 19:49:11 -- mev-boost[3167722]: time="2024-04-02T19:49:11.034Z" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.003367 method=POST path=/eth/v1/builder/validators status=200 version=1.7

Apr 02 19:49:02 -- mev-boost[3167722]: time="2024-04-02T19:49:02.319Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.156887 method=GET path=/eth/v1/builder/status status=200 version=1.7

Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.491Z" level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.459604 method=POST path=/eth/v1/builder/validators status=502 version=1.7

Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.491Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"not a known validator: 0x80c7db2bc1ea6eca8452930bc95d1f2a23e5593b3caa1c6a0424edb6964e5919b20c7d6847046c7d9a524168a7f212e8\"}\n" method=registerValidator numRegistrations=5 ua=Prysm/v5.0.2/b3053dc96ad2b89fc66ce44009178a010cd2258d url="https://agnostic-relay.net/eth/v1/builder/validators" version=1.7

Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.195Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"unknown validator\"}\n" method=registerValidator numRegistrations=5 ua=Prysm/v5.0.2/b3053dc96ad2b89fc66ce44009178a010cd2258d url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/validators" version=1.7

Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.19Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"unknown validator\"}\n" method=registerValidator numRegistrations=5 ua=Prysm/v5.0.2/b3053dc96ad2b89fc66ce44009178a010cd2258d url="https://bloxroute.regulated.blxrbdn.com/eth/v1/builder/validators" version=1.7

Apr 02 19:48:59 -- mev-boost[3167722]: time="2024-04-02T19:48:59.172Z" level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"not a known validator: 0x80c7db2bc1ea6eca8452930bc95d1f2a23e5593b3caa1c6a0424edb6964e5919b20c7d6847046c7d9a524168a7f212e8\"}\n" method=registerValidator numRegistrations=5 ua=Prysm/v5.0.2/b3053dc96ad2b89fc66ce44009178a010cd2258d url="https://boost-relay.flashbots.net/eth/v1/builder/validators" version=1.7
```

And here's what happened in the beacon logs at that time:

```Apr 02 19:49:06 -- prysm.sh[3176153]: time="2024-04-02 19:49:06" level=info msg="Peer summary" activePeers=88 inbound=82 outbound=6 prefix=p2p

Apr 02 19:49:01 -- prysm.sh[3176153]: time="2024-04-02 19:49:01" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=6 payloadHash=0x8aab06dea3f1 prefix=blockchain slot=8771943 syncBitsCount=495 txCount=264

Apr 02 19:49:01 -- prysm.sh[3176153]: time="2024-04-02 19:49:01" level=info msg="Synced new block" block=0x3b88aa0e... epoch=274123 finalizedEpoch=274121 finalizedRoot=0xcb8fc604... prefix=blockchain slot=8771943

Apr 02 19:48:59 -- prysm.sh[3176153]: time="2024-04-02 19:48:59" level=info msg="Updated fee recipient addresses" validatorIndices=[788802 788803 785062]

Apr 02 19:48:59 -- prysm.sh[3176153]: time="2024-04-02 19:48:59" level=info msg="Updated fee recipient addresses" validatorIndices=[1046016 1295274 1295289 715977 1188090]

Apr 02 19:48:49 -- prysm.sh[3176153]: time="2024-04-02 19:48:49" level=info msg="Finished applying state transition" attestations=128 kzgCommitmentCount=1 payloadHash=0x5ce4bd3571d4 prefix=blockchain slot=8771942 syncBitsCount=510 txCount=332```

No interventions have been performed. Here's the validator: https://beaconcha.in/validator/80c7db2bc1ea6eca8452930bc95d1f2a23e5593b3caa1c6a0424edb6964e5919b20c7d6847046c7d9a524168a7f212e8#attestations

which was not under control of the dvt operators. weird.

**Comment by james-prysm** [comment]
hmm it's possible there are edge cases where one node has synced and is in exited status ( what the mev relay is seeing) and another ( yours) still thinks the validator is exiting. it's good there's no intervention needed. I will bring this up with my team to see what they think.

**Comment by james-prysm** [comment]
Closing ticket for now as it resolved with no intervention, It is perhaps an edgecase with synced state, please feel free to reopen if it persists, we will keep in mind to improve syncing architecture.
