### ISSUE TITLE
How could I operate "partial (earnings) withdrawals" if my "withdrawal_credentials" begins wiith "01"

### ISSUE THREAD

**Issue by yasyzb** [prysmaticlabs/prysm#13857]
https://docs.prylabs.network/docs/wallet/withdraw-validator
I have read the doc above, it seems available for `withdrawal_credentials` which begins with `00`. 
I generated my `deposit_data-xx.json` by `./deposit new-mnemonic --num_validators=2 --mnemonic_language=english --eth1_withdrawal_address 0xxxx`, and the field `withdrawal_credentials` begins with `01`. So will the earnings auto sent to my `eth1_withdrawal_address`? Or how chould I operate `partial (earnings) withdrawals`?

**Comment by rkapka** [comment]
If your withdrawal credentials begin with `01`, then you will receive withdrawals.
