### ISSUE TITLE
Simulated Backend is Broken with latest State Transition

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1387]
State transition has changed a bit, epoch processing are switching between end of epoch to beginning of epoch. Currently the simulated back end does not work with state transitions after removing shard committees in state and optimized with the latest spec. This might take some time to fix since we have to wait for spec to stabilize, In the mean time, I commented out the skip block test

**Comment by rauljordan** [comment]
Fixed by @nisdas
