### ISSUE TITLE
Use Tree Hashing Algorithm Across the Repo

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1389]
Hi all,

Now that we have SSZ TreeHash functions from #716, we can begin using them in places required by the spec, such as in determining block and state roots throughout the repo. Opening this issue for tracking.

**Comment by houjieth** [comment]
I can take the part where we calculate prev block root. https://github.com/prysmaticlabs/prysm/blob/10b237e72dc2a5f6ed34b7a327ee0b9cebd8cc5d/beacon-chain/blockchain/service.go#L315

**Comment by houjieth** [comment]
It seems like not all field's type generated by protobuf is supported by our ssz library right now (like int32).
I will fix that as part of the PR.
