### ISSUE TITLE
The given withdrawal credentials is already in ETH1_ADDRESS_WITHDRAWAL_PREFIX form. Have you already set the EL (eth1) withdrawal addresss

### ISSUE THREAD

**Issue by yasyzb** [prysmaticlabs/prysm#13930]
# 💎 Issue

### Background

I want to partial withdraw my earning.

### Description

I follow the docs: `https://docs.prylabs.network/docs/wallet/withdraw-validator`, use `generate-bls-to-execution-change`, but it shows: `The given withdrawal credentials is already in ETH1_ADDRESS_WITHDRAWAL_PREFIX form. Have you already set the EL (eth1) withdrawal addresss`.
I check my `credentials` begins with `0x01`, so how should I withdrawal my earnings? thank you.

**Comment by potuz** [comment]
if your withdrawal credentials are already set to start with `0x01` you should be receiving your earnings automatically every few days on the account specified by the withdrawal credentials. I'll close this issue, please reopen it if you need further assistance.
