### ISSUE TITLE
Incompatible with k8s.io/client-go@v0.27.0+

### ISSUE THREAD

**Issue by gg718** [prysmaticlabs/prysm#13958]
One of my other dependencies pulled in a transient update of `k8s.io/client-go` and my code started to fail to compile with the following error:

> `github.com/prysmaticlabs/prysm/v5@v5.0.3/beacon-chain/cache/common.go:10:23: cannot use popProcessNoopFunc (value of type func(_ interface{}) error) as "k8s.io/client-go/tools/cache".PopProcessFunc value in argument to queue.Pop`

Would it be possible to fix this incompatibility?

**Comment by prestonvanloon** [comment]
Please send a PR to update that dependency and we will review it. Thanks

**Comment by shyam-patel-kira** [comment]
Hi @gg718 , do you have any version in mind for this update?
