### ISSUE TITLE
Gometalinter is not able to be run with go-bls

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1395]
Currently if we do bring go-bls into prysm, gometalinter is unable to be run in travis because fetching go-bls results in this error.
```
../go-bls/bls.go:6:29: fatal error: include/mcl/bls.h: No such file or directory
 #include "include/mcl/bls.h"
```
A PR to solve this would allow metalinter to ignore go-bls so that it can run successfully in travis. Related to #1366 .

**Comment by rauljordan** [comment]
Fixed!
