### ISSUE TITLE
Google Container Registry Shutdown

### ISSUE THREAD

**Issue by vineetguptadev** [prysmaticlabs/prysm#13955]
# 💎 Issue

We are seeing a banner / report that google will shutdown the public registry and currently prysm images are housed there. We are unsure from where we would be picking up new updated images. 

Can we please update here as to what the new place would be to consume those images ?
<img width="1566" alt="Screenshot 2024-05-06 at 09 53 41" src="https://github.com/prysmaticlabs/prysm/assets/116307289/1043c810-9f84-4a7c-bcb7-e0bcb0d75a96">

 Context and background information on the discussion...

**Comment by james-prysm** [comment]
> We will move from GCR to Artefact registry but the link will be the same.
from our devops

**Comment by vineetguptadev** [comment]
Thanks @james-prysm so looks like no change required on us to consume these images if URL won't change?

**Comment by Taranpreet26311** [comment]
Nope, it would work same as before. There will be no change required from user's end.

**Comment by james-prysm** [comment]
closing issue for now as I believe no action is needed
