### ISSUE TITLE
Various constants are out of date

### ISSUE THREAD

**Issue by decanus** [prysmaticlabs/prysm#1397]
Various constants are no longer in line with the beacon chain spec.

For example:

- ```BASE_REWARD_QUOTIENT``` is still ```1024``` although it was changed to ```32```
- ```MIN_DEPOSIT_IN_GWEI``` has changed to ```MIN_DEPOSIT```

**Comment by terenc3t** [comment]
Thanks Dean! 🙏🏼

**Comment by terenc3t** [comment]
assigned to @IvanTheGreatDev
