### ISSUE TITLE
Consider Case When ChainID != NetworkID When Signing Transactions

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#14]
On Ethereum Classic, ChainID != NetworkID and the following code would fail when signing the initial contract creation transaction in `vmc.go`:

```
return c.keystore.SignTx(accounts[0], tx, networkID /* chainID */)
```

We currently fetch networkID via the ethclient's NetworkID method, but we should consider situations in which this could break. Keeping it as an open issue for now.

**Comment by prestonvanloon** [comment]
Moving to full production release (diamond)

**Comment by prestonvanloon** [comment]
@rauljordan can you comment why this was closed?

**Comment by rauljordan** [comment]
This should be irrelevant now that we have the beacon chain. There will be no need to have write access to a mainchain node, and no need to consider this case as we will not be signing mainchain transactions.
