### ISSUE TITLE
how to fethc data from network level?

### ISSUE THREAD

**Issue by wzl521** [prysmaticlabs/prysm#14018]
After the Ethereum merge, block broadcasting happens at the consensus layer, right? How exactly is it broadcasted? I want to capture block information from the network layer, that is, not only to get the block information but also the peer nodes from which it was broadcasted. Which part of the code should I look at? Could you please explain this?

**Comment by prestonvanloon** [comment]
Execution layer blocks are broadcasted in the same manner as before the merge.

**Comment by wzl521** [comment]
> 执行层块的广播方式与合并之前相同。
https://tim.mirror.xyz/sR23jU02we6zXRgsF_oTUkttL83S3vyn05vJWnnp-Lc ，But，why the link states, "After the Ethereum merge, block broadcasting was discontinued by the execution client."

**Comment by prestonvanloon** [comment]
OK, that is correct actually. It's part of the BeaconBlock as ExecutionPayload

**Comment by wzl521** [comment]
So, which part of the code should I modify? I need to fetch block and transaction information from the network layer so that I can obtain information from peer nodes.

**Comment by wzl521** [comment]
OK，I have another question. as follows: 
func (s *Service) validateBeaconBlockPubSub(ctx context.Context, pid peer.ID, msg *pubsub.Message) (pubsub.ValidationResult, error) {
	receivedTime := prysmTime.Now()
	// Validation runs on publish (not just subscriptions), so we should approve any message from
	// ourselves.
	//验证在发布时运行（不仅仅是订阅），因此我们应该批准来自我们自己的任何消息。
	//信标区块广播验证
	if pid == s.cfg.p2p.PeerID() {
		return pubsub.ValidationAccept, nil
	}

	// We should not attempt to process blocks until fully synced, but propagation is OK.
	//如果没有完全同步，忽略处理区块
	//在完全同步之前，我们不应该尝试处理块，但传播是可以的。
	if s.cfg.initialSync.Syncing() {
		return pubsub.ValidationIgnore, nil
	}

	ctx, span := trace.StartSpan(ctx, "sync.validateBeaconBlockPubSub")
	defer span.End()

	m, err := s.decodePubsubMessage(msg)
	if err != nil {
		tracing.AnnotateError(span, err)
		return pubsub.ValidationReject, errors.Wrap(err, "Could not decode message")
	}

	s.validateBlockLock.Lock()
	defer s.validateBlockLock.Unlock()

	blk, ok := m.(interfaces.ReadOnlySignedBeaconBlock)

	if !ok {
		return pubsub.ValidationReject, errors.New("msg is not ethpb.ReadOnlySignedBeaconBlock")
	}
	data, ok := m.(interfaces.ExecutionData)
	if !ok {
		return pubsub.ValidationReject, errors.New("msg is not ethpb.ExecutionData")
	}
	transactions, err := data.Transactions()
	log.Info("validateBeaconBlockPubSub,抓取区块信息，区块号为:", data.BlockNumber())

	address, _ := s.cfg.p2p.Peers().Address(pid)
	fromPeerIP := address.String()

	track.EmitTrack(track.BlockBroadcast, time.Now().UnixMilli(), track.BlockBroadcastMessage{
		Number: data.BlockNumber(),
		Hash:   string(data.BlockHash()),
		Propagator: track.Propagator{
			FromPeerId: pid.String(),
			FromPeerIP: fromPeerIP,
			IsHead:     true,
			Timestamp:  int64(data.Timestamp()),
		},
		Header:     " ",
		TxCount:    uint64(len(transactions)),
		UncleCount: 0,
	})

	if blk.IsNil() || blk.Block().IsNil() {
		return pubsub.ValidationReject, errors.New("block.Block is nil")
	}

	graffitiArray := blk.Block().Body().Graffiti()

	log.Info("validateBeaconBlockPubSub,捕获到的slot为：", uint64(blk.Block().Slot()))
	track.EmitTrack(track.BeaconBlockBroadcast, time.Now().UnixMilli(), track.BeaconBlock{
		Slot:      uint64(blk.Block().Slot()),
		Graffiti:  graffitiArray[:],
		BlockHash: blk.Block().Body().Eth1Data().BlockHash,
		Proposer:  uint64(blk.Block().ProposerIndex()),
		FromPeer:  pid.String(),
	})
	log.WithField("blk", "propagation").Infof("slot: %d from : %v", blk.Block().Slot(), pid.String())

	// Broadcast the block on a feed to notify other services in the beacon node
	// of a received block (even if it does not process correctly through a state transition).
	//把信标区块广播出去
	s.cfg.blockNotifier.BlockFeed().Send(&feed.Event{
		Type: blockfeed.ReceivedBlock,
		Data: &blockfeed.ReceivedBlockData{
			SignedBlock: blk,
		},
	})

	if features.Get().EnableSlasher {
		// Feed the block header to slasher if enabled. This action
		// is done in the background to avoid adding more load to this critical code path.
		go func() {
			blockHeader, err := interfaces.SignedBeaconBlockHeaderFromBlockInterface(blk)
			if err != nil {
				log.WithError(err).WithField("blockSlot", blk.Block().Slot()).Warn("Could not extract block header")
				return
			}
			s.cfg.slasherBlockHeadersFeed.Send(blockHeader)
		}()
	}

	if err := validateDenebBeaconBlock(blk.Block()); err != nil {
		return pubsub.ValidationReject, err
	}

	// Verify the block is the first block received for the proposer for the slot.
	//验证该块是否是插槽提议者收到的第一个块。
	if s.hasSeenBlockIndexSlot(blk.Block().Slot(), blk.Block().ProposerIndex()) {
		return pubsub.ValidationIgnore, nil
	}

	blockRoot, err := blk.Block().HashTreeRoot()
	if err != nil {
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Ignored block")
		return pubsub.ValidationIgnore, nil
	}
	if s.cfg.beaconDB.HasBlock(ctx, blockRoot) {
		return pubsub.ValidationIgnore, nil
	}
	// Check if parent is a bad block and then reject the block.
	if s.hasBadBlock(blk.Block().ParentRoot()) {
		s.setBadBlock(ctx, blockRoot)
		err := fmt.Errorf("received block with root %#x that has an invalid parent %#x", blockRoot, blk.Block().ParentRoot())
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Received block with an invalid parent")
		return pubsub.ValidationReject, err
	}

	s.pendingQueueLock.RLock()
	if s.seenPendingBlocks[blockRoot] {
		s.pendingQueueLock.RUnlock()
		return pubsub.ValidationIgnore, nil
	}
	s.pendingQueueLock.RUnlock()

	// Be lenient in handling early blocks. Instead of discarding blocks arriving later than
	// MAXIMUM_GOSSIP_CLOCK_DISPARITY in future, we tolerate blocks arriving at max two slots
	// earlier (SECONDS_PER_SLOT * 2 seconds). Queue such blocks and process them at the right slot.
	genesisTime := uint64(s.cfg.clock.GenesisTime().Unix())
	if err := slots.VerifyTime(genesisTime, blk.Block().Slot(), earlyBlockProcessingTolerance); err != nil {
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Ignored block: could not verify slot time")
		return pubsub.ValidationIgnore, nil
	}

	// Add metrics for block arrival time subtracts slot start time.
	if err := captureArrivalTimeMetric(genesisTime, blk.Block().Slot()); err != nil {
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Ignored block: could not capture arrival time metric")
		return pubsub.ValidationIgnore, nil
	}

	cp := s.cfg.chain.FinalizedCheckpt()
	startSlot, err := slots.EpochStart(cp.Epoch)
	if err != nil {
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Ignored block: could not calculate epoch start slot")
		return pubsub.ValidationIgnore, nil
	}
	if startSlot >= blk.Block().Slot() {
		err := fmt.Errorf("finalized slot %d greater or equal to block slot %d", startSlot, blk.Block().Slot())
		log.WithFields(getBlockFields(blk)).Debug(err)
		return pubsub.ValidationIgnore, err
	}

	// Process the block if the clock jitter is less than MAXIMUM_GOSSIP_CLOCK_DISPARITY.
	// Otherwise queue it for processing in the right slot.
	if isBlockQueueable(genesisTime, blk.Block().Slot(), receivedTime) {
		if res, err := s.verifyPendingBlockSignature(ctx, blk, blockRoot); err != nil {
			log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not verify block signature")
			return res, err
		}
		s.pendingQueueLock.Lock()
		if err := s.insertBlockToPendingQueue(blk.Block().Slot(), blk, blockRoot); err != nil {
			s.pendingQueueLock.Unlock()
			log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not insert block to pending queue")
			return pubsub.ValidationIgnore, err
		}
		s.pendingQueueLock.Unlock()
		err := fmt.Errorf("early block, with current slot %d < block slot %d", s.cfg.clock.CurrentSlot(), blk.Block().Slot())
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not process early block")
		return pubsub.ValidationIgnore, err
	}

	// Handle block when the parent is unknown.
	if !s.cfg.chain.HasBlock(ctx, blk.Block().ParentRoot()) {
		if res, err := s.verifyPendingBlockSignature(ctx, blk, blockRoot); err != nil {
			log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not verify block signature")
			return res, err
		}
		s.pendingQueueLock.Lock()
		if err := s.insertBlockToPendingQueue(blk.Block().Slot(), blk, blockRoot); err != nil {
			s.pendingQueueLock.Unlock()
			log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not insert block to pending queue")
			return pubsub.ValidationIgnore, err
		}
		s.pendingQueueLock.Unlock()
		err := errors.Errorf("unknown parent for block with slot %d and parent root %#x", blk.Block().Slot(), blk.Block().ParentRoot())
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not identify parent for block")
		return pubsub.ValidationIgnore, err
	}

	err = s.validateBeaconBlock(ctx, blk, blockRoot)
	if err != nil {
		// If the parent is optimistic, process the block as usual
		// This also does not penalize a peer which sends optimistic blocks
		if !errors.Is(ErrOptimisticParent, err) {
			log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not validate beacon block")
			return pubsub.ValidationReject, err
		}
	}

	// Record attribute of valid block.
	span.AddAttributes(trace.Int64Attribute("slotInEpoch", int64(blk.Block().Slot()%params.BeaconConfig().SlotsPerEpoch)))
	blkPb, err := blk.Proto()
	if err != nil {
		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not convert beacon block to protobuf type")
		return pubsub.ValidationIgnore, err
	}
	msg.ValidatorData = blkPb // Used in downstream subscriber

	// Log the arrival time of the accepted block
	graffiti := blk.Block().Body().Graffiti()
	startTime, err := slots.ToTime(genesisTime, blk.Block().Slot())
	logFields := logrus.Fields{
		"blockSlot":     blk.Block().Slot(),
		"proposerIndex": blk.Block().ProposerIndex(),
		"graffiti":      string(graffiti[:]),
	}
	if err != nil {
		log.WithError(err).WithFields(logFields).Warn("Received block, could not report timing information.")
		return pubsub.ValidationAccept, nil
	}
	sinceSlotStartTime := receivedTime.Sub(startTime)
	validationTime := prysmTime.Now().Sub(receivedTime)
	logFields["sinceSlotStartTime"] = sinceSlotStartTime
	logFields["validationTime"] = validationTime
	log.WithFields(logFields).Debug("Received block")

	blockArrivalGossipSummary.Observe(float64(sinceSlotStartTime.Milliseconds()))
	blockVerificationGossipSummary.Observe(float64(validationTime.Milliseconds()))
	return pubsub.ValidationAccept, nil
}
Does the above code only perform block validation processing after the execution layer has finished syncing?

**Comment by prestonvanloon** [comment]
> Does the above code only perform block validation processing after the execution layer has finished syncing?

Yes. It does it before, after, and during the execution layer syncing

**Comment by wzl521** [comment]
Then why can't this code fetch any information after I start the execution layer?
track.EmitTrack(track.BlockBroadcast, time.Now().UnixMilli(), track.BlockBroadcastMessage{
	Number: data.BlockNumber(),
	Hash:   string(data.BlockHash()),
	Propagator: track.Propagator{
		FromPeerId: pid.String(),
		FromPeerIP: fromPeerIP,
		IsHead:     true,
		Timestamp:  int64(data.Timestamp()),
	},
	Header:     " ",
	TxCount:    uint64(len(transactions)),
	UncleCount: 0,
})

**Comment by prestonvanloon** [comment]
> Then why can't this code fetch any information after I start the execution layer?

I dont know. I am not able to help you further on this issue.

**Comment by wzl521** [comment]
ok，How can I make block synchronization faster? I've been using checkpoint sync but it always lags behind by 600 blocks.
