### ISSUE TITLE
I've been syncing Ethereum for three days, and it still hasn't completed！

### ISSUE THREAD

**Issue by wzl521** [prysmaticlabs/prysm#14034]
INFO [05-22|01:54:18.242] Syncing: state healing in progress       accounts=3298@174.27KiB slots=1780@139.70KiB codes=1046@7.68MiB nodes=7,292,767@1.82GiB pending=45090
INFO [05-22|01:54:19.777] add outbound peer to static node         peer=e96665f160737b00 err="read tcp 172.19.0.9:44312->131.153.232.43:30330: read: connection reset by peer"
INFO [05-22|01:54:19.777] "删除p2p节点"                        peercount=2  id=e96665f160737b00 duration=2.999s      req=false inbound=false err="read tcp 172.19.0.9:44312->131.153.232.43:30330: read: connection reset by peer"
INFO [05-22|01:54:21.536] Syncing: chain download in progress      synced=100.00% chain=752.34GiB headers=19,921,892@9.28GiB bodies=19,921,827@551.97GiB receipts=19,921,827@191.09GiB eta=2m27.589s
INFO [05-22|01:54:21.910] Adding p2p peer                          peercount=3  id=0dfa787492482194 conn=staticdial addr=107.201.231.252:31404 name=Nethermind/v1.26.0+0...

"It keeps displaying the above logs. What could be the issue?"

**Comment by james-prysm** [comment]
you could checkpoint sync https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync

**Comment by prestonvanloon** [comment]
These logs are from the execution client and it says it is doing a state
heal. This doesn't seem like a Prysm issue based on the information
provided.

**Comment by prestonvanloon** [comment]
Closing since we do not have any information to work from here. The logs above are from go-ethereum. 

See https://github.com/ethereum/go-ethereum/issues/29524
