### ISSUE TITLE
beacon-chain  invalid memory addreses or nil pointer dereference

### ISSUE THREAD

**Issue by qymlyl** [prysmaticlabs/prysm#14061]
### Describe the bug

When blobscan obtains a non-existent blob, prysm reports a null pointer exception

## blobscan send request to beacon-chain
![image](https://github.com/prysmaticlabs/prysm/assets/61776278/35bac039-d9cc-4219-8e94-d2b7114e6e3a)

## beacon-chain error
![image](https://github.com/prysmaticlabs/prysm/assets/61776278/7d29723a-0b3e-4f34-a1b8-16575c11d371)

### Has this worked before in a previous version?

```text
Unverified
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

use doceker, gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-2f2152

**Comment by james-prysm** [comment]
shouldn't be an issue in previous versions but thanks for the report we'll get this fixed

**Comment by james-prysm** [comment]
merged to fix develop, should be fixed there, and 5.0.3 should still be ok.
