### ISSUE TITLE
"Unrecognized option" when I execute "bazel run" 

### ISSUE THREAD

**Issue by daniel5713** [prysmaticlabs/prysm#14071]
# 💎 Issue
The command:  bazel run //cmd/beacon-chain --config=release --execution-endpoint=http://localhost:8551 --mainnet --jwt-secret=/tmp/jwtsecret

ERROR: --execution-endpoint=http://localhost:8551 :: Unrecognized option: --execution-endpoint=http://localhost:8551

What is the correct command to use "bazel run" to start prysm and connect with execution client? 

Thanks in advance!

**Comment by prestonvanloon** [comment]
Yes, that is correct. The bazel flags must be terminated by `--` before starting prysm's flags.

```
bazel run //cmd/beacon-chain $BAZEL_FLAGS -- $PRYSM_FLAGS
```

**Comment by daniel5713** [comment]
Thanks! It works.

Please update the related command in this webpage if you can.

https://docs.prylabs.network/docs/install/install-with-bazel

**Comment by prestonvanloon** [comment]
@daniel5713 thanks, fixing here https://github.com/prysmaticlabs/documentation/pull/943
