### ISSUE TITLE
Add version tag for the prysmctl docker image

### ISSUE THREAD

**Issue by islishude** [prysmaticlabs/prysm#14090]
prysmctl docker image only has latest tag.

I'm using `prysmctl testnet generate-genesis` to create a local develop network.

the latest commits have electra fork configurations, and I have to add them to the config file.

```
ELECTRA_FORK_VERSION
ELECTRA_FORK_EPOCH
```

please add version tag for it.

**Comment by prestonvanloon** [comment]
I'll add this to the release workflow for the next release.

Are there any prior releases that you need tagged?

**Comment by islishude** [comment]
> Are there any prior releases that you need tagged?

Thanks, please add `5.0.3`

**Comment by prestonvanloon** [comment]
@islishude I rebuilt for v5.0.3 and tagged.

gcr.io/prysmaticlabs/prysm/cmd/prysmctl@sha256:358bd6b0c41038334873aee205069ce422e7a0ad60548759e4ee65760a02780b

Future releases will be tagged for prysmctl
