### ISSUE TITLE
prysm client unable to start beacon node: Error retrieving checkpoint origin state and block: error requesting state by id = finalized: error reading http response body: unexpected EOF

### ISSUE THREAD

**Issue by xiaozhejesse** [prysmaticlabs/prysm#14113]
### Background

Try to set up prysm client for mainnet fullnode

### Description
command line:
./prysm.sh beacon-chain  --accept-terms-of-use --execution-endpoint=http://localhost:8551 --jwt-secret=/ethfn/jwt/jwt.hex --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info  --datadir /ethfn/consensus/data

log output:
nohup: ignoring input
Latest Prysm version is v5.0.3.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v5.0.3-linux-amd64: OK
gpg: Signature made Thu 04 Apr 2024 08:07:39 PM UTC
gpg:                using RSA key 
gpg: Good signature from "Preston Van Loon <preston@pvl.dev>" [unknown]
gpg:                 aka "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg:                 aka "Preston Van Loon <preston90@gmail.com>" [unknown]
gpg:                 aka "Preston Van Loon (0xf71E9C766Cdf169eDFbE2749490943C1DC6b8A55) <preston@machinepowered.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 
Verified /ethfn/consensus/prysm/dist/beacon-chain-v5.0.3-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --accept-terms-of-use --execution-endpoint=http://localhost:8551 --jwt-secret=/ethfn/jwt/jwt.hex --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info --datadir /ethfn/consensus/data --force-clear-db
time="2024-06-16 02:29:14" level=info msg="Finished reading JWT secret from /ethfn/jwt/jwt.hex" prefix=execution
time="2024-06-16 02:29:14" level=info msg="Running on Ethereum Mainnet" prefix=flags
time="2024-06-16 02:29:14" level=warning msg="In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. Please see our documentation for more information on this requirement (https://docs.prylabs.network/docs/execution-node/fee-recipient)." prefix=node
time="2024-06-16 02:29:14" level=info msg="Checking DB" databasePath="/ethfn/consensus/data/beaconchaindata" prefix=node
time="2024-06-16 02:29:14" level=info msg="Opening Bolt DB" path="/ethfn/consensus/data/beaconchaindata/beaconchain.db" prefix=db
time="2024-06-16 02:29:14" level=warning msg="Removing database" prefix=node
time="2024-06-16 02:29:14" level=info msg="Opening Bolt DB" path="/ethfn/consensus/data/beaconchaindata/beaconchain.db" prefix=db
time="2024-06-16 02:29:14" level=warning msg="database contains genesis with htr=0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b, ignoring remote genesis state parameter" prefix=genesis
time="2024-06-16 02:50:23" level=fatal msg="unable to start beacon node: could not start modules: could not start DB: Error retrieving checkpoint origin state and block: error requesting state by id = finalized: error reading http response body: unexpected EOF" prefix=main

other info:
I didn't see the port 12000 and 13000 are listening

**Comment by james-prysm** [comment]
looks like there was an issue connecting with the provided checkpoint URL? 
have you tried any other ones for checkpoint sync or if there's just an issue connecting?

**Comment by james-prysm** [comment]
closing as it seems to have resolved itself

**Comment by junghyun0783** [comment]
@xiaozhejesse 
hey~~
Hi, I'm having the same problem.

If it's a network issue,

are you talking about the "--suggested-fee-recipient" issue?
What network is it?
