### ISSUE TITLE
Modify Abigen to Support Vyper

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1416]
Currently Abigen only supports contracts written in solidity, the goal is to also allow contracts written in vyper to also have their go bindings be generated automatically. We generate the bindings by first generating the abi and bytecode from the vyper compiler then using that as inputs into abigen.

For this issue to be closed abigen simply needs to take in a vyper contract source as an argument and use that to generate the bindings.A PR for this will need to be opened in the go-ethereum repository to make the changes. 

Files/Folders that need to be changed to add support for vyper: 

https://github.com/ethereum/go-ethereum/blob/master/cmd/abigen/main.go
https://github.com/ethereum/go-ethereum/tree/master/common/compiler

The first change would be to add support for the vyper compiler under `common/compiler` , and the second change would be to modify the `main` routine in abigen to take in vyper contract source code as an argument so as to output the go bindings.

**Comment by kushagrasharma** [comment]
I'd like to work on this!

**Comment by prestonvanloon** [comment]
Sounds good @kushagrasharma

**Comment by siromivel** [comment]
Should this be closed as it was addressed in https://github.com/ethereum/go-ethereum/pull/19120?

**Comment by nisdas** [comment]
Ah yes it should, thanks @siromivel !
