### ISSUE TITLE
some issues in the ```GetLightClientUpdatesByRange``` function

### ISSUE THREAD

**Issue by rupam-04** [prysmaticlabs/prysm#14170]
# 💎 Issue

### Background

 
I am an EPF5 fellow who has been talking with @rkapka for some while about light clients and he pointed out some errors in the code. Listing them below
### Description

- We don't want to skip the update [here](https://github.com/prysmaticlabs/prysm/blob/a8ecf5d11878324690115c612beefd66ac6386dd/beacon-chain/rpc/eth/light-client/handlers.go#L134)
- In https://github.com/prysmaticlabs/prysm/blob/a8ecf5d11878324690115c612beefd66ac6386dd/beacon-chain/rpc/eth/light-client/handlers.go#L147-#L190 all the places where ```err != nil```, they should be returning ```httputil.HandleError```
- [Here](https://github.com/prysmaticlabs/prysm/blob/a8ecf5d11878324690115c612beefd66ac6386dd/beacon-chain/rpc/eth/light-client/handlers.go#L166) 66% votes are not required, 1 is enough. Also relevant unit tests required to be added

**Comment by rkapka** [comment]
Closing in favor of https://github.com/prysmaticlabs/prysm/issues/12991
