### ISSUE TITLE
Misleading fee recipient used in `payload_attributes` event

### ISSUE THREAD

**Issue by michaelsproul** [prysmaticlabs/prysm#14204]
### Describe the bug

In the SSE `/events` API, Prysm emits a misleading fee recipient in the `payload_attributes` field:

https://github.com/prysmaticlabs/prysm/blob/7c81c7da903884fd34ead687cfcba2ab6848639b/beacon-chain/rpc/eth/events/events.go#L471-L477

This is the fee recipient of the current head block, which would become the _parent_ of a new block built with these payload attributes. It would be incorrect for any consumer of this event stream (e.g. a block builder) to use the fee-recipient provided, because it would pay the block's fees to the proposer of the previous block, rather than the actual proposer!

I think a better solution would be to use the fee recipient of the true proposer, if that proposer is connected locally. In the most common case where they are _not connected_, a dummy value or beacon-node-wide default value could be used. This is the approach we use in Lighthouse.

For consumers of the stream, this makes it clearer that they need to get the proposer's correct fee recipient from elsewhere. Proposers can change their fee recipients between proposals, so the only up-to-date source of this information comes from off-chain, likely from a block relay in the current system.

### Has this worked before in a previous version?

```text
Not sure
```

**Comment by james-prysm** [comment]
agree, it's a bug. will be discussing internally an appropriate solution based on Sproul's suggestion.

that being said for those reading this issue

>  It would be incorrect for any consumer of this event stream (e.g. a block builder) to use the fee-recipient provided, because it would pay the block's fees to the proposer of the previous block, rather than the actual proposer!

please note on the beacon API this comment 
> The fee recipient may also be set via beacon node config, but should likely be ignored by block builders and most other API consumers.

instead, the validator registration fee recipient should be used
