### ISSUE TITLE
Prysm VC ignores `--wallet-dir` tag and uses default path for `auth-token` file

### ISSUE THREAD

**Issue by NeoPlays** [prysmaticlabs/prysm#14217]
### Describe the bug

Sine 5.0.4 the provided `--wallet-dir` flag is ignored by Prysm VC, which uses the default `$HOME/.eth2validators/prysm-wallet-v2` value instead for the generation of the `auth-token` file. 

### Has this worked before in a previous version?

```text
This used to work for 5.0.3
```

### 🔬 Minimal Reproduction

running in a docker container:

```
/app/cmd/validator/validator --accept-terms-of-use=true --web --holesky --datadir=/opt/app/data/db --wallet-dir=/opt/app/data/wallets --wallet-password-file=/opt/app/data/passwords/wallet-password
```

### Error

```text
`time="2024-07-15 08:21:56" level=info msg="Validator Client auth token for gRPC and REST authentication set at /.eth2validators/prysm-wallet-v2/auth-token" prefix=rpc`
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.0.4

**Comment by james-prysm** [comment]
`--keymanager-token-file` please use this flag for setting to a specified location now. this is just to be more consistent with other clients. here is some context https://github.com/ethereum/keymanager-APIs/pull/74

the default of the token previously was the data-dir folder. 

We will be investigating wallet dir consistency overall

**Comment by james-prysm** [comment]
I'll close this issue for now, if anyone else runs into this please refer to the above, will continue working on wallet improvements but won't be included for a few more releases.

**Comment by babakgemini** [comment]
I am getting the same error , I swapped the --wallet-dir with --keymanager-token-file , it generates one line and a totally different format and not JWT token . Was the format changed as well ?

**Comment by babakgemini** [comment]
never mind , saw the format change here 
https://github.com/prysmaticlabs/prysm/commit/feb16ae4aaa41d9bcd066b54b779dcd38fc928d2

https://github.com/ethereum/keymanager-APIs/pull/74/files
