### ISSUE TITLE
Sepolia synchronization suddenly stopped working.

### ISSUE THREAD

**Issue by junghyun0783** [prysmaticlabs/prysm#14210]
### Describe the bug

hello
Ethereum sepolia prysm was running well.
However, recently, Sepolia synchronization suddenly stopped working.

Why does it suddenly not work?
geth version: v1.14.6
prysm version: v5.0.4
I don't think it's a version issue. Is there a problem with the command?

`cmd /k geth --network=sepolia -syncmode "snap" --http.api admin,eth,debug,net,txpool,personal,web3,engine -datadir ".\dataSepolia" -http --http.port 20201 - -http.addr 0.0.0.0 --nat "any" --rpc.allow-unprotected-txs --snapshot=false -ipcdisable --authrpc.jwtsecret ../consensus/jwt_sepolia.hex --authrpc.vhosts="* " --authrpc.addr=0.0.0.0 --lightkdf --cache 16384`

What is the problem?
Experts, please help.

### Has this worked before in a previous version?

```text
yes
```

### 🔬 Minimal Reproduction

geth version: v1.14.6
prysm version: v5.0.4
Set it to .

There is no problem with Ethereum geth.

next
cmd /k geth --network=sepolia -syncmode "snap" --http.api admin,eth,debug,net,txpool,personal,web3,engine -datadir ".\dataSepolia" -http --http.port 20201 - -http.addr 0.0.0.0 --nat "any" --rpc.allow-unprotected-txs --snapshot=false -ipcdisable --authrpc.jwtsecret ../consensus/jwt_sepolia.hex --authrpc.vhosts="* " --authrpc.addr=0.0.0.0 --lightkdf --cache 16384

Run prysm with the command.

### Error

```text
Sepolia synchronization suddenly stopped working.
```

### Platform(s)

Windows (ARM)

### What version of Prysm are you running? (Which release)

5.0.4

### Anything else relevant (validator index / public key)?

yes

**Comment by james-prysm** [comment]
can you share some logs for geth/prysm in this case?

**Comment by junghyun0783** [comment]
@james-prysm 
hello. The issue has now been resolved.
After downgrading the version, I upgraded again.
After removing the "metaData" and "tosaccepted" files and running it, synchronization proceeded.
thank you
