### ISSUE TITLE
Update differences between code and help commands

### ISSUE THREAD

**Issue by peko-hr** [prysmaticlabs/prysm#14275]
## Description
- The actual source code and the behavior of the help command are different and need to be updated to avoid confusion.

https://github.com/prysmaticlabs/prysm/blob/6f7976766d23db64d5680266b542f1b531b07bc6/cmd/beacon-chain/flags/base.go#L23-L26

To make it more friendly, Value should be included.
This should also be reflected in the official documentation.

### 🔬 Minimal Reproduction

1. Build Prysm. (Docker is also acceptable)
2. Show help command
3. Check `max-builder-epoch-missed-slots`

### Platform(s)

Linux (x86), Mac (Apple Silicon)

### What version of Prysm are you running? (Which release)

v5.0.3

**Comment by peko-hr** [comment]
The number to be defined is 5.
Is the number 5 appropriate?

https://github.com/prysmaticlabs/prysm/blob/6f7976766d23db64d5680266b542f1b531b07bc6/config/params/mainnet_config.go#L265

**Comment by aminlatifi** [comment]
@peko-hr it has the "Good First Issue" label, fortunately. I am a new comer like to contribute to this project, may I pick it up?

**Comment by peko-hr** [comment]
@aminlatifi 

Of course, please.
Is there anything I can do?
