### ISSUE TITLE
Implement Script to Regenerate gRPC Mocks

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1429]
Hi all,

Currently if we modify any of the RPC services in our proto/beacon/rpc/v1/services.proto file, we have to regenerate the mocks used by gomock when testing these out in our repo. We have to do this for every RPC service in this file. For example, for the `BeaconServiceClient` and `BeaconServiceServer`:

```
mockgen github.com/prysmaticlabs/prysm/proto/beacon/rpc/v1 BeaconServiceClient,BeaconService_LatestAttestationClient,BeaconService_WaitForChainStartClient > ./validator/internal/beacon_service_mock.go
```
and
```
mockgen github.com/prysmaticlabs/prysm/proto/beacon/rpc/v1 BeaconServiceClient,BeaconService_LatestAttestationClient,BeaconService_WaitForChainStartClient > ./validator/internal/beacon_service_mock.go
```

Additionally, we need to modify their package name to be `package internal` instead of `package mock_v1` as they are included in the `internal` packages of the beacon-chain and validator. Ideally, we could have a script that regenerates all these mocks easily in our `scripts` directory.

**Comment by terenc3t** [comment]
thanks @wildmolasses! issue assigned to @wildmolasses
