### ISSUE TITLE
Store Previously Requested ETH1.0 Logs Block Number

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1430]
Hi all,

Currently our powchain service reads all historical logs from the deposit contract from ETH1.0. As the contract grows even more, we should be persisting the last requested block number for logs to disk in the powchain service to avoid looping through all of these logs every time the node is launched. a PR for this would store the last requested ETH1.0 block number for log fetching in BoltDB. Next time the node spins up, we can request logs started from this block number + 1. Thanks @nisdas for bringing this up.

**Comment by prestonvanloon** [comment]
Whoever takes this issue should outline a plan for caching these logs.

They need to consider how to do this after 2 million or 50 million PoW blocks without overwhelming the process memory.

**Comment by shayzluf** [comment]
I am taking this task

Looking into the current code first

**Comment by shayzluf** [comment]
@prestonvanloon caching the last block read index (big.Int) in boltdb and reading it shouldn't be an issue for the process memory . Am I missing something here?

**Comment by shayzluf** [comment]
It seems like this task has been merged with #1760 and taken by @nisdas I leave this task to @nisdas

**Comment by nisdas** [comment]
Clarified with @shayzluf in chat https://discordapp.com/channels/476244492043812875/483017808658169866/550915035895955466 , about the requirements for the issue

**Comment by prestonvanloon** [comment]
This is a mainnet config requirement. Reading 16k logs on start up takes several minutes.

**Comment by rauljordan** [comment]
Hey @prestonvanloon could you try this again with #4299

**Comment by prestonvanloon** [comment]
#4299 adds significant improvement from 3 minutes to under 1 minute, but this is still unsatisfactory for node restarts.

**Comment by rauljordan** [comment]
I believe this is resolved by #4329, right @nisdas?

**Comment by nisdas** [comment]
Yeap @rauljordan, this is resolved by #4329
