### ISSUE TITLE
"FATAL main: unable to start beacon node: could not start modules: could not start DB: could not load genesis from file: version=0x80000069 not found in any known fork choice schedule: unable to find requested BeaconChainConfig"

### ISSUE THREAD

**Issue by junghyun0783** [prysmaticlabs/prysm#14336]
I am currently running two containers, Ethereum geth and prysm.
However, when I stopped the container and ran it again, a problem occurred.

![59](https://github.com/user-attachments/assets/4e710b74-8e5c-44c1-a216-f4cf2996c658)

I don't know why this problem occurs.
Even if I delete the prysm container and run it again, the problem occurs.
This is the current Prism docker run command. Is there something wrong?
The genesis file used to work fine, but suddenly it doesn't.

Please, experts, tell me why this error occurs.

**Comment by junghyun0783** [comment]
This is the prysm docker creation command. Please refer to it.
`docker run -it --name eth_beaconmain --network medalla -v /home/docker/container/mainnet/eth/prysmlog:/var/log/prysm -v /home/docker/container/mainnet/eth/genesis.ssz:/genesis/genesis.ssz -v /home/docker/container/mainnet/eth/prysm:/data -v /home/docker/container/mainnet/eth/jwt:/root -p 30020:4000 -p 30028:13000/tcp -p 30029:12000/udp prysmaticlabs/prysm-beacon-chain:latest --force-clear-db --datadir=/data --jwt-secret="/root/jwt.hex" --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --monitoring-host=0.0.0.0 --log-file=/var/log/prysm/prysmBeaconChain.log --execution-endpoint=http://eth_mainnet:8551 --genesis-state=/genesis/genesis.ssz`

**Comment by syjn99** [comment]
It seems `genesis.ssz` contains other fork id(`0x80000069`), which is not in prysm codebase.
Medalla network is deprecated: use other network or `genesis.ssz`

**Comment by junghyun0783** [comment]
@syjn99 
If I use a different "genesis.ssz", will all the blocks I've received so far be lost?

**Comment by syjn99** [comment]
If sync from genesis, yes.

**Comment by junghyun0783** [comment]
@syjn99 
Previously, synchronization was working fine.
However, after the internet was disconnected and rebooted, it stopped working.
Isn't it a genesiss.ssz problem?

**Comment by junghyun0783** [comment]
@syjn99 
I have a question.
I stopped the container in the middle of initialization.
Will this cause a problem?
The beacon initialization was going well, but I stopped the container for a while due to a network problem, and when I ran it again, it didn't work.
Will there be a problem if I stop it during initialization?

**Comment by junghyun0783** [comment]
@syjn99 
Thank you, I solved it.

I added the flags "--checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info" and it worked.

Thanks for your help.
