### ISSUE TITLE
Regenerate golang proto files ?

### ISSUE THREAD

**Issue by artjoma** [prysmaticlabs/prysm#14358]
How to regenerate Go stubs from ptroto files located under proto folder using Bazel  ?
I try ``` bazel run //proto:network=mainnet ```
```
WARNING: Target pattern parsing failed.
ERROR: Skipping '//proto:network=mainnet': no such target '//proto:network=mainnet': target 'network=mainnet' not declared in package 'proto' defined by
```

**Comment by prestonvanloon** [comment]
There is a script for this. Run ./hack/update-go-pbs.sh

**Comment by artjoma** [comment]
@prestonvanloon thank you!
