### ISSUE TITLE
k8s.io/client-go ,the version is too low

### ISSUE THREAD

**Issue by easydo666** [prysmaticlabs/prysm#14372]
### Describe the bug

../../../../pkg/mod/github.com/prysmaticlabs/prysm/v5@v5.0.3/beacon-chain/cache/common.go:10:23: cannot use popProcessNoopFunc (value of type func(_ interface{}) error) as "k8s.io/client-go/tools/cache".PopProcessFunc value in argument to queue.Pop

The version of k8s.io/client-go referenced is too low, and the function "type PopProcessFunc func(obj interface{}, isInInitialList bool) error" has an extra bool

**Comment by prestonvanloon** [comment]
Closing as duplicate of #13958
