### ISSUE TITLE
[Mega Tracking] Align Codebase to Spec v0.1

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1449]
This issue tracks the overall progress of updating the current codebase to spec [v0.1](
https://t.co/8lh2x0TPyJ) and this [commit](https://github.com/ethereum/eth2.0-specs/blob/4cdb66728a27739fcb35e545386770f3a2972bf8/specs/core/0_beacon-chain.md)

As part of the test net deliverable, we should lock down on a spec version before hardening. v0.1 sounds like a good candidate given the end of Q1 is 2 months away.

**Comment by nisdas** [comment]
Changes I will be handling: 
`validator_registry_update_slot` to `validator_registry_update_epoch` 
remove `validator_registry_delta_chain_tip_hash32`
`previous_epoch_calculation_slot` to `previous_calculation_epoch` 
`current_epoch_calculation_slot` to `current_calculation_epoch`
`previous_justified_slot` to `previous_justified_epoch` 
`justified_slot` to `justified_epoch`
`finalized_slot` to `finalized_epoch` 
Fix references for all these changes
Fix tests to account for the changes

**Comment by terenc3t** [comment]
We can close this as soon as #1523, #1537, #1539, and #1540 gets merged
We'll use #1541 and #1542 to track anything after

**Comment by terenc3t** [comment]
Can close this. Please refer #1541 and #1542 for the next set of issues
