### ISSUE TITLE
Default scrape-interval for Client-stats exceeds rate-limit of Beaconcha.in API free plan

### ISSUE THREAD

**Issue by Jor-Tech** [prysmaticlabs/prysm#14536]
# 💎 Issue

**Background**

I am using the Prysm Client-stats app to monitor Prysm client statistics. It scrapes data from the node and parses this to the Beaconcha.in app which relies on the Beaconcha.in API. The current default configured value for the scraping interval (`--scraping-interval`) causes issues for users on the free plan of the Beaconcha.in API, as the total number of requests per month exceeds the rate limit.<br></br>
**Description**

The default scraping interval of Client-stats is currently set to 1 minute (1m0s). However, the Beaconcha.in API's free plan has a monthly rate limit of 30,000 requests. Due to the frequent scraping, this leads to an error: `response status code (429). response body=Too Many Requests`.<br></br>
**Proposed Solution:**

This issue can be resolved by adjusting the default scraping interval for Client-stats using the flag `--scrape-interval`. Setting the interval to about 1 minute and 36 seconds (1m36s) or higher would prevent exceeding the rate limit. To be on the safe side, 2 minutes could be a more appropriate default.
It would be helpful if the default value in Client-stats was adjusted to prevent exceeding the Beaconcha.in API rate limit, especially for users on the free plan.

**Comment by Jor-Tech** [comment]
Yes, please. 

Got a commit ready to push as branch `update-scrape-interval` but don't have permission to push it.

Suggested code change to [prysm/cmd/client-stats/flags/flags.go](https://github.com/prysmaticlabs/prysm/blob/dc91c963b9e896ae87f0a6d11f82229dab5dc928/cmd/client-stats/flags/flags.go#L28-L32):

```go
 ScrapeIntervalFlag = &cli.DurationFlag{ 
 	Name:  "scrape-interval", 
 	Usage: "Frequency of scraping expressed as a duration, eg 2m or 1m5s.", 
 	Value: 120 * time.Second, 
 } 
```

**Comment by prestonvanloon** [comment]
@Jor-Tech - You'll want to fork the repo on github, then submit a pull request from your fork.

Our contributing doc might be helpful here: 
 https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#contribution-steps
