### ISSUE TITLE
Coin issuance broadcast failed after node upgrade

### ISSUE THREAD

**Issue by COLUD4** [prysmaticlabs/prysm#14548]
After the LYX node was upgraded according to this document (https://luksovalidators.substack.com/p/lukso-dencun-hard-fork-mainnet), the node seemed to be synchronized normally without any abnormalities, but the coin broadcast failed.
Error:  { code: -32000, message: 'already known' }
Node version:
 Release v5.0.4 · prysmaticlabs/prysm
Release Trident (v1.14.7) · ethereum/go-ethereum
Node version before upgrade:
Release V4.2.1 · prysmaticlabs/prysm
Release Edolus (v1.13.12) · ethereum/go-ethereum

**Comment by james-prysm** [comment]
hmm wouldn't this be a question for lukso instead? we are on v5.1.2

**Comment by COLUD4** [comment]
> hmm wouldn't this be a question for lukso instead? we are on v5.1.2
Using 5.1.1 or 5.1.2 will result in an error
time="2024-10-17 14:34:52" level=warning msg="Running on custom Ethereum network specified in a chain configuration yaml file" prefix=flags
time="2024-10-17 14:34:52" level=warning msg="Starting beacon chain with max RPC page size of 200000" prefix=node
time="2024-10-17 14:34:52" level=warning msg="Subscribing to All Attestation Subnets" prefix=flags
time="2024-10-17 14:34:52" level=fatal msg="unable to start beacon node: could not set beacon configuration options: could not configure chain config: version 0x05000000 for fork electra in config lukso conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule" prefix=main

**Comment by james-prysm** [comment]
yes because lukso chain is its own chain, it would have a conflict due to configs, that would need to be whatever lukso uses

**Comment by prestonvanloon** [comment]
Thanks for the ticket @COLUD4. We do not have capacity to investigate issues with other chains at this time.
