### ISSUE TITLE
Keymanager API keystores getter partially broken or do not behave like on all other vcs

### ISSUE THREAD

**Issue by TobiWo** [prysmaticlabs/prysm#14577]
# 💎 Issue

### Background

The keymanager api endpoints:
- GET `/eth/v1/keystores`
- GET `/eth/v1/remotekeys`

behave different compared to all other clients which breaks interoperability. Furthermore `/eth/v1/keystores` is broken when keystores are managed via a remote signer (see below).

Although the keymanager api spec does not define a specific behavior when no keystores are managed locally or not via a remote signer but the behavior of all other clients makes a lot of sense (see below).

### Description

If keystores are managed locally, `/eth/v1/remotekeys` should return a 200 with the following response:
```json
{"data": []}
```
Instead it returns a `500` and a response json with some error message.

If keystores are managed by a remote signer, `/eth/v1/keystores` should return a 200 with the following response:
```json
{"data": []}
```
Instead the request fails totally with no error code and only the following error `Error: socket hang up`.

Furthermore, I found the following bugs:

1. There is a minor bug at the keymanager api authentication. If the authentication fails due to an incorrect bearer token prysm returns no json response but instead only the message `Forbidden: token value is invalid`. Instead it should be something like:

```json
{
    "status": 403,
    "message": "Token value is invalid"
}
```
2. I'm not sure if this is a bug since the spec is a bit vague on it. Prysm returns a fee-recipient for each and every pubkey which is put into the endpoint `/eth/v1/validator/<pubkey>/feerecipient`. In my understanding it should only return the fee recipient for managed validators.

**Comment by james-prysm** [comment]
can circle back on this some time but unfortunately where will be some inconsistencies with prysm and the other clients, the way we handle keys has been uniquely different than other clients since genesis and we have been slowly working towards more standardization. some differences are listed in https://github.com/ethereum/keymanager-APIs/tree/master/flows/client-specific/prysm . we'll try to address some of the inconsistencies but some may also be limited due to the current design of the system.

**Comment by TobiWo** [comment]
All good. I fully understand this. It always looks like a quickfix from the outside but I can imagine that it is much more complex.

I think the biggest issue currently is the broken `/eth/v1/keystores` endpoint if keystores are managed by a remote signer. I'm pretty sure this is not intended behavior (see above). This needs a bugfix.
