### ISSUE TITLE
Cannot produce block when more than 2 attester slashings in slashing pool

### ISSUE THREAD

**Issue by coldpak** [prysmaticlabs/prysm#14708]
### Describe the bug

Hi team,

This issue appears to occur specifically in the context of the Electra hardfork. When there are more than two attester slashings in the slashing pool, block production fails. While this may not currently be critical, it is a potential bug that could happen in the Mekong testnet.

This issue is described in PR #14691, which includes a fix to ensure proper handling of EIP-7549 rule in the slashing pool.

### Has this worked before in a previous version?

```text
It doesn't matter with pre-Electra hardforks.
```

### 🔬 Minimal Reproduction

1. `BuildBlockParallel` calls `getSlashings` 
2. `getSlashings` calls `PendingAttesterSlashings`
3. `PendingAttesterSlashings` returns at most 2 slashings because the `MaxAttesterSlashings` is set to 2.
4. Electra block must have at most 1 slashing in a block, so it fails at block validation, especially with length check logic.

### Error

```text
rpc error: code = Internal desc = could not build block in parallel: rpc error: code = Internal desc = Could not compute state root: could not calculate state root at slot 4916: could not process block: could not hash tree root beacon block body: incorrect list size
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

latest develop commit https://github.com/prysmaticlabs/prysm/commit/1f2d8cfae908c36622c0c1736bc9ed6c1b18ac22

### Anything else relevant (validator index / public key)?

N/A

**Comment by prestonvanloon** [comment]
Is this fixed in https://github.com/prysmaticlabs/prysm/pull/14691 ?

**Comment by coldpak** [comment]
Yes, it is!
