### ISSUE TITLE
Discrepancies Between Ethereum Consensus Specification and Implementation in RANDAO Processing During Block Handling

### ISSUE THREAD

**Issue by dulee21** [prysmaticlabs/prysm#14746]
# 💎 Issue

### Background
I am developing a private Ethereum network based on the Capella fork and currently studying the block processing flow defined in the Ethereum consensus specification.

### Description
According to the specification, [the process_block function](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#block-processing) is defined as follows:
```
def process_block(state: BeaconState, block: BeaconBlock) -> None:
    process_block_header(state, block)
    # [Modified in Capella] Removed `is_execution_enabled` check in Capella
    process_withdrawals(state, block.body.execution_payload)  # [New in Capella]
    process_execution_payload(state, block.body, EXECUTION_ENGINE)  # [Modified in Capella]
    process_randao(state, block.body)
    process_eth1_data(state, block.body)
    process_operations(state, block.body)  # [Modified in Capella]
    process_sync_aggregate(state, block.body.sync_aggregate)
```

Among these steps, I am currently analyzing [process_randao](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#randao), which is described in the specification as follows:
```
def process_randao(state: BeaconState, body: BeaconBlockBody) -> None:
    epoch = get_current_epoch(state)
    # Verify RANDAO reveal
    proposer = state.validators[get_beacon_proposer_index(state)]
    signing_root = compute_signing_root(epoch, get_domain(state, DOMAIN_RANDAO))
    assert bls.Verify(proposer.pubkey, signing_root, body.randao_reveal)
    # Mix in RANDAO reveal
    mix = xor(get_randao_mix(state, epoch), hash(body.randao_reveal))
    state.randao_mixes[epoch % EPOCHS_PER_HISTORICAL_VECTOR] = mix
```

To understand this, I reviewed the implementation in the file ([beacon-chain/core/blocks/randao.go](https://github.com/prysmaticlabs/prysm/blob/96b31a9f64a8f8b3909b11171ce3c2dab877cfc7/beacon-chain/core/blocks/randao.go))
However, unlike the specification, only the ProcessRandaoNoVerify function is used, which does not validate the RANDAO reveal.
The ProcessRandao function is defined but seems to be unused.

https://github.com/prysmaticlabs/prysm/blob/96b31a9f64a8f8b3909b11171ce3c2dab877cfc7/beacon-chain/core/blocks/randao.go#L30

https://github.com/prysmaticlabs/prysm/blob/96b31a9f64a8f8b3909b11171ce3c2dab877cfc7/beacon-chain/core/blocks/randao.go#L66

I am curious whether this difference reflects some additional information I am unaware of or if it is an intentional deviation from the specification.

**Comment by terencechain** [comment]
It's verified here: https://github.com/prysmaticlabs/prysm/blob/66d1bb54f629d06b2baa0bc756eb0ca2b76bf057/beacon-chain/core/transition/transition_no_verify_sig.go#L190
We batch verify all the signatures in block at once
