### ISSUE TITLE
Is Execution Payload Validation Intentionally Omitted in ProcessPayload?

### ISSUE THREAD

**Issue by dulee21** [prysmaticlabs/prysm#14741]
# 💎 Issue
### Background
I am currently building an Ethereum test network on the Capella version and studying the block processing section of the consensus specifications.

### Description
Most parts are implemented very well according to the consensus specification.
However, in the ProcessPayload section of beacon-chain/core/blocks/payload.go, the following line seems to be missing:
`assert execution_engine.verify_and_notify_new_payload(NewPayloadRequest(execution_payload=payload)).
`
In other words, the process of verifying whether the execution payload is valid appears to be absent.

Is this omission intentional?

```go
// ProcessPayload processes input execution payload using beacon state.
// ValidatePayloadWhenMergeCompletes validates if payload is valid versus input beacon state.
// These validation steps ONLY apply to post merge.
//
// Spec code:
// def process_execution_payload(state: BeaconState, payload: ExecutionPayload, execution_engine: ExecutionEngine) -> None:
//
//	# Verify consistency of the parent hash with respect to the previous execution payload header
//	if is_merge_complete(state):
//	    assert payload.parent_hash == state.latest_execution_payload_header.block_hash
//	# Verify random
//	assert payload.random == get_randao_mix(state, get_current_epoch(state))
//	# Verify timestamp
//	assert payload.timestamp == compute_timestamp_at_slot(state, state.slot)
//	# Verify the execution payload is valid
//	assert execution_engine.execute_payload(payload)
//	# Cache execution payload header
//	state.latest_execution_payload_header = ExecutionPayloadHeader(
//	    parent_hash=payload.parent_hash,
//	    FeeRecipient=payload.FeeRecipient,
//	    state_root=payload.state_root,
//	    receipt_root=payload.receipt_root,
//	    logs_bloom=payload.logs_bloom,
//	    random=payload.random,
//	    block_number=payload.block_number,
//	    gas_limit=payload.gas_limit,
//	    gas_used=payload.gas_used,
//	    timestamp=payload.timestamp,
//	    extra_data=payload.extra_data,
//	    base_fee_per_gas=payload.base_fee_per_gas,
//	    block_hash=payload.block_hash,
//	    transactions_root=hash_tree_root(payload.transactions),
//	)
func ProcessPayload(st state.BeaconState, payload interfaces.ExecutionData) (state.BeaconState, error) {
	var err error
	if st.Version() >= version.Capella {
		st, err = ProcessWithdrawals(st, payload)
		if err != nil {
			return nil, errors.Wrap(err, "could not process withdrawals")
		}
	}

	if err := ValidatePayloadWhenMergeCompletes(st, payload); err != nil {
		return nil, err
	}
	if err := ValidatePayload(st, payload); err != nil {
		return nil, err
	}
	if err := st.SetLatestExecutionPayloadHeader(payload); err != nil {
		return nil, err
	}
	return st, nil
}
```

**Comment by syjn99** [comment]
Hi, in Prysm, you can check the actual validation logic at `beacon-chain/blockchain/execution_engine.go`.

https://github.com/prysmaticlabs/prysm/blob/30d5749ef6de3b1b9e60cf362418a71b42e803f6/beacon-chain/blockchain/execution_engine.go#L225

As EL client is responsible to validate the execution payload, CL client "notifies" to EL via Engine API.

**Comment by dulee21** [comment]
Thank you for the response. However, my question was not about the responsibility of execution payload validation being on the Execution Layer (EL). I understand that EL is responsible for validating the execution payload, and the Consensus Layer (CL) only "notifies" the EL via the Engine API.

My concern is that in the ProcessPayload function, there seems to be no call to notify the EL about the execution payload (e.g., using notifyNewPayload or similar). This appears to deviate from the block processing logic as described in the Ethereum consensus specification, which includes the step "Verify the execution payload is valid" during block processing.

Could you clarify if this is intended behavior, or am I missing where the notification to EL is implemented in the process?

**Comment by syjn99** [comment]
https://github.com/prysmaticlabs/prysm/blob/30d5749ef6de3b1b9e60cf362418a71b42e803f6/beacon-chain/blockchain/receive_block.go#L64

You should check out block processing logic from `ReceiveBlock`. `notifyNewPayload` is called in `validateExecutionOnBlock`.

There are some parts in the actual implementation that deviates from `consensus-specs` for optimization. (e.g. verify signatures in batch, etc)

**Comment by dulee21** [comment]
Thank you so much for your response and the detailed explanation! I truly appreciate the time and effort you took to clarify this for me. Your support has been very helpful, and I’m grateful for your guidance.
