### ISSUE TITLE
VSCode ext bug !

### ISSUE THREAD

**Issue by AntonSaurytski83** [prysmaticlabs/prysm#14743]
### Describe the bug

Failed to trigger analysis. Please report this to the team. (error: Javafailed: Failed to analyze file: f:\JAVA\2024\spring-petclinic\src\main\java\org\springframework\samples\petclinic\owner\OwnerController.java: rpc error: code = Unknown desc = )

### 🔬 Minimal Reproduction

spring pet clinic public project

### Error

```text
Failed to trigger analysis. Please report this to the team. (error: Javafailed: Failed to analyze file: f:\JAVA\2024\spring-petclinic\src\main\java\org\springframework\samples\petclinic\owner\OwnerController.java: rpc error: code = Unknown desc = )
```

### Platform(s)

Windows (x86)

**Comment by nisdas** [comment]
@AntonSaurytski83 This issue is unrelated to prysm and as @crStiv has mentioned it would be more suitable to be opening this issue in the application's repository or support forum.
