### ISSUE TITLE
Beacon Chain Configs for 8 Validators

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1479]
**Problem:**
1.) We are starting out with 8 validators in a local test net, with 8 validators and 64 epoch length there's skipped slots:
Ex: ([]= skipped block, [#] = validator index assigned to that slot)
`[[] [] [] [] [] [] [] [5] [] [] [] [] [] [] [] [7] [] [] [] [] [] [] [] [4] [] [] [] [] [] [] [] [1] [] [] [] [] [] [] [] [3] [] [] [] [] [] [] [] [2] [] [] [] [] [] [] [] [0] [] [] [] [] [] [] [] [6]]`

2.)To keep things simple for the very first iteration, we don't wanna deal with skip blocks so I shortened the epoch length to 8:
`[[5] [7] [4] [1] [3] [2] [0] [6]]`

Question for @djrtwo, @JustinDrake and @vbuterin, what parameter numbers do you recommend for a local test net with 8 validators to start with? (`SHARD_COUNT`, `TARGET_COMMITTEE_SIZE`, and `EPOCH_LENGTH`)

**Comment by ralexstokes** [comment]
if you are just testing things out and scaled the epoch length by 8, try scaling everything else down by a factor of 8?

alternatively i would suggest either bumping up the number of validators, or just handling the skipped slots

**Comment by JustinDrake** [comment]
I'd do `SHARD_COUNT = 1`.

**Comment by prestonvanloon** [comment]
We tried
 
EPOCH_LENGTH = 8
SHARD_COUNT = 1
TARGET_COMMITTEE_SIZE = 1 

This was causing a divide by zero issue due to an empty crosslink committee in the first epoch. 
Let me step through the code and I'll add my findings to this comment.

**Comment by terenc3t** [comment]
Divide by 0 is our issue and it is currently tracked by #1481. Once we fix that we can handle skip slot

**Comment by djrtwo** [comment]
This also might be an issue depending on how it's interpreted (https://github.com/ethereum/eth2.0-specs/issues/541).

Is that issue failing due to no committee being assigned for that slot but the validator is requesting the proposer at that slot?

It is unfortunate that the most realistic early nets are at these unrealistic low numbers :/ (compared to production).
The protocol generally degrades gracefully but there are certainly edge cases around helper methods failing as you are running into.

**Comment by djrtwo** [comment]
@prestonvanloon 

> This was causing a divide by zero issue due to an empty crosslink committee in the first epoch.

Empty as in there is not one assigned to the slot at all or because the committee didn't show up to attest?

**Comment by djrtwo** [comment]
I might even go with `EPOCH_LENGTH = 4` so you get two validators per slot

**Comment by prestonvanloon** [comment]
@djrtwo we were having an issue with config overrides were not being applied. 

By the way, 8 doesn’t reflect a number of validators we would deploy on a testnet. We’re just looking to see the client do stuff before standing up the infrastructure for a larger deployment. 

We’ll circle back on this issue after we’ve caught up on all of the first class epoch changes. Thanks!

**Comment by djrtwo** [comment]
oh I know! I just meant these early simulations

**Comment by rauljordan** [comment]
Closed by #1565
