### ISSUE TITLE
BeaconProposerIdx panics instead of gracefully erring out

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1481]
Instead of panicking with index not found we should gracefully error out if there's no committee

https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/validators/validator.go#L88

**Comment by prestonvanloon** [comment]
I'll take this, it's crashing the server so needs to be fixed ASAP

**Comment by prestonvanloon** [comment]
It also happens here: https://github.com/prysmaticlabs/prysm/blob/176aa2688e770e3b079b766830c3a3eba58c67ae/beacon-chain/rpc/validator_server.go#L67

**Comment by prestonvanloon** [comment]
Looks like duplicated code, I'll simplify if possible

**Comment by terenc3t** [comment]
Thanks Preston! 🙏🏼

**Comment by prestonvanloon** [comment]
Working on this now
