### ISSUE TITLE
Broadcast Attestation to Network at Slot+0.5*SLOT_DURATION Seconds

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1498]
The spec mentions: A validator should create and broadcast the attestation halfway through the slot during which the validator is assigned -- that is SLOT_DURATION * 0.5 seconds after the start of slot.

Upon creating an attestation, the validator should wait until the time hits half of the duration between slots to submit it to the beacon node for broadcasting. We should implement this in the validator client's runner.go file.

**Comment by rauljordan** [comment]
This is pending the merge of #1487

**Comment by IvanTheGreatDev** [comment]
Hey Raul! Think I can handle this? 😄
