### ISSUE TITLE
Cap the Number of Operations Proposer Includes in Validator Client

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1511]
Hi all,

Currently, our proposer logic includes block operations when the validator is assigned to propose a block. The spec mentions there is a hard limit on the number of deposits, attestations, slashings, etc. that can be included in a block, however, we do not enforce this in our code in validator/client/validator_propose.go. Ideally, the server side methods can cap the number of items they give the proposer via RPC, and the proposer can do a simple cutoff to only include the max amount in the block.

**Comment by rauljordan** [comment]
Part of {{1510}}

**Comment by IvanTheGreatDev** [comment]
I'd like to take this!! 😄

**Comment by terenc3t** [comment]
Operation pool service is already taking care of this: 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/operations/service.go#L102

Marking this as closed. Feel free to reopen if anyone has a better implementation
