### ISSUE TITLE
Move SSZ to github.com/prysmaticlabs/go-ssz

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1549]
We should move the ssz shared library out of prysm and relicense under a more permissive license so other projects can contribute or use it freely. The current license suggestion is LGPL, but we should consider MIT as well since this library really isn't specific to Prysmatic Labs.

We need confirmation from @houjieth that their in progress work will not be significantly disrupted by this change. If so, we will wait for them to merge their latest work.

**Comment by houjieth** [comment]
Thanks Preston. I think it's great to make the ssz part more free to use.

I currently about 1 or 2 pending PR and I will send them out as soon as possible. The PR link will be put here.

**Comment by protolambda** [comment]
Can I ask what the current status is? Can I start using SSZ in my Go projects yet? :)

**Comment by prestonvanloon** [comment]
https://github.com/prysmaticlabs/go-ssz
