### ISSUE TITLE
Docker-Compose Our Ruby Release

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#158]
Hi all,

As we move into the Ruby release and now that #149 is in place, we should determine how we can release something compact and complete for the minimal sharding protocol for anyone to try out. Ideally, we would use docker-compose or other containerization techniques to do this.

The idea here is that for someone to get the full picture of what the minimal sharding protocol would look like, we want our end users to see:

- a bunch of incoming transactions being broadcast to the shardp2p network
- a bunch of proposers packaging them up into collations and submitting them to a sharding manager contract
- a group of notaries staking their ETH into the contract
- notaries being selected on each period
  - these notaries would then download submitted collations during their period and check for data availability
  - these notaries would then vote for these collation headers and if > 2/3 of them vote to approve, we set as canonical and finalize the collation
  
Right now, anyone that wants to try out system has to
1. Initialize a geth node
2. Run a geth node and a miner
3. Start a notary service using a ton of command line flags
4. Start a proposer service separately also using a ton of command line flags

At most, the user will only see 1 notary and 1 proposer working the system. If we can containerize this to initialize a variety of replicas so that we can simulate a system with many concurrent actors, that would be when I would consider the Ruby release to be finished. Additionally, we would need this system to be easily inspectable. That is, users should be able to see what's going on and what the different services are doing over the shardp2p network (perhaps the observer actor can be a hook-in for this?)

Let's use this issue as a thread to discuss how to do this via docker/kubernetes/etc.

**Comment by prestonvanloon** [comment]
+1 to containerize. I can help with k8s stuff.

**Comment by Magicking** [comment]
I see 3 solutions:

Easiest (user PoV):
- One-liner or multiple docker-compose files that initialize (possibly through scripts) & run everything.

Easiest(?) PoV:
- K8s, I'm not very familliar with it but AFAIK you can convert docker-compose files to k8s with kompose.

Complicated or for production:
 - Integration through puppeth (see cmd/puppeth/*)

Simple but without dependencies:
 - Nightly build to provides signed binaries

I would like to hear a little bit more about k8s, I don't know that much except from what I could see from the documentation but it seems to have an easy web interface, that would be more user friendly that a command line docker, @prestonvanloon have you played with that a little bit ?

**Comment by rauljordan** [comment]
We will no longer be doing this but instead running a cluster for Ruby through k8s on some cloud solution
