### ISSUE TITLE
SSZ: Support Fixed-Size Byte Array

### ISSUE THREAD

**Issue by houjieth** [prysmaticlabs/prysm#1600]
The ssz [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#tree-hash) have been changed to only support fixed-size array (not dynamic size array).

Currently our ssz implementation only supports byte slice which is akin to dynamic-size array.

We need to update the implementation and align our encoding/decoding/hash scheme with the spec.

Related source code:
https://github.com/prysmaticlabs/prysm/tree/master/shared/ssz

**Comment by shayzluf** [comment]
taking this task

**Comment by shayzluf** [comment]
@houjieth in the spec I see 

```Composite types
container: ordered heterogenous collection of values
key-pair curly bracket notation {}, e.g. {'foo': "uint64", 'bar': "bool"}
tuple: ordered fixed-length homogeneous collection of values
angle bracket notation [type, N], e.g. ["uint64", N]
list: ordered variable-length homogenous collection of values
angle bracket notation [type], e.g. ["uint64"]```

Seems like variable length is still supported

Could you point me to the change please?

**Comment by rauljordan** [comment]
Resolved in latest master of https://github.com/prysmaticlabs/go-ssz
