### ISSUE TITLE
Provide vyper compiler as part of the bazel toolchain

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1614]
Similar to how we can easily generate our protobuf bindings through bazel. It would greatly improve developer workflow to use a reliably consistent compiler for vyper provided via the bazel toolchain.

Related issues: 
- #1416 
- #272 & #411 

Ideal flow would be that we can generate the go bindings from a vyper source file through a new bazel rule. 

```python
vyper_go_library(
  name = "depositcontract",
  srcs = ["deposit-contract.vy"],
)
```
This generates the ABI, bytecode, and runs abigen to generate a go file that can be imported in other packages.

**Comment by rauljordan** [comment]
Closing due to stagnation + low priority
