### ISSUE TITLE
Make test function names consistent across codebase

### ISSUE THREAD

**Issue by IvanTheGreatDev** [prysmaticlabs/prysm#1631]
Sometime during development we shifted from using syntax like [`TestFunctionName`](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/blocks/block_test.go#L147) to [`TestFunctionName_Behavior`](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/blocks/block_test.go#L105) for tests. 
This issue is to make sure that all test cases are properly renamed to the current convention we use now in order to make the passing tests much more readable.

If the behavior is normal then the function should be prefixed with `_OK`.

**Comment by terenc3t** [comment]
Sweet. Wanna take on this @IvanTheGreatDev ?

**Comment by IvanTheGreatDev** [comment]
I'd be down! Although I wanna handle #1511 first!
