### ISSUE TITLE
Fetch Correct Ancestor Deposit Root in ETH1 Data

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1656]
Hi all,

As a follow-up to to #1615, if the data votes object slice is empty, the spec specifies:
```
Let block_hash be the block hash of the ETH1_FOLLOW_DISTANCE'th ancestor of the head of
the canonical eth1.0 chain.
Let deposit_root be the deposit root of the eth1.0 deposit contract in the
post-state of the block referenced by block_hash.
```

Currently, we have no mechanism to obtain historical deposit roots, so we would need a feature that would allow us to fetch that from the post-state of a block by blockhash in the ETH1.0 chain. This can be done in the powchain service of our beacon node.

**Comment by prestonvanloon** [comment]
@rauljordan can you add a comment on why this should be closed?

**Comment by rauljordan** [comment]
We correctly do this in our current master
