### ISSUE TITLE
Clear Operations Which Cause Errors in Block Processing

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1689]
Hi all,

Currently, if a block failed the state transition due to a faulty operation (an attestation which fails processing), the next proposer will attempt to include this faulty operation. Instead, we should be able to clear out this faulty operation so future proposers do not include it in their blocks, which would cause the chain to stall until the system dies. Perhaps we can clear attestations which cause errors from the operations service.

**Comment by prestonvanloon** [comment]
Is this still valid?

**Comment by terencechain** [comment]
Resolved via #1586
