### ISSUE TITLE
libp2p renamed all of their tags

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1704]
Now we cannot checkout the previous versions. 

The fix is to change all of the tags to their new format or use a commit hash. 

Inquiry to pin tags to their commit hash: https://github.com/renovatebot/config-help/issues/172

**Comment by prestonvanloon** [comment]
Example: https://github.com/prysmaticlabs/prysm/blob/b6cc79fa2ac0da749056b3d06958867f5f925b53/WORKSPACE#L618

Now is [gx/v0.3.15](https://github.com/libp2p/go-libp2p-blankhost/releases/tag/gx%2Fv0.3.15)

**Comment by prestonvanloon** [comment]
@raulk for FYI

**Comment by prestonvanloon** [comment]
The immediate blocking issue is resolved in #1705, but we should not consider the underlying issue resolved until we remove all tag based dependency imports.

**Comment by raulk** [comment]
Thanks for the shoutout here. This little breakage now is paving the way for clean gomod semantics, something that lots of downstream users will appreciate. Thanks for bearing with us!

**Comment by prestonvanloon** [comment]
Looks like ipfs just did the same thing. 

Some good news is that renovate will no longer push tag based updates, but still continue to only update on new versions.
