### ISSUE TITLE
Fix TestNextEpochCommitteeAssignment Slowness

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1714]
The test `TestNextEpochCommitteeAssignment` is taking long because of the `DepositsForChainStart` 16128 database writes. To fix it they should be batched 

See: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/validator_server_test.go#L186

**Comment by shayzluf** [comment]
I am working on it

**Comment by nisdas** [comment]
Nice :) , Assigned to @shayzluf
