### ISSUE TITLE
Cache the beacon chain state in order to reduce unneeded disk I/O

### ISSUE THREAD

**Issue by IvanTheGreatDev** [prysmaticlabs/prysm#1753]
This is an issue to represent the recent findings after running a local beacon chain, in which the higher the slot, the larger state elements such as `Eth1Data` and others grow. The size of `Eth1Data` in particular increases the block processing time by about 1 or 2 seconds each time an epoch transition is reached due to `BlockExists()` being performed up to 3 times on each item in `Eth1Data`. This continues until it surpasses `SECONDS_PER_SLOT` and the chain fails.

In beacon-chain/rpc/beacon_server.go, we call `BlockExists` [twice for each item in `Eth1Data`](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/beacon_server.go#L121-L154) and then [called twice again for any "ties" in data voting](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/beacon_server.go#L187-L208),

Images from tracing:
* [`Eth1Data` taking half a second at about 50 slots](https://cdn.discordapp.com/attachments/483017808658169866/550488569735675905/18dBAbBCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQGDaCCDlMG0OFQKFAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCNzPAk.png)

* [`Eth1Data` calling `BlockExists` and reading the state numerous times](https://cdn.discordapp.com/attachments/483017808658169866/550493890470477825/BABAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAAB3wTB0l1rqk5kpd7AAAAAElFTkSuQmCC.png)

* [Calls for `Eth1Data` taking more time as slot number increases](https://cdn.discordapp.com/attachments/483017808658169866/550494245849661460/BzdrM7iUTuFAAAAAElFTkSuQmCC.png)

* [`Eth1Data` call taking over 3 seconds](https://cdn.discordapp.com/attachments/483017808658169866/550494856326152192/VJxVxPgAABArMk4Dk4S9O0FgIECBCYVMBzcFIx1xMgQIDAKIG9Zmvr6WCx3W4tHEWsRl12nj8b7DX11tNeUSwuXWpXp3YxdHTNeX.png)

* [Whole lifecycle from the validator to the DB](https://cdn.discordapp.com/attachments/483017808658169866/550504632879808542/QOAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCNxjAki6uscmDOFCAAIQgAAEIAABCEAAAhCAAA.png)

* [General DB fetches taking over 20ms](https://cdn.discordapp.com/attachments/483017808658169866/550520727959240705/TEfX4Na3BJgAAAABJRU5ErkJggg.png)

* [Same as above](https://cdn.discordapp.com/attachments/483017808658169866/550521675209506837/wCfk4D2TyOfAAAAABJRU5ErkJggg.png)

A solution to this issue would be to save the state to cache so fetching the amount of data we need isn't as costly. 

Danny mentioned in particular that the [spec notes](https://github.com/prysmaticlabs/prysm/issues/1753) some definitions "make repeated use of heavy computing. Production implementations are expected to appropriately use caching/memoization to avoid redoing work". This is due to certain elements like `get_shuffling` *not being stored in the beacon state*.

This is also part related to #1718 , for a general goal of reducing disk I/O.

**Comment by prestonvanloon** [comment]
Some of the ETH1Data calls are being addressed in #1757.

I think the primary goal for this task is to optimize these calls
![image](https://user-images.githubusercontent.com/7246818/53568810-e6e8db80-3b30-11e9-9120-8528589a016a.png)

The state is an object that is read often (several times per second) but written less often (>1 second between writes).  To reduce I/O time for reading the state, we could keep a warm copy of the last written state in memory such that the state is only read from the actual disk at start up and read from memory for all other reads during.

We can achieve this functionalty by adding a property to the beaconDB and using a [RWMutex](https://golang.org/pkg/sync/#RWMutex) to ensure thread safe operation.

Here's a pseudo implementation example
```go
type BeaconDB struct {
  stateLock sync.RWMutex
  currentState *pb.BeaconState
  ...
}

func (db *BeaconDB) WriteState(state *pb.BeaconState) error {
  db.stateLock.Lock()
  defer db.stateLock.Unlock()
  db.currentState = state
   // Then write to disk as we do already
   ...
}

func (db *BeaconDB) State() *pb.BeaconState {
  db.stateLock.RLock()
  defer db.stateLock.RUnlock()
   if db.currentState != nil {
     return db.currentState
   }
   // Otherwise fetch from disk as we do already
   ...
}
```

The goals here are 
- [ ] Add state caching in BeaconDB
- [ ] Verify operation with thorough unit testing
- [ ] Verify improvement with another tracing screenshot
