### ISSUE TITLE
p2p: Implement broadcast 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#176]
[Design doc](https://docs.google.com/document/d/1cthKuGPreOSQH96Ujt7sArcT-IRICk6b-QcdD0EnLsI/edit)

- [ ] Implement `func (s *Server) Broadcast(msg interface{})`

More details to come through the design.

**Comment by nisdas** [comment]
@prestonvanloon Can we close this , its already implemented?

**Comment by terenc3t** [comment]
Yes, this was implemented under p2p's `service.go`
