### ISSUE TITLE
Implement Process_Exit_Queue from Spec 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#1764]
We are missing the step `process_exit_queue ` from current ETH2.0 beacon chain spec, this processing function happens at the end of epoch processing. This is not a blocker for test net deliverable and there's already a python implementation, so it's another good first issue!

```python
def process_exit_queue(state: BeaconState) -> None:
    """
    Process the exit queue.
    Note that this function mutates ``state``.
    """
    def eligible(index):
        validator = state.validator_registry[index]
        # Filter out dequeued validators
        if validator.withdrawable_epoch != FAR_FUTURE_EPOCH:
            return False
        # Dequeue if the minimum amount of time has passed
        else:
            return get_current_epoch(state) >= validator.exit_epoch + MIN_VALIDATOR_WITHDRAWABILITY_DELAY

    eligible_indices = filter(eligible, list(range(len(state.validator_registry))))
    # Sort in order of exit epoch, and validators that exit within the same epoch exit in order of validator index
    sorted_indices = sorted(eligible_indices, key=lambda index: state.validator_registry[index].exit_epoch)
    for dequeues, index in enumerate(sorted_indices):
        if dequeues >= MAX_EXIT_DEQUEUES_PER_EPOCH:
            break
        prepare_validator_for_withdrawal(state, index)
```

Reference commit: 
https://github.com/ethereum/eth2.0-specs/blob/bcb0b8bf874eb438327deda2894c0fb51da8f6b8/specs/core/0_beacon-chain.md

**Comment by Meeshbhoombah** [comment]
Hey @terenc3t how ya been, we spoke a bit at the Moloch DAO SF meetup - am interested in taking on this issue 👍

**Comment by terenc3t** [comment]
Sounds good. Thanks @Meeshbhoombah

**Comment by skillful-alex** [comment]
@Meeshbhoombah, are you working on this issue? I am ready to take it to development.

**Comment by Meeshbhoombah** [comment]
@skillful-alex Yes! Should be able to open a PR this afternoon or tomorrow morning.

**Comment by Meeshbhoombah** [comment]
@terenc3t wanted to confirm that the only files to change are:
- [`epoch_processing_test.go`](https://github.com/prysmaticlabs/prysm/blob/c1a9937760ea6a321c6e5f515499eb3a11301ba0/beacon-chain/core/epoch/epoch_processing_test.go)
- [`epoch_processing.go`](https://github.com/prysmaticlabs/prysm/blob/c1a9937760ea6a321c6e5f515499eb3a11301ba0/beacon-chain/core/epoch/epoch_processing.go)

**Comment by terenc3t** [comment]
correct!
