### ISSUE TITLE
Validators Need to Store Data They Have Signed

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1909]
Hi all,

As part of #1586, validators should keep track of the data they have signed (blocks/attestations) so that in case of a reorg, they have the necessary information to pull up from disk to propose when the time is needed or attest as necessary.

**Comment by skillful-alex** [comment]
I am ready to take this issue, and provide the result by March 25th. Do I take it?

**Comment by rauljordan** [comment]
This will be the responsibility of the slasher mechanism designed by @shayzluf and @0xKiwi. Could you guys add the link to the slashing design doc here for reference?

**Comment by nisdas** [comment]
This would be distinct from the slasher and will need to be done by each validator

**Comment by rauljordan** [comment]
Closing in favor of #3133
