### ISSUE TITLE
Invalid p2p messages can crash the service

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1924]
If `msg.Data` is nil, then this line can panic in the panic recovery 
https://github.com/prysmaticlabs/prysm/blob/334f13ac873df4e053f6ca2c8365ff83d4f80c69/beacon-chain/sync/regular_sync.go#L239

Related #330

**Comment by shayzluf** [comment]
taking this task

**Comment by nisdas** [comment]
hey @shayzluf I was working on this, maybe you could take up another open issue ?

**Comment by shayzluf** [comment]
no problem
