### ISSUE TITLE
[Mega Tracking] - Fork Choice Optimization 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#1951]
This issue tracks overall improvements for our current fork choice implementation. See #1950 as a starter.  Some high level ideas:

- Cache blocks and avoid reading blocks from DB to find head
- Look into different LMD-GHOST implementations

Helpful resources:
https://github.com/protolambda/lmd-ghost/

**Comment by terenc3t** [comment]
The optimized version we should be implementing is outlined here:
https://github.com/protolambda/lmd-ghost/#optimized-lmd-ghost-by-vitalik-buterin-vitalik

The reference implementation in python:
https://github.com/protolambda/lmd-ghost/#optimized-lmd-ghost-by-vitalik-buterin-vitalik

**Comment by rauljordan** [comment]
Duplicate of #3162
