### ISSUE TITLE
Implement Validator (Client Side) Load Balancing 

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#1970]
Validators (client in this context) could use some load balancing as they are common in today's micro service design with gRPC. 

Helpful resources:
https://medium.com/@ammar.daniel/grpc-client-side-load-balancing-in-go-cd2378b69242
https://grpc.io/blog/loadbalancing

**Comment by prestonvanloon** [comment]
In our cluster, we've opted to use istio's headless load balancing.
