### ISSUE TITLE
Validator Proposes At Slot 0

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1979]
Currently a validator is assigned to propose at slot 0, which will fail as the current state will have a slot of 1 and proposing at slot zero doesn't make sense as that is taken up by the genesis block.

**Comment by terenc3t** [comment]
This has always been working before though? Is this a regression?

**Comment by nisdas** [comment]
Its actually been like this for a while, we just haven't spotted it. It shows up in commits from more than a week ago. So I am not sure where it broke

**Comment by terenc3t** [comment]
I see. I think `Priority: High` is more appropriate since we are not sure if this is the root cause of proposer can't propose and what impact this issue has
