### ISSUE TITLE
Use Previous Block Root From State instead of Saved Block

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1980]
Currently we retrieve the chain head and hash it to generate the previous block root for state transitions. We should instead be using the previous block root from the state. This would solve some edge cases for us in sync. Ref: https://github.com/ethereum/eth2.0-specs/issues/692#issuecomment-472346984

**Comment by kushagrasharma** [comment]
I can work on this

**Comment by prestonvanloon** [comment]
@rauljordan can you add a comment why this should be closed? Please reference commit or PR.

**Comment by rauljordan** [comment]
This has been fixed by #2003
