### ISSUE TITLE
Default Config Struct for State Transition

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#2008]
We are starting to see a pattern in which we want to pass extra parameters to state transition. A good plan is to have a config struct that has some default config we can use when calling state transition if it is in nil.
This is will be an improvement over #2001 where the function argument will be more readable than just passing a bunch of bool parameters to the function

**Comment by prestonvanloon** [comment]
I don't like this pattern and I think we can do better by properly abstracting the methods. We shouldn't be passing additional arguments to dictate the behavior of some method(s), in my opinion.
