### ISSUE TITLE
Initial sync panics

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2039]
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/blockchain/fork_choice.go#L35

https://gist.github.com/prestonvanloon/9c94ca21042d517f61ee6b709ac7bae5

**Comment by prestonvanloon** [comment]
#2041 WIP

**Comment by rauljordan** [comment]
This can be closed post #2050

**Comment by prestonvanloon** [comment]
Closed in #2041
