### ISSUE TITLE
Documentation lacking for db.HistoricalStateFromSlot

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2149]
https://github.com/prysmaticlabs/prysm/blob/89531c16679c1782aafbca1eca8b9469b37c6f51/beacon-chain/db/state.go#L294

**Comment by prestonvanloon** [comment]
In progress by @JerryFireman Thanks!

**Comment by rauljordan** [comment]
Fixed by #2173
