### ISSUE TITLE
Drop Peer and Restart Initial Sync If State Root Mismatches When Exiting

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2155]
In InitialSync, once we attempt to exit, we verify the state root we have matches the one we received from our peers during the chain head query. If it does not match, we should drop the peer and instead restart the initial sync service to retry with another peer.

**Comment by cyberbono3** [comment]
i can start working on it

**Comment by rauljordan** [comment]
Fixed by @prestonvanloon
