### ISSUE TITLE
Cannot verify attestations if justified epoch is farther away than latestBlockRootsLength in state

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2159]
https://github.com/prysmaticlabs/prysm/blob/40ade64ffad46716da703e340ea29b09a371dbcf/beacon-chain/core/blocks/block_operations.go#L494-L508

Very similar to #2153

We should be looking at the database rather than these cached block roots in the state.

**Comment by rauljordan** [comment]
Fixed by #2160
