### ISSUE TITLE
Add flag to disable logging of rewards/penalties in validator client

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2190]
In a cluster deployment, we aren't so interested in logging this information.

The task is to add a flag `--disable-rewards-penalties-logging` to the validator client.

**Comment by frederickalcantara** [comment]
I would like to take on this issue. Is there a specific function that would need to get to get this flag to work?

**Comment by frederickalcantara** [comment]
This issue was resolved and got pushed to the master branch.
