### ISSUE TITLE
Regular Sync Inserts PostChainStart Deposits Again Into the State

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2199]
This is part of #1586. We have a major bug in which after restarting a node, regular sync processes previous post-chainstart deposits again into the state, leading validators to double their money. We should not allow this to be the case.

**Comment by prestonvanloon** [comment]
This happens consistently under the following conditions:
- Some post chainstart validators have their deposits included in blocks, but they are not yet activated
- In a multi-node scenario (possibly single node as well)

**Comment by prestonvanloon** [comment]
i think there are three (or more) problems here:
- pending deposits are not properly pruned after sync startup
- pending deposits are not verified not to have been already included in the blockchain when requesting via RPC
- pending deposits are not verified not to have been already included in the blockchain when processing a block with new deposits

**Comment by prestonvanloon** [comment]
I recommend solving from the bottom up. So in this order: 
- reject blocks that have duplicate deposits
- prevent serving duplicate deposits via RPC
- properly prune pending deposits on sync

**Comment by prestonvanloon** [comment]
We should include the spec change from PR https://github.com/ethereum/eth2.0-specs/pull/594 & PR https://github.com/ethereum/eth2.0-specs/pull/709.

This change has a deposit index that must be equal to the state.deposit_index.

https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#process_deposit

```python
def process_deposit(state: BeaconState, deposit: Deposit) -> None:
    """
    Process a deposit from Ethereum 1.0.
    Note that this function mutates ``state``.
    """
    # Deposits must be processed in order
    assert deposit.index == state.deposit_index

    ...
```

**Comment by prestonvanloon** [comment]
Pending deposits can be dropped on the following condition:
- deposit.index < finalized_state.deposit_index

Pending deposits can only be served via RPC on the following condition:
- deposit.index < current_state.deposit_index

New blocks can be considered valid with deposits only if deposits are processed in order where:
- deposit.index == state.deposit_index
