### ISSUE TITLE
Running the Beacon Chain Docs Error (MacOS & Linux)

### ISSUE THREAD

**Issue by frederickalcantara** [prysmaticlabs/prysm#2200]
In the docs of the readme file, it states that in order to run the beacon you had to type in the following in the argument command line. 

`bazel run //beacon-chain \ 
  --deposit-contract DEPOSIT_CONTRACT_ADDRESS`

What happened when I did this: I received the following error `[2019-04-07 20:17:28] FATAL node: No deposit contract specified. Add --deposit-contract with a valid deposit contract address to start.` 

The fix to this issue is to do the following: 

`bazel run //beacon-chain -- --deposit-contract=DEPOSIT_CONTRACT_ADDRESS`

The -- needed to replace the \ and the flag --deposit-contract needed to be equal to a value.

**Comment by nisdas** [comment]
Resolved by #2201
