### ISSUE TITLE
Validator balances are not consistent after reorgs

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2229]
![image](https://user-images.githubusercontent.com/7246818/55919187-e8430480-5bc2-11e9-99cd-13dca4b1758f.png)

**Comment by rauljordan** [comment]
This is not necessarily upon a reorg - it happened in our latest cluster run at around slot 8000 after a manual rolling restart began

**Comment by prestonvanloon** [comment]
![image](https://user-images.githubusercontent.com/7246818/56063456-a7a9dd80-5db2-11e9-87d8-bde3418b5459.png)

May be possibly related to #2199 which should be solved by #2232

**Comment by prestonvanloon** [comment]
It's not related to #2199. This screenshot is a run with #2232 included.

![image](https://user-images.githubusercontent.com/7246818/56065620-b5faf800-5db8-11e9-94bd-367e03a21777.png)

**Comment by rauljordan** [comment]
This is no longer the case with the new fork-choice rule. We will close for now unless this issue ever pops up again.
