### ISSUE TITLE
Set bitfield replaces existing bitfield

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2230]
This [line](https://github.com/prysmaticlabs/prysm/blob/master/shared/bitutil/bit.go#L22) from set bit assumes there's no aggregation and the bitfield is only represented by *one* validator since it overrides. We'll need to fix this when we support aggregation

Example:
1.) Before `01001111`
2.) After setting bit for validator at index 0: `1000000`
3.) But it should be `11001111`

**Comment by nisdas** [comment]
@terenc3t we currently do not do any aggregating yet,  we just take an index and set the bitfield for it. We would have to change the function to take a previous bitfield as an argument. We dont aggregate it anywhere in our repo now, so I dont know what the advantage of this would be

**Comment by terenc3t** [comment]
Correct, and as issue specified our set bit doesn't support aggregation, this is to track that we do not support aggregation so we are aware when things start failing when we implement this feature.

It's not an advantage, it's a needed feature for aggregating/verify aggregating signature : )

**Comment by nisdas** [comment]
@terenc3t ah got it, yeah sounds good :+1:. Definitely something we would need to implement later

**Comment by prestonvanloon** [comment]
This is resolved with new abstraction for go-bitfield in spec-v0.6 branch #2312
