### ISSUE TITLE
Sync: Beacon nodes should continue with their local chain on restart if peers have no data or less canonical slot number

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2241]
Imagine this scenario with 3 beacon nodes running in some unstable environment. All three are rebooted at the same time. They attempt to sync with each other, but none of them report the canonical head correctly so none of the nodes reach a valid state.

**Comment by rauljordan** [comment]
Update on this issue @prestonvanloon ?

**Comment by prestonvanloon** [comment]
This is a disaster scenario where the whole network goes offline at once and there is no one to sync with. I don't think it's relevant at this point, given our testnet stability
