### ISSUE TITLE
Validator client crashes when it loses connection with its beacon chain node before it's activation

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#2243]
This is an issue for the bug where the validator client crashes if the beacon chain node it is watching goes offline for any reason before the validators activation epoch. 

Once the validator is activated it retries the connection just fine as it should. However the client should have this behavior pre-activation as well.

And example of the error log is:
```
[2019-04-12 23:19:51] FATAL validator: Could not wait for validator activation: could not receive validator activation from stream: rpc error: code = Unknown desc = rpc context closed, exiting goroutine
```

**Comment by rauljordan** [comment]
This is not really relevant nor important anymore. If users do complain about this aspect, we can revisit, but this has been open for way too long and there are more important issues to tackle.

**Comment by prestonvanloon** [comment]
Re-opening because it is annoying and should be fixed.
