### ISSUE TITLE
Validator ejection doesn't work

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2249]
I am seeing balances continue to decrease below the validator ejection threshold.

![image](https://user-images.githubusercontent.com/7246818/56092449-36d5f480-5e8a-11e9-8425-644f0a9226ee.png)

You can see the balances drop below 0.016 and continue to drop. The active validator count does not decrease either.

**Comment by shayzluf** [comment]
working on it
