### ISSUE TITLE
Do not allow building on bad block

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#2268]
We currently process block if block's parent exists in DB, this does not consider the scenario when reorg happened but the new incoming block's parent is not in the canonical chain but it is in DB. Processing such invalid block (invalid meaning parent block not in the current chain) triggers errors such as:

```
ERRO[0048] Could not apply state transition: could not execute state transition with block could not execute state transition could not process block: could not process block attestations: could not verify attestation at index 0 in block: expected attestation.JustifiedEpoch == state.JustifiedEpoch, received 229 == 224  prefix=state-replay
```

Example diagram: 
(`block j` can only point to `f and g`, not `h and e`. We currently allow pointing to `h` and `e` happen):
<img width="524" alt="Screen Shot 2019-04-15 at 9 19 30 PM" src="https://user-images.githubusercontent.com/21316537/56181851-2d50a780-5fc4-11e9-8b74-7cb846be9d04.png">

**Edit:**
Descriptions above is not as critical as I thought, when it happens we could just log an error and continue. Bigger issues are outlined in https://github.com/prysmaticlabs/prysm/issues/2268#issuecomment-483511329

**Comment by prestonvanloon** [comment]
Why is it a problem if `J` points to `H`? Imagine if some node is not aware of the lower chain in the diagram. It is valid to produce `J` which has a parent `H`.

The error in the issue seems to be that we are including attestations from the lower chain in the upper chain.

**Comment by prestonvanloon** [comment]
Based on offline (discord) discussion, we have concluded that we have the following issues:

1. Bad blocks are not deleted from DB and therefore we accept peers building upon them
2. Attestations RPC may serve invalid attestations from another chain

**Comment by rauljordan** [comment]
If a block failed processing in our node due to our node having different attestations, once we receive a new block from another node building on that failed block, the base case of our recursive block ancestor fetching in regular sync **will be the failed block**. Even though a block fails processing, we still save it to the DB. Instead, we should delete and clear it out.

**Comment by nisdas** [comment]
One way to make sure that we do not allow building on a bad block, is to check whether the parent block is in the canonical chain. How we do it is very simplistic : 
- Receive Block
- Check if Parent is saved in db 
- The Process it 

what we should be doing instead is 
- keep track of all block roots in the canonical chain
- receive block
- If a block's parent isnt in the canonical chain, we reject processing the block as it is on a forked chain.

**Comment by nisdas** [comment]
Design for this over here: https://docs.google.com/document/d/1W6rgetZqdYAbxSCZys-KapqUlZgkDv0rxSkXhGhasFs/edit?usp=sharing
