### ISSUE TITLE
Address error feedback in #2270

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2272]
why does this need to be a struct ? we can use a function for this, where you input the error, and it adds the block error message to the inputted string

_Originally posted by @nisdas in https://github.com/prysmaticlabs/prysm/pull/2270/files_

We agreed offline that trivial string errors should be [errors.New](https://godoc.org/errors#New) rather than a complex struct.

**Comment by prestonvanloon** [comment]
Looking at this a bit more, it seems the intention is to have some encapsulating error for block processing failures and the only way to do this is to use a struct to wrap the error.

This can be closed if the variable is renamed with the standard `Error` suffix as described here: https://github.com/golang/go/wiki/Errors#naming

**Comment by nisdas** [comment]
Closing this since its been resolved.
