### ISSUE TITLE
Syncing is Possible with a Node with a Different Deposit Contract Address

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#2283]
We do not check if a peer that we are connected to has a different contract address, and if they are we are still able to sync with them. This should not be possible by default. A PR for this would modify our node handshake to check for the deposit contract address.

**Comment by terencechain** [comment]
@nisdas I think we can close this? we check contract address now and alert user to clear db

**Comment by nisdas** [comment]
@terencechain yeap this can be closed, its already been addressed
