### ISSUE TITLE
Rate limit peers issuing block requests

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2285]
Currently, bad peers might spam our nodes with thousands of block requests per second - we must prevent that by either dropping the peer or rate limiting the response.

**Comment by prestonvanloon** [comment]
Rate limiting in the p2p layer is a concept that needs careful design. We more likely need to build a reputation system where healthy peers can send virtually unlimited messages to indicate new information with occasional requests for information in bulk. The reputation would lower if a given peer suddenly started requesting loads of data. Once a reputation is low enough then the peer is disconnected or throttled.

I see two parts to this system:
- Reputation based throttling on incoming messages/requests.
- Reasonable limits on outgoing requests (we shouldn't knowingly spam peers, if we can avoid it) 

The reputation system is more complex and requires a careful design so let's consider the outbound limiting for resolution of this specific issue for now. 

Using the [golang rate package](https://godoc.org/golang.org/x/time/rate), we can set rate limits on a per peer basis stored in some in-memory map which is occasionally cleared if entries are not accessed in some TTL. i.e. we have an algorithm as such:

- call p2p.Send(msg, specificPeer)
- lmt = limitCache.get(specificPeer) // resets cache TTL
- lmt.LimitReached() // log WARN if limit reached
- lmt.Wait() // Wait for limit to allow the request to continue
- continue request to peer

Note: the cache must be eagerly pruned of TTL entries as the scenario where a peer disconnects and never returns is the likely cause for a TTL to expire. In this scenario, lazy deletion will not work as we may never `Get` for that same peer ID again. 

One thing to consider is a circuit breaker if there are `n` goroutines waiting for the limit, we may start dropping send requests all together with an error. For example, if there is some accidental infinite loop that spams requests as fast as the CPU will allow.

**Comment by rauljordan** [comment]
This functionality already exists in Prysm, closing
