### ISSUE TITLE
Handle Forked Chain Block

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#2286]
We should be properly handling forked chain block with the following:
```
If we receive bad blocks:
	discard it/ do not save it in db
If we receive blocks from forked chain:
	update attestations targets, save it in the db because the block can be head again
else:
	process the block 
```

Issue today:
1.) we save attestation targets even though the block is bad (bad signature/bad data)
2.) we don't handle receiving blocks from forked chain

**Comment by rauljordan** [comment]
How do we know if we're receiving blocks from a forked chain? Are we using a canonical block roots map?

**Comment by terenc3t** [comment]
@rauljordan that's the idea. Pass parent slot number and parent hash to the below

```go
// IsCanonical returns true if the input block hash of the corresponding slot
// is part of the canonical chain. False otherwise.
func (c *ChainService) IsCanonical(slot uint64, hash []byte) bool {
	c.canonicalBlocksLock.RLock()
	defer c.canonicalBlocksLock.RUnlock()
	if canonicalHash, ok := c.canonicalBlocks[slot]; ok {
		return bytes.Equal(canonicalHash, hash)
	}
	return false
}
```

**Comment by nisdas** [comment]
@terenc3t how do we know what the parent's slot number is ? Do we request it the parent block then if it doesnt exist locally

**Comment by terenc3t** [comment]
we should be able to input parent block hash and get the its slot back in DB, if not we should make that happen : )
