### ISSUE TITLE
Automatically Resolve Deposit Contract Address from k8s

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2287]
Hi all,

Instead of the bad user experience of people having to paste in a deposit contract address when they want to sync with our cluster, our Prysm nodes can automatically resolve the latest one from our configuration map in our kubernetes cluster. We would need to expose this via some endpoint in our prylabs domain.

**Comment by rauljordan** [comment]
@prestonvanloon would you be interested in exposing the endpoint if it won't take up too much time?

**Comment by prestonvanloon** [comment]
Done in #2303.

https://beta.prylabs.net/contract
