### ISSUE TITLE
Add Regression Test for Preventing Double Activation of Validator

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2289]
Hi all,

When we activate validators in update registry, we shouldn't activate those that are already active. This is solved in #2069 by adding a `!helpers.IsActiveValidator` condition when attempting to active, however, this needs a regression test to ensure it works as intended.

**Comment by prestonvanloon** [comment]
This area of logic is missing code coverage in general. 

![image](https://user-images.githubusercontent.com/7246818/56373377-c8b56880-61ce-11e9-819a-5c3b0a86f337.png)

https://github.com/prysmaticlabs/prysm/blob/0cb440c5c77ac06def520676a7a9c7801367e1e4/beacon-chain/core/validators/validator.go#L321-L344

**Comment by frederickalcantara** [comment]
@rauljordan I'll take on this issue.

**Comment by rauljordan** [comment]
This has been revamped since the past few releases and is no longer the case
