### ISSUE TITLE
Prune Blacklisted Block Hashes Past FinalizedState

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2298]
As a follow-up to #2297, we should prune the map of blacklisted block hashes once we have a new finalized state. At that point, all block hashes that came before the new finalized state can be safely deleted, as those blocks will never be considered again.

**Comment by JerryFireman** [comment]
I'd like to take this one on.

**Comment by rauljordan** [comment]
Wondering if this is still relevant given our sync+p2p has changed radically since April. @prestonvanloon could you chime in? I don't think we use the blacklisting hashes strategy anymore. Feel free to close if this issue is no longer relevant.

**Comment by rauljordan** [comment]
Outdated, we no longer use this approach in Prysm
