### ISSUE TITLE
Restructure Our First Release Around Beacon Chain

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#230]
Hi all,

Over the past few months, we have been working on finalizing the Minimal Sharding Protocol Spec put out by Vitalik a while back. This was originally created as a development target for sharding client teams while phase 1 decisions were still under review. Since then, a lot of work has been done on determining the most reasonable path forward for a sharding implementation, and a lot of news have been shared about Casper Proof of Stake and Sharding merging through something called a [random beacon chain](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?both).

Instead of having the sharding and Casper systems managed independently through two smart contracts on the Ethereum main chain, the latest research has advocated for the creation of a full PoS side chain that implements Casper and serves as the backbone of sharding moving forward. This PoS chain uses a RANDAO mechanism for committee reshuffling and built-in pseudo-randomness that is necessary for sharding.

This beacon chain construct has been [well-documented](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?both) and is the current focus of all the other casper/sharding teams. We are **updating** our set of requirements for our first release to focus around this beacon chain and as such, we will revise all of our current open issues/PRs to reflect this.

Our first release requirements document is kept [here](https://docs.google.com/document/d/125ajrN-0cKGwAMlv_bi02MKzGUxMDC_TeDvHCpqAKAs/edit#heading=h.60f99229mfjn) and our beacon chain design doc is [here](https://docs.google.com/document/d/1lTDUy6JwRGNE4rDKiyzaV-lxhG2SZ2F6wCthM-QCSFQ/edit#). Our beacon chain repository will be implemented [here](https://github.com/prysmaticlabs/beacon-chain).

After designing our beacon chain implementation, we will be replacing the Sharding Manager Contract in this repository with methods for a beacon chain interface we will initially implement as no-ops. Our sharding implementation has almost zero dependencies on Geth, which is why as we integrate the beacon chain into this repo, we can gradually eliminate all peripheral geth packages and migrate into our own build system.

**Comment by prestonvanloon** [comment]
@rauljordan What are the requirements to close this issue? 

If we are talking about phase 1 Ruby, does an update to the [Ruby PRD](https://docs.google.com/document/d/125ajrN-0cKGwAMlv_bi02MKzGUxMDC_TeDvHCpqAKAs/edit) satisfy this issue?

**Comment by rauljordan** [comment]
Good Q. Yes I think having an updated PRD with an idea of what we want to release will be enough to close this. I'd like to hold off until we make more progress on the beacon node.
