### ISSUE TITLE
Change fatal validator condition

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2384]
Validators currently have a fatal condition here:
```go
time="2019-04-25 19:49:44" level=fatal msg="Could not determine if beacon chain started: could not receive ChainStart from stream: rpc error: code = Unavailable desc = no healthy upstream" prefix=validator
```
This leads to crash loop backoffs and all sorts of other issues in our cluster.

**Comment by prestonvanloon** [comment]
This is specifically for the gRPC stream while waiting for activation. The validator should retry to open the stream rather than fatally crash.

**Comment by katzdan** [comment]
I would like to try and fix this one. Might need help in instructions for re-creating this issue.

**Comment by prestonvanloon** [comment]
I believe this was fixed, but I don't recall the specific PR number.
