### ISSUE TITLE
Tagging a Testnet Release

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2457]
In order to wrap up and finish up a testnet release:

- [x] Recommend --clear-db for testnet users to prevent unresolvable error conditions on restarts
- [x] On querying chain head, poll forever until the first response is received, then begin a timeout to receive more chain head responses
- [x] RPC service for querying validator activation
- [x] Minor changes to our website, giving users more options to obtain faucet funds or other ways of installing Prysm by linking to the Gitbook docs
- [x] Break ties in fork-choice

**Comment by terencechain** [comment]
- [ ] UI for latest block roots

**Comment by terencechain** [comment]
I can take on `Enable --clear-db in all nodes by default`

**Comment by rauljordan** [comment]
Working on fixing the chain head query

**Comment by terencechain** [comment]
Confirmed we won't delete DB by default, we'll add explicit instructions for users to clear db when restart
