### ISSUE TITLE
Add ARM support 

### ISSUE THREAD

**Issue by penta314** [prysmaticlabs/prysm#2546]
It has been found that the binaries are not built for ARM, hence people trying to run a node in for example Rasberry Pi 3 are getting crashes.

**Comment by prestonvanloon** [comment]
This requires build docker images/binaries with `--platforms=@io_bazel_rules_go//go/toolchain:linux_arm64`.

The validator client builds for ARM, but not the beacon-chain due to some cgo dependencies in go-ethereum.

**Comment by prestonvanloon** [comment]
I made a brief attempt at trying to cross compile for ARM, but running into weird issues with cgo. 
Commit ea790c5a1340822c617c9ad1a62194d60adf1af9

**Comment by diglos** [comment]
Hi,
It fails compiling directly on ARM64 as well, see attached log.
[beacon-chain-build-arm64.txt](https://github.com/prysmaticlabs/prysm/files/3173036/beacon-chain-build-arm64.txt)

**Comment by prestonvanloon** [comment]
The binaries should build on ARM as of e71e91c9aaa6ddf2a15a6fb329a95b7d88b8a254, but we don't officially support ARM binaries at this time.

**Comment by diglos** [comment]
Hi,
yes, it compiles fine on ARM64, thanks for noticing. I will be doing some testing with this.
Regards!

**Comment by XinyaYang0506** [comment]
@diglos Hi, 
I am trying to use this on raspberry pi, and on the way figuring out how to compile this repo from the source. Can you give me some guidance? thanks!

**Comment by diglos** [comment]
Hi Xinya,
the tricky part is compile bazel for ARM. This is possible on a ARM64 board with 4GB RAM but I don't know if the Raspberry pi can do this. You may try this guide (section 3):
https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md
and, once you have the bazel binary, follow this page instructions to build the prysm validator and beacon chain.

**Comment by XinyaYang0506** [comment]
I will try this, thanks!

**Comment by prestonvanloon** [comment]
I think this was blocked by crosstool rewrite (https://github.com/bazelbuild/bazel/issues/5380).

Most likely, we need to add some cc toolchains for cross compilation. See: https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html

There is a tutorial here for clang: https://github.com/bazelbuild/rules_go/blob/master/go/crosstool.rst

Other artifacts:
- https://github.com/bazelbuild/rules_go/issues/1642
- https://github.com/bazelbuild/rules_go/issues/1020
- https://github.com/bazelbuild/rules_go/issues/2089

**Comment by jbriquet** [comment]
Here are the notes I have taken when compiling bazel for an ARM64 (4 cores A53, 2GB RAM). 
```
Add repository to find openjdk-8 source
sudo add-apt-repository ppa:webupd8team/java

Install JDK8 and dependencies
sudo apt-get install build-essential openjdk-8-jdk python zip unzip

Download Bazel

wget https://github.com/bazelbuild/bazel/releases/download/0.25.3/bazel-0.25.3-dist.zip
unzip bazel-0.25.3-dist.zip -d bazel-0.25.3-dist

Install Bazel on targeted device
cd bazel-0.25.3-dist
export BAZEL_JAVAC_OPTS="-J-Xmx1g -J-Xms200m" \
export EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"  \
./compile.sh


# Successful compilation on ARM64 - 2cores, 4GB

INFO: Elapsed time: 1449.174s, Critical Path: 139.99s
INFO: 1777 processes: 1538 local, 239 worker.
INFO: Build completed successfully, 1824 total actions
```

**Comment by prestonvanloon** [comment]
Thanks @jbriquet! My last comment is referring to cross complation. We’d love to build ARM64 binaries for you without unreasonable build environment, but I am glad to see that you were able to build one after 1450s(!!!). 

ARM builds will soon be a priority for us and we’ll be providing regular ARM binaries for tagged releases soon :)

**Comment by diglos** [comment]
Great news!
I'm releasing beacon-chain and validator binaries in the next Ethereum on ARM release for NanoPC-T4 and RockPro64. So far, they work quite well :-)

**Comment by rauljordan** [comment]
This is resolved by #2970

**Comment by prestonvanloon** [comment]
I can verify that building on linux amd64 for arm64 works.

bazel build //beacon-chain //validator --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64

**Comment by prestonvanloon** [comment]
Recent BLS PR has broken ARM builds #3670. Reopening this issue for tracking.

**Comment by diglos** [comment]
Hi,
I just ran into this issue trying to compile Prysm for the Raspberry Pi 4. Thanks for reopening this.

**Comment by diglos** [comment]
Hi,
Any ETA to fix this?
Thanks!

**Comment by nisdas** [comment]
hey @diglos , with #4181 merged in, we have ARM support added in

**Comment by diglos** [comment]
Hi,
Thanks @nisdas.
It compiles on ARM64 (NanoPC-T4) but fails on ARM32 (Raspberry Pi 4) for both, beacon chain and validator. Please check attached log.

[prysm-arm7-error.txt](https://github.com/prysmaticlabs/prysm/files/3927163/prysm-arm7-error.txt)

**Comment by nisdas** [comment]
hey @diglos , thanks for testing this out. It seems like we might not be giving the correct archive for bls, I will try and see where it fails

**Comment by wikidemic** [comment]
There’s an army of RPi4 standing by to join test network.  
Any progress towards successful compile yet?

**Comment by nisdas** [comment]
Hey sorry currently we haven't been able to get it to work on arm32 yet, only arm64 is currently supported. I havent been able to dedicate the time to resolving this, I hope this can be done soon

**Comment by mangoleap** [comment]
I'm trying to get it to run on a NanoPC T4 (ARM 64). Installed docker and pulled the images.

When I run 

`docker run -v $HOME/prysm-data:/data -p 4000:4000 --name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:latest --no-genesis-delay --datadir=/data`

I get the error

`standard_init_linux.go:211: exec user process caused "exec format error"`

That's all, nothing else. Any idea how to proceed?

**Comment by wikidemic** [comment]
I 

> I'm trying to get it to run on a NanoPC T4 (ARM 64). Installed docker and pulled the images.
> 
> When I run
> 
> `docker run -v $HOME/prysm-data:/data -p 4000:4000 --name beacon-node gcr.io/prysmaticlabs/prysm/beacon-chain:latest --no-genesis-delay --datadir=/data`
> 
> I get the error
> 
> `standard_init_linux.go:211: exec user process caused "exec format error"`
> 
> That's all, nothing else. Any idea how to proceed?

@diglos seems to be on the ball here.  If you don’t answer for your docker image question, suggest you look up diglox image here on github - diglos/userpatches.    

I’m considering NanoPC T4 purchase from Friendly Arm this week.  So I’m tracking developer responsiveness here before I pull trigger.  Let us know if you make progress!

**Comment by prestonvanloon** [comment]
The current docker image is compile for AMD64 so it will not work on ARM64. It's not compiled for ARM and I am not sure about any workaround. 

To give you guys a sense of timeline, we most likely won't get to this until after the holiday. 

We'd welcome anyone to attempt a resolution here. I have a few ideas if someone wants to attempt resolving builds for ARM64.

**Comment by diglos** [comment]
Hi @mangoleap.

Are you running a Ethereum on ARM image?. If so, you can install it by typing (it is a very recent package):

`sudo apt-get update && sudo apt-get install prysm-beacon prysm-validator`

@prestonvanloon, @wikidemic, it compiles fine on ARM64 (NanoPC-T4 and RockPro64) after  #4181 merged. ARM7 (Raspberry Pi 4), doesn't work at the moment.

**Comment by mangoleap** [comment]
@diglos That worked, thank you!

If anyone wants to try it:

Config files are at
```
/etc/ethereum/prysm-beacon.conf
/etc/ethereum/prysm-validator.conf
```

Chain and validator can be started with
```
sudo systemctl start prysm-beacon
sudo systemctl start prysm-validator
```

Auto start up on boot can be enabled with
```
sudo systemctl enable prysm-beacon.service
sudo systemctl enable prysm-validator.service
```

Real time output from both services can be watched with
```
sudo journalctl -u prysm-beacon -f
sudo journalctl -u prysm-validator -f
```

**Comment by rauljordan** [comment]
Done by @SuburbanDad and included in our https://docs.prylabs.network

**Comment by jgresham** [comment]
Link to install docs: https://docs.prylabs.network/docs/install/arm/

**Comment by wikidemic** [comment]
I just attempted to load the ‘Unofficial’ version(2.1.0) of Bazel for ARM architecture using docs below.  Unfortunately, it did not work as the current version is now at 2.2 and does not incorporate this Arm edit (by SuburbanDad)

I haven’t coded in quite a while so I cann’t offer too much detail other than saying Bazel doesn’t load on my RPi4.  Installation script error notes that Unofficial Bazel isn’t current version and references a config file that requires editing before it is happy.

Hope that helps.
Mc

**Comment by SuburbanDad** [comment]
@wikidemic prysm has pinned to bazel 2.1.1 for now.  I added an arm64 build of 2.1.1:
https://github.com/SuburbanDad/bazel/releases/tag/2.1.1

give it a whirl

**Comment by jgresham** [comment]
@SuburbanDad Should the bazel binaries on your releases work on a raspi4? I having issues after running step 3 from here https://docs.prylabs.network/docs/install/arm/ so I am trying to build prysm from source. 

Here is the result from trying to use your bazel binaries on raspi4:
```
pi@raspberrypi:~/prysm $ ./bazel --version
-bash: ./bazel: cannot execute binary file: Exec format error
pi@raspberrypi:~/prysm $ file bazel
bazel: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=09b54219645538b60aaaf5829af803cf3fad9fd4, not stripped
```

Here is result from trying to run prysm on a raspi4:
```
pi@raspberrypi:~/prysm $ ./prysm.sh --clear-db --datadir=$HOME/prysm
pi@raspberrypi:~/prysm $ ls dist/
beacon-chain-v0.3.4-linux-armv7l  validator-v0.3.4-linux-armv7l
pi@raspberrypi:~/prysm $ ./prysm.sh beacon-chain
Latest Prysm version is v0.3.4.
Beacon chain is up to date.
Validator is up to date.
Starting Prysm beacon-chain
/home/pi/prysm/dist/beacon-chain-v0.3.4-linux-armv7l: line 1: Not: command not found
```

In the meantime, I am trying to build bazel 2.1.1 on a raspi4.

**Comment by SuburbanDad** [comment]
Hey @jgresham,

I am guessing you are running raspbian on you pi?  You need to run a 64 bit
operating system like Ubuntu to build and run prysm, and unfortunately
raspbian is 32 bit.

Good luck

**Comment by amaurer** [comment]
I found that the attempted download of the binaries failed from https://api.github.com/repos/prysmaticlabs/prysm/releases/latest

Line one of the binary file was "Not Found" which resulted in an error - `line 1: Not: command not found`

Turns out I was hitting the rate-limit imposed by github for unauthenticated requests.

```{"message":"API rate limit exceeded for x.x.x.x . (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}```
