### ISSUE TITLE
LMD ghost is reading from DB too frequently

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2552]
![image](https://user-images.githubusercontent.com/7246818/57497146-6e2a9c00-72a4-11e9-8c21-dc2b96cb00d6.png)

This is taking up 3.6s of time to complete while the majority of the work is done from fetching and unmarshalling ancestor blocks since finality. Suggestion is to keep these objects in memory and prune them on every new finalized epoch. This will greatly reduce the time taken to calculate LMD ghost according to the above flame graph.

**Comment by terencechain** [comment]
I'm looking into this
