### ISSUE TITLE
Could not process beacon block

### ISSUE THREAD

**Issue by ligi** [prysmaticlabs/prysm#2567]
just tried to run - but getting the following error:

`[2019-05-11 10:50:56] ERROR regular-sync: Could not process beacon block: block failed processing: could not process block: could not process block attestations: could not verify attestation at index 0 in block: expected attestation.JustifiedEpoch == state.PreviousJustifiedEpoch, received 21277 == 21276`

on commit d1fa88ce4bfb8e88d317058dfe7b1efed7d14c62

started via

`bazel run //beacon-chain -- --clear-db --datadir=/tmp/prysm-data`

**Comment by Skretch** [comment]
Uncertain if this is the same issue, but I got an error that looks very similar.
`ERROR regular-sync: Could not process beacon block: block failed processing: could not process block: could not process block attestations: could not verify attestation at index 119 in block: expected attestation.JustifiedRoot == state.JustifiedRoot, received 0x3c50faa946e027d035ac6859cf68d2f7c09e5c968701f3304ef561699e60edee == 0xd14c366808937137915bc751cf68370a6cda25d821dfb36db8cec806c8f54bfc`

<img src="https://i.gyazo.com/2cf270e55811eece05af0fc42d7346dd.png">

started via

`docker run -it -v /tmp/prysm-data:/data -p 4000:4000 gcr.io/prysmaticlabs/prysm/beacon-chain:sapphire --datadir=/data --clear-db`

**Comment by prestonvanloon** [comment]
This seems like a bug on the validator / block producer side. Somehow you are receiving a block that is not valid.

**Comment by Skretch** [comment]
Don't know if this will be helpful but got this error seconds after my validator was assigned a proposerSlot.
see 15:28:48
<img src="https://image.prntscr.com/image/qEU3zcdITEuXIuh7PXMnMg.png" width="300">
<img src="https://image.prntscr.com/image/7rDtEUk1QZ2eE8d-mDfOJw.png" width="300">

**Comment by jp8080nl** [comment]
I'm getting these errors a lot.
Can I provide more details somehow?

**Comment by rauljordan** [comment]
This is resolved by our new fork choice using the --next flag in our latest master. The problem was old fork choice did not handle network partitions well nor handling blocks that would be invalid from our chain's point of view.
