### ISSUE TITLE
Validator reporting incorrect loss after depositing 6.37 GoEth

### ISSUE THREAD

**Issue by Skretch** [prysmaticlabs/prysm#2573]
Validator is reporting a 50% loss when it splitt into two validators after I deposited 6.37 GoETH

<img src="https://i.gyazo.com/72b0143217e321b802b45386703e03cb.png">

**Comment by prestonvanloon** [comment]
This seems like a reporting issue with the balance-at-stake measured against the total deposit value. When you deposit multiple times, you are only earning interested from the first 32 ETH at stake. 

This is definitely something we need to fix, but you're not losing 50% money :)

**Comment by ethDreamer** [comment]
@prestonvanloon It looks like he made the deposit to TWO separate validator public keys in which case he IS earning interest from both deposits. The validator is simply reporting his initial balance incorrectly.

**Comment by prestonvanloon** [comment]
@ethDreamer Yep! I think that's the issue. It's a cosmetic / reporting problem only.

**Comment by katzdan** [comment]
I would like fix this issue.

**Comment by zediir** [comment]
There's already some work done here https://github.com/prysmaticlabs/prysm/pull/2771

**Comment by terencechain** [comment]
Closed via #2995

**Comment by prestonvanloon** [comment]
@terencechain #2995 was never merged. Should this be closed?
