### ISSUE TITLE
JSON log output for testing

### ISSUE THREAD

**Issue by mslipper** [prysmaticlabs/prysm#2574]
Hi Prysmatic team,

Antoine Toulmne and I are working on an ETH2 test runner that needs access to the state of the clients under test at each block. Currently, we're doing this by exposing a JSON log with the following format:

```
{
   "date":1557296388510,
   "index":1,
   "slot":1,
   "epoch":0,
   "block_root":"0x774D273A6A67482FAA5627A3F3CD3D55E2074EC89BDCC448873DA7B0F3F52C1B",
   "block_parent_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "block_body":"0x0DE2E04B0BF89EFEC669C00EF41BE42E8F93218B85CC6272C6CCD95B8399648D",
   "last_justified_block_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "last_justified_state_root":"0x38F7F34A166FB777C8647C66725F12454DCED268024BA5054C20ABF31CE7A213",
   "last_finalized_block_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "last_finalized_state_root":"0x38F7F34A166FB777C8647C66725F12454DCED268024BA5054C20ABF31CE7A213",
   "validators":[
      {
         "pubkey":"(05209b1ea72bd2c1a430cda13d79cfbe617694c18b374a0fbf2a85aa74f6f582373f4ace1ac7b996969bc7540125ce84,08b081dc8249ef361d17510d17a193a7aee28940a9ab1fba742c1f7f9a3f9cf1288a767efcd37c750e91a8d0cf408b1f)",
         "balance":"32000000000"
      }
   ]
}
```

We were thinking that the log would be exposed by either:

1. A CLI flag to write the log to the specified directory.
2. A JSON-RPC endpoint to get the log at a specified block.

Which would your team find more amenable, and what do you think of this approach in general? To make things easier, we're happy to implement this and open a PR.

**Comment by terencechain** [comment]
Would the test runner support protobuf? It would be easy to write an end point in our RPC server for the data test runner want using lib like [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb)

**Comment by prestonvanloon** [comment]
This also seems like something ideal for streaming events. Is it read on the fly and monitored or processed post test run?

**Comment by prestonvanloon** [comment]
Also any thoughts to a push gateway? I'd like to understand the use case a bit more. Do you have more details you could share?

**Comment by mslipper** [comment]
> Do you have more details you could share?

We're looking to support a number of different test cases within the runner:

1. Consensus spec compliance (i.e., via the YAML tests).
2. Networking spec compliance.
3. When they are developed, RPC spec compliance.

We'll perform testing both for single clients (i.e., by running the test suite against a 7-node Prysm cluster) and multiple clients (i.e., by running the test suite against a 7-node Prysm/Lighthouse cluster) for each of the above items. From there, we'll branch out into performance + stress testing. The goal of the JSON log specifically is to allow us to make assertions about the state of each node within a test cluster without having to standardize RPC interfaces immediately. In sum, the JSON log is a testing tool _only_ that we expect to be replaced eventually once RPC interfaces solidify.

> Is it read on the fly and monitored or processed post test run?

I believe we'd process it post test run. The runner is executed as part of a Jenkins job; including the JSON log as part of job results would be ideal for debugging purposes.

> Also any thoughts to a push gateway?

What do you mean by this?

> Would the test runner support protobuf?

We're not currently planning on it.

**Comment by mslipper** [comment]
Update: @atoulmne will be writing up some example code to illustrate the concept, I'll ping you all when he's done and we can chat. Otherwise, the WS stuff you mentioned if it's similar to Lighthouse's works for us as well.

**Comment by prestonvanloon** [comment]
Just added `--log-format=json` capability in https://github.com/prysmaticlabs/prysm/pull/2594. 
Does this satisfy the need for logs in JSON format?

**Comment by prestonvanloon** [comment]
By push gateway, i meant some service that receives the updates from the processes.

https://prometheus.io/docs/instrumenting/pushing/

**Comment by prestonvanloon** [comment]
Is there a general design doc for this? This seems like a big effort so I'd want to fully understand it as we would likely need to maintain it going forward. I'd also want it to be run on our own pre-submit.

**Comment by atoulme** [comment]
Hey Preston,
We're working on specifying this in more detail.
I have been playing with the code a bit - will push and then we can talk.

**Comment by atoulme** [comment]
Here is the commit: https://github.com/atoulme/prysm/commit/81b6c9b2091ab810d760e0652f4180737188b7ca

**Comment by atoulme** [comment]
I had a chance to catch up with Preston today, and we talked it out.
The best approach is to use their logging infrastructure, and possibly extend how much they're logging by adding more logging statements in the right place.
This is tracked also in #2395

**Comment by prestonvanloon** [comment]
We now support logging to JSON with #2395. Closing this for now. Please re-open if there are more actionable items.
