### ISSUE TITLE
Deposit contract does not allow deposits greater than 32 ETH

### ISSUE THREAD

**Issue by Shammah** [prysmaticlabs/prysm#2590]
I don't know how important this is, but I suspect that if you deposit 33 ETH, the deposit will not count as a full deposit. This means that you'll have to deposit 32 ETH more, totalling 65 ETH, to 'fix' the counter.

According to the spec at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_deposit-contract.md, it holds that:

> A deposit with an amount greater than or equal to `FULL_DEPOSIT_AMOUNT` in Gwei is considered as a full deposit.

Where `FULL_DEPOSIT_AMOUNT` is equal to 32 ETH. Shouldn't it then be the case that

https://github.com/prysmaticlabs/prysm/blob/23880351f8375e7342977d15430fc503a3a77a0d/contracts/deposit-contract/depositContract.v.py#L103

must be

`if deposit_amount >= self.MAX_DEPOSIT_AMOUNT: `

This does seem to be case in the official contract at 

https://github.com/ethereum/deposit_contract/blob/master/deposit_contract/contracts/validator_registration.v.py#L127

**Comment by ligi** [comment]
> must be

> if deposit_amount >= self.MAX_DEPOSIT_AMOUNT:

but this can never be true as for https://github.com/prysmaticlabs/prysm/blob/23880351f8375e7342977d15430fc503a3a77a0d/contracts/deposit-contract/depositContract.v.py#L79
as far as I see

**Comment by Shammah** [comment]
Oh, you're right, I completely forgot about that; I'm a dummy. I got confused for a second because the spec only talks about a minimum deposit, not a maximum deposit.

It's a bit strange, because for example if you'd like to start staking with 33 ETH, you have two ways to achieve this:

1. First deposit 1 ETH, then deposit 32ETH.
2. First deposit 32 ETH, then deposit 1 ETH.

While a bit cumbersome it's pretty minor and unlike what I initially thought, you cannot deposit more than `MAX_DEPOSIT_AMOUNT`. I'll ignore the fact that depositing 16 ETH twice does not trigger a full deposit, as the spec does not indicate it should be either.

**Comment by ligi** [comment]
yea - this is confusing. I think this issue could even be kept open - I am also not sure why there is a max.

**Comment by Shammah** [comment]
I'll let Prysmatic Labs decide what to do with this :)

**Comment by terencechain** [comment]
Thanks the issue @Shammah and @ligi. A better place for this would be: https://github.com/ethereum/eth2.0-specs/issues

Would you guys like to migrate the issue there? I'd be happy to open one for you guys as well

**Comment by ligi** [comment]
hm - as far as I see there is no max in the spec

**Comment by Shammah** [comment]
The spec says that you can deposit an amount bigger than 32 ETH and it'll count as a full deposit. The Prysm implementation simply does not allow a deposit bigger than 32 ETH. So what I thought was the issue as noted in the title, turns out to actually be a deviation in the spec.

**Comment by Shammah** [comment]
This issue is now most likely fixed as part of https://github.com/prysmaticlabs/prysm/pull/2648.

**Comment by nisdas** [comment]
@Shammah Yeap, this is taken care of in the updated deposit contract. Closing this issue now.
