### ISSUE TITLE
Metrics: Validator ejection count increases incorrectly during reorg

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2591]
![Screenshot from 2019-05-13 18-01-50](https://user-images.githubusercontent.com/7246818/57657467-6ff8a600-75a9-11e9-9f00-e44caafa9e6a.png)

See above screenshot. This reported 12,000+ ejected validators when there were less than 700 in the system

**Comment by rauljordan** [comment]
This is no longer the case in our v0.9 testnet
