### ISSUE TITLE
Wanted participants bitfield length Y, got X

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2615]
Multiple uses got the following screen (see screen shots). I suspect #2565 and #2588 didnt fix the bitfield issues through out the whole state transition cycle

<img width="679" alt="Screen Shot 2019-05-16 at 11 25 53 AM" src="https://user-images.githubusercontent.com/21316537/57866640-a9116000-77cd-11e9-848a-f104b5fe3ccc.png">

**Comment by prestonvanloon** [comment]
Holding off investigation until spec-v0.6 in testnet

**Comment by prestonvanloon** [comment]
This should be resolved in #2312.
