### ISSUE TITLE
Aggregate attestation to prevent engress size growing too big

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2616]
Talking with @prestonvanloon, the current engress is getting to be 3TB. One reason is we don't aggregate attestation which Is really inefficient spamming the same attestations through out the whole net work. One optimizaton we could explore to aggregate attestation that we can cut down the grow rate to 128x

**Comment by prestonvanloon** [comment]
@terencechain is there anything blocking this?

**Comment by terencechain** [comment]
Nothing blocking. Anyone can start with a proper design doc

**Comment by rauljordan** [comment]
Resolved by #3149
