### ISSUE TITLE
Server side stream -> client to notify client of reorg; client fetch new assignments

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2617]
Validators fetching assignments every epoch is ideal for a healthy network, however if there is a reorg that is more than one epoch deep then the previously fetched assignments are likely invalid. 

The suggested design here is a reorg notification stream that validator clients can subscribe to and fetch new assignments. This stream is should be very lightweight and simply notify the subscriber that there has been a reorg in general. This should not be specific to the subscriber (do not recalculate assignments for the subscriber in this stream).

- Validator client subscribes to stream
- Server notifies subscribers that there has been a reorg (specifically a deep reorg)
- Validator immediately fetches new assignments

**Comment by rauljordan** [comment]
No longer relevant as assignments are dependent on finality, not on a reorg at a slot
