### ISSUE TITLE
A proposal to aggregate attestation

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2629]
To fix #2616, Here is one proposal on how we can aggregate attestation.

1. Attester wait until middle of the slot to send attestation to beacon node so any blocks from this slot have time to reach the beacon node. Duration is from `0` to `SecondsPerSlot / 2`

2. Beacon node gathers and aggregates attestations. Duration is from `SecondsPerSlot / 2` to `SecondsPerSlot`

3. Beacon node broadcasts packaged attestations every `SecondsPerSlot`

With this approach, we'll update the following:
- beacon node needs a ticker to know when the end of the slot is
- beacon node needs to store attestation in memory and track when an attestation can be aggregated (e.g. same slot, same head root...etc) if aggregation is possible, it simply discards the duplicated the attestation and flip the existing attestation's bitfield to 1 based on the attester index
- beacon node RPC server only broadcasts attestations once every slot

**Comment by nisdas** [comment]
I am not sure I understand why we need to wait in steps 1 or 2. Isnt an attestation for the current head of the chain, why do we have to wait for block proposals ? Why not just have beacon nodes, just store any attestation that comes in, if a new attestation comes in with the same slot and blockroot we aggregate them.

**Comment by prestonvanloon** [comment]
Is this blocked by BLS? I'm wondering what the time delay solves as well. If all clients are waiting some amount of time then the messages would still be received at approximately the same time, after the delay.

**Comment by terencechain** [comment]
No it's not blocked by BLS as we don't verify signature today, just need to flip the bits. 
Time delay allows multiple attestations to pack into one and ease the # of attestation messages propagate in a network

**Comment by rauljordan** [comment]
We currently aggregate attestations in a way that resolves this issue as of latest master
