### ISSUE TITLE
Beacon Node P2P

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#263]
Hi all,

This issue is opened to design the structure of beacon chain p2p and how it will integrate with shardp2p. Since a beacon validator can be multiple roles at once (proposer, attester, etc.), it will need to manage multiple open p2p connections, each at different time points, and each requiring to connect to different networks and find peers within those networks.

This is an open issue for discussion as to how to do this.

**Comment by prestonvanloon** [comment]
Related: #108

**Comment by prestonvanloon** [comment]
This is pretty outdated, but we still do not have a formal design for p2p here.
