### ISSUE TITLE
Public Keys are not in G1

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#2652]
Currently the bls lib we use has its public keys in g2, which makes the compressed pubkey 96 bytes. However the spec has the pubkeys in g1, with compressed pubkeys being 48 bytes. This issue is to track this until it is resolved.

**Comment by prestonvanloon** [comment]
Investigating BLS library solutions this week. If anyone would like to join me in this effort, let me know. Otherwise, I will own this task for now.

**Comment by katzdan** [comment]
@prestonvanloon  - Please let me know if I can help with this issue.

**Comment by prestonvanloon** [comment]
Julian's work supports this now: #2724.

**Comment by prestonvanloon** [comment]
This is done!

#2792
