### ISSUE TITLE
Better debug references for beacon

### ISSUE THREAD

**Issue by jp8080nl** [prysmaticlabs/prysm#2670]
An indicator of sync errors or other issues with beacon node is validator reporting delta >= 0 

I would like to 
 1 export beacon logs (tail 50 - beacon_restart_log_#)
 2 restart beacon
when validator reporting delta >= 0 and epoch_issue_counter = 10
so I have a log with beacon issues and a restart for a new healthy beacon node

Could this be done with a watch-dog method and does it make sense at all?

**Comment by prestonvanloon** [comment]
1) Exporting logs can be done with new flags to log to disk. See #2660 
2) Can you elaborate more on this? We have a health check endpoint at :8080/healthz. This endpoint returns a 200 if everything is healthy and 500 if the server is unhealthy. If you would like some specific health check, we can add it here for your monitoring.

Let me know a bit more about what you're looking for. What is the epoch_issue_counter?

**Comment by jp8080nl** [comment]
Thanks for the information.
I was not aware of healthz endpoint.
We could now just check that endpoint and if unhealthy, export logs and then restart the container.
