### ISSUE TITLE
Could the ejetced validator be back to the active list?

### ISSUE THREAD

**Issue by MattWangming** [prysmaticlabs/prysm#2680]
I have participated in the testnet since last week, due to network issue or somthing else, my validator offten got ejected! I have tried in many ways to get it back but only result in failure. I have to redo the participation process from scratch. #2677 
So here comes my question on the validator participation in the beacon chain:

> according to the  <https://prysmaticlabs.gitbook.io/prysm/how-prysm-works/validator-deposit-contract> of last sentense 
`we emit a ChainStart log which sets the genesis time of Ethereum 2.0 to be 24 hours from when the threshold was reached`. 

This message can be seen from the validator client output. The genesis time is about `24 hours` from the current time. It could really give sufficient time to prepare the clients ready for the networks. 

It`s perfect for the node starting from scratch. But how about the those existing validators who were ejected from the active validator list by network issue, or any other unexpected reasons? What could be done through operation to make them back to the active list?

e.g. a new deposit be sent to the validator via the smart contract to make the deposit value above the lowest validator? Then it could be back to the list?

**Comment by nisdas** [comment]
@MattWangming Hey once a validator has been ejected due to having a balance less than the ejection limit, there isnt a way for the same validator be inducted back into the active validator set.

**Comment by MattWangming** [comment]
@nisdas Thanks for your reply. I mean if there is any design mechanism for the validator`s role life cycle management, e.g.
```
validator(bonded beyond the minimum deposit)-→activated to the active set-→ absent or some misbehavior with result **Eject**-→...
```
What is the following procedure should the validator itself take actively to make it back to the active list again?
There is  some reference in the POS, e.g. cosmos project. Here is some clue on its design explanation:[validator in cosmos](https://github.com/cosmos/cosmos-sdk/blob/master/docs/spec/staking/02_state_transitions.md#validators)
So I think there could also be similar mechanism design here, but I`m not sure...

**Comment by prestonvanloon** [comment]
Hey @MattWangming. This feature won't be present in phase 0. 
We definitely need this feature in the near future, ideally in phase 1.

**Comment by MattWangming** [comment]
Hi @prestonvanloon, thanks for your clarification. Look forward to this feature release to make validator more flexible.

**Comment by MattWangming** [comment]
Close it with positive feedback from core Dev: this feature is under drafting in the following phase 1.
