### ISSUE TITLE
Spec shuffle tests fail

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#2681]
Hi all,

Our shuffle function on PR https://github.com/prysmaticlabs/prysm/pull/2667  
fail to pass spec tests from here: https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/shuffling/core
our current implementation is based on protolambda's version of the spec function:
https://github.com/protolambda/eth2-shuffle

as you can see Proto's tests here https://github.com/protolambda/eth2-shuffle/blob/master/spec/tests.csv
already third case differ from spec test: 
`df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119	3	2:1:0`
spec tests:
`- seed: '0xdf3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119'
  count: 3
  shuffled: [2, 0, 1]`
the spec said to be on the opposite direction (unshuffle) it might be the reason for the diff

this is harmony's java implementation that pass the tests: https://github.com/harmony-dev/beacon-chain-java/blob/develop/consensus/src/main/java/org/ethereum/beacon/consensus/spec/HelperFunction.java#L339
you can see that the order of rounds is the opposite (unshuffle)

Will be great to have a new set of eyes on the code and find the reason it doesn't pass the spec tests

**Comment by prestonvanloon** [comment]
I think @nisdas found a fix for this. Can you confirm?

**Comment by shayzluf** [comment]
I confirm and close it. thanks again @nisdas
