### ISSUE TITLE
Beacon chain node could not execute head transition unexpectedly during the runtime

### ISSUE THREAD

**Issue by MattWangming** [prysmaticlabs/prysm#2683]
The beacon node securing to beacon networks is not stable enough. Latest docker image has been pulled down to run the beacon node locally, after a few minutes` execution, the beacon node could not execute state transition any more with unexpected reason. The validator`s behaviour was also impact by this fault. Here is some log output when error appeared:
```
time="2019-05-24 02:29:49" level=info msg="Chain head block and state updated" headRoot=0x721d14c6dabbedf7d8293524 headSlot=21718 prefix=blockchain stateSlot=21718
time="2019-05-24 02:29:55" level=info msg="Executing state transition" prefix=blockchain slotNumber=21719
time="2019-05-24 02:29:55" level=info msg="Block attestations" attestationsInBlock=64 prefix="core/state"
time="2019-05-24 02:29:55" level=info msg="Block deposits" depositsInBlock=0 prefix="core/state"
time="2019-05-24 02:29:55" level=error msg="Could not process beacon block: block failed processing: could not process epoch: bitfield is unable to be verified" prefix=regular-sync
time="2019-05-24 02:29:58" level=info msg="Executing state transition" prefix=blockchain slotNumber=21719
time="2019-05-24 02:29:58" level=info msg="Block attestations" attestationsInBlock=64 prefix="core/state"
time="2019-05-24 02:29:58" level=info msg="Block deposits" depositsInBlock=0 prefix="core/state"
```
The full docker log could be referred as below:
[beacon0524.log](https://github.com/prysmaticlabs/prysm/files/3214934/beacon0524.log)

**Comment by rauljordan** [comment]
This is a consequence of our v0.4 testnet, which our fork choice would be broken and would have two partitioned chains where a validator would be active in one chain but unknown in another, leading to `cannot verify bitfield` problems. This is a known bug that is resolved by latest changes to fork choice and our updates to the v0.8.1 specification as of latest master.
