### ISSUE TITLE
Linter failing due to upstream breaking change at HEAD

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2688]
This PR https://github.com/joonix/log/pull/13 renames log.FluentdFormatter to log.Formatter. 

This makes travis unhappy: https://travis-ci.com/prysmaticlabs/prysm/builds/113067474

We need to update our dependency and rename the affected lines of code in our project.

**Comment by prestonvanloon** [comment]
It looks like the appropriate usage is `log.SetFormatter(joonix.NewFormatter())`

**Comment by balboah** [comment]
sorry :)
