### ISSUE TITLE
Ensure Bazel Maintains the Same Visibility Upon New bazel run //:gazelle

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#269]
Hi all,

Even though we set the visibility of packages such as the beacon-chain to be `beacon-chain:__subpackages__`, triggering new gazelle runs will generate build files in new subfolders with public visibility. It will also switch the visibility of the binaries to public. We should fix this.

**Comment by prestonvanloon** [comment]
We have a primitive visibility checking script where we check that no target under beacon-chain or validator has public visibility. 

The specific requirement is that targets under beacon-chain or validator can only be accessed by sub packages under those directories.

**Comment by prestonvanloon** [comment]
I think this is out of scope for Prysm. If anything, we could file a feature request for gazelle, but this would likely be a low value P4 anyway.
