### ISSUE TITLE
Bazel build on windows does not show colors

### ISSUE THREAD

**Issue by zediir** [prysmaticlabs/prysm#2690]
When building on Windows using bazel the beacon chain and validator processes don't correctly display colors.

<img width="1610" alt="Capture" src="https://user-images.githubusercontent.com/418053/58353181-7e32a600-7e76-11e9-9590-18a2dfbaa55f.PNG">

Not sure if something specific to my configuration.

**Comment by katzdan** [comment]
What Windows version are you using? According to https://github.com/bazelbuild/bazel/issues/3108 and https://stackoverflow.com/questions/38772468/setconsolemode-and-enable-virtual-terminal-processing you need Windows 10. 
Even on Windows 10 on some machines - coloring of cmd.exe output may be disabled. You can re-enable it following the instructions here : https://github.com/ytdl-org/youtube-dl/issues/15758.

**Comment by zediir** [comment]
Adding the registry key did it 👍 

```[HKEY_CURRENT_USER\Console]
"VirtualTerminalLevel"=dword:00000001```
