### ISSUE TITLE
Libp2p Broke Travis

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2695]
Looks like some Libp2p's [breaking changes](https://github.com/libp2p/go-libp2p-host/pull/29) came our way, a few stuff was merged before merging in core package

In Travis:
```
# github.com/libp2p/go-libp2p/p2p/host/basic
../../libp2p/go-libp2p/p2p/host/basic/basic_host.go:145:32: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
	*BasicHost does not implement host.Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
../../libp2p/go-libp2p/p2p/host/basic/basic_host.go:172:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
	*BasicHost does not implement host.Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
# github.com/libp2p/go-libp2p/p2p/host/routed
../../libp2p/go-libp2p/p2p/host/routed/routed.go:153:20: cannot use rh.host.Mux() (type "github.com/libp2p/go-libp2p-core/protocol".Switch) as type *multistream.MultistreamMuxer in return argument: need type assertion
../../libp2p/go-libp2p/p2p/host/routed/routed.go:190:5: cannot use (*RoutedHost)(nil) (type *RoutedHost) as type "github.com/libp2p/go-libp2p-core/host".Host in assignment:
	*RoutedHost does not implement "github.com/libp2p/go-libp2p-core/host".Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
```

**Comment by prestonvanloon** [comment]
It might be fixed according to this: https://github.com/libp2p/go-libp2p/issues/649

**Comment by raulk** [comment]
Hey, gomod can be a pain sometimes. Easy way to fix this is to manually remove all go-libp2p modules from your go.mod file, and do a `go get` followed by a `go mod tidy`. That will ensure the build picks up the latest versions of everything.

**Comment by raulk** [comment]
I noticed prysm doesn't use go modules. Any particular reason?

**Comment by prestonvanloon** [comment]
We didn't have support for it originally with our build tooling, but it looks like we have support now: https://github.com/bazelbuild/bazel-gazelle/pull/292 We'll need to assess how this behaves with renovate.

We have two solutions here:
- Move off of travis and `go get` (low priority, but happening incrementally for months now)
- Add vgo support and try to keep go.mod in sync with the WORKSPACE dependencies

For now, we just ignore travis until the problem is resolved. We haven't had too much pain with this strategy so far.

**Comment by prestonvanloon** [comment]
This is no longer breaking us. The current travis breakage is #2724
