### ISSUE TITLE
runtime: out of memory error after beacon node start from scratch

### ISSUE THREAD

**Issue by MattWangming** [prysmaticlabs/prysm#2709]
I gitpull latest docker image from gcr this morning, and try to start beacon node locally but error printout `runtime: out of memory`, and the deamon break out:
```
time="2019-05-27 02:45:37" level=info msg="Validator activated" activationEpoch=0 index=255 prefix=validator
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x132787a, 0x16)
        GOROOT/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc004000000, 0x74000000, 0x2144ff8)
```
You can refer to the latest complete error log as below
[error.log](https://github.com/prysmaticlabs/prysm/files/3221673/error.log)

PS: is there any prerequisity for the testing HD environment, e.g. 1core, 1G memory with docker implementation enough?

**Comment by SjonHortensius** [comment]
I think 1 GiB of memory is simply not enough - my node uses ~ 5 GiB RSIZE and https://github.com/prysmaticlabs/prysm/pull/1232 also shows at least 3.5 GiB allocated. I'd definitely retry with more available memory

**Comment by MattWangming** [comment]
Hi @SjonHortensius, thanks for your info.

**Comment by prestonvanloon** [comment]
Thanks for the feedback. We're going to be working on reducing the memory footprint and identifying where this memory usage is coming from.

I would recommend at least 2GB of RAM, but I do not expect it to use more than 4GB at this time.

**Comment by MattWangming** [comment]
Close it with no more question on this issue.
