### ISSUE TITLE
build beacon-chain error

### ISSUE THREAD

**Issue by yahtoo** [prysmaticlabs/prysm#2715]
#bazel build //beacon-chain:beacon-chain
ERROR: /home/xxx/go/src/github.com/prysmaticlabs/prysm/beacon-chain/powchain/BUILD.bazel:3:1: no such package '@io_k8s_client_go//tools/cache': failed to generate BUILD files for k8s.io/client-go: Timed out and referenced by '//beacon-chain/powchain:go_default_library'
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: no such package '@io_k8s_client_go//tools/cache': failed to generate BUILD files for k8s.io/client-go: Timed out
INFO: Elapsed time: 632.928s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (441 packages loaded, 14210 targets configured)

**Comment by katzdan** [comment]
1. Can you please specify the environment you are trying to build one? OS, version?
2. Did you try to delete the repo, clone it again and then build again? if not - please do and report if it helped.

**Comment by yahtoo** [comment]
1.
Linux  4.15.0-47-generic #50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

2.  Did you try to delete the repo, clone it again and then build again? if not - please do and report if it helped.
when I try again, get this
INFO: An error occurred during the fetch of repository 'com_github_x_cray_logrus_prefixed_formatter'
INFO: Call stack for the definition of repository 'com_github_x_cray_logrus_prefixed_formatter':
 - /home/xxx/go/src/github.com/prysmaticlabs/prysm/WORKSPACE:165:1
ERROR: /home/xxx/go/src/github.com/prysmaticlabs/prysm/BUILD.bazel:56:1: no such package '@org_golang_x_tools//go/analysis/passes/asmdecl': BUILD file not found on package path and referenced by '//:nogo'
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: no such package '@org_golang_x_tools//go/analysis/passes/asmdecl': BUILD file not found on package path
INFO: Elapsed time: 0.140s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

3.
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/xxx/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xxx/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build182026216=/tmp/go-build -gno-record-gcc-switches"

**Comment by katzdan** [comment]
It looks like there is a different error on the second build attempt. I tried building again from scratch and everything went fine. Since the failure of the build is not consistent - I would assume there is something in your environment affecting the build (perhaps a networking issue?).

**Comment by prestonvanloon** [comment]
Seems like a networking issue to me. Timing out when fetching remote repositories.

**Comment by prestonvanloon** [comment]
Closing for now. Kindly reopen if this is still an issue.
