### ISSUE TITLE
Update Phore BLS library to newest version

### ISSUE THREAD

**Issue by meyer9** [prysmaticlabs/prysm#2724]
The new Phore BLS library uses basically the same API, but moves the BLS functions from `github.com/phoreproject/bls` to `github.com/phoreproject/bls/g{1,2}pubs`. Also, of course, the signature size/public key size is different depending on if you use public keys in G1 or G2.

**Comment by prestonvanloon** [comment]
Keys are now 48 bytes for public keys and 96 bytes for signatures if public keys are in G1.

**Comment by prestonvanloon** [comment]
This was closed in #2792
