### ISSUE TITLE
Remove Deprecated Validator Protobuf

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2726]
We'll need help on removing deprecated validator fields for protobuf, by doing so, it will allow us remove unused function like `eligibleToExit` and update `lookupValidatorStatusFlag` in RPC server.

@0xKiwi has expressed interest taking on this. Thanks Ivan!

**Comment by 0xKiwi** [comment]
So working on updating `lookupValidatorStatusFlag`, the indications for which status the validator currently is have changed.

Previously they were:
```
 	if v.ActivationEpoch > epoch {
		status = pb.ValidatorStatus_PENDING_ACTIVE
	} else if epoch >= v.ActivationEpoch && epoch < v.ExitEpoch {
		status = pb.ValidatorStatus_ACTIVE
	} else if v.StatusFlags == pbp2p.Validator_INITIATED_EXIT {
		status = pb.ValidatorStatus_INITIATED_EXIT
	} else if v.StatusFlags == pbp2p.Validator_WITHDRAWABLE {
		status = pb.ValidatorStatus_WITHDRAWABLE
	} else if epoch >= v.ExitEpoch && epoch >= v.SlashedEpoch {
		status = pb.ValidatorStatus_EXITED_SLASHED
	} else if epoch >= v.ExitEpoch {
		status = pb.ValidatorStatus_EXITED
	} else {
		status = pb.ValidatorStatus_UNKNOWN_STATUS
	}
```

But now since `StatusFlags` have been removed, they need to be modified. Are these changes correct? 
```
	farFutureEpoch := params.BeaconConfig().FarFutureEpoch

	if v.ActivationEpoch > epoch {
		status = pb.ValidatorStatus_PENDING_ACTIVE
	} else if epoch >= v.ActivationEpoch && epoch < v.ExitEpoch {
		status = pb.ValidatorStatus_ACTIVE
	} else if epoch < v.ExitEpoch && v.WithdrawableEpoch > v.ExitEpoch {
		status = pb.ValidatorStatus_INITIATED_EXIT
	} else if epoch >= v.WithdrawableEpoch {
		status = pb.ValidatorStatus_WITHDRAWABLE
	} else if v.Slashed && epoch >= v.ExitEpoch {
		status = pb.ValidatorStatus_EXITED_SLASHED
	} else if epoch >= v.ExitEpoch {
		status = pb.ValidatorStatus_EXITED
	} else {
		status = pb.ValidatorStatus_UNKNOWN_STATUS
	}
```

**Comment by 0xKiwi** [comment]
Also, in `beacon-chain/db/state_metrics.go`, there are configurations in place for prometheus that also need updating.

```
		validatorSlashedGauge.WithLabelValues(
			strconv.Itoa(i), //Validator index
		).Set(float64(v.SlashedEpoch))
```

With the removal of the deprecated protos, `SlashedEpoch` no longer exists, what should this be changed to?

**Comment by 0xKiwi** [comment]
Should `lookupValidatorStatusFlag()` be renamed to `lookupValidatorStatus()`?

**Comment by terencechain** [comment]
> Should `lookupValidatorStatusFlag()` be renamed to `lookupValidatorStatus()`?

that sounds good to me

**Comment by terencechain** [comment]
> Also, in `beacon-chain/db/state_metrics.go`, there are configurations in place for prometheus that also need updating.
> 
> ```
> validatorSlashedGauge.WithLabelValues(
> 	strconv.Itoa(i), //Validator index
> ).Set(float64(v.SlashedEpoch))
> ```
> 
> With the removal of the deprecated protos, `SlashedEpoch` no longer exists, what should this be changed to?

is there an another way to tell which epoch validator slashed?
