### ISSUE TITLE
Enhance new querying funcs to Block Tree RPC for Efficiency / Bandwidth Saving

### ISSUE THREAD

**Issue by katzdan** [prysmaticlabs/prysm#2739]
Continuing https://github.com/prysmaticlabs/prysm/issues/2643 - There is a need to add new funcs for querying the BlockTree rpc service.

I'll prepare a list of funcs for querying the block tree but first - regardless of how clients can query the beacon-chain service - I would recommend that **any** function that's used to query the tree will support paging to reduce amount of data retrieved and returned to the client.
Your thoughts?

**Comment by rauljordan** [comment]
No longer used in Prysm, we can close this for now
