### ISSUE TITLE
Sync issues by using beacon-chain:latest on 06.06.2019

### ISSUE THREAD

**Issue by cosminstefane** [prysmaticlabs/prysm#2760]
When I start the beacon chain (latest), it remains stuck at

>[2019-06-06 07:45:28] INFO regular-sync: Listening for regular sync messages from peers

When stopping it, I got:

>^C[2019-06-06 07:48:22] INFO node: Got interrupt, shutting down... [2019-06-06 07:48:22] INFO node: Stopping beacon node [2019-06-06 07:48:22] INFO prometheus: Stopping service [2019-06-06 07:48:22] INFO rpc: Stopping service [2019-06-06 07:48:22] INFO syncQuerier: Stopping service [2019-06-06 07:48:22] INFO initial-sync: Stopping service [2019-06-06 07:48:22] INFO regular-sync: Stopping service [2019-06-06 07:48:22] INFO blockchain: Stopping service [2019-06-06 07:48:22] INFO operation: Stopping service [2019-06-06 07:48:22] INFO attestation: Stopping service [2019-06-06 07:48:22] INFO powchain: Stopping service [2019-06-06 07:48:22] INFO p2p: Stopping service [2019-06-06 07:48:22] ERROR attestation: could not execute head transition: context canceled [2019-06-06 07:48:22] ERROR attestation: could not execute head transition: context canceled [2019-06-06 07:48:22] ERROR attestation: could not execute head transition: context canceled [2019-06-06 07:48:22] ERROR attestation: could not execute head transition: context canceled [2019-06-06 07:48:22] ERROR attestation: could not execute head transition: context canceled

Sapphire works as expected.

**Comment by nisdas** [comment]
For reference current master is at this commit: 85c5672ab3feb41f7dbf0c849eebf634923f967d

**Comment by prestonvanloon** [comment]
The chain may have been stalled at that point in time or you may have lost your peers, I am not sure at this moment. We're aiming to release some big changes in the next week or so and hopefully issues like this one are resolved.

Please reopen this issue if you still experience this at a later time. Thanks for reporting!

**Comment by cosminstefane** [comment]
Hi Preston, peers lost or not, sapphire was working, latest didn't. Now I have same problem, on both, I just pulled the latest. No problem, waiting for next update.
