### ISSUE TITLE
Handle Attester and Proposer Slashings in Operations Service

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2766]
Similar to attestations, and deposits, we should implement retrieval methods in the operation service for beacon block operations such as slashing and exit. These methods will be used for proposer RPC service to construct to-be-retrieved block

**Comment by cyberbono3** [comment]
I can start working on it

**Comment by prestonvanloon** [comment]
What does this mean exactly?

**Comment by terencechain** [comment]
It means to implement operation service for `slashing` and `exit` beacon chain objects, this is a high level place holder issue mainly needed to link code TODO with an issue. 

The detail design is needed to sort this out, and this is not urgent yet

**Comment by rauljordan** [comment]
This was done by @shayzluf , closing

**Comment by prestonvanloon** [comment]
This was not done. 

https://github.com/prysmaticlabs/prysm/blob/c44a30672eede4690de662bab71c70cb3a0abdea/beacon-chain/rpc/validator/proposer.go#L83-98

**Comment by shayzluf** [comment]
it was done here https://github.com/prysmaticlabs/prysm/blob/29aff0fdb8f1b93b6ed3e7982e1524ca419b6fbb/beacon-chain/rpc/validator/proposer.go#L82 will pick the relevant changes and create a new PR

**Comment by prestonvanloon** [comment]
Related ##4836
