### ISSUE TITLE
validator reports incorrect prevBalance with multiple accounts

### ISSUE THREAD

**Issue by ethDreamer** [prysmaticlabs/prysm#2772]
When staking with multiple keys, the validator thinks each account started with the sum of all account balances.  This causes it to calculate losses incorrectly.

![weirdstart](https://user-images.githubusercontent.com/37123614/59164554-87f61380-8adc-11e9-9466-c6482644651a.png)

**Comment by zediir** [comment]
duplicate of https://github.com/prysmaticlabs/prysm/issues/2573

**Comment by prestonvanloon** [comment]
Closing as duplicate of #2573
