### ISSUE TITLE
Tidying up validator client with latest spec

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2798]
Took a quick glance on our validator client and I think it needs some clean up to align to the latest 0.7 spec. Couple items I see are out of date and can be improved on:

1. Combine `BeaconClient` and `ValidatorClient` the separations of the two dont make sense and it's confusing. Other than `ProposerClient` and `AttesterClient`, we really just need 1 actor to query information on beacon chain like assignments
2. Revisit validator status usage, this may be outdated
3. Revisit rewards and penalties reporting, this may be outdated

**Comment by prestonvanloon** [comment]
It might be a good idea to add this as a general overhaul to the beacon chain / validator API similar to the changes we are making to support github.com/prysmaticlabs/ethereumapis. 

Perhaps these protos can live upstream as well.

**Comment by rauljordan** [comment]
I agree to point 1 - that's mostly the biggest point of confusion to anyone browsing our API at the moment.

**Comment by rauljordan** [comment]
Resolved already by @terencechain
