### ISSUE TITLE
Use Beacon Node Context to Establish Pattern for Cleaning Up Resources

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#280]
Now that we've established a pattern for passing contexts through to services in #273, let's take advantage of it.

Here's the chain of events when a user shuts down the beacon node:
1. `BeaconNode` listens for `SIGINT` or `SIGTERM`
2. `BeaconNode` calls `Stop` on all services
3. `Stop` calls `ctx.cancel`
4. goroutines exit

The new chain of events should be:
1. `BeaconNode` listens for `SIGINT` or `SIGTERM`
2. `BeaconNode` calls `ctx.cancel` (on its own context)
3. each service receives item from `ctx.Done()` and calls `Stop`
4. goroutines exit

The two benefits here are that `Stop` now gets called concurrently, and that subresources of each service can derive its own context from the beacon node context.

Edit: This should fix the `sharding` package to use the same pattern too.

**Comment by fgimenez** [comment]
hey @rawfalafel are you working on this? If not I'd like to give it a try (encouraged by the labels ;)

**Comment by rawfalafel** [comment]
hey @fgimenez 

After looking at this a litte longer, I realized that the changes are more invasive than I initially thought. That label's outdated, sorry! 

Regardless, looks like there aren't any unassigned "Good First Issue" tasks left. Its partly because everything's still in flux since the recent spec update. There should be an issue with the tag soon, so keep an eye out.

**Comment by terenc3t** [comment]
Can we close this after #353 and 335?

**Comment by rauljordan** [comment]
I can take hold of this one.

**Comment by prestonvanloon** [comment]
@rauljordan Any update on this? Has it been resolved?

**Comment by rawfalafel** [comment]
Not yet. The process still exits before allowing each goroutine to exit cleanly. The description is outdated though. I can take a look at the requirements later.

**Comment by terencechain** [comment]
Is this still relevant?

**Comment by rauljordan** [comment]
Our code has evolved significantly and the only few services which still have a run function as a main goroutine are properly closed when receiving a done signal from a canceled context
