### ISSUE TITLE
Continous Integration: Setup Bazel Remote Execution / Caching

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#282]
To create faster builds, we can leverage Bazel's feature to execute on remote workers and take some burden off of Travis (or other CI). It might make sense to do this when we launch a Sapphire testnet with extra resources in a compute cluster.

At this time we can also explore other CI pipelines for more flexibility, such as [Buildkite](https://buildkite.com).

This is low priority until Travis can no longer execute our tests within a reasonable amount of time. 

Assigning to myself as the default Bazel person on the team, but contributions are welcome if anyone is inclined to help.

**Comment by prestonvanloon** [comment]
@fgimenez I think a few proposals/investigation would be a good start.

I have looked at bazel-buildfarm and bazel-buildbarn. I think there are a few others that support the remoteexecution API (BuildGrid?).

Also, it appears that Google is working on a remoteexecution service. Maybe as part of Google Cloud? I'm not sure, but if you look at the Tensorflow project, they are using some kind of remote execution on Google Cloud in alpha. See this link for example: https://source.cloud.google.com/results/invocations/44817b60-501b-44cf-9bd0-f13c7e303427/targets

GCP offers this service and the price is reasonable, then we would likely use it. Otherwise, we'd probably add something to a kubernetes cluster.

**Comment by rauljordan** [comment]
Closed now that we have buildkite enabled and it is quite fast
