### ISSUE TITLE
Consider Roughtime as a NTP backup

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2834]
**Background**: https://roughtime.googlesource.com/roughtime

**Problem to solve**: NTP (network time protocol) responses are insecure and may be subject to MITM attacks. This is especially risky if the host machine only synchronizes its clock every few hours. 

**Summary**: Roughtime is a project that aims to provide secure time synchronisation. Roughtime can resolve clock time within <10s acceptance (typically <1s accuracy). This lowers the attack damage to less than 1 epoch and could be a helpful security feature for alerting node operators of potential NTP issues.

Thanks to @CarlBeek for bringing it up.

**Comment by prestonvanloon** [comment]
Cloudflare released a secure NTP recently.

 https://www.google.com/amp/s/blog.cloudflare.com/secure-time/amp/

**Comment by kivutar** [comment]
See also https://github.com/cloudflare/roughtime

**Comment by kivutar** [comment]
@prestonvanloon the SlotTicker is starting from the genesisTime, which comes from the genesis block I suppose, and it then using only monotonic time functions and types like Duration.

I don't see time.Now() being called in the SlotTicker, so it might not be a vector of attacks. What do you think?

**Comment by prestonvanloon** [comment]
@kivutar we use time.Until which uses time.Now

https://github.com/prysmaticlabs/prysm/blob/953c59a3021d66341c9464754588e08e1620651e/shared/slotutil/slotticker.go#L37

https://github.com/golang/go/blob/go1.12.5/src/time/time.go#L936

**Comment by rauljordan** [comment]
Resolved by #3151
