### ISSUE TITLE
Remove index from deposit

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2841]
The [index](https://github.com/prysmaticlabs/prysm/blob/spec-v0.6/proto/beacon/p2p/v1/types.proto#L193) is no longer a field in [Deposit](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#deposit), we'll need to update our `Deposit` type for protobufs as well as `ProcessDeposit` function in block_operations.go

I'm making this as critical because it's blocking ssz spec tests

**Comment by 0xKiwi** [comment]
Can this be closed now thanks to [this commit](https://github.com/prysmaticlabs/prysm/commit/f59563cfbe79b21e04e83764526fc4432d739de2)?

**Comment by nisdas** [comment]
Yeah sounds good, closing this
