### ISSUE TITLE
Design Doc Skeleton Template

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#286]
We have been writing a lot of design docs across multiple components (p2p, block processing, fork choice..etc) It will be very nice to have a design doc skeleton template. Let's use this issue to create a design doc skeleton template and place it in Prysmatic Lab's google drive

**Comment by prestonvanloon** [comment]
This is done and the gdoc skeleton is here: https://docs.google.com/document/d/1ItkSY7-moVfTLq1sD2BIA5qlDJjrOPoj12ieuzwC6JQ/edit?usp=sharing
