### ISSUE TITLE
Process blocks / attestations from RPC before propagating

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2871]
After some discussion with @terencechain today, we decided we would like to revisit our strategy for newly created blocks/attestations. 

To resolve this issue, we would need to outline all of the risks and benefits for each strategy. Here are some thoughts: 

Upon receiving a new objective via RPC. 
## Broadcast immediately, then validate after 
**Pros**
- Blocks have more time to propagate throughout the network with a short slot time
- Attestations have more time to propagate throughout the network with a much longer time constraint. 200 to 500ms is negligible for attestations where it is significant for blocks.  

**Cons**
- If blocks fail locally, they will almost certainly fail in our peers. Peers may have reputation implemented and prune "bad" peers.
- If the beacon chain node has any slashing detection, this would be in the validation of attestations. By-passing validation for attestations means there is a higher risk of validator being slashed.

**Comment by terencechain** [comment]
Captured a few notes @djrtwo mentioned on Gitter. These are good points as well

In response to Beacon node’s reputation is on the line:
`I think the idea here was a speed concern. A validator is a very privileged user wrt a beacon node (likely the owner). The validator also likely got the message (block/attestation) directly from the node, only to sign it and pass it back. To perform full block or attestation validation prior to sending would reduce the speed of the message hitting the network by a potentially not inconsequential amount. The trust relationship and requirements imo would imply sending immediately, then performing local validation and inclusion in the block tree.`

In response to Peers may disconnect you if you broadcast bad blocks and attestations:
`This is true but given the trust relationship here, a very exceptional case. If for some reason you were a BN providing attester services to untrusted attesters, it would certainly make sense to either (1) have a flag to toggle this pre-validation on/off or (2) only broadcast message that the BN previously passed out via requests (track signed_roots for messages you already validated and if you get one back signed, you know it’s safe to broadcast). Could also just do a bls_verify on the block if already seen signed_root(block) before when creating it initially`

Thanks Danny!

**Comment by prestonvanloon** [comment]
This could be a configuration flag. Perhaps public, unauthenticated nodes would allow anyone to submit attestations or blocks but the node would verify the processing before submitting to the network.

**Comment by rauljordan** [comment]
We have opted to go for the broadcast first => process after approach as the canonical way of handling this across eth2 clients. The pros of this outweigh the cons outlined above heavily and it is much preferred to get blocks out to the network ASAP than otherwise.
