### ISSUE TITLE
Move P2P to Shared Package

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#289]
Hi all,

The p2p implementation for sharding will also be needed by the beacon-chain repo. Let's move it to the shared package.

**Comment by prestonvanloon** [comment]
This is a bit more involved then simply moving p2p package to shared package so that both projects can consume it. 

Each actor may have its own topics and configuration to handle. We should design this carefully so that code can be effectively reused by random beacon chain and the sharding client.

**Comment by prestonvanloon** [comment]
I'll be starting work on this tomorrow

**Comment by prestonvanloon** [comment]
It looks like this can be moved to the shared package and made more generic with regards to what topics are subscribed.
