### ISSUE TITLE
[Mega Tracking] - Mutation Testing For Prysm

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2910]
This PR tracks the overall efforts of passing mutation testing for Prysm. Let's check off the package as we successfully tested it:

- [ ] attestation
- [ ] blockchain
- [ ] cache
- [ ] core
- [ ]  blocks
- [x]  epoch #2913 
- [x]  helpers #2912 
- [x]  state #2923 
- [ ]  validators
- [ ] db
- [ ] gateway
- [ ] internal
- [ ] node
- [ ] operations
- [ ] powchain
- [ ] rpc
- [ ] sync
- [ ] utils

**Comment by terencechain** [comment]
@prestonvanloon @0xKiwi can you guys check off what's been tested? thanks

**Comment by prestonvanloon** [comment]
I did 1 file of the helper package in spec-v0.6 branch. Still lots to go over.

**Comment by nisdas** [comment]
Is anyone taking this up ? We have had this as a task to do for more than 3 years. If there is no near-term plan to address this, then we should close the issue.

**Comment by rauljordan** [comment]
No plan and this is something that we typically do when there is nothing else to do. It's a nice thing to suggest, but there will always be more tests to do mutation testing for. I agree we should close
