### ISSUE TITLE
Finish Block Sanity Spec Test

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2922]
Current block sanity test is passing but it is passing without the important signature verification and state root verification enabled.
The default config for running state transition has both of them set as false meaning when we run state transition we miss those checks
To solve this issue, we should enable them and debug any potential failures that could be related with BLS, core logic or SSZ

Reference point: https://github.com/prysmaticlabs/prysm/blob/1cf1e081ac327ab3083f6be8f1643f1cca4ac1cb/beacon-chain/core/blocks/spectest/block_processing_test.go#L51

**Comment by rauljordan** [comment]
Closed by #2828
