### ISSUE TITLE
Implement HashTreeRootWithMax

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2929]
We'll need to implement `HashTreeRootWithMax` as it's blocking a few spec tests. The goal for `HashTreeRootWithMax` is to take some `[]interface, uint64` and apply the `max-size` tag to the `[]interface` and return the tree hash root. This is to avoid having to create a wrapper struct with the `max-size` tag.

Let's look at the following example:
```python
indices_list = List[ValidatorIndex, VALIDATOR_REGISTRY_LIMIT](get_active_validator_indices(state, index_epoch))

state.active_index_roots[index_root_position] = hash_tree_root(indices_list)
```
What we want is `get_active_validator_indices(state, index_epoch)` returns `uint64[]` then add `max-size` tag using `List[ValidatorIndex, VALIDATOR_REGISTRY_LIMIT]` casting then pass in to `hash_tree_root`

**Comment by rauljordan** [comment]
Done by https://github.com/prysmaticlabs/go-ssz/pull/47
