### ISSUE TITLE
Testing Methodology for Beacon Chain Block Processing

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#294]
Let's start a discussion on how we plan on testing the beacon chain. Like go-ethereum's simulated backend, it would be nice for beacon chain to have a similar back end functionality on advancing beacon blocks. Developers can use this functionality to test re-orgs, fork choice rules, and state changes. 
Another option is to avoid simulated back end architecture for testing, and focus on the e2e aspect such as testing with a beacon node launched in a local set up that's advancing beacon block. What do you guys think?

**Comment by rauljordan** [comment]
@prestonvanloon elaborated on the idea of not having a simulated backend but instead just having a real chain where data is persisted in-memory.

One of my only requests for this piece of functionality is to work with small interfaces in the implementation for easy mocking and extensibility.

One of the downsides of not having a simulated backend is that e2e testing approach will be difficult to maintain, but we can mitigate this by having e2e tests that are as high level as possible.

**Comment by rauljordan** [comment]
**Summary of what we need to do to wrap this up:**

Our blockchain service will have a running goroutine that 
- Listens for received blocks
- Checks if we can process them
- Runs updateActiveState for each
- Stores the updated state and processed block inside of a trie structure
- Persists this trie structure in local storage to prevent against the node being disconnected

Then, chain service will also run an UpdateHead goroutine that applies the forkchoice rule on this trie structure to create a canonical head+state, and then persist these canonical structures to the DB.

**Comment by rauljordan** [comment]
Can this count as part of #420? If so, can we close this?

**Comment by terenc3t** [comment]
Yeah. We can move this discussion to #420.
