### ISSUE TITLE
Flip flag default EnableCheckBlockStateRoot to true

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2947]
https://github.com/prysmaticlabs/prysm/blob/e5648f46c15765e21909868be359219790094ea9/beacon-chain/blockchain/block_processing.go#L114-L115

Also log a WARN statement if this is disabled.

**Comment by terencechain** [comment]
Similar to removing VerifySignature flag, this can be removed as well. Can't think of a use case for disabling this check

**Comment by prestonvanloon** [comment]
Lets remove this flag all together.

**Comment by rauljordan** [comment]
This has been removed as of latest master at hash [d5dcc25472fc2755b404fe0913e614a4dd2abe4a](https://github.com/prysmaticlabs/prysm/commit/d5dcc25472fc2755b404fe0913e614a4dd2abe4a)
