### ISSUE TITLE
Unskip fork choice tests

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2948]
https://github.com/prysmaticlabs/prysm/blob/e5648f46c15765e21909868be359219790094ea9/beacon-chain/blockchain/fork_choice_reorg_test.go#L29-L31

**Comment by prestonvanloon** [comment]
There are actually many skipped fork choice tests.

**Comment by rauljordan** [comment]
This is no longer relevant given the new fork choice package, which includes all sorts of new tests
