### ISSUE TITLE
Implement VerifyProposerSignature

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2950]
https://github.com/prysmaticlabs/prysm/blob/e5648f46c15765e21909868be359219790094ea9/beacon-chain/core/blocks/block_operations.go#L29-L38

**Comment by terencechain** [comment]
How did we pass yaml spec tests without this? ¯\_(ツ)_/¯

**Comment by prestonvanloon** [comment]
The unhappy path spec tests are not very clear. Essentially, you are given some invalid state and as long as it fails for any reason, then you pass the test.
