### ISSUE TITLE
Remove verifySignatures arguments from methods

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2951]
Example:
https://github.com/prysmaticlabs/prysm/blob/e5648f46c15765e21909868be359219790094ea9/beacon-chain/core/blocks/block_operations.go#L102-L106

There are many like this and this is a dangerous pattern.

**Comment by prestonvanloon** [comment]
Suggestion:
- Remove any `verifySignatures` argument
- Add a new `ProcessBlockHeaderNoVerifySig` method for the rare cases that you need to skip verification. 
- Abstract the code to be reusable between the two methods.

We are mostly concerned about accidental misuse of the method. 
A verbose API would help clarify / catch misuse.

**Comment by terencechain** [comment]
Given the following note from validator spec, I think `ProcessBlockHeaderNoVerifySig` should be `StateTransitionNoVerifySig` for clarify. This can be a separate issue and PR

```
Note: To calculate state_root, the validator should first run the state transition function on an unsigned block containing a stub for the state_root. It is useful to be able to run a state transition function that does not validate signatures or state root for this purpose.
```

**Comment by 0xKiwi** [comment]
Closing as the arguments have been removed 😄
