### ISSUE TITLE
Active State Transition Function for Beacon Chain

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#296]
Opening up this issue to plan and design beacon chain's state transition function. Please refer to latest [beacon chain spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view) as a reference.
As quoted in the design spec, the state transition is made up of 2 parts:

> 1.) The epoch transition, which happens only if slot_count // 64 > epoch_number, and affects the crystallized state and active state
> 2.) The per-block processing, which happens every block (if during an epoch transition block, it happens after the epoch transition), and affects the active state only
> 

This issue aims to addresses the state transition function in regards to per-block processing. It affects the active state only, and focuses on verifying aggregate signatures, saving temporary records relating to in-block activity in the active state. Last, we'll provide a helper function to hash the current active state so node can store the hash to current beacon block.

**Comment by rauljordan** [comment]
Was this closed by your some of your latest PR's @terenc3t ?

**Comment by terenc3t** [comment]
Not yet. We still need to verify aggregate signatures during active state transition and that's waiting on BLS

**Comment by terenc3t** [comment]
This is implemented with latest 2.1
