### ISSUE TITLE
Improve sorted indices check in validate_indexed_attestation

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2963]
https://github.com/prysmaticlabs/prysm/blob/97b9176411113ff242ef2ec96a1f5c233d29f191/beacon-chain/core/blocks/block_operations.go#L716-L721

We don't need to copy, sort, then compare the list to ensure it is sorted. It could be a simple O(n) iteration through the array to check they are in order.

**Comment by justinpage** [comment]
@prestonvanloon 

Would the following be an improvement?

```
	custodyBit0IndicesIsSorted := sort.SliceIsSorted(custodyBit0Indices, func(i, j int) bool {
		return custodyBit0Indices[i] < custodyBit0Indices[j]
	})

	if !custodyBit0IndicesIsSorted {
		return fmt.Errorf("custody Bit0 indices are not sorted, got %v", custodyBit0Indices)
	}
```

**Comment by prestonvanloon** [comment]
@justinpage, yeah that would be great!

This is work should be based on the [spec-v0.6](https://github.com/prysmaticlabs/prysm/tree/spec-v0.6) branch. This has all of our work with current updates to spec-v0.8. We expect this to be merged in a few days, so definitely build off of that branch if you want to avoid merge conflicts.

**Comment by justinpage** [comment]
@prestonvanloon Looks like this block is doing the same pattern. Can I apply the same update?

https://github.com/prysmaticlabs/prysm/blob/97b9176411113ff242ef2ec96a1f5c233d29f191/beacon-chain/core/blocks/block_operations.go#L723-L731

Thanks, I will branch off [spec-v0.6](https://github.com/prysmaticlabs/prysm/tree/spec-v0.6) and provide a pull request tomorrow.

**Comment by prestonvanloon** [comment]
Yes @justinpage. Thanks!

**Comment by justinpage** [comment]
#3060 is branched off of master per recommendation from 

https://github.com/prysmaticlabs/prysm/pull/3015#issuecomment-514027013
