### ISSUE TITLE
Flagless cross compile builds

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2974]
It seems we have to build cross compile invocations for each OS/arch pair, rather than invoking a build in a single command.

Blocked by https://github.com/bazelbuild/bazel/issues/6519

What we have:
```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64_cgo //beacon-chain //validator
bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64_cgo //beacon-chain //validator
bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64_cgo //beacon-chain //validator
bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64_cgo //beacon-chain //validator
```
What we want:
```
bazel build //:all_binaries_bundle
```
Which would produce a zip / tar with distros for each system.

**Comment by prestonvanloon** [comment]
Update: I have an idea to try from this comment: https://github.com/bazelbuild/bazel/issues/6519#issuecomment-512460430

Haven't had the time to attempt it yet.

**Comment by rauljordan** [comment]
Done by @SuburbanDad
