### ISSUE TITLE
Add RPC command to query node for the last block attested by (given) public key

### ISSUE THREAD

**Issue by ethDreamer** [prysmaticlabs/prysm#2981]
Please implement an RPC command to return the last block that a given public key has attested/checkpointed.  Some variation of this functionality is probably already necessary for a validator to rebuild its state for slashing protection.

Exposing this functionality as an RPC command would allow infrastructure to be built to monitor the blockchain and take action (send alerts, etc) if a validator goes offline.

**Comment by prestonvanloon** [comment]
> Some variation of this functionality is probably already necessary for a validator to rebuild its state for slashing protection.

We have a work in progress slashing protection mechanism that will solve this use case.

> Exposing this functionality as an RPC command would allow infrastructure to be built to monitor the blockchain and take action (send alerts, etc) if a validator goes offline.

We could expand on existing commands to solve this use case. Perhaps participation endpoint.

**Comment by rauljordan** [comment]
+1 @ethDreamer could you elaborate exactly on what the use case is? If it is explicitly only for monitoring, we wouldn't recommend doing so this way, but rather through some process monitoring of your actual validator instance. Slashing protection as @prestonvanloon will resolve the first use-case.

**Comment by rauljordan** [comment]
Hi @ethDreamer closing this for now unless there is a clearer use-case for the endpoint, if you have more input on this feel free to continue this thread and we can reopen if needed.
