### ISSUE TITLE
Update gitbook documentation for building with bazel

### ISSUE THREAD

**Issue by justinpage** [prysmaticlabs/prysm#3016]
I noticed the following section has the same commands repeated:

<img width="858" alt="Screen Shot 2019-07-21 at 4 34 31 PM" src="https://user-images.githubusercontent.com/3615935/61598647-c4d22180-abd5-11e9-9091-4ca2ac35d72a.png">

Whereas we probably expect the following:

<img width="830" alt="Screen Shot 2019-07-21 at 4 34 49 PM" src="https://user-images.githubusercontent.com/3615935/61598655-da474b80-abd5-11e9-94dd-c10ff932339b.png">

Not sure if there is an open-source repo for us to send updates to?

**Comment by prestonvanloon** [comment]
cc: @har00ga

**Comment by justinpage** [comment]
@prestonvanloon @har00ga 

While we're waiting for a reply. 

Any possibility of making this open-source: https://prysmaticlabs.gitbook.io/prysm/

**Comment by prestonvanloon** [comment]
I don't think gitbook supports open source contributions. I'm open to hearing an alternative to gitbook.

@har00ga is working on some improvements there.

**Comment by har00ga** [comment]
Sorry about that, thought I'd submitted a reply the other night -- This section will be fully revised as part of the Gitbook overhaul in the coming weeks. This part in particular is near the beginning of the index, so I imagine updates to it will be live over the next few days. I'll leave a note here when the relevant PR has been merged.

**Comment by rauljordan** [comment]
Resolved as of the latest updates to our Gitbook here: https://prysmaticlabs.gitbook.io/prysm/
