### ISSUE TITLE
Bazel failed to exclude nilness and unsafe pointer for dependencies (Mac only)

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3018]
Bazel build on beacon chain master is currently broken with the following error:

```
compilepkg: nogo: errors found by nogo during build-time code analysis:
/var/folders/l6/t4tq5tcx7fg0ddglrbgk5hxm0000gn/T/rules_go_work-492090240/_cgo_gotypes.go:425:8: tautological condition: nil == nil
/var/folders/l6/t4tq5tcx7fg0ddglrbgk5hxm0000gn/T/rules_go_work-492090240/watcher_fsevents_cgo.go:99:30: possible misuse of unsafe.Pointer
/var/folders/l6/t4tq5tcx7fg0ddglrbgk5hxm0000gn/T/rules_go_work-492090240/watcher_fsevents_cgo.go:104:35: possible misuse of unsafe.Pointer
/var/folders/l6/t4tq5tcx7fg0ddglrbgk5hxm0000gn/T/rules_go_work-492090240/watcher_fsevents_cgo.go:106:23: possible misuse of unsafe.Pointer
```

Meaning the dependencies have bad code and it fails our analysis, however nilness and unsafe pointer are already ignored in `nogo_config.json`

**Comment by terencechain** [comment]
Work around:

Edit the following  line to have no parameters
https://github.com/prysmaticlabs/prysm/blob/master/WORKSPACE#L111
`go_register_toolchains()`

**Comment by prestonvanloon** [comment]
Something off about the error message is that it's not under `external/*` so that could be a cause for the failure.

Can you try with this commit? https://github.com/prysmaticlabs/prysm/commit/721541672b8054f1a8b4a8978908edbaf192d652

**Comment by prestonvanloon** [comment]
Actually, looking at this PR https://github.com/bazelbuild/rules_go/pull/2087, its supposed to be a regex, not a glob. 

Please try this commit: https://github.com/prysmaticlabs/prysm/commit/ee491322ce1a430c73e90d24358d8a0a55486e85

**Comment by prestonvanloon** [comment]
If that fails, we'll just disable these checks for now.

**Comment by terencechain** [comment]
both https://github.com/prysmaticlabs/prysm/commit/721541672b8054f1a8b4a8978908edbaf192d652 and https://github.com/prysmaticlabs/prysm/commit/ee491322ce1a430c73e90d24358d8a0a55486e85 did not work
