### ISSUE TITLE
Fix DB's SaveState API

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3042]
[SaveState](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/db/state.go#L153) in DB package has a potential bug where we use the saving state's latest block header has key: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/db/state.go#L178

Per discussion with @prestonvanloon and @nisdas, we all agreed that the API should best off be `SaveState(state, blockRoot)` as the `blockRoot` refers to the what triggers the state. This API will also comply with the latest fork choice

**Comment by prestonvanloon** [comment]
@nisdas are you working on this in the database refactoring OKR?

**Comment by nisdas** [comment]
@prestonvanloon yes but this can be separate from that, since this might cause issues in runtime. I can do this in a separate PR

**Comment by terencechain** [comment]
fixed in #3193
