### ISSUE TITLE
Eliminate Usage of HistoricalStates - Use Exponential Backoff for State Generation

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3063]
Hi all,

An important task for becoming production ready is preventing the usage of HistoricalStates throughout our repo. Currently, we store every single state to the DB, which is not sustainable in a real environment. Instead, we should have the ability to regenerate states through only storing very few of them since the last finalized epoch. This is a tracking issue so we do not forget this important piece of functionality.

**Comment by terencechain** [comment]
To implement this, we'll require a design doc

**Comment by rauljordan** [comment]
This might not be necessary with state pruning, closing unless it comes up again and becomes something worth tackling
