### ISSUE TITLE
Refactor Prysm DB for Efficient, Long Term Usage

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3064]
This is a tracking issue to refactor the Prysm DB package to allow for:

1. Greater simplicity in function calls
2. Explicit naming and single responsibility for getters and putters
3. Batch updating/fetching
4. Easy filtering of data by attributes

This is a large effort that is being explored in the design document found [here](https://docs.google.com/document/d/1FWax9bD1oH7MCM80oa4fbFjZDqQFF7-Hf5ppq4iSX3Y/edit#heading=h.8alssqpx97hd)

**Comment by prestonvanloon** [comment]
Is this relevant to the existing refactor design that was reviewed and approved? https://docs.google.com/document/d/1ZnMpMzPhs_GyiG11KSNT2S4O2CPgG0uheEs52NznGTk
