### ISSUE TITLE
Sync Failing with State Root Verification Enabled

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3082]
A new node is never able to sync as it gets the following error
```
[2019-07-26 23:39:23] ERROR initial-sync: Failed to sync with peer. error=could not apply block state transition: block failed processing: validate state root failed, wanted: 0xa2e3c0cc723fdca09779cead5484446e9944b525cdbd71bd6298308d7dfd7a4a, received: 0x8a7710a14eca8898b12468846199726dcef3e6c2817ec2263c5ed1bc741bfe71 peer=QmSbxPPFQUzLjHHFZseP5DfjJbXKedM2x4YY7mBxwANsuV
```

**Comment by terencechain** [comment]
When sync responds the block to the peer, it needs to ensue the block's state root is valid. This could be a compatibility issue as well where one node has state enabled the other doesn't.

**Comment by terencechain** [comment]
another question for all is whether we should be checking state root and signature for state transition in initial sync? since there's a trust assumption between last finalized block and the batched of blocks

**Comment by nisdas** [comment]
@terencechain both nodes had state root verification enabled. If the block successfully was able to transition the state in one node it must be regarded as valid from that node's perspective. Since we pass finalized state at X and all the proceeding blocks from X+1, X+2, ... X+N. It should all be regarded as valid from the point of the synced node. I am hypothesizing it could be to do with our caches ? since state transitions are pure functions.
