### ISSUE TITLE
could not verify attestation due to delay

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3104]
The following error was reported in a single node + 64 validators local set up. Something to keep our eyes on

`could not process block attestations: could not verify attestation at index 0 in block: attestation slot 385 + inclusion delay 1 > state slot 385 at
slot 383`

**Comment by prestonvanloon** [comment]
Could you add more context to this issue? What delay? How can this be reproduced?

**Comment by terencechain** [comment]
`inclusion delay` refers to attestation inclusion delay, @rauljordan can elaborate on this, I was not able to reproduce it.

I just wanted to file before it gets lost in the shuffle

**Comment by terencechain** [comment]
can no longer reproduce
