### ISSUE TITLE
Prysm Eth2 Testnet installation help

### ISSUE THREAD

**Issue by speed141** [prysmaticlabs/prysm#3108]
Hi, please I need your help installing Prysm Eth2 Testnet

Step 3) Create a validator public-private key:

docker run -it -v /tmp/prysm-data:/data \
   gcr.io/prysmaticlabs/prysm/validator:sapphire \
   accounts create --keystore-path=/data --password=changeme

This command line give me this error:
docker: invalid reference format.
See 'docker run --help'.

**Comment by skillful-alex** [comment]
Do you work on linux?
Do you have a /tmp/prysm-data folder on your computer?
try:
```
docker run -it -v "/tmp/prysm-data:/data" \
gcr.io/prysmaticlabs/prysm/validator:sapphire \
accounts create --keystore-path=/data --password=changeme
```

**Comment by prestonvanloon** [comment]
yeah, it looks like you are missing the new line escape. If you're running on windows, try putting everything into one line.

**Comment by rauljordan** [comment]
Hi @speed141 did this resolve your issue?

**Comment by speed141** [comment]
Yes, thank you very much!!

Envoyé de mon iPhone
