### ISSUE TITLE
Implement mock start of eth2 for interop testing 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3116]
Opening this issue to track the implementation progress of mock start for interop testing. The mock start discussions and spec are defined here: https://github.com/ethereum/eth2.0-pm/issues/60

**Comment by prestonvanloon** [comment]
Also see: https://github.com/sigp/lighthouse/blob/master/docs/interop.md#yaml

**Comment by rauljordan** [comment]
Working on this

**Comment by rauljordan** [comment]
This functionality is available in our latest master
