### ISSUE TITLE
Attestation signatures are verified multiple items in RequestBlock RPC

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3132]
![Screenshot from 2019-08-03 16-39-48](https://user-images.githubusercontent.com/7246818/62416703-c6580c80-b60d-11e9-9d8d-178af423c867.png)

We should preprocess attestations as part of insertion into the attestation pool. Double verifying (at block proposal!!!) is too expensive and could cause block production to time out. This issue accounts for about ~500ms of wasted block production time.

**Comment by prestonvanloon** [comment]
Note: this is happening 3 times as part of block production.
1. Package attestations into a block
2. Compute resulting state root for this block 
3. Propose signed block

I think this is a total of 1.5s in signature verification.

**Comment by prestonvanloon** [comment]
Thoughts from offline discussion with @nisdas and @terencechain:

We are verifying attestation signatures in the following places:
1. New attestation: sync or RPC when we receive the initial (aggregated) attestation.
2. New block: at sync or RPC when we receive a block with attestations.
3. At attestation insertion into the attestation pool
4. When computing the state root, as part of operations processing. (Same as 2 probably).
5. When requesting attestations from pool.

Many of these are redundant verification in the same code path. I'll follow up with a simplified path where we only verify attestations when inserting into the attestation pool or when we receive a new block from RPC or sync.

**Comment by terencechain** [comment]
Id like to add, there should be 2 unique paths so we don't confuse them. The paths don't overlap.

receive attestation -> attestation gets put into pool -> attestations get packaged into a block -> block gets passed to the proposer -> proposer signs and submits it back
⬆️ This is for fork choice and block produce

receive block -> process attestations in the block and verify they are valid, if not, discard the block
⬆️ This is for finality gadget and rewards/penalties

**Comment by rauljordan** [comment]
I believe processing attestations in RPC was an artifact of the past we used as a "patch" to prevent justified epoch off-by-one errors. I believe this is mitigated by having new core logic, revamped fork choice, and an overall stronger runtime that we should not need to do this in many different places.
