### ISSUE TITLE
Optimize new fork choice rule

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3162]
To follow up on #3088, this issue calls for various optimization methods for the new fork choice. Techniques simple as "fast pathing" and "clean winner" will help fork choice in run time tremendously. Here are a few techniques we can explore:

- [x] fast pathing: if a node has. one child, then don't have to look up anything to know this is the best child
- [ ] majority voting/clear winner: if a node at a given height has majority of the votes at the height then it'll always be part of the highest weighted path from justified node to the head
- [ ] Log look up: don't have to check all heights, only look up a few heights in smaller steps
- [ ] attestation pruning: prune attestation for branches that are not part of the path

**Comment by terencechain** [comment]
Flame graph of fork choice on 512 sequential blocks. The techniques above should shorten this time by a lot
<img width="1326" alt="Screen Shot 2019-08-09 at 7 02 10 AM" src="https://user-images.githubusercontent.com/21316537/62787667-0db12380-ba7a-11e9-8893-0cde36b8f543.png">

**Comment by terencechain** [comment]
Implemented fast pathing and cut down 512 sequential block's `GetHead` time to:
**Before:**
`BenchmarkForkChoiceTree3-4              1    23124557997 ns/op`
**After:**
`BenchmarkForkChoiceTree3-4           2000        779190 ns/op`

**Comment by rauljordan** [comment]
Done by @terencechain with the new proto array feature
