### ISSUE TITLE
Deploy images to Dockerhub

### ISSUE THREAD

**Issue by TamirTian** [prysmaticlabs/prysm#3166]
Can you upload it to docker hub?
```bash
Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers
```

**Comment by prestonvanloon** [comment]
Can you elaborate on how this was caused? 

A quick google search for that error indicates that your environment did not have access to the internet. https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md#unable-to-pull-imagesclienttimeout-exceeded-while-awaiting-headers

**Comment by TamirTian** [comment]
It's ok when i changed other one Internet provider however previous network provider wasn't very good. 
Of course, we can use Ali hub of proxy the 'Docker.com' if pushed to docker hub

**Comment by prestonvanloon** [comment]
Got it! We'll see what we can do to mirror the images to dockerhub as well.

**Comment by rauljordan** [comment]
@prestonvanloon
