### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [prysmaticlabs/prysm#3214]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by yevgenypats** [comment]
Hi @prestonvanloon ! Thanks for pin-pointing the interesting places to fuzz, that would definitely save me some time. will keep you posted on the progress.

**Comment by yevgenypats** [comment]
@prestonvanloon we already have an initial fuzzer for go-ssz (which already found some bugs). I'm not familiar with the CI that you use (buildkite). how do I add another step there?

**Comment by prestonvanloon** [comment]
hey @yevgenypats we're very eager to include your changes with fuzz testing! 

Is there anything I can do to help?

**Comment by yevgenypats** [comment]
@prestonvanloon here are the instructions that are needed to be added to buildkite 

https://github.com/prysmaticlabs/go-ssz/pull/81

**Comment by rauljordan** [comment]
We are now using fuzzit thanks to some new work from @prestonvanloon. We can close this issue.
