### ISSUE TITLE
Testnet is down!

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3225]
The testnet at http://prylabs.net is currently not running and users fail to sync. 
The reason for this is that we turned off our nodes and effectively stopped the existing testnet so we could focus on a few critical components for final client interoperability in phase 0.

Here are the tracking issues for critical components that are blocking release of new testnet:
- [x] Fork choice changes https://github.com/prysmaticlabs/prysm/issues/3219
- [x] Networking interop alignment & sync protocol https://github.com/prysmaticlabs/prysm/issues/3147
- [x] Database refactor https://github.com/prysmaticlabs/prysm/issues/3064

**Comment by bitcoinsky3000** [comment]
Someone knows when the testnet will be online again?

**Comment by droconnel22** [comment]
Thank you @prestonvanloon and team for you hard work. Looking forward to Testnet being up soon.

**Comment by prestonvanloon** [comment]
Thanks for your patience all. The testnet is online again and mostly stable. At this point, I feel confident in closing this issue while we monitor for issues.

Enjoy! 
https://prylabs.net
