### ISSUE TITLE
Re-Enable Travis CI Once K8S Dependency Changes Stops Breaking Build

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3238]
Currently seeing this as breaking our CI build:

```
369.04s$ go get ${gobuild_args} -t ./...
# k8s.io/client-go/transport
../../../k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
../../../k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
# k8s.io/utils/trace
../../../k8s.io/utils/trace/trace.go:100:57: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
../../../k8s.io/utils/trace/trace.go:112:56: invalid operation: stepThreshold == 0 || stepDuration > stepThreshold || klog.V(4) (mismatched types bool and klog.Verbose)
```

Looks like some upstream dependencies changed, such as `klog` which are causing this problem.

We will disable travis for now until the k8s transitive dependencies are fixed, as they are causing red checkmarks and problems in our development for now.

**Comment by prestonvanloon** [comment]
I filed an issue here: https://github.com/kubernetes/client-go/issues/659

**Comment by rsreeni** [comment]
Hi,

Im still having the issue..

Heres the error I get

src/k8s.io/client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool

src/k8s.io/client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool

My go.mod refers as follows..

            istio.io/api v0.0.0-20190907133855-07957a9b3cc0

            k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d

            k8s.io/client-go v0.0.0-20190819141724-e14f31a72a77

            k8s.io/klog v0.4.0 // indirect

            k8s.io/kube-openapi v0.0.0-20190816220812-743ec37842bf // indirect

            k8s.io/utils v0.0.0-20190907131718-3d4f5b7dea0b // indirect
Any help on what I am doing wrong ? Stuck with a broken build now.

Thanks,

-Sreeni

**Comment by rauljordan** [comment]
Hi there @rsreeni, we don't recommend using go.mod with our project, as we exclusively fix our deps with Bazel so we don't worry about third party changes breaking our build. We don't currently have support for go mod

**Comment by rauljordan** [comment]
Travis provides little value to our project - we should consider abandoning it and sticking with the buildkite pipeline
