### ISSUE TITLE
Check Parent Hash in Block Processing Function

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#324]
When a beacon node processes a incoming beacon block, one of the verification step is to check the incoming block's parent hash correctly exists and locally stored in the beaconDB. To fix this issue, we should implement conditional check to verify `block.ParentHash`exists in beaconDB and return an error if it doesn't

https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/blockchain/core.go#L108

**Comment by s1na** [comment]
Can I give this a try?

**Comment by prestonvanloon** [comment]
Yes. 

Consider this assigned to @s1na
