### ISSUE TITLE
Have Each Service Run a Single, Main Routine to Prevent Race Conditions

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#325]
Hi all,

As per the work @rawfalafel is doing in #322, we have discussed having every service run a single, main routine instead of multiple different ones that have shared state. This will allow for the prevention of race conditions at runtime that will be pesky to catch and allow for simpler services.

**Comment by rawfalafel** [comment]
The one exception in `beacon` and `shared` that I see is `shared/p2p/service.go`. It starts one goroutine per topic but they're all self-contained.

**Comment by rauljordan** [comment]
I think it means that we originally had services that did:

```go
func Start() {
  go doXThing()
  go doYThing()
  go doZThing()
}
```

and instead we can have

``go
func Start() {
  go run()
}

func run() {
  // select statement that handles all goroutines with shared state
}
```

**Comment by terenc3t** [comment]
I can take on this later today if there's still any work left
