### ISSUE TITLE
Processed Attestations Need to be Tracked

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3258]
Currently we aggregate attestations on the fly, combining the bitfields and signatures to aggregate multiple attestations into a single one. However once an attestation with the same data root has been processed by the beacon node, we delete the attestation from our db.

We directly remove attestations by their data root from the db, we don't account for differing aggregation bitfields in the attestations that were processed and the ones that were deleted from the db. In networks with a small number of nodes, this wouldn't be an issue as attestations are easily gossiped to all nodes, so most attestations would be 'full' , however once networks become larger then a significant portion of attestations will not be successfully gossiped to all nodes. This will lead to the majority of attestations being 'partial' instead of 'full'. In this scenario the beacon node will have to track attestations by their data root, which validators have attested to them so far, and which validator's attestations have been processed and accounted for. 

This issue will track the design for effectively tracking attestations, and accounting for all possible edge cases.

**Comment by terencechain** [comment]
This is very similar to #3157, can we use that issue? and maybe copy some of the description from here to there

**Comment by nisdas** [comment]
@terencechain Just noticed that, shifting over to that issue and closing this one
