### ISSUE TITLE
Add Helper for Querying ValidatorIndex from State By Public Key

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3277]
This is a tracking issue to implement a simple helper with signature:

```go
func LookupValidatorIndexByKey(beaconState *ethpb.BeaconState, publicKey [48]byte) (uint64, bool, err)
```
which uses a public key to lookup a validator index in the beacon state.

**Comment by jamesthesken** [comment]
Hey @rauljordan I'd like to take a look at this if it's still needed

**Comment by jamesthesken** [comment]
Is this in reference to https://github.com/prysmaticlabs/prysm/issues/3277 ?

**Comment by rauljordan** [comment]
This is no longer needed nor does it solve a pressing problem, so will close unless it is worth revisiting
