### ISSUE TITLE
attestation signature fails to verify with 256+ validators

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3356]
With 256 validators on one beacon node, we start to see aggregated attestation fails to verify signature

`ERROR validator: Could not submit attestation to beacon node: rpc error: code = Unknown desc = attestation aggregation signature did not verify`

**Comment by rauljordan** [comment]
This has been fixed as of latest master. The problem was we were using binary.ReadUvarInt to parse the validator index from the DB, when instead we should have been using binary.LittleEndian.Uint64
