### ISSUE TITLE
batch attestation store  without goroutines 

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#3374]
i stumbled upon this code while writing slasher db store functions:
`	return k.db.Batch(func(tx *bolt.Tx) error {
		bkt := tx.Bucket(attestationsBucket)
		for i := 0; i < len(atts); i++ {
			indicesByBucket := createAttestationIndicesFromData(atts[i].Data, tx)
			if err := updateValueForIndices(indicesByBucket, keys[i], tx); err != nil {
				return errors.Wrap(err, "could not update DB indices")
			}
			if err := bkt.Put(keys[i], encodedValues[i]); err != nil {
				return err
			}
		}
		return nil
	})
}`

[in SaveAttestations function ](https://github.com/prysmaticlabs/prysm/blob/8f01b76366d0bfb17497f747fef47b96cb4bdbf4/beacon-chain/db/kv/attestations.go#L156-L169)

from my experience with [boltdb batching](https://github.com/boltdb/bolt#batch-read-write-transactions) it doesn't work without calling it from separate goroutines

to solve this issue we must call the put methods from separate goroutines.
@rauljordan wdyt

**Comment by rauljordan** [comment]
Resolves by #3622
