### ISSUE TITLE
Handle Concurrent Hello Handshakes

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3419]
When we connect with a new node, we send a hello request and they send us one vice versa. This leads to two concurrent streams being opened, there are cases that one handshake could fail while the other succeeds. This still will cause that peer to be disconnected despite being a valid peer. A PR to resolve this issue would check for streams already opened with that peer before initiating the hello handshake.

**Comment by prestonvanloon** [comment]
I wonder if this was a symptom of something else. For example, we see EOF and handshake failures when requesting another handshake after we have received one already. #3644 

This bug seems aligned in that if we had a successful handshake, the second one would fail.

**Comment by rauljordan** [comment]
Still relevant @prestonvanloon @nisdas?

**Comment by prestonvanloon** [comment]
Probably not.
