### ISSUE TITLE
BlocksByRoot request type should be [][32]byte

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3438]
The request type is not using a ssz container for `BlocksByRoot`. 

This breaks our design of using proto.Message as the base message so we'll need to rethink the API.

See https://github.com/ethereum/eth2.0-specs/pull/1404 for the latest incoming changes.

**Comment by prestonvanloon** [comment]
There are a few other diffs with networking spec, we'll need to review

**Comment by rauljordan** [comment]
Resolved by #3512
