### ISSUE TITLE
Implement Slashing Conditions

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#345]
The current research spec has not described the conditions in any detail yet, however when they do they will need to be implemented and added to the main `updateChainState` service. Tentatively the condtions that might be implemented are listed below:

- Casper FFG height equivocation
- Casper FFG surround
- Beacon chain proposal equivocation
- Shard chain proposal equivocation
- Proof of custody secret leak
- Proof of custody wrong custody bit
- Proof of custody no secret reveal
- RANDAO leak

**Comment by rauljordan** [comment]
Update on this @nisdas ? Can we close ?

**Comment by nisdas** [comment]
Nope , the spec has actually just been specified. So we will be implementing them now with #598

**Comment by rauljordan** [comment]
This is closed by #1086 and #1076
