### ISSUE TITLE
"Could not fetch validator index: not found"

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3462]
The following bug manifests when we have a validator client running both pre-chainstart and post-chainstart validator keys. The post-chainstart validators will frequently receive the error "could not fetch validator index: not found", instead of gracefully returning either an UNKNOWN status or doing a fallback search through the beacon state in case the validator is not found in the DB.

**Comment by prestonvanloon** [comment]
How to reproduce? Is this with mock start or from goerli?

**Comment by prestonvanloon** [comment]
Ping on this. Need more info or close please.

**Comment by rauljordan** [comment]
No longer relevant, resolved by how our current testnet handles activations
