### ISSUE TITLE
Update CanProcessBlock To Fetch Genesis Block From Disk

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#349]
Right now, `CanProcessBlock` checks the slot number's validity against a [fixed timestamp](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/block.go#L40). Ideally the timestamp should reflect the timestamp of the genesis block on disk. Furthermore, its fairly inefficient to create a new block object when all we need is the timestamp. This ticket should address both issues by fetching the genesis block from disk and keeping the timestamp in memory.

**Comment by IvanTheGreatDev** [comment]
I'm looking to give this a go, how would one fetch the genesis block from the disc?

**Comment by terenc3t** [comment]
Closed via #373

**Comment by IvanTheGreatDev** [comment]
Can this be closed now?

**Comment by nisdas** [comment]
Yeap, I will close it
