### ISSUE TITLE
Calling GenesisBeaconState at Chainstart Takes Too Long

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3501]
When ever we call `GenesisBeaconState`
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/state/state.go#L54
it takes a large amount of time if we have a large number of genesis deposits. This is because we process each deposit again in this function at chainstart, a potential solution would be to keep a genesis state in memory, or genesis validators in memory. This issue is to explore methods in which we can optimize this so that state generation at chainstart is as short as possible

**Comment by rauljordan** [comment]
No longer a problem in master with #4154
