### ISSUE TITLE
Split BeaconChain.persist Into Active/Crystallized State

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#352]
`persist` should be split into two functions to allow one to be udpated without the other. This will become  necessary when the size of the crystallized state increases with the validator set.

In addition, this issue should refactor the existing code to batch writes to disk, particularly when updating the crystallized state. Currently in `computeValidatorRewardsAndPenalties`, the entire crystallized state is being written to disk for every single validator. Instead the entire function should perform a single write to disk.

**Comment by terenc3t** [comment]
Addressed this in #367
