### ISSUE TITLE
Handle Different File Types for Genesis States

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3593]
Currently by default we unmarshal any genesis state file using ssz. However we might get genesis states of different file types such as json,yaml. By right we should be checking the file type of the genesis state before unmarshalling them. This issue is to track the implementation of this in the `interop-coldstart` service.

**Comment by rauljordan** [comment]
Still relevant? Can't foresee any use cases for json or yaml states so far -  seems like .ssz is the standard

**Comment by rauljordan** [comment]
@nisdas

**Comment by rauljordan** [comment]
Closing this for now as there is little utility in the feature
