### ISSUE TITLE
Exploring Shorter Duration Testnets

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3604]
This is a tracking issue to look into how far we can tweak our `SecondsPerSlot` parameter and still have a stable runtime. We can use this issue to track bottlenecks or critical failures as we reduce the slot duration and figure out what our current max-min scenario of `NumValidators` to `SecondsPerSlot` realistically is.

- [x] Mock BLS verification and signature creation with a feature flag to eliminate the BLS outlier in performance analysis
- [x] Optimize db.BlockRoots to return the keys in the db lookup instead of unmarshaling blocks and then computing their signing roots
- [x] Change the call to db.Blocks to a db.View transaction instead of an unnecessary Batch call
- [x] Batch save validator latest votes instead of a sequential save which is slow and does not leverage concurrency
- [x] Batch save operations for blocks, head block root, and attestations in general

**Comment by rauljordan** [comment]
Latest progress: was able to make a 30x improvement in fetching db block roots. Instead of fetching all blocks and computing their signing root, we now simply retrieve the bolt db keys.

Previous:
<img width="343" alt="Screen Shot 2019-09-27 at 12 10 02 PM" src="https://user-images.githubusercontent.com/5572669/65787996-c8c37800-e11f-11e9-9726-9971ef6f4967.png">

After:

![Screen Shot 2019-09-27 at 12 09 49 PM (2)](https://user-images.githubusercontent.com/5572669/65788017-cc56ff00-e11f-11e9-83fc-7f76f2e3922a.png)

**Comment by rauljordan** [comment]
Really great progress! 100x improvement in the ReceiveAttestation pipeline from before across the board, using more batching techniques in bolt and eliminating more red flames one at a time. The predominant bottleneck now is proto.Clone(state), db.HeadState, and indeed process slots -> . hash_tree_root(state).

![Screen Shot 2019-09-27 at 1 25 17 PM](https://user-images.githubusercontent.com/5572669/65792969-75a2f280-e12a-11e9-92cf-eedf8cf8e3f0.png)

**Comment by terencechain** [comment]
Can we close this? @rauljordan

**Comment by rauljordan** [comment]
Yes, we have decided 256 per beacon node is an relative maximum we would recommend per beacon node, and we are able to go down to 2 to 3 seconds without problem due to new optimizations
