### ISSUE TITLE
Beacon Chain block processing fails with error

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#3628]
Looks like processing block 28160 failed to process, after a resync it worked again.

Block processing information:
> [2019-09-27 15:58:56]  INFO sync: Requesting parent block currentSlot=28160 parentRoot=4fed5b23a950cfa9227263b674a086b90bf67df60b121afdbdc21419c5d7db5d

Error + Stacktrace:
https://pastebin.com/0yuj4Pv4

**Comment by rauljordan** [comment]
Duplicate of #3664
