### ISSUE TITLE
Change log level of not-so-relevant information

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#3630]
Lots and lots of this in Beacon Chain:
> WARN sync: Ignored incoming attestation that points to a block that isn't in the database.

As suggested in Discord by @rauljordan & @nisdas, move this to debug.

**Comment by terencechain** [comment]
This is actually a missing feature on our end. We need to save those attestations in a pending queue and process them as their blocks come in. In the mean time we can change it to `debug`. Thanks for opening this issue!

**Comment by rauljordan** [comment]
Resolved by #3600
