### ISSUE TITLE
CORS error from test net

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3638]
@nisdas reported there's a need to restart a few times before getting validator's status changed. The reason behind it could very well be the CORS failures from the testnet site:

`
participate:1 Access to XMLHttpRequest at 'https://api.prylabs.net/faucet.FaucetService/RequestFunds' from origin 'https://prylabs.network' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

**Comment by prestonvanloon** [comment]
This has been resolved.
