### ISSUE TITLE
Support Secure gRPC Connections by Default

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#366]
PR #364 introduces gRPC server connection through insecure connections.

https://github.com/prysmaticlabs/prysm/pull/364/files#diff-6df2af9c5a6ba83c50b7b5ec427fba94R39

We should do the following:
- Add flag to specify insecure connections (`--use_insecure_rpc` or similiar) where the default is secure connection
- Warning that this is an insecure connection
- Support TLS secure connections provided by the server through letsencrypt.org or similar 

There may be multiple gRPC server/client connections. This issue should capture all of those cases.

**Comment by rauljordan** [comment]
Can this be closed @prestonvanloon ?

**Comment by prestonvanloon** [comment]
Yes. The default would require to ship with a certificate of some kind. We have a WARN level logging to communicate that the connection is insecure for now.
