### ISSUE TITLE
Benchmark processing times with 65536 validators

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3668]
Specific requests are 

1. The processing time of a block containing 65536 votes split between 128 attestations
2. The processing time of a block containing 65536 votes split between 256 attestations

The obvious barrier to this test is the state setup.

Generating a state with 65536 deposits is expensive so we should consider a precomputed / pregenerated state on disk with keys to load. Additionally, some tests may want to precompute their setup data and store that on disk so the test isn't a extra burden to run in CI. 

General requirements:
- [ ] Precompute 65536 or more BLS keys (using the deterministic algorithm)
- [x] Precompute genesis state with 65536 validators (using keys from above)

Specific requirements:
- [x] Precompute a block with 65536 votes split between 128 attestations
- [x] Write a test that processes that block (to prevent code rot in the next step)
- [x] Write a benchmark that uses the inner logic of the test above to determine expected processing time
- [ ] Write second set of a test / bench with 65536 votes split between 256 attestations.

The latter scenario may be more difficult because MAX_ATTESTATIONS is a [hardcoded parameter](https://github.com/prysmaticlabs/prysm/blob/8ece8fb44bfc24fee83bfc4539fa5d9aaa12e215/proto/eth/v1alpha1/beacon_block.proto#L49) in `ssz-max` in protobuf definitions.

**Comment by rauljordan** [comment]
Done by #3688
