### ISSUE TITLE
Improve docker commands in the documentation

### ISSUE THREAD

**Issue by santiagorp** [prysmaticlabs/prysm#3692]
Some docker commands can be improved in the documentation.

In the file `README.md`, the command to start the beacon node has the following problems:

1. Typo in the `--clear-db` parameter (a backslash is missing in the previous line)
2. The `/tmp` directory is deleted in each system reboot so the chain data will need to be re-synced and also the private keys will be lost. As a result the user will need to re-create all the steps, get testnet ETH, activate a new validator, etc). Better to use a directory in the user directory.
3. The container created with the example will be kept and a new one will be created each time.

On the other hand a reminder indicating that validators should not be activated before the beacon node is synced should be added. Otherwise the validators will not be able to operate as intended and funds will be lost.

To avoid these issues I suggest the following changes:

1. Do not clear the DB unless necessary
2. Store the chain data and keys in the user directory instead of /tmp
3. Name the container so it can be start/stopped whenever the user wants to restart.
4. Add example commands to start, stop, delete and re-create the container and DB without losing keys.

In the same way the documentation at https://prysmaticlabs.gitbook.io/prysm/ and https://prylabs.net/participate should be updated to reflect the same changes.

Besides this, the command to generate the key pair from the https://prylabs.net/participate page should include the `--rm` parameter to delete the container after execution:

```
docker run --rm -it -v /tmp/prysm-data:/data \
   gcr.io/prysmaticlabs/prysm/validator:latest \
   accounts create --keystore-path=/data --password=changeme
```

In the same page (step 4) the user should be advised to **not start the validator till the beacon node** is synced!

**Comment by prestonvanloon** [comment]
cc: @har00ga

**Comment by har00ga** [comment]
Hey there, thanks for noting these issues :slightly_smiling_face: I'll have them adjusted on the README and in the Gitbook by the weekend.

**Comment by har00ga** [comment]
Updated in the Gitbook documentation: https://prysmaticlabs.gitbook.io/prysm/

**Comment by terencechain** [comment]
We can close this with the merge of #3834
