### ISSUE TITLE
Render graphviz raw string in html

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3696]
For #3690, I'm looking for help to use JS to render raw dot data.
For example the HTML can be:
```html
<html>
<head>
  <!-- CDN hosted graphviz library -->
</head>
<body>
  <graphviz>
    {{ dot syntax stuff here }}
  </graphviz>
</body>
</html>
```
http://viz-js.com/  <- Given such diagraph, the library can be rendered in browser. We'll need to fiure out how to plugin JS to the html template and understand how viz-js works.

**Comment by prestonvanloon** [comment]
https://github.com/mdaines/viz.js/wiki/Usage

I took a quick glance at the docs and here's what I think you need to do (mostly copied from the link above):
```html
<html>
<head>
<script src="viz.js"></script> <!--replace this with CDN-->
<script src="full.render.js"></script> <!--replace this with CDN-->
<script type="application/javascript">
   var graph = "%s"; // Inject your dot string here, fully escaped and everything.
</script>
<script>
  var viz = new Viz();
  
  viz.renderSVGElement(graph) // reading the global graph, or inject here.
  .then(function(element) {
    document.body.appendChild(element); // appends to document. 
  })
  .catch(error => {
    // Create a new Viz instance (@see Caveats page for more info)
    viz = new Viz(); // I dont know what this is about?

    // Possibly display the error
    console.error(error);
  });
</script>
</head>
<body>

</body>
</html>
```

CDN hosted files are here: https://cdnjs.com/libraries/viz.js

There are also examples here: https://github.com/mdaines/viz-examples

**Comment by terencechain** [comment]
Thanks so much for the context, here's an example dot string generated by the chain service handler:
```
digraph  {
	label="Canonical block = green";labeljust="l";rankdir="RL";
	n5[color="green",label="slot: 5\n root: 06d8",shape="box"];
	n6[color="green",label="slot: 6\n root: 31aa",shape="box"];
	n4[color="green",label="slot: 4\n root: 4e74",shape="box"];
	n2[color="green",label="slot: 2\n root: 73bf",shape="box"];
	n1[color="green",label="slot: 1\n root: 9106",shape="box"];
	n3[color="green",label="slot: 3\n root: faa7",shape="box"];
	n5->n4;
	n6->n5;
	n4->n3;
	n2->n1;
	n3->n2;
}
```

**Comment by rauljordan** [comment]
Closed by @terencechain and #4108

**Comment by prestonvanloon** [comment]
This doesn't print the HTML rendering. I'll pick this up since it's simply plugging in the suggestions from my comment in october

**Comment by terencechain** [comment]
thanks @prestonvanloon 

here's the code: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/blockchain/info.go#L78
