### ISSUE TITLE
Validators are Penalised Despite Consistent Participation

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3697]
![image](https://user-images.githubusercontent.com/33201827/66103528-b475f400-e5d3-11e9-9669-611d566eed19.png)

Some users have reported being penalised despite having their validator consistently attesting to the current head. The above image contains the logs of a validator which has been penalised.

1) Attestations are not being included properly, which leads to momentary penalties.
20 Messages not being successfully propagated through gossipsub, which leads to the attestation going missing

This issue is to track this bug

Possibly Related to #3691

**Comment by prestonvanloon** [comment]
Occasional penalty is expected when committee sizes are not divisible by the number of slots per epoch. 

Consistent penalty is another issue...

**Comment by rauljordan** [comment]
This no longer the case in our testnet with v0.9 since launch
