### ISSUE TITLE
BLS pubkey copy is not a copy

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3700]
The copy method calls Set
https://github.com/prysmaticlabs/prysm/blob/6d2ce49c066762069a6f3342a11b8883f2d523ee/shared/bls/bls.go#L130-L133

and Set uses the same pointers of `PointG1`

```go
func (p *PointG1) Set(p2 *PointG1) *PointG1 {
	p[0].Set(&p2[0])
	p[1].Set(&p2[1])
	p[2].Set(&p2[2])
	return p
}
```

https://github.com/kilic/bls12-381/blob/0e0109c48123644c3af40cb5f8586b18b58b460e/g1.go#L10-15

In short, these are still the same objects under the hood and could be mutated. This could allow for the pubkey cache to be poisoned which leads to #3664.

**Comment by prestonvanloon** [comment]
cc: @kilic

**Comment by kilic** [comment]
Naming is misleading. At element level it is a copy.

```go
type Fe [6]uint64

func (fe *Fe) Set(fe2 *Fe) *Fe {
	fe[0] = fe2[0]
	fe[1] = fe2[1]
	fe[2] = fe2[2]
	fe[3] = fe2[3]
	fe[4] = fe2[4]
	fe[5] = fe2[5]
	return fe
}
```

**Comment by prestonvanloon** [comment]
Thanks for clarifying!
