### ISSUE TITLE
Implement Validator Client <> Beacon Node Redundancy

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3745]
A bad beacon node will cause problems in individual validator clients such as causing them to lose money or get slashed. We should have the ability for a single validator to connect to multiple beacon nodes as sources of truth. This is a tracking issue as this feature will require a design to complete.

**Comment by prestonvanloon** [comment]
gRPC allows multiple servers with client side load balancing.  We actually had a lot of issues with frequent shifting of server backends. Perhaps a better route is to improve health checks and not serve traffic when a beacon chain is bad.

One simple solution is to provide multiple backends, if desired for client side load balancing.

**Comment by rauljordan** [comment]
> One simple solution is to provide multiple backends, if desired for client side load balancing.

This is sufficient to resolve this issue, that's what I had in mind

**Comment by jonfowler1231** [comment]
Did this enhancement ever get added?

**Comment by rauljordan** [comment]
Hi @jonfowler1231 this is possible by specifying a list of beacon node addresses to the validator client separated by comma such as:

`--beacon-rpc-provider=localhost:4000,localhost:4001`

It matters what beacon node you are connected to, and we recommend sticky load-balancing if you want to a highly-available setup. It is up to the operator how they wish to load balance validators and beacon nodes. We prefer stakers do not use this feature, but instead handle load balancing in their cloud infrastructure if they are running Prysm in the cloud
