### ISSUE TITLE
Phase 1: Implement custody bits on attestations

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3791]
This is a generalized tracking issue for stubbed logic regarding custody bitfields.

**Comment by rauljordan** [comment]
Is this still relevant? It has been removed and will likely be redesigned as phase 1 keeps materializing over the coming months.

**Comment by terencechain** [comment]
Still relevant. See: https://github.com/ethereum/eth2.0-specs/pull/1427

**Comment by terencechain** [comment]
With that said. We have removed all custody bit stubs for phase 0. I'm ok with closing this for now

**Comment by terencechain** [comment]
Custody bits completely removed in `master`, waiting for researchers/spec writers to redefine them in phase 1 spec. Will close this now
