### ISSUE TITLE
Error received during initial sync

### ISSUE THREAD

**Issue by pjindal** [prysmaticlabs/prysm#3809]
Received the following error during initial sync of the beacon chain using the latest docker image (10/19/19): 

https://media.discordapp.net/attachments/560308336248225812/635173657345523742/unknown.png

Copying error as text:

[2019-10-19` 16:18:09]  INFO initial-sync: Processing block 16445/28925 - estimated time remaining 17m7s blocksPerSecond=12.2 peers=5/8
[2019-10-19 16:18:21] ERROR powchain: Post https://goerli.prylabs.net: read tcp 172.17.0.2:56472->52.23.23.253:443: read: connection reset by peer
panic: no peers left to request blocks

goroutine 182 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc00090bcb0)
        beacon-chain/sync/initial-sync/service.go:107 +0x98d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 `+0x23e

@nisdas

**Comment by pjindal** [comment]
May be related to #3756 or #3665

**Comment by prestonvanloon** [comment]
This looks like an intermittent networking issue. Either on our side with the testnet hosted nodes or on your local machine. 

Going to close for now. Please re-open if you see it again.
