### ISSUE TITLE
Beacon chain recurring error / warning message every 10-15 minutes 

### ISSUE THREAD

**Issue by pjindal** [prysmaticlabs/prysm#3819]
The following error / warning message recurs every 10-15 minutes:

https://cdn.discordapp.com/attachments/560308336248225812/636008981994799114/unknown.png

Copying text as error:

[2019-10-22 00:08:02] ERROR sync: Failed to handle p2p pubsub error=pre state of target block 62424 does not exist
could not process attestation from fork choice service
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:69
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:146
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1357 topic=/eth2/beacon_attestation/ssz

@terencechain @nisdas

**Comment by prestonvanloon** [comment]
I believe this is due to multiple blocks stored at the same slot in the beacon database. It should be resolved with #3873.
