### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3841]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1091680]

goroutine 171 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(Service).initializeChainInf
o(0xc000a4b500, 0x186ad00, 0xc000044040, 0x0, 0x0)
beacon-chain/blockchain/service.go:316 +0x2d0
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(Service).Start(0xc000a4b500
)
beacon-chain/blockchain/service.go:112 +0x1a8
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
shared/service_registry.go:44 +0x23e
```

Offending line of code: https://github.com/prysmaticlabs/prysm/blob/be5451abef69a9b501945f96e36f03b6bb8874ae/beacon-chain/blockchain/service.go#L316

Not sure how to reproduce yet, asked user for copy of beaconchain.db.

**Comment by prestonvanloon** [comment]
Seems like a regression from #3824 since the symptom is a missing state in the db.

**Comment by prestonvanloon** [comment]
Discussed offline that the process that deletes saved states does so before updating the finalized checkpoint in the database. We can imagine that if the process was terminated in between these events then we have deleted the finalized state from the db.

Solutions:
- Return an error when database tries to delete the finalized state
- Update finalized checkpoint before deleting old states

**Comment by Utopii** [comment]
Got this error. Copy of beaconchain.db
[beaconchain.zip](https://github.com/prysmaticlabs/prysm/files/3765649/beaconchain.zip)
