### ISSUE TITLE
Adjust Processing of Deposit Logs When State Exists

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3852]
We currently process all the deposit logs from genesis irregardless if the node has an already saved beacon state or not. This is not an issue currently for our testnet as we only have 330 deposit logs to process. But in production the number could grow much larger to 65536,etc. Processing all deposit logs in the case of a restart would be repeated computation which serves no purpose, as the deposit logs have already been included on chain. This issue is to track the usage of a finalized checkpoint in the state to use as the point from which to process the remaining deposit logs.

**Comment by cyberbono3** [comment]
@prestonvanloon  can you assign me, please ?

**Comment by rauljordan** [comment]
This is already completed in master thanks to #4154
