### ISSUE TITLE
Hardcode Fork Version for Compute Domain

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3853]
Currently we use `genesis fork version` as our fork version for retrieving the domain for validators to sign with. This cannot be hardcoded currently to `[]byte{0,0,0,0}` as this would break deposit verification in the testnet. However in our next testnet restart we can hardcode it so as to have parity with the spec.

**Comment by terencechain** [comment]
Can we close this with the merging of #3654?

**Comment by nisdas** [comment]
You mean #3854, right ? Not yet we will need to hardcode the version to `[]byte{0,0,0,0}` first and that would only be possible in the case of a testnet restart
