### ISSUE TITLE
Cache Skipped Slots

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3860]
Currently if we face an extended period of no finality, `ProcessSlots` becomes expensive and eventually poses a substantial risk to the functioning of the beacon node. It is because each time we advance the state by 1 slot, we have to treehash the whole state. If we have, for example 10 epochs with no finality, this grows to 80 slots and the beacon-node will have to tree-hash the state 80 times. Usually the beacon-node is not able to complete this in 6s, and therefore any validator cannot propose blocks in time and this starts a death-spiral for the beacon-node and the network. This issue is to track for an implementation of a skipped slot cache that will alleviate this issue.

Some work has already been done on this:
https://github.com/prysmaticlabs/prysm/compare/cache-slots

**Comment by prestonvanloon** [comment]
Closed by #3879
