### ISSUE TITLE
Add Argument to Clear DB 

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3866]
Each time `--clear-db` is run on a beacon node, it forces the user to give an input to clear the db. An argument should be provided to it, to force clean the db. Ex: `--clear-db=force` . This would prevent on user input being required.

This is an issue to track the implementation of it

**Comment by mkinney** [comment]
I think this is ready, but I'd like some help having someone review it/provide feedback.

**Comment by prestonvanloon** [comment]
Why not just make this another flag? `--force-clear-db`? The argument seems a bit cumbersome

**Comment by nisdas** [comment]
that might be a better idea ... 
@mkinney what do you think ? sorry for the changed requirements on this

**Comment by mkinney** [comment]
Since there was only one function in clear_db.go that primarily prompted the user if they wanted to clear the db. Since that option is no longer available via command line flags, I removed that file.

**Comment by nisdas** [comment]
We actually just need 2.) . You can leave the clear-db flag as it is

**Comment by mkinney** [comment]
Ok. I'll do that.

**Comment by mkinney** [comment]
Ok to close this issue. PR was merged.

**Comment by prestonvanloon** [comment]
Closed by #3871
