### ISSUE TITLE
Feature flag cleanup: remove --optimize-process-epoch

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3874]
Ensure this is fully tested at runtime and ready to release.

Original issue #3753.

**Comment by terencechain** [comment]
Please review and merge #3855 for this. It fixed an critical edge case

**Comment by rauljordan** [comment]
No longer exists in master https://github.com/prysmaticlabs/prysm/commit/feb1267feee1c305b6ebaeda305b08f53fa589b7 and has been marked as deprecated
