### ISSUE TITLE
Feature flag cleanup: remove --prune-finalized-states

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3875]
This feature should be fully tested at runtime, released, and flag removed.

**Comment by rauljordan** [comment]
We can close this right @terencechain ?

**Comment by terencechain** [comment]
The flag is still there
https://github.com/prysmaticlabs/prysm/blob/master/shared/featureconfig/flags.go#L81

**Comment by rauljordan** [comment]
Deprecated and no longer used in runtime https://github.com/prysmaticlabs/prysm/commit/feb1267feee1c305b6ebaeda305b08f53fa589b7 - can close
