### ISSUE TITLE
Split Sync into Two Different Services

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#388]
Currently the sync service handles both the initial sync and regular sync. As our implementation grows our initial sync will become more complicated as we start to factor in security concerns, etc . Also the initial sync and regular sync use different methods and fields. 

A pr for this will create a separate struct/service for initial sync and regular sync and also will ensure that only one service will be run at a time. Ex: If the node has no stored state, then the initial sync is run. During that period regular sync is on 'pause' , when initial sync is done, the regular sync resumes.

**Comment by rauljordan** [comment]
Agree with this - same pattern as fetcher/downloader in geth. Perhaps we can do these as subpackages within the syncer package? Maybe call it "announcements" / "chainsync" ? I'd love for us to opt for something easier to understand. @nisdas can you update the sync design doc to include these two items?

**Comment by rawfalafel** [comment]
I can take this one. 

Agree that naming is key. I'm having problems thinking of a good concise name.

**Comment by rawfalafel** [comment]
Resolved with #404
