### ISSUE TITLE
Broadcast Newly Added Blocks

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#389]
Currently nodes do no broadcast any new blocks after they have been proposed or attested to, they just listen to the p2p feed for any newly processed blocks for syncing. A PR for this will allow proposers to broadcast their newly created blocks.  Once this is done nodes will be able to both send and receive blocks instead of currently where they just receive blocks.

**Comment by nisdas** [comment]
Ah, k yeah you are right. For some reason I mixed up saving the blocks with broadcasting them, changed the issue description.

**Comment by rauljordan** [comment]
Completed by #1830
