### ISSUE TITLE
Pre State of Slot 56911 Does Not Exist

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#3890]
I have been attempting to sync the beacon-chain from a clear DB today, and keep running into errors such as the following examples, in order:

> [2019-10-29 17:05:27]  INFO forkchoice: Executing state transition on block root=0x615fe62b... slot=40835
[2019-10-29 17:05:27] DEBUG blockchain: Saved new head info headRoot=0x615fe62b3b1504a0b7070822716668e70367c78a93be86f48307b201e2e108df slot=40835
[2019-10-29 17:05:27]  INFO blockchain: Finished applying state transition attestations=3 deposits=0 slot=40835
[2019-10-29 17:05:27]  INFO initial-sync: Processing block 40837/173398 - estimated time remaining 26h18m6s blocksPerSecond=1.4 peers=3/5
panic: could not process block from fork choice service: pre state of slot 40837 does not exist
goroutine 232 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0007d0b10)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e
2019/10/29 17:49:24 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined

...and...

> [2019-10-29 20:42:23]  INFO forkchoice: Executing state transition on block root=0x2858fb8b... slot=56908
[2019-10-29 20:42:24] DEBUG blockchain: Saved new head info headRoot=0x2858fb8b89c19c1cecade24a41f4e8160832ae2181b30a91c87d7bf9acf38e1b slot=56908
[2019-10-29 20:42:24]  INFO blockchain: Finished applying state transition attestations=2 deposits=0 slot=56908
[2019-10-29 20:42:24]  INFO initial-sync: Processing block 56911/175568 - estimated time remaining 26h22m5s blocksPerSecond=1.2 peers=5/5
panic: could not process block from fork choice service: pre state of slot 56911 does not exist
goroutine 225 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0007b20f0)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

So far, after a restart, syncing resumes until the next error occurs.

Pulled latest docker image earlier today, prior to these errors. Though I have seen similar behavior prior to that.

**Comment by Magicking** [comment]
I have the same problem using the today docker-image, I run with ```while true; do docker run -it -v /tmp/prysm-data:/data -p 4000:4000 \
  gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
  --datadir=/data \
  --no-genesis-delay \
  --init-sync-no-verify; sleep 1; done```

**Comment by metanull-operator** [comment]
Another...

> [2019-10-29 22:44:42]  INFO initial-sync: Processing block 65971/176791 - estimated time remaining 27h59m5s blocksPerSecond=1.1 peers=5/6
panic: could not process block from fork choice service: pre state of slot 65971 does not exist
goroutine 251 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0003ee8d0)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

**Comment by metanull-operator** [comment]
> [2019-10-30 02:55:54] DEBUG blockchain: Saved new head info headRoot=0xb74146868146d63a2cc610f62accfde17d288f58eb8159d6aee81b3f38ebccd4 slot=82313
[2019-10-30 02:55:54]  INFO blockchain: Finished applying state transition attestations=3 deposits=0 slot=82313
[2019-10-30 02:55:54]  INFO initial-sync: Processing block 82318/179303 - estimated time remaining 20h43m23s blocksPerSecond=1.3 peers=5/7
panic: could not process block from fork choice service: pre state of slot 82318 does not exist
goroutine 223 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc000399860)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

**Comment by metanull-operator** [comment]
>[2019-10-30 03:32:21]  INFO blockchain: Finished applying state transition attestations=3 deposits=0 slot=84747
[2019-10-30 03:32:21]  INFO initial-sync: Processing block 84752/179667 - estimated time remaining 23h58m6s blocksPerSecond=1.1 peers=5/6
panic: could not process block from fork choice service: pre state of slot 84752 does not exist
goroutine 236 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0005320c0)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

**Comment by metanull-operator** [comment]
> [2019-10-30 03:50:21] DEBUG blockchain: Saved new head info headRoot=0x199110ec77404872ba95feed14307c03d0d2bb419eb55f19198c263d6fc4121c slot=84747
[2019-10-30 03:50:21]  INFO blockchain: Finished applying state transition attestations=3 deposits=0 slot=84747
[2019-10-30 03:50:21]  INFO initial-sync: Processing block 84753/179847 - estimated time remaining 17h2m30s blocksPerSecond=1.6 peers=6/6
panic: could not process block from fork choice service: pre state of slot 84753 does not exist
goroutine 219 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc0002a9e00)
        beacon-chain/sync/initial-sync/service.go:106 +0x97d
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

**Comment by metanull-operator** [comment]
I'll hold back on any further reports, but it continues after this.

**Comment by metanull-operator** [comment]
OK. One more, but only because this next message was different than the rest. Could be separate issue.
 
> [2019-10-30 03:54:59]  INFO blockchain: Finished applying state transition attestations=1 deposits=0 slot=84756
[2019-10-30 03:54:59]  INFO initial-sync: Processing block 84757/179893 - estimated time remaining 16h0m58s blocksPerSecond=1.6 peers=6/6
[2019-10-30 03:54:59] DEBUG operations: No attestations found with this root. root=0x3ab03534139be56e94d4684ce6b86ff39f3b07e8e9b1cc5380e773477556ec72
[2019-10-30 03:54:59] DEBUG operations: block attestation aggregation_bits=[     100 10001000        0   100000     1100] index=0 root=0x3ab03534139be56e94d4684ce6b86ff39f3b07e8e9b1cc5380e773477556ec72 shard=7
[2019-10-30 03:54:59]  INFO forkchoice: Executing state transition on block root=0x02222f40... slot=84757
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0xd4a5ab]

> goroutine 223 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.Seed(0x0, 0x2962, 0x0, 0x0, 0x0, 0x0, 0xc00050af00, 0xc000103c00)
        beacon-chain/core/helpers/randao.go:33 +0x6b
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.CrosslinkCommittee(0x0, 0x2962, 0x0, 0xc00182be90, 0x12fca00, 0x23f4190, 0x14b9ba0, 0xc001660e18)
        beacon-chain/core/helpers/committee.go:93 +0x67
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.AttestingIndices(0x0, 0xc00118e230, 0x18770e0, 0xc00086f420, 0x0, 0x0, 0x0, 0x1871920, 0xc0014b5d40)
        beacon-chain/core/helpers/committee.go:182 +0x63
github.com/prysmaticlabs/prysm/beacon-chain/core/blocks.ConvertToIndexed(0x1871920, 0xc00182be90, 0x0, 0xc000f893b0, 0x0, 0x0, 0x0)
        beacon-chain/core/blocks/block_operations.go:707 +0x11e
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).updateBlockAttestationVote(0xc0003af420, 0x1871920, 0xc00182be90, 0xc000f893b0, 0xd16481593eebeec6, 0x9f3f5b763bdd860f)
        beacon-chain/blockchain/forkchoice/process_block.go:284 +0x149
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).updateBlockAttestationsVotes(0xc0003af420, 0x1871920, 0xc00182be90, 0xc0002215e0, 0x4, 0x4, 0x0, 0x0)
        beacon-chain/blockchain/forkchoice/process_block.go:269 +0x1ae
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).OnBlock(0xc0003af420, 0x1871920, 0xc00182be90, 0xc000118f80, 0x0, 0x0)
        beacon-chain/blockchain/forkchoice/process_block.go:81 +0x518
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockNoPubsubForkchoice(0xc000c102a0, 0x1871920, 0xc00182be60, 0xc000118f80, 0x0, 0x0)
        beacon-chain/blockchain/receive_block.go:123 +0x11e
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).roundRobinSync(0xc000c40120, 0x0, 0xed53a8850, 0x23bbfe0, 0x0, 0x0)
        beacon-chain/sync/initial-sync/round_robin.go:170 +0x2c5
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start(0xc000c40120)
        beacon-chain/sync/initial-sync/service.go:105 +0x5af
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
        shared/service_registry.go:44 +0x23e

**Comment by Magicking** [comment]
Using commit 2785a6d5eeabe28d231177ddd319891ed191f19d image that include the [Track finalized block root index and filter in blocks by range](https://github.com/prysmaticlabs/prysm/pull/3873/commits) PR the behavior I'm observing is that when we restart the beacon-client after a panic, it restarts with its block tip from a few blocks back and then continue processing past the faulty block.

Maybe there is room to consider that the peer that sent the faulty block was misbehaving (spam score?) and there might be another error somewhere for the peer node that sent the faulty block.

**Comment by nisdas** [comment]
hey @Magicking  #3880, should fix this. It will be cleaned up and up for review. If you want, you could try building the PR and sync with the testnet. I am confident this will prevent the `pre state of slot ...` panic from coming up again.

**Comment by Magicking** [comment]
Yes, before using the PR above I had the same `pre state of slot XXXX does not exist` as described by OP at multiple previous blocks

**Comment by rauljordan** [comment]
These problems are now resolved as of our latest testnet release, currently available in https://prylabs.net. Closing for now unless it manifests again.
