### ISSUE TITLE
GenerateFullBlock using the wrong state root?

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3891]
`GenerateFullBlock` 's state root is a tree hash of calculated state root. I found that to be weird but it's working?

```go
	s, err := state.CalculateStateRoot(context.Background(), bState, block)
	if err != nil {
		t.Fatal(err)
	}
	root, err := ssz.HashTreeRoot(s)
	if err != nil {
		t.Fatal(err)
	}
	block.StateRoot = root[:]
```

https://github.com/prysmaticlabs/prysm/blob/master/shared/testutil/block.go#L115

**Comment by rauljordan** [comment]
This is fine @terencechain because the rules of SSZ state hash tree root of a single element with 32 bytes is just that element (the identity function).
