### ISSUE TITLE
Switching web3provider seems to switch correctly

### ISSUE THREAD

**Issue by Magicking** [prysmaticlabs/prysm#3899]
At time of writing the default web3 provider seems to be down and switching to another (wss://goerli.eth.6120.eu/ws) seems to pass the initial check of web3provider available but a non-fatal 503 http error was displayed indicating that maybe the default provider is in use.

**Comment by mkinney** [comment]
What was the command that you were using?

If running from build, what is the commit?

What was the full error?

**Comment by mkinney** [comment]
Is this related to https://github.com/prysmaticlabs/prysm/issues/3755 ?

**Comment by rauljordan** [comment]
Closing - was not able to reproduce. If it is still an issue, feel free to reopen @Magicking
