### ISSUE TITLE
Decouple ETH1 Node From Beacon Node

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#3900]
The Beacon Node is tightly coupled with the connected ETH1 Node. With the Istanbul Hardfork on Goerli, all our beacon nodes ended up crashing due to disconnecting from the eth1 goerli node. Going forward we will need to decouple the eth1 node from our node. We should be able to handle failures,disconnection from the goerli node and still be able to propose blocks, etc .

This issue is to track handling of failures from any connected eth1 nodes.

- Always try to reconnect if an eth1 node disconnects with us
- Utilise a fallback eth1 node, if the default node is bad, serving us no data
or constantly disconnecting, etc.
- In the event the eth1 node cannot be connected with, the beacon node should still
be able to function, utilising a mocked eth1data object.

Related to #3899

**Comment by prestonvanloon** [comment]
Resolved by #3915 and #3914
