### ISSUE TITLE
Testnet is stalled / down

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3901]
The current running testnet (fork version 2) is stalled and will soon be dead. Next testnet is targeting to start on November 4th, pending milestone completion. 

See the [incident write up](https://docs.google.com/document/d/1R4WWO88UtMP_rMY9rwaIGlDuwP_lxhQLbb_zRp65kGY/edit#). 

Follow the progress in the associated milestone for this issue. We'll close this once we start with a new chain.

**Comment by rauljordan** [comment]
Testnet is back up with #3935 :)

**Comment by prestonvanloon** [comment]
Testnet site still needs to be updated. Working through ABI changes from the deposit contract. I'll close this issue again after that is resolved.

**Comment by prestonvanloon** [comment]
Testnet is running but new validator deposits are blocked by https://github.com/prysmaticlabs/prysm/issues/3979

**Comment by prestonvanloon** [comment]
Testnet back up at https://alpha.prylabs.network. Will promote to prod at end of day.
