### ISSUE TITLE
Genesis validator count

### ISSUE THREAD

**Issue by paulhauner** [prysmaticlabs/prysm#3909]
Hello :)

I changed our deposit signatures so they match what Prysm is using. I was able to start from genesis, however our genesis state has 91 validators and the one I received from @prestonvanloon has 64 validators. I believe that 91 is correct and 64 is not.

Looking at the [Genesis](https://github.com/ethereum/eth2.0-specs/blob/v0.8.4/specs/core/0_beacon-chain.md#genesis) section, the spec declares that the genesis state is the first eth1 block where `is_valid_genesis_state(candidate_state) is True`.

The deposits included in the genesis state should be "all valid deposits up to the eth1 block", not "just the first `MIN_GENESIS_VALIDATOR_COUNT` validators".

Looking at the Prysm testnet deposits, these two deposits are interesting:

- https://goerli.etherscan.io/tx/0xf514076edfb0c96610fc42cc9cdb8217603ed7e3108f3d72176783bf701be309
  - Block: 1487306
  - DepositEvent.index: `0x40` (64 dec)
- https://goerli.etherscan.io/tx/0x6b96fde6a16757ee36286c1d4134d8dba0c6c39998f4d70600011e56f28a74e5
  - Block: 1487306
  - DepositEvent.index: `0x5a` (90 dec)

I think these two transactions are sufficient to prove that the number of validators should be >= 91.

#### Note

I have raised a clarification on the spec here: https://github.com/ethereum/eth2.0-specs/pull/1460/files. What I'm saying here is still valid, regardless of the outcome of this PR.

**Comment by nisdas** [comment]
Hey thanks for bringing this up, yeah it seems like we might not be setting the genesis state correctly after re-reading the spec. I will work on this today and get this fixed

**Comment by nisdas** [comment]
@paulhauner #3911 should fix this. Running the PR locally , I also get 91 deposits so I think we should be compatible now

**Comment by paulhauner** [comment]
Great. I'd love to get a copy of your genesis state, if it's not much trouble?

I'll compare it to mine, which has the root `0x2a98…0088`.

**Comment by nisdas** [comment]
Alright attached is the state , with root 
`0xc933be3f4ef861ac5d122de2eb944a94da5025aedaa9bf08e2b878baf3433896` .

I am guessing the difference is the genesis time. We use a modified version of the genesis time:
Ours:
```py
        genesis_time= eth1_timestamp + 30_seconds
```
Spec:
```py
        genesis_time=eth1_timestamp - eth1_timestamp % SECONDS_PER_DAY + 2 * SECONDS_PER_DAY,
```
The primary reason is being able to start up a testnet quickly, otherwise we would have to wait 2 days before the chain starts.

State: 

[genesis.tar.gz](https://github.com/prysmaticlabs/prysm/files/3797127/genesis.tar.gz)
