### ISSUE TITLE
Implement RPC Endpoint to Retrieve Current Config Parameters

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3917]
Feature request from our users in our discord server: having a nice way to retrieve current chain configuration parameters via an RPC endpoint would be very useful to understand what sort of of node one is talking to.

**Comment by mkinney** [comment]
What info?

1. Any exposed endpoints? (rpc, gRPC, health check, swagger, etc.)

2. Anything from BeaconConfig?

(list is derived from the command `find . -type f -name \*.go -exec grep -o "params.BeaconConfig()\.[A-Za-z]*" {} \; | sort | uniq`)

params.BeaconConfig().ActivationExitDelay
params.BeaconConfig().BLSPubkeyLength
params.BeaconConfig().BLSWithdrawalPrefixByte
params.BeaconConfig().BaseRewardFactor
params.BeaconConfig().BaseRewardsPerEpoch
params.BeaconConfig().ChurnLimitQuotient
params.BeaconConfig().DefaultBufferSize
params.BeaconConfig().DefaultPageSize
params.BeaconConfig().DepositContractTreeDepth
params.BeaconConfig().DomainAttestation
params.BeaconConfig().DomainBeaconProposer
params.BeaconConfig().DomainDeposit
params.BeaconConfig().DomainRandao
params.BeaconConfig().DomainTransfer
params.BeaconConfig().DomainVoluntaryExit
params.BeaconConfig().EffectiveBalanceIncrement
params.BeaconConfig().EjectionBalance
params.BeaconConfig().EmptySignature
params.BeaconConfig().EpochsPerHistoricalVector
params.BeaconConfig().EpochsPerSlashingsVector
params.BeaconConfig().Eth
params.BeaconConfig().FarFutureEpoch
params.BeaconConfig().GenesisForkVersion
params.BeaconConfig().GoerliBlockTime
params.BeaconConfig().GweiPerEth
params.BeaconConfig().HistoricalRootsLimit
params.BeaconConfig().InactivityPenaltyQuotient
params.BeaconConfig().LogBlockDelay
params.BeaconConfig().MaxAttestations
params.BeaconConfig().MaxAttesterSlashings
params.BeaconConfig().MaxDeposits
params.BeaconConfig().MaxEffectiveBalance
params.BeaconConfig().MaxEpochsPerCrosslink
params.BeaconConfig().MaxPageSize
params.BeaconConfig().MaxProposerSlashings
params.BeaconConfig().MaxTransfers
params.BeaconConfig().MaxValidatorsPerCommittee
params.BeaconConfig().MaxVoluntaryExits
params.BeaconConfig().MinAttestationInclusionDelay
params.BeaconConfig().MinDepositAmount
params.BeaconConfig().MinEpochsToInactivityPenalty
params.BeaconConfig().MinGenesisActiveValidatorCount
params.BeaconConfig().MinGenesisTime
params.BeaconConfig().MinPerEpochChurnLimit
params.BeaconConfig().MinSeedLookahead
params.BeaconConfig().MinSlashingPenaltyQuotient
params.BeaconConfig().MinValidatorWithdrawabilityDelay
params.BeaconConfig().PersistentCommitteePeriod
params.BeaconConfig().ProposerRewardQuotient
params.BeaconConfig().PruneSlasherStoragePeriod
params.BeaconConfig().RPCSyncCheck
params.BeaconConfig().SecondsPerDay
params.BeaconConfig().SecondsPerSlot
params.BeaconConfig().ShardCount
params.BeaconConfig().ShuffleRoundCount
params.BeaconConfig().SlotsPerEpoch
params.BeaconConfig().SlotsPerEth
params.BeaconConfig().SlotsPerHistoricalRoot
params.BeaconConfig().TargetCommitteeSize
params.BeaconConfig().TestnetContractEndpoint
params.BeaconConfig().ValidatorPrivkeyFileName
params.BeaconConfig().ValidatorRegistryLimit
params.BeaconConfig().WeakSubjectivityPeriod
params.BeaconConfig().WhistleBlowerRewardQuotient
params.BeaconConfig().WithdrawalPrivkeyFileName
params.BeaconConfig().ZeroHash

3. Anything from beaconState?

(list is derived from: `find . -type f -name \*.go -exec grep -o "beaconState\.[A-Za-z]*" {} \; | sort | uniq`)

beaconState.Balances
beaconState.BlockRoots
beaconState.CurrentCrosslinks
beaconState.CurrentEpochAttestations
beaconState.CurrentJustifiedCheckpoint
beaconState.Eth
beaconState.FinalizedCheckpoint
beaconState.Fork
beaconState.GenesisTime
beaconState.LatestBlockHeader
beaconState.PreviousCrosslinks
beaconState.PreviousEpochAttestations
beaconState.PreviousJustifiedCheckpoint
beaconState.RandaoMixes
beaconState.Slashings
beaconState.Slot
beaconState.StartShard
beaconState.Validators

4. Anything else?

**Comment by mkinney** [comment]
Any info on how to use/generate using protoc-gen-gogo?

**Comment by terencechain** [comment]
@mkinney just beacon chain config, not the beacon state

**Comment by prestonvanloon** [comment]
IMO this can be a gRPC message that is a map of all properties in the beacon config.

```protobuf

...
rpc GetBeaconConfig(google.protobuf.Empty) returns (BeaconConfig);
...

message BeaconConfig {
  map<string, Any> config = 1;
}
```

This would be easier than defining the beacon config as a full message. 
I'm not sure what the use cases are here.

**Comment by mkinney** [comment]
Sorry for my ignorance. I've been doing a bit of learning about google's protobuf stuff today. I see that the go-go stuff has reflection, so, yeah, this may be much easier than I thought it'd be. (if you know what you're doing)

I think this came up in the `ethereum-api` channel:
> Maybe it would be nice to have endpoint to fetch current config params? 

and

> can you get the slots /epoch from the api somehow? otherwise  it needs to be specified for any deployment using the api, depending on network, so having an endpoint with the current epoch still seems worthwhile so you can get it programatically

**Comment by prestonvanloon** [comment]
For the config params, i'm suggesting a lazy way of returning generic map of the config params. 

For the current slot / epoch, you can get the genesis time and determine that from the current clock time.

**Comment by rauljordan** [comment]
Agree with the lazy approach instead of specifying all of the config values as a message, will follow that approach
