### ISSUE TITLE
Running container in kubernetes / openshift

### ISSUE THREAD

**Issue by xrow** [prysmaticlabs/prysm#3923]
Hi,

if I try to run the container in for example openshift I get the error message below because the container has no terminal available. I think I might be smart to not have the entrypoint pointed towards the binary. Try to use something like this as an entry point. Also it could be better to have env vars controlling the params of the binary. 

Proposal for new entry point
```
#!/bin/sh
exec $@
```

```
This container doesn't have a /bin/sh shell. Try specifying your command in a terminal with:

oc -n default exec beacon-node-5fc7dbf779-qgr62 -ti <command>
```

**Comment by prestonvanloon** [comment]
Hey xrow, our docker containers are extremely minimal. They consist of only the compiled binary for linux amd64 and the manifest that describes the docker image.

If you need shell, or any other tooling, then you may want to generate your own docker image. We think that a minimal image is more secure than an image that builds off of some external base image. 

With regards to environment variables, what are the use cases?

**Comment by xrow** [comment]
@prestonvanloon

The idea is basicly to be able to introspect a running container via web terminal. Do you think it is a security risk to have that available.

What are your security concerns in detail?

**Comment by xrow** [comment]
Also I have seen that you start 2 processes in the startup script. I don't know if that is really required. It could lead to less rubustness. It could be smarter to split it up into two containers and processes. But that is all depending a bit on how your software works in detail.

**Comment by xrow** [comment]
Just as a hint... I was thinking about something like this to also support the openshift uid security model....

```
FROM centos:latest

ENV VERSION=0.2.3
ENV HOME="/data"

COPY bin/uid_entrypoint /usr/bin/uid_entrypoint

RUN curl -L -o /usr/bin/beacon-chain https://github.com/prysmaticlabs/prysm/releases/download/v$VERSION/beacon-chain-v$VERSION-linux-amd64 && \
    curl -L -o /usr/bin/validator https://github.com/prysmaticlabs/prysm/releases/download/v$VERSION/validator-v$VERSION-linux-amd64 && \
	chmod 755 /usr/bin/beacon-chain && \
	chmod 755 /usr/bin/validator \
    chmod 755 /usr/bin/uid_entrypoint \
    mkdir /data && chmod 777 /data \
    chmod g=u /etc/passwd

VOLUME /data

WORKDIR /data

EXPOSE 4000/tcp
EXPOSE 7000/tcp

CMD /usr/bin/beacon-chain \
    --bootstrap-node= \
    --deposit-contract=0xD775140349E6A5D12524C6ccc3d6A1d4519D4029 \
	--p2p-port=4000 \
	--grpc-gateway-port=7000 \
    --interop-genesis-state="" \
	--p2p-priv-key=/tmp/id.key \
    --datadir=/data \
	--scatter

ENTRYPOINT [ "/usr/bin/uid_entrypoint" ]

USER 1001
```
#!/bin/bash

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

exec $@
```

```

**Comment by rauljordan** [comment]
Thoughts @prestonvanloon ?

**Comment by prestonvanloon** [comment]
I would probably recommend a builder pattern from a docker image since these are optimized for docker already. Take a look at how DappNode builds their docker images for beacon chain: https://github.com/eduadiez/DAppNodePackage-prysm-beacon-chain/blob/master/build/Dockerfile

```dockerfile
FROM gcr.io/prysmaticlabs/prysm/beacon-chain@sha256:113a07ab26a0e269cd0aee872f24464f163db353d658e32cc990e15fe205c856 as binary

FROM alpine

# Install dependencies
RUN apk --update add bash ca-certificates libc6-compat && \
    rm  -rf /tmp/* /var/cache/apk/*

COPY --from=binary /app/beacon-chain/image.binary /usr/local/bin/beacon-chain

ENTRYPOINT beacon-chain --datadir=/data --init-sync-no-verify $EXTRA_OPTS
```

With this, you can build upon or extend these docker images. However, we won't support anything other than the minimal docker images at this time.

**Comment by xrow** [comment]
@prestonvanloon prestonvanloon This is also a nice proposal, but will not fix the security demands of kubernetes nor openshift for whatever you ship. Plus the pattern has no support in RHEL 7 just RHEL 8. Sorry for being so picky.

https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html

REF:

```
#!/bin/bash

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

exec $@
```

**Comment by xrow** [comment]
Nevertheless. I am happy to maintain a better Kubernetes/OpenShift Version of the image.

**Comment by xrow** [comment]
Does the binary hav static bindings to the os layer or is all self contained?

**Comment by prestonvanloon** [comment]
Our docker images are essentially the go binary built for the architecture in a minimal image.

The base image we use is gcr.io/distroless/cc. See: https://github.com/GoogleContainerTools/distroless. Then we insert the built go binary. The only static bindings would be libc++, as far as I know. 

I think I understand your concern and we see an example of how to do this in the rules_docker repository readme: https://github.com/bazelbuild/rules_docker#go_image-custom-base I'll give this a try and report back here, thanks

**Comment by prestonvanloon** [comment]
@xrow I have a fix for you at #4320. Thanks!

**Comment by xrow** [comment]
Great move... I am not quite sure most people set that user id to 1001 and not 1002. I test your build sooner or later.

**Comment by prestonvanloon** [comment]
1001 is fine too, let me know if we should change it and I would happily submit a fix to do so.

**Comment by xrow** [comment]
Please do, if you would ask me like you did. I hope I can post more cloud native ideas in the future.

**Comment by prestonvanloon** [comment]
OK changed to uid 1001: https://github.com/prysmaticlabs/prysm/pull/4320/commits/f774aba452d59a05de49d27f10d13fd103fe2abf

**Comment by xrow** [comment]
Hi,

was testing the new image (version latest). Currently it is not yet fully compatible. I am currently investigating back loop errors because of permissions. Though first issue that needs fixing for debug is that the image is not compatible with the debug mode of the cloud platform. 

The command "sleep" needs to be in the path to enable container debug.

![Anmerkung 2020-01-06 171639](https://user-images.githubusercontent.com/295491/71831132-9921f580-30a8-11ea-8790-5221ae083615.png)
