### ISSUE TITLE
Local builds depend on git. exec: "git": executable file not found in $PATH

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3943]
If a Prysm binary is built without `--workspace_status_command=./scripts/workspace_status.sh` then the binary fails to start on systems that don't have git installed.

We need to revert or amend #3904 as this might cause issues for users that wish to build locally and run on machines that don't have git installed.

_Originally posted by @prestonvanloon in https://github.com/prysmaticlabs/prysm/pull/3868#issuecomment-550426870_

**Comment by prestonvanloon** [comment]
cc: @mkinney

**Comment by mkinney** [comment]
Sorry. Should not have put a fatal in there.
