### ISSUE TITLE
Finalized block index is missing blocks in finalized epoch

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3947]
When we index finalized block roots, we are assuming that the checkpoint root is the starting point for walking up the ancestry tree to build the canonical finalized chain. However, the finalized root in the checkpoint is the highest block up to or including the block at the finalized slot. This leaves the other blocks in the epoch un-indexed and therefore return false when asking `db.IsFinalizedBlock(...)`. 

The solution here is to index these epoch blocks as finalized, but rebuild the end of the index every time a new finalized checkpoint is added. 

I might also recommend that we annotate or rename `db.IsFinalizedBlock(...)` to indicate that the block is _finalized and canonical_. 

Until this is resolved, initial sync is broken, but I'll have a resolution later today / tonight.

**Comment by terencechain** [comment]
Run time is broken for initial syncing. if you need immediate relief take the following `+1` out:
https://github.com/prysmaticlabs/prysm/blob/0481eb4872be535764bf80a0e32bd157ade37ac2/beacon-chain/sync/rpc_beacon_blocks_by_range.go#L88
