### ISSUE TITLE
Allow Filtering of Blocks and Block Roots by Epochs

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3949]
This is pretty ugly:

```go
roots, err := db.BlockRoots(ctx, filters.NewFilter().SetStartSlot(helpers.StartSlot(checkpoint.Epoch)).SetEndSlot(helpers.StartSlot(checkpoint.Epoch+1)-1))
```
Instead, we should allow blocks to be filterable by `StartEpoch` and `EndEpoch` as well. Thanks @prestonvanloon for bringing this up.

**Comment by prestonvanloon** [comment]
Thanks for filing this! Just to clarify a bit on my objective. I wanted to query such that I would retrieve all block roots for blocks within the epoch identified by `checkpoint.Epoch`.
