### ISSUE TITLE
confused about epoch boundries and their respective blocks

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#3972]
hi guys,

the issue i have is from the point of view of an api user.

for some stuff it's a whole lot easier to reason in epochs rather than slots, like finalized and justified epochs, yet the api does not have a way of getting the current/justified/finalized epochs, just slots via `beacon/chainhead`. 
as i understand it, if we consider the number of slots in an epoch to be 8, epoch 0 would be slots 0-7, epoch 1 8-15 and so on. if we consider epoch 0 to be finalized, then `beacon/chainhead` seems to return end of epoch + 1 as the finalizedSlot, in the example above that would be 8, which increases confusion (for me at least). 

Why is the finalized slot not the end slot of the epoch if that is when the transition happens? Could the api docs mention anything on how to compute the epochs properly or, even better, could the api return epochs as well in chainhead to ease the  confusion?

thanks guys for all your hard work

**Comment by tzapu** [comment]
hey @prestonvanloon @terencechain maybe you could shed some light for me on the above. 
mostly looking into confirmation if epoch 0 would contain slots 0-7 and if that is the case, why does `beacon/chainhead` return as justifiedSlot/finalizedSlot the end of epoch + 1 (in case of epoch 0 it would return 8), should it not return the actual end of the epoch?
thanks

**Comment by prestonvanloon** [comment]
Hey @tzapu, sorry for the delay here!

When we finalize an epoch, the state's [finalized checkpoint](https://github.com/prysmaticlabs/prysm/blob/f43a7c67f222ac1325fc4a205cff8cb70faf1f25/proto/beacon/p2p/v1/types.proto#L45)  is updated. 

https://github.com/prysmaticlabs/prysm/blob/f43a7c67f222ac1325fc4a205cff8cb70faf1f25/proto/eth/v1alpha1/attestation.proto#L48-L56

If we finalized epoch 10, the checkpoint would have epoch=10 and a block root of the highest slot block in the finalized chain, up to slot 80 (start slot of epoch 10). If there were no block produced at slot 80, the root would point to 79 unless that were a skip slot, then it would point to 78 and so on.

Looking at the GetChainHead implementation:

https://github.com/prysmaticlabs/prysm/blob/199ddc6cdb2f8655743845ab33abdcc178d790ae/beacon-chain/rpc/beacon/blocks.go#L136-L151

We are setting "finalizedSlot" field to naively be epoch*SLOTS_PER_EPOCH which is not always correct based on the information I just described.

Here are a few suggestions:
- Look up the block root in the database, set the finalized / justified slots to the slot that the block actually represents
- Also return the epoch number for head / finalized / justified, etc

Here's my proposal response for GetChainHead:
```protobuf
message ChainHead {
    bytes head_block_root = 1 [(gogoproto.moretags) = "ssz-size:\"32\""];
    uint64 head_block_slot = 2;
    uint64 head_block_epoch = 3;

    uint64 finalized_slot = 4; // Not always equal to finalized_epoch * SLOTS_PER_EPOCH
    uint64 finalized_epoch = 5;
    bytes finalized_block_root = 6 [(gogoproto.moretags) = "ssz-size:\"32\""];

    uint64 justified_slot = 7;
    uint64 justified_epoch = 8;
    bytes justified_block_root = 9 [(gogoproto.moretags) = "ssz-size:\"32\""];

    uint64 previous_justified_slot = 10;
    uint64 previous_justified_epoch = 11;
    bytes previous_justified_block_root = 12 [(gogoproto.moretags) = "ssz-size:\"32\""];
}
```

**Comment by terencechain** [comment]
Suggesting to use `block_slot` instead of `slot:

```proto
message ChainHead {
    bytes head_block_root = 1 [(gogoproto.moretags) = "ssz-size:\"32\""];
    uint64 head_block_slot = 2;
    uint64 head_block_epoch = 3;

    uint64 finalized_block_slot = 4; // Not always equal to finalized_epoch * SLOTS_PER_EPOCH
    uint64 finalized_epoch = 5;
    bytes finalized_block_root = 6 [(gogoproto.moretags) = "ssz-size:\"32\""];

    uint64 justified_block_slot = 7;
    uint64 justified_epoch = 8;
    bytes justified_block_root = 9 [(gogoproto.moretags) = "ssz-size:\"32\""];

    uint64 previous_justified_block_slot = 10;
    uint64 previous_justified_epoch = 11;
    bytes previous_justified_block_root = 12 [(gogoproto.moretags) = "ssz-size:\"32\""];
}
```

**Comment by tzapu** [comment]
hey guys, thanks for this, the above reponse changes seem great. at first look they sort out all the issues without having to do any other lookups
cheers
