### ISSUE TITLE
New Deposits Are Unable to Be Included in Deposit Contract

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3979]
~As part of v0.9.0, we must compute the new deposit trie root with the deposit or ethereum 1 transaction will fail.~

~There are a few concerns here:~
- ~validator accounts create needs access to a synced node (eth1?) to determine latest deposit trie root~
- ~if the deposit is frontrun and the deposit trie root changes, then this transaction will fail. This is a UX concern because users will need to regenerate the deposit data, but do not need to create a new account.~
- ~if we know the transaction will fail, by reading the current deposit root in the smart contract, do not prompt the user to spend gas on such a transaction~
- ~if the transaction does fail, we should communicate this better to the user. Currently, it appears to have worked when the transaction was actually reverted.~

Still investigating...

**Comment by prestonvanloon** [comment]
This seems to be incorrect. @nisdas can you comment please?

**Comment by nisdas** [comment]
Just to clarify this doesn't have anything to do with the deposit trie root. Currently we are not able to send any new deposits using our deposit tool. We currently have 256 deposits successfully processed by the contract. However all new deposits are failing to be included.

**Comment by prestonvanloon** [comment]
Looks like it was a testnet site issue. https://alpha.prylabs.network working OK.
