### ISSUE TITLE
getting error when calling activesetchanges with an epoch param

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#3982]
tested here
https://api.prylabs.net/#/BeaconChain/GetValidatorActiveSetChanges
with an older epoch as the param

`curl -X GET "https://api.prylabs.net/eth/v1alpha1/validators/activesetchanges?epoch=85" -H  "accept: application/json"`

**Comment by rauljordan** [comment]
Hey @tzapu this is related to #3974, as we do not have good error codes. The issue is the nodes serving API traffic are not archive enabled, so it should be returning a proper error instead.

**Comment by tzapu** [comment]
cool, good to know, guess i need to setup my own archive node then.
