### ISSUE TITLE
Win 10 Docker: prylabs.net/participate commands do not work for Docker on Windows

### ISSUE THREAD

**Issue by Mkkoll** [prysmaticlabs/prysm#3997]
Windows 10 - Suggested docker commands to generate validator keys and start the beacon chain and validator do not work . Default path of usr/local/prysm/ in the suggested commands does not match the directory the user is asked to create in the Windows version of the instructions.

**Generating validator key**
Suggested command
```
docker run -it -v /usr/local/prysm/validator:/data \
   gcr.io/prysmaticlabs/prysm/validator:latest \
   accounts create --keystore-path=/data --password=changeme
```
Command I used to get running
`docker run -it -v /tmp/prysm-data:/data gcr.io/prysmaticlabs/prysm/validator:latest accounts create --keystore-path=/data --password=changeme`

**Starting validator**
Suggested command
```
docker run -it -v /usr/local/prysm/validator:/data --network="host" \
  gcr.io/prysmaticlabs/prysm/validator:latest \
  --beacon-rpc-provider=127.0.0.1:4000 \
  --keystore-path=/data \
  --password=changeme

```
Command i used to get running
`docker run -it -v /tmp/prysm-data:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keystore-path=/data --password=changeme
`

**Comment by terencechain** [comment]
@har00ga Mind updating the windows instructions with the above? thanks!

**Comment by har00ga** [comment]
No problem, will make this adjustment. :slightly_smiling_face:

**Comment by prestonvanloon** [comment]
Had to revert https://github.com/prysmaticlabs/prysm-testnet-site/pull/78, see comments in that PR

**Comment by har00ga** [comment]
Partial solution, now documented in Gitbook: https://prysmaticlabs.gitbook.io/prysm/activating-a-validator - prylabs.net site still needs to be adjusted to feature Windows-specific (and possibly Bazel) commands however

**Comment by rauljordan** [comment]
This can be closed, refer to https://prysmaticlabs.gitbook.io/prysm/activating-a-validator
