### ISSUE TITLE
beaconchain can't process deposit logs

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#4003]
Beaconchain spills out lots of these (numbers match every time, they don't change):
```
[2019-11-14 07:14:02] ERROR powchain: could not process log: Could not process deposit log: Could not get correct merkle index: despite requesting missing logs, latest index observed is not accurate. Wanted 314 but got 313
```

**Comment by rauljordan** [comment]
Resolved by @nisdas's bug fixes in our powchain service

**Comment by privatejava** [comment]
beacon_mainnet  | time="2021-02-09 15:54:10" level=error msg="Unable to process past logs Could not process deposit log: could not get correct merkle index: latest index observed is not accurate, wanted 85359, but received  85358" prefix=powchain

**Comment by Quilamir** [comment]
Jul 03 15:28:34 ip-10-0-255-202 prysm.sh[630]: time="2022-07-03 15:28:34" level=error msg="Could not process deposit log: received incorrect merkle index: wanted 409938 but got 410636" prefix=powchain

any idea how to get this resolved, been going on for quite a while now

**Comment by 3cl1ps** [comment]
same error here :
juil. 31 23:37:36 thomas-B550M beacon-chain[2825]: time="2022-07-31 23:37:36" level=info msg="Synced new block" block=0xc6a19f6c... epoch=136674 finalizedEpoch=136672 finalizedRoot=0x2044ce0a... prefix=blockchain slot=4373586 
juil. 31 23:37:36 thomas-B550M beacon-chain[2825]: time="2022-07-31 23:37:36" level=info msg="Finished applying state transition" attestations=69 prefix=blockchain slot=4373586 syncBitsCount=504 
juil. 31 23:37:43 thomas-B550M beacon-chain[2825]: time="2022-07-31 23:37:43" level=info msg="Falling back to historical headers and logs sync. Current difference is 48444" prefix=powchain 
juil. 31 23:37:43 thomas-B550M beacon-chain[2825]: time="2022-07-31 23:37:43" level=error msg="Could not process deposit log: received incorrect merkle index: wanted 416001 but got 417304" prefix=powchain

**Comment by nisdas** [comment]
Which execution client are you guys using ? @Quilamir @3cl1ps

**Comment by 3cl1ps** [comment]
/data4/prysm/beacon-chain --datadir=/data4/prysm/data --http-web3provider=http://127.0.0.1:8546,http://127.0.0.1:8548 --accept-terms-of-use --p2p-tcp-port=12000 --p2p-udp-port=1200
8546 is erigon, 8548 is nethermind.

prysm v2.1.3, erigon is using the latest commit (devel branch) : d866b119236c9b93ca071abc0e45526cf82b58d7

Linux thomas-B550M 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I restarted the service to increase log level, i don't have this error anymore.

**Comment by nisdas** [comment]
@3cl1ps Ok we are planning to remove the use of fallback nodes with the merge. Due to the interplay between consensus and execution clients, a consensus client (prysm) should only be connected to one execution client(nethermind, erigon). There have been reported issues with deposit logs via erigon, you might have better luck asking the erigon team on how to resolve it. Alternatively you can use only nethermind and see if that helps.

**Comment by Quilamir** [comment]
@nisdas i am using the latest erigon client version 2022.08.2-alpha-35c4faa1
