### ISSUE TITLE
Beacon node error: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by danilind** [prysmaticlabs/prysm#4013]
I got this error when trying to sync the beacon node on windows. Please see the attached screenshot. After i got the error i started the client over again, and the sync continued where it left of. I'm now at block 17000 without getting the same error any more times, it only happened once.

![unknown](https://user-images.githubusercontent.com/9575748/68993322-f81c7880-0876-11ea-834a-19b51ea126d0.png)

**Comment by prestonvanloon** [comment]
This issue is more apparent now that some nodes are disconnect peers when too many connections are open.
