### ISSUE TITLE
Restarting Beacon Node + Validator After a While Leads to UNKNOWN_STATUS in Validator

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4021]
This is a bug raised by some of our testnet users in our discord chat. Unfortunately, when turning off the beacon node + validator and starting them up again after a few hours, users reported seeing `UNKNOWN_STATUS` in their validator that is currently active in the protocol. The suspicion is there is some data stored in-memory regarding a validator's status that is lost upon a restart.

Have not yet attempted to reproduce, and it is still unknown if the issue manifests after a short restart (users confirm it happens after a long time between turning off the processes and turning them on again).

**Comment by prestonvanloon** [comment]
Information:

Reported log from user
```
[2019-11-17 20:09:31]  INFO validator: Waiting for validator to be activated in the beacon chain
[2019-11-17 20:09:31]  INFO validator: Waiting to be activated depositInclusionSlot=0 positionInActivationQueue=0 pubKey=0xa66504a1c3a6 status=UNKNOWN_STATUS
```

At the time of reporting, they were not ejected
```json
    {
      "publicKey": "pmUEocOmShlMd+kvG/etp1le4NrOi8LXRoqTcNlwaR46k/PtOOw1MfuXQZUPMw+i",
      "withdrawalCredentials": "ABH3UpQEMXqkrHE7B0q5LyunED2PBoVDet9uh7aVe10=",
      "effectiveBalance": "3200000000",
      "slashed": false,
      "activationEligibilityEpoch": "4779",
      "activationEpoch": "4784",
      "exitEpoch": "18446744073709551615",
      "withdrawableEpoch": "18446744073709551615"
    },
```

And they had a positive balance > 3.2 ETH.

```json
{
  "epoch": "5619",
  "balances": [
    {
      "publicKey": "pmUEocOmShlMd+kvG/etp1le4NrOi8LXRoqTcNlwaR46k/PtOOw1MfuXQZUPMw+i",
      "index": "352",
      "balance": "3303092168"
    }
  ],
  "nextPageToken": "1",
  "totalSize": 1
}
```

**Comment by prestonvanloon** [comment]
Confirmed that assignments does not read from any cached or in memory values. Determining assignments reads from the head state, so this could be a symptom of requesting assignments from a beacon chain node that is not in sync.

**Comment by prestonvanloon** [comment]
User confirms that the beacon chain node was in sync at the time. 

@terencechain confirms we block gRPC behavior from head state, so fetching assignments from out of sync node should have returned an obvious error if that were the case. https://github.com/prysmaticlabs/prysm/pull/3968

**Comment by prestonvanloon** [comment]
One possible problem area is when the ETH1 deposit fetcher fails to correctly return the deposit block number, an empty response is returned. This looks like the response the users are receiving.

https://github.com/prysmaticlabs/prysm/blob/53c4a26184909a2022e4b200dfb82a81d616a9fc/beacon-chain/rpc/validator/status.go#L83-L88

**Comment by prestonvanloon** [comment]
The root cause is somewhere in the deposit cache being cleared, but the immediate resolution is to check the head state for the validator existence before checking the ETH1 chain.

If a problem in the deposit cache remains, the consequences are that the ETh1DepositBlockNumber is zero when the validator is activated. This clearly isn't the intended behavior, but it is more tolerable than an empty response when a validator is active in the state.
