### ISSUE TITLE
Implement GetAttestingIndices RPC Endpoint

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4022]
A useful endpoint would be to allow anyone to retrieve the list of validator indices who participated in an attestation by providing the attestation bitfield and some other minimal info.  Will be useful for block explorers.

**Comment by prestonvanloon** [comment]
We already have a path for this:
- Have some attestation
- Call ListBeaconCommittees for the appropriate epoch
- Use the aggregation bitfield to determine the indices in the committee that attested to this attestation

**Comment by terencechain** [comment]
Instead of using aggregation_bitfield to determine the indices in the committee, use committee_index and slot. Easier

**Comment by prestonvanloon** [comment]
Some discussion offline that the proto response for get committees could be improved: https://discordapp.com/channels/476244492043812875/603588441741066241/646885914370637844

**Comment by prestonvanloon** [comment]
Closing and opening https://github.com/prysmaticlabs/ethereumapis/issues/48 for data structure improvements.
