### ISSUE TITLE
Enable build export as GOPATH-style structure.

### ISSUE THREAD

**Issue by gnattishness** [prysmaticlabs/prysm#4024]
As part of [beacon-fuzz](https://github.com/sigp/beacon-fuzz), we want to use a custom `go build` ( [`go-fuzz-build`](https://github.com/dvyukov/go-fuzz)) to build fuzzing harness static libraries with prysm (or parts of it) as a dependency.

For this, prysm (and its dependencies) should be accessible in a GOPATH-style directory structure.

Could also be useful for GOPATH-based editor/IDE integrations.

**Comment by gnattishness** [comment]
`go-fuzz` now has preliminary support for go modules, so this could be used in the future (if prysm had its dependencies defined in `go.mod`, `go.sum` files), but current implementation makes use of GOPATH structure, so we'll make use of that for now.

**Comment by rauljordan** [comment]
@prestonvanloon integrated go-fuzz with our latest version of Go in Prysm, we can close this
