### ISSUE TITLE
Use a port other than 8080 for Prometheus

### ISSUE THREAD

**Issue by blockchainunchained** [prysmaticlabs/prysm#4045]
It's extremely common for port 8080 to be in use, why have it as the default?

There is no need for Prometheus to be running on port 8080 specifically and it could quite easily run on a different port. This would make it easier to deploy the test network for newcomers.

**Comment by prestonvanloon** [comment]
Please use `--monitoring-port=12345` to set prometheus to another port. 

We set it to 8080 as default because it is a very common port and frequently used in development / local testing.
