### ISSUE TITLE
Implement Graffiti Flag to Add Custom Graffiti to Beacon Blocks

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4057]
We can add a graffiti flag to the validator binary for users to add useful/fun metadata into the blocks they produce. For our purposes, it would be useful to include the k8s podname running the validator container which produced the block (thanks @prestonvanloon for the suggestion).
```
bazel run //validator -- --graffiti=$(POD_NAME)
```

**Comment by prestonvanloon** [comment]
Adding the block graffiti in the validator client can go between the response from the beacon chain and signing the block.

https://github.com/prysmaticlabs/prysm/blob/89f4053c33444d1949db6d4f0af25dc95170a0f6/validator/client/validator_propose.go#L44-L54

The graffiti is at most 32 bytes. 
Users may want to set this to a fun value or to a functional one (k8s pod name, process metadata, etc).

**Comment by metanull-operator** [comment]
Can I get assigned this issue?

**Comment by prestonvanloon** [comment]
@metanull-operator are you still working on this?

**Comment by metanull-operator** [comment]
@prestonvanloon I am for now, unless there is an urgency to this. My first approach was incorrect, and I believe I understand the correct approach. I plan to make one more attempt this weekend.

**Comment by prestonvanloon** [comment]
No urgency, just a friendly ping. Thanks!

**Comment by metanull-operator** [comment]
I have this working now, but will be reviewing my code and writing tests prior to submitting a PR.

**Comment by metanull-operator** [comment]
A minor update to base code was made today which moves the call to ToBytes32() to lower down. This should protect against malicious RPC calls to ProposeBlock() that might try to pass too many bytes for graffiti.

Base implementation is now complete, AFAIC. Presently working out how to write tests that truly test the graffiti feature.

**Comment by metanull-operator** [comment]
Example of block containing graffiti using the latest code: https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=166533

**Comment by prestonvanloon** [comment]
Awesome!

**Comment by metanull-operator** [comment]
beaconcha.in now supports displaying UTF-8 graffiti.
Same block as previous link: https://beaconcha.in/block/166533

**Comment by prestonvanloon** [comment]
Great! Can we review a PR? Would love to start using this feature!

**Comment by metanull-operator** [comment]
Is there any action I need to take to close this issue?

**Comment by nisdas** [comment]
Hey nope, I think this can be closed :)
