### ISSUE TITLE
De-duplicate EthereumAPIs in Prysm

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4064]
In the Prysm repository, we maintain a copy of the upstream github.com/prysmaticlabs/ethereumapis protos with some gogoproto annotations for ssz.

Maintaining two sets of the same data can lead to issues.

See:
- https://github.com/prysmaticlabs/ethereumapis/pull/43
- https://github.com/prysmaticlabs/ethereumapis/pull/45
- https://github.com/prysmaticlabs/ethereumapis/pull/46

My suggestion is that we follow the patch pattern as provided by rules_go. 
We can define some patch file under third_party directory which would apply any modifications required for EthereumAPIs. 
This reduces the risk of these definitions from drifting apart.

**Comment by rauljordan** [comment]
Resolved by #4112
