### ISSUE TITLE
Error when retrieving epoch participation

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4076]
Sometime we get occasional errors when querying the `GetValidatorParticipation` API endpoint:

```
Error retrieving epoch participation statistics: rpc error: code = Internal desc = Could not compute participation: could not retrieve head attestations: could not get block root for epoch 8870: slot 70960 out of bounds
```

After waiting for a few minutes the call returns again a proper result.

**Comment by prestonvanloon** [comment]
At the time of the request, was this a previous, current, or future epoch?

**Comment by ppratscher** [comment]
We get this error vor historic and current epochs. For example:
```
Error retrieving validator assignment response: rpc error: code = NotFound desc = Could not retrieve data for epoch 343, perhaps --archive in the running beacon node is disabled
```

**Comment by ppratscher** [comment]
Most likely it was for the current epoch, we execute the call for the current, previous and last finalized epoch every 10s.

**Comment by prestonvanloon** [comment]
Yeah, I think that is likely what happened. We probably have an out of range error when calculating participation for a epoch that is still in progress.

Assigning to @terencechain because I think they worked on this. Terence, please triage as necessary.
