### ISSUE TITLE
Instructions for Local Testnet Start Command Do Not Work

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#4078]
Attempted to create a local testnet using instructions in README.md.

`bazel run //beacon-chain -- \
--no-genesis-delay \
--bootstrap-node= \
--deposit-contract 0xD775140349E6A5D12524C6ccc3d6A1d4519D4029 \
--clear-db \
--interop-num-validators 64 \
--interop-eth1data-votes`

This command results in an error:

`Unable to retrieve data from deposit contract could not retrieve deposit root: abi: unmarshalling empty output`

--no-genesis-delay is deprecated, and @prestonvanloon commented that he hadn't run the interop flags in a while.

**Comment by prestonvanloon** [comment]
I think this is what is happening: 0xD775140349E6A5D12524C6ccc3d6A1d4519D4029 is a dummy contract that is actually deployed. It is the old contract ABI. 

Here's a new one, can you try it out 0xDffEDfF9bD959DFD95e1b2BcdDA954c851f729EA @metanull-operator?

**Comment by metanull-operator** [comment]
After replacing the contract address, the command no longer gives any errors. The following is the last log entry from the beacon-chain at this time:

`INFO powchain: Connected to eth1 proof-of-work chain endpoint=wss://goerli.prylabs.net/websocket`

I have never run a local testnet before, so I'm not sure what it is supposed to look like. So far my validators are waiting to be processed into state, and the beacon chain is not doing anything after the last log entry above. I will give it a while to see whether anything changes.

**Comment by metanull-operator** [comment]
The testnet did not appear to start correctly, but it seems like a separate issue from this one. I can log something separately, if I can confirm that it isn't user error.

For the record, the errors I am receiving are about not being able to connect to goerli.prylabs.net (failure in name resolution), and "Not connected to ETH1. Cannot determine validator ETH1 deposit block number". These look like connectivity issues on my end more than anything else.

**Comment by prestonvanloon** [comment]
@metanull-operator is there any thing else I can help with to resolve this issue?

**Comment by metanull-operator** [comment]
Does the README need to be updated? Is that part of this issue?

**Comment by prestonvanloon** [comment]
Ah yes good point. We need to update the readme with the new address.

**Comment by rauljordan** [comment]
We'll update the readme to instead use `--deposit-contract $(curl https://prylabs.net/contract)` as the flag, as that will always work
