### ISSUE TITLE
unknown service error for "/eth/v1alpha1/validator/block"  api end point

### ISSUE THREAD

**Issue by mtbitcoin** [prysmaticlabs/prysm#4097]
"/eth/v1alpha1/validator/block" 

Getting an {"error":"unknown service ethereum.eth.v1alpha1.BeaconNodeValidator","code":12,"message":"unknown service ethereum.eth.v1alpha1.BeaconNodeValidator","details":[]} when attempting to call the api end point

**Comment by rauljordan** [comment]
Hey @mtbitcoin this is a discrepancy between Prysm's internal API usage vs. the public API on api.prylabs.network. This will be resolved by a PR for #4105.

**Comment by rauljordan** [comment]
Closing in favor of #4105
