### ISSUE TITLE
fetching of block at slot 0

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#4103]
There seems to be some inconsistency about how block at slot 0 is returned.
if you call `beacon/blocks?slot=0` you don't get any results
if you call `beacon/blocks?epoch=0` or `beacon/blocks?root=YL1nu10moi9VhNaKmf43YuqnQ8RBlmE1MCdjMFdTBkg` you do get a block back that looks like this
```
{
  "blockContainers": [
    {
      "block": {
        "slot": "0",
        "parentRoot": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        "stateRoot": "bqdbSQ8wcWphQTj84rAks9xaMW0QvGTwqd7C7JkPhRI=",
        "body": {
          "randaoReveal": "",
          "graffiti": "",
          "proposerSlashings": [],
          "attesterSlashings": [],
          "attestations": [],
          "deposits": [],
          "voluntaryExits": []
        },
        "signature": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      },
      "blockRoot": "YL1nu10moi9VhNaKmf43YuqnQ8RBlmE1MCdjMFdTBkg="
    }
  ],
  "nextPageToken": "",
  "totalSize": 1
}
```

i assume this is the genesis block but it's inconsistent returning it with some filters and not with others. 

thanks

**Comment by rauljordan** [comment]
Closing when https://github.com/prysmaticlabs/ethereumapis/issues/49 is resolved
