### ISSUE TITLE
Blockchain Tests Fail With Race Detection 

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#412]
Blockchain tests failed with race detection on in Travis and we have turned race detection off in blockchain tests package. Opened this issue to investigate why it was failing with race on and how to resolve it.

See: https://travis-ci.org/prysmaticlabs/prysm/jobs/416935859

**Comment by rauljordan** [comment]
I wonder if the race tests were failing because of how we were checking for logs. @nisdas implemented a helper func called wait for log that actually blocks until a log is received and can be placed at the end of tests. We can revisit this perhaps next week.

**Comment by rawfalafel** [comment]
Closing this one since no flaky tests were found while building #636
