### ISSUE TITLE
ERROR sync: Failed to handle p2p pubsub 

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#4122]
did not see this filed yet

[2019-11-26 23:19:13] ERROR sync: Failed to handle p2p pubsub error=attestation aggregation signature did not verify 0x857279c9d260
could not verify indexed attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).verifyAttestation
	beacon-chain/blockchain/forkchoice/process_attestation.go:170
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).OnAttestation
	beacon-chain/blockchain/forkchoice/process_attestation.go:90
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:30
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
	beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
	beacon-chain/sync/subscriber.go:161
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357
could not process attestation from fork choice service
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:31
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
	beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
	beacon-chain/sync/subscriber.go:161
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1357 topic=/eth2/beacon_attestation/ssz

**Comment by nikosv** [comment]
same error to me also

**Comment by torfbolt** [comment]
Also seeing the same here.

**Comment by torfbolt** [comment]
Still seeing this error quite regularly. When it occurs both clients continue to work, but the validator shows negative balance update, so it looks like no correct attestation is happening.

**Comment by torfbolt** [comment]
Actually I just noticed that the error title is the same, but the start of the trace looks a bit different for me now:

```
[2019-12-06 22:37:07] ERROR sync: Failed to handle p2p pubsub error=signature did not verify
github.com/prysmaticlabs/prysm/beacon-chain/core/blocks.init
        beacon-chain/core/blocks/block_operations.go:37
runtime.doInit
        GOROOT/src/runtime/proc.go:5222
runtime.doInit
        GOROOT/src/runtime/proc.go:5217
runtime.doInit
        GOROOT/src/runtime/proc.go:5217
runtime.doInit
        GOROOT/src/runtime/proc.go:5217
runtime.doInit
        GOROOT/src/runtime/proc.go:5217
runtime.doInit
        GOROOT/src/runtime/proc.go:5217
runtime.main
        GOROOT/src/runtime/proc.go:190
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1357
could not verify indexed attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).verifyAttestation
        beacon-chain/blockchain/forkchoice/process_attestation.go:175
github.com/prysmaticlabs/prysm/beacon-chain/blockchain/forkchoice.(*Store).OnAttestation
        beacon-chain/blockchain/forkchoice/process_attestation.go:95
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:32
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:161
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1357
could not process attestation from fork choice service
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:33
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:161
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1357 topic=/eth2/beacon_attestation/ssz

```

**Comment by rauljordan** [comment]
This happens when typically attestations come from some forked chain that does not verify based on the "canonical" chain validator committees. It is a normal log that occurs in times of high instability. Will reopen if it becomes a big problem again.
