### ISSUE TITLE
docs for mitigating validator status=UNKNOWN_STATUS

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#4123]
docs should ask user to double check that their deposit has made it into a beacon block

**Comment by rauljordan** [comment]
CC @har00ga maybe we can have more docs about validator activation statuses and what they mean as well as mitigating some of these issues? What do you think

**Comment by har00ga** [comment]
For sure, would definitely be useful. :slightly_smiling_face: Happy to discuss what should be included.

**Comment by rauljordan** [comment]
Assigning to @har00ga, action items for this are:
- Remind users to copy their public key somewhere when they run their validator client
- Point users to `https://beacon.etherscan.io` where they can paste in their public key and see the eth1 deposit information for their validator
- Let users know they can also see their estimated time to activation by looking up their public key on `https://beaconcha.in`

We can add this somewhere in our documentation for our docusaurus portal under a section called `Checking Your Validator's Activation`

**Comment by har00ga** [comment]
Roger that, will get on this over the next couple days. :slightly_smiling_face:

**Comment by rauljordan** [comment]
Closing in favor of #4734
