### ISSUE TITLE
--prune-finalized-state does not work as intended

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4126]
We are seeing about 50% of states retained. Specifically around 55k out of 110k.

The expected implementation should have retained all of the states at finalize checkpoints.

Two issues to solve here

- [ ] pruning finalized state doesnt work as intended
- [ ] pruning finalized state should remove all states older than the finalized one, except for archival nodes (to be confirmed why)

**Comment by terencechain** [comment]
#4139 should address the 2
