### ISSUE TITLE
If Node is a Validator, Exit if Web3 Connection Cannot be Established

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#413]
Hi all,

Currently, the beacon node acting as a validator does not exit if a connection to a web3 PoW node cannot be established. This is a critical component of all beacon validator functionality, and we should issue a Fatalf if the connection cannot occur. Otherwise, users will run into panic conditions. This Fatal tlog should occur if we have some sort of `--validator` flag enabled.

### In the Case the Beacon Node is Not Acting as a Validator

We will have an option for users to run a beacon node without being a validator for observation purposes. In this case, we should not throw a Fatalf if a web3 connection is not established.

**Comment by terenc3t** [comment]
Not all the users that launch beacon node is validator. I think's it's better to specify a validator flag and. If it's `on` and there's no web3 connection, beacon node issues Fatalf

**Comment by terenc3t** [comment]
I'll take on this tmw
