### ISSUE TITLE
Prevent Fetching of RPC-APIs Data if Not Synced

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4132]
All of our RPC endpoints should return an error if the node is performing chain sync, otherwise, the returned data may be inaccurate or wrong to users and people building on our API such as block explorers. We should return `status.Error(codes.Unavailable, "Node is currently syncing to head")` if the node is syncing. 

We currently do this for a few critical endpoints such as retrieving assignments [here](https://github.com/prysmaticlabs/prysm/blob/26da7c41143bd81d6af43089876dd9b683ff7245/beacon-chain/rpc/validator/assignments.go#L22) using an interface provided to the RPC servers called `SyncChecker`. We should extend this to all endpoints, ideally via some rule that applies to all so there won't be a need to copy paste the conditional everywhere.

**Comment by prestonvanloon** [comment]
On thing to consider is to use a gRPC interceptor for services where this matters.

I think the following services should require the interceptor:
- eth.v1alpha1.BeaconChain
- eth.v1alpha.Validator

These services may not need it:
- eth.v1alpha1.Node


Helpful guide: https://medium.com/@shijuvar/writing-grpc-interceptors-in-go-bf3e7671fe48

**Comment by prestonvanloon** [comment]
Removing this as testnet target. It's nice to have but not a high priority for release.

**Comment by rauljordan** [comment]
After further discussions with operators of block explorers, this feature is not necessary given we already expose the sync status endpoint from our node service. It does not pose much risk.
