### ISSUE TITLE
Fork choice filter viable branches

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4137]
We have been seeing head state reverts to older finalized epochs. This is due to discrepancy in fork choice branch filter. Since the validators use the state at the head to cast votes, but fork choice uses latest check points to advance. There's an edge case when the two go out of band.

The solution for is under research and can be tracked: https://github.com/ethereum/eth2.0-specs/pull/1495

**Comment by prestonvanloon** [comment]
Research topic has merged. https://github.com/ethereum/eth2.0-specs/pull/1495

**Comment by terencechain** [comment]
Waiting for official v0.9.3 release: https://github.com/ethereum/eth2.0-specs/pull/1507

Here's a few more fixes we should take in as well:
https://github.com/ethereum/eth2.0-specs/pull/1508
https://github.com/ethereum/eth2.0-specs/pull/1509
https://github.com/ethereum/eth2.0-specs/pull/1510

**Comment by terencechain** [comment]
Addressed in #4272
