### ISSUE TITLE
Attestation assignments not in line with committees

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#4140]
The 'new assignments/submittals' for attestation do not not always follow the committees.
Example case in screen prints.

Actual assignments according to validator log. Slots:
120443
120448
120461

Scheduled assignments according to Epoch committees:
120451 (epoch 15055 = 120447-120454)
120456 (epoch 15056 = 120454-120461)

BTW: slot 120454 has committees listed in both epochs=> related issue?

source of committee data (in screen prints): 
curl -s -X GET "http://localhost:4001/eth/v1alpha1/beacon/committees" -H "accept: application/json"

I get an assignment for slot 120448 for which I am (index 636) not part of the committee (according to epoch 15055). However for slot 120451 where I'm in the committee, my validator does not issue an attestation (because one attestation per epoch?). Then it has a new assignment for slot 120461 but ignores slot 120456 for which Im in the committee (according to epoch 15056). 

This looks weird as I thought slot assignments should follow the committees as determined by epoch. Most of the time it does, but not always.
Also strange is that slot 120454 appears in two subsequents epochs according to the api(localhost). 

The submitted attestations do match the committee index for each epoch (15055:1 & 15056:3) but that may be a coincidence.

validator/beacon version in example:
"version": "Git commit: 4dbf68b50c4611b8a6f930271f3d2e4db0e33612. Built at: 2019-11-27 23:53:38+00:00" (using Docker)

<img width="1130" alt="Screenshot 2019-11-28 at 10 59 19" src="https://user-images.githubusercontent.com/28559038/69802848-cababd80-11da-11ea-99ab-cb61fa75e63c.png">

Epoch committee info for 15056:
<img width="1207" alt="Screenshot 2019-11-28 at 11 04 58" src="https://user-images.githubusercontent.com/28559038/69802865-d3ab8f00-11da-11ea-8736-cdb94087e5d7.png">

Oh, and maybe an improvement would be to add a 'committeeIndex' (0,1,2,3,...) to the api results of v1alpha1/beacon/committees .

**Comment by handelaar2** [comment]
As there is no response, it must be me who misunderstands. In the mean time we are many builds later. let's wait for interop.

**Comment by nisdas** [comment]
hey @handelaar2 I am reopening this as I think it merits discussion. @terencechain what do you think ? The behaviour does not seem in line with the spec, it would explain why we have only 90% participation rate, instead of close to 100%

**Comment by terencechain** [comment]
I believe the log is correct but the assignment fetching via may not be correct. I suspect archival may have something to do with it

**Comment by terencechain** [comment]
cc @rauljordan for this

**Comment by handelaar2** [comment]
Another case of just now (it happens rarely, maybe 1in6 epochs).
There is a mismatch between epochs and the slots it contains. Epoch 21725 has started but the sequence of slots show in the committee list of 21724

Beacon
docker run -it -v $HOME/prysm-data:/data -p 4000:4000 -p 4001:4001  gcr.io/prysmaticlabs/prysm/beacon-chain:latest   --datadir=/data    --init-sync-no-verify --grpc-gateway-port 4001 --verbosity info --archive
(last time's example was without archive flag)

<img width="1285" alt="Screenshot 2019-12-05 at 20 49 47" src="https://user-images.githubusercontent.com/28559038/70269524-de4dc180-17a2-11ea-9ca0-049c47575384.png">

**Comment by handelaar2** [comment]
When I now retrieve the same epoch(21724) committee, it shows different slots in line with the actual attestations. It therefore looks that v1alpha1/beacon/committee initially gives wrong results. So if the latest (below) committee list is correct, the validator has sent the correct attestations and it is just the api being wrong at times. This would also conclude that the "low" participation rate cannot be explained with this error.

curl -s -X GET "http://localhost:4001/eth/v1alpha1/beacon/committees?epoch=**21724**" -H "accept: application/json"
<img width="1296" alt="Screenshot 2019-12-06 at 09 49 25" src="https://user-images.githubusercontent.com/28559038/70309806-99f80b00-180e-11ea-9caa-b5a2908d7022.png">

**Comment by rauljordan** [comment]
This is no longer seen in our current testnet given latest caching fixes along with deduplication of various core lines of code. Additionally, we have fixed the proposer selection bug which was leading to certain committee issues. If seen again, we can revisit.
