### ISSUE TITLE
services.proto refers to files under  non-existing dir'eth/v1alpha1/'? 

### ISSUE THREAD

**Issue by lucianyao** [prysmaticlabs/prysm#4161]
at [f55a380ad]:
in proto/beacon/rpc/v1/services.proto, there are:

```
import "eth/v1alpha1/beacon_block.proto";
import "eth/v1alpha1/attestation.proto";
```

but while the "eth/v1alpha1" was removed at the merge commit: 
[Apply Patch Rules to Use EthereumAPIs Generated Protos in Prysm](https://github.com/prysmaticlabs/prysm/commit/0326be86b5781b8e9d40d8f003d28a895e71203f)

could the paths be forgotten to update when refactoring?

**Comment by nisdas** [comment]
Thanks for opening this, #4163 should resolve this @lucianyao
