### ISSUE TITLE
gateway.go imports v1alpha1_gateway in "ethereumapis" while the gateway is still at "prysm"

### ISSUE THREAD

**Issue by lucianyao** [prysmaticlabs/prysm#4162]
[f55a380], in beacon-chain/gateway/gateway.go:
```
ethpb "github.com/prysmaticlabs/ethereumapis/eth/v1alpha1_gateway"
```
but v1alpha1_gateway is still at "prysm" instead of "ethereumapis"

the import path was updated at [0326be8].

**Comment by prestonvanloon** [comment]
I'm not seeing this. The path was changed in #4112 to the correct value.
