### ISSUE TITLE
Ensure handshakes for inbound p2p connections

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4180]
> The current code returns immediately if there is no inbound connection; this change just allows control to flow past the handshake piece.

> As to why the code isn't doing a handshake for inbound connections: no idea, but if I had to guess it would be that the outbound peer always initiates the handshake so the inbound doesn't need to do so as well.

_Originally posted by @mcdee in https://github.com/prysmaticlabs/prysm/pull/4173_

This looks like an existing issue discoverd in @mcdee's PR. Filing an issue so we can capture this.

**Comment by rauljordan** [comment]
We can close - confirmed with @nisdas and @mcdee "its mostly one way now. I think its defined in the spec, where the inbound peer sends the status request"
