### ISSUE TITLE
Fail to build for target Windows (on Mac)

### ISSUE THREAD

**Issue by wchuan11** [prysmaticlabs/prysm#4231]
Error message:
```
ERROR: While resolving toolchains for target @prysm//third_party/kafka:librdkafka: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type
INFO: Elapsed time: 0.416s.
```

Requires c++ toolchain to get it to work.

**Comment by prestonvanloon** [comment]
Related cross compile issues: #2849 #2974

**Comment by mtbitcoin** [comment]
Just to add more info to the above, the compilation for windows binaries on a Mac used too work before and only broke recently..

**Comment by wchuan11** [comment]
@nisdas If you manage to look into this, will test it out

**Comment by nisdas** [comment]
Hey @wchuan11 , I haven't been able to solve this so far. Unfortunately I am still blocked on this

**Comment by rauljordan** [comment]
Resolved by @SuburbanDad and @prestonvanloon

**Comment by wchuan11** [comment]
@SuburbanDad @prestonvanloon Is there any instructions or documentation to test on this?
Tested using `bazel build --define=ssz=minimal --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //beacon-chain` does not work on Mac still.

**Comment by prestonvanloon** [comment]
Please see https://github.com/prysmaticlabs/prysm/blob/master/tools/cross-toolchain/README.md

The README needs to be updated since #5008 has been resolved. Try using the docker sandbox approach. 

```
bazel build --config=windows_amd64_docker //beacon-chain
```
