### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by wchuan11** [prysmaticlabs/prysm#4232]
Error message:
```
INFO: Analyzed target //beacon-chain:beacon-chain (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/user/_bazel_user/ibht2cwa/external/com_github_herumi_bls_eth_go_binary/bls/BUILD.bazel:38:1: GoCompilePkg external/com_github_herumi_bls_eth_go_binary/bls/windows_amd64_stripped/go_default_library%/github.com/herumi/bls-eth-go-binary/bls.a failed (Exit 1)
exec: "C:/Program": file does not exist
compilepkg: error running subcommand: exit status 2
Target //beacon-chain:beacon-chain failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.598s, Critical Path: 0.88s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by prestonvanloon** [comment]
Looks very similar to https://github.com/bazelbuild/bazel/issues/4496. Can you take a look at that issue and see if it resolves your problem? @wchuan11

**Comment by wchuan11** [comment]
Have tried the suggestions in the referenced thread but issue remains.

**Comment by wchuan11** [comment]
@prestonvanloon Are you are able to build on your Windows VM?

**Comment by prestonvanloon** [comment]
@wchuan11, sorry about the delay. I was out of office last week and have not had a moment to attempt this. I'll try sometime later this week.

**Comment by Buttaa** [comment]
installed Git directly in C:\ as mentioned [here](https://github.com/bazelbuild/bazel/issues/4496#issuecomment-380482467)
Error still occurs - seems to be a path problem

**Comment by rauljordan** [comment]
Is this solved by our cross-compile stuff @prestonvanloon?

**Comment by prestonvanloon** [comment]
Not really. I don't think that we can build on windows, but we are now
providing windows binaries.

I think this can be closed unless someone really wants to build prysm from
source on windows.

>

**Comment by prestonvanloon** [comment]
I would like to close this if possible. Does anyone feel strongly about the need to build on windows?

We are able to build windows executables with recent cross compile changes. Let me know if this doesn't satisfy your use case and we can revisit this issue.

**Comment by Buttaa** [comment]
@prestonvanloon  as long as binaries are provided it should be fine. (more frequently if possible)

Note that Docker also doesn't work on some Windows versions (Windows home?). 
It will cut off a lot of potential users in the long run for testing.

**Comment by prestonvanloon** [comment]
Thanks for the feedback. I'm glad to hear the executables will work for windows solutions. 

We are working in improving our documentation around this and welcome any advice from windows users as our team is primarily linux / mac os x. 

I think there are some issues with [prysm.sh](https://github.com/prysmaticlabs/prysm/blob/master/prysm.sh) that have not been resolved on windows yet. If you've had any success with this script, please let us know how we can improve the documentation. Thanks @Buttaa
