### ISSUE TITLE
Prysm API: what are the reasons for missing slots/blocks?

### ISSUE THREAD

**Issue by strictlymomo** [prysmaticlabs/prysm#4235]
Here's a screenshot of the head of the blockchain at a certain point in time.

<img width="856" alt="Screen Shot 2019-12-09 at 3 49 13 PM" src="https://user-images.githubusercontent.com/8671427/70473761-b199f280-1a9f-11ea-9179-426f00ff998c.png">

You'll notice:
- 202903 - scheduled
- 202902 - **not exist**
- 202901 - scheduled

I don't think this is beaconcha.in as `https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=202902` yields:
```
{
  "blockContainers": [],
  "nextPageToken": "0",
  "totalSize": 0
}
```
Some other examples further back in time:

[Epoch 25247 - Finalized](https://beaconcha.in/epoch/25247)
- 4 proposed
- 0 missed
- 4 not exist: [201982](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201982), [201980](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201980), [201979](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201979), [201977](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201977)

[Epoch 25242 - Finalized](https://beaconcha.in/epoch/25242)
- 4 proposed
- 1 missed
- 3 not exist

Does a single node power the Prysm API? Is data missing due to lack of network propagation? Or should the non-existent blocks be missing blocks?

**Comment by mcdee** [comment]
There is no guarantee that any given slot has a block.  At each slot a single proposer _can_ create a block, but it is not _required_ to do so.  For example, the validator may be offline when it is given the role to propose.

**Comment by rauljordan** [comment]
As @mcdee mentioned, proposers can skip slots, so there won't be a block at every slot and that is part of the protocol. However, it is concerning when there was a block proposed but *no block archived in the DB* when attempting to retrieve it from the API. There are many nodes powering the API, not just one, so this is pretty strange behavior.

**Comment by strictlymomo** [comment]
> There is no guarantee that any given slot has a block. At each slot a single proposer can create a block, but it is not required to do so. For example, the validator may be offline when it is given the role to propose.

> there won't be a block at every slot and that is part of the protocol

Thanks. In this scenario, would you consider the status `missed` or "not exist"? Or does `missed` mean something else? 

To go back to [Epoch 25242](https://beaconcha.in/epoch/25242) example:
- Beaconchain UI = `Missed` block for [Slot 201940](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201940) . Would this indicate:

>  However, it is concerning when there was a block proposed but no block archived in the DB when attempting to retrieve it from the API.
 
- Beaconchain UI = non-existent for [Slot 201939](https://api.prylabs.net/eth/v1alpha1/beacon/blocks?slot=201939)

Both slots come back with the same response from the API, but have different statuses on beaconcha.in. 

Apologies in advance if this question is out-of-scope for you guys and should be posted in their repo instead.

**Comment by rauljordan** [comment]
I think `Missed` is a good work to mean: a validator was supposed to propose a block at slot X, but failed to do so.

The words `NotFound` or `Non-Existent` should refer to a block that was proposed at a slot, but for some reason it is missing from a node's database

**Comment by rauljordan** [comment]
Closing this as it has been answered
