### ISSUE TITLE
Keep invalid attestations until expiration 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4250]
As outline in a fork choice spec, an incoming attestation that is asserted as invalid may be valid at a later time. A node should keep it around and consider scheduling it for later processing. In our implementation, the node simply discards the invalid attestation and loses it for later processing. This could contribute to the unresolvable fork issue

**Comment by prestonvanloon** [comment]
I think we need to consider this carefully. Do we propagate invalid attestations? Our current pubsub pipeline only processes "valid" messages and propagates any new, distinct, and valid message.

**Comment by terencechain** [comment]
> I think we need to consider this carefully. Do we propagate invalid attestations? Our current pubsub pipeline only processes "valid" messages and propagates any new, distinct, and valid message.

This definitely requires a design doc. At the same time it's an important piece for fork choice to resolve
