### ISSUE TITLE
trying to fetch genesis block errors

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#4257]
hi

when trying to get the genesis block from your node, i get a 503 error for 
`curl -X GET "https://api.prylabs.net/eth/v1alpha1/beacon/blocks?genesis=true" -H  "accept: application/json"`

when i try to get it from my server i get 
`rpc error: code = Internal desc = Found more than 1 genesis block: list blocks`

please let me know how i can help debug this further,
cheers

**Comment by terencechain** [comment]
cc @rauljordan

**Comment by prestonvanloon** [comment]
We see the same thing in production as well. 

```
curl -v https://api.prylabs.net/eth/v1alpha1/beacon/blocks?genesis=true
...
< HTTP/2 500
< content-type: application/grpc
< grpc-status: 13
< grpc-message: Found more than 1 genesis block

```

**Comment by rauljordan** [comment]
hmm that's really bad, checking this right now

**Comment by rauljordan** [comment]
Confirmed it happens locally as well

**Comment by rauljordan** [comment]
#4269 fixes this @tzapu
