### ISSUE TITLE
Resume Sync After Initial Sync Completes

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#426]
With #404 being merged in , initial sync and resume sync are separate services. With this when initial sync is done, it exits the initial sync service. However normal sync is not resumed. A PR dealing with this issue will allow normal sync to resume, also the PR will deal with changing the sync polling interval so that nodes with insufficient number of peers are given a larger interval to get up to sync

- Resume Sync after Initial Sync
- Make sync polling interval dependent on number of connected peers

**Comment by rauljordan** [comment]
Can this be closed @nisdas?

**Comment by nisdas** [comment]
@rauljordan , Yeap this is resolved by #787
