### ISSUE TITLE
Add Slot Range Filter for Blocks

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4261]
No tracking issue, but this is a follow-up to #4183. We removed an epoch filter from the ListBlocks API due to it being ambiguous, but we should add a request that can specify a range of slots to retrieve, such as `0-100` (inclusive on both ends). This issue can be resolved via a straightforward PR.

**Comment by prestonvanloon** [comment]
Are we closing this as a non-issue or do we still want to add slot range for querying blocks?
