### ISSUE TITLE
Use Sparse Merkle Trie for Fork-Choice Rule Data Structure

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#429]
Hi all,

As part of #422, we are using a DAG to store received blocks at each received slot number. This is implemented naively as a map of slots to slices of blocks, which does not lend itself to light-client friendly proofs. SMT (Sparse Merkle Tries) have been discussed as the path forward. A PR for this would use an SMT instead of the map created in #422's `/beacon-chain/blockchain/service.go`.

Assigning provisionally to @nisdas.

**Comment by nisdas** [comment]
design doc for this https://docs.google.com/document/d/1C-9uOsA2ozWz5gcGwnbfZX1x8Ryi8jTJZqoouq8Lgm0/edit#

**Comment by rauljordan** [comment]
Closing this as we have decided to persist all processed blocks and purge after 2 * cycle_length
