### ISSUE TITLE
Migrate Docs to Docusaurus

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4301]
@har00ga brought up how Gitbook is becoming hard for us to maintain and customize for our growing documentation needs. A big part of it has to do with how closed source it is and also how it locks us into a particular form of editing and collaboration. Instead, @har00ga suggested using [Docusaurus](https://docusaurus.io/en/) as an alternative. It looks nice, is open source, allows for all sorts of customization, and we can host it ourselves. It uses pure markdown for the rendered pages where we can modify as we please. Opening this issue to migrate to this solution.

**Comment by prestonvanloon** [comment]
@rauljordan who owns this and do we know how much effort it is to migrate?

**Comment by rauljordan** [comment]
@har00ga is this something you could take up? It would be really awesome to have all our docs in docusaurus instead of Gitbook

**Comment by har00ga** [comment]
Oh sorry, I had only replied to this in Discord -- absolutely, happy to get this completed! It won't take long, Docusaurus accepts MD files so there's no painstaking reformatting to be done. There will need to be some adjustments made for the new layout considerations, but after that is completed it will mostly be  making the aesthetic changes that everyone would like to see. It'll take maybe a solid day or two worth of work in total.

**Comment by rauljordan** [comment]
Done by @har00ga in https://github.com/prysmaticlabs/documentation. We will be rolling this out to production soon!
