### ISSUE TITLE
Gossipsub Usage Is Incorrect

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#4317]
@protolambda has brought to light some problems with our current gossip sub usage. Currently we have two main problems with how we use it. 

1) Excessive Broadcasting 
We currently manually re-broadcast each message we receive; however the gossipsub router does this internally too over here. https://github.com/libp2p/go-libp2p-pubsub/blob/7e5b02f152ae2dd8bceb897affe7ef57cb3c6b4e/pubsub.go#L761 
So messages are being propagated twice, leading to message amplification occurring. This has been the cause of high average message counts.

2) Validation is separate from the gossipsub callback. We do message validation in our pipeline, not involving the gossipsub service of this. This leads to both good/bad messages being relayed to other peers. So whatever validation we do only affects the messages that we manually broadcast. We will need to add in the gossipsub validator to validate messages from specific topics

Related to #4218

**Comment by torfbolt** [comment]
Could the first issue be linked with https://github.com/prysmaticlabs/prysm/issues/4218?

**Comment by nisdas** [comment]
Hey @torfbolt that makes sense, it seems related
