### ISSUE TITLE
Flakey Casper Tests in Travis

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#434]
Casper Tests have been flakey in Travis but they work reliably in local environment. Opening up this issue to investigate why it's flakey to failure in Travis. Also, I've noticed it takes 6 seconds to execute casper tests in Travis, but only 405ms in local enviroment. 

Example log: https://travis-ci.org/prysmaticlabs/prysm/jobs/420168402

**Comment by prestonvanloon** [comment]
The long execution time might be due to testing for race conditions as well as a constrained environment.

**Comment by rauljordan** [comment]
Not so sure - there is no concurrency in the casper package AFAIK. This could be tricky.

**Comment by nisdas** [comment]
Is this still an issue ? I am having a hard time seeing how casper could be flakey, the functions are self - contained and there is no concurrency in the package. afaik see, the Casper test has been fine in the past few builds

**Comment by terenc3t** [comment]
We haven't seen this in a while. Closing for now, reopen if anyone sees it again.
