### ISSUE TITLE
Beacon client crashed with "slice bounds out of range"

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4351]
Tonight my client (30b4b045f503a52142a9f26a8d614b4d226b44eb) crashed and stopped with this error:

> [2019-12-24 03:30:02]  INFO blockchain: Finished applying state transition attestations=5 deposits=0 slot=305710
> panic: runtime error: slice bounds out of range [:608597649] with capacity 496
> 
> goroutine 10085697 [running]:
> github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x27850a0, 0x16a6620, 0xc003712e00, 0x199, 0x1b38960, 0x16a6620, 0xc001415690, 0xe5, 0x1f0, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0x13c0
> github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x27850a0, 0x1709d80, 0xc001bd28d8, 0x196, 0x1b38960, 0x1709d80, 0xc001415690, 0xe5, 0x1f0, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
> github.com/prysmaticlabs/go-ssz/types.(*compositeSliceSSZ).Unmarshal(0x27850a0, 0x14b1160, 0xc001710fd8, 0x197, 0x1b38960, 0x14b1160, 0xc001415688, 0x1d2, 0x1f8, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/slice_composite.go:137 +0x44e
> github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x27850a0, 0x170d980, 0xc001710f70, 0x199, 0x1b38960, 0x170d980, 0xc0014155ac, 0x2ae, 0x2d4, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
> github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x27850a0, 0x1722e40, 0xc005f23c38, 0x196, 0x1b38960, 0x1722e40, 0xc0014155ac, 0x2ae, 0x2d4, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/struct.go:153 +0x1284
> github.com/prysmaticlabs/go-ssz/types.(*structSSZ).Unmarshal(0x27850a0, 0x16b56e0, 0xc005f23c00, 0x199, 0x1b38960, 0x16b56e0, 0xc001415500, 0x35a, 0x380, 0x0, ...)
>         external/com_github_prysmaticlabs_go_ssz/types/struct.go:243 +0xf8d
> github.com/prysmaticlabs/go-ssz.Unmarshal(0xc001415500, 0x35a, 0x380, 0x1712900, 0xc005f23c00, 0x7f39fe4de6d0, 0x0)
>         external/com_github_prysmaticlabs_go_ssz/ssz.go:106 +0x335
> github.com/prysmaticlabs/prysm/beacon-chain/p2p/encoder.SszNetworkEncoder.Decode(0x0, 0xc001415500, 0x35a, 0x380, 0x1712900, 0xc005f23c00, 0x169bce0, 0xc00617886d)
>         beacon-chain/p2p/encoder/ssz.go:85 +0x69
> github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).decodePubsubMessage(0xc0000f2d80, 0xc00549e7b0, 0x179f9ad, 0x1e, 0x0, 0x0)
>         beacon-chain/sync/decode_pubsub.go:24 +0x227
> github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateBeaconBlockPubSub(0xc0000f2d80, 0x1b140a0, 0xc0000d2000, 0xc003becf00, 0x27, 0xc00549e7b0, 0x446200)
>         beacon-chain/sync/validate_beacon_blocks.go:34 +0x13c
> github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1(0x1b140a0, 0xc0000d2000, 0xc003becf00, 0x27, 0xc00549e7b0, 0xc001487b58)
>         beacon-chain/sync/subscriber.go:178 +0x6d
> github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc001743bc0, 0x1b140a0, 0xc0000d2000, 0xc003becf00, 0x27, 0xc00549e7b0, 0xc001034600)
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:335 +0x8a
> github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic(0xc000713cb0, 0xc001743bc0, 0xc003becf00, 0x27, 0xc00549e7b0, 0x276c440)
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:316 +0x18d
> github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic(0xc000713cb0, 0xc001bd28c8, 0x1, 0x1, 0xc003becf00, 0x27, 0xc00549e7b0, 0xc001034700)
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:269 +0x3c8
> github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic(0xc000713cb0, 0xc001bd28c8, 0x1, 0x1, 0xc003becf00, 0x27, 0xc00549e7b0)
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:258 +0x74
> github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1(0xc000713cb0, 0xc001bd28c8, 0x1, 0x1, 0xc003becf00, 0x27, 0xc00549e7b0)
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:233 +0x67
> created by github.com/libp2p/go-libp2p-pubsub.(*validation).validate
>         external/com_github_libp2p_go_libp2p_pubsub/validation.go:232 +0x473
>

**Comment by nisdas** [comment]
Hey @torfbolt #4350, captures the panic and prevents the node from crashing

**Comment by torfbolt** [comment]
Hi @nisdas, so you think this is already fixed, or is it just mitigated from crash to panic error message?

**Comment by nisdas** [comment]
I inadvertently caused the error in the network, so it shouldn't show up as an error either. This issue should not come up again

**Comment by torfbolt** [comment]
Thanks, closing it then.
