### ISSUE TITLE
Ejected validator has effective balance 3.2ETH

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4386]
Saw a few instances in beacon block explorer where a validator's status is ejected but still has 3.2ETH as effective balance. Opening this issue to track investigation.

![Screen Shot 2020-01-02 at 10 50 35 AM](https://user-images.githubusercontent.com/21316537/71685659-e66f3180-2d4d-11ea-92b5-5076459c949e.png)

https://beaconcha.in/validator/300

**Comment by rauljordan** [comment]
@ppratscher just wondering if this is something on the front-end side? Or does the data the beacon nodes send you say 3.2?

**Comment by terencechain** [comment]
Etherscan says 3.2 too

https://beacon.etherscan.io/validator/0x86000c054a50653b4d4e5e4fa5c01b8f3f2a0743f924e3afda0541a39a1839ce1645d0789451d7217a3b5f8c5928363c

**Comment by rauljordan** [comment]
He got ejected, then tried to top-off his balance by sending another deposit, and looks like effective balance jumped back up to 3.2 Nice catch @terencechain, this is a bug.

**Comment by terencechain** [comment]
After further discussion with @rauljordan and looking at the spec. This is an expected behavior from enshrined protocol design.
What we learn from this is wallet design for on-boarding and deposit workflow should be solid to protect user from such action
