### ISSUE TITLE
Log a warning if not dialable

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4418]
Especially when using flag --p2p-host-ip, users should be given a warning when one or more of their advertised multi-addresses are not accessible at start up.

Ideally, this would happen in the p2p start routine as a ping to all of the advertised multiaddresses. 
Additionally, this may be valuable to periodically check.

**Comment by rauljordan** [comment]
Assigning to @nisdas for triage for now

**Comment by nisdas** [comment]
Just to clarify, we would try to verify if our host ip was dialable ?

**Comment by prestonvanloon** [comment]
@nisdas yeah the idea is that all of the advertised multiaddresses should be dialable from the node itself. If they advertise "You can reach me at my public IP and port", but the routing is not set up correctly, then it would be helpful user feedback to report this WARN level message to the user.
