### ISSUE TITLE
Attestation failed to update vote

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4425]
![image](https://user-images.githubusercontent.com/26490734/71823817-738cf000-3098-11ea-8965-e8d78352ee14.png)

**Comment by Buttaa** [comment]
![image](https://user-images.githubusercontent.com/26490734/71826764-ffa21600-309e-11ea-9315-26959660c40a.png)

**Comment by terencechain** [comment]
Thanks for opening this issue. Luckily these part of the code will soon to be deprecated in v0.9.2 testnet relaunch. We'll keep it open until testnet restarts

**Comment by terencechain** [comment]
@Buttaa have you seen this in the recent runs? If not, can we close it?

**Comment by Buttaa** [comment]
> 
> 
> @Buttaa have you seen this in the recent runs? If not, can we close it?

i stopped using Docker, so I can't say. But I'll close it and re-open if I see it!

**Comment by rauljordan** [comment]
Duplicate of #4278
