### ISSUE TITLE
[HELP] Error: Unable to retrieve block from stream error=i/o deadline reached

### ISSUE THREAD

**Issue by yashbhavsar007** [prysmaticlabs/prysm#4441]
I became validator as per the following steps given on https://prylabs.net/participate but i got some errors which is shown in below image.
My system configuration is given below
AWS ec2 t2.large instance with 8 GB memory

Error: 
[2020-01-07 09:10:17] ERROR sync: Unable to retrieve block from stream error=i/o deadline reached
[2020-01-07 09:10:17] ERROR sync: Could not send recent block request: i/o deadline reached

![Screenshot 2020-01-07 at 2 40 49 PM](https://user-images.githubusercontent.com/26292780/71883389-5b7ea480-315c-11ea-9591-774bfa01518f.png)

**Comment by rauljordan** [comment]
Hey @yashbhavsar007 our testnet was undergoing a lot of errors in finality and other problems at that time. We are now working on revamping it with the latest version of the eth2 specification over the next 24 hours, so we can close this issue. If it happens to you with our new testnet again, feel free to re-open.
