### ISSUE TITLE
Add Flag for Configuring gRPC Max Message Call Size for Validator Client

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4444]
We have set the default value of:
```go
grpc.MaxCallRecvMsgSize(10 * 5 << 20), // 10Mb
```
in our validator client in #4154, but this should be a configurable value via a flag. Opening a tracking issue for this small task.

**Comment by prestonvanloon** [comment]
Minor comment, that default value is actually 50Mb. I think the comment is out of date.

**Comment by rauljordan** [comment]
Resolved by #4524
