### ISSUE TITLE
Deprecate GenesisBeaconState Function and Make OptimizedGenesisBeaconState Default

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4446]
Hi all, in the v0.9.2 branch we introduced an `OptimizedGenesisBeaconState` function which does not process deposits at the start. We maintained an old, spec-complaint version called `GenesisBeaconState` which we should be deprecated as it is only used in tests and has duplicated logic with the optimized version.

**Comment by nisdas** [comment]
`GenesisBeaconState` calls `OptimizedGenesisBeaconState` too 
https://github.com/prysmaticlabs/prysm/blob/v0.9.2/beacon-chain/core/state/state.go#L94 . I think we can leave it as it is, or change the name of `OptimizedGenesisBeaconState` . Maybe its misleading

**Comment by rauljordan** [comment]
Closing this - it's not a big deal and didn't realize one called the other
