### ISSUE TITLE
Consider Orphaned Block Information When Archiving Data Per Epoch

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4450]
Thanks @shayzluf for bringing this up. Currently, our archiver stores information regarding items for the canonical chain, such as committees, participation, etc. but fails to consider archiving information relating to orphaned or a forked chain, which would still be important for the slasher service to listen for. Opening this issue for discussion and for @shayzluf to elaborate more on the problem.

It seems like, specifically, we care about archiving committees for orphaned chain branches, is that right?

**Comment by shayzluf** [comment]
thanks @rauljordan for opening this issue. mainly there is a need to be able to get the committee for orphaned blocks so an attestation could be converted to indexed attestation. committee for an orphaned block could be different from canonical epoch randao mix so these have to be stored as well if encountered with

**Comment by rauljordan** [comment]
This is no longer necessary with the cold/hot state management, as archival nodes will be deprecated anyways and we'll have all the blocks needed to replay any states we want, even forked ones.
