### ISSUE TITLE
Deprecate Interop Code

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4462]
With the latest v0.9.2, interop feature is unfortunately broken in Prysm. Since we don't plan to support it for the long haul, now it's a good time to remove interop feature as whole in Prysm. Opening this issue to track the progress

**Comment by nisdas** [comment]
I would actually like to keep some of the interop code. @terencechain 
Its very useful for testing and getting validators to start up quickly. Some of the interop functions 
will still be needed for multi-client testing, I think we should fix the interop code instead of removing it

**Comment by terencechain** [comment]
Great. Thanks for the feedback

**Comment by rauljordan** [comment]
Closing this as there is no need to remove interop code yet
