### ISSUE TITLE
Define Clear Responsibilities of an Observer Beacon Node

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#448]
Hi all,

We currently have an observer mode when running a beacon node by default, which means a node that does not interact with validators in order to advance the canonical chain, but instead just listens on the p2p network and performs block sync. We have yet to clearly define all of the roles of an observer node throughout our system and how important they are for the future. Opening this issue for visibility and discussion.

**Comment by prestonvanloon** [comment]
Can you elaborate more on this issue? 

An observer has no responsibilities in the sharded system. This role exists merely to enable users to join the network without being a validator. The role is similar to a non-miner node in ethereum 1.0.

**Comment by rauljordan** [comment]
Pinging @terenc3t as he brought up this point in our call

**Comment by terenc3t** [comment]
We should discuss if there's additional observer functionality to implement before our pre-release/demo. My understanding is for the demo we'll launch geth node/validator node/observer node. For the observer node, do we need additional features like?

- cli flag to select if it's a beacon chain observer node or a shard chain observer node
- cli flag to select which shard to monitor
- anything else?

**Comment by rawfalafel** [comment]
There aren't any extra features we need that I can think of.

But, we should test that everything works as expected when zero/one/multiple validators connect to a beacon chain. There was that one bug where a buffered channel got stuck when no validators were available to flush the channel. We might run into similar bugs in the future.

**Comment by rauljordan** [comment]
Agree - we will do that in preparation for the pre-release

**Comment by rauljordan** [comment]
Closing this, as a dev flag will encompass a lot of this functionality for local development purposes #530
