### ISSUE TITLE
Implement Bloom Filter to Check If Beacon Block Exists

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#450]
Hi all,

A PR for this issue would implement a [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) data structure to check for existence of a beacon block in our beacon chain project. Bloom filters are quite efficient also used by geth for checking existence of logs. We can keep this data structure in our shared/utils/ package.

**Comment by prestonvanloon** [comment]
Can you elaborate more on this issue? 
Why do we need our own implementation of a bloom filter rather than using a third party library?

**Comment by rauljordan** [comment]
Thinking about this more and can't seem to figure out why we would use it instead of just a db.Has. Closing until further discussions.
