### ISSUE TITLE
 Could not receive attestation in chain service

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4503]
![image](https://user-images.githubusercontent.com/26490734/72209214-2a7bd800-34ac-11ea-9b8d-1427f64981f2.png)

`docker pull gcr.io/prysmaticlabs/prysm/beacon-chain:testFix`
`docker run -it -v $HOME/prysm:/data -p 4000:4000 gcr.io/prysmaticlabs/prysm/beacon-chain:testFix --datadir=/data --clear-db`

**Comment by shawnharmsen** [comment]
Getting the same issue:

[2020-01-13 23:58:37] ERROR blockchain: Could not receive attestation in chain service error=signature did not verify
github.com/prysmaticlabs/prysm/beacon-chain/core/blocks.init


As well as the p2p pubsub error=signature did not verify

[2020-01-13 23:59:18] ERROR sync: Failed to handle p2p pubsub error=signature did not verify
github.com/prysmaticlabs/prysm/beacon-chain/core/blocks.init
	beacon-chain/core/blocks/block_operations.go:38
runtime.doInit

log file attached
[sudo.m5.large.latest.log](https://github.com/prysmaticlabs/prysm/files/4056694/sudo.m5.large.latest.log)

**Comment by Buttaa** [comment]
@shawnharmsen  this seems to be Docker related, have you tried to run it with Bazel? Works fine for me now!

**Comment by shawnharmsen** [comment]
yup yup it works fine now.
Just listing a full log for reference.
Thanks for the help.

**Comment by prestonvanloon** [comment]
This might be a bigger issue. See related #4630 if you are still having issues.
