### ISSUE TITLE
Optimize proposer attestation inclusion

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4507]
As specified in the [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#attestations):
`
 The attestations added must satisfy the verification conditions found in attestation processing. To maximize profit, the validator should attempt to gather aggregate attestations that include singular attestations from the largest number of validators whose signatures from the same epoch have not previously been added on chain.
`

This has became a bottleneck in RPC get block request to verify all the candidate attestations signature before including them into the block. Opening this issue for investigation

In v1.0 of the [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#is_valid_indexed_attestation) on verifying attestation signature, attestation signature is verified via `bls.FastAggregateVerify`, I can imagine that's going to be whole lot faster than what we currently have. I suggest to resolve our current testnet, given complete validator honesty assumption. We can remove signature verification for attestation inclusion for block

**Comment by prestonvanloon** [comment]
Assigning to @farazdagi as Q2 OKR

**Comment by prestonvanloon** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/5980

**Comment by rauljordan** [comment]
Can we close this one @farazdagi ?

**Comment by farazdagi** [comment]
Not yet, I will re-visit attestations at the end of the week (I have semi-ready branch, that optimizes attestation selection by proposer), and file one more PR, to wrap this functionality up.

**Comment by rauljordan** [comment]
Update on this @farazdagi ?

**Comment by farazdagi** [comment]
Sorry for the delay, got stuck with next round of updates to init-sync. Will produce an update on this, right after I get my peer scoring related PRs merged (should be next couple of days).
