### ISSUE TITLE
Optimize fork choice filter block tree

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4509]
With latest fork choice fixes for finality reversion, `get_filter_block_tree` is becoming the main bottleneck for `head` calculation. Due the the nature of `filter_block_tree ` recursive calls, and `get_head` gets called everyone attestation received. Fork choice is becoming unsustainable in run time under mainnet config. Opening this issue to track fork choice optimization in particular `get_filter_block_tree`

<img width="1618" alt="Screen Shot 2020-01-09 at 9 28 53 PM" src="https://user-images.githubusercontent.com/21316537/72222709-c7765980-351c-11ea-823a-4f39175eb174.png">

**Comment by terencechain** [comment]
cc @ protolambda

**Comment by terencechain** [comment]
cc @protolambda

**Comment by protolambda** [comment]
Thanks for the cc, I've been talking about updated fork-choice optimizations with @paulhauner recently. Maybe we should have a little co-work call (and ask other fork-choice implementers of clients to join) to discuss how to handle optimization here?

**Comment by terencechain** [comment]
That will be great. I'll bring this up in the Discord for better coordination

**Comment by rauljordan** [comment]
Cached and done by #4515
