### ISSUE TITLE
Update to IETF BLS standard for run time

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4512]
Opening this issue to track the progress of updating BLS lib up to IETF standard. There's a few speed up method mentioned in the spec such as `FastAggregateVerify` which is desperately needed for run time.

Eth2 reference PR: https://github.com/ethereum/eth2.0-specs/pull/1532
The official IETF spec: https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-00

**Comment by prestonvanloon** [comment]
@nisdas has this been completed?

**Comment by nisdas** [comment]
Yeap it has been completed in our update to v0.10.1 . Closing this now
