### ISSUE TITLE
RPC Tests Broken on Master

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4531]
Running `bazel test //beacon-chain/rpc/beacon:go_default_test` on master passes, but running:
```
bazel test //beacon-chain/rpc/beacon:go_default_test --test_output=streamed
```
shows a panicking test of the form:

```
--- FAIL: TestServer_ListAssignments_Pagination_DefaultPageSize_NoArchive (14.87s)
panic: runtime error: slice bounds out of range [:250] with capacity 0 [recovered]
        panic: runtime error: slice bounds out of range [:250] with capacity 0
```
This is blocking development of new features / optimizations in that package.

**Comment by rauljordan** [comment]
Moreover, we need to identify why this only fails this way and if there are other packages in Prysm that fail as well.

**Comment by prestonvanloon** [comment]
Note that test output of streamed disables test sharding which is why this is failing now rather than without the test output flag. Maybe there is something leaking between tests in a cache or configuration override.
