### ISSUE TITLE
Restructure Prysm Discord server to host a community better

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#4556]
### The Prysm Discord Server
As our Prysm discord approaches almost 1,500 members, we want to start ensuring it is a welcoming community that will be growing as ETH2 grows closer to fruition. While the Prysm team uses the Discord plenty as our main communication platform, we don't want to alienate any newcomers or possible contributors by making them worry that simple questions or discussions are distracting to the team, or are off-topic.

Currently, a large amount of discussion is between the team members, we have several specific topic public-facing channels that are purely for development talk, which newcomers will most likely not participate in. This heavy amount of team discussion might make community members feel that discussion in them will be distracting, or off-topic, which may be the purpose of such specific channels, but we must offer an alternative channel for them to feel free to discuss whatever ETH2 related topics they wish.

### Possible Improvements
First off, we should go through each channel, and make sure the channel descriptions are descriptive but concise on the channels purpose. This can include information on whether or not they're for open discussion, team-only usage, or targeted for a specific topic they're made for.

Next, we should rename `#chatter` ("chatter" might make newcomers thing it's for chit-chat, not discussion) to something more welcoming like `#general`. This will encourage more users to ask questions regarding ETH2, the team, or anything on their minds.

Also, I believe adding a `#bug-report` channel below #general will help keep `#general` clear from users reporting bugs. If I'm a community member and I see the only "welcoming" channel is bug reports, I wouldn't want to discuss much.

Renaming the "research" category to "discussion" might also help encourage more newcomers to discuss the relevant topics there.

### Channel Restructure Suggestions
I suggest we make a "team" category, that puts team-only channels together. I personally prefer to keep private chats in their own category for organization reasons.

We should possibly move `#standup` to the dev-talk category, since it's mainly team discussion, and users seeing heavy team discussion close to the `#chatter` channel might worry about distracting the team. We want to prevent that.

Moving the "discussion" category above the "dev-talk" category can also be helpful, a new user joins and the first thing they see are tall these heavily team-chat populated channels on intimidating topics. Replacing those with more welcoming and open discussion topics will hopefully make them feel more welcome.

By suggestion of @mcdee we should also sort the channel names in dev-talk by alphabetical order, since there are such a large amount of channels.

**Comment by mcdee** [comment]
Whatever you end up with, *please* sort the channel names alphabetically.  It makes finding a particular channel significantly easier when there is a long list.

**Comment by 0xKiwi** [comment]
> Whatever you end up with, _please_ sort the channel names alphabetically. It makes finding a particular channel significantly easier when there is a long list.

Very good point, we can also add an exception to this for a general channel like #code-review by moving it to the top of the channel.

**Comment by rauljordan** [comment]
Thanks for the suggestions all! Our discord has been nicely remodeled thanks to these ideas: https://discord.gg/wgpaJdv
