### ISSUE TITLE
Eth1 mock RPC is broken

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4568]
With the latest master, eth1 mock RPC no longer works with run time via demo config. This unfortunately prevents testing a lot of upcoming important features. Putting this priority as high

The error received on the beacon node:
`[2020-01-16 14:39:26] ERROR powchain: could not get eth1 block hash: could not query block with given height: not found`

The commands I used:
```
bazel run //:eth1-mock-rpc -- --genesis-deposits 64 --unencrypted-keys-dir  ~/demo/

bazel run //beacon-chain --define ssz=minimal -- --http-web3provider http://localhost:7777 --web3provider ws://localhost:7778 --rpc-port 4000 --bootstrap-node= --monitoring-port=8080 --force-clear-db  --datadir=~/YOURDB --minimal-config --no-genesis-delay
```

**Comment by terencechain** [comment]
temporary assigning to @nisdas

**Comment by rauljordan** [comment]
No longer the case in master eth1-mock-rpc
