### ISSUE TITLE
Could not report validator's rewards/penalties

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4569]
![image](https://user-images.githubusercontent.com/26490734/72571641-7077d800-38c0-11ea-9ba8-bd6ccb5a4f8b.png)

percentChange=0.00034% to percentChange=-0.00112% even though I was online. 
I assume it was caused by this error?

**Comment by Buttaa** [comment]
which lead to this & validator+beacon node crash
![image](https://user-images.githubusercontent.com/26490734/72574297-cb153200-38c8-11ea-9278-53ff7db5bf71.png)

**Comment by Buttaa** [comment]
these issues seem to be Docker related since it's working perfectly fine with Bazel

**Comment by rauljordan** [comment]
This has to do with your beacon node being offline due to unrelated errors and also due to inefficiencies in our beacon node's operations. A lot of recent bug fixes will have resolved several of these problems.
