### ISSUE TITLE
Make State Immutable

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#458]
Currently, `ActiveState` is [mutable](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/types/state.go#L195) in [various](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/types/state.go#L166) [ways](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/types/state.go#L179). The problem with mutability, especially in an inherently immutable object like `ActiveState`, is that it opens up the possibility of leaving the object in an inconsistent state. 

Refactor `ActiveState` so that the object is immutable by returning a new object rather than modifying the existing one. In addition, new objects should be created only one time per block. There's actually a [bug](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/blockchain/core.go#L537-L544) where `recentBlockHashes` are [modified](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/blockchain/service.go#L341) [twice](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/blockchain/core.go#L283) during a new cycle. Bugs like these can be easily detected if the new state is created in one location.

Edit: Once its immutable, we can make a small improvement to the `Hash` function. Since the hash can never change, we can compute it once during construction and reuse it. This lets us get rid of the need to handle the error condition in `Hash`.

**Comment by nisdas** [comment]
@rawfalafel Is this resolved with @IvanTheGreatDev 's PR ?

**Comment by rawfalafel** [comment]
yep!
