### ISSUE TITLE
Make it easier for a staker to find their validators full public keys

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#4580]
Currently, as a staker using Prysm, there is no way for me to get my full public key from the validator client. The only way one can get their full public key is by checking the priv files or if they type the truncated public key from logs into https://beacon.etherscan.io and let it autocomplete their full address.

The validator client will benefit from allowing a staker to find the public keys for the validators they host easily.

One suggestion we've received is to add a `accounts list --keystore-path=/data` command to the validator client.

**Comment by rauljordan** [comment]
Done by @mcdee in #4590
