### ISSUE TITLE
Metrics request: highest possible slot

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#4586]
The node monitoring site eth2stats.io shows a nice timebased counter of the highest possible slot (slot counter increasing every 12 secs). It would be nice to add this slot-value to the metrics page. This way we can create measurements how far the node's head slot is away from this highest possible value (and how fast the delta is decreasing or increasing). 

It seems the value itself is already there, at least in initial-sync. See below screenprint 

<img width="1104" alt="Screenshot 2020-01-27 at 08 28 23" src="https://user-images.githubusercontent.com/28559038/73156857-71d6ab00-40df-11ea-959a-cc6eedaf0f5f.png">

And maybe the same for Epoch #

**Comment by garyschulte** [comment]
It looks like the sync block counter is implemented by taking the time since genesis and dividing by seconds per slot.  Is that a reliable way to calculate this metric or is there likely to be some accumulated drift?

**Comment by rauljordan** [comment]
Hi @garyschulte we do have this prometheus metric live in our nodes, it is called `beacon_slot` here https://github.com/prysmaticlabs/prysm/blob/80248cd296d441121373b733d9d971f85057d8b5/beacon-chain/blockchain/metrics.go#L13

**Comment by handelaar2** [comment]
@rauljordan Then it is lagging (at least for me). I refreshed my metric page and immediately took a screenshot.
beacon_slot here is 11 slots behind the "calculated genesis-seconds times 12" as shown by eth2stats

<img width="475" alt="Screenshot 2020-02-04 at 18 05 30" src="https://user-images.githubusercontent.com/28559038/73768542-7d7a3f80-4779-11ea-9190-f52ae8694815.png">

**Comment by garyschulte** [comment]
> @rauljordan Then it is lagging (at least for me). I refreshed my metric page and immediately took a screenshot.
> beacon_slot here is 11 slots behind the calculated "seconds since genesis" divided by 12" as shown by eth2stats. For me they are not the same.

I noticed the same behavior.  I am charting beacon_slot and beacon_head_slot, and head slot does definitely lag for whatever reason.  Perhaps whatever code path that isemitting that metric is not being triggered during those periods

**Comment by handelaar2** [comment]
This (already closed) issue has resolved itself via #4754

<img width="665" alt="2020-02-05_19-00-54" src="https://user-images.githubusercontent.com/28559038/73869137-12e50480-484a-11ea-919d-54676037d529.png">

It is ok now as can be seen in the screen print.
(I only observed a max of 1 slot behind the "ticker".

Thanks @terencechain

**Comment by handelaar2** [comment]
Still different things I would say (my_headslot<>others_headslot<>slot_ticker). I guess we need to create our own additional value outside the metrics-page to be able to also track the "slot_ticker". Confusing.

<img width="701" alt="2020-02-06_09-43-50" src="https://user-images.githubusercontent.com/28559038/73920951-baa01800-48c6-11ea-98e0-174ff35760cc.png">

**Comment by prestonvanloon** [comment]
@handelaar2 Based on your comments after closing, is this still an issue we should look into?

**Comment by rauljordan** [comment]
@handelaar2 please let us know if this is still a problem

**Comment by handelaar2** [comment]
Can only confirm in a few days after the restart of the testnet (don't have a proper beacon running right now)

**Comment by handelaar2** [comment]
I still see this as an issue.
 We are missing a kind of "CurrentSlot" in the metrics as defined in process_block_helpers.go That one is  "timebased" (using now() ) . 

beacon_head_slot and beacon_slot *are not* (not sure where they get their values from).
https://github.com/prysmaticlabs/prysm/blob/2fef9d3e5e08073eb901fa777527488d51d78311/beacon-chain/blockchain/metrics.go#L85
_

CurrentSlot (looks pure timebased to me):
https://github.com/prysmaticlabs/prysm/blob/1224e75ba1af59d5ed074db766d0bd4e9b77ea64/beacon-chain/blockchain/process_block_helpers.go#L23

_

To clarify again what I mean, below screenprint shows this timebased slot number:
the blue value on eth2stats at the top. As also can be seen in the screenprint, both metric "slot values" are lagging (not showing this timebased (theoretical best) slot). So I would like to see a metrics value which says for this example: 3990
<img width="1075" alt="2020-04-18_15-18-34" src="https://user-images.githubusercontent.com/28559038/79639219-a0b66780-818a-11ea-9e82-e0d105f7a247.png">

**Comment by mcdee** [comment]
There are two different metrics: the current slot of the _chain_, which is calculated purely from genesis timestamp and current time, and the current slot of the _node_, which is equivalent to the node's head slot as above.

There are discussions going on at https://github.com/ethereum/eth2.0-APIs/issues/25 regarding making this and other information available via a standard API.

**Comment by handelaar2** [comment]
That is my point Jim, we currently don't have in the metrics that "current slot of the *chain*" ((now-genesis)/12) as you call it. It is not there. So that is the value I would like to make available to prometheus/grafana (not via the api).

**Comment by handelaar2** [comment]
Thanks!
<img width="414" alt="2020-04-21_08-26-00" src="https://user-images.githubusercontent.com/28559038/79833251-53651080-83ab-11ea-8607-511e450cd310.png">
