### ISSUE TITLE
Rapid drop off peers

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4588]
![image](https://user-images.githubusercontent.com/26490734/72681444-ebf5a700-3ac3-11ea-84f5-17944546e88b.png)

`bazel run //beacon-chain -- --save-deposit-data --min-sync-peers 5 --enable-ssz-cache --datadir=$HOME/prysm`

**Comment by AndreMiras** [comment]
I'm also having the issue on `master` d72e18ba60bcdfa96c3237052a8c7cf9ee8df563 as I described here https://github.com/prysmaticlabs/prysm/issues/4565#issuecomment-576240909

**Comment by Domintek** [comment]
I too am also having this same issue and saw the fail at 35848 / 73840.

**Comment by Buttaa** [comment]
> 
> 
> I too am also having this same issue and saw the fail at 35848 / 73840.

also having this issue around 30-40k/73840.

**Comment by Buttaa** [comment]
@Domintek Issue solved for me. Not sure what has solved it though. Might have been clearing DB.

**Comment by AndreMiras** [comment]
I think this was the fix https://github.com/prysmaticlabs/prysm/pull/4594
Let's close the task then

**Comment by Gsuslu** [comment]
I`m having the same issue in the same block.

**Comment by AndreMiras** [comment]
I'm now running on last master with the command below (note the port `13000`) and I haven't seen this issue since then.
```sh
docker run -it -v $HOME/prysm:/data -p 4000:4000 -p 13000:13000 --name beacon-node   gcr.io/prysmaticlabs/prysm/beacon-chain:latest   --datadir=/data --p2p-host-ip=$(curl -s v4.ident.me)
```
Make sure you docker pull latest before.
```
docker pull gcr.io/prysmaticlabs/prysm/beacon-chain:latest
```

**Comment by prestonvanloon** [comment]
Related #4621
