### ISSUE TITLE
Fix recentBlockHashes Update

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#459]
Our update to [`replaceBlockHashes`](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/blockchain/core.go#L279) looks different from the [2.1 spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view#Per-block-processing). I'm not sure why the code is different from our spec (it doesn't look unintentional), so it may be best to check with @terenc3t first. 

It's also slightly related to #458 if anyone wants to tackle two issues at once :)

**Comment by terenc3t** [comment]
Indeed `replaceBlockHashes`is incorrect, let's fix it using this issue.

**Comment by rawfalafel** [comment]
This has been fixed with the state refactor.
