### ISSUE TITLE
Update Crystallized State Once Per Cycle

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#460]
Currently, [`setCrystallizedState`](https://github.com/prysmaticlabs/prysm/blob/f0abbf6f2679d9606e71b0c9d37113a7a2300d3a/beacon-chain/blockchain/service.go#L203) gets called every slot, even though it only changes once per cycle. Check that the state changed before writing to disk.

**Comment by terenc3t** [comment]
Fixed via #541
