### ISSUE TITLE
positionInActivationQueue stuck in the same position for more than 24 hours

### ISSUE THREAD

**Issue by GuillaumeOcculy** [prysmaticlabs/prysm#4611]
My position have not changed for more than 24 hours.
```
INFO validator: Waiting to be activated depositInclusionSlot=72991 positionInActivationQueue=6356 pubKey=0xad4847f951aa status=PENDING_ACTIVE
```
The estimation says that I should be activated in 6 days : https://www.beaconcha.in/validator/32146

<img width="935" alt="Screenshot 2020-01-22 at 00 05 24" src="https://user-images.githubusercontent.com/3475334/72851088-f9b95100-3caa-11ea-84c4-87d83a664490.png">
<img width="1429" alt="Screenshot 2020-01-22 at 00 05 45" src="https://user-images.githubusercontent.com/3475334/72851089-f9b95100-3caa-11ea-9d27-1857f1534bdd.png">

**Comment by rauljordan** [comment]
You are currently active, it just takes a super long time for validators to activate given we only have around 900 activations per day https://www.beaconcha.in/validator/32146
