### ISSUE TITLE
Explanation for High CPU / Mem Usage

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4619]
Hi all,

Some users have been asking why their Prysm nodes take up so much memory and cpu. In short, there are many **extremely** expensive data copying operations we perform on the beacon chain state over 56 times per slot (a period of 12 seconds), which eats up memory at an alarming rate. Additionally, the memory footprint of keeping around eth1 deposits from the deposit contract take up a big portion of the heap profile. Thanks to @prestonvanloon for pointing this out in #4604.

In terms of CPU specifically, the biggest culprit is the function `processSlots` found in https://github.com/prysmaticlabs/prysm/blob/b030771174750c3dfad30548800f755a3bfd9ad7/beacon-chain/core/state/transition.go#L237. This function calls `stateutil.HashTreeRootState` which eats up the vast majority of CPU cycles. Not only is it slow, but it also calls `proto.Clone()` on the beacon state, often times grinding sync to a halt. Aside from this, fork choice is also a big culprit on current CPU usage.

The issues with memory usage will be fully mitigated by #4614 and fork choice will be eliminated from our bottlenecks with #4615 and other fixes @terencechain is working on. We recommend users to just hang on for a bit while we work hard on resolving these problems.

<img width="1236" alt="Screen Shot 2020-01-22 at 9 44 24 AM" src="https://user-images.githubusercontent.com/5572669/72910922-d8825000-3cfe-11ea-8766-b5538655c961.png">

**Comment by torfbolt** [comment]
This probably explains and should fix #4578 and #4582

**Comment by mondsen** [comment]
Thanks a lot for this issue. Have you target hardware spec (minimum) that shall be capable of running the beacon chain?
