### ISSUE TITLE
Fix getSignedParentHashes

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#463]
From the spec:

Compute `parent_hashes = [get_block_hash(active_state, block, slot - CYCLE_LENGTH + i) for i in range(1, CYCLE_LENGTH - len(oblique_parent_hashes) + 1)] + oblique_parent_hashes`. 
eg, if `CYCLE_LENGTH = 4`, `slot = 5`, the actual block hashes starting from slot 0 are `Z A B C D E F G H I J`, and `oblique_parent_hashes = [D', E']` then `parent_hashes = [B, C, D' E'])`

This is fairly different from our [current implementation](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/active_state.go#L201). This ticket should align our implementation with the spec. The new slice should be initialized with a capacity of `CYCLE_LENGTH` to avoid unnecessary memory allocation and copy.

**Comment by danielschonfeld** [comment]
I'm confused about the nice-to-have.  Isn't the resulting array gonna be of length composed of `CYCLE_LENGTH-len(Attestation.oblique_parent_hashes)` + `len(Attestation.oblique_parent_hashes` ?

**Comment by rawfalafel** [comment]
> I'm confused about the nice-to-have. Isn't the resulting array gonna be of length composed of `CYCLE_LENGTH-len(Attestation.oblique_parent_hashes)` + `len(Attestation.oblique_parent_hashes)` ?

Yep, thanks!

**Comment by danielschonfeld** [comment]
i'm gonna have this done later today
