### ISSUE TITLE
ERROR sync: Failed to handle p2p RPC error=rate limited

### ISSUE THREAD

**Issue by GuillaumeOcculy** [prysmaticlabs/prysm#4667]
I have this error when I run this command : 
```
docker run -it -d -v $HOME/prysm:/data -p 4000:4000 -p 13000:13000 -m 4g --memory-swap=-1   gcr.io/prysmaticlabs/prysm/beacon-chain:latest   --datadir=/data
```
<img width="1439" alt="Screenshot 2020-01-27 at 16 29 19" src="https://user-images.githubusercontent.com/3475334/73187834-4a550200-4122-11ea-9f13-79e2117b2c24.png">

**Comment by rauljordan** [comment]
Hi @GuillaumeOcculy this was due to a bug that would keep requesting blocks and spamming peers due to a genesis time mismatch, so you would get rate limited for this spam. The bug has since then been resolved by @0xKiwi
