### ISSUE TITLE
Bug in `processAttestation` regarding justified_slot

### ISSUE THREAD

**Issue by djrtwo** [prysmaticlabs/prysm#468]
The following line is a bug in relation to the spec:
https://github.com/prysmaticlabs/prysm/blob/ee91be2c4a0ad3ce5a12783eeecf1262134f97ab/beacon-chain/blockchain/core.go#L255

The spec requires "Verify that the `justified_slot` and `justified_block_hash` given are in the chain and are equal to or earlier than the `last_justified_slot` in the crystallized state."

Note that there are two requirements:
- `attestation.justified_block_hash` is in the chain of the block being processed
- `attestation.justified_slot <= crystallized_state.last_justified_slot`

**Comment by IvanTheGreatDev** [comment]
Is this related to #476 at all?

**Comment by terenc3t** [comment]
No. This is for Justifiedslot. #476 is for slotNumber.

**Comment by terenc3t** [comment]
assigned to @danielschonfeld

**Comment by prestonvanloon** [comment]
Resolved in #516
