### ISSUE TITLE
[FEAT] Able to set encrypt password in ENVIRONMENT instead of via flag?

### ISSUE THREAD

**Issue by olwee** [prysmaticlabs/prysm#4681]
Would like to have the option of setting encrypt password in environment for validator clients instead of flag so we can delete credentials post launch of the validator client

**Comment by q9f** [comment]
Password as command line arg should be avoided at any cost.

ref https://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument/596696#596696

ref https://github.com/bitcoin/bitcoin/issues/2318

Viable solutions are config files, password files, or as the OP suggested, env variables.

**Comment by mcdee** [comment]
`keymanageropts` can be an environment variable or a file path, to allow for this.

**Comment by prestonvanloon** [comment]
We offer file based configuration now, if that helps. 

https://docs.prylabs.network/docs/prysm-usage/parameters/#loading-parameters-via-yaml-file
