### ISSUE TITLE
Booting a validator with 2000 keys takes 90 minutes.

### ISSUE THREAD

**Issue by q9f** [prysmaticlabs/prysm#4683]
note the timestamp:

```
~/.opt/prysm master*
❯ bazel-bin/validator/linux_amd64_stripped/validator --keymanager=keystore --keymanageropts='{"path":"/home/user/.prysm","passphrase":"xxxxx"}'
2020/01/29 07:14:07 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
[2020-01-29 07:14:07]  INFO node: Using custom parameter configuration
[2020-01-29 07:14:07]  WARN node: Using Demo Config
[2020-01-29 08:47:17]  INFO node: Validating for public key pubKey=0xac411e3b6353e1ed53cd029829e76ae76a126cc96e37ca2d4cd1a04e47c17a5f6c2d753abe61b1ef566faac926b7db4a
[2020-01-29 08:47:17]  INFO node: Validating for public key pubKey=0xb1f1ffa5237dee2e43fc6a93424b7516cc055b44a211419412707afd364329ece28a1cbda0dbceaef9447bf2b266386d
[2020-01-29 08:47:17]  INFO node: Validating for public key pubKey=0x875b3e8c205970473f18b27e8d21228f69ce9a84ca4e95f73c9b865c76379d93dbcc1a8c91b978810675962eafbe5a4e
```

2220 keys:

```
~/.opt/prysm master*
❯ ll /home/user/.prysm/validatorprivate* | wc -l
2220
```

maybe we could be more verbose about loading keys?

running prysm latest master @ 3e9bf58d81a986881de9d2d0fcbe565b3fe83ef2

on arch-linux 5.4.13-arch1-1 x86_64 gnu/linux, go version go1.13.6 linux/amd64, bazel version 2.0.0- (@non-git)

**Comment by mcdee** [comment]
Key load time will most likely be dominated by the time taken to decode individual keys, but I'll do some profiling to make sure.  It may be possible to have some sort of bulk store/decrypt, although I'd have to consider how best to build it (and the security implications of having such a thing)

**Comment by q9f** [comment]
5590 seconds / 2220 keys ~ 2.518 seconds per key.

if you could give me a quick pointer, I might be able to help profiling. are the keys encrypted with the password on disk? is this the reason it takes longer to read them?

**Comment by mcdee** [comment]
The relevant code is at https://github.com/prysmaticlabs/prysm/blob/master/validator/keymanager/direct_keystore.go#L75 although that uses the old keystore format; a new keystore (v4) implementation will be integrated in the next few days so you may want to hold off until then.  Even then, though, the majority of the time will be in decryption as each key will be in its own keystore and require decryption separate to the others.

It would be possible to build a different keystore format for bulk keys; this may be where we have to end up to be able to decrypt a significant number of keys quickly (although as mentioned above this could have security implications).

**Comment by q9f** [comment]
first thing coming to my mind is bitcoin's `wallet.dat` which is an encrypted database file of keypairs. downside of such an approach is that all keys use the same password. but if you run all validators on one machine, you probably don't want to use different passwords anyways.

**Comment by mcdee** [comment]
I just tried a test with 4,096 keys with keystorev4 and it imported them in ~11 seconds, so this may not be an issue.  I'll make a note here once the related patch is in, would love to hear your feedback on its performance.

**Comment by q9f** [comment]
ok sure. let me know how to test this.

**Comment by rauljordan** [comment]
Hey @q9f closing for now, as this is resolved in current master thanks to @mcdee , see #4687
