### ISSUE TITLE
--initial-sync-cache-state is not working properly

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4708]
--initial-sync-cache-state is not working properly
crashes at block 11392 on windows & macos

![image](https://user-images.githubusercontent.com/26490734/73599636-d8c3ec00-4545-11ea-9b17-8a83ac275df8.png)

**Comment by rauljordan** [comment]
This was due to a bug in fork choice in tandem with the --initial-sync-cache-state flag. We have since then resolved and our node on master is more resilient with the --proto-array-forkchoice flag.
