### ISSUE TITLE
Update Rewards to Align With Current Spec

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#471]
The spec has updated to include more details about rewards, a PR dealing with this will add the following to the Casper Package
-  `reward_quotient = BASE_REWARD_QUOTIENT * int(sqrt(total_deposits in ETH))`

The reward quotient will specify how the validator would be rewarded are and 1/`reward_quotient` would define the per slot maximum interest rate. 
 
-  `quadratic_penalty_quotient = int(sqrt(SQRT_E_DROP_TIME / SLOT_DURATION))`

If a validator is offline for N slots then the validator would be slashed this amount : (N^2/2)/ `quadratic_penalty_quotient`

-   Adjust participating validator's balances as defined in the spec depending on if `time_since_finality <= 2 * CYCLE_LENGTH`

**Comment by terenc3t** [comment]
We should probably explain how `reward_quotient` and `quadratic_penalty_quotient` are used in this issue

**Comment by nisdas** [comment]
Added some examples above
