### ISSUE TITLE
Add validator prometheus metrics

### ISSUE THREAD

**Issue by garyschulte** [prysmaticlabs/prysm#4723]
It would be helpful for dashboard and alerting if the validator client exposed additional prometheus metrics for validator performance, per public key.  

Useful validator metrics include:
* balances per validator public key
* attestations and failures per public key

Since some validator instances may have many hundreds (or thousands) of validator keys, this behavior should be behind a CLI parameter, with the default behavior to *not* emit validator account metrics

**Comment by somuchid** [comment]
lighthouse has some dashboards can be borrowed: https://github.com/sigp/lighthouse-metrics/tree/master/dashboards

**Comment by garyschulte** [comment]
true, but those dashboards are specific to the metrics that the lighthouse client emits.  This pr adds metrics that one could use to build a prysm-specific validator dashboard

**Comment by prestonvanloon** [comment]
Closing this as it was added in #4724. Thanks!
