### ISSUE TITLE
Archival service fails to return data or serves invalid data for certain epochs

### ISSUE THREAD

**Issue by ppratscher** [prysmaticlabs/prysm#4741]
We still see the following error messages from time to time:

```
time="2020-02-04T06:56:52Z" level=info msg="error retrieving beacon committees response: rpc error: code = NotFound desc = Could not retrieve data for epoch 5684, perhaps --archive in the running beacon node is disabled" module=rpc
time="2020-02-04T06:56:52Z" level=info msg="error retrieving epoch participation statistics: rpc error: code = NotFound desc = Could not retrieve data for epoch 0, perhaps --archive in the running beacon node is disabled" module=rpc
```

This happens usually after restarting a node or during times of finality issues. Unfortunately even after restarting affected nodes we are unable to recover epoch statistics data for certain epochs.

For example around epoch 3017 our node was restarted and now returns a participation rate of 0 for that epoch, but there are around 600 attestations in this epoch.

We use the following rpc call: `GetValidatorParticipation(context.Background(), &ethpb.GetValidatorParticipationRequest{QueryFilter: &ethpb.GetValidatorParticipationRequest_Epoch{Epoch: 3017}})`

see https://beaconcha.in/epoch/3017

https://api.prylabs.net/eth/v1alpha1/validators/participation?epoch=3017 returns the correct data for the epoch.

**Comment by prestonvanloon** [comment]
@terencechain can you confirm this issue will be resolved in new state management? #5185

**Comment by ppratscher** [comment]
Hello,

we are still seeing this issue with the latest client version.
After restarting our node the API returns 0 participation rate for the epoch that was currently active when the node was restarted. You can see it pretty nicely on the chart on our landing page:
![image](https://user-images.githubusercontent.com/1674920/79730033-8e563e00-82f0-11ea-9334-3b698ffb8013.png)

Ever spike means that our node was restarted.

**Comment by nisdas** [comment]
cc @rauljordan 

While our archiver will eventually be deprecated can we do a quick patch to resolve the above error ?

**Comment by terencechain** [comment]
This should be resolved running `-new-state-mgmt` flag
