### ISSUE TITLE
Eliminate All Uses of Proto.Clone From Prysm

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4757]
Proto.clone is an extremely expensive method that we have taken great lengths to avoid in some recent refactors. However, a quick grep in Prysm shows it still being used significantly for various reasons, especially in certain helper functions and cached values in the beacon chain. Now, we have a bunch of custom copy functions in `beacon-chain/state/getters.go` that we can use instead of an expensive, generic, proto.Clone call.

This is a tracking issue for us to use the custom copy functions from `beacon-chain/state/getters.go` instead of proto.Clone throughout the repo.

**Comment by terencechain** [comment]
Assigned to @garyschulte 

Thanks for helping with this one! :)
