### ISSUE TITLE
Add Proposer Validity Rule for Incoming Block

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#477]
Add proposer validation to part of block validity check. From v2.1 spec, to check whether the incoming beacon block has been signed by the correct proposer. We should perform the following check:

1.) Use `parent.slot_number % len(get_indices_for_slot(crystallized_state, parent.slot_number)[0])` to figure out which validator index is the proposer whom also attested for it's own proposed block.

2.) Verify the validator is in one of the `AttestationObject` of the incoming beacon block

**Comment by rawfalafel** [comment]
This is confusing, but the above description won't validate the current block's proposer, only the parent block's proposer.

> In general, when a block is produced, it is broadcasted at the network layer along with the attestation from its proposer.

This means that we need to modify `BeaconBlockRequest` to also include the attestation of the block, and then validate that signature the way its described above.

**Comment by djrtwo** [comment]
The proposer signature needs to be broadcast alongside the proposer's block. The proposer proposes a block at slot N and attests to it. The attestation cannot be included until at least slot N+1.

This is why the following was added to the pre-conditions for processing a block:
> An attestation from the proposer of the block (see later for definition) is included along with the block in the network message object

So I have to first see the proposer's signature floating around before I process the proposer's block.

This somewhat strange notion of validating the parent's proposer signature when validating the child, allows us to not have two different types of signatures in a block (proposer and attester) and lets us instead keep the single (and aggregatable) attestation signature.
