### ISSUE TITLE
API - gRPC internal server error for /blocks?epoch=

### ISSUE THREAD

**Issue by strictlymomo** [prysmaticlabs/prysm#4792]
e.g. `https://api.prylabs.net/eth/v1alpha1/beacon/blocks?epoch=6482` provides a response of

```
 content-length: 0 
 content-type: application/grpc 
 date: Fri, 07 Feb 2020 20:21:18 GMT 
 grpc-message: Internal Server Error 
 grpc-status: 2 
 server: istio-envoy 
 status: 200 
 x-envoy-upstream-service-time: 117 
```

**Comment by prestonvanloon** [comment]
Seems to be an issue in prod. This request works against a local server.

**Comment by prestonvanloon** [comment]
The response might be too large to handle. Still investigating...

**Comment by strictlymomo** [comment]
Attaching some additional data here. Thanks for your help in advance.

![Screen Shot 2020-02-12 at 12 46 01 PM](https://user-images.githubusercontent.com/8671427/74361945-c479bd80-4d95-11ea-8b3e-db8157d153da.png)

**Comment by terencechain** [comment]
Looks like @prestonvanloon has started investigation. Temporarily assigning to him for now

**Comment by prestonvanloon** [comment]
Yeah, this is definitely an infrastructure related problem, not an issue with Prysm itself.

**Comment by rauljordan** [comment]
Almost impossible to diagnose at this point and not too relevant to use as we will no longer expose an API in production
