### ISSUE TITLE
Incorrect values returned for certain epochs using API  ​/eth​/v1alpha1​/validators​/participation

### ISSUE THREAD

**Issue by mtbitcoin** [prysmaticlabs/prysm#4805]
When using the api endpoint (validators/participation/) and with the node fully synched, certain epochs (for example : https://beacon.etherscan.io/epoch/1077) are returning what appears to be an incorrect error message  

"Could not retrieve data for epoch 0, perhaps --archive in the running beacon node is disabled " 

curl -X GET "https://api.prylabs.net/eth/v1alpha1/validators/participation?epoch=1077" -H "accept: application/json"

They should just return zero values instead of the error message above

**Comment by prestonvanloon** [comment]
@terencechain can you take a look at this please?

**Comment by terencechain** [comment]
This will be resolved via #4958 

Retuning zero values is not necessarily correct it'll mean it's supported and it's 0 (no participation), which it's more confusing than "not supported"

I'll close this and defer to #4958, feel free to reopen again if it doesn't resolve when that completes
