### ISSUE TITLE
Initial Sync Cache State Leads to OOMs

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#4813]
Using the ```initial-sync-cache-state``` flags leads to  OOMs when syncing blocks in a period without finality. This is as we cache the relevant fields of each state in a slot. Without finality there is no pruning of states, so all these fields are kept on the heap and leads to the heap size quickly ballooning.

A solution for this would be to handle periods without finality properly and not keep all states in memory.

**Comment by rauljordan** [comment]
Can we close this @nisdas now that we're deleting states after init sync?

**Comment by prestonvanloon** [comment]
I'm not entirely sure this is resolved by #4817. If users are crashing OOM during init sync, then the problem is not resolved by #4817.

**Comment by michaelbryan92** [comment]
This is still happening. My Prysm node crashed while running well after the initial-sync period was over, and upon restarting had to sync the whole beacon chain again.
