### ISSUE TITLE
Create a Meaningful, E2E Demo Of BeaconChain+Validator

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#485]
Hi all,

This is an issue tracking progress towards creating a meaningful demo of our current beacon chain + validator system. Ideally, a user should be able to spin up a beacon node as a validator, connect one or more validator clients to it via RPC, and see meaningful interactions occurring.

Some of the Desired Features Are:
- [x] Initial + Incoming Block Sync
- [x] Validator Shuffling, State Transitions, Validator Being Selected On A Slot/Shard
- [x] Validator P2P Interactions (can all be in the same network for now)
- [x] Beacon Node and Validator Use Internal Clock for Slot Intervals
- [x] Attester Responsibility Implemented
- [x] --dev mode to stub out web3 service and signature verification for local demo
- [x] Stream Validator Assignments via gRPC to Validator Clients
- [x] Give Each Validator a Unique Identifier (PubKey) So We Can Attach 2+ Validators to Beacon Node
- [x] Flag for Different Config Values for Demo (CycleLength, etc.)
- [x] Leverage Simulator for Demo
- [ ] Update Documentation to Clearly Reflect the Demo Functionality

Let's tag this issue in any open PR's or new PR's moving forward. Once we get to the point where we can demo the system locally, we can close this one :).

**Comment by terenc3t** [comment]
Recommending the following parameters for demo:

cycle_length/validators/shards/min_committee_size
5/30/3/3
5/10/3/3
