### ISSUE TITLE
Deprecate BeaconState Protobuf before v0.10 Network Restart

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4868]
Hi all,

Currently our beacon state is a wrapper around an old beacon state protobuf object as we did not want to break backwards compatibility and old chain DB's. In preparation for a network restart, we should deprecate our old beacon state protobuf completely and just use the new state for everything in the beacon chain.

**Comment by prestonvanloon** [comment]
This might complicate database storage as all of our database objects are protobuf messages. One requirement is that ssz.Encode is significantly faster than proto.Marshal.

At the moment, with a generic ssz.Marshal, we could not move forward on this.

```
BenchmarkSszEncoding-8                       424           2569792 ns/op
BenchmarkProtoEncoding-8                   29558             43455 ns/op
```

Marking this as blocked until we have a custom SSZ #4738 and we have updated benchmarks to compare.

**Comment by rauljordan** [comment]
This isn't really important or worth it. We'll likely never get to it so unless it becomes an actual painpoint we can close.
