### ISSUE TITLE
[Mega Tracking] Fuzz test core packages

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#4882]
As part of improving the project resiliency we should fuzz test core package to detect possible panics.

- [x] blocks #4907
- [ ] epoch
- [ ] feed
- [ ] helpers
- [x] state #4883
- [ ] validators

**Comment by prestonvanloon** [comment]
@shayzluf can you give an update? Are the other packages going to be fuzz tested?

**Comment by shayzluf** [comment]
working on slasher as it got priority. will get back to add more fuzzing tests next week

**Comment by rauljordan** [comment]
Can we consolidate this and #1930 into a single tracking issue for fuzzing that serves as our single source of truth with checkboxes? Kindly triage when you have a chance @shayzluf, then we can close both of these issues.

**Comment by shayzluf** [comment]
we can consolidate this and #1930 @rauljordan

**Comment by rauljordan** [comment]
@prestonvanloon regarding fuzzing work: how does this issue relate to your latest work? Is it resolved or still requires triage?
