### ISSUE TITLE
Make `--gc-percent=x` adapt dynamically

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4885]
Memory spikes usually occur when syncing blocks without finality - where gc percent is required. 
Would be a nice feature if gc percent adapts dynamically during these blocks (e.g 100->10)

**Comment by prestonvanloon** [comment]
@nisdas is this feasible?

**Comment by nisdas** [comment]
It is feasible, but we would need to design this carefully as this could have have pretty negative consequences if it goes wrong. Also I would prefer to make our code better and handle/eliminate memory spikes altogether rather than go this way.

**Comment by rauljordan** [comment]
This indeed has a lot of risk, and it is a much better approach to handle memory usage through better programming than relying on GC this way, closing unless there is good support otherwise
