### ISSUE TITLE
Tracking: Troubleshooting tips for documentation

### ISSUE THREAD

**Issue by har00ga** [prysmaticlabs/prysm#4891]
Hey folks,

This is a tracker issue to maintain an ongoing list of problems that users frequently run into while setting up Prysm and its related tooling. The aim is to compile them into 'Troubleshooting' and 'Useful tips' pages in the [documentation portal](https://docs.prylabs.network) and hopefully simplify the process of finding answers for repeat questions.

I'll be going through tickets today to make note of obvious ones and will upload it here when done. Feel free to contribute to this list with problems you've experienced (and optionally the solution you found) to have them added to the below table, and we will do our best to make sure they are integrated to the doc portal in a meaningful way. :slightly_smiling_face: 

| # | Issue | Solution |
|---|:--------|:-----------|
| 1 | - | - |

**Comment by prestonvanloon** [comment]
Any update on this?

**Comment by rauljordan** [comment]
Closing and moving to the docs repo
