### ISSUE TITLE
Multi-Arch docker images

### ISSUE THREAD

**Issue by torfbolt** [prysmaticlabs/prysm#4900]
It would be great if the automatic docker build process could be expanded for multi-arch images, something like this:
https://www.docker.com/blog/multi-arch-images/

This way people with ARM machines could use the latest client versions and help testing the bleeding edge.

**Comment by prestonvanloon** [comment]
We're providing precompiled binaries with every release starting with tag v0.3.2.

Building ARM images should work with the following command
```
DOCKER_TAG=latest-arm64 ./bazel.sh run --config=release --config=linux_arm64_docker //beacon-chain:image_bundle
```

**Comment by prestonvanloon** [comment]
Actually, I just tried the above command and the result was 
```
ERROR: /home/preston/git/prysm/tools/BUILD.bazel:41:1: PackageTar tools/passwd_tar.tar failed (Exit 127) build_tar failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile bazel-out/aarch64-fastbuild/bin/tools/passwd_tar.args

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/env: 'python': No such file or directory
Target //beacon-chain:image_bundle failed to build
```

In any case, you could copy the release files into an ARM64 based image and that would satisfy the use case I think. 

I'll leave this open now to consider adding this automatically in our continuous integration pipeline.

**Comment by prestonvanloon** [comment]
@torfbolt we provide multiarch binaries now as a recommended installation for ARM.

I'll close this for now, thanks for the report!

**Comment by prestonvanloon** [comment]
Revisiting this issue to properly provide multiarch docker images.
