### ISSUE TITLE
Invalid activation epoch calculation 

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#4923]
Hi,

It looks like there is a problem with `activation_epoch` calculation when running with `--minimal-config`. Its Unix timestamp is behind `inclusion_slot` timestamp when the validator is in `PENDING` status. As soon as the validator moves to `ACTIVE` status, its `activation_epoch` is set correctly.

I've seen that issue in [#4623](https://github.com/prysmaticlabs/prysm/issues/4623#issuecomment-578329259) and thought the cause was fixed, but seems like it still persists.

### Environment:
Beacon chain, validator commit: `597b21c`
Config: `minimal`

**Comment by rauljordan** [comment]
Assigning @0xKiwi to this provisionally as it interacts with the validator activation code

**Comment by prestonvanloon** [comment]
@0xKiwi any update on this?

**Comment by 0xKiwi** [comment]
@prestonvanloon not entirely sure if I can find the problem, would help to see the logs.
We get the activation epoch from state so its most likely our inclusion slot estimate is not accurate for minimal config. 
Can you replicate this issue? @tsudmi

**Comment by tsudmi** [comment]
Hi @0xKiwi ,

Yes, I can still catch the error:
```python
        if validator.activated_at < validator.included_at:
            logger.warning(f'Received invalid activation time for validator={validator}:'
                           f' included_at={str(validator.included_at)}, activated_at={str(validator.activated_at)}')
            return
```
It prints:
```bash
Received invalid activation time for validator=0x59ca1b12742897b9d8: included_at=2020-05-04 12:40:00+00:00, activated_at=2020-05-04 12:39:12+00:00
```
Commit: `af5b92`

**Comment by terencechain** [comment]
@tsudmi let's check if this still exist in Onyx (in a few days)

**Comment by rauljordan** [comment]
Hi @tsudmi could you kindly confirm if this is still an issue for you?

**Comment by tsudmi** [comment]
Hi @rauljordan , I was only getting it when running with minimal config, but haven't checked whether it was fixed since Onyx.
Let's close it for now and once I will have a chance to run with minimal config again, I will check whether I could still reproduce.
