### ISSUE TITLE
Validator log: inclusion_slot + inclusion_distance incorrect

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#4935]
Two issues with the new voting summary in the validator log.

**Issue one (where correctlyVotedHead=true)**
InclusionSlot seems wrong. The inclusionSlot does not match the "calculation": inclusion slot - assigned slot = distance as provided by @terencechain in a discord chat.
The value of the inclusionSlot is from 'some' previous epoch.
326077-326127= -50  (!=1)
An inclusion cannot take place prior to an assignment.
 
<img width="1473" alt="2020-02-24_08-22-37" src="https://user-images.githubusercontent.com/28559038/75135126-d554f800-56e0-11ea-8ec5-ef60cb6cc07a.png">

**Issue two (where correctlyVotedHead=false)**   
In case the attestation was missed, the fields for inclusionSlot and inclusionDistance contain some "big wild " number. (value of 0 would probably make more sense)
<img width="1658" alt="2020-02-24_08-31-29" src="https://user-images.githubusercontent.com/28559038/75135179-00d7e280-56e1-11ea-92c8-54219af08d3d.png">

Git commit: 6fe86a3b30829d4d013a3b94d01a2c80d1ead324. Built at: 2020-02-22 15:32:42+00:00

**Comment by terencechain** [comment]
issue 2 is fine. 0 would not make more sense since it refers to genesis slot hence we refer to use max int for missed.

**Comment by terencechain** [comment]
issue 1 is something to look at and it seems cosmetic at first glance

**Comment by rauljordan** [comment]
@handelaar2 do you still observe this issue?

**Comment by handelaar2** [comment]
Yes
<img width="1280" alt="2020-04-15_08-11-26" src="https://user-images.githubusercontent.com/28559038/79304340-69795980-7ef1-11ea-83ae-d2686313a6d5.png">

**Comment by 0xKiwi** [comment]
Any updates on this issue? @farazdagi

**Comment by dv8silencer** [comment]
This this is flagged with Help Wanted so I was taking a look.  I just looked at my validator and I'm not having this issue though I only spent like five minutes looking.  If you are still having this issue, how can I reproduce it?  Thanks

**Comment by handelaar2** [comment]
It seems to me the issue is no longer there (meanwhile checking Onyx). The inclusion slot and inclusion distance do match the assignment slot now.
