### ISSUE TITLE
Add Block Default Fields for NewGenesisBlock

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#495]
**Requirements**
In [Block.NewGenesisBlock](https://github.com/prysmaticlabs/prysm/blob/9639161fccd503dfd7bdfc0eb43570294dcdd889/beacon-chain/types/block.go#L50) , initialize `CrystallizedStateHash` and `ActiveStateHash`. Crystallized state and Active state are created at the same time, so you can simply derive the hash from the object itself.

**Readings**
[2.1 spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view)

**Comment by rawfalafel** [comment]
The four fields missing are `RandaoReveal`, `PowChainRef`, `ActiveStateHash`, and `CrystallizedStateHash`. Maybe this issue should simply be to fill the last two since fields?

**Comment by danielschonfeld** [comment]
should this be closed?

**Comment by rawfalafel** [comment]
still looks relevant to me. description updated!

**Comment by rauljordan** [comment]
Closed by #518
