### ISSUE TITLE
Tracking: Delete deprecated SubmitAggregateAndProof

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#4952]
PR #4951 deprecates the old SubmitAggregateAndProof aggregator RPC.

This old method should be deleted at a later date after validator clients have stopped using it.

**Comment by terencechain** [comment]
Can this be closed? @prestonvanloon

**Comment by prestonvanloon** [comment]
No, still needs to be deleted

**Comment by prestonvanloon** [comment]
The new method has been implemented for 3 weeks and multiple releases. I think it's safe to delete the old method now. I'll start on that
