### ISSUE TITLE
Beacon stuck processing same slot

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#4964]
Using Latest: 
 af5cc31565629f3e766b11caf7d8a7560d6c8901. Built at: 2020-02-28 01:28:46+00:00

running with following feature flags:
--enable-ssz-cache 
--enable-byte-mempool 

<img width="1660" alt="2020-02-28_15-22-13" src="https://user-images.githubusercontent.com/28559038/75557965-50037780-5a41-11ea-9922-c891ea354168.png">

The Beacon got stuck processing slot 357060.
After trying the same slot for more than half an hour (14:12 till 14:39), initial-sync "takes over".
[@ 14:38:40]

[beacon.log](https://github.com/prysmaticlabs/prysm/files/4267565/beacon.log)  <====

**Comment by handelaar2** [comment]
Also happens with commit: a07e604eeacc9dd95705318fd92a1c7b5a2a1b42

<img width="1652" alt="2020-03-03_11-09-02" src="https://user-images.githubusercontent.com/28559038/75765218-7413d100-5d3f-11ea-98e9-827c9c0cfa18.png">

**Comment by handelaar2** [comment]
The same happened today with commit: 5961aaf588e2037164a236d744ebdf3a6774ed24. Built at: 2020-03-05 07:37:28+00:00
Active flags:
--enable-ssz-cache
--enable-byte-mempool
--check-head-state

<img width="1633" alt="2020-03-05_15-13-57" src="https://user-images.githubusercontent.com/28559038/75989870-4c199e80-5ef4-11ea-8ca5-ea900ca1fba0.png">

(This time, slot 400159)

**Comment by prestonvanloon** [comment]
Looks like `--enable-ssz-cache` is still causing issues. 

@rauljordan, what do you think?

**Comment by handelaar2** [comment]
Same happened again today with commit: 01cb01a8f26c36a7216855c483789f403c376160. Built at: 2020-03-09 05:39:28+00:00

Active flags:
--enable-ssz-cache
--enable-byte-mempool
--check-head-state

<img width="1628" alt="2020-03-09_12-59-47" src="https://user-images.githubusercontent.com/28559038/76211187-edab3380-6205-11ea-86c7-f06076559b7d.png">

(This time slot 428291)

**Comment by handelaar2** [comment]
Same happened again today with commit: 8d3fc1ad3ecf5457bb03621f2bbf50022cfd9d65. Built at: 2020-03-10 20:03:46+00:00
Active flags:
--enable-ssz-cache
--enable-byte-mempool
--check-head-state

<img width="1646" alt="2020-03-11_09-55-56" src="https://user-images.githubusercontent.com/28559038/76399228-9086bd80-637e-11ea-843e-30027211280c.png">

(This time, slot 441829)

Any solution in sight?

**Comment by nisdas** [comment]
@handelaar2 can you try running the node without this ?
```
--enable-ssz-cache
```

**Comment by nisdas** [comment]
Ah actually I think it might be this one 
```
--check-head-state
```
please run without this flag. I will look into it tomorrow, there are certain times it fails

**Comment by handelaar2** [comment]
it is unlike that it is --check-head-state
When I started seeing this behaviour, that flag did not exist (see initial post of this issue)

I will take out the ssz-cache flag now and see if the error returns. (And see if I can run at all without that szz-cash flag)

**Comment by handelaar2** [comment]
I ran the beacon 3 days **without** the --enable-ssz-cache flag. The error did not occur once.

Today I put back the enable-ssz-cache flag, and the error came back right away.
(I put the flag back because without it my CPU has problems keeping up)

<img width="1667" alt="2020-03-14_12-23-00" src="https://user-images.githubusercontent.com/28559038/76681040-aac6d280-65ee-11ea-9140-0847fc27d882.png">

commit: 1f87cb11fc1eba03bf9fdf4aa50a22c1cd276cfd. Built at: 2020-03-14 03:37:37+00:00

So it is confirmed this #issue occurs due to a bug in the ssz-cache (including the latest commit).

**Comment by terencechain** [comment]
cc @rauljordan

**Comment by prestonvanloon** [comment]
This should be resolved by #5364 which has fixed a race condition in the ssz cache. Please pull in the latest master branch or latest docker image and let us know if it's still an issue please.

**Comment by rauljordan** [comment]
This is now resolved by our ssz cache fixes which are now live in latest master by default
