### ISSUE TITLE
Show overall validator results instead of epoch specific

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#4987]
![image](https://user-images.githubusercontent.com/26490734/75759878-90f7d680-5d36-11ea-9cb5-04870804b289.png)

**Comment by terencechain** [comment]
I think we can show one for previous epoch and one for progression since starting up. Prev epoch stats is still useful imo

**Comment by prestonvanloon** [comment]
Assigning to @terencechain for now. 

@terencechain please triage appropriately.

**Comment by terencechain** [comment]
Since this is a "fun" one and does not require much code knowledge, I will like to ask community's help and I will provide full guidance for support. 

Any takers?

**Comment by dv8silencer** [comment]
I will try.
