### ISSUE TITLE
"Has No Symbols" Flooded Travis Test Log

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#499]
The entire log is flooded with complains of darwin_amd64_race's cgo libs have no symbols.

Log: https://travis-ci.org/prysmaticlabs/prysm/jobs/427326631

**Comment by prestonvanloon** [comment]
This is probably (definitely) caused by dependencies in go-ethereum, we'd need to update bazel-go-ethereum and it may be hard to merge in upstream changes if we deviate too much. Although maybe it's just some flag configuration for gcc. Not sure!

**Comment by rauljordan** [comment]
No longer relevant as we are using buildkite instead - travis is only there for cov and linting
