### ISSUE TITLE
Validator balance metrics misattributed by key

### ISSUE THREAD

**Issue by SuburbanDad** [prysmaticlabs/prysm#5014]
I have noticed a sawtooth pattern in the validator balances chart in my local grafana.  It looks like balances are being misattributed by key in the logs and metrics.  When you have balances that are significantly different, what ends up happening is a sawtooth chart that looks something like this:
<img width="417" alt="Screen Shot 2020-03-05 at 8 30 21 AM" src="https://user-images.githubusercontent.com/61096102/76002583-b06c3c00-5ebb-11ea-9ba5-289fb6cff965.png">

or when you have balances that are closer together, you get the same pattern but tighter:
<img width="416" alt="Screen Shot 2020-03-05 at 8 30 49 AM" src="https://user-images.githubusercontent.com/61096102/76002642-c679fc80-5ebb-11ea-8bf1-bfa477095167.png">

After confirming that the prometheus metrics match the log lines, it appears we are misattributing balances either in the response from the beacon chain or in the emitting of the metrics and log lines in the validator

**Comment by SuburbanDad** [comment]
This behavior became quite apparent on 2/29 when I made an additional deposit so I could have a validator with an effective balance of 3.2.  Note: there is only one pub key with an effective balance over 3.2:

<img width="1756" alt="Screen Shot 2020-03-05 at 8 39 38 AM" src="https://user-images.githubusercontent.com/61096102/76003580-1d340600-5ebd-11ea-97d0-0283979861ed.png">

**Comment by terencechain** [comment]
Asked on discord but also posting here and it doesn't get lost:
https://discordapp.com/channels/476244492043812875/476588476393848832/685180034323054695

**Comment by SuburbanDad** [comment]
This issue appears to be fixed by  #4968
