### ISSUE TITLE
Validator Management Contract: Pubkey Should Be 64 bytes

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#502]
Ethereum public keys are 64 bytes so the contract should accept an input of 64 bytes for the deposit parameter type. 

Also see: https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#PoW-main-chain-changes

**Comment by prestonvanloon** [comment]
Also see ValidatorRecord here: https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ#Beacon-chain

In this definition, it is `int256`. So we may need to confirm what type it should be.

**Comment by terenc3t** [comment]
If it's `int256` then pub key should be 32 bytes.
To clarify, we are not going to use current ethereum public keys for beacon chain/shard chains. We'll generate a new public key. This new public key would be 32 bytes and the signature scheme is still TBD. I'll make sure to bring this up during thurs meeting.

**Comment by prestonvanloon** [comment]
@terenc3t sounds good. Let's close this.

Please reopen if necessary. Thanks!
