### ISSUE TITLE
Feature flag cleanup for mainnet release

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5022]
As part of the next testnet restart, let's clean up and remove any deprecated feature flags.

**Comment by prestonvanloon** [comment]
As of #4878 we are no longer displaying deprecated flags in the help text. Given that these deprecated flags are no longer extremely annoying, I'm removing from testnet restart milestone and changing this to mainnet / v1 requirement.

**Comment by rauljordan** [comment]
Closing in favor of https://github.com/prysmaticlabs/prysm/issues/7509
