### ISSUE TITLE
Provide Aggregated/Unaggregated Attestations from Pool to RPC Stream Indexed Attestations

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5031]
Hi all,

Currently in #5029 we aggregate attestations we receive via RPC and then broadcast them to the slasher. In parallel, our attestation pool does the same aggregation routine in the background elsewhere in the node runtime. This redundancy is inefficient given the aggregation algorithm is slow. Ideally, we can remove the logic from rpc `StreamIndexedAttestations` and instead use the aggregated attestations in the attestation pool itself. One requirement is that slasher _also_ wants unaggregated attestations, not only aggregated ones. Slasher needs _everything_, it can't miss any information.

- [ ] send p2p aggregated attestations to slasher #5809
- [ ] send pool aggregated/ unaggregated attestations to slasher 
- [ ] remove indexed attestations stream redundant aggregation flow

**Comment by rauljordan** [comment]
Assigning to @shayzluf provisionally

**Comment by shayzluf** [comment]
thanks @rauljordan i am on it

**Comment by rauljordan** [comment]
Any update on this one @shayzluf ?

**Comment by shayzluf** [comment]
just created a pr that seems to resolve it @rauljordan please take a look

**Comment by rauljordan** [comment]
Slasher really needs _every_ attestation from the beacon node, both aggregate and unaggregated. If we just provided the atts from the attpool service, we'd just be feeding slasher aggregate attestations and missing some. For now, the current solution achieves the required goals. Closing this issue unless it's apparent that we _need_ to do this.
