### ISSUE TITLE
Balance decreasing

### ISSUE THREAD

**Issue by GuillaumeOcculy** [prysmaticlabs/prysm#5051]
Is there a reason why my balance is decreasing?

```go
INFO validator: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=13398 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=3.040461875 oldBalance=3.040473767 percentChange=-0.00039% pubKey=0x92612e5ca5ad9ca0
```

**Comment by prestonvanloon** [comment]
Thanks for the report.

The most common reasons for balance decreasing is 
- There hasn't been a finalized epoch (everyone gets penalized slightly)
- Your attestation was not received and/or included by a block proposer.

We are working on improving aggregation strategies and profitability in this testnet. 

I'll close this issue for now as the last few weeks have seen major progress towards validator profitability and stability.
