### ISSUE TITLE
status=UNKNOWN_STATUS should show "ETH1 DEPOSIT RECEIVED" when appropriate

### ISSUE THREAD

**Issue by superphiz** [prysmaticlabs/prysm#5059]
UNKNOWN_STATUS is extremely vague and is certain to cause a lot of turmoil in the minds of new stakers when we go live. Showing that an Eth1 deposit has been received before the validator is pending inclusion will enhance the quality of the product in the minds of end users. There may be other appropriate status updates that could be included.

**Comment by prestonvanloon** [comment]
Good point that UNKNOWN is a bit concerning. It simply means that the status was not set.

We should look into adding or fixing eth1 deposit received. We should be returning a status to indicate that the beacon node has seen the eth1 deposit. 

We could also display "Awaiting deposit" or something along those lines if the deposit has not been observed in eth1 deposit contract.

**Comment by rauljordan** [comment]
Assigning to @0xKiwi as this is part fo the validator activation process in the client

**Comment by 0xKiwi** [comment]
I intend to make some larger scale logging improvements for validator status after #5396 is merged. Have you tried a new validator deposit within the last few days @superphiz ?

**Comment by 0xKiwi** [comment]
I intend to make some larger scale logging improvements for validator status after #5396 is merged. Have you tried a new validator deposit within the last few days @superphiz ?

**Comment by 0xKiwi** [comment]
I intend to make some larger scale logging improvements for validator status after #5396 is merged. Have you tried a new validator deposit within the last few days @superphiz ?
