### ISSUE TITLE
Allow Multiple Proposal Slots in an Epoch

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5065]
Currently is is assumed that a validator will only have a single proposal slot in an epoch, however due to the fact that proposal slots are computed in on a per slot basis, there is the possibility that a validator could have multiple proposal slots in an epoch instead of once. This issue is to track the implementation of the required changes for this. We will need to modify our ethereum-api and the relevant code in prysm

**Comment by rauljordan** [comment]
Done in EthereumAPIs here https://github.com/prysmaticlabs/ethereumapis/pull/121

**Comment by rauljordan** [comment]
Now working on the Prysm-side
