### ISSUE TITLE
slasher get attestation gets disconnected on error

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5091]
error like `[2020-03-13 17:39:47] ERROR beaconclient: Could not receive attestations from beacon node error=rpc error: code = Internal desc = Could not retrieve committees for epoch 14289: rpc error: code = InvalidArgument desc = Cannot retrieve information about an epoch in the future, current epoch 14288, requesting 14289` 
cause the slasher rpc connection to stop

**Comment by terencechain** [comment]
Please close issues after merge!
