### ISSUE TITLE
My node on Hetzner got put on notice for abuse

### ISSUE THREAD

**Issue by ghost** [prysmaticlabs/prysm#5138]
Hi guys, 
I'm running the latest master (built yesterday) and just today Hetzner has put the server on notice for abuse. It's a fresh install dedicated node with only the beacon and validators running. Here is the log they sent. Not sure if this is where to report, but maybe this may be of interest here. 
I'm hoping that it's a false positive? Or something misconfigured?

Here is the abuse report in a gist
https://gist.github.com/convid-19/877876ebb83fe2a3e384ad92195f7099#file-abuse-report

**Comment by mcdee** [comment]
You will need to configure your firewall to stop outgoing connections to private networks.  Something like:

```
ufw deny out to 10.0.0.0/8 comment "Block connection requests to private networks"
ufw deny out to 172.16.0.0/12 comment "Block connection requests to private networks"
ufw deny out to 192.168.0.0/16 comment "Block connection requests to private networks"
ufw deny out to 169.254.0.0/16 comment "Block connection requests to link local networks"
```

ufw will probably require more configuration than this.

**Comment by convid-19** [comment]
Thank you! Will try that.

**Comment by prestonvanloon** [comment]
Hey @convid-19 is there anything else actionable in this issue?

**Comment by convid-19** [comment]
@prestonvanloon after applying the firewall rules, my validators are running and I'm not receiving any new complaints from Hetzner. Thank you.

This is a throwaway account, so I'll be riding off in to the sunset on my unicorn now... Yeehaa 🤠🦄
