### ISSUE TITLE
Could not receive attestation in chain service 

### ISSUE THREAD

**Issue by cleanunicorn** [prysmaticlabs/prysm#5164]
Operating system: Arch
```console
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

Running `beacon-chain` image in docker, latest image.
```console
$ docker image
gcr.io/prysmaticlabs/prysm/beacon-chain   latest              94bac9528587        50 years ago        60.1MB
```

Error message.

```
[2020-03-22 10:23:00]  WARN blockchain: Could not receive attestation in chain service aggregationCount=1 beaconBlockRoot=0xdaf35eb52bbb committeeIndex=4 error=could not process attestation for future block, 521509 > 521508
could not verify attestation beacon block
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).onAttestation
	beacon-chain/blockchain/process_attestation.go:107
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:36
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
	beacon-chain/blockchain/receive_attestation.go:113
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373
could not process attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:38
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
	beacon-chain/blockchain/receive_attestation.go:113
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 slot=521508 targetRoot=0x6e69e84e7997
[2020-03-22 10:23:00]  INFO blockchain: Finished applying state transition attestations=128 attesterSlashings=0 deposits=0 slot=521514
```

It recovered automatically, it kept going after outputting the error.

**Comment by prestonvanloon** [comment]
Looks like you received an attestation 1 second early.

There are two possible causes:
1. Your clock is wrong
1. Someone else's clock is wrong.

Thinking about this error and the concern that it brings to the user, maybe we can suppress this warning and simply delay processing for 1 second. We already have a minor tolerance enabled for time based assertions and this might be a rounding error. Looking into this now...

**Comment by prestonvanloon** [comment]
Another quick note, this attestation would _not_ have been re-processed in current master. 
The attestation you saw was dropped from your pool on failure.

**Comment by prestonvanloon** [comment]
After some more investigation. This issue is not a clock based problem. The error message is printing slots, not time.

I have a fix in progress that includes
- Improving the error message
- Preventing this issue by selecting the correct prior state for attestation data

Thanks for bringing this issue up, it's actually a bit of a big deal in some cases!
