### ISSUE TITLE
CORS headers on API

### ISSUE THREAD

**Issue by morrigan** [prysmaticlabs/prysm#5175]
Hi,

seems like [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers are not configurable on API. Not sure about other setup but I am using API with enabled gRPC gateway for JSON requests.

This is a required for all cases, either running API on another host or same host with different port. More precisely, `Access-Control-Allow-Origin` is required to be configurable.

**Comment by prestonvanloon** [comment]
I'll add a flag `--grpc-gateway-corsdomain` that will accept a comma separated list of domains to accept cross origin requests.
