### ISSUE TITLE
Verify all attestations in initial sync

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5176]
Currently, we do not verify all attestations before the finalized checkpoint unless using feature flag `--initial-sync-verify-all-signatures`.

**Comment by terencechain** [comment]
Something to look into on solving BLS bottlenecks during initial sync:
https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407/7

**Comment by terencechain** [comment]
Unless I'm missing something, we do verify all attestations signatures and even block signature unless `--initial-sync-no-verify` is specified.  Which we haven't used in a while

See: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/sync/initial-sync-old/round_robin.go#L224

**Comment by prestonvanloon** [comment]
@terencechain please close if this is not relevant.

**Comment by terencechain** [comment]
Correct my previous statement, we dont verify att sigs.  See:
<img width="1830" alt="Screen Shot 2020-03-29 at 12 30 13 PM" src="https://user-images.githubusercontent.com/21316537/78174493-3376a880-740e-11ea-9d94-df467aa73e07.png">

Marking this as need help for now

**Comment by prestonvanloon** [comment]
This isn't a hard requirement for testnet restart. Removing from testnet requirement to mainnet requirement.

**Comment by nisdas** [comment]
Before going forward with this we will need the ability to verify multiple signatures quickly:
https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407/7

Enabling will cause a large degradation in performance, with sync speeds dropping by 95%.

**Comment by prestonvanloon** [comment]
Bumping priority for this as this is a potential security vulnerability.

**Comment by prestonvanloon** [comment]
In the current code, enabling this functionality still reduces sync speed by about 90%. From 70bps to 6.5bps. 

Looking at how we can verify multiple signatures quickly via the links in previous comments.

**Comment by terencechain** [comment]
What else is left preventing us to close this? 

I think any follow up optimizations should just have its own issue

**Comment by nisdas** [comment]
+ 1, I think this issue can be closed now.
