### ISSUE TITLE
Make state mgmt service an implementation as DB

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5185]
Currently the new state mgmt service is implemented as a wrapper on top of DB, it's implemented as a service because it does service-like thing (ie. replay blocks, execute state transitions) @prestonvanloon brought a good point the new mgmt service should be an implementation as DB for better UX.

The easier to reason DB is the universal way on how users access state throughout the application. With DB still public, having two ways to access states means that it could the code and logic complicated

**Comment by rauljordan** [comment]
Hi @terencechain can we close this one?

**Comment by terencechain** [comment]
This is to bundle new state mgmt service to db layer to reduce disparity. Given a user can current do

`stateGen.StatebyRoot` and `db.State`

**Comment by rauljordan** [comment]
Update on this @terencechain ?

**Comment by terencechain** [comment]
Yeah let's keep this open

**Comment by terencechain** [comment]
Shifting priorities, i dont think we'll get to this before mainnet. Will reopen when the timing is acceptable
