### ISSUE TITLE
Migrate boltdb to bbolt

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5186]
BoltDB is deprecated and we've hit our first issue after upgrading to go 1.14. As time goes on, more of these issues will appear so we should migrate to an alternative as soon as possible.

etcd maintains a fork of bbolt which has the fix for go 1.14 above. 
https://github.com/etcd-io/bbolt

Specific fix https://github.com/etcd-io/bbolt/pull/201

This should be a drop in replacement for boltdb.

**Comment by nisdas** [comment]
This can be a drop in replacement but we might need to fork our metrics collector as it only supports the original boltdb. At least that was the blocker the last time I tried using the etcd fork

**Comment by prestonvanloon** [comment]
Good point. We can fork the metrics collector and drop in bbolt there as well.
