### ISSUE TITLE
DB: Replace Proto Marshaller with SSZ Marshaller

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5188]
As of our latest state benchmarks now utilising the `fast_ssz` library, 
```
BenchmarkMarshalState_FullStateProto/proto-8        1000           4158728 ns/op         5210114 B/op          3 allocs/op
BenchmarkMarshalState_FullStateProto/fast_ssz
BenchmarkMarshalState_FullStateProto/fast_ssz-8                     1000           3468476 ns/op         4849664 B/op          1 allocs/op
```
```
BenchmarkUnmarshalState_FullState/Proto_Unmarshal
BenchmarkUnmarshalState_FullState/Proto_Unmarshal-8                 1000          13735450 ns/op        17919463 B/op     133409 allocs/op
BenchmarkUnmarshalState_FullState/Fast_SSZ_Unmarshal
BenchmarkUnmarshalState_FullState/Fast_SSZ_Unmarshal-8              1000           8812379 ns/op         8445362 B/op     133303 allocs/op
```
There is a sizable improvement especially in unmarshal. Given the node is read heavy, with us reading the state much more often than writing to it, this will have a sizeable improvement in the performance of our node.

This issue is to track the replacement of replacing the encoder with ssz instead of protobufs in our db.

**Comment by prestonvanloon** [comment]
Note: this is a breaking change and must not merge directly to master except through the v0.11 branch.

**Comment by prestonvanloon** [comment]
Assigning to @nisdas. I noticed you were working on this in some branch already.

**Comment by prestonvanloon** [comment]
I'll take a look at this as well. It shouldn't be too difficult to require this change.
