### ISSUE TITLE
Respond canonical blocks for BeaconBlocksByRange for non-finalized block range

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5196]
As specified in [network spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#beaconblocksbyrange) for proper respond to `BeaconBlocksByRange` message: 

> Requests count beacon blocks from the peer starting from start_slot, leading up to the current head block as selected by fork choice. step defines the slot increment between blocks. 

Current a Prysm node will respond blocks that include non-canonical one without selected by forkchoice. 

```go
for i, b := range blks {
	blk := b.Block
	isRequestedSlotStep := (blk.Slot-startSlot)%m.Step == 0
	isRecentUnfinalizedSlot := blk.Slot >= helpers.StartSlot(checkpoint.Epoch+1) || checkpoint.Epoch == 0
	if isRequestedSlotStep && (isRecentUnfinalizedSlot || r.db.IsFinalizedBlock(ctx, roots[i])) {
		if err := r.chunkWriter(stream, b); err != nil {
			log.WithError(err).Error("Failed to send a chunked response")
			return err
			}
		}
	}
```

**Comment by prestonvanloon** [comment]
Just a note on this, we currently return canonical _finalized_ blocks. 
After the most recent finalized checkpoint, we just return whatever we blocks we know about.

**Comment by terencechain** [comment]
We only return ~~canonical~~ finalized blocks. We don't return blocks filtered canonical / fork choice.

```
315 ---- 317 ---- 319 ---- 320 (finalized) ---- 321
    \-316-----318
```

Instead of returning `[320, 319, 317, 315]`, we return `[320, 319, 318, 317, 316, 315]`. Unless I miss something while inspecting the code

**Comment by terencechain** [comment]
My previous comment was incorrect, we do return canonical finalized blocks here https://github.com/prysmaticlabs/prysm/pull/3873/files

Thanks @prestonvanloon for linking the page

**Comment by terencechain** [comment]
Need to implement https://github.com/ethereum/eth2.0-specs/pull/1795/files

**Comment by rauljordan** [comment]
Update on this @terencechain ?

**Comment by nisdas** [comment]
Hey this is already done in `v0.12`  @rauljordan #5955

**Comment by terencechain** [comment]
Nishant is right
