### ISSUE TITLE
Docs: Life of a Transaction in Sharding: Diagram

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#52]
Add flowchart or some graphic to illustrate the life of a transaction in a sharded system.

**Comment by prestonvanloon** [comment]
I think the infographic is a good example: https://www.icloud.com/keynote/05Q0CUa8WRPrvPx0tVgLTri_A#Ethereum_Sharding_Infographic

Specifically section 8. What's missing here is the process by which proposer collect and manage transactions. It would be helpful to visualize p2p communication from Ethereum user to packaged collation.

**Comment by terenc3t** [comment]
Is the infographic good enough to use and to close this issue? I can help with this if anything is needed

**Comment by prestonvanloon** [comment]
I'd like to keep this open until p2p is more defined

**Comment by rauljordan** [comment]
Should we close this? We are super far away from figuring out what shard tx's will look like - just trying to clean up our issue count a bit.

**Comment by nisdas** [comment]
@prestonvanloon Is this still relevant ? seems like this will be pretty far way for us

**Comment by prestonvanloon** [comment]
Yes

**Comment by prestonvanloon** [comment]
This isn't relevant until phase 2 so let's go ahead and close this until we need it. Backlog is growing too large.
