### ISSUE TITLE
Docker client on Linux appears to run out of memory during sync

### ISSUE THREAD

**Issue by mjackson001** [prysmaticlabs/prysm#5210]
This error is happening every couple of hours trying to sync a new node using the docker client on Ubuntu Linux

[2020-03-25 19:14:29] INFO initial-sync: Processing block 390429/545772 - estimated time remaining 5h23m37s blocksPerSecond=8.0 peers=15/22
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x16f4536, 0x16)
GOROOT/src/runtime/panic.go:1112 +0x72
runtime.sysMap(0xc1b4000000, 0x4000000, 0x273bc58)
GOROOT/src/runtime/mem_linux.go:169 +0xc5
runtime.(mheap).sysAlloc(0x2723b60, 0xc00000, 0x2723b68, 0x49e)
GOROOT/src/runtime/malloc.go:715 +0x1cd
runtime.(mheap).grow(0x2723b60, 0x49e, 0x0)
GOROOT/src/runtime/mheap.go:1286 +0x11c
runtime.(mheap).allocSpan(0x2723b60, 0x49e, 0x100, 0x273bc68, 0x435d76)
GOROOT/src/runtime/mheap.go:1124 +0x6a0
runtime.(mheap).alloc.func1()
GOROOT/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x2723b60, 0x49e, 0x7f9f81160101, 0x447c20)
GOROOT/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x93a0d8, 0x480101, 0xc08b292000)
GOROOT/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()

**Comment by prestonvanloon** [comment]
Discussed on discord to try the experimental memory management via flag `--enable-byte-mempool`.

**Comment by prestonvanloon** [comment]
Closing in favor of https://github.com/prysmaticlabs/prysm/issues/4970
