### ISSUE TITLE
Save State Metadata in the DB

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5216]
Currently we re-generate the field tries everytime we retrieve a state from the db. This can be expensive to do consistently as retrieving the data from the db would be faster than recomputing it again. This issue is to explore the possiblility and any potential issue that may arise from saving a state's metadata(fieldTries, merke layers,etc) in the db and using that instead.

**Comment by prestonvanloon** [comment]
I'll take a look at this

**Comment by rauljordan** [comment]
Update on this @prestonvanloon ?

**Comment by prestonvanloon** [comment]
No update yet. This won't get prioritized until after v0.11 testnet.

**Comment by prestonvanloon** [comment]
Oops. I forgot about this feature... It will have to be worked on after mainnet v1.

**Comment by nisdas** [comment]
I think there is very little benefit to this, so closing the issue now unless you feel otherwise @prestonvanloon
