### ISSUE TITLE
Make Noise The Default Handshake

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5265]
Currently SECIO is the default protocol for the initial handshake between peers. The default should be NOISE with the fallback being SECIO.

**Comment by prestonvanloon** [comment]
Reverted in https://github.com/prysmaticlabs/prysm/pull/5381

**Comment by prestonvanloon** [comment]
Blocked by #5372

**Comment by rauljordan** [comment]
Resolved in v0.12, now running in dev testnet
