### ISSUE TITLE
WaitForActivation is Very Inefficient

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5268]
Currently `WaitForActivation` sends a rpc call through `BlockTimeByHeight` for an ETH1 block header to our attached eth1 node for each validator. This is fine if we host a few validators, however if we have a large number of validators hosted this becomes very inefficient causing a very long start up time. This issue is track the resolution of this problem.

**Comment by prestonvanloon** [comment]
This has been a big pain sometimes. I think we can reorder the logic a bit like:

- Start up validator
- Check for assignments
- If no assignments because no one is activated, then WaitForActivation

**Comment by nisdas** [comment]
I think we could probably fix this by refactoring so that we dont make a rpc call to our eth1 node for each validator. Instead do it per `WaitForactivation` request

**Comment by rauljordan** [comment]
The function was not using a cache at all in the first place, this was improved by #5300 and @0xKiwi
