### ISSUE TITLE
Create --dev Flag for Advancing a Beacon Node Locally

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#527]
Hi all,

For a local development version of a beacon chain to advance, it would be useful to have a `--dev` flag we can enable in order to stub out certain items for a meaningful demo. For example, the dev flag can stub out the web3 service with some simulation of it instead and also skip certain validity checks such as validator pub key verification.

Opening this issue for discussion and ideas on what else we can stub out for our system to run locally and advance a beacon chain node.

**Comment by terenc3t** [comment]
#537 merged. Can we close this?
