### ISSUE TITLE
Update proposal slashing protection to new spec changes 

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#5282]
As of https://github.com/ethereum/eth2.0-specs/pull/1612/ , proposal slashings are now on a per slot basis, rather than a per epoch basis. As a result, the proposal slashing protection on the validator client needs to be modified to be aware of this. Currently if a validator proposes once in an epoch, they will be blocked from proposing in that epoch again when it won't be a slashable offense.

**Comment by terencechain** [comment]
Closed via #5292
