### ISSUE TITLE
v0.11: Flaky p2p tests

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5283]
Test target `//beacon-chain/p2p:go_default_test ` in the v0.11 branch has been very flaky.

The tests I see fail the most are
- TestStaticPeering_PeersAreAdded
- TestDiscv5_AddRetrieveForkEntryENR

Example errors:
```
TestDiscv5_AddRetrieveForkEntryENR: fork_test.go:246: Wanted fork digest: [24 174 76 203], received [245 165 253 66] 
```

After running 100 tests sequentially (can't run in parallel because the test demands port 2000), the results show that it fails 19 out of 118 runs. (Not sure why it ran 18 extra but ok).

**Comment by terencechain** [comment]
`TestStaticPeering_PeersAreAdded` still failing on the latest latest v0.11 branch. See: 
https://buildkite.com/prysmatic-labs/prysm/builds/26879#f8de094e-a52b-4339-a74d-15305981624d

**Comment by rauljordan** [comment]
This should now be resolved @terencechain , closed the last problematic p2p listener that wasn't being cleaned up
