### ISSUE TITLE
Update aggregator <-> beacon node work flow

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5288]
Open this PR to track the progress to revamping of beacon node <-> aggregator APIs and work flows. This involves changes in `ethereumapi` upstream, beacon node and validator RPC functions

Design doc:
https://hackmd.io/z1Z8ct3bRGi08oAzrxTN4Q?both

**Comment by prestonvanloon** [comment]
What are the required changes for this feature?

**Comment by terencechain** [comment]
1.) Update ethereumapi upstream
2.) Update p2p network, the beacon node with attesters should find persistent peers on the subnet in question to be able to publish, the beacon node with aggregator, should join the subnet
3.) Update beacon node RPC server functions to satisfy the workflow
4.) Update validator client RPC client functions to satisfy the workflow

**Comment by prestonvanloon** [comment]
What are the updates in EthereumAPIs?

**Comment by terencechain** [comment]
> What are the updates in EthereumAPIs?

Biggest one is validator needs to let beacon node know it is an aggregator ahead of time. Maybe a few other minors ones, will have to take a closer look later

**Comment by prestonvanloon** [comment]
Ok please update this issue with those findings. I don’t see any difference between the current implementation and the workflow you described.

**Comment by terencechain** [comment]
> Ok please update this issue with those findings. I don’t see any difference between the current implementation and the workflow you described.

The difference is a beacon node subscribes to all the subnets reported by the attesters, instead the beacon node needs to get the subnets reported by the agregators *ahead* of the time. Whether this requires an additional new message or modifies the exiting one, it's tbd

**Comment by prestonvanloon** [comment]
So we currently subscribe to subnets based on assignments given at the
start of the epoch or RPC requests (like ProposeAttestation or
GetAttestatonData or SubmitAggregateAndProof)

This issue is to change the logic to only subscribe when the attester
submits proof they are an aggregator? How do you recommend that we do this?

**Comment by terencechain** [comment]
> This issue is to change the logic to only subscribe when the attester
submits proof they are an aggregator? 

Yes, but BN needs access to that info earlier with one epoch look ahead

A few more things to work through
 * Validator needs to let beacon node that it's a aggregator with one epoch look ahead. Validator currently does not do that
 * BN should aggregate on demand instead blindly aggregate based on intervals

Will put more thoughts on this today and will report back with a concrete plan

**Comment by terencechain** [comment]
Created an one pager design doc with @prestonvanloon today

https://hackmd.io/z1Z8ct3bRGi08oAzrxTN4Q?both

**Comment by prestonvanloon** [comment]
Design doc LGTM. Thanks!

>

**Comment by terencechain** [comment]
Closed via: #5312, #5302, #5299
