### ISSUE TITLE
Routine for Aggregating Attestations

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#529]
Attester broadcasts attestation every slots. One of the responsibility of a beacon node is to receive incoming attestations and aggregate them into one aggregated attestation. Let's open a PR that takes in attestation via P2P to pass to blockchain service via feed. Blockchain service will aggregate these attestations inside a routine of its own

I'll work on it this week

**Comment by rawfalafel** [comment]
Why? Attestations need to be valid for the block to be valid. 

Fork choice rule can happen independely. Won't validating attestations separately make block validation more complex?

**Comment by terenc3t** [comment]
I should have been more clear with the issue. This is not for checking block validity and applying fork choice. This is for receiving broadcasted attestations from attesters and aggregating them using a separate routine. We currently don't do any of that.

**Comment by rawfalafel** [comment]
> Currently attestation processing logic lives in `processBlocks`

I see I see. What do you mean by `processBlocks` here?

**Comment by terenc3t** [comment]
> > Currently attestation processing logic lives in `processBlocks`
> 
> I see I see. What do you mean by `processBlocks` here?

Updated the issue  😅

**Comment by rawfalafel** [comment]
Thanks! BTW, I think that gathering and aggregating attestations should be a completely new service since it can be done independently of block processing and the fork choice rule.

**Comment by rauljordan** [comment]
Can this be closed?

**Comment by terenc3t** [comment]
We can close this. Basic attestation service functionalitty is done. We can open more issues when as spec gets more finalized

**Comment by terenc3t** [comment]
We can close this. Basic attestation service functionalitty is done. We can open more issues when as spec gets more finalized
