### ISSUE TITLE
Wait For Chainstart to Start P2P Service

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5291]
https://github.com/ethereum/eth2.0-specs/issues/1700

Building on from the above issue we will need to start our p2p service at chainstart instead of when the node starts up to avoid the situation of having 2 different fork digests to reconcile in pre-genesis and post-genesis. This would mean that peer discovery would only begin when we have the relevant chainstart eth1 block confirmed.

**Comment by rauljordan** [comment]
Done
