### ISSUE TITLE
Docs: Add TXgen Design Doc in Markdown

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#53]
[Google doc](https://docs.google.com/document/d/1YohsW4R9dIRo0u5RqfNOYjCkYKVCmzjgoBDBYDdu5m0/edit)

It needs a few updates for the new strategy of separating collator/validator responsibilities and p2p networking details.

**Comment by rauljordan** [comment]
Thoughts on closing this, @prestonvanloon ? state execution, transactions, and gas might be very different in Ethereum 2.0 and this issue will probably just stick around here for ages until then.

**Comment by prestonvanloon** [comment]
Sure. We may not even need it. I’ll reopen in the future if we need this.
