### ISSUE TITLE
Alert validators in case of beacon chain has a short range reorg

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5306]
Given validator requests assignment at the start of the epoch, in the case of a reorg back to the start of the epoch that cause validator assignments to change, validators currently have no way of knowing such reorg event and will still request based on the "old" assignment
Opening this issue for discussion and mitigation steps 

Design doc: https://hackmd.io/KWBj0PCDQUuPKpLQnIiZbw?both

**Comment by prestonvanloon** [comment]
Should we consider adding an assignments stream? Validators can subscribe to a given stream for assignments and in the event of a reorg then the beacon node sends new assignments immediately rather than the start of each epoch.

**Comment by terencechain** [comment]
> Should we consider adding an assignments stream? Validators can subscribe to a given stream for assignments and in the event of a reorg then the beacon node sends new assignments immediately rather than the start of each epoch.

I think that is a great idea. 
The least resistant path is just to have validators check their duties every slot to ensure that chain reorgs are recognized, although I don't have much concrete data to analysis how expensive that is.
Given this is higher priority after seeing many att sig fails to verify, there's two options:
1.) Implement duties streaming
2.) Implement validators polling duty every slot and gated behind a feature flag, then implement duties streaming. Both can happen in parrell.

Would you prefer 2 over 1?  @prestonvanloon

**Comment by prestonvanloon** [comment]
I prefer streaming over polling, especially for such an infrequent event.

**Comment by terencechain** [comment]
Design doc: https://hackmd.io/KWBj0PCDQUuPKpLQnIiZbw?both
