### ISSUE TITLE
kafka?

### ISSUE THREAD

**Issue by pkieltyka** [prysmaticlabs/prysm#5311]
thanks for your amazing work on prysm. I'm just recently starting to dig into the code a little bit and wondering why you're using kafka in the project? it's quite a heavy piece of infrastructure to make as a dependency to this client -- perhaps at first glance though I'm not understanding its use or plans. sorry for the strange question but just personally curious.

**Comment by 0xKiwi** [comment]
Hello @pkieltyka ! Thanks for the nice words and question :)

Maybe @prestonvanloon can explain why we use it, he's the most knowledgable to answer I believe.

**Comment by prestonvanloon** [comment]
@pkieltyka The idea for adding kafka is that we can stream beacon blocks and beacon attestations as they are saved to the database to some central repository. I imagine this makes ETL easier for things like BigQuery or certain types of slashing protection / alerting.

Admittedly, we have not taken advantage of this feature yet, but intend to do so in the near future.

Something to note is that building with kafka support is an opt-in piece of functionality as it causes some build issues on certain operating systems, building kafka takes a long time, and there is low/no demand for this feature. 

Does that answer your question?

**Comment by pkieltyka** [comment]
@prestonvanloon thanks for the answer. Personally I love to see systems to be as lean as possible and offer interfaces for people to plug in adapters. In this case you could still stream the blocks in a payload over a socket interface, and then write a kafka adapter outside of it -- would be much lighter then being part of the core codebase. Just my 2 cents.

**Comment by prestonvanloon** [comment]
Thanks for the feedback. At the time of implementing this feature, using the kafka exporter seemed like the ideal approach given the limited amount of time allocated to experimentation here.

If the optional dependency on kafka is causing anyone pain, we can consider removing kafka in favor of writing some extraction ETL using existing gRPC streams and unary RPC requests.

**Comment by pkieltyka** [comment]
yea, :+1: x100 for gRPC streams and unary RPC requests instead of kafka. 

and something even lighter than gRPC is webrpc -- which is plain http 1.1 or 2, over JSON, using a protocol schema for the payloads and generated clients in Go/TS. Streaming support is in this branch: https://github.com/webrpc/webrpc/tree/stream2/_examples/golang-streaming
