### ISSUE TITLE
Remove validator index from beacondb

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5327]
All of these methods can be replaced by use of the new beacon state managed validator index map.
```go
	ValidatorIndex(ctx context.Context, publicKey []byte) (uint64, bool, error)
	HasValidatorIndex(ctx context.Context, publicKey []byte) bool
	DeleteValidatorIndex(ctx context.Context, publicKey []byte) error
	SaveValidatorIndex(ctx context.Context, publicKey []byte, validatorIdx uint64) error
	SaveValidatorIndices(ctx context.Context, publicKeys [][48]byte, validatorIndices []uint64) error
```

Example:
```go
vID := headState.ValidatorIndexByPubkey(vPub) // Get
headState.SetValidatorIndexByPubkey(vPub, vID) // Set
```

**Comment by prestonvanloon** [comment]
If anyone on @prysmaticlabs/core-team picks this up, please self assign!

**Comment by prestonvanloon** [comment]
Any update on this @shayzluf? This should be a relatively straight-forward enhancement and it would be nice to get this in soon so we can test it before testnet restart.

**Comment by prestonvanloon** [comment]
I'll take this. Thanks

**Comment by terencechain** [comment]
fyi some alarms I raised with Shay's work, we need to be cautious with its scope:

https://github.com/prysmaticlabs/prysm/pull/5335#pullrequestreview-389356120

**Comment by prestonvanloon** [comment]
> 2 problems could arise using head state for validator indices:
1.) if the chain reorg back prior to finalized_check_pt to SetA. Users and applications will not be able to get validatorSetB

Is this actually a concern? Can validators join be assigned a validator index without finalization? 
Wouldn't validatorSetA always be the same as validatorSetB in this case?

> 2.) If the chain finalizes a conflict checkpoint with validatorSetC, the node will have trouble retrieving each set as it relies on the head state

What is validator set C?
