### ISSUE TITLE
ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks

### ISSUE THREAD

**Issue by chrishobcroft** [prysmaticlabs/prysm#5333]
When initially syncing Prysm, I get these `ERROR` messages coming up very regularly.
```
[2020-04-07 17:15:35] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
```

I am on a pretty slow / remote / unstable connection, so I can (in some ways) understand that the node will lose all peers now and again.

But why make this a ERROR? Is there actually a problem with the software? Or perhaps I'm out of touch on how logging levels are defined these days?

Here's the full message, with what looks like a scary stack-trace:
```
[2020-04-07 17:15:35] ERROR initial-sync: Round robing sync request failed error=no peers left to request blocks
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync-old.(*Service).roundRobinSync.func3.1
	beacon-chain/sync/initial-sync-old/round_robin.go:153
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync-old.(*Service).roundRobinSync.func3.1
	beacon-chain/sync/initial-sync-old/round_robin.go:153
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373
```

**Comment by chrishobcroft** [comment]
Also, the "robing" typo is already PR'd and merged: https://github.com/prysmaticlabs/prysm/pull/5317

**Comment by farazdagi** [comment]
- I agree, exposing internal details of data fetching (with addition call stack details, even) doesn't seem like a good idea, debug-level message should be enough (and for end user, some info-level "no peers, waiting for peers" is more than enough). 
- Btw, are you running the beacon node with `--disable-init-sync-queue` (error message suggests that previous implementation of init-sync is used)? Or, you are not running the node out of the current master branch?

**Comment by chrishobcroft** [comment]
I'm just running plain and simple `./prysm.sh beacon-chain`.

I tried it with `--disable-init-sync-queue`, but it said `flag provided but not defined: -disable-init-sync-queue`. Perhaps you mean `--enable-init-sync-queue`, that works?

**Comment by farazdagi** [comment]
Well, then it means are not on the latest master branch. The `--enable-init-sync-queue` flag has been enabled by default now, and you can disable it (in case problems w/ the new sync method are discovered). Can you please pull the latest master, and try running w/o any init-queue related flags?

**Comment by prestonvanloon** [comment]
The Prysm script downloads the latest release.

I can cut a new release today.

**Comment by prestonvanloon** [comment]
Building release binaries for v0.3.10. New release should be available in
the next hour or so

>

**Comment by criticaltv** [comment]
OK I'm now on 0.3.10 due to script auto updating the binaries. Good job on this, it is so easy to run the node...

**Comment by chrishobcroft** [comment]
@farazdagi do you still need me to do this:

> Can you please pull the latest master, and try running w/o any init-sync-queue related flags?

If so, can you link me to instructions? Right now I'm just running the beautifully simple `./prysm.sh beacon-chain`

**Comment by chrishobcroft** [comment]
It seems like 0.3.10 has fixed this issue, can this be closed?

**Comment by farazdagi** [comment]
- since Preston has released new version couple of days ago, no need to pull the master or all that jazz, you can continue relying on `./prysm.sh` script :)
- I am closing the issue, as new version doesn't have the described behaviour
