### ISSUE TITLE
Prysm triggers Windows Defender Warning

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5337]
![image](https://user-images.githubusercontent.com/7246818/78705663-abd3e280-78c2-11ea-924c-c20ce1573847.png)

**Comment by 0xKiwi** [comment]
Any update on this? @prestonvanloon

**Comment by prestonvanloon** [comment]
No update at this time. We have to purchase a certificate from a CA.

**Comment by prestonvanloon** [comment]
Waiting on verification from digicert.

**Comment by prestonvanloon** [comment]
Removing from v1. We won't have digicert certificate before Monday...
