### ISSUE TITLE
Fix Attestation Data Structure For Incoming Blocks

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#534]
**Background** : Incoming blocks must also include an attestation by the proposer. Specifically, a signature along with a shard block hash must be included. The current implementation includes `AggregatedAttestation`, a data structure that represents an aggregation of attestations, not a single one. There are fields that won't be used to validate the block, and are therefore a waste of resources.

**Relevant code**
* [Incoming blocks in the sync service](https://github.com/prysmaticlabs/prysm/blob/a53395db9474530a7abdb66c85685565a7d66ded/beacon-chain/sync/service.go#L154)
* [Block's attestation](https://github.com/prysmaticlabs/prysm/blob/master/proto/beacon/p2p/v1/messages.proto#L35)

**Requirements**: Replace `AttestationRecord` with a new proto message that contains just a signature and 32 byte hash representing the shard's block. Use these fields to validate the proposer's attestation.

**Comment by terenc3t** [comment]
I thought of this as I implemented #508. Ultimately I stopped because I couldn't figure out how to get `ObliqueParentHashes` and `JustifiedSlotNumber` if they don't come from the proposer. What do you think? @rawfalafel

**Comment by rauljordan** [comment]
Can this be closed as well @terenc3t @nisdas?

**Comment by terenc3t** [comment]
Yeah. We can
See relevant discussion: https://github.com/ethereum/eth2.0-specs/issues/6
