### ISSUE TITLE
Deprecate Archiver Service

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5350]
Now that we generate states on the fly by using a cool new state management technique piloted by @terencechain, we no longer need the concept of an "archival" node nor the "archiver" service in Prysm. This is a tracking issue to deprecate such service and delete its code from our repo. Blocked until v0.11 is merged in.

Edited by @terencechain 👇 

Here's the list of archival RPC end points that need work on:
- [x] ListValidatorAssignments
- [ ] GetValidatorActiveSetChanges
- [ ] GetValidatorParticipation
- [ ] ListBeaconCommittees
- [ ] StreamIndexedAttestations

**Comment by terencechain** [comment]
This is mentioned in #4958 

Should we just have one canonical tracking? or you prefer a side tracking for deprecation specifically?

**Comment by terencechain** [comment]
Working on `ListValidatorAssignments`

**Comment by rauljordan** [comment]
Can we close this one @terencechain

**Comment by terencechain** [comment]
No, we haven't fully deprecated the archival service yet. DB and service objects still exist

**Comment by prestonvanloon** [comment]
Is this still blocked? I think that the new state management was set to default for Onyx (alpha.10+).

**Comment by terencechain** [comment]
Blocked by testing. We should let the default mode (alpha 10+) run in the wild for a few weeks before fully deprecating archival service. There's no going back or else we'll just end up reverting work like in Topaz

**Comment by rauljordan** [comment]
Resolved
