### ISSUE TITLE
Add Suggestion to Use Eth2Stats in Testnet Site

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5352]
Thanks @tzapu for the suggestion - we're a big fan of eth2stats.io and many users would benefit from being able to see how their node fares compared to others in the network and feel like they have a sense of participation greater than just reading cli logs. We can suggest users to navigate to https://eth2stats.io/add-node after they start their node from our https://prylabs.net/participate portal and also suggest them to check out the 2 block explorers available.

**Comment by prestonvanloon** [comment]
Has this been completed? I recall seeing something about eth2stats somewhere, but I don't recall if it was for the testnet site instructions.

**Comment by rauljordan** [comment]
Hey @prestonvanloon done here https://github.com/prysmaticlabs/prysm-testnet-site/blob/master/src/app/pages/participate/participate.component.html#L159, the issue was to suggest it in the participate component of our testnet site
