### ISSUE TITLE
Better validator performance tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5360]
I'd like to see a more granular report on validator performances with the focus on comparing internal hosted validators versus external user launched validators.

Example, Prylabs controls 78% of the validators and the max participation is at 77%. What's the participation rate on the Prylabs validators and the participation rate on the external validators? 

A feature or tool like this will be really useful down the road

**Comment by rauljordan** [comment]
Thinkin about this more - perhaps blocks validator duties requests coming via RPC can update some metric with the validator indices that belong to Prysm. Maybe it can be done as part of the validator performance RPC call?

**Comment by rauljordan** [comment]
Actually just saw you mentioned "internal" vs external validators, so seems like it would have to be something not included in our codebase, but rather an external tool

**Comment by terencechain** [comment]
Let's move this discussion to the external tool's repo
