### ISSUE TITLE
Corrupt data in beaconDB causes initial sync to mark blocks as invalid

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5395]
Seeing this message 
```
{"error":"could not process block: could not delete states prior to finalized check point, range: 544, 5
76: snappy: corrupt input","message":"Block is invalid","prefix":"initial-sync","severity":"INFO"}
```

The block is not invalid, but the method `rmStatesOlderThanLastFinalized` is failing to delete an old finalized state. Initial sync cannot advance in this condition.

**Comment by terencechain** [comment]
Marking this a medium priority as it becomes less relevant in v0.11 (not part of the default initial sync block processing code path)

**Comment by rauljordan** [comment]
Would we still see this with your latest changes @terencechain ?

**Comment by terencechain** [comment]
Yeah. This is a different code path. This is only when `diable-new-state-mgmt` applies
