### ISSUE TITLE
ERROR sync: Failed to write to stream error=stream reset handler=status Killed

### ISSUE THREAD

**Issue by Strydom** [prysmaticlabs/prysm#5405]
Beacon node threw this error and stopped running last night.
No other information logged out...

`ERROR sync: Failed to write to stream error=stream reset handler=status
Killed`

Do errors get logged to files anywhere for more information?
I've lost the ones in my console now.

**Comment by rauljordan** [comment]
Looks like an out of memory issue @Strydom can you share more details about your setup? OS and Flags to run your beacon node?

**Comment by rauljordan** [comment]
Hi @Strydom please try this out with our new Topaz testnet, I don't believe this error occurs anymore. Please let us know in this thread if it still happens to you, closing in the meantime.
