### ISSUE TITLE
Fix NOISE Handshake Fallback to SECIO for P2P

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5410]
Hi all, currently the NOISE handshake does not consistently fallback to secio for libp2p security. If we want to upgrade our nodes to use Noise, we need to ensure the fallback is fully functional and always works otherwise we risk network partitions.

**Comment by shayzluf** [comment]
@rauljordan any update on this issue?

**Comment by shayzluf** [comment]
assigned to @nisdas as i think p2p issues owned by you. please reassign to me if you want me to find another assignee

**Comment by nisdas** [comment]
This is currently blocked @shayzluf 
https://github.com/libp2p/go-libp2p-noise/issues/70

**Comment by rauljordan** [comment]
Resolved in v0.12, running in dev testnet
