### ISSUE TITLE
Remove dependency on go-ethereum fork

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5418]
At present, we maintain an old fork of go-ethereum primarily to use the ethclient and discovery v5 protocol. Given some of the improvements in our build tooling, we should be able to use the upstream go-ethereum with minor changes.

**Comment by nisdas** [comment]
Just for an update, I have started opening PRs upstream so as to resolve any significant differences 
between our fork and go-ethereum master. 

https://github.com/ethereum/go-ethereum/pull/20917 
https://github.com/ethereum/go-ethereum/pull/20918

**Comment by rauljordan** [comment]
#5865 partially helps

**Comment by rauljordan** [comment]
Any update on this one @nisdas?

**Comment by rauljordan** [comment]
Still blocked by rules go and likely should be added to the backlog

**Comment by rauljordan** [comment]
@prestonvanloon is this related to some work you were doing earlier? Can this be closed or do we still have some pending items?

**Comment by prestonvanloon** [comment]
This is done. #9725
