### ISSUE TITLE
Bug in Getting Validator Balance of a Block

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#542]
In `NewStateRecalculations` from `crystallized_state.go` Every block, we are suppose to compare the attester's participated balance to the total balance of the block if every attester has participated. 

There's a bug of the current code where attester's participated balance is compared with the total deposits of the crystallized state. This is incorrect we should compare to the total deposits of the attester in that slot committee.

**Comment by nisdas** [comment]
Hey Terence I looked at this, and I am not sure this is a bug. Isnt total deposit the balance of all the active validators ?

**Comment by terenc3t** [comment]
I think there's a typo in the spec. I'm confirming with Danny now

**Comment by terenc3t** [comment]
Confirmed with Danny, the spec is a lil confusing but it's actually correct.

When a validator attest to a block. It actually is attesting up to CYCLE_LENGTH blocks. For each block, after a full cycle, there is a chance for every validator to have attested to it and we are counting block votes from the direct block attested to but all the other slots that get attested to implicitly although explicitly signed.
