### ISSUE TITLE
Failed to read keymanager options file (Windows, Docker, 24fc67a6dd)

### ISSUE THREAD

**Issue by remyroy** [prysmaticlabs/prysm#5436]
I'm manager to launched the beacon-chain:latest and validator:latest. I've managed to create my validator public / private key with:

```
$ docker run -it -v c:/prysm/:/data gcr.io/prysmaticlabs/prysm/validator:latest accounts create --keystore-path=/data --password=hidden
2020/04/15 02:36:40 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
[2020-04-15 02:36:40]  WARN flags: Using default mainnet config
[2020-04-15 02:36:41]  INFO accounts: Keystore generated for shard withdrawals at path path=/data/shardwithdrawalkey969b82599b60
[2020-04-15 02:36:42]  INFO accounts: Keystore generated for validator signatures at path path=/data/validatorprivatekey8e02d1eed5bf
[2020-04-15 02:36:42]  INFO accounts: Account creation complete! Copy and paste the raw transaction data shown below when issuing a transaction into the ETH1.0 deposit contract to activate your validator client
```

However, whenever I try to start my validator, I get the follow logs which seems to fail:

```
$ docker run -it -v c:/prysm/:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keymanager=keystore --keymanageropts='{"path":"/data","passphrase":"hidden"}'
2020/04/15 03:03:17 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
[2020-04-15 03:03:17]  WARN flags: Using default mainnet config
[2020-04-15 03:03:17] ERROR main: Failed to read keymanager options file: open '{path:/data,passphrase:hidden}': no such file or directory
```

This is with the following version:

```
$ docker run -it -v c:/prysm/:/data gcr.io/prysmaticlabs/prysm/validator:latest -v                              
2020/04/15 03:11:52 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined                                         
validator version Prysm/Git commit: 24fc67a6dd464584bde44f4377fc6f21f9de3e63. Built at: 2020-04-15 01:03:51+00:00
```

and

```
$ docker run -it -v c:/prysm/:/data gcr.io/prysmaticlabs/prysm/beacon-chain:latest -v
2020/04/15 03:16:02 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
beacon-chain version Prysm/Git commit: 24fc67a6dd464584bde44f4377fc6f21f9de3e63. Built at: 2020-04-15 01:15:57+00:00
```

**Comment by remyroy** [comment]
This issue can be solved when starting the validator with PowerShell instead of the regular cmd shell on Windows. Something like this in PowerShell:

```
docker run -it -v c:\prysm:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keymanager=keystore --keymanageropts='{\"path\":\"/data\",\"passphrase\":\"hidden\"}'
```

**Comment by remyroy** [comment]
Here is one of the correct convoluted way of escaping the --keymanageropts part for starting the validator on Windows using the regular cmd shell:

```
$ docker run -it -v c:/prysm/:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keymanager=keystore ""--keymanageropts={\"path\":\"/data\",\"passphrase\":\"hidden\"}""
```

**Comment by remyroy** [comment]
So this issue is related to the way the regular cmd shell on windows escape quotes or double quotes, the potential solution when using PowerShell or the potential solution using the escape mechanism shown just above.

**Comment by taddoo** [comment]
That solved my problems! Thank you very much.

I suggest to change "docker run -it -v $HOME/prysm/validator:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keymanager=keystore --keymanageropts='{"path":"/data","passphrase":"changeme"}'" command  in https://docs.prylabs.network/docs/prysm-usage/activating-a-validator/ to prevent confusion.

**Comment by GottliebFreudenreich** [comment]
I had the same problem when starting the systemctl prysm-validator via the prysm-validator.conf on a Ubuntu20.04 RaspPi4.. Adding additional quotation marks like
`ARGS="--keymanager=keystore "--keymanageropts=\'\{\"path\":\"/home/ethereum/.eth2validators\",\"passphrase\":\"changeme\"\}\'""` 
fixed the problem for me

**Comment by rauljordan** [comment]
Closed as our docs are now more airtight, recommending running Prysm with the windows .bat file, no longer mentioning the tricky keymanageropts command

**Comment by jcb31416** [comment]
the error remains with the .bat file (win10x64) following instructions detailed in https://docs.prylabs.network/docs/install/win/activating-a-validator:

`prysm.bat validator accounts status --keymanager=keystore --keymanageropts=%LOCALAPPDATA%\.eth2validators --beacon-rpc-provider=localhost:4000`

**Comment by prestonvanloon** [comment]
@jcb31416 what is the error?
