### ISSUE TITLE
Add full docker docs

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5437]
**Please add docs for  docker + validator (creating keys + how to run)**

 this is how it worked for me, the one on the website doesn't necessarily work for all OS:

**Docker windows creating keys:** 
docker run -it -v C:\Users\PCUSERNAME\prysm\validator/prysm:/data gcr.io/prysmaticlabs/prysm/validator:latest  accounts create --keystore-path=/data --password=changeme

**Docker windows running validator**
docker run -it -v c:/prysm/validator:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keystore-path=/data --password=changeme

**Docker Windows running beacon**
docker run -it -v c:/prysm/:/data -p 4000:4000 -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data

**MacOs Docker**

**creating keys**
docker run -it -v c:/prysm/validator:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=127.0.0.1:4000 --keystore-path=/data --password=changeme

**running validator** 
docker run -it -v $HOME/prysm:/data --network="host" \
  gcr.io/prysmaticlabs/prysm/validator:latest \
  --beacon-rpc-provider=127.0.0.1:4000 \
  --keystore-path=/data \
  --password=changeme

**running beacon**
docker run -it -v c:/prysm/:/data -p 4000:4000 -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data

**Comment by har00ga** [comment]
On this now

**Comment by Buttaa** [comment]
> 
> 
> On this now

the paths are messed up, users will end up with multiple folders with the commands above. 
I am trying to figure out how to avoid. Will let you know if i find a solution!

**Comment by rauljordan** [comment]
Done by https://github.com/prysmaticlabs/documentation/pull/43
