### ISSUE TITLE
Validator Key path issue

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5438]
MacOs

After creating keys with: ` ./prysm.sh validator accounts create --keystore-path=$HOME/validator --password=changeme`

running: `./prysm.sh validator --password=changeme` does not work. 
**There is a path issue and the path flag is required.** 

Works fine this way: 
`./prysm.sh validator --password=changeme --keystore-path=$HOME/validator`

**Comment by chrishobcroft** [comment]
I think this might be an inconsistency in the scripts.

To replicate:

1. I follow this: https://prylabs.net/participate
2. At step 3, I generate a keystore in `$HOME/validator`, and transaction data for the deposit contract ending `27962e`
3. At step 4, I run `./prysm.sh validator --password=changeme` which appears to generate another keystore at `$HOME/eth2validators`, and transaction data for the deposit contract ending `35dd64`.

Seems like there is a default location for keystore ($HOME/**.eth2validator**), and the suggestion to use `--keystore-path=$HOME/**validator**` when running `./prysm.sh validator accounts create` is different from this default.

**Comment by kumavis** [comment]
this worked for me, thanks
```bash
rm -rf $HOME/validator
./prysm.sh validator accounts create --keystore-path=$HOME/validator --password=changeme
./prysm.sh validator --password=changeme --keystore-path=$HOME/validator
```

**Comment by kumavis** [comment]
couldn't find a good reference, but its generally a bad idea to put passwords in cli args (they appear in bash history)

**Comment by farazdagi** [comment]
- yep, you're right, we have already removed that password from from cli https://github.com/prysmaticlabs/prysm-testnet-site/commit/e1a0571d0fd8b3d1957f8c20161e32a9f47d2c45
- preparing the fix for the current issue as well

**Comment by kumavis** [comment]
@farazdagi im not sure where the repo for https://prylabs.net/participate is, but it should be updated to match the new interface

**Comment by prestonvanloon** [comment]
@kumavis that repo can be found at https://github.com/prysmaticlabs/prysm-testnet-site
