### ISSUE TITLE
Request: Add a timer till genesis & during 48h time period

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5439]
Would be very helpful to have logs every minute until genesis!

100 minutes till genesis
99 minutes till genesis 
..

edit: 

- show current deposit count x/16384

- timer during 48h time period

**Comment by prestonvanloon** [comment]
I support this in the beacon node and validator processes 👍

**Comment by rauljordan** [comment]
@ShawkiS is interested in this

**Comment by ShawkiS** [comment]
Yeah, that will be great I'll start working on it.

**Comment by ShawkiS** [comment]
I'll write what is the solution looks like 

Adding this log in both `validator/client/service.go` and `beacon-chain/blockchain/service.go
`
```
func countdownToGenesis() {
ticker := time.NewTicker(time.Minute*5)
for {
  select {
    case <-genesisTime:
      // Exit upon hitting the genesis time.
      return
    case tick:=<-ticker.C:
      // Exit if we have already reached the genesis time, else log:
      log.Infof("%v minutes to genesis!", computeDifference(time.Now(), genesisTime))
  }
}
}
```

Note: The solution was by Raul on Discord

**Comment by prestonvanloon** [comment]
Unassigning from @ShawkiS since their PR has gone stale. @ShawkiS if you'd like to pick this up again, let us know. Otherwise we're stilling looking for help on this issue as a good first issue.

**Comment by Buttaa** [comment]
edited original post

-  show current deposit count x/16384

-  timer during 48h time period
