### ISSUE TITLE
Beacon Node Consistently Logs Error

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5443]
This was reported by @metanull-operator , the beacon node consistently logged this 
`exit status 128` 

```
verify" prefix=blocks
Apr 15 05:02:30 beacon01 beacon-chain[2068]: time="2020-04-15 05:02:30" level=warning msg="eth1 client is not syncing" prefix=powchain
Apr 15 05:02:36 beacon01 beacon-chain[2068]: 2020/04/15 05:02:36 exit status 128
Apr 15 05:02:48 beacon01 beacon-chain[2068]: 2020/04/15 05:02:48 exit status 128
Apr 15 05:03:00 beacon01 beacon-chain[2068]: 2020/04/15 05:03:00 exit status 128
Apr 15 05:03:12 beacon01 beacon-chain[2068]: 2020/04/15 05:03:12 exit status 128
```

This most likely has to do with this:
https://github.com/prysmaticlabs/prysm/blob/master/shared/version/version.go#L19 

This is the only place in prysm where we explicitly call `exec`. This could also potentially be from other imported libraries. Needs more investigation to ascertain the root cause

**Comment by metanull-operator** [comment]
Additional details:

Start command for beacon chain:
`beacon-chain --datadir=/home/eth2/prysm --min-sync-peers=7 --p2p-max-peers=50 --monitoring-port 8080 --p2p-tcp-port 13000 --p2p-udp-port 12000 --rpc-port 4000`

This error occurs regardless of whether a validator is running. It occurs after multiple restarts, after multiple clearings of the database, and after a reboot.

**Comment by metanull-operator** [comment]
As seen in the logs, the error message appears approximately every 12 seconds.

**Comment by metanull-operator** [comment]
Also worth noting that my validator client also reported this error, though only once. Not every 12 seconds.

`Apr 15 15:29:26 beacon01 validator[6962]: 2020/04/15 15:29:26 exit status 128`

**Comment by metanull-operator** [comment]
I have a second server with nearly identical hardware and software configuration. I get this same error on that second system as well.

**Comment by metanull-operator** [comment]
Updated both servers to v1.0.0-alpha.2. Beacon chains on both servers report same "exit status 128" three times only, and no longer repeat every 12 seconds after that. Only running validator on one of the two machines, but it also appears to have printed the same error 3-4 times before stopping.

**Comment by nisdas** [comment]
@metanull-operator could your try this in your local machines and paste what you get ?
```
git rev-parse HEAD
```

**Comment by metanull-operator** [comment]
4fbcedf5415505833f37bb557107519f04d33e86

**Comment by prestonvanloon** [comment]
Please build with `--config=release` to resolve this.

**Comment by metanull-operator** [comment]
Looks like that worked. What exactly did I just do? And what did I originally do wrong?

**Comment by prestonvanloon** [comment]
Using the release flag builds with the commit hash baked into the built binary, running without the release flag queries git to understand the current commit hash. It's mostly for development. 

The release config also compiles with compile time optimizations. You have a longer build but faster executable.

**Comment by metanull-operator** [comment]
@nisdas This can be closed. I don't believe I can close it.
