### ISSUE TITLE
weird genesis timestamp for topaz

### ISSUE THREAD

**Issue by tzapu** [prysmaticlabs/prysm#5448]
i've just setup a new node and tried to query for the genesis timestamp
the http api gives me 
```
$ curl -X GET "http://localhost:3001/eth/v1alpha1/node/genesis" -H  "accept: application/json"
{"genesisTime":"0001-01-01T00:00:00Z","depositContractAddress":"XKHgAAQ2ashfSSiHqqsS0OZBiHY="}
```
and over grpc `GetGenesis(...).GetGenesisTime().GetSeconds()` returns `-62135596800`

neither is ideal :D

**Comment by prestonvanloon** [comment]
We saw the same thing on https://prylabs.net. I think this might be an issue with grpc / json transcoding. It is likely that the beacon node reported `0` as the genesis start time and it was somehow converted to this ridiculous timestamp. 

In any case, this is unacceptable behavior for pre-genesis beacon node reporting. We'll have to find some alternative solution.

**Comment by rauljordan** [comment]
Done by #6031
