### ISSUE TITLE
Validator Path Issue 

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5456]
Windows10,

`validator-v1.0.0-alpha.2-windows-amd64.exe accounts create`

Leaving it blank for "default path" or even with a specific path does not work.

specific path:
![grafik](https://user-images.githubusercontent.com/26490734/79471172-8c476300-8002-11ea-8ca8-b08e4e6bfee1.png)
Blank:
![grafik](https://user-images.githubusercontent.com/26490734/79471129-7f2a7400-8002-11ea-91fd-c0851388bf1f.png)

**Comment by prestonvanloon** [comment]
Looks like a problem with the default path for the validator data directory.

As a workaround, please try using the datadir flag like `--datadir=C:\Users\Inan\Prysm` to specify the correct directory. Be sure to use the same flag when you start your validator as well.

**Comment by Buttaa** [comment]
![grafik](https://user-images.githubusercontent.com/26490734/79507762-8ec4af80-8038-11ea-870a-bc3389cf2d6e.png)
as mentioned on discord, doesn't solve the issue unfortunately

**Comment by prestonvanloon** [comment]
Thanks. Looks like something about the filepath name is incompatible with windows. It would be helpful if we printed the path it is trying to save in the error message as well as fix the underlying problem.

**Comment by Buttaa** [comment]
@prestonvanloon 

Binary Files work now. Solution was to drag&drop(to get the exact path lol) the binary file into the terminal and use:

`beacon-chain-v1.0.0-alpha.5-windows-amd64.exe`--datadir=/prysm`
if the folder is in C:\prysm

`validator-v1.0.0-alpha.5-windows-amd64.exe --keystore-path=/prysm --password=yourPassword`

**Comment by wgknowles** [comment]
Just tested this using v1.0.0-alpha.6 windows binaries

**Works:**
.\prysm.bat validator accounts create --keystore-path=C:\prysm\validator --password=changeme
.\prysm.bat validator accounts create --keystore-path=C:\prysm\validator
changeme

**Fails:**
.\prysm.bat validator accounts create
changeme
C:\prysm\validator

**Fails:**
.\prysm.bat validator accounts create --password=changeme
C:\prysm\validator

**Comment by wgknowles** [comment]
Possibly resolved by #5707 - need to build new binaries to test.

**Comment by wgknowles** [comment]
Still not working in alpha.7:
C:\Prysm>prysm.bat validator accounts create
A subdirectory or file C:\Prysm\dist already exists.
Latest prysm release is v1.0.0-alpha.7.
Using prysm version v1.0.0-alpha.7.
Starting Prysm validator accounts create
2020/05/13 07:59:40 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
[2020-05-13 07:59:40]  WARN flags: Using default mainnet config
[2020-05-13 07:59:40]  INFO accounts: Please specify the keystore path for your private keys (default: "C:\\Users\\Pumpkin\\AppData\\Roaming\\Eth2Validators"):

[2020-05-13 07:59:44]  INFO accounts: Please enter the password for your private keys
[2020-05-13 07:59:44]  INFO node: Enter a password:
[2020-05-13 07:59:46]  INFO node: Please re-enter your password:
 error=path "\r" does not existn: Could not create validator at path:
ERROR FAILED

**Comment by 0xKiwi** [comment]
Thanks for the update! @wgknowles , we'll look into this.

**Comment by Chambers-Chambers** [comment]
how do i go about getting ETH 2.0 Validator set up. Im mining ETC using my Computers but id like to be an ETH Validator as well. Mining seems simple compared to getting this set up. What am i doing wrong? Ive downloaded git
ive downloaded docker
ive used powershell
i tried making folders with seperate files like you would with mining ETC but i cant get it to work. Ive spent multiple days trying to figure it out.
simplified how can i get it to work. I have metamask and turned it to goerli network but im not sure how to become a validator even though my goal was to hodl 32eth specifically to become one. --much thanks

**Comment by rauljordan** [comment]
@0xKiwi do you know if this is resolved?

**Comment by 0xKiwi** [comment]
Sorry, assigned myself but forgot. I haven't looked into it, I think the issue still remains.

**Comment by rauljordan** [comment]
Please triage @0xKiwi
