### ISSUE TITLE
Security: runtime passwords

### ISSUE THREAD

**Issue by xrow** [prysmaticlabs/prysm#5483]
Hi,

currently I don`t like the idea of having the key and password on the disk. My idea would be to inject at least the password from a call back.

The callback could be a script the returns the password. 

`--password-callback=/path/to/script`

**Comment by shayzluf** [comment]
leaving the password blank prompts the user to enter the password in runtime. example:
'./prysm.sh validator accounts create --keystore-path=$HOME/.eth2validator'
'./prysm.sh validator --keystore-path=$HOME/.eth2validator'
does it satisfies your security needs?

**Comment by prestonvanloon** [comment]
Related: #4681

**Comment by xrow** [comment]
@shayzluf 
Actually my inital plan was find out how too pull the key and credetails from hashcorp vault.

If no password is set the keys are unencrypted correct?

**Comment by wgknowles** [comment]
.\prysm.bat validator accounts keys --keystore-path=..\validator
[2020-05-02 15:35:40] FATAL main: password is required

**Comment by shayzluf** [comment]
@wgknowles opened #5733 to solve this issue . thanks for reporting it

**Comment by xrow** [comment]
Ok one enchantment I did so far was the wallet or keystore is now on a in memory disk during runtime. That makes me feel safer. Still I want to split the things apart as much as possible.

I was now somehow thinking I should create a one time password throw it away after the thing starts. The question is how.

**Comment by xrow** [comment]
Maybe this will do `--password=$(cat /data/passwordfile; rm -Rf /data/passwordfile;)`

**Comment by 0xKiwi** [comment]
Hello @xrow , password flag should no longer be required for any of the validator commands, does this solve your problem?

**Comment by xrow** [comment]
I think i have a vaild workaround for now. thanks.
