### ISSUE TITLE
Could not request attestation to sign at slot error=rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by PengFei-eth** [prysmaticlabs/prysm#5484]
PC Specs: 
Win 10
8gb RAM
Quad Core 
170GB SSD

Running Beacon Chain and Validator in Docker

![error](https://user-images.githubusercontent.com/3522955/79625273-dcebb880-80f5-11ea-88c6-a9b5b9af347f.png)

**Comment by PengFei-eth** [comment]
![error_2](https://user-images.githubusercontent.com/3522955/79625736-ffcb9c00-80f8-11ea-8a11-f2905022b50f.png)

**Comment by rauljordan** [comment]
Hi @PengFei-eth this one is a bit hard to debug given there can be many reasons this happens (maybe your beacon node disconnected while a validator API call was in-flight, for example). I imagine there was something bottlenecking your node at the time that prevented the call from completing quickly. Unfortunately, we don't have enough info to reliably reproduce this. I imagine your node was likely CPU bottlenecked at the time. Given we don't have any actionable steps for this issue, we'll close. If it persists or shows up a lot more please let us know.
