### ISSUE TITLE
disable-dynamic-committee-subnets doent subscribe to all channels

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5487]
with dynamic subscription beacon node listens only to its connected validator committees attestations  even when using `--disable-dynamic-committee-subnets` flag

slasher friendly beacon node should listen to all attestation p2p channels

Should investigate and add detatils

**Comment by nisdas** [comment]
Hey @shayzluf is this still valid ? I am not seeing this when running that flag.

**Comment by rauljordan** [comment]
Confirmed I subscribe to all with the flag on
