### ISSUE TITLE
Initial sync took too long to switch to request parent sync

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5491]
It took 13 mins from `Synced up to slot N` to `Requesting parent block`. What's up with the long delay?

<img width="1268" alt="Screen Shot 2020-04-18 at 8 47 01 AM" src="https://user-images.githubusercontent.com/21316537/79642249-4baa2f80-8151-11ea-93f5-787705f9988a.png">

Took a profile during the delay. It doesn't say much:
<img width="2311" alt="Screen Shot 2020-04-18 at 8 16 49 AM" src="https://user-images.githubusercontent.com/21316537/79642283-844a0900-8151-11ea-8090-9d0a074986b3.png">

**Comment by terencechain** [comment]
could be related to #5476, no block comes in the pipeline hence request parent is halted

**Comment by prestonvanloon** [comment]
I am sure this is related to #5476 and will be resolved with #5500
