### ISSUE TITLE
Optimize depositBlockSlot

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5493]
Can we optimize `depositBlockSlot` for `validatorStatus`?  This took up a big portion of the flame at certain times for my beacon node that's serving 1000 validators

<img width="2353" alt="Screen Shot 2020-04-18 at 9 37 42 AM" src="https://user-images.githubusercontent.com/21316537/79643836-c1b29480-8159-11ea-9798-d1f0affe2c61.png">

**Comment by rauljordan** [comment]
@0xKiwi do you think we can close this? I believe the results we're seeing from your PR have helped get rid of this flame a lot

**Comment by 0xKiwi** [comment]
Yup! @rauljordan we can close this now, all of the improvements have been merged.
