### ISSUE TITLE
Bazel build error: target '@herumi_bls_eth_go_binary//:go_default_library' is not visible from target '//shared/bls:go_default_library'.

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#5506]
Version c3217abb837a75b72fb3d978edfc9b22863d0b72

ERROR prysm/shared/bls/BUILD.bazel:5:1: in go_library rule //shared/bls:go_default_library: target '@herumi_bls_eth_go_binary//:go_default_library' is not visible from target '//shared/bls:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: Analysis of target '//shared/bls:go_default_library' failed; build aborted
INFO: Elapsed time: 934.850s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (398 packages loaded, 9758 targets configured)
    Fetching @com_github_btcsuite_btcd; fetching 21s

**Comment by ethers** [comment]
Still issue on 33774721bb585d4fca85343fbd9592274f246274

**Comment by nisdas** [comment]
@ethers could you paste your build command from which you get the above error and what bazel version you are on ?

**Comment by ethers** [comment]
@nisdas  Version
Build label: 1.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 26 00:00:00 2019 (1574726400)
Build timestamp: 1574726400
Build timestamp as int: 1574726400

`bazel build //beacon-chain:beacon-chain`

Could herumi / https://github.com/prysmaticlabs/prysm/pull/5453 be contributing?  Is there a way to bypass it?  I know pretty much nothing about Bazel, herumi, but can try commenting out things in some files with some guidance.  Thanks

**Comment by prestonvanloon** [comment]
Please use bazel 2.1.1 or greater. The project recommends bazel 3.0.0

**Comment by ethers** [comment]
Thanks I'll try that. Meantime https://github.com/prysmaticlabs/documentation/pull/35/

**Comment by ethers** [comment]
Definitely been building much more and I'll close hoping it all succeeds
