### ISSUE TITLE
Binary broken on ARM64

### ISSUE THREAD

**Issue by mangoleap** [prysmaticlabs/prysm#5509]
After pulling the latest code via git the prysm.sh startup script doesn't work anymore. It exits with the error

`/root/prysm/dist/beacon-chain-v1.0.0-alpha.4-linux-linux-arm64: line 1: Not: command not found`

**Comment by eliaskg** [comment]
Btw I saw that there was a recent commit that [mentions ARM64](https://github.com/prysmaticlabs/prysm/pull/5507). I pulled afterwads

**Comment by mangoleap** [comment]
Btw I saw that there was a recent commit that [mentions ARM64](https://github.com/prysmaticlabs/prysm/pull/5507). I pulled afterwads

**Comment by 0xKiwi** [comment]
Hello! Sorry, this will be resolved by #5511. I had trouble testing it originally as I don't have access to an arm setup. Sorry for the trouble!

**Comment by 0xKiwi** [comment]
Should be fixed now! Please let me know if you have other problems!

**Comment by mangoleap** [comment]
Works now, thank you!
