### ISSUE TITLE
BLS Signature Aggregation

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#552]
Hi all,

Starting this issue to discuss BLS implementation for our beacon chain and opening it up for discussion. This can also serve as a tracking issue for any future PRs in this direction.

**Comment by terenc3t** [comment]
This is very similar to #258

**Comment by rauljordan** [comment]
Ah I missed that - thanks @terenc3t let's just use 258 in that case. Maybe we can retitle the issue to include BLS in there.
