### ISSUE TITLE
Sort `New assignment...` logs by `attesterSlot` order

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5522]
Will be nice to view these logs in ascending order based on `attesterSlot` and `proposerSlot`

<img width="790" alt="Screen Shot 2020-04-19 at 5 10 25 PM" src="https://user-images.githubusercontent.com/21316537/79703457-d168d080-8260-11ea-9068-8c6626a4e289.png">

**Comment by ShawkiS** [comment]
Hey Terence, I am sorry but I am totally new about the protocol, am I right that this is the code that must be edited: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/validator/assignments.go

The default assignment?

**Comment by mcdee** [comment]
@terencechain any thoughts on #5397 which provides more concise output for assignments (including ordering by slot)?

**Comment by ShawkiS** [comment]
sort.SliceStable(validatorAssignments, func(i, j int) bool {
	return validatorAssignments[i].AttesterSlot < validatorAssignments[j].AttesterSlot
})

Like that?

**Comment by ShawkiS** [comment]
Is it always that if the `attesterSlot` of a validatorAssignment is bigger the other validatorAssignment the `proposerSlot` is bigger?

**Comment by terencechain** [comment]
@mcdee that looks inline with my thinking, let's go with that
