### ISSUE TITLE
Add Subcommand to Retrieve Data Directory

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5526]
# 🚀 Feature Request

### Description

Users when running their beacon nodes and validator clients have difficulty determining 
which data directories their database files and keys are located at.

### Describe the solution you'd like

Both the beacon node and validator client should have a subcommand which 
will print the current data directory for the beacon/validator client. 

### Describe alternatives you've considered

Nothing so far, there is no current feature that exists in the beacon/validator client
currently

**Comment by ShawkiS** [comment]
Hey Nishant, I am totally new for the protocol, where is the code that set the direction that the nodes will be stored at?

What if we just take the return of that code or the var value store in a variable and present it in the most relative message? is this a good solution?

**Comment by nisdas** [comment]
hey @ShawkiS , this is where we use the data directory flag
https://github.com/prysmaticlabs/prysm/blob/master/shared/cmd/flags.go#L16. We need to basically print out the absolute path of the current data directory referenced by a node.

**Comment by ShawkiS** [comment]
```
				{
					Name: "directory",
					Description: `Retrieve validator data directory`,
					Flags: []cli.Flag{
						flags.DataDirFlag
					},
					Action: func(ctx *cli.Context) error {
							fmt.Printf("Validator of data directory is: %#x\n", flags.DataDirFlag)
					},
				},
```

Is that true?

**Comment by prestonvanloon** [comment]
@nisdas I don't understand the feature request here. You want to add a subcommand that prints the flag value? What is the use case?

**Comment by nisdas** [comment]
not really the flag value, just the current data directory. Users have a lot of difficulties figuring out where exactly their db/keys are located. Sometimes it isn't at the default directory or expected directory as they are mapping a separate volume when running the beacon node in docker. I haven't been able to find an easy way to help them locate their directory when debugging issues like this.

Maybe subcommand might be overkill, what would be something that would improve user's UX in this regard ?

**Comment by 0xKiwi** [comment]
I think #5617 would be a better alternative solution for this, thoughts? A subcommand meant for a flag info seems unneeded, logging it out would be great IMO.

**Comment by nisdas** [comment]
I was shying away from logging this as it gets very easy to miss it especially with novice/new users. Also I think we log the path anyway for validator keys ?

**Comment by 0xKiwi** [comment]
Doesn't seem like we do, validator doesn't log out the DB or the keystore path. I think logging those out would be a good improvement.

**Comment by rkapka** [comment]
Hi!

I would like to be assigned to this issue if that's OK. Should this feature include a test?

**Comment by 0xKiwi** [comment]
Data directory is now logged for the validator client as of #5653 , can we close this?
