### ISSUE TITLE
Segfault inside WSL2 when in shared folder

### ISSUE THREAD

**Issue by Swader** [prysmaticlabs/prysm#5533]
# 🐞 Bug Report

### Description

When running prysm in WSL2 on Windows (Ubuntu 18.04) the beacon-chain segfaults if started from a shared folder. It does not happen if started from within the Linux root.

![image](https://user-images.githubusercontent.com/1430603/79735266-4cc99100-82f8-11ea-8e25-2373c57dde1f.png)

![image](https://user-images.githubusercontent.com/1430603/79735295-5521cc00-82f8-11ea-9ac3-3503e6f405d1.png)

### Has this worked before in a previous version?

n/a

## 🔬 Minimal Reproduction

- Windows 10 insider, slow, updated
- WSL2 installed
- Ubuntu 18.04 installed
- clone repo into `~`
- clone repo into `/mnt/c/somefolder`
- run beacon-chain from each, observe success in former, failure in latter

## 🔥 Error

```bash
swader@DESKTOP-0OEAV37:/mnt/c/Users/Swader/repos/prysm$ ./prysm.sh beacon-chain
Latest Prysm version is v1.0.0-alpha.4.
Beacon chain is up to date.
Validator is up to date.
Starting Prysm beacon-chain
Segmentation fault
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10, insider, slow mode, WSL2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Alpha4
  </code>
</pre>

**Comment by prestonvanloon** [comment]
Can you clarify, are you running a Linux VM within windows?

Is there any issue with using the bash script within windows itself? 

cc: @0xKiwi

**Comment by Swader** [comment]
This is only inside WSL as stated in minimum reqs. The failure happens when launching in a folder outside the VM's root, and does not happen inside the VM's root.

WSL shares the VM's filesystem with the parent OS transparently, and it's accessible via `mnt` through the explorer and other tools like IDEs, but for some reason, this bridging is breaking the script in this case.

In Windows itself (no VM, native) there are no issues with the script.

**Comment by prestonvanloon** [comment]
Thanks for the update. I'm not entirely sure how to proceed with this issue given that I'm not familiar with running linux as a subsystem on windows. Added help wanted flag for now.

**Comment by Phistr90** [comment]
Cannot reproduce on my WSL. OS build 19608.1006.

**Comment by Swader** [comment]
Strange. I can't debug this more right now, but I'll come back to this with more info once I have time to  explore further.

**Comment by wgknowles** [comment]
Followed same steps, got a different result:
```wgknowles@Rig:/mnt/c/Prysm/prysm$ ./prysm.sh beacon-chain
-bash: ./prysm.sh: /bin/bash^M: bad interpreter: No such file or directory```

The ^M indicates that it's not handling the line break correctly.

```C:\>wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Running         2```

**Workaround**
It works just fine if I run prysm.sh from a non-shared folder (e.g. ~\prysm) and specify a datadir in the shared folder.

```wgknowles@Rig:~/prysm$ ./prysm.sh beacon-chain --datadir=/mnt/c/Users\wgknowles\AppData\Roaming\Eth2```

Probably not the best use of time troubleshooting this niche WSL issue to be fair...
