### ISSUE TITLE
Graffiti quotes [minor issue]

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#5536]
# 🐞 Bug Report

Minor issue with the graffiti flag: not possible to get quotes right. Both Prysm and my proposers are having trouble. Yet there are also cases where it parses correctly.

### Description

Quotes in graffiti don't work as expected.
The `"` is included.

### Has this worked before in a previous version?

Not sure.

## 🔬 Minimal Reproduction

Examples:

Mine (quotes included):

 `--graffiti="@protolambda"`

https://beaconcha.in/block/17578

Prysm (one quote, the other is cut off due to length):

https://beaconcha.in/block/17589

Ok:
https://beaconcha.in/block/14793

Note that I supply my argument through Docker entry point flags. And I assume the same for Prysm. Maybe this is not the case for the "ok" version.

## 🔥 Error

No error.

## 🌍  Your Environment

Different environments involved.

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

See examples.

**Comment by protolambda** [comment]
I'm going to try and not use quotes for now, but it would be nice to use spaces etc. in my graffiti.

**Comment by terencechain** [comment]
Thanks for opening this! @protolambda

**Comment by Phistr90** [comment]
AFAIk this worked for me --graffiti "test test"

**Comment by protolambda** [comment]
@Phistr90 Are you running it in docker, using the script, bazel, or other approach?

**Comment by Phistr90** [comment]
@protolambda bazel

**Comment by rauljordan** [comment]
@protolambda is this still an issue for you?

**Comment by protolambda** [comment]
No, works fine for me, I'll close this. Thanks, forgot about this issue.
