### ISSUE TITLE
Could not load blocks for hot state using root: end block roots don't match

### ISSUE THREAD

**Issue by piotrbednarczyk** [prysmaticlabs/prysm#5542]
# 🐞 Bug Report

### Description

 Beacon node fails to process blocks and after several retries output stack trace in the loop. Validator connected to the beacon node gets disconnected from the network as you can see on the validator chart [Validator status](https://beacon.etherscan.io/stat/balance/0x94cdb107e7f365243e12201fc85ca2f6770fcb671c5493bb59195989d30d86c052407dcc55e40a5a1bbb44a8dd7322e2)

After restart everything goes back to norm and processing continues.

## 🔥 Error

[Beacon node logs](https://pastebin.pl/view/98cbea60)
[Validator logs](https://pastebin.pl/view/9f604ad4)

## 🌍  Your Environment

**Operating System:** 

<pre>
  <code>
Ubuntu 18
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
I wish I could say - it's a version in docker container. I have a bit of an issue with getting the version of Prysm from it - cannot connect to container shell.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
[Validator status](https://beacon.etherscan.io/stat/balance/0x94cdb107e7f365243e12201fc85ca2f6770fcb671c5493bb59195989d30d86c052407dcc55e40a5a1bbb44a8dd7322e2)

**Comment by terencechain** [comment]
@piotrbednarczyk What version are you running? This has been fixed 2 days ago

**Comment by rauljordan** [comment]
Hi @piotrbednarczyk if you're using the docker :latest tag you may need to re-fetch from the registry: `docker pull gcr.io/prysmaticlabs/prysm/beacon-chain:latest` and restart your process

**Comment by piotrbednarczyk** [comment]
> @piotrbednarczyk What version are you running? This has been fixed 2 days ago

As I wrote - I have a problem with getting the version info from inside of docker container as I cannot connect to container shell. Is there any command I can execute to do it?

**Comment by rauljordan** [comment]
For docker, if you're using :latest, that means thats the current, cutting-edge version of our beacon node. It is likely you need to pull down the latest image if it hasn't been updated in a while.

**Comment by rauljordan** [comment]
We would recommend doing so as well for the validator client if needed. This tool exists to help refetch docker images if they change and restart their processes automatically: https://github.com/containrrr/watchtower

**Comment by piotrbednarczyk** [comment]
Ok, I will try to refetch the newest version and will check if the issue will take place again.
