### ISSUE TITLE
Add slasher to prysm.sh and future releases

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5549]
# 🚀 Feature Request

### Description

- Add slasher binaries to releases.
- Add slasher to prysm.sh

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by rauljordan** [comment]
Done in the latest release https://github.com/prysmaticlabs/prysm/tree/v1.0.0-alpha.5

**Comment by prestonvanloon** [comment]
Done in https://github.com/prysmaticlabs/prysm/pull/5543
