### ISSUE TITLE
validator accounts create - check if shardwithdrawalkey and validatorprivatekey written to disk before generating ETH1 Deposit TX

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm#5552]
# 🐞 Bug Report

### Description

When running the "validator accounts create" function with a keystore-path that doesn't exist, a ETH1 deposit TX is generated despite the fact that shardwithdrawalkey and validatorprivatekey have note been written to disk.  Many users are likely to not realise this is a problem until after they have sent their ETH1 to the deposit contract.

### Has this worked before in a previous version?
n/a

## 🔬 Minimal Reproduction

Note: In the example below, the folder c:\validator does not exist in the filesystem

docker run -it gcr.io/prysmaticlabs/prysm/validator:latest accounts create --keystore-path=c:/validator --password=changeme
2020/04/21 10:50:27 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
[2020-04-21 10:50:27]  WARN flags: Using default mainnet config
[2020-04-21 10:50:28]  INFO accounts: Keystore generated for shard withdrawals at path path=c:/validator/shardwithdrawalkeyb0b0b5b4f8ed
[2020-04-21 10:50:29]  INFO accounts: Keystore generated for validator signatures at path path=c:/validator/validatorprivatekey9796d4b39fb8
[2020-04-21 10:50:29]  INFO accounts: Account creation complete! Copy and paste the raw transaction data shown below when issuing a transaction into the ETH1.0 deposit contract to activate your validator client

========================Raw Transaction Data=======================

0x22895118000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120287d67b4bed7cbd71242d61a14628d77e718f0cd2409372d3eeb23e454f6d97e00000000000000000000000000000000000000000000000000000000000000309796d4b39fb818be34543dceaf19af18aaf993f3160fdbd0655ac7370dbdbe2c258dbb7f1df5b009917d4e29124377a90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200065812e59c3308a0ea37bf44785f0ad59bd4a3a9ba06da8107fe3f6359c9eab000000000000000000000000000000000000000000000000000000000000006098f49e65393206ae0381243edc26e595e54ffed7f5c19772a0a365908f7420621d2fe4de3f8b7dbbc615b34a90844f1a13b26b0dbd68413d471b7c72944369c928e0e175f6a9652507a6e298b87c5671adc77fc4e24180ee9f473f2f877d85b7

===================================================================

## 🔥 Error
n/a

## 🌍  Your Environment

Win10 w/ docker

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
INFO node: Starting validator node version=Prysm/Git commit: c0ca56717524014dca1d5e48b7ec729b85e55bac. Built at: 2020-04-18 06:00:30+00:00
  </code>
</pre>

**Comment by nisdas** [comment]
As a basic requirement for this issue to be resolved, we will need to verify paths are valid beforehand before writing keys to that particular directory. I was able to reproduce this by giving my validator a garbage path.

**Comment by Domintek** [comment]
I have had this very same issue running docker on Linux PoP!_OS 19.10 with the version of docker listed here:
domintek@pop-os:~$ docker -v
Docker version 19.03.6, build 369ce74a3c

Did not have this problem on the sapphire iteration of the validator.

My work around is to run beacon-node in docker and run validator in script.

**Comment by prestonvanloon** [comment]
Additionally, you need to correctly mount the volumes in docker. The process likely did write to the container's disk, but that disk is not mounted on your host machine. Please follow the instructions for the correct flags on https://docs.pryslabs.network or https://prylabs.net
