### ISSUE TITLE
Initial sync first slot takes a long time

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5562]
# 🐞 Bug Report

### Description

Thanks @nisdas for reporting this. `verifyBlkPreState` takes a long time to start up for initial syncing when processing the first block. It was regenerating the state from very far away check point.  For initial syncing, instead of using ~~last finalized slot~~ head slot, we should use last saved slot or last archived slot

**Comment by farazdagi** [comment]
Some relevant context: when `init-sync` starts it obtains head slot, finds its epoch and proceeds from there: https://github.com/prysmaticlabs/prysm/blob/db6dbdcde4bdd8167ff3277c2c53dc0909a254c3/beacon-chain/sync/initial-sync/blocks_queue.go#L138

**Comment by prestonvanloon** [comment]
What's wrong with syncing from last finalized? Syncing from last finalized chain might make it easier to sync if you shut down your node and the head of your chain was orphaned. 

If we move forward on this functionality, please make it configurable at runtime via flag.

**Comment by terencechain** [comment]
For running `new-state-mgmt` we should use `last-finalized-slot` there instead of `head-slot` since a node doesn't preserve states in the DB as often

**Comment by rauljordan** [comment]
Is this still relevant @terencechain @farazdagi ? Please close if complete

**Comment by terencechain** [comment]
still exists

**Comment by rauljordan** [comment]
Latest status on this one @terencechain ?

**Comment by terencechain** [comment]
Haven't really seen this with onyx. Will close this until it raises up again
