### ISSUE TITLE
Show STATUS when running ./validator accounts keys

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5578]
Would help if `./validator accounts keys` displays the current status of each key and their inclusionslot, ordered by their status.

**Comment by terencechain** [comment]
Good feature. Thanks @Buttaa

**Comment by michaelhly** [comment]
For this issue, should I just add a new "status" command [here](https://github.com/prysmaticlabs/prysm/blob/2f88174d0d8822ed2f64bbf1f47cd42db018f0af/validator/main.go#L92) and call the `GetValidator` method on the BeaconChainClient to fetch the statuses?

Or should I do this do it under the "key" command?

**Comment by michaelhly** [comment]
I took an attempt at writing a method that fetches account statuses from the BeaconNodeValidatorClient. Let me know if I am going in the right direction.
