### ISSUE TITLE
Add update option in prysm.sh

### ISSUE THREAD

**Issue by Yoldark34** [prysmaticlabs/prysm#5580]
# 🚀 Feature Request

### Description

The option allow to update beacon and validator files without the need to restart them before.
In order to gain time and avoid putting node offline for too long it is a good idea to update the process in background and then restart the beacon/validator.
At the actual state of prysm.sh this solution is already feasible.

prysm.sh update

It will update the beacon and the validator without the need of shutting them down. Then it will throw an error because the command is not defined.

> user@user:~$ prysm/prysm.sh update
> Latest Prysm version is v1.0.0-alpha.5.
> Beacon chain is up to date.
> Validator is up to date.
> Usage: ./prysm.sh PROCESS FLAGS.
> PROCESS can be beacon-chain or validator.
> Starting Prysm update
> prysm/prysm.sh: ligne 152: process : variable sans liaison

Implementing the command to display a success message or nothing is enough for the feature to work.
The user may then restart the node the way that it choose to.

### Describe the solution you'd like

Implement the update option in prysm.sh script file
It should display as this :

> user@user:~$ prysm/prysm.sh update
> Latest Prysm version is v1.0.0-alpha.5.
> Beacon chain is up to date.
> Validator is up to date.

or do the update if needed.

### Describe alternatives you've considered

We do nothing as it kind of work by itself.

**Comment by prestonvanloon** [comment]
We were also considering whether or not Prysm itself could download the binary in the background and periodically recommend to the user to restart the process. 

In any case, I support your proposal to download the latest binaries without starting the process so that the end user can minimize their downtime.

**Comment by Yoldark34** [comment]
If you want to make the download available in the background you must add the option to disable it as it may not be the best solution to every person.
And you will still need a way to download it by user command.
