### ISSUE TITLE
Rewards penalty bugs and resolution steps

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5593]
# 🐞 Bug Report
protolambda
### Background
Thanks to @protolambda and co, we found a few rewards and penalty bugs in prysm while doing interop testing with lighthouse. The bugs **don't** break topaz testnet or affect single client users negatively, the current decision is to keep topaz testnet and launch individual devnet with this fix to use for interop with lighthouse and others. This bug is non-substantive to the current validator and beacon node run time within the scope of single client testnet

### Resolution steps
* Fix bug to correct sum for target and head instead of source
* Fix bug for reward numerator overflow
* Launch devnet with this branch

**Comment by protolambda** [comment]
The scope of the bug is bigger here than just the overflow bug, please see my review here: https://github.com/prysmaticlabs/prysm/pull/5127#pullrequestreview-398976613

**Comment by terencechain** [comment]
> The scope of the bug is bigger here than just the overflow bug, please see my review here: [#5127 (review)](https://github.com/prysmaticlabs/prysm/pull/5127#pullrequestreview-398976613)

updated description, thank you

**Comment by terencechain** [comment]
Closing this as #5595 merged and @rauljordan provided instructions on setting up local prysm node for interop:
https://gist.github.com/rauljordan/d3d200197a3ce7370f060e111079ad64
