### ISSUE TITLE
Validator "Previous epoch voting summary" info message prints the wrong pubKey if two keys are in the same keymanager directory

### ISSUE THREAD

**Issue by mshean** [prysmaticlabs/prysm#5600]
# 🐞 Bug Report

### Description

 Validator "Previous epoch voting summary" info message prints the wrong pubKey if two keys are in the same directory. See the below logs for an example. 0xa7976999cafdfa24 is a key which is pending activation and is not valid yet. 0x949308ca28d2 is the key which is active and attesting, but it's not showing in the log message correctly. I discovered this while trying to make two pubkeys run on a single validator.

### Has this worked before in a previous version?

 Unknown

## 🔬 Minimal Reproduction

Create a validator keypair, fund it, wait for activation
Create a second validator keypair in another directory, then move the second keypair into the first keypair's directory.
Observe incorrect log messages

## 🔥 Error

<pre><code>

[2020-04-23 20:09:36]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x949308ca28d2] slot=42048
[2020-04-23 20:16:00]  INFO validator: Previous epoch voting summary correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=1314 inclusionDistance=1 inclusionSlot=41991 newBalance=64.020823481 oldBalance=64.02074911 percentChange=0.00012% pubKey=0xa7976999cafdfa24
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
docker desktop for macOS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain version 7c986ca6f95d
gcr.io/prysmaticlabs/prysm/validator version 7194c01ac0e9

validator git commit version 49ca0751b6e37387b6df5a56d68980f93ccf377b
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by shayzluf** [comment]
@0xKiwi please feel free to reassign to me
