### ISSUE TITLE
Update prysm to v0.12

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5603]
Opening this issue to track updating prysm to v0.12. The on-going branch getting worked on is here:
https://github.com/ethereum/eth2.0-specs/tree/v012x

**Comment by prestonvanloon** [comment]
Assigned to @terencechain as owner for v0.12. If this is not appropriate, please assign to me.

**Comment by terencechain** [comment]
@nisdas has been doing great work on this, will put him as an assignee so I don't get all the credit : )

**Comment by terencechain** [comment]
Deprecating this to favor #5935
