### ISSUE TITLE
Prysm launches beacon chain 1 hour before Lighthouse

### ISSUE THREAD

**Issue by q9f** [prysmaticlabs/prysm#5616]
# 🐞 Bug Report

### Description

Prysm launches beacon chain 1 hour before Lighthouse. I created a chain yesterday with the following config:

- min genesis time 1587755000 (7:03:20 pm UTC)
- min genesis delay 3600

However, both Prysm and Lighthouse did compute different genesis times:
- Prysm computed genesis time 8:00:00 pm UTC
- Lighthouse computed genesis time 9:00:00 pm UTC

### Has this worked before in a previous version?

N/A

## 🔬 Minimal Reproduction

I created a Schlesi config for Prysm to be able to hack the genesis delay:

https://github.com/prysmaticlabs/prysm/compare/v0.12...byz-f:q9-schlesi-config?expand=1

For Lighthouse, I uploaded the spec here: https://github.com/goerli/schlesi

## 🔥 Error

Lighthouse genesis time:

```
Apr 24 21:35:26.680 INFO Starting node prior to genesis          seconds_to_wait: 5073
```
The timestamp is UTC+2, so genesis time in Lighthouse is 9:00:00 pm UTC.

Prysm genesis time:

```
[2020-04-24 20:35:50]  WARN initial-sync: Genesis time is in the future - waiting to start sync... genesis time=2020-04-24 22:00:00 +0200 CEST
```

The timestamp is UTC+2, so genesis time in Prysm is 8:00:00 pm UTC.

## 🌍  Your Environment

**Operating System:**

Arch Linux with Bazel.

**What version of Prysm are you running? (Which release)**

Prysm from the `v0.12` branch with the consensus patch and Lighthouse compiled from master.

**Anything else relevant (validator index / public key)?**

~~I believe the error is on Prysm side here.~~ Update, see below.

**Comment by q9f** [comment]
Update, from the spec:

https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#genesis

```
genesis_time=eth1_timestamp - eth1_timestamp % MIN_GENESIS_DELAY + 2 * MIN_GENESIS_DELAY,
```

1587755000 - mod(1587755000; 3600) + 2 * 3600 = 1587762000

Which is 9:00:00 pm UTC if `eth1_timestamp` is equal or greater than `MIN_GENENIS_TIME` but @nisdas just explained me that `eth1_timestamp` can also be lower than that which might be the case here because I did the deposits significantly before `MIN_GENENIS_TIME`.

Forwarding that question to the Lighthouse team. @paulhauner Does your client do any checks to enforce `eth1_timestamp` to be greater than `MIN_GENENIS_TIME`? Or do you have any idea why Lighthouse computes a different genesis time than Prysm?

**Comment by q9f** [comment]
This is the block: https://goerli.etherscan.io/block/2581357

Timestamp is `1587752706` (6:25:06 pm UTC | Friday, April 24, 2020)

```
1587752706 - mod(1587752706;3600) + 2 * 3600
= 1587758400
```

Genesis time is `1587758400` (8:00:00 pm UTC | Friday, April 24, 2020)

So, Prysm is correct. Wondering why Lighthouse would come up with a timestamp one hour later...

**Comment by paulhauner** [comment]
Yep, looks like this is on our end. I've picked it up here:

https://github.com/sigp/lighthouse/issues/1051

Thanks @q9f!
