### ISSUE TITLE
When GPG is not installed on macOS, running beacon-chain fails with "failed_verification: numeric argument required"

### ISSUE THREAD

**Issue by bp1313** [prysmaticlabs/prysm#5625]
**Description:**
I tried to set up the beacon-chain and validator on the Topaz Testnet following the steps defined here for macOS:
https://docs.prylabs.network/docs/install/mac/

I ran this:
`./prysm.sh beacon-chain --clear-db`

and got this:
`Latest Prysm version is v1.0.0-alpha.5.
Downloading beacon chain@v1.0.0-alpha.5 to /Users/[redacted]/prysm2/./dist/beacon-chain-v1.0.0-alpha.5-darwin-amd64 (automatically selected latest available version)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39.5M  100 39.5M    0     0  16.6M      0  0:00:02  0:00:02 --:--:-- 16.6M
gpg is not available. Not verifying integrity of downloaded binary.
./prysm.sh: line 117: return: failed_verification: numeric argument required`.

Looking at line 117, there is a check for GPG. I guess my Mac did not have GPG? So I installed it and I was able to start my beacon-chain successfully.

Should there be a more user friendly message here? Or should the macOS installation guide be updated to include GPG installation?

**System config:**
macOS 10.15.5

**Comment by prestonvanloon** [comment]
The script is supposed to print a nice message. Thanks for filing this, there is definitely a bug.

https://github.com/prysmaticlabs/prysm/blob/faa5b309a297a3bb53672c2672c301310fbda0a8/prysm.sh#L133-L138
