### ISSUE TITLE
p2p_message_failed_validation_total for beacon_block is above 30%

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5630]
# 🐞 Bug Report

### Description

`p2p_message_failed_validation_total` for `beacon_block` is high. Opening this issue for investigation:

<img width="2538" alt="Screen Shot 2020-04-26 at 11 53 25 AM" src="https://user-images.githubusercontent.com/21316537/80316839-01f6c000-87b5-11ea-8f5c-da6ad8583998.png">

**Comment by terencechain** [comment]
Looked at this today. All the failed blocks were rejected by the `hasSeenBlockIndexSlot` cache:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/sync/validate_beacon_blocks.go#L55

That means the block was already passed validation but sync received again. Not an issue imo. Will close this if there's no more feedback in the next few days

**Comment by rauljordan** [comment]
Update on this one @terencechain ?

**Comment by terencechain** [comment]
No update yet. It's something to look into soon
