### ISSUE TITLE
Update RPC method `GetValidatorPerformance` to use validator indices

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5631]
# 🚀 Feature Request

### Description

Update RPC method `GetValidatorPerformance` to take also take in validator indices. 
Since we do support validator indices in other RPC methods. It'll be good to be consistent

**Comment by michaelhly** [comment]
Hey @terencechain. I was trying to implement this, but it looks like there is not an `Indices` field on `eth.ValidatorPerformanceRequest`.

This is the error I get when I try to test:
```
/private/var/tmp/_bazel_root/c240bada98f93dedfa31ab6c89c0c2d0/sandbox/darwin-sandbox/1328/execroot/prysm/beacon-chain/rpc/beacon/validators.go:937:24: req.Indices undefined (type *eth.ValidatorPerformanceRequest has no field or method Indices)
```

Perhaps I need to create a PR here first to add an Indices field?
https://github.com/prysmaticlabs/ethereumapis/blob/ba9042096e9fc49606279513d3e24e5e8cdbd5a0/eth/v1alpha1/beacon_chain.proto#L617

**Comment by terencechain** [comment]
> Hey @terencechain. I was trying to implement this, but it looks like there is not an `Indices` field on `eth.ValidatorPerformanceRequest`.
> 
> This is the error I get when I try to test:
> 
> ```
> /private/var/tmp/_bazel_root/c240bada98f93dedfa31ab6c89c0c2d0/sandbox/darwin-sandbox/1328/execroot/prysm/beacon-chain/rpc/beacon/validators.go:937:24: req.Indices undefined (type *eth.ValidatorPerformanceRequest has no field or method Indices)
> ```
> 
> Perhaps I need to create a PR here first to add an Indices field?
> https://github.com/prysmaticlabs/ethereumapis/blob/ba9042096e9fc49606279513d3e24e5e8cdbd5a0/eth/v1alpha1/beacon_chain.proto#L617

That's correct. Do you mind doing that? Thanks
