### ISSUE TITLE
[UX] No connection log when a validator connect to a beacon-chain node

### ISSUE THREAD

**Issue by Magicking** [prysmaticlabs/prysm#5647]
# 🐞 Bug Report

### Description

No logs of connection are shown from a beacon-chain journal when a validator connects to a beacon-chain node while there is an indication of connection/disconnection for a network peer at the same level of verbosity when syncing.

### Has this worked before in a previous version?

Not sure.

## 🔬 Minimal Reproduction

Beacon-chain: 
<pre>
  <code>docker run -d -u `id -u` -v `pwd`/prysm-beacon:/data -p '0.0.0.0:4000:4000' gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data --log-file=/data/beacon-1.log
  </code>
</pre>
Validator: 
<pre>
  <code>docker run -d -u `id -u` -v `pwd`/prysm-data:/data gcr.io/prysmaticlabs/prysm/validator:latest --datadir=/data --log-file=/data/validator-1.log --keymanager=keystore --keymanageropts '{ "path": "/data", "passphrase": "changeme" }' --beacon-rpc-provider $BEACON_HOST:4000
  </code>
</pre>

## 🔥 Error

No error.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
NixOS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
time="2020-04-27 11:18:06" level=info msg="Starting beacon node" prefix=node version="Prysm/Git commit: eb5513f8c209c6f1254f9cc311202f59c3570d3e. Built at: 2020-04-27 07:06:03+00:00"
time="2020-04-27 11:32:03" level=info msg="Starting validator node" prefix=node version="Prysm/Git commit: eb5513f8c209c6f1254f9cc311202f59c3570d3e. Built at: 2020-04-27 06:54:49+00:00"

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
<pre>
Beacon-chain
[magicking@broken:~/prysm/prysm-validator]$ docker logs 71fd9e6da227 | head
2020/04/27 11:32:00 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
time="2020-04-27 11:32:00" level=info msg="Logs will be made persistent" logFileName="/data/validator-1.log"
time="2020-04-27 11:32:00" level=info msg="File logging initialized"
time="2020-04-27 11:32:00" level=warning msg="Using default mainnet config" prefix=flags
time="2020-04-27 11:32:00" level=warning msg="Disabled validator proposal slashing protection." prefix=flags
time="2020-04-27 11:32:00" level=warning msg="Disabled validator attestation slashing protection." prefix=flags
time="2020-04-27 11:32:03" level=info msg="Validating for public key" prefix=node pubKey=0xa6049454baa25acafa53af84b2ab690ac9fbed97078a05a77751785d02753d5d3532d0a0429e6d5f867c6e078d3f4f3f
time="2020-04-27 11:32:03" level=info msg="Validating for public key" prefix=node pubKey=0xb1ef0fec56aeee43a7e0adf97bc3faf00b7314b46c834713b476df79dfd720d447afa5c2207c8ec2d4d29610fe2bf17b
time="2020-04-27 11:32:03" level=info msg="Starting validator node" prefix=node version="Prysm/Git commit: eb5513f8c209c6f1254f9cc311202f59c3570d3e. Built at: 2020-04-27 06:54:49+00:00"
time="2020-04-27 11:32:03" level=warning msg="You are using an insecure gRPC connection! Please provide a certificate and key to use a secure connection." prefix=validator
time="2020-04-27 11:32:03" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator
time="2020-04-27 11:32:03" level=info msg="Beacon chain started" genesisTime=2020-04-18 00:00:00 +0000 UTC prefix=validator

Validator:
[magicking@broken:~/prysm/prysm-validator]$ docker logs 1331 | grep "2020-04-27 11:32:0"
2020/04/27 11:18:06 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
time="2020-04-27 11:18:06" level=info msg="Logs will be made persistent" logFileName="/data/beacon-1.log"
time="2020-04-27 11:32:00" level=info msg="Processing block 17905/68259 - estimated time remaining 23m52s" blocksPerSecond=35.1 peers=11 prefix=initial-sync
[...]
time="2020-04-27 11:32:01" level=info msg="Processing block 17982/68260 - estimated time remaining 23m34s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17983/68260 - estimated time remaining 23m32s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17984/68260 - estimated time remaining 23m30s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17985/68260 - estimated time remaining 23m28s" blocksPerSecond=35.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17986/68260 - estimated time remaining 23m26s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17987/68260 - estimated time remaining 23m24s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17988/68260 - estimated time remaining 23m22s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17989/68260 - estimated time remaining 23m20s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17990/68260 - estimated time remaining 23m18s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17991/68260 - estimated time remaining 23m16s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17992/68260 - estimated time remaining 23m14s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17993/68260 - estimated time remaining 23m12s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17994/68260 - estimated time remaining 23m10s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17995/68260 - estimated time remaining 23m8s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17996/68260 - estimated time remaining 23m6s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17997/68260 - estimated time remaining 23m4s" blocksPerSecond=36.3 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17998/68260 - estimated time remaining 23m2s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 17999/68260 - estimated time remaining 23m0s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18000/68260 - estimated time remaining 22m58s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18001/68260 - estimated time remaining 22m56s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18002/68260 - estimated time remaining 22m55s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18004/68260 - estimated time remaining 22m53s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18005/68260 - estimated time remaining 22m51s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18006/68260 - estimated time remaining 22m49s" blocksPerSecond=36.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18007/68260 - estimated time remaining 22m47s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18008/68260 - estimated time remaining 22m45s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18009/68260 - estimated time remaining 22m43s" blocksPerSecond=36.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18010/68260 - estimated time remaining 22m41s" blocksPerSecond=36.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18011/68260 - estimated time remaining 23m39s" blocksPerSecond=35.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18012/68260 - estimated time remaining 23m37s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18013/68260 - estimated time remaining 23m35s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18014/68260 - estimated time remaining 23m33s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18015/68260 - estimated time remaining 23m31s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:02" level=info msg="Processing block 18016/68260 - estimated time remaining 23m29s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18017/68260 - estimated time remaining 23m27s" blocksPerSecond=35.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18018/68260 - estimated time remaining 23m25s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18019/68260 - estimated time remaining 23m23s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18020/68260 - estimated time remaining 23m21s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18021/68260 - estimated time remaining 23m19s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18022/68260 - estimated time remaining 23m17s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18023/68260 - estimated time remaining 23m15s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18024/68260 - estimated time remaining 23m13s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18025/68260 - estimated time remaining 23m11s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18026/68260 - estimated time remaining 23m9s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18027/68260 - estimated time remaining 23m7s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18028/68260 - estimated time remaining 23m5s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18030/68260 - estimated time remaining 23m3s" blocksPerSecond=36.3 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18031/68260 - estimated time remaining 23m1s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18032/68260 - estimated time remaining 22m59s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18033/68260 - estimated time remaining 22m57s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18034/68260 - estimated time remaining 22m56s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18035/68260 - estimated time remaining 22m54s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18036/68260 - estimated time remaining 22m52s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18037/68260 - estimated time remaining 22m50s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18038/68260 - estimated time remaining 22m48s" blocksPerSecond=36.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18039/68260 - estimated time remaining 22m46s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18040/68260 - estimated time remaining 22m44s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18041/68260 - estimated time remaining 22m42s" blocksPerSecond=36.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18042/68260 - estimated time remaining 22m40s" blocksPerSecond=36.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18043/68260 - estimated time remaining 22m39s" blocksPerSecond=37.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18044/68260 - estimated time remaining 22m37s" blocksPerSecond=37.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18045/68260 - estimated time remaining 22m35s" blocksPerSecond=37.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18046/68260 - estimated time remaining 22m33s" blocksPerSecond=37.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18047/68260 - estimated time remaining 22m31s" blocksPerSecond=37.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:03" level=info msg="Processing block 18048/68260 - estimated time remaining 22m29s" blocksPerSecond=37.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18049/68260 - estimated time remaining 23m44s" blocksPerSecond=35.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18050/68260 - estimated time remaining 23m42s" blocksPerSecond=35.3 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18051/68260 - estimated time remaining 23m40s" blocksPerSecond=35.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18052/68260 - estimated time remaining 23m38s" blocksPerSecond=35.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18053/68260 - estimated time remaining 23m36s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18054/68260 - estimated time remaining 23m34s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18055/68260 - estimated time remaining 23m32s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18056/68260 - estimated time remaining 23m30s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18057/68260 - estimated time remaining 23m28s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18058/68260 - estimated time remaining 23m26s" blocksPerSecond=35.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18059/68260 - estimated time remaining 23m24s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18060/68260 - estimated time remaining 23m22s" blocksPerSecond=35.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18061/68260 - estimated time remaining 23m20s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18062/68260 - estimated time remaining 23m18s" blocksPerSecond=35.9 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18063/68260 - estimated time remaining 23m16s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18064/68260 - estimated time remaining 23m14s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18065/68260 - estimated time remaining 23m12s" blocksPerSecond=36.0 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18066/68260 - estimated time remaining 23m10s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18067/68260 - estimated time remaining 23m8s" blocksPerSecond=36.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18068/68260 - estimated time remaining 23m6s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18069/68260 - estimated time remaining 23m4s" blocksPerSecond=36.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18070/68260 - estimated time remaining 23m2s" blocksPerSecond=36.3 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18071/68260 - estimated time remaining 23m0s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18072/68260 - estimated time remaining 22m58s" blocksPerSecond=36.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18073/68260 - estimated time remaining 22m56s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18074/68260 - estimated time remaining 22m54s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18075/68260 - estimated time remaining 22m53s" blocksPerSecond=36.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18076/68260 - estimated time remaining 22m51s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18077/68260 - estimated time remaining 22m49s" blocksPerSecond=36.6 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18078/68260 - estimated time remaining 22m47s" blocksPerSecond=36.7 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18079/68260 - estimated time remaining 22m45s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18080/68260 - estimated time remaining 22m43s" blocksPerSecond=36.8 peers=11 prefix=initial-sync
time="2020-04-27 11:32:04" level=info msg="Processing block 18081/68260 - estimated time remaining 23m47s" blocksPerSecond=35.1 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18082/68260 - estimated time remaining 23m45s" blocksPerSecond=35.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18083/68260 - estimated time remaining 23m43s" blocksPerSecond=35.2 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18084/68260 - estimated time remaining 23m41s" blocksPerSecond=35.3 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18085/68260 - estimated time remaining 23m39s" blocksPerSecond=35.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18086/68260 - estimated time remaining 23m37s" blocksPerSecond=35.4 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18087/68260 - estimated time remaining 23m35s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18088/68260 - estimated time remaining 23m33s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18089/68260 - estimated time remaining 23m31s" blocksPerSecond=35.5 peers=11 prefix=initial-sync
time="2020-04-27 11:32:05" level=info msg="Processing block 18090/68260 - estimated time remaining 23m29s" blocksPerSecond=35.6 peers=11 prefix=initial-sync
[...]
time="2020-04-27 11:32:09" level=info msg="Processing block 18277/68260 - estimated time remaining 23m54s" blocksPerSecond=34.9 peers=11 prefix=initial-sync
</pre>

**Comment by prestonvanloon** [comment]
I'm not sure we want to support this, at least at INFO level. Given that the API is stateless and the validator client has the option to load balance between many beacon nodes, I think this type of functionality will only create noise in the logs, especially if validators are bouncing between beacon nodes.

**Comment by Magicking** [comment]
That makes senses, I opened it as a bug because from a network standpoint, I was surprised to see other software connecting in logs while not seeing the validator connecting.
The context was that I was trying to help a user to know if its validator was connecting well to its local beacon-chain or not.

**Comment by prestonvanloon** [comment]
I'm not totally opposed to adding this. It isn't a feature that I would use but if there is user interest then I think we can add it, as long as it can be disabled with a flag. (--disable-validator-connection-logs) or something like that.

**Comment by ShawkiS** [comment]
Hi @prestonvanloon, I'll work on it

**Comment by prestonvanloon** [comment]
Please finish your other assigned issues before picking up another one. #5450 #5439

**Comment by ShawkiS** [comment]
Okay, I'll finish them asap
