### ISSUE TITLE
Fuzz: libp2p panic: inconsistent poll.fdMutex

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5703]
# 🐞 Bug Report

### Description

Fuzz test failed in a unique way when testing attestation processing. 
Given that the class under test has nothing to do with libp2p, I am wondering why yamux was failing.

https://github.com/prysmaticlabs/prysm/blob/b4a178a499958411b3f15cdd7ab47cda578e1244/fuzz/attestation_fuzz.go#L28

![deps](https://user-images.githubusercontent.com/7246818/80780576-5e930b80-8b24-11ea-8518-83b9cf61874e.png)

### Has this worked before in a previous version?

N/A

## 🔥 Error

<pre><code>FUZZER: panic: inconsistent poll.fdMutex
FUZZER: 
FUZZER: goroutine 238 [running]:
FUZZER: internal/poll.(*fdMutex).rwunlock(0x10c00008e370, 0x1, 0x10c0000d1090)
FUZZER: 	GOROOT/src/internal/poll/fd_mutex.go:179 +0x111
FUZZER: internal/poll.(*FD).readUnlock(0x10c00008e370)
FUZZER: 	GOROOT/src/internal/poll/fd_mutex.go:231 +0x34
FUZZER: internal/poll.(*FD).Read(0x10c0007cc100, 0x10c0000d1090, 0x4, 0x4, 0x4, 0x0, 0x0)
FUZZER: 	GOROOT/src/internal/poll/fd_unix.go:181 +0x1e7
FUZZER: net.(*netFD).Read(0x10c0007cc100, 0x10c0000d1090, 0x4, 0x4, 0x7f30fb913b88, 0x10c00008dc68, 0x8570b2)
FUZZER: 	GOROOT/src/net/fd_unix.go:202 +0x51
FUZZER: net.(*conn).Read(0x10c0007d0010, 0x10c0000d1090, 0x4, 0x4, 0x0, 0x0, 0x0)
FUZZER: 	GOROOT/src/net/net.go:184 +0x90
FUZZER: io.ReadAtLeast(0x7f30ce142338, 0x10c0007ca2d0, 0x10c0000d1090, 0x4, 0x4, 0x4, 0x855703, 0x788180, 0xffffffffffffffff)
FUZZER: 	GOROOT/src/io/io.go:310 +0x89
FUZZER: io.ReadFull(...)
FUZZER: 	GOROOT/src/io/io.go:329
FUZZER: github.com/libp2p/go-msgio.ReadLen(0x7f30ce142338, 0x10c0007ca2d0, 0x10c0000d1090, 0x4, 0x4, 0x7880f0, 0x0, 0x0)
FUZZER: 	external/com_github_libp2p_go_msgio/num.go:27 +0xb7
FUZZER: github.com/libp2p/go-msgio.(*reader).nextMsgLen(0x10c0000d1080, 0x2c, 0x40, 0xc)
FUZZER: 	external/com_github_libp2p_go_msgio/msgio.go:178 +0xd0
FUZZER: github.com/libp2p/go-msgio.(*reader).NextMsgLen(0x10c0000d1080, 0x0, 0x0, 0x0)
FUZZER: 	external/com_github_libp2p_go_msgio/msgio.go:173 +0xa9
FUZZER: github.com/libp2p/go-libp2p-secio.(*etmReader).Read(0x10c0003a50e0, 0x10c000131080, 0xc, 0xc, 0x0, 0x0, 0x0)
FUZZER: 	external/com_github_libp2p_go_libp2p_secio/rw.go:163 +0x136
FUZZER: io.ReadAtLeast(0x7f30ce197ad8, 0x10c000d6a000, 0x10c000131080, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
FUZZER: 	GOROOT/src/io/io.go:310 +0x89
FUZZER: io.ReadFull(...)
FUZZER: 	GOROOT/src/io/io.go:329
FUZZER: github.com/libp2p/go-yamux.(*Session).recvLoop(0x10c000566410, 0x0, 0x0)
FUZZER: 	external/com_github_libp2p_go_yamux/session.go:507 +0x109
FUZZER: github.com/libp2p/go-yamux.(*Session).recv(0x10c000566410)
FUZZER: 	external/com_github_libp2p_go_yamux/session.go:486 +0x3c
FUZZER: created by github.com/libp2p/go-yamux.newSession
FUZZER: 	external/com_github_libp2p_go_yamux/session.go:129 +0x3f8
FUZZER: ==137== ERROR: libFuzzer: deadly signal
FUZZER:     #0 0x82a041 in __sanitizer_print_stack_trace /local/mnt/workspace/bcain_clang_bcain-ubuntu_23113/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_stack.cc:86:3
FUZZER:     #1 0x78a718 in fuzzer::PrintStackTrace() /local/mnt/workspace/bcain_clang_bcain-ubuntu_23113/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:205:5
FUZZER:     #2 0x770853 in fuzzer::Fuzzer::CrashCallback() /local/mnt/workspace/bcain_clang_bcain-ubuntu_23113/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:232:3
FUZZER:     #3 0x7f30fecad0df  (/lib/x86_64-linux-gnu/libpthread.so.0+0x110df)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm_fuzzit:v0.11.0
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
b4a178a499958411b3f15cdd7ab47cda578e1244
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

edit: Fuzzit link https://app.fuzzit.dev/orgs/prysmaticlabs-gh/targets/attestation/qOt7HJQMihZLZeoxqxea

**Comment by prestonvanloon** [comment]
My immediate thinking is that something is being created in an Init function.

**Comment by prestonvanloon** [comment]
New thinking: This is broadcast related. I didn't find any evidence of Init() related side effects in the above dependency tree. I'll dig more into this tomorrow. We might want to mock out p2p Broadcast for fuzz testing.

**Comment by nisdas** [comment]
This looks like an issue with the test setup. That fuzz target has nothing to do with libp2p, so maybe something is leaking from our other tests.

**Comment by prestonvanloon** [comment]
Yeah, it's really odd though I don't see anything in the direct codepath.

**Comment by prestonvanloon** [comment]
One thing I can do is try to reduce the dependencies for each fuzz target. Right now they share a big set of common deps

https://github.com/prysmaticlabs/prysm/blob/2daab015b1043d19ca879a02a797ce8f5fc8bc6e/fuzz/BUILD.bazel#L44-L68

**Comment by prestonvanloon** [comment]
OK this is a much better graph. Now, only a single fuzz test involves p2p.

![deps](https://user-images.githubusercontent.com/7246818/80782691-095af800-8b2c-11ea-9d43-bfb5d54d1608.png)

**Comment by prestonvanloon** [comment]
Closing this since it's likely just poor test setup.
