### ISSUE TITLE
Add a Check for Validity to CheckBit Method

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#571]
In the shared sub-package in the repo, there is a helper function called `CheckBit` which is used to check for the existence of a bit in a bitfield. However the method panics whenever an index that does not exist in the bitfield is used in the function. 

A PR to solve this issue would instead return an error if an invalid index is used in conjunction with the inputted bitfield. The function signature should look like this:
```golang 
func CheckBit(bitfield []byte, index int) (bool,error) 
```

**Comment by rawfalafel** [comment]
Does this happen in the tests or in production? There's already validation to ensure bitfields are the correct length: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/casper/validator.go#L73

**Comment by nisdas** [comment]
I came up across this during testing, but also `shared.CheckBit` is used by itself across the repo. It would be better to have the check in the function rather than outside of it.
