### ISSUE TITLE
Confirm password during "validator accounts create"

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm#5715]
# 🚀 Feature Request

### Description
"validator accounts create" asks for a password when run without the --password flag, however the prompt is easy to miss, and doesn't provide good UX.  Many users are reporting that they can't decrypt their keys, likely due to stray keystrokes or right click pastes at this point.

### Describe the solution you'd like
Improve the UX for providing interactive password and require confirmation of the provided password to ensure it was entered correctly.

**Comment by shayzluf** [comment]
@0xKiwi please reassign to me if you find the assignment inappropriate
