### ISSUE TITLE
Validator status DEPOSITED never returned to Prometheus metrics

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#5720]
# 🐞 Bug Report

### Description

When adding a new validator key to my validator client, I was expecting my grafana dashboard to update my validator status from 0 (UNKNOWN) to 1 (DEPOSITED), then 2 (PENDING)

## 🔬 Minimal Reproduction

Create a new validator key pair, make deposit, and check for the validator client metrics to see that the value 1 (DEPOSITED) will never be returned

## 🔥 Error

The expected behavior is to get the status updated from 0 to 1 at the same time as in the log of the validator client. Instead I never saw the 1 status and it went directly to 2, skipping then the 1 status.

Both screeshot have been made at the exact same timing, just after restarting my validator client to make sure that my validator status was still to 0 or already at 1.
Validator client shows status at 1
https://cdn.discordapp.com/attachments/476588476393848832/706477013375909908/unknown.png

Prometheus metrics shows status at 0
https://cdn.discordapp.com/attachments/476588476393848832/706477312379584512/unknown.png

**Comment by shayzluf** [comment]
@0xKiwi please reassign to me if you find the assignment inappropriate
