### ISSUE TITLE
Collect block propagation information - 'number of hops' 

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#5721]
🚀 Feature Request

### Description

As seen in #5665 getting blocks late can lead to an increase in incorrect head voting.
In order to understand the root cause of late blocks and high propagation times better it might be helpful to get some data on how many hops were done in order to get the block from a peer.

But please note: This feature should be for debugging purposes only and should be removed for mainnet as it poses a security concern. It makes it easy to figure out the node that is associated with a certain validator.

**Comment by prestonvanloon** [comment]
I don't think this is going to be possible with the current networking protocol. We don't have any mechanism to transmit additional metadata with pubsub objects as far as i know

**Comment by Phistr90** [comment]
@prestonvanloon doesnt libp2p pubsub supports tracing? I might misunderstand that feature.

**Comment by rauljordan** [comment]
@raulvk we would love your feedback on this. How would you recommend tracking message propagation metadata such as hops using libp2p's options?

**Comment by nisdas** [comment]
Libp2p pubsub does support tracing, so if we do desire we can trace events. Ex: 
https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L375

**Comment by prestonvanloon** [comment]
Not sure how libp2p pubsub tracing collection works, but we could track the message IDs via opencensus.

**Comment by rauljordan** [comment]
We are closing this now that we are in mainnet. Unlikely we will develop this feature
