### ISSUE TITLE
Failed to propose block

### ISSUE THREAD

**Issue by xrow** [prysmaticlabs/prysm#5731]
#4918 🐞 Bug Report

### Description

I saw a missed blocks of my validators. If I look in the logs I see this message:

### Has this worked before in a previous version?

It might have been around for a while.

## 🔬 Minimal Reproduction

I just wait for a missed proposed block.

## 🔥 Error

<pre><code>
time="2020-05-03 20:14:24" level=info msg="Previous epoch aggregated voting summary" attestationInclusionPercentage=0.01 correctlyVotedHeadPercentage=0.01 correctlyVotedSourcePercentage=0.01 correctlyVotedTargetPercentage=0.01 epoch=3545 prefix=validator
--
  | time="2020-05-03 20:14:26" level=info msg="New assignment" attesterSlot=113474 committeeIndex=2 epoch=3546 prefix=validator proposerSlots=[113482] pubKey=0xa09f182da02c status=ACTIVE validatorIndex=17351
  | time="2020-05-03 20:14:52" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[17351] BeaconBlockRoot=0x9c2f66f34c40 CommitteeIndex=2 Slot=113474 SourceEpoch=3545 SourceRoot=0x7d503454a7a9 TargetEpoch=3546 TargetRoot=0x49d5d393f8cb prefix=validator
  | time="2020-05-03 20:16:27" level=error msg="Failed to request block from beacon node" blockSlot=113482 error="rpc error: code = Internal desc = Could not compute state root: could not calculate state root at slot 113481: could not process block: could not process block operation: could not process block attester slashings: unable to slash any validator despite confirmed attester slashing" prefix=validator pubKey=0xa09f182da02c
  | time="2020-05-03 20:20:48" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=3546 inclusionDistance=1 inclusionSlot=113422 newBalance=32.12191223 oldBalance=32.121850736 percentChange="0.00019%" prefix=validator pubKey=0xa09f182da02ce9bd
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.6
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
see logs

**Comment by xrow** [comment]
Here is a list of my validators https://beaconcha.in/dashboard?validators=17311,17343,17350,17351,17352,23859

they all seem to suffer that problem in a way.

**Comment by 0xKiwi** [comment]
Wow, @xrow. You're not running a slasher? This was from validators connected to your beacon node?

**Comment by xrow** [comment]
This was a log from a validator. A slasher was also there.

**Comment by prestonvanloon** [comment]
Can we validate slashing objects before adding them to a block?
