### ISSUE TITLE
Enable running prysm.sh validator accounts keys without providing password

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5733]
#🚀 Feature Request

### Description

`./prysm.sh validator accounts keys --keystore-path ~/validator` should support printout of keys without providing password on the terminal

### Describe the solution you'd like

would like to copy the behaviour of running the command with wrong password to running the command with no password

**Comment by shayzluf** [comment]
please reassign to me if you think the assignment is inappropriate

**Comment by nisdas** [comment]
Any reason this can't come under #5659 ?

**Comment by shayzluf** [comment]
Duplicate of #5659
thanks @nisdas for pointing it out
