### ISSUE TITLE
Slasher: PROCESS can be beacon-chain or validator.

### ISSUE THREAD

**Issue by ncsolar** [prysmaticlabs/prysm#5735]
# 🐞 Bug Report

### Description

When I try the command ./prysm.sh slasher i get errors

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was

## 🔬 Minimal Reproduction

When i run the command ./prysm.sh slasher 

## 🔥 Error

<pre><code>
Latest Prysm version is v1.0.0-alpha.6.
Beacon chain is up to date.
Validator is up to date.
Usage: ./prysm.sh PROCESS FLAGS.
PROCESS can be beacon-chain or validator.
Starting Prysm slasher 
./prysm.sh: line 131: process: unbound variable
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.6.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by ncsolar** [comment]
Update the error went away after deleting slasher.db

**Comment by farazdagi** [comment]
I suppose the issue is not that much with `slasher.db` but with incorrect argument (type, prbly?) passed to process. If you type `./prysm.sh foo-bar` you will get the error. #5747 should fix the issue or properly reporting when invalid process name is provided.
