### ISSUE TITLE
Version not always shown

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#5748]
# 🐞 Bug Report

 A clear and concise description of the problem...

When running the --version command from the bazel binary, the git version is not always shown. Instead it shows: {STABLE_GIT_COMMIT}

## 🔬 Minimal Reproduction

cd $HOME
$HOME/prysm/bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain --version
(not working)

cd ./prysm
$HOME/prysm/bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain --version
(working)

curl -s  http://localhost:4001/eth/v1alpha1/node/version | python -m json.tool
(only working when beacon was started from inside prysm directory)

see screenprint below

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

latest

**Anything else relevant (validator index / public key)?**
Maybe it is possible to "store" the git_commit (+build time) inside the binary, so it is always available.

![2020-05-05_17-12-31](https://user-images.githubusercontent.com/28559038/81082998-4d674780-8ef4-11ea-9390-055791042835.png)

**Comment by prestonvanloon** [comment]
If you build with the release configuration, the git commit is stamped within the binary `--config=release`

**Comment by handelaar2** [comment]
That worked:
bazel build --config=release //beacon-chain:beacon-chain
bazel build --config=release //validator:validator

$`curl -s  http://localhost:4001/eth/v1alpha1/node/version | python -m json.tool`
{
    "metadata": "",
    "version": "Prysm/Git commit: 4cc7f171f9d08a3f05951d20877f0f6ead444970. Built at: 2020-05-05 16:08:57+00:00"
}

Thanks.
