### ISSUE TITLE
Test EnterPassword function in shared/cmd

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#5749]
This is a tracking issue for adding a test for the `EnterPassword`. This function uses `terminal.ReadPassword` which obfuscates the text entered, making it difficult to properly test.

[This guide](https://petersouter.xyz/testing-and-mocking-stdin-in-golang/) may be of assistance.

**Comment by connorwstein** [comment]
Hey @0xKiwi I can take a look at this as a first time issue. I think the approach I would take is to follow the article more or less, change the signature to:

func EnterPassword(confirmPassword bool, pr PasswordReader) (string, error) 

where PasswordReader is an interface which we can gomock and we'd have an implementation of it which reads from stdin which we pass in for the 2 uses in account.go. Then I'd add a helpers_test.go file which has a table test of cases we'd want to validate: passwords match, don't match, failure to read etc. Does that make sense?

**Comment by 0xKiwi** [comment]
Makes great sense @connorwstein , your help would be very appreciated! 😁
