### ISSUE TITLE
Refactor Crystallized State

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#575]
### Current Problem
Currently a lot of the logic in `crystallized state` also incorporates Validator Rewards and Penalties, this makes it difficult to test the application of rewards and penalties extensively, as a lot of different elements have to be setup for the test making debugging very complicated.
### What would Solve this
A solution for this would be to extract out the logic pertaining to rewards and penalties, attestation indices, state recalc,dynasty recalc from `crystallised state` and place it in the casper package. This crystallized state file would solely handle the basic helper methods for it. Anymore logic pertaining to Casper would be taken out and shifted over

**Comment by nisdas** [comment]
My idea was that crystallized state would consist of two functions , namely Generating a New crystallized state , and helper methods for its fields. Adding in the other stuff makes a lot of the tests hard to carry out and isolate bugs. One example is #572. We dont have to take out everything related to casper but stuff like rewards and penalties . 

If you notice new state recalc is hard to test because there are so many moving parts to it. The conditions for state recalc, applying rewards/penalties imo should be in casper not crystallized state

**Comment by terenc3t** [comment]
@nisdas I see I see. That makes sense.
