### ISSUE TITLE
Endpoint /eth/v1alpha1/beacon/state does not address future slot request

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5753]
# 🐞 Bug Report

### Description

The debug end point `/eth/v1alpha1/beacon/state` does not account for fault case where request slot exceeds current slot:
`
{"error":"could not compute state by slot: could not process slot: unknown state","code":13,"message":"could not compute state by slot: could not process slot: unknown state","details":[]}
`

**Comment by prestonvanloon** [comment]
What is the expected result? Shouldn't we reject requests for slots from the future?

**Comment by terencechain** [comment]
> What is the expected result? Shouldn't we reject requests for slots from the future?

Correct. The expected result:
```go
	currentEpoch := helpers.SlotToEpoch(bs.GenesisTimeFetcher.CurrentSlot())
	if requestedEpoch > currentEpoch {
		return nil, status.Errorf(
			codes.InvalidArgument,
			"Cannot retrieve information about an epoch in the future, current epoch %d, requesting %d",
			currentEpoch,
			requestedEpoch,
		)
	}
```
