### ISSUE TITLE
alpine images are not yet functional

### ISSUE THREAD

**Issue by timmyers** [prysmaticlabs/prysm#5768]
# 🐞 Bug Report

### Description

`*-alpine` tag images are not yet functional, with error `libstdc++.so.6: cannot open shared object file: No such file or directory`

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

```
❯ docker run -it --rm gcr.io/prysmaticlabs/prysm/beacon-chain:latest-alpine
/app/beacon-chain/image.binary: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

## 🔥 Error

See above

## 🌍  Your Environment

Any docker environment.

**Comment by prestonvanloon** [comment]
Related: https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/issues/17

**Comment by prestonvanloon** [comment]
User reported alpine images are still not functional.

**Comment by rauljordan** [comment]
@timmyers this issue has likely gone stale. Can you try our latest alpine images and let us know if you run into any issues? if so, we can reopen

**Comment by nisdas** [comment]
Reopening this issue as it has been reported that alpine images are still not functional

**Comment by protolambda** [comment]
Which libraries in prysm require native dependencies? Previously I went through Herumi BLS to get it to run on alpine linux, see:
- https://github.com/herumi/bls/issues/50
- https://github.com/herumi/bls-eth-go-binary/pull/8

Maybe that's broken here? Or maybe there is a similar problem with another library?

**Comment by prestonvanloon** [comment]
This is what happens when I tried to run alpine:
```
Unable to find image 'gcr.io/prysmaticlabs/prysm/beacon-chain:latest-alpine' locally
latest-alpine: Pulling from prysmaticlabs/prysm/beacon-chain
169185f82c45: Pull complete 
3ac0fa0cb1ae: Pull complete 
c5a366754cd7: Pull complete 
91e8ba83d9d4: Pull complete 
Digest: sha256:6165bb335d267a7c2dd76a2620ed9e13c919c7db23190370df8f3c7e7dd9eab1
Status: Downloaded newer image for gcr.io/prysmaticlabs/prysm/beacon-chain:latest-alpine
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by pinglamb** [comment]
Is the issue related to dynamic linking described here: https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host

It seems to be able to build an alpine image using this command (with the flags suggested in the post):

```
bazelisk run --config=docker-sandbox --features=static --features=pure //beacon-chain:image --//tools:base_image=alpine
```

**Comment by pingnamo** [comment]
As discussed in Discord, this project probably cannot be built with `--features=static --features=pure`.

Further investigation shows that the binary built has dynamic dependencies like this:

```
# ldd beacon-chain
    /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
```

and the Alpine needs to have [libc6-compat](https://pkgs.alpinelinux.org/package/edge/main/x86_64/libc6-compat) installed so the dymanic linking will work (which seems to be a symlink to `/lib/libc.musl-x86_64.so.1`).

The alpine base image `Dockerfile`:

```
FROM alpine:3.12
RUN apk update && apk add --no-cache libc6-compat
```

This resolve the `standard_init_linux.go:211: exec user process caused "no such file or directory"` and the container will be able to start, but I am not sure if the `musl` provides enough functionalities for the binaries.

**Comment by pingnamo** [comment]
As discussed in Discord, this project probably cannot be built with `--features=static --features=pure`.

Further investigation shows that the binary built has dynamic dependencies like this:

```
# ldd beacon-chain
    /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
```

and the Alpine needs to have [libc6-compat](https://pkgs.alpinelinux.org/package/edge/main/x86_64/libc6-compat) installed so the dymanic linking will work (which seems to be a symlink to `/lib/libc.musl-x86_64.so.1`).

The alpine base image `Dockerfile`:

```
FROM alpine:3.12
RUN apk update && apk add --no-cache libc6-compat
```

This resolve the `standard_init_linux.go:211: exec user process caused "no such file or directory"` and the container will be able to start, but I am not sure if the `musl` provides enough functionalities for the binaries.

**Comment by pinglamb** [comment]
As discussed in Discord, this project probably cannot be built with `--features=static --features=pure`.

Further investigation shows that the binary built has dynamic dependencies like this:

```
# ldd beacon-chain
    /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe725e2b000)
```

and the Alpine needs to have [libc6-compat](https://pkgs.alpinelinux.org/package/edge/main/x86_64/libc6-compat) installed so the dymanic linking will work (which seems to be a symlink to `/lib/libc.musl-x86_64.so.1`).

The alpine base image `Dockerfile`:

```
FROM alpine:3.12
RUN apk update && apk add --no-cache libc6-compat
```

This resolve the `standard_init_linux.go:211: exec user process caused "no such file or directory"` and the container will be able to start, but I am not sure if `musl` provides enough functionalities for the binaries.
