### ISSUE TITLE
ARM64 docker image not supported

### ISSUE THREAD

**Issue by pagocs** [prysmaticlabs/prysm#5769]
# 🚀 Feature Request

### Description

 I would like to test the beacon chain and the validator node on RPI 4 in docker but I cannot find compatible ARM64 image.

### Describe the solution you'd like

 Will this be supported or someone could help me how I could be built myself?

**Comment by prestonvanloon** [comment]
There is no current plan to support ARM64 based docker images. 

I haven't tested this idea, but here's a thought that might be a good starting point for you to experiment. On an ARM device, build a docker image with a Dockerfile that looks something like this

```Dockerfile
FROM arm64v8/ubuntu

RUN apt-get install -y libstdc++ libgcc1 pgp

RUN curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh

CMD ./prysm beacon-chain
```

**Comment by pagocs** [comment]
Thank you @prestonvanloon for the information. I managed to create docker containers (beacon and validator) which are run perfectly for days now.

Config: RPi 4 4GB RAM.

If it is interesting I could share the dockerfile and basic instructions to setup and launch.

**Comment by rauljordan** [comment]
Hey @pagocs that would be great, could you suggest it as a pull request or issue in our documentation portal here https://docs.prylabs.network ? Thank you!

**Comment by prestonvanloon** [comment]
I think we could publish x86 and arm images to dockerhub. It seems rules_docker supports platform transition rules https://github.com/bazelbuild/rules_docker/pull/1963, that might be helpful. 

I know that dockerhub supports both platforms with the same tag. Still looking at google container registry to see if both platforms could be supported with the same tag.

**Comment by pablote** [comment]
> There is no current plan to support ARM64 based docker images

Can this be reconsidered please? I'm building a new setup around docker images/containers and arm hw, and I just realized this didn't worked either using the docker hub repo or gcr.io.

**Comment by prestonvanloon** [comment]
Blocked by this: https://github.com/prysmaticlabs/prysm/issues/10119
