### ISSUE TITLE
Ability to sync an ETH1 Node with Prysm.sh

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5781]
In order to provide a more realistic mainnet scenario user's should run their own ETH1 Node. 

A feature to sync one with `Prysm.sh eth1node ` would be great.

It might have some security risks because for testing we'll be on Görli and won't be syncing the mainnet to test, but it would be a great feature in the long run anyway.

**Comment by 0xKiwi** [comment]
This might be difficult consider it would be providing access to a release that we don't manage, @prestonvanloon what is your opinion on adding this?

**Comment by prestonvanloon** [comment]
This seems OK to add, but it makes some assumptions about which eth1node the user wishes to use.

**Comment by rauljordan** [comment]
Not sure if this is something we will get to and also makes assumptions about eth1 nodes that people should use
