### ISSUE TITLE
Improve blockchain package test coverage

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5783]
# 💎 Issue

### Background

After studying codecov, it turns `onBlock` and `onBlockInitialSyncStateTransition` dont have good test coverages. Part of the reason is these functions are really hard to test without proper mocking of state transition. Open this issue to track for better coverage of those 2 functions. We can begin to think about how to properly mock state transition

EDIT:
Improve test coverages of the following
file | coverage
-- | --
head.go | 79.7% statements
metrics.go | 76.6% statements
process_block_helpers.go | 76.2% statements
process_attestation_helpers.go | 74.5% statements
service.go | 68.6% statements
chain_info.go | 64.4% statements
init_sync_process_block.go | 60% statements
process_attestation.go | 59.4% statements
process_block.go | 42.2% statements
receive_attestation.go | 33.3% statements
receive_block.go | 24.6% statements
log.go | 16.7% statements
info.go | 0% statements

**Comment by rauljordan** [comment]
Still relevant @terencechain ?

**Comment by terencechain** [comment]
It's 67% now. Let's close it until we get to 75%

**Comment by prestonvanloon** [comment]
Removing from v1 milestone as it is not a release blocker.
