### ISSUE TITLE
Enforce Max Committees per Slot

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#579]
`getCommitteeParams` has a bug. The max number of committees per slot should be bounded by the total number of shards. The max committees per slot should also be bounded by total number of shards divide cycle length.

From 2.1 spec:
```
min(len(avs) // CYCLE_LENGTH // (MIN_COMMITTEE_SIZE * 2) + 1, SHARD_COUNT // CYCLE_LENGTH)
```

Here is the line that needs to change:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/casper/sharding.go#L62

**Comment by prestonvanloon** [comment]
@IvanTheGreatDev Are you working on this?

**Comment by IvanTheGreatDev** [comment]
Yes, I made a solution a long time ago but no one looked at it, you can see
the commit mentioned earlier. Should I PR it?
