### ISSUE TITLE
Req: Flag to start Slasher from a custom epoch

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5793]

**Comment by 0xKiwi** [comment]
This is a good idea @Buttaa ! The slasher now has `--disable-historical-detection` if you wish to disregard prior history. Historical detection still relies on `--new-state-mgmt` though.

**Comment by rauljordan** [comment]
Now that new-state-mgmt is the default, you can just use --disable-historical-detection to achieve the desired results
