### ISSUE TITLE
Check OS / pre-req's and fail fast if not met

### ISSUE THREAD

**Issue by wgknowles** [prysmaticlabs/prysm#5797]
# 🚀 Feature Request

### Description

A lot of time and hassle is spent troubleshooting issues that boil down to not running on supported operating systems, or not having the necessary pre-requisites (e.g. Homebrew on macOS).  It may be helpful to add in a check for this info by default, and then to introduce a new flag to bypass the check for people who are tinkering with unsupported configurations.

### Describe the solution you'd like

Example error messages:
```
ERROR: System does not meet the minimum Operating System requirement, use --bypass-os-check to skip this check. (expected Mac OS X 10.14+, found 10.13) 
ERROR: System does not meet software pre-requisites, use --bypass-prereq-check to skip this check. (Homebrew not found).
```
### Describe alternatives you've considered

Docs have all the info, but people don't RTFM.  Current error messages / stack dumps are quite scary.

**Comment by 0xKiwi** [comment]
@prestonvanloon any ideas on how this could be done? How would this work for docker users?

What conditions should we considered required by the client?

**Comment by prestonvanloon** [comment]
Supported OS / architectures are:
- Linux AMD64
- Linux ARM64
- Mac OS X AMD64 (OS X 10.14+ only)
- Windows AMD64 

The idea would be to complain if the host is not one of those things.

**Comment by dv8silencer** [comment]
I'd be happy to try to tackle this.  Other than Homebrew, is there any other (software, non-OS) prerequisite?

**Comment by farazdagi** [comment]
@dv8silencer are you still interested in tackling this issue? 

Re. answer to your question: the OSX version of `find` util is not GNU find compatible, so `prysm.sh` script will require one to install `findutils` with brew. This is only needed when system is run with `prysm.sh` though (and is already handled by the script itself).

I believe, we should keep scope simple and focused, that's:
  - start with OS/arch check only
  - not sure if we even need that separate disable check flag i.e. emitting warning when minimum requirements are not met should be enough (no need to stop the system, and then not to stop it when "disable check" flag is provided). User will have more feedback of what's going on, and that should be it.
