### ISSUE TITLE
Protecting key manager 

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5806]
# 🚀 Feature

### Description

Validators are not sufficiently slashing protected using the current local db validator protection mechanism. Connecting the validator to a slasher instance and validating its blocks and attestation before transmission will enable much more secure validation activity.

The other option that this feature possibly enables is running a redundant validator at a different location. this should be battle tested for timing issues and correctness

- [x] add slasher grpc client to validator #5807
- [x] validate attestation before submission using is slashable attestation slasher endpoint
- [x] validate block before submission using is slashable block endpoint
- [ ] test protection timing on local setup and using remote slasher

**Comment by nisdas** [comment]
Whats the status on this ? @shayzluf

**Comment by shayzluf** [comment]
Finished. One more issue exists for protection
