### ISSUE TITLE
Slasher kills beacon node: dropping peers

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5812]
# 🐞 Bug Report

### Description

It has been reported by a few users (ex: `Haxington`) that slasher kills beacon node with attached validators. Opening up this issue for tracking.

Chat link for reference: https://discordapp.com/channels/476244492043812875/476588476393848832/708479430565167105

**Comment by rauljordan** [comment]
@0xKiwi can we close? this was resolved by your fix to slasher right, can you link the PR?

**Comment by 0xKiwi** [comment]
> @0xKiwi can we close? this was resolved by your fix to slasher right, can you link the PR?

Hey @rauljordan, I haven't been able to replicate this. Maybe #5782 gated the root cause of this though.

**Comment by rauljordan** [comment]
This is a duplicate of #5854 ,  causing OOMs and peers to all drop to 0
