### ISSUE TITLE
Mismatch between Finalized Block And Epoch

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5827]
# 🐞 Bug Report

### Description

Currently there is a mismatch between finalized epochs and their related blocks. The finalized 
epoch does not exactly match the one provided by the slot in the block. 

### Has this worked before in a previous version?

Before #5811 

## 🔬 Minimal Reproduction

Run the node and look at the handshake errors from it from other peers.  

## 🔥 Error

```
[2020-05-12 20:19:13]  WARN sync: Failed to handle p2p RPC error=invalid epoch peer=16Uiu2HAmDstiv2UPX3pRgnTWuVgfoDZvkaUp7jbfoVi43nGsPt6P topic=/eth2/beacon_chain/req/status/1/ssz_snappy
```

**What version of Prysm are you running? (Which release)**

baf9ec60eb3ad308f0d587710209d7f35a8dd985

**Comment by terencechain** [comment]
This worries me. I wonder how it could happen

**Comment by nisdas** [comment]
Yeah it is off in a few places, 
Ex:
```go
	if helpers.SlotToEpoch(blk.Block.Slot) != msg.FinalizedEpoch {
		return errInvalidEpoch
	}
```
is there anything wrong with doing this ? @terencechain . I feel like I might be missing something, I was looking at our code for indexing finalized blocks in the db, and it seems like there are quite a few gotchas on determining which block is finalized and for what epoch it is finalized.

**Comment by terencechain** [comment]
@nisdas that won't work if there's skip slot. You have to account for skip slot scenario similar to this:

```go
fBlkSlot := helpers.SlotToEpoch(blk.Block.Slot)
fEpochStartSlot := helpers.StartSlot(msg.FinalizedEpoch)
if fEpochStartSlot > fBlkSlot {
  filter := filters.NewFilter().SetStartSlot(fBlkSlot).SetEndSlot(fEpochStartSlot)
  blks, err := s.beaconDB.Blocks(ctx, filter)
  if len(blks) != empty {
     // Should be empty if skipped.
     return errInvalidEpoch
  }
}
...
```

**Comment by rauljordan** [comment]
Is this still an issue @terencechain and @nisdas ?

**Comment by rauljordan** [comment]
Bump @terencechain @nisdas have we observed this since?

**Comment by nisdas** [comment]
Still an issue @rauljordan , we still need to verify it.

**Comment by protolambda** [comment]
This is actually quite important, can someone take a look at this please?

**Comment by nisdas** [comment]
@protolambda been on my todo list for too long, will take a look at it today. Thanks for the reminder.
