### ISSUE TITLE
`./prysm.sh validator accounts create` gives OOM on devices with low RAM / swap

### ISSUE THREAD

**Issue by chrishobcroft** [prysmaticlabs/prysm#5830]
# 🐞 Bug Report

### Description

`./prysm.sh validator accounts create` fails consistently, reporting `Killed`, when running on `Ubuntu 20.04 LTS` with **`512Mb` `RAM`** and **`0` `swap`**

### Has this worked before in a previous version?

 Not to my knowledge.

## 🔬 Minimal Reproduction

1. Deploy and connect to `Ubuntu 20.04 LTS` server with `1 vCPU`, `512 Mb RAM`

![image](https://user-images.githubusercontent.com/2212651/81699537-22956a00-9485-11ea-892e-7af03f3df230.png)

2. Run the following commands:
```
mkdir prysm \
                  && cd prysm 
curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh \
                  --output prysm.sh \
                  && chmod +x prysm.sh 
./prysm.sh \
                  validator \
                  accounts \
                  create \
                  --password changeme \
                  --keystore-path /home/ubuntu/.eth2validators
```

3. See the process generate the `shardwithdrawalkey...` and then fail with `Killed`, _without generating_ the `validatorprivatekey...` (see below for full transcript of session)

This process was repeated 20 times, with the same results each time.

Prior to running any process, the memory usage / availability reported by `top` was
```
MiB Mem :    474.5 total,     57.9 free,    127.6 used,    289.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    329.0 avail Mem 
```

## 🔥 Error

The process fails, and reports `Killed`.

Upon further investigation using `top`, it appears that the process requires more memory than is available, to generate the `validatorprivatekey...` files.

#### 512Mb RAM + 192Mb swap

When a total of **192Mb of swap** was added to the **512Mb of physical RAM**, the process **failed to create the `validatorprivatekey` as per above** 10/10 times.

Prior to running any process, the memory usage / availability reported by `top` was
```
MiB Mem :    474.5 total,    290.1 free,    126.6 used,     57.8 buff/cache
MiB Swap:    192.0 total,    192.0 free,      0.0 used.    326.8 avail Mem 
```

#### 512Mb RAM + 240Mb swap

When a total of **240Mb of swap** was added to the **512Mb of physical RAM**, the process **succeeded** 10/10 times in creating _both keystore files_, BUT failed 2/10 times to generate the `Raw Transaction Data` with `Killed`.

Prior to running any process, the memory usage / availability reported by `top` was
```
MiB Mem :    474.5 total,     71.5 free,    128.0 used,    274.9 buff/cache
MiB Swap:    240.0 total,    240.0 free,      0.0 used.    327.0 avail Mem 
```

#### 512Mb RAM + 256Mb swap

When a total of **256Mb of swap** was added to the **512Mb of physical RAM**, the process **succeeded** 9/10 times in creating _both keystore files_, AND failed 1/10 times to generate the `Raw Transaction Data` with `Killed`.

Prior to running any process, the memory usage / availability reported by `top` was
```
MiB Mem :    474.5 total,    297.7 free,    125.6 used,     51.2 buff/cache
MiB Swap:    256.0 total,    256.0 free,      0.0 used.    327.7 avail Mem 
```

## 🌍  Your Environment

`Ubuntu 20.04 LTS` server with `1 vCPU`, `512 Mb RAM`

**What version of Prysm are you running? (Which release)**

`validator-v1.0.0-alpha.7-linux-amd64`

**Full transcript of session**
```
ubuntu@pistachio:~$ mkdir prysm \
>                   && cd prysm 
ubuntu@pistachio:~/prysm$ curl https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh \
>                   --output prysm.sh \
>                   && chmod +x prysm.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7772  100  7772    0     0  28785      0 --:--:-- --:--:-- --:--:-- 28678
ubuntu@pistachio:~/prysm$ ./prysm.sh \
>                   validator \
>                   accounts \
>                   create \
>                   --password changeme \
>                   --keystore-path /home/ubuntu/.eth2validators
Latest Prysm version is v1.0.0-alpha.7.
Downloading validator@v1.0.0-alpha.7 to /home/ubuntu/prysm/dist/validator-v1.0.0-alpha.7-linux-amd64 (automatically selected latest available version)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32.4M  100 32.4M    0     0   150M      0 --:--:-- --:--:-- --:--:--  150M
Verifying binary integrity.
gpg: key 72E33E4DF1A5036E: public key "Preston Van Loon <preston@prysmaticlabs.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
validator-v1.0.0-alpha.7-linux-amd64: OK
gpg: Signature made Sat May  9 19:59:36 2020 UTC
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /home/ubuntu/prysm/dist/validator-v1.0.0-alpha.7-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm validator accounts create --password changeme --keystore-path /home/ubuntu/.eth2validators
2020/05/12 14:03:26 maxprocs: Leaving GOMAXPROCS=1: CPU quota undefined
[2020-05-12 14:03:26]  WARN flags: Using default mainnet config
[2020-05-12 14:03:27]  INFO accounts: Keystore generated for shard withdrawals at path path=/home/ubuntu/.eth2validators/shardwithdrawalkeya53410e31197
Killed
ubuntu@pistachio:~/prysm$ 
```

**Comment by 0xKiwi** [comment]
Thanks for reporting @chrishobcroft ! @prestonvanloon , how do you think we should handle this? This is a rather simple process so I'm surprised it takes up so much memory, could there be something we can improve?

**Comment by prestonvanloon** [comment]
We can look at the memory usage of the keystore creation to see if where we can reduce the memory profile. Otherwise, this system is below the minimum supported requirements for memory.

**Comment by chrishobcroft** [comment]
@prestonvanloon this system is only running a Validator, with a remote Beacon Chain. I couldn't find any minimum supported requirements for memory for a node running only a Validator - do you know of any?

From initial testing, it would appear that the Validator process requires somewhere between `18Mb` and `26Mb` during normal operations on `Ubuntu 20.04 LTS` (see below screenshot from Grafana)

![Screenshot from 2020-05-13 12-27-00](https://user-images.githubusercontent.com/2212651/81781405-adbe4080-9515-11ea-9211-32a6b8acdb3a.png)

Also, the node operates at 48-52% of RAM used, `Ubuntu 20.04 LTS` server with `512Mb RAM`and no swap (ironically, with Prometheus and Grafana using more RAM than Validator!) (see below screenshot from `top`):

![image](https://user-images.githubusercontent.com/2212651/81782029-d135bb00-9516-11ea-9c86-699fe9dcb49c.png)

So, it would seem that the process requires _much_ more RAM (~400-500Mb) for setup (generate keys, generate raw txn data) and also for startup (decrypt keys, start validating), than it does for ongoing validation.

Doing something which minimises this initial resource requirement can help in getting Validators (with remote Beacons) operating on devices with substantially lower resource availability.

**Comment by prestonvanloon** [comment]
@chrishobcroft This is great feedback. Thanks for taking the time to put it together with screenshots and all of your analysis. I agree that the validator in this setup should be very lightweight on memory usage. I believe the default keystore, which is used in go-ethereum, might be a memory hard encryption scheme or somehow needs to load a relatively significant portion of memory to complete the number of encryption / decryption rounds it needs.

With that said, the current default key management is soon to be deprecated and replaced. I would like to keep this issue open as a hard requirement for the next keystore implementation, which should be picking up progress in the next few weeks. Ideally, this change would land before the scheduled Topaz reset (after v0.12 spec release) and become the new default. 

With regards to minimum requirements for a validator, we haven't taken the time to properly bench these processes so I don't have a great answer at the moment. All we know is that there is still much room for improvement in certain areas of the application for resource usage.

How does all of that sound?

**Comment by criticaltv** [comment]
@prestonvanloon it all sounds very good. Thank you for taking the time to explain the situation!

Sadly my coding skills are very rusty, but I enjoy the analysis side of running platforms and protocols.

Keep up the great work @prysmaticlabs

**Comment by prestonvanloon** [comment]
Another user reported about 500mb validator usage at startup of normal operations. The memory was eventually reclaimed without restarting. I suspect there is something terrible with the keystore.

![image](https://user-images.githubusercontent.com/7246818/81974696-c3496e00-95da-11ea-8ae8-403b7e335be8.png)

Yellow line = validator memory

**Comment by GuillaumeMiralles** [comment]
I want to clarify something here, the graph is using the metrics `process_resident_memory_bytes` which seems to be the allocated memory for the process, and not the used one in the end.

With the metrics `go_memstats_alloc_bytes` it stays constant, no spikes at start.

This screenshot shows the exact moment than the previous one but with the `go_memstats_alloc_bytes` metric instead
![image](https://user-images.githubusercontent.com/23481418/82129667-bab48b80-97c4-11ea-9e79-81c9c5323e3a.png)

The validator is taking twice less memory and only for 10 minutes maximum

Not sure this info is useful, but better sharing still

**Comment by criticaltv** [comment]
Thanks @GuillaumeMiralles - it's hard to see the Validator RAM on this diagram.

Given that the RAM usage for a Beacon is an order of magnitude higher than a Validator, perhaps the Grafana dashboard template could split them to separate graphs?

**Comment by GuillaumeMiralles** [comment]
What really matters here is to see the spike at the restart, which we can see it on the graph.
But to make it more clear, I've done the graph for the **validator only** using the `go_memstat_alloc_bytes` still on the same timeFrame 
![image](https://user-images.githubusercontent.com/23481418/82137248-9aadb800-9816-11ea-9dcd-6aeae4d2d7b0.png)

**Comment by criticaltv** [comment]
Thank you @GuillaumeMiralles this is perfect evidence to characterise the issue! Presumably ths spike was after a restart of `validator`?

**Comment by GuillaumeMiralles** [comment]
Yes it is on restart. after the restart this is all good

**Comment by rauljordan** [comment]
No longer relevant
