### ISSUE TITLE
Slasher: Possible Memory leak (alpha-7)

### ISSUE THREAD

**Issue by DanielFontes** [prysmaticlabs/prysm#5838]
# 🐞 Bug Report

### Description

Slasher (alpha 7) suddenly starts to consume several GB of RAM (on 4GB Raspberry Pi) in only a couple of seconds.

### Has this worked before in a previous version?

In alpha-6 slasher was fine.

## 🔬 Minimal Reproduction

Run beacon-chain, validator and slasher on RPi4 and wait for some time.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Raspberry Pi 4 with Ubuntu 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha-7
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

I cannot see anything wrong in the logs...

<pre>
<code>
May 13 11:39:24 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:39:24" level=info msg="Received block from beacon node" prefix=beaconclient slot=183497
May 13 11:39:29 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:39:29" level=info msg="Attestations saved to slasher DB" amountSaved=1 prefix=beaconclient slot=183497
May 13 11:39:38 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:39:38" level=info msg="Received block from beacon node" prefix=beaconclient slot=183498
May 13 11:39:51 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:39:51" level=info msg="Received block from beacon node" prefix=beaconclient slot=183499
May 13 11:40:01 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:40:01" level=info msg="Received block from beacon node" prefix=beaconclient slot=183500
May 13 11:40:25 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:40:25" level=info msg="Received block from beacon node" prefix=beaconclient slot=183502
May 13 11:40:37 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:40:37" level=info msg="Received block from beacon node" prefix=beaconclient slot=183503
May 13 11:40:50 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:40:50" level=info msg="Received block from beacon node" prefix=beaconclient slot=183504
May 13 11:41:13 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:41:13" level=info msg="Received block from beacon node" prefix=beaconclient slot=183506
May 13 11:41:38 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:41:38" level=info msg="Received block from beacon node" prefix=beaconclient slot=183508
May 13 11:41:48 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:41:48" level=info msg="Received block from beacon node" prefix=beaconclient slot=183509
May 13 11:42:00 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:42:00" level=info msg="Received block from beacon node" prefix=beaconclient slot=183510
May 13 11:42:12 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:42:12" level=info msg="Received block from beacon node" prefix=beaconclient slot=183511
May 13 11:42:26 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:42:26" level=info msg="Received block from beacon node" prefix=beaconclient slot=183512
May 13 11:42:37 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:42:37" level=info msg="Received block from beacon node" prefix=beaconclient slot=183513
May 13 11:42:48 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:42:48" level=info msg="Received block from beacon node" prefix=beaconclient slot=183514
May 13 11:43:00 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:43:00" level=info msg="Received block from beacon node" prefix=beaconclient slot=183515
May 13 11:43:13 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:43:13" level=info msg="Received block from beacon node" prefix=beaconclient slot=183516
May 13 11:43:25 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:43:25" level=info msg="Received block from beacon node" prefix=beaconclient slot=183517
May 13 11:43:36 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:43:36" level=info msg="Received block from beacon node" prefix=beaconclient slot=183518
May 13 11:43:54 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:43:54" level=info msg="Received block from beacon node" prefix=beaconclient slot=183519
May 13 11:44:06 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:44:06" level=info msg="Attestations saved to slasher DB" amountSaved=1 prefix=beaconclient slot=183520
May 13 11:44:06 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:44:06" level=info msg="Received block from beacon node" prefix=beaconclient slot=183520
May 13 11:44:13 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:44:13" level=info msg="Received block from beacon node" prefix=beaconclient slot=183521
May 13 11:44:37 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:44:37" level=info msg="Received block from beacon node" prefix=beaconclient slot=183523
May 13 11:45:35 ethnode-565410fa9 systemd[1]: Stopping Prysm slasher daemon...
May 13 11:45:35 ethnode-565410fa9 slasher[1389]: time="2020-05-13 11:45:35" level=info msg="Got interrupt, shutting down..." prefix=node
</code>
</pre>

**Comment by 0xKiwi** [comment]
This is related to the lookback changes, unfortunately, the gating for the feature did not make it into alpha7 :(

If you'd like to try the slasher, try alpha6 or use current master. Sorry for the trouble!
