### ISSUE TITLE
Separate out validation for process_slot 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5844]
# 💎 Issue

### Background

From the spec `process_slots` and maybe more process functions violate single responsibility principles. It may be better to refactored the validation conditions to something like `validate_block_preconditions` It's important to have precondition checked in a way that makes  it obvious to the  reader that is is necessary for block production critical path

**Comment by prestonvanloon** [comment]
The critical assumption around block slot was resolved in #5846. I think we can resolve this for now.
