### ISSUE TITLE
Slasher "disable lookback" feature drains resources (i/o)

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5854]
# 🐞 Bug Report

### Description

After running slasher with disable lookback flag. memory and io resources of the machine are getting drained.

### Has this worked before in a previous version?

no
no adequate tests were written

## 🔬 Minimal Reproduction

run slasher with `--disable-lookback --clear-db --disable-historical-detection` flags

**Comment by rauljordan** [comment]
Hi @shayzluf can we consider resolved?

**Comment by shayzluf** [comment]
Would like flat spans to be implemented before

**Comment by rauljordan** [comment]
Hi @shayzluf are we good to close this?

**Comment by shayzluf** [comment]
Closed
