### ISSUE TITLE
New command to change a validator's password

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#5861]
# 🚀 Feature Request

### Description

I had a discussion on Discord (https://discordapp.com/channels/476244492043812875/560308336248225812/710615612203728996) recently about #5836. Someone had an issue that could be resolved by implementing a command that allows changing the validator's password. I believe it should be easy to implement - in fact the code in the linked PR already does this at some point. I am happy to submit another PR if this functionality would be useful.

### Describe the solution you'd like

Create a command `validator accounts change-password` that asks for the old password and for a new password. As a result the key files are encrypted with the new password.

### Describe alternatives you've considered

A workaround will be possible by using the `validator accounts merge` command from the linked PR, The user could move the key files to some other directory and merge them back to the desired directory, changing the password in the meantime. A true workaround :wink:

**Comment by rkapka** [comment]
Even though the feature sounds useful to me, I have some doubts how this could be actually implemented. These doubts boil down to me not understanding the difference between validator/accounts and how they are exactly related to key files. For example, if there are two pairs of key files in one directory, how can the user specify which pair they want to encrypt using a different password? Should the user provide the name of any one of the files from a pair? Some kind of an account ID or validator ID?

**Comment by wgknowles** [comment]
A few ideas:
1) You simply provide the "old" password, and ALL keys in the current (or specified --keystore-path) directory that are successfully decrypted are then updated to use the new password.

2) You specify the exact validator and withdrawal key to be updated using filenames, and then prompt for old & new password.  A potential problem here is being able verify that the 2 keys are actually correlated to each other.

**Comment by rkapka** [comment]
First option sounds promising, but I once again run into a problem with the go-ethereum key management library - it's not possible to check if the key has been successfully decrypted. This would require a change to the library. @nisdas mentioned in #5836 that it's undesirable, but I am really tempted to go ahead and modify it because it causes problems left and right.

**Comment by rkapka** [comment]
First option sounds promising, but I once again run into a problem with the go-ethereum key management library - it's not possible to check if the key has been successfully decrypted. This would require a change to the library. @nisdas mentioned in #5836 that it's undesirable, but I am really tempted to go ahead and modify it because it causes problems left and right.

**Comment by wgknowles** [comment]
Actually instead of using the current directory, default keystore directories should be used.  Refer to validator accounts create for default locations.
