### ISSUE TITLE
command "validator account create" gives error when the key store path directory is empty

### ISSUE THREAD

**Issue by CurrencyTycoon** [prysmaticlabs/prysm#5882]
# 🐞 Bug Report

### Description

It looks like the `validator account create` command will not create any new accounts if the target directory is empty.

`mkdir empty-keystore-dir`

` ./validator accounts create --keystore-path=./empty-keystore-dir --password=ok`

output:

[2020-05-17 12:39:32] FATAL main: Could not create validator at path: ./keystore error=path "./keystore" does not exist

Expecting:
INFO accounts: Account creation complete!  ....

### Has this worked before in a previous version?

Not tested on any previous version

## 🔥 Error

<code>
[2020-05-17 12:39:32] FATAL main: Could not create validator at path: ./keystore error=path "./keystore" does not exist
</code>

## 🌍  Your Environment

<pre>
  <code>
 x86_64 GNU/Linux 5.4
  go1.14.3
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
The latest pulled from master just the other day
  </code>
</pre>

**Further info**

It looks like the bug is in validator/accounts/account.go:124 in the `Exists` func

```// Exists checks if a validator account at a given keystore path exists.
func Exists(keystorePath string) (bool, error) {
	/* #nosec */
	f, err := os.Open(keystorePath)
	if err != nil {
		return false, nil
	}
	defer func() {
		if err := f.Close(); err != nil {
			log.Fatal(err)
		}
	}()

	_, err = f.Readdirnames(1) // Or f.Readdir(1)
	if err == io.EOF {
		return false, nil
	}
	return true, err
}
```

***Additional comment

It seems like `Exists` function expects at least one file or sub-directory to be present, and it will return an error if the keystore dir is empty even if it exists. 

I could gladly submit a PR with the following proposed fixes:

1. remove the following code from account.go

<code>
        _, err = f.Readdirnames(1) // Or f.Readdir(1)
	if err == io.EOF {
		return false, nil
	}
</code>

2. add a test case

Thanks

Edit: formatting

**Comment by prestonvanloon** [comment]
The culprit change is b42cc724c5fb82f9897c395302114ddf9e244f73 by @farazdagi. 
The intended behavior works as expected before this commit. 

@farazdagi could you take a look please?

**Comment by prestonvanloon** [comment]
A temporary workaround would be to use v1.0.0-alpha.6 for generating validator accounts.

```
USE_PRYSM_VERSION=v1.0.0-alpha.6 ./prysm.sh validator accounts create --keystore-path=/path/to/keystore
```

**Comment by CurrencyTycoon** [comment]
Many thanks.
My workaround was just to create an empty file in the keystore dir of my
choice first:

$ touch ~/.keystore/empty

Anyways, keep up the good work.
