### ISSUE TITLE
Proposer Index Is Incorrect during Deep Re-orgs

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5885]
# 🐞 Bug Report

### Description

In schlesi, there has been a current long running fork with more than 80 epochs since finality. This had led to clients being on different side of the fork. As a consequence Prysm has had to process blocks from the other side of the fork. However due to the nature of how long the chain had been forked, each block necessitated a recalculation of a base state from more than 70 epochs back. This has lead us being unable to process the block and the state. The error is stated below.

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

Running the slasher will reproduce the error as it tries to retrieve all blocks from genesis and
verify them.

## 🔥 Error

```
time="2020-05-17 00:51:25" level=error msg="Failed to handle p2p pubsub" error="could not process block: could not execute state transition: could not process block in slot 141257: could not process block header: proposer index: 317 is different than calculated: 150" prefix=sync topic="/eth2/9925efd6/beacon_block/ssz_snappy"
```

**Comment by prestonvanloon** [comment]
Can you add a bit more details on how to reproduce this issue? I am not understanding where the problem is.

**Comment by nisdas** [comment]
This is specifically in stategen, when we have a long period without finality. We regenerate a forked branch on receiving a new block; ex: 1000 blocks back, it seems that occasionally we regenerate incorrectly and have an unexpected proposer index from the state. This could most likely be from the proposer cache, with us saving the proposer index from another forked branch or some other dirty entry.
