### ISSUE TITLE
Proposer Index to be Added to Proposal Request

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#589]
Whenever a proposer proposes a new block and sends it to the beacon-chain to be processed, the proposer also has to include the attestation from the proposer of the previous slot in the proposal request. 

Currently for the demo, this attestation is created in the beacon node, so that the proposer client does not panic and fail. However, the correct method would be for the validator to send the attestation along with the proposal request for a block. A PR resolving this would allow validators to include attestation of the previous slot by the previous proposer in the current aggregated record.

**Comment by terenc3t** [comment]
I thought we are doing that Nishant

**Comment by rauljordan** [comment]
This is closed by #590
