### ISSUE TITLE
could not retrieve subnets: missing ENR key "attnets"

### ISSUE THREAD

**Issue by tunlong** [prysmaticlabs/prysm#5896]
After running the beacon-chain-v1.0.0-alpha.8-linux-amd64 on Ubuntu 18.04 server 64bit for more than 24hous, it will show this error. And my validator status will be getting poor. So I have to restart it. 

![image](https://user-images.githubusercontent.com/32350461/82221033-05afd980-9952-11ea-90fa-22bb4d85cdb4.png)

**Comment by prestonvanloon** [comment]
@nisdas can you take a look please?
