### ISSUE TITLE
Validator metric validator_balance shuffles pubKey balances

### ISSUE THREAD

**Issue by LarsHolte** [prysmaticlabs/prysm#5907]
# 🐞 Bug Report

Metric validator_balance has correct balance but wrong pubKey, and pubKey is shuffled when metrics update.

### Has this worked before in a previous version?

Yes, was ok in alpha.7
Problem started when updating to alpha.8 Git commit: 52c302307a677eb908459dd712ebe34102dd2a25. Built at: 2020-05-14 22:14:44+00:00
Problem persists using docker :latest Git commit: 62b617fa9a640f45f33e629f58333302ad25d7be. Built at: 2020-05-19 05:16:53+00:00

## 🔥 Error
Grafana:
![balance-shuffle](https://user-images.githubusercontent.com/10893517/82323229-09863f00-99d8-11ea-8cf1-16a9789dd37a.png)

## 🌍  Your Environment
Windows 10 Insider with WSL2 (Ubuntu 18.04) with Docker Edge experimental 2.3.0.1

**Anything else relevant (validator index / public key)?**
Validator has [50 keys](https://beaconcha.in/dashboard?validators=17134,18453,18454,18455,18456,18457,18458,18459,18497,18501,18502,18503,18504,18505,18506,18507,18508,18509,18510,18511,19716,19717,19718,19719,19720,19721,19722,19723,19724,19725,19726,19727,19728,19729,19730,19731,19732,19733,19734,19735,19736,19737,19738,19739,19740,19741,19742,19743,19744,19745).
Flags used (from PowerShell):
docker run -d --name Validator -v c:\DockerData\Prysm:/data -v "$($env:APPDATA)\ethereum2\wallets:/wallets" -p 8083:8083 gcr.io/prysmaticlabs/prysm/validator:latest --beacon-rpc-provider=192.168.0.100:4000 --keymanager=wallet --keymanageropts=/data/keymanager.json --datadir=/data --monitoring-port 8083 --enable-account-metrics --log-file=/data/log/validator.log

**Comment by GuillaumeMiralles** [comment]
I have seen another user having the exact same issue on discord
This 2 screenshots show the balance swaping with each other in the validator log
![image](https://user-images.githubusercontent.com/23481418/82681961-caadee80-9c4e-11ea-84af-8a9939e6ae31.png)
![image](https://user-images.githubusercontent.com/23481418/82682049-ed400780-9c4e-11ea-815c-37315cd331a7.png)


Here is the result in grafana

![image](https://user-images.githubusercontent.com/23481418/82682061-f0d38e80-9c4e-11ea-97e5-967ae450d7f0.png)

**Comment by LarsHolte** [comment]
Installed a new beacon node on Ubuntu 20.04 and started it with the prysm.sh script running alpha.8 git commit: f831a799c5a9133c8e3bdc396996ca98b6324b6e. Built at: 2020-05-14 01:18:22+00:00

After pointing the existing validator still running as a docker on WSL2 with the git commit 62b617fa9a640f45f33e629f58333302ad25d7be. Built at: 2020-05-19 05:16:53+00:00 to the new beacon node, the validator_balance is now back to normal.

Seems something on newer beacon nodes shuffles pubKeys messing up the validator metrics.

**Comment by GuillaumeMiralles** [comment]
This is happening to myself too now. Until the new release alpha 9 everything was fine, but when I updated my binaries with alpha 9 it started to shuffle my validator balances too.


![image](https://user-images.githubusercontent.com/23481418/83509563-ee352c80-a4cb-11ea-9be8-d12fa9379a80.png)

**Comment by Tachyonica** [comment]
I think I have the same issue.  Ubuntu 20, Windows 10, 4 keys plus 30 pending.


<img width="960" alt="Screenshot 2020-06-02 13 01 22" src="https://user-images.githubusercontent.com/45542100/83512959-491d5280-a4d1-11ea-8efd-d334fe3ea19f.png">

**Comment by slowbart** [comment]
I am still seeing this issue with alpha.9 docker images.

<img width="1199" alt="Untitled" src="https://user-images.githubusercontent.com/64903918/83636345-2ed69800-a5e9-11ea-8cde-82d724285bf9.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/64903918/83636464-5fb6cd00-a5e9-11ea-8492-5192db27c668.png">
