### ISSUE TITLE
Prysm Doesn't Run Rewards And Penalties Spec Tests

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5911]
# 🐞 Bug Report

### Description

Currently it appears that Prysm is actually skipping the Rewards and Penalties Spec tests. There have been test vectors for them in minimal, which we never run, probably missing some critical test cases. The way to resolve this is to add in the correct handlers for the rewards tests.

### Has this worked before in a previous version?

No

**Comment by terencechain** [comment]
Looks like this is only available for minimal and not  for mainnet

**Comment by terencechain** [comment]
Lowering the priority:
1.) These are minimal tests only
2.) v0.12 will come with better rewards and penalty tests for mainnet
3.) Will like to keep critical for run time blocker only

I can take a look at this today

**Comment by prestonvanloon** [comment]
Is there anything blocking the minimal config spec test?

**Comment by nisdas** [comment]
Closing this as #5916 is merged in
