### ISSUE TITLE
Allow States To Be Returned as SSZ Objects

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#5918]
# 🚀 Feature Request

### Description

Currently we do not have any easy way to retrieve our states as ssz objects, instead 
their json representation is returned with fields encoded in base64.

### Describe the solution you'd like

Our debug endpoints instead return the ssz representation of the state. Since
these endpoints are only for debugging runtime problems it would make sense for 
them to be ssz encoded.

### Describe alternatives you've considered

Manually converting the current format would be cumbersome.

**Comment by terencechain** [comment]
We should do the same for blocks as well

**Comment by rauljordan** [comment]
@terencechain that would be really hard if we tried to amend our current blocks endpoint to return ssz. You mean adding a new debug endpoint called debug/blocks that returns [][]byte ?

**Comment by rauljordan** [comment]
Would like to hear if there is a strong use case for it or required for the purposes of debugging

**Comment by terencechain** [comment]
For less UX friction, I think it has be a separate end point. Use case is to rerun state transition. Having ssz state is not enough without ssz block to rerun the state transition to debug consensus issues
