### ISSUE TITLE
Generate Random Seed to Shuffle Validator in Dev Mode

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#592]
Currently when we run beacon node in `--dev` mode, the validators don't get re-shuffled in between cycles. 
Reason is during new crystallized state transition, block chain service is not generating random seed and passing the random seed to the shuffle function.
It'd be cool to have this implemented for the demo so we can see validators gets reassigned to different incremental slots every cycle.

**Comment by rauljordan** [comment]
Closed by #597
