### ISSUE TITLE
Validator does not allow to create accounts with custom chain config

### ISSUE THREAD

**Issue by q9f** [prysmaticlabs/prysm#5922]
# 💎 Issue

Validator does not allow to create accounts with custom chain config. It does not accept flags such as `minimal-config`, `schlesi-testnet`, or `chain-config-file` and always defaults to mainnet accounts.

### Background

Witti testnet uses a different Genesis Fork Version than Schlesi.

https://github.com/goerli/schlesi/tree/master/prysm

### Description

Not being able to modify the Genesis Fork Version rendered my Prysm deposits on Witti invalid.

https://gist.github.com/ajsutton/8e03db5aea6e094d16333a7a0a0e5e39

**Comment by terencechain** [comment]
Closed via #5928
