### ISSUE TITLE
ListValidators is returning incorrect / unreliable results

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5933]
# 🐞 Bug Report

### Description

Discord discussion
https://discordapp.com/channels/476244492043812875/652609895941799976/712709237033271378

We are seeing a discrepancy between beaconcha.in, beacon.etherscan.io, and prometheus `max(validator_count{state="Active"})`. 

Users have also reported that sometimes they receive a particular count of validators and sometimes they receive another count with the same requests. 

### Has this worked before in a previous version?

Not sure when the issue started.

## 🔬 Minimal Reproduction

Not sure how to reproduce yet.

## 🔥 Error

No error, see description.

## 🌍  Your Environment

N/A - Affects all environments.

**What version of Prysm are you running? (Which release)**

<pre>
  <code>v1.0.0-alpha.8</code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by GuillaumeMiralles** [comment]
I believe that this issue is somehow related with #5907
