### ISSUE TITLE
Add a warning when the --rpc-port is already taken

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#5956]
# 🚀 Feature Request

### Description

When a user start his node, he doesn't know either the `--rpc-port` is already taken or not by another program. Which result by the validator that can't connect to it, and need some investigation to found out why is it

### Describe the solution you'd like

The user launch the node process, then at the start we could see either the `--rpc-port` is already taken by a warning, or maybe even an error? Since the validator won't be able to connect to it, there is no point to run the node all alone

**Comment by terencechain** [comment]
Thanks for opening this. It's a good first issue

**Comment by rauljordan** [comment]
The beacon node already logs the ERROR if the port is already taken @GuillaumeMiralles:

Tried this: example/main.go
```go
package main
 
import (
  "log"
  "net/http"
)

func main() {
  log.Fatal(http.ListenAndServe(":4000", nil))
}
```

Latest master branch, `bazel run //beacon-chain:beacon-chain`, received:
```
[2020-05-28 13:53:04] ERROR rpc: Could not listen to port in Start() 0.0.0.0:4000: listen tcp 0.0.0.0:4000: bind: address already in use
```
Let us know if this doesn't resolve your issue and we can reopen - thanks!

**Comment by GuillaumeMiralles** [comment]
@rauljordan that's weird. A user told me he haven't seen anything. Another one tested it too and didn't see anything. I'm gonna try that too a bit later
