### ISSUE TITLE
 INFO validator: Waiting to be assigned activation epoch positionInActivationQueue=2623 pubKey=0x953167d9252f status=PENDING

### ISSUE THREAD

**Issue by ambwembwe** [prysmaticlabs/prysm#5967]
Hi 

Its been over 10hrs and it does not look like my node is activated. I am just curious whether I should wait it out or redo the process given the message below

 INFO validator: Waiting to be assigned activation epoch positionInActivationQueue=2623 pubKey=0x953167d9252f status=PENDING

# 💎 Issue

### Background

 Context and background information on the discussion...

**Comment by prestonvanloon** [comment]
Based on the log you provided, there are nearly 2700 validators in the queue before you. Given that only 4 per epoch can be activated (900 per day), you can expect to wait about 3 more days from the time of that log.

Does that answer your question?

**Comment by ambwembwe** [comment]
Thanks I can wait just wanted to confirm that I have not missed a step or
anything.

**Comment by prestonvanloon** [comment]
Ok! No problem. Let us know if we can help clarify anything. It might be nice to print the estimated time til activation as well for clarity. If you’d like to file a feature request for that then we can look into it.

**Comment by ambwembwe** [comment]
that could a good feature to have but i know a lot about backlogs I am sure there other pressing issues. 

Thanks
