### ISSUE TITLE
Req: Add a list of Eth1 sync types that are required for the beaconnode to docs

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#5970]
A list of Eth1 client implementations (geth, parity, nethermind, etc.) and their sync types that are required to connect a beaconnode to. 
Maybe Eth1 teams can optimize these sync types even more then & users can test their hardware :)

**Comment by nisdas** [comment]
After #5826 is resolved, we should be able to support all eth1 clients. @Buttaa 
We would only require them to support a http rpc endpoint and for them to have stored
historical blocks and logs. I am pretty sure all clients would have a permanent record of chain history. An archival node isn't required for Prysm

**Comment by Buttaa** [comment]
@nisdas  

Geth has a few types..
full, fast, light, warp, leaf, snap(?), beam(?)

Not sure about the others. The idea is to run the viable ones along the testnet and check hardware usage. It would be wrong to test this a few days before the official launch.

**Comment by terencechain** [comment]
Blocked by #5826

**Comment by nisdas** [comment]
I think this is unblocked now, nethermind should work with prysm. @Buttaa have you tried it out ?

**Comment by Buttaa** [comment]
Not yet, i will give it a try next week!

There’s still one open task:
Since Eth1 nodes have different sync types, which one is required (excluding archival) to fulfill all Eth1 node requirements for the beaconnode? 
This might be a eth1 related question but still relevant for eth2 users. Please add a list of this to the docs.

- geth , —fast sync
- nethermind, (?)
- openethereum / (?)

**Comment by nisdas** [comment]
I do not know enough about sync modes in nethermind/open-ethereum but we should be able to support any node that is able to do the equivalent of `fast-sync` in those clients. 

We won't be able to support any `light sync` nodes from geth/nethermind/open-ethereum. But the default sync modes used should be fine. 

Although the obvious caveat is that you need a fully synced eth1 node before anything can be done.
