### ISSUE TITLE
GetDuties's P90 is  >2s

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5979]
# 🐞 Bug Report

### Description
Captured in cluster set up, `GetDuties`'s P90 is > 2s. That's too long and explains some of these context timeout issues seen on the validators side
![Screen Shot 2020-05-25 at 8 36 38 AM](https://user-images.githubusercontent.com/21316537/82828129-41243980-9e65-11ea-9289-f938be363ec7.png)

**Comment by rauljordan** [comment]
This has to do with how much data is requested and sent back as a polling call to the beacon chain. The new streaming approach does a single request with all validator keys and simply listens to received values over the stream. We can perform some metrics checks once the PR is merged in and compare using experimental.

**Comment by terencechain** [comment]
Let's monitor this for Onyx. Then we can close it

**Comment by rauljordan** [comment]
this is no longer an issue. We observe very situational 2.3s spikes, but nothing out of the ordinary as of current Onyx

<img width="1048" alt="Screen Shot 2020-07-22 at 9 54 07 AM" src="https://user-images.githubusercontent.com/5572669/88191728-5d441d00-cc01-11ea-9abd-822b4f53e620.png">
