### ISSUE TITLE
GetBlock's P50 is >2s

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5980]
# 🐞 Bug Report

### Description
GetBlock's P50 is > 2s and P90 is >8s. This explains some validators context timeout and reporting not as profitable as others. As we know, the main bottleneck for `GetBlock` is attestation aggregation. @farazdagi has started looking into aggregation optimizations

![Screen Shot 2020-05-25 at 8 36 24 AM](https://user-images.githubusercontent.com/21316537/82828221-6a44ca00-9e65-11ea-84ca-e8589994ecac.png)

**Comment by rauljordan** [comment]
Closing in favor of #4507 and #5801 as those are the culprits here and this issue doesn't have a direct resolution unless those are fixed
