### ISSUE TITLE
Kaspersky Antivirus Is Preventing Prysm's Internet Connection on Windows

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#5986]
# 🐞 Bug Report

### Description

A user running Prysm on windows was getting the error `ERROR: prysm requires an internet connection` when running Kaspersky antivirus on a windows machine. The user confirmed the error went away and was able to sync after temporarily disabling.

### Resolution

Amend the `ERROR: prysm requires an internet connection` to instead say `ERROR: Prysm requires an internet connection, perhaps your firewall or antivirus is blocking Prysm's internet access`

**Comment by raphpa** [comment]
This is a problem with curl not being able to pull the certificate revocation list as Kaspersky Internet Security intercepts all calls to port 80/443 and several others.
`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012)`

You can circumvent this by calling curl with --ssl-no-revoke

**Comment by raphpa** [comment]
Sorry, I was a bit unclear on that.
In the scripts you would have to add `--ssl-no-revoke` to every single curl call.

**Comment by Gusfzzm** [comment]
I'm having the same problem.
<img width="1333" alt="1698818773669" src="https://github.com/prysmaticlabs/prysm/assets/136805453/4c531777-3713-4a01-bb25-dd9d97911fa6">
I start the geth and then the consensus client and the following problem occurs
