### ISSUE TITLE
Validator Error

### ISSUE THREAD

**Issue by breadchain** [prysmaticlabs/prysm#5989]
# 🐞 Bug Report

Validator Error

First time user 

![111](https://user-images.githubusercontent.com/65928769/82848936-b1fa3e80-9ec3-11ea-96f1-e6ec2cedc90f.jpg)

## 🌍  Your Environment

**Operating System:**

Windows 10 Home
Intel i5-8250U CPU @1.60GHz 1.80 GHz
8.00 GB Ram
64 bit operating system 
**What version of Prysm are you running? (Which release)**

Prysm V1 alpha 8
**Anything else relevant (validator index / public key)?**
 pubKey=0xb786fad3b81fc0f7310bbb36a4d59e42a0a440553c2bc4f9d17463e01e40385a25aea07b99a65717ccabc33dbdec67b1

**Comment by terencechain** [comment]
@breadchain does the error persist?

**Comment by breadchain** [comment]
@terencechain it does.  Restarting beacon chain and validator does not seem to fix.

**Comment by prestonvanloon** [comment]
@terencechain can you please investigate and triage?

**Comment by terencechain** [comment]
This is such a rare incident which leads me to believe users have either
1.) local clock offset
2.) not enough cpu compute
alpha9 has lots of good improvements in that front, I'm going to put `Need-info` and let user respond both 1 and 2 are indeed good from their side, then try alpha9 to see if it's resolved

**Comment by breadchain** [comment]
![1](https://user-images.githubusercontent.com/65928769/83061363-d9b7e680-a02a-11ea-817d-629d82f5ce2e.jpg)

Looks like it was the local clock.  Looks to be running well now

**Comment by prestonvanloon** [comment]
Closing based on the most recent comment. Please open again if this issue is not resolved.
