### ISSUE TITLE
Witti genesis Status exchange: finalized root should be zeroed

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#6001]
# 🐞 Bug Report

### Description

The finalized-checkpoint in the genesis state has a zeroed root, so the Status should have a zeroed root too. However, Prysm used the actual block-root, equal to the head, and seems to ban others with a different finalized root. Lighthouse correctly follows the spec, but gets banned by the Prysm nodes because of this.

### Has this worked before in a previous version?

I was aware of the wrong root, but not the banning, and thought it was a non-issue first. But @paulhauner brought the banning to my attention, and it might have gone unnoticed with Schlesi luanch, since the genesis was so fast/small. After first finalized epoch however, it should start working.

## 🔬 Minimal Reproduction

See lighthouse and prysm status messages on Witti testnet.

## 🔥 Error

Peerstore dump of lighthouse where you can clearly see the status of each prysm peer:
https://gist.github.com/protolambda/905d8223f28f8f9dd3c3d5fd211bb41c

## 🌍  Your Environment

Running `:witti` docker image, and lighthouse with PR 1201 merged in (more lenient ENRs)

`gcr.io/prysmaticlabs/prysm/beacon-chain   witti               b958a7f62bbe `

**Comment by terencechain** [comment]
Resolved via #6002 in Witti 

The rest is tracked in #6006
