### ISSUE TITLE
Bazel dependency rule for Prysm

### ISSUE THREAD

**Issue by gnattishness** [prysmaticlabs/prysm#6005]
# 🚀 Feature Request

### Description

Implement a solution for external bazel projects to easily depend on Prysm.

Currently, this requires the external developer to copy the majority of Prysm's `WORKSPACE` into their own and update it whenever Prysm's `WORKSPACE` changes.

(This was originally discussed with @prestonvanloon out-of-band, but I've made the issue to track it)

### Describe the solution you'd like

The conventional solution would be for Prysm to define a `prysm_deps()` bazel rule in a `deps.bzl` file, which specifies all relevant dependencies for *building* Prysm, and would be called by Prysm's own `WORKSPACE`.

External projects can then, similarly, load the `deps.bzl` and call this `prysm_deps()` rule in their own `WORKSPACE`.

Below is an example of a fairly mature implementation of a similar setup:
https://github.com/google/tink/blob/8bdaed4f41edc01821be9b089123410be0b57a6c/tink_base_deps.bzl
With example usage as a depending project: https://github.com/google/tink/blob/8bdaed4f41edc01821be9b089123410be0b57a6c/examples/cc/WORKSPACE

Note the `if not native.existing_rule("rule_name")` notation, which stops the build from breaking if there is another/existing rule specifying the same dependency.
This allows the developer to choose a suitable version when more than 1 library requires the same dependency.

### Describe alternatives you've considered

Current workaround is mentioned in the initial description.

**Comment by prestonvanloon** [comment]
I’ll have this done by EOW. Thanks for filing an issue to track it!

**Comment by prestonvanloon** [comment]
This is in progress, should have a PR ready soon.
