### ISSUE TITLE
Return ZeroHash Instead of GenesisBlockRoot

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6006]
# 🐞 Bug Report

Currently in pre-genesis we return the genesis block root instead of a zerohash as the 
finalized root.

### Description

In pregenesis due to how our `chainservice` is structured, we return the genesis block root 
instead of the zerohash as our finalized checkpoint. A workaround was done in witti, to make
a special case for genesis. This issue is to track the resolution of the correct behaviour in master.

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Peer a Prysm Node With a Lighthouse Node.

## 🔥 Error

```
time="2020-05-26 22:24:21" level=warning msg="Failed to handle p2p RPC" error="invalid finalized root" peer=16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv prefix=sync topic="/eth2/beacon_chain/req/status/1/ssz_snappy"
```

**Comment by nisdas** [comment]
This is blocked until we have clarification here:
https://github.com/ethereum/eth2.0-specs/issues/1848

**Comment by prestonvanloon** [comment]
Based on feedback from https://github.com/ethereum/eth2.0-specs/issues/1848#issuecomment-637678479, zero hash is the correct approach.
