### ISSUE TITLE
Block api for slot=0 returns whole page instead of single block

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6009]
# 🐞 Bug Report

### Description
Using the block api (**eth/v1alpha1/beacon/blocks**) with ?slot=0 returns many blocks instead of 1. Before chainstart (after genesis) it only returned 1 (obviously). With a running chain, it returns a whole page with many blocks instead.

I think it should be possible on a running chain to query slot=0 where it then returns the genesis-block.
Observed this on witti.
 A clear and concise description of the problem...

### Has this worked before in a previous version?
don't know

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
Query the local beacon node with this:
`curl -s "http://localhost:4001/eth/v1alpha1/beacon/blocks?slot=0"|jq .`
You get many blocks (a whole page)

Do the same for a chain after genesis, but *before* start (to check for example the state root) then you correctly get this:
![2020-05-27_09-22-28](https://user-images.githubusercontent.com/28559038/82990419-7616c480-9ffc-11ea-93c3-4256bf03cfe9.png)

I would expect the same result (*only* one block) also on a running chain.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
witti branch, 2fe01459bc94309c5dcb67e214556ccb375f80dd
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
Hi @handelaar2 this is not the right usage of the API. If you want the genesis block, you need to do `"http://localhost:4001/eth/v1alpha1/beacon/blocks?genesis=true"`. Please see the usage in https://api.prylabs.network/#/BeaconChain/ListBlocks
