### ISSUE TITLE
`IntersectionUint64`, `IntersectionInt64`, `IntersectionByteSlices` return union if more than 2 slices are provided

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6029]
# 🐞 Bug Report

### Description

Pointed out by the Quantstamp team, the current function to return an intersection of input slices fails to return the intersection. Instead, it returns the union: https://play.golang.org/p/ewIKeH0sNoR

It works with two slices. But no more than that.

Implementation: https://github.com/prysmaticlabs/prysm/blob/master/shared/sliceutil/slice.go#L36

**Comment by kbak** [comment]
same bug occurs in `IntersectionInt64()`

**Comment by kbak** [comment]
also in `IntersectionByteSlices()`, see https://play.golang.org/p/IcxaciB5YbL
