### ISSUE TITLE
Use Proper Security Fallback

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6032]
# 🐞 Bug Report

Currently we have updated our v0.12 branch to the latest libp2p deps to support the new gossipsub. However, it was brought up by the quantstamp team that the security fallback of TLS has been added for the default option.

### Description

This issue is to track the resolution of this to instead only use noise with secio as the fallback.

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction
N.A

**What version of Prysm are you running? (Which release)**

04d6afa356ca666c4677027eeaec539c6b0facc5

**Comment by prestonvanloon** [comment]
Tentatively adding to v0.12 milestone. Is this a difficult feature to add?
