### ISSUE TITLE
As a golang developer I would like to just run go build

### ISSUE THREAD

**Issue by krasi-georgiev** [prysmaticlabs/prysm#6035]
A newcomer to the project expecting to just run `go build` and use some makefile, I am facing a full-blown bezel setup here. Wondering if you could provide some instructions on how to build it without bazel or explain what does the normal go build workflow is missing that bazel solves?

The main reason why I want to be able to run just `go build` is debugging. I normally run a debugger when trying to follow the code execution and with this bazel setup it makes it quite a challenge to run a debugger on vscode.

OTOH I just tried building it with bezel and it is taking quite a while where a simple `go build` would have probably taken a loss less time.

Sorry if this sound critic, just looking for the reasoning why use bazel instead of the go tooling.

**Comment by prestonvanloon** [comment]
Thanks for the feedback @krasi-georgiev. We're working on making Prysm work for local builds without Bazel (#6053) and we're looking to add documentation around Why Bazel? See https://github.com/prysmaticlabs/documentation/issues/138.

There are a few caveats to using go build for Prysm such as having precompiled c++ archives or pregenerated protobuf bindings. Bazel will always be slower than a `go build` as it is another layer on top of `go build` with many extra features. 

A short answer to "Why Bazel?" can be found in the description of #6053.
