### ISSUE TITLE
Types Tests Fail With Race Detection

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#604]
Types tests failed with race detection on in Travis and we have turned race detection off in types tests package. Opened this issue to investigate why it was failing with race on and how to resolve it.

https://travis-ci.org/prysmaticlabs/prysm/jobs/436267953

**Comment by rawfalafel** [comment]
The most suspicious part is the IO logic [here](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/crystallized_state.go#L49-L55). Can we test this theory by turning race back on and uncommenting `TestInitGenesisJson`?

**Comment by rawfalafel** [comment]
Resolved in #636

**Comment by terenc3t** [comment]
Looks like this is still there. Reopening

**Comment by rauljordan** [comment]
Fixed in #890
