### ISSUE TITLE
Slasher crashed: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6040]
# 🐞 Bug Report

### Description
Ran into a fatal error while using the slasher on the witti chain.
In fact I wanted to start fresh and so I deleted the slasher.db. Then restarted my slasher using:
`/home/ubuntu/prysm/bazel-bin/slasher/linux_amd64_stripped/slasher \
--datadir="/home/ubuntu/.eth2/witti" \
--verbosity=trace \
--enable-historical-detection=true `

Beacon continues to run with these relevant parameters:
`--verbosity=info \
--broadcast-slashing \
--witti-testnet \
--dev \
--enable-new-state-mgmt  \
--slots-per-archive-point=32 \
--grpc-gateway-port=4001 \
--disable-dynamic-committee-subnets \`

See the slasher log with the dump:
[slasher_fatal.log](https://github.com/prysmaticlabs/prysm/files/4701185/slasher_fatal.log)

### Has this worked before in a previous version?
no info

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
Stop the slasher in witti. Delete its slasher database and restart the slasher again.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
latest witti-branch: a9e63459ba518e785bf69fce7362264b81106864. Built at: 2020-05-29 07:31:37+00:00  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
@shayzluf and @0xKiwi please take a look at this issue

**Comment by 0xKiwi** [comment]
Thank you for reporting @handelaar2, will look into this.

**Comment by nisdas** [comment]
Has this been resolved @0xKiwi @shayzluf ?

**Comment by 0xKiwi** [comment]
It hasn't, but with the upcoming slasher db structure changes it should no longer be a problem.

**Comment by rauljordan** [comment]
No longer possible as the map read does not occur concurrently. See the latest code: https://sourcegraph.com/github.com/prysmaticlabs/prysm/-/blob/slasher/detection/attestations/spanner.go#L122
