### ISSUE TITLE
Add Peer Scorer To Gossipsub Router

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6043]
# 💎 Issue

Add Peer Score Option with Parameters to Gossipsub

### Background

Currently we have updated our version of gossipsub to v0.12, however we haven't been able to use any of the new peer scoring mechanics that have been introduced.

### Description

Currently the Gossipsub router doesn't support adding in the peer score handler for newly added topics. This makes peer scoring non-achievable due to the fact we utilize dynamic subscriptions for all our subnets. This issue is to track the eventual resolution of this.

Reference:
https://github.com/libp2p/go-libp2p-pubsub/issues/346

**Comment by rauljordan** [comment]
Update on this @farazdagi ? Is #6622 up to date?

**Comment by rauljordan** [comment]
Update on this one @farazdagi ? Any plans to pick this up soon?

**Comment by rauljordan** [comment]
Update on this one @farazdagi ?

**Comment by raulk** [comment]
The Lotus-side change has landed on master. Please take it out for a spin, and report back!

**Comment by farazdagi** [comment]
> Update on this one @farazdagi ?

@nisdas has created a draft branch https://github.com/prysmaticlabs/prysm/pull/7184, where he is experimenting with injecting peer scorer into p2p router.

**Comment by nisdas** [comment]
This can be closed gossip scoring has been enabled by default for a while.
