### ISSUE TITLE
Potential integer overflow cases

### ISSUE THREAD

**Issue by lpassos** [prysmaticlabs/prysm#6049]
# 🐞 Bug Report

### Description

 Following issue #6038, other places in code are also subject to integer overflow. 

Quantstamp reported:

> Some [potential] integer overflow cases:
(1) beacon-chain/rpc/validator/proposer.go: On L324, `BeaconConfig().MaxDeposits` is a `uint64`, but it is casted to `int`; (2) beacon-chain/rpc/validator/proposer.go (L296), beacon-chain/core/state/state.go (L81, L86),  beacon-chain/powchain/service.go (L175): `BeaconConfig().DepositContractTreeDepth` is a `uint64`, but it is casted to int in code; (3) beacon-chain/rpc/beacon/validators.go: On L84, L98, L228, L242, index is uint64, but it is casted to int

## 🔥 Error

Possible overflow.

**Comment by nisdas** [comment]
What would be the action item for something like this ? @terencechain @prestonvanloon 
Should we have maybe some sort of static analyzer to detect any castings that might lead to overflows with integers ?

**Comment by prestonvanloon** [comment]
We can add a static analysis where casting to a lower sized number is an error. 
That would be a good first issue too.
