### ISSUE TITLE
Warn Users They Are Using Our Hosted ETH1 Nodes

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6051]
# 🚀 Feature Request

### Description

Currently, prysm beacon nodes utilize our goerli ETH1 nodes by default, which can often times go down, leading to consequences for users. We should start encouraging people to find their own solutions to running ETH1 nodes in the spirit of decentralization, along with instructions on how to do so in prysm.

### Describe the solution you'd like

We should add a WARN level log if using default eth1 settings, encouraging users to run their own eth1 node and instructions on how to point their prysm beacon node to it using the web3provider flags.

**Comment by lpfloyd** [comment]
Hi. I would like to work on this if that's okay :)
I'm pretty new here and love the Ethereum community so I love you guys too haha

**Comment by prestonvanloon** [comment]
Assigned to @lpfloyd. Thanks for the help!

**Comment by lpfloyd** [comment]
Alright, awesome! I'll get started on this asap.

**Comment by rauljordan** [comment]
Hi @lpfloyd we would recommend this wording:
```
WARN: Using default ETH1 connection provided by Prysmatic Labs. Please consider running your own ETH1 node for better uptime, security, and decentralization of ETH2. Visit https://docs.prylabs.net/setup-eth1 for more information.
```
This should fire if the user is using the default flags for --web3provider and --http-web3provider

**Comment by lpfloyd** [comment]
Will do @rauljordan, thanks for the swift notice. This issue seems trivial enough to implement so I don't have any issues understanding it (i think). I'll open up a PR soon enough and get some feedback from you guys :)

However, I'm also taking this time to study some of the other modules as well and may need some help understanding certain things (beyond the scope of this issue) so please bear with me for the time being.

**Comment by rauljordan** [comment]
Hi @lpfloyd we'll take care of those docs. Perhaps you can issue the warning log in beacon-chain/node/node.go or beacon-chain/powchain/service.go - either should be ok IMO
