### ISSUE TITLE
Goerli is stalled. "eth1 client is not syncing"

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6057]
# 🐞 Bug Report

### Description

The Goerli PoA Test Network is currently experiencing difficulties producing blocks. 

- Warning message: "eth1 client is not syncing"
- No ETH1 transactions can be completed (no deposits, faucet funding, etc)

No new validator deposits will be recognized until Goerli starts producing blocks again and transactions can be included. Other than that, the Topaz and Witti ETH2 test networks should be unaffected. 

Assigning to Prysmatic Labs testnet oncall @terencechain @rauljordan

This issue will be closed when Goerli is OK again.

**Comment by prestonvanloon** [comment]
Discussion is happening in gitter: https://gitter.im/goerli/validators

**Comment by prestonvanloon** [comment]
Looks like a Goerli chain split. Some sealers will need to restart their nodes. It is the weekend and many sealers are EU based so it could be a few hours before we reach a resolution.

**Comment by tkstanczak** [comment]
Goerli is back up

Suggested votes:

Vote Yucong out (almost for sure he will not be signing again)
clique.propose("0x631ae5c534fe7b35aaf5243b54e5ac0cfc44e04c", false)

vote Dapowerplay out (not 100% sure about them but they have been silent for months now)
clique.propose("0xa8e8f14732658e4b51e8711931053a8a69baf2b1", false)

then we can check if Afri will be signing but I assume he will

**Comment by prestonvanloon** [comment]
Closing this as the immediate problem has been resolved. We'll cast those votes later today. Thanks
