### ISSUE TITLE
RecoverArchivedPoint Leads To Node Freezing And Eventually Crashing

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6059]
# 🐞 Bug Report

If restarting a node with the latest new state management enabled, the node freezes up and crashes.

### Description

The node crashes when applying the new state management whilst skipping historical state regeneration. 

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

```
./beacon-node --dev --skip-regen-historical-states --pprof --p2p-host-ip=$(curl v4.ident.me)
```

## 🔥 Error

![memBlowUp](https://user-images.githubusercontent.com/33201827/83346713-80fd8c00-a351-11ea-8379-8be4946ac744.png)

## 🌍  Your Environment

Ubuntu 18.04.4 LTS
Linux Kernel 4.15.0-101-generic

**What version of Prysm are you running? (Which release)**

ab5fbc72bf9beff40f2c84ef0d6d1b046a5fe4c9

**Comment by terencechain** [comment]
Thanks for opening this. Do you have the crash log?

**Comment by nisdas** [comment]
There wasn't any crash log, it just paused and did nothing after it processed its first batch of blocks and then froze and eventually my whole machine was unusable as there was a large OOM. I had to manually restart it

**Comment by prestonvanloon** [comment]
I had this issue as well. My computer locked up for almost 5 minutes. 
I was using `--dev --skip-regen-historical-states` as my only flags and it was unusable.

**Comment by rauljordan** [comment]
Any update on this @terencechain ?

**Comment by terencechain** [comment]
This won't be relevant soon. We just need to fully deprecate old state usages

**Comment by terencechain** [comment]
Old state usages are fully deprecated
