### ISSUE TITLE
Pending validator count reflects partially deposited validators

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6063]
# 🐞 Bug Report

### Description

There seem to be validators which have sent the minimum deposit value (1 ETH). These validators are not eligible for activation and are in a "pending" state. Typically, the "pending" state is understood as being in queue for activation. As such, this UX is causing some confusion for users trying to understand the queue size and their position in queue.

![image](https://user-images.githubusercontent.com/7246818/83359548-b7c2aa80-a32f-11ea-9068-029371d1c2c5.png)

*Prometheus report*

![Screenshot from 2020-05-31 11-13-23](https://user-images.githubusercontent.com/7246818/83359565-d3c64c00-a32f-11ea-952b-a3562c1f9558.png)

*Etherscan*

**Comment by 0xKiwi** [comment]
How should we go about this? This appears to be a gap in our determination of validator status.

**Comment by prestonvanloon** [comment]
We will need another status value. 

Here are the statuses we have at the moment:

```protobuf
enum ValidatorStatus {
  UNKNOWN_STATUS = 0;
  DEPOSITED = 1;
  PENDING = 2;
  ACTIVE = 3;
  EXITING = 4;
  SLASHING = 5;
  EXITED = 6;
}
```

To fix this, we can add a new enum value and clarify PENDING with a more strict definition.
- `PENDING` -- The validator is fully deposited and in the activation queue. 
- `PARTIALLY_DEPOSITED` -- The validator has not met the deposit threshold.

**Comment by michaelhly** [comment]
I can work on this. We just need to check for deposit amount > 32 ETH (in wei) here:
https://github.com/prysmaticlabs/prysm/blob/11c9699129029c0ee7bf83a738f2e650b7690bc3/beacon-chain/rpc/validator/status.go#L157
 and return the `PARTIALLY_DEPOSITED`status right?

**Comment by rauljordan** [comment]
@michaelhly what's the status on this one, how can we help?

**Comment by michaelhly** [comment]
@rauljordan Sorry, was a bit busy this week. Let me publish my PR. Just need to write tests.
