### ISSUE TITLE
GetvalidatorParticipation is reporting inaccurate values

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6070]
# 🐞 Bug Report

### Description

![image](https://user-images.githubusercontent.com/7246818/83431551-5876a000-a3ec-11ea-8c59-6a6b6d2a8295.png)

*Prometheus chart from last 30m*

![image](https://user-images.githubusercontent.com/7246818/83431604-6c220680-a3ec-11ea-8a15-c0e5d03aa20f.png)

*beaconcha.in recent epochs*

Beaconcha.in client side implementation: 
https://github.com/gobitfly/eth2-beaconchain-explorer/blob/b33cbd49a7d4826e9de49785b79e329d53872c18/rpc/prysm.go#L603

We can see here that the prometheus reported values are lower than the recorded values in beaconcha.in. Etherscan seems to experience the same issue. I believe that the prometheus metrics are accurate while the API reported values are higher than they should be. Perhaps not capturing the entire validator set for participation consideration?

Adding to v0.12 restart milestone as this should be addressed prior to any testnet restart.

**Comment by terencechain** [comment]
Hard to tell from the Grafana timestamp which epoch aligns to what time. I cross checked the implementations between metrics, rpc server side implementation and client side implementation, and they all seem correct.

The next thing to check is when client calls `GetValidatorParticipation(epoch uint64)` and what epoch does it pass in.  For the metrics, it captures right before processing of the first epoch slot, and it captures the participation of previous epoch. Example, before when processing slot 128, it captures participations of slot 64 -> slot 96

**Comment by terencechain** [comment]
cc @ppratscher

**Comment by prestonvanloon** [comment]
One thing I realized later is that our prometheus screenshot is an average value, so it might be slightly lower if any particular node is out of sync.

**Comment by rauljordan** [comment]
Is this still an issue @terencechain @prestonvanloon ?

**Comment by prestonvanloon** [comment]
I think there is still some issue. We still see some random dips in participation on block explorers. 

See comment from Danny: https://discordapp.com/channels/595666850260713488/724994681460490260/728618913163772004

![Screenshot from 2020-07-04 12-22-58](https://user-images.githubusercontent.com/7246818/86519601-209ab800-bdf1-11ea-9def-03c458fb4ee9.png)

There hasn't been any investigation into this yet, but I think we should keep it open until we confirm there is not an issue. Perhaps we can write a tool to frequently poll various recent epochs for participation then check them again once they are finalized. 

@peterbitfly Do you have any input on this? I noticed that the graphs on beaconcha.in have been resolved since Danny's comment. Was there a potential issue in Prysm's endpoints that you noticed?

**Comment by rauljordan** [comment]
Hi @peterbitfly wondering if you have more input on this

**Comment by guybrush** [comment]
In the last posted chart here: https://github.com/prysmaticlabs/prysm/issues/6070#issuecomment-653802308 the reported network-liveness was very high arround the epoch ~880, see epochs 881 and 883:

https://altona.beaconcha.in/epoch/881 - 1ETH voted, 0% participation rate (as reported by api)
https://altona.beaconcha.in/epoch/883 - 1ETH voted, 0% participation rate (as reported by api)

For participation-rate we basically write 1:1 into our db what we get from prysm.

Maybe this was related to #6417? But it got merged before altona, so at least the last posted chart from @prestonvanloon is not related.

Here is the chart from discord with better resolution: 
![altona-high-nl](https://user-images.githubusercontent.com/306324/88262814-32bd9700-ccc9-11ea-94d7-058706e6afb4.jpg)

Please note that avg-validator-income and total-accumulated-staking-reward charts are currently broken on altona.beaconcha.in also on beaconcha.in we have incomplete data in the db until epoch ~3325 (due #6417) - not sure if its worth fixing it with medalla being close.

**Comment by guybrush** [comment]
This is from the node we currently use for altona.beaconcha.in:
```
$ curl "localhost:3502/eth/v1alpha1/node/version"
{"version":"Prysm/v1.0.0-alpha.13/c2deab8948a634f3c64096337d243002f493b1d3. Built at: 2020-07-09 03:45:37+00:00","metadata":""}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=880"
{"epoch":"880","finalized":true,"participation":{"globalParticipationRate":0.8595156,"votedEther":"39744000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=881"
{"epoch":"881","finalized":true,"participation":{"globalParticipationRate":0.000021626298,"votedEther":"1000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=882"
{"epoch":"882","finalized":true,"participation":{"globalParticipationRate":0.86020756,"votedEther":"39776000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=883"
{"epoch":"883","finalized":true,"participation":{"globalParticipationRate":0.000021626298,"votedEther":"1000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=884"
{"epoch":"884","finalized":true,"participation":{"globalParticipationRate":0.86020756,"votedEther":"39776000000000","eligibleEther":"46240000000000"}}
```

This is from a node I am using for doing my experiments:
```
$ curl "localhost:3502/eth/v1alpha1/node/version"
{"version":"Prysm/v1.0.0-alpha.15/0e4cb68249892daa9e142ae6033da202c7fb01bb. Built at: 2020-07-18 03:54:27+00:00","metadata":""}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=880"
{"epoch":"880","finalized":true,"participation":{"globalParticipationRate":0.8595156,"votedEther":"39744000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=881"
{"epoch":"881","finalized":true,"participation":{"globalParticipationRate":0.8858132,"votedEther":"40960000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=882"
{"epoch":"882","finalized":true,"participation":{"globalParticipationRate":0.86020756,"votedEther":"39776000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=883"
{"epoch":"883","finalized":true,"participation":{"globalParticipationRate":0.8560554,"votedEther":"39584000000000","eligibleEther":"46240000000000"}}
$ curl "localhost:3502/eth/v1alpha1/validators/participation?epoch=884"
{"epoch":"884","finalized":true,"participation":{"globalParticipationRate":0.86020756,"votedEther":"39776000000000","eligibleEther":"46240000000000"}}
```

So I am guessing that the state in the database is still wrong on our altona-production-node and I can only fix it by resyncing a new node and delete the wrong entries.

**Comment by terencechain** [comment]
Can be closed. Discussion: https://discordapp.com/channels/476244492043812875/603588441741066241/742300946503172177
