### ISSUE TITLE
Libp2p updates are causing p2p peering issues in Topaz

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6077]
# 🐞 Bug Report

### Description

Something in #6053 has caused an issue where Prysm nodes are unable to peer with external nodes. Earlier today, Prylabs nodes entered an isolated partition after a normal rollout with #6053 included.

### Has this worked before in a previous version?

Rolling back to alpha.9 release has resolved the issue temporarily. 

## 🔬 Minimal Reproduction

To be determined...

**Comment by nisdas** [comment]
So the main cause for this is that we updated our kademlia dht library. However our previous version was v0.2.1, while https://github.com/libp2p/go-libp2p-kad-dht/releases/tag/v0.3.0 was a breaking release. And every release after that was also a breaking change. We ultimately updated to v0.8.1, which had many breaking changes along the way. Updating our local nodes to use this, was breaking compatibility with our current kad-dht bootnode.

Also discvoveryV5 does not work well with our cluster nodes, they were unable to peer with external  peers and only were able to peer with local nodes. 

Also related #5864 .

**Comment by prestonvanloon** [comment]
So we can rollback our kad-dht dependency to v0.2.1 until it is removed in #5864? 

Do we have any sense for why discv5 performs so poorly behind a NAT or virtual network?
