### ISSUE TITLE
Default or option to not write withdrawal key pairs to disk

### ISSUE THREAD

**Issue by ethers** [prysmaticlabs/prysm#6078]
https://lighthouse-book.sigmaprime.io/key-managment.html#withdrawal-keypairs

>  adopted a strategy where we do not save withdrawal keypairs to disk by default (it is opt-in). Instead, we assert that since the withdrawal keys can be regenerated from a mnemonic, having them lying around on the file-system only presents risk and complexity.
> 
> withdrawal keypairs can be trivially regenerated from the mnemonic via EIP-2333 so they are not saved to disk like the voting keypairs.

**Comment by terencechain** [comment]
Added this request to #6220. Let's track this feature there
