### ISSUE TITLE
测试币怎么领不成功呀

### ISSUE THREAD

**Issue by fengchaojiangithub** [prysmaticlabs/prysm#6079]

**Comment by prestonvanloon** [comment]
Hi @fengchaojiangithub, Could you help provide some details to your issue please?

**Comment by fengchaojiangithub** [comment]
Error: recaptcha error

> @fengchaojiangithub嗨，您能为您的问题提供一些详细信息吗？

**Comment by rauljordan** [comment]
你的Goerli ETH1 address 是什麼？@fengchaojiangithub

**Comment by fengchaojiangithub** [comment]
0xCA3b9435C206870fF00D6F17f72F5f0C76866c4d

**Comment by fengchaojiangithub** [comment]
麻烦大佬看下

**Comment by rauljordan** [comment]
Sent 100 @fengchaojiangithub

**Comment by fengchaojiangithub** [comment]
谢谢

**Comment by fengchaojiangithub** [comment]
https://prylabs.net/participate   除了这里还有没有稍微详细点的教程呀

**Comment by rauljordan** [comment]
除了https://prylabs.net 和 https://docs.prylabs.network 之外，我们还需要使用中文documentation.

看看 https://docs.prylabs.network

**Comment by fengchaojiangithub** [comment]
好的
谢谢
