### ISSUE TITLE
Mixed paths when using the default options

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6081]
# 💎 Issue

Depending on which OS you are, the docs will lead to different paths. 

```
https://docs.prylabs.network/docs/install/mac/

beaconnode: mkdir prysm --> $HOME/Prysm

https://docs.prylabs.network/docs/install/mac/activating-a-validator/

validator: $Home/.eth2validator
```

Discussion:
https://discordapp.com/channels/476244492043812875/476588476393848832/717311627858542612

Focusing on a single OS also leads to different paths. Seems to be a prysm client & docs issue

**Comment by rauljordan** [comment]
No longer relevant on the newer install guides
