### ISSUE TITLE
Running beacon-chain with --interop-genesis-state doesn't allow minimal config

### ISSUE THREAD

**Issue by lsankar4033** [prysmaticlabs/prysm#6089]
# 💎 Issue

Right now, running the beacon-chain with --interop-genesis-state assumes an ssz file with field sizes corresponding to mainnet config. I'm using this option to seed a testable prysm client with predictable beacon state for https://github.com/lsankar4033/stethoscope.

This is because the interop cold start code uses https://github.com/prysmaticlabs/prysm/blob/master/proto/beacon/p2p/v1/types.pb.go#L28 which implies mainnet config sizes for fields. I'm working around this by modifying this file in a fork for now.

This isn't high priority as it's not a production bug and I can hack a workaround for my use case, but I figured I'd flag it.

**Comment by rauljordan** [comment]
Hi @lsankar4033 please see https://gist.github.com/rauljordan/50302db7bb175c713d004cec8be601ea. You will need to run with --define=ssz=minimal for the beacon chain, validator, and the genesis state creation tool

**Comment by rauljordan** [comment]
The example in linked gist uses mainnet config, but should be easy to switch if you do `--define=ssz=minimal`

**Comment by lsankar4033** [comment]
forgot about this; this does what i want. sorry for the noise
