### ISSUE TITLE
Process Deposit Allocates a Large amount of Memory

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6104]
# 💎 Issue

Currently in runtime, memory usage for the beacon node can spike up dramatically. This happens whenever we have a block with deposits in them.

### Background

Each block that we receive with deposits is required to be processed in the beacon node. In the event that our head state's validator registry is shared with another state, we will need to copy the whole validator set.

### Description

The copying of each validator happens in `AppendValidator` . Due to the validator registry being the largest component of the state, doing this constantly is very taxing on the memory requirements of a node. Also the whole validator map is copied with each deposit being processed. Once the validator set crosses 30,000. Performing operations on the it become more expensive.

Previously we did implement a solution for this that was reverted [here](#5701) . Due to how much core consensus code this touched and the potential of a validator being incorrectly mutated, it was decided that it was better to revert it.

In order for this issue to be resolved, a tangible solution to this would have to be defined that would be something other than copy-on-write. The validator registry's constantly growing size makes this infeasible to do long term and is also a potential DOS vector.

**Comment by rauljordan** [comment]
Is this resolved by your append validator optimization @terencechain ?

**Comment by terencechain** [comment]
Sounds like it should. I'm going to close this until there's further notice

**Comment by prestonvanloon** [comment]
@terencechain wasn't the append validator optimization rolled back?
https://github.com/prysmaticlabs/prysm/pull/6659
https://github.com/prysmaticlabs/prysm/pull/6710

**Comment by terencechain** [comment]
@prestonvanloon That's correct. This should be opened

**Comment by nisdas** [comment]
Resolved by #6910
