### ISSUE TITLE
Avoid a lot of increase/decrease balance locking

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#6111]
# :fast_forward: optimization

### Background

Balance updates are inefficient. Most balances change very little, but they do change. They need to be updated, and the Increase/Decrease code path is long, and involves locks. This happens for each validator, each epoch.

As discussed in discord:
```
proto Today at 9:26 PM
Is Prysm using the new rewards tests? I see that attestationDelta in pre-compute package on the v0.12 branch does not yet return different values for each of the reward types. Do you sum the test vectors and compare that? The intention was to make it as transparent as possible what happens in the transition here.

terence Today at 9:34 PM
The new rewards tests are in the v0.12 branch. And yes to summing the individual component then compare the total. To compare the individual component one by one requires further refactor. It's a nice to have, we'll probably do it post v0.12 launch

proto Today at 9:41 PM
My strategy in zrnt was to keep the old structure, but just output multiple lists of rewards/penalties, per type. Then compare individually. And for the processing part, sum them up (and old balances), create a new balances tree, and replace the balances all at once. This avoids a lot of function calls, and some the tree-replacement is more efficient too

You're calling UpdateBalancesAtIndex for every balance mutation. So you'll be locking 30.000 times per epoch transition. While you can probably read the balances tree in one go. Create a new one, and then replace with a single lock/unlock call.
```

### Description

The code path is long, and involves many locks:

`ProcessRewardsAndPenaltiesPrecompute` > `IncreaseBalance` + `DecreaseBalance` > `BalanceAtIndex` (read lock/unlock) + `UpdateBalancesAtIndex` (read lock/unlock + write lock/unlock after + various state checks)

For `N` validators, that is `2*2*N` read locks and unlocks, and another `2*N` write locks/unlocks. Only the first lock could be contentious, after that you fork out a copy and the next locks are useless. It's amazing Go is so fast here, but I still think this can and should be avoided.

Copy over the balances (like done in other places, and it's just a single array of integers, so no biggie), then operate on that. And replace the balances subtree as a whole, as it's expected that most balances have changed (assuming most validators are active).

Quick link to part of the affected code:
https://github.com/prysmaticlabs/prysm/blob/c4afb8e2e73ba2268e2831e9010b6ddfab8a8d66/beacon-chain/core/epoch/precompute/reward_penalty.go#L44

**Comment by nisdas** [comment]
Addressed with #6122
