### ISSUE TITLE
Use Ferran's Generated SSZ Instead of Generic SSZ, Remove Bazel Passthrough

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6116]
# 💎 Issue

### Background

Currently, everywhere we do ssz.Marshal or Unmarshal, bazel applies a runtime patch to use ferran's fast ssz for whitelisted structs instead. This is a security hole when running with the normal Go tool. Instead, we should actually use ferran's fast ssz instead of go-ssz when we need to.

**Comment by protolambda** [comment]
Removing `go-ssz` is important, as I believe `compositeSliceSSZ` in go-ssz doesn't check list limits. Making it susceptible to a network split if used in production in a multi-client testnet. And there have been others problems, as discussed in discord. And with a new better SSZ, I am all for replacing the bazel build step to just default prysm to a safe and fast ssz, in every build mode. :clap:

**Comment by prestonvanloon** [comment]
I think this is related: https://github.com/prysmaticlabs/prysm/issues/5981
