### ISSUE TITLE
Sudden spike in mem and CPU usage + result with a big crash of the validators balance

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6123]
# 💎 Issue

### Description

A sudden spike of mem and CPU usage (about 6-10 times more than usual) for few seconds, with no specific errors neither warnings reported at all. This first spike has been followed a bit after by a crash of all my validators balance of about 0.5 ETH each. Then when the balances has been fixed there was a second spike of CPU usage, mem didn't move much

![image](https://user-images.githubusercontent.com/23481418/83732402-46933800-a64c-11ea-82f1-21c130f1a522.png)

### Has this worked before in a previous version?

This is not the first time I see this happening, even though it's pretty rare, but this is the first time this is that big. I will update this issue each time I see this pattern again

## 🔬 Minimal Reproduction

N/A

## 🔥 Error

N/A

## 🌍  Your Environment

**Operating System:**
Windows 10 HOME, with 16 GB RAM

**What version of Prysm are you running? (Which release)**
Alpha 9 using the prysm.bat

**Comment by GuillaumeMiralles** [comment]
Got another spike, smaller, but still. It seems to be more frequent that it was before
![image](https://user-images.githubusercontent.com/23481418/83743574-3171d580-a65b-11ea-8f48-2ad59e8e6147.png)

Also here are all the spikes in the last 24 hours
![image](https://user-images.githubusercontent.com/23481418/83743789-7eee4280-a65b-11ea-831a-9c1393b1b0b3.png)

**Comment by GuillaumeMiralles** [comment]
I noticed that this happens just when we got participation rate flirting with the 66%. Could it be the reason?

Also this time I get a loooot of errors. I dunno why

![image](https://user-images.githubusercontent.com/23481418/83783335-677d7c80-a690-11ea-936e-c7766e4f8dc6.png)

**Comment by GuillaumeMiralles** [comment]
Last comment, so you can see the pattern is always the same. Sudden spike in CPU and memory usage, then a temporary crash in validators balance. I won't post any others from now on, since it seems to always have this pattern or almost.

![image](https://user-images.githubusercontent.com/23481418/83874420-b4675e80-a735-11ea-9297-77507b537031.png)

**Comment by raphpa** [comment]
I also do have sudden memory usage spikes and other graphs dropping out at the very same moment, so it seems beacon-chain is quite busy at that moment and not giving metrics. Also memory usage continuously raises over time.

![image](https://user-images.githubusercontent.com/18283997/83941066-9575d480-a7e8-11ea-964f-e98c6f5f96b3.png)

**Comment by GuillaumeMiralles** [comment]
This is the error I get when a spike is happening
![image](https://user-images.githubusercontent.com/23481418/83944785-784ffe80-a806-11ea-851a-9dbdfeab03bf.png)

This error has been fixed already (@nisdas speaking)

So this issue might have been sorted out with it then

**Comment by raphpa** [comment]
After fixing the database issues in #6156 the RAM spiking issues have resolved as well for me

![image](https://user-images.githubusercontent.com/18283997/83968368-07254f80-a8c9-11ea-9b62-f3c0d393200c.png)

**Comment by nisdas** [comment]
This has been resolved by #6149, so closing this now. This fix will be included in alpha.10, if we do have a next release for Topaz.
