### ISSUE TITLE
beacon-chain panic on stopping when deployed in docker swarm mode

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6133]
# 🐞 Bug Report

### Description

When scaling down (stopping) a dockerized beacon-chain in docker swarm mode docker-chain does not exit gracefully and crashes. When scaling up (starting) again, beacon-chain starts to resync from a point where it exited gracefully the last time.

### Has this worked before in a previous version?

I did not notice it happening before. However I assume it worked before as beacon-chain starts resynching the chain from the point where the container was updated to alpha 9.

I would also expect the database to not completely roll back for days. Not sure if that has worked before or is expected to work that way.

## 🔬 Minimal Reproduction

Stack deploy beacon-chain alpha 9 in swarm mode. Scale up the service.
`docker service scale prysm_beacon-chain=1`

Scale down the service to 0 again
`docker service scale prysm_beacon-chain=0`

## 🔥 Error

Beacon-chain starts shutting down and panics as prometheus.Service does not exit

<pre>
time="2020-06-04 18:49:20" level=info msg="Got interrupt, shutting down..." prefix=node
time="2020-06-04 18:49:20" level=info msg="Stopping beacon node" prefix=node
time="2020-06-04 18:49:21" level=info msg="Saved full state on epoch boundary" blockRoot=aa9944720c4d prefix=state-gen slot=321792
time="2020-06-04 18:49:21" level=info msg="Processing block 0xcfae0791... 321793/344046 - estimated time remaining 1h52m23s" blocksPerSecond=3.3 peers=3 prefix=initial-sync
time="2020-06-04 18:49:22" level=panic msg="Could not stop the following service: *prometheus.Service, context deadline exceeded" prefix=registry
panic: (*logrus.Entry) (0x17537e0,0xc00a4ae7e0)

goroutine 13407 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000140690, 0xc00079e900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        external/com_github_sirupsen_logrus/entry.go:239 +0x2da
github.com/sirupsen/logrus.(*Entry).Log(0xc000777e30, 0x0, 0xc00d10eea0, 0x1, 0x1)
        external/com_github_sirupsen_logrus/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000777e30, 0x0, 0x17a9f15, 0x2c, 0xc00d10ef20, 0x2, 0x2)
        external/com_github_sirupsen_logrus/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        external/com_github_sirupsen_logrus/entry.go:352
github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StopAll(0xc000652160)
        shared/service_registry.go:57 +0x165
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Close(0xc0001600c0)
        beacon-chain/node/node.go:239 +0xdf
created by github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start.func1
        beacon-chain/node/node.go:218 +0x17d
</pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04 LTS
Docker 19.03.8

**What version of Prysm are you running? (Which release)**

Alpha 9 
gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-3fe47c

**Comment by nisdas** [comment]
Seems like an issue with prometheus here. Were you by any chance fetching data from the prometheus server at that moment ?

**Comment by raphpa** [comment]
Prometheus was running as well, so it is pretty likely that it was fetching data at that moment.

**Comment by raphpa** [comment]
Cannot reproduce this anymore, so it might have been also related to #6156 somehow.
