### ISSUE TITLE
bazel build fails if using bazel 3.2.0

### ISSUE THREAD

**Issue by Pablosan** [prysmaticlabs/prysm#6144]
# 🐞 Bug Report

### Description

Build instructions [here](https://docs.prylabs.network/docs/install/mac/bazel/) recommend using the latest version of Bazel which is 3.2.0, but the build will fail with a message that states Bazel 3.0.0 is required.

### Has this worked before in a previous version?

Yes, this would have worked up until the point Bazel's latest version was incremented up from 3.0.0

## 🔬 Minimal Reproduction

* Install Bazel 3.2.0
* Attempt a build

## 🔥 Error

I failed to capture the output, but it was very obvious that 3.0.0 was required.

## 🌍  Your Environment

Mac OS X 10.15.5 but this will happen in any environment.

**What version of Prysm are you running? (Which release)**

Latest as of 5 June, 2020. Client built from source.

This could either be fixed by relaxing the version requirements to `>=3.0.0` or by updating the requirement to `3.2.0`. I'm happy to work on a PR based on your guidance.

**Comment by nisdas** [comment]
> This could either be fixed by relaxing the version requirements to >=3.0.0
I think the right approach should be to allow versions up from `3.0.0` onwards to be compatible. There is no reason 3.2.0 shouldn't work. 
@prestonvanloon thoughts ?

**Comment by prestonvanloon** [comment]
Please paste the error. I just tried building with 3.2.0 and had no issues.

```
/tmp/bazel-3.2.0-linux-x86_64 build //beacon-chain //validator
...
INFO: Build completed successfully, 94 total actions
```

**Comment by Pablosan** [comment]
Hi @prestonvanloon. Here is the exact error:

`ERROR: The project you're trying to build requires Bazel 3.0.0 (specified in /Users/pablosan/src/prysm/.bazelversion), but it wasn't found in /usr/local/Cellar/bazel/3.2.0/libexec/bin.`

When I check the `.bazelversion` file, I see:

```
(master) % cat .bazelversion                                                                                              ~/src/prysm
3.0.0
```

`git log` on the file:

```
'fa435d39b - Update bazel to 3.0.0 (#5363) (8 weeks ago) <Preston Van Loon>'
'a43a40c1c - Create .bazelversion (#5003) (3 months ago) <prylabs-bulldozer[bot]>'
```

If I update the contents of the `.bazelversion` file to `3.2.0`, the build works fine.

**Comment by prestonvanloon** [comment]
I think it might make more sense to recommend users to use bazelisk which will automatically select the correct bazel version to use.

This is available as a homebrew formula here: https://formulae.brew.sh/formula/bazelisk.

Maybe some instructions like
```
brew install bazelisk
echo "alias bazel=bazelisk" >> ~/.bashrc 
source ~/.bashrc
```

**Comment by Pablosan** [comment]
Ah, yes, that makes sense and works fine. `bazel` is new to me as I haven't been using Go for a while. I'll switch to using bazelisk.
