### ISSUE TITLE
error/loop during sync: could not get prestate for slot 350432

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6148]
# 🐞 Bug Report

### Description

Updating to latest commit (302b0f8c802c0ae1e342135be69d031c59e4b558)
During sync (right after initial sync), it went into a loop with the same error.
In fact, there are two errors:
- could not get pre state for slot 350432
- ERROR sync: Failed to retrieve pre state error=unknown state summary
could not get state summary

![2020-06-05_18-10-30](https://user-images.githubusercontent.com/28559038/83901418-066eab00-a75b-11ea-9afd-e8a7fc188bb6.png)

A restart solved the above error. However syncing has become so slow that is is impossible

Full log:
[error.txt](https://github.com/prysmaticlabs/prysm/files/4737429/error.txt)

### Has this worked before in a previous version?
Previous version I ran (24d315c6d1ba47cadcdb063fc810e29e5368d8f0) worked normally

## 🔬 Minimal Reproduction

restarted beacon with 
--dev \
--grpc-gateway-port 4001 \
--http-web3provider=http://172.18.0.2:8545 \
--verbosity=info \
--datadir=/data \
--min-sync-peers=3 \
--p2p-host-ip=$(curl -s v4.ident.me) \
--log-file=/data/beacon.log \
--p2p-max-peers=30 

(inside a docker container

## 🔥 Error

<pre><code>
log posted above
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
latest see git commit mentioned earlier
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
I have seen this as well:
```
[2020-06-04 13:28:52] ERROR sync: Failed to retrieve pre state error=unknown state summary
could not get state summary
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).StateByRoot
	beacon-chain/state/stategen/getter.go:28
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
	beacon-chain/blockchain/process_attestation_helpers.go:42
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
	beacon-chain/blockchain/receive_attestation.go:79
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
	beacon-chain/sync/validate_committee_index_beacon_attestation.go:72
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
	beacon-chain/sync/subscriber.go:176
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
	external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373
could not get pre state for slot 344544
```

I don't see how this is `sync` related though. The error means an incoming attestation doesn't    have the corresponding block in the db. With that said. We still should look into why

**Comment by farazdagi** [comment]
![image](https://user-images.githubusercontent.com/188194/83903524-f6f55f00-a766-11ea-8718-daa36ecc037f.png)

The issue happens right after initial sync, when normal p2p sync/communication starts.

**Comment by nisdas** [comment]
@terencechain can we close this ?

**Comment by GuillaumeMiralles** [comment]
This error has been fixed for me with the flag `--slots-per-archive-point=256` that we have seen in the issue #6156 

This error was also resulting a huge spike of mem and CPU usage (#6123)

**Comment by nisdas** [comment]
ok thanks for confirming @GuillaumeMiralles , closing this now then
