### ISSUE TITLE
Crosscheck Hash Functions Against Spec

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#616]
Danny updated the general hash function spec for ETH2.0 client. I think now is a good time to cross check prysm (`beacon-chain` and `validator`) code base to ensure everywhere is using the correct hash function. In the write up: 

> We aim to have a STARK-friendly hash function `hash(x)` for the production launch of the beacon chain. While the standardisation process for a STARK-friendly hash function takes place—led by STARKware, who will produce a detailed report with recommendations—we use `BLAKE2b-512` as a placeholder. Specifically, we set `hash(x) := BLAKE2b-512(x)[0:32]` where the `BLAKE2b-512` algorithm is defined in [RFC 7693](https://tools.ietf.org/html/rfc7693) and the input `x` is of type `bytes`.

**Comment by IvanTheGreatDev** [comment]
So to be clear, the client should not be using keccak256 anymore?

**Comment by rauljordan** [comment]
@IvanTheGreatDev we've been using blake2b for all ETH2.0 related items, no more keccak
