### ISSUE TITLE
加了第二个验证器，运行不了

### ISSUE THREAD

**Issue by fengchaojiangithub** [prysmaticlabs/prysm#6178]
![131414](https://user-images.githubusercontent.com/22792162/84106360-7af06500-aa4d-11ea-8414-6a3549f93c40.png)

**Comment by nisdas** [comment]
@fengchaojiangithub Please stop opening issues like this. If you need help in running the beacom node, you can ask in our discord channel 
https://discord.gg/AnQ5Er . we will be happy to guide you there
