### ISSUE TITLE
Nethermind <> Prysm "Could not query block with height 2848563"

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6204]
![image](https://user-images.githubusercontent.com/26490734/84277573-03493580-ab34-11ea-9054-874376634d53.png)

`prysm.sh beacon-chain --datadir=$HOME/prysm --http-web3provider=http://localhost:8545/`

`Nethermind.Runner --config goerli --JsonRpc.Enabled true`

**Comment by MysticRyuujin** [comment]
I've just noticed this same error message in `ethereal` but...it's intermittent...

```
chase@eth2test:~$ ethereal network blocktime
Block 2856856 mined at 2020-06-11 15:17:54 -0500 CDT
Block 2856784 mined at 2020-06-11 14:59:54 -0500 CDT
15s
chase@eth2test:~$ ethereal network blocktime
Failed to obtain information about latest block: json: cannot unmarshal hex number with leading zero digits into Go struct field rpcBlock.transactions of type *hexutil.Big
chase@eth2test:~$ ethereal network blocktime
Failed to obtain information about latest block: json: cannot unmarshal hex number with leading zero digits into Go struct field rpcBlock.transactions of type *hexutil.Big
chase@eth2test:~$ ethereal network blocktime
Block 2856861 mined at 2020-06-11 15:19:09 -0500 CDT
Block 2856789 mined at 2020-06-11 15:01:09 -0500 CDT
15s
```

**Comment by MysticRyuujin** [comment]
I'd bet $ on this being an issue with the handling of HTTP/1.1 chunked transfers

**Comment by prestonvanloon** [comment]
Users have reported large log files due to flooded logs regarding Nethermind RPC issues. Assigning medium priority as this could lead to disk space exhaustion.

**Comment by rauljordan** [comment]
This is not necessarily something we can fix on our end. If it still reported, we can bring it back up or get in touch with the nethermind team
