### ISSUE TITLE
Rate limiting on infura eth1 node, no backoff of beacon-chain

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6206]
# 🐞 Bug Report

### Description

After getting rate limited on the infura eth1 node beacon-chain keeps trying to poll the endpoint every second. This causes the rate limiting to not resolve.

### Has this worked before in a previous version?

Have not seen any rate limiting. It is to check if polling is too fast either way.

## 🔬 Minimal Reproduction

Use infura endpoint.

## 🔥 Error

beacon chain error message, repeating every second
<pre>
time="2020-06-10 16:01:00" level=error msg="could not get block timestamp: could not query block with height 2848026: 429 Too Many Requests {"jsonrpc":"2.0","id":61386,"error":{"code":-32005,"message":"daily request count exceeded, request rate limited","data":{"rate":{"allowed_rps":1,"backoff_seconds":30,"current_rps":1.1},"see":"https://infura.io/dashboard"}}}" prefix=powchain
</pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04
Docker 19.03.8

**What version of Prysm are you running? (Which release)**

alpha.10
gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-1f20cb

**Comment by raphpa** [comment]
Cannot proof it with logs as they do not reach back that far, but I think what happened was:
- infura caused connection errors
- beacon-chain tries to reconnect every second, causing some rate limiting to kick in
- the daily limit got exceeded by the reconnect tries

My conclusion would be:
beacon-chain should backoff when reconnection on connection errors

**Comment by raphpa** [comment]
I have restarted everything and still see around 8000 calls per hour in normal operation. Which seems a little bit excessive to me.

![image](https://user-images.githubusercontent.com/18283997/84415168-a8d2d680-ac12-11ea-8be4-9251458b940f.png)

**Comment by prestonvanloon** [comment]
Thanks for that additional data. I agree that there is definitely something wrong here. 8000 hour is 2.2 requests per second. We should only be making requests every 14 seconds or so to get the latest block information.

**Comment by prestonvanloon** [comment]
It looks like the culprit is BlockTimeByHeight.

https://github.com/prysmaticlabs/prysm/blob/150f8beccd1ffac8731cbc353ccce4f76564dbbf/beacon-chain/powchain/block_reader.go#L62-L70

This method has no caching and apparently is called many times.

**Comment by prestonvanloon** [comment]
This is the frequented code path and it appears to happen several times per second, for the same input data.

```
goroutine 149 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        GOROOT/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        GOROOT/src/runtime/debug/stack.go:16 +0x22
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).BlockTimeByHeight(0xc00062afc0, 0x1c693a0, 0xc005b8fb00, 0xc00770b440, 0x0, 0x0, 0x0)
        beacon-chain/powchain/block_reader.go:75 +0x242
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).followBlockHeight(0xc00062afc0, 0x1c69320, 0xc0000440c8, 0xe23a7b5ea82cc8ce, 0x896c6d5047eaab96, 0xadb632bba572f907)
        beacon-chain/powchain/service.go:321 +0xb8
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).requestBatchedLogs(0xc00062afc0, 0x1c69320, 0xc0000440c8, 0xc00770b420, 0x0)
        beacon-chain/powchain/log_processing.go:359 +0x43
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).handleETH1FollowDistance(0xc00062afc0)
        beacon-chain/powchain/service.go:547 +0x12c
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc00062afc0, 0xc00598a360)
        beacon-chain/powchain/service.go:628 +0x1a6
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1(0xc00062afc0)
        beacon-chain/powchain/service.go:219 +0x50
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
        beacon-chain/powchain/service.go:217 +0x3f
```
