### ISSUE TITLE
Possible disk space exhaustion when finality cannot be reached

### ISSUE THREAD

**Issue by mderka** [prysmaticlabs/prysm#6215]
# Possible Disk Space Exhaustion

### Background

When the chain goes through a long period without reaching finality, it keeps many recent beacon states on disk, possibly leading to space exhaustion.

This issue was discussed with @prestonvanloon on Discord at the Quantstamp channel. 

### Description

When the chain goes through a long period without reaching finality, it keeps many recent beacon states on disk. Beacon states are expensive in size and 100 epochs worth can easily inflate the db to large sizes. This is a potential attack vector where the attacker may be able to stall the chain long enough that Prysm nodes run out of storage. Under normal conditions, Prysm cleans up recent states when finality is reached, keeping only checkpoints around. 

It is unclear how one could purposely execute such an attack without controlling a large portion of the network, but it can be feasible during low participation periods. As the attack would progress and nodes would be unable to operate, the control effect would compound, possibly leading to a (likely temporary) network takeover. 

A mechanism for freeing disk resources when the space is running low should be devised.

**Comment by 0xKiwi** [comment]
Assigned @terencechain for this issue, let me know if there should be a reassignment.

**Comment by terencechain** [comment]
This issue will be mitigated with new state mgmt (default) and even better with new state mgmt revamp @prestonvanloon and I are working on

**Comment by terencechain** [comment]
This is addressed by this: https://github.com/prysmaticlabs/prysm/pull/6488
