### ISSUE TITLE
Beacon stessing cpu before genesis

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6223]
# 🐞 Bug Report

### Description

Beacon chain starts stressing cpu before genesis block is mined. It's resolved after restarting the beacon chain.

### Has this worked before in a previous version?

Can't say, first time I'm monitoring a genesis launch closely.

## 🔬 Minimal Reproduction

Not yet reproducable.

## 🔥 Error

![image](https://user-images.githubusercontent.com/54934211/84495132-f26f0000-acaa-11ea-93c9-a3a8fc0ea4ac.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTC
  </code>
</pre>

<pre>
  <code>
alpha.10 docker
  </code>
</pre>

**Comment by 0xKiwi** [comment]
Hey @stefa2k , sorry its a bit late that we're seeing this, do you by any chance have your beacon node logs at the time of your report?

**Comment by stefa2k** [comment]
No sorry, I wanted to try with altano but I missed the launch :(

**Comment by terencechain** [comment]
There's a few variables that can go into this. Ex: beacon node peering progress

Without further evidence and resolution steps, I'm incline to close this, but will pay close attention next genesis
