### ISSUE TITLE
No p2p connections after discovery

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6224]
# 🐞 Bug Report

### Description

Beacon chain doesn't connect to any peers, it seems stuck after starting discovery.

### Has this worked before in a previous version?

Worked in alpha.9

## 🔬 Minimal Reproduction

Start the beacon chain and wait a bit, look at `p2p_peer_count`

## 🔥 Error

![image](https://user-images.githubusercontent.com/54934211/84495838-2696f080-acac-11ea-9de2-3e83b7de4c54.png)

```
beacon-chain  | time="2020-06-12 10:34:00" level=info msg="Chain started within the last epoch - not syncing" genesisTime=2020-06-14 05:17:24 +0000 UTC prefix=initial-sync
beacon-chain  | time="2020-06-12 10:34:00" level=info msg="Started discovery v5" ENR="enr:-LK4QO5WhORMeM4H80BfDSyRDC-43fmnQiiCjmD0oqGPQ4vCfjiSC52ZxMWEUP3r0e9fkmGIcX5NU4w_YBmyJCOqk88Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCmW0iXAAAAAP__________gmlkgnY0gmlwhKwTAAOJc2VjcDI1NmsxoQLbsm94b4xEM3QXPKU1OqXz-uYvs1-E3hOx5YiPBdo-hoN0Y3CCMsiDdWRwgi7g" prefix=p2p
beacon-chain  | time="2020-06-12 10:34:00" level=info msg="Node started p2p server" multiAddr="/ip4/172.19.0.3/tcp/13000/p2p/16Uiu2HAmADH5JbCy78uR67eppmzwuGBp8Eme5S1TEZ7S77dezi7o" prefix=p2p
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.10
  </code>
</pre>

**Comment by nisdas** [comment]
Resolved by #6226

**Comment by stefa2k** [comment]
Updated to docker images with tag `HEAD-c725a9`, same behaviour.

**Comment by stefa2k** [comment]
Now it connects to peers, but very slowly and low number of peers.
