### ISSUE TITLE
P2P Peer Limits Not Respected

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6229]
# 🐞 Bug Report

### Description

When running Prysm on Alpha.10 with default flags, my beacon node was observing 100+ peers. The default flag is to allow only 30 peers.

https://github.com/prysmaticlabs/prysm/blob/c725a9c8f24e442751848233b825d8cb090a3fde/shared/cmd/flags.go#L121-L126 

### Has this worked before in a previous version?

This worked in Alpha.9 and in Topaz testnet.

## 🔬 Minimal Reproduction

Run a node with default flags.

## 🔥 Error

N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>Linux AMD64</code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>v1.0.0-alpha.10</code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by protolambda** [comment]
Can confirm this bug. I set my p2p-max-peers at 50, but peer count is way over, one peer at 110 even.
