### ISSUE TITLE
Validator resolved 'localhost' to [::1] and could not connect

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6238]
# 💎 Issue

I could not recreate this issue myself, but this was a problem for an user on discord:

beacon-chain is binding to 127.0.0.1:4000 by default now, but validator seems to be connecting to localhost:4000 by default. 
In some cases it might happen that localhost is resolved to the IPv6 local address [::1] and a connection with the default parameters cannot be established, as beacon-chain is only listening on IPv4.

A solution would be to either
- bind beacon-chain to both interfaces or
- have validator/slasher connect to 127.0.0.1 by default

**Comment by prestonvanloon** [comment]
Looks like an issue caused by https://github.com/prysmaticlabs/prysm/pull/6113. @rauljordan can you take a look please?
