### ISSUE TITLE
Validator metric: pubkey returned should be harmonized in every metrics

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6241]
💎 Issue

### Background

I have built a ready to use grafana dashboard for the prysm community, and therefore I need it to be robust. With the Onyx testnet, I just found out that the validator metric `validator_balance` has changed for a shorter pubkey instead of the full one

![image](https://user-images.githubusercontent.com/23481418/84585973-6fb68400-ae15-11ea-97d9-c164713c0dce.png)

Here you can see that the pubkey in `validator_balance` and `validator_statuses` aren't the same anymore, but it was on topaz.

### Description

My issue now, is that I was assuming that those pubkeys returned for all the validator metric are the same. This mean that I can filter on multiple metric on the pubkeys.

For example, the total earning panel include this `count(validator_balance > 16 and validator_statuses == 3)`
There I can make sure that a very recently ACTIVATED (status 3) will be counted for the total earning only when it got his balance, because there is a small delay between the 2 metrics to show up.

Also I tried to change the value of the pubkey in this formula, but it doesn't work, so there is no work around on my end.

### Solution

I don't mind pubkey to be shorter than before, but I would expect at least to get the same pubkey for each metric, so I can apply filters on multiple metrics

**Comment by nisdas** [comment]
@0xKiwi Please look at this, the PR didn't fix it.

**Comment by GuillaumeMiralles** [comment]
Never mind, we found out with @nisdas that the windows binaries for alpha 12 aren't up to date and are built from alpha 11 version. So the issue has been fixed (from linux users feedback)

@prestonvanloon windows binaries alpha 12 need to be  re updated

**Comment by nisdas** [comment]
This is tracked in #6300
