### ISSUE TITLE
Enhance node (list) peers endpoint

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6263]
# 🚀 Feature Request

### Description

Prysm has an api that list peers. The data it provides is however limited (multi-address and direction only ).

The request is to enhance the api and provide more fields from the peer store. Lighthouse has a similar interface that has a richer content.

This allows for better analysis of peers.

The above request was discussed already on discord between @nisdas and @protolambda
![2020-06-15_13-43-31](https://user-images.githubusercontent.com/28559038/84655783-e0db6180-af11-11ea-8b0c-eedc33c18b91.png)

This is how the Lighthouse endpoint looks like:
![2020-06-15_13-45-09](https://user-images.githubusercontent.com/28559038/84655826-f486c800-af11-11ea-999b-6d7765bc0bd6.png)

This is prysm currently (also no option for selecting a single peer):
![2020-06-15_13-49-35](https://user-images.githubusercontent.com/28559038/84655888-108a6980-af12-11ea-9b26-9bb0a9c2213b.png)

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by rauljordan** [comment]
Can we close @nisdas?

**Comment by nisdas** [comment]
Yeap, we can @rauljordan
