### ISSUE TITLE
Beacon chain logs did not start after genesis 

### ISSUE THREAD

**Issue by pjindal** [prysmaticlabs/prysm#6279]
# 🐞 Bug Report

### Description 

 Beacon chain log did not move/update with blocks after genesis event while the validator client did. 

### Has this worked before in a previous version?

 Not sure 

## 🔬 Minimal Reproduction

Running alpha v11 and taking the Windows CMD instructions from here:

https://kb.beaconcha.in/tutorial-eth2-multiclient/prysm-client/windows-prysm/script-beaconnode-and-validator

## 🔥 Error

See image, notice the log times:
 
![5B2844DE-A4C2-454B-B856-20CDFE3FAFC4](https://user-images.githubusercontent.com/26806409/84728340-ffb41500-af5e-11ea-8fed-686c3e841f58.jpeg)

## 🌍  Your Environment

**Operating System:**

Windows 10 Home 
i7 4510 
16gb RAM

**What version of Prysm are you running? (Which release)**

Alpha v11

**Anything else relevant (validator index / public key)?**

N/a

**Comment by rauljordan** [comment]
Hi @pjindal did it work after a while? Was it stuck for a long time? Can you retry restarting your node to see if the issue was fixed?

**Comment by rauljordan** [comment]
Also please try Alpha-12 and clear your chain data with --force-clear-db in the beacon node. We believe this issue might have been resolved in the new release, please keep us posted.
