### ISSUE TITLE
Batch verify fork choice attestation signatures

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6284]
# 🚀 Feature Request

### Description

Fork choice verifies attestations signatures one at time before accounting them as votes. On average, fork choice verifies **20 attestation signatures every 6 seconds**. 
![Screen Shot 2020-06-16 at 3 27 59 PM](https://user-images.githubusercontent.com/21316537/84834327-fb7f0a80-afe5-11ea-9d14-b3bb34fe15a2.png)

With the recent merge of #6277, fork choce could batch verify attestation sigantures via one cgo call. This would require modifications and refactors to the current `process_attestation` path, I'm not entirely convinced that this is worth it since it's not visible on flame graph. With that said, I'm opening this issue to gauge interest and to check if anyone is interested to work on it

**Comment by terencechain** [comment]
Blocked by #6072

**Comment by rauljordan** [comment]
Still relevant @terencechain ?
