### ISSUE TITLE
validator_balance missing on prometheus interface

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6288]
# 🐞 Bug Report

### Description

validator_balance metrics are missing on the prometheus interface.
Might be related to #6257

### Has this worked before in a previous version?

Yes. Stopped working some time in the last 24-48h.

## 🔬 Minimal Reproduction

Run gcr.io/prysmaticlabs/prysm/beacon-chain:latest
Run gcr.io/prysmaticlabs/prysm/validator:latest
curl validator:8081/metrics

## 🔥 Error

No validator_balance in the output.

## 🌍  Your Environment

**Operating System:**

ubuntu 20.04
docker

**What version of Prysm are you running? (Which release)**

gcr.io/prysmaticlabs/prysm/beacon-chain:latest
gcr.io/prysmaticlabs/prysm/validator:latest

**Comment by GuillaumeMiralles** [comment]
Also, while talking with Kudeta on discord which have the same issue, it seems like a lot of others metric are unavailable. Every metric for successful or fail attestations, aggregations and proposals are gone too

**Comment by terencechain** [comment]
This doesn't touch on successful or fail atts, aggs and proposals. If that's gone, then it'd be a different issue to track
