### ISSUE TITLE
flag --unsafe-sync : no peers found

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6290]
# 🐞 Bug Report

### Description
Restarted my beacon to use latest build. Had issues so started again but now with the `--unsafe-sync` flag. With this flag active, my beacon does not find any peers. Without this flag, it finds peers within seconds.
Im also running the `--dev` flag

![2020-06-17_08-36-56](https://user-images.githubusercontent.com/28559038/84863756-c6ba9400-b075-11ea-8a3a-5ec91eeb4ae6.png)
![2020-06-17_08-38-02](https://user-images.githubusercontent.com/28559038/84863861-f8335f80-b075-11ea-8e6b-1a1cef03ea16.png)

Without the flag, it finds peers immediately. But an 'issue'  kicks in which was the reason to try the unsafe flag.
![2020-06-17_08-40-22](https://user-images.githubusercontent.com/28559038/84864085-6841e580-b076-11ea-9be1-181477e740df.png)
![2020-06-17_08-42-30](https://user-images.githubusercontent.com/28559038/84864202-97f0ed80-b076-11ea-8d47-469b212ddece.png)

 

### Has this worked before in a previous version?

I have used the unsafe flag once on the witti branch to mitigate a sync issue, without any problem

## 🔬 Minimal Reproduction
Run latest beacon with `--unsafe-sync` flag and `--dev`.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
version=Prysm/v1.0.0-alpha.11/4740f7ed57490a5a38601a1e66cb8a66f0a6df50. Built at: 2020-06-16 23:29:02+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
I think this flag is broken after new state management was released for Onyx. 

We should remove it after #6325 is resolved.

**Comment by terencechain** [comment]
Blocked by #6325
