### ISSUE TITLE
Re: Validator metric: pubkey returned should be harmonized in every metrics

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6299]
# 🐞 Bug Report

### Background

I suggest you to read this issue first #6241 

It hasn't been fixed, with alpha 12 I still encounter this problem, and total earning panel can't work

### Description

Read #6241 

### Solution

Read #6241

**Comment by nisdas** [comment]
@GuillaumeMiralles Closing this and tracking the issue in #6241 by re-opening it.
