### ISSUE TITLE
Windows Binaries for Alpha.12 Not Updated

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6300]
# 🐞 Bug Report

### Description

The currently tagged windows binaries are actually still alpha.11 instead of alpha.12 .

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

Running the binaries with ```--version``` would show 
```
Prysm/v1.0.0-alpha.11/87ca73d60512ef488fe9551237bc9601c0f34809
```
instead of Alpha.12 as the correct tag.

## 🔥 Error

```
Prysm/v1.0.0-alpha.11/87ca73d60512ef488fe9551237bc9601c0f34809
```

## 🌍  Your Environment

**Operating System:**

Windows

**What version of Prysm are you running? (Which release)**

Alpha.12 

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Wow! Ok I will take a look first thing in the morning

**Comment by prestonvanloon** [comment]
I confirmed the same behavior. Rebuilding these binaries now.

**Comment by prestonvanloon** [comment]
For historical context, here is the mislabeled beacon chain binary.

[beacon-chain-v1.0.0-alpha.12-windows-amd64.zip](https://github.com/prysmaticlabs/prysm/files/4800718/beacon-chain-v1.0.0-alpha.12-windows-amd64.zip)
```
54a40cdddfbeebe631b39975e9dbdb9de406d1c090ac59f0ea9c080bdfee7be4  beacon-chain-v1.0.0-alpha.12-windows-amd64.exe
```

Note: This is not exactly the same binary as alpha.11, but the underlying behavior appears to be the same. 

```
2b57c54adb4944ff56357b74262641c7c3eae5022ed24c9f995dfda62906d2a2  beacon-chain-v1.0.0-alpha.11-windows-amd64.exe
```

**Comment by prestonvanloon** [comment]
Rebuild produced the same result. Trying again with a cherry-pick of 50c4a05

**Comment by prestonvanloon** [comment]
[beacon-chain-v1.0.0-alpha.12-windows-amd64.zip](https://github.com/prysmaticlabs/prysm/files/4802195/beacon-chain-v1.0.0-alpha.12-windows-amd64.zip)

Here is the corrected binary. The release has been updated. 
I will flush the cache and confirm via prysm.bat before closing this issue.

**Comment by prestonvanloon** [comment]
The correct sha is 
```
a014a48894f03e72420cba378710e269fd76a5a22f54b93631a352353d90a0c6  beacon-chain-v1.0.0-alpha.12-windows-amd64.exe
```

I have flushed the cache in cloudflare, but I am not able to fetch the updated version just yet.

**Comment by prestonvanloon** [comment]
OK, I have purged all cache from cloudflare and set "development mode" which has resolved the issue.

If you come across this problem, please clear your `dist` directory located next to your prysm.bat. This will force a re-download of the alpha.12 binary.
