### ISSUE TITLE
FR: Add github's superlinter as github action

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6308]
# 🚀 Feature Request

### Description

We don't have any linting for non-go files such as json, yaml, markdown, and others that are present in this repository.

### Describe the solution you'd like

Add https://github.com/github/super-linter as a github action. 

### Describe alternatives you've considered

None.

**Comment by prestonvanloon** [comment]
Reopened by #6691

**Comment by terencechain** [comment]
Removing good first issue label

**Comment by nisdas** [comment]
Given that this takes 25 minutes to run is it still relevant now ?

**Comment by rauljordan** [comment]
I don't feel good about this. It will be a huge pain to maintain and only add more bloat to our CI when it seems like it doesn't bring as much benefit to us as our current linter.
