### ISSUE TITLE
Failed to retrieve pre state, could not get state summary: unknown state summary

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6315]
# 🐞 Bug Report

### Description

Beacon-chain came up with the following error level message. Operation continued normally after that.

## 🔥 Error

<pre><code>
time="2020-06-19 11:47:13" level=info msg="Synced new block" block=0x168348f4... epoch=1185 finalizedEpoch=1183 finalizedRoot=0x9eed1772... prefix=blockchain slot=37949
time="2020-06-19 11:47:13" level=info msg="Finished applying state transition" attestations=22 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-06-19 11:47:25" level=info msg="Synced new block" block=0x11d4b9f3... epoch=1185 finalizedEpoch=1183 finalizedRoot=0x9eed1772... prefix=blockchain slot=37950
time="2020-06-19 11:47:25" level=info msg="Finished applying state transition" attestations=32 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 37952: could not get state summary: unknown state summary" prefix=sync
time="2020-06-19 11:47:52" level=info msg="Saved full state on epoch boundary" blockRoot=3108d8f25182 prefix=state-gen slot=37952
time="2020-06-19 11:47:52" level=info msg="Deleted state during migration" prefix=state-gen root=9eed1772ec2e slot=37856
time="2020-06-19 11:47:52" level=info msg="Set hot and cold state split point" prefix=state-gen root=bf79f98a1412 slot=37888
time="2020-06-19 11:47:52" level=info msg="Starting next epoch" epoch=1186 finalizedEpoch=1184 justifiedEpoch=1185 prefix=blockchain previousJustifiedEpoch=1184
</code></pre>

## 🌍  Your Environment

Ubuntu 20.04 on ARM64
Docker

**What version of Prysm are you running? (Which release)**

Commit 802bdf5 / Alpha.12 compiled from source

**Comment by farazdagi** [comment]
@terencechain please triage.

**Comment by terencechain** [comment]
This should be resolved in: https://github.com/prysmaticlabs/prysm/pull/6295

Please try latest master or wait until alpha.13
