### ISSUE TITLE
Add a Bootstrap File Flag

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6316]
# 🚀 Feature Request

### Description

Currently the only way to specify multiple bootnodes is using the `bootstrap-node` flag
multiple times or specifying the values comma-separated in a single instance. Both these methods are prone to be specified incorrectly due to how ENRs are encoded.

### Describe the solution you'd like

Instead of manually typing out each bootstrap node we can instead provide the whole list in a file
and simply read the bootstrap nodes from there. That is a much easier and simpler way to manage
multiple bootnodes.

### Describe alternatives you've considered

N.A

**Comment by dv8silencer** [comment]
I'd be happy to try to tackle this.

**Comment by prestonvanloon** [comment]
Can't you do this already by loading config flags from file (https://github.com/prysmaticlabs/prysm/pull/4878)? 

flags.yaml
```yaml
bootstrap-node: enr:-Ku4QMKVC_MowDsmEa20d5uGjrChI0h8_KsKXDmgVQbIbngZV0idV6_RL7fEtZGo-kTNZ5o7_EJI_vCPJ6scrhwX0Z4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQJxCnE6v_x2ekgY_uoE1rtwzvGy40mq9eD66XfHPBWgIIN1ZHCCD6A
```

```
./prysm.sh beacon-chain --config-file=flags.yaml
```

**Comment by dv8silencer** [comment]
I think one reason is to separate configuration files consisting of client-specific flags from a file which would simply be a list of ENR nodes.  A list of nodes in YAML would be more portable [between clients] while a config file would be specific to a client.

**Comment by nisdas** [comment]
While that is possible, it is kind of messy, if you have 10 different bootnodes you would have to clump them all together. And with how unreadable ENRs are it can be difficult to see if you have made any mistake(ex: missed a comma, etc). Also having a separate file just for bootnodes can make it easy to handle it between clients.

**Comment by prestonvanloon** [comment]
Does it not work if you define the flag multiple times?
```
bootstrap-node: enr:-Ku4QMKVC_MowDsmEa20d5uGjrChI0h8_KsKXDmgVQbIbngZV0idV6_RL7fEtZGo-kTNZ5o7_EJI_vCPJ6scrhwX0Z4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQJxCnE6v_x2ekgY_uoE1rtwzvGy40mq9eD66XfHPBWgIIN1ZHCCD6A

bootstrap-node: enr:-Ku4QMKVC_MowDsmEa20d5uGjrChI0h8_KsKXDmgVQbIbngZV0idV6_RL7fEtZGo-kTNZ5o7_EJI_vCPJ6scrhwX0Z4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQJxCnE6v_x2ekgY_uoE1rtwzvGy40mq9eD66XfHPBWgIIN1ZHCCD6A

bootstrap-node: enr:-Ku4QMKVC_MowDsmEa20d5uGjrChI0h8_KsKXDmgVQbIbngZV0idV6_RL7fEtZGo-kTNZ5o7_EJI_vCPJ6scrhwX0Z4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQJxCnE6v_x2ekgY_uoE1rtwzvGy40mq9eD66XfHPBWgIIN1ZHCCD6A
```

**Comment by dv8silencer** [comment]
I wrote another branch using a StringSliceFlag.  It:

- Does not add another flag
- Can accept multiple --bootstrap-node flag/value pairs
- Any one of the values can be a file name ending with .enr  -- If it is, then it will YAML parse it and extract out all the nodes
- Users cannot pass multiple nodes using comma delimiter into one value

[Branch compared to prysm/master](https://github.com/prysmaticlabs/prysm/compare/master...dv8silencer:tempissue6316?expand=1)

Question:  Should I create a new PR and remove the older one?  Should I create another PR alongside it?  Should I try to merge this branch with the one that is already part of a PR?  (the commits are adding up on that one)
