### ISSUE TITLE
Beacon Chain Error - Failed to Revalidate Peer?

### ISSUE THREAD

**Issue by ENashton** [prysmaticlabs/prysm#6321]
![Onyx Error](https://user-images.githubusercontent.com/67170310/85179816-b867a600-b236-11ea-82ec-2505bd67aee2.gif)

About every eight to ten hours, I start receiving these errors on my beacon chain.  Once the "Failed to revalidate peer" error appears,  the "Could not receive attestation in chain service" warnings follow.  These errors and warnings will appeared about every five minutes once they start.  All the while, my three validators  have continued to attest without problem.  Once I restart the beacon chain, the errors and warning disappear.  

Running v1.0.0.0-alpha.12 on Windows 10.

**Comment by nisdas** [comment]
@ENashton Please update your binary , the windows binary uploaded was incorrect. Look at #6300 for details, delete your `/dist` folder and refetch the binary again.

**Comment by ENashton** [comment]
@nisdas Thanks! Refetched the binary and have been running the beacon chain for the last twelve hours without real incident.  On occasion I've received the "Failed to revalidate peer" error.  However it only occurs about once an hour now, and the validators have continued to attest without problem.

**Comment by shayzluf** [comment]
@ENashton closing this issue . please reopen it if it happen again.
Thank you
