### ISSUE TITLE
Logging: p2p fields & content inconsistency

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6328]
# 🐞 Bug Report

### Description

- "Peer Connected" and "Peer disconnected" have different naming for peer count. One is named "active", the other is named "activePeers".
- Difference in field "msg" is also persistent: "Peer **C**onnected" vs. "Peer **d**isconnected"
- "multiAddr" in one, "peer" in the other although it's the same entity referred

### Has this worked before in a previous version?

Reproducable on alpha.11 and alpha.12

## 🔬 Minimal Reproduction

Wait for the beacon node to connect and disconnect some peers, then look at the logs.

## 🔥 Error

```
"@timestamp","host.hostname","container.name",message
"Jun 20, 2020 @ 13:20:35.378","eth2-node-a","beacon-chain","time=""2020-06-20 13:20:35"" level=info msg=""Peer disconnected"" active=33 peer=16Uiu2HAkz4nNskNCipZcfxE9iyd6CiRpRPTYWhAPyJKekzB69sxD prefix=p2p"
"Jun 20, 2020 @ 13:20:35.378","eth2-node-a","beacon-chain","time=""2020-06-20 13:20:35"" level=info msg=""Peer Connected"" activePeers=34 direction=Outbound multiAddr=""/ip4/116.202.193.36/tcp/13000/p2p/16Uiu2HAkz4nNskNCipZcfxE9iyd6CiRpRPTYWhAPyJKekzB69sxD"" peer=16Uiu2HAkz4nNskNCipZcfxE9iyd6CiRpRPTYWhAPyJKekzB69sxD prefix=p2p"
"Jun 20, 2020 @ 13:17:13.236","eth2-node-a","beacon-chain","time=""2020-06-20 13:17:13"" level=info msg=""Peer disconnected"" active=33 peer=16Uiu2HAmRvAS3qnU29V2FUeWquJgnEJ8CRrwRcnpjHPZfsUrNTzR prefix=p2p"
"Jun 20, 2020 @ 13:16:45.926","eth2-node-a","beacon-chain","time=""2020-06-20 13:16:45"" level=info msg=""Peer disconnected"" active=34 peer=16Uiu2HAmVauqo3yKF6kXxD1qaqXg3wD9kdaD12HGRr3MshMpo75J prefix=p2p"
"Jun 20, 2020 @ 13:14:08.824","eth2-node-a","beacon-chain","time=""2020-06-20 13:14:08"" level=info msg=""Peer disconnected"" active=35 peer=16Uiu2HAmETjd9EuPhKVRShJZyEhm5XUyzmiuy8yfAYSeMZoYNCD4 prefix=p2p"
"Jun 20, 2020 @ 13:14:06.334","eth2-node-a","beacon-chain","time=""2020-06-20 13:14:06"" level=info msg=""Peer disconnected"" active=36 peer=16Uiu2HAmJMRj6n2DX8ofHfCFq3eQ2ZoCEu9kePEQMnUM8w4sk11c prefix=p2p"
"Jun 20, 2020 @ 13:14:01.048","eth2-node-a","beacon-chain","time=""2020-06-20 13:14:01"" level=info msg=""Peer Connected"" activePeers=37 direction=Outbound multiAddr=""/ip4/65.102.241.190/tcp/13003/p2p/16Uiu2HAmVauqo3yKF6kXxD1qaqXg3wD9kdaD12HGRr3MshMpo75J"" peer=16Uiu2HAmVauqo3yKF6kXxD1qaqXg3wD9kdaD12HGRr3MshMpo75J prefix=p2p"
"Jun 20, 2020 @ 13:14:00.406","eth2-node-a","beacon-chain","time=""2020-06-20 13:14:00"" level=info msg=""Peer Connected"" activePeers=36 direction=Outbound multiAddr=""/ip4/62.68.164.20/tcp/13000/p2p/16Uiu2HAmTHd3zaMkLn4Lwiw3i56a49WwBtkrqfiauz7EMZqb2XbQ"" peer=16Uiu2HAmTHd3zaMkLn4Lwiw3i56a49WwBtkrqfiauz7EMZqb2XbQ prefix=p2p"
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.11
alpha.12
  </code>
</pre>

**Comment by dv8silencer** [comment]
I'll try to tackle this.

**Comment by dv8silencer** [comment]
Is it meaningful to have direction= for the peer disconnection log?
Should it be active or activePeers?
Should disconnected/connected be capitalized or not?

**Comment by stefa2k** [comment]
> Is it meaningful to have direction= for the peer disconnection log?

Yes, I think so

> Should it be active or activePeers?

`activePeers` is a more deterministic term

> Should disconnected/connected be capitalized or not?

Most of the other logs dont capitalize after the first word. I'd suggest don't capitalize `connected` or `disconnected`
