### ISSUE TITLE
Validator metric: add the quantity of ETH deposited

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6329]
# 🚀 Feature Request

### Description

For the dashboard, it would be very interesting to get the amount of deposited ETH on each validator. For most of people it is 32, but some are depositing more than that

### Describe the solution you'd like

Each time a validator is receiving a deposit, then the node would send the new data to the validator. Then this data would be also retrieved on validator client restart

### Context

There are many people that told me about this. I did explain how to fix this manually by substracting the extra amount deposited, but this require the user to modify the dashboard, which is not very easy for everybody, and they need to be aware of it (some just delete the README panel of the dashboard without to read)

![image](https://user-images.githubusercontent.com/23481418/85223929-e5e35980-b3c6-11ea-89dd-b4ecae7f785e.png)

**Comment by rauljordan** [comment]
@GuillaumeMiralles could you share more details about the metrics you are currently using? Wouldn't validator_balance be enough for your purposes?

**Comment by GuillaumeMiralles** [comment]
No this metric wouldn't be enough. I cannot know how much ETH the user deposited on his validator, since he could do multiple deposits at different time. So in order to calculate perfectly the total earning, I require this data.
What it is done right now is that it guess that the validator got 32 ETH deposited, no more no less. So if the user wants to have the real total earning, he needs to substract the excess.
For example, the user deposited twice 32 ETH, the validator have received 64 ETH then. The user will then need to add `-32` at the end of the query, which is not user friendly at all

**Comment by potuz** [comment]
Do we really want this? the only way to effectively track this would be with a gauge for a timeseries since the deposits can happen at any time during the lifetime of the validator. This will be a series by pubkey.  I feel like this will increase the cardinality of the dbase mostly unnecessarily. The vast majority of users will not need this feature. Or can just simply change their dashboard accordingly when they deposit. Instead of relying on the node to tell them when they deposited.

**Comment by rauljordan** [comment]
Agreed this will be a very high cardinality database for folks with a lot of validators. We should mostly point users to block explorers if they desire this information
