### ISSUE TITLE
Display an error/warning message if a deposit is invalid

### ISSUE THREAD

**Issue by fabdarice** [prysmaticlabs/prysm#6334]
# 💎 Issue
My deposit of 32 gETH is invalid (likely because I did the deposit with an older version the validator client) as shown in the link here: https://beaconcha.in/validator/a308dc8b2571ac658488f41bb0cf9fa6811e2a23c36ffbc6a6fb478b1104db61ff2b795c0b35f9c5f69191f3b8c8e2bd#deposits

The validator client is however displaying this message:
`INFO validator: Deposit processed, entering activation queue after finalization positionInActivationQueue=0 pubKey=0xa308dc8b2571 status=DEPOSITED`

It would be preferable to display an error or warning message to the user that his deposit has failed.

### Background
Discussed with @nisdas : https://discordapp.com/channels/476244492043812875/476588476393848832/724477548414894080

**Comment by handelaar2** [comment]
also see #6036

**Comment by fabdarice** [comment]
@shayzluf @0xKiwi I'm actually already tackling this ticket, at the same time as #6036.

Should be pretty close

**Comment by fabdarice** [comment]
Would love your input on this: https://github.com/prysmaticlabs/prysm/issues/6036#issuecomment-651604627
