### ISSUE TITLE
Add Easy --onyx --witti --altona Flags for Switching Testnets

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6342]
# 🚀 Feature Request

### Description

Other clients typically have an easy way to specify what testnet to connect to by default via an easy flag that requires no configuration changes. For example, connecting to Witti would be:
```
./prysm.sh beacon-chain --witti
```
and similar for --onyx and --altona. A PR for this would hardcode the required parameters for those testnet versions and make it easy to launch a node this way.

**Comment by prestonvanloon** [comment]
I'll work on this today

**Comment by rauljordan** [comment]
Done by #6380

**Comment by prestonvanloon** [comment]
This FR asks for `--onyx` as well, but was not implemented by #6380. We will need this at some point, especially if new configuration changes merge in eth2-specs (i.e. https://github.com/ethereum/eth2.0-specs/issues/1894).

I'll reopen this and send a PR for resolution.

**Comment by prestonvanloon** [comment]
Actually, we can wait until we decide that Onyx is no longer the default to add `--onyx`. This would be either a mainnet release (v1.0.0) or Onyx deprecation. 

No need to keep this issue open until then.
