### ISSUE TITLE
Set up a validator node with Avado i3, was activated 2 days ago but does not seem to be online

### ISSUE THREAD

**Issue by teslabitcoin** [prysmaticlabs/prysm#6364]
is there a wait period after you are activated or am i missing something? any help is appreciated

**Comment by prestonvanloon** [comment]
@teslabitcoin yes, there is an activation queue. At the current scale, the onyx testnet can only activate 900 validators per day. 

You should be receiving estimated activation logs in your validator client. You can also find your validator on an eth2 block explorer and see the estimated activation epoch. 

![Untitled drawing](https://user-images.githubusercontent.com/7246818/85444392-22d65a00-b547-11ea-90ce-2f6a18b75f24.jpg)

Does this answer your question?

**Comment by teslabitcoin** [comment]
i have been activated 2 days ago but I do appear online. Is there anything i need to do after i am activated?

**Comment by prestonvanloon** [comment]
Can you tell me your public key or validator index?
Are there any interesting logs?
Which version of Prysm are you using?

**Comment by teslabitcoin** [comment]
https://beaconcha.in/validator/8d00558fdb3c2e30e170ded118583472bb80b84d614736485907887f0fa20fc27658f7299aecb26e56e429f7980aaa63#overview

0.2.3 thru avado, I just restarted the node and synching now but earlier when it was synched, still not active

**Comment by prestonvanloon** [comment]
OK that makes sense. 0.2.3 is very old and not compatible with Onyx. 

Please download the latest release for Prysm, we are currently on v1.0.0-alpha.12.

https://github.com/prysmaticlabs/prysm/releases/latest

**Comment by teslabitcoin** [comment]
hmm does not seem to be on avado's dapstore yet

**Comment by teslabitcoin** [comment]
thanks

**Comment by prestonvanloon** [comment]
Thanks for that info. I am not sure how to update Avado's DAppstore. 

@sponnet do you know how we can update DAppstore for Avado?
