### ISSUE TITLE
Node metric: total_voted_target_balance drops to 0 once in a while

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prysmaticlabs/prysm#6377]
# 💎 Issue

### Background

On the dashboard, we can follow the participation rate to have a quick idea of the network health. This info is very important in order to understand some of the penalties that could be encountered by the staker (participation rate < 66%)

### Description

Since a while now (at least since Topaz testnet) the participation rate suddenly drops to 0, and this is still on going on Onyx. 
I know that this is local on each node, could happen to any node but randomly, and if it happens to one it doesn't mean it will happen to the other nodes at the same time.

For the participation rate to drop to 0, it means that the metric `total_voted_target_balance` drops to 0, so at some point, this value isn't correctly fetched by the node, and set it to 0.

You can see here the `total_voted_target_balance` dropping to 0, then participation rate is dropping to 0 as well
![image](https://user-images.githubusercontent.com/23481418/85520821-b705f700-b603-11ea-9ce1-46e0ce6a39eb.png)

It would be good to fix this issue, it is really not a big deal so far, but still annoying (wrong chart + alerts for nothing)

**Comment by terencechain** [comment]
Here's the `total_voted_target_balance` chart in Prometheus for 10 days. There's no dropping to 0. This is mostly likely a Grafana set up or run time related issue than an Prysm bug

![Screen Shot 2020-06-24 at 9 18 11 AM](https://user-images.githubusercontent.com/21316537/85593322-c84b0580-b5fb-11ea-88c6-909fa718ea61.png)

**Comment by GuillaumeMiralles** [comment]
Unfortunately it is not

Here is the chart shown in prometheus on a large scale (2 weeks)
![image](https://user-images.githubusercontent.com/23481418/85595187-e723b900-b648-11ea-9181-1a38569aa737.png)

We don't see any drop to 0, but then take a look when you zoom in a bit
![image](https://user-images.githubusercontent.com/23481418/85595363-0e7a8600-b649-11ea-8ced-68e36c4fde25.png)

Every points are not shown, but still, the point to 0 exist

**Comment by terencechain** [comment]
I have something similar, but it looks the prometheus briefly lost connection and came back up shortly after
![Screen Shot 2020-06-24 at 10 21 52 AM](https://user-images.githubusercontent.com/21316537/85602924-b4f06800-b604-11ea-9bf8-574a5752a5ed.png)

**Comment by GuillaumeMiralles** [comment]
Yes on your graph it's not so clear because it seems this way, but on every other chart you have seen on discord, there was no gap at all when this happened.
Also, prometheus will keep the last value for the metric he got until this change, so this mean that the node send to prometheus the value of 0 at some point.

I don't see any other explanation

**Comment by terencechain** [comment]
Ok let's keep this open for tracking for purpose

**Comment by prestonvanloon** [comment]
@terencechain what's the plan for this issue? Are we monitoring it or can it be closed?

I removed help wanted because it isn't clear what is required here.

**Comment by terencechain** [comment]
We are monitoring this metric, but the value of this metric `total_voted_target_balance` very rarely drops to 0. Such event is very hard to reproduce and I haven't had the time to debug the why and the how

**Comment by GuillaumeMiralles** [comment]
That is very hard to reproduce indeed, I had another crash to 0 recently but it was mixed up with bunch of errors on the beginning of alpha 14, I was not available to give any informations unfortunately. Here we can see it's not just a flash crash, but it has stayed a bit long set to 0, so I assume it was different as usual

![image](https://user-images.githubusercontent.com/23481418/87397958-791e4200-c5b5-11ea-9528-157fe827dc51.png)

**Comment by GuillaumeMiralles** [comment]
I haven't seen this happening in a while + nobody talked about it in discord either, I close it. I'll reopen it if I see this behavior happening again.
