### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by MysticRyuujin** [prysmaticlabs/prysm#6382]
# 🚀 Feature Request

### Description

 I would like to see Log File Rotation, I was asked to go grab the logs from one of my nodes, only to realize that my log file is 11GB...

### Describe the solution you'd like

 I would like to see log file rotation

### Describe alternatives you've considered

 None?

**Comment by prestonvanloon** [comment]
> Log rotation is not provided with Logrus. Log rotation should be done by an external program (like `logrotate(8)`) that can compress and delete old log entries. It should not be a feature of the application-level logger.

https://github.com/sirupsen/logrus#rotation
https://linux.die.net/man/8/logrotate

Perhaps the action item here is to add documentation about how to use logrotate with Prysm, otherwise I think this feature request is a no-go for an application level implementation. While this may not be what you were looking for with this feature request, do you find that to be a reasonable resolution?

With regards to 11gb log file, did you have debug logging on? 
It seems hard to imagine 11gb of logs without debug logging enabled. If this was at the info level or higher, then we really need to think about turning down the verbosity at info level.

**Comment by raphpa** [comment]
Using logrotate would require prysm to reopen the logfile on a signal, else it will just keep writing to the moved logfile, ideally without restarting the processes. Using `copytruncate` with logrotate always comes with the risk of losing log messages.

Trying with HUP, it just exits prysm. Maybe you could add listening to a signal to prysm (USR1?) which makes it reopen the logfile.

**Comment by MysticRyuujin** [comment]
The 11GB was due to an issue parsing the ETH1 node JSON RPC response. Prysm flooded the log file with errors.

Can't you guys just rotate the log file on startup? That seems like a happy middle ground. If log file already exists, move it, start new log file.

**Comment by prestonvanloon** [comment]
@raphpa You could use `copytruncate` which would truncate the current file before copying.

> copytruncate
> 
> Truncate the original log file in place after creating a copy, instead of moving the old log file and optionally creating a new one. It can be used when some program cannot be told to close its logfile and thus might continue writing (appending) to the previous log file forever. Note that there is a very small time slice between copying the file and truncating it, so some logging data might be lost. When this option is used, the create option will have no effect, as the old log file stays in place.

I must admit, I have not tried using logrotate in practice. 
At Prylabs, we use a fluentd daemon to stream logs to elasticsearch and write logs to tmpfs.

**Comment by prestonvanloon** [comment]
@MysticRyuujin Is this https://github.com/prysmaticlabs/prysm/issues/6204 the Nethermind RPC issue?

**Comment by MysticRyuujin** [comment]
Sorry for the delay, yeah that's the issue

**Comment by prestonvanloon** [comment]
Closing this old post. Log rotation seems more of an operator preference than an application feature.

However, if there is still demand for documentation and examples of using logrotate, then please file a request at https://github.com/prysmaticlabs/documentation
