### ISSUE TITLE
Creating And Submitting Attestation Fails Occasionally

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6399]
# 🐞 Bug Report

### Description

Attestation requests fail occasionally with the error, which can lead to a drop in the validator's participation.

### Has this worked before in a previous version?

Yes it has.

## 🔬 Minimal Reproduction

Run a validator and beacon node

## 🔥 Error

```
{"error":"rpc error: code = InvalidArgument desc = Attestation request must be within current or previous epoch","message":"Could not request attestation to sign at slot","prefix":"validator","pubKey":"0x803f3275b3d0","severity":"ERROR","slot":80024}
```

## 🌍  Your Environment

**Operating System:**

**What version of Prysm are you running? (Which release)**

26e27bf0527798fbfedbc2f406d8b967cc7a54c9

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
Assigning to on call to look for cluster
