### ISSUE TITLE
node wil not connect to beaconchain. any thought?

### ISSUE THREAD

**Issue by teslabitcoin** [prysmaticlabs/prysm#6407]
<img width="1124" alt="Screen Shot 2020-06-25 at 1 38 33 PM" src="https://user-images.githubusercontent.com/67337164/85779652-71235e80-b6e9-11ea-9480-0a2a9e6d7def.png">

still trying to connect my node, could it be something with my router settings?

**Comment by teslabitcoin** [comment]
<img width="1124" alt="Screen Shot 2020-06-25 at 1 38 33 PM" src="https://user-images.githubusercontent.com/67337164/85788677-f5c6aa80-b6f2-11ea-870d-01bd65e10e03.png">

**Comment by teslabitcoin** [comment]
<img width="1079" alt="Screen Shot 2020-06-25 at 2 48 32 PM" src="https://user-images.githubusercontent.com/67337164/85788725-06772080-b6f3-11ea-93f0-7e6f1c899a97.png">

**Comment by shayzluf** [comment]
Hey @teslabitcoin ,
thanks for submitting an issue but it seems like a dappnode issue. closing it for now. Please reopen and add more details if you think this is a prysm issue
