### ISSUE TITLE
Remove Deprecated Blocks By Roots Request

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6408]
# 💎 Issue

### Background

Currently we have invalid ssz serialization/deserialization for our blocks by roots request. In order to not break backward
compatibility with onyx nodes, we support both the correct/incorrect formats. This issue is to track the eventual removal 
of the outdated request methods and its types and solely use the correct one.

**Comment by prestonvanloon** [comment]
What is invalid about it?

**Comment by nisdas** [comment]
We marshalled the blocks by roots request as a struct rather than a variable length array, so  the ssz representation of it was wrong before. In order to not break Onyx and still be compatible with other clients in Altona, we support both formats for now.

**Comment by rauljordan** [comment]
This is no longer relevant
