### ISSUE TITLE
Slasher health check via rpc

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6433]
# 🚀 Feature Request

### Description

To monitor the services the `beacon-chain` already supplies a number of json-rpc but `slasher` doesn't have any kind of health check endpoints yet.

### Describe the solution you'd like

Similar to `beacon-chain` implementing a simple json-rpc should do the trick, stating the slasher's connectivity to a beacon chain and availability for validators' submits. This can be as simple as https://api.prylabs.net/#/Node/GetSyncStatus

### Describe alternatives you've considered

The working alternative right now is to just check if the service ports of `slasher` are open for requests. But this has some obvious downsides:
- another service could listen to this port
- no information on service's status

**Comment by prestonvanloon** [comment]
All binaries support a `/healthz` endpoint served on the monitoring port. The "healthz" endpoint returns a 200 when the node is healthy and a 500 when not healthy. It also prints out the statuses of current services. If this endpoint returns 200, then it is OK to serve requests.

- Beacon-chain http://localhost:8080/healthz
- Validator http://localhost:8081/healthz
- Slasher http://localhost:8082/healthz

**Comment by shayzluf** [comment]
Closing this issue. Please reopen if you think this issue have to be addressed further

**Comment by nisdas** [comment]
I think what @stefa2k is getting at is that currently the health check in the slasher doesn't tell us when its ready to serve data to external clients. I had a look at all the `Status` methods and they weren't checking for when the slasher is ready, just basic grpc errors. Reopening this until that is addressed.

**Comment by prestonvanloon** [comment]
@shayzluf Any update on this issue

**Comment by shayzluf** [comment]
Will add those capabilities to healthz endpoint tomorrow
