### ISSUE TITLE
beacon-chain/rpc/service.logNewClientConnection has unsafe map access

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6434]
User reported concurrent map access panic and their logs point to these lines of code.

https://github.com/prysmaticlabs/prysm/blob/78465e25492795121855e758ee420e6334f22c22/beacon-chain/rpc/service.go#L403-L408

See comments here: https://github.com/prysmaticlabs/prysm/issues/5576#issuecomment-650606885

Assigning to @rauljordan as the original author of this log in #6233. 

cc: @stefa2k

**Comment by stefa2k** [comment]
looking good, service has been stable for 16h now without this errors
