### ISSUE TITLE
Inconsistent Genesis Time but accurate validator count

### ISSUE THREAD

**Issue by alibyte** [prysmaticlabs/prysm#6435]
# 🐞 Bug Report

### Description

Inconsistent genesis time but accurate validator count

n/a

## 🔬 Minimal Reproduction

Use the db file on here: http://www.filedropper.com/beaconchain

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian Server
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
current
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

Due to inconsistent genesis time, every epoch counts as missed, causing ETH to be deducted. Thank god it's not real ETH :)

**Comment by shayzluf** [comment]
Hey @alibyte 
thanks for filing this issue

can you please add more details about the way you run this instance:
- version tag...
did you clear your db? 
did you use any flag ?

**Comment by prestonvanloon** [comment]
Please add the specific version / commit you were running at the time to reproduce this. 

What do you mean inconsistent genesis time? You were getting a different genesis time without changing any parameters?
What is your eth1 node setup like? Are you running your own eth1 node or using Prylabs' nodes?

**Comment by alibyte** [comment]
Figured out the issue! Happens if your disk space fills up while syncing the beacon chain. there is no error or anything (at least I didn't get one) and the validator is running "behind" so to speak

**Comment by prestonvanloon** [comment]
Thanks @alibyte. I'll close for now. Please reopen or comment here if there is an action we can take to resolve the issue.
