### ISSUE TITLE
Can't find peers on altona via binarys

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6444]
# 🐞 Bug Report

### Description

`prysm.bat beacon-chain --altona --datadir=C:\prysm --verbosity=debug` 

**Cannot find peers via binary files on windows10 & macos**

![image](https://user-images.githubusercontent.com/26490734/86012312-19a12d80-ba1e-11ea-97a6-4a5386c2c17f.png)

![image](https://user-images.githubusercontent.com/26490734/86012283-1017c580-ba1e-11ea-8eb7-d39ed7de519f.png)

solved issue by adding `--bootstrap-node=enr:-Ku4QMqmWPFkgM58F16wxB50cqWDaWaIsyANHL8wUNSB4Cy1TP9__uJQNRODvx_dvO6rY-BT3psrYTMAaxnMGXb6DuoBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g`

**Found peers on docker without the bootstrap node.**

`docker run -it -v c:/prysm/:/data -p 4000:4000 -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data --altona`

**Comment by prestonvanloon** [comment]
This is fixed in #6441, but that PR did not make it into the alpha.13 release. 

I'll close this for now since there is no further action to take. 
The fix will land in the next weekly Prysm release and we have a work around to add bootstrap nodes via flag as you have done.
