### ISSUE TITLE
API Request: Show pending validators pre genesis 

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6445]
# 🚀 Feature Request

### Description

Since the validator queue is already known pre genesis, it would be great to return `pending validators` during this period via `/eth/v1alpha1/validators/queue`

**Comment by rauljordan** [comment]
@Buttaa we might not get to this given other priorities, but I've been reading the code and shouldn't it behave this way already? Once we have a genesis state, the /validators/queue endpoint should work ok. What results did you get earlier?

**Comment by Buttaa** [comment]
@rauljordan 
`/eth/v1alpha1/validators/queue` only returns the validators which have been recognized by beaconchain (8 hours), however the queue is already known once the deposit transaction reaches the deposit contract

**Comment by fabdarice** [comment]
If needed, I'll be happy to tackle this one.

**Comment by rauljordan** [comment]
Thanks @fabdarice, do you think we can get this wrapped up within a week? We should discuss the approach to this issue. One way we could do it is:
- Inside of the keymanageropts.json file within a wallet, we can store a "disabled_validators": [pubkey] entry and exclude those validators when initializing the keymanager (both imported and derived)
- Define `enable` and `disable` commands under prysm.sh validator accounts, which will allow a user to perform selection similar to accounts backup and delete. These commands will essentially write to the keymanageropts.json file as needed

**Comment by fabdarice** [comment]
Hey @rauljordan , Terence assigned me to https://github.com/prysmaticlabs/prysm/issues/7485
I'm currently getting myself familiar with the account/wallet codebase.

If #6445 is more urgent, I'm happy to switch gear, let me know. I'm planning on helping out during my spare-time.

Also, are you commenting on the right issues here?

**Comment by rauljordan** [comment]
oh shoot, sorry about that! For some reason thought this was #7485. This one is more important as genesis of the beacon chain is near

**Comment by prestonvanloon** [comment]
Removing from mainnet milestone. Sorry, this didn't get implemented in time.

**Comment by rauljordan** [comment]
We did not get to this feature :(
