### ISSUE TITLE
Panic with flag --disable-dynamic-committee-subnets (altona)

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#6447]
# 🐞 Bug Report

### Description

As soon as I add flag  `--disable-dynamic-committee-subnets` to my altona beacon, I get a panic message directly after startup and my beacon stops:
![2020-06-29_18-36-44](https://user-images.githubusercontent.com/28559038/86032717-12871900-ba38-11ea-9270-6792ebcb2c01.png)

### Has this worked before in a previous version?

Have run this flag with the witti test-net without any issue

## 🔬 Minimal Reproduction

Run a beacon node on altona with the following parameters:
`/home/ubuntu/prysm/bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain \`
`--datadir="/home/ubuntu/.eth2/altona" \`
`--enable-debug-rpc-endpoints \`
`--verbosity=info \`
`--disable-dynamic-committee-subnets \`
`--altona \`
`--dev \`
`--slots-per-archive-point=32 \`
`--grpc-gateway-port=4001 \`
`--p2p-host-ip=$IP \`
`--min-sync-peers=1 \`
`--p2p-max-peers=50 \`
`--bootstrap-node=enr:-KG4QLkU_qJgdh-DhT5HtONGvuqwbbW99piCe27Bpk8oO_hvC0qEYgOSpmVfZ-8iJgW71HO23ajEFCNOCvEaqpcIXiUDhGV0aDKQ_co5sAAAASH__________4JpZIJ2NIJpcIQDE_KiiXNlY3AyNTZrMaEDbBoq33b6SAUh96EJZWNYOqYwjm78pVviDreLfK-aeUKDdGNwgiMog3VkcIIjKA`

## 🔥 Error
panic: /eth2/%x/beacon_attestations_0 is not mapped to any message in GossipTopicMappings

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.13/2bce9c884abca8754ed35a07bcd6bc631fcd370d. Built at: 2020-06-29 05:54:08+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by 0xKiwi** [comment]
Hey @nisdas @rauljordan whats the status of this flag? Should it still be used?

**Comment by prestonvanloon** [comment]
@rauljordan it looks like topics are not properly registered with `--disable-dynamic-committee-subnets`.

Can you please take a look?

**Comment by nisdas** [comment]
Resolved by #6533 .
