### ISSUE TITLE
Warning message that should have been at debug level

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#6449]
# 🐞 Bug Report

### Warning message that should have been at debug level

Please move this to a debug level instead. This has triggered Grafana alerts every hours. It occurs for more that 50 times (for 30 validators)

### Has this worked before in a previous version?

No, it was happening on alpha.12

## 🔥 Error

<pre><code>
time="2020-06-29 18:34:24" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/a65b4897/beacon_attestation_54/ssz_snappy"
</code></pre>

## 🌍  Your Environment

**Operating System:**

Pi 4 8GB Ubuntu

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
alpha.13
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by 0xKiwi** [comment]
Hey @xuyenvuong , thanks for making this issue! @nisdas , should this log be moved to debug?

**Comment by prestonvanloon** [comment]
I think we should ignore this specific error entirely. I've filed libp2p/go-libp2p-pubsub#356 which exposes the error itself so we can properly ignore it. 

I'll start with a PR that hard codes this constant in Prysm such that we properly ignore the error, then I will add a TODO referencing this issue to remove the hard coded constant in Prysm in favor of `pubsub.ErrSubscriptionCancelled`.

**Comment by prestonvanloon** [comment]
Please do not close this issue without resolving the TODO created in commit dd4757d. 

Blocked by libp2p/go-libp2p-pubsub#356

**Comment by xuyenvuong** [comment]
Thank you @prestonvanloon - I'll will test it out.
