### ISSUE TITLE
Local ENRs created with wrong fork digest, cannot find peers

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6452]
# 🐞 Bug Report 

### Description

Sometimes, the Prysm node will never find peers. Upon looking at trace level logs, we see messages like this

```
 Fork ENR mismatches between peer and local node error=fork digest of peer with ENR -LK4QFJW-a3QirWz6yDyfCOmG0i2ALXpxipuuwSpMRfXmcphfSJCzm9p1PQen-PQjJ5PuH7vbrLXEln15lsux2-eubsbh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCmW0iXAAAAAP__________gmlkgnY0gmlwhLhL1hKJc2VjcDI1NmsxoQJVvylg8Cehv7aGnkFsagUfyJ76pypmCM2twC-Y7L_35oN0Y3CCMsiDdWRwgi7g: [166 91 72 151], does not match local value: [105 211 140 90]
```

I confirmed with @terencechain that the fork digest is `a65b4897` aka  `[166 91 72 151]`, but my node is reporting `69d38c5a` aka `[105 211 140 90]` in this log statement.

### Has this worked before in a previous version?

Hard to tell, this issue is flaky so it may have been present in older versions as well but it certainly seems more prevalent in alpha.13 and master at 6c7131cb544413e1ca73aeb18e6ff5b9acc813b7.

## 🔬 Minimal Reproduction

Restart beacon node with a new database / datadir. 

No flags added `bazel run //beacon-chain`

## 🔥 Error

Not really an error, but these logs are the symptom that something isn't right...

<pre><code>
[2020-06-29 14:04:31]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2020-06-29 14:04:36]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2020-06-29 14:04:41]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>linux-amd64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
6c7131cb544413e1ca73aeb18e6ff5b9acc813b7
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
My genesis validator root (when I can't find any peers) is `d92e3100ed9d2386d6e10ffd85712c89e864cf78bd6b1cc3164e8b487228b471`. 

@terencechain confirmed their (correct) genesis validator root is `4f9c5c3c1f498f2012167d7d3a2b2e94596bc9c0149d092c80dd0ff6803c4f5d`.

**Comment by prestonvanloon** [comment]
I got another validator root `894c7b313ca64c5c3c0271eedeb010dd7aed438eedd66435b77a0bc84615b11d` by restarting the beacon node

**Comment by prestonvanloon** [comment]
[bad_genesis_state.zip](https://github.com/prysmaticlabs/prysm/files/4848213/bad_genesis_state.zip)

This genesis state has `0xd92e3100ed9d2386d6e10ffd85712c89e864cf78bd6b1cc3164e8b487228b471` for the genesis validator root.

**Comment by terencechain** [comment]
[beacon_state_0.ssz.zip](https://github.com/prysmaticlabs/prysm/files/4848236/beacon_state_0.ssz.zip)

Here's my genesis state that is capable to peer with others

**Comment by prestonvanloon** [comment]
[states.diff.txt](https://github.com/prysmaticlabs/prysm/files/4848261/states.diff.txt)

A/from = good state 
B/to = bad state

**Comment by prestonvanloon** [comment]
The diff that stands out the most is a different eth1 block hash.

```
BeaconState objects A and B are different:
modified bytes: .Eth1Data.BlockHash
from = 8cfa23fb2d72f9f1773476158a30eea3e473595285593695ee4230987beac1ae
  to = 62a4849606edb96e71c46e12501819707141fa3d5ee5b9bf3418c462db381bd8
```

**Comment by prestonvanloon** [comment]
False alarm, I had unstaged changes around deposit verification that was allowing invalid deposits to be considered valid. Therefore the genesis state was created earlier than expected with different balances. 

If you are having issues finding peers, this is likely not the root cause of your problem. Thanks @terencechain for helping with investigation.
