### ISSUE TITLE
Beacon-chain not able to resume syncing after network connection was down

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6459]
# 🐞 Bug Report

### Description

After an outage of the internet connection for a couple of hours beacon-chain is not able to sync up with the chain again. Initial-sync always starts at block 117537, syncs up to block 117983 and starts over at 117537 again.

The log does not reach back far enough to the point the internet connection was available again. There was no new docker container started, so the process has not crashed in between.

A restart fixed this issue and beacon-chain was able to sync up to the chain head.

### Has this worked before in a previous version?

Not tried

## 🔬 Minimal Reproduction

Not tried to reproduce

## 🔥 Error

<pre><code>
time="2020-06-30 16:45:43" level=info msg="Processing block 0x6954467b... 117981/118641 - estimated time remaining 1m29s" blocksPerSecond=7.3 peers=29 prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Processing block 0x61347955... 117983/118641 - estimated time remaining 1m28s" blocksPerSecond=7.4 peers=29 prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Processing block 0x98b2b875... 117537/118641 - estimated time remaining 2m28s" blocksPerSecond=7.5 peers=29 prefix=initial-sync
time="2020-06-30 16:45:46" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:46" level=info msg="Processing block 0x8f7a09b5... 117538/118641 - estimated time remaining 2m55s" blocksPerSecond=6.3 peers=29 prefix=initial-sync
</code></pre>

Starting at block 117537 over and over again.

For all the available log see:
[onyx.log](https://github.com/prysmaticlabs/prysm/files/4853379/onyx.log)

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04 on arm64
Docker

**What version of Prysm are you running? (Which release)**

Commit 2bce9c8 compiled on arm64
Running in Docker

**Comment by prestonvanloon** [comment]
I've seen this as well when a peer would not give the requested set of blocks. A potential resolution here is to improve our peer scoring in initial sync. 

@farazdagi can you help?

**Comment by farazdagi** [comment]
Yep, working on this (we had a discussion about it with Nishant today, I will provide both simple heuristics based on peer's performance and look into full-fledged peer scoring).

**Comment by prestonvanloon** [comment]
ok great thanks!
