### ISSUE TITLE
Implement a Common Hash Function

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#646]
there are a few occurrences where we blake2b the input bytes then take the output bytes and truncate them into 32 length. Example:
```
	var hash [32]byte
	h := blake2b.Sum512(data)
	copy(hash[:], h[:32])
	return hash, nil
```
Instead of doing that in multiple places, Let's define a standard hash function call `Hash`, put it in `shared` and use it across pryzm.

**Comment by rauljordan** [comment]
Closed by #649

**Comment by rauljordan** [comment]
@IvanTheGreatDev btw if you add "resolves #[ISSUE_NUM_HERE]" to any PR, it'll automatically close the issue being referenced

**Comment by IvanTheGreatDev** [comment]
Ooooooo TIL
Thanks!
