### ISSUE TITLE
Incorrect log level for "double proposal"

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6472]
# 🐞 Bug Report

### Description

Log level incorrect of `Tried to sign a double proposal, rejected by external slasher`

### Has this worked before in a previous version?

-

## 🔬 Minimal Reproduction

Run 2 validators with the same set of accounts.

## 🔥 Error

```
time="2020-07-02 14:56:27" level=fatal msg="Tried to sign a double proposal, rejected by external slasher" epoch=4140 prefix=validator pubKey=0x841c0883c941
```

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
docker tag `:HEAD-6c7131`
  </code>
</pre>

**Comment by 0xKiwi** [comment]
This is fixed as part of #6406
