### ISSUE TITLE
monitoring-port for beacon-chain Is Ignored When Defined by YAML

### ISSUE THREAD

**Issue by SeaMonkey82** [prysmaticlabs/prysm#6478]
# 🐞 Bug Report

### Description

When prysm.sh is launched with the `--config-file` flag, the monitoring port defined in the YAML config is ignored and the default 8080 is used instead.

### Has this worked before in a previous version?

Don't know.  This is my first time using `--config-file`.

## 🔬 Minimal Reproduction

`./prysm.sh beacon-chain --config-file=$HOME/prysm/onyxbeacon.yaml`

YAML:
`monitoring-port: 8082`

## 🌍  Your Environment

Linux Mint 19.3

**What version of Prysm are you running? (Which release)**

1.0.0.alpha.13

**Anything else relevant?**

Could this have anything to do with the fact that MonitoringPortFlag is the only integer flag defined with type Int64Flag instead of IntFlag?  I'm no programmer...
https://github.com/prysmaticlabs/prysm/blob/aa52e693ce0a6307bbb68af66b60cc9519810992/beacon-chain/flags/base.go#L35

**Comment by mibsta** [comment]
I can confirm this behaviour. In fact passing the monitoring port via CLI also ignores the value passed and the node falls back to the default port 8080. 

Behaviour observed using the latest Docker images: 

```
"Id": "sha256:1f70dfb600767a7155a7a9d27acee000017e7c9934f9cb564aadb9dfd5425329",
        "RepoTags": [
            "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
        ],
        "RepoDigests": [
            "gcr.io/prysmaticlabs/prysm/beacon-chain@sha256:cc78cab6087bd6891fba995640b9247064b117c487ad8b723b5c2c2ea850f6bb"
        ]
```

**Comment by SeaMonkey82** [comment]
> In fact passing the monitoring port via CLI also ignores the value passed and the node falls back to the default port 8080.

I'm able to use an alternate port by passing the flag directly on the command line, but I'm using the script as opposed to docker.

**Comment by 0xKiwi** [comment]
Hey @prestonvanloon , do you know what could be going on here?

**Comment by prestonvanloon** [comment]
I've also confirmed this issue.

**Comment by prestonvanloon** [comment]
> Could this have anything to do with the fact that MonitoringPortFlag is the only integer flag defined with type Int64Flag instead of IntFlag? I'm no programmer...

Good call! This was exactly the issue.
