### ISSUE TITLE
Unable to Set Lighthouse Nodes as Bootnodes

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6490]
# 🐞 Bug Report

### Description

Prysm nodes are unable to set lighthouse nodes as their bootstrap nodes as it leads Prysm being unable to perform
a succesful discv5 handshake with the lighthouse node.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

`--bootstrap-nodes=lighthouse_enr`

## 🔥 Error

```
>> WHOAREYOU/v5                    
<< UNKNOWN/v5                          
>> WHOAREYOU/v5                       
<< UNKNOWN/v5                      
```
These packets are being exchanged between the same 2 peers, indicating that the handshake is unsuccessful.

## 🌍  Your Environment

**Operating System:**

Ubuntu

**What version of Prysm are you running? (Which release)**

Alpha.13

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
@nisdas Do you have any more details to share on this? I'm not sure how to triage

**Comment by nisdas** [comment]
@prestonvanloon It has been resolved, the user had some some misconfigured local settings.
