### ISSUE TITLE
How to deploy smart contract 

### ISSUE THREAD

**Issue by saarshah** [prysmaticlabs/prysm#6505]
I have deployed a smart contract on ropsten network and interact with it through web3, Node js, JavaScript. Now I want to deploy the same contract on Ethereum 2.0 (Proof of Stake) Testnet to check the difference. Is it possible ?

# 🚀 Feature Request

### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by rkapka** [comment]
Hi @saarshah. Creating and deploying smart contracts is not yet supported on Ethereum 2.0. You can read about the current state of affairs here: https://blog.ethereum.org/2020/06/02/the-state-of-eth2-june-2020/
If you would like to understand more about the Beacon Chain, then this is a great explainer: https://ethos.dev/beacon-chain/

**Comment by terencechain** [comment]
@saarshah 

Deposit contract deployment is not part of the Prysmatic lab's eth2 role & responsibility. This is not the best place for such question and seeking support. We are specialized in client and core protocol developments. While not so much on smart contract security and smart contract user documentations. Here's the correct place to post your question: https://github.com/ethereum/eth2.0-specs

**Comment by saarshah** [comment]
Thanks for your reply and i will try.
