### ISSUE TITLE
Beacon chain database corrupts at runtime

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#6516]
Hi,

I'm getting the following fatal error from beacon chain without any actions performed: 

```
time="2020-07-07 22:36:35" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2020-07-07 22:36:35" level=info msg="Chain genesis time reached" genesisTime="2020-06-14 05:17:24 +0000 UTC" genesisValidators=30253 prefix=slotutil
time="2020-07-07 22:36:36" level=fatal msg="Could not cache justified state balances: unknown boundary state" prefix=blockchain
```

## 🌍  Environment

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
   Prysm/v1.0.0-alpha.13/46b82eb15d508f277fd3733c38658701d5d5db69
  </code>
</pre>

**Comment by terencechain** [comment]
Fixed in https://github.com/prysmaticlabs/prysm/pull/6503

Please try `b868dfa48117ae3badd60546c13c07b766c8f50b` and reopen if the issue still persists.
