### ISSUE TITLE
Feature Flag Tracking: enableFinalizedDepositsCache

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#6518]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 
Opt-in

**Opt-in feature flag name**:
`enableFinalizedDepositsCache`

**Opt-out feature flag name**: 
`disableFinalizedDepositsCache`

### Feature Description
 Enables utilization of cached finalized deposits. This is helpful when building the deposit trie.

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete #6391
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated #7214
- [x] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by rkapka** [comment]
This seems to be doing well in long-running e2e tests since two weeks ago:
https://github.com/prysmaticlabs/prysm/pull/6391#issuecomment-660668028

Can we proceed with
> Feature flag is inverted to be opt-out and the opt-in flag is deprecated

**Comment by terencechain** [comment]
> This seems to be doing well in long-running e2e tests since two weeks ago:
> [#6391 (comment)](https://github.com/prysmaticlabs/prysm/pull/6391#issuecomment-660668028)
> 
> Can we proceed with
> 
> > Feature flag is inverted to be opt-out and the opt-in flag is deprecated

E2e is not enough, I'd wait until this is ran in the cluster (experimental) for the Medalla testnet for 5 days

**Comment by rkapka** [comment]
My bad. I forgot that the I added the flag in #6768. It was blocked by majority voting, but the issue has been finally resolved.

Let's get back to this a week after the PR get merged.

**Comment by rkapka** [comment]
#6768 has been merged almost 2 weeks ago. All good to move on @terencechain?

**Comment by terencechain** [comment]
> #6768 has been merged almost 2 weeks ago. All good to move on @terencechain?

yes!

**Comment by rkapka** [comment]
Closing this issue because we will deprecate flags after a beta release.
