### ISSUE TITLE
Deadlock When Sending A Large Amount of HTTP Requests to the Beacon Node 

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6529]
# 🐞 Bug Report

### Description

Sending a large amount of HTTP requests has the ability to stall the beacon node and prevent it from performing its duties.

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

Running a beacon node with its http gateway server enabled, and sending in a large amount of requests at once. Ex: (Validator Status). Eventually the beacon node will be stuck in a deadlock. This can be mitigated by running ```--dev``` or ```--new-beacon-state-locks``` , which allows us to use the new state with improved state locking. 

## 🔥 Error

![http_backlog](https://user-images.githubusercontent.com/33201827/86996344-00e30580-c1de-11ea-8e15-accbe6dfea94.png)

## 🌍  Your Environment

Ubuntu

**What version of Prysm are you running? (Which release)**

Alpha.13

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
This is addressed with --dev or --new-beacon-state-locks

The next step is to invert / roll out the feature flag

**Comment by farazdagi** [comment]
The flag has been inverted in https://github.com/prysmaticlabs/prysm/pull/6922 and is on by default now.
