### ISSUE TITLE
Usage of Last Processed Slot is A Griefing Vector

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6531]
# 💎 Issue

### Background

Currently we use a a variable in initial sync called `lastProcessedSlot` to prevent processing old blocks or 
already processed blocks. This is used whether we process blocks in batches or individually.

### Description

However having this variable makes the node's synchronization routine to griefing. A potentially malicious peer could send us 
a batch of non-finalized blocks which while being valid will lead us to increment our `lastProcessedSlot` to an incorrect value. 
Ex:
Finalized Chain
```
24 -> 25 -> 30 -> 31 -> 32 ....
```
Non-finalized branch
``` 
24 -> 26 -> 27 -> 28 -> 29
```
A malicious/less discerning peer could provide us with the non finalized branch which will lead us to incrementing the value to 29. However when we try to process blocks from the finalized branch, we will reject those blocks because 
```
25 < 29
```
This would lead us to stall our sync, and the only way to resolve it would be to restart the node. The correct /better solution would be to process blocks from our last finalized checkpoint onwards.

**Comment by prestonvanloon** [comment]
Bumping this to high priority as we're starting to see it in production.

**Comment by farazdagi** [comment]
Fixed in https://github.com/prysmaticlabs/prysm/pull/7006
