### ISSUE TITLE
Unable to build on/for Windows

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#654]
See these failures: 
https://gist.github.com/JerryFireman/95f555953197431fede5fc33b844ba1d
https://gist.github.com/JerryFireman/2fa1a1623be58d0f14afa839d38bed49

This also might open up a bigger issue on cross compiling to provide binaries for other architectures (i.e. raspberry pi, windows, android, etc). This is especially difficult due to dependencies on go-ethereum's cgo libraries.

Here's a (maybe helpful) example repo for cross compiling in bazel: https://github.com/mobileink/bazel-crosscompile
Also read: https://github.com/bazelbuild/rules_go#how-do-i-cross-compile

cc: @JerryFireman

**Comment by prestonvanloon** [comment]
I am out of office until November 1st and I plan to address this issue at that time, unless someone else has resolved it :)

**Comment by prestonvanloon** [comment]
Note, I can also replicate this behavior on linux by running:
```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //beacon-chain
```

Results in this error
```
ERROR: /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/com_github_ethereum_go_ethereum/crypto/BUILD.bazel:3:1: GoCompile external/com_github_ethereum_go_ethereum/crypto/windows_amd64_pure_stripped/go_default_library%/github.com/ethereum/go-ethereum/crypto.a failed (Exit 1)
GoCompile: error running subcommand: exit status 2
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:27:2: imported and not used: "github.com/ethereum/go-ethereum/crypto/secp256k1" as empty
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:32:9: undefined: secp256k1
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:60:9: undefined: secp256k1
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:67:9: undefined: secp256k1
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:72:10: undefined: secp256k1
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:81:9: undefined: secp256k1
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/sandbox/linux-sandbox/516/execroot/__main__/external/com_github_ethereum_go_ethereum/crypto/signature_cgo.go:86:9: undefined: secp256k1
```

The problem is likely somewhere in the cgo deps of https://github.com/prysmaticlabs/bazel-go-ethereum

**Comment by randomshinichi** [comment]
I'd like to work on this one - finally a use for my main PC

**Comment by myutzy** [comment]
I receive what appears to be the same error, or a related error, when running `bazel build //beacon-chain:beacon-chain` on Win 10 Pro x64. 

```
ERROR: C:/users/matt/_bazel_matt/spbvprbz/external/com_github_ethereum_go_ethereum/crypto/secp256k1/BUILD.bazel:4:1: in _cgo_collect_info rule @com_github_ethereum_go_ethereum//crypto/secp256k1:go_default_library%nacl_386%cgo_info:
Traceback (most recent call last):
        File "C:/users/matt/_bazel_matt/spbvprbz/external/com_github_ethereum_go_ethereum/crypto/secp256k1/BUILD.bazel", line 4
                _cgo_collect_info(name = 'go_default_library%nacl_386%cgo_info')
        File "C:/users/matt/_bazel_matt/spbvprbz/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 411, in _cgo_collect_info_impl
                _CgoInfo(orig_srcs = ctx.files.srcs, transf..., <6 more arguments>)
        File "C:/users/matt/_bazel_matt/spbvprbz/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 418, in _CgoInfo
                _select_archives(ctx.attr.libs)
        File "C:/users/matt/_bazel_matt/spbvprbz/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 131, in _select_archives
                fail("cc_library(s) did not produce a...")
cc_library(s) did not produce any files
ERROR: Analysis of target '//beacon-chain:beacon-chain' failed; build aborted: Analysis of target '@com_github_ethereum_go_ethereum//crypto/secp256k1:go_default_library%nacl_386%cgo_info' failed; build aborted
```

**Comment by randomshinichi** [comment]
Unfortunately I could not get bazel working far enough to reproduce this error. I'd like some proper instructions on how to set the compile environment up on Windows.

Here are the problems I waded through after spending some time on this. Please ping me if there is a guide to setting up the Windows compile env.
Ran into many minor MSYS errors.
You need to install Git for Windows.
Visual Studio Build Tools may need to be installed to compile protobuf-compiler.
1. BAZEL_SH needs to be set to C:\tools\msys64\usr\bin\bash.exe
2. bazel output directory needs to be set to something without spaces via TEST_TMPDIR and --output_user_root

```
bazel --output_user_root=\bazel_temp\bazelshinichikudo\ build //beacon-chain:beacon-chain
bazel --output_user_root=\bazel_temp\bazelshinichikudo\ build //validator:validator
```

And now, I have things like `/usr/bin/bash: line 4: rm: command not found.` Really need official env setup docs.

**Comment by JerryFireman** [comment]
Hi @randomshinichi I got Bazel running for Windows following these instructions
https://docs.bazel.build/versions/master/install-windows.html
It was a few weeks ago so my memory is foggy but as I remember the only issues I ran into were cleared by putting Visual C++ and Python in the path. When I tried to build Prysm I got the errors in the gist files posted above by @prestonvanloon. Please let me know if there is anything I  can do to help.

**Comment by morikawa-kaori** [comment]
Hi all.
I get error maybe same issue as talked here.
Windows10 Pro 64bit + Bazel then while building, I get error like this.

----------------
$ bazel build //beacon-chain:beacon-chain                                                            
INFO: Invocation ID: a6cc0111-e418-4ee8-9885-9ba5d24a5f40                                            
Loading:                                                                                             
Loading: 0 packages loaded                                                                           
ERROR: Skipping '/beacon-chain:beacon-chain': not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/beacon-chain:beacon-chain'                                                                                              WARNING: Target pattern parsing failed.
ERROR: not a valid absolute pattern (absolute target patterns must start with exactly two slashes): '/beacon-chain:beacon-chain'                                                     
INFO: Elapsed time: 0.833s                                                                           
INFO: 0 processes.                                                                                   
FAILED: Build did NOT complete successfully (0 packages loaded)                                      
FAILED: Build did NOT complete successfully (0 packages loaded)
---------------

if there is anything I can do to help this issue, please let me know.

**Comment by rauljordan** [comment]
We have decided to proceed by having windows users use the docker image to run Prysm. Shall we close this @prestonvanloon?

**Comment by prestonvanloon** [comment]
No, I'd like to leave this open because we'd really like to provide exe binaries for the main targets. 

#1635 enables `//validator` to build on windows so we are one step closer to getting this resolved.

**Comment by prestonvanloon** [comment]
I think we need to write (or add) a new crosstool for the c++ deps in sepc256k1 for (cross) compiling for windows. 

https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial

**Comment by prestonvanloon** [comment]
Also related: https://github.com/bazelbuild/rules_go/pull/1791

**Comment by prestonvanloon** [comment]
See tensorflow crosstool: https://github.com/tensorflow/tensorflow/blob/63be4a65a1ba37848d3bfbe72ea2b60184d9979e/third_party/toolchains/gpus/crosstool/BUILD

I think building the beacon chain requires the cpu and compiler flag.

ex
```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 \
  --cpu=x64_windows \
  --compiler=mingw-gcc \
  //beacon-chain
```

**Comment by prestonvanloon** [comment]
This builds on windows.
