### ISSUE TITLE
Beacon node gets flooded with incorrect blocks

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6548]
# 🐞 Bug Report

### Description

Participation rate is low (below 2/3) and finality isn't achieved since 30 epochs.

### Has this worked before in a previous version?

-

## 🔬 Minimal Reproduction

-

## 🔥 Error

[errors.csv.txt](https://github.com/prysmaticlabs/prysm/files/4904729/errors.csv.txt)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
docker tag HEAD-c2deab
prysm-docker-compose (default setup, no high-availability)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by raphpa** [comment]
Adding trace log 
[beacon.log.zip](https://github.com/prysmaticlabs/prysm/files/4904758/beacon.log.zip)

**Comment by stefa2k** [comment]
Full log (including `info`) here:
[beacon.zip](https://github.com/prysmaticlabs/prysm/files/4904786/beacon.zip)

**Comment by prestonvanloon** [comment]
Thanks.

We have two issues here:
- Someone is producing these bad blocks. Why/how is this the case? (need to investigate)
- This behavior is considered "bad" and we need to disconnect from that peer to avoid unnecessary resource usage.

I'm starting investigation on the second issue since that would resolve more user reports than the first issue, which I believe might be a single person running many validators.

**Comment by xuyenvuong** [comment]
Adding additional errors:
`time="2020-07-10 19:11:54" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 191360: could not get ancestor state: context deadline exceeded" prefix=sync
time="2020-07-10 19:11:54" level=error msg="Failed to retrieve pre state" error="could not get pre state for slot 191360: could not get ancestor state: context deadline exceeded" prefix=sync
time="2020-07-10 19:13:42" level=error msg="Panicked when handling p2p message! Recovering..." msg="Message: <
  from: "\000%\010\002\022!\002\212\014t=\032\313,\372\264]\300<\2027\034\010\302F*VP\323\307r\000M0\327q\n\024\250"
  data: "\305\003\004d\000\376\001\000\246\001\000\000l\376k\000\212k\000\030\344\000\000\000\225\353\002\005j\000\003\005\006\220\000\000DBp\035m\334\325w\275\206 w\342\323\331\324\302I\324\253\356\360\323\005Fg;\026M\236\024\024Y\027\000\005*\200\013Q\305\032\243qP\007\271L\272\367\3226b\017- \333\224\2508\261\232\375[n\2062\207\256$\\\r(\360\220`3\263\007\231\306\217\225~\274\310V[?z\314\336,\323\250\366$\362\314\\\353\177\350\027-\036\204\222\274P\364wb}\350\013\375\002U\241\365\312(\310t\340\265\356o\333=\316y\253\272\022\265cE\306>\330t\202\327\350\020,\210\313R\304( {\022\211\001\222\261\231\367\354\001\373\013\212\004\025\3626\260u\210\352\025\036<\207\315=;\224-6\310\200H\000\250\025\"\263=\217-%\242\260z\020\300\214\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\200"
  seqno: "\026\037\376? \201\177\323"
  topicIDs: "/eth2/a65b4897/beacon_aggregate_and_proof/ssz_snappy"
>
ReceivedFrom: "\000%\010\002\022!\002Q\n\201T\356Im\010A\356\306\332C\247\377f\255\220\020\246`\353\037m\275 \317\230\267\333\235U"
ValidatorData: <nil>
" prefix=message-handler r="bitlists are different lengths"
time="2020-07-10 19:13:42" level=error msg="Received nil message on pubsub" prefix=sync topic="/eth2/a65b4897/beacon_aggregate_and_proof/ssz_snappy"`

**Comment by mshean** [comment]
More logs if it helps
[beaconchain-and-validator-logs.zip](https://github.com/prysmaticlabs/prysm/files/4905012/beaconchain-and-validator-logs.zip)

**Comment by prestonvanloon** [comment]
Also looking at `bitlists are different lengths` for beacon_aggregate_and_proof

**Comment by lenifoti** [comment]
Altona verifier attestation failures - coincide with Eth1 Sync errors.

Mac OS
Version: alpha.14
Local time: UTC+12

[validator1.txt](https://github.com/prysmaticlabs/prysm/files/4906063/validator1.txt)
[beacon1.txt](https://github.com/prysmaticlabs/prysm/files/4906064/beacon1.txt)

e.g.

[2020-07-11 02:24:33] ERROR validator: Could not request attestation to sign at slot error=rpc error: code = InvalidArgument desc = invalid request: attestation slot 79772 not within attestation propagation range of 80940 to 80972 (current slot) pubKey=0x91ba99f3a50c slot=79772

**Comment by prestonvanloon** [comment]
> [2020-07-11 02:19:46]  WARN powchain: eth1 client is not syncing 

This is probably a symptom of #6544.

**Comment by prestonvanloon** [comment]
The fixes for this have been released to alpha.15. Please update your node and comment here if you are still having issues.

**Comment by xuyenvuong** [comment]
Thanks @prestonvanloon - Great works.
