### ISSUE TITLE
Standardize params.Config in Beacon-Chain and Validator Projects

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#656]
Hi all,

We currently have two different ways of getting configuration params in both projects, the beacon chain uses params.GetConfig() while the validator uses params.DemoConfig() or params.DefaultConfig(). This is a bit confusing and would be best if we just stick to the way the beacon chain does so. This obfuscates what type of config parameters the system is using and lets the cli and node handle this effectively through a flag. This is preferred.

A PR to close this would change validator's params package to match the way the beacon-chain handles its params.

**Comment by prestonvanloon** [comment]
IMO, there should be a single `params.Config()` which its contents are dictated by cli flags.

**Comment by cyberbono3** [comment]
I am interested to dig deeper and resolve my first issue

**Comment by rawfalafel** [comment]
@prestonvanloon , that sounds like a good idea. 

So the requirements would be a `config.go` file in the `shared` directory. 

The `SetEnv` method should accept a second parameter for `beaconchain` or `validator`. If the second parameter is `validator`, `GetConfig` returns a subset of the config with the fields `CollationSizeLimit`, `SlotDuration`, `CycleLength`. 

@cyberbono3 , sorry for the late response and thanks for offering! This issue doesn't delve too deep into the details of shasper, so I hope that what's here provides enough context. Feel free to ask any question in this thread or on our Discord though :+1:
