### ISSUE TITLE
Blocks saved during attestation prestate fetch?

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6564]
# 💎 Issue

### Background

During investigation of potential attestation inclusion issues, I was looking at the code paths for attestation processing.

### Description

As part of the validation for signed aggregated attestation and proof, there is a bit of code that seems out of place for `getAttPreState`.

https://github.com/prysmaticlabs/prysm/blob/a4cfd147ff7ab93aa54768d757012ea067066250/beacon-chain/blockchain/process_attestation_helpers.go#L32-L37

I find this bit of code weird since it deals with initial sync and saving blocks. This code needs to be annotated with comments or removed since it doesn't seem to be related to fetching the attestation pre-state. 

Assigning to @terencechain as a recent author of this code. 
@terencechain can you please comment here on what we should do?

**Comment by terencechain** [comment]
Hi! not sure if i was the original author but always excited to sort this out? how can i help?

**Comment by prestonvanloon** [comment]
If we look at this method from the point of view of “single responsibility”, why would a method that fetches an attestation pre state save initial sync blocks? What is going on with these lines of code and why is it important?

**Comment by terencechain** [comment]
You have a good point, that piece of code shouldn't be inside `getAttPreState`. I'll move it to `onAttestation` and add comments on why it's needed
