### ISSUE TITLE
Aggregator should use self-attested attestation

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6565]
**Problem statement:**

Prysm aggregator signs off and broadcasts the best aggregated attestation (e.g. the one with the most aggregation bits). This is the correct strategy, but we do miss one important check. Prysm aggregators should also check that the best aggregated attestation has similar `attestation_data` to their unaggregated attestation for the assigned slot.

As outlined in the [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#attestation-aggregation):
```
Some validators are selected to locally aggregate attestations with a similar attestation_data to their constructed attestation for the assigned slot.
```

**Problem example:**
Say the attestation pool looks like
```
{HeadRoot:0xA, AggregatedBits: 0x0001} // Proposed by local attester and selected to be aggregator
{HeadRoot:0xA, AggregatedBits: 0x0010} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x0001} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x0010} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x0100} // Received over the wire
```
As an aggregator at Bits `0x0001`, the aggregator should broadcast attestation:
```
{HeadRoot:0xA, AggregatedBits: 0x0011} 

NOT

{HeadRoot:0xB, AggregatedBits: 0x0111} 
```
Currently, the aggregator broadcasts `0xB` instead of `0xA`

This inconsistent behavior will cause local attesters to lose money

**Comment by prestonvanloon** [comment]
I think your example is a slashable event. The local attester would not create an attestation for head root 0xA and 0xB.

Nonetheless, the aggregator should always prefer their attestation over the most aggregated one to ensure their attestation is broadcasted as an aggregated attestation.

**Comment by terencechain** [comment]
> I think your example is a slashable event. The local attester would not create an attestation for head root 0xA and 0xB.

Ah yes. I meant for this:
```
{HeadRoot:0xA, AggregatedBits: 0x000001} // Proposed by local attester and selected to be aggregator
{HeadRoot:0xA, AggregatedBits: 0x000010} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x010000} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x001000} // Received over the wire
{HeadRoot:0xB, AggregatedBits: 0x000100} // Received over the wire
```

**Comment by prestonvanloon** [comment]
Working on this now
