### ISSUE TITLE
Implement "IsSynced" method to determine sync status of node

### ISSUE THREAD

**Issue by rawfalafel** [prysmaticlabs/prysm#661]
Currently, `sync/service.go` and `initial-sync/service.go` determines the sync status of the node (in relation to the network) by calling `db.HasStoredState()`. 

`db.HasStoredState()` only determines whether or not the local database has been initialized, not whether or not the local chain is caught up with the current chain. Therefore, we should replace `HasStoredState` with a new method `IsSynced` which surveys peers in the network.

**Comment by rawfalafel** [comment]
As a first step, I'm going to open up a preliminary PR to replaced `db.HasStoredState` with a stub for `IsSynced`. Merging that PR will allow #426 and #555 to be closed out.

**Comment by nisdas** [comment]
Closed by #787
