### ISSUE TITLE
Why you banned me ?

### ISSUE THREAD

**Issue by samuelbrunner** [prysmaticlabs/prysm#6621]
# 💎 Issue

### Background

 Context and background information on the discussion...

**Comment by samuelbrunner** [comment]
Picture of Epstein cause ban ?

**Comment by rauljordan** [comment]
Our discord and github are not appropriate communities for these topics. Please keep the discussion about eth2 and the Prysm client.

**Comment by samuelbrunner** [comment]
Okay no more fun with Epstein so
