### ISSUE TITLE
Req/Respone: Ping/Metadata - Verify that metadata.seq_nr is strictly increasing

### ISSUE THREAD

**Issue by tintinweb** [prysmaticlabs/prysm#6665]
# 🐞 Bug Report

### Description

Hey guys, just stumbled upon this and wanted to make sure you are aware of it. 
Prism does not seem to enforce that the sequence_nr is strictly increasing when updating the metadata of a node.

[Spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/p2p-interface.md#metadata)
> seq_number is a uint64 starting at 0 used to version the node's metadata. If any other field in the local MetaData changes, the node MUST increment seq_number by 1.

The spec states that nodes must increment the sequence nr. If for whatever reason a seq_nr is seen to decrement this should raise an alarm.

https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L55-L72

https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L115-L123

validation:
https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L126-L139

- ping response: check ping sequence nr > cached sequence nr
- get metadata: check ping sequence nr > cached sequence nr 
- discuss whether this should be a reason to decrement the score of a node

## 🔬 Minimal Reproduction

* hint a seq_nr that is lower than the one cached for the peer
* code validates that `ping_sequence_nr != cached_sequence_nr` 
* metadata is updated w/o checking if seqnr is strictly increasing (or the one provided in the getMetadata call is actually > the one that is cached).

cheers,

tin / consensys diligence

**Comment by nisdas** [comment]
Hey @tintinweb , thanks for this bug report ! This does definitely does look incorrect on our part, I will try to get this fixed over the next few days.

**Comment by nisdas** [comment]
@tintinweb you can keep an eye on #6711 , it should resolve the issue.
