### ISSUE TITLE
Validator version info still prints alpha.15

### ISSUE THREAD

**Issue by dapplion** [prysmaticlabs/prysm#6675]
Current validator version info has the correct build time `Built at: 2020-07-21 00:49:02+00:00` but the wrong version `validator version Prysm/v1.0.0-alpha.15`. See full output below:

```
./prysm.sh validator --version
Latest Prysm version is v1.0.0-alpha.16.
Validator is up to date.
Verifying binary integrity.
validator-v1.0.0-alpha.16-darwin-amd64: OK
gpg: Signature made Tue 21 Jul 04:31:44 2020 CEST
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /Users/edu/DAppNodePackages/DAppNodePackage-prysm-beacon-chain/prysm/./dist/validator-v1.0.0-alpha.16-darwin-amd64 has been signed by Prysmatic Labs.
Starting Prysm validator --version
INFO[0000] New calculated roughtime offset is -51877313 ns  prefix=roughtime
validator version Prysm/v1.0.0-alpha.15/0e4cb68249892daa9e142ae6033da202c7fb01bb. Built at: 2020-07-21 00:49:02+00:00
```

**Comment by prestonvanloon** [comment]
Sorry about that! This is a cosmetic issue only, 0e4cb68249892daa9e142ae6033da202c7fb01bb is the correct commit and that is what your log is indicating so you're running the correct code for alpha.16. 

I accidentally stamped the binary with the wrong git tag and DAppNode picked up the incorrectly stamped binaries before I could fix it.

cc: @eduadiez 

Edu, if you could reupload the binary assets to DAppNode, then that would be great! The files here https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0-alpha.16 and the ones hosted at https://prysmaticlabs.com/releases have the correctly stamped binary for alpha.16.

**Comment by dapplion** [comment]
No problem! Glad it already fixed :heart: We will probably stick to this version because the Aragon Package Manager would require to publish a new version to amend any file. But @eduadiez has the last word.
