### ISSUE TITLE
Healthz of beacon returns incorrect status before syncing

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6682]
# 🐞 Bug Report

### Description

When starting the beacon-chain service and querying `/healthz` the endpoint returns no errors, but only `OK`s like this:
```
$ curl localhost:8480/healthz
*gateway.Gateway: OK
*p2p.Service: OK
*powchain.Service: OK
*attestations.Service: OK
*blockchain.Service: OK
*initialsync.Service: OK
*sync.Service: OK
*rpc.Service: OK
*prometheus.Service: OK
```
At the same time it logs something like this:
```
time="2020-07-22 17:14:08" level=info msg="Processing deposits from Ethereum 1 chain" deposits=5632 genesisValidators=5552 prefix=powchain
```

The beacon-chain then enters syncing (connects to peers, loads blocks, ...) and the status change to this:
```
$ curl localhost:8480/healthz
*p2p.Service: OK
*powchain.Service: OK
*attestations.Service: OK
*initialsync.Service: ERROR syncing
*blockchain.Service: OK
*sync.Service: ERROR waiting for initial sync
*rpc.Service: OK
*gateway.Gateway: OK
*prometheus.Service: OK
```

I'd expect seeing `ERROR` when the service isn't started yet. When everything is `OK` one could assume the beacon is ready to serve validators, but in fact it didn't even start syncing.

## 🔬 Minimal Reproduction

Start an empty beacon-chain, query `/healthz` shortly after before syncing starts.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
docker tag `HEAD-62ae22`
  </code>
</pre>

**Comment by prestonvanloon** [comment]
There is a missing edge case in #7077. 

The beacon node should serve validators if it has a genesis state, but the chain has not started yet.
The beacon node should not serve validators while it is processing deposits to determine the genesis state.
