### ISSUE TITLE
More sophisticated peer pruning

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#6701]
# 💎 Issue

### Background

Currently, we prune peers beyond some configured limit. Peers with relatively low number of bad responses are pruned first. Pruning mechanism relies on number of bad responses only, and we can extend it to use `PeerScorer` for a more fine-grained operation.

### Description
- Once `init-sync` related scoring functionality is merged (to track, see #6622), we can use `PeerScorer.Score()` value to get overall performance of a peer across all the tracked metrics. This will give better understanding on how valuable peer is.
- With current prune func, we remove good peers first, what happens if we have threshold (max peers we allow to be kept in cache) number of bad peers? Peer statistics decays with the time, but if peer was marked bad -- chances are it will violate rules again, so even with decaying, we may end up in a situation when we surround our node with "non-performant peers" only.

**Comment by prestonvanloon** [comment]
Removing  from v1 milestone as there is not enough time to design and implement this feature before v1 cut off.

**Comment by rauljordan** [comment]
Is this something we resolve with peer scoring @nisdas ? Not sure what the resolution of this issue is

**Comment by nisdas** [comment]
This can be closed, as the feature is now gated by a flag and will be the default in subsequent releases.
