### ISSUE TITLE
[Mega issue] - Accounts Revamp testing feedback: HD Wallets

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#6723]
# Information 

Tested on Ubuntu 20.04

# Issues

### HD

JULY 25

- [ ] The following prompt is displayed when creating a new wallet:

> Confirm you have written down the recovery words somewhere safe (offline)? [y/N]

Typing anything other than `y` results in the same behaviour, so the `N` option does not make much sense. Furthermore, typing `Y` does not confirm although it should. Maybe it would be better to change `[y/N]` to `[y/Y]`?

- [ ] When recovering the wallet I typed this pass phrase:

> 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4

The message:

> FATAL accounts-v2: Could not recover wallet: could not initialize new wallet seed file: could not convert mnemonic to wallet seed: word \`1\` not found in reverse map

Then I typed `critic` 24 times and got this:

> FATAL accounts-v2: Could not recover wallet: could not initialize new wallet seed file: could not convert mnemonic to wallet seed: Checksum incorrect

In my opinion these messages are too technical. In both scenarios a unified, more user-friendly message should be displayed.

### HD

JULY 25

- [ ] Providing a wrong password on account creation displays this:

> FATAL accounts-v2: Could not create new account: could not initialize keymanager: could not initialize derived keymanager: could not decrypt seed configuration with password: invalid checksum

The message should just say that the password is incorrect.

- [ ] The command `create --help` lists a `--skip-mnemonic-confirm` flag, but the mnemonic is a part of HD wallet creation, not account creation. Providing this flag when creating an HD wallet results in an unknown flag error.
- [ ] There is a small difference in formatting between `list` for a non-HD wallet and an HD wallet.

Non-HD

> ideally-composed-chipmunk
[public key] 0xa5a1c7904c7a49a0930cb5494e340ae08c0b53e129d8555a3147ea8df10807ba98525ee0ba5ba487d99d6b579f057a54
[created at] 1 day ago

HD

> positively-relative-skunk | 1 hour ago
[withdrawal public key] 0xb0d4aff8a4557047858ee0d95115e453847680e3fc1d5f348e1814dafa4a666d776247e4e3d34c6876a3abda0a853f8a
[derivation path] m/12381/3600/0/0
[validating public key] 0x98585b12562cc6300658b9a1c3491b617e806d3eec672a2ba321658cacac0ad82ec184721651a53d987cefa115cb676a
[derivation path] m/12381/3600/0/0/0

The Non-HD one has the creation date on a separate `[created at]` line while the HD one has the creation date in the first line after a separator.

**Comment by nisdas** [comment]
Can we just put all the feedback into one issue. Ex: #6715 , otherwise this becomes fragmented and hard to track. I dont see the need to have 2 Mega Issues for Accounts Revamp testing

**Comment by rkapka** [comment]
Merged with #6715.
