### ISSUE TITLE
[Medalla] Could not determine if beacon chain started

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6734]
Docker, Windows & macos

`docker run -it -v e:/prysm:/data --network="host" gcr.io/prysmaticlabs/prysm/validator:latest --keystore-path=/data --datadir=/data --password=yourPassword --medalla`

`docker run -it -v e:/prysm/:/data -p 4000:4000 -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data --medalla`

![cmd_2020-07-27_13-19-54](https://user-images.githubusercontent.com/26490734/88536300-e72e2480-d00b-11ea-8daf-6536bd4c8689.png)

**Error during sync** 
`FATAL validator: Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = write tcp 127.0.0.1:53340->127.0.0.1:4000: write: broken pipe`

**Error once synced** 
`FATAL validator: Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection closed`

**Comment by terencechain** [comment]
The problem here is:
1.) Beacon node doesn't have a genesis state (eg. hasn't reached 16384 deposits)
2.) Beacon chain hasn't started

That is why validator err'ed out and correctly reported `Could not determine if beacon chain started`

**Comment by raphpa** [comment]
I think the error message is a bit misleading here.

Your beacon-chain is listening to 127.0.0.1
Running docker this is the local interface within the container and not visible to the outside world. Your validator cannot connect to it, even via the 'host' network (which should be avoided anyways).

What you want to do is:
- Create a docker network
`docker network create --attachable medalla`

- Start beacon-chain, make it listen to all interfaces and attach it to the docker network
`docker run --name beacon-chain --network medalla -v e:/prysm/:/data -p 12000:12000/udp -p 13000:13000 gcr.io/prysmaticlabs/prysm/beacon-chain:latest --datadir=/data --medalla --rpc-host=0.0.0.0 `

- Start validator, attach it to the docker network and have it connect to beacon-chain via the docker network
`docker run --name validator --network medalla -v e:/prysm/:/data gcr.io/prysmaticlabs/prysm/validator:latest --keystore-path=/data --datadir=/data --password=yourPassword --medalla --beacon-rpc-provider=beacon-chain:4000 `

**Comment by Buttaa** [comment]
> The problem here is:
> 1.) Beacon node doesn't have a genesis state (eg. hasn't reached 16384 deposits)
> 2.) Beacon chain hasn't started
> 
> That is why validator err'ed out and correctly reported `Could not determine if beacon chain started`

Shouldn't i still be able to have the validator client running at least? It throws an error and stops running..

**Comment by terencechain** [comment]
> Shouldn't i still be able to have the validator client running at least? It throws an error and stops running..

I agree. That would be nice...

**Comment by begetan** [comment]
Run `validator-v1.0.0-alpha.17-linux-amd64` without any issues since Medalla is ready for the launch
