### ISSUE TITLE
Beacon Chain Metrics validator_count for Active Validators Incorrectly Accounting for Exits

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#6735]
# 🐞 Bug Report

### Description

 Beacon chain metrics active validator count may be incorrectly subtracting exiting validators. 

Last night I started exiting 1100 validators. I have a grafana chart that shows validator_count for both "exiting" and "active" validators. I expected the exiting value with jump up to 1100 immediately, showing that the exit queue is now 1100 validators larger. This is exactly what happened.

However, I expected the active validators value to decrease by only 4 validators per epoch. Instead, the active validators count dropped by 1100 almost immediately.

This may be a misunderstanding on my part about how active validators should be calculated, but my assumption is that the 1100 validators are active until they reach the front of the queue are are inactivated 4 at a time. (Or whatever the precise rate is.)

Instead, it almost looks like the active validator count simply subtracts the exiting value.

It is possible this is as-designed, but I would think the active count should show actual current active validators, in which case I assume this is wrong.

### Has this worked before in a previous version?

Unknown. I was not monitoring these values closely when I was running a previous version.

## 🔬 Minimal Reproduction

Submit a number of exits larger than the number that can exit in a single epoch. See active validator count reduce by the full number instead of the number actually exiting in an epoch.

## 🔥 Error

See my chart below. Note that my chart shows exits as negative, intentionally, as a way of showing that the number of validators is being reduced by that amount. Nevertheless, note also that when my exiting value goes to -1100, the validator count drops by 1100 almost precisely in lock-step with the exiting number. Active validators is in brown and exiting is in yellow.

![image](https://user-images.githubusercontent.com/54516310/88547227-a9fd6e80-cfda-11ea-831a-2678f60efafa.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.16
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by metanull-operator** [comment]
This chart may illustrate my point better. Here you see that the exit queue is slowly dwindling as validators are exited, but the active validator count has already counted those as exited.

![image](https://user-images.githubusercontent.com/54516310/88563716-8690ee80-cfef-11ea-8593-8705a3f7b8f4.png)

**Comment by terencechain** [comment]
The described behavior was correct. Let's take a look at the eth2.0 spec. The definition for active is:

```python
def is_active_validator(validator: Validator, epoch: Epoch) -> bool:
    """
    Check if ``validator`` is active.
    """
    return validator.activation_epoch <= epoch < validator.exit_epoch
```

In this case, the current epoch has likely exceeded your validators exit epoch. Hence they were no longer active

The pending exit queue is different than the "active" status. While you are validators are still in the pending active queue, they are still expected to perform their duties. They are performing their duties without the "active" status
