### ISSUE TITLE
Handle Chain Reorg

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#674]
Hi all,

If a block with a lower slot is selected as a higher scoring one, we need to reorg the chain to match this result. This would entail adding reorg logic within the `updateHead` function after merging #643, leveraging persisted states for unfinalized blocks, and building up a new chain from the last finalized slot upwards.

A PR for this would also include pretty exhaustive tests for various reorg scenarios.

**Comment by terenc3t** [comment]
Closing this one. Please refer to #1307 for chain reorg
