### ISSUE TITLE
DeepSource: Potential code quality issues found

### ISSUE THREAD

**Issue by chsatyap** [prysmaticlabs/prysm#6747]
I forked this repo a while ago and ran a DeepSource analysis on it. DeepSource found a variety of different issues categorized based on their types and severity which you can view [here](https://deepsource.io/gh/chsatyap/prysm/).

Brief description -
Anti-Patterns: 341
Bug Risks: 300
Performance issues: 9
Security Issues: 1

You can find a detailed description and fixes for some of them [here](https://deepsource.io/gh/chsatyap/prysm/issues/?category=recommended).

Please let me know what issues you'd like to focus on fixing and I'd be happy to take a look into it. Also, you can choose to hide certain types of issues too (if you wish to ignore them or you believe it is a false positive). I'd also be happy to send a patch with the DeepSource configuration file with the required fixes.

You can find the required configuration file for DeepSource [here](https://github.com/chsatyap/prysm/blob/master/.deepsource.toml).

**Comment by prestonvanloon** [comment]
This is great! We discussed in the team that we would like to fix as many of these issues as we can.

We want to add new static analysis to our build tooling for some of these issues. 

I think these are a few good places to start that wouldn't require a static analyzer. 
- [unused code](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-U1000/occurrences)
- [Using a deprecated function, variable, constant or field](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA1019/occurrences)
- [File path traversal when extracting zip archive](https://deepsource.io/gh/chsatyap/prysm/issue/GSC-G305/occurrences)
- [The loop exits unconditionally after one iteration](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA4004/occurrences)
- [Simplify make call by omitting redundant arguments](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-S1019/occurrences)
- [Don’t use fmt.Sprintf("%s", x) unnecessarily](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-S1025/occurrences)
- And many of the anti-pattern suggestions would be welcome as well

I think these would be high value candidates for add a static analyzer in prysm.
- [Boolean expression has identical expressions on both sides](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA4000/occurrences)
- [Assigning to b.N in benchmarks detected](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA3001/occurrences)
- [&*x gets simplified to x and it does not copy x](https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA4001/occurrences)
- [Shadow of builtin detected](https://deepsource.io/gh/chsatyap/prysm/issue/CRT-A0001/occurrences)
- [Slice can be used directly](https://deepsource.io/gh/chsatyap/prysm/issue/CRT-A0016/occurrences)

For an example of a static analysis addition, please see #6401, #5403, #5296, #5456.

**Comment by chsatyap** [comment]
Thank you for your inputs! Issues that you don't wish to be tracked can be ignored and they shouldn't show up again. I'd look into the static analysis addition and let you know.

**Comment by rkapka** [comment]
Analysis from today: https://deepsource.io/gh/rkapka/prysm/
