### ISSUE TITLE
ancestor via db cause resource exhaustion

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6750]
# 🐞 Bug Report

### Description

As reported in the Discord channel and observed in clusters. The current Onyx testnet nodes have been using significantly more resources and that's due to long duration of epochs since finality. At this time of writing this, there's ~200 epochs since finality. https://beaconcha.in/. 

The biggest bottleneck is retrieving ancestors for block via DB

![Screen Shot 2020-07-28 at 9 40 14 AM](https://user-images.githubusercontent.com/21316537/88696865-a5a78300-d0b8-11ea-83ae-f709b9a032eb.png)

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Sync to head on Onyx testnet

## 🔥 Error

N/A

**Comment by raphpa** [comment]
In my case it is approaching nearly 100% of CPU and memory usage on two different nodes

**Comment by stefa2k** [comment]
Filtered my beaconchain log to only visualize warning/error/fatal:

[finality issues.txt](https://github.com/prysmaticlabs/prysm/files/4990125/finality.issues.txt)

**Comment by stefa2k** [comment]
Also some statistics:
![image](https://user-images.githubusercontent.com/54934211/88701401-42ded780-d10a-11ea-8f38-b3d6d03f1b7b.png)

**Comment by terencechain** [comment]
Thanks @stefa2k @raphpa 

There's multiple issues that contribute to resource exhaustion. This is just the first one. I'll be opening more issues today. 

Thanks again for closely monitoring and prompt reporting
