### ISSUE TITLE
Attacknet - l4 dos attack ruins prysm p2p connectivity and stops finality

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6765]
This issue tracks the overall progress of addressing the following attacknet incident, the resolutions and the logs:
https://github.com/ethereum/public-attacknets/issues/9

**Comment by AlexSSD7** [comment]
This issue can be solved by temporarily banning IPs that are flooding prysm's P2P port.

**Comment by nisdas** [comment]
Linking this comment from the main issue to shed more light on this:
https://github.com/ethereum/public-attacknets/issues/9#issuecomment-665696739
