### ISSUE TITLE
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0

### ISSUE THREAD

**Issue by zq19** [prysmaticlabs/prysm#6779]
After i run the below code：./prysm.sh beacon-chain --datadir=$HOME/.eth2

it happening：
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
.......

**Comment by rauljordan** [comment]
Duplicate of  #6746, please follow that issue for updates
