### ISSUE TITLE
Beacon Chain Sync Errors

### ISSUE THREAD

**Issue by jtesta** [prysmaticlabs/prysm#6783]
# 🐞 Bug Report

### Description

When running `./prysm.sh beacon-chain` (version alpha16), there seems to be trouble syncing blocks; errors with stack dumps are printed.  I've restarted the service several times in the last 4 days, but the same errors are still encountered.  The machine was also rebooted to no effect.

### Has this worked before in a previous version?

This error was not encountered with previous releases.

## 🔬 Minimal Reproduction

Simply run `./prysm.sh beacon-chain`

## 🔥 Error

<pre><code>
[2020-07-30 15:44:51]  WARN blockchain: Could not receive attestation in chain service aggregationCount=1 beaconBlockRoot=0x89f95330be30 committeeIndex=1 error=target epoch 10446 does not match current epoch 10448 or prev epoch 10447
could not process attestation
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveAttestationNoPubsub   
        beacon-chain/blockchain/receive_attestation.go:40
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).processAttestation
        beacon-chain/blockchain/receive_attestation.go:117
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373 slot=334292 targetRoot=0x89f95330be30
[2020-07-30 15:45:18]  INFO p2p: Peer connected activePeers=17 direction=Outbound multiAddr=/ip4/35.226.185.107/tcp/13000/p2p/16Uiu2HAm2GsaT7sw8T76VK9KiyLqHNkmc3EGjPqdNX72tYZcNYbG
[2020-07-30 15:45:21] ERROR sync: Failed to retrieve pre state error=context deadline exceeded
could not get pre state for slot 334304
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:34
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-07-30 15:45:22] ERROR sync: Failed to retrieve pre state error=context deadline exceeded
could not get ancestor state
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).loadHotStateByRoot
        beacon-chain/state/stategen/hot.go:98
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).StateByRoot
        beacon-chain/state/stategen/getter.go:40
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:32
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
could not get pre state for slot 334304
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:34
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaco
nAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-07-30 15:45:22] ERROR sync: Failed to retrieve pre state error=context deadline exceeded
could not get ancestor state
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).loadHotStateByRoot
        beacon-chain/state/stategen/hot.go:98
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).StateByRoot
        beacon-chain/state/stategen/getter.go:40
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:32
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
could not get pre state for slot 334304
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:34
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-07-30 15:45:34] ERROR sync: Failed to retrieve pre state error=context deadline exceeded
could not get pre state for slot 334336
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:34
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-07-30 15:45:34] ERROR sync: Failed to retrieve pre state error=context deadline exceeded
could not get ancestor state
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).loadHotStateByRoot
        beacon-chain/state/stategen/hot.go:98
github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).StateByRoot
        beacon-chain/state/stategen/getter.go:40
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:32
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
could not get pre state for slot 334336
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).getAttPreState
        beacon-chain/blockchain/process_attestation_helpers.go:34
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).AttestationPreState
        beacon-chain/blockchain/receive_attestation.go:74
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).validateCommitteeIndexBeaconAttestation
        beacon-chain/sync/validate_beacon_attestation.go:89
github.com/prysmaticlabs/prysm/beacon-chain/sync.wrapAndReportValidation.func1
        beacon-chain/sync/subscriber.go:180
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:423
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:406
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:355
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:326
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1
        external/com_github_libp2p_go_libp2p_pubsub/validation.go:296
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
</code></pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu Server 20.04.1 (fully updated)

**What version of Prysm are you running? (Which release)**

1.0.0.alpha.16

**Anything else relevant (validator index / public key)?**

Validator: 0xb282d36b2e46b888e16815daee35aa99f279cf1bd168f3621405b43896e5c4ff1fb75aa3c70c146972dfbce421b6acae

**Comment by sergiolch** [comment]
I have similar problem, it shuts down all the time.

last lines of output:

```
...
[2020-08-08 14:13:01]  INFO initial-sync: Block is not processed error=slot 27132 already processed
[2020-08-08 14:13:01]  INFO initial-sync: Block is not processed error=slot 27133 already processed
[2020-08-08 14:13:01]  INFO initial-sync: Block is not processed error=slot 27134 already processed
[2020-08-08 14:13:01]  INFO initial-sync: Block is not processed error=slot 27135 already processed
[2020-08-08 14:13:04]  INFO initial-sync: Processing block 0x95a1ea47... 27232/29164 - estimated time remaining 3m14s blocksPerSecond=9.9 peers=33
[2020-08-08 14:13:07]  INFO initial-sync: Processing block 0xe969f4e1... 27264/29164 - estimated time remaining 3m11s blocksPerSecond=9.9 peers=33
[2020-08-08 14:13:09]  INFO initial-sync: Processing block 0x1b0beae8... 27296/29165 - estimated time remaining 3m8s blocksPerSecond=9.9 peers=33
[2020-08-08 14:13:12]  INFO initial-sync: Processing block 0x7eaa23d0... 27328/29165 - estimated time remaining 3m15s blocksPerSecond=9.4 peers=33
[2020-08-08 14:13:15]  INFO p2p: Peer disconnected activePeers=32 multiAddr=/ip4/161.35.194.216/tcp/9000/p2p/16Uiu2HAm7SgCe3A5UENQKijj7XyQHzA5zsDorC2wPauG49PJ6VCM
[2020-08-08 14:13:17]  INFO p2p: Peer disconnected activePeers=31 multiAddr=/ip4/76.118.232.174/tcp/9000/p2p/16Uiu2HAm4sDtVcECLPgmNwSz2chpGiLvSirsY9z64NDbKNtWobvt
[2020-08-08 14:13:19]  INFO initial-sync: Processing block 0xd53ebe68... 27360/29165 - estimated time remaining 4m8s blocksPerSecond=7.2 peers=31
[2020-08-08 14:13:20]  INFO p2p: Peer disconnected activePeers=30 multiAddr=/ip4/172.104.153.202/tcp/9000/p2p/16Uiu2HAmMjZEa7r39HywuK6vZKPdzjCizpXnqwukoX7R6p2nYTmk
```

After that error:

```
...
goroutine 11266 [select]:
github.com/libp2p/go-mplex.(*Stream).waitForData(0xc00c5666c0, 0xc011b9d860, 0xc00067c600)
        external/com_github_libp2p_go_mplex/stream.go:76 +0x111
github.com/libp2p/go-mplex.(*Stream).Read(0xc00c5666c0, 0xc01a8803b8, 0x1, 0x1, 0xc006bf6300, 0x442625, 0xc017bc43a0)
        external/com_github_libp2p_go_mplex/stream.go:122 +0x248
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc01fa1f340, 0xc01a8803b8, 0x1, 0x1, 0x42affb, 0xc000032000, 0x29a3280)
        external/com_github_libp2p_go_libp2p_swarm/swarm_stream.go:71 +0x62
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc017bc43a0, 0x13, 0x13, 0xc009364860)
        external/com_github_multiformats_go_multistream/multistream.go:452 +0x63
github.com/multiformats/go-varint.ReadUvarint(0x1c52c60, 0xc017bc43a0, 0xc01fa1f340, 0x0, 0x0)
        external/com_github_multiformats_go_varint/varint.go:80 +0x77
github.com/multiformats/go-multistream.lpReadBuf(0x7f95f1b40f40, 0xc01fa1f340, 0xc01c510900, 0xc009364930, 0x42c0f5, 0x1676d20, 0x17c11c0)
        external/com_github_multiformats_go_multistream/multistream.go:416 +0x6b
github.com/multiformats/go-multistream.ReadNextTokenBytes(0x7f95f1b40f40, 0xc01fa1f340, 0xc01fa1f340, 0x7f95f1b40f40, 0xc01fa1f340, 0x12, 0x0)
        external/com_github_multiformats_go_multistream/multistream.go:399 +0x39
github.com/multiformats/go-multistream.ReadNextToken(...)
        external/com_github_multiformats_go_multistream/multistream.go:388
github.com/multiformats/go-multistream.(*lazyClientConn).doReadHandshake(0xc01fa1f3b0)
        external/com_github_multiformats_go_multistream/lazyClient.go:81 +0xba
github.com/multiformats/go-multistream.(*lazyClientConn).Read.func1()
        external/com_github_multiformats_go_multistream/lazyClient.go:66 +0x91
sync.(*Once).doSlow(0xc01fa1f3b0, 0xc009364aa8)
        GOROOT/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        GOROOT/src/sync/once.go:57
github.com/multiformats/go-multistream.(*lazyClientConn).Read(0xc01fa1f3b0, 0xc01205b26c, 0x1, 0x1, 0x15c6600, 0xc009364b01, 0xc01205b26c)
        external/com_github_multiformats_go_multistream/lazyClient.go:64 +0x10c
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc00f5d4f80, 0xc01205b26c, 0x1, 0x1, 0x18830c8, 0x5, 0x15c63c0)
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:1008 +0x52
github.com/prysmaticlabs/prysm/beacon-chain/sync.ReadStatusCode(0x1ca0260, 0xc00f5d4f80, 0x1c8c1c0, 0x29ed628, 0xc006697a80, 0x18af498, 0x21, 0xc00f907ce0, 0x27)
        beacon-chain/sync/error.go:39 +0xa0
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).sendMetaDataRequest(0xc0005e0a00, 0x1c87900, 0xc015248a00, 0xc00f907ce0, 0x27, 0x0, 0x0, 0x0)
        beacon-chain/sync/rpc_metadata.go:54 +0x1d7
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler.func1(0x1ca0260, 0xc02b254420, 0xc0005e0a00)
        beacon-chain/sync/rpc_ping.go:74 +0x139
created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
        beacon-chain/sync/rpc_ping.go:65 +0xa18
```

There are more output error line but it was too much.


## Environment:

### OS:

```
Debian GNU/Linux 9.13 (stretch)
```

### Prysm version:

```
beacon-chain-v1.0.0-alpha.19-linux-amd64
```

### public key:

validator:
```
0xb2d37fcffa9ea84416d7c353a9710d9a1eff8f871c1c31dad0adabd3332fdcde81beb865ea0d50193eb4c4b09228b0af
```

**Comment by rauljordan** [comment]
Hey guys, there have been significant improvements since then that optimize for memory and CPU. These issues you were seeing are related to resource constraints of your beacon node on your machine. If they still persist, please comment on here and we will reopen.
