### ISSUE TITLE
--enable-eth1-data-majority-vote fails long running e2e tests

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#6786]
# 💎 Issue

### Background

Introduced in PR #6644, e2e has been failing consistently.

### Description

![Screenshot from 2020-07-30 10-35-14](https://user-images.githubusercontent.com/7246818/88955179-6ad85300-d250-11ea-8fd9-e2089f5827a1.png)

https://buildkite.com/prysmatic-labs/prysm-e2e/builds/8830#66c4d791-2b6b-4117-9aa3-a5717f36f619

**Comment by prestonvanloon** [comment]
E2E still failing for #6787. @0xKiwi and I are looking into it.

**Comment by prestonvanloon** [comment]
So we had two bugs failing CI (and CI is still flaky / failing). 

We've fixed part of it with #6793. The feature flag from #6644 is still problematic though. The long running e2e test is testing deposits being activated, but with #6644 it doesn't seem to happen at the same time as the e2e expects.

You can try with 
```
bazel test //endtoend:go_default_test --define=ssz=minimal --test_filter=TestEndToEnd_Long_MinimalConfig --test_env=E2E_EPOCHS=15 --test_timeout=10000 --test_output=streamed
```

It has been failing for the check on epoch 9.

**Comment by rkapka** [comment]
#6818 finally fixed the problem. The long-running e2e has passed: https://buildkite.com/prysmatic-labs/prysm-e2e/builds/10765#1c4d085e-b4e5-41c8-8a2d-3f3f0a518713

**Comment by prestonvanloon** [comment]
Looks good to me! Thanks
