### ISSUE TITLE
INFO roughtime: New calculated roughtime offset is -17744575 ns beacon-node sync

### ISSUE THREAD

**Issue by impact4him** [prysmaticlabs/prysm#6791]
# 🐞 Bug Report

### NFO roughtime: New calculated roughtime offset is -17744575 ns beacon-node sync

 when launching  beacon node from docker. i'm getting this msg: INFO roughtime: New calculated roughtime offset is -17744575 ns shortly after [2020-07-30 17:41:43]  INFO powchain: Processing deposits from Ethereum 1 chain deposits=13824 genesisValidators=13584

### Has this worked before in a previous version? i don't know 1st time running beacon node

 not sure

## 🔥 INFO roughtime: New calculated roughtime offset is -17744575 ns beacon-node sync

<pre><code>

 no still running but the offset is going down

</code></pre>

## 🌍  Your Environment

Ubuntu Server 18.04 

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
1.0.0

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
That's just an offset which can go to the negative territory. It can be positive or negative. In this PR we changed it to debug
https://github.com/prysmaticlabs/prysm/pull/6792
