### ISSUE TITLE
Using "wallet" keymanager attempts to open v2 wallet

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#6795]
# 🐞 Bug Report

### Description

I am using `--keymanager=wallet` which worked fine under alpha.16, correctly identifying my validators. When I upgraded to alpha.17, the validator is attempting to open v2 wallets without me specifying that it should.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

I ran alpha.16 with the following command and yaml file.

`prysm.sh validator --config-file /home/validator/prysm-validator.yaml`

```
keymanager: "wallet"
keymanageropts: "/home/validator/keys/keymanager.json"
monitoring-host: "0.0.0.0"
graffiti: "poapq1gBp9OYNRuL4RxDngXFsyWa7JsA"
beacon-rpc-provider: "localhost:4000"
```

My copy of alpha.16 was a self-compiled binary. When I switched to prysm.sh after alpha.17 was released, without any changes to my configuration, I got an error.

## 🔥 Error

<pre><code>
Jul 31 06:34:16 nuc02 prysm.sh[205506]: Verified /home/validator/bin/dist/validator-v1.0.0-alpha.17-linux-amd64 has been signed by Prysmatic Labs.
Jul 31 06:34:16 nuc02 prysm.sh[205506]: Starting Prysm validator --config-file /home/validator/prysm-validator.yaml
Jul 31 06:34:17 nuc02 prysm.sh[205506]: Enter a wallet directory (default: /home/validator/.eth2validators/prysm-wallet-v2):
Jul 31 06:34:17 nuc02 prysm.sh[205506]: time="2020-07-31 06:34:17" level=fatal msg="Could not open wallet: could not scan text input" prefix=node
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.17
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by handelaar2** [comment]
For me this seems to work as work around: `--disable-accounts-v2`

**Comment by metanull-operator** [comment]
@handelaar2 Thanks for the tip. I'll use that for now. I guess the question is: Is that how it is intended to be used?

**Comment by prestonvanloon** [comment]
@metanull-operator, We are planning to remove the old accounts management before promoting to "beta".

Sorry about the issues here. We usually set new features to be "opt-in" before they are "opt-out" but we really wanted to make accounts v2 the canonical account management as it is compatible with the EIP-2335 standard for account storage which is what all of the eth2 clients are targeting. We wanted this in before Medalla, but we should have consider the migration path.

Let me see if there is any tooling that would help you convert your existing keystores to a keystore that is compatible with accounts v2. Would that solve your use case or is there some reason to stay with accounts v1?

**Comment by handelaar2** [comment]
Preston, for me I would like to continue using ethdo for my validator/withdrawal keys.  That stopped working with v2

**Comment by prestonvanloon** [comment]
@handelaar2 OK great, thanks for that feedback. 

Can you elaborate on that use case? 
Why do you prefer to use ethdo / keymanageropts? 

I'm happy to find a way to support ethdo keystores. Let me know what you think!

**Comment by metanull-operator** [comment]
@prestonvanloon 

I probably have a few different answers to this:

1. Long term, I probably don't care too much which tools I am using for deposits. For mainnet I won't be making a thousand deposits that I need to script out. The launchpad will probably be sufficient.

1. However, I do not like that my withdrawal key and my validator keys are under the same mnemonic. Seems like a decent sized security oversight to me. If I ever have to restore my validator keys with my mnemonic, it seems that would put my withdrawal key at risk of being discovered. I'd rather my withdrawal mnemonic be locked up somewhere I don't even need to pull it out unless I actually intend to withdraw.

1. Short term answer is that I already made my deposits using ethdo/ethereal before accounts v2 was released, and I'd rather not waste those deposits. Trying to restore from the mnemonic I already have using the new tools seems like more effort than I want to put into it. Seems like I'd have to write another script to automate much of that, given that I have different passphrases for each account.

So... unless someone can convince me otherwise, I think using the same mnemonic for my withdrawal key and validator key seems like a security risk. And I may continue to look into options that allow me to separate the two. Other than that, I don't have a long-term need to use ethdo/ethereal.

**Comment by prestonvanloon** [comment]
Great feedback. 

1. Sounds good!
2. I completely agree, I have raised this complaint before but it didn't go anywhere. It is [EIP-2334](https://eips.ethereum.org/EIPS/eip-2334) to do this. However, you have options not to use the hierarchical keystore. You can use the non-HD wallet.
```
? Select a type of wallet: 
    HD Wallet (Recommended)
  ▸ Non-HD Wallet (Most Basic)
    Remote Signing Wallet (Advanced)
```

3. Sounds good, I was thinking of writing a tool to migrate from accounts v1 to accounts v2.

I'm going to raise this issue again with other eth2 teams. Thanks!

**Comment by prestonvanloon** [comment]
Note: the HD wallet is recommended because it's faster to load. That's the only reason. We're working on an idea where the Non-HD wallets are stored in a single encrypted keystore such that it wouldn't take `n` rounds of decryption to start the validator.

**Comment by metanull-operator** [comment]
I don't think I would use non-HD wallets under any scenario. Mnemonics are easier to back up and deal with.

**Comment by rauljordan** [comment]
Hi @metanull-operator you need --disable-accounts-v2 if you want to use the old format. Tested it out and it seems to work.
