### ISSUE TITLE
Key importer doesn't work to existing folder that has files in it

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6800]
Windows, binaries. 

Key import only works to folders which have not been created before.

`C:\prysm` was an existing path, which caused an error

![mspaint_2020-07-31_10-38-31](https://user-images.githubusercontent.com/26490734/89017060-0aade380-d31a-11ea-975e-a7d641150497.png)

**Comment by terencechain** [comment]
Updated title to `Key importer doesn't work to existing folder that has files in it`
