### ISSUE TITLE
Account V2 import private key

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6805]
# 🚀 Feature Request

### Description

At the moment there is no way to import a private key (hex format) into account v2.

### Describe the solution you'd like

A way to import a private key into an exisiting wallet.

**Comment by 0xKiwi** [comment]
Hey @rauljordan isn't this a problem you were working on?

**Comment by rauljordan** [comment]
Added in #6929 @stefa2k
