### ISSUE TITLE
FATAL accounts-v2: Could not list accounts: could not initialize keymanager

### ISSUE THREAD

**Issue by crisgarner** [prysmaticlabs/prysm#6812]
# 🐞 Bug Report

### Description

Listing accounts or starting the validators crashes if there was an account saved before

### Has this worked before in a previous version?

N/A

## 🔬 Minimal Reproduction

- Install new Prysm client on a server that already used Prysm
- Import accounts v2 (No error was thrown) ```./prysm.sh validator accounts-v2 import --keys-dir=$HOME/eth2.0-deposit-cli/validator_keys```
- List accounts or run validator

## 🔥 Error

<pre><code>
FATAL accounts-v2: Could not list accounts: could not initialize keymanager: could not initialize direct keymanager: could not initialize keys cache: could not read password for account jointly-perfect-chimp: could not read /root/.eth2validators/prysm-wallet-v2-passwords/jointly-perfect-chimp.pass: open /root/.eth2validators/prysm-wallet-v2-passwords/jointly-perfect-chimp.pass: no such file or directory
</code></pre>

Running multiple times produces a different error:

<pre><code>
panic: send on closed channel

goroutine 94 [running]:
github.com/prysmaticlabs/prysm/shared/mputil.Scatter.func1(0x4000820240, 0x40006ce040, 0x4000203980, 0x4000203920, 0x0, 0x1)
    shared/mputil/scatter.go:45 +0x7c
created by github.com/prysmaticlabs/prysm/shared/mputil.Scatter
    shared/mputil/scatter.go:42 +0x178
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
                          ./+o+-       ethereum@ethnode-0b9def7ee
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: aarch64 Linux 5.4.0-1015-raspi
           .++ .:/++++++/-.+sss/`      Uptime: 4h 33m
         .:++o:  /++++++++/:--:/-      Packages: 716
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.0.17
       .:+o:+o/.          `+sssoo+/    Disk: 9.2G / 67G (15%)
  .++/+:+oo+o:`             /sssooo.   CPU: BCM2835 @ 4x 1.5GHz
 /+++//+:`oo+o               /::--:.   RAM: 743MiB / 7811MiB
 \+/+o+++`o++o               ++////.  
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.17 Running the Prysm startup script
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

The problem is solved by removing the .eth2validators folder and importing again the account

**Comment by prestonvanloon** [comment]
This will be fixed in #6823. Thanks for the report!
