### ISSUE TITLE
Roughtime reports clock offset by 4hrs

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#6825]
# 🐞 Bug Report

### Description

 Slasher was up and running on Medalla and encountered the below error. I have pinged cc: @nisdas @prestonvanloon 

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: alpha.16

## 🔥 Error

<pre><code>

time="2020-07-31 07:12:34" level=warning msg="Roughtime reports your clock is off by more than 2 seconds" offset=4h0m0.317286608s prefix=roughtime

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

ARM64 on Pi 4 8GB
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.17
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
Should be addressed by #6879

**Comment by terencechain** [comment]
Just observed this again in latest master

**Comment by rauljordan** [comment]
Has since been resolved https://docs.google.com/document/d/11RmitNRui10LcLCyoXY6B1INCZZKq30gEU6BEg3EWfk/edit#

**Comment by xuyenvuong** [comment]
Thanks.

**Comment by shawnz** [comment]
Sorry if this is the incorrect place for this comment. But shouldn't the roughtime system be taking the median and not the average?

The same suggestion was made here https://github.com/cloudflare/roughtime/issues/22

**Comment by nisdas** [comment]
Hey @shawnz ,

We do not currently use roughtime anymore it has been removed in this PR #7299 . As far as I am aware roughtime still takes the average of all responses rather than the median, but given the roughtime spec is still in progress and undergoing standardization this may change in the future.
