### ISSUE TITLE
Beacon Error due to eth2stats keeps on opening a new connection to the beacon node

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#6826]
# 🐞 Bug Report

### Description
Beacon on alpha.17 was throwing these below errors after I started eth2stats Medalla (grpc.medalla.eth2stats.io:443)

 A clear and concise description of the problem...

### Has this worked before in a previous version?
Yes

 Yes, the previous version in which this bug was not present was: alpha.16 on Onyx

## 🔬 Minimal Reproduction

1. Start Beacon
2. Start eth2stats via docker
> sudo docker run -v -d --restart always --network="host" \
--name eth2stats-client \
-v /home/ethereum/.eth2stats/data:/data \
alethio/eth2stats-client:latest run \
--eth2stats.node-name="Maximus" \
--data.folder="/data" \
--eth2stats.addr="grpc.medalla.eth2stats.io:443" --eth2stats.tls=true \
--beacon.type="prysm" \
--beacon.addr="localhost:4000" \
--beacon.metrics-addr="http://localhost:8080/metrics"

3. Observe the errors

## 🔥 Error

<pre><code>

time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup caesium.tannerryan.ca: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup roughtime.chainpoint.org: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup roughtime.cloudflare.com: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup roughtime.sandbox.google.com: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup roughtime.int08h.com: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Could not get rough time result: lookup ticktock.mixmin.net: too many open files" prefix=roughtime
time="2020-08-01 03:48:34" level=error msg="Failed to calculate roughtime offset" error="no valid responses" prefix=roughtime

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.17
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
@tzapu

**Comment by tzapu** [comment]
proto did a bunch of fixes that seem related here https://github.com/Alethio/eth2stats-client/pull/47
could you pull latest  and try again @xuyenvuong ?

**Comment by xuyenvuong** [comment]
@tzapu - Seems like it is fine now after pulling the latest. Thanks for looking into this.
