### ISSUE TITLE
Add native Windows support through PowerShell

### ISSUE THREAD

**Issue by Shammah** [prysmaticlabs/prysm#6828]
### Background

A couple of people are having troubles with .bat files in combination with terminals such as Git Bash. Stuff like environment variables not being found, weird .bat logic behavior and binaries not being found (cmd.exe has no curl for example).

### Description

The current .bat file should either be replaced or superseded by a PowerShell version. PowerShell is Microsoft's preferred way of automating tasks, and it is designed to replace the old legacy way of automating tasks by .bat scripts. It is build on the .NET Framework and there is even an open-source and cross-platform version available called PowerShell Core that runs on .NET Core. Unlike most shells, which accept and return text, PowerShell is built on top of the .NET Common Language Runtime (CLR), and accepts and returns .NET objects.

More information about what PowerShell exactly is and how it's useful can be found at:
https://docs.microsoft.com/nl-nl/powershell/scripting/overview?view=powershell-7
https://en.wikipedia.org/wiki/PowerShell

**Comment by shayzluf** [comment]
assigned to @0xKiwi as i think he has a windows machine
