### ISSUE TITLE
Accounts-v2: error handling passwords containing spaces

### ISSUE THREAD

**Issue by gumforest** [prysmaticlabs/prysm#6831]
# 🐞 Bug Report

### Description

When running ./prysm.sh validator accounts-v2 import, prsym refuses to allow passwords containing spaces. The program outputs the error message
"Entry not valid: not valid unicode"
(even though a space is valid unicode and eth2.0-deposit-cli allows the creation of passwords containing spaces).

## 🔬 Minimal Reproduction

To duplicate, run ./prysm.sh validator accounts-v2 import --keys-dir=$HOME/eth2.0-deposit-cli/validator_keys
on a fresh install of the program and enter a password containing a space.

## 🔥 Error

The error message output is "Entry not valid: not valid unicode"

The problem seems to come from line 55 in shared/promituitl/validate.go in the function IsValidUnicode(), which returns false if the input string contains a space. This function is called to check the password.

Passwords should instead be checked by a different function which allows whitespace, perhaps displaying an alert to users if they enter a password that contains whitespace. 

The current error message is especially confusing since a space is valid unicode.

**Comment by prestonvanloon** [comment]
Fixed by #6810. Expect this release to land in alpha.18 tomorrow. Thanks!
