### ISSUE TITLE
Ability to create seperate withdrawal & validator keys files

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6835]
Feature Request 

Derive the validator private and withdrawal private key as seperate files through the mnemonic phrase. 
The idea is to generate them offline and to just move the validator priv key.

**Comment by shayzluf** [comment]
assigned to @rauljordan will be happy to join the design discussion and take this issue

**Comment by rauljordan** [comment]
@Buttaa not sure this is in scope. We already have the eth2 deposit CLI that seems to serve this purpose. There is also ethdo if you want more granular management of keys. In Prysm, we want to keep things simple.
