### ISSUE TITLE
Metadata RPC problem: request stream write-end not closed, Teku not responding to open write stream.

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#6837]
# 🐞 Bug Report

### Description

- Teku is known to not respond to an RPC request when the requesting side is not closed (cc @ajsutton)
- Prysm has weird metadata request behavior, closing the write side late: https://github.com/prysmaticlabs/prysm/blob/84697a0a5935590927957bd20cd82f5764fcb11e/beacon-chain/sync/rpc_metadata.go#L49
- Prysm has RPC metadata errors, and it somehow involves Teku peers in the logs a lot
- Found earlier on the new attacknet (publishing later). Similar problems on Medalla, now closer to the bug cause thanks to @ajsutton
- Teku has another metadata issue, but it seems to make no difference here. Teku was sending 0 bytes for the length prefix in their own metadata requests, while they should just make an empty request. Fixed by @ajsutton in https://github.com/PegaSysEng/teku/pull/2494

### Has this worked before in a previous version?

Not sure, clients are getting stricter with RPC behavior, and new errors pop up all the time because of it.

## 🔬 Minimal Reproduction

- Start a prysm node
- Start a teku node
- Have the two connect
- Prysm sends a metadata response
- I think it does not close the stream write end before getting a response
- Teku won't respond before the write end is done
- Timeout

## 🔥 Error

Prysm errors on new attacknet:
https://gist.github.com/protolambda/4e511e7bb106724e97141b1614934aba

I think users on medalla are experiencing similar problems.

## 🌍  Your Environment

Official docker container, in an ubuntu host machine.

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.17/37343930dd6d769e7df9d267b6344c2dae5e41c2. Built at: 2020-08-01 17:37:23+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
-

**Comment by prestonvanloon** [comment]
It's not clear what the bug is on the Prysm side.

After Prysm sends the metadata response, then waits up to 60 seconds for the other side to receive it and reply with EOF. 
If we close the stream immediately after sending, then the receiving side my not receive any message. If Teku doesn't respond to receiving a message then the stream has a timeout before it is fully closed after 60s.

**Comment by ajsutton** [comment]
So Teku is able to request metadata from Prysm and successfully receive the response.  The problem appears to be when Prysm requests metadata from Teku.  The spec (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#requesting-side) says:

> The requester MUST close the write side of the stream once it finishes writing the request message. At this point, the stream will be half-closed.

So for metadata, once the stream is negotiated as there's no content to write the write side should be immediately closed. Teku won't send a response until the write stream is closed.

**Comment by prestonvanloon** [comment]
Thanks @ajsutton! I talked with @protolambda offline and read your message and I see the issue now. I'm proposing a fix now and it will land before our next release tomorrow

**Comment by nisdas** [comment]
Discussed offline with @protolambda , that we decided it might be best to leave it as it is for now. If we do close the stream for writing, and then wait for the metadata to be sent by the remote peer both lighthouse and prysm nodes have issues with it. With lighthouse there were stream deadlines being hit for some reason and for prysm there were stream resets. 

Another alternative solution that was tried was sending in a junk 1 byte payload after opening the stream, which seemed to work but deviates from the spec.

The main issue is that streams are being opened without any payloads being sent by the initiating peer. This is an issue in go-libp2p's stream management. Given that not receiving metadata isn't the worst thing in the world and we are so close to medalla's genesis. This issue can be looked at after and resolved in a better manner.

**Comment by rauljordan** [comment]
Thoughts on this @nisdas ?

**Comment by protolambda** [comment]
Now we're close to spadina, and still not changed. I wouldn't risk the change for spadina genesis itself, but it would still be good to clean up code, and testrun this change before mainnet.

**Comment by nisdas** [comment]
This would be a more involved change in stream multiplexer libraries rather than something internal to prysm. I can take a look and see how much work this would take to fix.

**Comment by prestonvanloon** [comment]
Closing this as it's very old and out of date. Please comment here to reopen or file another issue if this is still an issue.
