### ISSUE TITLE
Set the values of chain and network ID.

### ISSUE THREAD

**Issue by ferranbt** [prysmaticlabs/prysm#6851]
# 💎 Issue

Hi!
I am trying to set up a local eth2 deployment with a ganache eth1x testnet and a beacon chain connected to it. However, it fails [here](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/powchain/service.go#L374) because chainID and networkID are hardcoded values for the goerli testnet (and I cannot change either the chainID for ganache). Is there anyway we can have this values parameterized either as flags or from a config file?

**Comment by terencechain** [comment]
Yes, we should add cli flags for `chainID` and `networkID`

Similar to deposit contract here https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/flags/base.go#L17

**Comment by ncitron** [comment]
I can give this a shot. I'm thinking the best solution would be to just check in `shared/params/testnet_medalla_config.go`, `shared/params/testnet_altona_config.go`, and `shared/params/mainnet_config.go` if a chain-id and network-id flag has been set, and to override it if so.
