### ISSUE TITLE
Slasher alpha 18 in windows failed to run 

### ISSUE THREAD

**Issue by msc82** [prysmaticlabs/prysm#6858]
windows 10
run slasher 
this app cant run on your PC
access is denied
an error has occurred

**Comment by prestonvanloon** [comment]
Could you please add more information? 

What version were you running?
What flags did you use?
What error did you get exactly? 

Please post a screenshot if you can.

**Comment by msc82** [comment]
hi @prestonvanloon  it s me etherpower   ,   it s ok now after alpha 18 v2
