### ISSUE TITLE
`import` does not import all keys

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6862]
Created keys via launchpad.
The folder i am importing from has 51 keys, 1 out of the 51 has a different password. The client only imports 1 key, assumingly the one with a different password. 

Workaround is via account recovery and use the new wallet

![image](https://user-images.githubusercontent.com/26490734/89274383-229aa580-d641-11ea-8454-94fc297466ae.png)

**Comment by rauljordan** [comment]
Cannot reproduce @Buttaa, tried multiple iterations of this and it works as expected. If the problem indeed happened to you and it was not a directory issue, please let us know and we can reopen.
