### ISSUE TITLE
Running a validator systemd service file before genesis

### ISSUE THREAD

**Issue by Radi88** [prysmaticlabs/prysm#6867]
# 🐞 Bug Report

### Description
Before genesis I set up systemd service files for both the beacon chain and validator. Everything was working as it should and the validator showed it was activated and waiting for the beacon chain to start on genesis, and it was showing that it has to attest on slot 18. On genesis the beacon chain started and when it passed slot 18, I went to look at the validator and it didn't get an attestation. There is no error in the journalctl logs either. This same thing happened to me on genesis in the onyx testnet. I had my systemd service files ready, on genesis the beaconchain was doing what it should, but the validator wasn't and I wasn't getting attestations. I missed a lot of attestations before I stopped the validator service file and started it again. As soon as I did that it started attesting. Today, when I saw that I missed the attestation at slot 18 in epoch 0 I immediately stopped the validator service file and started it again. Then it started attesting. 
 

### Has this worked before in a previous version?
This same thing happened on the onyx testnet. Except I missed a lot of attestations, because I didn't stop and start the validator service file immediately after a missed attestation like I did today.

 

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
I am using ubuntu 20.04 on a raspberry pi 4.
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
Hi @Radi88 we are working on a fix that will prevent missed attestations, it will be live in our next release. If this still happens to you after our next release, please feel free to comment and we can re-open.
