### ISSUE TITLE
Docker beacon-chain sync problem after restart

### ISSUE THREAD

**Issue by adamskrodzki** [prysmaticlabs/prysm#6883]
# 🐞 Bug Report

### Description

Docker container with gcr.io/prysmaticlabs/prysm/beacon-chain:latest

repeatedly displays 
`Waiting for enough suitable peers before syncing required=3 suitable=0`
and do not connect to Medalla testnet

### Has this worked before in a previous version?
I do not know that is first version i tested

## 🔬 Minimal Reproduction

I've started prysm following
I installed and runned prysm using this instruction,
https://docs.prylabs.network/docs/install/install-with-docker
then after some time I lost internet connection causing my docker containers to stop, 

after couple of hours (~5) i restarted container and reconnect internet and now I see following message
`Waiting for enough suitable peers before syncing required=3 suitable=0`

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10 version 
[logs.log](https://github.com/prysmaticlabs/prysm/files/5026523/logs.log)

2004
Docker version 19.03.12, build 48a66213fe
  </code>
</pre>

I do not know how to get version of prysm running in a container

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
Hi @adamskrodzki , there have been significant improvements to peer scoring and networking since the last 3 weeks. Please try again and let us know if this issue persists. You can also checkout https://docs.prylabs.network/docs/prysm-usage/p2p-host-ip. Let us know on here if you still have the issue and we will reopen.
