### ISSUE TITLE
Missed Attestation but logs show Submitted Attestation

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#6886]
# 🐞 Bug Report

### Description

Validator 2104 shows a missed attestation for block 5774: https://beaconscan.com/validator/0x8f6dd53b1dad5aab95733af5a0d1b8fb7ebe34301482a22976c415721cd421e393ba0d3d53214af4492b2c8b5963aca3#attestations
But logs indicate otherwise:
```
time="2020-08-05 08:15:04" level=info msg="Submitted new attestations" AggregatorIndices=[] AttesterIndices=[2627 2462 2765 2104 2204 2606 2670] BeaconBlockRoot=0x4a5ba294bb3b CommitteeIndex=3 Slot=5774 SourceEpoch=179 SourceRoot=0x39d619e2b2e5 TargetEpoch=180 TargetRoot=0xdf755144aa6c prefix=validator
```

Validator 2104 is also affected: https://beaconscan.com/validator/0x914cfbe6e83dbee11a91bfe0a16e3a97b2f6d0dacc4f216722977b88f216298f3fda5575ce877702260a34ba492cef4a#attestations

This happened when haproxy switched to another slasher instance for the sole running validator instance.

### Has this worked before in a previous version?

Never tested

## 🔥 Error

Missing attestation, no errors or warnings in beacon, slasher or validator found.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

Validator instance: `HEAD-daedb7`
Validator's beacon instance: `HEAD-daedb7`

Slasher and Slasher's Beacon instances:
* before update: `HEAD-daedb7`
* after update: `HEAD-016b95`

**Comment by stefa2k** [comment]
this could be a doublicate of #6673

**Comment by terencechain** [comment]
yep! duplicated
