### ISSUE TITLE
Malwarebytes blocks outbound communication

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6892]
Malwarebytes blocks **some** outbound communications. Windows defender might be doing the same without any notification. Potentially blocking some block proposals or attestations.

![image](https://user-images.githubusercontent.com/26490734/89449087-e35f7800-d758-11ea-868f-621d84a23a2e.png)

**Comment by prestonvanloon** [comment]
Related: https://github.com/prysmaticlabs/prysm/issues/5337

**Comment by shayzluf** [comment]
assigned @prestonvanloon as #5337

**Comment by rauljordan** [comment]
Closing in favor of #5337
