### ISSUE TITLE
Beacon node crashes with out of memory despite having 1GB+ free

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#6901]
# 🐞 Bug Report

### Description

Beacon crashes with out of memory after running fine for 8 hours with ~ 1GB free memory on the system.

### Has this worked before in a previous version?

Don't Know

## 🔬 Minimal Reproduction

No reproducer.

## 🔥 Error

See attached log
[out_of_memory.log](https://github.com/prysmaticlabs/prysm/files/5032755/out_of_memory.log)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian  10
Running prysm.sh via two systemd scripts
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.19
  </code>
</pre>

Running beacon and validator on a vm with 2 gb of Ram, eth1 node is on another vm.

**Anything else relevant (validator index / public key)?**

**Comment by Belkaar** [comment]
![image](https://user-images.githubusercontent.com/2395990/89494776-32d49100-d7b7-11ea-9330-f089bb126b3e.png)

**Comment by Belkaar** [comment]
![image](https://user-images.githubusercontent.com/2395990/89495220-1c7b0500-d7b8-11ea-89c3-cbd831b59be7.png)

**Comment by nisdas** [comment]
@terencechain What do you think of this ? its a pretty interesting error that came up when regenerating states. Seems related to #6104

**Comment by terencechain** [comment]
> @terencechain What do you think of this ? its a pretty interesting error that came up when regenerating states. Seems related to #6104

Also related to https://github.com/prysmaticlabs/prysm/issues/6658. All the blocks are full of deposits today. 1GB may not be enough

**Comment by nisdas** [comment]
Working on a solution now, will have it up for review in an hour or two. @terencechain

**Comment by nisdas** [comment]
Resolved by #6910
