### ISSUE TITLE
Have prysm.sh create symlinks to the latest executables

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#6902]
# 🚀 Feature Request

### Description

Updating to a new prysm version requires modifying systemd service files, since the executable filename changes.

### Describe the solution you'd like

For easier integration prysm.sh/prysm.bat could create a symlink to the latest version.
Example: "beacon-chain-linux-amd64" pointing to "beacon-chain-v1.0.0-alpha.19-linux-amd64" 

This would allow to manually trigger the update using the --download-only option without having to modify other files.

### Describe alternatives you've considered

Running prysm.sh as a service. But that updates on every restart, which is not always wanted and requires write permissions for the executables for the user running beacon or validator.

**Comment by prestonvanloon** [comment]
This is nice to have. Unfortunately, there isn't enough time to complete before the v1 mainnet cut off. Removing from the milestone.

**Comment by james-prysm** [comment]
Closing as going forward we would like less and less use of the Prysm scripts and instead coming to our github directly for upgrades. We'll try to have something improve the ux around this with something more resiliant than the .sh or .bat scripts. prysmctl already requires downloads.
