### ISSUE TITLE
Could not update validator protection error=unexpected EOF

### ISSUE THREAD

**Issue by 2naive** [prysmaticlabs/prysm#6905]
# 🐞 Bug Report

### Description

 After Validator is activated -> error repeats

## 🔬 Minimal Reproduction

Basic installation

## 🔥 Error

https://pastebin.com/raw/X4czUgvB

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-17134-Microsoft x86_64)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
validator-v1.0.0-alpha.18-linux-amd64
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by shayzluf** [comment]
```if featureconfig.Get().LocalProtection {
				if err := v.UpdateProtections(ctx, slot); err != nil {
					log.WithError(err).Error("Could not update validator protection")
					continue
				}
			}
```
seems like local protection issue assigning @0xKiwi

**Comment by nisdas** [comment]
Closing this as it has been brought up by @2naive offline that he is running a node in WSL and its an issue with an old version of WSL similar to #2543 rather than the validator's database.

**Comment by 2naive** [comment]
[Updating to WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2) solves the problem.
