### ISSUE TITLE
Implement AttestationSignedData Type

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#692]
As part of the attestation verification, the beacon node verifies the aggregated signature coming from attestation and compare its correctness using the group pubkey generated and the serialized form of AttestationSignedData as the message. The AttestationSignedData object is defined as the following:

```
{
    # Fork version
    'fork_version': 'uint64',
    # Slot number
    'slot': 'uint64',
    # Shard number
    'shard': 'uint16',
    # 31 parent hashes
    'parent_hashes': ['hash32'],
    # Shard block hash
    'shard_block_hash': 'hash32',
    # Slot of last justified beacon block referenced in the attestation
    'justified_slot': 'uint64'
}
```
This is currently blocked by #591 and #552  as we need SSZ to serialize AttestationSignedData and BLS to verify AttestationSignedData and aggregated public keys with aggregated signature

**Comment by rauljordan** [comment]
Closed by #1027
