### ISSUE TITLE
Strange warnings "Invalid attester slot"

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#6925]
# 🐞 Bug Report

### Description

Strange warnings "Invaldi attester slot" as validators transitioned from PENDING to ACTIVE

### Has this worked before in a previous version?

Don't know.

## 🔬 Minimal Reproduction

Don't know

## 🔥 Error

<pre><code>
Aug 07 15:12:56 eth2-test prysm.sh[599]: time="2020-08-07 15:12:56" level=warning msg="Invalid attester slot" duty=public_key:"\204B|3t\002,\245\327\2742\000K\004Q85\251{EW\305\2124\024:\211C=y\006H\312f\316\277p\301\361\212c\3
Aug 07 15:12:56 eth2-test prysm.sh[599]: time="2020-08-07 15:12:56" level=warning msg="Invalid attester slot" duty=public_key:"\213\253\361\336\327\350\001\260\303^\036=p\027iu\333\265\376\243F\366f\307\\3754=O\032\266\035\306
Aug 07 15:12:56 eth2-test prysm.sh[599]: time="2020-08-07 15:12:56" level=warning msg="Invalid attester slot" duty=public_key:"\207[\361\346\2022BZ\321dy\267<\312\032p\217=\000\362\300\245\207\322*J>\004\313\376\202\357\0275!b\2
Aug 07 15:12:56 eth2-test prysm.sh[599]: time="2020-08-07 15:12:56" level=warning msg="Invalid attester slot" duty=public_key:"\247C\247\031\341\343\211h\263\357wG\315\266\230:1\250\315\264\030\250I\202\022;F\360s\022\225\215?\3</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian 10
prsym.sh using systemd
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.19
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
We have very little information to investigate. Did this eventually get fixed? Did it get fixed if you restarted your validator?

**Comment by terencechain** [comment]
Closing due to lack of information. Please reopen once new info is provided
