### ISSUE TITLE
Validator balance decreases without any reason

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6926]
Validator 18279 https://beaconcha.in/validator/18279

Balance decreases from epoch 665 to epoch 666 even though the validator hasn't missed any attestations or block proposals. 

```
C:\Users\Inan>curl -X GET "https://api.prylabs.net/eth/v1alpha1/validators/balances?epoch=666&indices=18279" -H  "accept: application/json"
{
 "epoch": "666",
 "balances": [
  {
   "publicKey": "hGvWiV5ahdNHtyap3yOjLUhtcILMQNrDe24OpA1oEy5S+vPiENNVk1/SHOlYyJpz",
   "index": "18279",
   "balance": "32040282742"
  }
 ],
 "nextPageToken": "",
 "totalSize": 1
}

C:\Users\Inan>curl -X GET "https://api.prylabs.net/eth/v1alpha1/validators/balances?epoch=665&indices=18279" -H  "accept: application/json"
{
 "epoch": "665",
 "balances": [
  {
   "publicKey": "hGvWiV5ahdNHtyap3yOjLUhtcILMQNrDe24OpA1oEy5S+vPiENNVk1/SHOlYyJpz",
   "index": "18279",
   "balance": "32040289983"
  }
 ],
 "nextPageToken": "",
 "totalSize": 1
}
```

**Comment by djrtwo** [comment]
Is the attestation "correct"?

If you get more things wrong about it than correct (say, head and source incorrect, but target correct), then you can lose a small amount of eth even if your attestation gets on chain.
Note this is still better than if it didn't get there at all

**Comment by MysticRyuujin** [comment]
```
{"log":"time=\"2020-08-07 07:02:26\" level=info msg=\"Previous epoch voting summary\" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=665 inclusionDistance=1 inclusionSlot=21285 newBalance=32.040338983 oldBalance=32.040282742 percentChange=\"0.00018%\" percentChangeSinceStart=\"0.07159%\" prefix=validator pubKey=0x846bd6895e5a startBalance=32.017419255\n","stream":"stderr","time":"2020-08-07T12:02:26.2819552Z"}

...

{"log":"time=\"2020-08-07 07:08:50\" level=info msg=\"Previous epoch voting summary\" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=666 inclusionDistance=1 inclusionSlot=21285 newBalance=32.040340311 oldBalance=32.040282742 percentChange=\"0.00018%\" percentChangeSinceStart=\"0.07159%\" prefix=validator pubKey=0x846bd6895e5a startBalance=32.017419255\n","stream":"stderr","time":"2020-08-07T12:08:50.254629Z"}
```

**Comment by terencechain** [comment]
> Is the attestation 100% "correct"?
> 
> If you get more things wrong about it than correct (say, head and source incorrect, but target correct), then you can lose a small amount of eth even if your attestation gets on chain.
> Note this is still better than if it didn't get there at all

That's what i thought. I'm going to close this until there's further evidence that points out the attestation in epoch 665 is profitable

**Comment by MysticRyuujin** [comment]
You mean other than the logs I posted?

**Comment by terencechain** [comment]
> You mean other than the logs I posted? How does once acquire the necessary evidence?

Right. The log seemed to support the evidence and showed that 2 out of the 3 fields were voted incorrectly: 
`correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false`

For evidence, i meant the math supporting behind it. I can calculate it later to double verify the decrease

**Comment by MysticRyuujin** [comment]
I guess I don't understand the logs or the behavior then.

You left off the `epoch=664` part of that line entry.

So my balanced decreased in 665 because 664 was bad, but the alert I get is for 666?

**Comment by terencechain** [comment]
> so is there just a delay then?

That's correct. Attestation has one epoch to get included in the chain. At epoch 666, we process the attestations from epoch 664
