### ISSUE TITLE
Log Out Graffiti Whenever It Is Provided Through A Flag

### ISSUE THREAD

**Issue by DeMEdPit** [prysmaticlabs/prysm#6935]
Had a block proposed in which my graffiti was not present. Turns out I was just missing `\` on the password commend line (i.e.,`--passwords-dir=/eth2passwords`.) This is user Docker. See below.

**Wrong**

`docker run -it -v $HOME/Eth2Validators/prysm-wallet-v2:/wallet --network="host" \`
`  -v $HOME/Eth2Validators/prysm-wallet-v2-passwords:/eth2passwords \`
`  gcr.io/prysmaticlabs/prysm/validator:latest \`
`  --beacon-rpc-provider=127.0.0.1:4000 \`
`  --wallet-dir=/wallet \`
`  --passwords-dir=/eth2passwords `   **<---**
 ` --graffiti="your text here"`

**Correct** 

`docker run -it -v $HOME/Eth2Validators/prysm-wallet-v2:/wallet --network="host" \`
`  -v $HOME/Eth2Validators/prysm-wallet-v2-passwords:/eth2passwords \`
`  gcr.io/prysmaticlabs/prysm/validator:latest \`
`  --beacon-rpc-provider=127.0.0.1:4000 \`
`   --wallet-dir=/wallet \`
`  --passwords-dir=/eth2passwords \`   **<---**
`  --graffiti="your text here"`

**Comment by prestonvanloon** [comment]
Hi @DeMEdPit, was there a mistake in the documentation or some action we can take?

Thanks for the report!

**Comment by nisdas** [comment]
Hey @DeMEdPit brought this up to me offline, what happened was that he had forgotten to properly format his command, with a backslash before the newline. So his graffiti never made it into his proposed block, which instead was zeroed out. We should log out the graffiti it is provided to make validator operarators aware that it is functional and will be a part of a future proposed block.
