### ISSUE TITLE
Prysm not attesting

### ISSUE THREAD

**Issue by JanKalin** [prysmaticlabs/prysm#6943]
# 🐞 Bug Report

### Description

I went through the instructions at https://docs.prylabs.network/docs/install/windows/ and https://docs.prylabs.network/docs/install/win/activating-a-validator/.

 I am not aware of making any mistakes, but the validator is not attesting any blocks and the deposit is being slowly depleted, as seen on https://beaconscan.com/validator/0x99ee7b41aea767ad9114433f8f3d9d177a88577c96f0bc7d59712afb221323a6f31bb772a2d413b4cabbf9714d55e699

### Has this worked before in a previous version?

Do not know. The only prysm release since the validator got activated was v1.0.0-alpha19

## 🔬 Minimal Reproduction

`.\prysm.bat beacon-chain --log-file d:\usr\prysm\beacon.log` to run the beacon chain and
`.\prysm.bat validator --keystore-path=%LOCALAPPDATA%\.eth2validator --graffiti poap/L7u1FoSlhMKvTgXpozbW3T6BnEA --log-file d:\usr\prysm\validator.log
[versions.txt](https://github.com/prysmaticlabs/prysm/files/5047466/versions.txt)
` to run the validator

## 🔥 Error

[beacon.log](https://github.com/prysmaticlabs/prysm/files/5047462/beacon.log)
[validator.log](https://github.com/prysmaticlabs/prysm/files/5047463/validator.log)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Windows 10 Pro running on I7-8700 with 8GB memory
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    v1.0.0-alpha.19
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

```
quark % dir %LOCALAPPDATA%\.eth2validators

 Volume in drive C is sys            Serial number is 0271:E36B
 Directory of  C:\Users\jank\AppData\Local\.eth2validators\*

 8/05/2020   9:33a        <DIR>    .
 8/05/2020   9:33a        <DIR>    ..
 8/05/2020   9:33a            537  shardwithdrawalkeyad804a8e7991
 8/05/2020   9:33a            537  validatorprivatekey99ee7b41aea7
```

```
quark % dir /s C:\Users\jank\AppData\Roaming\Eth2

 Volume in drive C is sys            Serial number is 0271:E36B
 Directory of  C:\Users\jank\AppData\Roaming\Eth2\*

 8/05/2020   9:58a        <DIR>    .
 8/05/2020   9:58a        <DIR>    ..
 8/05/2020   9:13a        <DIR>    beaconchaindata
 8/05/2020   9:13a             10  metaData
 8/05/2020   9:13a             64  network-keys
 8/09/2020   1:49p         32,768  validator.db
         32,842 bytes in 3 files and 3 dirs    40,960 bytes allocated

 Directory of  C:\Users\jank\AppData\Roaming\Eth2\beaconchaindata\*

 8/05/2020   9:13a        <DIR>    .
 8/05/2020   9:13a        <DIR>    ..
 8/09/2020   2:10p    536,870,912  beaconchain.db
    536,870,912 bytes in 1 file and 2 dirs    536,870,912 bytes allocated

    Total for:  C:\Users\jank\AppData\Roaming\Eth2\beaconchaindata\*
    536,870,912 bytes in 1 file and 2 dirs    536,870,912 bytes allocated

    Total for:  C:\Users\jank\AppData\Roaming\Eth2\*
    536,903,754 bytes in 4 files and 5 dirs    536,911,872 bytes allocated
```

```
quark % dir /s  C:\Users\jank\AppData\Roaming\Eth2Validators

 Volume in drive C is sys            Serial number is 0271:E36B
 Directory of  C:\Users\jank\AppData\Roaming\Eth2Validators\*

 8/05/2020   9:57a        <DIR>    .
 8/05/2020   9:57a        <DIR>    ..
 8/05/2020   9:57a        <DIR>    prysm-wallet-v2
              0 bytes in 0 files and 3 dirs

 Directory of  C:\Users\jank\AppData\Roaming\Eth2Validators\prysm-wallet-v2\*

 8/05/2020   9:57a        <DIR>    .
 8/05/2020   9:57a        <DIR>    ..
 8/09/2020   2:09p        <DIR>    derived
              0 bytes in 0 files and 3 dirs

 Directory of  C:\Users\jank\AppData\Roaming\Eth2Validators\prysm-wallet-v2\derived\*

 8/09/2020   2:09p        <DIR>    .
 8/09/2020   2:09p        <DIR>    ..
 8/05/2020   9:57a            137  keymanageropts.json
 8/05/2020   9:57a            741  seed.encrypted.json
            878 bytes in 2 files and 2 dirs    8,192 bytes allocated

    Total for:  C:\Users\jank\AppData\Roaming\Eth2Validators\prysm-wallet-v2\derived\*
            878 bytes in 2 files and 2 dirs    8,192 bytes allocated

    Total for:  C:\Users\jank\AppData\Roaming\Eth2Validators\prysm-wallet-v2\*
            878 bytes in 2 files and 5 dirs    8,192 bytes allocated

    Total for:  C:\Users\jank\AppData\Roaming\Eth2Validators\*
            878 bytes in 2 files and 8 dirs    8,192 bytes allocated
```

**Comment by terencechain** [comment]
I checked the `validator.log`, the validator client did not point to any key store keys. See error:
```
[2020-08-07 09:57:22]  WARN node: No keys found; nothing to validate
```

This is a user error. Can you please verify that path `--keystore-path=%LOCALAPPDATA%\.eth2validator` is correct?

**Comment by JanKalin** [comment]
Oh c**p. In the batch file I had `--keystore-path=%LOCALAPPDATA%\.eth2validator` instead of '--keystore-path=%LOCALAPPDATA%\.eth2validator`...

Sorry for bother...

**Comment by terencechain** [comment]
> Oh c**p. In the batch file I had `--keystore-path=%LOCALAPPDATA%\.eth2validator` instead of '--keystore-path=%LOCALAPPDATA%.eth2validators`...
> 
> Sorry for bother...

No worries! Glad we were able to figure this out : )
