### ISSUE TITLE
Refactor Find Peers With Subnet Method

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#6950]
# 💎 Issue

### Background

In the course of working on #6893, it came to attention that the `FindPeersWithSubnet` method was problematic and could lead to very high CPU usage. On initial benchmarks, running the method concurrently in 100 separate go-routines increased the runtime of each call linearly based on the number of go-routines running. This would indicate each network lookup was bounded by a global lock. 

### Description

Having a global lock for network lookups makes using this method inefficient as we might use this method when searching for subnets for many attesters. This would lead the method to take some very long times. Ex: 100 seconds, etc. The goal of the issue would be to implement a more efficient method for searching for peers of a particular subnet. Currently we simply perform a global network search and try to filter their enrs out. 

A potential solution would be a background routine which would look through the network asynchronously and try to filter out peers with the desired subnets. This maybe a better way to find peers then spamming network searches which yield limited results.

**Comment by rauljordan** [comment]
@nisdas is this still relevant or have there been significant improvements to this code? I recall this part of the codebase has changed a bit since the Medalla incident

**Comment by shayzluf** [comment]
@nisdas any update on this issue?

**Comment by rauljordan** [comment]
@nisdas is this something we'll ever get to or are we ok to close?

**Comment by nisdas** [comment]
This has actually already been done here #8048. Closing this now
