### ISSUE TITLE
Beacon, Validator, Slasher logs not going to the default log files after logrotate

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#6957]
# 🐞 Bug Report

### Description

 Beacon, Validator, Slasher logs not going to the default log files after logrotate. New logs are going to the newly rotated log. Since log rotate won't rotate empty logs, the log files are inflating. Restarting Beacon, Validator, Slasher would help to write to default log files. It would be nice to not restart these processes.

### Has this worked before in a previous version?

 Not sure. Assuming it's not working ever.

## 🔬 Minimal Reproduction

Steps to reproduce:

1. Setup beacon with "log-file: /home/ethereum/logs/beacon.log" (same for validator, and slasher)
2. Setup a new logrotate config file: /etc/logrotate.d/prysm-logs as follow:
/home/ethereum/logs/*.log 
{
    rotate 7
    daily
    missingok
    notifempty
    delaycompress
    compress
    postrotate
        systemctl reload prysm-logs
    endscript
}

## 🔥 Error

Observe:
1. Log got rotated from /home/ethereum/logs/beacon.log to /home/ethereum/logs/beacon.log.1
2. New logs are going to /home/ethereum/logs/beacon.log.1

-rw-rw-r--  1 ethereum ethereum        0 Aug  8 00:00 beacon.log
-rw-rw-r--  1 ethereum ethereum 18743512 Aug 10 23:26 beacon.log.1
-rw-rw-r--  1 ethereum ethereum        0 Aug  8 00:00 slasher.log
-rw-rw-r--  1 ethereum ethereum 12541561 Aug 10 23:26 slasher.log.1
-rw-rw-r--  1 ethereum ethereum        0 Aug  8 00:00 validator.log
-rw-rw-r--  1 ethereum ethereum 35626932 Aug 10 23:26 validator.log.1

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu latest on ARM64 (Pi 4 8GB)

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
alpha.19

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
No.

**Comment by raphpa** [comment]
That is an expected behaviour of logrotate. You would need an option to signal the processes to write to the new file (like HUP).

You can try using the `copytruncate` option of logrotate, which will copy the log to the new file and then truncate the current log to empty it.

**Comment by xuyenvuong** [comment]
@raphpa - I tried `copytruncate` option, but same behavior. I will look into HUP.

**Comment by xuyenvuong** [comment]
After moving `copytruncate` to the very top of the list, the logrotate seems to work fine. Closing this ticket.

`/home/ethereum/logs/*.log 
{
    rotate 7
    daily
    copytruncate
    missingok
    notifempty
    delaycompress
    compress
    postrotate
        systemctl reload prysm-logs
    endscript
}`
