### ISSUE TITLE
Travis Failing When Installing Bazel-Related Dependencies

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#697]
Currently, our BLS integration into Prysm uses Bazel to provide the required C library dependencies into cgo. That is, we import a c library provided by bazel using:

```c
#include "external/herumi_mcl/include/mcl/bn.h"
```

Bazel tests work fine as well as our build on Buildkite. However, travis will always fail as it does not use Bazel but instead uses the regular go tools. During the install steps of travis, it attempts to install all packages, which will throw an error code and crash as it cannot find the bn.h package contained within external. We do not want to check in the library as that would defeat the purposes of using Bazel.

A potential fix to this would be to migrate everything including lint to Bazel. As of now, we are keeping all BLS related PRs within the `bls` branch of Prysm to not crash master due to failing travis.

**Comment by terenc3t** [comment]
Here is the branch:
https://github.com/prysmaticlabs/prysm/tree/bls

**Comment by rauljordan** [comment]
This is no longer needed as we have moved bls to its separate repo [go-bls](https://github.com/prysmaticlabs/go-bls)
