### ISSUE TITLE
"accounts-v2 list --show-deposit-data" does not work for multiple accounts in combination with different creation methods

### ISSUE THREAD

**Issue by mondsen** [prysmaticlabs/prysm#6977]
# 🐞 Bug Report

### Description

 It is not possible to display all deposit data of the validator accounts when using the command
accounts-v2 list **--show-deposit-data**

Important information: the first validator account (account 0) was created using Medalla launchpad process. Account 1 and 2 were created using `accounts-v2 create` command.

Console output:
```
./prysm.sh validator accounts-v2 list --show-deposit-data
Latest Prysm version is v1.0.0-alpha.20.
Validator is up to date.
Verifying binary integrity.
validator-v1.0.0-alpha.20-linux-amd64: OK
gpg: Signature made Mi 12 Aug 2020 02:36:58 CEST
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /home/mond/prysm/dist/validator-v1.0.0-alpha.20-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm validator accounts-v2 list --show-deposit-data
[2020-08-12 21:30:57]  INFO accounts-v2: (wallet path) /home/mond/.eth2validators/prysm-wallet-v2
[2020-08-12 21:30:57]  INFO accounts-v2: (wallet directory) /home/mond/.eth2validators/prysm-wallet-v2
Wallet password: 
(keymanager kind) non-HD wallet

Showing 3 validator accounts
View the eth1 deposit transaction data for your accounts by running `validator accounts-v2 list --show-deposit-data

Account 0 | brightly-endless-slug
[validating public key] 0xa1bdf045b46938d7dd88b795740c78f23bc144f0a63fe5aa2293246df48edf53fac284728e3b432d4156bdf28cd5bfd0
If you imported your account coming from the eth2 launchpad, you will find your deposit_data.json in the eth2.0-deposit-cli's validator_keys folder


Account 1 | poorly-notable-pup
[validating public key] 0xa0c8691e3dd96a424f73574948436581e904165ef1483b2324bd4f4fe9942a0f98b5097914c1c48fe4201d26255e22d9
If you imported your account coming from the eth2 launchpad, you will find your deposit_data.json in the eth2.0-deposit-cli's validator_keys folder


Account 2 | fairly-easy-boa
[validating public key] 0xb1e61a763f9708b7fea373a9eace6d81f0403c3cfa0be137596e142467a3c6757f1782deb56000b1ef8c5b2cf320bd60
If you imported your account coming from the eth2 launchpad, you will find your deposit_data.json in the eth2.0-deposit-cli's validator_keys folder
```

### Has this worked before in a previous version?

 Don't know. Was first observed in alpha20

## 🔬 Minimal Reproduction

1. Run medalla launchpad process and import account/wallet with keys using the JSON files
2. Create new validator account using `accounts-v2 create` 
2b. (I only tested the output of --show-deposit-data after having three accounts, so maybe one account is not sufficient). Repeat step 2 - optional
3. run validator accounts-v2 list --show-deposit-data

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 x64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.20
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
Now we only allow HD wallets to display deposit data, so we will no longer have non-HD wallets with mixed deposit data + no deposit data available
