### ISSUE TITLE
Random "Slasher is not ready" errors on validator start

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#6988]
# 🐞 Bug Report

### Description

Validator fails to connect to slasher with the following error:
```
level=warning msg="Enabled validator attestation and block slashing protection using an external slasher." prefix=flags
level=fatal msg="Slasher is not ready: could not setup slasher protection client: can`t connect to slasher server at: prysm-slasher.chain.svc.cluster.local
:4002" prefix=validator
```
The slasher is running with no errors and constantly reports new attestations, blocks. It can successfully connect to the beacon node. Only after 7 connection trials (in average) validator stops throwing a fatal error above.

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was `1.0.0-alpha.17`

## 🔬 Minimal Reproduction

Start validator with `--enable-external-slasher-protection`, `--slasher-rpc-provider` flags provided.

Current version: `1.0.0-alpha.20`

**Comment by rauljordan** [comment]
@shayzluf

**Comment by shayzluf** [comment]
@rauljordan thanks, will look into it
