### ISSUE TITLE
Same command on Terminal works, but doesn't on Powershell

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#6989]
` C:\prysm\prysm.bat validator --wallet-dir=C:\prysm\wallet1 --datadir=C:\prysm --graffiti="beaconcha.in<3"`

![cmd_2020-08-13_18-59-24](https://user-images.githubusercontent.com/26490734/90164091-3e1b5400-dd97-11ea-91f4-e2f4c6f43e67.png)

**Comment by Shammah** [comment]
I've made a PR that specifically adds a PowerShell version of the `prysm.bat` script, but it has yet to be merged. Could you try it and out and see if it fixes your issue?

https://github.com/prysmaticlabs/prysm/pull/6829

**Comment by rauljordan** [comment]
Duplicate of #6828
