### ISSUE TITLE
Verify proposer attestation from last slot, not current slot

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#699]
**Background on verifying proposer attestation:**

1. One of the pre-condition for block processing is the block must come with attestation from the proposer of the block, the attestation must be included along with the block in the network message object. Otherwise, the client should reject the block
2. During block processing, for the current block to be valid it must include an attestation of the parent block from the proposer of the parent block, that attestation is in the first index
3. If you are a proposer of the current block, you must include the parent block's attestation in the first index

I don't think this is correct, we should get the parent block's proposer index and use that to verify `CheckBit`
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/block.go#L179-L190

**Comment by rawfalafel** [comment]
sounds right. nice catch!
