### ISSUE TITLE
interop mode does not use the interop genesis time

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#7014]
It appears that interop mode is no longer working as intended.  When starting up an interop node with the following command:

```
bazel run //beacon-chain:beacon-chain -- --force-clear-db --interop-num-validators=128 --datadir=/home/jgm/.eth2-interop --deposit-contract=0x6d22BA5f4eF18c119F7b09192453F417b4a33b0e --bootstrap-node= --no-discovery --interop-eth1data-votes --http-web3provider=http://localhost:8545/
```

the beacon node attempts to find peers to sync with, rather than starting the chain fresh as would be expected:

```
...
[2020-08-16 18:16:43]  WARN interop-cold-start: Saving generated genesis state in database for interop testing
[2020-08-16 18:16:43]  INFO slotutil: Chain genesis time reached genesisTime=2020-08-16 18:16:43 +0100 BST genesisValidators=128
...
[2020-08-16 18:16:43]  INFO blockchain: Blockchain data already exists in DB, initializing...
[2020-08-16 18:16:43]  INFO initial-sync: Starting initial chain sync...
[2020-08-16 18:16:43]  INFO initial-sync: Waiting for enough suitable peers before syncing required=3 suitable=0
[2020-08-16 18:16:43]  INFO slotutil: Chain genesis time reached genesisTime=2020-08-04 14:00:08 +0100 BST genesisValidators=128
...
```

The key point being that chain genesis time is initially at the correct time for interop (_i.e._ now), but reverts to that for the default configuration.

As a speculative fix, I added a line to `registerInteropServices()` after the call to `interopcoldstart.NewColdStartService()` as follows:

```
params.BeaconConfig().GenesisTime = genesisTime
```

which has the desired effect of overriding the genesis time with the interop value (and works  if `--interop-genesis-time` is supplied or not), but I'm no longer up-to-date enough with the codebase to know if there is a better way to fix the issue.

**Comment by 0xKiwi** [comment]
Hello @mcdee , Interop isn't a feature we're actively maintaining at the moment. @nisdas what do you think we should do about this?

**Comment by sinkingsugar** [comment]
This is a bit of a shame.. 
I was trying to make an automated multi-net test here, but prysm is not cooperating.. no wonders after reading this issue.
https://github.com/sinkingsugar/multinet
My rationale was the immense need to test gossip 1.1 behemoth interaction between clients.

**Comment by nisdas** [comment]
Hey @mcdee @sinkingsugar , i will fix this by today.

**Comment by sinkingsugar** [comment]
very nice thanks @nisdas !

**Comment by sinkingsugar** [comment]
by the way I didn't have exactly this issue as I was generating mock data in nimbus and passed this:
```
bazel run //beacon-chain -- \
  $BOOTNODES_ARG \
  --disable-discv5 \
  --force-clear-db \
  --datadir /tmp/beacon-prysm \
  --pprof \
  --verbosity debug \
  --interop-eth1data-votes \
  --chain-config-file $TESTNET_DIR/config.yaml \
  --contract-deployment-block 0 \
  --deposit-contract 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4 \ 
  --interop-genesis-state $TESTNET_DIR/genesis.ssz #&
```

It launched kind of ok but didn't do anything (no debug logs, didn't try to connect to bootstrap either)

**Comment by nisdas** [comment]
@sinkingsugar if you do want to run using the bootnodes you need to do 
```
--bootstrap-node=enr:-.....
```
with the argument being comma separated if you are providing multiple bootnodes. Also if you want to run the bootnodes you will need to remove this flag: `--disable-discv5` . That disables all discovery, so explains why your node does nothing.

**Comment by sinkingsugar** [comment]
I ran this:
```
prysm_1       | INFO: Running command line: bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain '--bootstrap-node=enr:-LK4QD6qbOduopg1Ccwm54WqwuibWXETCAbjp_KbkjVQ3NlvYuQkUl93l1V9bi_fKy8hJHHpB9NuzZY2Fqr9j2qy-qYBh2F0dG5ldHOI__________-EZXRoMpDhyRkeAAAAAP__________gmlkgnY0gmlwhKwUAAqJc2VjcDI1NmsxoQPo9xeq73VJWykX04FfKTx4HdDhrtgihvvPTz9QU1wPR4N0Y3CCw1CDdWRwgsNQ' --force-clear-db --datadir /tmp/beacon-prysm --pprof --verbosity debug --interop-eth1data-votes --chain-config-file /root/multinet/repo/data/testnet/config.yaml --contract-deployment-block 0 --deposit-contract 0x0000000000000000000000000000000000000000 ' '
```

Contract at 0x0 or mock address didn't make a difference

Full log here if you have a minute to check
https://gist.github.com/sinkingsugar/5ffe67a567358774609872770b6fa8f6

**Comment by sinkingsugar** [comment]
I just noticed a issue while pasting this.. there is no genesis state for some reason.. I will double check

**Comment by sinkingsugar** [comment]
Fixed command line:
```
prysm_1       | + bazel run //beacon-chain -- --bootstrap-node=enr:-LK4QJBpntKtkREBwfnJiamEMPrVqMaAk2tc4bKg-biVdXULPTVW4tVmi9hHGuQLDtlB9UWbkGsaydlWKjWsffQ5pqoBh2F0dG5ldHOI__________-EZXRoMpD-aTziAAAAAP__________gmlkgnY0gmlwhKwUAAqJc2VjcDI1NmsxoQPo9xeq73VJWykX04FfKTx4HdDhrtgihvvPTz9QU1wPR4N0Y3CCw1CDdWRwgsNQ --force-clear-db --datadir /tmp/beacon-prysm --pprof --verbosity debug --interop-eth1data-votes --chain-config-file /root/multinet/repo/data/testnet/config.yaml --contract-deployment-block 0 --deposit-contract 0x0000000000000000000000000000000000000000 --interop-genesis-state /root/multinet/repo/data/testnet/genesis.ssz
```

And log:
https://gist.github.com/sinkingsugar/5ffe67a567358774609872770b6fa8f6

**Comment by nisdas** [comment]
can you try with these two flags ?
```
 --deposit-contract=0x8A04d14125D0FDCDc742F4A05C051De07232EDa4 --verbosity=debug
```
you need a contract with the deposit and it looks like there are peering issues.

**Comment by nisdas** [comment]
also can you try it with #7106 ? this might solve the issues you are seeing.

**Comment by sinkingsugar** [comment]
I was just trying with the above flags before yes, I will try #7106

**Comment by sinkingsugar** [comment]
Didn't change much,
Updated the log:
https://gist.github.com/sinkingsugar/5ffe67a567358774609872770b6fa8f6

**Comment by nisdas** [comment]
do you mind running it with `--verbosity=trace` and pasting the logs here. That should help us more

**Comment by sinkingsugar** [comment]
[multinet.log](https://github.com/prysmaticlabs/prysm/files/5121646/multinet.log)


```
[34mprysm_1       |[0m [36mDEBUG[0m[08-25|06:12:38.174] Bad discv5 packet                        [36mid[0m=2481b0691c3961ef [36maddr[0m=172.20.0.10:50000 [36merr[0m="rlp: too few elements for discover.authHeaderList"
```
might be a issue I guess...?

**Comment by nisdas** [comment]
no worries, I think the main issue is this one
```
[34mprysm_1       |[0m time="2020-08-25 06:12:36" level=trace msg="Could not connect with peer {16Uiu2HAmULPTzyRTVh6zoW9KZ3zEYow1nfHMiZX6prihTudv2tKG: [/ip4/172.20.0.10/tcp/50000]}" error="failed to dial 16Uiu2HAmULPTzyRTVh6zoW9KZ3zEYow1nfHMiZX6prihTudv2tKG: all dials failed
[34mprysm_1       |[0m   * [/ip4/172.20.0.10/tcp/50000] failed to negotiate security protocol: peer id mismatch: expected
```

It seems like the node has a different peer id than expected.

**Comment by sinkingsugar** [comment]
Ah
```
got error on dial: failed to negotiate security protocol: peer id mismatch: expected 16Uiu2HAmULPTzyRTVh6zoW9KZ3zEYow1nfHMiZX6prihTudv2tKG, but remote key matches 16Uiu2HAmFoKBrhv5f3xF5V4LH91d4qLuJ89SJs5kyCA7ZUgDAVrM
```
I guess that's it

**Comment by sinkingsugar** [comment]
Any idea what is the `Bad discv5 packet` issue btw? we might wanna fix this too

**Comment by nisdas** [comment]
That might be related to the first error, it comes up if the node is communicating with a node which is misconfigured. Ex: Enr specifies a pubkey X but the peer instead communicates with a pubkey Y. The other peer might be misconfigured.
