### ISSUE TITLE
Slasher: "cound not update spans"

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#7030]
# 🐞 Bug Report

### Description

Slasher is having lots of errors

### Has this worked before in a previous version?

yes

## 🔥 Error

See slasher log:

[slasher span errors.txt](https://github.com/prysmaticlabs/prysm/files/5083150/slasher.span.errors.txt)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

https://github.com/stefa2k/prysm-docker-compose with docker tag `:v1.0.0-alpha.22`

**Comment by tsudmi** [comment]
Also experiencing that issue with external slashing protection enabled.
The validator outputs the following:
```
level=error msg="External slashing attestation protection returned an error: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error msg="Failed post attestation signing updates" error="external slasher service detected a submitted slashable attestation" prefix=validator pubKey=0x8896244f256b slot=98717 sourceEpoch=2290 targetEpoch=3084
```
Validator version: `HEAD-27c840`

**Comment by shayzluf** [comment]
@tsudmi running #7043 with --spans-cache-size=2000 should resolve this issue
