### ISSUE TITLE
Prysm sync on attacknet stuck

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#7033]
# 🐞 Bug Report

### Description

Prysm cannot sync to actual head in attacknet, after turning off Teku, and only syncing from lighthouse nodes.

### Has this worked before in a previous version?

Yes?

## 🔬 Minimal Reproduction

Start a Prysm node on the multi-client attacknet, it does not sync past slot 91615, while the lighthouse nodes are at 111000+.

## 🔥 Error

https://gist.github.com/protolambda/b8ebfd5530521008ead8273388010056

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu, running docker
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

Prysm/v1.0.0-alpha.21/f193dc2f54a84ee63b014a1f3ce33c53f29f4aaf. Built at: 2020-08-17 08:49:31+00:00

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
-

**Comment by protolambda** [comment]
After also turning off all but 1 prysm node, and thus exclusively syncing from healthy lighthouse nodes, it still does not work.

**Comment by djrtwo** [comment]
I'm pretty sure many users are seeing this on Medalla as well

**Comment by hwwhww** [comment]
Not relevant to this issue, I think the `v1.0.0-alpha.21` is the buggy release. Maybe consider updating to `v1.0.0-alpha.22`.

**Comment by farazdagi** [comment]
Yep, alpha.22 also has some code that allows init-sync not to exit too early.

**Comment by djrtwo** [comment]
It's `alpha.22` @hwwhww

**Comment by nisdas** [comment]
Hey guys @farazdagi is handling this in #7032. That should fix your issue, @protolambda can you try it out and confirm for the attacknets?

**Comment by protolambda** [comment]
The version numbers in docker releases are bugged I think (cc @prestonvanloon is aware of it, had an issue with it earlier as well). Please just focus on the commit hash, which is only 5 hours old right now. f193dc2f54a84ee63b014a1f3ce33c53f29f4aaf

@nisdas sure, I'll try that

**Comment by rauljordan** [comment]
Resolved by @nisdas here https://discordapp.com/channels/476244492043812875/619926417970429962/745644701193076817
