### ISSUE TITLE
"wallet-v2 recover" output not recognised by validator

### ISSUE THREAD

**Issue by mattcee233** [prysmaticlabs/prysm#7049]
# 🐞 Bug Report

### Has this worked before in a previous version? 

Unknown, I'm new but assume so based on the number of tutorials saying to use recover to import wallets

 

## 🔬 Minimal Reproduction 

use wallet-v2 recover to recover a wallet from passphrase then try to start validator using output wallet directory

## 🔥 Error

<pre><code>
No error message, but when starting validator having used recover to create wallet am asked for "New Wallet Password" rather than to just enter "Wallet Password" as expected

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Win10 x64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-alpha.23
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by mattcee233** [comment]
To clarify, if you are unable to reproduce this may well be user error - I was able to get everything running fine by using wallet-v2 import instead

**Comment by 0xKiwi** [comment]
Hello @mattcee233! Thank you for reporting! #7038 solves this issue, please try it again once it merges.
