### ISSUE TITLE
gRPC panicked! error=runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RoBiK75** [prysmaticlabs/prysm#7050]
# 🐞 Bug Report

### Description

The beacon node has been running for some time and then started to produce error messages repeating each 12 second. See bellow for the error message and stacktrace.

### Has this worked before in a previous version?

not sure

## 🔬 Minimal Reproduction

i don't know how to reproduce it

## 🔥 Error

<pre><code>
ERROR gRPC panicked! error=runtime error: invalid memory address or nil pointer dereference stack=goroutine 5172485 [running]:
runtime/debug.Stack(0xc0000fc000, 0x5e0287, 0x5)
        GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x9e67c0, 0xc0427ae570, 0x3b4e40, 0x26bf590, 0xc07e639150, 0xc0613cea80)
        shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x9e67c0, 0xc0427ae570, 0x3b4e40, 0x26bf590, 0x7b2630, 0x20, 0x5)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x9e67c0, 0xc0427ae570, 0xc0001268d0, 0xc0007bfab0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x77
panic(0x3b4e40, 0x26bf590)
        GOROOT/src/runtime/panic.go:969 +0x166
github.com/prysmaticlabs/prysm/beacon-chain/rpc/node.(*Server).ListPeers(0xc0087b3420, 0x9e67c0, 0xc0427ae600, 0xc02467c840, 0xc0087b3420, 0xc0000ca9c0, 0x7b3db8)
        beacon-chain/rpc/node/server.go:193 +0x325
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler.func1(0x9e67c0, 0xc0427ae600, 0x56c8a0, 0xc02467c840, 0x3b30a0, 0x2850868, 0x535ae0, 0x2850320)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:868 +0x86
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc0000ca780, 0x9e67c0, 0xc0427ae600, 0x56c8a0, 0xc02467c840, 0xc02467c860, 0xc02467c880, 0xc0427ae600, 0x9ffe00, 0x2850320, ...)
        beacon-chain/rpc/service.go:400 +0x77
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e67c0, 0xc0427ae600, 0x56c8a0, 0xc02467c840, 0x615d34, 0x25, 0x9e67c0, 0xc0427ae600)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0xc02467c860, 0xc02467c8a0, 0x3, 0x3, 0x9f25a0, 0xc0493771a0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0x165
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0x25, 0xc0198e5090, 0xc02eeba6c0, 0x7f8244177101)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0xc02467c860, 0xc02467c8c0, 0xc0427ae4b0, 0xc023012a68, 0x15d9a96, 0xc02467c900)
        external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0x20, 0xc02467c900, 0x203009, 0x203009)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0xc02467c860, 0xc02467c8e0, 0x0, 0x0, 0x0, 0x0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:31 +0xbc
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0xc05d22c600, 0xc02467c800, 0xc023012b30, 0x15da308)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x9e67c0, 0xc0427ae570, 0x56c8a0, 0xc02467c840, 0xc02467c860, 0xc02467c880, 0xc023012ba0, 0x16fac08, 0x4ccf20, 0xc0427ae570)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xd5
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler(0x49e340, 0xc0087b3420, 0x9e67c0, 0xc0427ae570, 0xc0529f51a0, 0xc0087d8c60, 0x9e67c0, 0xc0427ae570, 0x0, 0x0)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:870 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006f0d00, 0x9fa100, 0xc020d36480, 0xc05d22c600, 0xc0087d8f90, 0x26d6ff0, 0x0, 0x0, 0x0)
        external/org_golang_google_grpc/server.go:1082 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0006f0d00, 0x9fa100, 0xc020d36480, 0xc05d22c600, 0x0)
        external/org_golang_google_grpc/server.go:1405 +0xccb
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00c25cb10, 0xc0006f0d00, 0x9fa100, 0xc020d36480, 0xc05d22c600)
        external/org_golang_google_grpc/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        external/org_golang_google_grpc/server.go:744 +0xa1
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distribution:      Clear Linux OS
Installed version: 33620

Docker version 19.03.8, build afacb8b7f0d8d4f9d2a8e8736e9c993e672b41f3
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain:v1.0.0-alpha.23
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by j1v** [comment]
I possibly observe the same or similar bug. Found it after eth2stats started crashing repeatedly. 

Node is running great and returning all other kind of gRPC request, except /eth/v1alpha1/node/peers

```
curl -s -X GET "http://localhost:3500/eth/v1alpha1/node/peers" -H "accept: application/json"
{
"error":"runtime error: invalid memory address or nil pointer dereference",
"code":2,
"message":"runtime error: invalid memory address or nil pointer dereference",
"details":[]
}
```

and at the same time in the node : 

```
[2020-08-19 16:17:40] ERROR gRPC panicked! error=runtime error: invalid memory address or nil pointer dereference stack=goroutine 111056304 [running]:
runtime/debug.Stack(0xc00019c000, 0x18911a7, 0x5)
        GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1c976e0, 0xc07fa94150, 0x1665d60, 0x2875590, 0xc0b58e66c0, 0xc01f75f300)
        shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1c976e0, 0xc07fa94150, 0x1665d60, 0x2875590, 0x1a63550, 0x20, 0x5)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x1c976e0, 0xc07fa94150, 0xc000b20050, 0xc000641ab0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x77
panic(0x1665d60, 0x2875590)
        GOROOT/src/runtime/panic.go:969 +0x166
github.com/prysmaticlabs/prysm/beacon-chain/rpc/node.(*Server).ListPeers(0xc0062962a0, 0x1c976e0, 0xc07fa941e0, 0xc0338c9ce0, 0xc0062962a0, 0xc000576740, 0x1a64cd8)
        beacon-chain/rpc/node/server.go:193 +0x325
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler.func1(0x1c976e0, 0xc07fa941e0, 0x181d7c0, 0xc0338c9ce0, 0x1663fc0, 0x2a05d28, 0x17e6a00, 0x2a057e0)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:868 +0x86
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc000576500, 0x1c976e0, 0xc07fa941e0, 0x181d7c0, 0xc0338c9ce0, 0xc0338c9d00, 0xc0338c9d20, 0xc07fa941e0, 0x1cb0d20, 0x2a057e0, ...)
        beacon-chain/rpc/service.go:400 +0x77
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1c976e0, 0xc07fa941e0, 0x181d7c0, 0xc0338c9ce0, 0x18c6c54, 0x25, 0x1c976e0, 0xc07fa941e0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0xc0338c9d00, 0xc0338c9d40, 0x3, 0x3, 0x1ca34c0, 0xc0064a0600)
        external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0x165
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0x25, 0xc076c290e0, 0xc0209af700, 0x7f57f7889701)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0xc0338c9d00, 0xc0338c9d60, 0xc07fa94060, 0xc082293a68, 0x42e1a6, 0xc0338c9da0)
        external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0x20, 0xc0338c9da0, 0x20300c, 0x20300c)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0xc0338c9d00, 0xc0338c9d80, 0x0, 0x0, 0x0, 0x0)
        external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:31 +0xbc
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0xc01f3e6600, 0xc0338c9c80, 0xc082293b30, 0x42ea18)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x1c976e0, 0xc07fa94150, 0x181d7c0, 0xc0338c9ce0, 0xc0338c9d00, 0xc0338c9d20, 0xc082293ba0, 0x54f318, 0x177de40, 0xc07fa94150)
        external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xd5
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler(0x174f260, 0xc0062962a0, 0x1c976e0, 0xc07fa94150, 0xc02d77f500, 0xc00059be30, 0x1c976e0, 0xc07fa94150, 0x0, 0x0)
        bazel-out/k8-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:870 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0062aa000, 0x1cab020, 0xc002864c00, 0xc01f3e6600, 0xc0062a8180, 0x288cff0, 0x0, 0x0, 0x0)
        external/org_golang_google_grpc/server.go:1082 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0062aa000, 0x1cab020, 0xc002864c00, 0xc01f3e6600, 0x0)
        external/org_golang_google_grpc/server.go:1405 +0xccb
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000552630, 0xc0062aa000, 0x1cab020, 0xc002864c00, 0xc01f3e6600)
        external/org_golang_google_grpc/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        external/org_golang_google_grpc/server.go:744 +0xa1
```

The node is running 700+ peers

**Comment by 0xKiwi** [comment]
Thank you for reporting! @prestonvanloon do you know what the source could be for this bug?

**Comment by SeaMonkey82** [comment]
Just posting to say that I'm seeing this in alpha.24 as well.

**Comment by rauljordan** [comment]
Solved https://github.com/prysmaticlabs/prysm/pull/7612
