### ISSUE TITLE
Resyncing from scratch on Medalla: log warnings and errors for "ssz_snappy"

### ISSUE THREAD

**Issue by hannesrohde** [prysmaticlabs/prysm#7056]
# 🐞 Bug Report

### Description

I've removed all previous data in an attempt to re-sync Medalla from scratch.

After restarting the beacon-chain with an empty data dir using the latest docker image I observed sporadic warnings and errors in the logs, though sync seems to continue.

## 🔬 Minimal Reproduction

I am running the beacon chain in docker on Ubuntu using the following command with an empty $HOME/eth2 directory:

````
docker run -d --restart always \
        -v $HOME/eth2:/data -p 4000:4000 -p 12000:12000/udp -p 13000:13000 --name beacon-chain \
        gcr.io/prysmaticlabs/prysm/beacon-chain:latest \
        --datadir=/data \
        --p2p-host-ip=xx.xx.xx.xx \
        --rpc-host=0.0.0.0 \
        --monitoring-host=0.0.0.0
````

## 🔥 Error

<pre><code>
time="2020-08-19 16:49:30" level=info msg="Processing block 0x935bf68a... 3776/109146 - estimated time remaining 15h49m16s" blocksPerSecond=1.9 peers=30 prefix=initial-sync
time="2020-08-19 16:49:33" level=warning msg="Failed to decode stream message" error="i/o deadline exceeded" peer=16Uiu2HAm4sDtVcECLPgmNwSz2chpGiLvSirsY9z64NDbKNtWobvt prefix=sync topic="/eth2/beacon_chain/req/ping/1/ssz_snappy"
time="2020-08-19 16:49:44" level=info msg="Processing block 0x51c75628... 3808/109148 - estimated time remaining 20h54m2s" blocksPerSecond=1.4 peers=30 prefix=initial-sync
...
time="2020-08-19 17:15:41" level=info msg="Processing block 0xc3a997fa... 8320/109277 - estimated time remaining 14h1m18s" blocksPerSecond=2.0 peers=33 prefix=initial-sync
time="2020-08-19 17:15:46" level=error msg="Failed to close stream with protocol /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy" error="read data when expecting EOF" prefix=initial-sync
time="2020-08-19 17:15:56" level=info msg="Processing block 0x70fc6770... 8352/109279 - estimated time remaining 16h59m27s" blocksPerSecond=1.6 peers=33 prefix=initial-sync
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Ubuntu 18.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    docker image sha256 d89574351c2c1ff0a875d7dff3c48664b7961532b8d38ff9776ec230cbd51078
  </code>
</pre>

**Comment by 0xKiwi** [comment]
Hello @hannesrohde! Thank you for reporting! @prestonvanloon know anything about this? Should we make the log a debug instead of warning?

**Comment by terencechain** [comment]
These logs were moved to debug
