### ISSUE TITLE
Proposer needs to include attestation of the parent block

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#706]
When a validator is selected as a proposer it does not include the attestation of the parent block. This works on simulator + beacon node set up because simulated block's attester bitfield is all flipped to 1.

**Comment by rauljordan** [comment]
Can this be closed?

**Comment by terenc3t** [comment]
This is still relevant but far out. I'll move the milestone to to diamond

**Comment by rauljordan** [comment]
This can now be closed
