### ISSUE TITLE
When I recover mnemonic, it always generates a new one instead

### ISSUE THREAD

**Issue by 1mdc** [prysmaticlabs/prysm#7068]
# 🐞 Bug Report

### Description

I cannot recover mnemonic phrase. When I recover mnemonic, it always generates a new one instead. 

### Has this worked before in a previous version?

Yes It worked before.  I think version alpha-20

## 🔬 Minimal Reproduction

1. Generate new wallet `./prysm.sh validator wallet-v2 create`
2. Generate account `./prysm.sh validator accounts-v2 create`
3. Step 2 gives mnemonic
4. Delete wallet folder
5. Use mnemonic in step 3 to recover: `./prysm.sh validator wallet-v2 recover` but it generates a new one:
```
Starting Prysm validator wallet-v2 recover --wallet-password-file=./prysm-wallet-v2-password.txt --wallet-dir=./prysm-wallet-v2
Enter the language of your seed phrase: chinese_simplified, chinese_traditional, english, french, italian, japanese, korean, spanish:
english
Enter the seed phrase for the wallet you would like to recover:
[my mnemonic here]
[2020-08-20 20:00:01]  INFO derived-keymanager-v2: Write down the sentence below, as it is your only means of recovering your wallet
=================Wallet Seed Recovery Phrase====================

[a new mnemonic here]

===================================================================
Enter how many accounts you would like to recover (default: 0):
1

```

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Mac OS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha-23
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
The accounts-v2 behavior has been strange recently. It now also asks you to create a mnemonic until you run the validator if you haven't created an account yet. Example: `prysm.sh validator wallet-v2 create`, no mnemonic confirmation happens. Then I run `prysm validator` and it asks me to write down my mnemonic. Could https://github.com/prysmaticlabs/prysm/pull/7038 have affected the behavior @0xKiwi ? I don't recall it behaving this way until recently
