### ISSUE TITLE
It is not possible to use the analysistest package with Bazel

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#7074]
# 💎 Issue

### Description

Trying to run any analyzer tests such as these with Bazel

```
func TestAnalyzer(t *testing.T) {
	analysistest.Run(t, analysistest.TestData(), Analyzer)
}
```

results in

```
Failed
=== RUN   TestAnalyzer
    TestAnalyzer: analysistest.go:103: go tool not available: exec: "go": executable file not found in $PATH
--- FAIL: TestAnalyzer (0.00s)
```

`go test` works perfectly fine.

Because of this problem it is not possible to run such tests during the CI process. Example: https://github.com/prysmaticlabs/prysm/blob/master/tools/analyzers/cryptorand/analyzer_test.go (the file is explicitly ignored in `BAZEL.build`).

**Comment by shayzluf** [comment]
@rkapka are there more tools to be added or this can be closed?

**Comment by rkapka** [comment]
@shayzluf There will be one more, but this issue is not tracking them. It's #6747

As for this issue, I am going to propose a solution on Discord now. Thank you for pinging me.
