### ISSUE TITLE
Validators Slashed With Local Protection

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#7076]
# 🐞 Bug Report

### Description

In the course of the[ Medalla Incident](https://medium.com/prysmatic-labs/eth2-medalla-testnet-incident-f7fbc3cc934a), a large number of validators got slashed. A large amount of those validators were running with docker and forgot to specify the volume for the validator db. This lead to a new db being created on each restart. 

However a subset were also running local slashing protection on a persistent db. This did not succeed for a few validators leading them to be slashed.

**What version of Prysm are you running? (Which release)**

Alpha.21

**Anything else relevant (validator index / public key)?**
 
Attached are the DBs. 
1:
Pubkey: `0xae2a8200081ebc3d5b75cfaa25ea648d795585b1b0e32e128c09fc6f16f950d098c9df1e5a092b55f13c382884ac38fe`

https://cdn.discordapp.com/attachments/746233394903515208/746238513548099586/validator.db

2:
https://cdn.discordapp.com/attachments/476588476393848832/745948302695989258/validator.db

3:
https://beaconcha.in/validator/9556
https://cdn.discordapp.com/attachments/667761857209040916/746213204073512960/validator.db

**Comment by nisdas** [comment]
Another slashing for a user running a persistent db:

https://cdn.discordapp.com/attachments/476588476393848832/747705610266738739/validator.db

https://www.beaconcha.in/validator/14661

**Comment by farazdagi** [comment]
@shayzluf is that something you can look into?

**Comment by rauljordan** [comment]
@shayzluf is this still an issue?

**Comment by shayzluf** [comment]
Didn't find the cause for this
