### ISSUE TITLE
Exited validator balance keeps changing

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#7088]
# 🐞 Bug Report

### Description

The validator which was slashed and has changed the status to `Exited` keeps receiving penalties.
The validator exited 14 hours back.

Here are the beaconscan screenshots of the balance change:

![Screenshot 2020-08-23 at 15 19 38](https://user-images.githubusercontent.com/6001614/90978196-9d762280-e554-11ea-9e4e-6f8261c7f167.png)

![Screenshot 2020-08-23 at 15 24 49](https://user-images.githubusercontent.com/6001614/90978219-cbf3fd80-e554-11ea-8209-519d09c3b941.png)

The same changes I could see when querying beacon chain API with version `HEAD-f2afee`.

**Comment by terencechain** [comment]
This is expected. When a validator is slashed, a further delay of ~40 days is imposed. This further penalizes them by forcing them to hold the eth. This makes the penalty somewhat larger for malicious validators that are trying to destroy the chain at the same time than those validators that made a honest mistake
