### ISSUE TITLE
Can't justify & finalize slot in demo mode

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#709]
When running beacon node in demo mode + simulator, the justified slot, justified streak and finalized slot are always at 0

**Comment by terenc3t** [comment]
Ahh. It's the block vote cache, we are treating block vote cache as it's part of the active state but it isn't

**Comment by terenc3t** [comment]
@rawfalafel I think this line is the issue we should get back the old block vote cache
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/db/state.go#L185

**Comment by prestonvanloon** [comment]
Is #711 related?

**Comment by terenc3t** [comment]
@houjieth mentioned he wants to use a DB for storing block vote cache. #711 is to clean up the block vote cache in the DB periodically

**Comment by prestonvanloon** [comment]
So it is related? @terenc3t

**Comment by terenc3t** [comment]
Yes it is. This is blocking #711

**Comment by terenc3t** [comment]
Since this is a very top priority issue, I will be working on this as well

**Comment by houjieth** [comment]
@terenc3t I'm doing the following changes:
- Move BlockVoteCache out of ActiveState
- Using "block-vote-cache-<block_hash>" as DB key to store block vote info for each block as soon as we processed a block (before updating the chain head)
- Read from "block-vote-cache-<block_hash>" from DB when need to access block vote cache but do not read it inside GetActiveState()

I will probably submit a PR tonight. If you need to do it fast and unblock other things please feel free to go ahead first and I can help clean up the rest later :)

**Comment by terenc3t** [comment]
Awesome! That sounds good so far. 
I agree on moving block vote cache out of active state since it's going to be deprecated / combined with the crystallized state. I'll wait for your PR and we can begin our work from there 👍
