### ISSUE TITLE
Account V-2 Import Issue: Cannot import accounts into Prysm -  Message: "Please try again, could not use password to import account 0xa....."

### ISSUE THREAD

**Issue by allpeopletop** [prysmaticlabs/prysm#7099]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by 0xKiwi** [comment]
Hello @allpeopletop ! It seems your issue report is lacking some details, can you provide more information?

**Comment by terencechain** [comment]
Closing due to lack of details
