### ISSUE TITLE
Feature Request: Add debug endpoint to change flag values in flight

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#7108]
# 🚀 Feature Request

### Description

Similar to this idea https://github.com/prysmaticlabs/prysm/issues/5574 where we are able to change the log level verbosity, users have requested the ability to change other flag parameters. 

The specific user request was to be able to adjust the p2p max peer count.

### Describe the solution you'd like

An endpoint that allows users to change some or all flag values without having to restart their process.

### Describe alternatives you've considered

None yet.

**Comment by rauljordan** [comment]
Interested in this after audit resolutions

**Comment by prestonvanloon** [comment]
Not enough time to resolve this before v1 mainnet cut off.

**Comment by rauljordan** [comment]
We have decided to not implement this feature due to the risk it carries for a marginal benefit
