### ISSUE TITLE
Mechanism to clean up block vote cache 

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#711]
Documenting this while it's fresh. Thanks @rawfalafel for discussing this with me & feel free to add more color. We should have a separate goroutine or (service?) for cleaning up block vote cache. When CYCLE_LENGTH * SLOT_DURATION happens, the routine should detect for a new finalized slot, if there's a new finalized slot the routine cleanup block vote cache in db.

**Comment by houjieth** [comment]
I will take this one after https://github.com/prysmaticlabs/prysm/pull/739 is merged.
