### ISSUE TITLE
Prysm crashed on local testnet

### ISSUE THREAD

**Issue by TomWang10** [prysmaticlabs/prysm#7113]
# 🐞 Bug Report

### Description
We ran 1000 validators in the 2.0 testnet built by ourselves，then prysm crashed.

### Has this worked before in a previous version?

Not tested

## 🔬 Minimal Reproduction

I built a complete set of local eth1.0 and eth2.0 testnets, and used the following command to start 1000 validators:

#node1
bazel run //beacon-chain -- --datadir=/data/eth2/beacon-chain-data --http-web3provider=http://localhost:8545 --min-sync-peers 1 --clear-db

#node2
bazel run //beacon-chain -- --datadir=/data/eth2/beacon-chain-data --http-web3provider=http://localhost:8545 --min-sync-peers 1 --peer=/ip4/10.8.129.84/tcp/13000/p2p/16Uiu2HAmAiD8KqXuVyhTpXamhEmcSdgPWwPQy1bzh91sJn3GRnnt --clear-db

#validator 
bazel run //validator -- --datadir=/data/eth2/validator-data

## 🔥 Error

<pre><code>
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x18aea8a, 0x16)
        GOROOT/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc0c4000000, 0x4000000, 0x2a0e838)
        GOROOT/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x29f5660, 0x400000, 0xc0c3efd440, 0x7fb4ef5fdd78)
        GOROOT/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x29f5660, 0x1, 0x0)
        GOROOT/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x29f5660, 0x1, 0x29e0800, 0x2a0e848, 0x45f22d)
        GOROOT/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        GOROOT/src/runtime/mheap.go:871 +0x64
runtime.systemstack(0x0)
        GOROOT/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        GOROOT/src/runtime/proc.go:1041

goroutine 63640 [running]:
runtime.systemstack_switch()
        GOROOT/src/runtime/asm_amd64.s:330 fp=0xc029f19458 sp=0xc029f19450 pc=0x4879a0
runtime.(*mheap).alloc(0x29f5660, 0x1, 0x640108, 0xc0c3ee5120)
        GOROOT/src/runtime/mheap.go:865 +0x81 fp=0xc029f194a8 sp=0xc029f19458 pc=0x447551
runtime.(*mcentral).grow(0x2a05cb8, 0x0)
        GOROOT/src/runtime/mcentral.go:255 +0x79 fp=0xc029f194e8 sp=0xc029f194a8 pc=0x439ab9
runtime.(*mcentral).cacheSpan(0x2a05cb8, 0xc06f9d0ec0)
        GOROOT/src/runtime/mcentral.go:106 +0x2bc fp=0xc029f19530 sp=0xc029f194e8 pc=0x4395ec
runtime.(*mcache).refill(0x7fb5273227d0, 0x8)
        GOROOT/src/runtime/mcache.go:138 +0x85 fp=0xc029f19550 sp=0xc029f19530 pc=0x4390d5
runtime.(*mcache).nextFree(0x7fb5273227d0, 0x8, 0xc0b97bbae8, 0xc09b7beb40, 0xc0b97bb9e0)
        GOROOT/src/runtime/malloc.go:868 +0x87 fp=0xc029f19588 sp=0xc029f19550 pc=0x42dce7
runtime.mallocgc(0x30, 0x1707880, 0x1, 0x7fb5273227d0)
        GOROOT/src/runtime/malloc.go:1036 +0x793 fp=0xc029f19628 sp=0xc029f19588 pc=0x42e623
runtime.newobject(0x1707880, 0xc0000a8720)
        GOROOT/src/runtime/malloc.go:1165 +0x38 fp=0xc029f19658 sp=0xc029f19628 pc=0x42ea18
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv5).newLookup(0xc0004781e0, 0x1c9d1e0, 0xc0299040c0, 0xa15157555e45d65c, 0xaa6a0d934d8b3c5a, 0x6ec27dac2207dd23, 0xa8ba54bc3c3e9d76, 0x0)
        external/com_github_ethereum_go_ethereum/p2p/discover/v5_udp.go:274 +0x31 fp=0xc029f196b0 sp=0xc029f19658 pc=0xf644a1
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv5).newRandomLookup(0xc0004781e0, 0x1c9d1e0, 0xc0299040c0, 0x0)
        external/com_github_ethereum_go_ethereum/p2p/discover/v5_udp.go:270 +0xa8 fp=0xc029f19728 sp=0xc029f196b0 pc=0xf64448
github.com/ethereum/go-ethereum/p2p/discover.(*UDPv5).newRandomLookup-fm(0x1c9d1e0, 0xc0299040c0, 0x0)
        external/com_github_ethereum_go_ethereum/p2p/discover/v5_udp.go:267 +0x3e fp=0xc029f19758 sp=0xc029f19728 pc=0xf6b92e
github.com/ethereum/go-ethereum/p2p/discover.(*lookupIterator).Next(0xc029904100, 0xf)
        external/com_github_ethereum_go_ethereum/p2p/discover/lookup.go:213 +0x14a fp=0xc029f19788 sp=0xc029f19758 pc=0xf583aa
github.com/ethereum/go-ethereum/p2p/enode.ReadNodes(0x1c8bf60, 0xc029904100, 0xf, 0x1, 0x0, 0x0)
        external/com_github_ethereum_go_ethereum/p2p/enode/iter.go:38 +0x404 fp=0xc029f19a58 sp=0xc029f19788 pc=0xf4bac4
github.com/prysmaticlabs/prysm/beacon-chain/p2p.(*Service).FindPeersWithSubnet(0xc000576300, 0x1c9d2a0, 0xc0131ac5d0, 0x3f, 0xc004a7c000, 0x0, 0x0)
        beacon-chain/p2p/subnets.go:35 +0x1bb fp=0xc029f19f78 sp=0xc029f19a58 pc=0x124d7fb
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribeAggregatorSubnet.func1(0xc0008ea600, 0x3f)
        beacon-chain/sync/subscriber.go:317 +0x53 fp=0xc029f19fd0 sp=0xc029f19f78 pc=0x13547a3
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc029f19fd8 sp=0xc029f19fd0 pc=0x489ab1
created by github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).subscribeAggregatorSubnet
        beacon-chain/sync/subscriber.go:316 +0x323

goroutine 1 [chan receive, 525 minutes]:
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start(0xc000154840)
        beacon-chain/node/node.go:269 +0x1dc
main.startNode(0xc000464980, 0xc000117600, 0x0)
        beacon-chain/main.go:189 +0xc7
github.com/urfave/cli/v2.(*App).RunContext(0xc000574c00, 0x1c9d220, 0xc000042078, 0xc00003c070, 0x7, 0x7, 0x0, 0x0)
        external/com_github_urfave_cli_v2/app.go:315 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
        external/com_github_urfave_cli_v2/app.go:215
main.main()
        beacon-chain/main.go:163 +0x1be

goroutine 6 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00013fc50)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 7 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00008cc00)
        external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:162 +0x22d

goroutine 8 [select, 525 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00017fd70)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 9 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00008cd80)
        external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:162 +0x22d

goroutine 10 [select, 525 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000283e90)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00008cf00)
        external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:162 +0x22d

goroutine 12 [select, 480 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0002d0090)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 13 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00008d080)
        external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:162 +0x22d

goroutine 18 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00011c1b0)
        external/com_github_dgraph_io_ristretto/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
        external/com_github_dgraph_io_ristretto/policy.go:80 +0x129

goroutine 19 [runnable]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000110900)
        external/com_github_dgraph_io_ristretto/cache.go:314 +0xed
created by github.com/dgraph-io/ristretto.NewCache
        external/com_github_dgraph_io_ristretto/cache.go:162 +0x22d

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OS: Linux eth2-beacon 4.19.0-6.ucloud #1 SMP Wed Feb 12 08:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux, Ubuntu 18.04.3 LTS
Hardware Configuration: 2core,4GB memory

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Tag:399dc85737639df62f3dc2f7d95478307812440f
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by terencechain** [comment]
It seems like your node ran out of memory. Can you try more 8GB?
