### ISSUE TITLE
Implement Block Ancestor Hash Check

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#712]
When a beacon node processes the block, it should verify block's ancestor hashes are correctly populated by running [update_ancestor_hashes](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/block.go#L237-L247). If the ancestor_hashes is not correct we should reject the block

**Comment by rauljordan** [comment]
Can this be closed @terenc3t? Don't see it in the spec anymore.

**Comment by terenc3t** [comment]
no longer relevant due to spec changes
