### ISSUE TITLE
Validator: Could not get rough time result: lookup caesium.tannerryan.ca: Temporary failure in name resolution

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#7150]
# 🐞 Bug Report

### Description

Validators throwing the below errors and causing the earning to drop to close 0% on the hourly tracker.

### Has this worked before in a previous version?

 This seems to be intermittent as I upgraded my node to alpha.24 today.

## 🔬 Minimal Reproduction

No special changes between alpha.23 vs. alpha.24. 

## 🔥 Error

<pre><code>
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup caesium.tannerryan.ca: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup roughtime.chainpoint.org: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup roughtime.cloudflare.com: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup roughtime.sandbox.google.com: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup roughtime.int08h.com: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Could not get rough time result: lookup ticktock.mixmin.net: Temporary failure in name resolution" prefix=roughtime
time="2020-09-01 08:06:28" level=error msg="Failed to calculate roughtime offset" error="no valid responses" prefix=roughtime
time="2020-09-01 08:31:24" level=error msg="Could not report validator's rewards/penalties" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=valid
ator slot=200256
time="2020-09-01 08:31:28" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:31:28" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:31:36" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:31:36" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:31:48" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:31:48" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:00" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:00" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:12" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:12" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:24" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:24" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:36" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:36" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:48" level=error msg="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 08:32:48" level=error msg="Failed to update assignments" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
time="2020-09-01 09:05:56" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xa37
097a56784 slot=200428

</code></pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu latest. 

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

alpha.24

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

https://medalla.beaconcha.in/dashboard?validators=12425,12433,12437,12442,12446,12456,12457,12461,12465,12469,12473,12474,12477,12480,12487,12490,12493,12499,12504,12509,12511,12516,12521,12525,12527,12532,12542,12544,12552,12567,12568,12569,12574

**Comment by terencechain** [comment]
This may just be a temporary down time whether it is your internet or on the remote. 

Does this link work for you? caesium.tannerryan.ca

**Comment by xuyenvuong** [comment]
@terencechain - The link is working for me. It's probably just a hiccup from the ISP in my area. Thanks.

**Comment by prestonvanloon** [comment]
Closing as not reproducible
