### ISSUE TITLE
Slasher prevents proposal

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#7159]
# 🐞 Bug Report

### Description

Seems like slasher prevents proposal of all validators, not every time. Validator 2073 skipped a proposal because slasher prevented the proposal. https://beaconscan.com/slot/183839

### Has this worked before in a previous version?

Yes

## 🔥 Error

Validator A:
```
time="2020-08-30 01:47:56" level=error msg="Failed post block signing validations" error="made a double proposal, considered slashable by remote slashing protection" prefix=validator pubKey=0x94e2aa11465b slot=183839
```

Validator B:
```
time="2020-08-30 01:47:56" level=error msg="Failed post block signing validations" error="made a double proposal, considered slashable by remote slashing protection" prefix=validator pubKey=0x94e2aa11465b slot=183839
```

Validator C:
```
time="2020-08-30 01:47:56" level=error msg="Failed post block signing validations" error="made a double proposal, considered slashable by remote slashing protection" prefix=validator pubKey=0x94e2aa11465b slot=183839
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
https://github.com/stefa2k/prysm-docker-compose with https://github.com/stefa2k/ansible-prysm/blob/master/eth2node-ha.yaml docker tag `:HEAD-78a25f`
  </code>
</pre>

**Comment by stefa2k** [comment]
same thing here: https://beaconcha.in/validator/2222#blocks with slot 187519

And external slashing protection didn't work with https://beaconcha.in/validator/2222 there is only one `Failed block safety check` of proposal (on 3 nodes) expected were 2 `Failed block safety check`.

**Comment by rauljordan** [comment]
We have not been able to isolate this to slasher, and I believe @shayzluf has worked on this and has not found a correlation. Is it comes up and we have clear data about it, we can take further action
