### ISSUE TITLE
Implement Tree Hash Functions for Simple Serialize

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#716]
Let's Implement the following tree hash functions outlined in the spec for Simple Serialize. This is to make current data structures become more light client friendly and apply to crystalized state, active state, and blocks.

See reference: https://github.com/ethereum/eth2.0-specs/issues/54

**Comment by randomshinichi** [comment]
Hello, I'd be interested in doing this issue

**Comment by nisdas** [comment]
Sounds good, Assigned to you !

**Comment by randomshinichi** [comment]
Current status: The spec is not finalized yet. Just keep up to date with vbuterin's PRs on github.com/ethereum/eth2.0-specs

**Comment by terenc3t** [comment]
@houjieth has expressed interest to work on this. Assigning this to him. Thanks Jie!
