### ISSUE TITLE
--version miss version number and report wrong build time

### ISSUE THREAD

**Issue by somuchid** [prysmaticlabs/prysm#7163]
The output of --version are like these:

beacon-chain version Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}. Built at: 2020-09-02T11:52:20-04:00

validator version Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}. Built at: 2020-09-02T11:53:32-04:00

Running --version first time right after build:
beacon-chain version Prysm/{STABLE_GIT_TAG}/87181204d03c9c6b3b7c3d2bd10a95f04ba5b72a. Built at: 2020-09-02T11:48:30-04:00

It has a hex "/87181204d03c9c6b3b7c3d2bd10a95f04ba5b72a", when running --version again, the hex disappeared.

Every time --version is executed, the build time changes. It is actually current time, NOT the time build was made.

NO version number, such as v.1.2, is provided.

This is going to be a problem for version control in mainnet.

**Comment by prestonvanloon** [comment]
Please build with `--config=release` to properly stamp the process with build information.

```
bazel build //beacon-chain:beacon-chain --config=release
```
