### ISSUE TITLE
Run Fork Choice Tests Using the YAML Test Parser and Simulated Backend

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#718]
Hi all,

After the merge of #681, we have a fully functional yaml test parser for chain tests (fork-choice tests) we can utilize. The simulated backend includes the functionality of modifying global config parameters for a sandboxed execution environment for tests. The next step is to utilize the variables defined in the tests to seed the database with initial information required for the fork choice to be applied. This is a tracking issue for future PRs. This can be closed once we successfully run a fork-choice test using the simulated backend.

**Comment by randomshinichi** [comment]
I'd like to do this issue too

**Comment by nisdas** [comment]
@randomshinichi Ah , I think @rauljordan is already covering this in #681.

**Comment by terenc3t** [comment]
#681 is just the outline, this issue is to implement the test

**Comment by nisdas** [comment]
I think this issue tracks a few future PRs, I am not sure if there is sufficient context in this for someone to start working on it immediately

**Comment by terenc3t** [comment]
Yeah. Let's break this down into smaller PRs

**Comment by prestonvanloon** [comment]
Assigning to Raul for now. Please outline smaller tasks for external contributors, if applicable.

**Comment by nisdas** [comment]
@rauljordan I think this is resolved, should this be closed ?

**Comment by rauljordan** [comment]
Resolved
