### ISSUE TITLE
Slasher is contributing to Attestation and Aggregate Failure

### ISSUE THREAD

**Issue by asovern-crypto** [prysmaticlabs/prysm#7193]
An increase in both CPU usage along with Attestation and Aggregate failures started happening once ten more validator keys were activated within the same Validator.

After resync of the Beacon Node with activating both Validators and Slasher at the same time.  

Both issues presented again within the first ten attestations but after new attestations were assigned with the error codes Deadline Exceeded.  

This is a similar issue that was occurring during the finality incident in August, that improved once v 23 came out.

**Comment by shayzluf** [comment]
Are you running slasher with historical detection?

**Comment by asovern-crypto** [comment]
No flags for historical detection.
Only flag are to set the remote monitoring host and port.
Since turned off Slasher on same device as node/validator, there have not
been att or agg errors.

Will attempt to rpc Slasher into the node for external monitoring at least.
