### ISSUE TITLE
[Tracking Issue] Inform how the user can track their validator exit status

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#7208]
# 💎 Issue

### Background

Follow-up to #6882 

After submitting a voluntary exit, the user is not able to track the status of his exit in the Prysm client. It would be nice to log a link to some block explorer's web page where the status of the exit would be displayed, e.g. https://beaconcha.in/exits/0x29389283982 

### Description

~~- [ ] Have the functionality available on a block explorer's website.~~
~~- [ ] Add a log with the correct link to the block explorer after a successful exit has been submitted.~~

**Comment by rauljordan** [comment]
@rkapka would it be enough if we just show a link to beaconcha.in/exits/0x02939023 once? And then the user can frequentlly check that link to see if they have exited

**Comment by rkapka** [comment]
@rauljordan I had the same thought a few days ago. Let's implement it this way and close the issue.

**Comment by rauljordan** [comment]
I don't think the feature is available yet on beaconcha.in and likely not for a while given their long backlog. Perhaps we can just recommend users to visit https://beaconcha.in/validator/{VALIDATOR INDEX | PUBKEY} to track it? @rkapka

**Comment by rkapka** [comment]
Agreed, let's implement it as you suggest.
