### ISSUE TITLE
Verify justified_block_hash is the hash of the block at the justified_slot

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#721]
Beacon node only verifies justified_block is stored in the DB by doing a lookup using justified_block_hash. 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/types/block.go#L266-L271

Instead of verifying justified block has to be in the current chain, one more additional check needs to be implemented: Beacon node needs to verify the justified block's slot number is the same as justified_slot

From spec:
`Verify that justified_block_hash is the hash of the block in the current chain at the slot -- justified_slot`

**Comment by JerryFireman** [comment]
I'd like to work on this issue.

**Comment by terenc3t** [comment]
Thanks! @jerryfireman Let me know if there's any questions. Happy to answer them on Discord

**Comment by rauljordan** [comment]
Closing due to spec changes - this is not part of the current Ethereum 2.0 spec any longer https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md
