### ISSUE TITLE
Update cloudflare/roughtime Go dependency

### ISSUE THREAD

**Issue by tannerryan** [prysmaticlabs/prysm#7223]
# 💎 Issue

### Background

The Roughtime ecosystem list maintained by Cloudflare has been updated.

### Description

I run one of the servers within Cloudflare's Roughtime ecosystem which Prysm uses. The domain name of the Caesium Roughtime server has been updated from [caesium.tannerryan.ca](https://caesium.tannerryan.ca) to [time.0xt.ca](https://time.0xt.ca).

While the old domain name will continue to resolve for an extended period of time (years), it would be best that the dependency is updated for future releases of the Prysm client.

I would have submitted a PR but the contributor's guide suggests for an issue to be opened.

**Comment by terencechain** [comment]
Thanks @tannerryan feel free to submit a PR. Much appreciated 🙏

**Comment by tannerryan** [comment]
Closing issue as per https://github.com/prysmaticlabs/prysm/pull/7299.
