### ISSUE TITLE
Beacon node memory usage grows until evicted

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#7225]
# 🐞 Bug Report

### Description

Beacon nodes get restarted every hour as their memory usage grows up until 4GB and then they get OOM killed.
This happens every hour. Beacon node version: `v1.0.0-alpha.24`

Here is the usage graph:

![Screenshot 2020-09-11 at 13 25 55](https://user-images.githubusercontent.com/6001614/93020298-e154c880-f5e4-11ea-9c21-42272bfef7ec.png)

1 - `2GB`, 2 - `4GB`.

**Comment by terencechain** [comment]
The chart looks pretty consistent at 2GB with `1`. We'll need more info here. What's the difference between `1` and `2`? is it during initial syncing? how many peers? how many validators?

**Comment by tsudmi** [comment]
Hi @terencechain , 

`1` is the memory requested: 2GB. When it grows to `2` it means that it exceeds the requested amount twice (4GB), then the node restarts, and memory consumption starts growing again.

This is not during the initial sync and the number of peers has the default value (30?).
There are 56 validator clients in total, each one attesting up to 50 validator keys.

**Comment by rauljordan** [comment]
This one is hard for us to resolve, as it is a general issue that has no actionable PR. We can perhaps close in favor of #7585. We might also be raising our recommended hardware specs to help stakers deal with worst case scenarios
