### ISSUE TITLE
Beacon: "Cannot delete seen attestations" error=<nil> prefix="pool/attestations

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#7238]
# 🐞 Bug Report

### Description

 
After upgrade to alpha.25 there new errors are surfacing on the beacon log. It was very cryptic so, it hard to dig into more. The config on my current setup has not change since alpha.24

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: alpha.24

## 🔬 Minimal Reproduction

Upgrade from alpha.24 to alpha.25, restart beacon chain, then observer the log.

## 🔥 Error

<pre><code>

time="2020-09-14 18:27:18" level=error msg="Cannot delete seen attestations" error=<nil> prefix="pool/attestations"
time="2020-09-14 18:27:30" level=error msg="Cannot delete seen attestations" error=<nil> prefix="pool/attestations"

</code></pre>

## 🌍  Your Environment

**Operating System:**
Ubuntu latest on ARM 64.

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
Running alpha.25 
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
https://medalla.beaconcha.in/dashboard?validators=12425,12433,12437,12442,12446,12456,12457,12461,12465,12469,12473,12474,12477,12480,12487,12490,12493,12499,12504,12509,12511,12516,12521,12525,12527,12532,12542,12544,12552,12567,12568,12569,12574

**Comment by terencechain** [comment]
duplicated #7236
