### ISSUE TITLE
Running into `FATAL blockchain: Could not set up chain info: finalized state and block can't be nil` after a restart of beacon chain

### ISSUE THREAD

**Issue by mohammedpatla** [prysmaticlabs/prysm#7266]
# 🐞 FATAL blockchain: Could not set up chain info: finalized state and block can't be nil

### This is when I run the prysm beacon script using this command
``` ./prysm.sh beacon-chain --http-web3provider=https://goerli.prylabs.net --verbosity debug --log-file beacon.log```
The issue is resolved when I delete beaconchain/beaconchain.db and restart, but at some point my script automatically is killed(not sure why it's killed) and when I try to resume, this is the error I run into.

## 🔬 Minimal Reproduction

Only happens when the script is killed (automatically for me). When it does I re-run the command above, and this error is thrown.

## 🔥 Error

Link to logs: - https://www.dropbox.com/s/t94u51kj7n7d4kx/beacon.log?dl=0

## 🌍  Your Environment

**Ubuntu 20.04LTS**
**Python 3.8.2**
**Prysm v1.0.0-alpha.25**

**https://beaconcha.in/validator/0x943aed722d1f23024eac88713b4926e36a091529537466797a5fd5788a64f643b5ffcaa2822ef68c7f2bbe43a1ca9d86**

**Comment by mohammedpatla** [comment]
link to .db https://www.dropbox.com/s/5xxtseged6sjetl/olddata.zip?dl=0

**Comment by mohammedpatla** [comment]
Ok so i figured out the cause of the issue.

When the Beacon chain is killed because of lack of system resources(either hardware or software limitations) it corrupts all the data I think that's why its unable to restart and resume.

**Comment by farazdagi** [comment]
The error is triggered by the following code: https://github.com/prysmaticlabs/prysm/blob/951c139cff5592398514f3cb5051e292ee52fda8/beacon-chain/blockchain/service.go#L445-L457

@terencechain what can be a reason for a `nil` finalized state returned from `stategen.Resume()`? Is there a known way to make sure that even on abrupt node termination, the last saved checkpoint is still guaranteed to have non-nil state?

**Comment by terencechain** [comment]
Should be fixed in #7359, please give a try with alpha27
