### ISSUE TITLE
When creating a new Direct-type wallet, the password provided is not used

### ISSUE THREAD

**Issue by dv8silencer** [prysmaticlabs/prysm#7269]
# 🐞 Bug Report

### Description

Whenever wallet-v2 create is used to create a Direct wallet with password A, and then later accounts-v2 create is used to create a direct-type account with password B, password B becomes the actual wallet password.  B can be anything (Bypass validation) e.g. "asdf"

in CreateWalletWithKeymanager 
```
case v2keymanager.Direct:
        if err = createDirectKeymanagerWallet(ctx, w); err != nil {
            return nil, errors.Wrap(err, "could not initialize wallet with direct keymanager")
        }
        log.WithField("--wallet-dir", cfg.WalletCfg.WalletDir).Info(
            "Successfully created wallet with on-disk keymanager configuration. " +
                "Make a new validator account with ./prysm.sh validator accounts-v2 create",
        )
```
The only thing done is to write the keymanageropts.json which doesn't involve password A.  Then, the program exits.

in v2/accounts_create.go  

```
func CreateAccount(ctx context.Context, cfg *CreateAccountConfig) error {
    keymanager, err := cfg.Wallet.InitializeKeymanager(ctx, false /* skip mnemonic confirm */)
    if err != nil && strings.Contains(err.Error(), "invalid checksum") {
        return errors.New("wrong wallet password entered")
    }
    if err != nil {
        return errors.Wrap(err, "could not initialize keymanager")
    }
 InitializeKeymanager calls NewKeymanager which calls initializeAccountKeystore and 
func (dr *Keymanager) initializeAccountKeystore(ctx context.Context) error {
    encoded, err := dr.wallet.ReadFileAtPath(ctx, AccountsPath, accountsKeystoreFileName)
    if err != nil && strings.Contains(err.Error(), "no files found") {
        // If there are no keys to initialize at all, just exit.
        return nil
    } else if err != nil {
        return errors.Wrapf(err, "could not read keystore file for accounts %s", accountsKeystoreFileName)
    }
```
If an all-accounts.keystore.json isn't found, then it just returns nil error and I think the keymanager stays default
-- the inputted wallet password is never "tested" (and can't be) but rather used as 'correct' password to encrypt the new keys with.

### Has this worked before in a previous version?

I don't know.

## 🔬 Minimal Reproduction

See above

## 🔥 Error

See above

## 🌍  Your Environment

**Operating System:**

Ubuntu VM running Docker

**What version of Prysm are you running? (Which release)**
Master @ 7c2096f20976cceddda8791fabd60df56b1da208

**Comment by rauljordan** [comment]
Successfully reproduced. When creating a wallet, the user is asked for a strong password, but we do not use that anywhere. So when they try to create an account, they are able to bypass all validation by using a weak password as we have nothing to compare it to
