### ISSUE TITLE
prysm beacon-chain

### ISSUE THREAD

**Issue by ric2020stake** [prysmaticlabs/prysm#7271]
# 🐞 Bug Report

### Description Starting Prysm beacon-chain with "./prysm.sh beacon-chain"

 A clear and concise description of the problem...

### Has this worked before in a previous version? don't know

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
Starting Prysm beacon-chain --datadir /mnt/ssd/prysm
./prysm.sh: rivi 241: /home/pi/prysm/dist/beacon-chain-v1.0.0-alpha.25-linux-arm64: No such file or directory

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:** raspberry pi4 4G

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by ric2020stake** [comment]
I need help with this problem
Starting Prysm beacon-chain --datadir /mnt/ssd/prysm
./prysm.sh: rivi 241: /home/pi/prysm/dist/beacon-chain-v1.0.0-alpha.25-linux-arm64: Tiedostoa tai hakemistoa ei ole

**Comment by terencechain** [comment]
This is a set up error, please ask help in the discord chat rooms
