### ISSUE TITLE
ssz mainnet spec test is skipped for v0.12.3

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7277]
**Why?**
In v0.12.3, the ssz mainnet spec test got mistakenly skipped due to miss configuration on the generator. Due to that, eth2.0-spec-test did not have ssz mainnet spec test. The impacted file on our end is `ssz_static_mainnet_test.go`

https://github.com/ethereum/eth2.0-specs/issues/2076

****When will this be fixed?****
When v0.12.4 releases

**Comment by prestonvanloon** [comment]
https://github.com/ethereum/eth2.0-specs/issues/2076#issuecomment-696329058

The tests were regenerated for v0.12.3 with the missing spec tests. 
CI will fail until we update the sha in WORKSPACE.
