### ISSUE TITLE
Different wallet types don't mix well within the same wallet directory

### ISSUE THREAD

**Issue by dv8silencer** [prysmaticlabs/prysm#7281]
# 🐞 Bug Report

Example:

Start w/ user w/  No Prysm wallets/never used Prysm before/just freshly installed Prysm after going through eth2.0-deposit-cli

1) accounts-v2 import --keys-dir ........ (as one may import launchpad keys).  During interaction w/ the program, create the wallet [direct] with Password A and in default dir
2) accounts-v2 list   ---> works as expected
3) wallet-v2 create HD (DERIVED) type wallet in default directory w/ Password B
----After this point, behavior is as if Direct (pass A) wallet no longer exists
4) accounts-v2 create --> Input Password A (direct pass) -> Fail w/ "Could not create new account: wrong wallet password entered"
5) try 4 again with Password B (derived) --> success
6) accounts-v2 list, fails with A, good with B but only show's B (HD) account, no mention of Direct account
7) run the validator, only password B works (A fails w/ "could not read keymanager for wallet: could not initialize derived keymanager: could not decrypt seed configuration with password: invalid checksum").

### Description

See above

### Has this worked before in a previous version?

Complex set of steps, unclear what variety may have worked before.  Sorry

## 🔬 Minimal Reproduction

See above

## 🔥 Error

See above

## 🌍  Your Environment

Ubuntu VM running Docker

**What version of Prysm are you running? (Which release)**

current Master

**Anything else relevant (validator index / public key)?**
No

**Comment by rauljordan** [comment]
There should only be one wallet type per wallet directory. An easy solution to this issue is to disallow multiple wallets in the same directory

**Comment by dv8silencer** [comment]
`wallet-v2 recover` bypasses the checks and allows a user to have multiple wallet types per directory.  This can be reproduced by making a direct wallet, then using `wallet-v2 recover` into same wallet dir, which results in both direct and derived types in the same folder

Also:
in validator/rpc/wallet.go, (s *Server) CreateWallet() calls CreateWalletWithKeymanager line 43--- is this another way to create multiple different wallets in the same directory?
