### ISSUE TITLE
ListValidatorBalances responds "Could not get state"

### ISSUE THREAD

**Issue by deni64k** [prysmaticlabs/prysm#7298]
# 🐞 Bug Report

### Description

This GRPC query
```json
{
  "publicKeys": [],
  "indices": [
    "32831"
  ],
  "epoch": "10575"
}
```

leads to an error:
```
Internal (13)
Could not get state
```

### Has this worked before in a previous version?

It worked on the current version because I was running very similar queries without having any problems.

## 🔬 Minimal Reproduction

1. Public API

```
% curl -i "https://api.prylabs.net/eth/v1alpha1/validators/balances?epoch=10575&indices=32831" -H "accept: application/json"
HTTP/2 500 
content-type: application/grpc
grpc-status: 13
grpc-message: Could not get state
x-envoy-upstream-service-time: 1828
x-backend: beacon-chain-prod-4
x-source: unknown
date: Tue, 22 Sep 2020 02:13:59 GMT
server: istio-envoy
content-length: 0
x-backend: beacon-chain-prod-4
x-source: istio-ingressgateway
```

2. GRPC
```
% grpcurl -plaintext -d '{"epoch": "10575","publicKeys": [],"indices": ["32831"]}' -protoset beacon_chain.protoset localhost:4000 ethereum.eth.v1alpha1.BeaconChain/ListValidatorBalances
ERROR:
  Code: Internal
  Message: Could not get state
```

## 🔥 Error

Nothing in logs

## 🌍  Your Environment

**Operating System:**

macOS, Linux

**What version of Prysm are you running? (Which release)**

`v1.0.0-alpha.25`

**Anything else relevant (validator index / public key)?**

epoch=10575

indices=[32831]

**Comment by terencechain** [comment]
Works for me on latest master

➜  ~ curl -X GET "http://localhost:3051/eth/v1alpha1/validators/balances?epoch=10575&indices=32831" -H "accept: application/json"
{"epoch":"10575","balances":[{"publicKey":"kXRKQA10JoIToMMQejOwiLUOCpIzfBQ1wu9RprEH1lxeHjGNc2pe7V9gutcT/xZp","index":"32831","balance":"32038661584"}],"nextPageToken":"","totalSize":1}%                                                                                                                                                             


Can you try alpha 26?

**Comment by deni64k** [comment]
The same error on alpha 26.

**Comment by shayzluf** [comment]
@rauljordan please reassign to me if you find the assignment inappropriate

**Comment by terencechain** [comment]
> The same error on alpha 26.

@deni64k if it's possible, can you upload your DB somewhere for us to take a look? Feel free to dm me on discord with any questions

**Comment by prestonvanloon** [comment]
@terencechain this happened in our nodes too. We could pull the db from beacon-chain-prod-4 if that is helpful.

**Comment by deni64k** [comment]
I have my db shared here: https://ipfs.io/ipfs/Qmdofz1aG4XjT78kg7aPRAKPGgxu2k7j9cPZW8zFVvtF1F?filename=prysm.tar.gz
But, my upload speed is very slow, 10 MiB, so you might have to wait for long to download it.

**Comment by terencechain** [comment]
> I have my db shared here: https://ipfs.io/ipfs/Qmdofz1aG4XjT78kg7aPRAKPGgxu2k7j9cPZW8zFVvtF1F?filename=prysm.tar.gz
> But, my upload speed is very slow, 10 Mbps, so you might have to wait for long to download it.

Thanks @deni64k, we have figured out the bug and have a solution. You can cancel the upload now if you want.

**Comment by deni64k** [comment]
Just tested it on `6ad117b17562501f18b80b0ca8aeadf290f61054`:

```
% grpcurl -plaintext -d '{"epoch": "10575","publicKeys": [],"indices": ["32831"]}' -protoset beacon_chain.protoset 192.168.0.18:31000 ethereum.eth.v1alpha1.BeaconChain/ListValidatorBalances
{
  "epoch": "10575",
  "balances": [
    {
      "publicKey": "kXRKQA10JoIToMMQejOwiLUOCpIzfBQ1wu9RprEH1lxeHjGNc2pe7V9gutcT/xZp",
      "index": "32831",
      "balance": "32038661584"
    }
  ],
  "totalSize": 1
}
```

The output is as expected.

Thanks, folks, for a very quick fix!

**Comment by terencechain** [comment]
> Just tested it on `6ad117b17562501f18b80b0ca8aeadf290f61054`:
> 
> Thanks, folks, for a very quick fix!

Anytime! thanks for confirming and the reporting!
