### ISSUE TITLE
Wrong Result Returned from rpc.ListValidators Call

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7306]
# 🐞 Bug Report

### Description

Thanks to @mcdee for finding this. 

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

curl -X GET "http://localhost:3500/eth/v1alpha1/validators?epoch=10989" -H "accept: application/json"

will return a total size of 57387 which is incorrect

## 🔥 Error

The culprit is here https://sourcegraph.com/github.com/prysmaticlabs/prysm/-/blob/beacon-chain/rpc/beacon/validators.go#L279

```go
if requestedEpoch < currentEpoch {
  stopIdx := len(validatorList)
  for idx, item := range validatorList {
    // The first time we see a validator with an activation epoch > the requested epoch,
    // we know this validator is from the future relative to what the request wants.
    if item.Validator.ActivationEpoch > requestedEpoch {
      stopIdx = idx
      break
    }
  }
  validatorList = validatorList[:stopIdx]
}
```

From Jim:
> That assumption is bad.  If there is a validator in there with less than a full deposit then its activation epoch will be far future, but there could be ones after it that have been activated.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Catalina
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Alpha.25
  </code>
</pre>

**Comment by terencechain** [comment]
Resolved via #7354
