### ISSUE TITLE
Config file params ignored when running subcommand

### ISSUE THREAD

**Issue by bidlocode** [prysmaticlabs/prysm#7310]
🐞 Bug Report

### Description

Config file parameters ignored when running subcommand. Config file parameters in question:
<pre>
  <code>
wallet-dir: /data/wallets
wallet-password-file: /data/passwords/wallet-password
keys-dir: /launchpad/eth2.0-deposit-cli/validator_keys
  </code>
</pre>

## 🔬 Minimal Reproduction

Everything works as expected:
<pre>
  <code>
./prysm.sh validator --config-file=/config/validator.yaml
./prysm.sh validator accounts-v2 import --wallet-dir="/data/wallets" --wallet-password-file="/data/passwords/wallet-password" --keys-dir="/launchpad/eth2.0-deposit-cli/validator_keys"
  </code>
</pre>

But ignored when:
<pre>
  <code>
./prysm.sh validator --config-file=/config/validator.yaml accounts-v2 import

#wallet-dir, wallet-password-file from config still ignored
./prysm.sh validator --config-file=/config/validator.yaml accounts-v2 import --keys-dir="/launchpad/eth2.0-deposit-cli/validator_keys"
  </code>
</pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux docker
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v1.0.0-alpha.26/22bcfd2c340a8cb682468e5a7112404aee1e3849. Built at: 2020-09-22 15:28:34+00:00 (docker image)
  </code>
</pre>

**Comment by bidlocode** [comment]
Looks like the problem is that all flags from config-file get redefined in all subcommands. In this case it happens in `validator/accounts/v2/cmd_accounts.go`
```		{
			Name:        "import",
			Description: `imports eth2 validator accounts stored in EIP-2335 keystore.json files from an external directory`,
			Flags: []cli.Flag{
				flags.WalletDirFlag,
				flags.KeysDirFlag,
				flags.WalletPasswordFileFlag,
				flags.AccountPasswordFileFlag,
				flags.ImportPrivateKeyFileFlag,
				featureconfig.AltonaTestnet,
				featureconfig.OnyxTestnet,
				featureconfig.SpadinaTestnet,
				flags.DeprecatedPasswordsDirFlag,
			},
			Action: func(cliCtx *cli.Context) error {
				featureconfig.ConfigureValidator(cliCtx)
				if err := ImportAccountsCli(cliCtx); err != nil {
					log.Fatalf("Could not import accounts: %v", err)
				}
				return nil
			},
		},```

**Comment by dmcclung** [comment]
Is there a way to check the cliCtx to see if the configure yaml has already been parsed?

**Comment by bidlocode** [comment]
just by checking the `cmd.ConfigFileFlag.Name` i guess

config-file being parsed every time app initialized in `validator/main.go` (when `cmd.ConfigFileFlag.Name` flag is set) 
```
	app.Before = func(ctx *cli.Context) error {
		if ctx.IsSet(cmd.ConfigFileFlag.Name) {
			if err := altsrc.InitInputSourceWithContext(appFlags, altsrc.NewYamlSourceFromFlagFunc(cmd.ConfigFileFlag.Name))(ctx); err != nil {
				return err
			}
		}
```

**Comment by bidlocode** [comment]
i feel that the fix to this probably will involve good amount of refactoring

**Comment by bidlocode** [comment]
1. or we can take away `Flags: []cli.Flag{}` completely from all subcommand definitions
2. or leave only subcommand related flags

```
			Flags: []cli.Flag{
				flags.ImportPrivateKeyFileFlag,
			},
```

**Comment by dmcclung** [comment]
The context has a parent context.
https://github.com/urfave/cli/blob/master/context.go

I would debug and see if that parent context is there. I'm guessing that a sub command should have the context of the parent which then should have the flags set. When the validator is configured, it may need to look at the parent context if available.

**Comment by bidlocode** [comment]
we can do that with something like this?
<pre><code>if parentCtx.flagSet != nil {
           //...
}</code></pre>
but why do we redeclare all common shared flags in all subcommands again?

**Comment by bidlocode** [comment]
If we follow this current concept:
<pre><code>USAGE:
   prysm.sh [options] command [command options] [arguments...]</code></pre>
As i see it, in subcommand definitions, it should be either:
- only subcommand related flags, and to check if any not set flag in **currtent ctx** were set in **parent ctx**
- only subcommand related flags, and make these flags required (because all subcmds are interactive?)

or:
- as it is now, and to check if any not set flag in **currtent ctx** were set in **parent ctx**

First two will require from users more strict positional(common, subcommand) usage of the flags
The last one with redundant flags in every subcommand will be easier on user

**Comment by rauljordan** [comment]
NOTE: Accounts-v2 is deprecated, do not use accounts-v2 in Prysm
