### ISSUE TITLE
Option to explicitly disable unneeded ports

### ISSUE THREAD

**Issue by bidlocode** [prysmaticlabs/prysm#7317]
🚀 Feature Request

### Description

option to disable rpc port, grpc-gateway, monitoring port or any non-vital ports
for example --rpc-port 0 to disable rpc-port on validator instance

**Comment by prestonvanloon** [comment]
You can disable grpc gateway with `--disable-grpc-gateway` and monitoring port `--disable-monitoring`. 

gRPC is needed by the validator and we don't have support at the moment to disable it. Is there a use case for syncing a beacon node that doesn't allow validators to connect via gRPC?

**Comment by bidlocode** [comment]
As far as i understand
in the most mininal configuration we only need p2p-ports and grpc-port on **beacon** node?

<pre>
<code>## beacon-chain
tcp:4000
tcp:13000
udp:12000</code>
</pre>

All other ports are optional
<pre>
<code>## beacon-chain
tcp:8080	OK		--disable-monitoring
tcp:3500	OK		--disable-grpc-gateway

## validator
tcp:8081	???		(--disable-monitoring ERRO[0000] flag provided but not defined)
tcp:7000	???
tcp:7500	???		(--disable-grpc-gateway ERRO[0000] flag provided but not defined)

## slasher
tcp:8082	???		(--disable-monitoring ERRO[0000] flag provided but not defined)
tcp:4002	???
</code>
</pre>

**Comment by bidlocode** [comment]
I can add it, but i don't really familiar with the process of contributing to the project

**Comment by prestonvanloon** [comment]
Looks like a few things to do here:
- The disable-monitoring flag doesn't work on validator or slasher
- Validator port 7000 is the validator's gRPC server, used for querying information in the UI 
- Validator port 7500 is the gRPC gateway, same usage as port 7500. This should also be disabled with disable-grpc-gateway
- Slasher port 4002 is the slasher's gRPC server, it does not have a flag to disable it at the moment. 

Here's our contributing guide: https://docs.prylabs.network/docs/contribute/contribution-guidelines/

Feel free to ping me or anyone on the team in discord, I can help point you in the right direction to register and use these flags.
