### ISSUE TITLE
validator dies if beacon node not ready, with "error while dialing"

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#7339]
# 🐞 Bug Report

### Description

If the beacon node is not ready when the validator starts, the validator will exit with error, see below

For automated environments, this will require wrapping the validator in "wait-for-it" or similar. While depends_on can make sure the beacon node is up, nothing prevents a race condition where the beacon node is not yet accepting connections when the validator starts.

Unsure whether considered a bug or an enhancement: Validator could be in a try loop for the beacon until it finds the beacon or someone kills it. This is the approach your beacon takes for eth1 sources if I am not mistaken, and the approach the Lighthouse validator takes for beacon sources.

### Has this worked before in a previous version?

Unknown

## 🔬 Minimal Reproduction

Minimal would be validator started before beacon.
Less minimal may be a docker-compose environment with beacon and validator, but it'll take you a minute to reproduce a race condition.

## 🔥 Error

<pre><code>
prysm-validator_1         | time="2020-09-24 16:04:11" level=fatal msg="Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.224.2:4000: connect: connection refused"" prefix=validator
</code></pre>

## 🌍  Your Environment

Ubuntu 20.04.01
docker/docker-compose

**What version of Prysm are you running? (Which release)**

1.0.0-alpha26

**Comment by rauljordan** [comment]
https://github.com/prysmaticlabs/prysm/pull/8057 done
