### ISSUE TITLE
Mismatch Between Recommend Wallets in Docs vs. Code

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7343]
From one of our stakers in our Discord:
```
Just a tiny thing on the documentation that might confuse a user. On 
https://docs.prylabs.network/docs/prysm-usage/running-a-validator/ 
in "Wallet Kinds" you see:
Simple import (recommended) HD wallet (least secure) Remote signer (most secure)
While running validator wallet-v2 create you get
HD Wallet (Recommended)  --- Non-HD Wallet (Most Basic)  --- Remote Signing Wallet (Advanced)
So two different kinds of wallets are being recommended.
```
We should recommend a simple import wallet always

**Comment by viveksahu26** [comment]
Hey @rauljordan , I would like to work on this issue.

**Comment by rauljordan** [comment]
Assigned! The right solution is to change the text in Prysm to align with the docs

**Comment by potuz** [comment]
hehe, I'm happy that I have two different "Good First Issue" here :). Anyway, if you change the text in Prysm and you recommend the non-HD wallet, then I'd recommend that you also change the order so that it is also the first one offered.
