### ISSUE TITLE
Discovery V5 half handshake bug

### ISSUE THREAD

**Issue by zilm13** [prysmaticlabs/prysm#7346]
# 🐞 Bug Report

### Description
Sequence
<pre><code>
random packet ->
<- whoareyou
malformed authheadermessage packet ->
malformed authheadermessage packet (same) ->
malformed authheadermessage packet (same) ->
malformed authheadermessage packet (same) ->
correct authheadermessage packet ->
</code></pre>
passes the authorization. You could send any number of malformed AuthHeaderMessages until timeout from my tests.

### Has this worked before in a previous version?
Discovery V5 implementation in Prysm is affected. Probably V5.1 doesn't fix the issue as it adds only cheap AES on top, but expensive EC Curve is still in the place.

## 🔬 Minimal Reproduction

I've created a test for Go implementation of discovery, as you are using it, it passes:

<pre><code>
func TestHandshake_attack(t *testing.T) {
	t.Parallel()
	net := newHandshakeTest()
	defer net.close()

	// A -> B   RANDOM PACKET
	packet, _ := net.nodeA.encode(t, net.nodeB, &findnodeV5{})
	resp := net.nodeB.expectDecode(t, p_unknownV5, packet)

	// A <- B   WHOAREYOU
	challenge := &whoareyouV5{
		AuthTag:   resp.(*unknownV5).AuthTag,
		IDNonce:   testIDnonce,
		RecordSeq: 0,
	}
	whoareyou, _ := net.nodeB.encode(t, net.nodeA, challenge)
	net.nodeA.expectDecode(t, p_whoareyouV5, whoareyou)

	// A -> B   FINDNODE after timeout
	//net.clock.Run(handshakeTimeout + 1)

	incorrect_challenge := &whoareyouV5{
		AuthTag: challenge.AuthTag,
		IDNonce: [32]byte{5, 6, 7, 8, 9, 6, 11, 12},
		RecordSeq: challenge.RecordSeq,
		node: challenge.node,
		sent: challenge.sent,
	}
	incorrect_findnode, _ := net.nodeA.encodeWithChallenge(t, net.nodeB, incorrect_challenge, &findnodeV5{})
	incorrect_findnode2 := make([]byte, len(incorrect_findnode))
	copy(incorrect_findnode2, incorrect_findnode)
	net.nodeB.expectDecodeErr(t, errInvalidNonceSig, incorrect_findnode)
	net.nodeB.expectDecodeErr(t, errInvalidNonceSig, incorrect_findnode2)
	findnode, _ := net.nodeA.encodeWithChallenge(t, net.nodeB, challenge, &findnodeV5{})
	net.nodeB.expectDecode(t, p_findnodeV5, findnode)
}
</code></pre>

## 🔥 Error

**Expected behaviour**
Session should be dropped on first malformed AuthHeaderMessage

**Comment by nisdas** [comment]
This has been added in to the v5.1 branch as of this commit:
https://github.com/ethereum/go-ethereum/pull/21647/commits/59b11fa55e228a3ec299a75590a04252a48b43e0 

So this should be resolved once v5.1 is merged in to geth's master.

**Comment by rauljordan** [comment]
Resolved now that discv5.1 is merged
