### ISSUE TITLE
Use journald loglevel on Linux systems

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#7353]
Currently if running on the background on Linux using systemd, all events are logged at the default level (typically "info").  

By prefixing the lines of output with angle brackets with the loglevel, for example 

<4> This is a warning message
<6> This is an info message

Then a command like `journalctl -u beacon-chain -p 4` will only print the warning message. 

Arguably this is uncomfortable for those not using journald and/or piping the logs somewhere else. In this case a simple workaround is not to print if running in the foreground. For a more involved solution journald exposes the syslog API so that this can be handled there. Given that the vast majority of Linux systems already switched to systemd I think that simply prefixing the lines would satisfy most people while the trade for those running custom logs would be minimal.

**Comment by prestonvanloon** [comment]
We could add this as another logging format. We already support JSON and fluentd, so another format would be acceptable if anyone finds it useful.

**Comment by potuz** [comment]
Journald accepts JSON (as long as it's key=value pairs) so it may be simple to port already the JSON format

https://www.freedesktop.org/wiki/Software/systemd/json/

https://stackoverflow.com/questions/45604563/injecting-structured-json-logs-into-journald

**Comment by prestonvanloon** [comment]
Try `--log-format=json` or `--log-format=fluentd`, fluentd is also JSON but a more standard format. JSON should be a single object with key value pairs for each entry, fluentd might have nested objects.

**Comment by potuz** [comment]
That just prints the json in the journal, to feed the json I think it has to be through the local socket or connecting with HTTP on port 19531 for example.

**Comment by potuz** [comment]
I know nothing about go, installed it today and started browsing your code, found that you're using logrus and found a very simple hook for journald

https://github.com/sirupsen/logrus/commit/4d9b4f0c8393f52d78a2876e8784813819d9fcb1
https://github.com/wercker/journalhook

Seems very simple to implement, if noone takes this in the next few days I may add it

**Comment by potuz** [comment]
I added a PR, but then I read that you guys do not accept PRs with new dependencies. Instructions were to open a new Issue, but perhaps this one is enough?

**Comment by prestonvanloon** [comment]
@potuz Unfortunately, PR #7429 adds a dependency on core-os which does not work when building on windows. 
We are reverting that PR and re-opening this issue. 
Please see #7454

**Comment by potuz** [comment]
I'll see if I can add a flag for linux, I'm surprised this got past the CI

**Comment by prestonvanloon** [comment]
> I'm surprised this got past the CI
Yeah, looks like we don't test windows builds in the CI. I'll take a look into that as well.
