### ISSUE TITLE
`prysm.sh` : add support for `sha256sum`

### ISSUE THREAD

**Issue by georgercarder** [prysmaticlabs/prysm#7369]
# 🦄 Feature Request

The shell script `prysm.sh` currently checks the environment for `shasum` which gives `shasum -a 256` later on line :137 to check integrity of download. Some systems have `sha256sum` installed in place of `shasum` where the call `sha256sum -c <file to check>` is equivalent to `shasum -a 256 -c <file to check>`.
An incoming PR `shell_script_support4_sha256sum` makes the appropriate changes to `prysm.sh` to accommodate this other call.

**Comment by farazdagi** [comment]
Thank you for starting this. It is certainly not a "Feature tracking" request (so updated issue text and removed "Tracking" label). Other that that, your idea sounds good, will review linked PR now.
