### ISSUE TITLE
Update Shard to Beacon Chain Crosslinking Mechanics

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#737]
The [crosslink mechanic has been updated](https://github.com/ethereum/eth2.0-specs/pull/111) due to a potential attack that was brought up [here](https://github.com/ethereum/eth2.0-specs/issues/106). With this changes, validator shuffling has a lower barrier to entry. To sufficiently implement these changes, we should wait to combine active & crystallized state to a [single state implementation](https://github.com/ethereum/eth2.0-specs/pull/122) to avoid future refactor hence I'm making this blocked at this very moment

**Comment by rauljordan** [comment]
This can be closed as we have already merged active and crystallized state along with all the merged PRs as part of the greater effort in: https://github.com/prysmaticlabs/prysm/issues/781
