### ISSUE TITLE
Display deposit contract address during deposit process 

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#7371]
Display the deposit contract address next to the logs so users can verify the contract address on the logs

![image](https://user-images.githubusercontent.com/26490734/94537208-447c6700-0243-11eb-87cf-6fc506c977af.png)

**Comment by bidlocode** [comment]
it will give incorrect contract message if you trying to run with different contract 
`"database contract is %#x but tried to run with %#x", knownContract, cfg.DepositContract.Bytes()`

**Comment by prestonvanloon** [comment]
I see how it could be helpful to log the contract address. Thanks!
