### ISSUE TITLE
Could not set up chain info: finalized state and block can't be nil

### ISSUE THREAD

**Issue by ChuckNorrison** [prysmaticlabs/prysm#7372]
this is still an issue... what can i do to get into this spadina testnet with the prysm clinet which seems to be fixed to 0.26?

Closed duplicates
https://github.com/prysmaticlabs/prysm/issues/7366
https://github.com/prysmaticlabs/prysm/issues/7356

**Comment by ChuckNorrison** [comment]
cause this will loose a lot of money in LIVE and nobody cares, this gets solved with a client switch

**Comment by terencechain** [comment]
Hi, this was fixed in master and will get resolved in alpha-v0.27 which will be released today. Apology for the inconvenience. I will ping you once the fix is ready to test again
