### ISSUE TITLE
Infura showing huge blank method bandwidth usage

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#7374]
Hi, I am running a validator on spadina and another on medalla on the same machine. On Arch linux with these commands:

```
$ ps -ef | grep beacon-chain
user  233427       1 14 08:09 ?        00:26:22 /pathtodist/dist/beacon-chain-v1.0.0-alpha.26-linux-amd64 --datadir=/path-to/validator --http-web3provider=https://goerli.infura.io/v3/a2195faddressedited f --p2p-host-ip=myip --verbosity warn
user  239908  206224  5 10:53 pts/0    00:00:58 ./dist/beacon-chain --spadina --datadir=./spadina --http-web3provider=https://goerli.infura.io/v3/a21addressedited f --p2p-host-ip=myip --p2p-tcp-port=26000 --p2p-udp-port=24000 --grpc-gateway-port=7001 --rpc-port=8000 --monitoring-port=8090 --bootstrap-node=enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g --clear-db
```

And infura is showing a huge bandwitdh usage of blank method calls: 

![fo](https://user-images.githubusercontent.com/16044918/94570205-f9fbea00-0244-11eb-9a32-65d8fc8a9d78.jpg)

I am happy to provide you any logs if you want, but I guess this happened only because of the second instance running spadina (which I had to relaunch and delete the dbase several times) and that one is running in the foreground without any interesting logs to show. If you want I can resync and relaunch logging to a file but I'm not sure if it will recreate the issue. I'm posting here cause @nisdas asked on Discord

**Comment by prestonvanloon** [comment]
What is a blank method? This seems like a bug in infura. Have you talked with them?

**Comment by potuz** [comment]
It may well be indeed. I'll contact them and come back here. I asked a few people on discord and all were seeing similar issues

**Comment by prestonvanloon** [comment]
@potuz Please let me know what you find out. I wouldn't be surprised if this was real API traffic and it would make investigation easier if we knew what calls Infura is reporting 2gb. Thanks

**Comment by potuz** [comment]
Fwiw, I switched to a local geth node and the total bandwidth on the same validators stays more or less the same. I haven't really tried to separate by calls though.

**Comment by potuz** [comment]
```
Hi @potuz - welcome to the Infura community! The blank calls are bulk Eth1 calls the Eth2 client is making (i.e. these are batch requests from Prysm to our Eth1 Goerli endpoint).

From our end, this seems like it may be a Prysm bug.
```

**Comment by prestonvanloon** [comment]
@nisdas have your recent PRs helped with this issue?

**Comment by rkapka** [comment]
This is Medalla after running for a couple of hours. @potuz can you please verify that the issue still persists?

![obraz](https://user-images.githubusercontent.com/28876818/96602881-c8ca8300-12f3-11eb-9e60-c7bef9674230.png)

**Comment by rkapka** [comment]
Closing the issue after as a result of Discord discussion: https://discord.com/channels/476244492043812875/667761857209040916/768142565496455208
