### ISSUE TITLE
bootstrap-node option doesn't work from a config file only works on CLI

### ISSUE THREAD

**Issue by OisinKyne** [prysmaticlabs/prysm#7376]
# 🐞 Bug Report

### Description

I was taking part in the Spadina genesis on Alpha26. A fix was announced to add a bootnode via ENR to help get peers and get on the network. I am supplying config to my beacon client via a config file. I added 
```yaml
spadina: true
bootstrap-node: "enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g"
```
to my config file and cleared my DB. 

When I started the client again I got the error:
```log
time="2020-09-29T12:56:13Z" level=error msg="Mismatched type for flag 'bootstrap-node'. Expected '[]interface{}' but actual is 'string'" prefix=main
```

I tried it with and without the double quotes around the ENR and got the same error each time. I made sure to wipe the DB too. 

When I instead placed this arg into my docker run command instead of my config file it worked as expected.

```bash
docker run --restart=always --name=beacon-chain -d -p 13000:13000 -p 4000:4000 -p 8080:8080 -p 12000:12000/udp --network=host gcr.io/prysmaticlabs/prysm/beacon-chain:{{ prysm_docker_tag }} --config-file=/config/beacon-config.yaml --bootstrap-node=enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g
```

### Has this worked before in a previous version?

I did not try this on a previous version.

## 🔬 Minimal Reproduction

Run a beacon client on alpha.26 with `bootstrap-node` set in a config file rather than as a CLI arg.

## 🔥 Error

<pre><code>
time="2020-09-29T12:56:13Z" level=error msg="Mismatched type for flag 'bootstrap-node'. Expected '[]interface{}' but actual is 'string'" prefix=main

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Ubuntu
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    Docker image of the beacon client version alpha.26
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
You can check out my validator [here](https://spadina.beaconcha.in/validator/a7b325b816204783ddf2e02c7f418ba94f8978c9504dac196ff60c307136ecb1b824025dc5acdbe14c2191a8aaca9486#overview) if you would like to see that I got it rectified when I put the `bootstrap-node` flag into the CLI rather than the config file.

**Comment by prestonvanloon** [comment]
Bootstrap node is a repeated flag so it must be an array in yaml. Please see: https://github.com/prysmaticlabs/prysm/issues/6822

**Comment by prestonvanloon** [comment]
@OisinKyne if you have any suggestions on where we could document this better, I would love the opportunity to improve it. Thanks

**Comment by OisinKyne** [comment]
Hey @prestonvanloon that looks to be what was wrong all right. 

As for docs, maybe in this table: https://docs.prylabs.network/docs/prysm-usage/parameters#base-flags

`--bootstrap-node` can be described as:

> The address of **one or more** bootstrap node **(s)**. Beacon node will connect for peer discovery via DHT. Multiple nodes can be separated with a comma, **if supplying this value as a config file, these nodes should be specified as a YAML array.** Default:

Also, do you guys use any aliases for CLI args? An alias between `bootstrap-node` and `bootstrap-nodes` might help people infer this is meant to be an array of nodes rather than a single value.
