### ISSUE TITLE
prysm bazel build does not support ArchLabs

### ISSUE THREAD

**Issue by georgercarder** [prysmaticlabs/prysm#7377]
Prysm bazel build does not support archLabs (likely also will not support Arch-Linux).
When I try to build on my system running "ArchLabs" I get the following logs:
```
[me@mysystem prysm]$ bazel build //beacon-chain:beachon-chain
Starting local Bazel server and connecting to it...
INFO: Repository llvm_toolchain instantiated at:
  /mnt/teraByteDisk/teraByteDisk/prysm/prysm/WORKSPACE:29:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /home/me/.cache/bazel/_bazel_me/ef3f60115dbd95e5e1d7dfbf229016bc/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/me/.cache/bazel/_bazel_me/ef3f60115dbd95e5e1d7dfbf229016bc/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102, column 37, in llvm_toolchain_impl
		_download_llvm_preconfigured(rctx)
	File "/home/me/.cache/bazel/_bazel_me/ef3f60115dbd95e5e1d7dfbf229016bc/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, column 17, in download_llvm_preconfigured
		fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
Error in fail: Failed to detect host OS version: 

Unsupported linux distribution and version: ArchLabs, 2019.10.29
ERROR: no such package '@llvm_toolchain//': Failed to detect host OS version: 

Unsupported linux distribution and version: ArchLabs, 2019.10.29
INFO: Elapsed time: 2.379s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

# 🚀 Feature Request

### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by farazdagi** [comment]
Do you think it is configuration issue in Prysm, or ArchLabs is not supported by upstream `llvm_toolchain`?

**Comment by georgercarder** [comment]
From the logs above it looks like the query is within the path `/home/me/.cache/bazel/_bazel_me/`, i.e. it's an issue with the relationship of bazel vs my system. I'm personally not familiar with Bazel as I'd tyically use gnu `make` in its place. With `make`, if a package is missing in my system I can fetch and install the package in a way tailored to my system. Being that Bazel works within that cache in  `/home/me/.cache/bazel/_bazel_me/`, I'd have to find the way Bazel wants that cached. I don't think I'm going to put more work into learning the ways of Bazel. But maybe this open issue could help others.

**Comment by prestonvanloon** [comment]
@farazdagi this is an issue with `grailbio/bazel-toolchain`. I thought arch was supported with https://github.com/grailbio/bazel-toolchain/pull/2. However it looks like "ArchLabs" doesn't match the OS name "arch" https://github.com/grailbio/bazel-toolchain/blob/e3de4f318c6615fde7b248cef7c38c1205bcc856/toolchain/tools/llvm_release_name.py#L20.


Any idea why your OS reports "ArchLabs" instead of "arch"?

**Comment by georgercarder** [comment]
Yes, the machine where this issue arose from has as its OS an arch-linux based distro called ArchLabs.

**Comment by prestonvanloon** [comment]
OK. It sounds like someone would need to add the appropriate changes upstream to `grailbio/bazel-toolchain` to support ArchLabs OS.

**Comment by 0xKiwi** [comment]
Closing as this is a toolchain issue, unrelated to prysm.
