### ISSUE TITLE
Beacon Error: gRPC panicked - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xuyenvuong** [prysmaticlabs/prysm#7380]
# 🐞 Bug Report

### Description

Upgraded to alpha.27 and get error dump as below

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: alpha.26

## 🔬 Minimal Reproduction

Upgraded from alpha.26 to alpha.27 same config.

## 🔥 Error

<pre><code>

time="2020-09-29 23:58:21" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 3041872 [running]:
runtime/debug.Stack(0x40001ec000, 0x5dcceb, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x88
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x9f45c0, 0x405c7ffc80, 0x3aebe0, 0x24c3df0, 0x1300, 0x54)
	shared/traceutil/recovery_interceptor_option.go:29 +0x110
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x9f45c0, 0x405c7ffc80, 0x3aebe0, 0x24c3df0, 0x7af708, 0x20993e8, 0x40775912e8)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x50
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x9f45c0, 0x405c7ffc80, 0x40001ac068, 0x4077591a78)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x68
panic(0x3aebe0, 0x24c3df0)
	GOROOT/src/runtime/panic.go:969 +0x11c
github.com/prysmaticlabs/prysm/beacon-chain/rpc/node.(*Server).ListPeers(0x400a6199d0, 0x9f45c0, 0x405c7ffd10, 0x4053abaa80, 0x400a6199d0, 0x405c7ffd10, 0x40001b6c40)
	beacon-chain/rpc/node/server.go:193 +0x278
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler.func1(0x9f45c0, 0x405c7ffd10, 0x568680, 0x4053abaa80, 0x3ace40, 0x263d030, 0x5315a0, 0x263cb20)
	bazel-out/aarch64-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:868 +0x7c
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0x40001b6a00, 0x9f45c0, 0x405c7ffd10, 0x568680, 0x4053abaa80, 0x4053abaaa0, 0x4053abaac0, 0x405c7ffd10, 0xa0de40, 0x263cb20, ...)
	beacon-chain/rpc/service.go:397 +0x64
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405c7ffd10, 0x568680, 0x4053abaa80, 0x612858, 0x25, 0x9f45c0, 0x405c7ffd10)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x4053abaaa0, 0x4053abaae0, 0x3, 0x3, 0xa00720, 0x401262c780)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0xfc
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x25, 0x4066a3bf40, 0x0, 0x5973a0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x4053abaaa0, 0x4053abab00, 0x20, 0x491dc0, 0x403b9559a8, 0x2302c28)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0x8c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x538949a435aab, 0x1ce27661, 0x4029902000, 0xffffa8fab560)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x4053abaaa0, 0x4053abab40, 0x0, 0x0, 0x0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:31 +0xa0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x4037fa2d00, 0x4053abaa20, 0x403b955af8, 0x1bb502c)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x9f45c0, 0x405c7ffc80, 0x568680, 0x4053abaa80, 0x4053abaaa0, 0x4053abaac0, 0x4c89c0, 0x405c7ffc80, 0x60, 0x50b360)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xbc
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler(0x499a80, 0x400a6199d0, 0x9f45c0, 0x405c7ffc80, 0x4065f303c0, 0x400a54d740, 0x9f45c0, 0x405c7ffc80, 0x0, 0x0)
	bazel-out/aarch64-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:870 +0x128
google.golang.org/grpc.(*Server).processUnaryRPC(0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4037fa2d00, 0x400a54daa0, 0x24dbc10, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1082 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4037fa2d00, 0x0)
	external/org_golang_google_grpc/server.go:1405 +0xa1c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x40002fc3c0, 0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4037fa2d00)
	external/org_golang_google_grpc/server.go:746 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:744 +0x8c
"
time="2020-09-29 23:58:21" level=info msg="Synced new block" block=0xd86f74d9... epoch=12702 finalizedEpoch=12700 finalizedRoot=0xd4c280a5... prefix=blockchain slot=406491 slotInEpoch=27
time="2020-09-29 23:58:21" level=info msg="Finished applying state transition" attestations=40 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-09-29 23:58:22" level=info msg="Verified and saved pending attestations to pool" blockRoot=d86f74d9e87f pendingAttsCount=1 prefix=sync
time="2020-09-29 23:58:30" level=info msg="Peer disconnected" activePeers=98 multiAddr="/ip4/70.79.136.182/tcp/13000/p2p/16Uiu2HAm2jvaBpXWgAsk3rAJpXmAGLjhQv93uq7qgkTgmy27k9cS" prefix=p2p
time="2020-09-29 23:58:33" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 3046789 [running]:
runtime/debug.Stack(0x40001ec000, 0x5dcceb, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x88
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x9f45c0, 0x405b69a840, 0x3aebe0, 0x24c3df0, 0x1300, 0x54)
	shared/traceutil/recovery_interceptor_option.go:29 +0x110
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x9f45c0, 0x405b69a840, 0x3aebe0, 0x24c3df0, 0x7af708, 0x20993e8, 0x4021e092e8)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x50
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x9f45c0, 0x405b69a840, 0x40001ac068, 0x4021e09a78)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x68
panic(0x3aebe0, 0x24c3df0)
	GOROOT/src/runtime/panic.go:969 +0x11c
github.com/prysmaticlabs/prysm/beacon-chain/rpc/node.(*Server).ListPeers(0x400a6199d0, 0x9f45c0, 0x405b69a8d0, 0x406e277e20, 0x400a6199d0, 0x405b69a8d0, 0x40001b6c40)
	beacon-chain/rpc/node/server.go:193 +0x278
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler.func1(0x9f45c0, 0x405b69a8d0, 0x568680, 0x406e277e20, 0x3ace40, 0x263d030, 0x5315a0, 0x263cb20)
	bazel-out/aarch64-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:868 +0x7c
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0x40001b6a00, 0x9f45c0, 0x405b69a8d0, 0x568680, 0x406e277e20, 0x406e277e40, 0x406e277e60, 0x405b69a8d0, 0xa0de40, 0x263cb20, ...)
	beacon-chain/rpc/service.go:397 +0x64
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405b69a8d0, 0x568680, 0x406e277e20, 0x612858, 0x25, 0x9f45c0, 0x405b69a8d0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x406e277e40, 0x406e277e80, 0x3, 0x3, 0xa00720, 0x401262c780)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:31 +0xfc
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x25, 0x404b880e60, 0x0, 0x5973a0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x406e277e40, 0x406e277ea0, 0x20, 0x491dc0, 0x4012f6f9a8, 0x2302c28)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:107 +0x8c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x538977bbad6ca, 0x33187a11, 0x4034972700, 0xffffa8faa7d0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x406e277e40, 0x406e277ec0, 0x0, 0x0, 0x0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:31 +0xa0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x4039d9ef00, 0x406e277da0, 0x4012f6faf8, 0x1bb502c)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:25 +0x58
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x9f45c0, 0x405b69a840, 0x568680, 0x406e277e20, 0x406e277e40, 0x406e277e60, 0x4c89c0, 0x405b69a840, 0x60, 0x50b360)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:34 +0xbc
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._Node_ListPeers_Handler(0x499a80, 0x400a6199d0, 0x9f45c0, 0x405b69a840, 0x4042ecb260, 0x400a54d740, 0x9f45c0, 0x405b69a840, 0x0, 0x0)
	bazel-out/aarch64-opt/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_arm64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/node.pb.go:870 +0x128
google.golang.org/grpc.(*Server).processUnaryRPC(0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4039d9ef00, 0x400a54daa0, 0x24dbc10, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1082 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4039d9ef00, 0x0)
	external/org_golang_google_grpc/server.go:1405 +0xa1c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x40002fc3c0, 0x400a6e0000, 0xa081c0, 0x40102ac780, 0x4039d9ef00)
	external/org_golang_google_grpc/server.go:746 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:744 +0x8c

</code></pre>

## 🌍  Your Environment

**Operating System:**
Ubuntu latest on Pi4 8GB
<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**
alpha.27
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
https://medalla.beaconcha.in/dashboard?validators=12425,12433,12437,12442,12446,12456,12457,12461,12465,12469,12473,12474,12477,12480,12487,12490,12493,12499,12504,12509,12511,12516,12521,12525,12527,12532,12542,12544,12552,12567,12568,12569,12574

**Comment by 0xKiwi** [comment]
Hello @xuyenvuong , thank you for reporting. What caused this error? Was the beacon node just running and it randomly stopped or did you attempt to cancel it?
