### ISSUE TITLE
Clear Database does not work on Windows

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#7401]
# 🐞 Bug Report

### Description

Users running with the `clear-db` flag in windows will end up with the node unable to start due to 
the OS claiming another process is currently using the db. 

### Has this worked before in a previous version?

Before Alpha.27

## 🔬 Minimal Reproduction

Run either beacon-node or validator with `--clear-db` 

## 🔥 Error

```
 WARN node: Removing database
ERROR main: could not clear database: could not remove database file: remove C:\Users\Username\AppData\Roaming\Eth2\beaconchaindata/beaconchain.db: The process cannot access the file because it is being used by another process.
ERROR FAILED
```

## 🌍  Your Environment

**Operating System:**

Windows

**What version of Prysm are you running? (Which release)**

Alpha.27

**Anything else relevant (validator index / public key)?**

**Comment by dv8silencer** [comment]
I can tackle this.

**Comment by terencechain** [comment]
assigned to @dv8silencer, thanks!
