### ISSUE TITLE
FindPeersWithSubnet does not handle connectWithPeer bad-peer case

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#7424]
Possibly a bug with finding subnet peers, looking for clarification.

### Background

Just browsing code, and noticed that [`connectWithPeer`](https://github.com/prysmaticlabs/prysm/blob/7a96412ef2fddd7aa03a2f2841a892c30d00034f/beacon-chain/p2p/service.go#L405) just returns nil without doing anything when the peer is bad. Although this seems like reasonable behavior, the callers expect a connection.

### Description

The [`FindPeersWithSubnet`](https://github.com/prysmaticlabs/prysm/blob/18b3203f31eb8e453bb13bff18a9a9e6e6cb64fa/beacon-chain/p2p/subnets.go#L24) function expects the `connectWithPeer` to actually connect, and sets `exists` to true, even though there won't be a connection to a bad peer.

**Comment by nisdas** [comment]
Thanks for reporting this @protolambda , labeling this as a bug as it is not the expected behaviour .

**Comment by rauljordan** [comment]
Any update on this one @nisdas or @farazdagi ?

**Comment by fabdarice** [comment]
I could potentially help with next. Might need some guidance on an easy way to reproduce it?
