### ISSUE TITLE
Req-resp Error responses are decoded incorrectly.

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#7425]
# 🐞 Bug Report

### Description

`ErrorResponse` is defined in the spec as a `List[byte, 256]`, not a `Container{ List[byte, 256] }`. The spec states:

> ssz_snappy: The contents are first SSZ-encoded and then compressed with Snappy frames compression. For objects containing a single field, only the field is SSZ-encoded not a container with a single field. For example, the BeaconBlocksByRoot request is an SSZ-encoded list of Root's. This encoding type MUST be supported by all clients.

And defines the error as:

> The ErrorMessage schema is:
>
>   (
>     error_message: List[byte, 256]
>   )
>
> Note: By convention, the error_message is a sequence of bytes that MAY be interpreted as a UTF-8 string (for debugging purposes). Clients MUST treat as valid any byte sequences.

The schema used in Prysm, and the type with generated FastSSZ methods, incorrectly deserialize as container.

The difference is that the first 4 bytes are being recognized as offset in the container case. And for such single-field container, it would always be `0x00000004`. Hence the spec actively avoids adding useless wrappers on responses like that.

This results in all standard-format req-resp errors not being readable when decoded in Prysm (since Prysm expects that magic useless offset), as well as all produced errors starting with zeroes when read on another client (and potentially being completely invalid because of the added 4 bytes, i.e. 260 bytes total).

### Has this worked before in a previous version?

Not that I know.

## 🔬 Minimal Reproduction

-

## 🔥 Error

None.

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

See relevant code and commit here: https://github.com/prysmaticlabs/prysm/blob/70f3fcdbd9e861dab869c7a2062f989b5ceca222/proto/beacon/p2p/v1/generated.ssz.go#L1475

**Comment by nisdas** [comment]
Thanks for reporting this @protolambda , will get this fixed by this week.
