### ISSUE TITLE
"bucket already exists" when we don't delete local DB

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#743]
I've been running into this following error when we don't delete local DB every time. It's easily reproducible on Master. 

Steps to reproduce:
1.) 
`go run main.go --datadir testdir --verbosity debug --rpc-port 4000 --genesis-json ../genesis.json --simulator --demo-config` ==> Works

2.) 
Don't delete testdir

3.)
`go run main.go --datadir testdir --verbosity debug --rpc-port 4000 --genesis-json ../genesis.json --simulator --demo-config` ==> Fails with the following:
`[2018-11-12 07:29:54] ERROR main: bucket already exists
exit status 1`

4.) 
Delete testdir

5.)
`go run main.go --datadir testdir --verbosity debug --rpc-port 4000 --genesis-json ../genesis.json --simulator --demo-config` ==> Works

**Comment by nisdas** [comment]
@terenc3t I will be tackling this after I am done with initial sync.

**Comment by nisdas** [comment]
Closed by #787
