### ISSUE TITLE
absolute vs. relative path

### ISSUE THREAD

**Issue by johanschaap** [prysmaticlabs/prysm#7431]
Just started to run both an ETH1 and beacon-node on my VPS. But I found that _only an_ **absolute path** is working to connect to the beacon-node to the ETH 1 goerli chain...

Please review both of my commands below:

![Screenshot 2020-10-04 at 22 24 28](https://user-images.githubusercontent.com/30007331/95026373-38543780-0691-11eb-8a16-878122252674.png)

The command that starts with ~/.ethereum/ is gives an Error. dv8S mentioned that this can be solved by extending the filepath...

Hope this is clear. Good luck with the dress rehearsel. I'll be there!

Best,

**Comment by nisdas** [comment]
hey @johanschaap if you do want to use the relative path you will need to remove `=` otherwise we are unable to properly parse it. So the command will be 

```
./prysm..sh beacon-chain --http-web3provider ~/.ethereum/goerli/geth.ipc
```
using `=` prevents the shell from correctly expanding the path.

**Comment by prestonvanloon** [comment]
Thanks for the workaround @nisdas. I think prysm should accept a relative path with the `=` sign. 
Any idea why it is this?

**Comment by bidlocode** [comment]
probably because the `~` is the same as `$HOME` and shell parses and replaces it with env vars before give it as args?
