### ISSUE TITLE
Prysm Wallet Recovery Not Aligned With Latest Launchpad

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7448]
# 💎 Issue

### Background

The current Zinken launchpad now supports an updated EIP2333 derivation scheme https://github.com/ethereum/eth2.0-deposit-cli/pull/108 which we are not compliant with. Unfortunately, updating Prysm to be compliant would break existing Medalla user's key recovery. This is a tracking issue for us to find a sensible way to upgrade, which would likely be through a migration tool that runs automatically for users.

**Comment by potuz** [comment]
Just my two cents: leave this incompatible. Add instructions on your website on how to use ethdo to recover  and upgrade the accounts for those users that wish to do so.
