### ISSUE TITLE
accounts-v2 import into non-existent wallet leads to error in Windows

### ISSUE THREAD

**Issue by dv8silencer** [prysmaticlabs/prysm#7455]
# 🐞 Bug Report

### Description
If you `accounts-v2 import --key-dir /path/to/keys` in Windows it will lead to:

`FATAL accounts-v2: Could not import accounts: could not initialize wallet: could not check if wallet exists: could not check if dir is valid: open C:\Users\dv8si\AppData\Roaming\Eth2Validators\prysm-wallet-v2: The system cannot find the path specified.`

if the wallet directory does not already exist.

Issue might have root in accounts/v2/wallet/wallet.go where OpenWalletOrElseCli() calls Exists() where even if HasDir returns (false, nil), it attempts the IsValid() check which tries to open the path even if the directory does not exist.  This leads to the error which

```
	if err != nil {
		if strings.Contains(err.Error(), "no such file") {
			return false, nil
		}
		return false, err
	}
```
tries to look for but the wording of that message may be specific to Linux.

### Has this worked before in a previous version?
I don't recall when the last time I did detailed testing in Windows for import was.  I know I have and this wasn't an issue before.   #7400 may have introduced it.

## 🔬 Minimal Reproduction

See above.

## 🔥 Error

See above

## 🌍  Your Environment

**Operating System:**

Windows 10

**What version of Prysm are you running? (Which release)**

alpha.28

**Anything else relevant (validator index / public key)?**

No

**Comment by prestonvanloon** [comment]
@rauljordan can you take a look to see if this is related to changes in #7400 please?
