### ISSUE TITLE
Enable/Disable Validator Keys

### ISSUE THREAD

**Issue by MysticRyuujin** [prysmaticlabs/prysm#7485]
# 🚀 Feature Request

### Description

I would like the ability to enable/disable validator keys on the fly without having to delete and/or re-import the keys.

### Describe the solution you'd like

Lighthouse has a simple `enabled: true|false` flag that can be set on a per-validator entry:
https://lighthouse-book.sigmaprime.io/validator-management.html

I would like the ability to do something similar. This would allow more flexibility and portability between validator clients when using an external wallet management system. In the event that Lighthouse or Prysm encounters a bug / DDoS / etc. this would help in being able to flip a switch and move validator clients without worrying about your Prysm validator coming back online and double signing. It would allow for more rapid testing between clients, etc.

This could either be a command like `accounts-v2 enable|disable` or it could just be a key we could set inside `all-accounts.keystore.json` or something? :man_shrugging:

I just feel like enable/disable is better than delete and re-import most of the time.

### Describe alternatives you've considered

Obviously there are risks in running dual validator setups (active/standy), but this would LESSEN that risk for those of us that want to experiment.

**Comment by 0xKiwi** [comment]
Thanks for the suggestion @MysticRyuujin !

@rauljordan , do you think this is a feature we can implement? Might be useful and not too bad to implement.

**Comment by MysticRyuujin** [comment]
fwiw @rauljordan asked me to open this issue and said it should be doable, over on discord.

**Comment by metanull-operator** [comment]
Consider whether an enable/disable "all" option would be appropriate in any related commands. It seems convenient, but it may not be desirable for other reasons.

**Comment by fabdarice** [comment]
If needed, I'll be happy to tackle this one.

**Comment by terencechain** [comment]
@fabdarice sounds good, thanks!

**Comment by fabdarice** [comment]
Will tackle this, keeping y'all posted.

**Comment by fabdarice** [comment]
Continuing the discussion here @rauljordan .
> Thanks @fabdarice, do you think we can get this wrapped up within a week? We should discuss the approach to this issue. One way we could do it is:

>1) Inside of the keymanageropts.json file within a wallet, we can store a "disabled_validators": [pubkey] entry and exclude those validators when initializing the keymanager (both imported and derived)
> 2) Define enable and disable commands under prysm.sh validator accounts, which will allow a user to perform selection similar to accounts backup and delete. These commands will essentially write to the keymanageropts.json file as needed

I was thinking of doing 2, which in my opinion is easier for the average joe.
