### ISSUE TITLE
Deposit processed, entering activation queue after finalization

### ISSUE THREAD

**Issue by kirkyb** [prysmaticlabs/prysm#7493]
# 💎 Issue

### Background

 My 32 GoETH has been processed but the prysm.bat validator appears to be stuck at "Deposit processed, entering activation queue after finalization" for over 6 hours now.
Is this normal behaviour?

Thanks.

**Comment by 0xKiwi** [comment]
Hello, this is normal behavior as there may not be finalization yet or the queue is extremely long.
