### ISSUE TITLE
web ui should require wallet password only when needed

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#7505]
When running the validator with --web flag, the browser asks for the wallet password on the first time you open the webpage. I think the user should be able to provide an arbitrary unrelated password to access monitoring features and be requested the wallet password when required to perform actions on the wallet itself or some of the accounts.

**Comment by bidlocode** [comment]
+1 it's really important for security reasons also

**Comment by potuz** [comment]
Should this be closed by #7569 ?
