### ISSUE TITLE
Remove feature flags for beta

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7509]
This issue tracks the follow of the following + rationales:

* Delete the following feature flags:
    * `disable-fork-choice-unsafe`: This is an unsafe flag. It hasn't been used in a while. This was designed in Sapphire days for emergency recovery. #7511
    * `disable-ssz-cache`: This hasn't been used in a while. This was designed in Topaz days for emergency recover. #7513
    * `skip-bls-verify`: This hasn't been used in a while. This was designed in Topaz days for emergency recover.  #7516
    * `disable-initial-sync-verify-all-signatures`: This is an unsafe flag. One can easily trick a requesting peer to a malicious chain. #7517
    * `cache-filtered-block-tree`: This has been deprecated ever since we move to proto array fork choice. This flag is doing nothing. Safe to delete. #7511
    * `enable-local-protection`: This should be default on mainnet, it has been default `true` for a while. Safe to delete. \
#7543
    * `disable-strict-attestation-pubsub-verification`: This is an unsafe flag and was only used once during Topaz testnet. #7526
    * `disable-update-head-attestation`: This is an unsafe flag and used during Sapphire testnet. #7533
    * `disable-domain-data-cache`: This has been enabled by default since Topaz testnet. Safe to delete.  #7526
    * `enable-state-gen-sig-verify`: This was an option but it was never used. Safe to delete #7526
    * `check-head-state`: This was an old feature from Sapphire testnet. Safe to delete. #7511
    * `dont-prune-state-start-up`: This was an old feature before stategen pkg. Safe to delete. #7511
    * `disable-reduce-attester-state-copy`: This has been enabled since Sapphire testnet. Safe to delete. #7526
    * `disable-new-beacon-state-locks`: This has been enabled since Onyx testnet. Safe to delete. #7533
    * `disable-batch-block-verify`: This has been enabled for a month. Safe to delete. #7526
    * `init-sync-verbose`: This has not been used. Safe to delete. #7533
    * `disable-accounts-v2`: We want to use v2 for beta. Safe to delete.
    * `enable-att-broadcast-discovery-attempts`: (Won't be removed, this needs to be inverted)
    * `disable-broadcast-slashings`: Unsafe flag. The node should broadcast slashing by default.  #7533
    * `wait-for-synced`: I dont think this was used in a while. Will delete if no one further comments (Won't be removed, incomplete feature)

 * Delete all **deprecated** feature flags #7512

**Comment by terencechain** [comment]
Questions for @rkapka 

Can I delete these two flags?
    * disable-finalized-deposits-cache
    * enable-eth1-data-majority-vote

**Comment by rkapka** [comment]
> disable-finalized-deposits-cache

Yes

> enable-eth1-data-majority-vote

No - please see #7362. It requires an optimization PR that @nisdas is working on. We might be able to invert the flag without the optimization, but it might result in a lot of `BlockExists` calls, which send requests to the ETH1 endpoint.

**Comment by terencechain** [comment]
Questions for @nisdas, can i delete the following flags?
* enable-att-broadcast-discovery-attempts
* disable-dynamic-committee-subnets
* disable-noise

**Comment by terencechain** [comment]
`disable-finalized-deposits-cache` was removed in #7533

**Comment by kwood** [comment]
I'm confused as to why `disable-broadcast-slashings` was removed? Broadcasting currently removes all incentive to run a slasher, as 100% of the whistleblower reward currently goes to the proposer. The explanation above `The node should broadcast slashing by default` doesn't really make sense, that already was the default. Is there something else unsafe about not broadcasting slashings?
