### ISSUE TITLE
Update ValidatorRegistration Contract as Per the Latest Spec

### ISSUE THREAD

**Issue by zincoshine** [prysmaticlabs/prysm#751]
Update ValidatorRegistration contract as per the latest spec

The initial deployment phases of Ethereum 2.0 are implemented without consensus changes to the PoW chain. A registration contract is added to the PoW chain to deposit ETH. This contract has a registration function which takes as arguments pubkey, withdrawal_shard, withdrawal_address, randao_commitment as defined in a ValidatorRecord below. A BLS proof_of_possession of types bytes is given as a final argument.

The registration contract emits a log with the various arguments for consumption by the beacon chain. It does not do validation, pushing the registration logic to the beacon chain. In particular, the proof of possession (based on the BLS12-381 curve) is not verified by the registration contract.

A PR that would resolve this issue would be to update the current Validator Registration Contract by adding in a proof of possesion parameter to the deposit function.

**Comment by zincoshine** [comment]
I am happy to work on this one.

**Comment by nisdas** [comment]
Awesome :) , assigned to @zincoshine

**Comment by nisdas** [comment]
@zincoshine Could you elaborate what is the issue that needs to be dealt with in modifying the VRC above in the issue decription. The current description just describes what the VRC is

**Comment by zincoshine** [comment]
proof of possession should also be passed as a parameter to the deposit function. @nisdas

**Comment by nisdas** [comment]
@zincoshine Any updates on this ?

**Comment by nisdas** [comment]
@terenc3t Can this be closed now ?

**Comment by terenc3t** [comment]
I
