### ISSUE TITLE
Duplicate Exit Throws Error

### ISSUE THREAD

**Issue by metanull-operator** [prysmaticlabs/prysm#7534]
# 🐞 Bug Report

### Description

Running 5 validators on Zinken, and I wanted to attempt an exit. Using prysm.sh I ran the command to exit and select 1 validator to exit. After seeing that my validator appeared on the exit queue, I ran prysm.sh again to exit my remaining validators. I selected the "all" option to exit all validators, not realizing that my previously exited validator is still in the list. 

Output seems to indicate that the four new exits were processed correctly, but the error message around the previously-exited validator is not pretty.

### Has this worked before in a previous version?

Never tried it before.

## 🔬 Minimal Reproduction

Exit one key, then exit that same key and more.

## 🔥 Error

<pre><code>
If you still want to continue with the voluntary exit, please input the passphrase from the above URL:
Exit my validator
[2020-10-14 17:20:58]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2020-10-14 17:20:58] ERROR accounts-v2: voluntary exit failed for account 0xXXXXXXXXXXXX error=rpc error: code = InvalidArgument desc = validator has already submitted an exit, which will take place at epoch: 561
failed to propose voluntary exit
github.com/prysmaticlabs/prysm/validator/client.ProposeExit
        validator/client/propose.go:157
github.com/prysmaticlabs/prysm/validator/accounts/v2.performExit
        validator/accounts/v2/accounts_exit.go:196
github.com/prysmaticlabs/prysm/validator/accounts/v2.ExitAccountsCli
        validator/accounts/v2/accounts_exit.go:61
github.com/prysmaticlabs/prysm/validator/accounts/v2.glob..func6
        validator/accounts/v2/cmd_accounts.go:160
github.com/urfave/cli/v2.(*Command).Run
        external/com_github_urfave_cli_v2/command.go:164
github.com/urfave/cli/v2.(*App).RunAsSubcommand
        external/com_github_urfave_cli_v2/app.go:427
github.com/urfave/cli/v2.(*Command).startApp
        external/com_github_urfave_cli_v2/command.go:279
github.com/urfave/cli/v2.(*Command).Run
        external/com_github_urfave_cli_v2/command.go:94
github.com/urfave/cli/v2.(*App).RunContext
        external/com_github_urfave_cli_v2/app.go:306
github.com/urfave/cli/v2.(*App).Run
        external/com_github_urfave_cli_v2/app.go:215
main.main
        validator/main.go:354
runtime.main
        GOROOT/src/runtime/proc.go:203
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-10-14 17:20:58]  INFO accounts-v2: Voluntary exit was successful for the accounts listed publicKeys=0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.29
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rkapka** [comment]
Hi there!

This is how Prysm currently handles error logging. Because you wanted to exit a validator that had already exited, an error occurred and was logged out to the terminal. I understand that it's a bit unusual to see an error message and a success message during one command execution, but that's just how it is at the moment.

We might consider changing it in the future. Thank you for submitting the issue.

**Comment by metanull-operator** [comment]
Hi. My issue is the stack trace, not the fact that there are two error messages. Stack traces aren't particularly user friendly.

**Comment by metanull-operator** [comment]
@rkapka

**Comment by rkapka** [comment]
Should be fixed in the next release @metanull-operator
