### ISSUE TITLE
Waiting for beacon node to sync to latest chain head

### ISSUE THREAD

**Issue by kirkyb** [prysmaticlabs/prysm#7548]
I've been having trouble getting Prysm to work, it was working perfectly fine 2-3 days ago but now I am receiving the error "Waiting for beacon node to sync to latest chain head"

How do I go about fixing this issue please?

I have updated Geth and Prysm so I'm running on the latest releases.

**Comment by rkapka** [comment]
Hi @kirkyb 

Could you clarify a little bit? From what I understand your beacon node is fully synced, but the validator displays a message suggesting that it's not. Can you please provide some logs for both the node and the validator?

**Comment by pasajeros** [comment]
I have the same problem. Already for weeks. Ubuntu 20.04 on Raspberry Pi, latest packages from repository:
prysm-beacon/now 1.0.0-alpha29-0 arm64 [installed,local]
prysm-slasher/now 1.0.0-alpha29-0 arm64 [installed,local]
prysm-validator/now 1.0.0-alpha29-0 arm64 [installed,local]

Please tell me what you need to investigate? I added the logs for the node and validator.
[validator.log](https://github.com/prysmaticlabs/prysm/files/5430011/validator.log)
[beaconchain.log](https://github.com/prysmaticlabs/prysm/files/5430013/beaconchain.log)

**Comment by nisdas** [comment]
@kirkyb @pasajeros Please update both beacon node and validator to our latest release the issue has been fixed.

**Comment by pasajeros** [comment]
@nisdas do you know what release and which repository to use for Ubuntu 20.04 on arm64 (Raspberry Pi)? Because now "sudo apt update" doesn't show a new release.

**Comment by nisdas** [comment]
ah k, I am not sure about that. The current ethereum on ARM images might not be updated to beta yet. 
cc @diglos

**Comment by kirkyb** [comment]
I'm currently running on the 1.00 beta for both validator and beacon chain. I think the issue I'm facing is that the validators are currently running at <66% network participation so the chains aren't being finalised.

**Comment by ChuckNorrison** [comment]
no peers here with currenz pre release beta.0 since restarting the service yesterday. Ports are all open and avaiable public after `--rpc-host` was used (4000 and custom p2p ports 13001 tcp, 12001 udp). Did not found any reasons besides broken libp2p

**Comment by rauljordan** [comment]
No longer the case in beta.1

**Comment by keithyau** [comment]
![image](https://github.com/prysmaticlabs/prysm/assets/659311/e4a390d2-2a4f-42f8-979d-b74e9208418e)
it happens again in 2024
