### ISSUE TITLE
Clarify argument `--http-web3provider` required format

### ISSUE THREAD

**Issue by Neozaru** [prysmaticlabs/prysm#7553]
# 🚀 Feature Request

### Description

About this part of the doc : 
 
![image](https://user-images.githubusercontent.com/1905292/96283458-88f65980-0fdc-11eb-8b05-61b43122d725.png)

Quick feedback on that part : I tried to set `--http-web3provider=localhost`, then `--http-web3provider=127.0.0.1`. Took me a while to realize that the full string was required (`--http-web3provider=http://localhost:8545`).

### Describe the solution you'd like

- The most trivial solution is to update the doc so people like me can understand what is the required string format.
- Another solution is to assume that HTTP is used by default - and eventually using the default port when not specified. The risk of using default values is to connect to the wrong node when an user runs multiple `geth` instances.

**Comment by rauljordan** [comment]
Fixed by https://github.com/prysmaticlabs/documentation/pull/256
