### ISSUE TITLE
Panic index out of range during initial sync

### ISSUE THREAD

**Issue by bidlocode** [prysmaticlabs/prysm#7558]
# 🐞 Bug Report

## 🔥 Error
<pre><code>
beacon       | time="2020-10-17 09:30:05" level=info msg="Peer disconnected" activePeers=98 multiAddr="/ip4/15.207.63.236/tcp/9001/p2p/16Uiu2HAmB3fTGtZ49VT6mVWg4mavkY2JeGyVrgg9eHcohUAUENhT" prefix=p2p
beacon       | time="2020-10-17 09:30:08" level=info msg="Peer disconnected" activePeers=97 multiAddr="/ip4/167.86.116.134/tcp/9000/p2p/16Uiu2HAm1mj3S8m7DB6jwd2RKeMHLJSCTsENuZyA2LGvsT7EvWm2" prefix=p2p
beacon       | time="2020-10-17 09:30:12" level=info msg="Processing block batch of size 50 starting from  0x5926f67a... 386694/531750 - estimated time remaining 4h5m26s" blocksPerSecond=9.8 peers=97 prefix=initial-sync
beacon       | time="2020-10-17 09:30:17" level=info msg="Processing block batch of size 52 starting from  0xec9eca48... 386758/531750 - estimated time remaining 5h3m57s" blocksPerSecond=8.0 peers=97 prefix=initial-sync
beacon       | time="2020-10-17 09:30:18" level=info msg="Peer connected" activePeers=99 direction=Outbound multiAddr="/ip4/95.217.215.48/tcp/9000/p2p/16Uiu2HAkzPkLiBA3aLLD5iAgmW2vLf8xemZQRxD5FsjNG8xa3c8B" prefix=p2p
beacon       | time="2020-10-17 09:30:23" level=info msg="Processing block batch of size 53 starting from  0x129c1492... 386822/531751 - estimated time remaining 3h47m52s" blocksPerSecond=10.6 peers=98 prefix=initial-sync
beacon       | time="2020-10-17 09:30:28" level=info msg="Peer connected" activePeers=100 direction=Outbound multiAddr="/ip4/135.181.17.60/tcp/11001/p2p/16Uiu2HAm54bj9NpJqXC1EpVkfts5ty8n3GrTUJhcm5ZNJnkxNZfV" prefix=p2p
beacon       | panic: runtime error: index out of range [281474976727722] with length 73246
beacon       | 
beacon       | goroutine 248 [running]:
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.handleValidatorSlice(0xc0a3f04000, 0x11e1e, 0x11e1e, 0xc08bc16a00, 0x691, 0x691, 0xc00aeefe00, 0x905344d0, 0x8eb182d76c4dfd81, 0xc00aeeff20, ...)
beacon       | 	beacon-chain/state/field_trie.go:257 +0x27e
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.fieldConverters(0xb, 0xc08bc16a00, 0x691, 0x691, 0x2f92a0, 0xc066034a80, 0x11500, 0xc050d9aee0, 0xc00aef0060, 0x173e4d1, ...)
beacon       | 	beacon-chain/state/field_trie.go:164 +0x92d
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.(*FieldTrie).RecomputeTrie(0xc058f53dd0, 0xc08bc16a00, 0x691, 0x691, 0x2f92a0, 0xc066034a80, 0x0, 0x0, 0x0, 0x0, ...)
beacon       | 	beacon-chain/state/field_trie.go:78 +0x15f
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).recomputeFieldTrie(0xc050d9aee0, 0xb, 0x2f92a0, 0xc066034a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/state_trie.go:385 +0x371
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).rootSelector(0xc050d9aee0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/state_trie.go:319 +0xffd
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).HashTreeRoot(0xc050d9aee0, 0xa0b120, 0xc05f992930, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/state_trie.go:196 +0x2c1
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/core/state.ProcessSlot(0xa0b120, 0xc05f992930, 0xc050d9aee0, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/core/state/transition.go:222 +0x1ce
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.processSlotsStateGen(0xa0b120, 0xc05f992900, 0xc050d9aee0, 0x5e701, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/stategen/replay.go:160 +0x184
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.executeStateTransitionStateGen(0xa0b120, 0xc05f9928d0, 0xc050d9aee0, 0xc01bc16780, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/stategen/replay.go:123 +0x150
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).ReplayBlocks(0xc0009f1440, 0xa0b120, 0xc05f9928a0, 0xc050d9aee0, 0xc025d49f00, 0x1a, 0x20, 0x5e71f, 0x0, 0x0, ...)
beacon       | 	beacon-chain/state/stategen/replay.go:32 +0x18d
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).loadStateByRoot(0xc0009f1440, 0xa0b120, 0xc076717bf0, 0xad6ced9530eb7bf9, 0x52dbda426d13ff72, 0x2b7cdbe81301281e, 0xbc8727f00373e2da, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/stategen/getter.go:195 +0x44f
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/state/stategen.(*State).StateByRoot(0xc0009f1440, 0xa0b120, 0xc076717b30, 0xad6ced9530eb7bf9, 0x52dbda426d13ff72, 0x2b7cdbe81301281e, 0xbc8727f00373e2da, 0x0, 0x0, 0x0)
beacon       | 	beacon-chain/state/stategen/getter.go:44 +0x256
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).cacheJustifiedStateBalances(0xc0000efa00, 0xa0b120, 0xc095074810, 0xad6ced9530eb7bf9, 0x52dbda426d13ff72, 0x2b7cdbe81301281e, 0xbc8727f00373e2da, 0x0, 0x0)
beacon       | 	beacon-chain/blockchain/head.go:299 +0x457
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).updateJustifiedInitSync(0xc0000efa00, 0xa0b120, 0xc095074810, 0xc0936ffc80, 0xd21d7417f6177a8e, 0xc04c9e5240)
beacon       | 	beacon-chain/blockchain/process_block_helpers.go:215 +0xe6
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).handleBlockAfterBatchVerify(0xc0000efa00, 0xa0b120, 0xc095074810, 0xc04c9e5200, 0xe9aba9b3faf6fbda, 0x2c0557afcc806b43, 0x15a09db0dbb5dca6, 0xd21d7417f6177a8e, 0xc0936ffcc0, 0xc0936ffc80, ...)
beacon       | 	beacon-chain/blockchain/process_block.go:310 +0x2c1
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockBatch(0xc0000efa00, 0xa0b120, 0xc095074810, 0xc080041800, 0x35, 0x40, 0xc074925100, 0x35, 0x35, 0x0, ...)
beacon       | 	beacon-chain/blockchain/receive_block.go:127 +0x374
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks(0xc000013c80, 0xa0b060, 0xc006b165c0, 0x0, 0xed6bb52d8, 0x2a1a4c0, 0xc080041800, 0x35, 0x40, 0xc000e8d228, ...)
beacon       | 	beacon-chain/sync/initial-sync/round_robin.go:253 +0x797
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData(0xc000013c80, 0xa0b060, 0xc006b165c0, 0x0, 0xed6bb52d8, 0x2a1a4c0, 0x5e704, 0xc08725c750)
beacon       | 	beacon-chain/sync/initial-sync/round_robin.go:114 +0x14c
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync(0xc000013c80, 0x0, 0xed6bb52d8, 0x2a1a4c0, 0x0, 0x0)
beacon       | 	beacon-chain/sync/initial-sync/round_robin.go:66 +0x465
beacon       | github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc000013c80)
beacon       | 	beacon-chain/sync/initial-sync/service.go:111 +0x922
beacon       | created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
beacon       | 	shared/service_registry.go:46 +0x23e
</code></pre>

## 🌍  Your Environment
<pre><code>linux docker
gcr.io/prysmaticlabs/prysm/beacon-chain@sha256:f08861f9690356872b0b02db3daf9c5b344b6f49f1ec5ec681b9e595f824343e</code></pre>

**Comment by rauljordan** [comment]
@bidlocode we have spent time attempting to diagnose the code path based on the stack trace above, and it is impossible for us to determine what led to this condition. It seems there might have been some crazy memory corruption occurring when you had this panic. We have now handled the code so there will no longer be a panic if this happens again, but unfortunately will have to close this unless it arises once more
