### ISSUE TITLE
Memory usage increases significantly during non-finality

### ISSUE THREAD

**Issue by emansipater** [prysmaticlabs/prysm#7585]
# 💎 Issue

Memory usage has been all over the place during the recent non-finality on Medalla, but reached a peak for me of 7.85 GiB and is routinely bumping over 6 GiB.

### Background

It's been tough for Dappnode to keep up with all the releases lately, but these numbers are based on the current dappnode stable package for Prysm on Medalla (v1.0.0-alpha.27).  Lighthouse [has a similar problem](https://github.com/sigp/lighthouse/issues/1795). 

### Description

There is a lot more memory consumption happening during non-finality than the recommended specs in most guides tell you to plan for. Does all this memory help with performance during non-finality?  Then the recommended specs should be increased.  And if it doesn't, then this is a performance problem that should be fixed.  Non-finality periods are exactly the times that nodes need to be rock-solid and not having performance constraints hurt them.

**Comment by terencechain** [comment]
Finality was reached on 11/3 ~230pm pst.

My Prysm beacon node memory has been around 5GB for the last 2 weeks. 

We can close this for now. Let's re-open if memory spikes up again
