### ISSUE TITLE
Script warns for --<testnet> flag even when it's provided in configuration file

### ISSUE THREAD

**Issue by Djadih** [prysmaticlabs/prysm#7592]
# 🐞 Bug Report

### Description

The script warns/reminds the user to specify the --<testnet> flag, despite the user providing that information in the configuration file.

### Has this worked before in a previous version?

Probably did not work in a previous version, as this warning is pretty recent.

## 🔬 Minimal Reproduction

Create a config-file example.yaml with the following contents:
`datadir: '<the dir where you want the contents stored>'`
`http-web3provider: '<your web3 provider, in my case Geth running on a local machine>'`
`p2p-max-peers: 70`
`testnet: 'medalla'`

Start the beacon-chain with that config file:
`./prysm.sh beacon-chain --config-file=./example.yaml` 

## 🔥 Error

<pre><code>
Latest Prysm version is v1.0.0-beta.0.rc.
Beacon chain is up to date.
Verifying binary integrity.
beacon-chain-v1.0.0-beta.0.rc-linux-arm64: OK
gpg: Signature made Tue Oct 20 15:50:06 2020 UTC
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /home/ubuntu/prysm/dist/beacon-chain-v1.0.0-beta.0.rc-linux-arm64 has been signed by Prysmatic Labs.
Starting Prysm beacon-chain --config-file=./example.yaml
[2020-10-21 06:12:56]  WARN flags: --[testnet] flag is not specified (default: Medalla), this will become required from next release! 
[2020-10-21 06:12:56]  INFO flags: Using "max_cover" strategy on attestation aggregation

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain-v1.0.0-beta.0.rc-linux-arm64
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
Pretty sure a simple fix that would increase modularity would be to make this a key/value flag like the others. Where "--testnet" is the key and "medalla" is the value.
Also, the warning message suggests using "Medalla" with a capital "M" is incorrect. Inputting that even on the command line leads to an unrecognized flag. It should "medalla" with a lowercase m.

**Comment by prestonvanloon** [comment]
cc: @bidlocode

**Comment by bidlocode** [comment]
In yaml it's `medalla: true`
When you provide a flag you see a different warning like this `WARN flags: Running on Medalla Testnet`. It's ok.
All available flags and correct way of specifing them are in `--help`.
