### ISSUE TITLE
beacon-chain fails to sync to head

### ISSUE THREAD

**Issue by jerryji** [prysmaticlabs/prysm#7636]
# 🐞 Bug Report

### Description

 beacon-chain fails to sync to head, seems to be related to `--head-sync`

### Has this worked before in a previous version?

 Never observed similar issue in previous versions

## 🔬 Minimal Reproduction

Not sure how this issue can be reproduced deterministically, the key arguments used were `--head-sync --blst --medalla`, and the sync issue did go away after removing `--head-sync`

## 🔥 Error

The behaviour is beacon-chain forever (i.e., for more than an hour) reported a few seconds behind the head while system resources (4 CPU, 16G RAM, SSD) usage was all under 50%

A snippet of the log --

[beacon-chain--blst--head-sync--medalla.txt](https://github.com/prysmaticlabs/prysm/files/5434212/beacon-chain--blst--head-sync--medalla.txt)

Nishant thinks I got into "sync loop" --

![image](https://user-images.githubusercontent.com/83122/97099745-71e3f580-16c7-11eb-889c-ebd3ee268c19.png)

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

compiled from master with `bazel build //beacon-chain:beacon-chain --config=release`

<pre>
  <code>
Prysm/v1.0.0-beta.0.rc/544dac298aa5bca9ead72559737c77c45ab1a79a
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by ChuckNorrison** [comment]
mine is missing peers at spadina testnet after update and reboot. This is running with 0 peers after hours of config tweaking, i cant find a reason. Lighthouse has the same issue with current release and zinken testnet.

**Comment by yorickdowne** [comment]
@ChuckNorrison Spadina and Zinken are done, they also do not support discv5.1. The longer-running testnet is Medalla.

**Comment by rauljordan** [comment]
this has since been resolved in 1.0.0-beta.1, please let us know if the issue persists and we can reopen @jerryji
