### ISSUE TITLE
Beacon node repeatedly processes the same blocks

### ISSUE THREAD

**Issue by rev3ks** [prysmaticlabs/prysm#7639]
# 🐞 Bug Report

### Description
logs repeatedly process the same blocks, never making any progress. Checked if this was a known issue or user error in discord and was directed to open a ticket. I saw this behavior when using --head-sync option. I may have nuked the database on a previous restart, so I am guessing it did not have up to date state to start from.

### Has this worked before in a previous version?
Never tried in a previous version

## 🔬 Minimal Reproduction
I was able to reproduce just by rebooting my machine and rerunning. But the state of the database may be the issue here, to get to this state I had rebooted without remembering to add --head-sync (my intent was to test the command). The beacon node started on reboot via a script. I then modified my boot script to add --head-sync hoping I might be able to try again and rebooted again. Before rebooting the first time the beacon node was synced. 

## 🔥 Error
error manifested in repeated logs processing the same block
<pre><code>
time="2020-10-25 01:02:49" level=info msg="Processing block 0xbe8a3eb7... 531360/588613 - estimated time remaining 1h37m52s" blocksPerSecond=9.8 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0x8fdf8081... 531520/588613 - estimated time remaining 1h19m57s" blocksPerSecond=11.9 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0xe53d989c... 531552/588613 - estimated time remaining 1h16m4s" blocksPerSecond=12.5 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0x74b202ce... 531584/588613 - estimated time remaining 1h12m33s" blocksPerSecond=13.1 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0xf7efce0b... 531616/588613 - estimated time remaining 1h9m20s" blocksPerSecond=13.7 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0x40a26321... 531744/588613 - estimated time remaining 59m25s" blocksPerSecond=15.9 peers=30 prefix=initial-sync
time="2020-10-25 01:02:50" level=info msg="Processing block 0x7eb1a632... 531808/588613 - estimated time remaining 56m41s" blocksPerSecond=16.7 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0xbe8a3eb7... 531360/588614 - estimated time remaining 1h29m35s" blocksPerSecond=10.7 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0x8fdf8081... 531520/588614 - estimated time remaining 1h14m20s" blocksPerSecond=12.8 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0xe53d989c... 531552/588614 - estimated time remaining 1h10m58s" blocksPerSecond=13.4 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0x74b202ce... 531584/588614 - estimated time remaining 1h7m53s" blocksPerSecond=14.0 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0xf7efce0b... 531616/588614 - estimated time remaining 1h5m3s" blocksPerSecond=14.6 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0x40a26321... 531744/588614 - estimated time remaining 56m15s" blocksPerSecond=16.9 peers=30 prefix=initial-sync
time="2020-10-25 01:02:57" level=info msg="Processing block 0x7eb1a632... 531808/588614 - estimated time remaining 53m47s" blocksPerSecond=17.6 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0xbe8a3eb7... 531360/588614 - estimated time remaining 1h0m35s" blocksPerSecond=15.8 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0x8fdf8081... 531520/588614 - estimated time remaining 53m9s" blocksPerSecond=17.9 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0xe53d989c... 531552/588614 - estimated time remaining 51m24s" blocksPerSecond=18.5 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0x74b202ce... 531584/588614 - estimated time remaining 49m45s" blocksPerSecond=19.1 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0xf7efce0b... 531616/588614 - estimated time remaining 48m13s" blocksPerSecond=19.7 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0x40a26321... 531744/588614 - estimated time remaining 43m10s" blocksPerSecond=21.9 peers=30 prefix=initial-sync
time="2020-10-25 01:03:04" level=info msg="Processing block 0x7eb1a632... 531808/588614 - estimated time remaining 41m42s" blocksPerSecond=22.7 peers=30 prefix=initial-sync
time="2020-10-25 01:03:07" level=info msg="Processing block 0xbe8a3eb7... 531360/588614 - estimated time remaining 40m31s" blocksPerSecond=23.6 peers=30 prefix=initial-sync
time="2020-10-25 01:03:10" level=info msg="Processing block 0x8fdf8081... 531520/588615 - estimated time remaining 53m9s" blocksPerSecond=17.9 peers=30 prefix=initial-sync
time="2020-10-25 01:03:10" level=info msg="Processing block 0xe53d989c... 531552/588615 - estimated time remaining 51m24s" blocksPerSecond=18.5 peers=30 prefix=initial-sync
time="2020-10-25 01:03:10" level=info msg="Processing block 0x74b202ce... 531584/588615 - estimated time remaining 49m45s" blocksPerSecond=19.1 peers=30 prefix=initial-sync
time="2020-10-25 01:03:10" level=info msg="Processing block 0xf7efce0b... 531616/588615 - estimated time remaining 48m13s" blocksPerSecond=19.7 peers=30 prefix=initial-sync
time="2020-10-25 01:03:11" level=info msg="Processing block 0x40a26321... 531744/588615 - estimated time remaining 43m10s" blocksPerSecond=21.9 peers=30 prefix=initial-sync
time="2020-10-25 01:03:11" level=info msg="Processing block 0x7eb1a632... 531808/588615 - estimated time remaining 41m42s" blocksPerSecond=22.7 peers=30 prefix=initial-sync
time="2020-10-25 01:03:18" level=info msg="Processing block 0xbe8a3eb7... 531360/588615 - estimated time remaining 1h0m35s" blocksPerSecond=15.8 peers=28 prefix=initial-sync
time="2020-10-25 01:03:19" level=info msg="Processing block 0x8fdf8081... 531520/588615 - estimated time remaining 53m9s" blocksPerSecond=17.9 peers=28 prefix=initial-sync
time="2020-10-25 01:03:20" level=info msg="Processing block 0xe53d989c... 531552/588616 - estimated time remaining 51m24s" blocksPerSecond=18.5 peers=28 prefix=initial-sync
time="2020-10-25 01:03:20" level=info msg="Processing block 0x74b202ce... 531584/588616 - estimated time remaining 49m45s" blocksPerSecond=19.1 peers=28 prefix=initial-sync
time="2020-10-25 01:03:20" level=info msg="Processing block 0xf7efce0b... 531616/588616 - estimated time remaining 48m13s" blocksPerSecond=19.7 peers=28 prefix=initial-sync
time="2020-10-25 01:03:20" level=info msg="Processing block 0x40a26321... 531744/588616 - estimated time remaining 43m10s" blocksPerSecond=21.9 peers=28 prefix=initial-sync
time="2020-10-25 01:03:22" level=info msg="Processing block 0xbe8a3eb7... 531360/588616 - estimated time remaining 42m7s" blocksPerSecond=22.6 peers=28 prefix=initial-sync
time="2020-10-25 01:03:23" level=info msg="Processing block 0x8fdf8081... 531520/588616 - estimated time remaining 38m22s" blocksPerSecond=24.8 peers=28 prefix=initial-sync
time="2020-10-25 01:03:23" level=info msg="Processing block 0xe53d989c... 531552/588616 - estimated time remaining 37m26s" blocksPerSecond=25.4 peers=28 prefix=initial-sync
time="2020-10-25 01:03:23" level=info msg="Processing block 0x74b202ce... 531584/588616 - estimated time remaining 36m33s" blocksPerSecond=26.0 peers=28 prefix=initial-sync
time="2020-10-25 01:03:23" level=info msg="Processing block 0xf7efce0b... 531616/588616 - estimated time remaining 35m42s" blocksPerSecond=26.6 peers=28 prefix=initial-sync
time="2020-10-25 01:03:24" level=info msg="Processing block 0x40a26321... 531744/588616 - estimated time remaining 32m51s" blocksPerSecond=28.9 peers=28 prefix=initial-sync
time="2020-10-25 01:03:24" level=info msg="Processing block 0x7eb1a632... 531808/588616 - estimated time remaining 31m59s" blocksPerSecond=29.6 peers=28 prefix=initial-sync
time="2020-10-25 01:03:27" level=info msg="Processing block 0xbe8a3eb7... 531360/588616 - estimated time remaining 42m7s" blocksPerSecond=22.6 peers=28 prefix=initial-sync
time="2020-10-25 01:03:27" level=info msg="Processing block 0x8fdf8081... 531520/588616 - estimated time remaining 38m22s" blocksPerSecond=24.8 peers=28 prefix=initial-sync
time="2020-10-25 01:03:27" level=info msg="Processing block 0xe53d989c... 531552/588616 - estimated time remaining 37m26s" blocksPerSecond=25.4 peers=28 prefix=initial-sync
time="2020-10-25 01:03:27" level=info msg="Processing block 0x74b202ce... 531584/588616 - estimated time remaining 36m33s" blocksPerSecond=26.0 peers=28 prefix=initial-sync
time="2020-10-25 01:03:28" level=info msg="Processing block 0xf7efce0b... 531616/588616 - estimated time remaining 38m18s" blocksPerSecond=24.8 peers=28 prefix=initial-sync
time="2020-10-25 01:03:28" level=info msg="Processing block 0x40a26321... 531744/588616 - estimated time remaining 35m2s" blocksPerSecond=27.1 peers=28 prefix=initial-sync
time="2020-10-25 01:03:28" level=info msg="Processing block 0x7eb1a632... 531808/588616 - estimated time remaining 34m3s" blocksPerSecond=27.8 peers=28 prefix=initial-sync
time="2020-10-25 01:03:30" level=info msg="Processing block 0xbe8a3eb7... 531360/588616 - estimated time remaining 42m7s" blocksPerSecond=22.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:31" level=info msg="Processing block 0x8fdf8081... 531520/588616 - estimated time remaining 38m22s" blocksPerSecond=24.8 peers=29 prefix=initial-sync
time="2020-10-25 01:03:31" level=info msg="Processing block 0xe53d989c... 531552/588616 - estimated time remaining 37m26s" blocksPerSecond=25.4 peers=29 prefix=initial-sync
time="2020-10-25 01:03:31" level=info msg="Processing block 0x74b202ce... 531584/588616 - estimated time remaining 36m33s" blocksPerSecond=26.0 peers=29 prefix=initial-sync
time="2020-10-25 01:03:31" level=info msg="Processing block 0xf7efce0b... 531616/588616 - estimated time remaining 35m42s" blocksPerSecond=26.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:32" level=info msg="Processing block 0x40a26321... 531744/588617 - estimated time remaining 32m51s" blocksPerSecond=28.9 peers=29 prefix=initial-sync
time="2020-10-25 01:03:32" level=info msg="Processing block 0x7eb1a632... 531808/588617 - estimated time remaining 31m59s" blocksPerSecond=29.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:34" level=info msg="Processing block 0xbe8a3eb7... 531360/588617 - estimated time remaining 31m20s" blocksPerSecond=30.4 peers=29 prefix=initial-sync
time="2020-10-25 01:03:35" level=info msg="Processing block 0x8fdf8081... 531520/588617 - estimated time remaining 29m11s" blocksPerSecond=32.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:35" level=info msg="Processing block 0xe53d989c... 531552/588617 - estimated time remaining 28m38s" blocksPerSecond=33.2 peers=29 prefix=initial-sync
time="2020-10-25 01:03:35" level=info msg="Processing block 0x74b202ce... 531584/588617 - estimated time remaining 28m7s" blocksPerSecond=33.8 peers=29 prefix=initial-sync
time="2020-10-25 01:03:36" level=info msg="Processing block 0xf7efce0b... 531616/588617 - estimated time remaining 27m37s" blocksPerSecond=34.4 peers=30 prefix=initial-sync
time="2020-10-25 01:03:36" level=info msg="Processing block 0x40a26321... 531744/588617 - estimated time remaining 25m51s" blocksPerSecond=36.6 peers=30 prefix=initial-sync
time="2020-10-25 01:03:36" level=info msg="Processing block 0x7eb1a632... 531808/588617 - estimated time remaining 25m18s" blocksPerSecond=37.4 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0xbe8a3eb7... 531360/588617 - estimated time remaining 30m26s" blocksPerSecond=31.4 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0x8fdf8081... 531520/588617 - estimated time remaining 28m24s" blocksPerSecond=33.5 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0xe53d989c... 531552/588617 - estimated time remaining 27m53s" blocksPerSecond=34.1 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0x74b202ce... 531584/588617 - estimated time remaining 27m23s" blocksPerSecond=34.7 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0xf7efce0b... 531616/588617 - estimated time remaining 26m54s" blocksPerSecond=35.3 peers=30 prefix=initial-sync
time="2020-10-25 01:03:40" level=info msg="Processing block 0x40a26321... 531744/588617 - estimated time remaining 25m14s" blocksPerSecond=37.5 peers=30 prefix=initial-sync
time="2020-10-25 01:03:44" level=info msg="Processing block 0x7eb1a632... 531808/588618 - estimated time remaining 31m2s" blocksPerSecond=30.5 peers=29 prefix=initial-sync
time="2020-10-25 01:03:47" level=info msg="Processing block 0xbe8a3eb7... 531360/588618 - estimated time remaining 40m31s" blocksPerSecond=23.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0x8fdf8081... 531520/588618 - estimated time remaining 48m55s" blocksPerSecond=19.4 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0xe53d989c... 531552/588618 - estimated time remaining 47m26s" blocksPerSecond=20.1 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0x74b202ce... 531584/588618 - estimated time remaining 46m1s" blocksPerSecond=20.6 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0xf7efce0b... 531616/588618 - estimated time remaining 44m42s" blocksPerSecond=21.2 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0x40a26321... 531744/588618 - estimated time remaining 40m20s" blocksPerSecond=23.5 peers=29 prefix=initial-sync
time="2020-10-25 01:03:51" level=info msg="Processing block 0x7eb1a632... 531808/588618 - estimated time remaining 39m2s" blocksPerSecond=24.2 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0xbe8a3eb7... 531360/588619 - estimated time remaining 1h0m35s" blocksPerSecond=15.8 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0x8fdf8081... 531520/588619 - estimated time remaining 53m9s" blocksPerSecond=17.9 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0xe53d989c... 531552/588619 - estimated time remaining 51m24s" blocksPerSecond=18.5 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0x74b202ce... 531584/588619 - estimated time remaining 49m46s" blocksPerSecond=19.1 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0xf7efce0b... 531616/588619 - estimated time remaining 48m13s" blocksPerSecond=19.7 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0x40a26321... 531744/588619 - estimated time remaining 43m11s" blocksPerSecond=21.9 peers=29 prefix=initial-sync
time="2020-10-25 01:03:58" level=info msg="Processing block 0x7eb1a632... 531808/588619 - estimated time remaining 41m42s" blocksPerSecond=22.7 peers=29 prefix=initial-sync
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
$ ./prysm/prysm.sh version
Latest Prysm version is v1.0.0-beta.0.rc.
  </code>
</pre>

**Comment by rauljordan** [comment]
this has since been resolved in 1.0.0-beta.1, please let us know if the issue persists and we can reopen @rev3ks
