### ISSUE TITLE
WebUI: Create HD Wallet Internal server error

### ISSUE THREAD

**Issue by ChuckNorrison** [prysmaticlabs/prysm#7679]
# 🐞 Bug Report

### Description

I try to Create HD Wallet via WebUI, that fails with a red coloured notification after the desired Wallet Password was entered

### Has this worked before in a previous version?

unknown

## 🔬 Minimal Reproduction

Open WebUI, Create HD Wallet, use complex passwords with special chars

## 🔥 Error

<pre><code>
Internal server error, something went wrong
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Server 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
prysm.sh v1.0.0-beta.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
This is a spadina environment. I created a subfolder "medalla" in default path and entered the desired wallet path in webui as recommended.

**Comment by rauljordan** [comment]
Hi @ChuckNorrison this is related to https://github.com/prysmaticlabs/prysm-web-ui/issues/91 and also due to host:port issues that we are looking into. Please subscribe to that issue for updates
