### ISSUE TITLE
My node v1.0.0-beta.1 is consuming a lot of memory.

### ISSUE THREAD

**Issue by Nikolay-everstake** [prysmaticlabs/prysm#7703]
# 💎 Issue

### Background
My node is consuming a lot of memory.
node version v1.0.0-beta.1
### Description
My node v1.0.0-beta.1 is consuming a lot of memory.
OS Ubuntu 16.04.6 LTS
Linux ethereum2 4.15.0-70-generic 
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
64 Gb RAM
My proc report
cat /proc/16950/status
Name:   beacon-chain-v1                                
Umask:  0002                                     
State:  S (sleeping)                                   
Tgid:   16950                                                                                                             
Ngid:   0                                                                                                                                                                                    
Pid:    16950                                                                                                                                                                                
PPid:   11346                                                                 
TracerPid:      0                                                                                                                                                                            
Uid:    1001    1001    1001    1001                                                                                                         
Gid:    1001    1001    1001    1001                                                                                                                                                         
FDSize: 256                                   
Groups: 999 1001                                                                        
NStgid: 16950                                                                                                                                                                                
NSpid:  16950                                             
NSpgid: 16950                                               
NSsid:  11346                                                     
VmPeak: 20496692 kB                                                   
VmSize: 20496692 kB                                                     
VmLck:         0 kB                                                                                                       
VmPin:         0 kB                                                            
VmHWM:  15165044 kB                                                          
VmRSS:  15165044 kB                                                           
RssAnon:         9618368 kB                 
RssFile:         5546676 kB

**Comment by nisdas** [comment]
@Nikolay-everstake How many validators are you running ?

**Comment by Nikolay-everstake** [comment]
On this node 2 validators.

вт, 3 нояб. 2020 г., 05:57 Nishant Das <notifications@github.com>:

**Comment by rauljordan** [comment]
@Nikolay-everstake could you update us on your performance with beta.2? Are you also running a slasher?

**Comment by Nikolay-everstake** [comment]
Yes. I have updated node nodes to beta.2 
on node with 2 val keys  
RssAnon:         5595112 kB
RssFile:         6522604 kB
slasher runned
on node with 100 val keys
RssAnon:         7603080 kB
RssFile:         6335452 kB
slasher runned

**Comment by 0xKiwi** [comment]
Hello @Nikolay-everstake , the slasher is not necessarily mainnet-ready and may incur large memory usage, we recommend not using it if you are using the same beacon node for your validators.

Is your problem still occurring without the slasher?
