### ISSUE TITLE
Email list to inform users of critical issues/updates

### ISSUE THREAD

**Issue by dankrad** [prysmaticlabs/prysm#7705]
When critical updates are published, or there are urgent problems with the clients that need all stakers to intervene, there should be a way to quickly get this information out to all Prysm users. I recommend:
 *  Setting up an email list that stakers can subscribe to and on which highly critical information can be pushed
 * Additionally, setting up groups/accounts on other channels (twitter, telegram, etc.) can be helpful

Not all users can be expected to constantly monitor discussion channels such as discord, so having a low-noise direct channel that reliably reaches all stakers is essential.

**Comment by prestonvanloon** [comment]
We can support a low volume email list for release announcements. I'll set something up this week. Thanks for the suggestions!

**Comment by prestonvanloon** [comment]
A mailing list can be found here: https://groups.google.com/g/prysm-dev

**Comment by ChuckNorrison** [comment]
Highly recommend this discord channel https://discord.gg/RyhtQqQ6bz

**Comment by rauljordan** [comment]
This is now fixed in our documentation portal, as we have now included a page on how to keep Prysm up to date
