### ISSUE TITLE
Add `--mainnet` flag

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#7735]
# 🚀 Feature Request

### Description

Please add a `--mainnet` flag to Prysm beacon and validator (and slasher).

Rationale: I am using docker tooling that uses `--${NETWORK}` to work with mainnet as well as test nets. This tooling will be easier if it works the same way for main as well as test, without needing to special-case Prysm. 

`mainnet` is used by eth2.0-deposit-cli as the string to indicate main net, and hopefully other clients will adopt that string for their `--network` options.

**Comment by prestonvanloon** [comment]
Right now, mainnet is the default option. We could support this functionality where a `--mainnet` flag is a no-op since mainnet was the default anyway. In go-ethereum, these types of network flags have been defined for testnets only where the lack of a defined network flag means you intended the main network. 

Perhaps eth2.0-deposit-cli can remove that flag requirement? 
It sounds like that that cli is the special-case or do other eth2 clients also require this flag?

**Comment by yorickdowne** [comment]
In a nutshell, where this leaves me for eth2-docker tooling:

With `--mainnet`, the user need make no choice other than set `NETWORK` to `mainnet` in `.env`.

Without it, it becomes some kind of shuffle where I have maybe a `prysm-base.yml` for main and `prysm-base-test.yml` for test. I can work around it - I'd just love to make it really easy for users of the "eth2-docker" tooling.

**Comment by prestonvanloon** [comment]
@yorickdowne, it looks like this has a tangible benefit to you and is a small ask for the project. Let's add this feature. Thanks!

**Comment by yorickdowne** [comment]
> It sounds like that that cli is the special-case or do other eth2 clients also require this flag?

Teku does `--network mainnet`. Nimbus and LH haven't released their support yet.

Geth indeed has no flag, it requires some user intervention to indicate "not test".

**Comment by yorickdowne** [comment]
After discussion on Discord, rationale for this change: Not having the flag makes my tooling more difficult, having it makes it easier.

Without the flag works, it's just extra steps. So instead of NETWORK= and then either medalla or mainnet, I'll need to duplicate prysm-base and have a prysm-base-main and prysm-base-test yml, because the docker-compose entrypoint right now assumes it can specify ${NETWORK}.

I can work around it. I'd love it if I didn't have to.
