### ISSUE TITLE
Use Dynamic Moving Average for Eth1 Blocktime

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#7739]
# 💎 Issue

Use Moving Average for ETH1 Blocktime

### Background

Currently our eth1 block time is a static parameter created at node initialization. However while this has been the average for a while, it would be much more accurate to instead use a moving average of the last 1000 eth1 blocks and use that to determine our estimated eth1 block time. This would be more accurate than using a static value, as the static value might not always hold(ice age difficulty increase).

**Comment by rauljordan** [comment]
From @nisdas: "This is no longer relevant. For the purposes of consensus among clients, we wont be using any sort of dynamic block time"
