### ISSUE TITLE
Security: validator account vs interactive password vs remote signer

### ISSUE THREAD

**Issue by gregbkr** [prysmaticlabs/prysm#7740]
# 💎 Open question on validator account security

### Background

Some questions following the [documentation](https://docs.prylabs.network/docs/wallet/introduction) about how to protect your validator account, understanding the consequence of a hack while running on a VPS in the cloud, or using remote signer with a raspberry at home.

### Description

Hello,

I understand that ETH2 keys can be generated on a secure device (airgapped rapsberry) with [deposit-cli](https://github.com/ethereum/eth2.0-deposit-cli) and come in two set of data to secure:
- `A 24 words seed`: the master key (that control withdraw, validators creation) -> we save it to a paper, and put it in a safe: SAFE, no one may be able to withdraw our ETH.
- `Validator account`: a file (`password` protected) to be moved to an active node (VPS, home raspberry) to stake ETH (hot wallet) -> security to be discussed below...

1. What are the worse things an attacker could do if they get hand on `validator account` + `password`:
- I can think of running several validators to volontary get slashed/burn all ETH in our wallet. Attacker wins nothing, but we lose a lot. Can someone make you burn to oblivion (until your balance goes to 0 ETH)?
- Other?

2. About that `validator account`:

| Tag | Config | Description | Ease of use | Security 
-------|-----------|-----------------|-----------------|------------
| 2.a | validator + password on VPS |  We could move the file to a VPS, write the `password` to `password.txt` and run staking with `prysm validator --password-file password.txt` | using systemd, we could automate staking relaunch if the server restart. | but if an attacker enter our VPS, he can get everything: `validator account` and `password`
|2.b| validator + interactive password on VPS|  We could move the file to a VPS, and enter manual/interactive `password` when we run `prysm validator` then we type the password when asked | each time the daemon stop, we will need to be alerted and go manually on the server to start it + `password` input | password don't live in file which is much better, but may live in RAM somewhere to get? (not sure)
| 2.c | Remote signer (VPS + home raspberry)| We could use remote-signer, your `validator account` will then live on your home raspberry (more protected) and sign request from the VPS (in the cloud, more in the front line). | not trivial to install, and now you need to take care of 2 boxes | someone entering our VPS will not find `validator account` file, but could he not run 2 `prysm validator` and voluntary "burn/slash" our ETH, our remote-signer would just do his job, signing anything from VPS. in this case, it is the same security as tag `2.a`.

I would love to better understand the risk of each points.
Thank you for your help!
Greg.

**Comment by rauljordan** [comment]
@gregbkr you summarized it perfectly. I'll add a bit more to the risks of each. 

For (2.a), yes the attacker could gain your password and thereby obtain your accounts and unencrypted validating private keys. The attacker will never have your withdrawal private keys, however.

For (2.b) The decrypted accounts live in RAM so yes they could dump the RAM and still steal your accounts

For (2.c) Yes this is a potential scenario, but you could setup slashing protection via `slasher` as a middleware in a third box between the remote signer and validator client. We do not currently have guides for this, but this is the most secure setup. Even if someone dumps your RAM, there is nothing of interest as there are no keys to steal. This is as air-gapped as you can get! It is indeed difficult, and would require a custom setup and/or help from our team. Our remote signer reference implementation [here](https://github.com/prysmaticlabs/remote-signer) is not production-ready as it is only for demonstration purposes. You would have to build a better one that can fulfill these needs

**Comment by gregbkr** [comment]
Thank you @rauljordan for your clear answer!
Is there on the roadmap any "ledger eth2 staking app", to protect your validator private key, similar to [tezos-baking-app](https://github.com/obsidiansystems/ledger-app-tezos)? It seems like the ultimate/efficient security solution. Thanks!

**Comment by rauljordan** [comment]
Unfortunately, no hardware wallet support is known at the moment. The best we recommend for average stakers is to keep your mnemonic always offline and safe, and only import validating keys into Prysm as you need them. For advanced stakers, remote signers are the best way, but there isn't a documented way to set one up yet for production. We are working on using a remote signer internally and after that effort is done, we can perhaps open source it or add instructions in our docs
