### ISSUE TITLE
Validator Does Not Attest For EXITING Accounts

### ISSUE THREAD

**Issue by jerryji** [prysmaticlabs/prysm#7745]
# 🐞 Bug Report

### Description

 validator ( v1.0.0-beta.1 ) does not attest for accounts in EXITING status

### Has this worked before in a previous version?

 N.A.

## 🔬 Minimal Reproduction

Voluntary exit an account, _then_ start its validator

NOTE: if the account changes status to EXITING _while_ its validator is running, validator would keep on attesting

## 🔥 Error

<pre><code>
Nov 07 22:24:10 * validator[45603]: time="2020-11-07 22:24:10" level=info msg="Validator status" activationEpoch=0 index=10040 prefix=validator pubKey=0x8510d8b931b4 status=EXITING
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-beta.1
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

EXITING account --

https://beaconscan.com/validator/10040

**Comment by terencechain** [comment]
@jerryji nice one! thanks for reporting

**Comment by potuz** [comment]
I think the following should solve this issue:

```
$ git diff
diff --git a/validator/client/validator.go b/validator/client/validator.go
index 7dfb81dcc..a72506644 100644
--- a/validator/client/validator.go
+++ b/validator/client/validator.go
@@ -331,7 +331,7 @@ func (v *validator) checkAndLogValidatorStatus(validatorStatuses []*ethpb.Valida
                                        "activationEpoch": status.Status.ActivationEpoch,
                                }).Info("Waiting for activation")
                        }
-               case ethpb.ValidatorStatus_ACTIVE:
+               case ethpb.ValidatorStatus_ACTIVE,ethpb.ValidatorStatus_EXITING:
                        validatorActivated = true
                case ethpb.ValidatorStatus_EXITED:
                        log.Info("Validator exited")
```
I am not willing to sacrifice my validator to test :)
