### ISSUE TITLE
Error powchain

### ISSUE THREAD

**Issue by PandamineHub** [prysmaticlabs/prysm#7749]
Hello, when I am starting BC in docker, I am not able to connect to eth1 node which is running:

docker run -it -v C:\Users\jakub\AppData\Roaming\Eth2:/data -p 4000:4000 -p 13000:13000 -p 12000:12000/udp gcr.io/prysmaticlabs/prysm/beacon-chain:stable --datadir=/data --rpc-host=127.0.0.1 --monitoring-host=127.0.0.1 --http-web3provider=http://localhost:8545 --medalla

When I run BC using prysm installation scrypt, it can connect to eth1 node properly:

.\prysm.bat beacon-chain --http-web3provider=http://localhost:8545 --medalla

Could you please help me what is wrong in using docker to connect to eth1node?

<img width="1127" alt="Capture" src="https://user-images.githubusercontent.com/49977808/98486269-a81f8a00-221c-11eb-95c7-183301377db4.PNG">

**Comment by nisdas** [comment]
How are you running your eth1 node ?

**Comment by PandamineHub** [comment]
> How are you running your eth1 node ? Could you list out the command through which you are running it with.

geth --datadir="C:\Mainnet_Testnet" --http --goerli

**Comment by nisdas** [comment]
`--http.vhosts` , you will need to whitelist the host ip of your beacon node. Which will be a private ip assigned by docker. 
From geth's docs
```
  --http.vhosts value                 Comma separated list of virtual hostnames from which to accept requests (server enforced). Accepts '*' wildcard. (default: "localhost")
```

**Comment by PandamineHub** [comment]
Thank you very much for your help so far. Could you please help me how to find out which ip has been assigned by docker?

**Comment by PandamineHub** [comment]
Hello, I have tried out following:

Private address:
ipconfig | findstr /i "IPv4 Address"

Public address:
curl v4.ident.me

IP address of home router:
ipconfig | findstr /i "Gateway"

But no address work for my docker, still cannot connect to my eth1 node localy. But prysm.bat still working properly with "localhost" connection.

How can I found the IP assigned by docker?

Thank you very much!!

Jakub

**Comment by nisdas** [comment]
Hey Jakub, 

can you try `ipconfig docker0` , I am assuming the windows counterpart works the same as linux. 

If you do see a private ip specified, you can provided that + `/16` 

so ex: `172.0.0.1/16` and provide that to geth in the flag. 

Also if you still have issues you can come to our discord: https://discord.gg/vfNBrSDV

**Comment by nisdas** [comment]
@PandamineHub has already informed me offline that he has it resolved, it had to do with his geth setup while trying to use a non-localhost binding address.
