### ISSUE TITLE
Docker image build v1 glibc error

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#7750]
# 🐞 Bug Report

### Description

GLIBC version problem in docker. Is docker not supposed to help avoid such situations where the host has a different glibc version?

### Has this worked before in a previous version?

Not building prysm docker images with bazel often, not sure.

## 🔬 Minimal Reproduction

Had some versioning problem with bazel (installed 3.2 from source, but bad version string), running `/usr/bin/bazel-real` as work-around.

```
/usr/bin/bazel-real build //beacon-chain
DOCKER_TAG=toledo /usr/bin/bazel-real run //beacon-chain:image_bundle
docker run --rm gcr.io/prysmaticlabs/prysm/beacon-chain:toledo --help
```

## 🔥 Error

<pre><code>
/app/beacon-chain/image.binary: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/beacon-chain/image.binary)
</code></pre>

## 🌍  Your Environment

**Operating System:**

On the host:
<pre>
  <code>
gcc --version
gcc (GCC) 10.2.0

 ldd --version
ldd (GNU libc) 2.32

Os: x86_64 Linux 5.8.10-arch1-1
  </code>
</pre>

The binary version of prysm works in the host.

But host shouldn't matter. Docker images should be self-contained.
No clue what glibc version runs in the docker, maybe change it in bazel somewhere?

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-rc.0
  </code>
</pre>
commit: d954e8ffcafc310ef1894755f974f9df8122b741

Why does Prysm even require glibc, did something change in the dependencies? I made a PR to herumi long ago to avoid glibc/musl etc. needs, so it runs on Alpine.

Also, confirm that the docker alpine image also doesn't work. Can't find a file or something during docker run. But I see that alpine not working is a known issue :(

**Comment by protolambda** [comment]
Can't seem to build the master branch either. Still want to run Prysm v1 branch for Toledo. Can anyone help prepare a docker image?

**Comment by nisdas** [comment]
Not too sure why you have that failure, would have to dig into it. However I managed to build toledo and push it up for both the beacon node and validator. If you need the slasher too, I can build for that and push it up too.  
https://console.cloud.google.com/gcr/images/prysmaticlabs/GLOBAL/prysm/beacon-chain?gcrImageListsize=30
https://console.cloud.google.com/gcr/images/prysmaticlabs/GLOBAL/prysm/validator?gcrImageListsize=30

You can fetch it using the `toledo` tag, let me know if it works for you.

**Comment by prestonvanloon** [comment]
Please use `--config=release` to build docker images.

**Comment by prestonvanloon** [comment]
Alpine still broken, no one is looking into it right now as far as i know :( #5768
