### ISSUE TITLE
Repeating docker `exec: "git": executable file not found`

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#7753]
# 💎 Issue

### Background

Docker image does not have git executable, and git tag is missing in linker options when building. The result is that every time GetVersion() is called, it re-tries to execute `git`, and fails over and over.
This results in spam in the logs, ignores consistent logging (it's just `log` package, instead of the prysm logger), and costs unnecessary overhead (eth2stats polls it a lot)

### Description

https://github.com/prysmaticlabs/prysm/blob/15706a36cb251232ae0fbb787d1287a3e6aad707/shared/version/version.go#L30

```
2020/11/09 18:37:55 exec: "git": executable file not found in $PATH
```

Caching that the version is unavailable would be nice.

**Comment by prestonvanloon** [comment]
Please build with `--config=release`

**Comment by protolambda** [comment]
@prestonvanloon thanks, not aware of that flag. @nisdas built this image for me though, since local build with bazel wasn't working, see: #7750

**Comment by nisdas** [comment]
@protolambda This has been fixed with the latest image for toledo, I recompiled it with our release flag. Let me know if it works for you.

**Comment by protolambda** [comment]
That worked, thank you. Would still be nice to limit `exec "git"` attempts, or document the release flag near the bazel code (I couldn't find it)

**Comment by nisdas** [comment]
Yeah, its still a `TODO` unfortunately. 
https://github.com/prysmaticlabs/documentation/issues/258

We will try and get this documented before mainnet, for anyone building from source using the release flag would be more desirable.
