### ISSUE TITLE
Version is not correctly displayed when running beaconchain node

### ISSUE THREAD

**Issue by fabdarice** [prysmaticlabs/prysm#7765]
# 🐞 Bug Report

### Description

As we can see in the log below, the Prysm version is not correctly displayed, the string interpolation seemed to be missed.

```
time="2020-11-10 05:58:52" level=info msg="Starting beacon node" prefix=node version="Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}. Built at: 2020-11-10T05:58:51-08:00"
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux Arch
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.0.0-beta.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
N/A

**Comment by fabdarice** [comment]
Happy to fix this real quick.

**Comment by nisdas** [comment]
@fabdarice you need to build with `--config=release`  it will bake in the binary data. For reference:
https://github.com/prysmaticlabs/prysm/issues/7497
