### ISSUE TITLE
Missed proposal due to "validator has already submitted an exit", but no exit submitted

### ISSUE THREAD

**Issue by leontodd** [prysmaticlabs/prysm#7766]
# 🐞 Bug Report

### Description

I noticed that my validators had been attesting but consistently missing all proposals. I've included the logs from the time of one of the missed proposals below. The log seems to indicate that the proposal failed because the validator had already submitted an exit. I have not exited any validators and can't seem to find any indication that this validator has been submitted for exit.

I restarted the beacon node and am no longer experiencing this issue - proposals seem to be fine now.

### Has this worked before in a previous version?

I have never experienced this before in previous versions.

## 🔬 Minimal Reproduction

Unknown

## 🔥 Error

<pre><code>

time="2020-11-10 10:24:33" level=error msg="Failed to request block from beacon node" blockSlot=704822 error="rpc error: code = Internal desc = Could not compute state root: could not calculate state root at slot 704821: could not process block: could not process block operation: could not process validator exits: could not verify exit 2: validator has already submitted an exit, which will take place at epoch: 28012" prefix=validator pubKey=0x88105fd3a50c

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm v1.0.0-beta.1
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

This is the validator that attempted to propose before the above log was generated, look for the missed proposal at the same timestamp as the log:
https://medalla.beaconcha.in/validator/78693

I have 160 active validators. The 160 validators had 14 proposals from `2020-11-10 01:43:58` to `2020-11-10 12:01:57` (UTC+1).
All 14 of those showed this same error, but all 14 had different pub keys.

**Comment by rkapka** [comment]
I don't think anything can be done here without an explanation of how to reproduce this, @leontodd. Are you able to provide more details?

**Comment by prestonvanloon** [comment]
@rkapka It seems like they had voluntary exit in their queue when that voluntary exit had already been included in the chain. 

This user is likely not going to be able to give us reproduction instructions so we will have to reverse engineer the problem. 
It is very likely that something is wrong with this method:
https://github.com/prysmaticlabs/prysm/blob/fcbb168c76ac6a471fdd6c5a2a1611857883499d/beacon-chain/operations/voluntaryexits/service.go#L34-L57

**Comment by prestonvanloon** [comment]
I suspect that their voluntary exit pool had two different exits for the same validator.

**Comment by prestonvanloon** [comment]
Fixed by #7774
