### ISSUE TITLE
Should mainnet genesis delay be 7 days?

### ISSUE THREAD

**Issue by imnisen** [prysmaticlabs/prysm#7780]
https://github.com/prysmaticlabs/prysm/blob/d3ca9985eb9c00d1d7f1fc69b1c48bc6c54f5c7e/shared/params/mainnet_config.go#L46

As in the [spec](https://github.com/ethereum/eth2.0-specs/blob/450c8c26f9873775c842669edb6d6f3cca02b7ea/configs/mainnet/phase0.yaml#L82)

```
GENESIS_DELAY: 604800
```

**Comment by nisdas** [comment]
Hey @imnisen you can monitor this here:
https://github.com/prysmaticlabs/prysm/tree/v1.0.0-rc.0

We havent updated all our config values yet, we will be doing them in time. That branch is still a work in progress.
