### ISSUE TITLE
Handle missing validator.db file or relevant data

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#7791]
# 🚀 Feature Request

### Description

I order to harden slashing protection and educate our users about its importance we have to add steps that prevents the accidental lose of the validator.db file or its relevant content

### Describe the solution you'd like

Two steps solution:

- [x]  add warning for missing file

- [x] prompt user for running an activated validator key that has no relevant protection data (should be done after data interchange import feature will be complete)

**Comment by rauljordan** [comment]
Closing in favor of #7813
