### ISSUE TITLE
Final Pass at Removing Deprecated Flags and Old Testnet Configs for v1.0.0

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7798]
This is a tracking issue to remove all deprecated and old testnet configs and flags for Prysm's v1.0.0 release, to start mainnet with a clean slate

**Comment by shayzluf** [comment]
@rauljordan can we bring back :
- disable-broadcast-slashings
- disable-dynamic-committee-subnets 
that were deleted in
https://github.com/prysmaticlabs/prysm/pull/7533
they are needed flags

**Comment by terencechain** [comment]
> @rauljordan can we bring back :
> 
> * disable-broadcast-slashings
> * disable-dynamic-committee-subnets
>   that were deleted in
>   #7533
>   they are needed flags

@shayzluf can you please clarify why they are needed? Lighthouse or teku for example do not have those flags

**Comment by nisdas** [comment]
#7836 has been merged again. So you can just use that

**Comment by shayzluf** [comment]
@terencechain for `disable-broadcast-slashings` i think people would like to try their luck in including the slashings they found

**Comment by terencechain** [comment]
> @terencechain for `disable-broadcast-slashings` i think people would like to try their luck in including the slashings they found

I dont think we should encourage this behavior:
1.) Not outlined in the validator spec
2.) Other clients (LH and Teku) dont have this
3.) We dont have documentation to support this
4.) Incentives don't add up, the inclusion reward is little and chances to become proposer is also very little
5.) It was fine to implement for experimental and testing purpose but im not sure how we feel about rolling this feature into mainnet

**Comment by prestonvanloon** [comment]
The only remaining items for this are just to remove deprecated flags? @rauljordan

**Comment by terencechain** [comment]
Fixed with #7877
