### ISSUE TITLE
geth restart causes beacon node to lose connection to powchain endpoint and doesn't reconnect

### ISSUE THREAD

**Issue by alexfisher** [prysmaticlabs/prysm#7806]
# 🐞 Bug Report

### Description

With this week's ETH 1 network issue due to out-of-date geth releases, I performed two geth updates that triggered this error condition two different times.  I'm running geth in its own docker container and prysm beacon and validator in their own containers.  Typically, the beacon node connects to geth via IPC which is shared between each respective docker container as a volume mapped to the same data directory with the geth.ipc file.

During and after geth container restart, I see the following error get logged on the prsym beacon container:

`level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: dial unix /root/.ethereum/goerli/geth.ipc: connect: connection refused" prefix=powchain`

This error condition persists until I restart the beacon container and then it connects fine on first try:

`level=info msg="Connected to eth1 proof-of-work chain" endpoint="/root/.ethereum/goerli/geth.ipc" prefix=powchain`

I experienced this on the upgrade to yesterday's geth release, as well as the previous version.  I noticed other people on discord having similar issues (and one similar bug report), but am don't think anyone identified the issue as being caused by geth restart (causing the condition of ETH1 connection failure) followed by beacon node restart (causing ETH1 connection issue to be resolved).

### Has this worked before in a previous version?

Have been participating in Medalla since genesis and have been using IPC connection for at least the past 2 months without issue.

## 🔬 Minimal Reproduction

Running docker-compose services, but some of the parameters for each container are below:

Docker container with geth goerli

--maxpeers=20 --goerli --port=31303

Docker container with prysm beacon:

accept-terms-of-use: yes
head-sync: yes
medalla: yes
http-web3provider: /root/.ethereum/goerli/geth.ipc
p2p-max-peers: 40
rpc-port: 4100
p2p-tcp-port: 13100
p2p-udp-port: 12100
datadir: /data
p2p-host-ip: ""
p2p-host-dns: ""
rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
p2p-denylist: ["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","100.64.0.0/10","169.254.0.0/16"]
enable-db-backup-webhook: true
blst: yes

## 🔥 Error

See above.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Server 20.04.1 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-beta.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by dpSky** [comment]
I used the bash shell to start the goetherum client and encountered the same problem, beaconchain **could not link to eth1 powchain**. 
I configured them like this:
`/usr/local/bin/geth --goerli --http --datadir /var/eth-box/geth --rpc --rpcaddr 127.0.0.1`

`ExecStart=/usr/local/bin/beacon-chain --p2p-host-ip=‘’ --datadir=/var/eth-box/beacon-chain --http-web3provider=http://127.0.0.1:8545 --accept-terms-of-use`

Use **netstat -tl** to check the port of goeth and confirm that 8545 is in the listening state

`Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp        0      0 localhost:8545          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:domain       0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 [::]:30303              [::]:*                  LISTEN     
tcp6       0      0 ::1:35243               [::]:*                  LISTEN`

I have used source code to compile and install and tested docker to run them, but I found that the success rate of prysm linking eth1 node is a probabilistic problem.

It will always prompt Could not connect to powchain endpoint" error="could not dial eth1 nodes: eth1 node using incorrect chain id

**Comment by rauljordan** [comment]
Hi @alexfisher we recommend setting up a fallback eth1 node: https://docs.prylabs.network/docs/prysm-usage/setup-eth1#adding-fallback-eth1-nodes. Does this issue still happen to you?

**Comment by rauljordan** [comment]
Hi @alexfisher let us know if this is still an issue and we can re-open
