### ISSUE TITLE
Windows: prysm.bat does not recognize AMD processors as 64 bit

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#7810]
https://github.com/prysmaticlabs/prysm/blob/075f1458b46e2e61f5e883076b0d52b637814e83/prysm.bat#L37-L41

![unknown (1)](https://user-images.githubusercontent.com/7246818/99099697-a85ab500-258f-11eb-9de2-e3645b81c27c.png)

There is no "x86" string for AMD processors such as AMD Ryzen 5 4600H

**Comment by prestonvanloon** [comment]
Workaround script can be used here: https://gist.github.com/prestonvanloon/22b39cffb75371fbe3036d054a89a3ed

**Comment by prestonvanloon** [comment]
cc: @wgknowles

**Comment by wgknowles** [comment]
On holiday for a week, but here’s some helpful info: https://ss64.com/nt/syntax-64bit.html

**Comment by ThothLogos** [comment]
I was just poking around your issues, some possibilities to explore perhaps for whoever jumps on it:

```
C:\Users\thoth> WMIC ComputerSystem GET SystemType
SystemType
x64-based PC

C:\Users\thoth> WMIC OS GET OSArchitecture
OSArchitecture
64-bit
```

**Comment by ahadda5** [comment]
I ran this test by manually changing the registry entry to be AMD64. It worked just fine. 

```
> reg Query "HKLM\Hardware\Description\System\CentralProcessor\0"

HKEY_LOCAL_MACHINE\Hardware\Description\System\CentralProcessor\0
    Component Information    REG_BINARY    00000000000000000000000000000000
    Identifier    REG_SZ    AMD64 Family 23 Model 96 Stepping 1
    Configuration Data    REG_FULL_RESOURCE_DESCRIPTOR    FFFFFFFFFFFFFFFF0000000000000000
    ProcessorNameString    REG_SZ    Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
    VendorIdentifier    REG_SZ    GenuineIntel
    FeatureSet    REG_DWORD    0x311b3fff
    ~MHz    REG_DWORD    0xc18
    Update Revision    REG_BINARY    00000000DE000000
    Previous Update Revision    REG_BINARY    00000000B4000000
    Update Status    REG_DWORD    0x0
    Platform Specific Field 1    REG_DWORD    0x8
    Platform Specific Field 2    REG_BINARY    00000000

```
On running the prysm.bat  a beacon-chain-v1.4.2-windows-amd64 was downloaded! 
I think its safe to close .

**Comment by wgknowles** [comment]
The offending line of code is actually searching for the lack of "x86" being present rather then looking for anything related to AMD/Intel 64.  The reason the OP was having issues is that the value of "Platform Specific Field1" (which contains the microcode version) started with 0x86.  I'm guessing this bug probably resolved itself as microcode updates to Ryzen no longer have 0x86 in the version number?

**Comment by ahadda5** [comment]
> The offending line of code is actually searching for the lack of "x86" being present rather then looking for anything related to AMD/Intel 64. The reason the OP was having issues is that the value of "Platform Specific Field1" (which contains the microcode version) started with 0x86. I'm guessing this bug probably resolved itself as microcode updates to Ryzen no longer have 0x86 in the version number?

Good point.  By the way i was manually changing the registry entries(it is an Intel64 in my case)   :) 
In such a case maybe look in the that field only vs all fields . but yet again one is under the mercy of the vendor/Microsoft updates.

**Comment by prestonvanloon** [comment]
Closing old issue. Please add a comment if this is still ongoing. Thanks!
