### ISSUE TITLE
Introduce "stable" docker tag for easier tooling

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#7815]
# 🚀 Feature Request

### Description

Currently, a versioned docker tag and a `latest` tag exist, where `latest` tracks development on `master`.

In addition to these two, a `stable` tag would be useful, that tracks latest release. This makes docker tooling easier,
as there's no need to change configuration files with a new release.

I have no opinion on the exact name of such a tag. There might be a `release-1.x` as well or instead, to go with semantic versioning and avoid pulling in breaking changes, similar to how geth has `stable` and `release-1.9`.

**Comment by raphpa** [comment]
There actually is a :stable tag in the registry
[https://console.cloud.google.com/gcr/images/prysmaticlabs/GLOBAL/prysm/beacon-chain](https://console.cloud.google.com/gcr/images/prysmaticlabs/GLOBAL/prysm/beacon-chain?gcrImageListsize=30&gcrImageListquery=%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22stable_5C_22_22%257D%255D)

**Comment by prestonvanloon** [comment]
We provide a stable tag with every release.
