### ISSUE TITLE
add --no-check-certificate for beacon node

### ISSUE THREAD

**Issue by egoni** [prysmaticlabs/prysm#7818]
# 🚀 Feature Request

### Description

If geth is running behind nginx proxy to serve tls encription with self signed certificate, the connection to the geth client fails because the beacon node can't verify the certification issuer:
`[2020-11-15 02:17:04] ERROR powchain: Could not connect to powchain endpoint error=Post "https://<ipgeth>/": x509: certificate signed by unknown authority`

### Describe the solution you'd like

Please add some kind of `--no-check-certificate` parameter to prysm beacon-node to skip tls verification

### Describe alternatives you've considered

Workaround would be to use real CA or let's encrypto certificates

**Comment by prestonvanloon** [comment]
Another workaround is to add the self signed certificate as a trusted CA.

https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html

**Comment by rauljordan** [comment]
We would prefer to add a self-signed cert instead of allowing a dangerous skip of verification for more users, which would be tempting to use in some cases
