### ISSUE TITLE
Remove go-ssz usage

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7845]
This PR tracks the progress of go-ssz usage removal. We are deprecating go-ssz in favor of fast ssz. Here's the branch that started the removal, it's currently stuck at basic type since fast ssz does not have support for it.

Given the complexity, this will be pursued after mainnet

https://github.com/prysmaticlabs/prysm/tree/rm-go-ssz

**Comment by fabdarice** [comment]
@terencechain is that something that someone without experience with go-ssz OR fast-ssz could tackle?
Note that I've read a few explanations on SSZ.

**Comment by pinglamb** [comment]
@terencechain @0xKiwi Another usage I have spotted about `go-ssz` is `ssz.DeepEqual` which seems to be about special handling of `empty slice` and `nil` (they are equal from `ssz` point of view). Should it be something we should copy into `prysm` codebase or `fastssz` needs to support?

**Comment by prestonvanloon** [comment]
@pinglamb I think that can go into Prysm's codebase. Thanks
