### ISSUE TITLE
After restart node, It keep warn Range is not processed err=Range had no valid blocks to process

### ISSUE THREAD

**Issue by duongvansang** [prysmaticlabs/prysm#7860]
I restarted my medalla node, and could not sync any more 
Log keep printout:  WARN initial-sync: Range is not processed err=Range had no valid blocks to process

OS: Ubuntu 20.04 LTS on WSL
ETH1: Openethereum

**Comment by terencechain** [comment]
This is a warning and is expected in some edge cases. Medalla also has been deprecated so please give Pyrmont a try
