### ISSUE TITLE
Error during Pyrmont beaconchain initialization

### ISSUE THREAD

**Issue by jeffprestes** [prysmaticlabs/prysm#7867]
# 🐞 Bug Report

### Description

Error during Pyrmont beaconchain initialization
When I run: ```./prysm.sh beacon-chain --pyrmont --http-web3provider=/home/jeffprestes/.ethereum/goerli/geth.ipc```
I am getting this return: ```ERROR main: database contract is 0x00000000219ab540356cbb839cbe05303d7705fa but tried to run with 0x8c5fecdc472e27bc447696f431e425d02dd46a8c```  

### Has this worked before in a previous version?
Yes, it worked on Medalla testnet

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction

```./prysm.sh beacon-chain --pyrmont --http-web3provider=/home/jeffprestes/.ethereum/goerli/geth.ipc```

## 🔥 Error

<pre><code>
ERROR main: database contract is 0x00000000219ab540356cbb839cbe05303d7705fa but tried to run with 0x8c5fecdc472e27bc447696f431e425d02dd46a8c
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Ubuntu Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
 Latest Prysm version is v1.0.0-beta.3.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by pinglamb** [comment]
I got similar error when I started the beacon node pointing to mainnet and restarted to point to pyrmont.

You can try to start with `--clear-db` to clean the database or perhaps clean it yourself by removing I think `~/.eth2` folder.

**Comment by jeffprestes** [comment]
Thanks @pinglamb 
It worked. 
For future references the entire successful command line was: 
```./prysm.sh beacon-chain --pyrmont --clear-db --http-web3provider=/home/jeffprestes/.ethereum/goerli/geth.ipc```
