### ISSUE TITLE
Attestation aggregation: further optimizations

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#7871]
# 🚀 Feature Request

### Description

- Extracted from #6236
- Within scope of this item we need to provide more benchmarks (both when it comes to algorithm clock-time efficiency and profitability).
- Additionally, more work on how we filter out duplicate validators' votes will be conduced within the same scope.

**Comment by terencechain** [comment]
I'd put more emphasis on filter out duplicate validators vote. Aggregated attestation signature subsctraction may be hard to implement and introduce additional overhead to a running node. With that said, it's a good area to explore if there's free cycle
