### ISSUE TITLE
New accounts import to existing wallet asks for New Password instead of Existing Password in some cases

### ISSUE THREAD

**Issue by realdevknow** [prysmaticlabs/prysm#7893]
# 🐞 Bug Report

### Description

When importing new additional accounts to a directory with an existing wallet, the CLI will ask for a "New Wallet Password" in certain cases. 

If the ```--wallet-dir``` argument is passed directly as an argument to the import command, the CLI will correctly ask you for your existing wallet password, since a wallet exists already in that dir. 

If you do not pass the ```--wallet-dir``` argument, but instead respond to the subsequent "Enter a wallet directory" prompt with a directory that has an existing wallet, it asks for a "New Wallet Password" and makes user enter twice and adhere to pwd reqs, instead of just asking for existing "Wallet Password". If this "New Wallet Password" is different from the existing one, there will be a FATAL error. The existing password must be entered into both New Password and Confirm New Password prompts for it to work.

Expectation is that the CLI asks for existing wallet password in both of the above cases.

### Has this worked before in a previous version?

Unknown. Have not used previous versions.

## 🔬 Minimal Reproduction

Setup:

1. Create wallet with keys in some directory, e.g. /walletDir and give it a password e.g. walletPwd
2. Add additional keys (new accounts) to key directory, and then proceed as below:

Scenario A (correct)

```bazel run //validator:validator -- accounts import --pyrmont --keys-dir={path to keys} --wallet-dir /walletDir```

Scenario B (unexpected)

```
bazel run //validator:validator -- accounts import --pyrmont --keys-dir={path to keys}

>>Enter A Wallet Directory
>>/walletDir

>>New Password (expected prompt for existing wallet password)
>>Confirm New Password (must enter old existing password in both of these fields)
```

## 🌍  Your Environment

**Operating System: Ubuntu**

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-beta.3
  </code>
</pre>

This isn't a critical issue, but more of a UX item that can be misleading.

**Comment by fabdarice** [comment]
Hey @realdevknow, thanks for the details. I was not able to reproduce your situation (didn't reach the FATAL error, although reach a different issue).

```
$ bazel run //validator wallet create -- --wallet-dir=/home/pz/Desktop/test-eth2-wallet
✔ Imported Wallet (Recommended)
Password requirements: at least 8 characters including at least 1 alphabetical character, 1 number, and 1 unicode special character. Must not be a common password nor easy to guess
New wallet password:
Confirm password:
[2020-11-22 08:14:12]  INFO accounts: Successfully created wallet with on-disk keymanager configuration. Make a new validator account with ./prysm.sh validator accounts create --wallet-dir=/home/pz/Desktop/test-eth2-wallet
```

```
bazel run //validator accounts import -- --keys-dir=/home/pz/Workspace/Ethereum/eth2_pyrmont_deposit/

Enter a wallet directory (default: /home/pz/.eth2validators/prysm-wallet-v2):
/home/pz/Desktop/test-eth2-wallet
Password requirements: at least 8 characters including at least 1 alphabetical character, 1 number, and 1 unicode special character. Must not be a common password nor easy to guess
New wallet password:
Confirm password:
[2020-11-22 08:14:38]  INFO accounts: Successfully created new wallet wallet-path=/home/pz/Desktop/test-eth2-wallet
Enter the password for your imported accounts:
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [8s:0s]
Successfully imported 9 accounts, view all of them by running accounts list
```

**Comment by fabdarice** [comment]
I agree with you that it shouldn't ask for a New wallet password, since the password has already been created previously.

**Comment by realdevknow** [comment]
@fabdarice The Fatal error was only reached if I used a different wallet password than the existing wallet in the New / Confirm prompts. If I used the same password I knew I used originally, it worked despite the misleading New Password prompts.

**Comment by fabdarice** [comment]
@realdevknow yes I did set a different password as well, was still able to import the keys.

**Comment by 0xKiwi** [comment]
Hello @fabdarice ! Thank you for making an issue! This definitely seems like a problem with the accounts process.
Any updates on #7909 ? We've been focusing on the release so haven't had the time to review it.

@rauljordan wdyt about the change in #7909?

**Comment by fabdarice** [comment]
hey @0xKiwi , #7909 should be ready to go.
I originally made it a lot more complex than it should be.
