### ISSUE TITLE
FATAL Validator: Could not determine if beacon chain started:.... (Error while trying to run the validator)

### ISSUE THREAD

**Issue by ethstak3r** [prysmaticlabs/prysm#7894]
Hello,
The below error has popped up in my command prompt while trying to run the validator according to step 6 in the link: https://docs.prylabs.network/docs/testnet/pyrmont 

FATAL validator: Could not determine if beacon chain started: Could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connectex: No connection could be made because the target machine actively refused it."

I don't know what's causing this. Please advise.. how do I solve this?
I am using Windows 10 Home.
Thank you in advance.

**Comment by 0xKiwi** [comment]
Hello @ethstak3r ! Thanks for creating an issue!

Are you running your beacon node? Is it running properly if so? 

Also, what version of Prysm are you using? 

Thank you!
