### ISSUE TITLE
Windows accounts import issue:  "file already exists without proper 0600 permissions"

### ISSUE THREAD

**Issue by dv8silencer** [prysmaticlabs/prysm#7898]
#🐞 Bug Report

`[2020-11-22 09:02:07] FATAL accounts: Could not import accounts: could not write accounts: file already exists without proper 0600 permissions`

### Description
In Windows (with no prior existing wallet at the location), if you accounts import first (which creates the wallet and imports) and then immediately again, it will give the above error.  See:

```
PS H:\...\prysm\validator> .\validator.exe accounts import --keys-dir H:\prysmstuff\testKeys0 --pyrmont
[2020-11-22 09:06:51]  WARN flags: Running on Pyrmont Testnet
Enter a wallet directory (default: C:\Users\dv8si\AppData\Roaming\Eth2Validators\prysm-wallet-v2):

Password requirements: at least 8 characters including at least 1 alphabetical character, 1 number, and 1 unicode special character. Must not be a common password nor easy to guess
New wallet password:
Confirm password:
[2020-11-22 09:06:57]  INFO accounts: Successfully created new wallet wallet-path=C:\Users\dv8si\AppData\Roaming\Eth2Validators\prysm-wallet-v2
Enter the password for your imported accounts:
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [3s:0s]
Successfully imported 5 accounts, view all of them by running accounts list
```
**Immediately re-executed**:
```
PS H:\...\prysm\validator> .\validator.exe accounts import --keys-dir H:\prysmstuff\testKeys0 --pyrmont
[2020-11-22 09:07:05]  WARN flags: Running on Pyrmont Testnet
[2020-11-22 09:07:05]  INFO prompt: (wallet path) C:\Users\dv8si\AppData\Roaming\Eth2Validators\prysm-wallet-v2
Wallet password:
Enter the password for your imported accounts:
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [3s:0s]
[2020-11-22 09:07:14] FATAL accounts: Could not import accounts: could not write accounts: file already exists without proper 0600 permissions
```

Now, this seems to be because in shared/fileutil/fileutil.go for WriteFile() ~L63:
```
	if FileExists(expanded) {
		info, err := os.Stat(expanded)
		if err != nil {
			return err
		}
		if info.Mode() != params.BeaconIoConfig().ReadWritePermissions {
			return errors.New("file already exists without proper 0600 permissions")
		}
	}
	return ioutil.WriteFile(expanded, data, params.BeaconIoConfig().ReadWritePermissions)
```
Here, the first time, the file won't exist.  It will use ioutil.WriteFile to create the the file and write it.  Unfortunately, it appears that the ReadWritePermissions are ignored.  This may be OS-dependent behavior.  I'm not quite sure where to look on Windows to definitively find the permissions but a simple right click on all-accounts.keystore.json shows it "Read and execute" checked.

### Has this worked before in a previous version?

I believe it worked before but may have been a while ago.

## 🌍  Your Environment

**Operating System:**

Windows 10 (AMD64)

**What version of Prysm are you running? (Which release)**

Current master 98557e8f5e62c2f716bcfca3b843fb0d2738d78a

**Comment by egk10** [comment]
Same issue , trying to add another validator 
![importar key validador](https://user-images.githubusercontent.com/69823897/100021250-f78abc00-2dbf-11eb-8694-9e043398e4cc.PNG)

**Comment by alec-francis** [comment]
I can confirm this issue. Ran into the same error when adding a second validator on my Windows machine.

**Comment by samjessup** [comment]
I also hit this problem.

In case it's useful, I confirmed that os.stat.Perm() on windows currently returns 0666 for a normal file, and 0444 if you set the windows read only flag.   Changing windows security permissions on the file makes no difference, it will always return 0666 even if you do not have access to the file.

**Comment by achimachim** [comment]
Hello samjessup ..i am having this problem right now too. Did you find a way how to solve it?

**Comment by achimachim** [comment]
@ Alec Francis ..https://github.com/prysmaticlabs/prysm/issues/7898#issuecomment-735314390 ..im having the same problem. Did you find a solution?

**Comment by alec-francis** [comment]
> @ Alec Francis ..[#7898 (comment)](https://github.com/prysmaticlabs/prysm/issues/7898#issuecomment-735314390) ..im having the same problem. Did you find a solution?

I actually switched to Ubuntu Server. It's much more practical than Windows for running a resilient node. Since I switched everything has been great.

**Comment by achimachim** [comment]
https://github.com/prysmaticlabs/prysm/issues/7898#issuecomment-748439227 ..but do you know whether there would be a solution to continue with windows? ..i dont want to change actually, its all setup now with windows..

**Comment by alec-francis** [comment]
I don't know, sorry. I never looked into it. Maybe someone else will chime in at some point.

**Comment by samjessup** [comment]
I don't have a workaround or fix yet, @Cipioo has a pull request in for a very similar issue ( #8164 ).   Nearly the same fix would apply here, or the whole thing should be abstracted to a function to fix once, I don't know what would be best.

**Comment by Cipioo** [comment]
Agreed, I think there should be a better solution to resolve both these at the same time.

**Comment by achimachim** [comment]
well, i just solved it, with the huge help of one in the community. ..just summarizing it abstract: 1. get the old and new keys (not depositing yet) 2. create a new wallet (make sure you never use the old wallet again cause of slashing) 3. import the old and new keys to the new wallet 4. ..and then finish the deposit.. ..just adding does not work out, cause of the mentioned problem..
