### ISSUE TITLE
[Accounts] Remove imported wallet `wallet create` 

### ISSUE THREAD

**Issue by fabdarice** [prysmaticlabs/prysm#7907]
# Description
`wallet create` today doesn't provide anything beneficial for imported wallet as it will simply create an empty directory.
On top of that, it asks for a password, which is ultimately never used because no accouns are imported in that step.
People got confused (i.e: #7893 ).

This ticket suggests removing Imported Wallets from `wallet create` since `accounts import` already provide everything we need for that feature.

Discussion on discord: https://discord.com/channels/476244492043812875/667761857209040916/780122268046589952

**Comment by rauljordan** [comment]
We received feedback from some users running a cloud deployment that they really need the ability to create an empty imported wallet and then dynamically import keys later. Unfortunately, we'll have to close this PR given the importance of that feature to these large stakers
