### ISSUE TITLE
Utilize Certificate/Key for Secure gRPC Connections

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#791]
In the future, we'll need to enforce secure gRPC connections to some degree, as this is a critical point of failure when it comes to beacon node vs. validator client interactions. gRPC supports this out of the box, we just have to provide the .crt and .key files required for secure connections through which data can be sent through.

**Comment by cyberbono3** [comment]
Hey. I can start dig into it. Can u clarify if it is required to utilize Certificate/Key for gRPC connections between beacon node and validator client only ? or for all gRPC connections?

**Comment by cyberbono3** [comment]
Could you please supply me with instructions for self signed certificates?

**Comment by prestonvanloon** [comment]
I think this is more of a documentation issue. We just need someone to provide an example of how to use gRPC client / server certificates and how to generate one with openssl.

**Comment by prestonvanloon** [comment]
Assigning to @har00ga, but welcoming any external contributor to provide an example. Thanks!

**Comment by mcdee** [comment]
I was looking at this yesterday as part of the validator clean-ups.  From what I can tell the situation is a little weird:

  - the validator defaults to a non-secure connection
  - the validator will create a secure connection if the `--tls-cert` parameter is applied.  This parameter expects a CA root certificate for the CA that signed the beacon node's certificate

This is somewhat non-standard.  A more common way of doing things would be:

  - the validator has a `--tls` parameter that sets up a secure connection between the validator and beacon node
  - the `--tls-cert` parameter is optional for beacon nodes that have certificates signed by CAs that are not well-known

It may also be possible to attempt a TLS connection first and downgrade to an insecure connection if that fails, although this isn't something I've tried before so not sure how grpc will take it.  I'll see if I can play around with this at the weekend to work out if we need code/parameter changes, what they are, and give some kind of write-up for secure beacon<->validator communications.

**Comment by har00ga** [comment]
No problem, will add a note about this to the docs. :slightly_smiling_face:
