### ISSUE TITLE
Failed block safety check: validator history empty for public key

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#7918]
# 🐞 Bug Report 

### Description

User reported issue that they were missing block proposals. They found in their logs that the slashing protection mechanism blocked their block proposal.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

ExecStart=/usr/local/bin/validator --web --pyrmont --datadir /var/lib/prysm/validator_pry --wallet-dir /var/lib/prysm/validator_pry --wallet-password-file /var/lib/prysm/validator_pry/password.txt --graffiti "StakingToTheMoon" --accept-terms-of-use

## 🔥 Error

<pre><code>
level=error msg="Failed block safety check" error="failed to get proposal history: validator history empty for public key: 0x8f45b3954aebe0bca36d9edd582320a9646db
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0-beta.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by akarub** [comment]
This is the validator: https://pyrmont.beaconcha.in/validator/0x8f45b3954aebe0bca36d9edd582320a9646db2537995a678cde04472562dbaba064414c68ef500c7d4cb4fb2f424e84c#blocks

**Comment by akarub** [comment]
I also have this on the logs:

`Nov 18 03:00:17 staking-server validator[55834]: time="2020-11-18 03:00:17" level=warning msg="error creating directory: /var/lib/prysm/validator_pry" error="dir already exists without proper 0700 permissions" prefix=tos`

The validator.db was created on the folder. The datetime is being updated, but the size stayed the same, 600KB

![image](https://user-images.githubusercontent.com/74686152/99922280-b5ae3700-2d27-11eb-9987-6ec2a69196ef.png)

I've followed this guide:
https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-pyrmont-prysm-a10b5129c7e3

**Comment by terencechain** [comment]
Setting priority to high

**Comment by akarub** [comment]
I ran the chown again and restarted the node. The size of the validator.db has grown, but hadn't got new proposals to see if it's working now.

![image](https://user-images.githubusercontent.com/74686152/100093342-4fbccf00-2e4f-11eb-86f1-a36c966e7c8b.png)

**Comment by akarub** [comment]
One of the validators from the same setup, was able to successfuly propose a new block:
https://pyrmont.beaconcha.in/validator/0x89620cb60d646bc79b32051802e2ede9c0cff767015f7d24c94a54aede70a5eaea561db0919b0647abc5559cef96d092#blocks

Is it safe to assume the other validator that had problems, will be able to propose new blocks, or should I wait to see?

**Comment by rauljordan** [comment]
Resolved in v1.0.1
