### ISSUE TITLE
validator --version doesn't print out actual version but Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}

### ISSUE THREAD

**Issue by agro1986** [prysmaticlabs/prysm#7924]
# 🐞 Bug Report

### Description

 

```
validator --version
```

prints out

```
validator version Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}. Built at: 2020-11-23T21:20:48+09:00
```

### Has this worked before in a previous version?

don't know. works with `beacon-chain --version` which gives

```
beacon-chain version Prysm/v1.0.0-beta.3/f361450e8da18033f5458b018e3e6784295f50ca. Built at: 2020-11-23 06:51:54+00:00
```

## 🔬 Minimal Reproduction

```
bazel build //validator:validator --config=release
cp bazel-bin/validator/validator_/validator /usr/local/bin/
```

then run

```
validator --version
```

built on amazon linux 2

## 🔥 Error

<pre><code>

$ validator --version
2020/11/23 21:20:48 exit status 128
validator version Prysm/{STABLE_GIT_TAG}/{STABLE_GIT_COMMIT}. Built at: 2020-11-23T21:20:48+09:00

$ echo $?
0
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
amazon linux 2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.0.0-beta.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by pinglamb** [comment]
I tested with your command and the build reports proper version

Build command:
```
bazelisk build //validator:validator --config=docker-sandbox --config=release
```

Result:
```
$ ./bazel-bin/validator/validator_/validator --version
validator version Prysm/v1.0.0.rc.1/f361450e8da18033f5458b018e3e6784295f50ca. Built at: 2020-11-23 17:59:03+00:00
```

Base on the bazel config, the values of `STABLE_GIT_TAG` and `STABLE_GIT_COMMIT ` are defined in `./scripts/workspace_status.sh`, and in `.bazelrc`:

```
build:release --workspace_status_command=./scripts/workspace_status.sh
```

I guess your validator bin is built without `--config=release`. Can you try again?

**Comment by agro1986** [comment]
@pinglamb I think I found the cause. The snippet below:
```
bazel run //validator:validator -- accounts import ...
```
(which is on popular guides like https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-pyrmont-prysm-a10b5129c7e3 )

Will cause bazel to be rebuilt without "--config=release" option, which will cause the wrong output.

Is there a (potential) security vulnerability if you import validator keys using a binary without --config=release?

Btw the guide here: https://docs.prylabs.network/docs/mainnet/joining-eth2/

also has the command

```
bazel run //validator:validator -- accounts import ...
```

So the same issue might arise following prysm's official docs

**Comment by agro1986** [comment]
modifying the command to:

```
bazel run //validator:validator --config=release -- accounts import ...
```

might be a potential solution to that

**Comment by 0xKiwi** [comment]
Hey @agro1986 , thanks for filing this. @prestonvanloon is this something we can improve its display of on the validator?

**Comment by rauljordan** [comment]
Binaries are now stamped and documentation is updated to build from source using --config=release
