### ISSUE TITLE
Connecting to Infura with JWT

### ISSUE THREAD

**Issue by mohamedmansour** [prysmaticlabs/prysm#7939]
Infura only has JWT Authentication, meanwhile Prysm has Cert authentication. Would be nice if we can use different authentication providers for the --http-web3provider

**Comment by shayzluf** [comment]
working on it

**Comment by mohamedmansour** [comment]
> working on it

Awesome thanks! Please work with @nisdas on his fallback eth1 node because the intent of using authenticated infura would be for a fallback url in case the local primary url fails.
