### ISSUE TITLE
Macs with M1 chip are missing precompiled binaries (darwin-arm64)

### ISSUE THREAD

**Issue by soumensahoo** [prysmaticlabs/prysm#7950]
# 🐞 Bug Report

### Description
I am using Mac mini (with latest M1 Model) and all commands are run in Rosetta 2 terminal.
When starting Beacon-chain node using following command, it throws following error#1.
./prysm.sh beacon-chain --http-web3provider=$HOME/Mainnet/geth.ipc

When running the command with environment variable, it throws error#2 below. 
PRYSM_ALLOW_UNVERIFIED_BINARIES=1 ./prysm.sh beacon-chain --http-web3provider=$HOME/Mainnet/geth.ipc

Currently i am using workaround by downloading the binary from git prysm project and running the binary directly. 
"./dist/beacon-chain-v1.0.0-darwin-amd64 --http-web3provider=$HOME/Mainnet/geth.ipc"

Error#1:
Latest Prysm version is v1.0.0.
Downloading beacon chain@v1.0.0 to /Users/soum/prysm/./dist/beacon-chain-v1.0.0-darwin-arm64 (automatically selected latest available version)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2337    0  2337    0     0   5228      0 --:--:-- --:--:-- --:--:--  5228
Verifying binary integrity.
shasum: /Users/soum/prysm/./dist/beacon-chain-v1.0.0-darwin-arm64.sha256: no properly formatted SHA checksum lines found
Failed to verify Prysm binary. Please erase downloads in the
dist directory and run this script again. Alternatively, you can use a
A prior version by specifying environment variable USE_PRYSM_VERSION
with the specific version, as desired. Example: USE_PRYSM_VERSION=v1.0.0-alpha.5
If you must wish to continue running an unverified binary, specific the
environment variable PRYSM_ALLOW_UNVERIFIED_BINARIES=1

Error#2:
Latest Prysm version is v1.0.0.
Downloading beacon chain@v1.0.0 to /Users/soum/prysm/./dist/beacon-chain-v1.0.0-darwin-arm64 (automatically selected latest available version)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2337    0  2337    0     0   6976      0 --:--:-- --:--:-- --:--:--  6976
Starting Prysm beacon-chain --http-web3provider=/Users/soum/Mainnet/geth.ipc
/Users/soum/prysm/./dist/beacon-chain-v1.0.0-darwin-arm64: line 1: syntax error near unexpected token newline'
/Users/soum/prysm/./dist/beacon-chain-v1.0.0-darwin-arm64: line 1: <!doctype html>'

### Has this worked before in a previous version?
This is first time i am using prysm.sh in Mac os.

## 🔬 Minimal Reproduction
I followed the steps from https://docs.prylabs.network/docs/mainnet/joining-eth2

## 🔥 Error
See description above

**Comment by soumensahoo** [comment]
I think the following Beacon Node Run command ("PRYSM_ALLOW_UNVERIFIED_BINARIES=1 ./prysm.sh beacon-chain --http-web3provider=$HOME/Mainnet/geth.ipc") is trying to download "beacon-chain-v1.0.0-darwin-arm64" but in the repository the actual file name is beacon-chain-v1.0.0-darwin-amd64 
The variable ${arch} (i.e. uname -m) defined in prysm.sh returns arm64 not amd64, that's why it returns the html error above.
Not sure if it is Mac OS issue in the new M1 processor model.

Code Snippet from prysm.sh:
file=beacon-chain-${prysm_version}-${system}-${arch}
curl -L "https://prysmaticlabs.com/releases/${file}" -o $BEACON_CHAIN_REAL

**Comment by prestonvanloon** [comment]
@soumensahoo we do not offer arm64 binaries are mac at this time. 

You may try compiling the code yourself, but we have not tested on M1 chips yet so please observe carefully and try with a testnet before staking any real value ETH.

**Comment by soumensahoo** [comment]
I am running the eth1 node and the beacon-chain node(by running the beacon-chain node binary directly) and getting below errors from time to time. I just restart and it runs fine until error pop up again. not to mention I am running both in Mac mini M1 chip. 

eth1 node run logs:
INFO [11-28|13:40:22.135] Imported new chain segment               blocks=19   txs=2560 mgas=236.828 elapsed=8.212s mgasps=28.839 number=11343890 hash="194544…80648e" age=17h41m47s dirty=356.15MiB
INFO [11-28|13:40:30.286] Imported new chain segment               blocks=21   txs=2448 mgas=262.145 elapsed=8.151s mgasps=32.158 number=11343911 hash="48f24e…0d2a01" age=17h37m49s dirty=360.74MiB
assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation
(StateRecovery.cpp:304 check_cfg)

beacon-chain node run logs:
[2020-11-28 15:50:10]  INFO slotutil: 63h11m12s until chain genesis genesisTime=2020-12-01 07:00:23 -0500 EST genesisValidators=21063
[2020-11-28 15:51:10]  INFO slotutil: 63h10m12s until chain genesis genesisTime=2020-12-01 07:00:23 -0500 EST genesisValidators=21063
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1075b64d8 abi_kind=6 emulation_interval=[0x107a96fac,0x107a96fc0) instruction_interval=[0x107a96f98, 0x107a96fc0) x86_rip=0x40bf250
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)
 

![2B122859-FCF4-4637-896F-1616BD121103](https://user-images.githubusercontent.com/30180875/100527332-a142c200-319f-11eb-9dac-2c1c93cb9e1a.jpeg)

**Comment by prestonvanloon** [comment]
Thanks for that screenshot! Running the amd64 binaries on Mac M1 arm64 chips is not recommended at this time.

**Comment by rauljordan** [comment]
Closing this issue, we are not supporting M1 at the moment and have no plans to do so in the short term, sorry @soumensahoo

**Comment by Sajjon** [comment]
Any update for M1 support?

**Comment by prestonvanloon** [comment]
@Sajjon M1 should work with the darwin amd64 binaries. I'll take a look into cross compiling arm64 for darwin this week.

**Comment by Sajjon** [comment]
@prestonvanloon awesome, looking forward hearing from you! Would be nice to not involve Rosetta 2.

**Comment by mrabino1** [comment]
% PRYSM_ALLOW_UNVERIFIED_BINARIES=1 ./prysm.sh beacon-chain
Latest Prysm version is v1.3.9.
Beacon chain is up to date.
Starting Prysm beacon-chain 
/Users/ooooooooo/eth2node/prysm/./dist/beacon-chain-v1.3.9-darwin-arm64: line 1: syntax error near unexpected token `newline'
/Users/ooooooooo/eth2node/prysm/./dist/beacon-chain-v1.3.9-darwin-arm64: line 1: `<!doctype html>'


------

Looking forward to the cross compiling.. happy to test when it is avail..

**Comment by mrabino1** [comment]
I suspect this may also require an updated prysm.sh    .. n?

**Comment by prestonvanloon** [comment]
> I suspect this may also require an updated prysm.sh .. n?

We could amend prysm.sh to download the darwin_amd64 binary for M1 chips. M1 can run either amd or arm, but it is faster with arm. At least that is how I understand it.

**Comment by mrabino1** [comment]
pretty sure this works for an M1.. 

readonly wrapper_dir="$(dirname "$(get_realpath "${BASH_SOURCE[0]}")")/dist"

 if [ "$(uname -s)" == "Darwin" ] && [ "$(uname -m)" == "arm64" ]
then
arch="amd64"
else
arch=$(uname -m)
arch=${arch/x86_64/amd64}
arch=${arch/aarch64/arm64}
fi
readonly os_arch_suffix="$(uname -s | tr '[:upper:]' '[:lower:]')-$arch"

**Comment by voska** [comment]
I've been running (amd64) Prysm on M1 for the past few months without issues, but in seeking better performance, I tried compiling natively for M1 arm64. Currently, Bazel 3.7.0 is required to compile Prysm, and Bazel doesn't have an arm64 build for 3.7.0, but they do for 4.1.0.

If we can update Prysm to use Bazel 4.1.0, then we should be able to successfully compile darwin-arm64 builds.

**Comment by prestonvanloon** [comment]
@voska Prysm is up to date with bazel, but there may be some issues with building Prysm with bazel on an M1 device. 
I've seen a few comments here and there in discord but there hasn't been any work from an M1 chip owner on reporting or fixing bazel builds for Prysm.

A hard requirement for our infrastructure and delivery of ARM binaries for Mac is that it can be cross compiled from a linux host. The cross compilation support takes some hours of head scratching to complete. It can be done, but it seems to be low priority at this time.

**Comment by leolara** [comment]
I think the status of this is almost 99% complete with this PR: https://github.com/prysmaticlabs/prysm/pull/10192

I think just this is missing: https://github.com/prysmaticlabs/prysm/issues/10263

**Comment by prestonvanloon** [comment]
@leolara the true blocker for this is the cross compilation config. 

For darwin amd64, we run the following 
```
bazel build --config=release --config=osx_amd64_docker  //cmd/beacon-chain //cmd/validator //cmd/client-stats
```

We need to establish a `osx_arm64_docker` config that would produce arm64 binaries.

**Comment by leolara** [comment]
> @leolara the true blocker for this is the cross compilation config.
> 
> For darwin amd64, we run the following
> 
> ```
> bazel build --config=osx_amd64_docker  //cmd/beacon-chain //cmd/validator //cmd/client-stats
> ```
> 
> We need to establish a `osx_arm64_docker` config that would produce arm64 binaries.

As requested: https://github.com/prysmaticlabs/prysm/pull/10981 :-)

**Comment by prestonvanloon** [comment]
This is done since v3.0.0. We just need to amend the prysm.sh and prysm.bat scripts for darwin users to download the ARM64 binary instead of using the AMD64 version.
