### ISSUE TITLE
Multiple ETH1 endpoints

### ISSUE THREAD

**Issue by vvavepacket** [prysmaticlabs/prysm#7969]
# 🚀 Feature Request

### Description

Currently the beacon node accepts a single URL for ETH1 endpoint. Due to the recent AWS outage, its important to have multiple endpoint support just incase if the primary ETH1 fails, beacon node will then fallback to the secondary URL. Then if the primary endpoint recovers then start to switch from secondary to primary

### Describe the solution you'd like

Modify the beacon node code to accept multiple endpoints, and if the first URL fails, fallback to the second one.. Maintain a polling call to all endpoints for health checks. If they are healthy then recover to the first URL.

### Describe alternatives you've considered

As of now this is handled outside the application level which can be on NGINX / proxies. But its best to move this to application code.

**Comment by MysticRyuujin** [comment]
Lighthouse has this now 👍 

An optional for those looking is [dshackle](https://github.com/emeraldpay/dshackle). However, the eth_chainId function is broken in the latest release (v0.8.3) and a fix is pending release.

**Comment by alrevuelta** [comment]
Lighthouse recently added this feature on [v.1.0.1](https://github.com/sigp/lighthouse/releases/tag/v1.0.1). Would be really nice to have :D

**Comment by aviadshimoni** [comment]
I've really considered moving to lighthous because of that. that's a really useful and easy and reasonable feature.
thanks for the community.

**Comment by mondsen** [comment]
I agree it would be a good thing, but you have several of options
- move to lighthouse as you said
- use nginx as proxy to do this
- wait

**Comment by MysticRyuujin** [comment]
NGINX and/or HAProxy won't fail over unless the node is completely unavailable, it doesn't do any real health check on the state of the node. `dshackle` is a better option, but that's relying on a 3rd party dependency and it has it's own issues here and there, but it's probably the best option for now.

**Comment by vvavepacket** [comment]
I'll wait. I believe the next release will include this MR.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/06/20,
06:50:04 PM

**Comment by nisdas** [comment]
I will be working on this today, should be ready by v1.05. With mainnet launch last week, there were other more pressing issues to deal with but I am now free to pursue this today.

**Comment by AtHeartEngineer** [comment]
> I will be working on this today, should be ready by v1.05. With mainnet launch last week, there were other more pressing issues to deal with but I am now free to pursue this today.

new hero

**Comment by nisdas** [comment]
Alright PR is up in #8062, if everything goes well you guys can expect it in v1.0.5

**Comment by nisdas** [comment]
Alright feature has been merged in, so you all will see this in v1.05 next week.
