### ISSUE TITLE
Compiling issue - Build v1.0.0 did NOT complete successfully - an error of analyzers

### ISSUE THREAD

**Issue by LukkePrague** [prysmaticlabs/prysm#7980]
# 🐞 Bug Report

### Description

I was unable to compile build v1.0.0, everytime I got an error. When I disabled analyzers it solved my issue:

go to /go/prysm/BUILD.bazel and put a # sign at the beginning of every line starting from "//tools/analyzers/maligned:go_tool_library", up to "//tools/analyzers/properpermissions:go_tool_library",

### Has this worked before in a previous version?

Didn't try a previous version.

## 🔬 Minimal Reproduction

git clone -b v1.0.0 --single-branch https://github.com/prysmaticlabs/prysm.git
cd prysm
bazel build //beacon-chain:beacon-chain --config=release

## 🔥 Error

<pre><code>
tarting local Bazel server and connecting to it...
DEBUG: /home/validator/.cache/bazel/_bazel_validator/877fbf541a51cff22e7e9ea106fabafd/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_clang_gen not using checked in configs as user set attr to 'False' 
DEBUG: /home/validator/.cache/bazel/_bazel_validator/877fbf541a51cff22e7e9ea106fabafd/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:14: rbe_ubuntu_gcc_gen not using checked in configs as user set attr to 'False' 
INFO: Analyzed target //validator:validator (659 packages loaded, 12220 targets configured).
INFO: Found 1 target...
ERROR: /home/validator/.cache/bazel/_bazel_validator/877fbf541a51cff22e7e9ea106fabafd/external/com_github_google_go_cmp/cmp/BUILD.bazel:3:11: GoCompilePkg external/com_github_google_go_cmp/cmp/cmp.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags blst_enabled,blst_enabled -src external/com_github_google_go_cmp/cmp/compare.go -src ... (remaining 41 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags blst_enabled,blst_enabled -src external/com_github_google_go_cmp/cmp/compare.go -src ... (remaining 41 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: nogo: errors found by nogo during build-time code analysis:
/home/validator/.cache/bazel/_bazel_validator/877fbf541a51cff22e7e9ea106fabafd/sandbox/linux-sandbox/158/execroot/prysm/external/com_github_google_go_cmp/cmp/report_text.go:17:16: crypto-secure RNGs are required, use CSPRNG or PRNG defined in github.com/prysmaticlabs/prysm/shared/rand: rand.New() (from "math/rand")
/home/validator/.cache/bazel/_bazel_validator/877fbf541a51cff22e7e9ea106fabafd/sandbox/linux-sandbox/158/execroot/prysm/external/com_github_google_go_cmp/cmp/report_text.go:17:25: crypto-secure RNGs are required, use CSPRNG or PRNG defined in github.com/prysmaticlabs/prysm/shared/rand: rand.NewSource() (from "math/rand")
Target //validator:validator failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 54.034s, Critical Path: 7.46s
INFO: 161 processes: 9 internal, 152 linux-sandbox.
FAILED: Build did NOT complete successfully

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.1
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.0 Mainnet Ready
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rkapka** [comment]
This error occurred while following https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-pyrmont-prysm-a10b5129c7e3

**Comment by 0xKiwi** [comment]
Hello @LukkePrague ! Thanks for submitting an issue. Can you provide your local bazel version?

**Comment by LukkePrague** [comment]
> Hello @LukkePrague ! Thanks for submitting an issue. Can you provide your local bazel version?

Hi. As rkapka mentioned, my local bazel version is latest at the moment - 3.7.0.

**Comment by LukkePrague** [comment]
The same issue with v1.0.1

**Comment by LukkePrague** [comment]
I just installed brand new machine (so not using VMWare this time) and I got a same error! Same for v1.0.2. I had to disable analyzers in order to have this built...

**Comment by nisdas** [comment]
@LukkePrague Is this still an issue for you ?
