### ISSUE TITLE
Consolidate All Prysm Web Backends Into One

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7984]
# 💎 Issue

### Background

Currently, the web UI utilizes several different backends to retrieve information, leading to annoying CORS issues and complex configuration options at runtime. This has been evidenced by significant user reports of errors and overall complexity when adding features.

Instead, we should consolidate all of the backends into a single /api proxy endpoint, and the validator client should handle fetching all the data the UI requests, including logs which today are done via _yet another_ backend http://localhost:8080/logs.

**Comment by yorickdowne** [comment]
R-Amen.

Ideal operation in my book is that the Web UI can be accessed remotely, not just via localhost: That is, http://prysm-host:7500 is sufficient. This will also allow it to be secure with a TLS reverse proxy such as traefik, caddy or nginx.
