### ISSUE TITLE
Validator wont get passed download step

### ISSUE THREAD

**Issue by banananramatron** [prysmaticlabs/prysm#7986]
# 💎 Issue
Trying to run prysm.bat on winows CLI:
set PRYSM_AUTORESTART=1
cmd /k prysm.bat validator --datadir=C:\prysm --web
![image](https://user-images.githubusercontent.com/75162432/100499248-cac61280-31cc-11eb-83c1-1573be04718f.png)

### Background
installed Geth and beacon node and they are running ok
![image](https://user-images.githubusercontent.com/75162432/100499256-e9c4a480-31cc-11eb-99f1-4cdd9d0172a2.png)
file structure:
![image](https://user-images.githubusercontent.com/75162432/100499266-fcd77480-31cc-11eb-8c7d-a812dff554cf.png)
Setup Node as per this guide: https://kb.beaconcha.in/guides/pyrmont-windows

 Context and background information on the discussion...
ran medalla, didnt get this error
ran pyrmont and got this same issue.  Got the validator to work by using running cli inside directory with prysm.bat rather than the command in the parent directory

**Comment by banananramatron** [comment]
Found something that fixed it.  I loaded all parameters into a batch file called validator.bat.  When prysm.bat was running it would run validator.bat and therefore loop the program again.  Renamed Validator.bat to Validator run.bat and its working correctly.
![image](https://user-images.githubusercontent.com/75162432/100513800-c1d93f00-31d4-11eb-9a7b-b1ef00a1efaf.png)

**Comment by nisdas** [comment]
@rkapka Re-opening this as its still an issue, users shouldn't need to create custom batch files to run the binaries.

**Comment by banananramatron** [comment]
I have batch files for convenience to keep all commands in one place instead of manually typing it out or using a shortcut

**Comment by rauljordan** [comment]
Have we seen more reports of this? If I recall, this is the only report we have received. If the solution was sufficient for @banananramatron perhaps we can close @nisdas

**Comment by 0xKiwi** [comment]
Closing unless it can be replicated.
