### ISSUE TITLE
Unable to process past headers cannot convert block header with nil block number

### ISSUE THREAD

**Issue by Mr-Lim** [prysmaticlabs/prysm#7989]
Mainnet
ETH1 node is Nethermind .41 using default mainnet.cfg (includes fastsync of receipts, bodies, ancient barrier of 11000000 for both)
Running Prysm beacon-node

AFTER processing deposits from ETH1, Prysm starts giving the errors below. Prior to this, no errors:

←[90m[2020-11-28 12:55:56]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=17920 ←[32mgenesisValidators←[0m=17910
←[90m[2020-11-28 12:56:00]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=18432 ←[32mgenesisValidators←[0m=18422
←[90m[2020-11-28 12:56:45]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=18944 ←[32mgenesisValidators←[0m=18934
←[90m[2020-11-28 12:56:49]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=19456 ←[32mgenesisValidators←[0m=19446
←[90m[2020-11-28 12:57:34]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=19968 ←[32mgenesisValidators←[0m=19958
←[90m[2020-11-28 12:57:39]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=20480 ←[32mgenesisValidators←[0m=20470
←[90m[2020-11-28 12:57:43]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Processing deposits from Ethereum 1 chain ←[32mdeposits←[0m=20992 ←[32mgenesisValidators←[0m=20982
←[90m[2020-11-28 12:57:44]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Minimum number of validators reached for beacon-chain to start ←[32mChainStartTime←[0m=2020-12-01 07:00:23 -0500 EST
←[90m[2020-11-28 12:57:44]←[0m ←[33m WARN←[0m←[36m blockchain:←[0m ProcessAttestations routine waiting for genesis time
←[90m[2020-11-28 12:57:44]←[0m ←[33m WARN←[0m←[36m blockchain:←[0m Genesis time received, now available to process attestations
←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m blockchain:←[0m Initialized beacon chain genesis state
←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m initial-sync:←[0m Genesis time has not arrived - not syncing ←[32mgenesisTime←[0m=2020-12-01 07:00:23 -0500 EST
←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m p2p:←[0m Started discovery v5 *removed*
←[90m[2020-11-28 12:57:45]←[0m ←[32m INFO←[0m←[36m p2p:←[0m Node started p2p server *removed*
←[90m[2020-11-28 12:57:50]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
←[90m[2020-11-28 12:57:57]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
←[90m[2020-11-28 12:57:57]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
←[90m[2020-11-28 12:58:03]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
←[90m[2020-11-28 12:58:03]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
←[90m[2020-11-28 12:58:09]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
←[90m[2020-11-28 12:58:10]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number
←[90m[2020-11-28 12:58:16]←[0m ←[32m INFO←[0m←[36m powchain:←[0m Connected to eth1 proof-of-work chain ←[32mendpoint←[0m=http://localhost:8545
←[90m[2020-11-28 12:58:16]←[0m ←[31mERROR←[0m←[36m powchain:←[0m Unable to process past headers cannot convert block header with nil block number

**Comment by prestonvanloon** [comment]
@nisdas do you know what causes a nil block number? Perhaps the eth1 node was not fully synced?

**Comment by nisdas** [comment]
@prestonvanloon This is a current open issue with nethermind
https://github.com/NethermindEth/nethermind/issues/2525

@Mr-Lim please subscribe to the above issue ^

Block requests fail occasionally which make it difficult to continue processing block headers and logs.

**Comment by tkstanczak** [comment]
We believe that it will happen for users who did not select --Sync.DownloadReceiptsInFastSync true during the initial sync. In such cases for now resync of Nethermind is required so the receipts are available - version 1.9.41 has this option enabled by default to avoid problems for users who are not aware of it.

**Comment by nisdas** [comment]
Closing this as it has been resolved in nethermind as of 1.9.41
