### ISSUE TITLE
Validator exits with "Could not wait for validator activation while waiting for deposit"

### ISSUE THREAD

**Issue by stefanlsd** [prysmaticlabs/prysm#7995]
# 🐞 Bug Report

### Description

 Could not wait for validator activation: could not receive validator activation from stream: rpc error: code = Unavailable desc = transport is closing" prefix=validator

### Has this worked before in a previous version?
Unsure as this may be under specific conditions

## 🔬 Minimal Reproduction
- Running on  pyrmont
- Running two accounts on single validator
Beacon chain is in sync with testnet
(time="2020-11-29 18:50:42" level=info msg="New gRPC client connected to beacon node" addr="192.168.4.29:32820" prefix=rpc
time="2020-11-29 18:50:44" level=info msg="Synced new block" block=0x55e9c07e... epoch=2539 finalizedEpoch=2537 finalizedRoot=0xc2070367... prefix=blockchain slot=81253 slotInEpoch=5
time="2020-11-29 18:50:44" level=info msg="Finished applying state transition" attestations=128 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0)
- Did a GTH deposit and it hasn't yet been activated yet (https://beaconscan.com/pyrmont/validator/0x84e78ce870e7986f64115432162805a5f8a8722954d4605bcdf337dc476e42f436456776fe16546434af0b16778fd936)
-Started Validator. Crashes after a bit. Logs below.

## 🔥 Error
Validator Logs (in debug)
<pre><code>

time="2020-11-29 18:43:40" level=info msg="Logs will be made persistent" logFileName="/data/validator.log"
time="2020-11-29 18:43:40" level=info msg="File logging initialized"
time="2020-11-29 18:43:40" level=warning msg="Running on Pyrmont Testnet" prefix=flags
time="2020-11-29 18:43:40" level=info msg="Opened validator wallet" keymanager-kind=direct prefix=node wallet="/keys/direct"
time="2020-11-29 18:43:40" level=info msg="Checking DB" databasePath="/data" prefix=node
time="2020-11-29 18:43:40" level=info msg="Starting validator node" prefix=node version="Prysm/v1.0.0/9d174d592735da35244d11f1cd44f47b469e9018. Built at: 2020-11-27 20:39:48+00:00"
time="2020-11-29 18:43:40" level=debug msg="Starting 2 services: [*prometheus.Service *client.ValidatorService]" prefix=registry
time="2020-11-29 18:43:40" level=debug msg="Starting service type *prometheus.Service" prefix=registry
time="2020-11-29 18:43:40" level=debug msg="Starting service type *client.ValidatorService" prefix=registry
time="2020-11-29 18:43:40" level=debug msg="Starting prometheus service" address="0.0.0.0:8080" prefix=prometheus
time="2020-11-29 18:43:40" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
time="2020-11-29 18:43:40" level=info msg="Validating for public key" prefix=validator publicKey=0x84e78ce870e7
time="2020-11-29 18:43:40" level=info msg="Validating for public key" prefix=validator publicKey=0x83c1beabd91c
time="2020-11-29 18:43:40" level=debug msg="gRPC stream started." backend=[] method="/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForChainStart"
time="2020-11-29 18:43:40" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator
time="2020-11-29 18:43:40" level=info msg="Beacon chain started" genesisTime=2020-11-18 12:00:07 +0000 UTC prefix=validator
time="2020-11-29 18:43:40" level=debug msg="gRPC request finished." backend=[] duration=492.042µs method="/ethereum.eth.v1alpha1.Node/GetSyncStatus"
time="2020-11-29 18:43:40" level=debug msg="gRPC stream started." backend=[] method="/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForActivation"
time="2020-11-29 18:43:40" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x84e78ce870e7 status="UNKNOWN_STATUS"
time="2020-11-29 18:43:40" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x83c1beabd91c status="UNKNOWN_STATUS"
time="2020-11-29 18:43:52" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x84e78ce870e7 status="UNKNOWN_STATUS"
time="2020-11-29 18:43:52" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x83c1beabd91c status="UNKNOWN_STATUS"
time="2020-11-29 18:44:04" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x84e78ce870e7 status="UNKNOWN_STATUS"
time="2020-11-29 18:44:04" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x83c1beabd91c status="UNKNOWN_STATUS"
time="2020-11-29 18:44:16" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x84e78ce870e7 status="UNKNOWN_STATUS"
time="2020-11-29 18:44:16" level=info msg="Waiting for deposit to be observed by beacon node" prefix=validator pubKey=0x83c1beabd91c status="UNKNOWN_STATUS"
time="2020-11-29 18:44:32" level=fatal msg="Could not wait for validator activation: could not receive validator activation from stream: rpc error: code = Unavailable desc = transport is closing" prefix=validator

</code></pre>
Beacon Logs
<pre><code>

time="2020-11-29 18:33:59" level=info msg="Logs will be made persistent" logFileName="/data/beacon.log"
time="2020-11-29 18:33:59" level=info msg="File logging initialized"
time="2020-11-29 18:33:59" level=warning msg="Running on Pyrmont Testnet" prefix=flags
time="2020-11-29 18:33:59" level=info msg="Using "max_cover" strategy on attestation aggregation" prefix=flags
time="2020-11-29 18:33:59" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
time="2020-11-29 18:34:00" level=info msg="Deposit contract: 0x8c5fecdc472e27bc447696f431e425d02dd46a8c" prefix=node
time="2020-11-29 18:34:00" level=info msg="Waiting for state to be initialized" prefix=initial-sync
time="2020-11-29 18:34:00" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.0.0/9d174d592735da35244d11f1cd44f47b469e9018. Built at: 2020-11-27 20:42:50+00:00"
time="2020-11-29 18:34:00" level=info msg="gRPC server listening on port" address="0.0.0.0:4000" prefix=rpc
time="2020-11-29 18:34:00" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
time="2020-11-29 18:34:00" level=info msg="Starting JSON-HTTP API" address="127.0.0.1:3500" prefix=gateway
time="2020-11-29 18:34:00" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2020-11-29 18:34:01" level=info msg="Chain genesis time reached" genesisTime="2020-11-18 12:00:07 +0000 UTC" genesisValidators=100010 prefix=slotutil
time="2020-11-29 18:34:01" level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://eth-goerli.alchemyapi.io/v2/vN5dtmOYRrA_5xgL-nCCPDyGgGZgtwyq" prefix=powchain
time="2020-11-29 18:34:04" level=info msg="Loading blocks to fork choice store, this may take a while." endSlot=81087 prefix=blockchain startSlot=81088
time="2020-11-29 18:34:04" level=info msg="Starting initial chain sync..." prefix=initial-sync
time="2020-11-29 18:34:04" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2020-11-29 18:34:04" level=info msg="Started discovery v5" ENR="enr:-LK4QBcb0nkzuNqXNCjApVTYkj6S3y6xknsRKCxH0LEP2iltXnsdCisWFinu-ogr8WqA8E8K3Gpv6eIOwD4AQzC8wjMBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA7CIeVAAAgCf__________gmlkgnY0gmlwhCJaNz6Jc2VjcDI1NmsxoQNlFc26s9SdT5LMyd-wGYZzpCdqeacxfj-wwZctTRePOIN0Y3CCMsiDdWRwgi7g" prefix=p2p
time="2020-11-29 18:34:04" level=info msg="Node started p2p server" multiAddr="/ip4/192.168.4.28/tcp/13000/p2p/16Uiu2HAmKTap1cQ7CsiDfh2E3ssXNxeiHGktm535NtJEBLSYSujm" prefix=p2p
time="2020-11-29 18:34:04" level=info msg="Node started external p2p server" multiAddr="/ip4/34.90.55.62/tcp/13000/p2p/16Uiu2HAmKTap1cQ7CsiDfh2E3ssXNxeiHGktm535NtJEBLSYSujm" prefix=p2p
time="2020-11-29 18:34:04" level=warning msg="IP address is not accessible" address="34.90.55.62:13000" error="dial tcp 34.90.55.62:13000: connect: connection refused" prefix=p2p protocol=tcp
time="2020-11-29 18:34:10" level=info msg="Processing block batch of size 56 starting from  0xf09bb988... 81089/81170 - estimated time remaining 28s" blocksPerSecond=2.8 peers=7 prefix=initial-sync
time="2020-11-29 18:34:15" level=info msg="New gRPC client connected to beacon node" addr="192.168.4.24:11837" prefix=rpc
time="2020-11-29 18:34:34" level=info msg="Processing block batch of size 1 starting from  0x4aa254c7... 81151/81172 - estimated time remaining 7m0s" blocksPerSecond=0.1 peers=25 prefix=initial-sync
time="2020-11-29 18:34:34" level=warning msg="Batch is not processed" err="no good blocks in batch" prefix=initial-sync
time="2020-11-29 18:34:34" level=info msg="Synced to finalized epoch - now syncing blocks up to current head" headSlot=81172 prefix=initial-sync syncedSlot=81151
time="2020-11-29 18:34:36" level=info msg="Synced new block" block=0xa423a3da... epoch=2536 finalizedEpoch=2534 finalizedRoot=0x90291c48... prefix=blockchain slot=81170 slotInEpoch=18
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
GKE - Kubernetes
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.1 docker container
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by stefanlsd** [comment]
To add, once the deposits were accepted on the chain the validator started working and hasn't had any issues. Seems to be some race condition while waiting for deposits.

**Comment by rauljordan** [comment]
Closed by #8057. Validator will reattempt connections
