### ISSUE TITLE
Logs in Prysm UI are not the same as the command line

### ISSUE THREAD

**Issue by mrabino1** [prysmaticlabs/prysm#7996]
v1.0.1

When you look at the validator logs in the prysm UI they are different than the logs thrown to syslog (for example).. including around which validators are activated.

**Comment by rkapka** [comment]
Can you please give a specific example and/or screenshots of the differences?

**Comment by mrabino1** [comment]
difficult to do without doxing myself.. summary.. I have more than one validator.. and in the prysm UI log of hte validator.. it shows only one..

**Comment by rauljordan** [comment]
Duplicate of https://github.com/prysmaticlabs/prysm-web-ui/issues/94, please track that one for a resolution
