### ISSUE TITLE
validator accounts delete (then select all) doesn't actually delete all of the accounts

### ISSUE THREAD

**Issue by mrabino1** [prysmaticlabs/prysm#7997]
v1.0.1

running
 ./validator accounts delete --wallet-dir={dir}/.eth2validators/prysm-wallet-v2

and then select ALL

it looks like it selects them all. the user confirms.. it starts to delete.. and then completes

then you run 
./validator accounts list --wallet-dir={dir}/.eth2validators/prysm-wallet-v2
and about half are still there.. 

repeat the process above multiple times.. and then after about 5 loops.. the user actually has deleted all of the accounts..

**Comment by rauljordan** [comment]
Thanks @mrabino1 this is a big problem, we will look into soon

**Comment by shayzluf** [comment]
looking into it

**Comment by rkapka** [comment]
As I mentioned on Discord, we are not able to reproduce the issue. Can you please give us some more information? For example how many validators you had initially, is this Mainnet, Pyrmont or Medalla etc.

**Comment by mrabino1** [comment]
mainnet .. ubuntu server. ARM. imported 200 validators (not funded yet)..  then then try to delete all of them... it only does half..

**Comment by mrabino1** [comment]
<img width="765" alt="2020-12-02_19-52-29" src="https://user-images.githubusercontent.com/4902221/100921517-f868cf80-34dc-11eb-9e8d-fdf6856af9c1.png">
<img width="787" alt="2020-12-02_20-09-11" src="https://user-images.githubusercontent.com/4902221/100921537-fbfc5680-34dc-11eb-8909-36c171a9823d.png">
<img width="748" alt="2020-12-02_20-11-38" src="https://user-images.githubusercontent.com/4902221/100921550-028ace00-34dd-11eb-80b3-259223430843.png">
<img width="1446" alt="2020-12-02_20-12-24" src="https://user-images.githubusercontent.com/4902221/100921558-0585be80-34dd-11eb-8c29-db6ddedc26ce.png">
<img width="881" alt="2020-12-02_20-13-25" src="https://user-images.githubusercontent.com/4902221/100921569-09194580-34dd-11eb-8eca-2127ca5843f8.png">
<img width="1431" alt="2020-12-02_20-15-54" src="https://user-images.githubusercontent.com/4902221/100921582-0caccc80-34dd-11eb-9018-ec6149d3a21b.png">
<img width="1070" alt="2020-12-02_20-16-32" src="https://user-images.githubusercontent.com/4902221/100921603-12a2ad80-34dd-11eb-96c0-8e46a4f87052.png">
<img width="814" alt="2020-12-02_20-17-04" src="https://user-images.githubusercontent.com/4902221/100921607-15050780-34dd-11eb-80b8-4e302b6ee1e1.png">
<img width="1075" alt="2020-12-02_20-17-36" src="https://user-images.githubusercontent.com/4902221/100921617-17676180-34dd-11eb-8fa1-439a5629f779.png">
<img width="1070" alt="2020-12-02_20-19-44" src="https://user-images.githubusercontent.com/4902221/100921622-19c9bb80-34dd-11eb-9f10-ba90376e087e.png">
<img width="750" alt="2020-12-02_20-20-08" src="https://user-images.githubusercontent.com/4902221/100921627-1c2c1580-34dd-11eb-9c17-d783c7a7fd0c.png">
<img width="774" alt="2020-12-02_20-20-33" src="https://user-images.githubusercontent.com/4902221/100921637-1e8e6f80-34dd-11eb-86c0-ff6bab4793d5.png">
<img width="998" alt="2020-12-02_20-20-59" src="https://user-images.githubusercontent.com/4902221/100921648-23532380-34dd-11eb-9f9d-2edde55cabdd.png">
<img width="894" alt="2020-12-02_20-21-59" src="https://user-images.githubusercontent.com/4902221/100921656-264e1400-34dd-11eb-8c3f-0bc2cc7cb91c.png">
<img width="750" alt="2020-12-02_20-22-28" src="https://user-images.githubusercontent.com/4902221/100921660-28b06e00-34dd-11eb-984c-5aa29c70d72c.png">
<img width="1055" alt="2020-12-02_20-23-43" src="https://user-images.githubusercontent.com/4902221/100921670-2b12c800-34dd-11eb-8136-d303c0140add.png">
<img width="979" alt="2020-12-02_20-25-27" src="https://user-images.githubusercontent.com/4902221/100921674-2d752200-34dd-11eb-9674-00f5d118a05b.png">
<img width="1027" alt="2020-12-02_20-26-44" src="https://user-images.githubusercontent.com/4902221/100921684-2fd77c00-34dd-11eb-8611-08b5148e3446.png">

**Comment by rkapka** [comment]
Thank you for the reproduction steps, this is very helpful.

**Comment by mrabino1** [comment]
so in text

create 200 validators offline
import all 200
delete all
(only about half get deleted)
delete all 
(only about half get deleted)
...... repeat
then ultimately it deleted them all..
