### ISSUE TITLE
can i build eth2.0 client   by  openthereum-prysm  in china?by the steps in guild file.

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#8001]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by AKZ98** [comment]
#8001

**Comment by nisdas** [comment]
Hey @navy665180 , openethereum and Prysm shouldnt have any issues running, this question is better suited in our discord server.
https://discord.gg/Fz4vsKbaXn
