### ISSUE TITLE
Error http2: Transport: cannot retry 

### ISSUE THREAD

**Issue by alec-francis** [prysmaticlabs/prysm#8005]
# 💎 Issue

### Background

My beacon node seems to be running fine but I did see one occurrence of the error below in the log.

```
Nov 30 19:44:34 ubuntu beacon-chain[8008]: time="2020-11-30 19:44:34" level=error msg="Post "https://mainnet.infura.io/v3/<redacted>": http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error" prefix=powchain
```

### Description
This may not matter as the error has only shown up once and everything else seems to be running fine.

I'm running version 1.0.2 and here is my start command:

```
beacon-chain --datadir=/var/lib/prysm/beacon --http-web3provider=https://mainnet.infura.io/v3/<redacted> --accept-terms-of-use
```

Also, I checked Infura and I'm well under the daily request limit.

Thanks,

Alec

**Comment by prestonvanloon** [comment]
Without looking into this at all... this seems like an error with infura.

**Comment by alec-francis** [comment]
No worries. I'll close. I thought I would just put the error on record as it hasn't come up in previous issues on this repo.

Alex
