### ISSUE TITLE
ERROR powchain: Unable to process past logs stream error: stream ID 15; INTERNAL_ERROR

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#8008]
# 🐞 Bug Report
hi !   In WINDOWS  STEP2:
I use infura,to get the note of eth1.0
prysm.bat beacon-chain --http-web3provider=https://mainnet.infura.io/v3/6d453562570341079329bf3d7a408ccb

i think the problem is i can not connect infura.  i am not sure.also i don't kown how to solve the problem.
chould you help me ??or give me any advice?
thanks!

![无标题](https://user-images.githubusercontent.com/75147624/100705679-975cd100-33e2-11eb-99e8-a9b97d2b8097.png)

 

ERROR powchain: Unable to process past logs read tcp 192.168.1.102:55365->52.207.135.19:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

windows10

<pre>
  <code>

  </code>
prysm.bat beacon-chain --http-web3provider=<YOUR_ETH1_NODE_ENDPOINT>

**What version of Prysm are you running? (Which release)**
V1.0.2
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
This is an issue with your internal eth1 provider, so this is something we cant solve.
