### ISSUE TITLE
Separate monitoring-host from UI Logs endpoint

### ISSUE THREAD

**Issue by eduadiez** [prysmaticlabs/prysm#8010]
# 🚀 Feature Request

### Description

In dappnode, we need a way to set the `monitoring-host` and the UI logs endpoint separately and be able to set `monitoring-host` to 0.0.0.0. Right now we use domains in dappnode, but sometimes we are not able to update the new ip in time, so we get this error:

```
time="2020-11-30 14:25:01" level=error msg="Could not listen to host:port :validator.prysm.dappnode:8081: listen tcp 172.33.0.14:8081: bind: cannot assign requested address" prefix=prometheus
```
### Describe the solution you'd like

It'd be ideal if we could set (even if it's with an environment variable) different endpoints for the `monitoring-host` and where the UI connects to obtain the logs

**Comment by rauljordan** [comment]
Part of #7984, subscribe to that issue for a resolution
