### ISSUE TITLE
Why won't my deposit verify on BeaconChain when running my validator?  I am losing ETH by the minute.

### ISSUE THREAD

**Issue by JBC2323** [prysmaticlabs/prysm#8049]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Can you please provide any info?

**Comment by prestonvanloon** [comment]
Duplicate of #8050
