### ISSUE TITLE
My computer crashed running my BeaconNode - Critical Process Error and Memory Management

### ISSUE THREAD

**Issue by JBC2323** [prysmaticlabs/prysm#8050]
The last issue was my Dad's Node.  His validator has been confirming deposit since Monday and he is losing Ethereum.  This is an outrage.  His Node is 1883.

Mine is 3069.  This is a seperate outrage in that my computer went blue screen on memory management.  Then I got a critical process error and I have to re-install Windows.  What is going on here!

Justin Chapman

# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
I understand your dad (validator 1883) is not active. 
Can you provide any details? 
What version of Prysm are you running? 
Can you share any logs in your beacon node or validator? 
Are there any errors?

For your validator 3069, I understand you reinstalled windows. Is there still an issue?

**Comment by JBC2323** [comment]
Microsoft Windows [Version 10.0.18363.1198]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\>D:

D:\>cd prysm

D:\prysm>prysm.bat validator accounts import --keys-dir="E:\Justin's Flash Backup\Dad's Ethereum Validator Node\ETH 2.0 Mainnet Deposit\validator_keys\keystore-m_12381_3600_0_0_0-1605229897.json"
A subdirectory or file D:\prysm\dist already exists.
Latest prysm release is v1.0.3.
Using prysm version v1.0.3.
'Validator' is not recognized as an internal or external command,
operable program or batch file.
WARN GPG verification is not natively available on Windows.
WARN Skipping integrity verification of downloaded binary
Verifying binary authenticity with SHA256 Hash.
SHA256 Hash Match
Starting Prysm validator accounts import --keys-dir="E:\Justin's Flash Backup\Dad's Ethereum Validator Node\ETH 2.0 Mainnet Deposit\validator_keys\keystore-m_12381_3600_0_0_0-1605229897.json"
[2020-12-04 14:59:15]  WARN flags: Running on ETH2 Mainnet
Enter a wallet directory (default: C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2):

Password requirements: at least 8 characters including at least 1 alphabetical character, 1 number, and 1 unicode special character. Must not be a common password nor easy to guess
New wallet password:
Confirm password:
[2020-12-04 14:59:29]  INFO accounts: Successfully created new wallet wallet-path=C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2
Enter the password for your imported accounts:
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [1s:0s]
Successfully imported 1 accounts, view all of them by running accounts list
Press any key to continue . . .

D:\prysm>prysm.bat validator
A subdirectory or file D:\prysm\dist already exists.
Latest prysm release is v1.0.3.
Using prysm version v1.0.3.
'Validator' is not recognized as an internal or external command,
operable program or batch file.
WARN GPG verification is not natively available on Windows.
WARN Skipping integrity verification of downloaded binary
Verifying binary authenticity with SHA256 Hash.
SHA256 Hash Match
Starting Prysm validator
[2020-12-04 14:59:52]  WARN flags: Running on ETH2 Mainnet
[2020-12-04 14:59:52]  INFO prompt: (wallet path) C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2
Wallet password:
[2020-12-04 14:59:59]  INFO node: Opened validator wallet keymanager-kind=direct wallet=C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2\direct
[2020-12-04 14:59:59]  WARN node: Slashing protection file C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2\direct\validator.db is missing.
If you changed your --wallet-dir or --datadir, please copy your previous "validator.db" file into your current --datadir.
Disregard this warning if this is the first time you are running this set of keys.
[2020-12-04 14:59:59]  INFO node: Checking DB databasePath=C:\Users\18176\AppData\Roaming\Eth2Validators\prysm-wallet-v2\direct
[2020-12-04 14:59:59]  INFO node: Starting validator node version=Prysm/v1.0.3/fc7c6776f66c675dfc0e26a9f16141720bf9f2df. Built at: 2020-12-01 14:23:47+00:00
[2020-12-04 14:59:59]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2020-12-04 14:59:59]  INFO validator: Validating for public key publicKey=0xb4e55bd91193
[2020-12-04 14:59:59]  INFO validator: Waiting for beacon chain start log from the ETH 1.0 deposit contract
[2020-12-04 14:59:59]  INFO validator: Beacon chain started genesisTime=2020-12-01 06:00:23 -0600 CST
[2020-12-04 14:59:59]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0xb4e55bd91193 status=UNKNOWN_STATUS
[2020-12-04 15:00:11]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0xb4e55bd91193 status=UNKNOWN_STATUS
[2020-12-04 15:00:23]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0xb4e55bd91193 status=UNKNOWN_STATUS
[2020-12-04 15:00:35]  INFO validator: Waiting for deposit to be observed by beacon node pubKey=0xb4e55bd91193 status=UNKNOWN_STATUS

**Comment by JBC2323** [comment]
It's still waiting been waiting for 5 days

**Comment by prestonvanloon** [comment]
What is this public key `0xb4e55bd91193`? 

It's not validator 1883 (`0x8031a3d23db9d7d3ed733cb7daaca8368de476ee14d53ea8962d7970be433041dc3db253cf0a1b34a8497abdb8ddcd57`).

and it's not 3069 (`0xa8813256536de76870d9bc94dec6ff16614fc2461b25a5ddc4aa809530665786cba531ea98fc53f9e472489162b21a84`).

**Comment by JBC2323** [comment]
I have no idea that's a good question
I just used the keystore that was saved post-deposit
Thanks for your quick feedback

**Comment by JBC2323** [comment]
I am about to re-install WIndows after mine crashed and re-boot my validator node.  I have been getting penalized all day.

**Comment by JBC2323** [comment]
Do I need to access my Dad's keystore and insert the correct validator key into the public key section or will that break the keystore file for his deposit key

**Comment by prestonvanloon** [comment]
I think that is the issue. You'll need to restore the validator client with the correct keystore to start validating again.

**Comment by JBC2323** [comment]
In the keystore JSON file right?
Where it says "description": "", "pubkey": "........................ that's where I type my Dad's Validator Node Public Key?

**Comment by JBC2323** [comment]
Inside the JSON Keystore-m file?

**Comment by JBC2323** [comment]
Thanks again!

**Comment by JBC2323** [comment]
About to try

**Comment by prestonvanloon** [comment]
> Do I need to access my Dad's keystore and insert the correct validator key into the public key section or will that break the keystore file for his deposit key

First thing you'll want to do is to make sure your Dad's keys are not running on any other machine. If you run your Dad's validator and he runs it too, then you could get slashed. 

When you import the validator keys from the launchpad keystore, it doesn't modify the original keystore file. Prysm loads the JSON file, decrypts it with the provided password, then creates a new wallet in prysm with a new password.

> Where it says "description": "", "pubkey": "........................ that's where I type my Dad's Validator Node Public Key?

There is no typing of public keys. You'll need to find the correct keystore, you do not modify the json file!

**Comment by JBC2323** [comment]
I went in the JSON script and replaced the wrong public ID with my Dad's and it worked

**Comment by JBC2323** [comment]
Unbelivable for some reason it had the wrong public ID - What is this public key 0xb4e55bd91193
The keystore file

**Comment by JBC2323** [comment]
With mine I am very concerned about the memory mamagement error and critical process error 
WHen I re-install WIndows I will reach back out with feedback.  I have an external D Drive that has 16TB HD

**Comment by prestonvanloon** [comment]
> I went in the JSON script and replaced the wrong public ID with my Dad's and it worked

I don't think this worked. You might have seen the public key printed when you completed the import, but the secret key in the keystore will not match.

https://github.com/prysmaticlabs/prysm/blob/01bf97293feae72ad8298bf670352927629321bd/validator/keymanager/imported/import.go#L106-L113

Can you please reach out on discord? I'm very concerned about your situtation. https://discord.gg/z9efH7e

**Comment by JBC2323** [comment]
It isn't working you're right this is awful

**Comment by JBC2323** [comment]
The validator is running but not attesting

**Comment by JBC2323** [comment]
Why would we receive a keystore with a validation public address different than my Dad's validation address

**Comment by prestonvanloon** [comment]
Please reach out on discord and we can help you there. https://discord.gg/z9efH7e

**Comment by prestonvanloon** [comment]
We connected on discord and resolved this offline. The user's account was recovered successfully from their mnemonic phrases.
