### ISSUE TITLE
ERROR powchain: Could not connect to powchain endpoint error=403 Forbidden: {"jsonrpc":"2.0","error":{"code":-32002,"message":"rejected due to project ID settings"}}

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#8054]
# 🐞 Bug Report

### Description

./prysm.sh beacon-chain --http-web3provider=https://mainnet.infura.io/v3/8ac88cb61b9347139361bba090d26f0f
use infura ,then
![mistake](https://user-images.githubusercontent.com/75147624/101275569-81d01880-37e1-11eb-9d27-9e39c8cccd69.png)

could not dial eth1 nodes

### Has this worked before in a previous version?

no
 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

ERROR powchain: Could not connect to powchain endpoint error=403 Forbidden: {"jsonrpc":"2.0","error":{"code":-32002,"message":"rejected due to project ID settings"}}

could not dial eth1 nodes
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).connectToPowChain
	beacon-chain/powchain/service.go:366
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).waitForConnection
	beacon-chain/powchain/service.go:438
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1
	beacon-chain/powchain/service.go:257
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1374

## 🌍  Your Environment

ubuntu

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
what is wrong?i try many times ,but aways like this

**Comment by prestonvanloon** [comment]
Hi! Sorry you are having issues. It looks like a misconfiguration in your infura settings. Could you confirm that you don't have any security restrictions set on your infura project? 

It would look something like this
![Screenshot from 2020-12-06 09-58-45](https://user-images.githubusercontent.com/7246818/101288124-b0ca9800-37a9-11eb-9fb8-48816e397167.png)

![Screenshot from 2020-12-06 09-58-38](https://user-images.githubusercontent.com/7246818/101288126-b3c58880-37a9-11eb-9c1d-c3012c4877a7.png)

**Comment by navy665180** [comment]
could you explan "security restrictions"? it is on infura?or on my operator system(ubuntu)?

**Comment by navy665180** [comment]
ethereum@ubuntu:~$ curl https://mainnet.infura.io/v3/dd973522085c4043a159cb34e9503f4d
404 page not found

**Comment by R3TSU** [comment]
> ethereum@ubuntu:~$ curl https://mainnet.infura.io/v3/dd973522085c4043a159cb34e9503f4d
> 404 page not found

@navy665180, Just want to add, this is how to test the endpoint

curl -X POST https://mainnet.infura.io/v3/dd973522085c4043a159cb34e9503f4d -H 'Content-Type: application/json' -H 'cache-control: no-cache'  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'

when successful, it should return something like this
{"jsonrpc":"2.0","id":1,"result":"0xaec9fb"}

that endpoint is successful, suggesting you recreate your project id before somebody starts abusing your account.

**Comment by nisdas** [comment]
Would echo what @R3TSU mentioned above, please recreate your project ID. Unfortunately you have published your private url here so anyone can now abuse that url.

**Comment by nisdas** [comment]
As stated above this is an issue with infura, so it would be best to contact them. Closing this issue as this isn't something prysm can handle.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @navy665180)

**Comment by Mitoax** [comment]
This indeed works, after disable all checkbox and clean the allowlists, everything now works fine.
