### ISSUE TITLE
about infura

### ISSUE THREAD

**Issue by navy665180** [prysmaticlabs/prysm#8055]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

can not connect the infura. 
i guess the port is not open ??
how and where to open the port??
thanks!
![mistake](https://user-images.githubusercontent.com/75147624/101283475-90d0be00-3815-11eb-88a0-0fa339ebe1b4.png)

### Has this worked before in a previous version?no

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**linux

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**1.1.3

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

![mistake](https://user-images.githubusercontent.com/75147624/101283498-bc53a880-3815-11eb-8db7-e04bac6147a1.png)

**Comment by rauljordan** [comment]
Hi @navy665180 this seems like a problem with your infura settings, not in Prysm. Can you try to see if your infura options allow you to have a public endpoint?
