### ISSUE TITLE
Logging a countdown till next validator scheduled operation

### ISSUE THREAD

**Issue by danielschonfeld** [prysmaticlabs/prysm#8056]
# 🚀 Feature Request

### Describe the solution you'd like

Logging a countdown till the next validator scheduled operation across all validator public keys the process is assigned. A prometheus metric might not be a bad idea too.

I think it'll make for better ability to time upgrade and minor restarts, without losing on valuable profits, in particular proposing a block.

### Describe alternatives you've considered

At the moment there are no alternative, and a simple upgrade restart, or a config change, can cost you your spot at proposing a block and enjoy the greater financial incentives it brings with it.

**Comment by Novop** [comment]
Indeed a prometheus metric would be very helpful in timing validator restarts

**Comment by terencechain** [comment]
Did some work on this today:

<img width="897" alt="Screen Shot 2020-12-09 at 8 07 42 PM" src="https://user-images.githubusercontent.com/21316537/101721407-c2879600-3a5c-11eb-941f-a364ccdba911.png">

**Comment by danielschonfeld** [comment]
Wow this looks fantastic!!!!

**Comment by terencechain** [comment]
> Wow this looks fantastic!!!! Thank you!

Anytime. Thanks for the great feedback. This will be part of next mondays release

**Comment by potuz** [comment]
I would like this to be reverted. My reasons for this are twofold. On the one hand because this adds one extra message per slot `No duty until next epoch`  and `Next duty`  which makes 1) harder to read the log if you are looking for information and 2) requires space to keep these extra message every 12 second. 

On the other hand this information is already included in the logs that prysm has by default at level info: The attestation and proposal roles are scheduled and logged every 6.4 minutes in the validator logs (e.g. `Attestation schedule`) and this includes the precise slot when your validator will be attesting/proposing. And the current slot is being logged every slot by the beacon `Synced new block`, contains epoch, slot and the position of the slot in the epoch. This is all that a user needs to know where he/she stands and when he/she will be attesting. 

I think that the benefits of this PR are minimal compared to the above problems.

**Comment by terencechain** [comment]
> I would like this to be reverted. My reasons for this are twofold. On the one hand because this adds one extra message per slot `No duty until next epoch` and `Next duty` which makes 1) harder to read the log if you are looking for information and 2) requires space to keep these extra message every 12 second.
> 
> On the other hand this information is already included in the logs that prysm has by default at level info: The attestation and proposal roles are scheduled and logged every 6.4 minutes in the validator logs (e.g. `Attestation schedule`) and this includes the precise slot when your validator will be attesting/proposing. And the current slot is being logged every slot by the beacon `Synced new block`, contains epoch, slot and the position of the slot in the epoch. This is all that a user needs to know where he/she stands and when he/she will be attesting.
> 
> I think that the benefits of this PR are minimal compared to the above problems.

@danielschonfeld any input to this?

**Comment by danielschonfeld** [comment]
I don't generally disagree with @potuz assertions.  But I do want to ask couple questions for discussion
1) Does the current 'Attestation Schedule' message, also show when your validator is scheduled for Proposal?
  - My original intent was to have a way of mitigating losing on such a once in a while event, which was more profitable for the validator because of an upgrade restart or other server maintenance
 2) If it does, I am still thinking that in the case of multiple validators (imagine like 20 or 30), you still have to fish for this info to know if you're "safe" restarting your process.  In such cases, the next duty line, summarizing when you're supposed to work again, regardless of which validator it is, comes in very handy.

Having all that raised for discussion.  Perhaps there is room to make this logging facility a flag, and having it turned ``off`` by default.  

Also, if it is determined that this logging is verbose and pointless.  I would like to suggest perhaps, turning it into a prometheus consumable metric.   I think that will be valuable and leaves the decision of whether one wants to waste to space on it or not, entirely within the end user's hands.

**Comment by potuz** [comment]
>
> 1. Does the current 'Attestation Schedule' message, also show when your validator is scheduled for Proposal?
> 
Yes it does, there's a log message `Proposal schedule`
 
> 1. If it does, I am still thinking that in the case of multiple validators (imagine like 20 or 30), you still have to fish for this info to know if you're "safe" restarting your process.  In such cases, the next duty line, summarizing when you're supposed to work again, regardless of which validator it is, comes in very handy.

In case you have 20 - 30 validators then it doesn't matter, you will have duties throghout the epoch. In any case, there is going to be one message for each proposal slot (with multiple indexes if you have more than one validator proposing in that slot) and similar for attestations. 

> Also, if it is determined that this logging is verbose and pointless. I would like to suggest perhaps, turning it into a prometheus consumable metric. I think that will be valuable and leaves the decision of whether one wants to waste the space on it or not, entirely within the end user's hands.

This will be even worse, the prometheus db will increase dramatically having this on a per-pubkey basis. Prometheus keeps values of every single scrap.

**Comment by danielschonfeld** [comment]
> This will be even worse, the prometheus db will increase dramatically having this on a per-pubkey basis. Prometheus keeps values of every single scrap.
> 
> EDIT: On prometheus perhaps it won't be too dramatic to expose the slot of the duties, this would be only once per epoch per pubkey.

There is no need for per public key.  You only want to know when you're about to take an action.  It doesn't matter per public key, since it's an all or nothing.  One metric, with the next slot you're scheduled to have any kind of duty on.  Preferably two, one with ``next_attestation_slot`` and one with ``next_proposal_slot``.

**Comment by potuz** [comment]
> > This will be even worse, the prometheus db will increase dramatically having this on a per-pubkey basis. Prometheus keeps values of every single scrap.
> > EDIT: On prometheus perhaps it won't be too dramatic to expose the slot of the duties, this would be only once per epoch per pubkey.
> 
> There is no need for per public key. You only want to know when you're about to take an action. It doesn't matter per public key, since it's an all or nothing. One metric, with the next slot you're scheduled to have any kind of duty on. Preferably two, one with `next_attestation_slot` and one with `next_proposal_slot`.

That would be useless for the purpose you want it: validators get assigned a duty at epoch transitions. Consider you have two validators, on epoch start they are assigned on duties as follows.  The first validator is assigned on slot M to to attest. The second validator is assigned on slot M+1 to propose. In this circumstances you won't have any notice of the proposition.
