### ISSUE TITLE
Prysm beaconchain stops syncing / block processing after (VPN) reconnection

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#8059]
# 🐞 Bug Report

### Description

I have a prysm beacon node setup which I run over a vpn with port forwarding on a residential internet connection. The ISP disconnects every 24h and issues a new IP.
When the disconnect happens, obv Prysm loses all the peers. The vpn connection is reestablished. Prysm seems to reconnect to peers (75) and also has peers for all subnets etc (see logPeers). However, prysm shows no block syncing / processing activity afterwards - no log msgs on info lvl at all. I have to restart the beacon node because it cant recover.

There is only one error msg see below. Please see logs for further log msgs. Please note that the disconnection happens at around 02:47:52 and the vpn connection is re-established at around 02:48:48. And after that prysms starts to reconnect to peers.

Side note: Geth is reconnecting fine and stays synced.

### Has this worked before in a previous version?

It worked fine on the testnets without the vpn. It was fine the first two days with same version with vpn. But it seems that the problem doesn't occur every time there is an internet disconnection /vpn reconnection. So not sure what to deduct from that.

## 🔬 Minimal Reproduction

24h dis-/reconnect or manually dis/-reconnecting my modem or manually dis/-reconnecting for my device from the internet.

## 🔥 Error

The only log msg on lvl error is
<pre><code>
 level=error msg="Failed to find peers" error="failed to find peers for subnet" prefix=p2p

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain version Prysm/v1.0.2/b150acffca3d93e8cf1f404ff7e4602391017186.
  </code>
</pre>

[logdebug.txt](https://github.com/prysmaticlabs/prysm/files/5650163/logdebug.txt)
[logPeers.txt](https://github.com/prysmaticlabs/prysm/files/5650164/logPeers.txt)

**Comment by farazdagi** [comment]
Are you absolutely sure that after losing the connection node is stuck i.e. it doesn't get recovered in 6-8 minutes? Your logs do not show that, can you please share full logs?

**Comment by Phistr90** [comment]
@farazdagi Yes, I am sure that it doesnt recover in 6-8mins. It doesn't recover in at least 20mins. I did that the other day, wont try it again and lose money.
Also, Nishant told me that he was able to reproduce it. Their node recovered after 30mins but that's obv. totally unacceptable.

**Comment by farazdagi** [comment]
Ok, thank you for clarification. Definitely, such a long recovery is not normal (normally, we expect a node to get back online in couple of epochs at most). We will be looking into it, as a high priority item.

**Comment by Phistr90** [comment]
I had the same issue today midday. VPN reconnection (no connection for about <1min) and it took prysm about 20mins to recover.

**Comment by Phistr90** [comment]
Updated to v1.0.5 today. The reconnection worked today without a problem. As I pointed out before the problem is a little inconsistent but nonetheless this is a positive indication that it works now if you guys applied a fix in the new release.

**Comment by farazdagi** [comment]
Closing as the issue should be resolved now.
