### ISSUE TITLE
lots of "Incorrect voting" cause balance decrease 

### ISSUE THREAD

**Issue by nining** [prysmaticlabs/prysm#8074]
# 🐞 Bug Report

### Description

I'm hosting more than 500 validators on the same machine.  Most of the time the validator process worked perfectly.  But some time I got the following error message in the validator process log, and when I checked the validator's balance I found some decrease for that epoch.

<pre><code>
...
144578:time="2020-12-08 17:26:43" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1549 inclusionDistance=4 inclusionSlot=49572 newBalance=32.018810757 oldBalance=32.018824574 percentChange="-0.00004%" percentChangeSinceStart="0.00109%" prefix=validator pubKey=0xa8b1f5965559 startBalance=32.018463298
144592:time="2020-12-08 17:26:43" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1549 inclusionDistance=2 inclusionSlot=49570 newBalance=32.018621145 oldBalance=32.018631157 percentChange="-0.00003%" percentChangeSinceStart="0.00110%" prefix=validator pubKey=0xb2d3a08438a3 startBalance=32.018269881
144624:time="2020-12-08 17:26:43" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1549 inclusionDistance=4 inclusionSlot=49572 newBalance=32.008328782 oldBalance=32.008342599 percentChange="-0.00004%" percentChangeSinceStart="0.00109%" prefix=validator pubKey=0x914f82d99181 startBalance=32.007981323
144631:time="2020-12-08 17:26:43" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1549 inclusionDistance=4 inclusionSlot=49572 newBalance=32.007029398 oldBalance=32.007043215 percentChange="-0.00004%" percentChangeSinceStart="0.00109%" prefix=validator pubKey=0xa543adf8c220 startBalance=32.006681939
...
</code></pre>

<pre><code>
...
12804:time="2020-12-08 20:19:31" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1576 inclusionDistance=1 inclusionSlot=50433 newBalance=32.042429177 oldBalance=32.042431591 percentChange="-0.00001%" percentChangeSinceStart="0.00706%" prefix=validator pubKey=0x8f458d202078 startBalance=32.040168401
12922:time="2020-12-08 20:19:31" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=1576 inclusionDistance=1 inclusionSlot=50433 newBalance=32.032992646 oldBalance=32.03299506 percentChange="-0.00001%" percentChangeSinceStart="0.00698%" prefix=validator pubKey=0x93dc55f4de89 startBalance=32.030758287
...
</code></pre>

### Has this worked before in a previous version?

Previous version v1.0.3 also has this issue.

## 🔥 Error

<pre><code>

</code></pre>

If my validator process has this issue in an epoch, about 10 to 20 validators had been affected, not all 500 validators.  That's the most frustrating.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 x64
Kernel Linux beacon-node-2 5.8.0-29-generic #31~20.04.1-Ubuntu SMP Fri Nov 6 16:10:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.4
  </code>
</pre>

**Hardware configurations:**

<pre>
  <code>
4 vCPU on Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
8GB Memory
60+60GB SSD for OS and applications
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

<pre>
<code>
https://beaconcha.in/validator/25214
https://beaconcha.in/validator/24768
https://beaconcha.in/validator/26637
</code>
</pre>

**Comment by mikemr** [comment]
I am seeing similar issue 
time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477

**Comment by potuz** [comment]
All the slots reported here are votes on the first slot of the epoch. I think this is related to what has been discussed in R&D Discord

**Comment by terencechain** [comment]
> I am seeing similar issue
> time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477

does this persist? keep in mind when you first start out your validator client, this is what you will see in the first 2 epochs

**Comment by nining** [comment]
> > I am seeing similar issue
> > time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477
> 
> does this persist? keep in mind when you first start out your validator client, this is what you will see in the first 2 epochs

It persists all the time.  Now I'm monitoring the balance decrease event.  Everyday this issue occurs about 10~20 times, and every time it affected 10~20 validators.

**Comment by nining** [comment]
> > I am seeing similar issue
> > time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477
> 
> does this persist? keep in mind when you first start out your validator client, this is what you will see in the first 2 epochs

It persists.  And it's not the first 2 epochs after the validator activated.  Please check this validator https://beaconcha.in/validator/24791

**Comment by potuz** [comment]
> > > I am seeing similar issue
> > > time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477
> > 
> > 
> > does this persist? keep in mind when you first start out your validator client, this is what you will see in the first 2 epochs
> 
> It persists. And it's not the first 2 epochs after the validator activated. Please check this validator https://beaconcha.in/validator/24791 . It activated at epoch 977 and at epoch 2042 its balance decreased 2248G.
> 

Are you sure it was that validator? In epoch 2042 that validator attested in slot 65373, it's attestation was included in the next slot and it voted for the right head.

**Comment by potuz** [comment]
I wanted to add that in a day there are 7200 slots, 225 of which are the first slot of an epoch. With 500 validators you would expect in average to have 15-16 votes in the first slot of an epoch on each epoch. So when you get the first block late you will expect in average to have a balance decrease in as many validators as you are seeing. Given the numbers I see on mainnet I would have expected this to happen more often than 10-20 times a day (5%-10%)

**Comment by nining** [comment]
> > > > I am seeing similar issue
> > > > time="2020-12-10 13:29:51" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=2112 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.147345665 oldBalance=32.147395807 percentChange="-0.00016%" percentChangeSinceStart="0.13842%" prefix=validator pubKey=xxxx startBalance=32.102907477
> > > 
> > > 
> > > does this persist? keep in mind when you first start out your validator client, this is what you will see in the first 2 epochs
> > 
> > 
> > It persists. And it's not the first 2 epochs after the validator activated. Please check this validator https://beaconcha.in/validator/24791 . It activated at epoch 977 and at epoch 2042 its balance decreased 2248G.
> 
> Are you sure it was that validator? In epoch 2042 that validator attested in slot 65373, it's attestation was included in the next slot and it voted for the right head.

Here is the validator's log:

92820:time="2020-12-10 21:49:07" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=2040 inclusionDistance=1 inclusionSlot=65281 newBalance=32.07000012 oldBalance=32.070002368 percentChange="-0.00001%" percentChangeSinceStart="0.10021%" prefix=validator pubKey=0xb82d5e6fe8de startBalance=32.037894203

"2020-12-10 21:49:07" is the epoch 2042's time.

**Comment by potuz** [comment]
> 
> Here is the validator's log:
> 
> 92820:time="2020-12-10 21:49:07" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=true correctlyVotedTarget=false epoch=2040 inclusionDistance=1 inclusionSlot=65281 newBalance=32.07000012 oldBalance=32.070002368 percentChange="-0.00001%" percentChangeSinceStart="0.10021%" prefix=validator pubKey=0xb82d5e6fe8de startBalance=32.037894203
> 
> "2020-12-10 21:49:07" is around the epoch 2042's time (12/10/2020 9:49:11 PM).

Ok that's in epoch 2040 and the validator voted in slot 65280 which is the first block of the epoch. This seems to be the phenomenon described in previous comments

**Comment by rauljordan** [comment]
We suspect https://github.com/prysmaticlabs/prysm/pull/8094
https://github.com/prysmaticlabs/prysm/pull/8107 will resolve these issues. Will report once we have more proof

**Comment by rauljordan** [comment]
We believe the issues are now resolved by the improvements from #8094 and #8107 coming in release v1.0.6 this week. Let us know if you are still having issues afterwards

**Comment by rauljordan** [comment]
My bad, was confusing this issue with another that was causing missed votes. Reopening and will try out the solution on pyrmont for this issue today

**Comment by nining** [comment]
Before updated to v1.1.0, I'm using v1.0.5.  Now I have around 900 accounts.  Nearly every epoch there're several to dozens account's balance dropped.

**Comment by adamk-everythingandroid** [comment]
Not sure if this is related to this issue or change but thought I'd add into in case it helps.

I have had no issues with beacon node or validator (aside from my own network connection) for over a month, I upgraded to v1.1.0 2 days ago and my validator started missing attestations about 12 hours later with logs looking like the ones in this issue:
```
time="2021-01-22 05:49:47" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=11537 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 [...]
time="2021-01-22 05:49:47" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=11537 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 [...]
time="2021-01-22 05:49:47" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=11537 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 [...]
```

This happened overnight for me so I didn't look at it till the morning (about 7 hours of missed attestations). After restarting my services everything has been fine since.

Not sure if any of this information is relevant or a red herring:

 - just 2 minutes before attestations started being missed my validator submitted a block proposal (ended up being orphaned)
 - my beacon node stopped logging anything about 3 hours before the validator started missing attestations (no errors or info in the logs after that)
 - i asked on Discord and there were 2 other users with similar/related issues after upgrading to 1.1.0 (both missed attestations and restarted and then it was fine)

**Comment by SolidityFinance** [comment]
Having a similar issue to @adamk-everythingandroid. Everything operates great until it suddenly doesn't (resulting in incorrect head source and target). Once the head source and target are incorrect, all future votes will be incorrect (missed) and block proposals missed as well. Only a manual restart of the server seems to resolve the issue. Luckily this has only happened when I've been awake, but if not it seems this pattern would continue until manual intervention occurs.

Running 2 validators
Beaconchain has 128 peers
Ubuntu 20.04 x64
Prysm 1.10

**Comment by Jlonghi** [comment]
I am also running a lot of validators and experience this issue every 20 or so epochs. Some of my validators will miss and some will vote correct.

Can provide detailed logs if interested. 
```
time="2021-01-29 17:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=13325 inclusionDistance=1 inclusionSlot= newBalance=32.718421793 oldBalance=32.718381996 percentChange="0.00012%" percentChangeSinceStart="0.00195%" prefix=validator pubKey= startBalance=32.717783654
time="2021-01-29 17:33:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=13325 inclusionDistance=18446744073709551615 inclusionSlot=18446744073709551615 newBalance=32.710570177 oldBalance=32.71060171 percentChange="-0.00010%" percentChangeSinceStart="0.00175%" prefix=validator pubKey= startBalance=32.709998768

```

**Comment by alancwoo** [comment]
I'm running 1.2.1 and also just encountered this issue. It seems potentially related to https://github.com/prysmaticlabs/prysm/issues/8430

What I noticed is my first missed attestation occurred (for me across all validators) at 5:51 AM, epoch `17483`.

Looking at my beacon logs, it froze on the message almost 12 hours earlier with no further output until restarting:

> "Synced new block" block=0x2363c367... epoch=17379 finalizedEpoch=17377

Everything is working again after restarting the beacon service.

**Comment by rauljordan** [comment]
We have not seen many reports of this since the 1.3 versions of Prysm. Unless it becomes a noteworthy issue for a good portion of Prysm stakers, we can close this

**Comment by nining** [comment]
I still suffered the same problem.  I have 900 validators and it occurs in every hour

**Comment by potuz** [comment]
> I still suffered the same problem. I have 900 validators and it occurs in every hour.

900 validators vote in average 264 times per hour on the first slot of an epoch. It is highly likely that some of those blocks are late. The (block, epoch) fork choice change in the specs will fix this.
