### ISSUE TITLE
Remote signer wallets in 1.0.4 break backwards compatibility with older wallets

### ISSUE THREAD

**Issue by Jlonghi** [prysmaticlabs/prysm#8091]
# 🐞 Bug Report

### Description

Remote wallets created before 1.0.4 do not have 
```
"require_tls": true,
```
Causing an error when trying to start a validator that used tls with remote signer previously.
Adding require_tls fixes the issue.

### Has this worked before in a previous version?

There was no issues in versions before 1.0.4

## 🔬 Minimal Reproduction

Start a validator on version 1.0.3 or lower and use a keymanageropts.json with the form of 
 
```
{
	"remote_cert": {
		"crt_path":
		"key_path": 
		"ca_crt_path":
	},
	"remote_address": 
}
```
And connect to a remote-signer with tls. The above format was the format keymanageropts.json was created in older versions. In 1.0.4 it has the "require_tls": true, field.
## 🔥 Error

<pre><code>
level=fatal msg="Could not wait for validator activation: could not fetch validating keys: could not list accounts from remote server: rpc error: code = Unavailable desc = connection closed" prefix=validator
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.0.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by nisdas** [comment]
Seems like this PR is the cause: https://github.com/prysmaticlabs/prysm/pull/7953
Looks like it ended up having the opposite effect :) , @rkapka 

https://github.com/prysmaticlabs/prysm/pull/7953/files#diff-d315c7707882861692f23127b1360d9e4c5cc3722afa2d21c1b1a2bba2c33bd1R72

The default value for that flag is false, so it ends up being a requirement to run tls by default. Is that intended ?

**Comment by rkapka** [comment]
> The default value for that flag is false, so it ends up being a requirement to run tls by default. Is that intended ?

Yes, this is intended. TLS should be enabled by default.
