### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by stefa2k** [prysmaticlabs/prysm#8105]
# 🐞 Bug Report

### Description

Was updating host, running docker, got the panic two times below.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

Don't know, happened only once but two times in a row.

## 🔥 Error

```
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="Running on ETH2 Mainnet" prefix=flags
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Using "max_cover" strategy on attestation aggregation" prefix=flags
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="Starting beacon chain with max RPC page size of 100000" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Waiting for state to be initialized" prefix=initial-sync
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.0.4/b4437e6cecd78257d2699f42073a90a940baf716. Built at: 2020-12-07 18:32:43+00:00"
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Starting JSON-HTTP API" address="0.0.0.0:3500" prefix=gateway
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="gRPC server listening on port" address="0.0.0.0:4000" prefix=rpc
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Connected to eth1 proof-of-work chain" endpoint="http://geth:8545" prefix=powchain
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
prysm_beacon            | panic: runtime error: makeslice: cap out of range
prysm_beacon            |
prysm_beacon            | goroutine 166 [running]:
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).batchRequestHeaders(0xc0002fd7a0, 0xae9616, 0xae9334, 0xae9334, 0xae9616, 0x0, 0x0, 0xc000c21340)
prysm_beacon            |       beacon-chain/powchain/service.go:581 +0x77
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).cacheHeadersForEth1DataVote(0xc0002fd7a0, 0x9a3200, 0xc00220c100, 0x0, 0x0)
prysm_beacon            |       beacon-chain/powchain/service.go:785 +0xa8
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initPOWService(0xc0002fd7a0)
prysm_beacon            |       beacon-chain/powchain/service.go:695 +0x37a
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc0002fd7a0, 0xc006d34360)
prysm_beacon            |       beacon-chain/powchain/service.go:710 +0x89
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1(0xc0002fd7a0)
prysm_beacon            |       beacon-chain/powchain/service.go:258 +0x50
prysm_beacon            | created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
prysm_beacon            |       beacon-chain/powchain/service.go:256 +0x65
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain:v1.0.4 with https://github.com/stereum-dev/ethereum2-docker-compose
  </code>
</pre>

**Comment by nisdas** [comment]
Oh this is really odd, seems like an underflow here. Is there anything special about the eth1-providers you were running over here ?

**Comment by stefa2k** [comment]
Using geth's latest official docker image

**Comment by nisdas** [comment]
Is it running behind a load-balancer to route requests to different geth nodes ? Or is it a vanilla setup with only 1 geth node being relied on over here.

**Comment by stefa2k** [comment]
no load balancer, geth also got other clients

**Comment by nisdas** [comment]
Ah k, which other clients are being used alongside geth ?

**Comment by stefa2k** [comment]
Sorry I meant that geth also get's used by other eth2 beacon clients not just this prysm beacon chain. Lighthouse and Teku are also connected to the same geth. There is no failover set for the eth2 prysm beacon client or any loadbalancer failover. It's a direct connection between geth and prysm's beacon-chain.

**Comment by nisdas** [comment]
Ah k thanks for the context, will dig into it and see why it fails. Just curious, have you tried any later versions since v1.04, and has it failed any more times since the initial incident ?

**Comment by andreea-bogdan** [comment]
I've got a similar setup with @stefa2k and got the same panic error yesterday when I restarted geth.
My beacon and geth are running with docker-compose, no depends_on between them.

Yesterday it looked like every restart of geth caused a panic error on the beacon, followed by a restart of the beacon. 
Tried it several times, because I was a bit worried, and got the same behaviour all the time. Today I am not sure anymore if the restart of geth caused this, but I think it is worth looking into this flow.

`time="2020-12-20 13:20:14" level=info msg="Connected to eth1 proof-of-work chain" endpoint="http://geth:8545" prefix=powchain
time="2020-12-20 13:20:15" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
panic: runtime error: makeslice: cap out of range

goroutine 393 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).batchRequestHeaders(0xc0001366c0, 0xaf3c74, 0xaf35f9, 0xaf35f9, 0xaf3c74, 0x0, 0x0, 0xc00c4221c0)
        beacon-chain/powchain/service.go:581 +0x77
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).cacheHeadersForEth1DataVote(0xc0001366c0, 0x9a3200, 0xc000ca8380, 0x0, 0x0)
        beacon-chain/powchain/service.go:785 +0xa8
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initPOWService(0xc0001366c0)
        beacon-chain/powchain/service.go:695 +0x37a
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc0001366c0, 0xc006560360)
        beacon-chain/powchain/service.go:710 +0x89
github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1(0xc0001366c0)
        beacon-chain/powchain/service.go:258 +0x50
created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
        beacon-chain/powchain/service.go:256 +0x65`

After restart, geth was lagging a bit behind with the blockchain, but I guess this is normal because of the caching.
I'm running the beacon with version v1.0.4 and geth with release-1.9.

**Comment by OliverKnights** [comment]
Received the same error running prysm inside a docker container (ubuntu 20.04), prysm version 1.0.5, geth 1.9.25
```
prysm    | time="2021-01-10 09:50:51" level=info msg="Starting JSON-HTTP API" address="127.0.0.1:3500" prefix=gateway
prysm    | time="2021-01-10 09:50:51" level=info msg="Connected to eth1 proof-of-work chain" endpoint="http://geth.frontend:8545" prefix=powchain
geth     | INFO [01-10|09:50:56.072] Looking for peers                        peercount=1 tried=57 static=0
prysm    | panic: runtime error: makeslice: cap out of range
prysm    |
prysm    | goroutine 128 [running]:
prysm    | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).batchRequestHeaders(0xc001284640, 0x3e30ef, 0x3e2c23, 0x3e2c23, 0x3e30ef, 0x0, 0x0, 0x0)
prysm    |      beacon-chain/powchain/service.go:621 +0x77
prysm    | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).cacheHeadersForEth1DataVote(0xc001284640, 0x99fba0, 0xc000673880, 0x0, 0x0)
prysm    |      beacon-chain/powchain/service.go:824 +0xa8
prysm    | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initPOWService(0xc001284640)
prysm    |      beacon-chain/powchain/service.go:734 +0x37a
prysm    | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc001284640, 0xc0493d64e0)
prysm    |      beacon-chain/powchain/service.go:748 +0x85
prysm    | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1(0xc001284640)
prysm    |      beacon-chain/powchain/service.go:274 +0xd5
prysm    | created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
prysm    |      beacon-chain/powchain/service.go:267 +0x65

```
