### ISSUE TITLE
Wrong chain ID when configuring testnet

### ISSUE THREAD

**Issue by protolambda** [prysmaticlabs/prysm#8108]
# 🐞 Bug Report

### Description

When configuring a custom testnet, the chain ID and network ID config variables are ignored.

### Has this worked before in a previous version?

It appears that the current testnets all hardcode the variables, whereas it should be configurable.

See #6727

## 🔬 Minimal Reproduction

Load a custom testnet config, containing:
```
# Ethereum goerli testnet
DEPOSIT_CHAIN_ID: 5
DEPOSIT_NETWORK_ID: 5
```

## 🔥 Error

<pre><code>
time="2020-12-14 14:11:40" level=debug msg="Trying to dial endpoint: https:// (our goerli endpoint, ignore this) " prefix=powchain
time="2020-12-14 14:11:41" level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: eth1 node using incorrect chain id, 5 != 1" prefix=powchain
</code></pre>

## 🌍  Your Environment

.

**What version of Prysm are you running? (Which release)**

v1.0.4

**Anything else relevant (validator index / public key)?**
-

cc @parithosh who is working on testnets, new to the EF Eth2 devops team

**Comment by parithosh** [comment]
Additonal information:

- Config file was loaded onto prysm using the flag ` --chain-config-file="<PATH-TO-CONFIG>/prysm_config.yaml"`

**Comment by nisdas** [comment]
This wouldn't be too difficult, our deposit/chain id are part of our network config. We would simply need to shift it over to the beacon config with the appropriate yaml tags and it should resolve this.
