### ISSUE TITLE
Prysm Makes Excessive Block Requests With Nethermind

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8115]
# 🐞 Bug Report

### Description

Currently when running a prysm node with nethermind, there are certain situations that trigger the beacon node to make very large amounts of `eth_blockNumber` requests(rather than batching it as expected). This would indicate that there maybe certain edge cases being hit which were not observed with geth. 

Making large amounts of single block/log requests would indicate that the node infact has not synced with the historical headers/ logs. We only batch headers/logs when syncing, the fact that single requests are made indicates that the node thinks it is synced. However this indicates that it might not be the case when running with nethermind and therefore warrants investigation.   

### Has this worked before in a previous version?
N.A

## 🔬 Minimal Reproduction

Run the beacon node with `--pyrmont` with a synced nethermind goerli node providing the relevant 
eth1 data. 

## 🌍  Your Environment

**Operating System:**

Windows

**What version of Prysm are you running? (Which release)**

v1.05

**Comment by nisdas** [comment]
An update on this:
- Got a Nethermind node up and running which managed to sync goerli in about 2- 3 hours. 
- However was unable to reproduce this issue at all, nethermind worked perfectly fine with the prysm beacon node
on pyrmont.
- I suspect the issue here is with the OS running these 2 clients, I tried this out on linux while this error came up regularly with users running nethermind and prysm on windows. In order to investigate, will have to spin up a windows machine to dig deeper into it.

**Comment by MicahZoltu** [comment]
It appears to be an issue with stopping Nethermind and/or Beacon client for a while and then starting them back up.  I was able to reproduce this problem by shutting both down for a night, and then starting both back up the next day.  It may be possible to reproduce by only shutting down one of them for a day.
