### ISSUE TITLE
Allow All the Different Data Directories To Be Easily Configurable In Validator

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8116]
# 🚀 Feature Request

### Description

Allow all the different data directories to be configurable with a single flag in the validator. Currently if we want to set a non default wallet directory , we ideally also want all the db/backup dbs and other related data to be in the same directory. However given how we specify the directories, if we set ```wallet-dir``` to a different path, our other directories would still reference an older path. We would have to set ```--backup-dir``` to the path that we want and so on. 

### Describe the solution you'd like

A single flag to specify all the data directories that we want under one banner instead specifying flags individually for everything.

**Comment by rkapka** [comment]
Interesting idea. Maybe we could break our YAML into sections and allow to specify a single YAML with all Prysm configuration?

Example with bad syntax:
```
shared
   wallet-dir: /shared
  (...)
beacon-chain
  foo: xyz
  (...)
validator
  bar: xyz
slasher
  wallet-dir: /slasher -- overwrites the value from shared
```

**Comment by shayzluf** [comment]
> Interesting idea. Maybe we could also allow to specify a single YAML divided into sections with all Prysm configuration?
> 
> Example with bad YAML syntax:
> 
> ```
> shared
>    wallet-dir: /shared
>   (...)
> beacon-chain
>   foo: xyz
>   (...)
> validator
>   bar: xyz
> slasher
>   wallet-dir: /slasher -- overwrites the value from shared
> ```
> 
> This would require having the same flags for all components, though.

i think it will not be a good idea (validator, beacon, slasher have their own yaml files and possibly on different machines.
adding dir yaml will add another flag or complexity.

**Comment by shayzluf** [comment]
Closing it as `wallet-dir` already configures all the validator output paths
`http://localhost:8080/db/backup` defaults to `$wallet-dir/backups/` to configure it use `db-backup-output-dir` flag
