### ISSUE TITLE
Show the "number of pubkeys attesting" in the "Next duty" log output

### ISSUE THREAD

**Issue by chrishobcroft** [prysmaticlabs/prysm#8118]
# 🚀 Feature Request

### Description

 A clear and concise description of the problem or missing capability...

The new feature in the logging output for the `validator` is very nice - it shows a user how long until the any of the Validators will have a duty to perform.
```
prysm.sh[5372]: time="2020-12-15 15:29:43" level=info msg="Next duty" currentSlot=101846 dutySlot=101850 prefix=validator role=attester secondsLeft=40 slotInEpoch=22
```

This is very useful when restarting a process (e.g. to update to a new version of prysm) or to restart the OS (e.g. to update the OS), and to attempt to minimise the number of duties that are not fulfilled (better for the network, avoids Validators missing income etc.)

I propose to add 1 additional field to this, to show **the number of pubkeys that will be required to attest** when the next duty is due to be fulfilled - this way, I can minimise the number of times I restart and potentially miss a double (or even triple) attestation.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
Add an additional field showing the number of `pubkeys` which will be attesting in that slot:

```
prysm.sh[5372]: time="2020-12-15 15:29:43" level=info msg="Next duty" currentSlot=101846 dutySlot=101850 prefix=validator role=attester pubkeys=2 secondsLeft=40 slotInEpoch=22
```

### Describe alternatives you've considered

Oh yes, I can imagine creating far more sophisticated tools to assist Validator node operators to minimise negative impact of routine maintenance and upgrades, with visualisations showing e.g. the when Validators will be required to perform duties in the next 20 slots, and how many validators will be performing duties, something like this:

![image](https://user-images.githubusercontent.com/2212651/102236827-fad61b00-3f19-11eb-8dc1-53ca5c295df7.png)

 Have you considered any alternative solutions or workarounds?

**Comment by pinglamb** [comment]
For each slot, it is possible that the `validator` needs to do multiple `attesting` (for different `pubkeys`) and `proposing`. In case of both `attesting` and `proposing` in same slot, the current `Next duty` implementation will favour the one appears first in the `duties` array.

So to cater all the cases, should the log be:

```
# 2 attesting + 1 proposing (proposing should be 0/1)
msg="Next duties" currentSlot=101 dutySlot=105 prefix=validator attesting=2 proposing=1 secondsLeft=40 slotInEpoch=22
```

**Comment by chrishobcroft** [comment]
Looks good to me.

Perhaps change the order, so that the countdown timer is at the end of the line, to make it super-easy to read off?

Like this:
```
msg="Next duties" currentSlot=101 dutySlot=105 prefix=validator attesting=2 proposing=1 slotInEpoch=22 secondsLeft=40
```

**Comment by pinglamb** [comment]
Seems the tags order is managed by `logrus`, currently it is sorted alphabetically, so it will be like:

```
msg="Next duties" attesting=2 currentSlot=101 dutySlot=105 prefix=validator proposing=1 secondsLeft=40 slotInEpoch=22
```

**Comment by pinglamb** [comment]
@rauljordan @farazdagi I have created an PR, feel free to share what you guys think about the log format.
