### ISSUE TITLE
Newb-friendly UX on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [prysmaticlabs/prysm#8123]
# 🚀 Feature Request

### Description

Improve the validator UX for Windows users who are not particularly tech savvy.

### Describe the solution you'd like

1. Downloadable installer.
2. Installs Beacon client as a system service.
3. Installs Validator client as a system service.
4. Adds system tray icon for monitoring their status.
5. Clicking on the system tray icon brings up a UI (could be electron app, or browser app).
6. Web UI allows me to fully configure/manage the services, including choosing what chain they are connected to, what accounts they are using, etc.
7. Most importantly, don't require users to open a command prompt or edit a config file by hand.

### Describe alternatives you've considered

There is a spectrum between hostile to non-developers and incredibly approachable to everyone.  Right now, the CLI tooling is very close to the "non-developer hostile" end of the spectrum as you have to use CLI tools with certain flags that are buried in docs in order to run/manage a beacon client/validator.  The above suggested setup would bring us a long way toward "approachable" and I don't think comes with any *major* hurdles.

However, some steps could be taken that get part way there such as making it so everything can be configured from a UI but without the installer and system services as an intermediate step, or perhaps installer and system services with config file editing by hand.

**Comment by rkapka** [comment]
I think we should prioritize these items in terms of "how seriously can a user hurt themselves without this feature"?

**Comment by exo3000** [comment]
Something like this already exists as a 3rd party app. However, I cannot attest to its security. https://github.com/mauser001/Eth2Overwatch

**Comment by james-prysm** [comment]
I think third party tools will satisfy this in the mean time. we are currently assessing how to improve the user experience as a whole as well.
