### ISSUE TITLE
Programmatic Graffiti File Access

### ISSUE THREAD

**Issue by Zolmeister** [prysmaticlabs/prysm#8126]
# 🚀 Feature Request

### Description

Allow external scripts to modify graffiti at run-time.

### Describe the solution you'd like

With #8041 landing, all that's required for programmatic access (via file-updating) is to not cache the config file.

### Describe alternatives you've considered

Currently can be worked around by restarting validators.

**Comment by james-prysm** [comment]
should be resolved as part of https://github.com/prysmaticlabs/prysm/issues/13188
