### ISSUE TITLE
Nomachine breaks Prysm: Could not determine if beacon chain started

### ISSUE THREAD

**Issue by cyperbg** [prysmaticlabs/prysm#8128]
# 🐞 Bug Report

Nomachine remote admin software seems to break Prysm

I followed [THIS](https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-prysm-56f681646f74) guide to setup an ETH validator and everything worked fine until I installed Nomachine remote administrator program.
Then Prysm started restarting in a loop:
```
Dec 15 22:21:54 Staker validator[48358]: time="2020-12-15 22:21:54" level=fatal msg="Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection closed" prefix=validator
Dec 15 22:21:54 Staker systemd[1]: prysmvalidator.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 22:21:54 Staker systemd[1]: prysmvalidator.service: Failed with result 'exit-code'.
Dec 15 22:21:59 Staker systemd[1]: prysmvalidator.service: Scheduled restart job, restart counter is at 495.
Dec 15 22:21:59 Staker systemd[1]: Stopped Prysm Eth2 Validator Client.
Dec 15 22:21:59 Staker systemd[1]: Started Prysm Eth2 Validator Client.
```

Then I uninstalled Nomachine and it started working again.

Do you have an explanation why Nomachine might be breaking Prysm?

Ubuntu 20.04.1 LTS
32GB RAM

**Comment by prestonvanloon** [comment]
Looks like nomachine uses port 4000, which is the same port that Prysm's beacon chain serves.

Suggestion:
- Set beacon chain to use a non default port grpc. `--rpc-port=4001`
- Set validator to use this new address. `--beacon-rpc-provider=127.0.0.1:4001`

Alternatively, set nomachine to not use port 4000. I don't know how to do this so I'm not suggesting it.

**Comment by cyperbg** [comment]
That explains it. Thank you.
