### ISSUE TITLE
Refactor Historical Logs And Block Fetching to Have a More Graceful Retry

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8134]
# 🚀 Feature Request

### Description

It has been brought up by @ferranbt that to avoid situations like #7827 , we could have a more graceful way to request blocks/logs in the event we do exceed the limit of eth1 provider.

### Describe the solution you'd like

The solution would be similar to the one implemented here:
https://github.com/umbracle/go-web3/blob/master/tracker/tracker.go#L344

which uses a flow control(similar to TCP flow control) approach to auto adjust batch sizes for blocks/deposit logs. This allows for an easier user experience and also prevent the node from running into situations where it cannot start up at all due to restrictions implemented by the eth1 provider.

**Comment by ferranbt** [comment]
This is how it would look like if we remove all the unnecessary stuff from that code.
```
func () getLogs(from, to uint64) ([]*Logs, error) {
    res := []*Logs{}

    batchSize := t.config.BatchSize
    additiveFactor := uint64(float64(batchSize) * 0.10)

    i := from

START:
    dst := min(to, i+batchSize)

    logs, err := t.provider.GetLogs(i, dst, ...)
    if err != nil {
        if tooMuchDataRequestedError(err) {
            // multiplicative decrease
            batchSize = batchSize / 2
            goto START
        }
        return nil, err
    }

    res = append(res, logs...)
    i += batchSize + 1

    // update the batchSize with additive increase
    if batchSize < t.config.BatchSize {
        batchSize = min(t.config.BatchSize, batchSize+additiveFactor)
    }

    if i <= to {
        goto START
    }
    return logs, nil
}
```

**Comment by pinglamb** [comment]
Is it okay to use `goto`? If it is not preferred, I can try to refactor it.

**Comment by rkapka** [comment]
> Is it okay to use `goto`? If it is not preferred, I can try to refactor it.

Please use a `for` and `continue` instead of `START` and `goto START`.

**Comment by pinglamb** [comment]
I have drafted a PR according to the idea shared by @nisdas and @ferranbt. Please feel free to comment.
