### ISSUE TITLE
Implement DB block getter by slot

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#8138]
# 🚀 Feature Request

To retrieve a block using slot using the DB is inefficient today. We do the following in our code base:
```go
//    Example in rpc blockV1/block.go
        blks, roots, err := bs.BeaconDB.Blocks(ctx, filters.NewFilter().SetStartSlot(slot).SetEndSlot(slot))
	if err != nil {
		return nil, errors.Wrapf(err, "could not retrieve blocks for slot %d", slot)
	}
	numBlks := len(blks)
	if numBlks == 0 {
		return nil, nil
	}
	blk = blks[0]
	if numBlks == 1 {
		break
	}
```
I'd like to see the following getters. It'll improve both performance and code clarity

`BlockBySlot(ctx, slot) *block, bool, error`

`BlockRootBySlot(ctx, slot) [32]byte, bool, error`

**Comment by pinglamb** [comment]
It seems that there can be multiple blocks for a given slot, in the PR I followed the `blk = blks[0]` idea to return the first block. Also, what is the use of `bool` returned here:

```
BlockBySlot(ctx, slot) *block, bool, error
BlockRootBySlot(ctx, slot) [32]byte, bool, error
```

**Comment by pinglamb** [comment]
After checking the uses of getting blocks by slot, it seems the getters should return multiple blocks and the caller will handle that themselves.

```
BlocksBySlot(ctx, slot) []*block, error
BlockRootsBySlot(ctx, slot) [][32]byte, error
```

**Comment by terencechain** [comment]
> It seems that there can be multiple blocks for a given slot, in the PR I followed the `blk = blks[0]` idea to return the first block. Also, what is the use of `bool` returned here?
> 
> ```
> BlockBySlot(ctx, slot) *block, bool, error
> BlockRootBySlot(ctx, slot) [32]byte, bool, error
> ```

The `bool` is for whether blocks in that slot exists
