### ISSUE TITLE
Beacon node DB backup not working after first successful backup (Windows 10)

### ISSUE THREAD

**Issue by yv989c** [prysmaticlabs/prysm#8152]
# 🐞 Bug Report

### Description

After properly setting up the beacon node startup parameters to enable database backups, I'm able to perform an initial backup if the target backup folder does not exist, after it's created then subsequent backup attempts will fail with the following error:
`Failed to create backup error=dir already exists without proper 0700 permissions`

My startup script:
`prysm.bat beacon-chain --config-file=config.yaml`

My config.yaml content
<pre>
<code>datadir: 'C:\Apps\prysm\data'
http-web3provider: 'http://localhost:8545'
p2p-max-peers: 5
db-backup-output-dir: E:\prysm-data\backups
enable-db-backup-webhook: true</code></pre>

### Has this worked before in a previous version?
I don't know. I'm starting with v1.0.5.

## 🔬 Minimal Reproduction
Start the beacon node with the parameters shown above, let it sync-up and then execute:
`curl -I http://127.0.0.1:8080/db/backup`

If the target backup folder does not exists, it will be created and a backup file too, after that, any subsequent attempts will result in the error shown below.

## 🔥 Error

<pre><code>[2020-12-17 14:13:47]  INFO blockchain: Synced new block block=0x9f171744... epoch=3667 finalizedEpoch=3665 finalizedRoot=0xcdfe7715... slot=117367 slotInEpoch=23
[2020-12-17 14:13:47]  INFO blockchain: Finished applying state transition attestations=8 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0
[2020-12-17 14:13:51] ERROR db: Failed to create backup error=dir already exists without proper 0700 permissions
github.com/prysmaticlabs/prysm/shared/fileutil.MkdirAll
        shared/fileutil/fileutil.go:50
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).Backup
        beacon-chain/db/kv/backup.go:42
github.com/prysmaticlabs/prysm/shared/backuputil.BackupHandler.func1
        shared/backuputil/http_backup_handler.go:22
net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
        GOROOT/src/net/http/server.go:2417
net/http.serverHandler.ServeHTTP
        GOROOT/src/net/http/server.go:2843
net/http.(*conn).serve
        GOROOT/src/net/http/server.go:1925
runtime.goexit
        src/runtime/asm_amd64.s:1374
[2020-12-17 14:13:59]  INFO blockchain: Synced new block block=0x13113387... epoch=3667 finalizedEpoch=3665 finalizedRoot=0xcdfe7715... slot=117368 slotInEpoch=24
[2020-12-17 14:13:59]  INFO blockchain: Finished applying state transition attestations=30 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10 Pro (2004)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.0.5 (beacon-chain-v1.0.5-windows-amd64.exe)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by yv989c** [comment]
Hi @Cipioo , I believe this should also fix another permission issue that I'm getting when importing subsequent validator keys.

> [2020-12-21 20:19:29]  WARN flags: Running on ETH2 Mainnet
Enter the password for your imported accounts:
Importing accounts, this may take a while...
Importing accounts... 100% [==========================================]  [2s:0s]
[2020-12-21 20:20:48] FATAL accounts: Could not import accounts: could not write accounts: file already exists without proper 0600 permissions
ERROR FAILED

The line throwing this error seems to be:
https://github.com/prysmaticlabs/prysm/blob/a0c475671c4e13fd3092ac77c17cf15621820d77/shared/fileutil/fileutil.go#L74

And this PR is introducing new `ReadWritePermissions` flags when running on Windows, that I hope will address this issue.
In order to workaround this issue, I had to delete the wallet and import all the validators at once.

Thanks.

**Comment by Cipioo** [comment]
Yes, that pull request is to fix this issue.

**Comment by aaqr12** [comment]
I'm currently in the process of verifying with one key, and if you import another key after you deposit it, that error will occur.
Can I delete my wallet and call it back in this situation?
