### ISSUE TITLE
SSZ marshalling and unmarshalling codestyle improvement

### ISSUE THREAD

**Issue by blazejkrzak** [prysmaticlabs/prysm#8157]
# 🚀 Feature Request

### Description
Currently ssz serialization and deserialization is written in very unclear way.
Lets assume this code below:
```go
func (p *PendingAttestation) UnmarshalSSZ(buf []byte) error {
	...
	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	// Field (1) 'Data'
	...
	if err = p.Data.UnmarshalSSZ(buf[4:132]); err != nil {
		return err
	}
       ...
}
```

Ranges of buf bytes `[0:4]` `[4:132]` and so on are hardcoded and points for no clear answer if `[4:132`] or `[4:133]` is a proper one. Even though it is compatible with ssz structure it is nowhere near the go possibility to annotate strutcs.

### Describe the solution you'd like
Since the overal design choice is good, we are lacking clear way to annotate structs
Loosely named `ssz-pointer:"n:m"` where `0 =< n < m`
Possible code example
```go
type PendingAttestation struct {
	AggregationBits      github_com_prysmaticlabs_go_bitfield.Bitlist `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3,casttype=github.com/prysmaticlabs/go-bitfield.Bitlist" json:"aggregation_bits,omitempty" ssz-max:"2048" ssz-pointer:"0:4"`
	Data                 *v1alpha1.AttestationData                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" ssz-pointer:"4:132"`
	InclusionDelay       uint64                                       `protobuf:"varint,3,opt,name=inclusion_delay,json=inclusionDelay,proto3" json:"inclusion_delay,omitempty"`
	ProposerIndex        uint64                                       `protobuf:"varint,4,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
}
```

### Describe alternatives you've considered

Leave it as it is, and wait for structure of ssz change, then handle all the mess.

**Comment by nisdas** [comment]
Hey @blazejkrzak ,

If I am understanding correctly, you desire a way to annotate the portion of a buffer from which the fields serialized data is put in ?
The size of the buffer for a field is determined by its underlying type. Ex: `uint64` is 8 bytes , if you have a custom annotation, you risk the possibility of the serialized blob being an invalid ssz object.

**Comment by blazejkrzak** [comment]
If type determines size annotation could be handled without pointers if we'd agree that order of fields in struct matter.

**Comment by nisdas** [comment]
Yeap the order does matter here of fields in a struct during serialization.  A schema is required during deserialization so as to appropriately allocate the required bytes for variably sized objects from their offsets.

For a better idea you can take a look at the ssz spec:
https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#deserialization
