### ISSUE TITLE
Add support for Graffiti in hex

### ISSUE THREAD

**Issue by Dimasin** [prysmaticlabs/prysm#8168]
I can uses graffiti string in hex format? E.g:
0xf09f90a057656c636f6d6520746f20746865204e657720426567696e6e696e67

**Comment by rkapka** [comment]
Hi @Dimasin 

Please ask the question on our Discord server: https://discord.gg/YMVYzv6

Thank you!

**Comment by terencechain** [comment]
> I can uses graffiti string in hex format? E.g:
> 0xf09f90a057656c636f6d6520746f20746865204e657720426567696e6e696e67

In short, you can not input hex and expect it to convert to ascii (e.g. Welcome to the New Beginning). Is there a particular reason that you would like to do this?

**Comment by Dimasin** [comment]
Graffiti uses UTF-8 characters, such as 0xf09f90a0. Using the copy / paste method may not always guarantee an accurate result. A string in hex format will always be displayed the same way.

**Comment by terencechain** [comment]
> Graffiti uses UTF-8 characters, such as 0xf09f90a0. Using the copy / paste method may not always guarantee an accurate result. A string in hex format will always be displayed the same way.

It's a reasonable request. Can you update the description to something like "Add support for Graffiti in hex" ?

**Comment by d00medman** [comment]
It isn't entirely clear to me what the request is here. Do you have examples of hex graffiti being displayed in different ways, or examples of hex strings which are not properly translated into graffiti?

**Comment by Dimasin** [comment]
> 
> 
> It isn't entirely clear to me what the request is here. Do you have examples of hex graffiti being displayed in different ways, or examples of hex strings which are not properly translated into graffiti?

It isn't entirely clear to me what you want me to do. I've already made my case. This is, after all, just a suggestion.

**Comment by nisdas** [comment]
@d00medman From what I understand, @Dimasin wants to provide hex data as grafitti rather than a UTF-8 string. So instead of providing the validator 

```
--graffiti=🐠Welcome to the New Beginning
```
we can instead use 

```
--graffiti=0xf09f90a057656c636f6d6520746f20746865204e657720426567696e6e696e67
```
Then the validator will internally convert the hex data to a utf-8 compatible string and add that to any future proposed blocks.

**Comment by prestonvanloon** [comment]
We could support functionality like 
```go
if "0x" == graffiti[0:2] {
  graffiti = convertHex(graffiti[2:])
}
```
This would consider any string that starts with the `0x` prefix, as is common in ethereum, to be a hex encoded data which should be treated as such.

**Comment by potuz** [comment]
Except it's quite common in this environment to have avatars of the form 0xpotuz and this will force them to encode the string. Perhaps something like `hex:09ab12`?

**Comment by prestonvanloon** [comment]
@potuz That would be acceptable and solve the problem at hand, with minimal burden on the user. Thanks for that suggestion!
