### ISSUE TITLE
Validator status should be "PENDING", but shows "PARTIALLY_DEPOSITED" 

### ISSUE THREAD

**Issue by eyougo** [prysmaticlabs/prysm#8169]
# 💎 Issue

### Background

I'm running the beacon node and validator node with the lastest version 1.0.5. 

### Description

In my Validator's log, I see it like this:

```
time="2020-12-21 09:15:49" level=info msg="Validator status" activationEpoch=18446744073709551615 index=47055 prefix=validator pubKey=0xaf381147128a status="PARTIALLY_DEPOSITED"
```

And when I request validator info from rpc interface, i got this result 
```
{"status":"PARTIALLY_DEPOSITED","eth1DepositBlockNumber":"11463518","depositInclusionSlot":"0","activationEpoch":"18446744073709551615","positionInActivationQueue":"8305"}
```
The activationEpoch 18446744073709551615 is an infinite number, not the actual epoch.

I used to deposit ETH partially, but now I have already deposited full 32 ETH for this validator, see 
https://beaconscan.com/validator/0xaf381147128a7c71b64809822dd22a09c26610f52205097097638876bbbde274359b1ff007c565fd20e5c84056c38743

That looks like my node should be "Pending" state, but it shows "PARTIALLY_DEPOSITED".

Will this affect the activation and work of my validator later when it go to active state?

**Comment by nisdas** [comment]
There is a certain time lag before the new deposit is represented on chain. How long after your 2nd deposit did you check for the validator's status from the rpc interface ? If it is immediately, then it is expected as you have to wait a few hours before the deposit is represented on chain.

**Comment by nisdas** [comment]
@eyougo If you have any more issues, do let us know, however we will be closing this issue now as it seems like an issue in waiting for deposits to be processed to the beacon chain.
