### ISSUE TITLE
Incorrect banning of peer on custom testnet

### ISSUE THREAD

**Issue by parithosh** [prysmaticlabs/prysm#8172]
# 🐞 Bug Report

### Description

Prysm client bans other clients in the custom testnet incorrectly. Shortly after banning, the Prysm client looses all peers on custom testnet. Essentially, two nodes with identitical setup and config are banning each other and then loosing all their peers slowly.

## 🔬 Minimal Reproduction

1. Run custom testnet with this genesis config: https://gist.github.com/parithosh/72b32ae41b0e016a6b546764754fc0be
2. Start 2 Prysm beacon nodes with:
```  
--chain-config-file=/PATH/custom_testnet_config/prysm_config.yaml --deposit-contract="0x84F345c9D796150d515521Df25645f3B1327eDA7" --contract-deployment-block="3903529" --http-web3provider=<GOERLI RPC ENDPOINT>" --p2p-host-ip=<PUBLIC IP> --bootstrap-node="enr:-Ku4QCP_MwhNN8EBistazkVY4AnIG2Cx5Hnw0QXt53bIECB7N9CgUnfEfDVcau4UlKbDd8uS8ZrgoGq-g6FuGmdyhycBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAGiHTPiYmJif__________gmlkgnY0gmlwhBK8Xq-Jc2VjcDI1NmsxoQKM-X_EGDB4HLPrJmelJEWB2l92lvbcBq7CYOVXRawg0IN1ZHCCIyg"
```
3. Observe the number of peers, initially the node should have a large number of peers. As time goes on, it will loose peers. 

## 🔥 Error

Logs from Prysm node 1: `time="2020-12-22 14:13:36" level=debug msg="Sending Goodbye message to peer" Reason="client banned this node" peer=16Uiu2HAmMA3ssu2pxRSqqNPCNFDArHXrYcPZ9zbp231dT62XxkCs prefix=sync`

The peer ID `16Uiu2HAmMA3ssu2pxRSqqNPCNFDArHXrYcPZ9zbp231dT62XxkCs` refers to the Prysm node 2 (Obtained by SSH-ing into the node 2 and running `curl localhost:8080/p2p`)

## 🌍  Your Environment

**Operating System:**
Ubuntu 

**What version of Prysm are you running? (Which release)**
Prysm running in a docker container (prysmaticlabs/prysm-beacon-chain:latest) with image ID: `eb792117754b`. Can be pulled with: `prysmaticlabs/prysm-beacon-chain@sha256:bb445a703c4632e018c6db92f81dd09178791f832346d89c4d5128d4cb5fb704`

**Comment by nisdas** [comment]
Hey @parithosh , thanks for the report. Had a few questions:  
- Were all these peers on the same network interface ?
- How many peers were you running with before a Prysm node just started banning everyone ? 
- Is this reproducible with only 2 peers in your test network ?

**Comment by parithosh** [comment]
@nisdas thanks for picking it up! 

- Each peer was on its own AWS instance, so no shared NICs
- The total custom net had 10 peers running before a Prysm node started banning
- No, this was reproducible with more than 2 peers

**Comment by nisdas** [comment]
I tried running the steps to reproduce, but it seems like your bootnode might be down. In your VPC , do all peers share the same public ip ? Or is each instance allocated with a separate public ip

**Comment by parithosh** [comment]
I tried recreating it myself with the same config and I'm not able to reproduce it either. Perhaps it did have to do with the bootnodes. I'll give it another shot and report back with more concrete steps. Thanks for your help!
