### ISSUE TITLE
Graffiti - Ordered list option for yaml file.

### ISSUE THREAD

**Issue by AtHeartEngineer** [prysmaticlabs/prysm#8181]
I would like to request an option to read a list of items from a graffiti file. Currently there is only an option for a default and a random list, but I would like a list that goes in order. Example below:

```
ordered:
  - graffitiwall:300:500:#000000
  - graffitiwall:300:50:1#000000
```

**Comment by pinglamb** [comment]
Created a PR for that and

* `ordered` has lower priority than `random` when both specified
* the next item to use will reset after `validator` restart

**Comment by AtHeartEngineer** [comment]
This seems stuck in a holding pattern, I made a suggestion in the PR but I don't know if github alerted anyone

**Comment by prestonvanloon** [comment]
> This seems stuck in a holding pattern, I made a suggestion in the PR but I don't know if github alerted anyone
@AtHeartEngineer 

I responded on the PR. https://github.com/prysmaticlabs/prysm/pull/8189#issuecomment-759088266
I think we can move forward on this. @pinglamb did you have a chance to see the feedback / comments?
