### ISSUE TITLE
Redundant request for getting duties for the next epoch

### ISSUE THREAD

**Issue by roman-blox** [prysmaticlabs/prysm#8194]
https://github.com/prysmaticlabs/prysm/blob/4c6e0c5f4656b7f0b6a7df065d4ec0a3b802d4e0/validator/client/validator.go#L381

No needed to send one more request for getting duties of the next epoch. It is possible to get the same data from the first response `resp.GetNextEpochDuties()` without sending one more RPC request.

**Comment by nisdas** [comment]
On further discussion in #8204 with @KaanKC, it is risky to access the duties of the next epoch, as it might change in the event of a deeper re-org. Two possible ways forward 
1) Close the issue and leave the current code as it is.
2)  Remove the Next epoch Duties from the response payload and stop a node from requesting the next epoch's duties.

The major downside on going with 2) is that we have to modify our validator rpc schema, which isn't backwards compatible. So anyone running a beacon node with this change will not be compatible with older validator versions. 
@terencechain , thoughts ?

**Comment by roman-blox** [comment]
@nisdas you can mark the field of next epoch duties as deprecated and remove the usage from the validator.

**Comment by terencechain** [comment]
> On further discussion in #8204 with @KaanKC, it is risky to access the duties of the next epoch, as it might change in the event of a deeper re-org. Two possible ways forward
> 
> 1. Close the issue and leave the current code as it is.
> 2. Remove the Next epoch Duties from the response payload and stop a node from requesting the next epoch's duties.
> 
> The major downside on going with 2) is that we have to modify our validator rpc schema, which isn't backwards compatible. So anyone running a beacon node with this change will not be compatible with older validator versions.
> @terencechain , thoughts ?

2 is better long term and we can roll this in during v1.1.0 or v1.2.0.. etc
1 is ok for now but we'll have to remember tracking 2 somewhere  : )
