### ISSUE TITLE
Issue with external slashing protection in v1.0.5 - nil signature provided

### ISSUE THREAD

**Issue by OisinKyne** [prysmaticlabs/prysm#8208]
# 🐞 Bug Report

### Description

External Slashing Protection may not be working in v1.0.5. 

I realised my validator had an outage of approx 5 hours (my fault for not checking my alerting and assuming it self healed. Rather than wait for my geth node to resync, I bumped my version to v1.0.5 so I could make use of the `fallback-web3provider` and point it at my infura account. Everything looked fine on the beacon node + slasher but my validator was not submitting attestations because the slasher was not confirming that they were safe. 

Mitigated by downgrading back to v1.0.4

### Has this worked before in a previous version?

Yes, I have been running a slasher as external slashing protection through all of the 1.0 releases. 

## 🔬 Minimal Reproduction

Run a dockerised beacon + validator + slasher with external slashing protection on. Flags used:

```
# Slashing protection from the accompanying slasher
enable-external-slasher-protection: yes
enable-local-protection: yes
slasher-rpc-provider: slasher:5000
```

## 🔥 Error

<pre><code>

time="2021-01-05 15:55:03" level=error msg="External slashing attestation protection returned an error: rpc error: code = InvalidArgument desc = nil signature provided"
time="2021-01-05 15:55:03" level=error msg="Failed attestation slashing protection check" error="external slasher service detected a submitted slashable attestation" prefix=validator pubKey=0x****** slot=253173

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Ubuntu 20.04 with Docker 19.03.11
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    Prysm v1.0.5 in Docker 
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
I think this may have something to do with #8086. 

@rauljordan What do you think? 

I think we should be using RPC [ethereum.v1.Slasher.IsSlashableAttestationNoUpdate](https://github.com/prysmaticlabs/prysm/blob/9d737d60f4030e5fa68c3272b2285e61af6dd236/proto/slashing/slashing.proto#L23) but we are actually using [ethereum.v1.Slasher.IsSlashableAttestation](https://github.com/prysmaticlabs/prysm/blob/9d737d60f4030e5fa68c3272b2285e61af6dd236/proto/slashing/slashing.proto#L16) which requires a signature.
