### ISSUE TITLE
Validator Api allows you to get duties for the epochs in the future

### ISSUE THREAD

**Issue by mohamedmansour** [prysmaticlabs/prysm#8240]
# 🐞 Bug Report

The API allows you to request duties for many epochs ahead. It should disallow that and treat them as out of bounds.

<pre>
  <code>
http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12002&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384072
next == 384120

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12003&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384120
next == 384129

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12004&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384129
next == 384162

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12005&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384162
next == 384213
  </code>
</pre>

**Comment by terencechain** [comment]
One possible solution is here: #8239
