### ISSUE TITLE
[Feature Request] Adding a flag for automatic validator backup on every epoch

### ISSUE THREAD

**Issue by yashbhavsar007** [prysmaticlabs/prysm#8259]
# 🚀 Feature Request

### Description

As of now we have --enable-db-backup-webhook flag on validator node and to backup the slashing history we need to call localhost:monitoringport/db/backup

### Describe the solution you'd like
Can we have the flag which automatically creates backup on every epoch?

**Comment by mohamedmansour** [comment]
You could run a cronjob every 7 minutes, I know its not exact, but it is good enough.

```
crontab -e
```

Add entry:
```
*/7 * * * * curl http://127.0.0.1:8080/db/backup
```

In order not to waste space, perhaps create a script that removes the old files and adds a new file, the following script will keep the last 3 backups and remove everything else:
```
*/7 * * * * ~/.eth2/backup.sh
```

**~/.eth2/backup.sh**
```
#!/bin/bash
ls -t1 /home/ethereum/backups | tail -n +4 | xargs rm -r
curl http://127.0.0.1:8080/db/backup
return 0
```

**Comment by d00medman** [comment]
@mohamedmansour why an independently running cron job rather than a goroutine in the background directly running the backup method?

**Comment by rauljordan** [comment]
Hi @yashbhavsar007 I unfortunately think that we will not get to this feature given it is not as necessary as one may think. Validator doppelganger detection is, for the most part, the best way to prevent slashings even if you lose your slashing protection history and have to restart your validator. These approaches have been working fine for most users and there are other features we would like to prioritize in Prysm
