### ISSUE TITLE
Metrics page takes a while to come up

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#8274]
# 🐞 Bug Report

### Description

Metrics page takes a while to load. Sometime up to 30 mins. Upon further profiling by @nisdas, the metrics collection seems to stuck at prombolt as Its iterating through a lot of buckets 

### Has this worked a before in a previous version?

No

## 🔬 Minimal Reproduction

Load the metrics page localhost:8080/metrics

## 🔥 Error

N/A

**What version of Prysm are you running? (Which release)**

V1.0.5 or latest develop 09a792d

**Anything else relevant (validator index / public key)?**

Nope

**Comment by sdalmeida** [comment]
![image](https://user-images.githubusercontent.com/1103528/104978452-da452900-59cf-11eb-9c39-5f3664de662c.png)
I'm also experiencing the same issue. Seems like the beacon-chain metric takes a bit longer than 30 seconds to report back

**Comment by skillful-alex** [comment]
Looks to be reproduced on version 1.1.0.
In this case, the CPU utilization is 100%. Writing to disk is lower than usual.
10 seconds is the default scrape timeout for Prometheus.

![Grafana](https://user-images.githubusercontent.com/46927280/105345708-a1869900-5bf5-11eb-9266-5d95af68dd91.png)

**Comment by skillful-alex** [comment]
In another similar situation I have:
* CPU 100%
* error from Beacon node:
```
msg="Could not to retrieve pre state" error="could not get pre state for epoch 11665: could not load blocks for hot state using root: context deadline exceeded" prefix=sync
msg="Could not to retrieve pre state" error="could not get pre state for epoch 11665: could not get ancestor state: context deadline exceeded" prefix=sync
msg="Could not to retrieve pre state" error="could not get pre state for epoch 11665: could not get ancestor state: context deadline exceeded" prefix=sync
msg="Could not to retrieve pre state" error="could not get pre state for epoch 11665: could not get ancestor state: context deadline exceeded" prefix=sync
msg="Could not update head" error="context deadline exceeded" prefix=blockchain
```
* error from Validator
```
msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x*** slot=373296
msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x*** slot=373296
msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x*** slot=373298
```
* increased metrics failed_attestations  and failed_aggregations.

slots 373296 and 373298 included in epoch 11665.

But I had a weak instance. Now I have increased the CPU for beacon node and tomorrow I will write if it fixed the error.

**Comment by skillful-alex** [comment]
After increasing the CPU from 2 to 4 threads (AMD EPYC 7282), the maximum prometeus scrape_duration_seconds value is 89ms.

**Comment by nisdas** [comment]
Thanks for the detailed reports @skillful-alex , I will dig deeper into this by hopefully this week and we should be able to have a resolution by the next release if the core issue isn't too difficult to resolve.

**Comment by nisdas** [comment]
There is a better summary on the core issue offline:
https://discord.com/channels/476244492043812875/550365651118850081/803258212701700116

The gist of this is that, iterating through buckets often can be expensive and can be especially expensive for heavily used buckets such as `blocks` and `state-summary` buckets. These buckets often have multiple routines reading and writing to it, given that we require bucket stats , which requires us to iterate through all the pages in a bucket it can be pretty expensive especially for buckets with a large amount of data(ex:  blocks bucket). In periods with high intensity , getting stats from this particular bucket can be very expensive, which leads to the high cpu and memory usage seen here. A few tentative solutions:

- Disable all db metrics collection, so as to still have access to other metrics. 
- Disable metrics collection for those particular buckets.

The former is an extreme solution which would lead us to having much less data on a critical part of the application. The latter is a better variant of this, as we can instead focus on the problematic buckets and not collect any data from them(while still unblocking us and any subsequent metrics collection).
