### ISSUE TITLE
Cannot run the Windows exe "This app can't run on your PC" error message on 1.1.0

### ISSUE THREAD

**Issue by exo3000** [prysmaticlabs/prysm#8282]
I've tried on two different Windows versions and machines, Server 2016 and Windows 10, and get the exact same error message. "This app can't run on your PC. GUI error here: https://i.imgur.com/WJdKjX7.png

**Comment by prestonvanloon** [comment]
May be related to #8283

**Comment by exo3000** [comment]
Yes, very likely.

**Comment by prestonvanloon** [comment]
Are you running a 32-bit OS or 64-bit OS?

**Comment by exo3000** [comment]
64-bit, both machines.

**Comment by prestonvanloon** [comment]
Thanks for confirming that. I'm thinking it is some kind of file permissions issue

**Comment by terencechain** [comment]
Looks to be duplicated as #8283

**Comment by prestonvanloon** [comment]
Yes, closing as duplicate of #8283
