### ISSUE TITLE
Web UI validator import returns 500 internal server error if keystore-m password is wrong

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#8290]
# 🐞 Bug Report

### Description

Prysm 1.1.0 with Web UI and using the UI to create a wallet and import a keystore-m, on Ubuntu 20.04

If the password for the keystore-m is incorrect, Prysm Web UI will display an error 500 internal server error, but not inform the
user that the password for the keystore-m was incorrect. The wallet is created, just without keys.

Expected behavior: Prysm Web UI prompts user that the password for keystore-m is wrong, the way CLI import does.

**Comment by terencechain** [comment]
This issue should be opened in https://github.com/prysmaticlabs/prysm-web-ui

We can copy and paste it there
