### ISSUE TITLE
PrysmWebUI no longer displays Epoch Information

### ISSUE THREAD

**Issue by sdalmeida** [prysmaticlabs/prysm#8294]
# 🐞 Bug Report

### Description

Prism WebUI doesn't display Deposit information after updating to version v1.1.0

### Has this worked before in a previous version?

Yes it did

## 🔬 Minimal Reproduction

Create a beacon-chain using version v1.1.0
Create a Validator node using version v1.1.0

Register for a new validator (deposit 32ETH, etc).
Import Wallet/Account to Prysm WebUI

I don't know which statuses causes this crash on the UI, but my validator is on `DEPOSITED` state

![image](https://user-images.githubusercontent.com/1103528/105104242-e092de00-5a7f-11eb-93ca-3c161dfe192a.png)

## 🔥 Error

![image](https://user-images.githubusercontent.com/1103528/105104450-4717fc00-5a80-11eb-8aa5-ea1846ec0600.png)

## 🌍  Your Environment

**Operating System:**

Ubuntu 18.04

**What version of Prysm are you running? (Which release)**

v1.1.0

**Comment by terencechain** [comment]
This issue should be opened in https://github.com/prysmaticlabs/prysm-web-ui

We can copy and paste this issue there
