### ISSUE TITLE
Cannot expose beacon client host via ipv6

### ISSUE THREAD

**Issue by jo-tud** [prysmaticlabs/prysm#8300]
# 🐞 Bug Report

### Description

I'm trying to do is expose port 13000 via ipv6. 
My ISP supports ONLY ipv6. I've set up port forwarding correctly (it works for ssh) but port 13000 is not reachable.

When I add `p2p-local-ip: "::"` to my prysm-beacon.yaml I get errors in the validator client and it crashes (see below error).

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Try to expose an ipv6 address via `--p2p-local-ip`

## 🔥 Error

<pre><code>
level=fatal msg="Failed to start discovery" error="could not create listener: could not listen to UDP: listen udp4 [::]:12000: address ::: non-IPv4 address" prefix=p2p

level=fatal msg="Could not determine if beacon chain started: could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = 
connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
time="2021-01-20 12:40:13" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.1.0/9b367b36fc12ecf565ad649209aa2b5bba8c7797. Built at: 2021-01-18 19:47:14+00:00"
  </code>
</pre>

**Comment by 0xKiwi** [comment]
Any progress on this? @nisdas

**Comment by nisdas** [comment]
This has been addressed in earlier PRs a while back. Closing it now.
