### ISSUE TITLE
Beacon Node randomly stops synching without any Error

### ISSUE THREAD

**Issue by sbleden** [prysmaticlabs/prysm#8314]
After the latest update to v1.1.0  my Beacon Node randomly stopps synching but i got no warning or error at the console.

 ```
time="2021-01-21 15:42:47" level=info msg="Finished applying state transition" attestations=71 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-21 15:42:52" level=info msg="Peer summary" activePeers=30 inbound=0 outbound=30 prefix=p2p
time="2021-01-21 15:43:00" level=info msg="Synced new block" block=0xf5cb156a... epoch=11509 finalizedEpoch=11507 finalizedRoot=0xbb05d764... prefix=blockchain slot=368313 slotInEpoch=25
time="2021-01-21 15:43:00" level=info msg="Finished applying state transition" attestations=24 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-21 15:43:11" level=info msg="Synced new block" block=0xe84b73f5... epoch=11509 finalizedEpoch=11507 finalizedRoot=0xbb05d764... prefix=blockchain slot=368314 slotInEpoch=26
time="2021-01-21 15:43:11" level=info msg="Finished applying state transition" attestations=18 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2021-01-22 06:16:35" level=warning msg="Running on ETH2 Mainnet" prefix=flags
```

As you see i got the latest Info Message at 15:43:11. This morning i restarted the running container and everything was fine afterwards.

This happens two times in the last two days.

I'm running the latest stable docker image (1.1.0) with the following parameters:
`--datadir=/data --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --monitoring-host=0.0.0.0 --http-web3provider=http://eth1_node:8545 --accept-terms-of-use`

Do you have any idea how i can solve this problem?

**Comment by nazar-kuzo** [comment]
@sbleden I have exactly same problem pal, never had a client downtime on previous Prysm versions, but just after update to v1.1.0 my beacon-node stopped syncing in a day of work.
P.S. Running my setup in a cloud VM.

**Comment by sbleden** [comment]
I currently restarting the container with the beacon client every two hours. Till now everything works fine but i think this ist not a Long Term Solution.

**Comment by nazar-kuzo** [comment]
@sbleden yeah, I think that this is the only way to recover beacon node working again.

Do you restart becon node manual or by some scheduler?

I dediced to go with “cron” app for ubuntu and task “docker restart -t 5 beacon-node” since I’m running validator as Docker image.

**Comment by LouisDiesser** [comment]
I have the same problem.  For me the logging of the beacon node stops first and a few hours later I get missed attestations.
In addition, restarting the beacon node takes longer for me since v1.1.0 (I'm using a systemd service).

**Comment by nazar-kuzo** [comment]
@LouisDiesser I can confirm that running it on docker image it takes 30-40 seconds to restart and fully sync beacon node and 60-70 seconds for validator recover connection to beacon-node.

so I assume that there is a chance to miss the attestation because of scheduled restart. I decided to go restarting beacon node once a day

**Comment by LouisDiesser** [comment]
@nazar-kuzo I'm restarting manually at the moment, but for me it takes a few hours after logging has stopped until the beacon node completely stops working and I get missed attestations.

**Comment by drgonzo31** [comment]
I'm having the same issue. Using the latest package with DAppNode. It has stopped syncing twice now. Once was two days ago, and again about 1 hour ago.  Manual restart fixes the problem. This started with the latest prysm release.

**Comment by LouisDiesser** [comment]
Happened again on v1.2.1. The beacon node stops logging and five and a half hours later I get missed attestations.

**Comment by nisdas** [comment]
> Happened again on v1.2.1. The beacon node stops logging and five and a half hours later I get missed attestations.

This seems unrelated, if the beacon node stops logging then you should get failed attestations immediately not 5.5 hours later. 

What are the last logs from your beacon node ?

**Comment by nisdas** [comment]
@nazar-kuzo @sbleden 
If you guys have updated to the latest version, can you confirm that it does work without issues ?

**Comment by LouisDiesser** [comment]
> > Happened again on v1.2.1. The beacon node stops logging and five and a half hours later I get missed attestations.
> 
> This seems unrelated, if the beacon node stops logging then you should get failed attestations immediately not 5.5 hours later.
> 
> What are the last logs from your beacon node ?


`prysm.sh[8169]: time="2021-02-09 20:32:35" level=info msg="Finished applying state transition" attestations=75 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
prysm.sh[8169]: time="2021-02-09 20:32:47" level=info msg="Synced new block" block=0x5818c313... epoch=15820 finalizedEpoch=15818 finalizedRoot=0x05bcafd4... prefix=blockchain slot=506262 slotInEpoch=22
prysm.sh[8169]: time="2021-02-09 20:32:47" level=info msg="Finished applying state transition" attestations=21 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
prysm.sh[8169]: time="2021-02-09 20:32:59" level=info msg="Synced new block" block=0xb45e87c0... epoch=15820 finalizedEpoch=15818 finalizedRoot=0x05bcafd4... prefix=blockchain slot=506263 slotInEpoch=23
prysm.sh[8169]: time="2021-02-09 20:32:59" level=info msg="Finished applying state transition" attestations=42 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
prysm.sh[8169]: time="2021-02-09 20:33:09" level=info msg="Peer summary" activePeers=107 inbound=101 outbound=6 prefix=p2p
prysm.sh[8169]: time="2021-02-09 20:33:11" level=info msg="Synced new block" block=0x63bb6ac1... epoch=15820 finalizedEpoch=15818 finalizedRoot=0x05bcafd4... prefix=blockchain slot=506264 slotInEpoch=24
prysm.sh[8169]: time="2021-02-09 20:33:11" level=info msg="Finished applying state transition" attestations=70 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
Feb 10 02:09:10 systemd[1]: Stopping Ethereum 2 Beacon Chain...
Feb 10 02:10:40 systemd[1]: prysmbeacon.service: State 'stop-sigterm' timed out. Killing.
Feb 10 02:10:40 systemd[1]: prysmbeacon.service: Killing process 8169 (beacon-chain-v1) with signal SIGKILL.
Feb 10 02:10:41 systemd[1]: prysmbeacon.service: Main process exited, code=killed, status=9/KILL
Feb 10 02:10:41 systemd[1]: prysmbeacon.service: Failed with result 'timeout'.
Feb 10 02:10:41 systemd[1]: Stopped Ethereum 2 Beacon Chain.
Feb 10 02:10:41 systemd[1]: Started Ethereum 2 Beacon Chain.
Feb 10 02:10:41 prysm.sh[8380]: Latest Prysm version is v1.2.1.
Feb 10 02:10:41 prysm.sh[8380]: Beacon chain is up to date.`

I missed the first attestation at 1:54 a.m. and then restarted the beacon node service at 2:10 a.m.

**Comment by nazar-kuzo** [comment]
@nisdas I'm running on v 1.2.0 and can confirm that issue is not reproducing for me.

Also I want to confirm that this behavior was same to me: beacon node stops showing logs in web ui our output and after some period, (it might be one or couple of hours) validator fails with attestations, so it doesn’t happen immediately and validator works for some period

**Comment by nisdas** [comment]
Thanks for the explanation, @nazar-kuzo @LouisDiesser were both of you running on the web ui also through the validator ? Or is this reproducible when running the node normally(without UI).

**Comment by nazar-kuzo** [comment]
@nisdas If I understood your question correctly, I was always running the beacon node with ports open for web UI. Here is a config:

```
sudo docker run -t -d -v $HOME/.eth2:/data \
  --name beacon-node \
  -p 3500:3500 -p 4000:4000 -p 13000:13000 -p 12000:12000/udp \
  gcr.io/prysmaticlabs/prysm/beacon-chain:stable \
  --datadir=/data \
  --rpc-host=0.0.0.0 \
  --grpc-gateway-host=0.0.0.0 \
  --grpc-gateway-corsdomain=http://0.0.0.0:7500,http://127.0.0.1:7500,http://localhost:7500,http://{VM IP}:7500 \
  --http-web3provider={Infura endpoint} \
  --accept-terms-of-use
```

Validator config:

```
sudo docker run -t -d -v $HOME/Eth2Validators/prysm-wallet-v2:/wallet \
  -v $HOME/Eth2:/validatorDB \
  -v $HOME/eth2.0-deposit-cli:/walletPassword \
  -p 7500:7500 \
  --network="host" --name validator \
  gcr.io/prysmaticlabs/prysm/validator:stable \
  --grpc-gateway-host=0.0.0.0 \
  --beacon-rpc-provider=127.0.0.1:4000 \
  --beacon-rpc-gateway-provider={VM IP}:3500 \
  --wallet-dir=/wallet \
  --wallet-password-file=/walletPassword/wallet-password.txt \
  --datadir=/validatorDB \
  --web --accept-terms-of-use
```

This config allows me accessing web ui via public IP of my vm. When I noticed that web ui is not showing the logs for beacon node I tried to log into vm and check output from the beacon node directly and it was showing the same output as through the web ui.

**Comment by LouisDiesser** [comment]
@nisdas 
I'm also running the validator with WebUI enabled.
I can't say whether this issue can be reproduced without WebUI.
But it's difficult to reproduce this issue at all. After I had it in v1.1.0 for the second time, everything worked fine for two weeks until v1.2.1.

**Comment by LouisDiesser** [comment]
Happened again today. This time it took 9 hours after logging stopped until I got missed attestations. Disabled the WebUI now.

**Comment by nisdas** [comment]
@LouisDiesser @nazar-kuzo 
I have opened up #8430 , you guys can track this there. For now I would recommend disabling the web-ui since you have had issues with it.

**Comment by rauljordan** [comment]
@LouisDiesser please keep us posted if the issue stops after you have disabled the web ui

**Comment by nazar-kuzo** [comment]
@nisdas issue persist on v 1.2.0, happend to me twice from our last conversation

**Comment by sbleden** [comment]
I'm still restarting the beacon node automaticly every two hours. This problem never happend aggain.

**Comment by nazar-kuzo** [comment]
@LouisDiesser Issue still reproduces on v 1.2.2, after update, it worked okay for 2 hours and then beacon node stopped sync with no error.

**Comment by nisdas** [comment]
@nazar-kuzo This is with `--web`, correct ? You might have to disable it for now while we look into it

**Comment by nazar-kuzo** [comment]
@nisdas to me it seems unrelated since beacon node doesnt have any options that are web related, it only opens ports for validator. So disabling web in validator should not have to affect beacon node freeze. Also about this is mentioned here #8430

If you strongly recommended to disable web option for validator since you are sure that it is affecting somehow, I can do that

**Comment by nisdas** [comment]
To clarify on this , having the flag on the validator does affect the beacon node. The validator performs rpc calls
to the beacon node for the web-ui to retrieve all the chain related data(ex: activation, balances,rewards, etc) . There is a possibility that the validator is hammering the beacon node for a certain amount time before it causes it to 'freeze' . Given that this has been reported by many users running the web-ui, I assume it is the case.

**Comment by nazar-kuzo** [comment]
@nisdas ah, okay, since other guys are not reporting any updates for days, it might be making sense, I`ll try to run it without --web option and get back in a day with updates

**Comment by nazar-kuzo** [comment]
@nisdas seems like removing webui option helped, no issues for 36 hours so far
