### ISSUE TITLE
[Feature Request] Add in a Custom Static Analyzer for Mutex Locks

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8323]
# 🚀 Feature Request

### Description

Deadlocks while not common have come up more times than I would like. The majority of the times(if not all) this can be attributed to improper lock usage.

### Describe the solution you'd like

In the current form of how our current static analyzers are currently structured, we can have a similar one to prevent developers from inadvertently introducing recursive read locking/locking. Given that this is a deadlock condition that can eventually grind down our core beacon/validator processes to a halt, it is important to have a better way to detect errors such as these. 

By parsing the AST of the respective files in the repository, we can determine where mutex locks are being improperly applied and remedy them. 

For an example which illustrates this problem: 
#8314 
#8321 
#7905

Some examples of analyzers currently being applied in Prysm:
https://github.com/prysmaticlabs/prysm/tree/develop/tools/analyzers

### Describe alternatives you've considered

As far as I am aware there have been no external static linting tools/ analyzer to check for improper lock usage.

**Comment by yuilleb** [comment]
Pretty sure #7905 falls under this issue as well.

**Comment by mi-yu** [comment]
Hi, @rvnair and I are students at the University of Texas at Austin and would like to work on this as part of a [Distributed Systems project](https://github.com/vijay03/cs380d-s21)

**Comment by rauljordan** [comment]
Hi @mi-yu that sounds awesome! We would love to have you work on this. We are glad to offer support and any help on the Go programming aspect and the goals of the analyzer. You can join our Discord [here](https://discord.gg/hmq4y2P) and we can assist you in our #contribute channel. Let us know if you have any questions. Thanks for the interest!

**Comment by rauljordan** [comment]
Hey @mi-yu another contributor is also interested in this task, so perhaps both of you can collaborate towards finding a good solution. If you join our Discord under the #contribute channel, you'll see the conversation

**Comment by mi-yu** [comment]
Got it, we will reach out, thank you
