### ISSUE TITLE
Cannot backup beacon-chain data (on arm64)

### ISSUE THREAD

**Issue by monossido** [prysmaticlabs/prysm#8324]
# 🐞 Bug Report

### Description

I start beacon-chain with this argouments (and others):

```
--enable-db-backup-webhook true --db-backup-output-dir=/home/ethereum/backup/
```
If i run 
```
curl http://127.0.0.1:8080/db/backup
```
Nothing happen, no response for severals minutes (hours), and than the curl process just kills themself or somthing like that.
In beacon-chain logs I can see immediatly
```
time="2021-01-24 18:46:58" level=info msg="Writing backup database." backup="/home/ethereum/.eth2/beaconchaindata/backups/prysm_beacondb_at_slot_0484434.backup" prefix=db
```
But that file is just 110mb.
So I believe that the backup is not done.

If I do the same steps with the validator I can see a response on the curl side "OK". And the backup file is about 736kB
Also as you can see my "--db-backup-output-dir" is ignored, I don't know why.

### Has this worked before in a previous version?

Nope. Tried 1.0.4 and 1.1.0 version

## 🌍  Your Environment

I'm running prysm on raspberry with this ubuntu image https://github.com/diglos/pi-gen
On pyrmont network.

**Comment by nisdas** [comment]
Hey @monossido , 

Thanks for reporting this, I believe this may also be related to #8274 . For some reason boltdb has some issues iterating through all the relevant buckets which is causing issues seen while backing up for you. We still haven't the root cause yet, but I will be investigating it this week. Just for my knowledge, what is the size of your db ?

**Comment by monossido** [comment]
```
8.1G	beaconchain.db
```

Thank you! If you need other infos just ask.

**Comment by nisdas** [comment]
Hey @monossido , 

This should be fixed in the latest release, do you mind confirming if this issue has been resolved for you ?

**Comment by monossido** [comment]
I can confirm it's fixed!
Thank you.

But I ran into another issue, trying to backup in a ntfs partition I've this error
```level=error msg="Failed to create backup" error="dir already exists without proper 0700 permissions" prefix=db```
Only the first time without the pre existing directory it works. 

I'm closing because it's another issue, tell me if it's better to create a new one.
