### ISSUE TITLE
Add a new sub command to print out / export validator daily income

### ISSUE THREAD

**Issue by Giladio** [prysmaticlabs/prysm#8372]
# 🚀 Feature Request

### Describe the solution you'd like

A sub command that will allow a date range as an input any prysm user to easily print out (or even better, export to a spreadsheet) the entire list of daily income per each validator maintained by that client, in that given date range. 

### Describe alternatives you've considered

At the moment only the current balance can be extracted from the client at any given time and beacon explorers do not provide any exporting features so the only workaround is manually reading the values posted by one of the beacon explorers and typing in the daily income for each validator into a spreadsheet.

**Comment by Giladio** [comment]
If its possible to make this work retro-actively (i.e. print out all daily income starting from Dec-01-2020) would be very helpful. Thanks!

**Comment by mrabino1** [comment]
To further that request and to +1 it.. in addition to the above, to be able to query with a startdate and enddate to bracket into a window of time, for one, some, or all of the validators in the wallet (or custom non-wallet.

in an ideal world, it would also include the avg ETH price for that given day, though that can be pulled from other sites..

**Comment by skillful-alex** [comment]
Is this option not suitable https://beaconcha.in/dashboard?validators=1234,5678 ?
And maybe look at the validator_balance metric (though then it must be saved in Prometheus ...)
What's the start of the day? My validator works in a different time zone than me.

**Comment by Giladio** [comment]
@skillful-alex - The option of looking up beaconcha.in or beaconscan.com for that matter is that you need to hover with your mouse over every day, _memorize_ the 8 digits after the 0.0 (since you can't copy a tool tip) and _type that manually_ in to a spreadsheet. 
If you have several validators, thats a really annoying and unreliable process. 

Do you know any way of extracting that from the html page somehow?
I have also made the request to the Beaconcha.in guys to have an 'export' button above the daily income chart, but not clear when that will be available, and I know Rotki are planning to role out their solution at some point. Either way, always best to have the output directly from the source (the actual validator client) - less room for error.

Re your second point - I don't think the tax authorities care if you report based on UTC or UTC+whatever, as long as all income is accounted for on a daily basis. Actually, some tax advisers say weekly might be fine, but no one really knows yet and they can make up the rules as they go, so 'daily' makes sense as the most granular report they could ever require.

**Comment by makultar** [comment]
There is sometihng like: https://github.com/eth2353/eth2-staking-rewards-calculator

I cannot get it to work though. Gets stuck at 98% and then exits with error: https://pastebin.com/AP7Cd5yw
Config: Set at least one validator pubkey, port 3500, prysm: true. 

But its would be better if its already integrated in Prysm somehow.

**Comment by kazazor** [comment]
+1 on that request. I could think of many things to do with such an ability like having the ability to provide this output to my country's tax authorities which actually demand this information twice a year FOR EACH GIVEN DAY OF THE YEAR :/

This feature will help me a lot.

**Comment by mrabino1** [comment]
Gents, humor me if I am wrong on this.. but it would seem the above requests are just a query on the beaconchain itself (with a constraint of which validator).. so maybe the request could be / should broadened to how users via the CLI can query the beaconchain db? From there, users can construct whatever query they want inclusive of income.. thoughts?

**Comment by mrabino1** [comment]
a python implementation .... of something similar...
https://github.com/eth2353/eth2-staking-rewards-calculator

**Comment by Giladio** [comment]
Generic queries to the beacon chain directly via the CLI would be great, but sounds to me like a much more complex feature to implement and support (and not sure its even on the roadmap for the client team). In this case, I assume most users would need/want to report their income and a specific subcommand can be useful - Also, opened this issue after consulting with the team on Discord where a subcommand was suggested, but indeed any form of access to query the db and get the data would suffice.

**Comment by mrabino1** [comment]
@makultar checkout the https://github.com/eth2353/eth2-staking-rewards-calculator repo again.. there is a fix there.. it works for me now..

**Comment by Giladio** [comment]
Thanks! will check it out

**Comment by Giladio** [comment]
Hey folks. Meanwhile looks like Beaconcha.in heard the requests from the community and added the feature: https://mainnet.beaconcha.in/validator/1590/stats - Still would be a nice-to-have on prysm, but much less urgent now obviously.

**Comment by rauljordan** [comment]
@rvnair and @mi-yu are working on this

**Comment by mi-yu** [comment]
Commenting to get assigned @rauljordan

**Comment by rvnair** [comment]
Me as well @rauljordan

**Comment by terencechain** [comment]
After chatting with @mi-yu and @rvnair , we have decided to implement this as a standalone function that's outside of prysm
