### ISSUE TITLE
validator stops working 

### ISSUE THREAD

**Issue by mischa3** [prysmaticlabs/prysm#8374]
My validator node stops working from time to time and after i press enter on the validator cmc, every task that was in the missing time shows up and says: deadline exceeded. After this the validator node works fine until this happens some days later again. I think it needs something that retries after a problem or something like that what do you think?

The funny part about this is that my grafana page also logged out from time to time and i dont receive an message after the process is down.  I dont know if it is something with the internet connection, because i had the issue at the start of the ETH staking often, then long time nothing and now its more often. I know the internet connection has at the moment some downs.

**Comment by skillful-alex** [comment]
windows? cmc=cmd?
in windows, if you select something in the console (by mouse), then the process freezes and waits for copying (what you do by press enter).

**Comment by mischa3** [comment]
ohh yes cmd. I click by mouse on the validator node and press enter, after this all the missing tasks are loading with an error and then it continue fine. So if i dont select something by mouse it should works fine? or its because i have a program on windows that freezes the process. Is there an option to select the ethereum validator with high priority or something like that?

**Comment by rauljordan** [comment]
> So if i dont select something by mouse it should works fine

this is right, it seems like that is the behavior on Windows or programs running on cmd. You can change this behavior with https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10. Let us know if this does not resolved your problem @mischa3 and we can re-open this issue
