### ISSUE TITLE
Add Ability to Exit All Validators

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8383]
# 🚀 Feature Request

### Description

Currently, stakers with many validators cannot perform mass voluntary exits as the CLI command is interactive

### Describe the solution you'd like

Allow performing automated exits by skipping the confirmation prompts during the CLI command for validators.

### Describe alternatives you've considered

Someone advanced enough to use the various flags to skip confirmations knows what they are doing, and there is no reason we should disallow automatic exits.

**Comment by makultar** [comment]
**Aaand for anyone who can help me with a quickfix while waiting:**
[https://www.reddit.com/r/ethstaker/comments/lb3gue/looking_for_script_that_will_automatically_exit/
](url)

... Would be much appreicated :) Thanks!

**Comment by rkapka** [comment]
> Currently, stakers with many validators cannot perform mass voluntary exits as the CLI command is interactive

@rauljordan
What do you exactly mean by **many validators**? Many keys inside the same validator client or many validator clients each running one key or a few keys?

**Comment by makultar** [comment]
> > Currently, stakers with many validators cannot perform mass voluntary exits as the CLI command is interactive
> 
> @rauljordan
> What do you exactly mean by **many validators**? Many keys inside the same validator client or many validator clients each running one key or a few keys? There is one confirmation step for all keys combined.

As in having 32 ETH * 20 validators running on Prysm, on the same machine. 
So I assume this would be _"Many keys inside the same validator client"_ :] That what I meant at least.

**Comment by makultar** [comment]
-

**Comment by makultar** [comment]
@rajkat from Prysms discord:
_Does anyone know how the withdrawal from withdrawal address will work when enabled?  At that time, do we have to exit the validators? That's kind of difficult in case a family member or someone else has to do on your behalf.  I think the ideal solution would be to allow withdrawing the entire balance of the validator from the withdrawal address and when the balance falls below the 16 eth, the validator automatically exits. Does anyone have insights into this or can we have the core eth2 wallet team implement such a feature. Basically for someone to withdraw who is not techie enough, it should be as simple as logging with ledger or trezor with their eth2 app on their device and executing a withdraw transaction. A lot of things regarding funds safety are so scary with today's implementation of eth2 wallet system and also discouraging for many. Lot of forethought has to be given into this in order not to screw up things._

**Comment by makultar** [comment]
rajkat on #General @ Prysm discord:

> Does anyone know how the withdrawal from withdrawal address will work when enabled?  At that time, do we have to exit the validators? That's kind of difficult in case a family member or someone else has to do on your behalf.  I think the ideal solution would be to allow withdrawing the entire balance of the validator from the withdrawal address and when the balance falls below the 16 eth, the validator automatically exits. Does anyone have insights into this or can we have the core eth2 wallet team implement such a feature. Basically for someone to withdraw who is not techie enough, it should be as simple as logging with ledger or trezor with their eth2 app on their device and executing a withdraw transaction. A lot of things regarding funds safety are so scary with today's implementation of eth2 wallet system and also discouraging for many. Lot of forethought has to be given into this in order not to screw up things.
> 
> If such a system is implemented, then @makultar concern about auto exit is also solved at a much higher level
