### ISSUE TITLE
All nodes went offline today after update from 1.0.5 to 1.1.p

### ISSUE THREAD

**Issue by Chrisco92** [prysmaticlabs/prysm#8396]
# 🐞 Bug Report

### Description

Hello guys, i updated yesterday the client from 1.05 to 1.1.0. That day everything went fine and my effectiveness went up back to perfect. I also tried the web interface via ssh port forwarding and it looks great. But 2h ago, all the validators went offline for about 1h. I restarted both services, the validator and the beaconchain and now they are back online. I haven't had any problems with offline going clients before.

When the validator were offline, I checked the web interface and there weren't any logs for the validator available, just the empty window.

The Server was online all the time. Now the validators are back for one our without any warnings. Seems on discord more people have the problem with 1.1.0
I used Somers Guide  on Medium to set up everything. Would a rollback to 1.0.5 be the same update procedure like this:
<img width="758" alt="update process" src="https://user-images.githubusercontent.com/7690840/106874032-65633600-66d5-11eb-8ca0-0218f19a66b4.png">

Is there a way to use the default Prysm.sh commands from the documentation even though I used his tutorial?
https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-prysm-56f681646f74

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was:  v.1.0.5 

## 🔬 Minimal Reproduction

<img width="986" alt="beaconLog" src="https://user-images.githubusercontent.com/7690840/106871496-94c47380-66d2-11eb-83dd-b44ff3d561cf.png">
<img width="994" alt="validator client" src="https://user-images.githubusercontent.com/7690840/106871504-968e3700-66d2-11eb-8221-0b6771417928.png">

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1037-aws x86_64)
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.1.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
If you need more information please asked

**Comment by nisdas** [comment]
Hey @Chrisco92 , this should be fixed in the next release. The fix has been merged into our develop branch:
#8321

**Comment by Chrisco92** [comment]
@nisdas , thanks for the pretty. Looking forward for the next release. Is there a estimated release day ?  I had the exact problem today again, nearly ad the exact time. A restart of the validator service helped, but the balances were reduced again.

Are you familiar with Somers Guide like I Mentioned before? is there a way to get the .sh-functions from the documentation worked  ? Planing to do a rollback if the next release will take some time, getting the validators down once a day is quite inconvenient.

Cheers!

**Comment by makultar** [comment]
> @nisdas , thanks for the pretty. Looking forward for the next release. Is there a estimated release day ? I had the exact problem today again, nearly ad the exact time. A restart of the validator service helped, but the balances were reduced again.
> 
> Are you familiar with Somers Guide like I Mentioned before? is there a way to get the .sh-functions from the documentation worked ? Planing to do a rollback if the next release will take some time, getting the validators down once a day is quite inconvenient.
> 
> Cheers!

Can you please specify what .sh funktions from the Prysm documentation you mean? What commands do you want to use/execute?

**Comment by Chrisco92** [comment]
the recommed prysm.sh database rollback commands. Bazel and docker aren't installed at the moment.

**Comment by nisdas** [comment]
Hey @Chrisco92 ,

This issue should be resolved, let me know if that is not the case. I am closing the issue for now, as there have been no more reports since v1.2 onwards.
