### ISSUE TITLE
Reoccuring (WARN NODE/VALIDATOR: The process just restarted)

### ISSUE THREAD

**Issue by Novop** [prysmaticlabs/prysm#8401]
# 🐞 Bug Report

### Description

**Problem: Processes gets randomly restarted!**
I have my grafana dashboard send me notifications of any issues on my validator. 

I have been running my validators since Genesis without any problems.  
I updated my client to v1.0.5 on 15th of December.  Had no issues until the 30th of January. 

I believe the reason I was able to catch these issues is because, in my configuration I have set a 13min sleep delay when the validator first boots up, for extra slashing protection (via the ExecStartPre=/bin/sleep 780 in the validator service file) 

This also means that each time the process gets restarted, I also miss attestations (which is just a side effect of the process restarting)

**At this point i am running client version v1.0.5**
January 30th  - WARN NODE/VALIDATOR: The process just restarted

February 2nd 4:51AM - WARN NODE/VALIDATOR: The process just restarted
February 2nd 9:41AM - WARN NODE/VALIDATOR: The process just restarted

**At this point I went ahead and updated my client to version v1.1.0 to see if the problem is solved**
February 3nd 02:00AM - WARN NODE/VALIDATOR: The process just restarted
February 3nd 02:34AM - WARN NODE/VALIDATOR: The process just restarted
February 3nd 06:10AM - WARN NODE/VALIDATOR: The process just restarted

February 5nd 02:17AM - WARN NODE/VALIDATOR: The process just restarted
- This time i also received this value (Metric name | Value) (beacon node | 0.090)

### Has this worked before in a previous version?

This started happening after the 30th of Jan

## 🔬 Minimal Reproduction

I have followed Someresats guide mainly. 

## 🌍  Your Environment

DigitalOcean VPS
Ubuntu
16GB Ram
300GB SSD
 
Infura endpoint
Alchemy endpoint (fallover)

**Comment by nisdas** [comment]
@Novop Do you have any validator error logs that might explain why it is being restarted ?

**Comment by Novop** [comment]
The process was restarted again this hour.
I have identified the process to be the 'Beacon-chain' process. 

Still no clue as to why this is happening. 

![beaconchain](https://user-images.githubusercontent.com/13527777/107058404-3f28bd80-67dd-11eb-9a0f-f427dcab4f40.png)

**Comment by Novop** [comment]
Is there a specific log, that you would like me to check?

![whattocheck](https://user-images.githubusercontent.com/13527777/107065338-55d31280-67e5-11eb-9a4d-a1f7178b1085.png)

**Comment by rauljordan** [comment]
Discussed offline with @Novop , there is something else in his systemd or operating system configuration that is sending SIGTERM calls to Prysm. Additionally, his monitoring had false positives of restarts where there was no actual restart in the node nor validator. If further issues occur, I have an open line with Novop to discuss solutions
