### ISSUE TITLE
List all validator id's

### ISSUE THREAD

**Issue by makultar** [prysmaticlabs/prysm#8404]
# 🚀 Feature Request

### Description

I would like a straight forward command to output the ?index id's? of your validator(s). Not sure if _index id_ is the correct word for it but basically the validator id number that is shown in the second column here: https://mainnet.beaconcha.in/validators/leaderboard

### Describe the solution you'd like

`--list-validator-id   --all`
Requests a dump of available id's, while --all selects all. Specifiying --pubkey 0x1  0x2  0x3  0x4 can be useful too.

### Describe alternatives you've considered

Beaconcha.in works, if you don't have a lot of validators. However, I don't think we should force users to a website when our own data surely got to be available on our own staking machines.

**Comment by makultar** [comment]
Chris @ Prysm Discord
_I don't think there's a command to get that index ID in prysm you can do validator accounts list , but that returns the public keys of your validators_

Is it possible to create this type of command? 
How do beaconcha.in retrieve ids?

**Comment by makultar** [comment]
Another request... 
`/usr/local/bin/validator accounts list --wallet-dir=/var/lib/prysm/validator 
`
currently lists all pubkeys in this format:
```
Account 1 | x1
[validating public key] 0x1234567

Account 2 | x2
[validating public key] 0x2345678

Account 3 | x3
[validating public key] 0x3456789
```
Is it possible to have a command to dump raw pubkeys without no text (Account 1, validating public key). **Only** the pubkey 0x12345 on each row?

Perhaps its possible by using grep but I could _not_ get it to work. And I like when everything is just programmed into the program I am using.

**Comment by rauljordan** [comment]
Hi @makultar this is indeed possible, but we will have to connect to a beacon node to retrieve the validator indices for the public keys you own, so you will need to have a running beacon node. The validator client cannot figure this out on its own. For your second feature request, yes we can add a flag that lists the raw public keys output to make it easier for scripts to retrieve.

**Comment by makultar** [comment]
> Hi @makultar this is indeed possible, but we will have to connect to a beacon node to retrieve the validator indices for the public keys you own, so you will need to have a running beacon node. The validator client cannot figure this out on its own. For your second feature request, yes we can add a flag that lists the raw public keys output to make it easier for scripts to retrieve.

Understood. I think the majority interested in index id's most likely does! Otherwise just let us know by an error message. Sounds good to me 👯 

Thanks!!
