### ISSUE TITLE
Many errors during initial sync: beacon node doesn't have a parent in db with root

### ISSUE THREAD

**Issue by etalot** [prysmaticlabs/prysm#8416]
I'm try to run validator. Did not send yet 32 ETH, because I have doubts due to log a lot of errors uppon beacon syncing like this:
<pre><code>
[2021-02-07 21:45:50] WARN initial-sync: Batch is not processed error=beacon node doesn't have a parent in db with root: 0xb8cc934b6da198dffa5b479ca9f36b8fd59385d896ea722cfd9f8c3e150810c
</code></pre>

I've already done 4 initial syncs

1: ~20,000 of these errors
2: ~6000 of these errors
3: ~271 of these errors
4: ~8000 of these errors

It's strange.

**Operating System:**

<pre>
  <code>
Ubuntu 18.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm v1.2.0
  </code>
</pre>

**Comment by terencechain** [comment]
cc @nisdas @farazdagi
