### ISSUE TITLE
Allow/Deny IP Ranges by Specifying if they are Public/Private

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8466]
# 🚀 Feature Request

### Description

Instead of listing out all the specific IP subnets for different ranges of private addresses we can instead just provide a flag to denote this. Thanks to @hanswurst37 for raising this up in #5663 .

### Describe the solution you'd like

`--p2p-allowlist=public` or `p2p-denylist=private` 

A user could provide a string `public` / `private` to our current allowlist/denylist flags. We simply have to supply the subnets to our connection gater and it will filter it out for us.

**Comment by DigiDr** [comment]
Agree this would be very helpful! Perhaps Prysm could provide also provide a default list as some users will find this challenging to understand and cope with.

**Comment by kevlu93** [comment]
will take a look into this
