### ISSUE TITLE
Database Backups Leads To High Memory Usage

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8486]
# 🐞 Bug Report

### Description

Database backups in the beacon node, lead to a very large increase in memory usage. This eventually kills the node
and host machine due to Bolt iterating through all the buckets and keys and trying to copy them.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

Backup a live beacon node in mainnet.

**Comment by Dimasin** [comment]
After initiate back up: `wget -T 600 http://127.0.0.1:8080/db/backup`, the file `prysm_beacondb_at_slot_0582037`.backup is created in the `db-backup-output-dir directory`. For some time the length of this file increased, then stopped at 175300Kb.
In the beacon-chain event log, when initiating the creation of a backup copy, a message appears:
`time="2021-02-20 13:07:57" level=info msg="Writing backup database." backup="db-backup-output-dir directory"`
After 2-3 minutes, the systemd reports an abnormal crash of the beacon-chain service and its restart:
```
13:10:09 systemd[1]: beacon-chain.service: Main process exited, code=killed, status=9/KILL
13:10:09 systemd[1]: beacon-chain.service: Failed with result 'signal'.
13:10:14 systemd[1]: beacon-chain.service: Scheduled restart job, restart counter is at 1.
13:10:14 systemd[1]: Stopped Prysm Beaconchain.
13:10:14 systemd[1]: Started Prysm Beaconchain.
```
This happens every time try to back up the beacon site database.
The validator database is backing up without any problems.

**Comment by prestonvanloon** [comment]
Seems like boltdb might be reading the entire contents of some buckets into memory, then writing it to disk. This would be problematic for large buckets in the beacon chain, while the validator db still has relatively small buckets.
