### ISSUE TITLE
Make Slashing Protection Export Find validator.db Automatically Inside of Wallet Directory

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8500]
# 🚀 Feature Request

### Description

Currently, performing a slasher protection export or import requires the --datadir flag which needs to be a path to a folder containing a `validator.db` file. This is confusing and leads users to sometimes pass in a wrong folder and receive an empty slashing protection history.

### Describe the solution you'd like

The import/export commands should recursively look into the folder specified for a validator.db file and check if it exists, then use it for performing their operations. This way, a user can simply pass in --datadir=/walletdir and not be concerned about getting an empty response. This will improve user experience and minimize risk of someone exporting an empty slashing protection history.

**Comment by ahadda5** [comment]
@rauljordan  i see adding a utility func part of the shared fileutil to recursively look at the file name specified in `ProtectionDbFileName`  in the folder specified --datadir.  
This will be called from the `ExportSlashingProtectionJSONCli `or the `ImportSlashingProtectionJSONCli  `after parsing the datadir path, with the proper error handling if the file does not exist.    I'll come back to you with changes.

**Comment by rauljordan** [comment]
That sounds exactly like the solution we have in mind @ahadda5 , thanks for the interest in this one! Appreciate your contributions

**Comment by ahadda5** [comment]
i'm trying to unit test my util func  `RecusriveFileFind`  and i'm getting this error.   Where do you start?   

The func was tested in a separate program and works. 


`>bazel test //shared/fileutil:go_default_test --test_output=streamed  --sandbox_debug --verbose_failures
`
```
1614258108.302969315: src/main/tools/linux-sandbox-pid1.cc:279: remount rw: /dev/shm
1614258108.303131616: src/main/tools/linux-sandbox-pid1.cc:363: calling fork...
1614258108.303269417: src/main/tools/linux-sandbox-pid1.cc:393: child started with PID 2
shared/fileutil/fileutil_test.go:244:10: tmpDirFnames declared but not used
compilepkg: error running subcommand external/go_sdk/pkg/tool/linux_amd64/compile: exit status 2
1614258108.391016971: src/main/tools/linux-sandbox-pid1.cc:410: wait returned pid=2, status=0x100
1614258108.391032271: src/main/tools/linux-sandbox-pid1.cc:428: child exited normally with code 1
1614258108.457685392: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //shared/fileutil:go_default_test failed to build
INFO: Elapsed time: 0.542s, Critical Path: 0.31s
INFO: 4 processes: 2 internal, 2 linux-sandbox.
FAILED: Build did NOT complete successfully
//shared/fileutil:go_default_test                               FAILED TO BUILD

FAILED: Build did NOT complete successfully

```

**Comment by ahadda5** [comment]
Here is the new test func

```
func TestRecursiveFileFind(t *testing.T) {
	tmpDir, tmpDirFnames := tmpDirWithContentsForRecursiveFind(t)
	tests := []struct {
		name  string
		root  string
		path  string
		found bool
	}{
		{
			name:  "file1",
			root:  tmpDir,
			path:  "subfolder1/subfolder11/file1",
			found: true,
		},
		{
			name:  "file2",
			root:  tmpDir,
			path:  "subfolder2/file2",
			found: true,
		},
		{
			name:  "file1",
			root:  tmpDir + "/subfolder1",
			path:  "subfolder11/file1",
			found: true,
		},
		{
			name:  "file3",
			root:  tmpDir,
			path:  "file3",
			found: true,
		},
		/*{
			name:  "file4",
			root:  tmpDir,
			path:  "",
			found: false,
		},*/
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			found, fpath, err := fileutil.RecursiveFileFind(tt.name,tt.root)
			require.NoError(t, err)

			assert.DeepEqual(t, tt.found, found)
			assert.DeepEqual(t, tt.path, fpath)
		})
	}
}
```

**Comment by ahadda5** [comment]
```
func tmpDirWithContentsForRecursiveFind(t *testing.T) (string, []string) {
	dir := t.TempDir()
	fnames := []string{
		"subfolder1/subfolder11/file1",
		"subfolder2/file2",
		"file3"
	}
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "subfolder1", "subfolder11"), 0777))
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "subfolder2"), 0777))
	for _, fname := range fnames {
		require.NoError(t, ioutil.WriteFile(filepath.Join(dir, fname), []byte(fname), 0777))
	}
	sort.Strings(fnames)
	return dir, fnames
}
```

**Comment by ahadda5** [comment]
tmpDirFnames  was declaraed not used



> Here is the new test func
> // RecursiveFileFind returns true, and the path, if a file is not a directory and exists
> // at dir or any of its subdirectories. Finds the first instant based on the Walk order and returns.
> // Define non-fatal error to stop the recursive directory walk
> 
> ```
> func TestRecursiveFileFind(t *testing.T) {
> 	tmpDir, tmpDirFnames := tmpDirWithContentsForRecursiveFind(t)
> 	tests := []struct {
> 		name  string
> 		root  string
> 		path  string
> 		found bool
> 	}{
> 		{
> 			name:  "file1",
> 			root:  tmpDir,
> 			path:  "subfolder1/subfolder11/file1",
> 			found: true,
> 		},
> 		{
> 			name:  "file2",
> 			root:  tmpDir,
> 			path:  "subfolder2/file2",
> 			found: true,
> 		},
> 		{
> 			name:  "file1",
> 			root:  tmpDir + "/subfolder1",
> 			path:  "subfolder11/file1",
> 			found: true,
> 		},
> 		{
> 			name:  "file3",
> 			root:  tmpDir,
> 			path:  "file3",
> 			found: true,
> 		},
> 		/*{
> 			name:  "file4",
> 			root:  tmpDir,
> 			path:  "",
> 			found: false,
> 		},*/
> 	}
> 
> 	for _, tt := range tests {
> 		t.Run(tt.name, func(t *testing.T) {
> 			found, fpath, err := fileutil.RecursiveFileFind(tt.name,tt.root)
> 			require.NoError(t, err)
> 
> 			assert.DeepEqual(t, tt.found, found)
> 			assert.DeepEqual(t, tt.path, fpath)
> 		})
> 	}
> }
> ```
