### ISSUE TITLE
Issues with beacon chain at sync moment with 1.3.2

### ISSUE THREAD

**Issue by eidast** [prysmaticlabs/prysm#8537]
# 🐞 Bug Report

### Description

When I run the beacon chain, I receive a segmentation fault error at the moment of the finish of the sync in the beacon chain

### Has this worked before in a previous version?

Yes, the previous version I was running was: 1.2.1

## 🔬 Minimal Reproduction

I execute the beacon chain with the following command:

```
#!/bin/bash

GRAFFITI=BLAHBLAH

/opt/validator/prysm.sh validator --wallet-dir=/opt/validator/wallet --wallet-password-file=/opt/validator/pwdfile.txt --mainnet --web --monitoring-host=0.0.0.0 --accept-terms-of-use --graffiti=${GRAFFITI}
```

## 🔥 Error

The trace is too long, so I prefer share this gist

https://gist.github.com/eidast/890ca15a145d195883fe7d5398227e0a

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

Linux ip-10-0-1-51 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:53:34 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

processor       : 0
BogoMIPS        : 243.75
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

root@ip-10-0-1-51:/opt/validator# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

1.3.2

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

I rollback to 1.2.1 and everything back to work, after that I upgrade to 1.2.2 and worked as expected.

AWS Instance: 
- t4g.xlarge

**Comment by nisdas** [comment]
```
runtime/debug.Stack(0x14003da12d8, 0x39c2c0, 0x2320e70)
	GOROOT/src/runtime/debug/stack.go:24 +0x88
main.main.func2()
	beacon-chain/main.go:183 +0x50
panic(0x39c2c0, 0x2320e70)
	GOROOT/src/runtime/panic.go:965 +0x154
github.com/golang/snappy.encodeBlock(0x140052470da, 0x5e452c, 0x5e452c, 0x14004f90000, 0x10000, 0x297758, 0xc23)
	external/com_github_golang_snappy/encode_arm64.s:666 +0x360
github.com/golang/snappy.Encode(0x14005228000, 0x603606, 0x603606, 0x14004fa0000, 0x287758, 0x287758, 0x0, 0x964578, 0x14002ea13b0)
	external/com_github_golang_snappy/encode.go:39 +0x17c
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.encode(0x964578, 0x14002ea1380, 0x95c7e8, 0x140002269c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	beacon-chain/db/kv/encoding.go:50 +0x1e8
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveStates(0x1400148f100, 0x964578, 0x14002ea1380, 0x14003da9800, 0x1, 0x1, 0x14003da97e0, 0x1, 0x1, 0x0, ...)
	beacon-chain/db/kv/state.go:88 +0x110
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveState(0x1400148f100, 0x9644d0, 0x14000262dc0, 0x14000bdccb0, 0x69abfd935b1d614d, 0xac1c962f0a7f3a01, 0x9595fe7cf853c8a0, 0x60930763810350fe, 0x0, 0x0)
	beacon-chain/db/kv/state.go:75 +0xe8
github.com/prysmaticlabs/prysm/beacon-chain/interop-cold-start.(*Service).saveGenesisState(0x14000bdc850, 0x9644d0, 0x14000262dc0, 0x14000bdccb0, 0x0, 0x0)
	beacon-chain/interop-cold-start/service.go:194 +0x50c
github.com/prysmaticlabs/prysm/beacon-chain/interop-cold-start.NewService(0x9644d0, 0x14000262dc0, 0x14001b75b40, 0x4038787418)
	beacon-chain/interop-cold-start/service.go:82 +0x304
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).registerInteropServices(0x14000c6ad80, 0x0, 0x0)
	beacon-chain/node/node.go:729 +0x150
github.com/prysmaticlabs/prysm/beacon-chain/node.New(0x1400148ef00, 0x5, 0x5, 0x0)
	beacon-chain/node/node.go:191 +0x7c0
main.startNode(0x1400148ef00, 0x0, 0x0)
	beacon-chain/main.go:221 +0x150
github.com/urfave/cli/v2.(*App).RunContext(0x14000465500, 0x964508, 0x14000238010, 0x14000240000, 0x7, 0x7, 0x0, 0x0)
	external/com_github_urfave_cli_v2/app.go:315 +0x520
github.com/urfave/cli/v2.(*App).Run(...)
	external/com_github_urfave_cli_v2/app.go:215
main.main()
	beacon-chain/main.go:188 +0x1d4
```
Running it with an interop genesis state also fails at snappy. This seems like a snappy specific issue over here on arm64, the short term solution to this would be to revert go 1.16 for now:
https://github.com/prysmaticlabs/prysm/pull/8521

**Comment by TennisBowling** [comment]
I have this problem

**Comment by LeoHChen** [comment]
I am using the latest v1.3.2 on ARM64 of an AWS c6g.large instance.
And I hit another segmentation fault, the following is the trace.

https://gist.github.com/LeoHChen/6a97ebc4ac9978165582c337c232064f
