### ISSUE TITLE
Missing alert condition in grafana configuration files .json

### ISSUE THREAD

**Issue by aster62** [prysmaticlabs/prysm#8569]
# 🐞 Bug Report

### Description

Configs files: 
https://docs.prylabs.network/assets/grafana-dashboards/big_amount_validators.json
https://docs.prylabs.network/assets/grafana-dashboards/small_amount_validators.json

The 2 grafana configuration files are missing a section for the alert "name": "WARN NODE/VALIDATOR: The process just restarted"

The alert runs 2 queries against prometheus to get the uptime of the beacon-chain and validator, but the alert doesn't process the validator uptime, so the alert doesn't trigger if only the validator service restarts.

### Has this worked before in a previous version?

most likely not.

## 🔬 Minimal Reproduction

Screenshot 1: Current alert
Screenshot 2: Supposed alert
[Screenshots](https://imgur.com/a/WqtFOCh)
*Note that according to the .json the first picture of the IS situation should have query(**A**,10s,now) instead of query(**B**...), I accidentally made the screenshot after I changed the config, then only fixed my error for screenshot 2.

## Proposed solution

Replace the conditions section of the alert (small_amount_validators.json lines 2726 - 2750, big_amount_validation.json lines 2711 - 2735) to add the alerting condition for query(B,10s,now)
from
```
"conditions": [
          {
            "evaluator": {
              "params": [
                0.1
              ],
              "type": "lt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "10s",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "last"
            },
            "type": "query"
          }
        ],
```
to

```
"conditions": [
          {
            "evaluator": {
              "params": [
                0.1
              ],
              "type": "lt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "A",
                "10s",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "last"
            },
            "type": "query"
          },
          {
            "evaluator": {
              "params": [
                0.1
              ],
              "type": "lt"
            },
            "operator": {
              "type": "or"
            },
            "query": {
              "params": [
                "B",
                "10s",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "last"
            },
            "type": "query"
          }
        ],
```

**Comment by 0xKiwi** [comment]
@prestonvanloon know anything about this?

**Comment by prestonvanloon** [comment]
Closing old issue. These dashboards are out of date and there are many options for monitoring now.
