### ISSUE TITLE
Failed attestations and aggregations (context deadline exceeded)

### ISSUE THREAD

**Issue by sezu** [prysmaticlabs/prysm#8570]
# 🐞 Bug Report

### Description

I've noticed a large spike in beacon/validator errors since upgrading to v1.2.1. These errors are causing failed attestations and aggregations (and probably proposals too!).

## 🔬 Minimal Reproduction

I've got the beacon and validator on separate machines hosted within a VPS. --max-peers 60 on the beacon. No extra flags on the validator.

## 🔥 Error

```
# Beacon
"time="2021-03-05 11:42:23" level=error msg="Could not to retrieve pre state" error="could not get pre state for epoch <REDACTED>: context deadline exceeded" prefix=sync" 
"time="2021-03-05 11:57:16" level=error msg="Could not to retrieve pre state" error="could not process slots up to epoch <REDACTED>: context deadline exceeded" prefix=sync" 

# Validator
"time="2021-03-05 12:39:47" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=<REDACTED> slot=<REDACTED>" 
"time="2021-03-05 11:46:11" level=error msg="Could not submit slot signature to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator slot=<REDACTED>" 
```

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.10

**What version of Prysm are you running? (Which release)**

v1.3.2

**Comment by greenlip23** [comment]
Increase max peer to 100?

**Comment by sezu** [comment]
> Increase max peer to 100?

How would this fix the issue? "Context deadline exceeded" means that the requests aren't able to be processed within a certain amount of time. I had my peers set to 80 and since dropped them to 60 to try and reduce load.

**Comment by greenlip23** [comment]
I had similar message(deadline....) before. It happen when I use --web flag or --slot cache. 
Also If you run with many validators, increase peer to 100 will help for those miss attestation.
Or delete --attest-timely.
Try those.

**Comment by sezu** [comment]
> I had similar message(deadline....) before. It happen when I use --web flag or --slot cache.
> Also If you run with many validators, increase peer to 100 will help for those miss attestation.
> Or delete --attest-timely.
> Try those.

I'm not running with any other flags. This isn't helpful advice. I was previously running with 80 peers which should be more than enough.

**Comment by sezu** [comment]
Closing this issue as it seems to be a duplicate and upgrading to v1.3.4 significantly reduced the errors.
