### ISSUE TITLE
Use Embed Config Pattern to Minimize Number of Struct Fields in Prysm Services

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8603]
# 🚀 Feature Request

### Description

Currently, a `Service` struct in the Prysm codebase, such as the blockchain service, initial sync service, rpc service, etc. all have a massive number of struct fields. These services also have a `Config` struct that allows us to initialize them, leading to a ton of duplicated code. For example:

```go
type Config struct {
  GenesisTime time.Time
  Database db.Database
  NetworkID string
  ...
  IndexedAttestationsFeed *event.Feed
}

type Service struct {
  genesisTime time.Time
  database db.Database
  networkID string
  ...
  indexedAttestationsFeed *event.Feed
}

func New(ctx context.Context, cfg *Config) *Service {
  return &Service{
    genesisTime: cfg.GenesisTime
    database: cfg.Database,
    networkID: cfg.NetworkID,
    ...
    indexedAttestationsFeed: cfg.IndexedAttestationsFeed
  }
}
```

This means we have to write the code essentially 3 times! Some services have over 30 struct fields, making this incredibly hard to deal with and diffs impossible to read when adding new fields.

### Describe the solution you'd like

The optimized slasher refactor #8331, introduced a new pattern which we should use across all of Prysm:

```go
type Config struct {
  GenesisTime time.Time
  Database db.Database
  NetworkID string
  ...
  IndexedAttestationsFeed *event.Feed
}

type Service struct {
  cfg *Config
  // Add other unexported, service-specific fields below:
  ...
}

func New(ctx context.Context, cfg *Config) *Service {
  return &Service{
    cfg: cfg,
  }
}
```

**Comment by kevlu93** [comment]
Think this issue can be closed.
