### ISSUE TITLE
Handle Early Blocks And Attestations

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#8606]
Prysm does not handle early block. A block could arrive early with respect to `MAXIMUM_GOSSIP_CLOCK_DISPARITY`, however the block could get dropped.

Solutions:
1. Allow importing block with a tolerance of `MAXIMUM_GOSSIP_CLOCK_DISPARITY`
2. If a block is verified and it's within `MAXIMUM_GOSSIP_CLOCK_DISPARITY`, queue it to be processed at the start of the appropriate slot

I personally prefer 2 over 1

**Comment by prestonvanloon** [comment]
What about propagation? If we receive a block early, we should not propagate it until the slot start?

**Comment by terencechain** [comment]
> What about propagation? If we receive a block early, we should not propagate it until the slot start?

We should not propagate it until the block is verified (i.e. passing p2p spec's validation steps)

**Comment by nisdas** [comment]
Given that there is no straight forward way for prysm to handle early blocks/attestations, if any blocks are beyond the `MAXIMUM_GOSSIP_CLOCK_DISPARITY` limit, they are simply thrown away. We then re-request those blocks through rpc which adds in an unnecessary delay for processing them. Given that clocks are expected to be synchronized for each validator within 12 seconds of each other, the current clock disparity is excessively strict. 

Some potential solutions to this issue: 
- Modify Pending Queues to handle early blocks/attestations better. If the objects are early till an acceptable bound, we instead insert them to the pending queue. 
- The pending queue then follows the current slot ticker and then processes them in time. This solution would involve modifying a sensitive area of the code that is already pretty difficult to understand clearly.  
- We could alternatively create a totally new queue just for early blocks/attestations, only main downside is creating a new background routine. Given that all our blocks/attestations have appropriate locks this shouldn't conflict with other active routines.
