### ISSUE TITLE
Define Prater Bootstrap Nodes

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#8612]
Tracking issue for full Prater support of bootstrap nodes.

Related: https://github.com/eth2-clients/eth2-testnets/pull/40

**Comment by prestonvanloon** [comment]
@terencechain still need to remove this TODO
https://github.com/prysmaticlabs/prysm/blob/034a28710e11632b15ed105aaf755d2c586c6812/shared/featureconfig/config.go#L128

**Comment by terencechain** [comment]
> @terencechain still need to remove this TODO
> https://github.com/prysmaticlabs/prysm/blob/034a28710e11632b15ed105aaf755d2c586c6812/shared/featureconfig/config.go#L128

Ops. Missed it. Thanks!
