### ISSUE TITLE
State Management Improvements

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#8785]
# 💎 Issue

### Background

Currently our State Management is a critical part of Prysm, as it handles how our state is accessed across all the different services in Prysm. How our State Management runs affects the overall CPU Usage and Memory Consumed by the beacon node. We use reference counting to keep track of all the different fields that are shared across the different beacon states in prysm. By keeping track of references, we can restrict any new memory allocated to only when writing to any shared field due to Copy On Write semantics employed by our State Management.

### Description

Our current design allows us to make extremely cheap copies of the beacon state without ballooning memory and having wild CPU usage. This allows us to verify a large amount of individual attestations in a subnet without leading to a corresponding larger increase in memory usage. Along with shared fields, we also employ a shared field trie which is shared across states. This allows us to have a markedly faster state Hash Tree Root. 

Advantages of Our Current Design:
- Cheap Copies of State
- Relatively Fast HTR( Hash Tree Root) in most cases compared to the non-cached HTR using fast-ssz.
- Reduced Memory and CPU Usage by the beacon node.

Disadvantages of Our Current Design:
- Increased Complexity Of Managing Multiple States
- Most methods have to be modified around managing a Shared State.
- Due to the Shared Nature of the large root arrays, they almost are always copied during a state transition. 
- Significant amount of Memory Fragmentation due to how many slices are copied for each state. This makes it harder for the GC to identify disused regions of memory and mark them as obsolete. 

Potential Improvements to Make:

- Improve State Management with regards to state transitions from received blocks. 
Currently we have a global shared `hot state` cache. This is used for all our gossip validators, including attestation subnets and aggregate attestations. Verification of these objects usually does not require any additional state transition to be carried out, however due to how we copy our state, the relevant field tries are also copied. So when we do infact receive a new block, we usually have to copy the whole field trie before performing the  block transition. We could potentially employ a unique cache for *only* state transitions from blocks. 

- Cast Individual Fields By Using Fixed Size Types. 
This will help the GC greatly as instead of having to clear up Slices , which are harder to keep track of, cleaning up disused arrays( without any references) are much easier. This also allows us to improve the general efficiency of state transitions as we can keep objects on the stack versus throwing them to the heap.

- Improve Semantics Around Attestation Validation/Processing

Currently we fetch a copy of the state for *each* attestation, this provides a burden on the beacon node as the network grows bigger memory usage from state copies will also grow linearly. We should attempt to keep memory usage with regards to validator registry size as sub-linear if possible. 
There are many potential solutions to explore here : 
- Batched Attestation Processing
- Use a more specific cache for *only* attestation/aggregate validation.

**Comment by rkapka** [comment]
## Benchmarking

### Benchmark code

https://gist.github.com/rkapka/486daa18f440262c45a9e88c00b17ce1

Benchmark performed 1024 state copies. I created separate `copy` functions for all array sizes to make the native beacon state's code faster.

### Timing

Proto: **28.5s**
Native: **22.5s**

### Memory

**Proto**

![Proto state](https://user-images.githubusercontent.com/28876818/135617750-930bf95f-c365-4276-8a78-17b07379e77b.png)

**Native**

![obraz](https://user-images.githubusercontent.com/28876818/135617842-7a8cb537-dc06-4a9b-a436-b1ad8c2770ca.png)

### Conclusion

Native version runs 21% faster and uses 29% less memory.

**Comment by nisdas** [comment]
This has been addressed, all the planned improvements have been merged in over the last couple of years.
