### ISSUE TITLE
Missing input validation in SecretKeyFromBigNum

### ISSUE THREAD

**Issue by dnkolegov** [prysmaticlabs/prysm#8819]
# 💎 Issue

### Description

BLS's `SecretKeyFromBigNum` is an exported function that creates a BLS private key. It can be misused as follows:
`SecretKeyFromBigNum("1")` will produce a BLS private key consisting of 31 zero bytes.

The description of the function `SecretKeyFromBigNum takes in a big number string and creates a BLS private key` doesn't say anything related to 0-bytes padding.

At the present time the function is not used within the codebase but as I have said above it is available outside the project.

**Comment by veorq** [comment]
We'd also recommend to filter out values longer than 32 bytes (which would eventually be rejected by `SecretKeyFromBytes`).

For the FromBigNum case, in principle any number is an equally valid value, but some values are "more equal" than others. You may for example reject the degenerate cases (0 and 1), and perhaps reject ridiculously short strings as it's statistically unlikely to hit (say) at 4 byte value if picking a random secret key, whatever its encoding.

**Comment by nisdas** [comment]
Hey @dnkolegov @veorq , 

Thanks for bringing this up, the function was used previously only used for testing(the reason why we have the zero bytes padding). Given that this is publicly accessible, it would be better to more strictly validate this, I will proceed to remove the padding and instead just build the secret key from the provided string directly without any additional padding.
