### ISSUE TITLE
The Aggregate function doesn't validate a public key

### ISSUE THREAD

**Issue by dnkolegov** [prysmaticlabs/prysm#8824]
# 💎 Issue

### Background
BLST defines two function aggregating public keys: [`AggregatePublicKeys`](https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/blst/public_key.go#L56) and [`Aggregate`](https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/blst/public_key.go#L94).

The former validates public keys properly, but the latter doesn't.
[https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-5.1](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-5.1) requires first validating public keys.

cc: @veorq

**Comment by nisdas** [comment]
Hey @dnkolegov ,

the latter method expects a decompressed public key, and given that we perform key validation during decompression we do not repeat it again. 
https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/blst/public_key.go#L100

Currently there is only 1 method through which decompression and validation is performed:
https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/blst/public_key.go#L29

So any `PublicKey` object being used has also been validated beforehand. For what its worth the latter method is 
only used in a test over here:
https://github.com/prysmaticlabs/prysm/blob/develop/shared/bls/blst/public_key_test.go#L75

**Comment by veorq** [comment]
Makes sense, thanks for the clarification, we suspected something like this :)
