### ISSUE TITLE
Implement Weak Subjectivity Sync

### ISSUE THREAD

**Issue by remyroy** [prysmaticlabs/prysm#8845]
# 🚀 Feature Request

### Description

Implement a *fast* way to sync the beacon chain from scratch using a checkpoint state.

### Describe the solution you'd like

See [this video by Adrian Sutton](https://www.youtube.com/watch?v=ce9uVRl23zI) from the Teku development team. You can get more details on [the related Teku documentation page](https://docs.teku.pegasys.tech/en/latest/HowTo/Get-Started/Checkpoint-Start/).

**Comment by terencechain** [comment]
@farazdagi is currently working on this!
