### ISSUE TITLE
Support Czech based on the Launchpad Languages. 

### ISSUE THREAD

**Issue by ahadda5** [prysmaticlabs/prysm#8853]
# 🚀 Feature Request

### Description

[Launchpad supported languages](https://launchpad.ethereum.org/en/languages)  have been updated recently on Apr 12. 

### Describe the solution you'd like
2 weeks prior Prysm enhanced its web backend ,Part of #8664 , by supporting bip39 Mnemonic language in recovering their wallet from a mnemonic.
Currently supported languages in Bip39 are: English, chinese_simplified, chinese_traditional , French, Italian , Japanese , Korean, Spanish

New list: Chinses simplified, Czech, English, Italian, Korean, Spanish, French , Greek, Indonesian, Portuguese, Romanian, Arabic, German, Japanese, Turkish. 

Both the CLI and web  have to be up-to-date with the Launchpad language support. 

### Describe alternatives you've considered
None. Maintain the status quo.

**Comment by ahadda5** [comment]
If the Prysm team approves the feature I can take this one.

**Comment by rkapka** [comment]
@ahadda5 Assigned :)

**Comment by ahadda5** [comment]
Well the Launchpad list set is inclusive of the bip39  except the Chinese(simplified vs traditional). Should we maintain traditional?   I know @rauljordan has Chinese knowledge so maybe he can help?

**Comment by rauljordan** [comment]
Yes we should maintain traditional @ahadda5 as they have a different corpus and the characters are different

**Comment by ahadda5** [comment]
We are limited with what bip39 offers.   Portuguese can be added to the go library.  Tracking this [issue ](https://github.com/tyler-smith/go-bip39/issues/46)
