### ISSUE TITLE
Update go-libp2p-noise to release v0.2.0

### ISSUE THREAD

**Issue by dnkolegov** [prysmaticlabs/prysm#8863]
# 💎 Issue

### Background

At the present time, the project is using go-libp2p-noise v0.1.2 based on github.com/flynn/noise package that has [two bugs](https://github.com/flynn/noise/security/advisories/GHSA-g9mp-8g3h-3c5c) in nonce handling in versions prior to v1.0.0.

We recommend updating the go-libp2p-noise package to the last version.

**Comment by nisdas** [comment]
Hey @dnkolegov , 

Thanks for reporting this, as of the current moment we are waiting for https://github.com/libp2p/go-libp2p/issues/1090 . Once a new release is tagged on their end, we can updated all our libp2p dependencies (including the patch for noise).
