### ISSUE TITLE
Multiple Beacon endpoints for validator nodes

### ISSUE THREAD

**Issue by barnabasbusa** [prysmaticlabs/prysm#8874]
# 🚀 Feature Request

### Description

The validator currently only accepts a single URL for ETH2 (beacon) endpoint. In order to be able to provide an even lighter setup for validator operators and to enable further redundancy of the network multiple endpoint support for beacon nodes should be implemented. Similarly to how the ETH1 fallback works, a beacon fallback could be implemented. 

### Describe the solution you'd like

Modify the validator code to accept multiple endpoints, and if the first URL fails, fallback to the second one. Maintain a polling call to all endpoints for health checks. If they are healthy then recover to the first URL.

### Describe alternatives you've considered
There are no existing alternatives that I have considered so far.

**Comment by prestonvanloon** [comment]
Currently, Prysm does support multiple beacon node backends natively with gRPC load balancing. Add 2 or more beacon node connection strings to the `beacon-rpc-provider` flag with a comma separating. Example: `--beacon-rpc-provider=127.0.0.1:4000,123.45.67.89:4000`. This is "client side load balancing" as described [here](https://grpc.io/blog/grpc-load-balancing/).

Would that satisfy your feature request? 

This functionality is not well documented within Prysm. If you find that answer acceptable, we can resolve this feature request with the proper documentation. Thanks!

**Comment by barnabasbusa** [comment]
Infura now supports eth2 endpoints too. Would it work with their https/wss endpoints too? I was not aware that this is natively supported. Indeed the lack of documentation might be the cause of it.

**Comment by 0xKiwi** [comment]
Bumping for @prestonvanloon to notice the reported error. Is this something to fix on our end?

**Comment by prestonvanloon** [comment]
We don't support the standard eth2 API so you can't use infura as a grpc beacon node address at this time. 
Follow #7510 for progress on standard eth2 APIs support.

**Comment by potuz** [comment]
Can we close this issue as the requested feature is already implemented?
