### ISSUE TITLE
unable to connect to geth locally 

### ISSUE THREAD

**Issue by danielschonfeld** [prysmaticlabs/prysm#8878]
# 🐞 Bug Report

### Description

Sometimes the beacon node complains about geth giving it bad headers, I can't pinpoint when this happens and usually a restart of geth solves it.  None the less I don't know if the bug is with geth or prysm, but it seems like all is working properly on geth and i even curled manually to make sure I get a 200 response with the proper data i expected.

### Has this worked before in a previous version?

Hard to tell

## 🔬 Minimal Reproduction

Again hard to tell

## 🔥 Error

<pre><code>
level=error msg="Unable to process past headers 502 Bad Gateway" prefix=powchain
</code></pre>
## 🌍  Your Environment

**Operating System:**

<pre>
  <code> 
    Ubuntu 20.04 for both geth and prysm
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
   1.3.8-hotfix
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

NA

**Comment by nisdas** [comment]
This does happen intermittently, especially if the rpc connection between geth and prysm gets terminated. If you are running this with infura, it is possible that it can happen too. However the beacon node should immediately reconnect, does that happen ?

**Comment by danielschonfeld** [comment]
it seems to happen only with my local geth, not with infura and seems to happen when i first load beacon chain after a reboot.  I can't however rule out that the problem is with geth, even tho when I curl it myself it seems to respond just fine, while beacon chain thinks these errors exist.

**Comment by nisdas** [comment]
These seems like an issue with your local setup rather an something inherent with prysm. Closing this issue now unless you feel otherwise.
