### ISSUE TITLE
segmentation violation (v1.3.2)

### ISSUE THREAD

**Issue by guybrush** [prysmaticlabs/prysm#8886]
# 🐞 Bug Report

### Description

One of our node crashed with a `SIGSEGV`, this was the first time I have seen a crash like this. The version of the node was `Prysm/v1.3.2/29d1959b81921946f620b8fc745be660c8185d39 `

You can find the logs here: https://gist.github.com/guybrush/c5e1edd181725e6d590cbe6852e7db82

**Comment by prestonvanloon** [comment]
Was there any improper shutdown of this node? It seems that this error is happening when trying to read from the database and I wonder if the process was writing to the database when it was improperly terminated.

**Comment by guybrush** [comment]
Hm sorry I am not 100% certain, at least it has not been shutdown manually.

**Comment by guybrush** [comment]
We had another crash with 1.3.9: https://gist.github.com/guybrush/1ffc524773118b700aaa5a899472be27

**Comment by nisdas** [comment]
Alright fix incoming today, this is almost related to improper usage of slice allocation in a db transaction. A similar issue: #3320
