### ISSUE TITLE
Block Validity Conditions for Initial Sync

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/prysm#891]
Beacon node downloads beacon blocks during initial sync from other peers, it also should be checking whether incoming blocks valid before passing to other services or saving it to local DB. If the incoming block is not valid (e.g. incorrect slot number, incorrect proposer signature) The initial sync service should just discard the block.

**Comment by rauljordan** [comment]
This has been implemented by @nisdas

**Comment by nisdas** [comment]
@rauljordan , This is still an open issue, currently with the changes in the spec, I didnt add in any validity checks so as not to break sync. Since the blocks are simulated ones, so we have to fix/deprecate the simulator first and then add in validity checks

**Comment by terenc3t** [comment]
I think we can close this? Feel free to reopen if its not satisfied
