### ISSUE TITLE
Optimize `CheckAttesterDoubleVotes` Slasher DB Method

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8913]
# 💎 Issue

### Background

Our optimized slasher implementation is a total rewrite of how slasher is meant to function. Although it is meant to be more efficient from first principles, there are a few low-hanging fruit we want to improve to ensure the implementation is up to high standards.

One of the slow functions is `CheckAttesterDoubleVotes` found https://github.com/prysmaticlabs/prysm/blob/401f73d341a119feccacb1f9cf56d11d2b9fdea6/beacon-chain/db/slasherkv/slasher.go#L89. The goal of the function is to detect if a validator has created a double vote attestation, that is, the validator has cast two attestations at the same target epoch with different attestation data roots.

The current implementation is fairly naive, doing the following:
```
Take in a list of attestations
Create an empty list of double votes found
for each attestation:
  for each validator in its attesting indices:
    database_key = attestation.target_epoch ++ validator
    if exists_in_db(database_key): append to list of double votes
```

We could have hundreds of attesting indices and hundreds of attestations passed into this function. The impact on CPU is quite clear here: 

<img width="1748" alt="Screen_Shot_2021-05-20_at_9 44 50_AM" src="https://user-images.githubusercontent.com/5572669/119023450-863f5680-b967-11eb-8238-3deaef19f85b.png">

### Description

We want to identify a solution that improves this performance bottleneck and can be benchmarked.

**Comment by sajanjswl** [comment]
Hi, @rauljordan I would like to work on this issue. Any extra pointers will be appreciated.
Thanks!
