### ISSUE TITLE
Add "--propose-block-late"

### ISSUE THREAD

**Issue by Buttaa** [prysmaticlabs/prysm#8921]
# 🚀 Feature Request

### Description

As a block proposer I would like to have choice to not propose block immediately, but after X seconds in the given slot.
With MEV around, proposing blocks as late as possible will allow the block proposer to find/get more MEV opportunities.

### Describe the solution you'd like

Because it is risky to propose blocks late, my idea was to let the user choose how late it has to be, so:

`--propose-block-late 5000 11000` where `5000` is for a single block proposal in ms and `11000` for blocks where i have two in a row (assuming no eth2 spec change and only the next block proposer needs to know about the current block, which is me).

The upper cap should be 11.x seconds

**Comment by terencechain** [comment]
Let's wait until the merge is around the corner before we evaluate this feature

**Comment by mohsenghajar** [comment]
Please suggest reading material about MEV

**Comment by potuz** [comment]
I think clients should strive to do what's best for the network, I would advocate for the opposite and look for in-protocol ways to penalize late blocks. This feature would literally go against the [honest validator spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#block-proposal)

> A validator is expected to propose a [SignedBeaconBlock](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedbeaconblock) at the beginning of any slot during which `is_proposer(state, validator_index)` returns `True`.

**Comment by Buttaa** [comment]
> I think clients should strive to do what's best for the network, I would advocate for the opposite and look for in-protocol ways to penalize late blocks. This feature would literally go against the [honest validator spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#block-proposal)
> 
> > A validator is expected to propose a [SignedBeaconBlock](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#signedbeaconblock) at the beginning of any slot during which `is_proposer(state, validator_index)` returns `True`.

Don't you think it would give users with coding skills an unfair advantage against those who can't?

**Comment by rauljordan** [comment]
hi @Buttaa thinking about this - it seems like the behavior you want is best accomplished by MEV Boost. Given that exists, I don't see why we would be adding this feature unless you have a different use case. What do you think?
