### ISSUE TITLE
Prysm Node panics with message "close of closed channel"

### ISSUE THREAD

**Issue by fkbenjamin** [prysmaticlabs/prysm#8958]
# 🐞 Bug Report

### Description

 Since yesterday I'm experiencing the following behavior on two of our Prysm nodes.  Every few hours, the node panics with the following message: "panic: close of closed channel". After being restarted, everything works again until the same behavior happens again a few hours later.

### Has this worked before in a previous version?

 Yes, this behavior only started occurring yesterday, bevor that even the same version seemed to work.

## 🔥 Error

<pre><code>
May 29 13:44:59 prysm prysm.sh[2728527]: time="2021-05-29 13:44:59" level=info msg="Finished applying state transition" attestations=50 prefix=blockchain slot=1288723
May 29 13:45:06 prysm prysm.sh[2728527]: panic: close of closed channel
May 29 13:45:06 prysm prysm.sh[2728527]: goroutine 210 [running]:
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*Subscription).close(...)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/subscription.go:46
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleRemoveSubscription(0xc0002c2c00, 0xc061f75700)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:674 +0xa5
May 29 13:45:06 prysm prysm.sh[2728527]: github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc0002c2c00, 0x1e31910, 0xc00037f2c0)
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:558 +0x1505
May 29 13:45:06 prysm prysm.sh[2728527]: created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
May 29 13:45:06 prysm prysm.sh[2728527]:         external/com_github_libp2p_go_libp2p_pubsub/pubsub.go:293 +0xb7e
May 29 13:45:06 prysm systemd[1]: prysm.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04.2 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain-v1.3.9-linux-amd64
  </code>
</pre>

**Comment by prestonvanloon** [comment]
This looks like an issue in libp2p pubsub. I've filed an issue here: https://github.com/libp2p/go-libp2p-pubsub/issues/425

**Comment by prestonvanloon** [comment]
A fix is in for go-libp2p-pubsub. We will need to review this diff to update go-libp2p-pubsub: https://github.com/libp2p/go-libp2p-pubsub/compare/v0.4.0...55d412efa7f5a734d2f926e0c7c948f0ab4def21

**Comment by rauljordan** [comment]
We have updated libp2p to this version a long time ago as we are now on 0.8.0. Closing
