### ISSUE TITLE
Client Stats v1.3.10 Windows - Unsupported 16-Bit Application/This App Can't Run on Your PC

### ISSUE THREAD

**Issue by 399iejijw9e29ejiwjljasd** [prysmaticlabs/prysm#8979]
# 🐞 Bug Report

### Description

Client Stats v1.3.10 Windows fails to execute on Windows Server 2019 (Unsupported 16-Bit Application) or Windows 10 (This App Can't Run on Your PC)

### Has this worked before in a previous version? Did not try before

 Did not try before

## 🔬 Minimal Reproduction

Tried on a Windows 10 and Windows Server 2019 machine, different error but the same outcome. The executable will not run.

## 🔥 Error

<code><pre>
Windows Server 2019 - "Unsupported 16-Bit Application"
Windows 10 - This App Can't Run on Your PC

client-stats-v1.3.10-windows-amd64.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10/Windows Server 2019
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v1.3.10
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
No

**Comment by prestonvanloon** [comment]
We had a typo in our build script when adding this new binary and the wrong file was copied as the windows binary. In fact, the windows binary that was uploaded is actually the darwin / mac binary. I'll rebuild and reissue this for windows.

**Comment by prestonvanloon** [comment]
I have reuploaded these files. The correct sha is
```
c47fbd327dda5579f421317bf012ff185334a2d9e98b9023a2f42169f82de82b  client-stats-v1.3.10-windows-amd64.exe
```
