### ISSUE TITLE
Fix/Remove buggy unused code in math_helper.go

### ISSUE THREAD

**Issue by asanso** [prysmaticlabs/prysm#8989]
# 🐞 Bug Report

### Description

The current code base contains some buggy but unused code that has an 
issue similar to the one reported in https://github.com/prysmaticlabs/prysm/pull/8910 .

It would be advisable to remove this function or fix it.
 
## 🔥 Error

The function is called [`ClosestPowerOf2`](https://github.com/prysmaticlabs/prysm/blob/develop/shared/mathutil/math_helper.go#L76)

**Comment by prestonvanloon** [comment]
Thanks for reporting this!
