### ISSUE TITLE
Split the Sync Services Routines

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#900]
Currently both the `Sync` and `InitialSync` services both respond to requests and process blocks in the same goroutine. This brings up an attack vector , where a malicious node can potentially basically DOS another node by overloading that node with requests which would prevent the node from block processing and advancing their local chain in the `SyncService` or saving blocks in `InitialSyncService`. 

One way to mitigate this is to split the main goroutine into two separate routines, where one would be in-charge of block processing and the other would be respond to block requests. This would be similar to how it is currently carried out in the `blockchain` service where one routine handles, block processing and the other routine actually updates head, applies fork-choice rule etc to the local chain. 

This issue is also tangentially related to #898.

**Comment by prestonvanloon** [comment]
How does this align with #1018?

**Comment by nisdas** [comment]
This can be included in the PR for #1018 too , where we will be combining the sync services into a single services. This just deals with splitting up the big-goroutines into multiple smaller ones.

**Comment by rauljordan** [comment]
Update on this @nisdas ?
