### ISSUE TITLE
Can't get validator balances for certain epochs

### ISSUE THREAD

**Issue by aely-aronoff** [prysmaticlabs/prysm#9019]
# 🐞 Bug Report

### Description

During API call to `GET /eth/v1alpha1/validators/balances?epoch=XXXXX`, I get `{"code":13, "message":"Could not get state", "details":[]}`. Happens on both Pyrmont and mainnet. Other endpoints referencing that same epoch work fine (both `GET /eth/v1alpha1/validators/assignments?epoch=XXXXX` and `GET /eth/v1alpha1/validators/participation?epoch=XXXXX` seem to work correctly). 

My hunch is that the error is being thrown here:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/beacon/validators.go#L71
That seems to be the only place where the exact string "Could not get state" appears. Other places either have a lower-case 'c' or have a colon with another message afterwards.

The error came up while I was polling forward through epochs. For instance, starting at epoch 40,000, get a validator's balance in every epoch until the present. 

The weirdest part: The error seems to happen only for epochs a random stretch before a DB archive point. For example, I have an archive point at epoch 45,312. I get that error for all epochs from 45,286 until epoch 45,311. It's fine for a few epochs until epoch 45,345, then all epochs until 45,439 are broken. Epoch 45,440 is an archive point. Note that epoch 45,376 *is* an archive point, but I still get the error for that epoch. Usually, it only lasts until the next archive point, but 45,376 stood out because it's an archive point that didn't fix things. I couldn't find any pattern in when the errors first occur, but they're consistently broken until an archive point, though not necessarily the first archive point encountered. (I put all the specific broken epoch ranges that I noticed at the very bottom)

### Has this worked before in a previous version?

Don't know but it didn't work in either version 1.3.9 or 1.3.10.

## 🔬 Minimal Reproduction

I'm running it with the Prysm install script using systemd. Service file (`/etc/systemd/system/goerli-prysm-beacon.service`):
<pre><code>[Unit]
Description = Prysm beacon chain Goerli
Wants = network-online.target
After = network-online.target

[Service]
Type = simple
User = goerli-prysm
ExecStart = /home/MY_USER_NAME/prysm/prysm.sh beacon-chain --pyrmont --p2p-max-peers=45 --monitoring-host="0.0.0.0" --http-web3provider=http://127.0.0.1:8546 --accept-terms-of-use --datadir=/home/MY_USER_NAME/prysm
# Restart = on-failure

[Install]
WantedBy = multi-user.target</code></pre>

I'm running a geth instance locally as well as a Prysm validator locally, similarly with systemd.
The above service file is essentially the same as the one that's running mainnet except without the `--pyrmont` flag.

## 🔥 Error

I don't see anything in the logs (which I access with `journalctl -u goerli-prysm-beacon`). The log keeps saying it's applying state transitions, finding peers, etc. In general, the node is working correctly and if the error is thrown where I think it's thrown there isn't any logging of the Golang error that takes place.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 Operating System: Ubuntu 20.04.2 LTS
  Kernel: Linux 5.8.0-53-generic
  Architecture: x86-64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
curl -X GET http://127.0.0.1:3500/eth/v1alpha1/node/version
{"version":"Prysm/v1.3.10/5ae6e83c7f6238593c6dfa3a8e05fc7c3778783f. Built at: 2021-06-02 14:47:33+00:00", "metadata":""}
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

Pyrmont, I get that error for epochs in these ranges:
44984-44991
45025-45055
45222-45247
45286-45311
45345-45439
45474-45503
45537-45567
45604-45631

Mainnet, I get that error for epochs in these ranges:
42846-42879
42910-42943
42973-43007

There are probably other holes, but those are the ones I wrote down so far.

I'm happy to run stuff if it'll help for debugging!

Cheers!
Aely

**Comment by prestonvanloon** [comment]
We think that these requests might be timing out after 30 seconds. Unfortunately, the underlying error is not surfaced. I'll submit a PR to surface the underlying error. 

https://github.com/prysmaticlabs/prysm/blob/7a6ce27497268f840b9cd9f11c9c892388970db9/beacon-chain/rpc/beacon/validators.go#L69-L72

In the meantime, could you try a smaller value for `--slots-per-archive-point=2048` in the beacon chain node? I believe that smaller checkpoints may help alleviate the request latency.

**Comment by aely-aronoff** [comment]
Ah that makes sense. Would you like me to try deploying the new version with your new PR to see what the underlying error is?

**Comment by prestonvanloon** [comment]
That could be helpful. gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-6981b1 is the latest in develop branch, if you run docker.

**Comment by aely-aronoff** [comment]
Can confirm the problem was timing out. Shortening the slots per archive point solved it for me. Thank you!
