### ISSUE TITLE
[2021-06-11 14:16:46]  INFO validator: Validator exited index=20000 pubKey=0x8d3828000000 status=EXITED

### ISSUE THREAD

**Issue by iPhonePKAndroid** [prysmaticlabs/prysm#9021]
由于服务器关机，没有运行，之后2台服务器同时运行，导致出错，同时没有收益，为什么？
"""
Because the server is shut down, it is not running, and then two servers are running at the same time, which leads to an error and no profit at the same time. Why?
"""

```
[2021-06-11 14:16:46]  INFO validator: Validator exited index=20000 pubKey=0x8d3828000000 status=EXITED
```

**Comment by prestonvanloon** [comment]
Hi, which network is this? I can't find that validator index pubkey pair in mainnet, prater, or pyrmont.

**Comment by iPhonePKAndroid** [comment]
> Hi, which network is this? I can't find that validator index pubkey pair in mainnet, prater, or pyrmont.

mainnet,and you?

**Comment by prestonvanloon** [comment]
There must be some mistake. Validator 20000 is not exited. Validator 20000 is also not pubkey `0x8d3828000000`.

https://beaconcha.in/validator/20000

**Comment by iPhonePKAndroid** [comment]
> 一定有什么错误。验证器 20000 未退出。Validator 20000 也不是 pubkey `0x8d3828000000`。
> 
> https://beaconcha.in/validator/20000

Excuse me, how is this solved?

**Comment by mohamedmansour** [comment]
> > 一定有什么错误。验证器 20000 未退出。Validator 20000 也不是 pubkey `0x8d3828000000`。
> > https://beaconcha.in/validator/20000
> 
> Excuse me, how is this solved?

Are you referring to validator 25894? https://beaconcha.in/validator/25894

**Comment by iPhonePKAndroid** [comment]
yes





------------------ Original ------------------
From: Mohamed Mansour ***@***.***&gt;
Date: Mon,Jun 14,2021 3:23 PM
To: prysmaticlabs/prysm ***@***.***&gt;
Cc: 超级问鼎 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prysmaticlabs/prysm] [2021-06-11 14:16:46]  INFO validator: Validator exited index=20000 pubKey=0x8d3828000000 status=EXITED (#9021)






一定有什么错误。验证器 20000 未退出。Validator 20000 也不是 pubkey 0x8d3828000000。
https://beaconcha.in/validator/20000

Excuse me, how is this solved?

Are you referring to validator 25894? https://beaconcha.in/validator/25894

**Comment by mohamedmansour** [comment]
> yes
> […](#)

If that validator was yours, then yea it sucks. That validator was slashed because of “attestation violation”. This could happen because of these reasons:

- **Double voting**: An attester signs two different attestations in one epoch.
- **Surround votes**: An attester and sign an attestation that surrounds another one.

If you have a misconfigured docker, or a setup that does complex recovery, you could have voted incorrectly or even twice. Do you recall what happened?

**Comment by iPhonePKAndroid** [comment]
Double voting: An attester signs two different attestations in one epoch.


So what should I do






------------------ Original ------------------
From: Mohamed Mansour ***@***.***&gt;
Date: Mon,Jun 14,2021 7:06 PM
To: prysmaticlabs/prysm ***@***.***&gt;
Cc: 超级问鼎 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prysmaticlabs/prysm] [2021-06-11 14:16:46]  INFO validator: Validator exited index=20000 pubKey=0x8d3828000000 status=EXITED (#9021)





  
yes
 …
  
If that validator was yours, then yea it sucks. That validator was slashed because of “attestation violation”. This could happen because of these reasons:
  
Double voting: An attester signs two different attestations in one epoch. 

Surround votes: An attester and sign an attestation that surrounds another one. 
 
If you have a misconfigured docker, or a setup that does complex recovery, you could have voted incorrectly or even twice. Do you recall what happened?

**Comment by prestonvanloon** [comment]
Please review this article: https://medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50

In short, there is nothing for you to do until withdrawals are enabled in eth2. At that time, you can retrieve the remaining validator balance. This is expected in early 2022.

**Comment by iPhonePKAndroid** [comment]
So there's nothing I can do now? Can't keep digging? My principal will not be lost? But I will lose ETH profits? Is there no other solution? Please

**Comment by iPhonePKAndroid** [comment]
> Please review this article: https://medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50
> 
> In short, there is nothing for you to do until withdrawals are enabled in eth2. At that time, you can retrieve the remaining validator balance. This is expected in early 2022.

So there's nothing I can do now? Can't keep digging? My principal will not be lost? But I will lose ETH profits? Is there no other solution? Please

**Comment by iPhonePKAndroid** [comment]
我认为客户端在同时运行的两个客户端之后，应该会自动暂停掉一个。
他显然没那么智能，该死的。





------------------ Original ------------------
From: Preston Van Loon ***@***.***&gt;
Date: Mon,Jun 14,2021 11:24 PM
To: prysmaticlabs/prysm ***@***.***&gt;
Cc: 超级问鼎 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [prysmaticlabs/prysm] [2021-06-11 14:16:46]  INFO validator: Validator exited index=20000 pubKey=0x8d3828000000 status=EXITED (#9021)






Closed #9021.

**Comment by iPhonePKAndroid** [comment]
> 请查看这篇文章：[https](https://medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50) : [//medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50](https://medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50)
> 
> 简而言之，在 eth2 中启用提款之前，您无事可做。届时，您可以检索剩余的验证器余额。预计在 2022 年初。

我认为客户端在同时运行的两个客户端之后，应该会自动暂停一个。
所以我现在什么都做不了？不能继续挖吗？我的本金不会丢吧？但是我会失去 ETH 的利润吗？没有其他解决办法吗？请


"
I think the client should automatically pause one of the two clients running at the same time. I think the client should automatically pause one of the two clients running at the same time.
So there's nothing I can do now? Can't you keep digging? I won't lose my principal, will I? But will I lose ETH's profits? Is there no other solution? Please
"

**Comment by nisdas** [comment]
@iPhonePKAndroid This is being worked on here:
https://github.com/prysmaticlabs/prysm/pull/8932

It is recommended to never be running 2 clients at the same time. Your underlying principal will be fine after the slashing penalty has been netted out. However, unfortunately you will not be able to earn any more validator rewards from now on. As of the current moment there is nothing else you can do, except to wait for withdrawals.
