### ISSUE TITLE
Terminate/Exit Validator 126732

### ISSUE THREAD

**Issue by tcchen123** [prysmaticlabs/prysm#9028]
# 💎 Issue
Can help to exit Validator 126732 ? It is running on Kovan testnet.

### Background 
I have destroyed all my resources setup and purge all data profile on Digital Ocean. 
I do not have access it the account and resources that created this validator. 
Now, I cannot exit this Kovan testnet validator.
Kindly help to exit it.

![20210613 Kovan Testnet Validator 126732](https://user-images.githubusercontent.com/19972041/121793858-b5c74300-cc35-11eb-8949-3ba7a5a4c49c.JPG)

**Comment by prestonvanloon** [comment]
Please review the documentation for exiting a validator. https://docs.prylabs.network/docs/wallet/exiting-a-validator

Without access to the validator keys, you cannot exit the validator.

**Comment by tcchen123** [comment]
> Please review the documentation for exiting a validator. https://docs.prylabs.network/docs/wallet/exiting-a-validator
> 
> Without access to the validator keys, you cannot exit the validator.

Does this mean the validator will always exist on the kovan testnet ? Is there another way to remove this validator ?
