### ISSUE TITLE
Memory does not get freed when doing a backup

### ISSUE THREAD

**Issue by mohamedmansour** [prysmaticlabs/prysm#9031]
Prysm Beacon v1.3.10

It jumped from 5gb to 20gb when I started the backup, and it never released the memory after the backup completed. Initiated after curl `http://127.0.0.1:8080/db/backup`

![image](https://user-images.githubusercontent.com/68524/121850738-11c7b100-cca2-11eb-8182-abbd81b1f92f.png)

After I restarted Prysm, it freed the memory.
![image](https://user-images.githubusercontent.com/68524/121853689-142c0a00-cca6-11eb-99e9-7f219ab1d6e9.png)

**Comment by nisdas** [comment]
In-memory beacon backups have been disabled since v4 due to their infeasibility, so closing this issue
