### ISSUE TITLE
Show Error in Logs if Passing Invalid Flag in Config Yaml

### ISSUE THREAD

**Issue by mohamedmansour** [prysmaticlabs/prysm#9032]
Would be nice to show an error in logs if an invalid flag is passed from config yaml.

I was struggling why my port forward of grpc API is, and it turned out I mistyped: `rpc-gateway-host: '0.0.0.0', should have been instead of `grpc-gateway-host: '0.0.0.0'` That was a few hours lost.

**Comment by mohamedmansour** [comment]
In yaml.v2 go package, there is `UnmarshalStrict` that can be used instead of `Unmarshal`, in https://github.com/prysmaticlabs/prysm/blob/HEAD/shared/params/loader.go#L33

**Comment by mohamedmansour** [comment]
@nisdas if I do this, it will be a breaking change for those who have invalid flags

```
[2021-06-14 03:17:52] FATAL Failed to parse chain config yaml file. error=yaml: unmarshal errors:
  line 1: field pc not found in type params.BeaconChainConfig
```

**Comment by nisdas** [comment]
@mohamedmansour we can either introduce it in the next minor version bump: 1.4.x . Or release it in the version after the PR is merged in. Correcting for invalid behaviour shouldn't be classified as a breaking change imo but I can see how users running with the config will see it differently. I am fine pushing this onto 1.4.x , wdyt @prestonvanloon ?
