### ISSUE TITLE
s390x architecture support

### ISSUE THREAD

**Issue by e-desouza** [prysmaticlabs/prysm#9034]
# 🚀 Feature Request

### Description

 Prysm support for the s390x architecture

### Describe the solution you'd like

 I will be porting to s390x but just created this FR to get community support as questions arise. Most of the build completes (esp with the recently mcl/bls port to s390x) but I'm sure I'll need help along the way..

### Describe alternatives you've considered

 There are no good ETHv2 alternatives on s390x. This needs to run on s390x so amd64/arm64 etc wouldn't work either..

**Comment by prestonvanloon** [comment]
This is unlikely to be supported from the core team. I believe that you might be able to compile [lighthouse](https://github.com/sigp/lighthouse) for s390x. I saw that the BLS library, blst, seems to support s390x in rust. https://github.com/supranational/blst/blob/29b6b95e26aee872d1793f801f296d076be5b57f/.travis.yml#L51-L54

Not sure what would be required to support this architecture or how we would test it. 
mcl & herumi's dependency will soon be removed, so I wouldn't focus too much energy on that.

Please keep this issue up to date with any progress you make. If it seems viable to cross compile for s390x, then we could add this to our list of supported architectures in the future. However, this feature would rely heavily on external contributors as the core team has limited bandwidth to support this functionality in the near future.

**Comment by e-desouza** [comment]
Hi @prestonvanloon , we've been focusing on porting some other protocols due to the BLST gap but are back now. Is there a build flag to turn **off** the need for BLST? I understand it'll be slow, but I want to get a rough idea of order of magnitude perf degradation in the absence of optimized BLST. We'll be pursuing that path in parallel, but wanted to get a functional build working on the platform.

**Comment by prestonvanloon** [comment]
@e-desouza https://github.com/prysmaticlabs/prysm/pull/8710 removed the alternative library for BLS. You could revert this PR and continue to use Herumi's BLS library, which may or may not support s390x. It also has some architecture specific functionality so it may not satisfy your use case.  At one point, we used https://github.com/phoreproject/bls as a pure go bls implementation. I am not sure if it is up to spec anymore, but you could consider forking prysm and adding this as an alternative bls implementation. If spec tests pass, then you should be good to go.

**Comment by james-prysm** [comment]
I believe this issue has been resolved, closing for now, can reopen if needed.
