### ISSUE TITLE
Try to exit a Validator - Terminate/Exit Validator 126732 #9028

### ISSUE THREAD

**Issue by tcchen123** [prysmaticlabs/prysm#9036]
Please review the documentation for exiting a validator. https://docs.prylabs.network/docs/wallet/exiting-a-validator

Without access to the validator keys, you cannot exit the validator.

_Originally posted by @prestonvanloon in https://github.com/prysmaticlabs/prysm/issues/9028#issuecomment-860677685_

It is ok then to leave this validator as-is as I cannot exit it on the kovan testnet ? Is there another way to kill this kovan test validator ?

**Comment by prestonvanloon** [comment]
Nothing can be done without access to the validator keys. This validator cannot exit without the validator keys. Eventually, this validator will leak its balance until it is ejected.
