### ISSUE TITLE
E2E Test Suite

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#904]
Currently there are no tests in our repo that ensure that a beacon/validator client is able to start up correctly and run as expected. Critical bugs which lead to failures in launching clients, clients not running as expected and panics in them are not able to be detected unless someone manually runs a client themselves. For an example of this, #903. 

A solution to stop this from happening would be to have an end to end test suite which would ensure that the clients are running as expected and no critical errors have been introduced by a PR. This issue is to track discussion on implementing a e2e test suite for prysm.

**Comment by terencechain** [comment]
Can close this with latest merge of E2E test. Feel free to open another mega tracking e2e issue if there's more to this
