### ISSUE TITLE
Balance Leakage  to cause Validator to be ejected

### ISSUE THREAD

**Issue by tcchen123** [prysmaticlabs/prysm#9040]
Nothing can be done without access to the validator keys. This validator cannot exit without the validator keys. Eventually, this validator will leak its balance until it is ejected.

_Originally posted by @prestonvanloon in https://github.com/prysmaticlabs/prysm/issues/9036#issuecomment-860847424_

Q1.  By how much the balance leakages of the validator will result in it been ejected ?

**Comment by vanpa** [comment]
If a validator's balance drops below 16 ETH (typically due to inactivity), it will be ejected. Ejections are treated the same as a voluntary exits.

These may be good questions to discuss in the discord, also the "Prysm Eth2 Docs" are really helpful, see the Validator lifecycle section

**Comment by prestonvanloon** [comment]
@tcchen123 The answer is above. I recommend that you join our discord server for faster answers to these types of questions. 

https://discord.com/invite/YMVYzv6

**Comment by tcchen123** [comment]
Vanpa, thanks for feedback.
Is below 16 ETH the hard limit set by who ? Can it be changed to say eg 80%
of 32 ETH deposit = 25.6 Eth ?

**Comment by prestonvanloon** [comment]
That is set by the protocol as defined in the eth2 specification. https://github.com/ethereum/eth2.0-specs/tree/master

Changing this value would be a hard fork network upgrade requiring coordination through the whole eth2 development group.

**Comment by tcchen123** [comment]
Preston, much appreciate your prompt reply.
Noted.
