### ISSUE TITLE
prysm.sh, prysm.bat, prysm.ps1 should not save 404 pages

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#9041]
# 🐞 Bug Report

### Description

When the prysm download scripts access a 404 page. The script should not save the 404 page and try to continue through the script. The script should fail immediately when hitting a 404.

### Has this worked before in a previous version?

N/A

## 🔬 Minimal Reproduction

USE_PRYSM_VERSION=fake ./prysm.sh beacon-chain version

## 🔥 Error

<pre><code>Latest Prysm version is fake.
Downloading beacon chain@fake to /home/preston/git/prysm/dist/beacon-chain-fake-linux-amd64 (specified in $USE_PRYSM_VERSION)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2337    0  2337    0     0  10869      0 --:--:-- --:--:-- --:--:-- 10869
Verifying binary integrity.
shasum: /home/preston/git/prysm/dist/beacon-chain-fake-linux-amd64.sha256: no properly formatted SHA checksum lines found
Failed to verify Prysm binary. Please erase downloads in the
dist directory and run this script again. Alternatively, you can use a
A prior version by specifying environment variable USE_PRYSM_VERSION
with the specific version, as desired. Example: USE_PRYSM_VERSION=v1.0.0-alpha.5
If you must wish to continue running an unverified binary, specific the
environment variable PRYSM_ALLOW_UNVERIFIED_BINARIES=1
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
N/A
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
N/A
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by ahadda5** [comment]
@prestonvanloon  starting with the .sh script, it is clear that it constructs the path based on the dir, version, system(win, Linux ) and architecture(amd64 etc).   It then immediately assumes it is up to date!  Not sure why you would do that. 
So a simple check ; curl the full paths of beacon-chain/validator/client-states  ensuring if it exists , if not stop.

**Comment by mohamedmansour** [comment]
@prestonvanloon @rauljordan i noticed we have like a script for every os, In Chromium dev since the infra is in python (recently moving to go) we write all the scripts in python and then wrappers so .bat and .sh just call it. Maybe something along those lines could be done to these scripts? Makes maintenance easier

**Comment by rauljordan** [comment]
Closed by #9072
