### ISSUE TITLE
If you apply tls, the endpoints are not separated by comma

### ISSUE THREAD

**Issue by SunSet0418** [prysmaticlabs/prysm#9049]
# 🐞 Bug Report

### Description

When connecting multiple beacon node endpoints, enter a single string separated by comma
This only works well if it's unsafe.
When the tls certificate is applied, multiple endpoints, not separated by comma are recognized as one domain.

ex) `"beaconnode-service:4000,fallback-beaconnode-service:4000"`

I want to apply tls certificate to both default node and fallback node.

### Has this worked before in a previous version?

I tried it for the first time in `v1.3.9`. I don't know if it's working on previous versions.

## 🔥 Error

<pre><code>
could not setup beacon chain ChainStart streaming client: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for beaconnode-service, beaconnode-service.bc.svc.cluster.local, beaconnode-service.bc, fallback-beaconnode-service, fallback-beaconnode-service.bc.svc.cluster.local, fallback-beaconnode-service.bc, not beaconnode-service:4000,fallback-beaconnode-service:4000": could not connect
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Kubernetes

Certificate Issuer : cert-manager
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
BeaconChain : v1.3.10
Validator : v1.3.9
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by diesel-dunamu** [comment]
@rkapka This means declaring multiple hosts in the beacon-rpc-provider flag.
ex) `--beacon-rpc-provider=hostA,hostB,hostC`

**Comment by SunSet0418** [comment]
@rkapka This means declaring multiple hosts in the beacon-rpc-provider flag. ex) `--beacon-rpc-provider=hostA,hostB,hostC`

**Comment by azvz** [comment]
I have a similar issue without k8s. When using the `--beacon-rpc-provider=hostA,hostB,hostC` parameter (comma separated list of hosts). Even though all of the hosts are mentioned in the certificate: 
```bash
user@host:/var/lib/prysm/tls$ openssl x509 -in beacon.pem -text -noout | grep DNS
                DNS:hostA, DNS:hostB, DNS:hostC, IP Address:127.0.0.1
```
I am still getting the error mentioned by @SunSet0418. 

Connecting to individual hosts ex. `--beacon-rpc-provider=hostA` works fine.

**Comment by rkapka** [comment]
Thanks for the report @azvz. I will take a look at this next week.
