### ISSUE TITLE
validator healthz endpoint not working

### ISSUE THREAD

**Issue by Belkaar** [prysmaticlabs/prysm#9052]
# 🐞 Bug Report

### Description
calling "curl -s http://localhost:8081/healthz" returns no data and log contains errors.

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was: not really sure, but smaller than 1.3.9

## 🔬 Minimal Reproduction

start validator with these params: 
`/opt/prysm/validator_active --accept-terms-of-use --attest-timely --graffiti "XXXXXX" --datadir /mnt/store_0/validator --wallet-dir /mnt/store_0/validator/wallet --wallet-password-file /mnt/store_0/validator/passwords/wallet.pass --web`

call curl -s http://localhost:8081/healthz

## 🔥 Error

<pre><code>
Jun 16 21:04:39 eth2 validator_active[14512]: 2021/06/16 21:04:39 http: panic serving 127.0.0.1:40808: runtime error: invalid memory address or nil pointer dereference
Jun 16 21:04:39 eth2 validator_active[14512]: goroutine 715 [running]:
Jun 16 21:04:39 eth2 validator_active[14512]: net/http.(*conn).serve.func1(0xc001db3720)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:1824 +0x153
Jun 16 21:04:39 eth2 validator_active[14512]: panic(0x10fcaa0, 0x1accf30)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/runtime/panic.go:971 +0x499
Jun 16 21:04:39 eth2 validator_active[14512]: google.golang.org/grpc.(*ClientConn).GetState(...)
Jun 16 21:04:39 eth2 validator_active[14512]:         external/org_golang_google_grpc/clientconn.go:544
Jun 16 21:04:39 eth2 validator_active[14512]: github.com/prysmaticlabs/prysm/shared/gateway.(*Gateway).Status(0xc000ae15e0, 0xc001146ff0, 0xc001d99878)
Jun 16 21:04:39 eth2 validator_active[14512]:         shared/gateway/gateway.go:202 +0x3a
Jun 16 21:04:39 eth2 validator_active[14512]: github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).Statuses(0xc00111eda0, 0xc001d99928)
Jun 16 21:04:39 eth2 validator_active[14512]:         shared/service_registry.go:67 +0xe8
Jun 16 21:04:39 eth2 validator_active[14512]: github.com/prysmaticlabs/prysm/shared/prometheus.(*Service).healthzHandler(0xc00111f340, 0x142b4f0, 0xc001f44540, 0xc002000900)
Jun 16 21:04:39 eth2 validator_active[14512]:         shared/prometheus/service.go:70 +0x47
Jun 16 21:04:39 eth2 validator_active[14512]: net/http.HandlerFunc.ServeHTTP(0xc0011b23d0, 0x142b4f0, 0xc001f44540, 0xc002000900)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:2069 +0x44
Jun 16 21:04:39 eth2 validator_active[14512]: net/http.(*ServeMux).ServeHTTP(0xc00115aa00, 0x142b4f0, 0xc001f44540, 0xc002000900)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:2448 +0x1ad
Jun 16 21:04:39 eth2 validator_active[14512]: net/http.serverHandler.ServeHTTP(0xc0011947e0, 0x142b4f0, 0xc001f44540, 0xc002000900)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:2887 +0xa3
Jun 16 21:04:39 eth2 validator_active[14512]: net/http.(*conn).serve(0xc001db3720, 0x142df38, 0xc001f74540)
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:1952 +0x8cd
Jun 16 21:04:39 eth2 validator_active[14512]: created by net/http.(*Server).Serve
Jun 16 21:04:39 eth2 validator_active[14512]:         GOROOT/src/net/http/server.go:3013 +0x39b

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian Linux amd64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.3.11 (also happens on 1.3.10 and 1.3.9)
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Was your validator connected to a beacon node?

**Comment by prestonvanloon** [comment]
@rkapka Looks related to some gateway work. `g.conn` seems that it is not set when calling Status(). Any idea?

Simple solution is to check that it is not nil.

**Comment by Belkaar** [comment]
> Was your validator connected to a beacon node?

Yes and correctly attesting

**Comment by rkapka** [comment]
This was fixed in https://github.com/prysmaticlabs/prysm/pull/9050
