### ISSUE TITLE
Feature: prysm.sh can update itself

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#9133]
# 🚀 Feature Request

### Description

Add functionality to `prysm.sh` to update itself, and print a warning when it is run as a user that does not have permissions to update it. 

### Current behavior

With `prysm.sh` owned by `yorick`, it does not update itself, example:

```
yorick@ethlinux:~/prysm$ ./prysm.sh client-stats
Latest Prysm version is v1.3.11.
Process 'client-stats' is not found!
Usage: ./prysm.sh PROCESS FLAGS.
       ./prysm.sh PROCESS --download-only.
PROCESS can be beacon-chain, validator, or slasher.
```

**Comment by james-prysm** [comment]
Closing this one as we will eventually migrate away from prysm.sh
