### ISSUE TITLE
Bandwidth increase on the input chain

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#9159]
Since a few days back, I'm seeing an increase in the input bandwidth. The input and output rates are diverging as you can see in this graph. The scale is a big off due to the event marked there, but the two lines are clearly separating with the input one having increased about 30% while the output less than 10%

![fo](https://user-images.githubusercontent.com/16044918/124750886-630f3d00-defc-11eb-96fb-9712da928339.jpg)

This is a dedicated server running:
-  Arch linux 5.12.12-x86_64 
- `beacon-chain version Prysm/v1.3.9/255354f27eb9cdd7d3afe5ef9759629150785276` and same commit for the validator client. 
- Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
- 64GB DDR4 RAM
- 2Tb NVME

**Comment by prestonvanloon** [comment]
Thanks for filing an issue. I'm thinking about what action @prysmaticlabs/core-team can take here. 
Do you have any additional information that would be relevant? Which network was this?

**Comment by potuz** [comment]
> Thanks for filing an issue. I'm thinking about what action @prysmaticlabs/core-team can take here.
> Do you have any additional information that would be relevant? Which network was this?

Those are my thoughts, just opened cause @nisdas asked, so that he remembers to look into bandwidth growth. This is on mainnet. I think this is mostly a placeholder for @nisdas to look if there's an actual issue. I'm fine if this is closed at any moment.

**Comment by terencechain** [comment]
I will close this since there hasn't been any follow-up for ~100 days. Feel free to open this issue, and we can reopen the investigation again
