### ISSUE TITLE
Log auth token with --web

### ISSUE THREAD

**Issue by dapplion** [prysmaticlabs/prysm#9188]
# 🚀 Feature Request

### Description

When using the `--web` the UI routes are not authenticated and "anyone" can start the user flow. That's not ideal, thus the validator client alerts of this possibility with periodic logs.

### Describe the solution you'd like

When using the `--web` flag, the validator client can generate a random auth token and log it to stdout + write it to a file to persist it. Then the user should copy the token and log in with it. Password managers will still see the login action and store the token so the user doesn't have to grab it again from the logs.

### Describe alternatives you've considered

Status quo

**Comment by dnkolegov** [comment]
> When using the --web flag, the validator client can generate a random auth token and log it to stdout + write it to a file to persist it

If a logging mechanism and file are used for token delivery you need to be sure that:
- the file has permissions 0600
-  token will not be logged into a log file readable for anyone

Such bugs were found in Lighthouse:
- https://github.com/sigp/lighthouse/issues/2438
- https://github.com/sigp/lighthouse/issues/2437

**Comment by dapplion** [comment]
> > When using the --web flag, the validator client can generate a random auth token and log it to stdout + write it to a file to persist it
> 
> If a logging mechanism and file are used for token delivery you need to be sure that:
> 
> * the file has permissions 0600
> * token will not be logged into a log file readable for anyone
> 
> Such bugs were found in Lighthouse:
> 
> * [API token can be read from a log file by any user sigp/lighthouse#2438](https://github.com/sigp/lighthouse/issues/2438)
> * [File permissions for validator client API keys are insecure sigp/lighthouse#2437](https://github.com/sigp/lighthouse/issues/2437)

Good points! The flags could be more granular then to log to stdout or file depending on the security of the user's specific setup.

**Comment by dapplion** [comment]
@rauljordan bump

**Comment by rauljordan** [comment]
This is now done! will be included in the next release
