### ISSUE TITLE
prysm beacon-chain reliably crashes after a couple of hours

### ISSUE THREAD

**Issue by MeoMix** [prysmaticlabs/prysm#9214]
# 🐞 Bug Report

### Description

About a week ago I started having trouble keeping my beacon-chain running reliably. Nothing appreciable has changed on my end since the issue started occurring, but if https://github.com/prysmaticlabs/prysm/issues/9070 is related then perhaps it is a recent regression in prysm.

I've tried disabling Windows Defender entirely as well as restarting my machine.

### Has this worked before in a previous version?

I've been running two nodes since genesis without issue. I was not having issues with 1.3.10

## 🔬 Minimal Reproduction

` ./prysm beacon-chain --http-web3provider=http://127.0.0.1:8545/`
` ./prysm validator --wallet-dir=C:\Users\MeoMedia\Desktop\ethereum\wallets\prysm-wallet-v2`

*wait a few hours* and when I check powershell everything has crashed.

## 🔥 Error

Here's what I see in powershell. It continues on for quite some time, but a brief scan didn't seem like the additional info was relevant. If there's a log file on my machine I'm not sure where to find it just yet.

https://pastebin.com/hesC9vgG

**Updated**
https://controlc.com/8dcff677

## 🌍  Your Environment

I'm running Windows 10 x64 on a fully up-to-date machine. 2tb nvme SSD which isn't under load. 20GB ram, using about 70% of it. 1080ti not under load.

**What version of Prysm are you running? (Which release)**

PS C:\Users\MeoMedia\desktop\ethereum\prysm> ./prysm beacon-chain --version
A subdirectory or file C:\Users\MeoMedia\Desktop\ethereum\prysm\dist already exists.
Latest prysm release is v1.3.11.
Using prysm version v1.3.11.
'Beacon' is not recognized as an internal or external command,
operable program or batch file.
WARN GPG verification is not natively available on Windows.
WARN Skipping integrity verification of downloaded binary
Verifying binary authenticity with SHA256 Hash.
SHA256 Hash Match
Starting Prysm beacon-chain --version
beacon-chain version Prysm/v1.3.11/9fd5575f65ae6f238462ead00ce4f0b16cd0370c. Built at: 2021-06-16 16:24:20+00:00

**Anything else relevant (validator index / public key)?**

https://beaconscan.com/main/validator/0x8bfd0c40f3fcbc57a690893ddbf82de1100413df89a702057050cd8ef55ad07ce7104caa63877d59088e33aeb3494bac

**Comment by nisdas** [comment]
@MeoMix Thanks for the report, do you by chance have the full stack trace ? Unfortunately what you pasted is only a portion of it, so it isn't possible for us to narrow down the issue with it.

**Comment by MeoMix** [comment]
@nisdas Understood, let me try to get a full one. It's clipping in powershell when I get to it and need to save something to disk.

**Comment by MeoMix** [comment]
@nisdas Here is a full stack trace. For the the non-pastebin link but it's over the max limit for a regular pastebin account.

I've edited my original post to reference this one, too.

https://controlc.com/8dcff677

**Comment by nisdas** [comment]
```
Exception 0xc0000005 0x1 0x343cda0 0x1ace6d3
PC=0x1ace6d3

runtime: unknown pc 0x1ace6d3
stack: frame={sp:0xdfb57fec18, fp:0x0} stack=[0x0,0xdfb57ffc30)
000000dfb57feb18:  5bffb34a08f9078d  4fd345220935f1c2
000000dfb57feb28:  1957fe963d0ee89a  00f5601d52c3dac8
000000dfb57feb38:  1add014188e3c1e2  48bd8d9775045f75
000000dfb57feb48:  e4669e560040657d  5a309c9d6a215102
000000dfb57feb58:  21ad29de5c9b3485  f281b6152bdfe379
000000dfb57feb68:  761acf978dd5f7d8  30ae80d43f73ac6a
000000dfb57feb78:  d00478bda7f18bfd  0460cfdd8caf9ba3
000000dfb57feb88:  00bf72c44d320241  c76d9e68ddf6586d
000000dfb57feb98:  67d3c16fd6c4ac40  6eb638966c0cdde2
000000dfb57feba8:  0000000001acefa7  000000c075cf4778
000000dfb57febb8:  000000dfb57ff630  000000dfb57ff1a0
000000dfb57febc8:  000000000343cd40  6921d9ad68416e47
000000dfb57febd8:  009078dfd763ea39  694076a176771053
000000dfb57febe8:  182edd29e6846d3f  ffb3fed34ee6415e
000000dfb57febf8:  f387f0d2b184a291  3748fd9217384b7b
000000dfb57fec08:  a936b4720b5b836f  1868e8ffba608db2
000000dfb57fec18: <0000000001ace830  60c89cbedb870f60
000000dfb57fec28:  000000dfb57ff1a0  000000dfb57ff140
000000dfb57fec38:  000000dfb57ff080  000000dfb57ff630
000000dfb57fec48:  000000dfb57ff570  000000c075cf46b8
000000dfb57fec58:  0000000001ace970  000000dfb57ff080
000000dfb57fec68:  000000dfb57ff140  000000dfb57ff140
000000dfb57fec78:  000000dfb57ff080  000000dfb57ff630
000000dfb57fec88:  000000dfb57ff570  000000c075cf46b8
000000dfb57fec98:  0000000001ac099a  000000c075cf4598
000000dfb57feca8:  000000c075cf4598  000000dfb57fee60
000000dfb57fecb8:  000000dfb57feec0  000000dfb57fef80
000000dfb57fecc8:  000000c075cf4718  000000c075cf45f8
000000dfb57fecd8:  000000c075cf4658  7dbd2898fb7026dd
000000dfb57fece8:  584f334b3d67f22f  43fc1ea8a0b30c30
000000dfb57fecf8:  b737da47605f94b9  fe07b998389d677b
000000dfb57fed08:  008fe9b32cbc52eb  ce8754893086556a
runtime: unknown pc 0x1ace6d3
stack: frame={sp:0xdfb57fec18, fp:0x0} stack=[0x0,0xdfb57ffc30)
000000dfb57feb18:  5bffb34a08f9078d  4fd345220935f1c2
000000dfb57feb28:  1957fe963d0ee89a  00f5601d52c3dac8
000000dfb57feb38:  1add014188e3c1e2  48bd8d9775045f75
000000dfb57feb48:  e4669e560040657d  5a309c9d6a215102
000000dfb57feb58:  21ad29de5c9b3485  f281b6152bdfe379
000000dfb57feb68:  761acf978dd5f7d8  30ae80d43f73ac6a
000000dfb57feb78:  d00478bda7f18bfd  0460cfdd8caf9ba3
000000dfb57feb88:  00bf72c44d320241  c76d9e68ddf6586d
000000dfb57feb98:  67d3c16fd6c4ac40  6eb638966c0cdde2
000000dfb57feba8:  0000000001acefa7  000000c075cf4778
000000dfb57febb8:  000000dfb57ff630  000000dfb57ff1a0
000000dfb57febc8:  000000000343cd40  6921d9ad68416e47
000000dfb57febd8:  009078dfd763ea39  694076a176771053
000000dfb57febe8:  182edd29e6846d3f  ffb3fed34ee6415e
000000dfb57febf8:  f387f0d2b184a291  3748fd9217384b7b
000000dfb57fec08:  a936b4720b5b836f  1868e8ffba608db2
000000dfb57fec18: <0000000001ace830  60c89cbedb870f60
000000dfb57fec28:  000000dfb57ff1a0  000000dfb57ff140
000000dfb57fec38:  000000dfb57ff080  000000dfb57ff630
000000dfb57fec48:  000000dfb57ff570  000000c075cf46b8
000000dfb57fec58:  0000000001ace970  000000dfb57ff080
000000dfb57fec68:  000000dfb57ff140  000000dfb57ff140
000000dfb57fec78:  000000dfb57ff080  000000dfb57ff630
000000dfb57fec88:  000000dfb57ff570  000000c075cf46b8
000000dfb57fec98:  0000000001ac099a  000000c075cf4598
000000dfb57feca8:  000000c075cf4598  000000dfb57fee60
000000dfb57fecb8:  000000dfb57feec0  000000dfb57fef80
000000dfb57fecc8:  000000c075cf4718  000000c075cf45f8
000000dfb57fecd8:  000000c075cf4658  7dbd2898fb7026dd
000000dfb57fece8:  584f334b3d67f22f  43fc1ea8a0b30c30
000000dfb57fecf8:  b737da47605f94b9  fe07b998389d677b
000000dfb57fed08:  008fe9b32cbc52eb  ce8754893086556a

goroutine 8259885 [syscall]:
github.com/supranational/blst/bindings/go._Cfunc_blst_pairing_commit(0xc075cf4580)
        _cgo_gotypes.go:827 +0x45
github.com/supranational/blst/bindings/go.PairingCommit(...)
        /execroot/prysm/external/com_github_supranational_blst/bindings/go/blst.go:213
github.com/supranational/blst/bindings/go.multipleAggregateVerifyPkInG1.func1(0xc075cb8a98, 0x1b51ca0, 0x2b, 0x2b, 0xc075cb8a9c, 0xc075cb8aa0, 0x3, 0xc075cbfbc0, 0xc075cb0100, 0x40, ...)
        /execroot/prysm/external/com_github_supranational_blst/bindings/go/blst.go:637 +0x31f
created by github.com/supranational/blst/bindings/go.multipleAggregateVerifyPkInG1
        /execroot/prysm/external/com_github_supranational_blst/bindings/go/blst.go:610 +0x1fa
```
This is a very interesting error, would point to some incompatibility with your hardware with our crypto library. Do you mind listing out the hardware specs of the machine you are running prysm on ?

```
Architecture:       
OS version:
Number of Cores:
Processor:
Processor Vendor:
System Memory:
CPU (Mhz):
.
.
```

**Comment by MeoMix** [comment]
Architecture: AMD64
OS: Windows 10 Pro N 64-bit (10.0, Build 19042.1110), Version: 20H2, Windows Feature Experience Pack 120.2212.3530.0
Processor: AMD Ryzen 7 1700x Eight-Core Processor (16 CPUs), ~3.4GHz
Memory: 20480MB (G.Skill Ripjaws V Series DDR4)
MOBO: Gigabyte AX370-Gaming 5
GPU: NVIDIA GeForce GTX 1080 Ti (not OCed)
SSD: SAMSUNG 970 EVO Plus SSD 2TB - M.2 NVMe

**Comment by nisdas** [comment]
> Presumably you mean something isn't jiving well with https://github.com/supranational/blst ?

That is correct. thanks for pasting your info here. I will see if I can anything related.

**Comment by MeoMix** [comment]
@nisdas Alright. Let me know if I can be of any assistance in debugging. I'll reinstall the software in a few days to see if "turning it off and on" helps at all, but will leave it in a bad state for now just in case you need more info.

**Comment by nisdas** [comment]
So interestingly a random crash on windows was reported here too:
https://github.com/golang/go/issues/40878

It had to do with the anti-virus messing with it. I looked through our commits between v1.3.10 and v1.3.11 , and there was no update to our crypto library. It seems like this version has been running for a few months across many different releases. 
https://github.com/prysmaticlabs/prysm/commit/80ab9201b35b543c245d190d0216eac9863155a1

It has been unchanged since our v1.3.6 release. 

Is there any chance it might be something recently installed/updated in your host machine ?

**Comment by MeoMix** [comment]
@nisdas It could be something to do with a windows update? Beyond that though, no. I'll see if there's any additional measures I can take to reduce Windows virus scanning.

**Comment by nisdas** [comment]
>  It could be something to do with a windows update?
That is possible, but I would have expected other complaints too. You can try switching off the AV, when running prysm just to see if it makes a difference.

**Comment by MeoMix** [comment]
> > It could be something to do with a windows update?
> 
> That is possible, but I would have expected complaints from other users too in that case. You can try switching off the AV, when running prysm just to see if it makes a difference.

Yah. I've added an exclusion to the ethereum folder and tried to more aggressively kill off Windows Defender. I'll let you know how it goes. This is likely it from the looks of the issue you linked -- nice find. I appreciate you digging for me. :)

**Comment by MeoMix** [comment]
It crashed twice in the last day, but the frequency seems lower than it was before I started messing with the AV more. I haven't fussed with registry settings to enable me to turn off "Real Time Protection" for more than a few minutes, but I have the entire rest of the Windows Defender suite disabled and no virus scan has occurred for the past three days.

I will look into disabling Windows Defender fully via registry and see if that helps next.

**Comment by MeoMix** [comment]
I received updates to prysm about a day ago and ran with the new latest for a while.

Interestingly, I'm no longer hard crashing. When I check my computer, instead of coming back to a stack trace, I see periodic blips of instability. Every 10-20 minutes I see a few "context deadline exceeded" messages. Then, everything seem to work as expected. Then, it blips again.

https://pastebin.com/f5RnxrKR

Windows Firewall is also entirely disabled at the moment. I have not experienced any Internet connectivity issues which might account for lack of peer discovery.

**Comment by nisdas** [comment]
So I looked at the logs pasted, the context deadline errors means that something is blocking outbound peer dials. Therefore the node cannot find enough peers to broadcast to. Any way to see if there is any windows process that might be overzealous here and blocking off the beacon node. The logs you have are very similar to the ones reported by windows users previously when they had their AV/some other process basically shut the beacon node off.

**Comment by MeoMix** [comment]
I edited my registry and disabled Windows Defender entirely and restarted. Been running for a day and still seeing issues. I don't have any protection running at all that I'm aware of at this point. Pretty interesting stuff. I'll let you know if I think of anything else to try.

**Comment by MeoMix** [comment]
A couple of days ago I installed new versions for the ETH upgrade, restarted prysm. prysm crashed after running for a while (unusual, hadn't hard crashed on me in a couple of weeks just failed to send data). I restart it, and now it's been running smooth for over a day. Yesterday had perfect uptime for the first time in 30 days. no change on my part beyond installing latest and turning everything off/on once more.

**Comment by rauljordan** [comment]
Hi @MeoMix does this issue still surface for you?

**Comment by MeoMix** [comment]
@rauljordan Yup. I haven't been actively debugging it, though. Last weekend I worked up the motivation to make another attempt. I wiped the folder I was using for storage of data, created a new folder, installed the latest prysm + geth, did a full redownload of blockchain data, and issue continues to repro. I don't have windows firewall or defender enabled.

https://beaconscan.com/main/validator/0x8bfd0c40f3fcbc57a690893ddbf82de1100413df89a702057050cd8ef55ad07ce7104caa63877d59088e33aeb3494bac

You can see the days I made an attempt at getting it running again. It runs fine for almost a full day before it starts timing out. Then if I stop/start the prysm services - it'll work again for a day before beginning to time out.

My next debugging attempt will be one which eliminates my current ISP from the equation by running things through AWS. I suspect that will work fine but won't offer up any information as to what has happened with my local machine.

**Comment by MeoMix** [comment]
Well, this started working again. Or, appears to be. I've been running for three days straight just fine. Will update again if it stops.
