### ISSUE TITLE
Possible DoS via beacon node API endpoints if the API exposed to untrusted parties

### ISSUE THREAD

**Issue by dnkolegov** [prysmaticlabs/prysm#9247]
# 💎 Issue

### Background

If the beacon node API is accessible on the internet then an attacker can perform a range-based DoS attack using `/eth/v1/validator/duties/attester/`.

The documents https://docs.prylabs.network/docs/how-prysm-works/ethereum-public-api and https://docs.prylabs.network/docs/how-prysm-works/ethereum-public-api don't contain warnings that Prysm Beacon Node API shouldn't be exposed to untrusted parties. 

At the same time, Prysm uses TLS to provide server-side authentication and encryption.

See also:
- https://github.com/sigp/lighthouse/issues/2468

At least we suggest adding the warning to the documentation.
### Description
Since TLS is already [used](https://docs.prylabs.network/docs/prysm-usage/secure-grpc/) it would be great to add optional certificate-based client-side authentication for customers deploying the nodes on clouds or the internet.

**Comment by prestonvanloon** [comment]
@rkapka Please take a look, re-assign as necessary.

**Comment by rkapka** [comment]
Hi @dnkolegov , we have added a warning to the documentation: https://docs.prylabs.network/docs/how-prysm-works/ethereum-public-api#performing-requests-against-a-local-prysm-node

Do you find it sufficient?

**Comment by rkapka** [comment]
As for certificate-based client-side authentication, thanks for mentioning it! We will take a look into this matter.

**Comment by dnkolegov** [comment]
>Do you find it sufficient?
Yes. It looks good.

**Comment by dnkolegov** [comment]
Opened a [feature request](https://github.com/prysmaticlabs/prysm/issues/9293) for client-side authentication.
