### ISSUE TITLE
Incorrect log message: Falling back to alternative endpoint

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#9258]
# 🐞 Bug Report

### Description

The beacon-node switches to an alternative ETH1 endpoint in case the primary is not available.
The corresponding log message however shows the primary ETH1 endpoint. This seems wrong to me.
After the colon it should show where it actually switched to.
Obviously a very minor bug.

![2021-07-23_07-38-02](https://user-images.githubusercontent.com/28559038/126741848-5da36978-64da-4181-b72c-aa0fc407fca6.png)

(in the above case it should show my Infura alternative endpoint instead)

### Has this worked before in a previous version?
n/a

## 🔬 Minimal Reproduction
Switch to alternative ETH1 endpoint and observe beacon log

## 🔥 Error
It says it falls to alternative, but it shows the primary

## 🌍  Your Environment
n/a

**Comment by ahadda5** [comment]
@handelaar2 i run alchemy, do you have geth on your machine? how do you specify an alternative in beacon-chain? where is that option?

**Comment by handelaar2** [comment]
@ahadda5 My Geth is on a separate machine (raspberry pi 4) in the local network.

The fallback option is defined by startup parameters of the beacon chain.
Primary defined by:`--http-web3provider=http://192.xx.xx.xx:8545`
Fallback defined by: `--fallback-web3provider=https://mainnet.infura.io/v3/xxx`

Fallback can be any (other) eth1-node. I think you can even define multiple fallbacks.
For using Infura you need to setup a (free) account.
