### ISSUE TITLE
Prysm.bat is Broken In Usage

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#9260]
# 🐞 Bug Report

### Description

Any users fetching the bat file to use to run the beacon-node or validator will not be able to. Some changes introduced
in #9072 have unfortunately broken the usage of it. 

### Has this worked before in a previous version?

Yes before this PR:
#9072  

## 🔬 Minimal Reproduction

```
prysm.bat beacon-chain
```

## 🔥 Error

```
C:\Prysm>prysm.bat beacon-chain --datadir=C:\prysm --http-web3provider=xxxxx
A subdirectory or file C:\Prysm\dist already exists.
Latest prysm release is v1.4.2.
Using prysm version v1.4.2.
( was unexpected at this time.
C:\Prysm>
```

## 🌍  Your Environment

**Operating System:**

Windows

**What version of Prysm are you running? (Which release)**

v1.4.1 ( This is also observed on v1.4.2).

## Workaround
For any other windows users running into this issue, the workaround is to use the bat script from here:
https://github.com/prysmaticlabs/prysm/blob/fc898d541fdc13faf5be5221833f9a8e904538ee/prysm.bat

This will work the same way as before.

**Comment by ahadda5** [comment]
That is correct.  it acts weird. 
First the script before #9072 was going into each if statement. So introduced the goto to skip it. 
Second as mentioned in the description , one has to run this command first. 

> open a cmd (either admin or regular )
**> under the prysm folder run this. Not running this extra code it will cause the actual script to complain ( was unexpected at this time. I think this is a glitch with curl/bat on windows. I'll check with Microsoft. [need to resolve this!]**
> >for /f "delims=" %i in ('curl --silent -w "%{http_code}" -L https://prysmaticlabs.com/releases/beacon-chain-%prysm_version%-%system%-%arch% -o gg.txt') do set http=%i
> set USE_PRYSM_VERSION=fake
> 
> prysm.bat beacon-chain version

**Comment by ahadda5** [comment]
i understand my workaround is not fit for a production release. I'll check with windows.

**Comment by ahadda5** [comment]
I posted this on [stackflow](https://stackoverflow.com/questions/68498480/bat-curl-with-for-complaining-about-a-was-unexpected-at-this-time)

**Comment by rkapka** [comment]
After you get everything working you might want to post your code to https://codereview.stackexchange.com/ to get some feedback.
