### ISSUE TITLE
Check slight memory utilization impact of #9155

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9263]
After separating out validators from the "BeaconState" in #9155. We memory utilisation seems to be slightly higher than normal. The issue is to track and see if the memory utilization is due to #9155 relate changes and fix it. Also he cache hit ratio has come down after https://github.com/prysmaticlabs/prysm/pull/9155#discussion_r672336449 fix. we need to find a good way to **increase the cache hit** ratio.

![915_final](https://user-images.githubusercontent.com/940575/126748402-431b070a-040b-4958-9f69-f7032cd7e78a.png)

_Originally posted by @jmozah in https://github.com/prysmaticlabs/prysm/issues/9155#issuecomment-885446271_

**Comment by nisdas** [comment]
@jmozah Can you add some more description to the issue ? Currently there is just a chart in the in the issue description and nothing else on the content of the issue.

**Comment by jmozah** [comment]
check this aafter #9298. may be it will come down.
Also, a bug fix regarding hash should improve the cache hits.
