### ISSUE TITLE
Migrate back from new validator schema to old one

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9281]
### Description

#9155 introduced a new validator schema to solve [#8954](https://github.com/prysmaticlabs/prysm/issues/8954). After this PR is merged, the migration is always one way. This issue is to add a revert of that migration to keep the feature more in control.

**Comment by nisdas** [comment]
Would a revert back here be realistic ? Once you do zero-out the validators from individual states, how exactly are you supposed to revert it back ? The process would involve basically resyncing the node. Any other solution ( ex: using the cached validators,etc), would be prone to being invalidated by any bug in the feature. I am not sure how feasible this would be to simply 'migrate' back to.

**Comment by terencechain** [comment]
> Would a revert back here be realistic ? Once you do zero-out the validators from individual states, how exactly are you supposed to revert it back ? The process would involve basically resyncing the node. Any other solution ( ex: using the cached validators,etc), would be prone to being invalidated by any bug in the feature. I am not sure how feasible this would be to simply 'migrate' back to.

@jmozah is working on a design doc for this, but the latest design discussion is here: https://discord.com/channels/476244492043812875/483017808658169866/869298337537486868

**Comment by jmozah** [comment]
Based on the design doc https://hackmd.io/soUUA3-dTYCSeBx4bkRc-Q#Migration
we have decided to pick option 2, which is 

Take a DB snapshot/backup before turning on the feature flag. if the DB gets corrupted, the user has to restore the DB from backup.

**Pro:**
- Simple
- No code changes required
**Con:**
- Node should start syncing from the restored point
- Extra space for backup

This has to be added to the release doc to make the user realise the risk he is taking.

**Comment by jmozah** [comment]
Closing this issue as we have taken decision to go in direction specified above.
