### ISSUE TITLE
Issues with posting data to the Ethereum API

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#9302]
# 🐞 Bug Report

### Description

Some problem with posting data to the API have been reported by our users.

**Attestations**
> Trying to send in attestations with the HTTP API and receiving errors of the form `{"index":0,"message":"attestation slot 1813226 + inclusion delay 1 \u003e state slot 1813226"}` I'm pretty sure this attestation should be accepted, and the message isn't clear as to why it's being rejected (at the time of the rejection state slot is indeed 1813226)

**Blocks**
> problem to produce block `{"code":13,"message":"Could not advance slot to calculate proposer index: expected state.slot 2111 < slot 2111","details":[]}` (on grpc-gateway)  on local testnet, and strange is that test found that block

**Comment by ahadda5** [comment]
what was the POST/GET data?

**Comment by rkapka** [comment]
@ahadda5 I think this might be a version of the *off-by-one* error. We are probably checking something using `<`/`>` when it should be `<=`/`>=`

**Comment by ahadda5** [comment]
@rkapka  one thing to note, based on running @BeroBurny test case for the 500 error: 

is that running /eth/v1/events?topics=attestation (or block) on port 5051( ethApiPort)  causes the error, 
"unexpected end of JSON input" , however running the same on port 5050 (grpc server ) it is fine! 
So its ethApiPort vs grpcGatewayPort implementation .

**Comment by ahadda5** [comment]
also, since this error was observed through SSE, could it be that this line requires   (see [this](https://stackoverflow.com/questions/27994327/golang-json-unmarshal-unexpected-end-of-json-input)
`json.NewDecoder(msg.Data.Body).Decode(eventData)` instead of  `json.Unmarshal(msg.Data, eventData);`

**Comment by rkapka** [comment]
> @rkapka one thing to note, based on running @BeroBurny test case for the 500 error:
> 
> is that running /eth/v1/events?topics=attestation (or block) on port 5051( ethApiPort) causes the error, "_unexpected end of JSON input"_ , however running the same on port 5050 (grpc server ) it is fine!
> So its ethApiPort vs grpcGatewayPort implementation at least for this "unexpected JSON error".

I already looked at the events issue and the problem there is less obvious. It would be great if you could concentrate on the 2 quotes bugs.

**Comment by mcdee** [comment]
Here is some recent information.  The following was sent to `/eth/v1/beacon/pool/attestations`:

```
[
  {
    "aggregation_bits": "0x0000000000008000000000000000000002",
    "data": {
      "slot": "1827397",
      "index": "17",
      "beacon_block_root": "0x27fc584f7b69f8a010bce415c66644ce93bc35f92b27703fabad81ce0f4c5f04",
      "source": {
        "epoch": "57105",
        "root": "0x68d2ca9a58312e26ff5a59a78202bafeb8688a64cb67fc81a4839152e04c1929"
      },
      "target": {
        "epoch": "57106",
        "root": "0x1bba17596b00db33b3c8910fb2572a4e857efc786c6f479a506938ba2328cd51"
      }
    },
    "signature": "0x90f58fed9a43a5a29f85409e72ee71f0295b6135e750821693633df2d64cadc95615ce33ab256a241b54571eb9f9cd5c031f1fb8a7dda95df65710c9de63b12fb926dcf5f68da4371b0c6a98b572fa65c5aba68dc783f812f3bdbfcc5d622d33"
  }
]
```

This was sent to a pyrmont node at 2021-07-30T08:19:35+01:00, which is four seconds in to the beginning of slot 1,827,397:

```
$ ethdo chain time --timestamp='2021-07-30T08:19:35+0100'
Epoch 57106
  Epoch start 2021-07-30 08:18:31
  Epoch end 2021-07-30 08:24:55
Slot 1827397
  Slot start 2021-07-30 08:19:31
  Slot end 2021-07-30 08:19:43
```

The response received was:

```
[
  {
    "index": 0,
    "message": "attestation slot 1827397 + inclusion delay 1 \u003e state slot 1827397"
  }
]
```

The last log entries in prysm are:

```
[2021-07-30 08:19:31]  INFO blockchain: Synced new block block=0x27fc584f... epoch=57106 finalizedEpoch=57104 finalizedRoot=0xb3094cb7... slot=1827397 slotInEpoch=5
[2021-07-30 08:19:31]  INFO blockchain: Finished applying state transition attestations=107
```

This is running against the current head of the develop branch 

```
$ rev-parse HEAD
560fe694259d3a223496f5f2feb5f20aa9c295e7
```
