### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 5dao** [prysmaticlabs/prysm#9314]
# 🐞 Bug Report

### Description

build error

## 🔥 Error

<pre><code>
ERROR: /home/x/.cache/bazel/_bazel_sh/61afc18407c47a8ab67af2f1ff4fb3ad/external/commands_overloads/linux_commands.bzl:3:20: invalid escape sequence: \$. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
</code></pre>

## 🌍  Your Environment

git: 47c28e6cd6b90097855014361ee19b853584c08f

**Comment by prestonvanloon** [comment]
Please use bazel version 3.7.0 or bazelisk. Prysm is not compatible with bazel 4, which gives the error you provided.

https://docs.prylabs.network/docs/install/install-with-bazel#install-bazel-using-bazelisk
