### ISSUE TITLE
Make Running a Prysm Local Devnet Trivial

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9351]
# 🚀 Feature Request

### Description

Running a local Prysm "devnet" meaning mock beacon node + validators is non-trivial and requires some commands and flags that are unintuitive to users. Being able to launch a dev setup is important and is done extensively by our team when testing code, however, no instructions are written anywhere and it is not simple to do so.

### Describe the solution you'd like

Ideally, something like `prysm.sh beacon-chain --dev` and `prysm.sh validator --dev` would spin up some simple configuration with N validators, allowing easy testing of changes at runtime with minimal overhead. If certain parameters wish to be changed, they can be specified as additional flags. Note this will only launch a single beacon node. For more complex setups, such as peering multiple nodes to this dev environment, we should also have a simple approach to accomplish this. Perhaps --dev mode can launch a very primitive bootnode that makes spinning up a second beacon node with --dev peer with the first.

These changes should be accompanied by a new page in our documentation portal on how to run a local devnet.

### Current approach

The current way to launch a single node, local devnet is to do the following

**Generate genesis state**

`bazel run //tools/genesis-state-gen -- --num-validators=1024 --output-ssz=/tmp/genesis.ssz --mainnet-config`

**Run beacon node**

```
bazel run //beacon-chain -- --datadir /tmp/chaindata --force-clear-db --interop-genesis-state /tmp/genesis.ssz --interop-eth1data-votes --min-sync-peers=0 --http-web3provider=https://goerli.prylabs.net/ --deposit-contract 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4  --bootstrap-node= --pprof
```

**Run validator client with keys**

```
bazel run //validator -- --beacon-rpc-provider localhost:4000 --interop-num-validators=1024 --interop-start-index=0 --force-clear-db
```

Note the approach above uses deterministic private keys for the sake of testing, so perhaps our solution can allow users to also specify their own keys easily.

**Comment by nisdas** [comment]
@rauljordan With this being added to our docs, do we still want this ? With the requirement to run an execution node, this will be more complicated to execute via prysm.sh

**Comment by rauljordan** [comment]
Agreed we already have this in our docs and it is sufficient, closing
