### ISSUE TITLE
[docs] improve documentation for running inside docker container

### ISSUE THREAD

**Issue by ralexstokes** [prysmaticlabs/prysm#9370]
# 🐞 Bug Report

### Description

The default host for the HTTP APIs is `127.0.0.1` but given the way docker networking works out of the box, this interface is not reachable from outside the container by default.

I stumbled into this testing out the new (standard) HTTP APIs and it would be nice if there is some mention of it in the docs on running prysm inside a container.

A suitable workaround is to run the HTTP APIs on `0.0.0.0` e.g.
```bash
docker run -p 3501:3501 gcr.io/prysmaticlabs/prysm/beacon-chain:stable --grpc-gateway-host 0.0.0.0
```

**Comment by rauljordan** [comment]
Hi @ralexstokes thanks for opening this! We do have docs on how to use Prysm with various installation methods, including Docker, here in our [testnet onboarding guide](https://docs.prylabs.network/docs/testnet/pyrmont), [mainnet guide](https://docs.prylabs.network/docs/mainnet/joining-eth2), and [docker](https://docs.prylabs.network/docs/install/install-with-docker) installation guides. Arguably, these are not very visible right off the bat. Aligning with the Altair release, we want to create a `v2.0.0` release of Prysm which will also include a rework of the docs for simplicity. We'll keep this in mind over the coming weeks. In the meantime, let us know if there is anything else we can help with. We answer faster in our [Discord](https://discord.gg/prysmaticlabs)

**Comment by prestonvanloon** [comment]
Closing old issues. This should be covered in documentation by now, but if you are still finding issues with docker then please reply here or create a new issue.
