### ISSUE TITLE
Include Golangci-lint in Our Github Actions and Resolve Lint Failures

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9371]
# 🚀 Feature Request

### Description

Our team currently relies on a combination of static analyzers for critical issues, shadowing, ineffectual assignment, and more. Additionally, we utilize Goland IDE's code inspection and a few other tools to improve code quality before checking in code into the repo. However, we should be leveraging linters a lot more than we do today. This issue describes what we want in terms of linters in our repo.

### Describe the solution you'd like

After some experience with various Go linters, [golangci-lint](https://golangci-lint.run/usage/configuration/) seems like the one with the most documentation, maintenance, and speed. We believe it would be a great addition to our project, and can be customized as much as we desire. We started with adding golangci-lint as a Github action in this [pull request](https://github.com/prysmaticlabs/prysm/pull/9369) #9369, however, the amount of work needed to get our repository to satisfy its rules is a lot for our team at the moment.

We are looking for help on satisfying [golangci-lint](https://golangci-lint.run/usage/configuration/) in Prysm. A PR to resolve this issue can start from the `lint-action` branch from #9369 and help us resolve all pending action items.

**Comment by estensen** [comment]
Hi, I'd like to help with this. I can start this weekend 😎

**Comment by estensen** [comment]
@rauljordan There are about 50 cases of shadowing declaration of `err`. What's the preferred way of solving that?

Example
```go
err := doSomething()
if err != nil {
	panic()
}

if err := doSomethingElse(); err != nil {
	panic()
 }
```

Renaming errors seems a bit ugly to me
```go
err := doSomething()
if err != nil {
	panic()
}

if otherErr := doSomethingElse(); otherErr != nil {
	panic()
 }
```

To not use the one-liner format is more verbose
```go
err := doSomething()
if err != nil {
	panic()
}

err = doSomethingElse()
if err != nil {
	panic()
 }
```

Or ignore them as they're not really a problem?

**Comment by rauljordan** [comment]
Let's ignore that linter because we agree it is not a problem. Don't add individual ignore rules for each instance, but instead, remove that linter from golangci-lint

**Comment by rkapka** [comment]
Won't that remove checking shadowing all together @rauljordan ?

**Comment by rauljordan** [comment]
We already have a custom `errcheck` analyzer and a `shadowpredecl` analyzer that we use as an alternative, but the default one from golangci-lint checks all cases of if err := shadowing: https://github.com/prysmaticlabs/prysm/tree/develop/tools/analyzers/shadowpredecl

**Comment by estensen** [comment]
Extracting constants doesn't increase readability IMO.

Before
```go
if v.Validator.PublicKey != "0x8931cd39ec3133b6ec91f26eec4de555cd7966086b1993dfe69c2b16e80adc62ce82d353b3356d8cc249e4e2d4254122" {
	field = "PublicKey"
	expected = "0x8931cd39ec3133b6ec91f26eec4de555cd7966086b1993dfe69c2b16e80adc62ce82d353b3356d8cc249e4e2d4254122"
	actual = v.Validator.PublicKey
	break
}
```

After
```go
const (
	publicKey     = "0x8931cd39ec3133b6ec91f26eec4de555cd7966086b1993dfe69c2b16e80adc62ce82d353b3356d8cc249e4e2d4254122"
	publicKeyName = "PublicKey"
)
...
if v.Validator.PublicKey != publicKey {
	field = publicKeyName
	expected = publicKey
	actual = v.Validator.PublicKey
	break
}
```

Progress can be viewed [here](https://github.com/estensen/prysm/commits/lint-action)

**Comment by rkapka** [comment]
I would put these consts right next to their first usage. I think you are extracting them to package-level, no?

**Comment by estensen** [comment]
Some consts, like `public`, `linux` etc are used in multiple functions in multiple files in the same package. And it feels they could live in either file. Maybe extract to `const.go`?

**Comment by estensen** [comment]
`staticcheck` warns about 25 uses of deprecated methods. A lot of them from tests. 
Is there a reason they're stil hanging around?
Should deprecated methods just be ignored by the linter?

```
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go,line=679,col=40::SA1019: req.PublicKeys is deprecated: Do not use.  (staticcheck)
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go,line=685,col=25::SA1019: req.PublicKeys is deprecated: Do not use.  (staticcheck)
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go,line=1355,col=30::SA1019: res.ActivationPublicKeys is deprecated: Do not use.  (staticcheck)
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go,line=1397,col=30::SA1019: res.ExitPublicKeys is deprecated: Do not use.  (staticcheck)
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go,line=1406,col=25::SA1019: res.ExitPublicKeys is deprecated: Do not use.  (staticcheck)
::error file=beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go,line=1457,col=30::SA1019: res.ExitPublicKeys is deprecated: Do not use.  (staticcheck)
::error file=endtoend/evaluators/slashing.go,line=127,col=23::SA1019: duties.Duties is deprecated: Do not use.  (staticcheck)
::error file=endtoend/evaluators/validator.go,line=93,col=14::SA1019: participation.Participation.GlobalParticipationRate is deprecated: Do not use.  (staticcheck)
::error file=shared/bls/blst/bls_benchmark_test.go,line=49,col=7::SA1019: aggregated.AggregateVerify is deprecated: Use FastAggregateVerify or use this method in spectests only.  (staticcheck)
::error file=shared/bls/blst/signature_test.go,line=40,col=24::SA1019: aggSig.AggregateVerify is deprecated: Use FastAggregateVerify or use this method in spectests only.  (staticcheck)
::error file=shared/cmd/password_reader.go,line=6,col=2::SA1019: package golang.org/x/crypto/ssh/terminal is deprecated: this package moved to golang.org/x/term.  (staticcheck)
::error file=shared/promptutil/prompt.go,line=16,col=2::SA1019: package golang.org/x/crypto/ssh/terminal is deprecated: this package moved to golang.org/x/term.  (staticcheck)
::error file=slasher/rpc/server.go,line=224,col=2::SA1019: sl.Slashable is deprecated: Do not use.  (staticcheck)
::error file=slasher/rpc/server.go,line=236,col=2::SA1019: sl.Slashable is deprecated: Do not use.  (staticcheck)
::error file=slasher/rpc/server_test.go,line=178,col=25::SA1019: sl.Slashable is deprecated: Do not use.  (staticcheck)
::error file=spectest/general/phase0/bls/aggregate_verify_test.go,line=61,col=16::SA1019: sig.AggregateVerify is deprecated: Use FastAggregateVerify or use this method in spectests only.  (staticcheck)
::error file=tools/forkchecker/forkchecker.go,line=138,col=25::SA1019: p.VotedEther is deprecated: Do not use.  (staticcheck)
::error file=tools/forkchecker/forkchecker.go,line=139,col=25::SA1019: p.EligibleEther is deprecated: Do not use.  (staticcheck)
::error file=tools/forkchecker/forkchecker.go,line=140,col=25::SA1019: p.GlobalParticipationRate is deprecated: Do not use.  (staticcheck)
::error file=validator/client/attest.go,line=187,col=23::SA1019: v.duties.Duties is deprecated: Do not use.  (staticcheck)
::error file=validator/client/validator.go,line=140,col=17::SA1019: v.validatorClient.WaitForChainStart is deprecated: Do not use.  (staticcheck)
::error file=validator/client/validator.go,line=602,col=23::SA1019: v.duties.Duties is deprecated: Do not use.  (staticcheck)
::error file=validator/client/validator_test.go,line=574,col=57::SA1019: v.duties.Duties is deprecated: Do not use.  (staticcheck)
::error file=validator/client/validator_test.go,line=576,col=18::SA1019: resp.Duties is deprecated: Do not use.  (staticcheck)
::error file=validator/client/validator_test.go,line=577,col=18::SA1019: resp.Duties is deprecated: Do not use.  (staticcheck)
```

**Comment by rauljordan** [comment]
Hi @estensen, some of these are correct that they are deprecated, but still being in use in our codebase. We should audit to check which ones are incorrectly deprecated and if there is a plan to actually stop using them. In the meantime, I would advocate for removing that linter or that SA1019 at least to unblock work. We should open a tracking issue titled something like "Audit Deprecated Uses from Staticcheck Analyzer" so that we can properly resolve that warning

**Comment by estensen** [comment]
I've done a lot of work, but since the codebase is pretty active I fear it's going to be hell trying to merge in the latest changes and review for you.
What about adding one linter at a time and creating one PR each time a linter is added and issues are fixed?
