### ISSUE TITLE
Apple Silicon M1 support?

### ISSUE THREAD

**Issue by paulmillr** [prysmaticlabs/prysm#9385]
### Feature Description

Prysm needs native support for Apple Silicon M1. The chips are extremely efficient and silent.

Currently it seems to be possible to compile AMD64 code for ARM with [Rosetta](https://support.apple.com/en-us/HT211861), which is meh - it's non-native, not as energy-efficient as ARM apps etc.

All clients status:

- Lighthouse: https://github.com/sigp/lighthouse/issues/2329 - compiles and runs, no binaries for now
- Nimbus: https://github.com/status-im/nimbus-eth2/issues/2534 - official darwin-arm64 binaries in test mode
- Prysm: https://github.com/prysmaticlabs/prysm/issues/9385 - we're here
- Teku: https://github.com/ConsenSys/teku/issues/3920 - future plans

**Comment by nisdas** [comment]
@prestonvanloon , how much work would it be to add `darwin_arm64` support ? Go has supported it since 1.16 and for bazel we should have a darwin toolchain that can compile this for us.

**Comment by asanso** [comment]
>Currently it seems to be possible to compile AMD64 code for ARM with Rosetta, 

@paulmillr  may you share a workaround here? I tried Rosetta on M1 and still no luck

**Comment by asanso** [comment]
Adding a patch to update herumi that has now [static binary for M1 mac](https://github.com/herumi/bls-eth-go-binary/commit/7763804ee078a5882d07f91df074c46d15f085b0).

```
diff --git a/go.mod b/go.mod
index 32d08f953..c5c14a309 100644
--- a/go.mod
+++ b/go.mod
@@ -41,7 +41,7 @@ require (
        github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
        github.com/grpc-ecosystem/grpc-gateway/v2 v2.0.1
        github.com/hashicorp/golang-lru v0.5.5-0.20210104140557-80c98217689d
-       github.com/herumi/bls-eth-go-binary v0.0.0-20210130185500-57372fb27371
+       github.com/herumi/bls-eth-go-binary v0.0.0-20210902234237-7763804ee078
        github.com/huin/goupnp v1.0.2 // indirect
        github.com/ianlancetaylor/cgosymbolizer v0.0.0-20200424224625-be1b05b0b279
        github.com/ipfs/go-ipfs-addr v0.0.1
diff --git a/go.sum b/go.sum
index 0ff120a42..db416ce07 100644
--- a/go.sum
+++ b/go.sum
@@ -498,6 +498,8 @@ github.com/hashicorp/memberlist v0.1.3/go.mod h1:ajVTdAv/9Im8oMAAj5G31PhhMCZJV2p
 github.com/hashicorp/serf v0.8.2/go.mod h1:6hOLApaqBFA1NXqRQAsxw9QxuDEvNxSQRwA/JwenrHc=
 github.com/herumi/bls-eth-go-binary v0.0.0-20210130185500-57372fb27371 h1:LEw2KkKciJEr3eKDLzdZ/rjzSR6Y+BS6xKxdA78Bq6s=
 github.com/herumi/bls-eth-go-binary v0.0.0-20210130185500-57372fb27371/go.mod h1:luAnRm3OsMQeokhGzpYmc0ZKwawY7o87PUEP11Z7r7U=
+github.com/herumi/bls-eth-go-binary v0.0.0-20210902234237-7763804ee078 h1:7V5qCWTKJ0T/9KjYo2dBFaIDEb2dvy3onu9nqOIIFDc=
+github.com/herumi/bls-eth-go-binary v0.0.0-20210902234237-7763804ee078/go.mod h1:luAnRm3OsMQeokhGzpYmc0ZKwawY7o87PUEP11Z7r7U=
 github.com/holiman/bloomfilter/v2 v2.0.3 h1:73e0e/V0tCydx14a0SCYS/EWCxgwLZ18CZcZKVu0fao=
 github.com/holiman/bloomfilter/v2 v2.0.3/go.mod h1:zpoh+gs7qcpqrHr3dB55AMiJwo0iURXE7ZOP9L9hSkA=
 github.com/holiman/uint256 v1.2.0 h1:gpSYcPLWGv4sG43I2mVLiDZCNDh/EpGjSk8tmtxitHM=
```

**Comment by nisdas** [comment]
To add on to that, the above patch along with this one will allow `go build` to work
https://gist.github.com/nisdas/a84c92e987611288a07521f459e24e41

So you can build and run prysm using `go` to build . However translating this to bazel will take a bit more work as we will also require the appropriate toolchain for darwin-arm64.

**Comment by asanso** [comment]
Thanks @nisdas  how about committing this 2 patches though at least?

**Comment by prestonvanloon** [comment]
> Thanks @nisdas how about committing this 2 patches though at least?

This sounds good. Please submit a patch for dependency updates to unblock M1 compilation. Cross-compilation will be more involved, but the dependency updates are required in both scenarios.

**Comment by asanso** [comment]
> Please submit a patch for dependency updates

@prestonvanloon  both patches are attached to this issue

**Comment by mrabino1** [comment]
We will probably need to update the prysm.sh script to pull the correct binaries.

**Comment by nisdas** [comment]
@mrabino1 Unfortunately that would require changes to our cross compiler toolchain. What the PR does is allow you to build and run prysm on a M1 using `go build`. However to generate binaries that can be tagged and released will take more work.

**Comment by mrabino1** [comment]
@nisdas gotcha... I am more referencing that the prysm.sh script was modified to pull binaries as a workaround (as it was failing).. today it works.. but not running arm binaries. just the macOS ones... in the future, and if the team wants to support it (e.g the work you are referencing) the prysm.sh script will need to be modified ..

**Comment by nisdas** [comment]
Gotcha, yes that would require a fix to our scripts for it.

**Comment by prestonvanloon** [comment]
Also see https://github.com/prysmaticlabs/prysm/issues/7950 (this issue may be a duplicate)

**Comment by leolara** [comment]
I think the status of this is almost 99% complete with this PR: https://github.com/prysmaticlabs/prysm/pull/10192

**Comment by leolara** [comment]
I think just this is missing: https://github.com/prysmaticlabs/prysm/issues/10263

**Comment by gdistasi** [comment]
Do you think it is going to be ready before the Merge?

**Comment by leolara** [comment]
from https://github.com/prysmaticlabs/prysm/issues/7950#issuecomment-1148656929

[prestonvanloon](https://github.com/prestonvanloon) said:

> the true blocker for this is the cross compilation config.
> 
> For darwin amd64, we run the following
> 
> bazel build --config=osx_amd64_docker  //cmd/beacon-chain //cmd/validator //cmd/client-stats
> We need to establish a osx_arm64_docker config that would produce arm64 binaries.

**Comment by leolara** [comment]
@gdistasi I am not sure, there are many items to takle in implementing cross compilation. But the normal compilation on a M1 works already.

**Comment by tjayrush** [comment]
> @gdistasi I am not sure, there are many items to takle in implementing cross compilation. But the normal compilation on a M1 works already.

Can you point me to instructions on how to do this?

**Comment by prestonvanloon** [comment]
@tjayrush 

If you install M1 native go on your M1 device, you can build Prysm with go like `go build ./cmd/beacon-chain` and it will be compiled for the M1 chip. 

We have also started issuing M1 supported binaries with each release. They are labeled darwin_arm64.

Please DM me if you need more support!

**Comment by gdistasi** [comment]
you can download the binaries for m1, they work
