### ISSUE TITLE
Unable to login via grpc after update to 2.0.0-rc.0

### ISSUE THREAD

**Issue by lukaszsamson** [prysmaticlabs/prysm#9420]
# 🐞 Bug Report

### Description

After validator update to 2.0.0-rc.0 calling Auth.login results in
Authorization token could not be found

### Has this worked before in a previous version?

yes

## 🔬 Minimal Reproduction

Call Auth.login with valid password

## 🔥 Error

<pre><code>
%GRPC.RPCError{message: "Authorization token could not be found", status: 16}
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
2.0.0-rc.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

Most likely broken in https://github.com/prysmaticlabs/prysm/pull/9284/files - service endpoints has changed and authorization exclusion list in https://github.com/prysmaticlabs/prysm/blob/efa1f293110e94195b5fa36b9a77069f383f849f/validator/rpc/intercepter.go#L19 was not updated accordingly

**Comment by rauljordan** [comment]
This is resolved by #9416. Apologies for causing this breaking change
