### ISSUE TITLE
Hello I have a problem. I have active  a node of ethereum 2.0 with prysm beacon. Lately the amount of RAM that the Prysm Beacon service uses is enormous. I have 16 Gb but 90% of it is used by Prysm and it keeps growing until the computer crashes, so I have to manually restart it every 4-5 hours. When I first started running Prysm months ago the amount of RAM was much less. How can I solve that? Is this excessive consumption of RAM memory normal? Thank you.

### ISSUE THREAD

**Issue by victorsl90** [prysmaticlabs/prysm#9429]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
Hi @victorsl90 for faster communication on this, please join us on Discord [here](https://discord.gg/wgpaJdv). We will need more information about your computer and your setup to help us diagnose the problem. In particular, please you can share more details with us about your operating system, hardware (please see our [recommended specifications](https://docs.prylabs.network/docs/install/install-with-script#recommended-specifications)), and wondering if you see any errors in the logs of your computer. Are you running several nodes in a single computer?

**Comment by victorsl90** [comment]
Hi perfect, tomorrow morning I will join the discord channel and give all the details about my problem, thank you very much for helping me.

**Comment by victorsl90** [comment]
Hello @rauljordan , I have already explained my case in detail in the Discord forum, I hope you can help me to solve it. Thank you.

**Comment by victorsl90** [comment]
Mi user name in discord is VSL
