### ISSUE TITLE
Built v1.4.3 but got v2.0.0-rc.0 when checking with ./beacon-chain --version

### ISSUE THREAD

**Issue by agro1986** [prysmaticlabs/prysm#9440]
# 🐞 Bug Report

### Description

 Built v1.4.3 but got v2.0.0-rc.0 when checking with ./beacon-chain --version

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

Always updated minor versions. No problem up until now.

## 🔬 Minimal Reproduction

```
$ git fetch
$ git checkout v1.4.3
$ bazel build //cmd/beacon-chain:beacon-chain --config=release
$ bazel build //cmd/validator:validator --config=release
$ ./bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain --version
beacon-chain version Prysm/v2.0.0-rc.0/8bca66ac6408a03af52d65541f58384007ed50ef. Built at: 2021-08-21 08:29:39+00:00
$ ./bazel-bin/cmd/validator/validator_/validator --version
validator version Prysm/v2.0.0-rc.0/8bca66ac6408a03af52d65541f58384007ed50ef. Built at: 2021-08-21 08:30:15+00:00
```

**Operating System:**

<pre>
  <code>
AWS Linux 2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.4.3
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
hi @prestonvanloon do you know if this is still an issue

**Comment by prestonvanloon** [comment]
Yeah, it is still a bug. If you tried to build a release from v1.4.3 then it would probably report v4.0.2 today

**Comment by prestonvanloon** [comment]
Closing this issue as won't fix since we aren't looking for a workaround.
