### ISSUE TITLE
No syncing anymore and no access to Prysm Pyrmont WebUI - log on to the UI I get the error "Autorization token could not be found"

### ISSUE THREAD

**Issue by success14me** [prysmaticlabs/prysm#9471]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rauljordan** [comment]
No longer an issue as we have changed the web UI to use an auth-token format. This should go away in the next Prysm release
