### ISSUE TITLE
Reinsert All Orphaned Attestations

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#9473]
# 💎 Issue

### Background

In #9442 , we added in the ability to re-insert oprhaned attestations back into the pool. However the change misses some 
edge cases.

### Description

```
100 ->  102 -> 103 (Fork A) 
  \ -> 101 -> 104 (Fork B)
```

If you shift from fork A to fork B, all the attestations at slot 102 get thrown away and are not included in the pool. Only 103 gets re-inserted. While deeper re-orgs are unlikely in mainnet, for correctness purposes we should be reinserting the whole orphaned branch rather than just the previous head block.

**Comment by jinfwhuang** [comment]
I would like to work on this issue if there is no else working on it already.

**Comment by nisdas** [comment]
Hey @jinfwhuang , 

Thanks for the interest ! This has been assigned to you.
