### ISSUE TITLE
Prysm 1.0.17 crashes with runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by VTsuprov** [prysmaticlabs/prysm#9512]
# 🐞 Bug Report

Prysm 1.0.17 crashes with runtime error: slice bounds out of range. The server is dappnode (see below). The Prysm beacon log:

goroutine 49 [running]:
go.etcd.io/bbolt.unsafeByteSlice(...)
	external/io_etcd_go_bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
	external/io_etcd_go_bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x9fff, 0x1)
	external/io_etcd_go_bbolt/cursor.go:328 +0xc5
sort.Search(0xffff, 0xc01d55a620, 0xc0)
	GOROOT/src/sort/search.go:66 +0x58
go.etcd.io/bbolt.(*Cursor).nsearch(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20)
	external/io_etcd_go_bbolt/cursor.go:327 +0x105
go.etcd.io/bbolt.(*Cursor).search(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0x2c437)
	external/io_etcd_go_bbolt/cursor.go:257 +0x1d4
go.etcd.io/bbolt.(*Cursor).searchPage(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0x7fb8c19b5000)
	external/io_etcd_go_bbolt/cursor.go:308 +0x16c
go.etcd.io/bbolt.(*Cursor).search(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0x19b5)
	external/io_etcd_go_bbolt/cursor.go:265 +0x194
go.etcd.io/bbolt.(*Cursor).searchPage(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0x7fb8cccd3000)
	external/io_etcd_go_bbolt/cursor.go:308 +0x16c
go.etcd.io/bbolt.(*Cursor).search(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xccd3)
	external/io_etcd_go_bbolt/cursor.go:265 +0x194
go.etcd.io/bbolt.(*Cursor).searchNode(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xc0272fbc00)
	external/io_etcd_go_bbolt/cursor.go:285 +0x111
go.etcd.io/bbolt.(*Cursor).search(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xfd27)
	external/io_etcd_go_bbolt/cursor.go:262 +0x14f
go.etcd.io/bbolt.(*Cursor).searchNode(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xc0272fb880)
	external/io_etcd_go_bbolt/cursor.go:285 +0x111
go.etcd.io/bbolt.(*Cursor).search(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xbe15)
	external/io_etcd_go_bbolt/cursor.go:262 +0x14f
go.etcd.io/bbolt.(*Cursor).seek(0xc01d55ac70, 0xc01d20dcc0, 0x20, 0x20, 0xce82ae52823687c3, 0x49227a5281f95bd6, 0x6f1cba21f4570d91, 0xcf8a4af7fabe664a, 0x0, 0x0, ...)
	external/io_etcd_go_bbolt/cursor.go:159 +0x7d
go.etcd.io/bbolt.(*Bucket).Get(0xc028fa3d80, 0xc01d20dcc0, 0x20, 0x20, 0xcf8a4af7fabe664a, 0x0, 0x0)
	external/io_etcd_go_bbolt/bucket.go:262 +0xbb
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlocks.func1(0xc0119750a0, 0x1, 0xc0119750a0)
	beacon-chain/db/kv/blocks.go:269 +0x1ae
go.etcd.io/bbolt.(*DB).Update(0xc000d8a200, 0xc028ef8e50, 0x0, 0x0)
	external/io_etcd_go_bbolt/db.go:694 +0x93
github.com/prysmaticlabs/prysm/beacon-chain/db/kv.(*Store).SaveBlocks(0xc000d88180, 0x963118, 0xc017efe840, 0xc025539a40, 0x1d, 0x1d, 0x0, 0x0)
	beacon-chain/db/kv/blocks.go:261 +0x154
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).cacheJustifiedStateBalances(0xc00017f320, 0x963118, 0xc017efe840, 0x340628487cd9fd49, 0x66fd70b16029d61d, 0x880f69d2f628c28, 0x2a8494f01ee98d7, 0x0, 0x0)
	beacon-chain/blockchain/head.go:265 +0xb3
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).updateJustifiedInitSync(0xc00017f320, 0x963118, 0xc017efe840, 0xc00800c370, 0x0, 0x0)
	beacon-chain/blockchain/process_block_helpers.go:218 +0xd6
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).handleBlockAfterBatchVerify(0xc00017f320, 0x963118, 0xc017efe840, 0x970f48, 0xc01d210f50, 0xec28dbd2bc68c659, 0x3f42f77127d7d0da, 0x5e0412a65e291dd6, 0x2cf0866ba17be61f, 0xc00800c3c0, ...)
	beacon-chain/blockchain/process_block.go:298 +0x385
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockBatch(0xc00017f320, 0x963070, 0xc0247d1580, 0xc0247b1400, 0x3f, 0x40, 0xc012ebf000, 0x3f, 0x3f, 0x0, ...)
	beacon-chain/blockchain/receive_block.go:103 +0x308
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks(0xc0194b6380, 0x963070, 0xc0247d1580, 0x0, 0xed7582757, 0x27caa80, 0xc0247b1400, 0x3f, 0x40, 0xc028ef9508, ...)
	beacon-chain/sync/initial-sync/round_robin.go:283 +0x8fb
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData(0xc0194b6380, 0x963070, 0xc0247d1580, 0x0, 0xed7582757, 0x27caa80, 0x1d9b5f, 0xc0272fd560)
	beacon-chain/sync/initial-sync/round_robin.go:133 +0x14f
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch(0xc0194b6380, 0x963070, 0xc0247d1580, 0x0, 0xed7582757, 0x27caa80, 0x0, 0x0)
	beacon-chain/sync/initial-sync/round_robin.go:86 +0x250
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).roundRobinSync(0xc0194b6380, 0x0, 0xed7582757, 0x27caa80, 0x0, 0x0)
	beacon-chain/sync/initial-sync/round_robin.go:49 +0x19e
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).Start(0xc0194b6380)
	beacon-chain/sync/initial-sync/service.go:105 +0x8ba
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
	shared/service_registry.go:46 +0x236
time="2021-09-01 18:37:40" level=warning msg="Running on Ethereum Consensus Mainnet" prefix=flags
time="2021-09-01 18:37:40" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
time="2021-09-01 18:37:40" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
time="2021-09-01 18:38:28" level=info msg="Waiting for state to be initialized" prefix=initial-sync
time="2021-09-01 18:38:28" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.4.2/b3650903ea23b040928732a2bed8b75d584ba903. Built at: 2021-07-21 19:09:23+00:00"
time="2021-09-01 18:38:28" level=info msg="gRPC server listening on port" address="0.0.0.0:4000" prefix=rpc
time="2021-09-01 18:38:28" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
time="2021-09-01 18:38:28" level=info msg="Starting API middleware" API middleware address="0.0.0.0:3501" prefix=gateway
time="2021-09-01 18:38:28" level=info msg="Starting gRPC gateway" address="0.0.0.0:3500" prefix=gateway
time="2021-09-01 18:38:28" level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: eth1 node has not finished syncing yet" prefix=powchain
time="2021-09-01 18:38:33" level=info msg="New gRPC client connected to beacon node" addr="127.0.0.1:34220" prefix=rpc
time="2021-09-01 18:38:52" level=info msg="New gRPC client connected to beacon node" addr="172.33.0.3:34596" prefix=rpc
time="2021-09-01 18:38:57" level=info msg="New gRPC client connected to beacon node" addr="172.33.0.3:34598" prefix=rpc
time="2021-09-01 18:39:09" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
time="2021-09-01 18:39:51" level=info msg="Chain genesis time reached" genesisStateRoot=7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b genesisTime="2020-12-01 12:00:23 +0000 UTC" genesisValidators=21063 prefix=slotutil
time="2021-09-01 18:39:52" level=info msg="Starting initial chain sync..." prefix=initial-sync
time="2021-09-01 18:39:52" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2021-09-01 18:39:52" level=info msg="Started discovery v5" ENR="enr:-LK4QPgNwWaLvN3s9zGjkOmSR09xKUc6KasQ2ILx0AhzWSB8MIOj9aXC86xZ4HRDIqRGSB46GTa7BlWSXgGJt_hLdgsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpC1MD8qAAAAAP__________gmlkgnY0gmlwhKwhAASJc2VjcDI1NmsxoQNkXkLd_7h4x2bf7TTLcipjszamGuBnq5Ei5iqWq4b5xoN0Y3CCMsiDdWRwgi7g" prefix=p2p
time="2021-09-01 18:39:52" level=info msg="Node started p2p server" multiAddr="/ip4/172.33.0.4/tcp/13000/p2p/16Uiu2HAmKQnV7S3XADMP9LJzScTUmxBaPqbWb6pJt5JPrBooGmos" prefix=p2p
time="2021-09-01 18:39:57" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=1
time="2021-09-01 18:40:04" level=info msg="Processing block batch of size 31 starting from  0x9e2ecf1b... 1940225/1974798 - estimated time remaining 6h11m45s" blocksPerSecond=1.6 peers=3 prefix=initial-sync
time="2021-09-01 18:40:32" level=info msg="Processing block batch of size 62 starting from  0xeec42dc7... 1940256/1974800 - estimated time remaining 3h5m43s" blocksPerSecond=3.1 peers=19 prefix=initial-sync
time="2021-09-01 18:40:41" level=info msg="Processing block batch of size 63 starting from  0x59c668bc... 1940320/1974801 - estimated time remaining 1h31m56s" blocksPerSecond=6.2 peers=21 prefix=initial-sync
panic: runtime error: slice bounds out of range [::3950455307] with length 2147483647

### Has this worked before in a previous version?
The system worked well for monthes. Automatic update was disabled. There were no any changes on the server or router. The server crashed suddenly. I tried to restart the server, the router, I updated the Prysm to the last version. The error is still here

## 🌍  My Environment

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.47
dappmanager.dnp.dappnode.eth: 0.2.42, branch: v0.2.43, commit: ec541936
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.7
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 19.03.8
dockerCliVersion: 19.03.8
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.9.0-3-amd64
Disk usage: 41%

Auto diagnose is Ok:
IPFS resolves
Has connected to the internet, and detected own public IP
No ports have to be opened OR the router has UPnP enabled
NAT loopback enabled, external IP resolves
Disk usage is ok (<95%)
All core DAppNode Packages are running

**Comment by prestonvanloon** [comment]
Hi @VTsuprov. We will look into this as soon as possible. I think your database has been corrupted somehow and you'll need to resync from genesis. 

If you could make a copy of `/data/beaconchaindata/beaconchain.db` and share would us, that would be helpful.
In any case, please delete or rename that db file so that Prysm will complete a full resync. 
Removing this file does not remove any slashing protection history.

**Comment by VTsuprov** [comment]
> If you could make a copy of `/data/beaconchaindata/beaconchain.db` and share would us, that would be helpful.
You can upload my corrupted file from here
https://badbugs.me/files/beaconchain.db

I deleted all the data and restarted the syncing process from the genesis. The first 10% of syncing went Ok

**Comment by VTsuprov** [comment]
I have 50% of syncing
But web UI looks strange with errors which should not be linked with the fact that the node has to be yet syncronised
![image](https://user-images.githubusercontent.com/18898852/131902799-42a5f819-cca6-4ca4-b763-c6deba827326.png)

**Comment by VTsuprov** [comment]
Finaly, evrth works. As soon as Prysm syncronised from the genesis I again started to mine. It took around 40 hours to sync 30GB of beacon node. I strongly recomend to do at least a copy of blockchain for Dapnode users.
Thanks  @prestonvanloon for your advise.

**Comment by rauljordan** [comment]
Closing as this seems to be resolved
