### ISSUE TITLE
account backup file order/naming convention don't match 'account list'

### ISSUE THREAD

**Issue by garyng2000** [prysmaticlabs/prysm#9514]
when trying to move a few(not all) validators from one node to another, I try to do a 'backup'(to get the current key pair files), then delete(via the account list)

what I have found is that the keystore files are just a indexed list name which don't match the 'account list' command. so I have to go through every single one to find the corresponding keystore file.

I should probably find the public key from the keystore instead of using the account list, but I think they better be align for easier referencing.

not critical, just FYI

**Comment by james-prysm** [comment]
The CLI commands for prysm account backup and listing were were worked somewhat recently. closing now due to staleness, but can reopen if required.
