### ISSUE TITLE
Bazel toolchain doesn't correctly figure out LLVM name for Suse distributions

### ISSUE THREAD

**Issue by pgagala** [prysmaticlabs/prysm#9515]
# 🐞 Bug Report

### Description

It isn't possible to install Prysm from the source (https://docs.prylabs.network/docs/install/install-with-bazel)
on Suse Linux distributions (leap, tumbleweed).
Bazel toolchain (https://github.com/grailbio/bazel-toolchain) currently doesn't correctly figure out the LLVM name for Suse distributions.

### Has this worked before in a previous version?

Rather not but I didn't check all previous versions of the Bazel toolchain.

## 🔬 Minimal Reproduction
Precondition: Operating system - any of Suse distribution
Type `bazel build //beacon-chain:beacon-chain --config=release` in main Prysm folder.

## 🔥 Error

<pre><code>

➜  prysm git:(develop) bazel build //beacon-chain:beacon-chain --config=release
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository llvm_toolchain instantiated at:
  /home/pgagala/go-projects/src/prysm/WORKSPACE:29:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /home/pgagala/.cache/bazel/_bazel_pgagala/f80ecb809416ccd6b5020a2975b0b48e/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/home/pgagala/.cache/bazel/_bazel_pgagala/f80ecb809416ccd6b5020a2975b0b48e/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/home/pgagala/.cache/bazel/_bazel_pgagala/f80ecb809416ccd6b5020a2975b0b48e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-sles20210714.tar.xz
Please ensure file name is correct.
ERROR: no such package '@llvm_toolchain//': Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-sles20210714.tar.xz
Please ensure the file name is correct.
INFO: Elapsed time: 4.771s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
NAME="openSUSE Tumbleweed"
VERSION="20210714"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210714"
PRETTY_NAME="openSUSE Tumbleweed"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210714"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Version from develop branch commit hash: 95e07963fb920754536f91c4495bce8223f801b0
  </code>
</pre>

**Comment by pgagala** [comment]
PR merged. **0.6** release from https://github.com/grailbio/bazel-toolchain/releases/tag/0.6 should be used in a system in order to fix that issue

**Comment by rkapka** [comment]
cc @prestonvanloon

**Comment by prestonvanloon** [comment]
This is blocked by updating bazel to v4.0.0 then we can update to 0.6 of that toolchain.
