### ISSUE TITLE
/eth/v1/beacon/blocks returns 500

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#9516]
# 🐞 Bug Report

### Description

A call to `/eth/v1/beacon/blocks` (and also `/eth/v1/beacon/headers`) with a valid block root returns a 500 error code.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

Against a pyrmont node:

```
curl -s localhost:3501/eth/v1/beacon/blocks/0x538b7fb164b0b0769995fbc2764651a89f6a5454fd29715097943b9f429b3209
```

## 🔥 Error

<pre><code>
{"message":"Could not get signed beacon block: could not get raw block: unsupported phase0 block","code":500}
</code></pre>

## 🌍  Your Environment

prysm 2.0.0-rc.1

**Comment by rkapka** [comment]
This block is an Altair block, which is not supported by `v1/beacon/blocks`. Headers not working is indeed a bug. This endpoint should support both Phase 0 and Altair.
