### ISSUE TITLE
correctly-insert-orpahned-atts and correctly-prune-canonical-atts increases memory allocations in an extreme way.

### ISSUE THREAD

**Issue by mohamedmansour** [prysmaticlabs/prysm#9523]
I have enabled these in v1.4.4:
```
correctly-insert-orphaned-atts: True
correctly-prune-canonical-atts: True
```

I am seeing excessive CPU usage for beacon:
![image](https://user-images.githubusercontent.com/68524/131974305-cac5f26b-7aea-40e7-aa48-4d1cc5d5f5c2.png)

Golang Rate of Objects Allocated increased from 150K to 2.6M 
![image](https://user-images.githubusercontent.com/68524/131974376-4108a3b7-b112-405f-bb48-2e843e636d9e.png)

And the ssz_snappy experiences some consistent failures
![image](https://user-images.githubusercontent.com/68524/131974432-90f266d1-c3ed-4487-95d2-1d505f96930b.png)

Nothing in the log.

After I disabled:
```
# correctly-insert-orphaned-atts: True
# correctly-prune-canonical-atts: True
```

The top graphs I shared went back to normal, no more  spikes in CPU or memory allocations

**Comment by terencechain** [comment]
Hi @mohamedmansour, thanks for opening this! We dont see this issue on both prater and pyrmont nodes after enabling both flags 12 hours ago. 24 hours screen shots:

Can I help us narrow down:
 - The set of flags your nodes is running?
 - Is the node syncing? or done syncing?
 - Which flag is the problem?
 
![Screen Shot 2021-09-03 at 7 56 40 AM](https://user-images.githubusercontent.com/21316537/132026228-afef9b46-d093-48e3-99e7-c1681b0d652b.png)
![Screen Shot 2021-09-03 at 7 56 17 AM](https://user-images.githubusercontent.com/21316537/132026232-77cd5cd6-75a4-47bc-900a-120e65f4aaa8.png)

**Comment by mohamedmansour** [comment]
@terencechain I added those two parameters to beacon and the charts look like this, notice the spikes (before was previous version of prysm, then during spike and after spike is 1.4.4. The nodes were done syncing.

`((process_cpu_seconds_total{job="$beacon_job"} - process_cpu_seconds_total{job="$beacon_job"} offset 2m) > 0)*100/120/go_maxprocs{job="$beacon_job"}`
![image](https://user-images.githubusercontent.com/68524/132043333-9dbca283-fbee-408a-87b5-44b819a8c298.png)

`rate(go_memstats_mallocs_total[1m])`
![image](https://user-images.githubusercontent.com/68524/132043378-8a63e334-1c94-4768-b8f9-fc4fca5d329f.png)

`rate(go_memstats_alloc_bytes_total[1m])`
![image](https://user-images.githubusercontent.com/68524/132043455-2a10e6bb-ec52-4fb9-83f0-8c9e2e6c3c5d.png)

`node_memory_MemAvailable_bytes`
![image](https://user-images.githubusercontent.com/68524/132043841-f306ef17-4fbf-48af-98de-1163a5fd1fe9.png)


**beacon.yml**

```
mainnet: True
p2p-max-peers: 100
http-web3provider: "/home/ethereum/.ethereum/geth.ipc"
fallback-web3provider:
  - https://mainnet.infura.io/v3/ID
  - https://eth-mainnet.alchemyapi.io/v2/ID
accept-terms-of-use: True
enable-db-backup-webhook: True
db-backup-output-dir: "/ethereum/backups"
enable-optimized-balance-update: True
attestation-aggregation-force-opt-maxcover: True
enable-next-slot-state-cache: True
# correctly-insert-orphaned-atts: True
# correctly-prune-canonical-atts: True
```
**validator**
```
web: True
mainnet: True
accept-terms-of-use: True
attest-timely: True
enable-doppelganger: True
```

**Comment by terencechain** [comment]
> @terencechain I added those two parameters to beacon and the charts look like this, notice the spikes (before was previous version of prysm, then during spike and after spike is 1.4.4. The nodes were done syncing.
> 
> `((process_cpu_seconds_total{job="$beacon_job"} - process_cpu_seconds_total{job="$beacon_job"} offset 2m) > 0)*100/120/go_maxprocs{job="$beacon_job"}`
> ![image](https://user-images.githubusercontent.com/68524/132043333-9dbca283-fbee-408a-87b5-44b819a8c298.png)
> 
> `rate(go_memstats_mallocs_total[1m])`
> ![image](https://user-images.githubusercontent.com/68524/132043378-8a63e334-1c94-4768-b8f9-fc4fca5d329f.png)
> 
> `rate(go_memstats_alloc_bytes_total[1m])`
> ![image](https://user-images.githubusercontent.com/68524/132043455-2a10e6bb-ec52-4fb9-83f0-8c9e2e6c3c5d.png)
> 
> `node_memory_MemAvailable_bytes`
> ![image](https://user-images.githubusercontent.com/68524/132043841-f306ef17-4fbf-48af-98de-1163a5fd1fe9.png)
> 
> **beacon.yml**
> 
> ```
> mainnet: True
> p2p-max-peers: 100
> http-web3provider: "/ethereum/.ethereum/geth.ipc"
> fallback-web3provider:
>   - https://mainnet.infura.io/v3/ID
>   - https://eth-mainnet.alchemyapi.io/v2/ID
> accept-terms-of-use: True
> enable-db-backup-webhook: True
> db-backup-output-dir: "/ethereum/backups"
> enable-optimized-balance-update: True
> attestation-aggregation-force-opt-maxcover: True
> enable-next-slot-state-cache: True
> # correctly-insert-orphaned-atts: True
> # correctly-prune-canonical-atts: True
> ```
> 
> **validator**
> 
> ```
> web: True
> mainnet: True
> accept-terms-of-use: True
> attest-timely: True
> enable-doppelganger: True
> ```

When you have a chance, do you mind trying each of the flag to help us pinpoint which one of the two (maybe both?) is the offender here? Thanks your help as always

**Comment by mohamedmansour** [comment]
@terencechain enabled `correctly-insert-orphaned-atts: True` , will test for an hour and reach back. I am using the following grafana dashboard https://gist.github.com/mohamedmansour/116d09195f0e91aee2591d79547f7d22

So far `correctly-insert-orphaned-atts` is doing good:
![image](https://user-images.githubusercontent.com/68524/132059308-d81bbc42-8777-4190-beeb-0170c764fd6c.png)

**Comment by terencechain** [comment]
Thanks so much @mohamedmansour , I really appreciate you working through this with us

**Comment by mohamedmansour** [comment]
@terencechain  it seems `correctly-insert-orphaned-atts` is normal, when I enable just `correctly-prune-canonical-atts`, the only difference is that the CPU usage went down when `correctly-insert-orphaned-atts: False` and `correctly-insert-orphaned-atts=True`

![image](https://user-images.githubusercontent.com/68524/132077343-ceb1d272-7673-4c86-8f45-5e45b7ce9ad9.png)

I will try with both of them on now. Will report back in few hours.

**Comment by mohamedmansour** [comment]
So I can't reproduce the issue. The issue seems gone, and we cannot be certain it is these flags that is causing the issue. The server only has prysm installed, so after I found the anomalies, after the restart of beacon, it seems to go back to normal

![image](https://user-images.githubusercontent.com/68524/132080738-5393f2de-5538-4335-bb47-eef04a626428.png)

**Comment by terencechain** [comment]
Thanks for the update! Let's keep monitoring this. Please ping us if you see anything. Thanks again for all the detailed testing 

re: expired expectation, good clue, ill look into this

**Comment by terencechain** [comment]
These two metrics will provide more insights: `saved_orphaned_att_total`, `beacon_reorg_total`

**Comment by mohamedmansour** [comment]
@terencechain is there a way to verify if I have the flags on runtime?

**Comment by terencechain** [comment]
> @terencechain is there a way to verify if I have the flags on runtime?

If `saved_orphaned_att_total` is > 0 then you have `correctly-insert-orphaned-atts` on

Not much else you can do besides looking at the startup log :(.  (this is a good feature request though)

**Comment by mohamedmansour** [comment]
Still seems normal while both settings are on for past 4 days
![image](https://user-images.githubusercontent.com/68524/132378726-bec50324-2c23-46ea-a24a-b1389afbff4b.png)

**Comment by terencechain** [comment]
> Still seems normal while both settings are on for past 4 days
> ![image](https://user-images.githubusercontent.com/68524/132378726-bec50324-2c23-46ea-a24a-b1389afbff4b.png)

Thanks for the update!
