### ISSUE TITLE
Validator not able to resume operation after beacon_chain restart

### ISSUE THREAD

**Issue by lukaszsamson** [prysmaticlabs/prysm#9568]
# 🐞 Bug Report

### Description

We run mainnet validator and beacon chain on the same linux machine. Recently we had to restart beacon_chain (to enable `correctly-insert-orphaned-atts`  and `correctly-prune-canonical-atts` flags). The validator was left running during the beacon_chain restart. It was not able to resume normal operation and needed manual restart.

### Has this worked before in a previous version?

I don't have logs anymore but it happened before on 1.3.x

## 🔬 Minimal Reproduction

With active validator and synced beacon_chain running on the same machine
1. stop beacon_chain and wait a bit
2. start beacon_chain
3. observe validator logs

## 🔥 Error

In the logs you can see:

0. normal operation
1. beacon chain stop at 11:15:41
2. validator notices grpc cancellation at 11:15:41
2. beacon_chain start at 11:15:49
3. 11:16:03 - 11:17:15 validator retries grpc calls every ~12s
4. beacon_chain fully synced at 11:17:26
5. 11:17:26 - 11:18:54 no more retries, validator stuck while beacon_chain is working correctly
6. validator restart at 11:18:54
7. situation back to normal

validator log
<pre><code>
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:41" level=error msg="Could not receive blocks from beacon node, could not connect" error="rpc error: code = Canceled desc = Context canceled" prefix=validator
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:41" level=warning msg="block stream interrupted" error="rpc error: code = Canceled desc = Context canceled: could not connect" prefix=validator
Sep 08 11:15:45 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:45" level=error msg="Failed to retrieve blocks stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Sep 08 11:15:45 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:45" level=warning msg="block stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
Sep 08 11:15:49 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:49" level=error msg="Failed to retrieve blocks stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Sep 08 11:15:51 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:51" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Sep 08 11:15:51 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:51" level=warning msg="block stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
Sep 08 11:15:55 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:55" level=error msg="Failed to retrieve blocks stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Sep 08 11:15:55 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:15:55" level=warning msg="block stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
Sep 08 11:16:03 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:16:03" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:16:15 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:16:15" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:16:27 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:16:27" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:16:39 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:16:39" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:16:51 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:16:51" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:17:03 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:17:03" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:17:15 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:17:15" level=error msg="Could not check if validators are exited" error="rpc error: code = Unavailable desc = Syncing to latest head, not ready to respond" prefix=validator
Sep 08 11:18:54 eth2-prod-1a systemd[1]: Stopping Prysm Validator daemon...
Sep 08 11:18:54 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:18:54" level=info msg="Got interrupt, shutting down..." prefix=node
Sep 08 11:18:54 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:18:54" level=info msg="Context canceled, stopping validator" prefix=validator
Sep 08 11:18:54 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:18:54" level=error msg="Could not receive blocks from beacon node, could not connect" error="rpc error: code = Canceled desc = context canceled" prefix=validator
Sep 08 11:18:54 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:18:54" level=info msg="Stopping service" prefix=validator
Sep 08 11:18:54 eth2-prod-1a prysm.sh[12747]: time="2021-09-08 11:18:54" level=info msg="Stopping Prysm validator" prefix=node
Sep 08 11:18:54 eth2-prod-1a systemd[1]: Started Prysm Validator daemon.
</code></pre>

beacon_chain log
<pre><code>
Sep 08 11:15:41 eth2-prod-1a systemd[1]: Current command vanished from the unit file, execution of the command list won't be resumed.
Sep 08 11:15:41 eth2-prod-1a systemd[1]: Stopping Prysm Beacon chain daemon...
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=info msg="Got interrupt, shutting down..." prefix=node
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=info msg="Stopping beacon node" prefix=node
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/voluntary_exit/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/beacon_aggregate_and_proof/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/beacon_attestation_28/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/beacon_attestation_44/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/beacon_attestation_25/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/beacon_block/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/attester_slashing/ssz_snappy"
Sep 08 11:15:41 eth2-prod-1a prysm.sh[12416]: time="2021-09-08 11:15:41" level=warning msg="Subscription next failed" error="context canceled" prefix=sync topic="/eth2/b5303f2a/proposer_slashing/ssz_snappy"
Sep 08 11:15:45 eth2-prod-1a systemd[1]: Stopped Prysm Beacon chain daemon.
Sep 08 11:15:49 eth2-prod-1a systemd[1]: Started Prysm Beacon chain daemon.
Sep 08 11:15:49 eth2-prod-1a systemd[1]: Starting Prysm Beacon chain daemon...
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Latest Prysm version is v1.4.4.
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Beacon chain is up to date.
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Verifying binary integrity.
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: beacon-chain-v1.4.4-linux-amd64: OK
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: gpg: Signature made Wed Sep  1 17:45:16 2021 UTC using RSA key ID F1A5036E
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>"
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: gpg: WARNING: This key is not certified with a trusted signature!
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: gpg:          There is no indication that the signature belongs to the owner.
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Verified /crypto/eth2/dist/beacon-chain-v1.4.4-linux-amd64 has been signed by Prysmatic Labs.
Sep 08 11:15:49 eth2-prod-1a prysm.sh[31919]: Starting Prysm beacon-chain --accept-terms-of-use --http-web3provider=http://10.21.4.17:8545 --fallback-web3provider=http://10.21.4.36:8545 --datadir=/crypto/eth2/datadir --enable-db-backup-webhook --db-backup-output-dir /crypto/eth2/backup/beacon_chain --correctly-insert-orphaned-atts --correctly-prune-canonical-atts
Sep 08 11:15:50 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:50" level=warning msg="Running on Ethereum Consensus Mainnet" prefix=flags
Sep 08 11:15:50 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:50" level=warning msg="Enabled feature flag" correctly-insert-orphaned-atts="This fixes a bug where orphaned attestations don't get reinserted back to mem pool. This improves validator profitability and overall network health,see issue #9441 for further detail" prefix=flags
Sep 08 11:15:50 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:50" level=warning msg="Enabled feature flag" correctly-prune-canonical-atts="This fixes a bug where any block attestations can get incorrectly pruned. This improves validator profitability and overall network health,see issue #9443 for further detail" prefix=flags
Sep 08 11:15:50 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:50" level=info msg="Checking DB" database-path="/crypto/eth2/datadir/beaconchaindata" prefix=node
Sep 08 11:15:50 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:50" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Waiting for state to be initialized" prefix=initial-sync
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.4.4/29d48dfe7eb38959752048aec700f31c3abf7484. Built at: 2021-09-01 16:20:28+00:00"
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Starting API middleware" API middleware address="127.0.0.1:3501" prefix=gateway
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="gRPC server listening on port" address="127.0.0.1:4000" prefix=rpc
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Starting gRPC gateway" address="127.0.0.1:3500" prefix=gateway
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Connected to eth1 proof-of-work chain" endpoint="http://10.21.4.17:8545" prefix=powchain
Sep 08 11:15:51 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:51" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
Sep 08 11:15:52 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:52" level=info msg="Chain genesis time reached" genesisStateRoot=7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b genesisTime="2020-12-01 12:00:23 +0000 UTC" genesisValidators=21063 prefix=slotutil
Sep 08 11:15:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:56" level=info msg="Starting initial chain sync..." prefix=initial-sync
Sep 08 11:15:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:56" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Sep 08 11:15:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:56" level=info msg="Started discovery v5" ENR="enr:-LK4QG4UoPE3GyaPBflgqc44P7qLY3Cb93xqtZj9Ftl3_DizdsOPUZujhha6IHEYYFj137XZbc8YLqRcSpSJ3f-UPCsBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpC1MD8qAAAAAP__________gmlkgnY0gmlwhAoVBByJc2VjcDI1NmsxoQLqGkwmPVEerESo2LLIy2dEp-cb80LL7g4aa6-ygI-oSIN0Y3CCMsiDdWRwgi7g" prefix=p2p
Sep 08 11:15:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:56" level=info msg="Node started p2p server" multiAddr="/ip4/10.21.4.28/tcp/13000/p2p/16Uiu2HAmBBWe1TNtAXwF97v726uAd3uzTihnU7R8ZsPGmKoar9my" prefix=p2p
Sep 08 11:15:57 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:15:57" level=info msg="New gRPC client connected to beacon node" addr="127.0.0.1:47826" prefix=rpc
Sep 08 11:16:02 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:16:02" level=info msg="Processing block batch of size 31 starting from  0x4ca453d6... 2022913/2022978 - estimated time remaining 41s" blocksPerSecond=1.6 peers=11 prefix=initial-sync
Sep 08 11:16:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:16:56" level=info msg="Peer summary" activePeers=44 inbound=0 outbound=44 prefix=p2p
Sep 08 11:16:59 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:16:59" level=info msg="Processing block batch of size 35 starting from  0xdd049b80... 2022944/2022983 - estimated time remaining 22s" blocksPerSecond=1.8 peers=43 prefix=initial-sync
Sep 08 11:17:09 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:09" level=info msg="Synced to finalized epoch - now syncing blocks up to current head" headSlot=2022983 prefix=initial-sync syncedSlot=2022978
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Synced new block" block=0x903b00f8... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022979 slotInEpoch=3
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Synced new block" block=0x8f5bdb49... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022980 slotInEpoch=4
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Finished applying state transition" attestations=99 prefix=blockchain
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Synced new block" block=0x46eab2cf... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022981 slotInEpoch=5
Sep 08 11:17:10 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:10" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:17:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:11" level=info msg="Synced new block" block=0x3a1bde44... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022982 slotInEpoch=6
Sep 08 11:17:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:11" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:17:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:11" level=info msg="Synced new block" block=0x5f368542... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022983 slotInEpoch=7
Sep 08 11:17:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:11" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:17:26 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:26" level=info msg="Synced to head of chain" headSlot=2022985 prefix=initial-sync syncedSlot=2022983
Sep 08 11:17:26 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:26" level=info msg="Synced up to slot 2022983" prefix=initial-sync
Sep 08 11:17:31 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:31" level=info msg="Synced new block" block=0xc5643fe9... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022984 slotInEpoch=8
Sep 08 11:17:31 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:31" level=info msg="Finished applying state transition" attestations=79 prefix=blockchain
Sep 08 11:17:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:35" level=info msg="Synced new block" block=0xe874d40e... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022985 slotInEpoch=9
Sep 08 11:17:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:35" level=info msg="Finished applying state transition" attestations=57 prefix=blockchain
Sep 08 11:17:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:35" level=info msg="Synced new block" block=0x93fcc436... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022986 slotInEpoch=10
Sep 08 11:17:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:35" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:17:47 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:47" level=info msg="Synced new block" block=0x4f401429... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022987 slotInEpoch=11
Sep 08 11:17:47 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:47" level=info msg="Finished applying state transition" attestations=60 prefix=blockchain
Sep 08 11:17:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:56" level=info msg="Peer summary" activePeers=46 inbound=0 outbound=46 prefix=p2p
Sep 08 11:17:59 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:59" level=info msg="Synced new block" block=0x9a10f50d... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022988 slotInEpoch=12
Sep 08 11:17:59 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:17:59" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:18:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:11" level=info msg="Synced new block" block=0x28994291... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022989 slotInEpoch=13
Sep 08 11:18:11 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:11" level=info msg="Finished applying state transition" attestations=77 prefix=blockchain
Sep 08 11:18:27 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:27" level=info msg="Synced new block" block=0xb8d7e3b7... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022990 slotInEpoch=14
Sep 08 11:18:27 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:27" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:18:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:35" level=info msg="Synced new block" block=0x98f78550... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022991 slotInEpoch=15
Sep 08 11:18:35 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:35" level=info msg="Finished applying state transition" attestations=128 prefix=blockchain
Sep 08 11:18:47 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:47" level=info msg="Synced new block" block=0xb879f167... epoch=63218 finalizedEpoch=63216 finalizedRoot=0xe0ee654b... prefix=blockchain slot=2022992 slotInEpoch=16
Sep 08 11:18:47 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:47" level=info msg="Finished applying state transition" attestations=64 prefix=blockchain
Sep 08 11:18:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:56" level=info msg="Peer summary" activePeers=43 inbound=0 outbound=43 prefix=p2p
Sep 08 11:18:56 eth2-prod-1a prysm.sh[31919]: time="2021-09-08 11:18:56" level=info msg="New gRPC client connected to beacon node" addr="127.0.0.1:47936" prefix=rpc
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
aws linux 2
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.4.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
Did this issue resolve? It seems that your beacon node was synced at 11:17:26 and the validator connection failure logs stopped at that time too. The validator was stopped about 90s later at 11:18:54. 

Did you miss any attestation? It seems like the validator did connect successfully to the beacon node.

**Comment by lukaszsamson** [comment]
> Did you miss any attestation during that 90s?

No

> It seems like the validator did connect successfully to the beacon node

If it if fact did reconnect, I'd expect some info level log message confirming that, e.g. Validator activated or Attestation schedule

**Comment by terencechain** [comment]
closing this as there hasn't been any follow-up for ~100 days. Feel free to open this issue, and we can reopen the investigation again
