### ISSUE TITLE
Regularly (approx. every 2 days) attestations are missed (DeadlineExceeded)

### ISSUE THREAD

**Issue by mondsen** [prysmaticlabs/prysm#9596]
# 🐞 Bug Report

### Description

**Problem statement:** my node is missing attestations on a regular basis. Approx. every 2 days one of my validators misses an attestation. 

I did not had these issues in the past and it got worse with the latest update to 1.4.4 to which I updated September 2nd. I only had 3 missed attestations in August, but already 7 in September and there is still half a month to go... 

I checked with the existing issues but can't see that those are related. For example, I am running on a dedicated host with 4 Ryzen CPUs and see no CPU spikes. Total CPU utilization is always below 10%. On my node, I am running the beacon-node and 2 validators. Nothing more. 

I also checked if it might be related to time sync issues, but my NTP is running fine and I don't see a problem there either. 

I also reduced the amount of peers connected, but nothing changed. 

**Parameters:**
beacon-chain.yaml
```datadir: /home/xxx/prysm/data
accept-terms-of-use: true
log-file: /home/xxx/prysm/logs/beaconchain.log
http-web3provider: https://mainnet.infura.io/v3/xxxxx
p2p-host-ip: "xxxx"
#p2p-max-peers: 70
fallback-web3provider: 
  - https://eth-mainnet.alchemyapi.io/v2/xxx
```
validator.yaml
```log-file: /home/xxx/prysm/logs/validator.log
wallet-password-file: /home/xxx/prysm/walletpassword
graffiti: "xxx"
enable-duty-count-down: true
```

## 🔥 Error

I can see these error types, where "Could not submit..." is the most frequent (the other one only appeared once)

<pre><code>
[2021-09-02 15:07:23] ERROR validator: Could not request attestation to sign at slot error=rpc error: code = DeadlineExceeded desc = context deadline exceeded pubKey=0x994d552b4f80 slot=1980334

[2021-09-09 16:21:07] ERROR validator: Could not submit attestation to beacon node error=rpc error: code = DeadlineExceeded desc = context deadline exceeded pubKey=0x994d552b4f80 slot=2031102
</code></pre>

## 🌍  Your Environment

**Operating System:**
**Host:**
- dedicated root VM with 4 CPUs (non-shared) and 
- 16 GB RAM
- Ubuntu 20.04.3 LTS with latest updates

**What version of Prysm are you running? (Which release)**
v1.4.4

**Comment by terencechain** [comment]
Does this issue persist? 

I will close this since there hasn't been any follow-up for ~100 days. Feel free to open this issue, and we can reopen the investigation again
