### ISSUE TITLE
Missing block proposal due to StateBySlot() / StateByRoot()

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9612]
# 💎 Issue

### Background

As part of debug session for the `GetBlock()` optimisation, this issue was found and needs to be looked in to.

### Description

**stategen->StateBySlot() / StateByRoot()**

- This was observed few times that the loadStateByRoot() takes several seconds and the proposal will be lost. Bolt might be the culpreit here as it might take time to get state that is not in hoStateCache or the epochCache. The **second major time saving** in this track is this fix. 

![](https://i.imgur.com/6qQaUiM.png)

**Comment by terencechain** [comment]
Let's refer to #9708
