### ISSUE TITLE
Mising skipClotCache

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9613]
# 💎 Issue

### Background

As part of debug session for the `GetBlock()` optimisation, this issue was found and needs to be looked in to.

### Description

**computeStateRoot->CalculateStateRoot->ProcessSlots()**

- **skipSlotCache.Get()** - This is the most strangest one. skipSlotCache is a simle cache and its get takes more than a second. The only reason i can think is that the lock inside Get() is held by someone for a far more long time.
- **scenario 1** 
![](https://i.imgur.com/kN0h0lU.png)
- **scenario 2**
![](https://i.imgur.com/PjM1TRz.png)

**Comment by terencechain** [comment]
Let's refer to #9708
