### ISSUE TITLE
HashTree taking more time

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9614]
# 💎 Issue

### Background

As part of debug session for the `GetBlock()` optimisation, this issue was found and needs to be looked in to.

### Description

It is observed that the hashing algorithm is taking some time  to calculate the root. The VM had support for AVX2 and AVX512. May be the hypervisor didnt allow SIMD instruction set, i am not sure of that. But this happens in this setup. This is very siilar to what was captured by potus and Nishant  [here](https://github.com/prysmaticlabs/prysm/issues/9389), but it might be different.

- **scenario 1**
![](https://i.imgur.com/8SZBMeJ.png)
- **scenario 2**
![](https://i.imgur.com/mkOCVYf.png)

**Comment by terencechain** [comment]
Let's refer to #9708
