### ISSUE TITLE
Installation Documentation has incorrect instructions for slasher

### ISSUE THREAD

**Issue by jgilbs** [prysmaticlabs/prysm#9628]
# Slasher Documentation is inaccurate

### Background

In the future, it is expected that slasher functionality will move from a dedicated binary to a command line argument to the beacon-chain binary.  This change is expected with v2.0.0, coinciding with the Altair upgrade.  As part of this change, public facing client documentation will need to be updated.

### Description

I have found several errors in documentation that should be addressed prior to the v2.0.0 release

1. Currently, the guide at https://docs.prylabs.network/docs/prysm-usage/slasher/ indicates that one should simply add --slasher to the beacon node command line arguments to active a slasher.  However, as of c2.0.0-rc.0, this command line flag is inaccurate and using it causes `"ERR0[0000] flag provided but not defined: -slasher  prefix-main"  `  It appears that the documentation is referencing a future state which is not yet correct.  Documentation should be caveated with this information.

2. This same page also references an invalid command line switch for slashing protection at the validator `--enable-external-slashing-protection` but this command line switch as implemented in the validator is actually `--enable-external-slasher-protection`

**Comment by rauljordan** [comment]
Hi @jgilbs thanks for bringing this up. Our docs seem to be ahead of our code. Slasher will be available in release v2.0.0 or v2.0.1. Our plan for improving our docs involves adding documentation versioning, which will help with this problem. I will amend the current docs to resolve this issue for now.
