### ISSUE TITLE
UpdateAncestorHashes is unused 

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#963]
This is not called from the beacon-chain main package.

Can it be deleted?

https://github.com/prysmaticlabs/prysm/blob/391eacd1d725aa6e16f15fee2a0ae0862506dd3e/beacon-chain/types/block.go#L237-L247

Found by [codecoroner](https://github.com/3rf/codecoroner)

**Comment by terenc3t** [comment]
This is part of the helper function which is waiting to get used for #712. I'll add a TODO
