### ISSUE TITLE
Slashing protection import fails silently if `validator.db` is not found

### ISSUE THREAD

**Issue by michaelsproul** [prysmaticlabs/prysm#9665]
# 🐞 Bug Report

### Description

The slashing protection import CLI fails silently if the validator database directory exists but doesn't contain a validator database.

## 🔬 Minimal Reproduction

Import a slashing protection file into an empty directory (`/path/to/empty-directory`):

```bash
$ ./validator-v1.4.4-linux-amd64 slashing-protection import --pyrmont --slashing-protection-json-file slashing-protection.json
[2021-09-24 09:33:14]  WARN flags: Running on Pyrmont Testnet
Enter the directory of the validator database you would like to use (default: /home/michael/.eth2):
/path/to/empty-directory
$ echo $status
0
```

I think in this case the CLI should print an error, as it does in the case where the directory doesn't exist at all:

```
$ ./validator-v1.4.4-linux-amd64 slashing-protection import --pyrmont --slashing-protection-json-file jankus.json
[2021-09-24 09:39:22]  WARN flags: Running on Pyrmont Testnet
Enter the directory of the validator database you would like to use (default: /home/michael/.eth2):
/tmp/notreal
[2021-09-24 09:39:27] ERROR main: err finding validator database at path /tmp/notreal: lstat /tmp/notreal: no such file or directory
$ echo $status
0
```

(the exit code should probably be non-zero, but that's a separate issue)

## 🌍  Your Environment

- Ubuntu 21.04
- Prysm v1.4.4: `validator version Prysm/v1.4.4/29d48dfe7eb38959752048aec700f31c3abf7484. Built at: 2021-09-01 16:20:28+00:00`

**Comment by nisdas** [comment]
Hey @michaelsproul , 

Thanks for the report, this should be fixed by #9355, @rauljordan can confirm. Unfortunately that did not make it into v1.4.4, so any user facing this would have to wait for our v2 release. If they really do want to export it, they can run our v2 release candidates which has the fix in them. I will leave this open till will have our official v2 release.

**Comment by michaelsproul** [comment]
Awesome, thanks @nisdas! I was wondering if it would turn out to be something like that, thanks for the prompt reply 😊

**Comment by rauljordan** [comment]
Confirmed this one is indeed resolved. If issue still surfaces for any reason after v2 release of Prysm (next Monday), we'll definitely reopen! Thanks @michaelsproul
