### ISSUE TITLE
Bazel CI pipeline

### ISSUE THREAD

**Issue by jinfwhuang** [prysmaticlabs/prysm#9681]
# 🚀 Bazel CI pipeline in github action

### Description

The repo uses Bazel as the primary build tool, but the repo's CI pipeline doesn't seem to run any of the bazel targets. Running the Bazel tests will enforce Bazel tooling setups are setup correctly. The automatically run Bazel commands are also useful starting places for new users to understand how Bazel toolings work.

### Describe the solution you'd like

Create a **Bazel** github action

### Describe alternatives you've considered

n/a

**Comment by jinfwhuang** [comment]
It looks like that there are already plenty of Bazel CI pipelines that are configured in `buildkite`. That could make this issue irrelevant. 

However, if I am not mistaken, it looks like that `buildkite` is configured outside of this repo. That is, the buildkite jobs are not configured in the monorepo similar to how github workflows are configured in code. If that is the case, it might still be useful to have some limited CI pipeline that are recorded and managed in some files within this repo.

**Comment by prestonvanloon** [comment]
Hey @jinfwhuang, thanks so much for this report! Indeed, we use buildkite for our continuous integration pipeline and require many bazel operations to pass before a PR can merge. 

Buildkite does support reading the pipeline steps from the repository, so that is something we could do. I'll look into this topic next week, after v2 is released.

**Comment by jinfwhuang** [comment]
Feel free to enlist my help when you start looking at it. I am looking for opportunities to get my hands dirty with this repo.

**Comment by prestonvanloon** [comment]
Closing old issue. We do not plan to integration more of our CI into github actions or define steps within the Prysm repo.
