### ISSUE TITLE
`config/spec` api call doesn't return altair preset

### ISSUE THREAD

**Issue by pawanjay176** [prysmaticlabs/prysm#9686]
# 🐞 Bug Report

### Description

The `config/spec` api call isn't returning the `MIN_SYNC_COMMITTEE_PARTICIPANTS` altair preset field. This was reported by a user on discord when trying to use prysm beacon with lighthouse vc on prater.

## 🔥 Error

Error on Lighthouse vc when trying to parse call to `config/spec`
```
Error("missing field `MIN_SYNC_COMMITTEE_PARTICIPANTS`")
```

## 🌍  Your Environment

<pre>
  <code>
Prysm/v2.0.0-rc.2 (linux amd64)
  </code>
</pre>

**Comment by rkapka** [comment]
Hi @pawanjay176 , thanks for submitting the issue.

`MIN_SYNC_COMMITTEE_PARTICIPANTS` is not specified in either of the constant listings:
https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#constants
https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/beacon-chain.md#constants

It's also not a known constant in our whole codebase. I appears like it should not be present in Lighthouse.

**Comment by rkapka** [comment]
If I'm not mistaken, sync committee size is constant, so a minimum does not make much sense. We already have `SYNC_COMMITTEE_SIZE`. This needs some more investigation.

**Comment by pawanjay176** [comment]
@rkapka Seems like the preset is used in the light client sync [protocol](https://github.com/ethereum/consensus-specs/blob/2c632c0087f0a692ab74987229524edbb941eeb3/specs/altair/sync-protocol.md#misc)

The beacon api https://ethereum.github.io/beacon-APIs/#/Config/getSpec says that we should include all the config constants as well as the presets
> Retrieve specification configuration used on this node. The configuration should include:
- Constants for all hard forks known by the beacon node, for example the phase 0 and altair values
- Presets for all hard forks supplied to the beacon node, for example the phase 0 and altair values
