### ISSUE TITLE
UDP/Tor Support: The Hidden Service for the Serenity

### ISSUE THREAD

**Issue by shogochiai** [prysmaticlabs/prysm#971]
Serenity would use libp2p, and UDP would be omitted. So, is there any plan to add Tor support for Ethereum?

Relevant topics
In Parity
https://github.com/paritytech/parity-ethereum/issues/6460

In BitcoinABC
https://github.com/Bitcoin-ABC/bitcoin-abc/issues/117

**Comment by rauljordan** [comment]
Hi @shogochiai no concrete plans at the moment, but this would seem like a good and useful feature to have. @prestonvanloon perhaps can shed more light on our libp2p configuration. We are currently planning on creating a testnet where some nodes will be behind NAT and can receive inbound connections via a libp2p relay node, but haven't taken a deeper look on privacy-related options such as Tor.

**Comment by prestonvanloon** [comment]
Hey @shogochiai, the current plan is to leverage libp2p supported transports. If libp2p plans to support it then we'll support it as well.

Check out their [roadmap](https://docs.google.com/document/d/1Rd4yNw1TNQBvfRrKeEMSTseb6fvPzS-C--obOn0nul8/edit?usp=sharing) and follow https://github.com/libp2p/go-libp2p/issues/353 for updates on UDP support in libp2p.

**Comment by prestonvanloon** [comment]
For the record, I would really like to adopt this for Prysm. Let's leave this issue open while the libp2p team makes progress on their 2019 roadmap and potential support for UDP transport.

**Comment by cartercarlson** [comment]
(First time contributor) I don't have a ton of experience with Tor, but my impression is that with Tor you are going through a series of routers.  All of the extra paths would impact your network latency, which may cause issues if you're trying to run a validator node.

**Comment by shogochiai** [comment]
FYI: I believe this is a relevant topic (without Tor).

https://ethresear.ch/t/anonymity-a-zkp-to-remove-the-mapping-ip-address-wallets-public-key-of-a-validator/6049

**Comment by rauljordan** [comment]
@nisdas is this something in scope for us or does this need to be a change done in libp2p itself? If so, we can perhaps close this issue as we cannot resolve it ourselves

**Comment by prestonvanloon** [comment]
This would require changes in libp2p and Prysm. 

Some people are working on this idea: https://github.com/berty/go-libp2p-tor-transport

**Comment by nisdas** [comment]
@rauljordan The main changes will have to be done at the base transport level which would be in libp2p. Also a preston mentioned there would need to be quite a few changes in prysm itself too to allow the possibility of running something like this.

**Comment by 0xKiwi** [comment]
Closing until the situation for this feature changes on libp2ps side.
