### ISSUE TITLE
Invalid validator balances for v1 endpoints

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#9721]
# 🐞 Bug Report

### Description

`/eth/v1/beacon/states/{state_id}/validators` and `/eth/v1/beacon/states/{state_id}/validator_balances` endpoints always return 32 ETH balances for the active validators.

## 🔬 Minimal Reproduction

I've tried requesting the same data from Infura Teku and local Prysm and received different responses for the same slot number. The teku nodes returned balances together with the rewards, but prysm nodes returned effective balances (32 ETH).

Running Prysm `1.4.4`

**Comment by prestonvanloon** [comment]
@rkapka is this issue still valid in v2.0.0 @ 4f31ba648977a00668cafa10bc3aa93f41fbe31e?
