### ISSUE TITLE
API queries for more than 256 blocks behind  time out

### ISSUE THREAD

**Issue by tsudmi** [prysmaticlabs/prysm#9724]
# 🐞 Bug Report

### Description

I've tried querying the validators data (`/eth/v1/beacon/states/{state_id}/validator`) using both gRPC and REST API endpoints for more than 256 slots (8 epochs) behind and they time out.

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

Running Prysm `1.4.4`

**Comment by rkapka** [comment]
Hi @tsudmi , thanks for reporting this. Did you try it on a freshly synced node, or one that has been running for some time?

**Comment by rkapka** [comment]
Hey @tsudmi , the flag will have impact on saving states from the point when the flag is applied onward. So you won't be able to quickly fetch states from before running the node with the new value. I hope this explanation is not too convoluted :-)
