### ISSUE TITLE
CORs Error for 2.0.0 release

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#9736]
# 🐞 Bug Report

### Description

v2 upgrade is causing cores issue

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was: 1.4.4

## 🔬 Minimal Reproduction

running http://127.0.0.1:3500/eth/v1alpha1/node/genesis api

## 🔥 Error
<pre>
  <code>
Access to fetch at 'http://127.0.0.1:3500/eth/v1alpha1/node/genesis' from origin 'http://127.0.0.1:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
  </code>
</pre>

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
2.0.0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by rkapka** [comment]
Fixed in #9732
