### ISSUE TITLE
Validator data dir is set in a frustrating way

### ISSUE THREAD

**Issue by jimpo** [prysmaticlabs/prysm#9739]
# 💎 Issue

Data dir is inconsistent between commands. Some CLI commands don't allow it as an argument and use the default (eg. `validator wallet create`) when checking TOS. Therefore I'm forced to use the default datadir location. Then when you run the validator, it changes the data dir to somewhere inside the wallet dir, even when passed the --datadir arg! (See https://github.com/prysmaticlabs/prysm/blob/develop/validator/node/node.go#L202)

### Background

I just want to run the sequence of CLI commands:

```bash
validator wallet create ...
validator slashing-protection import ...
validator ...
validator slashing-protection export ...
 ```

and due to the inconsistencies in data dir CLI management resulting from [this logic](https://github.com/prysmaticlabs/prysm/blob/develop/validator/node/node.go#L202), I can't do that without renaming my data dir between commands or symlinking or some other trickery.

**Comment by prestonvanloon** [comment]
@jimpo, this seems like an oversight in some of the validator commands. We should fix this soon to improve the user experience of validator wallet and db management. Thanks for filing.
