### ISSUE TITLE
UI sanity testing in e2e

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#9744]
# 🚀 Feature Request

### Description

Prysm UI has suffered from multiple critical issues in new releases such as the UI not serving at all, CORS issues, etc. 

I started some work in #8981, but it turned stale and will need to be reworked.

### Describe the solution you'd like

- Add selenium based e2e testing for the UI.
- Update CI runners to have a headless chrome browser
- Add more testing of the basic user flow to ensure the most critical functionality works as expected

### Describe alternatives you've considered

None.

**Comment by james-prysm** [comment]
Probably isn't needed anymore for this, unless we figure out what we want to do with web ui going forward.
