### ISSUE TITLE
Remote signer in e2e

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#9745]
# 🚀 Feature Request

### Description

Prysm has client support for validator remote signing, but there is a clear testing gap between the [reference implementation of the remote signer server](https://github.com/prysmaticlabs/remote-signer). At a minimum, Prysm's e2e tests should include the reference implementation in end to end testing to ensure there is no breakage between releases.

### Describe the solution you'd like

- Include remote signer component to some, but not all, of the validator components in e2e tests

### Describe alternatives you've considered

None

**Comment by james-prysm** [comment]
closing issue since web3signer is already added as a scenario test and proposing deprecation of Prysm Remote Signer features https://github.com/prysmaticlabs/prysm/issues/11700
