### ISSUE TITLE
Prysm validator (post-merge) support for multiple override fee recipient addresses based on multiple validators

### ISSUE THREAD

**Issue by mrabino1** [prysmaticlabs/prysm#9757]
### Description

Post "merge", the validator when selected to propose a block will override the execution clients coinbase address using one from the validator to have all applicable transaction fees go to that address. 

Challenge: Many node operators that are running multiple validators are not the economic beneficiary of the validator. 

### Describe the solution you'd like

Similar to how Prysm has implemented a YAML for graffiti (https://docs.prylabs.network/docs/prysm-usage/graffiti-file)

It is recommended to use a parameter for the validator process to link to a coinbase.yaml where we would indicate the directed coinbase override address based on the validator index.

e.g. 

specific:
  163: "0xA090e606E30bD747d4E6245a1517EbE430F0057e"
  914: "0xA090e606E30bD747d4E6245a1517EbE430F0057e"
  546: "0xb5d85cbf7cb3ee0d56b3bb207d5fc4b82f43f511"
  237: "0x678467B755983d3087336D2326cB273D33e0F350"
default: "0x678467B755983d3087336D2326cB273D33e0F350"

----
(note: the above addresses were just randomly selected)

Based on the above, the economic association could be seen that index 163 & 914 are owned by the same person but not the node operator.. and 546 is not related to anyone.. and 237 and the node operator are the same..

----

TBD, if no address is provided (nor a default) in the yaml, the validator should default to send the coinbase proceeds to the withdrawal address.

**Comment by mcdee** [comment]
Would this be better as an addition to the beacon node API, where the validator client can pass the desired coinbase along with its block proposal request (or a pre-proposal request)?  The beacon node is going to need some sort of nudge from the validator client to know when to tell the execution client to prepare the payload, after all.

**Comment by mrabino1** [comment]
Looks like we need to replace coinbase in this thread with fee_recipient to conform to the CL specs.

**Comment by mcdee** [comment]
Note also https://github.com/ethereum/beacon-APIs/pull/178 which contains details of the standard API endpoint and its operation.

**Comment by prestonvanloon** [comment]
> Looks like we need to replace coinbase in this thread with fee_recipient to conform to the CL specs.

Also done in #9918

**Comment by kanewallmann** [comment]
@terencechain was this closed because it was implemented? Is it possible to set a fee recipient on a per validator basis with Pyrsm or is this issue being tracked elsewhere?

**Comment by potuz** [comment]
> @terencechain was this closed because it was implemented? Is it possible to set a fee recipient on a per validator basis with Pyrsm or is this issue being tracked elsewhere?

This was closed because we are forced to follow whatever the spec says about this. In the current design for the API endpoint this is specified close to what the OP requested, but it is still open, you can follow the link posted above by @mcdee

**Comment by kanewallmann** [comment]
@potuz correct me if I'm wrong, but it seems like this spec is only a matter of how a VC could tell a BN which fee recipient to use. It still requires the VC to support a per validator fee recipient which would be a VC implementation decision not one forced by the spec.

e.g. a VC could have a single fee recipient config for all validator accounts and submit that value to every call to prepare_beacon_proposer. There's nothing in the spec forcing the VC to maintain a mapping of validator accounts to fee recipients.

This feature request requires that functionality in the spec, but having this functionality in the spec doesn't guarantee this feature request will be implemented in Prysm.

**Comment by potuz** [comment]
> @potuz correct me if I'm wrong, but it seems like this spec is only a matter of how a VC could tell a BN which fee recipient to use. It still requires the VC to support a per validator fee recipient which would be a VC implementation decision not one forced by the spec.
> 
> e.g. a VC could have a single fee recipient config for all validator accounts and submit that value to every call to prepare_beacon_proposer. There's nothing in the spec forcing the VC to maintain a mapping of validator accounts to fee recipients.
> 
> This feature request requires that functionality in the spec, but having this functionality in the spec doesn't guarantee this feature request will be implemented in Prysm.

This is correct, what I meant is that not long ago this feature would have been impossible since it was being considered that only the EL would set the fee recipient. As soon as this is settled surely this will be implemented if this this is compatible with the spec (and it looks that it will be)
