### ISSUE TITLE
`/eth/v1/validator/duties/attester/<epoch>` panics when a validator is inactive

### ISSUE THREAD

**Issue by moshe-blox** [prysmaticlabs/prysm#9773]
Hi 😄

I'm using Prysm to query duties (because it's the quickest 👍), and I encountered a case where it panics (though the client doesn't crash).

# 🐞 Bug Report

### Description

When querying the duties of multiple validators, if only one of them is inactive (has exited or has an activation epoch > queried epoch), then the query panics.

This is in contrast with Teku & Lighthouse which discard the inactive validators and proceed to return the duties of the active ones.

## 🔬 Minimal Reproduction

```
curl --request POST \
  --url http://<prater-prysm-node>/eth/v1/validator/duties/attester/42058 \
  --header 'Content-Type: application/json' \
  --data '["215536", "215535"]'
```

This request queries the attester duties of two validators at epoch `42058` on `prater`:

- Validator `215536` is active
- Validator `215535` was exited an epoch ago (this one causes the panic)

## 🔥 Error

```json
{
  "message": "runtime error: invalid memory address or nil pointer dereference",
  "code": 500
}
```

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 64-bit
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm/v2.0.1 (linux amd64)
  </code>
</pre>

**Comment by rkapka** [comment]
Hi @moshe-blox , thanks a lot for reporting this! I already have a fix ready in #9780. Next release of Prysm will have this change incorporated.
