### ISSUE TITLE
/eth/v2/validator/blocks returning error

### ISSUE THREAD

**Issue by mcdee** [prysmaticlabs/prysm#9787]
# 🐞 Bug Report

### Description

Attempting to fetch a block using the `/eth/v2/validator/blocks` endpoint returns an error when there are deposits expected.

### Has this worked before in a previous version?

Unsure.  It appears that if there are no outstanding deposits then this operation completes successfully.

## 🔬 Minimal Reproduction

GET the following endpoint on prater:

```
/eth/v2/validator/blocks/1488736?randao_reveal=0xa77ab0d077903ccb6e20a53e20f10d73185e099a943af31acab53265e97787288747529f982d74f4365b6eb730e3e81613c044a50caecb62db7af9a023a317de2433294f40824fd888308f69eef860dc326d5ec9810977ab25d2b0a1bba00b88&graffiti=0x0000000000000000000000000000000000000000000000000000000000000000
```

## 🔥 Error

<pre><code>
{
  "message": "Could not fetch Altair beacon block: could not compute state root: could not calculate state root at slot 1488735: could not process block: could not process block operation: could not verify operation lengths: incorrect outstanding deposits in block body, wanted: 16, got: 0",
  "code": 500
}
</code></pre>

## 🌍  Your Environment

`develop``

**Comment by rkapka** [comment]
https://discord.com/channels/476244492043812875/550365651118850081/904686597864316949

My node proposed a block (without broadcasting) for a week, during which there were blocks with 16 and less deposits, and did not encounter any issues.

**Comment by prestonvanloon** [comment]
Is this consistently reproducible with vouch? 

This error can manifest any time that blocks are required to have deposits and the eth1 node connection is offline. I wonder if this is what happened to @mcdee.

**Comment by rkapka** [comment]
This has been already discussed on Discord. Although we cannot exclude this possibility, there are no visible evidence that this happened.

**Comment by mcdee** [comment]
Yeah, nothing to suggest that the ETH1 connection was down at the time.

This issue has not recurred on mainnet so far.

**Comment by rkapka** [comment]
Let's keep this issue open for 2 more weeks. If the issue problem not surface again, I will close it.

**Comment by mcdee** [comment]
I have just seen what is likely the same issue on prater:

```
{
  "message": "Could not fetch Altair beacon block: could not compute state root: could not calculate state root at slot 1742082: invalid sync committee signature",
  "code": 500
}
```

**Comment by potuz** [comment]
This looks different as validating signatures and deposit count are in very different paths
