### ISSUE TITLE
Validate beacon blocks test case passing for wrong reasons

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9791]
# 🐞 Bug Report

### Description

In the file `validate_beacon-locks-test.go`, few test cases are passing for the wrong reasons.
Ex: `TestValidateBeaconBlockPubSub_InvalidSignature`, the validation check at the end checks for `validationReject`, but it is not checking if the reject is for the right reason, which in this case is Invalid signature. The `validationReject` we are getting is because there is an error in `decodePubsubMessage`.

### Has this worked before in a previous version?

Same from the beginning i think

## 🔬 Minimal Reproduction

Run the test case in debug mode and you will see why it sends a `validationReject`.

## 🔥 Error
No Error is displayed

**Anything else relevant (validator index / public key)?**

In develop, there is an error code that is send  back from `validateBeaconBlockPubSub` along with the libp2p error, we can use that to check if this fails for the right reason.

**Comment by terencechain** [comment]
It seems like a good first issue to improve unit test
