### ISSUE TITLE
beacon chain service with eth1(infura) stuck at "deposit contract"

### ISSUE THREAD

**Issue by liszechung** [prysmaticlabs/prysm#9842]
# 🐞 Bug Report

### Description

was running v2.0.0 without problems. but when upgraded to v2.0.2, beacon-chain stopped at 

"Nov 01 18:07:29 centos-s-2vcpu-4gb-nyc3-01 bash[1647]: time="2021-11-01 18:07:29" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node"

### Has this worked before in a previous version?
it worked in the prev

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
my command
./prysm.sh beacon-chain --http-web3provider=https://mainnet.infura.io/v3/<projectID> --p2p-max-peers 80
i am on centos, digitalocean 

i used systemctl to start service and journal to see logs
there is "started GETH" and "stopped GETH "
The beacon chain is killed by the system

Nov 01 18:24:30 centos-s-2vcpu-4gb-nyc3-01 bash[1764]: time="2021-11-01 18:24:30" level=warning msg="Running on Ethereum Consensus Mainnet" prefix=flags
Nov 01 18:24:30 centos-s-2vcpu-4gb-nyc3-01 bash[1764]: time="2021-11-01 18:24:30" level=info msg="Checking DB" database-path="/root/.eth2/beaconchaindata" prefix=node
Nov 01 18:24:30 centos-s-2vcpu-4gb-nyc3-01 bash[1764]: time="2021-11-01 18:24:30" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
Nov 01 18:31:01 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: prysm_beacon.service: Main process exited, code=killed, status=9/KILL
Nov 01 18:31:01 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: prysm_beacon.service: Failed with result 'signal'.
Nov 01 18:31:07 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: prysm_beacon.service: Service RestartSec=5s expired, scheduling restart.
Nov 01 18:31:07 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: prysm_beacon.service: Scheduled restart job, restart counter is at 1.
Nov 01 18:31:07 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: Stopped Geth.
Nov 01 18:31:07 centos-s-2vcpu-4gb-nyc3-01 systemd[1]: Started Geth.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
CentOS 8.3 x64 8GB RAM
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by prestonvanloon** [comment]
It seems like your process is running out of memory. Could you try again with debug logs on and upload those results please?

Add `--verbosity=debug` to your beacon chain process to add debug logging.
