### ISSUE TITLE
Determine Runtime Error States for Beacon Node

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#985]
Hi all,

This is an issue tracking progress on improving how our beacon node handles errors gracefully. This is along the same lines as #632. In particular, we want to go through our beacon node implementation and check that for each service, there will not be any particular error condition that would cause the system to fail or leave the system in an inconsistent state. For example, if we have an error happening within a goroutine of the blockchain service such as when a block is processed, we do not want the system to crash and do not want to overwhelm the user with error logs. Most logs, unless they are very unexpected failures, should be at debug level.

One of the most important items to consider with respect to this is how we handle errors at the gRPC stream/request layer. If a validator client receives an error, for example, typically it will just not proceed with its runtime or attempt to make the request again. Having a critical error such as a validator client getting an error when it was supposed to receive notification of its announcement should be fixed by the validator client reattempting immediately after to correct its course.

This is more of a discussion issue thread to identify places where this currently happens in Prysm and PRs related to fixing them should be referencing this PR. @nisdas expressed interest in identifying these gaps in the repo and a good place to start would be to go through each service and outline potential points of failure in this thread.

Anyone else can pick up PRs related towards fixing potential failure states we find and handling them gracefully.

**Comment by rauljordan** [comment]
@houjieth perhaps you could be interested in this given your experience in building production-level projects, happy to chat about this more over discord

**Comment by nisdas** [comment]
Blocked until #781 is resolved

**Comment by rauljordan** [comment]
This can be closed now that we have identified a lot of monitoring options for production
