### ISSUE TITLE
Unable to build on Ubuntu 21.10

### ISSUE THREAD

**Issue by felso** [prysmaticlabs/prysm#9850]
# 🐞 Bug Report

### Description

 I'm unable to build on Ubunut 21.10. 
### Has this worked before in a previous version?

 Probably not as it appears to be a problem on this version of Ubuntu.

## 🔬 Minimal Reproduction

Install Ubuntu 21.10 and prerequisites and try to build.

## 🔥 Error

<pre>
$ bazel build //beacon-chain:beacon-chain
INFO: Repository llvm_toolchain instantiated at:
  /home/john/go/src/github.com/prysmaticlabs/prysm/WORKSPACE:29:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /home/john/.cache/bazel/_bazel_john/fb201037fe3d8fe5c21826a2279f80a1/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/john/.cache/bazel/_bazel_john/fb201037fe3d8fe5c21826a2279f80a1/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
		_download_llvm_preconfigured(rctx)
	File "/home/john/.cache/bazel/_bazel_john/fb201037fe3d8fe5c21826a2279f80a1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
		fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/john/.cache/bazel/_bazel_john/fb201037fe3d8fe5c21826a2279f80a1/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
		_download_llvm_preconfigured(rctx)
	File "/home/john/.cache/bazel/_bazel_john/fb201037fe3d8fe5c21826a2279f80a1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
		fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
ERROR: no such package '@llvm_toolchain//': Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
INFO: Elapsed time: 0.183s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
<code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Latest development branch.
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by Saturnoul** [comment]
Change the version of llvm may work.
In WORKSPACE, set `llvm_version` to `10.0.1`, it will look like below after change
`llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "10.0.1",
)`

**Comment by guiomie** [comment]
This fixed my issue also, why would llvm_toolchain not be set at 10.0.1 by default in WORKSPACE ?

**Comment by prestonvanloon** [comment]
> This fixed my issue also, why would llvm_toolchain not be set at 10.0.1 by default in WORKSPACE ?

@guiomie pull requests are welcome!

**Comment by leolara** [comment]
@prestonvanloon preparing a PR, this issue also affects 22.04.

**Comment by rauljordan** [comment]
Tested today, we finally have an LLVM v10 for Ubuntu 18+! Closing

**Comment by leolara** [comment]
@rauljordan yes, the MacOs ARM PR was based in the PR referenced here, so this changed got included when that one was merged
