### ISSUE TITLE
Problem with memory consumption

### ISSUE THREAD

**Issue by amyboose** [prysmaticlabs/prysm#9869]
![image](https://user-images.githubusercontent.com/93859970/140638965-d2ed3dac-43bc-4a29-a03b-e84eb3d3e4c0.png)
![image](https://user-images.githubusercontent.com/93859970/140639014-10a9ee4f-99b8-4295-ba8a-7f5f73da376d.png)
12 GB memory consumption with flag --slasher. And infinitely growing memory consumption without flag --slaher.
Please add memory dispose function to windows 
May be ask some programmers from Geth how they dispose memory

**Comment by prestonvanloon** [comment]
We're aware of memory issues with `--slasher`, but a memory leak in Prysm with default parameters is a new issue.

Could you please add more details? What version of prysm? What OS? What flags are you using?

**Comment by amyboose** [comment]
![image](https://user-images.githubusercontent.com/93859970/140656160-ca7e48ff-d1af-4244-a7d1-54a9b23eae09.png)

Flags: prysm.bat beacon-chain --p2p-max-peers=100 --enable-next-slot-state-cache --http-web3provider=http://127.0.0.1:8545 --datadir="D:\Ethereum\Eth2 beacon chain"

OS: windows 10

Prysm version: 2.0.2

About every 5 days I reload prysm to dispose a memory. It starts with about 2 GB in Grafana grapth and increasing every day. You can see 5 GB used memory in screenshot and 3 GB in Task Manager. I don't know why these numbers differ. But I know that both numbers will increase every day.

**Comment by prestonvanloon** [comment]
Thanks for that additional context. Could you add this flag `--pprof` to your beacon node? This is going to enable debug profiling. After a few days when you see a high memory usage, could you then download the file located at http://localhost:6060/debug/pprof/allocs. Please upload that `allocs` file and attach to this issue. 

The allocs file shows us where all the memory is allocated. It does not contain any sensitive information or memory values.

**Comment by amyboose** [comment]
Ok, will do it

**Comment by amyboose** [comment]
I've tried open http://localhost:6060/debug/pprof/allocs. But there is just infinitely loading page without any downloading file. How can I fix that?

**Comment by prestonvanloon** [comment]
`curl http://localhost:6060/debug/pprof/allocs > /tmp/allocs.pprof`

It may take some time if the allocs are very large.
