### ISSUE TITLE
Slashing protection export gives wrong warn-message

### ISSUE THREAD

**Issue by handelaar2** [prysmaticlabs/prysm#9905]
# 🐞 Bug Report

### Description
When I export the slashing protection of the Prater testnet, the command does not accept a "--prater" parameter. When I run the exporter command, it gives the warning: 
 `WARN flags: Running on Ethereum Consensus Mainnet`
This is not true, as I was exporting for Prater

### Has this worked before in a previous version?
N/A

## 🔬 Minimal Reproduction
Run:
`/usr/bin/validator slashing-protection export --datadir=/pathto/prater/validator --slashing-protection-export-dir=/pathto/validator`

## 🔥 Error
The issued warning is incorrect and therefore confusing. Slashing protection activities require absolute clarity. 

**What version of Prysm are you running? (Which release)**
2.0.2

**Anything else relevant (validator index / public key)?**
![2021-11-15_18-50-48](https://user-images.githubusercontent.com/28559038/141830381-86ca7f82-6e57-474d-bd3c-076356e366e1.png)

**Comment by rauljordan** [comment]
Thanks @handelaar2 , fixing this ASAP! I confirmed it will not affect functionality, and is just a cosmetic issue, but important to clarify that

**Comment by handelaar2** [comment]
If you ask me, it is not correct yet. So if I don't explicitly enter `--prater`, it assumes `--mainnet` and issues the same warning as before. The validator-db continues to be for the prater-network and the export is successful. The "export command" should raise an error if the network parameter does not match the validator-db. There should be a check.
