### ISSUE TITLE
Make API timeout configurable

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#9917]
# 🚀 Feature Request

### Description

It is currently not possible to specify an HTTP timeout for API requests. The value is hard-coded at 2 minutes here: https://github.com/prysmaticlabs/prysm/blob/a78cdf86cc4e614ced18aa7af32c89b4372657c7/api/gateway/apimiddleware/process_request.go#L80
This is problematic because some queries might take longer, especially those which access past states.

### Describe the solution you'd like

Add a CMD `--api-timeout` flag that accepts the desired timeout value in minutes. It should default to `2`.

**Comment by rauljordan** [comment]
Good first issue!

**Comment by prycey77** [comment]
Can I pick this up?

**Comment by rkapka** [comment]
> Can I pick this up?

Absolutely! I assigned you to the issue.
