### ISSUE TITLE
Re-propagation of seen aggregated attestations dramatically increases bandwidth 

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#9935]
The re-propagation of seen aggregated attestations `attestion_aggregate_proof` was enabled in the consensus networking spec in Altair (See: [rationale](https://github.com/ethereum/consensus-specs/issues/2183) and [pr](https://github.com/ethereum/consensus-specs/pull/2225))

Prysm implemented it in [9830](https://github.com/prysmaticlabs/prysm/pull/9830) and included it in the release [v2.0.3](https://github.com/prysmaticlabs/prysm/releases/tag/v2.0.3). Post release, we received multiple reports the outbound traffic **quadrupled** in certain situations for nodes then we root caused down to to the large increases in `attestion_aggregate_proof` re-propagation

Worth noting that Prysm may be the only client with re-propagation enabled, some other clients implementations are still in PR mode: [lighthouse's pr](https://github.com/sigp/lighthouse/pull/2750)

Opening this PR to document further findings, resolutions... etc

**Comment by prestonvanloon** [comment]
I observed a 100% (x2) increase in outbound network traffic on a small serving beacon-chain/validator client. 
I did not observe quadruple increase. Testnets also did not reflect significant increase in outbound traffic, at least from the data we recorded. I'd like to verify that our testnet data sampling is accurately capturing p2p traffic, but I have no reason to believe it is not at this time.

**Comment by mohamedmansour** [comment]
I observed 2x CPU usage as well, is this related?
![image](https://user-images.githubusercontent.com/68524/143325544-1991c0a8-dd88-4645-bd9c-a50e03b709d8.png)

Network is 2x as well:
![image](https://user-images.githubusercontent.com/68524/143325634-b0260ca3-3f84-4f3b-85ed-212bd60dc796.png)

**Comment by prestonvanloon** [comment]
>  is this related?

Very likely. 

v2.0.4 release candidate is 1d53fd2fd32f652dbf0c8b4d50ee49f03805c5d8. 
If you are up to it, please run from that commit. We are still testing / evaluating it with prod serving validators at this time, but believe CPU use is lower with the changes at 1d53fd2fd32f652dbf0c8b4d50ee49f03805c5d8.

**Comment by mohamedmansour** [comment]
@prestonvanloon  okay that fixed the cpu and network (on mainnet):
![image](https://user-images.githubusercontent.com/68524/143330279-d8fc4899-a82b-48fa-b344-5ab7710c73da.png)
![image](https://user-images.githubusercontent.com/68524/143330255-a26fb5a4-cd99-4989-8634-40098c54ee24.png)

**Comment by prestonvanloon** [comment]
This is resolved in v2.0.4
