### ISSUE TITLE
future sync committee membership API returns invalid state id error

### ISSUE THREAD

**Issue by kevinwucodes** [prysmaticlabs/prysm#9940]
# 🐞 Bug Report

### Description

When trying to obtain the next membership set of sync committees, Prysm is unable to provide that membership.  Teku, however, is able to provide the next sync committee membership.  I'm not sure if Prysm or Teku is out of spec.

### Has this worked before in a previous version?

No, obtaining future sync committee membership does not seem to have ever worked in Prysm.

## 🔬 Minimal Reproduction

Let's suppose the current epoch is 80621.  The next sync committee epoch would be 80621 + 256 = 80877.

```
curl 'http://192.168.0.1:3500/eth/v1/beacon/states/finalized/sync_committees?epoch=80877'
```

When calling this, I get the Prysm error below:

## 🔥 Error

```
{"message":"Could not fetch beacon state using request: rpc error: code = Internal desc = Invalid state ID: slot cannot be in the future","code":500}
```

**This error does not occur when using Teku.  Teku returns the next sync committees membership.**

## 🌍  Your Environment

**Operating System:**

- Ubuntu Server 20.04.3 LTS (Focal Fossa)

**What version of Prysm are you running? (Which release)**

- v2.0.3
  
**Anything else relevant (validator index / public key)?**

- None.

**Comment by mrabino1** [comment]
related .. 

021-11-24 18:28:40,840 Incremented Retry for (url='/eth/v1/beacon/states/2458798/validator_balances'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
2021-11-24 18:28:40,841 Retry: /eth/v1/beacon/states/2458798/validator_balances

Exception: Error while fetching data from beacon node: {"message":"could not proxy request: Get "http://127.0.0.1:3500/internal/eth/v1/beacon/states/MjQwODM5OA==/validator_balances/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","code":500}

**Comment by potuz** [comment]
> related ..
> 
> 021-11-24 18:28:40,840 Incremented Retry for (url='/eth/v1/beacon/states/2458798/validator_balances'): Retry(total=4, connect=None, read=None, redirect=None, status=None) 2021-11-24 18:28:40,841 Retry: /eth/v1/beacon/states/2458798/validator_balances
> 
> Exception: Error while fetching data from ...
This is not related to the issue. If it's happening consistently perhaps you should open a different one
