### ISSUE TITLE
2.0.3 introduces a breaking change in gRPC API

### ISSUE THREAD

**Issue by lukaszsamson** [prysmaticlabs/prysm#9942]
# 🐞 Bug Report

### Description

 Unable to authorize to gRPC API after upgrade to to 2.0.3

### Has this worked before in a previous version?

 Yes

## 🔥 Error

<pre><code>
unknown method Login for service ethereum.validator.accounts.v2.Auth

</code></pre>

**Comment by alexpeterson91** [comment]
The port is changed to 3500, the RPC gateway port instead of the previous RPC at port 4000. This fixed my issues running an SSV validator

**Comment by rkapka** [comment]
cc @rauljordan and @james-prysm

**Comment by prestonvanloon** [comment]
Please review the changes in https://github.com/prysmaticlabs/prysm/pull/9740. There was refactoring of web UI authentication. 

Can you explain the use case for this RPC method?

**Comment by lukaszsamson** [comment]
@prestonvanloon The use case is remote monitoring and management of prysm nodes via gRPC API as documented here (https://docs.prylabs.network/docs/how-prysm-works/prysm-public-api) and (https://docs.prylabs.network/docs/how-prysm-works/ethereum-public-api/). We are calling `Ethereum.Validator.Accounts.V2.Auth.Login` to get a token from `Ethereum.Validator.Accounts.V2.AuthResponse`. Then we use that token to authorize other gRPC calls, e.g. `Ethereum.Validator.Accounts.V2.Beacon.GetValidatorBalances`. The authorization relied on `Authorization: Bearer {TOKEN}` header. This worked in versions 1.3-2.0.2. My expectation is that it should still work as there were no mentions of gRPC changes nor deprecations in the release notes for versions 2.0.0, 2.0.1, 2.0.2 and 2.0.3.
I understand that authorization part is not well documented and standarized but a breaking change like this should not be introduced in a patch version. It should happen on a major version or at least on a minor with first deprecating the old API and documenting it in the release notes.

**Comment by rauljordan** [comment]
Hi @lukaszsamson thank you for reporting this. We really apologize for this breaking change, as we did not anticipate this use-case. Looks like you are calling the: `Ethereum.Validator.Accounts.V2` namespace, which is only used by the [Prysm Web Interface](https://docs.prylabs.network/docs/prysm-usage/web-interface) for performing web authenticated requests using a bearer auth token. Most users will never need to use this API namespace.

Instead, we highly recommend you should use the **beacon node** API to accomplish your goal. You can find these APIs under [here](https://github.com/prysmaticlabs/prysm/blob/develop/proto/prysm/v1alpha1/beacon_chain.proto) and they have namespace `Ethereum.Eth.v1alpha1`. Looks like you are currently hitting your **validator client**'s grpc port, which I believe is localhost:3500 by default. Instead, the recommended APIs live in the **beacon node** which serves grpc at localhost:4000 by default. You'll find methods in there to retrieve validator balances and all kinds of other use-cases for your needs.

For remote monitoring and management, you should not be using our validator web UI authorization scheme, but instead relying on practices such as TLS certificates and/or whitelisting IPs for remote access. We are happy to further support you on our [Discord](https://discord.gg/prysmaticlabs) if you have further questions. You can feel free to DM me in our Discord server.

**Comment by prestonvanloon** [comment]
Thanks for the feedback @lukaszsamson. I will see that our future release notes have a separate section for gRPC / API changes to highlight potential breaking changes. 

As Raul mentioned, we weren't aware of downstream users of this API (other than web UI users) which contributed to the lack of notification of these breaking changes.

**Comment by terencechain** [comment]
Closing as there's no more further investigation into this. Future release notes will be improved from now on
