### ISSUE TITLE
[Performance] 2.0.3. Validator unstable for about a week

### ISSUE THREAD

**Issue by SebastianMetzger** [prysmaticlabs/prysm#9947]
# 🐞 Bug Report

### Description

Since last week I recognized my validator missed a couple of attestations.

This was also visible in the monitoring
![image](https://user-images.githubusercontent.com/2345498/143857452-1da09758-4a96-48d9-8b4a-47e067958df8.png)
![image](https://user-images.githubusercontent.com/2345498/143857790-9902a41c-8ac9-45af-984a-7007d898a200.png)

### Has this worked before in a previous version?
Before it worked more stable
Probably also related to a not so strong Digital Ocean instance I use for my validator
![image](https://user-images.githubusercontent.com/2345498/143857960-bbab2556-fe91-45ec-9478-9881436987b6.png)

Just upgraded to a stronger instance (4cpu, 8gb ram) and I believe it will fix the issue, but just FYI, maybe it is a sign of a deeper problem?

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
     Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
      2.0.3
  </code>
</pre>

**Comment by nisdas** [comment]
Hey @SebastianMetzger ,

This is related to this issue: https://github.com/prysmaticlabs/prysm/issues/9935 . We will be having a new release very soon for this(most likely today). We already have a release candidate being tested https://github.com/prysmaticlabs/prysm/issues/9935#issuecomment-978480929 . You can revert back to v2.0.2 for the timebeing to alleivate the performance issues you have seen.

**Comment by potuz** [comment]
can we close this issue as duplicate?

**Comment by SebastianMetzger** [comment]
From my side would be fine

**Comment by nisdas** [comment]
Closing this issue then, this can be tracked in #9935.
