### ISSUE TITLE
Remove Unnecessary Use of Integer Types in Prysm

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9958]
# 💎 Issue

### Background

Thank you @uncdr for bringing this to our attention. As Prysm is becoming a more complex project, we should place a lot of care into how we use primitive types. The danger of using integer types where they are not needed is problematic, as there could be future changes to the codebase that lead to bugs. Artem from our team has mentioned we should only use integers as a type when we really need signed numbers. Otherwise, everything should be unsigned and enforced by the compiler.

### Description

This is a tracking issue to refactor all uses of integer types in Prysm into uints (either uint, uint16, 32, or 64) and audit them carefully. Ideally, this should be enforced by a static analyzer or some Github action script which checks for uses of integers, casting of values into integer types, and more. Wherever we need integers, which is rare, we should add exceptions, which can be done via comment pragmas, such as `//ignore:int` which can be parsed by the analyzer.

In the meantime, there a few low-hanging fruit we can take of, such as refactoring all uses of `cliCtx.IntFlag` into `clicCtx.Uint64Flag` for flag definitions of uint values.

### TODOs
- [ ] Create some kind of static analyzer or Github action which checks for uses of the `int` type in Prysm, running as part of every pull request
- [ ] Refactor unnecessary uses of `int` into `uint` with the respective size, typically `uint64`

**Comment by hansmrtn** [comment]
I'd like to work on this
