### ISSUE TITLE
Add More Information via Logs When "Checking DB" On Startup

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9970]
# 💎 Issue

### Background

Prysm currently takes ages to start for some users after they have shut down their service for a while due to some database book-keeping. From a user's perspective running Prysm with normal settings, they would see something like:

```
[2021-12-01 22:18:03] INFO: Checking DB...
```
and nothing for minutes or even half an hour as we've heard in reports. We should add regular info logs to this to explain what is going on underneath the hood or even suggest adding a progress bar if the situation warrants it. @nisdas can probably add more color as to what is happening underneath the hood and how we can add more info about it.

**Comment by rauljordan** [comment]
This is a scary situation because many users freak out thinking their system is stuck

**Comment by potuz** [comment]
This happened to myself after a loss of power and this in part led me to buy an ups. I was about to pull a snapshot when out of nowhere the db healed

**Comment by james-prysm** [comment]
Might look into this one
