### ISSUE TITLE
Allow Triggering of Beacon DB + Validator DB Backups via API (for Web UI)

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9971]
# 🚀 Feature Request

### Description

Currently, Prysm supports triggering database backups via an HTTP webhook documented [here](https://docs.prylabs.network/docs/prysm-usage/database-backups).  The way it works is as follows:

The user has to add the following flags to their beacon node and/or validator:

- `--enable-db-backup-webhook`: Serve an http server to initiate database backups. The handler is served on the beacon node's monitoring host and port. Default endpoint is `http://127.0.0.1:8080/db/backup` if the flag is enabled.
- `--db-backup-output-dir`: Folder path to where backups will be output to, such as `/path/to/mybackups`. If the directory exists, make sure the permissions for that directory is `0700`.

The beacon node will expose an HTTP endpoint `http://monitoringhost:monitoringport/db/backup`, which is `http://127.0.0.1:8080/db/backup` by default. Then, the user can hit this endpoint via HTTP, and a backup will initiate which will be output to the `--db-backup-output-dir` path.

### Describe the solution you'd like

As Prysm's validator also supports a [web interface](https://docs.prylabs.network/docs/prysm-usage/web-interface), we should be able to trigger these backups from the web UI, and ideally give feedback to the user that a backup has been trigger and that the backup has completed. To do this, we would need the following components:

Create the following gRPC API endpoints to trigger a backup
- In the validator client: add `TriggerValidatorDBBackup` and `TriggerBeaconDBBackup` endpoints to trigger the actual backup process. Also, we might want a `ValidatorDBBackupHistory` and a `BeaconDBBackupHistory` which can check all triggered backups and their status (whether or not they have completed)
- Add the ability to check for status of backups. Today, the backup webhook doesn't return anything to the user aside from a status 200 if the trigger was successful. We might want to also return a backup ID, which can be used to check if the backup has completed later (useful for displaying to a user). We also want a way to read a history of triggered backups and their status.

**Comment by jamesthesken** [comment]
Is this issue still up for grabs? I was hoping to dig into the Web UI!

**Comment by rkapka** [comment]
> Is this issue still up for grabs? I was hoping to dig into the Web UI!

@rauljordan What is the state of backups?

**Comment by nisdas** [comment]
We should discourage live beacon backups for this reason:
https://github.com/prysmaticlabs/documentation/pull/392

**Comment by rauljordan** [comment]
After thinking about this for some time, I agree this is a huge risk and should be something that is triggered by the operator. The webhook offers a good compromise of security and ease of use, but has dangers if exposed to everyone via the public API
