### ISSUE TITLE
Missing spec tests in sss_static.go

### ISSUE THREAD

**Issue by asanso** [prysmaticlabs/prysm#9990]
The [`ssz_static.go`](https://github.com/prysmaticlabs/prysm/blob/develop/testing/spectest/shared/phase0/ssz_static/ssz_static.go#L31) is skipping several test types.
Indeed it hardcodes `ssz_random` while many other test types are present e.g. : `ssz_one`, `ssz_nil` , etc as in https://github.com/ethereum/consensus-spec-tests/tree/master/tests/minimal/altair/ssz_static/AggregateAndProof

**Comment by terencechain** [comment]
Closing thanks to #10003
